### ISSUE TITLE
Remove: ZAP over TOR Support

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#1001]
With the upgrade to LND 0.9.0 - somhow the connection over TOR is not working anymore in iOS- see: https://github.com/LN-Zap/zap-iOS/issues/333

For a manual try follow: https://github.com/openoms/bitcoin-tutorials/blob/master/Zap_to_RaspiBlitz_through_Tor.md

**Comment by theotherside** [comment]
I just followed the commands suggested in the above link. In the latest Zap from ios app store on 20200125 and I got the same exact error shown in https://github.com/LN-Zap/zap-iOS/issues/333

**Comment by rootzoll** [comment]
Moving to v1.5 release.

**Comment by lordgivemestrength** [comment]
Would this issue be the reason the QR code does not come up when trying to generate it to scan in Zap?

I have been playing with this for days, to no avail.
Everything else seems to work OK, but I get no joy when trying to connect any wallet - no QR code is displayed on either the PI or laptop.

Similarly, would disabling TOR help?

**Comment by rootzoll** [comment]
@lordgivemestrength if no QR code shows up on trying to connect any of the wallets this #1001 seems not to be your issue. Can you open a new issue and try to give more detail on your problem?

**Comment by rootzoll** [comment]
Doing some tests and writing down the results. So with LND 0.9.2 connecting with:
 
- iOS (appstore) IP based --> works

iOS (appstore) over TOR --> gives this error:
![IMG_0002](https://user-images.githubusercontent.com/2472225/77188419-35964a00-6a93-11ea-8c21-d28fd7df9122.PNG)

iOS (testflight mainnet) over TOR --> gives this error:
![IMG_0003](https://user-images.githubusercontent.com/2472225/77188463-46df5680-6a93-11ea-8247-c508a42f80bf.PNG)

**Comment by rootzoll** [comment]
pusching the error to v1.6

**Comment by Astro92** [comment]
Can confirm I receive the same error (could not connect to server. (unknown error 1)) on 1.5

**Comment by mandreko** [comment]
I see this error as well :(

**Comment by CoderBoogs** [comment]
I also see this error. Has anyone tried any of the other mobile apps? Does fully noded work well?

**Comment by rootzoll** [comment]
There is no movement on the ZAP repo on this issue, so I will remove the TOR option again for now with v1.6 release. As an alternative way v1.6 will have IP2TOR bridge subscription services ... so you can run your node behind TOR but rent a public IP+Port that can ce used to connect apps like Zap. See #1194

**Comment by rootzoll** [comment]
Switched ZAP over TOR for Android back on based on request:
https://github.com/rootzoll/raspiblitz/issues/1308

**Comment by openoms** [comment]
The issue looks to be fixed soon on the side of Zap as well: https://github.com/LN-Zap/zap-iOS/pull/342
Will need testing once appears in the App store

**Comment by mandreko** [comment]
Will we need to update Raspiblitz to test once the new version of Zap appears in the Apple store?

**Comment by openoms** [comment]
Appears to work, try for yourself:
![image](https://user-images.githubusercontent.com/43343391/86668991-15ab7780-bfeb-11ea-85d2-57571b26bee0.png)

**Comment by rootzoll** [comment]
I readded the option to connect Zap iOS over Tor to the Raspiblitz fpr v1.6: https://github.com/rootzoll/raspiblitz/issues/1308

**Comment by woeisme** [comment]
Someone should update [this page](https://github.com/openoms/bitcoin-tutorials/blob/master/Zap_to_RaspiBlitz_through_Tor.md) to show it working again

**Comment by openoms** [comment]
> Someone should update [this page](https://github.com/openoms/bitcoin-tutorials/blob/master/Zap_to_RaspiBlitz_through_Tor.md) to show it working again

done
