### ISSUE TITLE
Locale / Localization

### ISSUE THREAD

**Issue by jagottsicher** [raspiblitz/raspiblitz#101]
Login via putty and setting translation to UTF8 leads to letters in the menu, but correct up/down characters on the info screen, while login with iso8859-1 leads to a nice menu border, but cryptic utf-characters like " â¼"

**Comment by rootzoll** [comment]
thanks for the report. If anybody has a quick idea to fix this I am happe to merge. But I would not put high priority on this fix, because for the future the goal would be to change from SSH/Dialogs to Webbrowser/Dialogs.
