### ISSUE TITLE
HTTPS Proxy & LetsEncrypt

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#1027]
Extra App like BTCPayServer and LNBits (for a working LNURL extension) need a HTTPS with an letsencrypt cert that either works with SSH-Reverse Tunnel or dynDNS&PortForwarding. For this it makes sense to have a HTTPS proxy server (nginx) with letsencrypt that other services can share in the future.

**Comment by rootzoll** [comment]
Because this is a bigger task .. moving to v1.6 so that v1.5 is not delayed

**Comment by frennkie** [comment]
As #255 already suggests using `nginx` is a very good solution.

We should focus *this* issue on the "getting a certificate" part. 

Let's Encrypt has (at least) two different ways to get cert https://letsencrypt.org/docs/challenge-types/

* `HTTP-01` (requires inbound Port 80 connectivity)
* `DNS-01` (requires control over a DNS (sub) domain with possibility to set `TXT` records)

Especially `DNS-01` looks very promising! :-D

**Comment by rootzoll** [comment]
@frennkie do you want to push the Lets Encrypt Part to v1.7

**Comment by frennkie** [comment]
I would like to include the script to install (and restore) the client in v1.6 if possible. This would include the entry in 'Services'.

But everything else still needs a lot of documentation and deciding on use cases that make sense.

**Comment by frennkie** [comment]
I merged the `acme.sh` installation which also includes an update for the FAQ. While this gives (advanced) users the option to get LE certificates there is no integration with e.g. Nginx yet.

Regarding the Apps I have already merged the Nginx integration for `LNbits` and for `RTL`. But the other Apps that host web services are still open. I think having dedicated issues for each would be the best way to track it.

Keeping this issue open for a integration between the LE certificates and Nginx.

**Comment by rootzoll** [comment]
Is there anything that needs to be recovered on a update?

**Comment by frennkie** [comment]
The recovery should check `/mnt/hdd/raspiblitz.conf` for `letsencrypt` and if it is **enabled** it should run `config.scripts/bonus.letsencrypt.sh on`.

The certificates and the configuration info for renewals is stored on the external disk (`app-data`).

**Comment by frennkie** [comment]
@rootzoll I noticed that the `Let's Encrypt` client is now in the `Node Settings & Options` menu. I first looked in the `Additional Services`. 

Selecting the entry triggers the installation - but not more. What is our plan forward? 
Suggestion: Installing the client adds a new entry in the main menu where actions (list, get, configure) can selected.

In that case I would still find it more intuitive to place the client installation in `Additional Services`.

**Comment by rootzoll** [comment]
Actions like (list, get, configure) are basically what we introduced with Subscriptions. We could even remove "lets encrypt" from the "Settings" and install it on the first subsbription and delete it after the canceling the last "lets encrypt subscription".

So when a user goes into SUBSCRIBE there will be a an additional "NEW2" option called something like "Lets Encypt HTTPS" and then (like choosing a IP2TOR Bridge Host) we can offer a fixed list (no need to conact a outside API here) of DNS-Services that we offer to use like "DuckDNS" or "FreeDNS".

It makes sense to have this as a subscription (even it costs nothing) there is a renewable process of the LetsEncrypt cert in the background.

**Comment by rootzoll** [comment]
Looks good on testing. Will be part of v1.6. Closing issue.
