### ISSUE TITLE
In lnd.rescue.sh scp invocation, tell user to escape * with backspace or do it for user

### ISSUE THREAD

**Issue by guilsa** [raspiblitz/raspiblitz#1029]
In here [1], add information to user that they might need to to escape wildcard with a backslash `\`.

Error:

```
➜  ~ scp -r admin@my_rapi_pi:/home/admin/lnd-rescue-*.tar.gz ./
zsh: no matches found: admin@my_rapi_pi:/home/admin/lnd-rescue-*.tar.gz
```

No error (with backslash before asterisk):

```
➜  ~ scp -r admin@my_rapi_pi:/home/admin/lnd-rescue-\*.tar.gz ./
```

[1] https://github.com/rootzoll/raspiblitz/blob/480a67729081cdd81357f508c0174b9ce05fa38e/home.admin/config.scripts/lnd.rescue.sh#L62

**Comment by rootzoll** [comment]
Hi @guilsa thx for the report. While doing dev in v1.4 MacOS did the change to zsh and I was see the error also. Got that fixed for upcomming v1.4 by putting the parameter value into quotes. So consider this issue solved for the v1.4 release.
