### ISSUE TITLE
RaPi4 with official 7" touch screen incompatible

### ISSUE THREAD

**Issue by SteakDestroyer** [raspiblitz/raspiblitz#1032]
It seems when using RaPi4 with a 7" touch screen, on boot the screen will hang at "Load/Save RF Kill Switch Status."
The Pi continues to function properly but the LCD will not update.

**Comment by openoms** [comment]
Did you try this? https://github.com/rootzoll/raspiblitz/issues/767
Available in the 1.4RC3 image: https://github.com/rootzoll/raspiblitz/blob/v1.4/README.md#installing-the-software

**Comment by orweinberger** [comment]
@SteakDestroyer Although I was seeing a different message when my setup hanged, I suggest you try SSHing and executing `sudo ./LCD-Show/LCD7B-show`. That worked for my 7" official setup.

**Comment by SteakDestroyer** [comment]
@orweinberger #  Thankyou for the info. I just finished syncing the blockchain and am ready to try this out,  however I'm very inexperienced with Linux and terminal. 
I have tried your suggested command, with a response of
"command not found"

**Comment by SteakDestroyer** [comment]
@orweinberger Never mind, Just figured it out. :)
Thankyou again for the hot tip!
