### ISSUE TITLE
Disable screen dependence on initial install

### ISSUE THREAD

**Issue by arcbtc** [raspiblitz/raspiblitz#1036]
For folks like me, who want to run the blitz without the screen, it would be nice to remove its dependence on the initial image boot. I currently have to plug in the screen, then unplug once everything is installed.

**Comment by rootzoll** [comment]
Please check if this feature coming with the v1.4 meets your requirements:
https://github.com/rootzoll/raspiblitz/issues/767#issuecomment-578323849

**Comment by nyxnor** [comment]
Screen is now optional on the build_sdcard.sh,
pls close this.
