### ISSUE TITLE
Faster sync by connecting to a desktop computer

### ISSUE THREAD

**Issue by meronym** [raspiblitz/raspiblitz#1037]
My Raspiblitz was offline for several months and I just got it back online. Judging by the last 24h progress, it will take weeks to get it fully synced again. Is there any way to speed up the process?

I was thinking about connecting the Raspiblitz HDD to my (linux) desktop and run `bitcoind` and `lnd` there, what should I keep in mind for this setup to work properly?

**Comment by rootzoll** [comment]
Basically I would recommend upgrading to a RaspberryPi4-2GB - that will catch up some months within hours. 

On RaspberryPi3 for speed up with your laptop you could: Install a Bitcoin Core on your laptop (same version as on Blitz) - sync and validate the complete Blockchain on laptop (might take 1-2 days). Then ssh into RaspiBlitz (should at least be Version 1.3) and CTRL+C to terminal. Run 'repair' command and delete/reset (JUST) the Blockchain Data and then choose the option to COPY the blockchain from your laptop to the Blitz over the local LAN (takes around 4 hours).

The above is based on tested routines. You could also try to install Bitcoin Core in laptop and try to sync it with the HDD connected .. but not sure if this will mess up some file permissions, I never tried.
