### ISSUE TITLE
RESEARCH: Run ION on RaspiBlitz

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#1038]
Microsoft is building an open identity system as 2nd layer on Bitcoin. Even they recommend 6GB memory ist would be interesting if you can get it running on a RaspiBitz RP4-4GBRAM-1TBSSD.

"ION is a public, permissionless, Decentralized Identifier (DID) network that implements the blockchain-agnostic Sidetree protocol on top of Bitcoin (as a 'Layer 2' overlay) to support DIDs/DPKI (Decentralized Public Key Infrastructure) at scale."

https://github.com/decentralized-identity/ion/blob/master/install-guide.md

**Comment by nyxnor** [comment]
[This is a duplicate too](https://github.com/rootzoll/raspiblitz/issues/1818) (triplicate)
Close this, the other has more information.
