### ISSUE TITLE
Touchscreen displays incorrect version.

### ISSUE THREAD

**Issue by hermanlim** [raspiblitz/raspiblitz#1039]
Running updated 1.3->1.4

Touchscreen displays Raspiblitz v1.3 - bitcoin - mainnet 
instead of
Raspiblitz v1.4 - bitcoin - mainnet

**Comment by rootzoll** [comment]
Thanks .. should now be fixed for final v.14-2020-02-19 release.

**Comment by hermanlim** [comment]
Just out of curiosity, which file needed changing? I looked through the source but couldn’t find the relevant file to fix it myself. 

Herman

Please excuse the brevity and any typos as this message has been composed on a mobile device.

**Comment by rootzoll** [comment]
Take a look at your `/mnt/hdd/raspiblitz.conf` there you can update version to v1.4 .. the final v1.4 release will now automatically update that version string. My testing of updating a v1.3 to v1.4 with touchscreen showing 1.4 was sucessfull. Closing issue.
