### ISSUE TITLE
CONNECT in menu useless

### ISSUE THREAD

**Issue by jagottsicher** [raspiblitz/raspiblitz#104]
As long you cant copy+paste with putty/ssh the connect input field is pretty useless unless you can correctly type lots of hex-digits.

Of course you can use the shell and the lightning cli, but what's CONNECT in the menu then good for?

**Comment by rootzoll** [comment]
On osx terminal its possible to copy/paste peer addresses into the dialog. So it makes sense here. But sure, if copy/paste is not working, this makes not sense. The plan for the future is to change from SSH-UI to Webbrowser-UI .. to copy/paste should be much easier there. So I will not put to much effort into perfecting SSH-UI Dialogs at the moment. The goal was to present a simple UI showing/demonstration basic first ligthning steps.
