### ISSUE TITLE
Display rotated and swapped axis touch on update from 1.3 to 1.4

### ISSUE THREAD

**Issue by odudex** [raspiblitz/raspiblitz#1047]
Not an hard issue but this can help who faced same problems.
For flipped display I solved by checking "LCD rotate" on services, rebooted, than unchecked it, rebooted again than it was solved.
Than touch(with XPT2046 controller) has swapped axis. I tried calibration, but it gave me: error='not installed'. So instead of messing with drivers I solved by manually editing /boot/config.txt and adding "swapxy=1" to last line:
dtoverlay=tft35a:rotate=270, swapxy=1

**Comment by nyxnor** [comment]
Pls close this.
