### ISSUE TITLE
RECEIVE does crash into permission problem

### ISSUE THREAD

**Issue by jagottsicher** [raspiblitz/raspiblitz#105]
When trying to creatin an invoive I get:

```
******************************
Create Invoice / Payment Request
******************************

COMMAND LINE:
lncli --chain=bitcoin addinvoice 100000

RESULT:
./BBcreateInvoice.sh: line 63: ./.error.out: Permission denied
******************************
WIN
******************************


Give this Invoice/PaymentRequest to someone to pay it:



You can use 'lncli --chain=bitcoin lookupinvoice ' to check the payment.

Press ENTER to return to main menu.

```

I think It was an awesome feature if a QR-Code was shown!

**Comment by rootzoll** [comment]
Thanks for the report. Will check if QR code display in terminal is a low hanging fruit :)

**Comment by rootzoll** [comment]
added chmod for error.out - needs testing.

**Comment by geco91** [comment]
@rootzoll test worked. recommend ticket for closing.

**Comment by rootzoll** [comment]
On the last hackday we intergrated the RTL web interface to manage your node and make fundings and payments. See progress on this ticket: https://github.com/rootzoll/raspiblitz/issues/134

In the long term this should replace the shell scripts .. creating invoices is not there yet, but when QR codes will surely be a part of it ... as they are already when funding chain wallet over RTL.

So basic bug is fixed and QR codes will then come with RTL - will close ticket for now.

**Comment by saubyk** [comment]
@rootzoll you can create invoices now with RTL. We can add QR code for the invoices in the next build.
