### ISSUE TITLE
Autofix "Give root password for maintenance"

### ISSUE THREAD

**Issue by ostermayer** [raspiblitz/raspiblitz#1053]
Updated 1.4 then install electrs from menu --> after restart ssh doesn't work due to operation timeout.  let sit for a few hours but no ability to ssh 

Also could not ssh after upgrade from 1.3 (with electrs installed )-> 1.4.  needed to do a full fresh install and restore in order to get 1.4 to work.  

no shimfan, running pi4 headless on ethernet

**Comment by rootzoll** [comment]
Do you found any other cooling options for your raspiblitz? I had ssh login problems on a Raspi that was overheating and got instable. Is it now (after 1.4 fresh install) running without problems?

**Comment by ostermayer** [comment]
it runs on a 40c temp or less sitting in a always cool spot

**Comment by ostermayer** [comment]
![72ED9858-58DD-48E2-ACBD-E67561F2AF3E](https://user-images.githubusercontent.com/4887941/76247119-09660800-620d-11ea-8254-fa07442ecd47.jpeg)

**Comment by ostermayer** [comment]
this was the cause and is only fixed by attaching a keyboard and then ssh worked afterwards

**Comment by rootzoll** [comment]
For the v1.5 RC1 release trying to add a forced fsck for such cases - like described here:
https://github.com/krishraghuram/mess/issues/31#issuecomment-370811935

Hopefully this will fix this "Give root password for maintenance" issue.

**Comment by joernroeder** [comment]
quick note: I just ran into this with a after updating to v1.6

**Comment by ostermayer** [comment]
yes as did I

**Comment by rootzoll** [comment]
Yepp .. this was sadly not fixing this. If you run into it you need to make a fresh sd card and let the RaspiBlitz recover.

Our next hope to fix this is to run OS from SSD and not SD card in the a future release - that option may come with v1.7 or v1.8 https://github.com/rootzoll/raspiblitz/issues/1235
