### ISSUE TITLE
RESEARCH: Add ZFS/ZOL Support

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#1066]
Now that with experimantal BTFS support the blitz.datadrive.sh script has an abstraction for supporting different file systems, we can also look into supporting further alternatves like https://github.com/openzfs/zfs

Please comment if you are interested and we can exchange details.

**Comment by nyxnor** [comment]
Mentioned here https://github.com/rootzoll/raspiblitz/issues/2104
Pls close this.
