### ISSUE TITLE
Boot required control d

### ISSUE THREAD

**Issue by ostermayer** [raspiblitz/raspiblitz#1070]
![2115D520-8A22-4097-A071-E4B9F33F734C](https://user-images.githubusercontent.com/4887941/76247242-36b2b600-620d-11ea-88b6-e81695ba0f19.jpeg)

**Comment by ostermayer** [comment]
could not boot fully into os until i did control d

when running headless without screen this. it made it appear as if ssh was down

**Comment by ostermayer** [comment]
this occurred after rtl install on reboot

**Comment by openoms** [comment]
Thanks for reporting I have this issue sometimes too, could not pin down what causes it yet.

**Comment by ostermayer** [comment]
i believe this happens if reboot occurs before lnd and bitcoind have stopped.  was able to reproduce by doing shutdown -now while lnd and bitcoind were in the process of stopping

**Comment by MrSlumber** [comment]
Keep my fingers crossed that this can be solved. Thanks to everyone contributing! :-)

**Comment by MrSlumber** [comment]
Oh no... Today I did a reboot knowing that the Pi wasn't fully synced and... same as @ostermayer posted above... :-(  No chance via SSH also because "connection refused"

Appreciate your help on this topic! Thank you :-)

**Comment by rootzoll** [comment]
@MrSlumber if you havent tried - power down and make a fresh sd card, see if it catches up

**Comment by cereal88** [comment]
> @MrSlumber if you havent tried - power down and make a fresh sd card, see if it catches up

**cant** login via SSH but now i can ping the pi and i see the loginscreen (login to pi via ssh admin@ip.....password is raspiblitz)

**Comment by MrSlumber** [comment]
> @MrSlumber if you havent tried - power down and make a fresh sd card, see if it catches up

Thank you but it didn't change. Did a fresh install but after some time again the same error.

**Comment by rootzoll** [comment]
It can be that your SSH keys are corrupted on the HDD - in that a fresh sd card will not help.
See if this fixes the SSH login problem: https://github.com/rootzoll/raspiblitz/issues/420#issuecomment-522248515

**Comment by MrSlumber** [comment]
> It can be that your SSH keys are corrupted on the HDD - in that a fresh sd card will not help.
> See if this fixes the SSH login problem: [#420 (comment)](https://github.com/rootzoll/raspiblitz/issues/420#issuecomment-522248515)

Thank you, will try :-)

**Comment by rootzoll** [comment]
Also added "fsck.mode=force" for the v1.5 RC1 release ... hope this will fix that issue .. see:
see https://github.com/rootzoll/raspiblitz/issues/1053#issuecomment-600878695

Closing issue.
