### ISSUE TITLE
Since 3 days Raspiblitz stopped working

### ISSUE THREAD

**Issue by lucbran** [raspiblitz/raspiblitz#1071]
Hi,
in spite of several reboots I get this error message as attached.
![20200310_091841](https://user-images.githubusercontent.com/22008556/76293378-3835ba00-62b1-11ea-9253-28c29e82b4eb.jpg)

**Comment by openoms** [comment]
https://github.com/rootzoll/raspiblitz/blob/master/FAQ.md#how-do-i-generate-a-debug-report
Share the link with the debug output after running this:
`/home/admin/XXdebugLogs.sh | nc termbin.com 9999`

**Comment by lucbran** [comment]
Hi,
here is the log  report: https://termbin.com/8qvi

**Comment by openoms** [comment]
your node is syncing, it takes some patience on a RPi3:
`progress=0.998828 `

**Comment by lucbran** [comment]
ok so when i read:bitcoinlnd is not running, is not correct info?

**Comment by openoms** [comment]
Your bitcoin node is not active, because it is syncing. 

You can say the message is inaccurate.

**Comment by lucbran** [comment]
but why this new long syncing after same was running well for long time?

**Comment by lucbran** [comment]
hi
looks like I am stuck at the same point...?
https://termbin.com/m8au

**Comment by openoms** [comment]
It is hard to tell from this, but likely to be a hardware failure / corruption.
Type:
`repair`
make a backup of the lnd data and reset the blockchain to start syncing from scratch. If does not work worth looking into changing the hard drive.

**Comment by nyxnor** [comment]
Pls close this.
