### ISSUE TITLE
Update LND 0.9.2

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#1078]
https://github.com/lightningnetwork/lnd/releases/tag/v0.9.2-beta

especially because of bugf fix for RaspberryPi
https://github.com/golang/go/commit/8b77410

**Comment by openoms** [comment]
Running 0.9.2 already without issues. The only difference from v0.9.1 is the fix.
Manual update has been tested: https://github.com/lightningnetwork/lnd/issues/4052#issuecomment-597274642

**Comment by 21-btcclub** [comment]
my node is now on 0.9.0, do I need to update first to 0.9.1 then to 0.9.2 or is there a script to follow? Or is there a guidance to build and from master for loop service?

**Comment by openoms** [comment]
you can update LND from any version with this script:
https://github.com/openoms/lightning-node-management/tree/master/lnd.updates#update-lnd-to-v092-beta

**Comment by rootzoll** [comment]
Extended even to the update to LND v0.10.0 --> https://github.com/rootzoll/raspiblitz/issues/1116
