### ISSUE TITLE
Update Bitcoin 0.19.1

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#1079]
https://github.com/bitcoin/bitcoin/releases/tag/v0.19.1

**Comment by openoms** [comment]
Updated successfully on my nodes.

Find the script to update between releases:
https://github.com/openoms/bitcoin-tutorials/tree/master/raspiblitz.updates#v0191

**Comment by rootzoll** [comment]
Looking good - closing issue for v1.5 RC2 release.
