### ISSUE TITLE
Switching to TESTNET leads to failed verification

### ISSUE THREAD

**Issue by jagottsicher** [raspiblitz/raspiblitz#108]
Swiched a completely  snyced and set up node to testnet and snced and setup there again. 

A try to connect to a faucet for testnet end up this way: 
```
` lncli connect 0270685ca81a8e4d4d01beec5781f4cc924684072ae52c507f8ebe9daf0caaab7b@159.203.125.125:9735
[lncli] rpc error: code = Unknown desc = verification failed: signature mismatch after caveat verification
`
```

**Comment by rootzoll** [comment]
testnet3 was quite messed up over the last of weeks. I kind of ignored it ... but will try to repair support for version 1.0 next month. Until then I will be afk for vacation.

**Comment by jagottsicher** [comment]
maybe this hint can help:
```
****************************************************************************
Helping Instructions --> for creating a new LND Wallet
****************************************************************************
A) For 'Wallet Password' use your PASSWORD C --> !! minimum 8 characters !!
B) Answere 'n' because you dont have a 'cipher seed mnemonic' (24 words) yet
C) For 'passphrase' to encrypt your 'cipher seed' use PASSWORD D (optional)
****************************************************************************

lncli --chain=bitcoin create
./70initLND.sh: 134: ./70initLND.sh: cannot create ./.error.out: Permission denied

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!! Make sure to write down the 24 words (cipher seed mnemonic) !!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
If you are ready. Press ENTER.

```
During setup there is already a problem

**Comment by rootzoll** [comment]
TODO: Retesting switching to testnet.
TODO: Use/test new network.chain.sh config script
TODO: Add Dialogs to 00menu.sh - replace 95switchTestMain.sh

**Comment by rootzoll** [comment]
TODO: test new integration in services and the config script
TODO: test the complete switching process again
TODO: remove old switching script

**Comment by rootzoll** [comment]
@jagottsicher about the failed verification ERROR -> when using lncli on testnet the parameter `--network=testnet` is mandatory

see https://github.com/Stadicus/guides/issues/240#issuecomment-428923161

**Comment by rootzoll** [comment]
OK - I adapted and tested (one testrun) all scripts to run with testnet again. Will be part of next sd card release.  closing ticket for now.
