### ISSUE TITLE
Closed terminal led to removal of torrent downloaded blockchain

### ISSUE THREAD

**Issue by patrikmojzis** [raspiblitz/raspiblitz#1084]
After Raspberry finished downloading the BTC blockchain via torrent, it started to move these files. During that process I closed the terminal as I thought it not necessary to have it open while I wait. However, when I checked it later and went to the next step of syncing up the last few percent of blockchain, it started to sync but from 0%. Is there any way how to restore the blockchain I have downloaded via torrent?

**Comment by rootzoll** [comment]
> Is there any way how to restore the blockchain I have downloaded via torrent?

In such cases you need to start freshat the moment - also see:
https://github.com/rootzoll/raspiblitz/issues/768#issuecomment-602869624
