### ISSUE TITLE
RTL update to release v0.7.0-beta-Loop

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#1085]
This is a major release with the integration of Lightning Lab's submarine swap service called Loop.

https://github.com/Ride-The-Lightning/RTL/releases/tag/v0.7.0

**Comment by rootzoll** [comment]
Just tested the v0.7.0 see #1087 ... installs just fine.

So next todo is to connect the loop service thru the config correctly.

**Comment by rootzoll** [comment]
OK - merged the PR for loop service ... now testing.

**Comment by rootzoll** [comment]
Testing looks good. RTL with loop support will be part of v1.5 RC1 release.

**Comment by openoms** [comment]
Looks and feels so good: https://twitter.com/openoms/status/1241824425726615555
