### ISSUE TITLE
Updating BTCPayServer to v1.0.4.2

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#1090]
Small update. Make one test run again, before release.

**Comment by rootzoll** [comment]
@openoms I reverted back to the old version to clear another bug first. Can you second check: 

- When I install TOR & then BTCPayServer the server semmes running
- I get a wget response on 23000
- but when calling the onion address in a TOR browser there is no answere

**Comment by openoms** [comment]
Couldn't reproduce this. Updated the scripts and uninstalled Tor. Installed BTCPay v1.0.3.164 together and after Tor too, the Hidden Service became available after a couple of seconds of returning to the main menu.

![image](https://user-images.githubusercontent.com/43343391/77575908-1dc42900-6ecc-11ea-8f9f-ccbfd0e1656f.png)

**Comment by openoms** [comment]
Could not reproduce this problem. I have synced and modified the latest script uninstalled Tor and reinstalled Tor + BTCPay together and then one-by-one too.
Don't see a reason in the changelog which could cause this.
v1.0.3.164 working fine:
![image](https://user-images.githubusercontent.com/43343391/77581522-c460f780-6ed5-11ea-877b-59935c80fa23.png)

**Comment by rootzoll** [comment]
OK it looks like its something with my TOR desktop browser - BTCPAY Server is showing up on my mobile TOR browser. So we are good here.

**Comment by openoms** [comment]
New major BTCPay release 1.0.4.0 with Payjoin support (requires an other hot wallet, not tested on the blitz yet):
https://docs.btcpayserver.org/features/payjoin

https://twitter.com/BtcpayServer/status/1250853659618967553

Will test and update here.

Their LND support is still partially broken, unfortunately only works properly with LND 0.8.2 for now.
https://github.com/rootzoll/raspiblitz/issues/1104

**Comment by openoms** [comment]
Installation looking good on 1.5RC1 with:
https://github.com/btcpayserver/btcpayserver/releases/tag/v1.0.4.0
and
https://github.com/dgarage/NBXplorer/releases/tag/v2.1.24

**Comment by openoms** [comment]
Managed to generate a hot wallet and the payjoin link is available to be paid with another BTCPay wallet as described in: https://docs.btcpayserver.org/features/payjoin

**Comment by rootzoll** [comment]
OK is merged - looking for final testing on v1.5 RC2 (coming as soon as lnd 0.10.0 is out).

**Comment by rootzoll** [comment]
Test look good .. closing for v1.5 RC2 release.

**Comment by openoms** [comment]
https://github.com/btcpayserver/btcpayserver/releases/tag/v1.0.4.1

**Comment by rootzoll** [comment]
Merged update. TODO: One final install test.

**Comment by openoms** [comment]
Updated to v1.0.4.2 as discussed in https://github.com/rootzoll/raspiblitz/pull/1140#issuecomment-620759409
https://github.com/rootzoll/raspiblitz/commit/05d6e644fcb9bfa54a3d82f5656054f022ac72b0
