### ISSUE TITLE
bitcoind not working

### ISSUE THREAD

**Issue by denis-3** [raspiblitz/raspiblitz#1094]
Hello.
After downloading bitcoind and downloading some blocks from the blockchain, the Raspberry Pi tells me that "The bitcoind service is not running." When I look into the debug logs, I see that it says bitcoind is active and running. What is the error in this case and how can I fix it? (The full debug log is here: https://termbin.com/8bc6) (Also attached is the error message the computer gives me, which contradicts the debug log)
<img width="509" alt="Screen Shot 2020-03-26 at 2 52 18 PM" src="https://user-images.githubusercontent.com/62725075/77700436-6eda2880-6f71-11ea-9ad8-57463edc3766.png">

Thanks in advance for any help!

**Comment by rootzoll** [comment]
From the logs it looks like its rolling thru all. the blocks ... this may take a while. Please check the logs regularlay and see if you still can see progress or if it got stuck on some error.

**Comment by denis-3** [comment]
It seems that I can't download any more blocks; when the Raspberry Pi were to boot up, the system would automatically start checking for bitcoind (which gives the same error as I first described).

**Comment by rootzoll** [comment]
If data on your hard drive got corrupted I would maye start fresh. Format HDD to FAT format on your lapop and make a fresh SD card.

**Comment by denis-3** [comment]
Thank you for the advice! I started fresh and formatted the HDD, and it is not giving me the initial error.
