### ISSUE TITLE
Windows OpenSSH client recommendation

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#1099]
I am just trying the windows openssh client in Powershell. Works really well. Easier than Putty/Kitty, might worth recommending in the readme.

https://www.howtogeek.com/336775/how-to-enable-and-use-windows-10s-built-in-ssh-commands/

![image](https://user-images.githubusercontent.com/43343391/77830989-4f373180-7124-11ea-90f9-533aa6355f66.png)

**Comment by openoms** [comment]
![image](https://user-images.githubusercontent.com/43343391/77831447-22d0e480-7127-11ea-8cea-46d2ae99adc3.png)

In this case only need to delete or edit the `Windows(C:)/Users/USERNAME/.ssh/known_hosts` file

**Comment by kaiobe** [comment]
I installed the Ubuntu 20.04 app from the the MS Store which uses the Windows Subsystem for Linux (WSL). Allows you to use Linux Terminal and run Linux command line utilities. Believe there's a version for a bunch of Linux distros.
https://www.microsoft.com/store/productId/9N6SVWS3RX71

**Comment by openoms** [comment]
@kaiobe this is after you have activted WSL, right? https://docs.microsoft.com/en-us/windows/wsl/install-win10
It takes a couple more steps.
