### ISSUE TITLE
Backup Solution

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#110]
This is a reasearch issue and there to collect infos and discuss. Its about the bigger question about wallet/channel state backup. 

For a personal discussion I got the hint to maybe look into this tech:
https://en.wikipedia.org/wiki/Distributed_Replicated_Block_Device

**Comment by rootzoll** [comment]
The backup topic seems to complex to solve with a service wrapper lile RaspiBlitz. Closing this for now and waiting for LND to provide backup features in the future.

**Comment by fluidvoice** [comment]
Of lesser importance perhaps to backup the SD card but ran into this and just wanted to save it...
https://github.com/billw2/rpi-clone

> rpi-clone is a shell script that is for cloning a running Raspberry Pi booted source disk (SD card or USB disk) to a destination disk which will be bootable. Destination disks are SD cards in the SD card slot or a USB card reader, USB flash disks, or USB hard drives.
