### ISSUE TITLE
BTCpay Server showing LN invoices as partially paid since LND 0.9.2

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#1104]
Linking to this issue on the BTCpay side: https://github.com/btcpayserver/btcpayserver/issues/1343#issuecomment-606533009

Seems to be a problem with connecting to LND v0.9.2 and above, waiting for an update to fix.

**Comment by openoms** [comment]
Updating to LND v0.10.0 https://github.com/rootzoll/raspiblitz/issues/1116 will break the LN invoice checking in BTCpay. It will be not possible to downgrade the nodes to the last compatible (lnd 0.9.0) version from v0.10.0 as major versions have irreversible database migrations.

Our priority is to keep up with LND.

Will update BTCpay once they sort out the compatility with LND 0.9.2 and above.
Note that this bug does not affect the onchain invoices,PayJoin capability and any other function of BTCPay.

Possible solution temporarily is to connect BTCpay to an external lightning node running LND 0.9.0.

**Comment by Roasbeef** [comment]
If someone has the raw listinvoices output for an invoice showing as "partial paid" we can likely get to the bottom of this pretty quickly.

**Comment by rootzoll** [comment]
Seems like RockstarDev wants also to work on this this weekend:
https://twitter.com/r0ckstardev/status/1253788719800336384?s=20

**Comment by openoms** [comment]
This seems to be fixed now in BTCPay and compatible with LND v0.10.0 RC4 too. 
Will need to checkout the latest master or wait for the next release: https://github.com/btcpayserver/btcpayserver/commits/master

**Comment by openoms** [comment]
Can confirm that the issue is fixed when building BTCpay with the commit: 
https://github.com/btcpayserver/btcpayserver/commit/d4dbe6fe17d844caf1636d29dc7d96414f0b18c6

We can incorporate this version to the next release. 

Fixed here: https://github.com/btcpayserver/btcpayserver/commit/c7305ba5e163698150a2acc8e1038a6bb5d197e6

**Comment by pretyflaco** [comment]
Can confirm that v1.5rc2 solves this. 
👌👏
