### ISSUE TITLE
Screen crooked after initialization.

### ISSUE THREAD

**Issue by tongokongo** [raspiblitz/raspiblitz#1106]
After initial block download (with fresh setup, starting from 0) the screen is showing the values with additional tabulation. No problem while interacting with a starting screen from ssh connection. Version 1.5-rc1, RPi4 4GB. There were no problems with previous versions on this hardware.

Restarting (power-off/on) fixes the problem.
![IMG_20200402_155143](https://user-images.githubusercontent.com/29152385/78319764-af5f1680-751c-11ea-88d8-0add1e059490.jpg)

**Comment by rootzoll** [comment]
I have seen similar graphic errors with LCDs that were not the model that was linked in the shopping list. If its not that LCD linked in the shopping and you get this too often, please exchange it.

**Comment by nyxnor** [comment]
Pls close tjis.
