### ISSUE TITLE
How to fix [lncli] rpc error: code = Unknown desc = no policy for outgoing channel 

### ISSUE THREAD

**Issue by 21-btcclub** [raspiblitz/raspiblitz#1107]
if I check my channel on my raspiblitz I get

*** YOUR LIGHTNING CHANNELS ***

mainnet                            Commit ------- Balance --------- --- Fee ----
Alias or Pubkey           Capacity   Fee        Local       Remote   Base PerMil
-------------------- ------------- ------ ------------ ------------ ----- ------
[lncli] rpc error: code = Unknown desc = no policy for outgoing channel 614498357105459200 
[lncli] rpc error: code = Unknown desc = no policy for outgoing channel 614498357105459200 
LNBIG.com [lnd-33]          719834    198       358878       360758             
-------------------- ------------- ------ ------------ ------------ ----- ------
[lncli] rpc error: code = Unknown desc = no policy for outgoing channel 614498357105459200 
Totals          1 ch        719834    198       358878       360758 Day:        
[lncli] rpc error: code = Unknown desc = no policy for outgoing channel 614498357105459200 
                                                                    Week:       
[lncli] rpc error: code = Unknown desc = no policy for outgoing channel 614498357105459200 
                                                                    Month:      

I found the same problem here:
https://github.com/lightningnetwork/lnd/issues/2911
on end 
"No work has been done on this yet. We can likely consider it for the v0.8.0 release."

My question is whether anyone has been working on this problem

**Comment by nyxnor** [comment]
Probably LND error at the time. Was it fixed @21-btcclub. If yes, pls close this.
