### ISSUE TITLE
Error while formatting 1TB SanDisk SSD Plus

### ISSUE THREAD

**Issue by bluewitch** [raspiblitz/raspiblitz#1120]
Having an issue with formatting the SSD, The error message instructed me to submit this to the Raspiblitz Github
![LM-6](https://user-images.githubusercontent.com/1021092/79512141-a890d300-7ff5-11ea-99eb-4d513c214bd3.png)

**Comment by rootzoll** [comment]
It looks like there is one partition on your disk that the standard procedure was not able to remove. Can you show me the output of -->`lsblk -o NAME,TYPE,LABEL,PTTYPE,PARTLABEL,PARTFLAGS`

**Comment by cereal88** [comment]
![btrfs2](https://user-images.githubusercontent.com/52385375/79585684-7011f780-80d0-11ea-9689-fd35f18fa2f8.PNG)

**Comment by cereal88** [comment]
ok, if you use an 32GB USB Stick u have only 29,8GB and the formatting script use the HDD/SSD to create the 30.0GB Partition. So it fails ....Now im using a 64GB USB Stick. Now im syncing Blockchain

**Comment by openoms** [comment]
I have tested the BTRFS script and running got to work it successfully, but did not use a thumbdrive when setting up.
Needed to modify the fstab manually to fix: https://github.com/rootzoll/raspiblitz/issues/1055

**Comment by cereal88** [comment]
![btrfs4](https://user-images.githubusercontent.com/52385375/79635548-e87cc500-8171-11ea-9830-dc9e20486f04.PNG)
![btrfs-disc](https://user-images.githubusercontent.com/52385375/79635556-f16d9680-8171-11ea-949d-b624559c24fe.PNG)
i am confused

**Comment by openoms** [comment]
put the middle 889GB partition in the fstab to be mounted in  `/mnt/storage`

Mine looks like this (redacted):
```
sudo cat /etc/fstab 
proc            /proc           proc    defaults          0       0
PARTUUID=xxxxxx-01  /boot           vfat    defaults          0       2
PARTUUID=xxxxxx-02  /               ext4    defaults,noatime  0       1
UUID=xxxxxxxxxxxxxxxx /mnt/hdd btrfs noexec,defaults,subvolid=257 0 2
UUID=xxxxxxxxxxxxxxxx /mnt/storage btrfs noexec,defaults,subvolid=257 0 2
UUID=xxxxxxxxxxxxxxxx /mnt/temp vfat noexec,defaults,uid=1002,gid=1002 0 2
```

```
$ lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda           8:0    0 931.5G  0 disk 
├─sda1        8:1    0    30G  0 part /mnt/hdd
├─sda2        8:2    0 867.5G  0 part /mnt/storage
└─sda3        8:3    0    34G  0 part /mnt/temp
mmcblk0     179:0    0  29.7G  0 disk 
├─mmcblk0p1 179:1    0   256M  0 part /boot
└─mmcblk0p2 179:2    0  29.5G  0 part /
```
```

**Comment by nyxnor** [comment]
Pls close this.
