### ISSUE TITLE
Attempted to re-login with ssh and raspiblitz as a password

### ISSUE THREAD

**Issue by bluewitch** [raspiblitz/raspiblitz#1121]
![LM-11](https://user-images.githubusercontent.com/1021092/79519034-7c7e4d80-8007-11ea-8331-65e37571a0b6.png)

**Comment by rootzoll** [comment]
Have you started the RaspiBlitz fresh? In worst-case make a fresh sd-card image.

**Comment by nyxnor** [comment]
Pls close this.
