### ISSUE TITLE
ElectrumX an Electrum Server alternative

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#1130]
Advantages: 
* has a rolling compaction so takes up space only incrementally , now up to 41 GB (vs Electrs up to 125 GB during initial sync and compacting to ~ half)
* supports batch querying of addresses (significant when using busy wallets like with joinmarket)

Negative:  
* takes much longer to sync
* needs txindex (+ 25 GB - but needed for other applications too, like BTC-RPC-Explorer)
Implementation notes: 
https://electrumx.readthedocs.io/en/latest/HOWTO.html#installing-on-raspberry-pi-3
https://electrumx.readthedocs.io/en/latest/HOWTO.html#running

**Comment by rootzoll** [comment]
The new standard HDD/SSD will be 1TB ... see https://github.com/rootzoll/raspiblitz/issues/1128#issuecomment-616816075

So I think we dont have much pressure/prio to change the Electrum server implementation at the moment.

**Comment by openoms** [comment]
ok, I am happy to close this, just wanted to make a note.
Electrs works well for personal usage, can reopen if someone would want to try ElectrumX.

**Comment by openoms** [comment]
Reopening as ElectrumX synced in ~2days on my server and is looking to be 5-6 days on the RPi. Might worth it for the huge performance benefit for large wallets:
https://sparrowwallet.com/docs/server-performance.html

Manual experimental guide to get started: https://github.com/openoms/bitcoin-tutorials/blob/master/electrumx.md

**Comment by openoms** [comment]
Took 6.5 days on the RPi  https://twitter.com/openoms/status/1487099572694437892 and likely superseeded by Fulcrum: https://github.com/cculianu/Fulcrum #2924

Closing again.
