### ISSUE TITLE
CleanUp XXsyncScripts.sh

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#1139]
Move the functionality of the `XXsyncScripts.sh` into a `config.scripts` script that then can also be used to set branch / repo etc.

**Comment by frennkie** [comment]
What exactly do you mean by this... everything?! :-D

**Comment by rootzoll** [comment]
@frennkie repo/branch ca be set with v1.5 ... so I think this is a double left over. Moving to config.scripts not so important. Closing issue.
