### ISSUE TITLE
Shred usage

### ISSUE THREAD

**Issue by frennkie** [raspiblitz/raspiblitz#1151]
@rootzoll What is the intention of the `shred` calls - e.g. in setpassword https://github.com/rootzoll/raspiblitz/blob/d0a24b295e4b6a1034c8e747bf28a1ee5776c9be/home.admin/config.scripts/blitz.setpassword.sh#L96

 Calling `shred` without parameters leaves the file behind (with random/garbage content). `shred -u` will also delete the file leaving behind less clutter.

**Comment by rootzoll** [comment]
The intension is to minimize the risk that temporary storage data can be recontructed and reveal sensible data. Using the -u option makes sense.

Best way would be not to temp store passwords at all and just keep as a var in mem. I recently found a way how to do that with with whiptal ... I will also replace that for the password entries.
