### ISSUE TITLE
Install loop

### ISSUE THREAD

**Issue by arcbtc** [raspiblitz/raspiblitz#1153]
Blitz is trying to restore my old corrupted Blitz, but is doing a strange install loop, where it is asking me to enter password A, doing a reboot, then asking me to enter password A again. 

I am trying to install without the screen, so this could be the issue

![image](https://user-images.githubusercontent.com/33088785/80865087-df661a80-8c7e-11ea-9dee-77993ada4bb8.png)

**Comment by rootzoll** [comment]
After the reboot .. what is the first thing/text/dialog you see (beside the regular linux/raspiblitz bootscreens)?

**Comment by arcbtc** [comment]
Switching to v1.5 so hopefully that will fix it.

**Comment by arcbtc** [comment]
Switched to v1.5 so redundant issue
