### ISSUE TITLE
Background initial sync on install

### ISSUE THREAD

**Issue by arcbtc** [raspiblitz/raspiblitz#1154]
Could the Blitz/bitcoind use a hosted blockchain and move the initial synch into a background operation?
So a user could start using the blitz more or less immediately.

**Comment by rootzoll** [comment]
There is a feature for bitcoind in the plans called "assumetxo" that could bootstrap with UTXO snapshots and then validate the history in the background:
https://github.com/jamesob/assumeutxo-docs/tree/2019-04-proposal/proposal

Once this is available, its something the RaspiBlitz will offer.

**Comment by arcbtc** [comment]
Could LND in the Blitz be neutrino, then use a local copy of the blockchain, once it is synched?

**Comment by rootzoll** [comment]
The RaspiBlitz is depend here what solutions are delivered by bitcoin core to solve this. the Coming "assumetxo" was the one solution targeting this use case  - as far as I heard. What other options are out there I dont know and would be something to discuss with the bitcoin core devs.

**Comment by arcbtc** [comment]
That's why I thought the neutrino angle could work, bypass core

**Comment by rootzoll** [comment]
Having two different BTC backends will mess up stuff up on too many ends, will take a lot of time to implement and there is a solution from bitcoin core in the works anyway . If you install a RaspiBlitz, you decided to run a FullNode - not a light client. If Bitcoin Core can speed that up in the future, that would be great - Im waiting for it and "assumetxo" looks like a good future fit.

**Comment by arcbtc** [comment]
Fair enough. I'll go bug people about assumetxo!

Cheers
