### ISSUE TITLE
status display has no date or time on it, data displayed is of unknown freshness

### ISSUE THREAD

**Issue by sneak** [raspiblitz/raspiblitz#1161]
There's no way to know if the status display is current or not.   It could have frozen; a date and time display (with seconds) should be incorporated into the LCD layout.

**Comment by frennkie** [comment]
@rootzoll what do you think about this..? I could add this to the, BlitzTUI title bar (even had this in an earlier version of BlitzTUI). I had second precision.. But I think Minutes is completely fine.

**Comment by sneak** [comment]
Seconds means I don’t have to sit there staring at it for a whole minute to know if it froze or is still running.  Please show seconds.

**Comment by sneak** [comment]
If you’re feeling fancy, it could show green or red based on the ntp sync status found in `ntptime` output.

**Comment by rootzoll** [comment]
Second to see update rate sounds good.

**Comment by frennkie** [comment]
@sneak are you using the normal LCD view or the Touch Screen view? In any case this sounds like a great issue for sending in a Pull Request.

**Comment by rootzoll** [comment]
Fixed witrh merge https://github.com/rootzoll/raspiblitz/pull/1565 .. will be part of v1.6.1 release
