### ISSUE TITLE
ThunderHub on the RaspiBlitz

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#1165]
Another great  LND Lightning Node Manager in your Browser.  
see https://www.thunderhub.io/  
Install instructions on the RaspiBlitz: https://gist.github.com/openoms/8ba963915c786ce01892f2c9fa2707bc

**Comment by openoms** [comment]
https://twitter.com/thunderhubio/status/1262822950971023361
https://github.com/apotdevin/thunderhub/releases

v0.6.0 - Add Server Authentication
Changes
ADD: SSO cookie authentication
ADD: Server accounts authentication
ADD: Switch to turn of third party fetching
ADD: Configure ThunderHub from .env file

**Comment by rootzoll** [comment]
If somebody on the next HackSprint is creating a install script for this we can put it into the v1.6 - so far I push this a bit back to v1.7

**Comment by openoms** [comment]
TunderHub now allows pre-creating password protected accounts on the server side. Running it for a while now. Everything is there for the install script so should be ready soon.

**Comment by rootzoll** [comment]
I merged and fixed some smaller things on the service menu.
But I am not able to open the thuderhub page on port 3010.
The systemd service is active, no error in the logs and port 3010 open ... so where to look next?

**Comment by rootzoll** [comment]
Perfect - the patch is fixing it and now it runs on my Blitz too :)
So just some final testing needed once v1.6 gets near to final release and were good.

**Comment by openoms** [comment]
very cool GUI for the Faraday stats on v0.7.0: https://twitter.com/thunderhubio/status/1268950899935846400?s=20

and our update function works well too :)

**Comment by rootzoll** [comment]
The faraday integration is sweet :)

The basic install script is still 0.6.13 ... @openoms will you upadte to the new version?

**Comment by openoms** [comment]
Updating to an even newer version v0.7.1.
That's why I felt the need for the update script because iterates so quickly.

My bad it is not really a faraday integration, but look-alike stats. Anyway the idea is coming from there and very useful in the GUI!

**Comment by rootzoll** [comment]
Updated to 0.8.4 see #1295

**Comment by rootzoll** [comment]
OK Thunderhub now also makes a clean reinstall on recover/update. Will be part of v1.6 final. Closing issue.
