### ISSUE TITLE
Torrent stops at 100%

### ISSUE THREAD

**Issue by FlyingMotion** [raspiblitz/raspiblitz#117]
it were downloaded more than 231230404 byte, see attached picture. Now it stopped at 231230408 and don´t finish the process. As I restarted the ssh the process was finished and the test for the readyness of the chainnetwork started.
![1](https://user-images.githubusercontent.com/43551180/45970992-397d1380-c038-11e8-9d4a-f82fc9b828b8.png)
![2](https://user-images.githubusercontent.com/43551180/45970993-397d1380-c038-11e8-884f-fcd5030e6012.png)

**Comment by rootzoll** [comment]
Back from vacation - sorry for the delayed response.

For the latest release (which you are running) the torrent download script looks if there is a "complete flag" set in the rtorrent metadata file. In all my test cases this was a proper detection that the torrent download was complete. Not sure why this didnt worked in your case.

I could also break monitor loop when download size is OK with an added timeout - but would like to avoid the extra complexity. 

I leave this issue open until verison 1.0 release - if anybody reports on the same problem or I can reproduce i will add the extra break case.

**Comment by geco91** [comment]
see PR #155 - it adds a small text info, so that user can force manually the monitor loop to close if torrent stops at 100% and automatic finish detection is not triggering. This should cover the edge case for now.

@rootzoll recommend closing this issue, when merging #155

**Comment by rootzoll** [comment]
#155 is merged. closing issue.
