### ISSUE TITLE
Update ElectRS to 0.8.5

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#1176]
https://github.com/rootzoll/raspiblitz/pull/1175

**Comment by rootzoll** [comment]
Also ElectRS is now served over HTTPS with nginx - see  #1254
- [ ] retest ElectRS over HTTPS

**Comment by openoms** [comment]
Electrs 0.8.5 is out (improves Electrum 4.0 compatibilty)

https://github.com/romanz/electrs/blob/master/RELEASE-NOTES.md

**Comment by rootzoll** [comment]
OK ElectRS is update
- [ ] test install
- [ ] retest ElectRS over HTTPS

**Comment by ogas2** [comment]
Hi, how can I update my raspiblitz to have the ElectRS 0.8.5?

**Comment by rootzoll** [comment]
@ogas2 ElectRS 0.8.5 will be part of RaspiBlitz v1.6 release. There is already a RC3 available for v1.6 ... but if its just recommended for test nodes: https://github.com/rootzoll/raspiblitz/blob/v1.6/README.md#downloading-the-software

Final v1.6 will be out within next week hopefully.

**Comment by rootzoll** [comment]
Not sure how to test the https (electrum just eat sthe https string) .. but it installs after recovery/update. Will be part of v1.6. Closing issue.
