### ISSUE TITLE
Update Loop to v0.6.5-beta

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#1177]
Introducing Multi-Loop
https://twitter.com/lightning/status/1261019739935191047?s=20

**Comment by rootzoll** [comment]
TODO: Test if working - also with RTL

**Comment by openoms** [comment]
Loop updated to 0.6.3 allowing Loop out from multiple channels with LND 0.10.1. https://github.com/lightninglabs/loop/releases
Surely command line only, but should not break RTL compatibility.

**Comment by rootzoll** [comment]
Nice - will add fpr v1.6. With all those releases coming out rapidly .. its like living on a train station :)

**Comment by openoms** [comment]
https://github.com/lightninglabs/loop/releases/tag/v0.6.4-beta

new update with some bug fixes

**Comment by openoms** [comment]
have the certificate bug in the go install script as well.

```
*** Installing Go v1.13.3 for armv6l ***
--2020-06-14 13:35:03--  https://dl.google.com/go/go1.13.3.linux-armv6l.tar.gz
Resolving dl.google.com (dl.google.com)... ::
Connecting to dl.google.com (dl.google.com)|::|:443... connected.
ERROR: The certificate of ‘dl.google.com’ is not trusted.
ERROR: The certificate of ‘dl.google.com’ doesn't have a known issuer.
The certificate's owner does not match hostname ‘dl.google.com’
!!! FAIL !!! Download not success.
```

EDIT: this was caused by my Pi-hole blocking Google.

Testing v0.6.4-beta.

**Comment by rootzoll** [comment]
OK updated to 0.6.5 ... installs and looks good so far. Ready for final testing.

**Comment by rootzoll** [comment]
Testing worked - together with RTL. Closing issue.
