### ISSUE TITLE
update 1.4 to 1.5 without new SD card because pi is more than just a node

### ISSUE THREAD

**Issue by phenomeus** [raspiblitz/raspiblitz#1181]
hi everybody, is there a way to update 1.4 to 1.5 without writing a fresh SD card with 1.5 because my rpi4 is more than just a RaspiBlitz 

i have also wireguard, Homebridge and pi hole on it and don't want to set up everything from scratch. 

thank you in advance

**Comment by rootzoll** [comment]
There is no clean way  - maybe just update LND and Bitcoind manually with scripts by openoms - but basically you stay at v1.4.

See background on this here: https://github.com/rootzoll/raspiblitz/blob/master/FAQ.md#why-do-i-need-to-re-burn-my-sd-card-for-an-update

**Comment by phenomeus** [comment]
Thanks for the answer. Unfortunately I read that already and Still hoped to get a hackY script. 

Can I execute the Manual build Script on that 1.4 pi?

Is there an upgrade way from Version 1.5 for the future releases or will it always be like this?

**Comment by rootzoll** [comment]
> Is there an upgrade way from Version 1.5 for the future releases or will it always be like this?

This is the upgrade way ... its the idea: if you add personal extra apps to it, that you take care of making them update secure: make yourself a small install script and store important data that should survice an update to mnt/hdd/app-data

> Can I execute the Manual build Script on that 1.4 pi?

I never tried - if you feel lucky, give it a try and report back.

**Comment by rootzoll** [comment]
TODO: Make it possible that the user can set a `custom-installs.sh` script in the `app-data` folder that gets called on upadtes with a fresh sd card. This way at least someone can automize to make custom installs in the pi re-done on on a update.

**Comment by phenomeus** [comment]
ok, so I did "wget https://raw.githubusercontent.com/rootzoll/raspiblitz/master/build_sdcard.sh && sudo bash build_sdcard.sh" after I stopped bitcoind and lnd and it went through. nice :) 

after the reboot I still see version 1.4 on the blue screen. now I wait until bitcoin is fully started

**Comment by phenomeus** [comment]
hmm, tor is somehow "broken": 2020-06-15T21:34:15Z connect() to 127.0.0.1:9050 failed after select(): Connection refused (111)

if I untick TOR in services and do a reboot I have a running bitcoind. if I tick/ activate TOR again, I get the above error

**Comment by phenomeus** [comment]
so to sum up: running the build script is a legit way but its not "upgrading" as expecting. it just runs through. maybe there is still a way to bump the version up to date. the daemons are getting updated with this way.

**Comment by phenomeus** [comment]
ok i figured it out and updated to 1.5.1, will try this again to version 1.6 and further, will report back. its possible, but with a lot of tinkering. still, thus I learn a lot how raspiblitz is made, very handy to support here in the future

**Comment by nyxnor** [comment]
@rootzoll Can this be added to the future release collector? I think it is important to update without flashing the sd card.

**Comment by rootzoll** [comment]
@nyxnor There is already a way to add custom installs script to run on a new update - see: https://github.com/rootzoll/raspiblitz/blob/v1.7/FAQ.md#why-do-i-need-to-re-burn-my-sd-card-for-an-update is there anyting more you want from this issue?

**Comment by nyxnor** [comment]
@rootzoll Can close this.
