### ISSUE TITLE
Torrent 'update' wont start

### ISSUE THREAD

**Issue by currenc-group** [raspiblitz/raspiblitz#1188]
After downloading bitcoin blockchain, the bitcoin update wont start. Any ideas why?
![Screenshot 2020-05-17 09 42 53](https://user-images.githubusercontent.com/63955967/82138724-e5353180-9822-11ea-8721-521aa2c3a4d9.png)

**Comment by ServerGuy420** [comment]
same here. Even 3 days later is not possible. Then synced with PC and copy to Raspiblitz.

**Comment by rootzoll** [comment]
One of the linked tracker services justseed.it went offline forever and also the other 3 backup tracker seemed not reachable for my seeding torrent client.

**Comment by rootzoll** [comment]
Planning to drop the torrent download option for the next release - also for other reasons: see #1179 ... please abort the torrent download with x and use the COPY option.

**Comment by currenc-group** [comment]
It is difficult to find a laptop with more than 250 gb space, so it will be difficult to download it to laptop and copy it to raspberry. Is there any alternative? If not, could you provide links where to download the blockchain from?

**Comment by ServerGuy420** [comment]
Torrents currently work in uTorrent. I don't know how it is directly via Raspiblitz.

I am currently uploading the blockchain to my server. This may take 2-3 days, but may help users in the future.

**Comment by rootzoll** [comment]
Because the torrent tracker of the upadte torrent file had problems I made a try to change those and hope they might work better. You need to hotfix your v1.5 to get the update:
- if you still try to torrent download - press x (delete old)
- Press CTRL+z (or CTRL+c) to exit to terminal
- Run command: `./XXsyncScripts.sh`
- Run command: `raspiblitz`
- Now start torrent option again

If somebody wants to help out better seeding the update-torrent filer for faster downloads, please seed this torrent from your computer/server: `https://github.com/rootzoll/raspiblitz/raw/v1.5/home.admin/assets/raspiblitz-bitcoin2-2020-01-28-update-c.torrent`

**Comment by ServerGuy420** [comment]
Yup, seeding is going much better now :)

**Comment by currenc-group** [comment]
> Because the torrent tracker of the upadte torrent file had problems I made a try to change those and hope they might work better. You need to hotfix your v1.5 to get the update:
> 
> * if you still try to torrent download - press x (delete old)
> * Press CTRL+z (or CTRL+c) to exit to terminal
> * Run command: `./XXsyncScripts.sh`
> * Run command: `raspiblitz`
> * Now start torrent option again
> 
> If somebody wants to help out better seeding the update-torrent filer for faster downloads, please seed this torrent from your computer/server: `https://github.com/rootzoll/raspiblitz/raw/v1.5/home.admin/assets/raspiblitz-bitcoin2-2020-01-28-update-c.torrent`

Thanks mate! I have accepted to wait for multiple weeks if necessary and went with with sync option (on 17% now). Since torrent is available again, i'd like to cancel the sync and download the blockchain via torrent again. Thing is, i can't cancel the syncing by clicking X anymore.

Is there a way to get back to downloading via torrent, or do i need to re-install everything?

**Comment by ServerGuy420** [comment]
I was able to choose another option after restart or continue syncing.

**Comment by currenc-group** [comment]
> I was able to choose another option after restart or continue syncing.

I didn't get this option unfortunately, it went back to syncing (and lost 0.5% for some reason).
Hopefully rootzoll can give advice.
![Screenshot 2020-05-22 11 26 28](https://user-images.githubusercontent.com/63955967/82653348-59a31280-9c1f-11ea-8b4e-c166dfd68d98.png)

**Comment by rootzoll** [comment]
Whe it goes backwards it means prob that somehow the validation stopped and because the blockchain growth you get a reverse status %. Not sure why this is happening .. maybe try a reboot: ssh in, CTRL-x or CTRL-z to get to terminal and run command `restart`

**Comment by currenc-group** [comment]
After 2 months of syncing, we're almost there 😄 
![Screenshot 2020-07-13 12 50 31](https://user-images.githubusercontent.com/63955967/87308918-38beb580-c51c-11ea-9987-568dcfc2d5a0.png)
