### ISSUE TITLE
[Hardware Alternative] HardKernel Odroid C4 

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#1196]
I had this promising SBC arrive and will test the RaspiBlitz scripts on it in the coming days: https://twitter.com/openoms/status/1253328059354116096

Advantages over the RPi4 4GB:
- close to fully open source hardware with all schematics readily available: https://wiki.odroid.com/odroid-c4/hardware/hardware#schematics_drawings_and_s905x3_datasheet 
- 64 bit Linux support by default
- eMMC socket - faster and more reliable then SDcards
- faster CPU
- 4*USB3 + microUSB connector
- more robust 12V power supply
- comes with a heatsink by default
- price is comparable, cheaper in many places

Benchmarks:
https://github.com/ThomasKaiser/sbc-bench/blob/master/Results.md:
![image](https://user-images.githubusercontent.com/43343391/82548543-5e01f980-9b53-11ea-9e59-94d4572ed742.png)
![image](https://user-images.githubusercontent.com/43343391/82548569-65c19e00-9b53-11ea-83d2-0cb94ce2e23f.png)
![image](https://user-images.githubusercontent.com/43343391/82548597-77a34100-9b53-11ea-83b1-08f89da04d6a.png)

Many Linux images available and all are 64 bits:
- Debian Buster
- Ubuntu
- Armbian (a choice of Ubuntu or Debian base)
- Manjaro (Arch)

Will start the first tests with Armbian since that is the closest to Raspbian and has Xserver and LXDE desktop option for the Touch UI as discusssed in: https://github.com/rootzoll/raspiblitz/issues/1184

**Comment by openoms** [comment]
The LXDE desktop is running on the HDMI already on Armbian Buster.
Screen activation:
https://wiki.odroid.com/accessory/display/3.2inch_tft_touchscreen_shield/c4/start

EDIT:
So far it seems not to have the display driver so will attempt again with the manufacturer's Ubuntu MATE desktop.
http://de.eu.odroid.in/?directory=.%2Fubuntu_20.04lts%2Fc4%2F

**Comment by rootzoll** [comment]
@openoms anything to keep in mind for a v1.6 release on this?

**Comment by openoms** [comment]
@rootzoll I have some minor refactoring the sd card build script, but it should not affect buillding on raspbian so there nothing to wait for here.

**Comment by openoms** [comment]
The display works so far, waiting to test the TUI.

Install steps:
```
https://wiki.odroid.com/odroid-c4/os_images/ubuntu/mate/20200422
Username 	Password 
root 	odroid
odroid 	odroid 

# activate display https://wiki.odroid.com/accessory/display/3.2inch_tft_touchscreen_shield/c4/start

sudo apt update && sudo apt full-upgrade

# Enable SPI Driver
# https://wiki.odroid.com/odroid-c4/application_note/gpio/spi#tab__odroid-c42
# SPICC0
sudo fdtput -t s /media/boot/meson64_odroidc4.dtb /soc/cbus@ffd00000/spi@13000 status "okay"
 # SPIDEV0
sudo fdtput -t s /media/boot/meson64_odroidc4.dtb /soc/cbus@ffd00000/spi@13000/spidev@0 status "okay"

# disable spidev node to avoid conflict.
sudo fdtput -t s /media/boot/meson64_odroidc4.dtb /soc/cbus@ffd00000/spi@13000/spidev@0 status "disabled"

# Enable LCD and Touchscreen
sudo fdtput -t s /media/boot/meson64_odroidc4.dtb /soc/cbus@ffd00000/spi@13000/ads7846@1 status "okay"
sudo fdtput -t s /media/boot/meson64_odroidc4.dtb /soc/cbus@ffd00000/spi@13000/hktft32@0 status "okay"

reboot
```

then on every start:
```
#Run Console
#map the console number 1 to the frame buffer 4 screen
sudo con2fbmap 1 4
# change the current console to 1
sudo chvt 1
```
https://twitter.com/openoms/status/1265598511523004421

The LCD goes to sleep after a while. Can be woken by pressing a key on an attached keyboard. Did not figure out how to keep awake yet.

**Comment by openoms** [comment]
Trying the Odroid forum about controlling the display: https://forum.odroid.com/viewtopic.php?f=205&t=39088

**Comment by openoms** [comment]
Building on the eMMC vs using an SDcard is significantly faster. Comparable to using the SSD: https://github.com/rootzoll/raspiblitz/issues/1235

**Comment by rootzoll** [comment]
#1243

**Comment by openoms** [comment]
The display comes alive automatically with these lines before the SCRIPT activation in `/home/pi/.bashrc`:
```
#map the console number 1 to the frame buffer 4 screen
sudo con2fbmap 1 4
# change the current console to 1
sudo chvt 1
```

As described in: https://forum.odroid.com/viewtopic.php?f=205&t=39088
Editing `/media/boot/boot.ini` with adding 
`consoleblank=0`
within the double quotes after
`setenv bootargs`
keeps the screen alive!

Now need to debug the installation of:

- [x] lnbits - python 3.8 needed in Pipfile

- [x] reduce the display font as in https://github.com/rootzoll/raspiblitz/issues/244#issuecomment-476713706 
(realized that the display I have has a 320x240 resolution (half) - the right one will be: https://wiki.odroid.com/accessory/display/3.5inch_lcd_shield/3.5inch_lcd_shield with the same number of pixels as the RPi LCD 480×320)
- [x] joinmarket]
`sudo ln -s /usr/bin/python3.8 /usr/bin/python3.7`
fixed the joinmarket installation
- [ ] lndmanage 
```
Building wheels for collected packages: grpcio
  Building wheel for grpcio (setup.py) ... error
```
- [ ] specter
```
Cryptoadvance Specter Setting changed ..
#    --> INSTALL Cryptoadvance Specter ***
#    --> Enable wallets in Bitcoin Core
#    --> Installing prerequisites
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libusb-1.0.0-dev
```
- [ ] touchscreen

**Comment by openoms** [comment]
Specter needs some debugging
```
Cryptoadvance Specter Setting changed ..
#    --> INSTALL Cryptoadvance Specter ***
#    --> Enable wallets in Bitcoin Core
#    --> Installing prerequisites
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libusb-1.0.0-dev
```

**Comment by openoms** [comment]
Install python 3.7 from source:
```
sudo apt-get install build-essential checkinstall
sudo apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev \
    libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-
cd /usr/src
sudo wget https://www.python.org/ftp/python/3.7.7/Python-3.7.7.tgz
sudo tar xzf Python-3.7.7.tgz
cd Python-3.7.7
sudo ./configure --enable-optimizations
sudo make altinstall
```
Alternatively (much quicker): 
```
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt install python3.7
```
Make 3.7 the default with: 
`sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.8 2`
`sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.7 1`
`sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1`

needs: `sudo apt-get reinstall python3.7-venv`

**Comment by openoms** [comment]
Also fails (on Odroid C4 - Ubuntu - python 3.8):
![image](https://user-images.githubusercontent.com/43343391/85957006-8dd9c380-b981-11ea-9616-50c4b810338c.png)
![image](https://user-images.githubusercontent.com/43343391/85957008-97632b80-b981-11ea-9628-1df0ed14c663.png)
![image](https://user-images.githubusercontent.com/43343391/85957019-a3e78400-b981-11ea-85de-e367759b527c.png)
![image](https://user-images.githubusercontent.com/43343391/85957031-ba8ddb00-b981-11ea-81ec-a2b40cc0e303.png)  
Pasted the 24words
![image](https://user-images.githubusercontent.com/43343391/85957056-f4f77800-b981-11ea-90fb-f5c64f0af1d4.png)
![image](https://user-images.githubusercontent.com/43343391/85957059-f9bc2c00-b981-11ea-9a9f-2b67ee343e3f.png)
![image](https://user-images.githubusercontent.com/43343391/85957063-06d91b00-b982-11ea-8258-7ac4e14a7bed.png)

**Comment by openoms** [comment]
For the record manual SDcard install looking ok with v1.6:
https://pastebin.com/raw/3BGKYHjV

will need to install `btrfs-progs` instead of `btrfs-utils`.

Needed to manually unmount the HDD from both :
```
Sometimes a reboot helps --> sudo shutdown -r now
admin@odroid:~$ lsblk
NAME         MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda            8:0    0 931.5G  0 disk 
└─sda1         8:1    0 931.5G  0 part /media/usb0
mmcblk0      179:0    0  29.1G  0 disk 
├─mmcblk0p1  179:1    0   128M  0 part /media/boot
└─mmcblk0p2  179:2    0    29G  0 part /
mmcblk0boot0 179:32   0     4M  0 disk 
mmcblk0boot1 179:64   0     4M  0 disk 
mmcblk0rpmb  179:96   0     4M  0 disk 
admin@odroid:~$ sudo umount /media/usb0
admin@odroid:~$ lsblk
NAME         MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda            8:0    0 931.5G  0 disk 
└─sda1         8:1    0 931.5G  0 part /mnt/hdd
mmcblk0      179:0    0  29.1G  0 disk 
├─mmcblk0p1  179:1    0   128M  0 part /media/boot
└─mmcblk0p2  179:2    0    29G  0 part /
mmcblk0boot0 179:32   0     4M  0 disk 
mmcblk0boot1 179:64   0     4M  0 disk 
mmcblk0rpmb  179:96   0     4M  0 disk 
admin@odroid:~$ sudo umount /mnt/hdd
```
for the hdd contents to be recognised.

**Comment by openoms** [comment]
My only C4 is dead :( .
