### ISSUE TITLE
Make BTCPayServer install on update/recovery

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#1198]
At the moment on v1.5:
--> TODO: BTCPay Server install does not run clean during provision
--> needs install when everything is already 'running'

**Comment by rootzoll** [comment]
This should be part of the "re-factoring" of the setup process: #1126

**Comment by openoms** [comment]
The BTCpay install scripts is also not configured for testnet so could do with some refactoring itself for a future release.

**Comment by openoms** [comment]
@rootzoll i think this is sorted already and can be closed
