### ISSUE TITLE
Weird letters as style

### ISSUE THREAD

**Issue by Kapot** [raspiblitz/raspiblitz#1200]
Hey,

Not sure what I did wrong but my info screen looks like this (SSH on Kitty and on Termuis (Android).

![raspiblitz](https://user-images.githubusercontent.com/6935358/82702636-a6fc9f80-9c72-11ea-824f-930c248df8e7.png)

Any way to fix this?

**Comment by frennkie** [comment]
Did you check first https://github.com/rootzoll/raspiblitz/issues/353 and may be also https://github.com/rootzoll/raspiblitz/issues/314 ?

**Comment by Kapot** [comment]
Hey, yes I did. But it seems to be in my pi rather then the software I use to ssh.

When I tried to change to HDMI output I got this message, maybe this helps?

	
> # SWITCHING VIDEO OUTPUT TO --> HDMI
> apt-listchanges: Can't set locale; make sure $LC_* and $LANG are correct!
> perl: warning: Setting locale failed.
> perl: warning: Please check that your locale settings
> LANGUAGE = (unset),
> LC_ALL = (unset),
> LC_TIME = "nl_NL.UTF-8",
> LC_MONETARY = "nl_NL.UTF-8",
> LC_ADDRESS = "nl_NL.UTF-8",
> LC_TELEPHONE = "nl_NL.UTF-8",
> LC_NAME = "nl_NL.UTF-8",
> LC_MEASUREMENT = "nl_NL.UTF-8",
> LC_IDENTIFICATION = "nl_NL.UTF-8",
> LC_NUMERIC = "nl_NL.UTF-8",
> LC_PAPER = "nl_NL.UTF-8",
> LANG = "en_US.UTF-8"
> are supported and installed on your system.
> perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
> locale: Cannot set LC_ALL to default locale: No such file or directory

Then the SSH connection got closed.

**Comment by frennkie** [comment]
Which image are you using?

On a fresh V1.5 install I get this for `locale`

```
admin@raspberrypi:~ $ locale
LANG=en_GB.UTF-8
LANGUAGE=
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=
```

Env

```
admin@raspberrypi:~ $ env | grep -iE "^term|^lang"
LANG=en_GB.UTF-8
TERM=putty
```

**Comment by Kapot** [comment]
v1.5-2020-05-08.img. I did raspi-config to setup timezone etc, maybe I made a mistake there? Anyone know how to change back to en_GB.UTF-8 for everything?

**Comment by frennkie** [comment]
Should be something like `sudo dpkg-reconfigure locales` (re-) install missing locales.

More info: https://www.thomas-krenn.com/en/wiki/Configure_Locales_in_Ubuntu

**Comment by Kapot** [comment]
> Should be something like `sudo dpkg-reconfigure locales` (re-) install missing locales.
> 
> More info: https://www.thomas-krenn.com/en/wiki/Configure_Locales_in_Ubuntu

This seem to have fixed it. It seems normal now across devices!

**Comment by rootzoll** [comment]
@frennkie anything we should add/change on the setup for next release?

**Comment by frennkie** [comment]
Nope - not that I'm aware of...

**Comment by Kapot** [comment]
The message of raspbian that the WiFi is disabled and you have to run raspi-config to set the country triggered me to do it. Can't disable this message I think?

**Comment by rootzoll** [comment]
TODO: Check on the "WiFi is disabled" message for v1.6 release.

**Comment by Kapot** [comment]
To complete it, this is the message shown:

> Wi-Fi is currently blocked by rfkill.
> Use raspi-config to set the country before use.

**Comment by frennkie** [comment]
I briefly looked into it.. on Windows running `KiTTY` (a `PuTTY` fork) the setting (2) here is key:

![KiTTY_Config](https://user-images.githubusercontent.com/6499251/83300793-f1dd6080-a1f8-11ea-9d77-cd9aa7232854.png)

**Comment by frennkie** [comment]
> TODO: Check on the "WiFi is disabled" message for v1.6 release.

@rootzoll can you be more precise on what we want to check there? I have used `sudo raspi-config` 2-3 times today on a fresh v1.5 node (change Timezone, setup WiFi instead of LAN) and this works fine.

**Comment by rootzoll** [comment]
@frennkie if you tested on windows and this was working fpr you, then we can close this issue.
