### ISSUE TITLE
Move BlitzTUI log to RAM disk

### ISSUE THREAD

**Issue by frennkie** [raspiblitz/raspiblitz#1205]
The RAM disk (`/var/cache/raspiblitz/`) is a nice way to avoid reads and writes to either the SD card or the external disk for non-persistent data. Several things can be moved; the BlitzTUI log should be  a prime example.

**Comment by hermanlim** [comment]
As of a couple of days ago, RPI4 supports booting from USB! (https://www.tomshardware.com/how-to/boot-raspberry-pi-4-usb) So perhaps a way to reduce wear on SD card (by eliminating it completely once initial setup completed) and/or also to simplify setup.

[Edit: Update 1]
USB booting certainly does work, however using the recommended 1TB Crucial SSD and a compatible SATA-USB cable (non powered) with the official RPi4 Power Adapter, there appeared to be some issues getting the mouse and keyboard to work -perhaps power related.

[Edit: Update 2]
Everything works well now. Keyboard was trying to charge so sapping off more power than usual leading to flaky/weird behaviour.

I've run bitcoind and another crypto daemon without so much as a hitch.

**Comment by rootzoll** [comment]
@frennkie after a day of running the BlitzTUI with RAM logs it constantly restarts and the error in the logs is `No space left on device` on `/usr/lib/python3.7/logging/handlers.py`.

This is how the pi directory looks like:
![Bildschirmfoto 2020-06-03 um 13 46 15](https://user-images.githubusercontent.com/2472225/83633243-e7c4b480-a5a0-11ea-8767-fa36c97ea49e.png)

**Comment by frennkie** [comment]
Did you use the sync script? If yes... Was BlitzTUI updated to 0.48.1? I limited the size to 2 files with max 2 MB

**Comment by rootzoll** [comment]
OK BlitzTUI was not updated correctly - I think there was a "sudo" missing to remove the old version. Now its updated and runs OK so far.

**Comment by frennkie** [comment]
I started the ram disk initially with 4MB...2x 2MB log files are already 4MB... I created a PR for increase to 8MB (I guess we could go to like 32MB...)

**Comment by rootzoll** [comment]
32 seems like a good number :)

**Comment by rootzoll** [comment]
Looks good. Closing issue.
