### ISSUE TITLE
Different time zones RTL

### ISSUE THREAD

**Issue by inpharmaticist** [raspiblitz/raspiblitz#1217]
I recently changed the time zone of my node (via sudo raspi-config) and RTL still shows old and new transactions in the original time.

**Comment by openoms** [comment]
just restart the node

**Comment by inpharmaticist** [comment]
Restarted, made a new payment, confirmed date on the node. RTL still showing 7 hours ahead.

**Comment by openoms** [comment]
Are you expecting RTL to change the times retrospectively in the lnd database?

The time of ab invoice creation for example.is matched with the time on the underlying OS.

Check the time on your node with the command:
`date`

**Comment by inpharmaticist** [comment]
No, for each of my attempts above, I made new payments that also weren't correct. Date on node is currently correct.

![image](https://user-images.githubusercontent.com/49789899/82962013-d01f7780-9f73-11ea-8887-25836647e9a1.png)

FWIW times were corrected on Zeus. Seems like an RTL issue.
