### ISSUE TITLE
RTL not paying invoices

### ISSUE THREAD

**Issue by inpharmaticist** [raspiblitz/raspiblitz#1218]
I've been trying to pay LN invoices (such as from yalls.org) and RTL doesn't pay them. Last week it was giving an error (don't remember the details). Now, it just doesn't do anything.  I can pay through the raspiblitz menu or the terminal commands, though.

**Comment by openoms** [comment]
please provide more details.
Browser used, error messages etc.

Also seems like to be an RTL problem not raspiblitz

**Comment by CoderBoogs** [comment]
@inpharmaticist i been trying to create a pay article on yalls and it never worked. Have you tried other lnd wallets besides RTL?

**Comment by frennkie** [comment]
Same for me.. I can pay a yalls.org invoice using `lncli payinvoice ` and can browser `RTL` (e.g. balances and channels) but paying an invoice from `RTL` fails. 

There is an error in the log which I will have a look at.. check yourself: `sudo journalctl -f -u RTL`

Partial log:

```
node[3242]: ERROR: Channels(143) => Send Payment: {"name":"StatusCodeError","statusCode":500,"message":"500 - {\"error\":\"checksum failed. Expected 6tfy89, got e3y4a6.\"
...
"url":"https://localhost:8080/v1/channels/transactions"
```

In the `LND` (0.9.2) log I get this:

```
[/lnrpc.Lightning/SendPaymentSync]: checksum failed. Expected zdf4ls, got 6fjkjl.
```

**Comment by frennkie** [comment]
The is an issue on RTL and there appears to be a fix in `RTL` version `0.7.1` https://github.com/Ride-The-Lightning/RTL/issues/283 "Firefox Payment Failure Issue" https://github.com/Ride-The-Lightning/RTL/commit/a980d9c3fa8772667608238199ccec8afc480516

**Comment by frennkie** [comment]
Can confirm: Tor Browser (Firefox) does not work. Chrome works on Version 0.7.0 (RB V1.5)

**Comment by openoms** [comment]
Try updating RTL with:

`sed -i s/v0.7.0/v0.7.1/g /home/admin/config.scripts/bonus.rtl.sh`

and reinstall from the menu.

**Comment by frennkie** [comment]
Yes.. that fixed it for me: https://github.com/rootzoll/raspiblitz/commit/ca8f5dd39118ed94dc5e3f08a91e843587a1b2d8

**Comment by inpharmaticist** [comment]
> please provide more details.
> Browser used, error messages etc.
> 
> Also seems like to be an RTL problem not raspiblitz

It was on Linux Mint using Firefox.  Followed:

>`sed -i s/v0.7.0/v0.7.1/g /home/admin/config.scripts/bonus.rtl.sh`
Removed and re added from "Activate/Deactivate Services" menu

Working now. Thanks.

**Comment by CoderBoogs** [comment]
Correction! I am having the same issue my apologies for providing mis information. Will apply the update suggested.
