### ISSUE TITLE
Nginx integration for Thunderhub

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#1233]
As discussed in https://github.com/rootzoll/raspiblitz/issues/255

Dedicated issue to not delay adding ThunderHub to services in https://github.com/rootzoll/raspiblitz/pull/1225

**Comment by rootzoll** [comment]
I try to put together a RC1 for the hacksprint. @openoms is it realistic to get this done for an RC2 the week after the hacksprint?

**Comment by openoms** [comment]
Will have a look at how RTL in configured with it's four ports. 
Having an RC1 base will help to see it in action.

**Comment by rootzoll** [comment]
OK. Self-Signed HTTPS now looks good :)

**Comment by rootzoll** [comment]
Testing also after recovery/update looks good. Will be part of v1.6 release. Closing issue.
