### ISSUE TITLE
Update Bitcoin Core to v0.20.0

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#1236]
Successfully tested with running the latest scripts:
![btccore](https://user-images.githubusercontent.com/43343391/83641038-e1383c00-a5a4-11ea-9be7-c7beee43e4f3.png)

Manual update script: https://github.com/openoms/bitcoin-tutorials/blob/master/raspiblitz.updates/README.md#v0200

**Comment by rootzoll** [comment]
https://github.com/bitcoin/bitcoin/releases/tag/v0.20.0

**Comment by openoms** [comment]
Did not get any problems, but the new lnd version release notes have

>This marks the second minor release in the v0.10.0 series! This release allows lnd to be compatible with bitcoind 0.20, and fixes an important bug related to an on disk Static Channel Backups (SCB).

https://github.com/lightningnetwork/lnd/releases/

Best to update.
Related: https://github.com/rootzoll/raspiblitz/issues/1240

**Comment by rootzoll** [comment]
The Bitcoin 0.20.0 looking good. Closing issue.
