### ISSUE TITLE
Shopping list updates

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#1239]
Adding details to the shopping list: https://github.com/rootzoll/raspiblitz/pull/1238

The links can be tested individually with a help of a VPN, but only clicked through for amazon.co.uk:
* The LCD is out of stock.
* The 1TB Hard Drive links to a 500 GB.
* The standard package should point to the 4GB RPi4 as the best value for money choice

**Comment by nyxnor** [comment]
Pls close this as there are more recent ones.
