### ISSUE TITLE
IP2Tor - shop-list

### ISSUE THREAD

**Issue by frennkie** [raspiblitz/raspiblitz#1247]
Should a call to shop-list without an URL work?

```
admin@host:~ $ config.scripts/blitz.subscriptions.ip2tor.py
# manage ip2tor subscriptions for raspiblitz
# blitz.subscriptions.ip2tor.py create-ssh-dialog [servicename] [toraddress] [torport]
# blitz.subscriptions.ip2tor.py shop-list [shopurl]
# blitz.subscriptions.ip2tor.py shop-order [shopurl] [servicename] [hostid] [toraddress:port] [duration] [msatsFirst] [msatsNext] [?description]
# blitz.subscriptions.ip2tor.py subscriptions-list
# blitz.subscriptions.ip2tor.py subscriptions-renew [secondsBeforeSuspend]
# blitz.subscriptions.ip2tor.py subscription-cancel [id]
# blitz.subscriptions.ip2tor.py subscription-by-service [servicename]

admin@tpt3:~ $ config.scripts/blitz.subscriptions.ip2tor.py shop-list

None
error='incorrect parameters'
admin@host:~ $
```

**Comment by rootzoll** [comment]
When the url is missing, then a "incorrect parameters" is correct. Because which shop should be called?

**Comment by frennkie** [comment]
That's fine.. But then this is misleading..!

```
# blitz.subscriptions.ip2tor.py shop-list [shopurl]
```

Need to remove the brackets from shopurl..

**Comment by rootzoll** [comment]
Oh ok ... I always thought that something in brackets is a Variable. If a variable/parameter is optional it would be [?shopurl]

**Comment by frennkie** [comment]
I would say

```
blitz.subscriptions.ip2tor.py shop-list [shopurl]
```

-> shopurl is optional

```
blitz.subscriptions.ip2tor.py shop-list shopurl
```

-> shopurl is required... 

🤷

**Comment by rootzoll** [comment]
We could be more strict on having "one standard" but is it that important?

**Comment by frennkie** [comment]
Just saying: https://en.wikipedia.org/wiki/Usage_message

If something has `[]` then around it then it is **optional**.

@openoms Do you want to be the *tiebreaker* here and decide whether we fix this or leave it as is?! ;-D

**Comment by openoms** [comment]
> Just saying: https://en.wikipedia.org/wiki/Usage_message
> 
> If something has `[]` then around it then it is **optional**.
> 
> @openoms Do you want to be the *tiebreaker* here and decide whether we fix this or leave it as is?! ;-D


According the  wiki article:  
```
<for required>  
[for optional]  
```
arguments.

I think it is useful to put some kind of bracket to indicate it is an argument. Otherwise it looks like it is a part of the command.

So in this case it would be:

```​
blitz.subscriptions.ip2tor.py <shop-list> [shopurl]
```

**Comment by frennkie** [comment]
I don't like the <>. 

People should be easily able to copy paste from the help output.

The only things that should get any kind of brackets is the description as this can be given of not.

**Comment by openoms** [comment]
The the options/variables which need to be filled (and not copy-pasted) would need to be in some kind of bracket.
`< >` for required
`[ ]` for optional
If you are showing the options as different commands then they can be easily copied and don't need brackets.
