### ISSUE TITLE
Stuck in maintenance mode after screen rotate

### ISSUE THREAD

**Issue by Q8w3rgxr** [raspiblitz/raspiblitz#1252]
I used the rotate screen option in the menu and got prompted with the maintenance screen after the reboot. As suggested here [**issue782**](https://github.com/rootzoll/raspiblitz/issues/782) i flashed a new sd card. The raspiblitz software is starting and going into recovering mode but then shuts down and restarts back to the maintenance screen again (tried it 3 times with fresh sd cards). 

Any idea on how to fix this? My biggest concern is that something with the HDD is wrong and i have to resync the Blockchain. 

Is it still possible to get the old 1.4 raspiblitz version? Feels wrong to try to recover with a newer version... 

**Hard-/Software:**
- Raspberry Pi4b (4GB) (Also tried with my old P3, same problem)
- Original SD raspiblitz v1.4-2020-02-20
- New SD  raspiblitz v1.5.1-2020-05-30

Original 1.4 SD (at least the screen rotation worked...)
![Screenshot 2020-06-10 at 10 02 30](https://user-images.githubusercontent.com/16136112/84244481-fd3b6080-ab03-11ea-8dec-707eae782855.png)

New 1.5 SD
![Screenshot 2020-06-10 at 10 02 07](https://user-images.githubusercontent.com/16136112/84244592-252ac400-ab04-11ea-9b0f-6bde55c06c68.png)

HDD is mountable in Ubuntu (are there maybe any hidden logs?)
<img width="444" alt="Screenshot 2020-06-10 at 10 52 27" src="https://user-images.githubusercontent.com/16136112/84247732-c287f700-ab08-11ea-8a02-061652f92ffe.png">

**Comment by rootzoll** [comment]
If you get stuck in that "maintenance mode" thats annoying. You already tried the basic things to fix this error like reflashing the sd card or even getting a new sd card to try with - that solved this error on my side all the time.

But because this is not working for you we are getting into a try-and-error area here:
- Do you still have the Shimfan running? - it caused strange boot errors before.
- If you start a fresh sd card image without the HDD connected, what does the screen say?
- Have tried to start it without the LCD and checked if you can SSH in?

**Comment by Q8w3rgxr** [comment]
Thanks for trying to help me! I tried everything you recommended.

- No Shimfan running, i just use cooling pads
- if i start with a fresh sd card without the HDD connected it tells on the display to ssh in. In ssh it complains that there is no HDD connected:
<img width="466" alt="Screenshot 2020-06-11 at 17 34 13" src="https://user-images.githubusercontent.com/16136112/84406435-cea7ad80-ac09-11ea-84f2-fffe90a0cea1.png">
After connecting the HDD and restarting it, recovery mode starts but after that it always ends up in maintenance mode again. 
<img width="986" alt="Screenshot 2020-06-11 at 17 27 51" src="https://user-images.githubusercontent.com/16136112/84406019-3dd0d200-ac09-11ea-9ed2-c71e60b5d9f7.png">
-->
<img width="868" alt="Screenshot 2020-06-11 at 17 32 26" src="https://user-images.githubusercontent.com/16136112/84406245-8daf9900-ac09-11ea-8445-a5c63e43b652.png">

- starting without the LCD does not work. As soon as it gets into maintenance mode, there is no ssh connection possible.

So, how about starting with a fresh HDD and then using the option to copy the blockchain from the old one? Will the syncing data be cpoied as well? My only concern is that i have to wait for the sync again as it took about 2 months...

**Comment by Q8w3rgxr** [comment]
Ok, so i wasnt able to solve the problem directly but at least the blockchain and sync data wasn´t affected so i was able to recover it from the old HDD.
