### ISSUE TITLE
Update Torrent File and FTP download 

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#127]
Focus of last release was to change to a more stable torrent client and a better FTP server. Beside some edge case reports this looks good. Next step is now to update the data of FTP and Torrent with new index for Bitcoin 0.17.0 - to get rid of the long time consuming update index after download.

**Comment by arcbtc** [comment]
I had no luck with the torrent so switched to ftp, however it has been hanging at 98% for past 12hrs?
![image](https://user-images.githubusercontent.com/33088785/46697761-43dd0700-cc0d-11e8-9139-638bb5e4bf81.png)

**Comment by arcbtc** [comment]
Still stuck 24hrs later? I'll try pulling the chain from somewhere else

**Comment by rootzoll** [comment]
@arcbtc not sure why this happened. Will run FTP test again - see if I can reproduce.

For the torrent: Make two torrents - a) Base Blocks and keep this as a base for a long time for good seeding. b) Torrent with Update Blocks, chainstate and Indexes. Later on maybe automate the upadte torrent, but keep it manual for now.

**Comment by Smiggel** [comment]
I am also stuck at 98% using torrent download.

**Comment by Smiggel** [comment]
Torrent fails at 98%. Setup wants to continue, but everytime it stops as it says the torrent fails. I can keep the data for a continued download, but it does not help. It keeps being stuck in this loop. Trying now using FTP.

**Comment by arcbtc** [comment]
Could it be the FTP thinks the file needs to be bigger?  This blockchain was only a few hours old and downloaded through bitcoin core:
![image](https://user-images.githubusercontent.com/33088785/46945400-90d93700-d06c-11e8-9119-32d7f5ac0fd2.png)

**Comment by rootzoll** [comment]
Yeah it should check for 253000000 not 259000000 - thats too big. Do you use the lastest SD card image? raspiblitz-2018-09-22.img.gz?

**Comment by arcbtc** [comment]
I think so. Will flash sd and report back

**Comment by Smiggel** [comment]
@rootzoll, same happens with a own build. I used the script to build the new node instead of the disk image. 

The FTP download continues after 253000000.

It’s also not working. The node tries to download the blockchain all over again.

**Comment by Smiggel** [comment]
Ok, update. This morning, after a night of downloading, the download continues after 253000000 and then stopped. I exited the download process and continued the setup. So far it looks good. The node downloaded the remaining blocks and it's now continuing.

**Comment by JupJar** [comment]
using latest SD Card build
no luck with the torrent so switched to ftp, however ......

<img width="538" alt="screenshot 2018-10-17 at 12 01 52" src="https://user-images.githubusercontent.com/35327533/47063235-85207880-d204-11e8-83a9-cab414769ddb.png">

**Comment by rootzoll** [comment]
OK. FTP and Torrent looks also good on my side now. I wrote a bit about the new torrent setup (base&update): https://github.com/rootzoll/raspiblitz/blob/master/background_downloadBlockchain.md

I set this issue to close for now.
