### ISSUE TITLE
 [ERR] RPCS: [/lnrpc.Lightning/SubscribeChannelGraph]: router not started

### ISSUE THREAD

**Issue by AntonKanns** [raspiblitz/raspiblitz#1277]
Hello. I am running a Rootzoll RaspiBlitz Node. In my lnd.log i have the following error: [ERR] RPCS: [/lnrpc.Lightning/SubscribeChannelGraph]: router not started
Can you tell me the reason and how to fix it

XXdebugLog.sh: https://termbin.com/f4sm

**Comment by AntonKanns** [comment]
![Anmerkung 2020-06-22 153425](https://user-images.githubusercontent.com/44521792/85293644-ee5a9380-b49d-11ea-87af-5ae5f2b26f61.jpg)

**Comment by rootzoll** [comment]
This looks like an edge LND error ... please check the LND Dev Slack/Issues on that:
https://dev.lightning.community

**Comment by nyxnor** [comment]
Please close this issue @AntonKanns

**Comment by rootzoll** [comment]
Closing this issue. Please reopen if still an issue.
