### ISSUE TITLE
LND Update fails

### ISSUE THREAD

**Issue by AntonKanns** [raspiblitz/raspiblitz#1278]
Hello, 
when i try to Update LND 10.0.0 I get the following error message:
PGP Author Check failed

![photo_2020-06-22_15-29-29](https://user-images.githubusercontent.com/44521792/85293165-4349da00-b49d-11ea-9f17-e849a23ee09e.jpg)

![photo_2020-06-22_15-29-53](https://user-images.githubusercontent.com/44521792/85293190-4b097e80-b49d-11ea-896e-25e343af2707.jpg)

Can someone help me please?
Btw it is possible to install the Experimental LND update but the Optional LND Update leads to this error.

Greetings
Anton

**Comment by openoms** [comment]
Can use this script instead: https://github.com/openoms/lightning-node-management/tree/master/lnd.updates#update-lnd-to-v0101-beta

**Comment by nyxnor** [comment]
pls close this.
