### ISSUE TITLE
Raspberry 3.2 inch Display (waveShare) weird output

### ISSUE THREAD

**Issue by salihmech** [raspiblitz/raspiblitz#1283]
Good day all,

   I have been using a Raspberry 3.2 inch Display (waveShare) for a long time and have not had any issues since the beginning. My projects with raspi camera were working perfectly. Developed many projects with this configuration.

  One day after powering up the raspberry and seing the boot screen as usual, the screen unexpectedly showed weird output like seen in the picture once it reached to the desktop. 

The screen is always shifting to the left (about 20 pixels) with a certain frequency. The frequency is almost equal to fps. Colors are also inverting and going back to normal in sequence.

  I could not resolve it whatever I tried so finally decided image the SD card with a safe configuration and problem was gone.

  Now what makes me thoughtful is not being fully capable of understanding the possible reason and I picked the quick way to skip the problem but it just remains there, unresolved and always bearing a potential to strike back one day.

   I would appreciate any kind of help. My experience with Raspbery is only 1 year.

Note: Different programs yielded the same result. The problem looks independent of the program.
  
![image](https://user-images.githubusercontent.com/67318848/85395364-4782ff80-b550-11ea-9a0e-bd30b992e749.png)

**Comment by nyxnor** [comment]
Dependant on the screen. Please close this issue.
