### ISSUE TITLE
Use auto nat discover starting in lnd 0.5-beta

### ISSUE THREAD

**Issue by frennkie** [raspiblitz/raspiblitz#129]
This the same issue as Stadicus/guides#249

**Comment by rootzoll** [comment]
I followed your guide. Making new build and testing. Much thx.

**Comment by rootzoll** [comment]
On my testing it did not work and the lnd made a shutdown getting into a loop of unlock, shutdown, unlock, shutdown - so this setting is not godd as a default ... will put scripts to old state for now.

Maybe add an option later to activate this.

**Comment by frennkie** [comment]
Did you allow your Raspiblitz to create UPnP port forwardings..?

**Comment by rootzoll** [comment]
@frennkie the ufw rule "allow local LAN SSDP for UPnP discovery" is active - is that what you mean?

**Comment by frennkie** [comment]
The LND guys implemented this feature with a dependency... I don't know why.
The LND tries to configure the port forwarding on your Router (E. g. Fritzbox) of tcp port 9735 to your Raspiblitz.
If this does not succeed, then it won't use the external IP...

**Comment by rootzoll** [comment]
OK. For the next sd card release I will keep this feature off by default. Moving issue to version 1.0 milestone to at least make it an option to activate.

**Comment by frennkie** [comment]
> Moving issue to version 1.0 milestone to at least make it an option to activate.

Yes, makes sense.. also I forgot, that there is still an issue with the nat option: lightningnetwork/lnd#2014. 

LND will not re-create the port forwarding if - e.g. after a 24 hour DSL disconnect the port forwarding is no longer active on the router. I have been running the code in the PR for two weeks now and it's working fine. But I have to see how and when this can be merged into the official code.

**Comment by rootzoll** [comment]
@frennkie can you report on any progress on this issue with lnd?

For version 1.0 want to remember to put "auto nat discover" as an option into the service section, but deactivated by default for now.

**Comment by frennkie** [comment]
I have been occupied otherwise... From my point of view LND needs to be changed.. Not sure how fast such a change can be incorporated..

**Comment by rootzoll** [comment]
The plan for version 1.0 is to put the autonat option into the settings - so people can activate, test and play with it. 

TODO: test config script and settingsmenu

**Comment by rootzoll** [comment]
With the next sd card release the auto-nat feature can be switched on in the servcie section to experiment with. Closing this ticket for now.

**Comment by frennkie** [comment]
Fine with me. 

As long as the two PRs for lnd are not merge it would make sense to add some context/additional information for people who think about enabling the option.

**Comment by rootzoll** [comment]
If you write up two/three lines with additional info I can add it as an notice during the install process.
