### ISSUE TITLE
[Testing] LND wallet recovery cannot be exited 

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#1298]
Looping through:
![image](https://user-images.githubusercontent.com/43343391/85956870-a9909a00-b980-11ea-9db7-1c98a90a0f65.png)
![image](https://user-images.githubusercontent.com/43343391/85956874-b01f1180-b980-11ea-8b7c-64bb7ca17c68.png)
![image](https://user-images.githubusercontent.com/43343391/85956879-b614f280-b980-11ea-956c-3d6ba9e821d5.png)
![image](https://user-images.githubusercontent.com/43343391/85956881-bb723d00-b980-11ea-9346-2d9f960d50ca.png)

Solution: make `Cancel` functional

**Comment by openoms** [comment]
Also fails (on Odroid C4 - Ubuntu - pytton 3.8):
![image](https://user-images.githubusercontent.com/43343391/85957006-8dd9c380-b981-11ea-9616-50c4b810338c.png)
![image](https://user-images.githubusercontent.com/43343391/85957008-97632b80-b981-11ea-9628-1df0ed14c663.png)
![image](https://user-images.githubusercontent.com/43343391/85957019-a3e78400-b981-11ea-85de-e367759b527c.png)
![image](https://user-images.githubusercontent.com/43343391/85957031-ba8ddb00-b981-11ea-81ec-a2b40cc0e303.png)  
Pasted the 24words
![image](https://user-images.githubusercontent.com/43343391/85957056-f4f77800-b981-11ea-90fb-f5c64f0af1d4.png)
![image](https://user-images.githubusercontent.com/43343391/85957059-f9bc2c00-b981-11ea-9a9f-2b67ee343e3f.png)
![image](https://user-images.githubusercontent.com/43343391/85957063-06d91b00-b982-11ea-8258-7ac4e14a7bed.png)

**Comment by rootzoll** [comment]
OK should be fixed.
