### ISSUE TITLE
SCB: Local backup and timestamping

### ISSUE THREAD

**Issue by dennisreimann** [raspiblitz/raspiblitz#1302]
Just a question if these things are wanted, because I'd like to extend the background checks with the following:

* A `localBackupTarget` option (in addition to `scpBackupTarget`) to save the SCB file to a USB drive/stick
* Timestamp the backups, so that they do not get overwritten (e.g. `channel-20200630-061500.backup`)

**Comment by rootzoll** [comment]
> A localBackupTarget option (in addition to scpBackupTarget) to save the SCB file to a USB drive/stick

Good idea :)

> Timestamp the backups, so that they do not get overwritten (e.g. channel-20200630-061500.backup)

Would add more resellience and because a new file is not created that often should work for all backup targets. Its to be kept in mind that this also then has to work on the technical side, when people upload the channel.backup file again to the RaspiBlitz.

**Comment by dennisreimann** [comment]
Alright, I‘ll prepare a PR. Thanks for the pointer regarding the restore process. 👍

**Comment by rootzoll** [comment]
merged #1305 and done in #1309
