### ISSUE TITLE
Reactivate Option Zap Android/iOS over Tor

### ISSUE THREAD

**Issue by michaelWuensch** [raspiblitz/raspiblitz#1308]
Hi,

Zap Android only supports tor using gRPC. (it is just the iOS app that uses REST for tor)

Therefore the lndconnect string hast to use port 10009 when tor is activated.
Furthermore extraparameter="--nocert" should not be there. We need that cert.

Can you please adjust the lndconnectstring generation for tor on android

https://github.com/rootzoll/raspiblitz/blob/282d9c3139616c5d509c4787d50ecc3e64fdbcfe/home.admin/config.scripts/bonus.lndconnect.sh#L72-L73

**Comment by rootzoll** [comment]
OK this will be part of v1.6RC2 - please test once RC2 is out. Thanks.

**Comment by rootzoll** [comment]
OK Test with Zap iOS over TOR is now working again.
