### ISSUE TITLE
Using the main menu to shutdown while the blockchain is still synching

### ISSUE THREAD

**Issue by Kapot** [raspiblitz/raspiblitz#1310]
Hey,

As the synch take a long time I'm looking for a way to use the build-up shutdown option from the main menu when the synch is still in progress.

Yet you can only ctrl+c to the terminal, you cannot enter the main menu. Is there a command or way to safely shutdown the node while still in synch progress?

**Comment by rootzoll** [comment]
Yes the command from the terminal to safely shutdown is called `off`.
