### ISSUE TITLE
Password setup typo

### ISSUE THREAD

**Issue by ferologics** [raspiblitz/raspiblitz#1313]
During my setup I noticed that the dialog asks for Password B but title says "Password A"

<img width="941" alt="image" src="https://user-images.githubusercontent.com/5576161/86460041-fdf09c80-bd27-11ea-8fca-7a19f8ec2ea5.png">

**Comment by ferologics** [comment]
Fix in RP #1312

**Comment by rootzoll** [comment]
Thanks - merged :)
