### ISSUE TITLE
SSH Display changed. Lots of Qs and Xs

### ISSUE THREAD

**Issue by inpharmaticist** [raspiblitz/raspiblitz#1314]
I spun up a new node recently. The only things I've done with it are install electrs, stopping electrs, opening two channels, and adding two lines to the bitcoin.conf file (deprecatedrpc=size and peerbloomfilters=1).  This morning I noticed this.

![image](https://user-images.githubusercontent.com/49789899/86515684-9f7ef900-bdcf-11ea-90f4-cf4602682211.png)

**Comment by rootzoll** [comment]
@openoms do you have the details on how to change the charset on windows?

**Comment by frennkie** [comment]
@inpharmaticist can you test this: https://github.com/rootzoll/raspiblitz/issues/1200#issuecomment-636169777

**Comment by openoms** [comment]
It is the dialog program playing funny with Putty.
Would recommend using openssh from the windows store with PowerShell: https://github.com/rootzoll/raspiblitz/issues/1099

**Comment by inpharmaticist** [comment]
> It is the dialog program playing funny with Putty.
> Would recommend using openssh from the windows store with PowerShell: #1099

I wasn't using putty. I was using the terminal in linux mint, but it stopped on its own anyway.

**Comment by openoms** [comment]
check for any `.dialog` files in the `/home/admin/` dir. Can stay from an unclear shutdown. Should be back to the normal (default) settings if those are deleted.

**Comment by inpharmaticist** [comment]
Not seeing any.

![image](https://user-images.githubusercontent.com/49789899/86535908-88f0a480-be98-11ea-88df-50f3cbada05d.png)

**Comment by openoms** [comment]
> Not seeing any.

Use `ls -la` to show the hidden files.

**Comment by inpharmaticist** [comment]
Still no.

https://pastebin.com/caVVqbnE

**Comment by openoms** [comment]
Don't know where the problem is. Try another terminal app or device. Also flashing the sdcard should solve it if the problem is on the blitz filesystem.

**Comment by b-t-e** [comment]
Had the same issue with PuTTY since installing raspiblitz (1.7.0) a few weeks ago.
Fixed it today with these settings under Window | Translation:
- Remote character set: **UTF-8**
- Handling of line drawing characters: **Use Unicode line drawing code points**
- Enable VT100 line drawing even in UTF-8 mode: **ON**

![PuTTY Config](https://user-images.githubusercontent.com/87646149/130316007-0fdcb65c-604c-4104-ac5c-271bc6af56b6.PNG)
