### ISSUE TITLE
GermanShoppingList: PowerOutlet needs update

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#133]
I saw a "undervaltage report" on the new Poweroutlet of german shopping list. Test another one.

**Comment by dimarkov** [comment]
I've also noticed these warnings with the Homespot power adapter from the list.

**Comment by rootzoll** [comment]
OK - I changed the shopping list to another one - the "Rydges EU 5V 3A". Closing the ticket for now. Please report if any warning show up with that one. Thx.
