### ISSUE TITLE
LNBits wrong URL format

### ISSUE THREAD

**Issue by hermanlim** [raspiblitz/raspiblitz#1340]
At the moment, on Raspiblitz, attempting to add a wallet opens the wrong URL, one that is missing the correct port number. Insertion of the correct port number in the URL results in the correct behaviour.

Eg. 192.168.1.2:5001 opens LNBits Page. Entering wallet name 'test' wrongly opens https://192.168.1.2/wallet?usr=[...] when it should open https://192.168.1.2:5001/wallet?usr=[...]

Raspiblits 1.6RC2

**Comment by frennkie** [comment]
Please verify solution in already merged #1339.

**Comment by rootzoll** [comment]
Working on my test machine ... fix will be part of final v1.6 release.
