### ISSUE TITLE
Warn when node is using unsafe cltv_expiry_delta value (<18)

### ISSUE THREAD

**Issue by manreo** [raspiblitz/raspiblitz#1342]
See details here:
lightningnetwork/lightning-rfc#789
and here:
https://twitter.com/realtbast/status/1283298246983659520

I think it would be very efficient to the network if there is some way for raspiblitz to warn when the node has channels with cltv_expiry_delta lower than the recommended value (there are more than 7k such channels on mainnet)

**Comment by openoms** [comment]
We are using the LND defaults unless changed by the user.
I think the warning should be on GUIs like for example
ThunderHub does suggest to change low values on the `Details` page and gives a method to change the values individually or for all channels at the same time:
![image](https://user-images.githubusercontent.com/43343391/87659705-dbae4400-c755-11ea-801b-dd5ad3521285.png)
![image](https://user-images.githubusercontent.com/43343391/87659735-e49f1580-c755-11ea-97a0-2a7855e8aff0.png)

**Comment by manreo** [comment]
Great, I did not know that.
Maybe a warning can also be added on the main screen, it will be a shame if people will lose their money.

![image](https://user-images.githubusercontent.com/35897350/87688721-03ba9900-c790-11ea-8360-6381da25f066.png)

Thank you.

**Comment by nyxnor** [comment]
It is not supposed to be a Blitz command, but a service command, cant get displayed in the status screen, as it is already full of info now and not working currently. Also moving for the WebUI. Pls close this.
