### ISSUE TITLE
Adding Script: app-data/custom-installs.sh

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#1346]
see: https://github.com/rootzoll/raspiblitz/issues/1181#issuecomment-640880974

This script runs with sudo rights after an update/recovery from a fresh sd card.
This is the place to put all the install commands, cronjobs or editing of system configs 
for the users personal modifications of RaspiBlitz to be redone after upadate/recovery.

**Comment by adevoss** [comment]
Thanx! Nice. I will start to use it.

**Comment by adevoss** [comment]
Did you thought of the 'noexec' mount option in /etc/fstab?

Suggestion:
Add to _bootstrap_provision.sh:
cp -av /mnt/hdd/app-data/custom-install.sh /home/admin

Deleting 'noexec' option lowers security so not a good option IMO.

**Comment by rootzoll** [comment]
@adevoss Your correct - the script will now be copied over to /home/admin before running.

**Comment by rootzoll** [comment]
Works :) Closing issue.
