### ISSUE TITLE
Feature request: Confirm Reboot/PowerOff

### ISSUE THREAD

**Issue by adevoss** [raspiblitz/raspiblitz#1354]
When I wanted to reboot my Pi, in the menu I choose 'Reboot' and it just rebooted.
Exactly what it should do of course.

What about a confirmation: Are you sure? A mistake is easily made.

Same with 'Off' probably. Did not try that.

**Comment by frennkie** [comment]
Feel free to give this a try - sounds like a good "first issue" :-D

If you have the Touch User Interface enabled - I did implement a confirm dialog there. Might make sense to look at the wording and use something similar.

**Comment by adevoss** [comment]
My first issues were #1281 and #1297 but I will give it a try this weekend. Good third issue.
I don't have a screen but the Update/Patch menu has a lot of confirmation questions. So I'll take a look at that.

**Comment by rootzoll** [comment]
- [X] merge and adapt PR

**Comment by rootzoll** [comment]
tested and is working. closing issue.
