### ISSUE TITLE
Instructions on how to access the Fully Noded quick connect QR?

### ISSUE THREAD

**Issue by Fonta1n3** [raspiblitz/raspiblitz#1357]
Hi, I often get your users asking me how to connect their raspiblitz to Fully Noded, unfortunately I do not yet run a raspiblitz so have no clue..

Please can you supply me with basic instructions and ideally screen shots so I can add them to my docs and share it with your users when they ask.

Thank you!

**Comment by rootzoll** [comment]
Tor needs to be switched on on that node.
SSH-MAINMENU > FULLY_NODED ... and then follow the instructions.
- install from testflight
- run app & scan the pairing QR code displays on LCD or in terminal (ASCII-QR)

**Comment by Fonta1n3** [comment]
> Tor needs to be switched on on that node.
> 
> SSH-MAINMENU > FULLY_NODED ... and then follow the instructions.
> 
> - install from testflight
> 
> - run app & scan the pairing QR code displays on LCD or in terminal (ASCII-QR)

Thanks for the info, will add it to our docs.

Fwiw the App Store version is definitely where you should be pointing people, Testflight is not updated/utilized for FN. https://apps.apple.com/us/app/fully-noded/id1436425586

**Comment by rootzoll** [comment]
@Fonta1n3 I updated the AppStore link. Thx. Will be part of the v1.6 release.

**Comment by nyxnor** [comment]
Please close this issue.
