### ISSUE TITLE
ip2tor: limit retries when PO (order) is rejected

### ISSUE THREAD

**Issue by frennkie** [raspiblitz/raspiblitz#1360]
When a RaspiBlitz IP2TOR Subscription is rejected the client will currently try to renew it anyway continuously:

![image](https://user-images.githubusercontent.com/6499251/87858667-d278cf00-c92f-11ea-9bca-bf9cf2ce158b.png)

**Comment by rootzoll** [comment]
Ah OK ... will add this to client.

**Comment by rootzoll** [comment]
@frennkie ok this should be fixed .. please check if you see this again with RC3

**Comment by frennkie** [comment]
@rootzoll Please be aware that I added some more status options the the Purchase Orders and the Bridges:

* https://github.com/frennkie/django-ip2tor/blob/master/charged/lnpurchase/models.py#L26
* https://github.com/frennkie/django-ip2tor/blob/master/shop/models.py#L378

As far as I see it you have not been using them so far and I didn't do any *breaking* changes when adding the additional codes... so just FYI.
