### ISSUE TITLE
How to run Ethereum node on Raspberry Pi 4 ?

### ISSUE THREAD

**Issue by godas14** [raspiblitz/raspiblitz#1362]
Hello Sir,

Please make a script and instructions for starting the Ethereum 2.0 node on Raspberry Pi 4

**Comment by rootzoll** [comment]
You can build a script that would add such a node, but personally I cannot see that it would be a good fit with the rest of the software stack that is specialized to work around bitcoin & lightning. But if you really want it, do it and let us know.

**Comment by openoms** [comment]
Is Eth 2.0 a thing or is this a troll question?

**Comment by nyxnor** [comment]
Pls close this, eth reverting to -2.0.
