### ISSUE TITLE
IP address not detected in amd64 VM

### ISSUE THREAD

**Issue by adevoss** [raspiblitz/raspiblitz#1364]
When running _bootstrap.sh the IP address is not detected and the loop is endless.
gotLocalIP never becomes 1

OS: Debian Buster amd64
Network interface: ens3
IP address: 192.x.x.x

I don't know a solution right now that works for all setups.

**Comment by adevoss** [comment]
Files involved:
_bootstrap.sh and blitz.statusscan.sh

**Comment by rootzoll** [comment]
Is this still with the RC3?

**Comment by adevoss** [comment]
Yes. Tested yesterday. Working on a pr.
ens3 isn't a common network interface name.

**Comment by rootzoll** [comment]
PR merged ... please test if it now works for you.

**Comment by adevoss** [comment]
Already tested before submitting pr. :smiley:

**Comment by nyxnor** [comment]
Pr merged and tested as mentioned above, pls close this.
