### ISSUE TITLE
switch testnet -> main; missing RTL changes

### ISSUE THREAD

**Issue by frennkie** [raspiblitz/raspiblitz#1365]
I just switched a node from testnet to mainnet. There are at least two RTL issue:

* [config update](https://github.com/rootzoll/raspiblitz/blob/22d26e8d5900d65633565c81d8a13389edb99bee/home.admin/config.scripts/network.chain.sh#L87 )

* systemd file

**Comment by nyxnor** [comment]
Frennkie, please close this issue if solved.

**Comment by openoms** [comment]
PR incoming  to rework RTL working on parallel networks together with LND and c-lightning

**Comment by openoms** [comment]
Fixing in: https://github.com/openoms/raspiblitz/commit/e3c758fa825d07d95ced8c4b56f5387799515308
