### ISSUE TITLE
Downloading image times out

### ISSUE THREAD

**Issue by torkelrogstad** [raspiblitz/raspiblitz#137]
Trying to open https://wiki.fulmo.org/downloads/raspiblitz-2018-09-22.img.gz results in a timeout.

**Comment by geco91** [comment]
This is an old sd card image - the newest one is https://wiki.fulmo.org/downloads/raspiblitz-2018-10-20.img.gz

**Comment by geco91** [comment]
@rootzoll proposed ticket to be closed

**Comment by torkelrogstad** [comment]
Sure! It was in the Readme when I opened the issue, but I see it's replaced now.
