### ISSUE TITLE
Research: sphinx.chat

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#1376]
Check if you can get https://sphinx.chat app running with your RaspiBlitz ... is there an option to connect your own node?

**Comment by gcomte** [comment]
Might be valuable: https://github.com/stakwork/sphinx-relay/blob/master/install_guide_myNode_and_Raspiblitz.md

**Comment by Juized** [comment]
https://github.com/stakwork/sphinx-relay/blob/master/docs/raspiblitz_deployment.md

**Comment by rootzoll** [comment]
Integrated already in v1.6.2 :)
