### ISSUE TITLE
LNBIts/IP2Tor

### ISSUE THREAD

**Issue by normandmickey** [raspiblitz/raspiblitz#1377]
Tried to test LNUrlW using IP2Tor.  Was able to create and fund wallet and withdrawal link.  However i get the attached error when trying to receive sats using Breez wallet.
![Screenshot_20200723-214356_Breez](https://user-images.githubusercontent.com/2455566/88354301-75658a80-cd2e-11ea-8f20-e70ae8035e92.jpg)

**Comment by rootzoll** [comment]
Try to add LetsEncrypt (with a duckdns domain) to LBbits. Its now in 1.6RC3 for testing under subscriptions.

**Comment by normandmickey** [comment]
Thanks, that worked! 

https://liab-blitz.duckdns.org:38950/withdraw/JCHJNhKySd7sdoNk5Gosmn
