### ISSUE TITLE
Update README & FAQs, set Version and Release.

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#1380]
TODO list for final v1.6 release:
- [X] Move Whats New FAQ section in a CHANGES file
- [X] Update README to fit all the new menus and features.
- [X] Clean FAQ from old/outdated features.
- [X] Set Version to 1.6.0
- [X] Fix the DuckDNS URL call bug
- [X] Create singned Release sd card image & upload
- [X] Create torrent for SD card image and ask people to redistribute
- [X] Make last test of image with updating own node
- [X] Last Test of IP2TOR
- [X] Merge into Master
- [X] Tag GitHub Repo
- [X] Announce new Version on twitter

**Comment by APItudeProduct** [comment]
A bit off-topic, but is there a preview image for us impatient ones? XD

**Comment by vmavromatis** [comment]
Is there maybe a preview image for us impatient ones? XD
