### ISSUE TITLE
Static IP address before starting setup

### ISSUE THREAD

**Issue by xpsx** [raspiblitz/raspiblitz#1381]
Hello, iam new here and new to RaspberryPi and Linux.
i don't have an DHCP server on my private network, and i choose all addresses manually, how can i assign an IP address,subnetmask and gateway to Raspiblitz? is there a configurfation file like the WIFI that i can use?
thank you very much

**Comment by rootzoll** [comment]
Thats part of the RaspberryPi ... so you can use any tutorial on the net that describes "How to set a static ip on the RaspberryPi".

**Comment by adevoss** [comment]
Edit file `/etc/dhcpcd.conf` (uncomment the Example static IP configuration part)
