### ISSUE TITLE
QR code not a compatible url (iOS)

### ISSUE THREAD

**Issue by xpsx** [raspiblitz/raspiblitz#1383]
Hello,

iam running full node over Tor, and i can't connect via QR code with Zap or Fully Noded, format not supported or not a compatible url.
what should i do?
thanks

**Comment by xpsx** [comment]
the qr codes in SSH are for appstore

**Comment by rootzoll** [comment]
Yeah those might be a bit confusing ... hope UX on this will get better once we have a WebUI.
