### ISSUE TITLE
Question: Install Raspiblitz on normal amd64 PC?

### ISSUE THREAD

**Issue by maltokyo** [raspiblitz/raspiblitz#1386]
I have an old PC, can I use it instead of a Pi?  I am looking for a tutorial on this, but cannot find, thank you!
(sorry if this is the wrong place to ask, if it is, just redirect me please!)

**Comment by openoms** [comment]
Not tested or supported, but worth a try. Will likely need some custom work. Be ready to debug and modify some scripts.
Here are the rough principles:
https://github.com/rootzoll/raspiblitz/tree/master/alternative.platformsare 
Flash a compatible image to the USB drive (not a disk - need to use an equivalent to the SDcard on the RPi).
So set up Debian or Ubuntu to a USB. Boot and run the build_sdcard.sh.
The scripts will format the internal SSD for the blockchain and data.
From there you will need to figure out.
It helps if you run an RPI4 node so you know how it should work.

**Comment by maltokyo** [comment]
Thank you. @openoms  The reason I asked is because I heard you on the Stephan Livera podcast, and there you mentioned that it could be installed on an old PC.  At least that's how I heard it ;)

**Comment by openoms** [comment]
Yes it certainly can, most of the install scripts are written to support 32 and 64 bit ARM and 64bit x86.
Testing is not fully done on other boards than the RPi4 (and 3) because of lack of interest.
Any custom setup can be standardised once someone wants to work on it and share the results.

**Comment by maltokyo** [comment]
Great. Will try!

**Comment by adevoss** [comment]
See https://github.com/rootzoll/raspiblitz/pull/1297.
Drive names (/dev/sdXn) can be different. Check if /etc/fstab is valid after executing build_sdcard.sh. It is modified by the script.
If it is not valid the PC won't boot (happened to me, make backup first)

I tested my pr on a amd64 vm (Debian)
- install Debian (other Linux distro will do I think)
- install and configure sudo if not already installed
- execute: `sudo ./build_sdcard.sh` 
- not used it as a node after first installation

**Comment by openoms** [comment]
the amd64 install  is working now, see: https://github.com/rootzoll/raspiblitz/tree/dev/alternative.platforms and
 https://github.com/rootzoll/raspiblitz/pull/3052
