### ISSUE TITLE
./00infoBlitz.sh: 4: ./00infoBlitz.sh: source: not found

### ISSUE THREAD

**Issue by Smiggel** [raspiblitz/raspiblitz#139]
I used the script to build my node. It's up and running, but when using the terminal and selecting the option "Info". I get to see the error:./00infoBlitz.sh: 4: ./00infoBlitz.sh: source: not found.

The file it refers to does exists however in the same location.

**Comment by rootzoll** [comment]
It seemed that you catched an in between commit when build - sorry thats due to my not working on development forks yet ... will do after version 1.0

for source to work in 00infoBlitz.sh it needs to be a bash script with starting: #!/bin/bash ... its already changed in the actual code.

**Comment by Smiggel** [comment]
Ok, thanks!
