### ISSUE TITLE
Changing to LTC Chain and back

### ISSUE THREAD

**Issue by hermanlim** [raspiblitz/raspiblitz#1390]
Is there a script/menu option to change to LTC (and back to BTC) after one has set up the Raspiblitz (like how one can change from mainnet BTCto testnet BTC and back again)? 

From what I can see, the only way is during setup time.

**Comment by rootzoll** [comment]
You choose BTC or LTC at the beginning ... there is no option to switch while running.

**Comment by hermanlim** [comment]
Is this deliberately designed this way to avoid fund loss? Is it inherently risky to change post setup?

**Comment by rootzoll** [comment]
Its because we cannot test any bonus application how they would work with such a (unsusual) change under the hood. It would be a lot of testing on every release for a edge use case.
