### ISSUE TITLE
Missing Blocks from Torrent file?

### ISSUE THREAD

**Issue by inpharmaticist** [raspiblitz/raspiblitz#1398]
I'm troubleshooting some issues I was having with a previous node and decided to redownload the blockchain torrent. The torrents completed and synced up to the current block but it looks like a lot of really old blocks are missing. I think I saw a step of the torrent download that checks a has of the file and it passed so I'm wondering if there is something wrong with the index or blockchain files. This is a new samsung SSD, so I'd be surprised if there was something wrong with the drive. 

![image](https://user-images.githubusercontent.com/49789899/89093366-8c2f6100-d36e-11ea-992c-b8e7d33dfd3c.png)

**Comment by rootzoll** [comment]
Tanks for the report .. but downloading the blockchain thru torrent will be gone with v1.6 anyway. See for details: https://github.com/rootzoll/raspiblitz/issues/1179
