### ISSUE TITLE
Update to: Specter v0.8.1

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#1411]
see https://github.com/rootzoll/raspiblitz/issues/1171#issuecomment-669027062 from #1171

**Comment by ben-kaufman** [comment]
Hi, in case you haven't started with this yet, there's version 0.6.1 which contains a few bug fixes and would be nice to have instead.

https://github.com/cryptoadvance/specter-desktop/releases/tag/v0.6.1

**Comment by rootzoll** [comment]
@ben-kaufman thx, havent yet 0.6.1 sounds good :)

**Comment by rootzoll** [comment]
Also merged PR #1481 to add missing library

**Comment by ChuckNorrison** [comment]
Here we go :)
https://github.com/cryptoadvance/specter-desktop/releases/tag/v0.7.2

**Comment by rootzoll** [comment]
Update PR merged - moving to final testing.

**Comment by openoms** [comment]
Specter 0.8.0 is out:
https://github.com/cryptoadvance/specter-desktop/releases/tag/v0.8.0

Update successfully with the UPDATE menu (available in the latest script for RaspiBlitz v1.6.1)

I suggest we should ship with the latest version by default.

**Comment by openoms** [comment]
​Update from Specter v0.5.5 in RaspiBlitz v1.6 paste these command to the RaspiBlitz terminal:
```
#uninstall old version
config.scripts/bonus.cryptoadvance-specter.sh off
# install the missing dependency
sudo apt install -y libffi-dev
# change script to use the latest version
sed -i "s#cryptoadvance.specter==*#cryptoadvance.specter==0.8.1#g"  /home/admin/config.scripts/bonus.cryptoadvance-specter.sh
```
Install Specter from the SERVICES

Edit: updated to v0.8.1

**Comment by rootzoll** [comment]
Update Bug Reported: https://github.com/rootzoll/raspiblitz/pull/1566#issuecomment-699681734

**Comment by rootzoll** [comment]
@openoms merged #1619 ... did you found any hint of the bug mentioned above while testing.

**Comment by openoms** [comment]
Nope, but I am way past of updating from 0.5.5. 
There were no errors installing v0.8.0 or 0.8.1. Update works too.

**Comment by openoms** [comment]
We could probably add this entry to the bitcoin.conf:
![image](https://user-images.githubusercontent.com/43343391/95376083-77c09500-08d8-11eb-83f2-8596aa04bbb0.png)

Should bring some performance gains and have enough space on the 1TB drives.
Any concerns?

checking how long it takes, just started now on my RPi4 4GB + SSD:
```
$ sudo cat  /mnt/hdd/bitcoin/debug.log | grep "block filter"
2020-10-07T19:00:12Z * Using 111.8 MiB for basic block filter index database
2020-10-07T19:00:54Z basic block filter index thread start
2020-10-07T19:00:54Z Syncing basic block filter index with block chain from height 0
2020-10-07T19:01:25Z Syncing basic block filter index with block chain from height 6824
...
2020-10-07T19:03:32Z Syncing basic block filter index with block chain from height 15584
```

**Comment by openoms** [comment]
Was about 10 hours in the background rescanning a couple wallets simultaneously. 
```
sudo cat  /mnt/hdd/bitcoin/debug.log | grep "block filter"
2020-10-07T19:00:12Z * Using 111.8 MiB for basic block filter index database
2020-10-07T19:00:54Z basic block filter index thread start
2020-10-07T19:00:54Z Syncing basic block filter index with block chain from height 0
...
2020-10-08T05:15:31Z basic block filter index is enabled at height 651757
2020-10-08T05:15:31Z basic block filter index thread exit
```
Once activated the warning from Specter is gone, so does not need much explanation I think. 

Takes 5.5 GB now:
```
sudo du -hd 2 /mnt/hdd/bitcoin/
91M	/mnt/hdd/bitcoin/blocks/index
321G	/mnt/hdd/bitcoin/blocks
3.9G	/mnt/hdd/bitcoin/chainstate
28G	        /mnt/hdd/bitcoin/indexes/txindex
5.5G	/mnt/hdd/bitcoin/indexes/blockfilter
```

**Comment by rootzoll** [comment]
All funtions of Specter run OK while the additional index is building ... or do we need a info in the status menu, that the "index is still building"?

**Comment by openoms** [comment]
I did not find any problems while building the index as it works without as well only slightly slower. The warning disappears probably because it is looking in the bitcoin.conf.
Will ask quickly in the Specter TG to be sure.

**Comment by rootzoll** [comment]
OK merged the Specter-BlockfilterIndex PR ... installs fine so far. I am see this testing OK. @openoms if you dont get any contradicting info from the specter TG then I will close this issue for the v1.6.1 release.

**Comment by openoms** [comment]
they said there should be no issue while indexing. Specter queries the bitcoind RPC for everything, that should be able to deal with it.

**Comment by rootzoll** [comment]
OK perfect .. closing this issue for v.16.1 release.
