### ISSUE TITLE
Update instructions are not clear

### ISSUE THREAD

**Issue by xpsx** [raspiblitz/raspiblitz#1417]
Hello,
I don’t understand how to update correctly from 1.5.1 to 1.6
I have only one Micro SD card which is inside, when i went to update page, i read that i need to download and flash the Micro SD card then press next, so my question is: do i need another Micro SD card? Or i can safely remove the Micro SD card while I’m in the update page?
Or do i need to shutdown the raspiblitz and overwrite the micro SD card?
Any help would be appreciated.

PS: i have only one Micro SD card

**Comment by Smiggel** [comment]
Just press update. After that you can download a backup for critical files. Then you see the following:

>  If you start the update: The RaspiBlitz will power down.   │ 
                                                            │ Once the LCD is white and no LEDs are blicking anymore:    │ 
                                                            │                                                            │ 
                                                            │ - Remove the Power from RaspiBlitz                         │ 
                                                            │ - Exchange the old with the new SD card                    │ 
                                                            │ - Connect Power back to the RaspiBlitz                     │ 
                                                            │ - Follow the instructions on the LCD                       │ 
                                                            │                                                            │ 
                                                            │ Do you have the SD card with the new version image ready   │ 
                                                            │ and do you WANT TO START UPDATE NOW?
