### ISSUE TITLE
Image does not boot on a Pi2

### ISSUE THREAD

**Issue by Smiggel** [raspiblitz/raspiblitz#142]
Does anyone else have this issue? The disk light on pi turns a few times in the beginning and then it stops. I fails to boot.

Is this, because I am trying the image on a pi 2?

**Comment by charlesrocket** [comment]
image is for 64bit, pi2 and previous hardware are 32bit

**Comment by Smiggel** [comment]
Hmmm ok. Didn’t know that. Thanks.
