### ISSUE TITLE
BTC Explorer not loading after update 1.5.3 to 1.6.0

### ISSUE THREAD

**Issue by Smiggel** [raspiblitz/raspiblitz#1421]
I noticed that when BTC Explorer runs on the old version of Raspiblitz, it does not work after upgrading to 1.6.0. I did see in the logs that it was installed and enabled, but the webinterface is not accessible.

I removed BTC Explorer using the menu, and re-installed it using the menu and then it works.

**Comment by rootzoll** [comment]
As candle reported there was an outage at NPM .. future versions will make better "error detection" on the installs to notify the user on it: #1419

**Comment by rootzoll** [comment]
Just tested the install of the Explorer again and it all looks good. Closing issue.
