### ISSUE TITLE
Joinmarket watch order book locally w/ Tor enabled

### ISSUE THREAD

**Issue by woeisme** [raspiblitz/raspiblitz#1425]
When installing local orderbook service on joinmarket and tor is enabled the following dialogue is blank:
![image](https://user-images.githubusercontent.com/1057395/89715017-28baba00-d992-11ea-8cad-3f3bfd5c3268.png)

**Comment by woeisme** [comment]
Additional information from ob-watcher
![image](https://user-images.githubusercontent.com/1057395/89715026-438d2e80-d992-11ea-849e-cfd3ef0a1b41.png)

**Comment by rootzoll** [comment]
@openoms ?

**Comment by openoms** [comment]
try to run:
`pip3 install matplotlib`
at the prompt: ` (jmvenv) joinmarket`
the install is quite lengthy and might fail.
Will look into it.

**Comment by openoms** [comment]
The output should be improved, but the ob-watcher works for me.
@woeisme exit the log screen with CTRL+C and select the `OFFERS` option again. 
It should show you the Hidden Service address for you own Offer Book.

Here is my one tested:
`gopnmsknawlntb4qpyav3q5ejvvk6p74a7y5xotmph4v64wl3wicscad.onion`

**Comment by openoms** [comment]
Also might be related: https://github.com/JoinMarket-Org/joinmarket-clientserver/issues/657#issuecomment-669344536
Can try 
`sudo apt-get install libopenjp2-7 libtiff5`
if not solved when selecting the `OFFERS` option in the menu again.

**Comment by woeisme** [comment]
Hey @openoms 

I followed your instructions, this time it displays an onion address correctly, but visiting that address with Tor Browser shows 'Unable to connect'. 

Next page after that is the complaint page about missing matplotlib again. 

Trying:

 `sudo apt-get install libopenjp2-7 libtiff5`

resulted in: 

```
sudo apt-get install libopenjp2-7 libtiff5
Reading package lists... Done
Building dependency tree
Reading state information... Done  
libopenjp2-7 is already the newest version (2.3.0-2+deb10u1).  
libtiff5 is already the newest version (4.1.0+git191117-2~deb10u1).  
The following package was automatically installed and is no longer required:  
  libbluetooth3  
Use 'sudo apt autoremove' to remove it.  
```

Still not showing offers however.

**Comment by openoms** [comment]
can you try the manual instructions?

https://github.com/openoms/bitcoin-tutorials/tree/master/joinmarket#run-the-offer-book-locally

Not sure if I can reproduce the problem.

**Comment by woeisme** [comment]
using:
`sudo apt-get install python-matplotlib`

seems to have installed it, however running `python ob-watcher.py` either from cli or from within the menu still fails at detecting it is installed.

**Comment by openoms** [comment]
@woeisme it is not supposed to be a system package.
Matplotlib is installed with pip in the `jmvenv`.
uninstall from the system:
`sudo apt-get remove python-matplotlib`

And install it in the `jmvenv` (when in the `joinmarket` user) with: 
`pip install matplotlib`

**Comment by openoms** [comment]
@woeisme reworked the `OFFERS` in JoininBox to fix the above problems.
You can use the `UPDATE` option to get to the latest master.

**Comment by woeisme** [comment]
I had attempted the pip install of matplotlib earlier with no success.

Went into main Raspiblitz service menu, removed joinmarket then reinstalled. 
Switched to joinmarket user ssh session, First selected Update, then Offers -> Start (start watching locally) which installed matplotlib successfully. 
Order book now loads locally.

**Comment by openoms** [comment]
Great, thank you for reporting!
