### ISSUE TITLE
Incorrect password instruction for Specter

### ISSUE THREAD

**Issue by shawnyeager** [raspiblitz/raspiblitz#1430]
Per instructions, below, user is to use Password B, whereas Password A is what successfully logged me in.

<img width="542" alt="Screen Shot 2020-08-10 at 8 44 59 AM" src="https://user-images.githubusercontent.com/980297/89789546-59ac0380-dae6-11ea-9bd8-bade8c2e120e.png">

**Comment by rootzoll** [comment]
@shawnyeager Thanks for the report ... wil recheck for update release v1.6.1

**Comment by rootzoll** [comment]
OK I just rechecked with the lastest code for v1.6.1 release ... it is password B for specter login.

Last check before closing the issue: Test on a fresh setuped RaspiBlitz with test v1.6.1 code

**Comment by rootzoll** [comment]
OK found some smaller bugs to fix on fnal testing: #1642 .. but Specter looks good now and used all the correct passwordB on tests. Closing this issue for v1.6.1 release.
