### ISSUE TITLE
lnbits inaccessible post-install via `raspiblitz` menu [release 1.6]

### ISSUE THREAD

**Issue by shawnyeager** [raspiblitz/raspiblitz#1431]
After installing and seeing confirmation with URL, etc., the service is inaccessible, producing the following:

```
502 Bad Gateway
nginx/1.14.2
```

**Comment by rootzoll** [comment]
@shawnyeager can you try to reinstall LNbits (turn off and on in services)

**Comment by shawnyeager** [comment]
Good call. That did the trick. Thanks!
