### ISSUE TITLE
Incorrect password instruction for BTC-RPC-Explorer [release 1.6.1]

### ISSUE THREAD

**Issue by shawnyeager** [raspiblitz/raspiblitz#1434]
User is instructed to use Password B, but Password A is required.

<img width="485" alt="btc-rpc-raspi" src="https://user-images.githubusercontent.com/980297/89850035-77618300-db4f-11ea-9210-df41ed077add.png">

**Comment by rootzoll** [comment]
@shawnyeager I checked ... it should be password B ... I found a bug that if you change password B afterwards some other passwords on apps dont get changed. So could it be that you had in the beginning the same password A as B and then changed B?

**Comment by shawnyeager** [comment]
@rootzoll Ah, interesting. I set all passwords (using 1Password's generator) at time time of install, and have not changed. For whatever reason, I've only ever been able to login to web services with Password A.

**Comment by rootzoll** [comment]
Can you take a look into your bitcoin conf and just let me know that there is really your password B (and not your Password A that maybe got entered during setup becaue of a copy paste hickup). Todo so ... go to Terminal and run:
`sudo cat /mnt/hdd/bitcoin/bitcoin.conf` and verify whats set for `rpcpassword`.

**Comment by rootzoll** [comment]
Seems related: https://github.com/rootzoll/raspiblitz/issues/1445

**Comment by rootzoll** [comment]
I just tested again ... its Password B as instructed. Closing issue for v1.6.1 release.
