### ISSUE TITLE
cosmetic: remove trailing '/' from localBackupDir in _background.sh to prevent '...//...'

### ISSUE THREAD

**Issue by PatrickScheich** [raspiblitz/raspiblitz#1451]
the local variable `localBackupDir` in file `_background.sh` has a trailing `/`. 
This leads to `/home/admin/backups/scb//channel.backup` for the subsequent variable `localBackupPath=${localBackupDir}/channel.backup`

change from 
```
localBackupDir=/home/admin/backups/scb/
```
to
```
localBackupDir=/home/admin/backups/scb
```

**Comment by rootzoll** [comment]
Thanks - will be part of v1.6.1 service release.

- [x] testing SCB backup again

**Comment by rootzoll** [comment]
OK SCB backup to USB drive is working still fine. This will be part of v1.6.1 - closing issue.
