### ISSUE TITLE
Cancelling autounlock from menu fails [v1.6]

### ISSUE THREAD

**Issue by shawnyeager** [raspiblitz/raspiblitz#1458]
I was looking through the config options in menu, selected lnd autounlock, then, after being prompted to store the password on-device, selected `cancel`. The process continued anyway, confirming that autounlock is now active.

**Comment by rootzoll** [comment]
Good find - will check the "CANCEL" option on that dialog for the next v1.6.1 service release.

**Comment by ChuckNorrison** [comment]
cancel button in reboot dialogue will also result in a reboot and not cancel

**Comment by rootzoll** [comment]
@ChuckNorrison checked the reboot dialog on SSH main menu and it respects my cancel.
@shawnyeager found the problem in the auto-unlock cancel. Will be fixed in v1.6.1

**Comment by rootzoll** [comment]
OK Testing works. Will be part of v1.6.1 release .. closing issue.
