### ISSUE TITLE
Lnd not starting after updating to v1.6 

### ISSUE THREAD

**Issue by syracusebitcoin** [raspiblitz/raspiblitz#1461]
Hey i just updated to V1.6 and Lnd is not starting. Here is the debug log if anyone might be able to help me figure out what i messed up. please and thank you.

blitzversion: 1.6.0
chainnetwork: bitcoin / main
 23:26:29 up 12 min,  3 users,  load average: 1.03, 1.40, 0.95

*** BLOCKCHAIN SYSTEMD STATUS ***
● bitcoind.service - Bitcoin daemon
   Loaded: loaded (/etc/systemd/system/bitcoind.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2020-08-17 23:23:03 BST; 3min 26s ago
  Process: 11192 ExecStartPre=/home/admin/config.scripts/blitz.systemd.sh log blockchain STARTED (code=exited, status=0/SUCCESS)
  Process: 11194 ExecStart=/usr/local/bin/bitcoind -daemon -conf=/home/bitcoin/.bitcoin/bitcoin.conf -pid=/home/bitcoin/.bitcoin/bitcoind.pid (code=exited, status=0/SUCCESS)
 Main PID: 11195 (bitcoind)
    Tasks: 18 (limit: 4915)
   Memory: 256.3M
   CGroup: /system.slice/bitcoind.service
           └─11195 /usr/local/bin/bitcoind -daemon -conf=/home/bitcoin/.bitco…

Aug 17 23:23:03 raspberrypi systemd[1]: bitcoind.service: Can't open PID …tory
Aug 17 23:23:03 raspberrypi systemd[1]: Started Bitcoin daemon.
Hint: Some lines were ellipsized, use -l to show in full.

*** LAST BLOCKCHAIN ERROR LOGS ***
sudo journalctl -u bitcoind -b --no-pager -n8
-- Logs begin at Mon 2020-08-17 23:13:40 BST, end at Mon 2020-08-17 23:26:29 BST. --
Aug 17 23:18:11 raspberrypi systemd[1]: Starting Bitcoin daemon...
Aug 17 23:18:11 raspberrypi systemd[1]: Started Bitcoin daemon.
Aug 17 23:22:46 raspberrypi systemd[1]: Stopping Bitcoin daemon...
Aug 17 23:22:48 raspberrypi systemd[1]: bitcoind.service: Succeeded.
Aug 17 23:22:48 raspberrypi systemd[1]: Stopped Bitcoin daemon.
Aug 17 23:23:02 raspberrypi systemd[1]: Starting Bitcoin daemon...
Aug 17 23:23:03 raspberrypi systemd[1]: bitcoind.service: Can't open PID file /home/bitcoin/.bitcoin/bitcoind.pid (yet?) after start: No such file or directory
Aug 17 23:23:03 raspberrypi systemd[1]: Started Bitcoin daemon.

*** LAST BLOCKCHAIN 20 INFO LOGS ***
sudo tail -n 20 /mnt/hdd/bitcoin/debug.log
2020-08-17T22:26:19Z connect() to 127.0.0.1:9050 failed after select(): Connection refused (111)
2020-08-17T22:26:20Z connect() to 127.0.0.1:9050 failed after select(): Connection refused (111)
2020-08-17T22:26:20Z connect() to 127.0.0.1:9050 failed after select(): Connection refused (111)
2020-08-17T22:26:21Z connect() to 127.0.0.1:9050 failed after select(): Connection refused (111)
2020-08-17T22:26:21Z connect() to 127.0.0.1:9050 failed after select(): Connection refused (111)
2020-08-17T22:26:22Z connect() to 127.0.0.1:9050 failed after select(): Connection refused (111)
2020-08-17T22:26:22Z connect() to 127.0.0.1:9050 failed after select(): Connection refused (111)
2020-08-17T22:26:23Z connect() to 127.0.0.1:9050 failed after select(): Connection refused (111)
2020-08-17T22:26:23Z connect() to 127.0.0.1:9050 failed after select(): Connection refused (111)
2020-08-17T22:26:24Z connect() to 127.0.0.1:9050 failed after select(): Connection refused (111)
2020-08-17T22:26:24Z connect() to 127.0.0.1:9050 failed after select(): Connection refused (111)
2020-08-17T22:26:25Z connect() to 127.0.0.1:9050 failed after select(): Connection refused (111)
2020-08-17T22:26:25Z connect() to 127.0.0.1:9050 failed after select(): Connection refused (111)
2020-08-17T22:26:26Z connect() to 127.0.0.1:9050 failed after select(): Connection refused (111)
2020-08-17T22:26:26Z connect() to 127.0.0.1:9050 failed after select(): Connection refused (111)
2020-08-17T22:26:27Z connect() to 127.0.0.1:9050 failed after select(): Connection refused (111)
2020-08-17T22:26:27Z connect() to 127.0.0.1:9050 failed after select(): Connection refused (111)
2020-08-17T22:26:28Z connect() to 127.0.0.1:9050 failed after select(): Connection refused (111)
2020-08-17T22:26:28Z connect() to 127.0.0.1:9050 failed after select(): Connection refused (111)
2020-08-17T22:26:29Z connect() to 127.0.0.1:9050 failed after select(): Connection refused (111)

*** LND SYSTEMD STATUS ***
● lnd.service - LND Lightning Daemon
   Loaded: loaded (/etc/systemd/system/lnd.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2020-08-17 23:26:04 BST; 24s ago
  Process: 12929 ExecStartPre=/home/admin/config.scripts/blitz.systemd.sh log lightning STARTED (code=exited, status=0/SUCCESS)
  Process: 12931 ExecStart=/usr/local/bin/lnd --tor.active --tor.streamisolation --tor.v3 --listen=127.0.0.1:9735 ${lndExtraParameter} (code=exited, status=1/FAILURE)
 Main PID: 12931 (code=exited, status=1/FAILURE)

*** LAST LND ERROR LOGS ***
sudo journalctl -u lnd -b --no-pager -n12
-- Logs begin at Mon 2020-08-17 23:13:40 BST, end at Mon 2020-08-17 23:26:29 BST. --
Aug 17 23:25:03 raspberrypi systemd[1]: Started LND Lightning Daemon.
Aug 17 23:25:04 raspberrypi lnd[11910]: dial tcp 127.0.0.1:9050: connect: connection refused
Aug 17 23:25:04 raspberrypi systemd[1]: lnd.service: Main process exited, code=exited, status=1/FAILURE
Aug 17 23:25:04 raspberrypi systemd[1]: lnd.service: Failed with result 'exit-code'.
Aug 17 23:26:04 raspberrypi systemd[1]: lnd.service: Service RestartSec=1min expired, scheduling restart.
Aug 17 23:26:04 raspberrypi systemd[1]: lnd.service: Scheduled restart job, restart counter is at 9.
Aug 17 23:26:04 raspberrypi systemd[1]: Stopped LND Lightning Daemon.
Aug 17 23:26:04 raspberrypi systemd[1]: Starting LND Lightning Daemon...
Aug 17 23:26:04 raspberrypi systemd[1]: Started LND Lightning Daemon.
Aug 17 23:26:04 raspberrypi lnd[12931]: dial tcp 127.0.0.1:9050: connect: connection refused
Aug 17 23:26:04 raspberrypi systemd[1]: lnd.service: Main process exited, code=exited, status=1/FAILURE
Aug 17 23:26:04 raspberrypi systemd[1]: lnd.service: Failed with result 'exit-code'.

*** LAST 30 LND INFO LOGS ***
sudo tail -n 30 /mnt/hdd/lnd/logs/bitcoin/mainnet/lnd.log

*** LAST NGINX LOGS ***
sudo journalctl -u nginx -b --no-pager -n20
-- Logs begin at Mon 2020-08-17 23:13:40 BST, end at Mon 2020-08-17 23:26:29 BST. --
-- No entries --
--> CHECK CONFIG: sudo nginx -t
sudo: nginx: command not found

*** LAST 20 TOUCHSCREEN LOGS ***
sudo tail -n 20 /home/pi/.cache/lxsession/LXDE-pi/run.log
** Message: 23:14:33.580: app.vala:76: Launching /usr/bin/ssh-agent 
SSH_AUTH_SOCK=/tmp/ssh-yBR5kUsWloJY/agent.883; export SSH_AUTH_SOCK;
SSH_AGENT_PID=887; export SSH_AGENT_PID;
echo Agent pid 887;
** Message: 23:14:33.656: app.vala:130: xset exit with this type of exit: 0
** Message: 23:14:33.657: app.vala:139: Exit normal, don't reload
** Message: 23:14:33.657: app.vala:130: xset exit with this type of exit: 0
** Message: 23:14:33.657: app.vala:139: Exit normal, don't reload
** Message: 23:14:33.657: app.vala:130: xset exit with this type of exit: 0
** Message: 23:14:33.657: app.vala:139: Exit normal, don't reload
** Message: 23:14:33.657: app.vala:130: /usr/bin/ssh-agent exit with this type of exit: 0
Traceback (most recent call last):
  File "/home/admin/python3-env-lnd/bin/blitz-tui", line 6, in <module>
    from blitztui.main import main
  File "/home/admin/python3-env-lnd/lib/python3.7/site-packages/blitztui/main.py", line 17, in <module>
    from PyQt5.QtCore import Qt, QProcess, QThread, pyqtSignal, QCoreApplication, QTimer, QEventLoop
ModuleNotFoundError: No module named 'PyQt5'
** Message: 23:14:33.758: app.vala:130: sh exit with this type of exit: 256
** Message: 23:14:33.758: app.vala:145: Exit normal, don't reload
Openbox-Message: Unable to find a valid menu file "/usr/share/lxde/openbox/menu.xml"

*** LAST 20 LOOP LOGS ***
sudo journalctl -u loopd -b --no-pager -n20
-- Logs begin at Mon 2020-08-17 23:13:40 BST, end at Mon 2020-08-17 23:26:29 BST. --
Aug 17 23:23:32 raspberrypi systemd[11375]: loopd.service: Changing to the requested working directory failed: No such file or directory
Aug 17 23:23:32 raspberrypi systemd[11375]: loopd.service: Failed at step CHDIR spawning /usr/local/gocode/bin/loopd: No such file or directory
Aug 17 23:23:32 raspberrypi systemd[1]: loopd.service: Main process exited, code=exited, status=200/CHDIR
Aug 17 23:23:32 raspberrypi systemd[1]: loopd.service: Failed with result 'exit-code'.
Aug 17 23:24:33 raspberrypi systemd[1]: loopd.service: Service RestartSec=1min expired, scheduling restart.
Aug 17 23:24:33 raspberrypi systemd[1]: loopd.service: Scheduled restart job, restart counter is at 8.
Aug 17 23:24:33 raspberrypi systemd[1]: Stopped Loopd Service.
Aug 17 23:24:33 raspberrypi systemd[1]: Started Loopd Service.
Aug 17 23:24:33 raspberrypi systemd[11718]: loopd.service: Changing to the requested working directory failed: No such file or directory
Aug 17 23:24:33 raspberrypi systemd[11718]: loopd.service: Failed at step CHDIR spawning /usr/local/gocode/bin/loopd: No such file or directory
Aug 17 23:24:33 raspberrypi systemd[1]: loopd.service: Main process exited, code=exited, status=200/CHDIR
Aug 17 23:24:33 raspberrypi systemd[1]: loopd.service: Failed with result 'exit-code'.
Aug 17 23:25:33 raspberrypi systemd[1]: loopd.service: Service RestartSec=1min expired, scheduling restart.
Aug 17 23:25:33 raspberrypi systemd[1]: loopd.service: Scheduled restart job, restart counter is at 9.
Aug 17 23:25:33 raspberrypi systemd[1]: Stopped Loopd Service.
Aug 17 23:25:33 raspberrypi systemd[1]: Started Loopd Service.
Aug 17 23:25:33 raspberrypi systemd[12064]: loopd.service: Changing to the requested working directory failed: No such file or directory
Aug 17 23:25:33 raspberrypi systemd[12064]: loopd.service: Failed at step CHDIR spawning /usr/local/gocode/bin/loopd: No such file or directory
Aug 17 23:25:33 raspberrypi systemd[1]: loopd.service: Main process exited, code=exited, status=200/CHDIR
Aug 17 23:25:33 raspberrypi systemd[1]: loopd.service: Failed with result 'exit-code'.

*** LAST 20 RTL LOGS ***
sudo journalctl -u RTL -b --no-pager -n20
-- Logs begin at Mon 2020-08-17 23:13:40 BST, end at Mon 2020-08-17 23:26:29 BST. --
-- No entries --

*** LAST 20 ElectRS LOGS ***
sudo journalctl -u electrs -b --no-pager -n20
-- Logs begin at Mon 2020-08-17 23:13:40 BST, end at Mon 2020-08-17 23:26:29 BST. --
Aug 17 23:23:32 raspberrypi systemd[11374]: electrs.service: Changing to the requested working directory failed: No such file or directory
Aug 17 23:23:32 raspberrypi systemd[11374]: electrs.service: Failed at step CHDIR spawning /home/electrs/electrs/target/release/electrs: No such file or directory
Aug 17 23:23:32 raspberrypi systemd[1]: electrs.service: Main process exited, code=exited, status=200/CHDIR
Aug 17 23:23:32 raspberrypi systemd[1]: electrs.service: Failed with result 'exit-code'.
Aug 17 23:24:33 raspberrypi systemd[1]: electrs.service: Service RestartSec=1min expired, scheduling restart.
Aug 17 23:24:33 raspberrypi systemd[1]: electrs.service: Scheduled restart job, restart counter is at 8.
Aug 17 23:24:33 raspberrypi systemd[1]: Stopped Electrs.
Aug 17 23:24:33 raspberrypi systemd[1]: Started Electrs.
Aug 17 23:24:33 raspberrypi systemd[11719]: electrs.service: Changing to the requested working directory failed: No such file or directory
Aug 17 23:24:33 raspberrypi systemd[11719]: electrs.service: Failed at step CHDIR spawning /home/electrs/electrs/target/release/electrs: No such file or directory
Aug 17 23:24:33 raspberrypi systemd[1]: electrs.service: Main process exited, code=exited, status=200/CHDIR
Aug 17 23:24:33 raspberrypi systemd[1]: electrs.service: Failed with result 'exit-code'.
Aug 17 23:25:33 raspberrypi systemd[1]: electrs.service: Service RestartSec=1min expired, scheduling restart.
Aug 17 23:25:33 raspberrypi systemd[1]: electrs.service: Scheduled restart job, restart counter is at 9.
Aug 17 23:25:33 raspberrypi systemd[1]: Stopped Electrs.
Aug 17 23:25:33 raspberrypi systemd[1]: Started Electrs.
Aug 17 23:25:33 raspberrypi systemd[12063]: electrs.service: Changing to the requested working directory failed: No such file or directory
Aug 17 23:25:33 raspberrypi systemd[12063]: electrs.service: Failed at step CHDIR spawning /home/electrs/electrs/target/release/electrs: No such file or directory
Aug 17 23:25:33 raspberrypi systemd[1]: electrs.service: Main process exited, code=exited, status=200/CHDIR
Aug 17 23:25:33 raspberrypi systemd[1]: electrs.service: Failed with result 'exit-code'.

*** ElectRS Status ***
##### STATUS ELECTRS SERVICE
configured=1
serviceInstalled=1
serviceRunning=0
tipSynced=0
initialSynced=0
electrumResponding=0
infoSync='Not running - check: sudo journalctl -u electrs'

*** LAST 20 BTCPayServer LOGS ***
sudo journalctl -u btcpayserver -b --no-pager -n20
-- Logs begin at Mon 2020-08-17 23:13:40 BST, end at Mon 2020-08-17 23:26:30 BST. --
-- No entries --

*** LAST 20 LNbits LOGS ***
sudo journalctl -u lnbits -b --no-pager -n20
-- Logs begin at Mon 2020-08-17 23:13:40 BST, end at Mon 2020-08-17 23:26:30 BST. --
Aug 17 23:24:03 raspberrypi systemd[11558]: lnbits.service: Changing to the requested working directory failed: No such file or directory
Aug 17 23:24:03 raspberrypi systemd[11558]: lnbits.service: Failed at step CHDIR spawning /bin/sh: No such file or directory
Aug 17 23:24:03 raspberrypi systemd[1]: lnbits.service: Main process exited, code=exited, status=200/CHDIR
Aug 17 23:24:03 raspberrypi systemd[1]: lnbits.service: Failed with result 'exit-code'.
Aug 17 23:24:33 raspberrypi systemd[1]: lnbits.service: Service RestartSec=30s expired, scheduling restart.
Aug 17 23:24:33 raspberrypi systemd[1]: lnbits.service: Scheduled restart job, restart counter is at 9.
Aug 17 23:24:33 raspberrypi systemd[1]: Stopped lnbits.
Aug 17 23:25:03 raspberrypi systemd[1]: Started lnbits.
Aug 17 23:25:03 raspberrypi systemd[11911]: lnbits.service: Changing to the requested working directory failed: No such file or directory
Aug 17 23:25:03 raspberrypi systemd[11911]: lnbits.service: Failed at step CHDIR spawning /bin/sh: No such file or directory
Aug 17 23:25:03 raspberrypi systemd[1]: lnbits.service: Main process exited, code=exited, status=200/CHDIR
Aug 17 23:25:03 raspberrypi systemd[1]: lnbits.service: Failed with result 'exit-code'.
Aug 17 23:25:33 raspberrypi systemd[1]: lnbits.service: Service RestartSec=30s expired, scheduling restart.
Aug 17 23:25:33 raspberrypi systemd[1]: lnbits.service: Scheduled restart job, restart counter is at 10.
Aug 17 23:25:33 raspberrypi systemd[1]: Stopped lnbits.
Aug 17 23:26:04 raspberrypi systemd[1]: Started lnbits.
Aug 17 23:26:04 raspberrypi systemd[12932]: lnbits.service: Changing to the requested working directory failed: No such file or directory
Aug 17 23:26:04 raspberrypi systemd[12932]: lnbits.service: Failed at step CHDIR spawning /bin/sh: No such file or directory
Aug 17 23:26:04 raspberrypi systemd[1]: lnbits.service: Main process exited, code=exited, status=200/CHDIR
Aug 17 23:26:04 raspberrypi systemd[1]: lnbits.service: Failed with result 'exit-code'.

*** LAST 20 Thunderhub LOGS ***
sudo journalctl -u thunderhub -b --no-pager -n20
-- Logs begin at Mon 2020-08-17 23:13:40 BST, end at Mon 2020-08-17 23:26:30 BST. --
Aug 17 23:24:03 raspberrypi systemd[11563]: thunderhub.service: Changing to the requested working directory failed: No such file or directory
Aug 17 23:24:03 raspberrypi systemd[11563]: thunderhub.service: Failed at step CHDIR spawning /usr/bin/npm: No such file or directory
Aug 17 23:24:03 raspberrypi systemd[1]: thunderhub.service: Main process exited, code=exited, status=200/CHDIR
Aug 17 23:24:03 raspberrypi systemd[1]: thunderhub.service: Failed with result 'exit-code'.
Aug 17 23:24:33 raspberrypi systemd[1]: thunderhub.service: Service RestartSec=30s expired, scheduling restart.
Aug 17 23:24:33 raspberrypi systemd[1]: thunderhub.service: Scheduled restart job, restart counter is at 9.
Aug 17 23:24:33 raspberrypi systemd[1]: Stopped ThunderHub daemon.
Aug 17 23:25:03 raspberrypi systemd[1]: Started ThunderHub daemon.
Aug 17 23:25:03 raspberrypi systemd[11912]: thunderhub.service: Changing to the requested working directory failed: No such file or directory
Aug 17 23:25:03 raspberrypi systemd[11912]: thunderhub.service: Failed at step CHDIR spawning /usr/bin/npm: No such file or directory
Aug 17 23:25:03 raspberrypi systemd[1]: thunderhub.service: Main process exited, code=exited, status=200/CHDIR
Aug 17 23:25:03 raspberrypi systemd[1]: thunderhub.service: Failed with result 'exit-code'.
Aug 17 23:25:33 raspberrypi systemd[1]: thunderhub.service: Service RestartSec=30s expired, scheduling restart.
Aug 17 23:25:33 raspberrypi systemd[1]: thunderhub.service: Scheduled restart job, restart counter is at 10.
Aug 17 23:25:33 raspberrypi systemd[1]: Stopped ThunderHub daemon.
Aug 17 23:26:04 raspberrypi systemd[1]: Started ThunderHub daemon.
Aug 17 23:26:04 raspberrypi systemd[12933]: thunderhub.service: Changing to the requested working directory failed: No such file or directory
Aug 17 23:26:04 raspberrypi systemd[12933]: thunderhub.service: Failed at step CHDIR spawning /usr/bin/npm: No such file or directory
Aug 17 23:26:04 raspberrypi systemd[1]: thunderhub.service: Main process exited, code=exited, status=200/CHDIR
Aug 17 23:26:04 raspberrypi systemd[1]: thunderhub.service: Failed with result 'exit-code'.

*** LAST 20 SPECTER LOGS ***
sudo journalctl -u cryptoadvance-specter -b --no-pager -n20
-- Logs begin at Mon 2020-08-17 23:13:40 BST, end at Mon 2020-08-17 23:26:30 BST. --
-- No entries --

*** MOUNTED DRIVES ***
Filesystem     Type     1K-blocks      Used Available Use% Mounted on
/dev/root      ext4      30450024   3483680  25679288  12% /
devtmpfs       devtmpfs   1966332         0   1966332   0% /dev
tmpfs          tmpfs      2000124         0   2000124   0% /dev/shm
tmpfs          tmpfs      2000124      8692   1991432   1% /run
tmpfs          tmpfs         5120         4      5116   1% /run/lock
tmpfs          tmpfs      2000124         0   2000124   0% /sys/fs/cgroup
tmpfs          tmpfs        32768         0     32768   0% /var/cache/raspiblitz
/dev/mmcblk0p1 vfat        258095     52246    205849  21% /boot
/dev/sda1      ext4     960322016 442473136 468997456  49% /mnt/hdd
tmpfs          tmpfs       400024         0    400024   0% /run/user/1000
tmpfs          tmpfs       400024         0    400024   0% /run/user/1001

*** WIFI Info ***
activated=0
connected=0
localip=''

*** HARDWARE TEST RESULTS ***
UndervoltageReports in Logs: 0
raspberryPi=4
powerFAIL=0
powerWARN=0
powerMIN='862500 microVolt'
tempFAIL=11
tempWARN=15
tempMAX='8000 centiGrad'
IMPORTANT: There are some hardware issues with your setup.
'Run Hardwaretest' in main menu or: sudo /home/admin/05hardwareTest.sh

*** SYSTEM STATUS (can take some seconds to gather) ***
localIP='192.168.0.13'
tempCelsius='72.0'
uptime=761
upsStatus='OFF'
startcountBlockchain=3
bitcoinActive=1
blockchainHeight=644184
initialSync=0
syncProgress=100.00 
startcountLightning=11
lndActive=0
blitzTUIActive=1
blitzTUIRestarts=0
scriptRuntime=1

**Comment by ChuckNorrison** [comment]
this system lost a lot of stuff in this upgrade.

> sudo: nginx: command not found

Someone who got some backup experience should check this out

**Comment by rootzoll** [comment]
@openoms and @frennkie I start to see a pattern here ... a lot of bug reports lately have todo with "installs not running correctly" lets talk next week how we can improve this maybe thru pre-packaging apt-get, pip and npm depencendies on the sd card - this would also make the RaspiBlitz better suitable for areas with flaky, costly or low-bandwidth internet.

@syracusebitcoin if possible send me a copy of your `/home/admin/raspiblitz.recover.log` to christian@fulmo.org and then try an update again with a fresh sd card that hopefully this time all dependecies get loaded and installed correctly.

**Comment by syracusebitcoin** [comment]
Hello everyone. Thanks for the help. @rootzoll the problem was indeed a bad SD card. I recently got a new one, re-flashed the img and it seems to be working fine for the most part. There seem to be a few kinks here and there but I think with a little bit of research I can fix these issues. Again thanks everyone for the help.
