### ISSUE TITLE
Blockchain started syncing then got 'Service bitcoind is not running' message

### ISSUE THREAD

**Issue by kbholden** [raspiblitz/raspiblitz#1462]
Debug report for 'Service bitcoind is not running' message

admin@raspberrypi:~ $ /home/admin/XXdebugLogs.sh | nc termbin.com 9999
tail: error reading '/mnt/hdd/lnd/logs/bitcoin/mainnet/lnd.log': Input/output error
nginx: [emerg] BIO_new_file("/mnt/hdd/app-data/nginx/tls.cert") failed (SSL: error:02001005:system library:fopen:Input/output error:fopen('/mnt/hdd/app-data/nginx/tls.cert','r') error:2006D002:BIO routines:BIO_new_file:system lib)
nginx: configuration file /etc/nginx/nginx.conf test failed
/home/admin/config.scripts/blitz.statusscan.sh: line 4: /mnt/hdd/raspiblitz.conf: Input/output error
/home/admin/config.scripts/blitz.ups.sh: line 4: /mnt/hdd/raspiblitz.conf: Input/output error
https://termbin.com/1u3g

**Comment by ChuckNorrison** [comment]
seems your nginx is missing his tls.cert? you can try to repair in menu your certificates

oh and your bitcoin directory seems to have insufficient permissions. maybe it needs a chown and some chmod on this

> Aug 18 02:31:14 raspberrypi bitcoind[22260]: Error: Cannot write to data directory '/home/bitcoin/.bitcoin'; check permissions.

thats what it looks on my system right now:

> admin@raspberrypi:/home/bitcoin $ ls -laht
> total 24K
> drwxr-xr-x 10 root    root    4.0K Aug 15 18:12 ..
> drwxr-xr-x  3 bitcoin bitcoin 4.0K Aug 11 19:39 .
> lrwxrwxrwx  1 bitcoin bitcoin   12 Aug 11 19:39 .lnd -> /mnt/hdd/lnd
> lrwxrwxrwx  1 bitcoin bitcoin   17 Aug 11 19:39 .litecoin -> /mnt/hdd/litecoin
> lrwxrwxrwx  1 bitcoin bitcoin   16 Aug 11 19:39 .bitcoin -> /mnt/hdd/bitcoin
> drwx------  3 bitcoin bitcoin 4.0K Aug 11 14:43 .gnupg
> -rw-r--r--  1 bitcoin bitcoin  220 Jul 16 22:16 .bash_logout
> -rw-r--r--  1 bitcoin bitcoin 3.5K Jul 16 22:16 .bashrc
> -rw-r--r--  1 bitcoin bitcoin  807 Jul 16 22:16 .profile

so we need a symlink to our external hdd to the bitcoin workspace. maybe this got lost in your system.

i dont know the best way to solve this without loosing anything

**Comment by rootzoll** [comment]
@kbholden bitcoind AND lnd do not run correctly. Something went bad during install. If this is a fresh install I would recommend to start fresh: Format HDD/SSD on laptop and start again with fresh sd card image. If this is after an update: Shutdown and reboot with a fresh sd card again.

**Comment by nyxnor** [comment]
Pls close this.
