### ISSUE TITLE
Moving from 2TB HDD to 1TB SSD

### ISSUE THREAD

**Issue by bitsam** [raspiblitz/raspiblitz#1468]
Hey experts, I would like to migrate the raspiblitz HDD to an SSD, however my node is currently using a 2TB HDD and from what I have read the current process to migrate from HDD to SSD advises to have the same capacity or larger target drive. Is it possible to migrate to a smaller drive?

I also want to move from a Pi3 to Pi4, If you could advise the best method for both the HDD to SSD & Pi3 to Pi4 migration with a limited interruption?

Many thanks
Sam

**Comment by rootzoll** [comment]
To move data between hard drives we have the "MIGRATION" options. It will package all the important data into a zip for doenload and then you setup a fresh RaspiBLitz with the new HDD7SSD and you import that migration file. But you have to copy/sync the blockchain again.

see for details: https://github.com/rootzoll/raspiblitz/blob/master/README.md#import-a-migration-file
