### ISSUE TITLE
3,5 lcd does not turn off

### ISSUE THREAD

**Issue by jadolph** [raspiblitz/raspiblitz#147]
distupgrade and rpi-update were successfully completed

`ls: cannot access '/sys/class/backlight/rpi_backlight/bl_power': No such file or directory`

**Comment by geco91** [comment]
To control the LCD look at the files in /home/admin/LCD-show and at the waveshare wiki https://www.waveshare.com/wiki/3.5inch_RPi_LCD_(A)

@rootzoll Because this is not part of the actual feature set of the RaspiBlitz at the moment closing the ticket is proposed for now.
