### ISSUE TITLE
Canceling out of 'Change Passwords' fails [v1.6]

### ISSUE THREAD

**Issue by shawnyeager** [raspiblitz/raspiblitz#1482]
I selected `Change Passwords` from the raspiblitz menu, then selected `RPC Password`, as I intended to change from a non-alphanumeric-only password. I then double-checked, realized it was alphanumeric, and selected `<Cancel>`. This fails, insisting that the password field be filled. The only way out is to close the terminal window.

**Comment by rootzoll** [comment]
Like with #1458 .. will check the CANCEL option again for v1.6.1

**Comment by rootzoll** [comment]
found the problem in the auto-unlock cancel. Will be fixed in v1.6.1

**Comment by rootzoll** [comment]
Tested working. Will be part of v1.6.1 release - closing issue.
