### ISSUE TITLE
Update: ThunderHub 0.9.15

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#1487]
PR #1463 updated to v0.9.4

**Comment by Marcoblue** [comment]
At the moment 0.9.15 is the newest version. In 0.8.12 are some errors, that are fixed in newer ones.

**Comment by rootzoll** [comment]
@openoms there is already a 0.9.14 tagged ... should be update before release?

**Comment by openoms** [comment]
Yes, not aware of any problems, but there is always something added 👍

**Comment by rootzoll** [comment]
Updated to 0.9.15 and install looks OK

**Comment by rootzoll** [comment]
Installed fine on final testing. Update will be part of v1.6.1 - closing issue.
