### ISSUE TITLE
Update: JoinMarket v0.7.1 (with joininbox menu v0.1.11) 

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#1488]
working to refactor the update script
The challenge is to use system-site-packages in the jmvenv virtual env to keep the QT GUI working from the blitz.

**Comment by rootzoll** [comment]
merged PR - setting for final testing

**Comment by rootzoll** [comment]
Install on final testing is working. Will be part of v1.6.1 release. Closing issue.

**Comment by openoms** [comment]
JoinMarket v0.7.1 is released, just testing installation. Could not find significant differences in dependencies.

**Comment by openoms** [comment]
Installation is tested ok. 
The changes with payjoin will need modifications in the joininbox menu: https://github.com/openoms/joininbox/issues/15
but basic functionality (running the Yield generator and walllet generation and info) is working.

**Comment by openoms** [comment]
To update JoinMarket separately can use this much improved script:
```
# download from this repo
wget https://raw.githubusercontent.com/rootzoll/raspiblitz/v1.6/home.admin/config.scripts/bonus.joinmarket.sh
# uninstall old version (wallets are preserved on the disk)
sudo bash bonus.joinmarket.sh off
# install with the latest updates
sudo bash bonus.joinmarket.sh on
```

**Comment by rootzoll** [comment]
OK install seems to work - rest is up to you @openoms to test on Release Candidate. Will be part of v1.6.1 - closing this issue.
