### ISSUE TITLE
fail2ban ssh authentications based on systemd

### ISSUE THREAD

**Issue by ChuckNorrison** [raspiblitz/raspiblitz#1495]
After fail2ban and ubuntu gets updated, it needs to be set to backend=systemd to work as expected

`sudo nano jail.conf`

find backend and set from auto to systemd. 

`sudo systemctl restart fail2ban`

Now we can check for authentication failures on our ssh port with:

`sudo fail2ban-client status sshd`

You can check this behaviour here:
https://github.com/fail2ban/fail2ban/issues/1379#issuecomment-679965811

A file named **jail.local** can be written to **/etc/fail2ban** to make it work:

> [DEFAULT]
> bantime = 1d
> backend = systemd

I also increased the bantime from 10 minutes to 1 day

**Comment by rootzoll** [comment]
Thanks - marked this for v1.7 release. 1 day might be a bit much ... more than once I was shutting myself out by typing the wrong password for the wrong raspi. 1 day is maybe a bit much .. 1 h I would see a max to still keep it practical.

**Comment by ChuckNorrison** [comment]
1h is still great. For me its easy task to log from another machine to remove my ip ban manually, but for new users it could be a mess... maybe a whitelist entry from local network could be possible to avoid selfbans and only check for authentications from unknown

so this will help in the .conf or .local file:

```
[DEFAULT]
# "ignoreip" can be an IP address, a CIDR mask or a DNS host. Fail2ban will not                          
# ban a host which matches an address in this list. Several addresses can be                             
# defined using space separator.
                                                                         
ignoreip = 127.0.0.1 192.168.1.0/24
```

**Comment by freerko** [comment]
stumbled upon this issue looking for the current fail2ban setting of raspiblitz because I tried a wrong password too often. Please don't increase it even further, 10min should be more than enough to prevent brute-force attacks via SSH. 
Adding private networks 10.0.0.0/8, 172.16.0.0/12 and 192.168.0.0/16 to the ignore list would be very helpful as well.

**Comment by rootzoll** [comment]
I am not sure about whitelisting local networks ... there are too many smart devices nowadays in your local network. But yeah 10min should be enough ... I just recently banned myself by using wrong password on wrong machine. Even the 10min wait was bad enough ... and should be fine for practical reasons.
