### ISSUE TITLE
[Feature Request] Add Umbrel

### ISSUE THREAD

**Issue by grnqrtr** [raspiblitz/raspiblitz#1503]
I just started reading through this blog/tutorial: https://freedomnode.com/blog/how-to-setup-umbrel-to-work-with-an-existing-bitcoind-and-lnd/

It is described as "hacky" but tells you how to add umbrel to an existing bitcoind and lnd instance. I think it would be cool to have this clean/stylish web browser dashboard included in raspiblitz.

**Comment by rootzoll** [comment]
Its something that could be worth looking into. For a future RaspiBlitz v1.8 it on our idea list to add some kind of WebUI for RaspiBlitz ... so why not offer the Umbrel-Dashboard (RaspiBlitz Edition) for that. May have to contact the Umbrel dev team on that at one point to see if they would be cool with that.

The RaspiBlitz would need the same WebAPI for that. Those has two parts:
- umbrel-manager (API calls special to the node) --> https://github.com/getumbrel/umbrel-manager
- umbrel-middleware (API calls as wrapper for LND & Bitcoind) --> https://github.com/getumbrel/umbrel-middleware

Both run on NodeJS, not my favorite choice for a core part of RaspiBlitz - a rewrite of those APIs using python+fastapi would be something to consider.

**Comment by nyxnor** [comment]
"Nice" license Umbrel, very nice.
