### ISSUE TITLE
Refresh PGP signing key

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#1517]
and refresh on keybase. 

![Bildschirmfoto 2020-09-08 um 17 53 29](https://user-images.githubusercontent.com/2472225/92499640-66fb0180-f1fc-11ea-8dba-a59804ae4a64.png)

**Comment by rootzoll** [comment]
The add Signature again - lika last release:
```
SHA-256: bf8f70cf3a6d87d1b786936306ae092b6350be22f0c19c3a06171450178594ca or [SIGNATURE](https://raspiblitz.org/raspiblitz-v1.6-2020-08-04.img.gz.sig)
```

**Comment by openoms** [comment]
@rootzoll can we get a signature for the v1.6.1 image please?

**Comment by rootzoll** [comment]
OK uploaded and updated public key on keybase with extended expire.
