### ISSUE TITLE
LNURL Fallback support in mobile wallets

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#1518]
Example: https://twitter.com/rootzoll/status/1303359479162056705?s=20

- Make a list of LN mobile wallets to check LNURL Fallback is working.
- Ask not supporting wallets to add support.
- Make PR to https://github.com/fiatjaf/awesome-lnurl#wallets

**Comment by frennkie** [comment]
Where should that Twitter notification link point to..? :-D

**Comment by rootzoll** [comment]
corrected link

**Comment by michaelWuensch** [comment]
Just for your interest, I added support in Zap Android. Will be shipped with the next version.

**Comment by rootzoll** [comment]
OK I tested with Zap-iOS and if I scan (under 'send') a plain LNURL QR code it is recognizing the LNURL ... but if I scan a LNURL fallback scheme I get a 'Unvalid Address Format' error.

**Comment by rootzoll** [comment]
Asked for shockwallet here: https://github.com/shocknet/wallet/issues/300

**Comment by rootzoll** [comment]
Tried to test lntxbot with an LNURL generated from lnbits.com ... when I was putting the LNURL into a fallback-scheme URL its was not working, while the plain LNURL string worked:
![Bildschirmfoto 2020-10-17 um 19 42 22](https://user-images.githubusercontent.com/2472225/96349873-ad246a00-10b2-11eb-8b25-2dfbd2d76ea3.png)

**Comment by rootzoll** [comment]
Tried LNbits ... if I add a LNURL in the "Paste Request" form and it works. But it failes with a fallback URI - like this:

![Bildschirmfoto 2020-10-17 um 20 04 22](https://user-images.githubusercontent.com/2472225/96350185-d34b0980-10b4-11eb-82a9-17398b06f61a.png)

The response by LNbits is:

![Bildschirmfoto 2020-10-17 um 20 08 47](https://user-images.githubusercontent.com/2472225/96350193-e231bc00-10b4-11eb-97b9-ee9b386a0011.png)

**Comment by rootzoll** [comment]
On coinos.io entering a LNURL on "send" works, but a LNURL fallback scheme is rejected like this:
![Bildschirmfoto 2020-10-17 um 20 15 49](https://user-images.githubusercontent.com/2472225/96350423-fde99200-10b5-11eb-87e8-7faa82eaeff6.png)

**Comment by rootzoll** [comment]
Breez wallet was able to scan plain LNURL QR codes ... but failed on LNURL fallback-scheme with "QR code cannot be processed" warning (both on android & ios) - on this example: 
![Bildschirmfoto 2020-10-17 um 21 32 06](https://user-images.githubusercontent.com/2472225/96352021-69d0f800-10c0-11eb-8aa0-db0fa8d58bc2.png)

**Comment by rootzoll** [comment]
Tested BluWallet with a plain LNURL QR code worked - BUT LNURL fallback scheme failed (closing scan without response) - for example:

![Bildschirmfoto 2020-10-17 um 22 22 35](https://user-images.githubusercontent.com/2472225/96352893-7442c000-10c7-11eb-8df6-5a3b13ed4713.png)

**Comment by rootzoll** [comment]
Zeus (just tested Android, but asume iOS is the same) its recognizing the LNURL fallback scheme - all good :)

**Comment by rootzoll** [comment]
BLW worked both - LNUR plain & with fallback-scheme.

**Comment by rootzoll** [comment]
Blixt Wallet was able to scan a plain LNURL but falied on LNURL fallback-scheme with 'QR sav errer: Code is not a valid Lightning invoice'.

**Comment by fiatjaf** [comment]
Please give your support! https://github.com/hsjoberg/blixt-wallet/pull/246

**Comment by rootzoll** [comment]
Opened also issue on Breez wallet: https://github.com/breez/breezmobile/issues/381

**Comment by rootzoll** [comment]
ShockWallet is welcoming a PR and might take a look at it:
https://github.com/shocknet/wallet/issues/300

**Comment by fiatjaf** [comment]
Another one here: https://github.com/BlueWallet/BlueWallet/pull/1993

**Comment by fiatjaf** [comment]
ShockWallet here: https://github.com/shocknet/wallet/pull/302

**Comment by fiatjaf** [comment]
It does work on https://t.me/lntxbot if you just paste the LNURL string directly (or take a picture of a QR code) without the command. I think I must improve documentation to make it explicit that you don't need to write commands when pasting invoices or lnurls.

**Comment by fiatjaf** [comment]
Here is an attempt at Breez: https://github.com/breez/breez/pull/127

**Comment by rootzoll** [comment]
So it really looks good now - I think we can close this issue already for v1.6.2 release:
![Bildschirmfoto 2020-11-11 um 16 07 10](https://user-images.githubusercontent.com/2472225/98828760-bf3ac380-2438-11eb-9b20-295ec3d9c3e7.png)

Last on my list is Zap for iOS ... I think sending this reminder is all we can do.
https://twitter.com/rootzoll/status/1326542471875104768?s=20
