### ISSUE TITLE
nginx service failing to run on boot

### ISSUE THREAD

**Issue by SecretSatoshis** [raspiblitz/raspiblitz#1537]
I was am having an issue accessing BTCPayServer via Tor &/or http on boot. I am running v1.6.0.

After running  - sudo systemctl status nginx

I get the error: 
Starting A high performance web server and a reverse proxy server...
nginx: [emerg] a duplicate listen [::1]:23002 in /etc/nginx/sites-enabled/btcpay_tor.conf:5
nginx: configuration file /etc/nginx/nginx.conf test failed
nginx.service: Control process exited, code=exited, status=1/FAILURE
nginx.service: Failed with result 'exit-code'.
Failed to start A high performance web server and a reverse proxy server.

After running -sudo service nginx restart my issue is resolved and I can connect to my BTCPayServer instance. I am unsure why the service is not running at the start.

**Comment by rootzoll** [comment]
Will retest BTCPayServer install for v1.6.1 release.

**Comment by rootzoll** [comment]
Also because of this merge: https://github.com/rootzoll/raspiblitz/pull/1539

**Comment by rootzoll** [comment]
@TrueFlow I tested again for the v1.6.1 release and on my machine the BTCPay is running after a reboot from the beginning. Is this happening on your machine after every reboot or just after the first boot after the update?

**Comment by rootzoll** [comment]
The merge #1539 looks fine .... marked for final testing.

**Comment by frennkie** [comment]
@TrueFlow can you run this command and paste the output:

```
grep 2300 /etc/nginx/sites-available/*
```

**Comment by syracusebitcoin** [comment]
I am running into this error too. my raspiblitz needed to reboot and after the reboot I can no longer log into BTCPay server, Thunderhub, or LNbits from my lan connection.

**Comment by rootzoll** [comment]
OK tested BTCPay server for v1.6.1 release ... all testings look good. Closingt this issue.
