### ISSUE TITLE
Updating bitcoind version

### ISSUE THREAD

**Issue by adolfosrs** [raspiblitz/raspiblitz#156]
I want to update my raspiblitz bitcoind version from `v0.16.2` to `v0.17.0` but a bit scary of screwing it. What would be the best way without having to remount my SD card?

Would running the following be enough?

```
bitcoinVersion="0.17.0"
sudo -u admin wget https://bitcoin.org/bin/bitcoin-core-${bitcoinVersion}/bitcoin-${bitcoinVersion}-arm-linux-gnueabihf.tar.gz
sudo -u admin tar -xvf bitcoin-${bitcoinVersion}-arm-linux-gnueabihf.tar.gz
sudo install -m 0755 -o root -g root -t /usr/local/bin bitcoin-${bitcoinVersion}/bin/*
```

**Comment by mr-dakota** [comment]
Check the FAQ from the Raspibolt guide, there is a section on updating that is useful for the Raspiblitz too: https://github.com/Stadicus/guides/blob/master/raspibolt/raspibolt_faq.md

You will need to stop the LND and Bitcoin system units before you update.

```
$ sudo systemctl stop lnd
$ sudo systemctl stop bitcoind
```

**Comment by adolfosrs** [comment]
Awesome! Sorry, did not find this guide before. Thanks a bunch.
