### ISSUE TITLE
Loop Out's are failing

### ISSUE THREAD

**Issue by rene78** [raspiblitz/raspiblitz#1562]
I am not able to use Loop Out anymore.
![image](https://user-images.githubusercontent.com/36115705/93588329-88ea4600-f9ab-11ea-99fc-daacb6f94f6b.png)

Is it related to this error message?
![image](https://user-images.githubusercontent.com/36115705/93588417-aae3c880-f9ab-11ea-8c93-342e63a673ea.png)

RaspiBlitz v1.6

**Comment by rootzoll** [comment]
Can you check if the macaroon really exist? Have you updated from an older verson? Have you tried to reset macaroons with: MENU > LNDCRED > RESET ?

**Comment by rene78** [comment]
@rootzoll The file doesn't exist
![image](https://user-images.githubusercontent.com/36115705/93626022-1ac17580-f9e3-11ea-832b-4bc57c6f7000.png)
Even after resetting the macaroons as instructed by you the file is still missing and the same error message appears after entering _loopd_.
I cannot tell you whether this version is an updated one because I bought the Raspiblitz (metal case) off eBay one week ago.

**Comment by frennkie** [comment]
I would have recommended MENU > LNDCRED > SYNC.

**Comment by rene78** [comment]
@frennkie Still the same outcome. Same 3 files 🤔...
Seems to be related to https://github.com/lightninglabs/loop/issues/274
Strangely 4 days ago I was able to successfully use _Loop Out_ via RTL.

**Comment by frennkie** [comment]
Running loopd as user admin is currently not correct on Raspiblitz. There is a Systemd service that is running loopd (as bitcoin if I recall correctly).

The failing loops can have many reasons within the LN network.. E.g. Capacity issues.

**Comment by rene78** [comment]
> ...E.g. Capacity issues.

@frennkie You seem to be right. Just tried a Loop Out with only 250k Satoshi and it seems to work.
I'd close the issue again. Thanks for the help everyone!
