### ISSUE TITLE
Idea: Logout shortcut

### ISSUE THREAD

**Issue by Marcoblue** [raspiblitz/raspiblitz#1568]
In the main menu I would find a shortcut with logout useful.  At the bottom it would fit. The function would have to correspond to an exit and avoids having to switch to the console first.

**Comment by frennkie** [comment]
How much shorter than `CTRL+c` and then `CTRL+d` can it get?

**Comment by openoms** [comment]
![image](https://user-images.githubusercontent.com/43343391/140729770-f03cb46f-306d-49c0-b790-20cb8b158902.png)

There is now an exit label on the main menu.
