### ISSUE TITLE
SSH access via Tor hidden service

### ISSUE THREAD

**Issue by woeisme** [raspiblitz/raspiblitz#1590]
Would be nice to allow SSH access via Tor hidden service to be able to administer the Raspiblitz without having to worry about NAT. 
Should just be another hidden service entry right?

**Comment by woeisme** [comment]
actually got this working in about 10 minutes with the following process:
(run all modifications as root via sudo -s)

edit /etc/tor/torrc 

> HiddenServiceDir /mnt/hdd/tor/sshd_2222/
HiddenServiceVersion 3
HiddenServicePort 2222 127.0.0.1:22

> systemctl restart tor

>cat /mnt/hdd/tor/sshd_2222/hostname

Use Torbot VPN mode to add Connectbot (or your ssh client of choice)
In connectbot use the onion address and port you chose (2222 above)
Imported a public key from Connectbot to the Raspiblitz. 
And Voila! ssh access to your Raspiblitz machine from anywhere in the world.

**Comment by woeisme** [comment]
Could someone nice add a feature / enhancement label to this Issue ?

**Comment by openoms** [comment]
this might make a good FAQ entry but I don't think that offering ssh access as a Hidden Service is a good idea from the security point of view.
Also it needs Tor on connecting machine so adds further complexity to the setup.

This can be adapted to be specific to the RaspiBlitz: https://github.com/openoms/joininbox/blob/master/FAQ.md#ssh-through-tor-from-linux

**Comment by rootzoll** [comment]
Just adding a reminder to check if this setting survives a reset/recovery for v1.7 version.

**Comment by openoms** [comment]
I don't think it would since the Hidden Service is defined on the SDcard in /etc/tor/torrc and not restored by any script.

It would also be a security issue when during the first boot ssh can be accessed remotely with the default password (`raspiblitz`).

I don't think that persisting this setting would be a good idea.

**Comment by rootzoll** [comment]
OK makes sense - closing issue.
