### ISSUE TITLE
Idea: Activate possibility for RBF (Replace by Fee)

### ISSUE THREAD

**Issue by Marcoblue** [raspiblitz/raspiblitz#1591]
In order to be able to use RBF (Replace by Fee), this function must be activated before the (first) transaction is done. 

For this purpose, walletrbf=1 must be added to the bitcoin.conf.

Does it make sense to do this as default?

**Comment by libaohua-qb** [comment]
in my view, RBF is default available is you do nothing

**Comment by rootzoll** [comment]
@openoms is the RBF active has any side effects on e.g. Joinmarket?

**Comment by openoms** [comment]
what is the usecase here?
@Marcoblue are you planning to contruct transactions with bitcoin-cli?
Because this setting would not have effect on anything else.
Every wallet (including joinmarket) is setting their own RBF flag.

**Comment by Marcoblue** [comment]
@libaohua-qb At default RBF is inactive. I cannot see where it is switched on.
It can be switched on during start with startoption -walletrbf or thru bitcoin.conf.

@openoms I had a problem with a channel openeing thru RTL. So you mean RBF is possible there over the console?
Maybe this:
bitcoin-cli -conf=/mnt/blockchains/bitcoin/bitcoin.conf bumpfee txid

Can't test it now, because my transaction worked already after 3 days.

**Comment by openoms** [comment]
See my answer here: https://github.com/rootzoll/raspiblitz/issues/640#issuecomment-699898165

I suggest to close this since the request is based on a misunderstanding.
