### ISSUE TITLE
typo in comparison and possible script-flow glitch

### ISSUE THREAD

**Issue by PatrickScheich** [raspiblitz/raspiblitz#1598]
looking into `_background.sh` lines 104...

```
  updateDynDomain=0
  if [ ${recheckPublicIP} -eq 1 ]; then
    echo "*** RECHECK PUBLIC IP ***"

    # execute only after setup when config exists
    if [ ${configExists} -eq 1 ]; then

      publicIPChanged=$(/home/admin/config.scripts/internet.sh update-publicip | grep -c 'ip_changed=1')
      
    # check if changed
    elif [ ${publicIPChanged} -get 0 ]; then

      # refresh data
      source /mnt/hdd/raspiblitz.conf

      # only restart LND if auto-unlock is activated
      if [ "${autoUnlock}" = "on" ]; then
        echo "restart LND with to pickup up new publiIP"
        sudo systemctl stop lnd
        sudo systemctl start lnd
      else
        echo "new publicIP but no LND restart because no auto-unlock"
      fi

      # trigger update if dnyamic domain (if set)
      updateDynDomain=1

    else
        echo "public IP has not changed"
    fi

  fi
```

I guess the line `elif [ ${publicIPChanged} -get 0 ]; then` should be `elif [ ${publicIPChanged} -gt 0 ]; then`

further looking into the program flow it might not do as intended....

if the config file exsits then the check for changed global IP is executed, but I guess that the `elif [ ${publicIPChanged} -get 0 ]; then`  part which will evaluate the above return value will not be executed.
I might be wrong as I'm not so familiar with bash programming.

**Comment by rootzoll** [comment]
Jupp the `-get` is a bad typo and the `if` just makes sense ... must have been a late night edit of mine. Good catch. Thanks.
