### ISSUE TITLE
Detection of HDD/SSD without partitions

### ISSUE THREAD

**Issue by adevoss** [raspiblitz/raspiblitz#1621]
Tested #1603 with /dev/vdb without partitions as datadrive. Does not get detected and gives error (same as #1615)
Of course it is not mounted but 'hddRaspiData' has no value so it results in the same error.

blitz.datadrive.sh status: hddPartitionCandidate='vda1'. That is the OS partition.

I can't think of a solution right now but I will be working on one.

**Comment by adevoss** [comment]
See #1625

**Comment by rootzoll** [comment]
OK merged into v1.6 branch ... TODO testing on normal setup with HDD

**Comment by rootzoll** [comment]
Tested with a HDD with no partions - got detected and formatted correctly. Closing this issue for v1.6.1 release.
