### ISSUE TITLE
[Feature Request] Add OpenDEX

### ISSUE THREAD

**Issue by kilrau** [raspiblitz/raspiblitz#1627]
### Why?
[opendexd](https://github.com/opendexnetwork/opendexd) as optional service enables RaspiBlitz users to use their bitcoin in existing lightning channels to offer orders on the [OpenDEX Network](https://opendex.network/) and to earn via arbitrage profits from trades. [Here](https://blog.exchangeunion.com/launching-opendex-the-decentralized-exchange-standard-b907d2a99b5a) an explanation what OpenDEX is, how it uses lightning and how the arbitrage works. [Here](https://decrypt.co/40669/opendex-wants-bring-defi-style-returns-bitcoin) an independent article covering the concept. Tl;dr: it lets your sats work for you

### What?
Add opendexd via [opendex-docker](https://github.com/opendexnetwork/opendex-docker), which packages the minimal dependencies, into service menu item within RaspiBlitz.

Notes:
- opendexd needs lnd with hold-invoice support. The default lightning labs binaries don't include this. Option a) add hold-invoice support via [this](https://github.com/rootzoll/raspiblitz/blob/v1.6/home.admin/config.scripts/lnd.update.sh) existing script
- 64-bit base OS. [Considered inevitable](https://github.com/rootzoll/raspiblitz/issues/1199#issuecomment-640215632) (needed for LND to support a db >2GB) and greatly improves performance for docker.
- installation of docker. Easiest probably via a script:
```
curl -fsSL https://get.docker.com -o get-docker.sh && 
sudo sh get-docker.sh
sudo usermod -aG docker ${USER}
```

**Comment by kilrau** [comment]
Small update here:
- went the xud-docker way and install docker as dependency in the installation flow.
- decided to make the docker installation a generic docker install script available to other services
- developing & testing straight on the [arm64 image](https://github.com/rootzoll/raspiblitz/issues/1199)

**Comment by rootzoll** [comment]
Good news everyone ... the RaspiBlitz v1.7RC1 image based on the RaspiOS 64-bit is now available:
https://github.com/rootzoll/raspiblitz/tree/dev#downloading-the-software

Also there is a basic docker framework that can be activaed now:
https://github.com/rootzoll/raspiblitz/blob/dev/home.admin/config.scripts/blitz.docker.sh

So happy to see someone hacking and adding OpenDEX to the RaspiBlitz - remeber to work/test with the `dev` branch :)

**Comment by cstenglein** [comment]
Closing this since OpenDEX doesn't seems to be [actively maintained anymore](https://opendex.network/)
