### ISSUE TITLE
Update BTCPay Server to 1.0.5.7

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#1638]
https://twitter.com/BtcpayServer/status/1314135659699867648

@openoms do you see anything against updating to lastest version for v1.6.1 release or shoudl be push it to v1.7?

**Comment by openoms** [comment]
just installed v1.0.5.6 succcessfully 😃.
Will try this now.

**Comment by rootzoll** [comment]
Merged the upadte ... final TODO: Test install on recovery.

**Comment by rootzoll** [comment]
OK also working fine on recovery/update. Will be part of v1.6.1 release. Closing issue.
