### ISSUE TITLE
Fix sd card expanding on provision

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#1644]
On testing found that on recovering/update the sd card failed to expand to full capacity.

**Comment by rootzoll** [comment]
Should now work again for RaspberryPi wit merge of #1645
First test look good ... TODO: final recheck with finale release image

**Comment by openoms** [comment]
Great to have this fixed, was a returning problem for the blitzes on v1.6 actually!

**Comment by rootzoll** [comment]
OK this looks good now my 16 sd card & ma 32 gb card using now with after v1.6.1 update full capacity. Closing issue.
