### ISSUE TITLE
Stuck on boot

### ISSUE THREAD

**Issue by nerdminerstore** [raspiblitz/raspiblitz#1651]
Hello,

i followed the readme: Downloading image, write it to the SD-Card aso. Did this several times before with other versions.

After booting the Raspiblitz v1.6 (latest download) it freezes after around 4 seconds on the same line every time. I tried different SD-Cards and SSD drives. All with same result. I had v1.5 running on the same setup without problems. An image of MyNode worked without problems.

Im on Raspberry Pi 4 4GB with 1TB Crucial SSD - I use a 825x board for the SSD, may this cause a problem in the new version? Seems like everything is working fine until its stuck. 

![IMG_4033](https://user-images.githubusercontent.com/54980603/95664907-e22d3b80-0b4b-11eb-9eb2-cbba99e61962.jpg)

Regards
Other

**Comment by chiefuschrist** [comment]
Did you add the "hdmi" file to the boot drive? It looks like you're using an actual LCD screen. I had the same problem until I added the hdmi file. I think it's expecting to boot everything onto the screen you can attach to the raspi, unless I'm mistaken!

**Comment by nerdminerstore** [comment]
Hi! No i do not use the LCD screen. Im using my TV screen on first boot just to see whats happening. I installed a few raspiblitz before and did it always that way without any problems. 

Where to add the hdmi file? And where to get it?

**Comment by openoms** [comment]
just boot without the HDMi connected and connect via ssh as described in the readme. Similar as here: https://github.com/rootzoll/raspiblitz/issues/1618#issuecomment-703639582

**Comment by nerdminerstore** [comment]
That did the trick! Strange, but thanks a lot!!
