### ISSUE TITLE
Add Circuitbreaker to SSH-GUI

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#1654]
See #1581 & #1649 .. evolve this further:

- [x] add to SSH-GUI
- [x] install on recovery/update

**Comment by openoms** [comment]
Circuitbreaker is already part of the recovery process: https://github.com/rootzoll/raspiblitz/blob/9ae1a2d9bfdd4d644ed103ef69442dd6b31899f7/home.admin/_bootstrap.provision.sh#L544

I think this service should be on by default with the option to switch it off from the `SETTINGS` menu.
https://twitter.com/openoms/status/1363781464832286720
https://twitter.com/openoms/status/1363792824068677634

**Comment by rootzoll** [comment]
I would not change it to "on by default" (yet) .. first now make it easy to activate it under SETTINGS - see if we get any error or side effects reports.

**Comment by openoms** [comment]
Agreed, although I am using it om multiple successful routing nodes.
There is a high amount of probes reported from time-to-time, but force closes are very rare now.
It gives a peace of mind that those node are at least less vulnerable to a flooding attack.

**Comment by rootzoll** [comment]
OK now ready for v1.7 release and final testing.

**Comment by rootzoll** [comment]
Tests look good. Will be part of v1.7. Closing issue.
