### ISSUE TITLE
Lot of DNS requests v4.ipv6-test.com

### ISSUE THREAD

**Issue by Marcoblue** [raspiblitz/raspiblitz#1656]
Raspiblitz requests "v4.ipv6-test.com" 3x per minute via ipv4 and ipv6. Does it have to be that often?
![DNS](https://user-images.githubusercontent.com/71592699/95774283-643e7100-0cc0-11eb-95b2-2ce89d9a5442.jpg)

**Comment by rootzoll** [comment]
Did you tested with RaspiBlitz v1.6.0 image or with latest scripts preparing for v1.6.1?

**Comment by Marcoblue** [comment]
It is with v1.6.0. When 1.6.1 is released, I will check again.

**Comment by rootzoll** [comment]
If your node is for testing you can update 1.6.0 to the latest scripts with: MENU > UPDATE > PATCH > PATCH-MENU > PATCH and do a reboot. Please let me know if you still see that many requests - that would be great.

**Comment by rootzoll** [comment]
Will move this to v1.7 milestone .. with the default Tor getting the public IP gets less important anyway. Seems like a good time to also then make changes on this.

**Comment by Marcoblue** [comment]
At 1.6.1 it is still the same.

**Comment by rootzoll** [comment]
Hi @Marcoblue the merged PR should now fix the too much calling .. can you verify?
To get the fix on your RaspiBlitz v1.6.1 go to UPDATE > PATCH > PATCHMENU > PATCH and restart.
After the restart you should see the results.

**Comment by Marcoblue** [comment]
It works. After the restart he has asked once, but not again since then ( 12 minutes ago).

**Comment by rootzoll** [comment]
Perfect :) So this will fix will be part of v1.6.2 release ... closing issue.

**Comment by bigsk1** [comment]
Googled why this is happening also and found this, running on latest 1.7.2 same issue none stop every 10 secs. I can try and patch and restart but running latest. I** edit, I have another node running on same netwrok and have it as a peer as well as an open channel with. On thunderhub it shows local ip as sync ip, not tor address. Wondering if this is why.
