### ISSUE TITLE
RTL update to 0.9.1 + UPDATE option

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#1658]

**Comment by rootzoll** [comment]
OK merged .. will just run a final test on it.

**Comment by rootzoll** [comment]
Had on testing problems with using Password B ... will recheck, maybe it was just a side effect from somewhere.

**Comment by rootzoll** [comment]
OK tested again and install and password worked fine. Will be part of v1.6.1 release. Closing issue.
