### ISSUE TITLE
Improve LND emergency update options 

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#1661]
By example the event #1647 showed that a "Trusted UPDATE" to the latest stable version would be good to have fo the future. It could work that we check for latest release (not ReleaseCandidate) and check fingerprint with all trusted developer keys. If not matching any - ask user if wants to get reckless.

Also have the same for Bitcoin - maybe even combine both because the lastest stable LND might need the latest stable Bitcoind. Some food for thought. Maybe combine both to "Emergency" update .. and now with TOR by default, maybe have an RaspiBlitz hidden info-service as an option that is called once a day to inform on "updates" & "emergencies" (might be a subscription service). Just food for thought.

**Comment by nyxnor** [comment]
This above is food for thought, so I will link the related topic to this one can be closed or and the others being solved separately.
* [Update Bitcoin core](https://github.com/rootzoll/raspiblitz/issues/2183)
* [Update LND](https://github.com/openoms/lightning-node-management/blob/master/lnd.updates/lnd.update.sh)
* [Update Blitz](https://github.com/rootzoll/raspiblitz/issues/367)
