### ISSUE TITLE
Make VagrantVM also run with Tor

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#1671]
As testing in #1579 showed the vagrantVM is not running with Tor - just with clearnet yet. For v1.7 release find a way that it is also runnibg with Tor by default.

**Comment by nolith** [comment]
This definitely surprise me as [https://github.com/rootzoll/raspiblitz/pull/1571](https://github.com/rootzoll/raspiblitz/pull/1571) was entirely developed and tested with vagrant.

**Comment by rootzoll** [comment]
Maybe it was another side effect - idid worked on first try on my machine and I wrote this issue to retrest and mybe fix later.

**Comment by rootzoll** [comment]
Closing this issue because personally vagrant is not part anymore of my dev setup.
