### ISSUE TITLE
TOS on IP2Tor bridges & how to get support

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#1672]

**Comment by openoms** [comment]
Is now only one IP2Tor subscription allowed at a time on v1.6.2?

**Comment by ghost** [comment]
HI, I just tested IP2Tor for sphinx. But it was not activated with error (something similar to) "payment not received". 

- I have tried `eu-fra1`
- The payment for 40 sats went out of my node.
- The subscription list is empty.

I tried `nam-tor1` and it worked.

**Comment by rootzoll** [comment]
@frennkie do you see any problem with the `eu-fra1`?

**Comment by frennkie** [comment]
I just checked the orders.. There were successful payments before and after that approximate time. And there is no failed request...

Are there more logs? Did you also try another service besides Sphinx?

**Comment by ghost** [comment]
If you give me some hint how to find that in logs I can share it.

No I just tested Sphimx.
