### ISSUE TITLE
Fix BTRFS

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#1676]
![Bildschirmfoto 2020-10-16 um 14 53 42](https://user-images.githubusercontent.com/2472225/96260549-791c4c80-0fbf-11eb-97b0-639ba0ee9701.png)

**Comment by adevoss** [comment]
Got this same when trying out btrfs. #1668 (edit: and #1612) fixes this.

**Comment by rootzoll** [comment]
Merged already in v1.6.1 ... but re-check for a v1.7 release.

**Comment by holgern** [comment]
Parts of the problem are fixed by PR #1697 in which the tempmount parameter is changed when the filesystem is btrfs

**Comment by adevoss** [comment]
#1706 is in some places the same and in other places different from #1697. #1711 is also part of the approach I took.

**Comment by joernroeder** [comment]
running into this as well. Whats the best approch here? just wait for the new release or are the changes already merged and  updatable via `XXupdateScripts.sh`?

**Comment by rootzoll** [comment]
Found that when BTRFS is running with a USB RAID1 thumb drive and I switch on the Backup StaticChannel to USB .. it wants to use that RAID1 devcie and format it. Will fix this as part of this issue.

**Comment by rootzoll** [comment]
Ok fixed with merge of #1759

**Comment by rootzoll** [comment]
ToDos for final testing of BTRFS:
- [x] Run a update/recover with RAID1 & USB-Backup connected
- [x] Run a complete migration with a RC1 of v1.6.2

**Comment by rootzoll** [comment]
Before release check that this is solved: https://github.com/rootzoll/raspiblitz/issues/1785#issuecomment-735395411

**Comment by rootzoll** [comment]
OK BTRFS Migration is now looking good. Closing issue for v1.6.2 release.
