### ISSUE TITLE
Raspberry Pi Screen

### ISSUE THREAD

**Issue by maestro32** [raspiblitz/raspiblitz#1689]
Is this the correct Raspberry Pi screen to buy?
[https://www.amazon.com/TFT-LCD-Raspberry-Controller-Interface/dp/B08KZXSJW2/ref=sr_1_12?dchild=1&keywords=XPT2046&qid=1603199760&sr=8-12]

The link in the Shopping List doesnt really point to anything

**Comment by openoms** [comment]
Yes, this looks good. The important thing is to have the right keywords in the product description which there are.

**Comment by nyxnor** [comment]
@maestro32 Please close this.
