### ISSUE TITLE
Provisioning of "DYNAMIC DOMAIN" gets stuck

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#1691]
On last log line "# start to create new generate new TLSCert" recovery got stuck ... check if systematic or edge case.

**Comment by rootzoll** [comment]
manual fix: ssh in (with password 'raspiblitz') and deactivate dynamic DNS. turn off. reflash sd card again and recover.

**Comment by openoms** [comment]
Had another user reporting this.

Deactivate the Dynamic Domain with the script by running:
`config.scripts/internet.dyndomain.sh off`

https://t.me/RaspiBlitzFAQ/145

**Comment by openoms** [comment]
@rootzoll shall we recommend to deactivate the dynDomain before updating to avoid getting stuck?

**Comment by rootzoll** [comment]
@openoms Yepp .. until we have a v1.6.2 - targeting mid november.

**Comment by geco91** [comment]
Will check what is going wrong on the logs when updating with dyndomain on.

Also maybe thats a good point to optimize the `internet.dyndomain.sh` config script with:
- have a `status` parameter
- fail on `on` when no domain is given
- make sure outputs are comment safe
- check if can be set thru settings menu correctly

**Comment by geco91** [comment]
These are the logs where it blocks the update/provisioning:

```
Provisioning DYNAMIC DOMAIN - run config script
number of args(2)
making sure services are not running
# switching the DynamicDNS ON
# dynDomain(home.rotzoll.de)
# dynUpdateUrl()
# lnd.tlscert.sh domain-add
# OK the domain was already added lnd.conf
# DynamicDNS is now ON
# checking if LND is running
# making sure services are not running
# keep old tls data as backup
# start to create new generate new TLSCert
```

Because LND is not running the TLS cannot get created and it blocks. But during recovering there is no need to recreate the TLS - the macaroons and certs from backup will be used anyway after setup. Will check script again to make this work again.

**Comment by geco91** [comment]
Can confirm that #1721 fixed the "getting stuck on update" problem on my test machine.

**Comment by rootzoll** [comment]
Tested with RC2 - working fine with dynamic domain on. Closing issue for v1.6.2 release.
