### ISSUE TITLE
btrfs migration with raid (usb drive) does not work

### ISSUE THREAD

**Issue by holgern** [raspiblitz/raspiblitz#1696]
Migration from raspiblitz 1.6 to 1.6.1 with btrfs and raid (32 GB usbstick) enabled, did not work.

Problem is that the drive letters of the drive and the USB drive are switched in blitz.datadrive.sh status.

**Comment by rootzoll** [comment]
Should be fixed ... will be tested as part of #1676. Closing this isue.
