### ISSUE TITLE
Improve Release Update UI

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#1698]
Let peole know in UI that they also can just overwrite the old sd card - but it would be safer to use a second one.
Also check if its possible to copy automatic sd card backup to `boot` partion (is big enough?) so thats its easier to get the resuefile from sd card with laptop.

**Comment by geco91** [comment]
The boot partition of sdcard has about 200MB free space. So pushing a copy there could be possible but may not work future proof because the whole LND folder content could grow much bigger ... so will just commit a PR that is changing the description.

**Comment by rootzoll** [comment]
PR #1732 merged for v1.6.2 release. Closing this issue.
