### ISSUE TITLE
"Stuck at Specter"

### ISSUE THREAD

**Issue by grnqrtr** [raspiblitz/raspiblitz#1699]
I noticed this in the Telegram chat before attempting the update to 1.6.1:
![specter3](https://user-images.githubusercontent.com/16716573/96743849-6068c800-13ff-11eb-9ae2-f0a8ce2fe951.png)

I then noticed that I also got "stuck at specter": 
![specter](https://user-images.githubusercontent.com/16716573/96743869-65c61280-13ff-11eb-84c4-304857a67826.png)

I opened another ssh session and checked bitcoind status and also tried restarting bitcoind with `sudo systemctl restart bitcoind` as well as `start` and `stop`. A while later I realized in my original tab that the update seemed to be continuing after it said `Job for bitcoind.service cancelled.`
![specter2](https://user-images.githubusercontent.com/16716573/96743885-68c10300-13ff-11eb-8de0-ef97121e00db.png)

Things seem to be working okay now, but there was this hang up.

**Comment by holgern** [comment]
I also had this problem and had to restart again. It had worked on the second try.

**Comment by openoms** [comment]
Thanks for reporting!
Yes it seems it is getting stuck during recovery on restarting bitcoind at https://github.com/rootzoll/raspiblitz/blob/7f2e12472e4f3cba68db53a6879c1284860e9ad1/home.admin/config.scripts/bonus.cryptoadvance-specter.sh#L271

This was planned to be changed for the next release anyway: https://github.com/rootzoll/raspiblitz/issues/1639
so tagging for v1.6.2.

For now might be the best to deactivate Specter before starting the update and reinstall afterwards.

**Comment by openoms** [comment]
To solve it while recovering run:  
`sudo systemctl stop bitcoind`

**Comment by geco91** [comment]
Can confirm that on my test machine with #1699 it fixed the getting stuck when `blockfilter=0` before update.

**Comment by openoms** [comment]
This should be solved by this: https://github.com/rootzoll/raspiblitz/pull/1722. Thanks @geco91!

**Comment by theansweris420** [comment]
had the same issue. after the final reboot the specters  .onion adress was a new one. i didnt save the first. just the seed. is there a change of resotring it only with the seed?

**Comment by openoms** [comment]
> had the same issue. after the final reboot the specters .onion adress was a new one. i didnt save the first. just the seed. is there a change of resotring it only with the seed?

Specter does not store private keys so there is no seed for it. The onion address changing does not affect the stored data.

You might be thinking of the seed given for the LND wallet. That is only enough to restore the onchain balance, not the channels. See the FAQ for details.

**Comment by rootzoll** [comment]
OK tested with RC2 and looks good. Closing issue for v1.6.2 release.
