### ISSUE TITLE
undervoltage detected

### ISSUE THREAD

**Issue by charlesrocket** [raspiblitz/raspiblitz#17]
LCD screen throw the error before the reboot `undervoltage detected` during LN setup, with following hdd errors. trying to recreate

**Comment by charlesrocket** [comment]
changing power source giving undervoltage on boot right away. too much load on hdd during init or local power source

**Comment by rootzoll** [comment]
Do you have the Power Supply from the Shopping list?
https://www.amazon.de/dp/B01E75SB2C

To run an external HDD the Pi needs some extra power - with the power supply from the shopping list I never had any running it with one HDD.

**Comment by charlesrocket** [comment]
@rootzoll im using different one from US list, but it doesn't really look like lack of power, at this time. thought that your PSU might be newer, but parameters are the same. and it would throw the error on boot. right now im having endless cycle of
```0.00%
error code: -28
error message:
Loading block index...
(standard_in) 1: syntax error
./70initLND.sh: 24: [: -eq: unexpected operator
./70initLND.sh: 27: [: -eq: unexpected operator
waiting to start sync
```
```
0.00%
error code: -28
error message:
Rewinding blocks...
(standard_in) 1: syntax error
./70initLND.sh: 24: [: -eq: unexpected operator
./70initLND.sh: 27: [: -eq: unexpected operator
waiting to start sync
```
```
0.00%
error code: -28
error message:
Verifying blocks...
(standard_in) 1: syntax error
./70initLND.sh: 24: [: -eq: unexpected operator
./70initLND.sh: 27: [: -eq: unexpected operator
waiting to start sync
```
```
0.00%
error: couldn't connect to server: unknown (code -1)
(make sure server is running and you are connecting to the correct RPC port)
(standard_in) 1: syntax error
./70initLND.sh: 24: [: -eq: unexpected operator
./70initLND.sh: 27: [: -eq: unexpected operator
waiting to start sync
```

looks like bitcoind reading/fixing corrupted (after funky torrent download) blockchain on hdd, but can't connect over cli to get the status. deleting conf files from hdd helped for a while, then rpc error popped up again. will try to catch it again.

can't rule out the bad torrent download at this time since im getting weird signals from my ISP, nobody likes heavy traffic 🛩

**Comment by rootzoll** [comment]
I updated the US Shopping list, because the power supply there had just 2.5A - I am running one with 3.0A .. the extra 0.5A seems to protect you on power peaks from the HDD.

About the looping errors on sync - see https://github.com/rootzoll/raspiblitz/issues/18

**Comment by charlesrocket** [comment]
i was afraid that its broken torrent file after days of funky downloads, since it was working for a while without any power issues
```
2018-07-28 13:31:40 msghand thread start
2018-07-28 13:31:40 LevelDB read failure: Corruption: block checksum mismatch: /home/bitcoin/.bitcoin/testnet3/chainstate/024914.ldb
2018-07-28 13:31:40 Corruption: block checksum mismatch: /home/bitcoin/.bitcoin/testnet3/chainstate/024914.ldb
2018-07-28 13:31:40 Error: Error reading from database, shutting down.
2018-07-28 13:31:40 Error reading from database: Database corrupted
```

deleting chainstates, looks like got it rebuilding
