### ISSUE TITLE
Mempool installation confirmation info refers to BTC RPC Explorer install

### ISSUE THREAD

**Issue by senf42** [raspiblitz/raspiblitz#1701]
At the end of installing Mempool Space in 1.6.1, there is a dialog box that says there may be ~7 hours required to build the transaction index before ready, and to use the EXPLORE option in the menu for more details. It looks like this is the standard dialog for BTC RPC Explorer's installation, and should be updated to refer to Mempool Space.

**Comment by rootzoll** [comment]
PR #1733 merged and correction will be part iof v1.6.2 release. Closing issue.
