### ISSUE TITLE
TODO before updating to v1.6.1

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#1702]
There are more reports from getting stuck during recovery when updating to v1.6.1 collected some caveats to be run before updating:
```
config.scripts/internet.dyndomain.sh off
config.scripts/bonus.cryptoadvance-specter.sh off
sudo chown -R electrs:electrs /mnt/hdd/app-storage/electrs
```
* Deactivates the Dynamic Domain: https://github.com/rootzoll/raspiblitz/issues/1691
* Switches the Specter service off (the data is preserved and will be restored when reinstalled): https://github.com/rootzoll/raspiblitz/issues/1699
* fixes the electrs database owner just in case: https://github.com/rootzoll/raspiblitz/issues/1700

EDIT: before updating a node with a BTRFS RAID running see this comment: https://github.com/rootzoll/raspiblitz/issues/1715#issuecomment-716433182

**Comment by geco91** [comment]
Also check if nginx is running still fine when RTL & LNbits are installed ... had a problem on one test machine, but not sure if that is also a problem on a fresh machine.

**Comment by rootzoll** [comment]
Ok all the mentioned problems have a seperate issue and the update/recovery worked with RTL & LNbits. So closing this issue for v1.6.2 release.
