### ISSUE TITLE
Thunderhub is still 0.9.14 at Raspiblitz v1.6.1

### ISSUE THREAD

**Issue by Marcoblue** [raspiblitz/raspiblitz#1710]
At https://github.com/rootzoll/raspiblitz/blob/v1.6/CHANGES.md it shows 0.9.15, but on the Raspiblitz v1.6.1 Thunderhub Webpage it shows still 0.9.14

**Comment by openoms** [comment]
Update to the latest release of ThunderHub any time from the UPDATE menu. New versions are quite frequent,

**Comment by Marcoblue** [comment]
I did it already and be on 0.9.16 now. Still no big deal, but the Changes.md is wrong.

**Comment by rootzoll** [comment]
@Marcoblue I corrected the `changes` files. Thx.
