### ISSUE TITLE
SSH connection refused during BC sync and after reboot

### ISSUE THREAD

**Issue by nderambure** [raspiblitz/raspiblitz#1727]
Just to report that during Blockchain sync during fresh install, if I disconnect SSH and try to reconnect, the password is refused (yes it's the good one ;) )
Same after reboot.
I'm restarting again from scratch to see if anything changed.
I've seen couple of messages with same problem.
I'm using Raspiblitz 1.6.0 on a Pi4 and the hard drive from shopping list.

**Comment by ChuckNorrison** [comment]
you could try `sudo systemctl restart sshd` to solve it temporary, i observed a failed sshd service start at boot time in unknown circumstances. 

Maybe `sudo systemctl status sshd` can give some more informations

**Comment by nderambure** [comment]
Thx, I'll try that in my next attempt.

**Comment by ChuckNorrison** [comment]
this check_network attempt could be helpful in here, especially the `@reboot` in roots crontab

https://github.com/raspberrypi/linux/issues/3034#issuecomment-723420437

fstab options `_netdev` and `nofail` seems to be useful too, as tested here 

https://github.com/rootzoll/raspiblitz/issues/1618#issuecomment-709547783

**Comment by nyxnor** [comment]
@rootzoll Please close this
