### ISSUE TITLE
LND error

### ISSUE THREAD

**Issue by PandamineHub** [raspiblitz/raspiblitz#1738]
Hello everybody,

could you please help me? MyNode has been working for few days, I have set up my lightning wallet and open few channels. After one restart of my raspberry 4 with MyNode, LND is still in status "Opening DB" and there is showing below error. It looks like there is missing certificate, but I am not sure how it could be possible when it worked before.Could you please help me?

-- Logs begin at Mon 2020-11-02 04:35:19 CST, end at Mon 2020-11-02 05:01:42 CST. --
Nov 02 05:01:20 myNode systemd[1]: loopd.service: Failed with result 'exit-code'.
Nov 02 05:01:20 myNode systemd[1]: loopd.service: Main process exited, code=exited, status=1/FAILURE
Nov 02 05:01:20 myNode loopd[13032]: loopd exited with an error: open /home/bitcoin/.lnd/tls.cert: no such file or directory
Nov 02 05:01:20 myNode loopd[13032]: 2020-11-02 05:01:20.991 [INF] LNDC: Creating lnd connection to localhost:10009
Nov 02 05:01:20 myNode loopd[13032]: 2020-11-02 05:01:20.991 [INF] LOOPD: Version: 0.8.1-beta commit=
Nov 02 05:01:20 myNode systemd[1]: Started loopd.
Nov 02 05:01:20 myNode loopd[13019]: [lncli] open /mnt/hdd/mynode/lnd/tls.cert: no such file or directory
Nov 02 05:01:20 myNode loopd[13019]: Checking if LND is synced...
Nov 02 05:01:20 myNode loopd[13018]: Not shutting down!
Nov 02 05:01:20 myNode loopd[13018]: Checking if device is shutting down...
Nov 02 05:01:20 myNode systemd[1]: Starting loopd...
Nov 02 05:01:20 myNode systemd[1]: Stopped loopd.
Nov 02 05:01:20 myNode systemd[1]: loopd.service: Scheduled restart job, restart counter is at 22.
Nov 02 05:01:20 myNode systemd[1]: loopd.service: Service RestartSec=1min expired, scheduling restart

**Comment by openoms** [comment]
You have opened an issue with the wrong project. This is abou the RaspiBlitz, not MyNode.
Their support channels are here: https://mynodebtc.com/support

Closing.
