### ISSUE TITLE
Specter: update to v0.9.2

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#1743]
PR: https://github.com/rootzoll/raspiblitz/pull/1742

The UPDATE menu option has also worked on RaspiBlitz v1.6.1, but needed to run:
`sudo systemctl restart cryptoadvance-specter`
to load the new version.

**Comment by rootzoll** [comment]
PR merged - putting on final testing

**Comment by rootzoll** [comment]
even updated to 0.10.0 - closing issue :)
