### ISSUE TITLE
LCD Screen Blinking after boot

### ISSUE THREAD

**Issue by Aki113s** [raspiblitz/raspiblitz#1745]
I can get in via SSH, so the system is working, it seems after every update I battle with the LCD screen. I had saved the commands to install the driver and used it the last 3 updates and it worked fine once rebooted, this one not so much. Ideas??

**Comment by openoms** [comment]
Sounds like you are not using the LCD screen recommended in the readme and supported by the project with drivers installed in the SDcard image.
Can only  suggest to follow the manufacturer's instructions to set it up.
Can post the exact type and maybe pictures including the display's back, someone might have used it.

**Comment by Aki113s** [comment]
[https://ibb.co/LrggmXm](url)
 I have a 3.5 inch display so ill try that, but it is a XPT2046. I also tried the following commands to install drivers which always worked before.

sudo rm -rf LCD-show
git clone https://github.com/goodtft/LCD-show.git
chmod -R 755 LCD-show
cd LCD-show/
sudo ./MPI4008-show

[http://www.lcdwiki.com/4inch_HDMI_Display-C](url)

**Comment by nyxnor** [comment]
`sudo raspi-config`
7 Advanced options
A6 Screen Blanking
Select "No"

**Comment by 1Vincent2** [comment]
Unsubscribe

**Comment by nyxnor** [comment]
Please close this issue if it was solved.

**Comment by nyxnor** [comment]
@rootzoll Please close this
