### ISSUE TITLE
Specter UI says "Tor service is down..." while status screen has a public onion address

### ISSUE THREAD

**Issue by 7hacker** [raspiblitz/raspiblitz#1749]
I installed Specter and logged in.

A notification in the top-right panel indicates "Tor services is down..." while my status screen shows a public onion address in green.

How do I know I am behind Tor with the conflicting status?

**Comment by openoms** [comment]
The Specter UI Hidden Service has nothing to do with Bitcoin Core or LND running behind Tor. 
Please see Specter in the RaspiBlitz menu for the .onion address with which you can access Specter over Tor.

**Comment by 7hacker** [comment]
My bad, this is not a valid issue. Closing
