### ISSUE TITLE
Upgrade nodeJS to 14.15.0

### ISSUE THREAD

**Issue by ghost** [raspiblitz/raspiblitz#1750]
I have encountered this issue https://github.com/alexbosworth/balanceofsatoshis/issues/85 with Balance of Satoshi and author commented that I should upgrade nodejs.

Raspi runs with verson:
```
node -v
v12.16.3
```

Last LTS is `14.15`, newest is `15.1` (https://nodejs.org/en/download/releases/)

Is it possible / good idea to upgrade?

**Comment by openoms** [comment]
go for it: https://github.com/rootzoll/raspiblitz/pull/1748#issue-517123777

**Comment by rootzoll** [comment]
PR merged. v1.6.2 will ship with 14.15 - closing issue.

**Comment by ghost** [comment]
Thanks <3
