### ISSUE TITLE
Update LNBalances Script

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#1762]
A upgrade for the `lnbalance` script from the RaspiBlitz MAIN MENU
https://twitter.com/gcomxx/status/1325720963258994691?s=20

![Bildschirmfoto 2020-11-11 um 23 32 38](https://user-images.githubusercontent.com/2472225/98872039-3773aa00-2476-11eb-8841-b5d5180ca939.png)

**Comment by rootzoll** [comment]
PR merged. TODO: Test after fresh install or recovery.

**Comment by rootzoll** [comment]
When I tested the script on a fresh node (zero balance but one channel was opned to that node) I get this error:
![Bildschirmfoto 2020-11-12 um 18 52 12](https://user-images.githubusercontent.com/2472225/98976970-50349c00-2518-11eb-81e3-e88fd20007b7.png)

**Comment by gcomte** [comment]
Will take care of this this weekend.

**Comment by gcomte** [comment]
Fixed it with [this commit](https://github.com/gcomte/ln-gems/commit/2c5fe492fd705d7b04b46bb62549144c9a120082) but it looks like there are some more issues

**Comment by gcomte** [comment]
FYI: https://github.com/gcomte/ln-gems/issues/3

**Comment by rootzoll** [comment]
OK cool. Tested and looking good. Will be part of v1.6.2 release. Closing issue.
