### ISSUE TITLE
Pool install returns "too many levels of symbolic links"

### ISSUE THREAD

**Issue by Jestopher-BTC** [raspiblitz/raspiblitz#1764]
The installation for Pool can be successfully run from the pool user. 

running `pool accounts list` returns `[pool] unable to read macaroon path : open /home/pool/.pool/mainnet/pool.macaroon: too many levels of symbolic links`

**Comment by openoms** [comment]
It is likely a leftover from testing previous install scripts. 
Advised to reflash the v1.6.1 image and try again.

**Comment by openoms** [comment]
Fixed after manually removing symlinks. 
Feel free to (re)open for any other issues.
