### ISSUE TITLE
sdcard expansion of fresh install (not recovery)

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#1765]
see https://github.com/rootzoll/raspiblitz/issues/214#issuecomment-723595602

**Comment by RR82** [comment]
FYI, I had this same problem on a fresh install of v1.6.1. I solved it by resizing the partition with gnome-disks. It's nice to know there is a script I could have run.

**Comment by rootzoll** [comment]
I think I found why its not happening on fresh install - not on final testing.
BTW with a new update this will autofix itself for older setups.

**Comment by rootzoll** [comment]
OK tested on fresh setup looks good. Closing issue for v1.6.2 release.
