### ISSUE TITLE
Channel is not closed

### ISSUE THREAD

**Issue by LupusPluvia** [raspiblitz/raspiblitz#1767]
the channel is not closed for 2 months when it was closed.

the closure of the canal has meanwhile been forced.

what can i do but wait
![Screenshot_20201112-153724_Zap](https://user-images.githubusercontent.com/15277011/98954365-017a0880-24fe-11eb-8c57-d1cb0b49b3db.jpg)

**Comment by rootzoll** [comment]
So the "Closing Transaction" (that is displayed) has confirmations? I am not exactly sure what is happening in your case ... but sounds like a LND issue. Best support on that you should be able to get in the LND Slack: https://lightning.engineering/slack.html

**Comment by LupusPluvia** [comment]
Okay danke
