### ISSUE TITLE
LND restarts with over 1GB channel.db: solved when compacting the database with chantools

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#1778]
Now the second time I had repeated LND restarts after the channel.db grew above 1GB.
Solved with compacting as documented here:
https://openoms.gitbook.io/lightning-node-management/lnddatabasecompaction

![image](https://user-images.githubusercontent.com/43343391/99432295-ddeefd80-2903-11eb-9c53-294d72ed5d95.png)

Check the size of the channel.db on the blitz:  
`sudo du -h /mnt/hdd/lnd/data/graph/mainnet/channel.db`

The script could have a good place in the REPAIR menu to compact on demand rather then automatically.

Curious if this issue will be solved with [moving to 64bit](https://github.com/rootzoll/raspiblitz/issues/1199) as well. 

Anyway the compaction has a performance benefit as well so will be a good option to have.

**Comment by rootzoll** [comment]
Is there a PR incomming or to be pushed to v1.7?

**Comment by openoms** [comment]
Not so urgent I think since only I had the issue so far AFAIK. In any case can point people to the guide already. Need to check if the next major LND version will have the compaction built in as well.

**Comment by openoms** [comment]
Ok, it seems it is coming in LND v0.12 and already in the master so don't need to  implement this with chantools: https://github.com/lightningnetwork/lnd/issues/4131

Will just leave this issue here until the release.

**Comment by openoms** [comment]
This has been tested and solved with moving to a 64bit base image.
