### ISSUE TITLE
Option to connect to bitcoin node through neutrino

### ISSUE THREAD

**Issue by wereHamster** [raspiblitz/raspiblitz#178]
I have btcd running on a server and lnd can connect to it through neutrino in order to access the bitcoin network. That way I don't need to have a large harddrive on the machine where I run lnd. It would be nice if raspiblitz supported this mode as well.

**Comment by rootzoll** [comment]
Yes that would be an idea - but its hard to make the RaspiBlitz work in every possible configuration. The RaspiBlitz is designed to be a all switches Bitcoin-Fullnode with Lightning runinng. 

There is the plan to also start a "lightclient" version of the Blitz that works without HDD and has a RaspberryZero as hardware platform for the future. If you like to buidl something in that direction, please share.
