### ISSUE TITLE
[Feature Request] Add 'Compact channels.db on restart' to options menu

### ISSUE THREAD

**Issue by Jestopher-BTC** [raspiblitz/raspiblitz#1782]
Channels.db files are growing larger and it is becoming a recommended practice to compact the file using guggero's chan tools. Can an option be added from the raspiblitz menu to select "Compact channels database on restart" ? Initially I was thinking that this would be a selection like the services menu, but it may be prudent to add an options menu where a user can turn on/off keysend, wumbo, channels.db compaction, etc.

**Comment by openoms** [comment]
Discussed here already, will be part of LND v0.12: https://github.com/rootzoll/raspiblitz/issues/1778
Hope you don't mind me closing the duplicate issue.
