### ISSUE TITLE
RC1 when installing mempool script needs user input

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#1784]
![Bildschirmfoto 2020-11-18 um 18 34 24](https://user-images.githubusercontent.com/2472225/99566170-d5aec500-29cc-11eb-98c6-5c4499024904.png)

This could block during recover phase. Check how this was fixed before.

**Comment by ChuckNorrison** [comment]
Best answer is to set environment var for this:
`export NG_CLI_ANALYTICS=ci`

**Comment by rootzoll** [comment]
@ChuckNorrison hmmm ... that is already in the code:
https://github.com/rootzoll/raspiblitz/blob/0c5b549fb042854daa99958df81f65a3e816ca21/home.admin/config.scripts/bonus.angular_cli.sh#L46

**Comment by rootzoll** [comment]
I will add the environment var also to the `.bashrc` of the admin.

**Comment by rootzoll** [comment]
Ok tested again that mempool is running thru on recovery without blocking. Last test todo on a fresh install if that interaction is still showing up.

**Comment by rootzoll** [comment]
OK last PR shows no working test. Closing issue for v1.6.2 release.
