### ISSUE TITLE
Update: Thunderhub 0.10.4

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#1791]
with lnmarkets & boltz integration

**Comment by rootzoll** [comment]
PR merged and first test worked. Final testing is needed for recovery with RC2 release.

**Comment by rootzoll** [comment]
Recovery runs fine. Closing issue for v1.6.2 release.

**Comment by kilrau** [comment]
Failed to manually build an image from master yesterday with the script, still checking what went wrong. In the meanwhile - do you have a RC2 image ready somewhere? @rootzoll

**Comment by rootzoll** [comment]
Reopen for final testing. RC2 is coming today or tomorrow.

**Comment by rootzoll** [comment]
I just tested the thunderhub install again with the latest script and it worked - so i will pack it up for RC2 for more community testing. If any install error occurs any error message details help.

**Comment by rootzoll** [comment]
v1.6.2RC2 is available - see: https://github.com/rootzoll/raspiblitz/issues/1785#issuecomment-734025137

**Comment by kilrau** [comment]
Couldn't find any issues.

**Comment by rootzoll** [comment]
OK closing issue for v1.6.2 release.

**Comment by openoms** [comment]
From https://t.me/thunderhub/5454:

>When logging into lnmarkets, from where is it getting the IP data? Running thunderhub on mynode, so apologies if this question is better suited for mynode. Would have thought it was running behind tor, but the "Last IP" on the lnmarkets page in thunderhub after logging in is the naked ip

The ThunderHub  service should be `torifiy`-d same as it i done with Pool: https://github.com/rootzoll/raspiblitz/blob/077ee8b6ad82d78a69c2f4ae7e493ba5dfbbfcfd/home.admin/config.scripts/bonus.pool.sh#L94

(and Loop has native proxy support)

WIP PR: https://github.com/rootzoll/raspiblitz/pull/1819

**Comment by rootzoll** [comment]
@openoms can we push the torifying of services to 1.7 where we have the milestone to go Tor by default. I want to build the final v1.6.2 release today?

**Comment by openoms** [comment]
> @openoms can we push the torifying of services to 1.7 where we have the milestone to go Tor by default. I want to build the final v1.6.2 release today?

yes absolutely. Closing this now and will follow up in another issue.
