### ISSUE TITLE
Stuck on: the Lightning service needs to scan the Blockchain

### ISSUE THREAD

**Issue by eurtnl** [raspiblitz/raspiblitz#180]
Hi, first of all i would like to thank you for the well written document and effort you put in this project!

Since a week or two i'm trying to get this work on my pi. The biggest problem i had so far was downloading a copy of the bitcoin blockchain but eventually the torrent option got me a copy of the blockchain.

So i did move on but now i'm stuck at the phase where "the lightning service needs to scan the blockchain". It does say that it can take some time, but it's scanning for two days now and i keep getting this error:

> *** Test if chainnetwork is ready ...
> 1543342443
> result()
> error(error: Could not connect to the server 127.0.0.1:8332 Make sure the bitcoind server is running and that you are connecting to the correct RPC port.)

followed by 4 or 5 lines saying something like

> 2018-11-27T18:16:26Z UpdateTip: new best=0000000000000000001d1da5bf072a8d70e88c6ae72b10c7788c369dbe662fe0 height=550764 version=0x20000000 log2_work=90.03722 tx=358195175 date='2018-11-20T00:34:10Z' progress=0.995541 cache=51.4MiB(415215txo)
> 2018-11-27T18:16:26Z UpdateTip: new best=000000000000000000056190995d325d534ad4e4ff2e8e3ad81698d0c4b13a53 height=550765 version=0x20c00000 log2_work=90.037252 tx=358195176 date='2018-11-20T00:34:37Z' progress=0.995541 cache=51.4MiB(415216txo)
> 2018-11-27T18:16:44Z UpdateTip: new best=000000000000000000180f150713e04b91bff4fb14d9d308e7897dc7ab52b95b height=550766 version=0x20000000 log2_work=90.037284 tx=358197504 date='2018-11-20T00:38:34Z' progress=0.995542 cache=51.6MiB(416720txo)
> 2018-11-27T18:17:10Z UpdateTip: new best=00000000000000000014d747cf78bca4ab72b27bfaeab50328e1bb4798a18f4b height=550767 version=0x20800000 log2_work=90.037317 tx=358198611 date='2018-11-20T00:42:26Z' progress=0.995544 cache=51.5MiB(416270txo)
> 2018-11-27T18:17:39Z UpdateTip: new best=0000000000000000000a9cbc42c697f2e019bae3fd0e9866726e15be96387db9 height=550768 version=0x20000000 log2_work=90.037349 tx=358201516 date='2018-11-20T00:50:01Z' progress=0.995547 cache=52.1MiB(421452txo)
> Waiting 1 minute and then trying again ...

So i have two questions:

1. does the "progress=0.995547" mean it's almost finished when reaching 1

2. can i ignore the testnet error (since i just want to go straight to live net)

**Comment by rootzoll** [comment]
1) yes - getting to 1 is the goal. You can see progress .. the blockchain is syncing from the downloaded state to the final actual state of the network
2) In the beginning - during setup/syncs - there can be times were the services need some time to get ready to be reachable and tresponding. We will see in the end if there is some more critical.

**Comment by eurtnl** [comment]
OK, thanks!
I'll just have to wait a little longer. That's no problem bitcoin won't leave either ;-)

**Comment by rootzoll** [comment]
I will close this issue fro now. Feel free to open up again or comment if you have further problems with this.

**Comment by eurtnl** [comment]
I'm still stuck:

> *** Test if chainnetwork is ready ...
> 1543400259
> result()
> error(error: Could not connect to the server 127.0.0.1:8332
> 
> Make sure the bitcoind server is running and that you are connecting to the correct RPC port.)
> 2018-11-28T09:51:12Z Syncing txindex with block chain from height 551729
> 2018-11-28T09:51:28Z txindex is enabled at height 551810
> 2018-11-28T09:51:28Z txindex thread exit
> 2018-11-28T09:56:23Z New outbound peer connected: version: 70015, blocks=551810, peer=65
> 2018-11-28T10:16:34Z UpdateTip: new best=0000000000000000000356f3ae64b14b601505199e1afd6921b750ce58dd8f61 height=551811 version=0x20000000 log2_work=90.070805 tx=360392682 date='2018-11-28T10:16:32Z' progress=1.000000 cache=107.8MiB(942756txo) warning='20 of last 100 blocks have unexpected version'
> Waiting 1 minute and then trying again ...
