### ISSUE TITLE
Update: Electrs 0.8.6

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#1801]
https://github.com/romanz/electrs/pull/334

**Comment by openoms** [comment]
The good thing is prometheus is not used for electrs (or anything else on RaspiBlitz AFAIK)


The bad is that the latest Electrum v4.0.5 reportedly does not connect to electrs. Did not test it yet.

**Comment by Kixunil** [comment]
Electrum 4.0.5 definitely refuses to connect to `electrs` older than https://github.com/romanz/electrs/commit/c88a0dc331eb16163276becf98fcc020565d97eb I'm recompiling to see if it works with the newest version.

**Comment by Kixunil** [comment]
Confirmed, it's fixed in master. See also https://github.com/romanz/electrs/issues/331

**Comment by romanz** [comment]
A new release is ready: https://crates.io/crates/electrs/0.8.6
Many thanks for reporting and investigating this issue!

**Comment by rootzoll** [comment]
OK update for RaspiBlitz is merged and worked on testing. Now testing recovery.

**Comment by rootzoll** [comment]
OK recovery worked - update will be part of v1.6.2 release. Closing issue.
