### ISSUE TITLE
List all my BTC addresses 

### ISSUE THREAD

**Issue by WetPuppyKisses** [raspiblitz/raspiblitz#181]
There is a way to list all my addresses?

The listaddressgroupings or listaddresses command is not working for me.

**Comment by rootzoll** [comment]
Not sure why those commands not working ... maybe best place to get an answere is in the lnd slack. --> https://lightningcommunity.slack.com

Becuase this seems no RaspiBlitz issue - i am closing it. If you get the feedback from LND slack, that its something with RaspiBlitz config, please report back. thx.
