### ISSUE TITLE
custom-install(s).sh file name (1.6.1)

### ISSUE THREAD

**Issue by adevoss** [raspiblitz/raspiblitz#1817]
When installing 1.6.1 I noticed the difference in names in the cp command.
It all works but a bit confusing. To me.
Maybe not renaming but just copy the file?

**Comment by rootzoll** [comment]
Hmmm .. I think it was was always `custom-installs.sh` (not with an underline). See FAQ on it here:
https://github.com/rootzoll/raspiblitz/blob/v1.6/FAQ.md#why-do-i-need-to-re-burn-my-sd-card-for-an-update

**Comment by adevoss** [comment]
My point is not hyphen/underline (you're right it is hyphen) but the renaming of the file.
_bootstrap.provision.sh
`line 549: sudo cp -av /mnt/hdd/app-data/custom-installs.sh /home/admin/custom-install.sh >> ${logFile}`

**Comment by adevoss** [comment]
Edited the title from underscore to hyphen.

**Comment by rootzoll** [comment]
> My point is not hyphen/underline (you're right it is hyphen) but the renaming of the file.
_bootstrap.provision.sh line 549: sudo cp -av /mnt/hdd/app-data/custom-installs.sh /home/admin/custom-install.sh >> ${logFile}

This is the script just making a work copy of that script to the admin home folder - it gets deleted in line 554 directly after excution. So main location of the script stays at `/mnt/hdd/app-data/custom-installs.sh`. Does that answere your question?

**Comment by adevoss** [comment]
Sorry, no. I know it's not a bug, it's only a minor minor thing.
On the hdd the file is called 'custom-installs.sh' (watch the s before the .) and in the /home/admin directory it is 'custom-install.sh'.
Overlooked that it got deleted afterwards. That's making it even more minor.

**Comment by rootzoll** [comment]
OK now I get your point ;) .. will mark this for v1.7 to change.

**Comment by rootzoll** [comment]
OK change done ... make final testing if custom install script still works on recovery/update.

**Comment by rootzoll** [comment]
OK final testing looks good .. will be part of v1.7 release.
