### ISSUE TITLE
[Feature Request] Add ION - Scalable Decentralised Identifiers on Bitcoin

### ISSUE THREAD

**Issue by ros-mac** [raspiblitz/raspiblitz#1818]
This would be great addition and it appears they have a point that it is most likely the missing link for Dapps

https://youtube.com/watch?v=kUb7ENx6Nyk   # a short overview

https://aka.ms/ion-beta-post    # Github etc. linked off this

**Comment by rootzoll** [comment]
The idea to add it to the RaspiBlitz you can find it already as an issue here: #1038 - it would be great if someone tries this out. On how to contribute to RaspiBlitz see here: https://www.youtube.com/watch?v=ZVtZepV3OfM

**Comment by rootzoll** [comment]
ION is now live: https://techcommunity.microsoft.com/t5/identity-standards-blog/ion-we-have-liftoff/ba-p/1441555

**Comment by ros-mac** [comment]
https://twitter.com/csuwildcat/status/1375467632602705923 # guide for 64bit Pi4
https://twitter.com/csuwildcat/status/1375159127391924226  # more info on specs

https://github.com/henkvancann/ion/tree/master/docs  # faq/Q+A

**Comment by cstenglein** [comment]
Since this project is [archived since Jul 21, 2022](https://github.com/henkvancann/ion) I'm closing this for now.
