### ISSUE TITLE
Dropbox did not do backup

### ISSUE THREAD

**Issue by AntonKlein** [raspiblitz/raspiblitz#1822]
The Dropbox did not do the backup. I did it exactly the way described here in Github.
I'm  wondering because after copying the token the StaticChannelBackup Dropbox is not selected with a  "*" (see picture below). 

Can anyone help me?  My mac is running with "HighSierra" 

![RAspi 1](https://user-images.githubusercontent.com/75214677/100547057-08767a00-3265-11eb-9e55-1ae692171141.jpeg)

**Comment by openoms** [comment]
What version of the SDcard image you are using?
Will need to achieve that to have that SCB on Dropbox option selected. Waht happens if you select it and press OK?

**Comment by AntonKlein** [comment]
> What version of the SDcard image you are using?
> Will need to achieve that to have that SCB on Dropbox option selected. Waht happens if you select it and press OK?

and here I pasted the token which was generated under "settings" in the Dropbox (and yes I copied all the letters :-) 
![rasp1 2](https://user-images.githubusercontent.com/75214677/100547740-a15ac480-3268-11eb-80ae-821456d59a02.jpeg)

**Comment by rootzoll** [comment]
Is that with a v1.6.2RC or with 1.6.1?

**Comment by AntonKlein** [comment]
It’s with 1.6.1.

Christian Rotzoll <notifications@github.com> schrieb am So. 29. Nov. 2020
um 18:21:

**Comment by rootzoll** [comment]
v1.6.2 which is close to release will have a fix for that:
https://github.com/rootzoll/raspiblitz/issues/1457

If you have a node to run tests on you can even give the release cadidate a test:
https://github.com/rootzoll/raspiblitz/issues/1785

I am closing this issue as a duplicate - please use #1457 for further report.
