### ISSUE TITLE
Losing connection to Electrs after a week of uptime. 

### ISSUE THREAD

**Issue by aeonBTC** [raspiblitz/raspiblitz#1829]
Hardware: Pi4 (4GB)
Software:  Raspiblitz 1.6.1

Ive been running a node just fine for a few months but am now noticing a problem when trying to connect to electrs.

I'm usually able to connect to my electrs server but after a week or so it stops connecting. When I open my electrum wallet it continually tries to initialize a sync but it never succeeds. 

Electrs returns the following error:

> Dec 01 03:49:11 raspberrypi electrs[3696]: 2020-12-01T03:49:11.411+00:00 - ERROR - [127.0.0.1:34054] connection handling failed: Error: failed to send {"id":13,"jsonrpc":"2.0","result":null}
Dec 01 03:49:11 raspberrypi electrs[3696]: Caused by: Broken pipe (os error 32)
Dec 01 03:49:11 raspberrypi electrs[3696]: 2020-12-01T03:49:11.411+00:00 - DEBUG - [127.0.0.1:34054] shutting down connection

If I restart my node it fixes the problem, but after another week or so the same thing starts to happen.

**Comment by rootzoll** [comment]
v1.6.2 is out that contains a electrs upadte - please try and report if you still have problems with this.

**Comment by aeonBTC** [comment]
Seems to be working fine now. Thank you.
