### ISSUE TITLE
[edge case] restarting bitcoind during the recovery process freezes

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#1830]
This is an edge case only if the recovery process starts with a new blockchain database without txindex, but BTC-RPC-Explorer enabled.
On activating `txindex` and restarting bitcoind the process freezes same as with the `blockfilterindex` in :https://github.com/rootzoll/raspiblitz/issues/1699
```
# *** INSTALL BTC-RPC-EXPLORER ***
nodeJS is already installed
Installed nodeJS v14.15.0
switching txindex=1 and restarting bitcoind
```
Ran
`sudo systemctl stop bitcoind`
manually for the process to continue.
```
Job for bitcoind.service canceled.
```

**Comment by rootzoll** [comment]
PR merged for v1.7 ... final testing
