### ISSUE TITLE
nginx: command not found after updating to v1.6.2

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#1834]
From https://t.me/raspiblitz/45313
![image](https://user-images.githubusercontent.com/43343391/100859734-8023ef00-3487-11eb-8764-e4f89681f619.png)

>getting this when checking electrs from the menu, tried uninstall, re-install already
$ sudo nginx -t
sudo: nginx: command not found
perhaps nginx wasn't installed during the update process

Running:
`sudo apt install nginx`
and
`restart`
fixed the issue.

**Comment by nyxnor** [comment]
Maybe check for important services being uninstalled with the background.sh script and then installing them again.

**Comment by openoms** [comment]
this has been probably an uncomplete recovery, nginx  is not uninstalled during any setup step.
Also no further reports of this so closing.
