### ISSUE TITLE
bitcoind didn't start after upgrade to 1.6.2 / duplicate entries in bitcoin.conf

### ISSUE THREAD

**Issue by ghijg** [raspiblitz/raspiblitz#1838]
After updating my raspiblitz from 1.6.0 to 1.6.2 bitcoind could not be started. 

I found duplicate entries in bitcoin.conf. After cleaning up manually everything was working fine.

Terminal was showing this:
![raspiblitz-update-bitcoind-error](https://user-images.githubusercontent.com/70027324/101091167-1820f600-35b8-11eb-99c3-aaf08778875b.png)

debug.log was showing this message:
> Error: Error loading wallet wallet.dat. Duplicate -wallet filename specified.

Here's my bitcoin.conf with duplicate entries:
[bitcoin.conf-double-entries-after-update.txt](https://github.com/rootzoll/raspiblitz/files/5639151/bitcoin.conf-double-entries-after-update.txt)

**Comment by rootzoll** [comment]
Thanks for the report - maybe a config health check for bitcoin, lnd & raspiblitz configs makes sense for future versions.
