### ISSUE TITLE
Update to v1.6.2 wiped out Specter and electrs fails to start

### ISSUE THREAD

**Issue by shawnyeager** [raspiblitz/raspiblitz#1842]
So, my Specter config is gone – devices and wallets.

And electrs isn't starting with the following:

```
Dec 04 22:12:23 raspberrypi systemd[1]: Started Electrs.
Dec 04 22:12:23 raspberrypi systemd[7819]: electrs.service: Failed to execute command: No such file or directory
Dec 04 22:12:23 raspberrypi systemd[7819]: electrs.service: Failed at step EXEC spawning /home/electrs/electrs/target/release/electrs: No such file or directory
Dec 04 22:12:23 raspberrypi systemd[1]: electrs.service: Main process exited, code=exited, status=203/EXEC
Dec 04 22:12:23 raspberrypi systemd[1]: electrs.service: Failed with result 'exit-code'.
Dec 04 22:13:23 raspberrypi systemd[1]: electrs.service: Service RestartSec=1min expired, scheduling restart.
Dec 04 22:13:23 raspberrypi systemd[1]: electrs.service: Scheduled restart job, restart counter is at 1.
Dec 04 22:13:23 raspberrypi systemd[1]: Stopped Electrs.
Dec 04 22:13:23 raspberrypi systemd[1]: Started Electrs.
Dec 04 22:13:23 raspberrypi systemd[1]: electrs.service: Main process exited, code=exited, status=203/EXEC
Dec 04 22:13:23 raspberrypi systemd[1]: electrs.service: Failed with result 'exit-code'.
Dec 04 22:14:23 raspberrypi systemd[1]: electrs.service: Service RestartSec=1min expired, scheduling restart.
Dec 04 22:14:23 raspberrypi systemd[1]: electrs.service: Scheduled restart job, restart counter is at 2.
Dec 04 22:14:23 raspberrypi systemd[1]: Stopped Electrs.
Dec 04 22:14:23 raspberrypi systemd[1]: Started Electrs.
Dec 04 22:14:23 raspberrypi systemd[13427]: electrs.service: Failed to execute command: No such file or directory
Dec 04 22:14:23 raspberrypi systemd[13427]: electrs.service: Failed at step EXEC spawning /home/electrs/electrs/target/release/electrs: No such file or directory
Dec 04 22:14:23 raspberrypi systemd[1]: electrs.service: Main process exited, code=exited, status=203/EXEC
Dec 04 22:14:23 raspberrypi systemd[1]: electrs.service: Failed with result 'exit-code'.
Dec 04 22:14:56 raspberrypi systemd[1]: Stopped Electrs.
```

**Comment by shawnyeager** [comment]
Using Fully Noded, I can still see the wallets (perhaps obvious, as they're via Bitcoin Core), but I'm now unsure if and how to best restore within Specter. I do have the PDF exports.

Any ideas, @stepansnigirev?

**Comment by rootzoll** [comment]
About electrs please try an off/on under SERVICES again. About specter what wallets did you set .. @openoms can you take a second look?

**Comment by openoms** [comment]
Looks like the recovery process did not finish running or the SDcard has failed. 
Would flash again an monitor the recovery log for errors.
Specter is storing the wallets on the disk inside the bitcoin directory.

**Comment by shawnyeager** [comment]
Thanks, @rootzoll. Uninstalled and reinstalled electrs; that worked. 

Regarding wallets, not sure I follow the question. I had added one ColdCard and two wallets to it.

**Comment by shawnyeager** [comment]
@openoms The wallets are there. As noted above, I can see them via Fully Noded. However, they're gone within Specter.

**Comment by openoms** [comment]
Reinstall Specter too.

Actually now I am not sure if reinstalling Specter would pick up the wallets automatically from the bitcoin directory. 
It might need other data as well which is stored on the SDcard? 
@k9ert shall we make a data directory for Specter on the disk to preserve settings during Sdcard updates?

@shawnyeager in the meantime if you copy out the Specter wallets and devices from the bitcoin dir to the machine where you open the Specter GUI you can import them back in the settings.

**Comment by shawnyeager** [comment]
I used a brand new SD card for 1.6.2. I still have my card with 1.6.1. Could I retrieve the Specter config from there?

**Comment by openoms** [comment]
Boot with 1.6.1 make a Specter backup from the Specter settings, restore in 1.6.2.(it is ok the LND channel states are on the disk and no major version jump between the two.)

**Comment by shawnyeager** [comment]
Thanks, @openoms. I was able to boot into 1.6.1 and export my Specter backup, then restore under 1.6.2. However, when booting back into 1.6.2, LND is failing to start after repeated reboots.

```
****************************************
* The LND service is not running.
****************************************
If you just started some config/setup, this might be OK.

8 RESTARTS DETECTED - LND might be in a error loop
Dec 05 21:10:03 raspberrypi lnd[31981]: dial tcp 127.0.0.1:9050: connect: connection refused
Dec 05 21:11:03 raspberrypi lnd[3773]: dial tcp 127.0.0.1:9050: connect: connection refused
err='Tor tcp connection refused'
More Error Detail:
err='Tor tcp connection refused'

-> Use command 'repair' and then choose 'BACKUP-LND' to make a just in case backup.
-> Use command 'debug' for more log output you can use for getting support.
-> Use command 'menu' to open main menu.
-> Have you tried to turn it off and on again? Use command 'restart'

admin@raspberrypi:~ $
```

Full debug log here: https://termbin.com/0gzmz

I do have an LND backup. What's my best course of action, please?

**Comment by openoms** [comment]
Tor failed which can debugged or updated , but the easiest option is to flash the v1.6.2 image fresh.

**Comment by rootzoll** [comment]
PR merged. Putting on final testing. @openoms what is the smallest "fuction test" to check that the persitent data between updates is working?

**Comment by openoms** [comment]
if a device is added and a wallet is created it should be restored after reinstall and SDcard change also

**Comment by rootzoll** [comment]
test looked good. closing issue for v1.6.3 release
