### ISSUE TITLE
RTL Loop error "HTTP request to an HTTPS server"

### ISSUE THREAD

**Issue by afcreamer** [raspiblitz/raspiblitz#1852]
Hello,

I've had trouble loading loop  in RTL and could not find other reports of this issue.

Raspiblitz v1.6.2
Loop 0.11.1-beta
RTL 0.9.3-beta

ERROR: Loop(327) => List Swaps Error: {"name":"StatusCodeError","statusCode":400,"message":"400 - \"Client sent an HTTP request to an HTTPS server.\\n\"","error":"Client sent an HTTP request to an HTTPS server.\n","options":{"url":"http://localhost:8081/v1/loop/swaps","rejectUnauthorized":

**Comment by rootzoll** [comment]
Do you get the same error if you call RTL with `https://[LOCALIP]:3001` and `http://[LOCALIP]:3000`?

**Comment by afcreamer** [comment]
Yes I just attempted it again on both and had the same result.

**Comment by softsimon** [comment]
I have the same problem. Ride The Lightning can't connect to Loop after latest upgrade.

> Do you get the same error if you call RTL with `https://[LOCALIP]:3001` and `http://[LOCALIP]:3000`?

Same problem using RTL from HTTP (http://raspberrypi.local:3000) as HTTPS (https://raspberrypi.local:3001)

**Comment by openoms** [comment]
Just noting that you can always downgrade to the tested, working version by reinstalling from SERVICES.

Will need to investigate this with the RTL team I think, probably something with the API changed and might need to upgrade Loop too and adapt the config.

**Comment by marssystems** [comment]
This was solved by the RTL team back in October.

https://github.com/Ride-The-Lightning/RTL/issues/515

**Comment by openoms** [comment]
OK, PR incoming:
This fixes the HTTPS issue:
```
source /mnt/hdd/raspiblitz.conf

sudo cp /home/rtl/RTL/sample-RTL-Config.json /home/admin/RTL-Config.json
    sudo chown admin:admin /home/admin/RTL-Config.json
    sudo chmod 600 /home/admin/RTL-Config.json || exit 1
    PASSWORD_B=$(sudo cat /mnt/hdd/${network}/${network}.conf | grep rpcpassword | cut -c 13-)
    # modify sample-RTL-Config.json and save in RTL-Config.json
    sudo node > /home/admin/RTL-Config.json <<EOF
//Read data
var data = require('/home/rtl/RTL/sample-RTL-Config.json');
//Manipulate data
data.nodes[0].lnNode = '$hostname'
data.nodes[0].Authentication.macaroonPath = '/home/rtl/.lnd/data/chain/${network}/${chain}net/';
data.nodes[0].Authentication.configPath = '/home/rtl/.lnd/lnd.conf';
data.multiPass = '$PASSWORD_B';
data.nodes[0].Settings.userPersona = 'OPERATOR'
data.nodes[0].Settings.channelBackupPath = '/home/rtl/RTL-SCB-backup-$hostname'
data.nodes[0].Settings.swapServerUrl = 'https://localhost:8081'
//Output data
console.log(JSON.stringify(data, null, 2));
EOF
    sudo rm -f /home/rtl/RTL/RTL-Config.json
    sudo mv /home/admin/RTL-Config.json /home/rtl/RTL/
    sudo chown rtl:rtl /home/rtl/RTL/RTL-Config.json
 ```

**Comment by openoms** [comment]
Now getting the error about the macaroon path, but the Loop macaroon authentication is not in RTL v0.9.3, so will need to wait for the next release, use RTL master or downgrade Loop to v0.9.0: https://github.com/lightninglabs/loop/releases


Macaroon auth is in:
https://github.com/Ride-The-Lightning/RTL/pull/543

RTL v0.10.0 seems to be close: https://github.com/Ride-The-Lightning/RTL/milestone/20

**Comment by rootzoll** [comment]
RTL 0.10.0 released TODO: Add to v1.6.3 release.
https://twitter.com/RTL_App/status/1340815355959267329?s=20

**Comment by rootzoll** [comment]
PR merged. On final testing.

**Comment by rootzoll** [comment]
testing looks good. closing for v1.6.3 release.
