### ISSUE TITLE
Add terminology definitions to Raspiblitz documentation

### ISSUE THREAD

**Issue by gked** [raspiblitz/raspiblitz#1853]
Could you please add terminology definitions for the screenshot below so that new comers understand the numbers displayed in 

Capacity - 
Commit Fee - 
Local - 
Remote - 
Base - 
PerMil - 

**There was also a proposal to add tooltips for these in RTL.**

![image](https://user-images.githubusercontent.com/12704474/101531757-8a8f2e80-3948-11eb-8253-96dae6524012.png)

**Comment by rootzoll** [comment]
You can make that terminology definitions here and I can add them to the script.

**Comment by gked** [comment]
@rootzoll I don't have all of the definitions. This was partially why I wanted to see them to be correctly defined in the app.
So, if someone else can vet what I have for correctness and completeness then I think, we could add them.
Anyways, this is what I have:

- Capacity - total sats in the channel (their side + your side)
- Commit Fee - the fee that's charged if either side of the channel closes (changes depending on fee market)
- Local - sats on your side of the channel (outbound liquidity)
- Remote - sats on their side of the channel (inbound liquidity)
- Base-Fee - fixed fee (in millisatoshis) per forwarding on this channel
- PerMil - amount based fee (in millisatoshis per 1 satoshi) on forwarding on this channel

**Comment by rootzoll** [comment]
Base is the "Base-Fee" (millisatohis) you charge for every forwarding on that channel.

**Comment by gked** [comment]
> Base is the "Base-Fee" (millisatohis) you charge for every forwarding on that channel.

Thanks, I updated Base-Fee definition. PerMil is the only definition left,

**Comment by rootzoll** [comment]
I updated for "PerMil" and wil add to the script output

**Comment by rootzoll** [comment]
@gked changes comitted. You can test them with command MENU > PATCH > PATCH-MENU > BRANCH > set to `1853channelinfo` ... after that when you go back it should output the additional info.

**Comment by gked** [comment]
@rootzoll just tested it and verified. Thanks!

**Comment by rootzoll** [comment]
Merged. Closing for release.
