### ISSUE TITLE
Seed phrase is left behind in file .seed.temp when a new LND wallet is created from the menu

### ISSUE THREAD

**Issue by mmarsalko** [raspiblitz/raspiblitz#1857]
This could happen due to a loss of power or from ctrl-c'ing out during setup. Haven't tried reproducing this myself, but I'd noticed my seed phrase was in the file /home/admin/.seed.tmp.

I'd recommend putting important temporary files like this in /tmp so they disappear when power is lost or when the system reboots.

**Comment by softsimon** [comment]
I too had the file `/home/admin/.seed.tmp` present containing my correct seed phrase.

As far as I am aware I didn't do a incomplete setup. I did a regular step by step successful install of v1.6.1

**Comment by tomstammis** [comment]
Looks to be the same for me. Seed is present, have not ctrl+c'ed out of the setup process, iirc.

**Comment by rootzoll** [comment]
Thanks for the report. For v1.7 we will have a refactor of the setup process ... will add this issue as a reminder to move any setup related data to memory-based temp storage.

**Comment by openoms** [comment]
Seems that the seed if left behind if displayed correctly and only deleted if there are no 24 words displayed:
https://github.com/rootzoll/raspiblitz/blob/64ee445b251ad3f59609e5f3cbcb24cd0e7ce664/home.admin/70initLND.sh#L202

All who generated the seed on the current SDcard should run:
`shred -u /home/admin/.seed.tmp`
to delete it safely.

Check again:
`sudo find / -name .seed.tmp`

To be clear the file sitting there is only accessible via SSH (encrypted tunnel) and access is secured by the PasswordA and/or the ssh keys + fail2ban to prevent brute forcing.

The master private key is also encoded in the lnd wallet.db which is encrypted and protected  by the PasswordC (unless you use autounlock accepting the warnings)

Be mindful of the content of old SDcards kept around too (format them).

Described here as well: https://t.me/RaspiBlitzFAQ/191

**Comment by gked** [comment]
+1 I was able to locate the file as well. Also went through the normal install process.
@openoms thanks for providing work around.

**Comment by MiBy0815** [comment]
The issue description is kind of misleading, IMHO. Various people have confirmed this to happen without any interruption of the setup process

**Comment by openoms** [comment]
@rootzoll this might worth a v1.6.3 build with no strong recommendation to update, but it would solve the issue for new users setting up the LND wallet the first time with the fresh image

**Comment by rootzoll** [comment]
I haven opened a v1.6.3 release milestone and added this to be fixed.

**Comment by rootzoll** [comment]
OK the branch 1857seeddelete contains a fix that makes sure the seed file gets deleted and moves it even to the RaspiBlitz RAM disk so that even after shredding it should leave no trace behind.

To be final tested and team discussed.

**Comment by rootzoll** [comment]
OK this looks good on testing now - will be part of 1.6.3 - closing issue.
