### ISSUE TITLE
Improve logs on Sphinx Relay

### ISSUE THREAD

**Issue by gonzaloaune** [raspiblitz/raspiblitz#1860]
Hey @rootzoll, I was looking into the problems people are having with Sphinx Relay and noticed the logs are not being sent to nginx. I'm not very familiar on how to do it but I was able to send it to `/var/log/daemon.log` by changing this line:

https://github.com/rootzoll/raspiblitz/blob/v1.6/home.admin/config.scripts/bonus.sphinxrelay.sh#L368

To

```
StandardOutput=stdout
```

Alternatively, you can send it to the nginx logs doing:

```
StandardOutput=file:/var/log/nginx/access_sphinxrelay.log
```

Same can be done for stderr.

This at least will help people debug the errors they're having. The problem seems to be node's console.log where it sends it directly to stdout, but from there to nginx, again, no idea.

**Comment by rootzoll** [comment]
Done. PR merged. Will be part of v1.6.3 release.
