### ISSUE TITLE
Sphinx App Connection

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#1862]
Go the following report on Telegram:

```
For people having problem connecting with Raspiblitz, I saw some cases where Relay finished the setup but Sphinx doesn't know about it, might have been because of slow connection or Tor problems, I'm not sure.

The solution, if you're not worried about your Sphinx DB which you shouldn't because you never used it, is to run the following commands

sudo mv /mnt/hdd/app-data/sphinxrelay/sphinx.db /mnt/hdd/app-data/sphinxrelay/old-sphinx.db

sudo systemctl restart sphinxrelay

That will move the sphinx db to a new file so it gets recreated when restarted

After this a new connection string will be created so you need to do the following to see it again:

/home/admin/config.scripts/bonus.sphinxrelay.sh status
If that doesn’t work for you, let me know
```

My first guess: Could it be that the HTTP request to the Relay is kind of cached and because its not working on first try (when relay is not ready) it also does not work on following calls (because the cached request result is send)? That would explain why a reset of the DB might fix this, because it creates a new secret string and the next request from the App will be done with a fresh URL that was never cached before.

The question on this might then be: "Where does the Caching happen?"
- On the Sphinx App side?
- On the IP2Tor somehow?
- On the nginx reverse HTTPS Proxy?
- On the Sphinx Relay Server?

@frennkie can we rule out any caching on the IP2Tor & ngnix side?

**Comment by gonzaloaune** [comment]
This might be a race condition as well or the iOS app (not sure about Android) not waiting enough for the request to finish. I've seen this happening before where:

- iOS App sends request
- Relay takes too long to finish the request and sends back the info
- iOS App already timed out and assumed the setup process failed

Now iOS App and Relay know 2 different things, I talked to Tom (the iOS app dev) about this issue and we found a way for the mobile apps to at least retry in that case so this might not be an issue in the future. I think this is purely a communication problem between Mobile <> Relay

**Comment by rootzoll** [comment]
Connections over IP2Tor and a home hosted node on a RPi take some time .. its a diffent beast then testing against a server in the cloud or in your own computer - so race conditions could be a good point to look at too @gonzaloaune also a more detailed error message on iOS when the connection is not happening would also be helpfull.

**Comment by rootzoll** [comment]
Make sure to have and install the latest Sphinx Relay Server for v1.6.3 release.

**Comment by rootzoll** [comment]
OK Sphinx is always installing the latest master from server - so no need for an update at the moment:
https://github.com/rootzoll/raspiblitz/blob/9210987ebba272780eb538c15c5fcef6f5abecc8/home.admin/config.scripts/bonus.sphinxrelay.sh#L321

The Sphinx Relay is now writing its standard out to the journal service and is listed on debug out.
Should be fine for final testing.

**Comment by The34Goon** [comment]
Trying to update my IP2TOR subscription for Sphinx I get this error:

### Exception on Subscription

Unknown Error happened - please report to developers: ('letsancrypt acme failed', "# preparing DUCKDNS 
 creating certs for XXXX.XXXX.XXX
[Mon 11 Jan 20:46:50 CET 2021] Creating domain key 
[Mon 11 Jan 20:46:50 CET 2021] The domain key is here: /mnt/hdd/app-data/letsencrypt/certs/XXXX.XXXX.XXX_ecc/XXXX.XXXX.XXX.key
[Mon 11 Jan 20:46:50 CET 2021] Single domain='XXXX.XXXX.XXX'
[Mon 11 Jan 20:46:50 CET 2021] Getting domain auth token for each domain
[Mon 11 Jan 20:46:53 CET 2021] Getting webroot for domain='XXXX.XXXX.XXX'
[Mon 11 Jan 20:46:53 CET 2021] Adding txt value: XXXXXXXXXYYYYYYYYYYYYYZZZZZZZZZ for domain:  _acme-challenge.XXXX.XXXX.XXX
[Mon 11 Jan 20:46:53 CET 2021] Trying to add TXT record
[Mon 11 Jan 20:46:54 CET 2021] Errors happened during adding the TXT record, response=KO
[Mon 11 Jan 20:46:54 CET 2021] Error add txt for domain:_acme-challenge.XXXX.XXXX.XXX
[Mon 11 Jan 20:46:54 CET 2021] Please add '--debug' or '--log' to check more details.
[Mon 11 Jan 20:46:54 CET 2021] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
ls: cannot access '/mnt/hdd/app-data/letsencrypt/certs/XXXX.XXXX.XXX_ecc//fullchain.cer': No such file or directory
error='acme failed'
")

**Comment by rootzoll** [comment]
@frennkie can you a reason why the acme script fails to work of accessing the cert?

**Comment by m00ninite** [comment]
Any idea what the deal is here? I'm able to get Sphinx to connect briefly, but then it just ends up stuck the next time I open the app.

> Mar 15 03:56:52 raspberrypi env[7092]: => [socket.io] connected!
Mar 15 03:56:53 raspberrypi env[7092]: -> 2021-03-15 03:56:53: GET /balance 200 297ms
Mar 15 03:56:53 raspberrypi env[7092]: -> 2021-03-15 03:56:53: GET /msgs?offset=0&limit=200&date=2021-03-15%2003:54:00 404 4ms
Mar 15 03:56:53 raspberrypi env[7092]: -> 2021-03-15 03:56:53: GET /msgs?offset=0&limit=200&date=2021-03-15%2003:54:00 404 8ms
Mar 15 03:56:54 raspberrypi env[7092]: -> 2021-03-15 03:56:54: GET /msgs?offset=0&limit=200&date=2021-03-15%2003:54:00 404 8ms
Mar 15 03:56:55 raspberrypi env[7092]: -> 2021-03-15 03:56:55: GET /msgs?offset=0&limit=200&date=2021-03-15%2003:54:00 404 13ms
Mar 15 03:56:55 raspberrypi env[7092]: -> 2021-03-15 03:56:55: GET /msgs?offset=0&limit=200&date=2021-03-15%2003:54:00 404 12ms
Mar 15 03:56:56 raspberrypi env[7092]: -> 2021-03-15 03:56:56: GET /msgs?offset=0&limit=200&date=2021-03-15%2003:54:00 404 10ms

**Comment by gonzaloaune** [comment]
Are you running the latest version of Sphinx on your phone and also the latest version of Relay? @m00ninite

**Comment by m00ninite** [comment]
@gonzaloaune The app is up to the latest on iOS app store.. the relay, I'm not sure. I just installed it this weekend via the raspiblitz menu. If it's grabbing the latest code off github, I'd assume it's the latest, or at least very recent.

Edit: just checked the repo on my blitz.. looks like it's on v1.1.3? That seems rather old.  Tried updating to checking out v2.0.3 and the service wouldn't even start, so I switched back.

**Comment by m00ninite** [comment]
Ok, I ended up using raspiblitz's built-in update mechanism for sphinx-relay and it fixed it. Go figure :)

**Comment by rootzoll** [comment]
OK for the next release RaspiBlitz will now check if the connection string has already been used and recommends actions to act on (export keys, deinstall/reinstall to also get to latest release tag version & updating server URL). This might not fix every issue repoerted here - but please if you find further issues on testing upcomming 1.7RC1 and above please open a fresh issue so that we can keep a better overview. 

Closing this issue and will do further final testing on #2089
