### ISSUE TITLE
Orientation for "some long time" - final Blockchain Sync

### ISSUE THREAD

**Issue by son-y** [raspiblitz/raspiblitz#187]
I'm at the point of "Waiting for final Blockchain Sync".
It says "this can take some long time". At the moment I'm waiting longer than the FTP Download of the blockchain took - about 20 hours.
What is the orientation time this progress should take?

This is what it shows up to me:
![grafik](https://user-images.githubusercontent.com/45509868/49338593-58dd8180-f623-11e8-9dde-bd932d94113b.png)
Does the number after progress mean >99%?

I know, my issue is really near to the #121 - but can you tell me how long I have to wait to end this final sync?

**Comment by son-y** [comment]
Sorry to say that I was just to eager! I waited some more hours and now everything is synced!

To the world: Wait some minutes and trust the work of rootzoll 💃

**Comment by rootzoll** [comment]
OK thanks - but:  dont trust, verify ;)

**Comment by pkclyoni** [comment]
Hi,

I'm currently at the same stage and I understand the final sync will take some time. But would just like to confirm if several observations are normal.
i) Sync progress oscillating around approx. 99.9999xxx % for past 5 days
ii) Bytes going into the pi amount to only approx. 10MB for the same time period (5 days)
Running on a 5400RPM hdd, and on 10Mbs broadband.

Slightly technically challenged here and would appreciate some help.

**Comment by fluidvoice** [comment]
```
ssh admin@yournode
tail -f /mnt/hdd/bitcoin/debug.log
```

**Comment by pkclyoni** [comment]
As soon as I ssh in, my passwords (A+C) are requested and subsequently after entering them, the sync screen appears. When/where do I enter the line ‘tail -f /mnt/hdd/bitcoin/debug.log’?

I should add that I am running a litecoin alongside the lightning node. Sorry it wasn’t mentioned before

**Comment by fluidvoice** [comment]
cancel out of the menu system. Hit ctrl+c if you need to.

**Comment by pkclyoni** [comment]
got it. 

but the debug.log content seems overwhelming. Anything in particular do you need me to weed out for your viewing?

**Comment by fluidvoice** [comment]
as long as your sync progress has increased from what it was above, 0.993816303, and keeps increasing until 1.000000 you're prob fine. You might just have a slow connection.

**Comment by pkclyoni** [comment]
A quick run through the log, and I can see multiple times (over a number of days) where I've had a progress of 1.000000. And yet on the sync display it remains fluctuating at 99.9999xx. Should this be a concern? (e.g. does each progress to 1.000000 only indicate the progress for a single block rather than the entire chain?)

**Comment by fluidvoice** [comment]
Not sure. Can you fund your wallet, connect to nodes, and open channels? If so then prob not.

**Comment by pkclyoni** [comment]
Is it normal for the progress to be stuck at 1.000000 after each update in debug.log, yet the progress is displayed as 99.9999xxx?

**Comment by fluidvoice** [comment]
I don't know. But again, if it's functioning correctly - connections, open channels, fund wallet, etc., then I'd not worry about it. I've seen on the LCD display my node slow down, lose sync at times, then some minutes later it catches back up again and everything is displayed as normal.

**Comment by rootzoll** [comment]
Flipping between 0.99999.. and 1.0 is absolutly fine, because thats the usual blockchain keeping up with the lastest blocks. 

The RaspiBlitz just needs a sync close to 1.0 and finally the LND service needs to respond on the `lncli getinfo` cammand with a `synced_to_chain: true`

**Comment by pkclyoni** [comment]
> Flipping between 0.99999.. and 1.0 is absolutly fine, because thats the usual blockchain keeping up with the lastest blocks.

Got it.

> The RaspiBlitz just needs a sync close to 1.0 and finally the LND service needs to respond on the lncli getinfo cammand with a synced_to_chain: true

At the current stage, this returns '[lncli] unable to read macaroon path (check the network setting!): open /home/admin/.lnd/data/chain/bitcoin/mainnet/admin.macaroon: no such file or directory'

Images below taken at my current stage. Including them for reference.
<img width="1156" alt="screenshot 2019-01-10 at 11 43 22 pm" src="https://user-images.githubusercontent.com/46291152/50981283-96dc9800-1535-11e9-869e-25dedb9afb0c.png">
![img_3422](https://user-images.githubusercontent.com/46291152/50981365-cbe8ea80-1535-11e9-83a2-612b6155c66b.jpg)

**Comment by theotherside** [comment]
How long should it typically take to go from 0-100? Running the latest version from a reformatted HDD with raspberry Pi 3. What can affect the speed?

**Comment by rootzoll** [comment]
@pkclyoni try to run the lncli as bitcoin user with:
`sudo -u bitcoin lncli getinfo`
normally the admin should ne able to call lncli also correctly, but something seemed to got messed up. I would advise at some point (best when next release comes out) to run the update with a fresh sd card - see: https://github.com/rootzoll/raspiblitz/blob/master/FAQ.md#how-to-update-my-raspiblitz-after-version-098

**Comment by rootzoll** [comment]
@theotherside going from 0-100 means the RaspiBlitz syncs the complete blockchain from other bitcoin-nodes itself (what is possible as the SYNC option during setup). But this will take you a long time (multiple days/weeks) because the raspberry has very low CPU power. Its just a method of last resort.

**Comment by pkclyoni** [comment]
> try to run the lncli as bitcoin user with:
sudo -u bitcoin lncli getinfo

this returns a similar message:
'[lncli] unable to read macaroon path (check the network setting!): open /home/bitcoin/.lnd/data/chain/bitcoin/mainnet/admin.macaroon: no such file or directory'

> going from 0-100 means the RaspiBlitz syncs the complete blockchain from other bitcoin-nodes itself (what is possible as the SYNC option during setup). But this will take you a long time (multiple days/weeks) because the raspberry has very low CPU power. Its just a method of last resort.

is it possible to increase the sync speed? (e.g. specifically selecting which nodes to sync from; also read somewhere that adjusting db cache might help)

**Comment by rootzoll** [comment]
> is it possible to increase the sync speed?

Thats why the RaspiBlitz offers download of a prepared blockchain via torrent or ftp if you start with an empty HDD. 

> this returns a similar message:
> '[lncli] unable to read macaroon path (check the network setting!): ...

something is messed up ... I would advise at some point (best when next release comes out) to run the update with a fresh sd card - see: https://github.com/rootzoll/raspiblitz/blob/master/FAQ.md#how-to-update-my-raspiblitz-after-version-098

**Comment by pkclyoni** [comment]
Hi, just an update to confirm if behaviour is still normal. I seem to be keeping up with the latest blocks and yet I'm still stuck at 'waiting for final blockchain sync'

<img width="1176" alt="screenshot 2019-02-10 at 5 17 14 pm" src="https://user-images.githubusercontent.com/46291152/52531931-efcb6600-2d57-11e9-9764-d156c6f5386f.png">

**Comment by rootzoll** [comment]
@pkclyoni did it catched up finally? If its still not coming up - it seems that lnd is not running or looping restarting. I that case debug logs would be helpfull: /home/admin/XXdebugLogs.sh

**Comment by pkclyoni** [comment]
This is what I got from XXdebugLogs.sh:
<img width="798" alt="screenshot 2019-02-15 at 8 27 42 pm" src="https://user-images.githubusercontent.com/46291152/52856819-67d2cb00-3160-11e9-84d7-cb72596b6683.png">
<img width="795" alt="screenshot 2019-02-15 at 8 26 21 pm" src="https://user-images.githubusercontent.com/46291152/52856824-6a352500-3160-11e9-9db7-e5b3818d1fb1.png">

what's next?

**Comment by rootzoll** [comment]
Thats odd .. first your litecoind was running and now it seems to fail on starting up. XXdebugLogs.sh should also print the last logs from litecoind ... can you see any error/warning in there?

**Comment by pkclyoni** [comment]
> XXdebugLogs.sh should also print the last logs from litecoind

Is this what you mean by litecoind logs:
<img width="1318" alt="screenshot 2019-02-15 at 10 29 17 pm" src="https://user-images.githubusercontent.com/46291152/52862866-3ca4a780-3171-11e9-999a-ea6f0a804465.png">

They were there, but since I didn't see anything different from the logs posted in my previous posts, I just left it out.

**Comment by rootzoll** [comment]
To recap: The systemd says its failing in starting the litecoind, but in the logs you see its working/running?

Hmmm .. could be that there is already a litecoind running and systemd cannot start a second one? Have you tried a reboot `sudo shutdown -r now`?

If this is not resolving. I would try with a fresh v1.0 sd card image. You can keep the already downloaded blockchain but delete the rest from the HDD with: ./XXcleanHDD.sh ... like you would update an old version - here in the FAQ starting at step3: https://github.com/rootzoll/raspiblitz/blob/master/FAQ.md#how-to-update-a-old-raspiblitz-before-version-098

**Comment by rootzoll** [comment]
Preview image of v1.0 can be downloaded here: wiki.fulmo.org/downloads/raspiblitz-v1.0-2019-02-14.img.zip

**Comment by pkclyoni** [comment]
> The systemd says its failing in starting the litecoind, but in the logs you see its working/running?

looks like it :-)

> Hmmm .. could be that there is already a litecoind running and systemd cannot start a second one? Have you tried a reboot `sudo shutdown -r now`?
If this is not resolving. I would try with a fresh v1.0 sd card image. You can keep the already downloaded blockchain but delete the rest from the HDD with: ./XXcleanHDD.sh ... like you would update an old version - here in the FAQ starting at step3: https://github.com/rootzoll/raspiblitz/blob/master/FAQ.md#how-to-update-a-old-raspiblitz-before-version-098

will give this a try and get back.

> it seems that lnd is not running or looping restarting

so no signs that this is the issue then?

**Comment by pkclyoni** [comment]
Here's the result from XXdebugLogs.sh after running `sudo shutdown -r now`:
<img width="1988" alt="screenshot 2019-02-15 at 10 59 54 pm" src="https://user-images.githubusercontent.com/46291152/52864666-9313e500-3175-11e9-9dbf-6e1aa4ab443b.png">

**Comment by rootzoll** [comment]
Yeah shutdown/restart was not fixing it .. would go for the fresh  fresh v1.0 sd card image - you can download a preview of the v1.0 image here: wiki.fulmo.org/downloads/raspiblitz-v1.0-2019-02-14.img.zip

**Comment by pkclyoni** [comment]
Everything works after updating to v1.0. Thanks for being so patient.
