### ISSUE TITLE
Unable to copy blockchain from laptop on win7 via SCP

### ISSUE THREAD

**Issue by maaxxyy** [raspiblitz/raspiblitz#1870]
Hi as described above, it took 9 days to copy the blockchain to my laptop (win7), now i am finding it near impossible to transfer the files via scp, I can ssh into my pi with out any issues. I have also installed winSCP and all i get is a permission error. 
I'll post some screen shots  shortly to explain my issue more in depth. Thanks

**Comment by rootzoll** [comment]
Are you running an RaspberryPi3 or a 4? Are you using the latest v1.6.2 release?

**Comment by maaxxyy** [comment]
Hi i'm using pi 3 b+, using v1.6.1 release. 
How do you run v1.6.2? The file when downloaded is 52mb and not a image file to burn to sd card like v1.6.1.

**Comment by rootzoll** [comment]
I just tested again ... its a 2.3GB file that is a disk image:
https://github.com/rootzoll/raspiblitz#downloading-the-software

**Comment by maaxxyy** [comment]
Ah right i was looking at the releases on the right hand of the front page, i'll download this and see how i get on, thanks.

**Comment by maaxxyy** [comment]
Hi just flashed the new software to sd card, running into the same problem when trying to run - 
scp -r ./chainstate ./blocks bitcoin@192.168.0.51:/mnt/hdd/bitcoin
scp is not recognised as a internal or external command, operable 
I have putty, pscp.exe and winscp installed but not able to transfer the files.
If i try winscp i get this error - scp: /home/bitcoin/blocks: Permission denied
When trying to drag and drop the files.

got it running by executing this - 
pscp -scp -r -P 22 ./chainstate ./blocks bitcoin@192.168.0.51:/mnt/hdd/bitcoin

**Comment by rootzoll** [comment]
I dont have a WIndows 7 to test it with ... please let me know if that woked with "pscp -scp -r -P 22 ./chainstate ./blocks bitcoin@192.168.0.51:/mnt/hdd/bitcoin" would be good to add that info to the script.

**Comment by maaxxyy** [comment]
Yes that worked, its downloading right now. I ssh into pi on my win7 laptop (where i have installed bitcoin core), then opened a new terminal and wrote -
pscp -scp -r -P 22 ./chainstate ./blocks bitcoin@192.168.0.51:/mnt/hdd/bitcoin

I also installed putty, winscp and pscp.exe to get to the above solution (you may not need to install winscp)
This will take a few hours to complete.

**Comment by nyxnor** [comment]
@maaxxyy Good that is worked. Please clos this issue.
