### ISSUE TITLE
Set fee for closing channel

### ISSUE THREAD

**Issue by chacham18** [raspiblitz/raspiblitz#188]
Hi guys,

I've been using the raspiblitz and it's great. A lot has to be done within the CLI, but you really helped me with all the setup process and I'm very grateful. There's one question I have regarding the commitment fees and fees to close the channel. I recently closed one individual channel using the CLI and encountered a problem - I used the sat_per_byte setting as bellow:

` $ lncli closechannel --sat_per_byte 3 --force [channel_point]
`
All worked fine and I got a tx id as result. All settled within a couple of mins after the command.
But when looking for the actual settlement fee that was used when closing the channel on chain, I see 31.25 sat/B instead of the 3 sats per byte I set it above to use.

Is this something that can be changed? Is this related to some specific raspiblitz pack setting that overwrites the lncli command?

Would be grateful if you could help me understand this important aspect of channel mngmt.
Thanks!

**Comment by rootzoll** [comment]
When you directly use the lncli that pure LND - not RaspiBlitz. 

Why fees are off, I dont know. It would be best if you check with the LND Slack:
https://lightningcommunity.slack.com
