### ISSUE TITLE
RASPIBLITZ root page wants to tell more about HTTPS but link does not work

### ISSUE THREAD

**Issue by we-do-it-lu** [raspiblitz/raspiblitz#1880]
![image](https://user-images.githubusercontent.com/26678816/102494113-7946d000-4074-11eb-8398-bec4bdfcb720.png)

**Comment by rootzoll** [comment]
This is a feature in the works ... that will get developed further targeting for version 1.7/1.8.

**Comment by rootzoll** [comment]
The static root page will get replaced with new WebUI login with v1.8.0 release. Closing issue.
