### ISSUE TITLE
Electrum not connecting...

### ISSUE THREAD

**Issue by RC-RPB** [raspiblitz/raspiblitz#1881]
https://termbin.com/slupy

Caveat: I don't know much. 

Was connecting fine after patching 1.6.1. I remember last time that just reinstalling Electrs didn't work, I had to delete the index and start over from scratch. Updated to 1.6.2 and it's no longer working. I tried everything I know how to do, which is very little. Reinstalled Electrs, then deleted the index and reinstalled, disabled Tor, then deleted the index and reinstalled again. Still no luck.

**Comment by hermanlim** [comment]
There was a comment which sounded similar to yours awhile back if I remember correctly. I believe the problem had something to do with the security certificates. 

Try deleting the cert for the raspiblitz in ~/.electrum/certs (from the computer, not raspiblitz).

**Comment by RC-RPB** [comment]
That did it. Thank you sir!
