### ISSUE TITLE
Funding confirmation taking ages

### ISSUE THREAD

**Issue by maaxxyy** [raspiblitz/raspiblitz#1884]
Hi guys how long does funding confirmation normally take on the raspiblitz? My funds are still not confirmed from my hardware wallet. Thanks

**Comment by NilByte** [comment]
It depends on which fee rate you used and the state of the Bitcoin mempool.

https://jochen-hoenicke.de/queue/#0,1w

Check the transaction status in a block explorer.

https://blockstream.info/

**Comment by rootzoll** [comment]
On https://whatthefee.io you can see your chances that your transaction gets confirmed based in the fee of your transaction.

**Comment by maaxxyy** [comment]
My payment is still being sent, i sent it on the 17th of Dec, with low network fee. On ledger its showing as not confirmed. Thanks for the replies but still confused lol

**Comment by NilByte** [comment]
You hit a spike in the mempool. This is what happens when the price goes crazy like it is right now.

**Comment by nyxnor** [comment]
@maaxxyy Solved? Also, this depends on the fees you used, not on the Blitz. Please close this issue if done.

**Comment by nyxnor** [comment]
@rootzoll Please close this.
