### ISSUE TITLE
Recommended LCD-Display not available

### ISSUE THREAD

**Issue by TheSaltyJ** [raspiblitz/raspiblitz#1887]
The recommended LCD-Display is not available at amazon.de. Would that https://www.amazon.de/gp/product/B01N48NOXI/ref=ox_sc_act_title_1?smid=A3U321I9X7C9XA&psc=1 be an suitable alternative?

**Comment by rootzoll** [comment]
@Animalmother9000 any updates on the shopping list links?

**Comment by LightRider5** [comment]
@TheSaltyJ sorry but I can't reproduce the error. Just tried it and it is available.

**Comment by TheSaltyJ** [comment]
oh wow, they must have restocked it literally today! Thanks though. For the future, would that product in my comment be compatible with the setup? Feel free to close the issue.

**Comment by josephtyler** [comment]
For what it's worth, I had the same issue a few weeks ago. I clicked the link and it was unavailable, so I bought another similar display (and I also tried the official Raspberry Pi 7" display) to no avail. I checked again today and it was available so I ordered it!

Do you know what would be required to support the official 7" display?

**Comment by nyxnor** [comment]
@josephtyler Depends on the brand, the manufacturer normally has a custom script for the display.
@TheSaltyJ Can you close this issue?
