### ISSUE TITLE
Unable to install Specter on 1.6.1

### ISSUE THREAD

**Issue by mmarsalko** [raspiblitz/raspiblitz#1893]
There seems to be a few things missing during setup

> dialogcancel(0)
> Loop Setting unchanged.
> RTL Webinterface Setting unchanged.
> BTC-RPC-Explorer Setting unchanged.
> Cryptoadvance Specter Setting changed ..
>  bonus.cryptoadvance-specter.sh on
>     --> INSTALL Cryptoadvance Specter ***
>     --> Enable wallets in Bitcoin Core
> Multiwallet is active and wallet.dat is used.
> The bitcoin core wallet is already on
>     --> Installing prerequisites
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Note, selecting 'libusb-1.0-0-dev' for regex 'libusb-1.0.0-dev'
> The following package was automatically installed and is no longer required:
>   libbluetooth3
> Use 'sudo apt autoremove' to remove it.
> The following additional packages will be installed:
>   libusb-1.0-doc python3-virtualenv
> The following NEW packages will be installed:
>   libffi-dev libudev-dev libusb-1.0-0-dev libusb-1.0-doc python3-virtualenv virtualenv
> 0 upgraded, 6 newly installed, 0 to remove and 128 not upgraded.
> Need to get 110 kB/594 kB of archives.
> After this operation, 2,435 kB of additional disk space will be used.
> Err:1 http://raspbian.raspberrypi.org/raspbian buster/main armhf libudev-dev armhf 241-7~deb10u4+rpi1
>   404  Not Found [IP: 93.93.128.193 80]
> E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/s/systemd/libudev-dev_241-7~deb10u4+rpi1_armhf.deb  404  Not Found [IP: 93.93.128.193 80]
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

The installation also seems to get a little confused (doesn't detect the failures). Blitz "thinks" it successfully installed, but trying to connect to the specter IP/port displayed on the screen doesn't actually work.

**Comment by rootzoll** [comment]
Specter installs got updated already in released v1.6.2 ... v1.6.3 will even have a more updated version. Closing issue.
