### ISSUE TITLE
Mempool add "loading blocks" info

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#1899]
If you install on a fresh RaspiBlitz just "mempool explorer" (without any other apps) it gets stuck for some time on "loading blocks" ...

![Bildschirmfoto 2020-12-22 um 23 15 17](https://user-images.githubusercontent.com/2472225/102937975-a26bc400-44ab-11eb-84fc-2174b23f5a1b.png)

Add to info that this can happen and usually should be gone after 2hours.

**Comment by NilByte** [comment]
You get the info that it could take 7 hours. This is on an installation with RTL and  a few other apps installed.

![image](https://user-images.githubusercontent.com/36365571/102941137-3c366f80-44b2-11eb-922d-98f588b477de.png)

**Comment by rootzoll** [comment]
There are two things ... one is waiting for the txindex to get ready and then mempool needs to gather data for some blocks until its ready - but maybe that is something for mempool to improve on their side - if "Loading blocks" takes too long it should give a some more info to the user why its taking so long.

**Comment by rootzoll** [comment]
Reported on mempool github: https://github.com/mempool/mempool/issues/277
Pushing this to v1.7 release.

**Comment by NilByte** [comment]
After about 16 hours I tried to deactivate and activate Mempool again. Same loading blocks message. Then activated Bitcoin Explorer and did a reboot. Mempool then loaded.

Reboot seems to fix it as a workaround.

**Comment by softsimon** [comment]
We are aware of the many issues related to the now deprecated mempool v1 version. 

Please stay put for mempool v2 version for raspberry pi in the coming weeks. (and hopefully raspiblitz)
