### ISSUE TITLE
junk characters around edges of the TERMINAL raspiblitz menu display

### ISSUE THREAD

**Issue by agr999** [raspiblitz/raspiblitz#1900]
Menu commands are fine and can select/unselect but there exist "junk" characters (i.e. were not there originally) around the edges of the display. Problem appeared after aborting an Electrs server sync.

RaspiBlitz functionality does not appear to be affected. It's only bothersome to look at. ;) Just wondering where this junk comes from and perhaps how to get rid of it.

v1.6.2

Edit: using ssh under linux to connect (headless) Also note, LCD display unaffected - displays fine.

Update: closed & reopened terminal after a half a day or so - voila display is fine now. Weird. Had shutdown & restarted a terminal window previously but not for as long - to no avail. Anyway, issue has gone. Feel free to close this issue if so inclined.

**Comment by NilByte** [comment]
If you use Putty, try this.

![image](https://user-images.githubusercontent.com/36365571/103044083-7c175880-457f-11eb-9f04-a1f57b49111b.png)

**Comment by nyxnor** [comment]
@agr999 Please close this issue if solved.

**Comment by c03rad0r** [comment]
Perhaps this has something to do with how the encoding is interpreted on the terminal that ssh's into the machine. A [similar problem](https://nostr.build/i/8e7347cd1f07b4ca59469719d3fd48e01ee251d24db7da7b80659bd4fe4e233a.jpg) was discovered when logging into a raspiblitz from the terminal of a chromebook. The problem didn't occur logging in to the same pi from termux on an android, though.

**Comment by rootzoll** [comment]
@chGoodchild yes this problem occurs based on the SSH client/terminal people use.
