### ISSUE TITLE
Stuck on Processing triggers for rsyslog (8.1901.0-1) ...

### ISSUE THREAD

**Issue by miningdave** [raspiblitz/raspiblitz#1905]
Did a clean shutdown to update to newest version.
Burned new image and booted, it came back up to recovering and sits there.
Waited a day and then pulled the power and tried again, Same thing.

Any thoughts on next step(s)?

Thanks,
Dave

**Comment by rootzoll** [comment]
What does it say on the display?

**Comment by miningdave** [comment]
Nothing, it just sat there. Black screen. Went through the entire boot process and stopped.
I just wiped and started again this morning I empty all the lnd channels before doing an upgrade so no big deal.
Trust me, if there was money in there I would have been posting hourly :-)

**Comment by nyxnor** [comment]
@miningdave Can you close this issue?

**Comment by miningdave** [comment]
Closing.
