### ISSUE TITLE
Add info to readme what to do when USBstick in RAID mode is failing

### ISSUE THREAD

**Issue by holgern** [raspiblitz/raspiblitz#1910]
After switching off the touchscreen setting, my rapiblitz rebooted unexpected fast. The dirty reboot causes that my harddisk with btrfs filesystem is now broken.

btrfs rescue zero-log /dev/sda2 shows:
parent transid verify failed on 444560588800 wanted 94010 found 93456

I'm not able to mount with:
mount -t btrfs -o rootflags=recovery,nospace_cache,clear_cache /dev/<btrfs-device> /<mountdir>

My raspiblitz is not booting anymore and I'm not able to repair my harddrive. I need to start over.

**Comment by holgern** [comment]
As I'm not able to format the 32 GB stick (I was using btrfs with raid), I think everything was caused by a failing 32 gb USB stick.
I'm not able to read and I'm not able to format my stick, so I'm thinking the USB stick broke.

The broken usb-stick in RAID mode, broke then also the btrfs on the ssd.

**Comment by holgern** [comment]
As the raid is not protecting against failing usb sticks, I think it would be better to remove the raid option from raspiblitz. 
This would also reduce complexity in the scripts.

**Comment by openoms** [comment]
I think the RAID option is great, but need to improve the fallback option and be able to.boot in degraded mode.

Cheap USB sticks are harmful imo, see: https://github.com/rootzoll/raspiblitz/issues/924
I am running with a Sandisk USB Pro SSD with no issues. 

Great guidance from the c-lightning team on BTRFS: https://lightning.readthedocs.io/BACKUP.html#filesystem-redundancy

**Comment by holgern** [comment]
Thanks, I think the link to the guide should be added to the readme. I think I broke every by using wrong btrfs commands.

**Comment by rootzoll** [comment]
Closing this issue because we consider to remove BTRFS from RaspiBlitz .. see: https://github.com/raspiblitz/raspiblitz/issues/2045#issuecomment-2471845122
