### ISSUE TITLE
Main menu not loading when ssh in

### ISSUE THREAD

**Issue by CoderBoogs** [raspiblitz/raspiblitz#1912]
I have been Having this issue since 1.6.0 when I ssh in menu doesn't load. It stays stuck on Starting the main menu.... 

Any ideas on how to fix this without having to reboot the raspiblitz?

**Comment by Houtek** [comment]
Have you tried to hit CTRL+C and start the menu manually with "raspiblitz" or "blitz" (without quotes)?
Otherwise you could try to start the menu with "./00raspiblitz.sh" (no quotes), "raspiblitz" and "blitz" are shortcuts.

**Comment by son-y** [comment]
If I press CTRL+C in a SSH connection, the connection closes. Any ideas to get this problem done?

**Comment by nyxnor** [comment]
@CoderBoogs Please close this issue if it was solved.

**Comment by nyxnor** [comment]
@rootzoll Please close this.
