### ISSUE TITLE
electrs txid_limit config is disabled causing queries to get stuck

### ISSUE THREAD

**Issue by softsimon** [raspiblitz/raspiblitz#1914]
We are currently testing mempool explorer for Raspiblitz and there is an issue with the address page containing many transactions. The API call to electrum to fetch the txids (blockchainScripthash_getHistory), bitcoind get stuck with 100% cpu for hours because there's no limit... the default limit is actually 100 which is more reasonable, .. setting the limit to 1000 could work also .. and an error will be returned instead.

This is the default config on my raspiblitz 1.6.2
```
# allow BTC-RPC-explorer show tx-s for addresses with a history of more than 100
txid_limit = 0
```

From the romanz/electrs documentation:

> doc = "Number of transactions to lookup before returning an error, to prevent 'too popular' addresses from causing the RPC server to get stuck (0 - disable the limit)"
> default = "100"

**Comment by rootzoll** [comment]
For the v1.6.3 I will change the config to `txid_limit = 1000` .. should we delay the v1.6.3 to include the new mempool explorer?

**Comment by wiz** [comment]
@rootzoll What was your timeline for the release? I think we shouldn't rush Simon too much, also it will take some time to work on the new build scripts and deployment environment, etc. - a lot has changed since v1

**Comment by rootzoll** [comment]
@wiz after the weekend would be my latest target

**Comment by wiz** [comment]
Okay we will try to ship it this weekend

**Comment by rootzoll** [comment]
@wiz keep me updated

- [ ] include and test mempool update
- [ ] set `txid_limit = 1000`

**Comment by wiz** [comment]
I've just started reviewing and testing Simon's PR to add bitcoind support https://github.com/mempool/mempool/pull/281
After merging this, I can begin working on a PR to RaspiBlitz and the other Raspberry Pi distributions
It's already Monday here so I guess we won't ship it "this weekend" 😅

**Comment by rootzoll** [comment]
OK. new mempool version is merged. tests looking good :) closing issue for v1.6.3 release.
