### ISSUE TITLE
setup error on raspiblitz

### ISSUE THREAD

**Issue by OrionRaycraft** [raspiblitz/raspiblitz#1916]
I have had zero error messages until now in my debug check i got this message

failed to start a high performance web server and a reverse proxy server

Thoughts?

**Comment by rootzoll** [comment]
any context to that error message? on which step during the process? in which section of the debug check?

**Comment by OrionRaycraft** [comment]
![Capture](https://user-images.githubusercontent.com/76847073/103447664-b3f35f80-4c53-11eb-9921-6ce2fe48baf1.JPG)

**Comment by OrionRaycraft** [comment]
I tried to copy the log and received this error message

**Comment by OrionRaycraft** [comment]
![Capture2](https://user-images.githubusercontent.com/76847073/103447717-878c1300-4c54-11eb-8640-e378b34d7153.JPG)

**Comment by OrionRaycraft** [comment]
i can log into raspiblitz software

**Comment by rootzoll** [comment]
OK .. if lnd.service is not found then something went very strange wrong. If you dont have any funds on there yet Iwould recommend a fresh start: format the HDD on your laptop clean and make a fresh sd card image to start with.

**Comment by nyxnor** [comment]
@OrionRaycraft Did you solve this? Close this issue if affirmative.

**Comment by nyxnor** [comment]
@rootzoll Please close this issue.
