### ISSUE TITLE
Has anyone used a larger screen?

### ISSUE THREAD

**Issue by miningdave** [raspiblitz/raspiblitz#1927]
Was going to setup a 2nd unit, but my eyes are not what they used to be and I was thinking of going with a 5" or 7" screen instead of the 3.5". However, I don't see any mention if they will work with it or not. The larger screens I see are not fed though the GPIO so I don't know if that matters.

Thanks,

**Comment by rootzoll** [comment]
You can run a larger screen on the hdmi port ... for that you need to switch from LND-GPIO-Pins output to HDMI output ... see: https://github.com/rootzoll/raspiblitz/blob/v1.6/FAQ.md#can-i-run-the-raspiblitz-without-a-displaylcd

**Comment by nyxnor** [comment]
@rootzoll Please close this
