### ISSUE TITLE
got a new case with expandable storage, lol

### ISSUE THREAD

**Issue by DrBlackross** [raspiblitz/raspiblitz#1929]
i just need to rework the shutdown [scripts](https://github.com/RetroFlag/retroflag-picase) and link them to raspiblitz shutdown and reboot...

i got this... (i think)
![137639468_1121204128341556_5385980238673696437_n](https://user-images.githubusercontent.com/20823032/104133104-4b8d3800-534f-11eb-8b8a-afd51a00c992.jpg)

thumb drive in the front is my channel backup drive, the other port on the front is a spare (or rerouted) usb3 

[Case is here](https://www.amazon.com/RETROFLAG-Raspberry-Supply-Cooling-Heatsinks/dp/B08DN9K2ZG)

**Comment by nyxnor** [comment]
@DrBlackross Very cool indeed.
Can you close this? Im cleaning opened issues.
