### ISSUE TITLE
/home/admin/raspiblitz.info: No such file or directory

### ISSUE THREAD

**Issue by hopitas** [raspiblitz/raspiblitz#194]
I updated the script files on my raspiblitz and now when I try to start 00mainMenu.sh this error:

/home/admin/raspiblitz.info: No such file or directory

Where/how is this file is generated? bitcoind and lnd seem to be working.

**Comment by rootzoll** [comment]
Updating the scripts does not lead to a stable verison - its more as a last resort or for development. Please wait for the next sd card release. If you have funds on your blitz try to cashout or recover coins like described here: https://github.com/rootzoll/raspiblitz#recover-your-coins-from-a-failing-raspiblitz
