### ISSUE TITLE
Decentral data exchange relay

### ISSUE THREAD

**Issue by hikaman** [raspiblitz/raspiblitz#1946]
Is it planned and possible to integrate a croc relay on raspiblitz? I think decentral data exchange would be a nice enhancement for a decentral infrastructure. 

This is what I am talking about 
https://github.com/schollz/croc

**Comment by rootzoll** [comment]
Its not planned. You can do a contribution to install it as an additional app ... but because its not directly related to Bitcoin/Lightning there are some users that see adding/running such additional software just raising the attack vector on the node.

**Comment by nyxnor** [comment]
Please close this, no other mention or development happened about this.
