### ISSUE TITLE
Bitcoin IP shown in yellow

### ISSUE THREAD

**Issue by N00bl0rd999** [raspiblitz/raspiblitz#1952]
Hi,
port 8333 is reachable and open, why is my BTC IP address not turning green?

**Comment by NilByte** [comment]
FAQ is a good place to find stuff. ;)

https://github.com/rootzoll/raspiblitz/blob/v1.6/FAQ.md#why-is-my-node-address-on-the-display-yellow-not-green

**Comment by N00bl0rd999** [comment]
> FAQ is a good place to find stuff. ;)
> 
> https://github.com/rootzoll/raspiblitz/blob/v1.6/FAQ.md#why-is-my-node-address-on-the-display-yellow-not-green

Yeah, I'm just not talking about the LN node address.

**Comment by NilByte** [comment]
It's the same explanation.

https://github.com/rootzoll/raspiblitz/blob/v1.6/FAQ.md#why-is-my-bitcoin-ip-on-the-display-red

**Comment by N00bl0rd999** [comment]
Why is it green in those screenshots?
https://github.com/rootzoll/raspiblitz/raw/v1.6/pictures/raspiblitz.jpg
https://github.com/rootzoll/raspiblitz/raw/v1.6/pictures/ssh9z-ready.png

Is that because of them being an older version?

**Comment by NilByte** [comment]
It depends on how your internet connection is configured by your provider.

You can do a port scan here and get more information.

https://www.ipfingerprints.com/portscan.php

In any case, yellow is fine and not indicating a problem.

**Comment by N00bl0rd999** [comment]
As I said, both ports are indicated as "open" by port scanning services.

> It depends on how your internet connection is configured by your provider.
What exactly would that mean?

> In any case, yellow is fine and not indicating a problem.
Thank you!

**Comment by amcitaly** [comment]
The picture that you post show the address all in green because TOR is activated. Personally if I use public IP and port 8333 open has never been green but always yellow and so the LND. If you want to see all green try run the node under TOR, as in the picture

**Comment by gtx1070rig** [comment]
So there are no errors if dyndns address and lnd public:ip are yellow?

**Comment by amcitaly** [comment]
Yellow is OK, there is no error. If you try test your port 8333 and 9735 you will see they are open and reachable from outside

**Comment by rootzoll** [comment]
Yes Yellow means OK ... the RaspiBlitz can confirm that testing that port on your public IP gives an answere. BUT that RaspiBlitz cannot confirm that the service answering is really this bitcoin core - it could be also another service in your home network that is just responding on that port. Because the RaspiBlitz cannot know for sure - the address is just yellow - not green.
