### ISSUE TITLE
!!! BUILD FAILED --> PGP Verify not OK / signature(0) verify(0)

### ISSUE THREAD

**Issue by Hobeal** [raspiblitz/raspiblitz#1955]
Hi, i need help please. Im getting this error.

**Comment by nyxnor** [comment]
Please provide more information. Check this same type of issue here https://github.com/rootzoll/raspiblitz/issues/797

**Comment by openoms** [comment]
Please provide more info.
is it the lnd PGP key? 
Does manual verification of the LND binary work?

**Comment by Hobeal** [comment]
I already solved the problem but now I have these errors, there´s nothing in  /home/admin how can i solve this problem?

**key-bindings added to /home/admin/.bashrc
Cloning into 'raspiblitz'...
fatal: Remote branch master not found in upstream origin
cp: cannot stat '/home/admin/raspiblitz/home.admin/*.*': No such file or directory
cp: cannot stat '/home/admin/raspiblitz/home.admin/.tmux.conf': No such file or directory
chmod: cannot access '*.sh': No such file or directory
cp: cannot stat '/home/admin/raspiblitz/home.admin/assets': No such file or directory
cp: cannot stat '/home/admin/raspiblitz/home.admin/config.scripts': No such file or directory
chmod: cannot access '/home/admin/config.scripts/*.sh': No such file or directory
ls: cannot access '/home/admin/raspiblitz/home.admin/BlitzPy/dist': No such file or directory

*** INSTALLING BlitzPy Version:  ***
grep: /home/admin/config.scripts/lndlibs/rpc_pb2_grpc.py: No such file or directory
sed: can't read /home/admin/config.scripts/lndlibs/rpc_pb2_grpc.py: No such file or directory
grep: /home/admin/config.scripts/lndlibs/rpc_pb2_grpc.py: No such file or directory
sed: can't read /home/admin/config.scripts/lndlibs/rpc_pb2_grpc.py: No such file or directory
autostart added to /home/admin/.bashrc
autostart LCD added to /home/pi/.bashrc

*** HARDENING ***
Reading package lists... Done
Building dependency tree
Reading state information... Done
Suggested packages:
  mailx monit sqlite3
Recommended packages:
  python whois python3-pyinotify
The following NEW packages will be installed:
  fail2ban python3-systemd
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 420 kB of archives.
After this operation, 2,060 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster/main arm64 fail2ban all 0.10.2-2.1 [385 kB]
Get:2 http://deb.debian.org/debian buster/main arm64 python3-systemd arm64 234-2+b1 [34.9 kB]
Fetched 420 kB in 0s (1,848 kB/s)
Selecting previously unselected package fail2ban.
(Reading database ... 40684 files and directories currently installed.)
Preparing to unpack .../fail2ban_0.10.2-2.1_all.deb ...
Unpacking fail2ban (0.10.2-2.1) ...
Selecting previously unselected package python3-systemd.
Preparing to unpack .../python3-systemd_234-2+b1_arm64.deb ...
Unpacking python3-systemd (234-2+b1) ...
Setting up fail2ban (0.10.2-2.1) ...
Created symlink /etc/systemd/system/multi-user.target.wants/fail2ban.service → /lib/systemd/system/fail2ban.service.
[fail2ban-tmpfiles.conf:1] Line references path below legacy directory /var/run/, updating /var/run/fail2ban → /run/fail2ban; please update the tmpfiles.d/ drop-in file accordingly.
Setting up python3-systemd (234-2+b1) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for systemd (241-7~deb10u5) ...
Activating CACHE RAM DISK ...
sudo: /home/admin/config.scripts/blitz.cache.sh: command not found

*** RASPI BOOTSTRAP SERVICE ***
chmod: cannot access '/home/admin/_bootstrap.sh': No such file or directory
cp: cannot stat './assets/bootstrap.service': No such file or directory
Failed to enable unit: Unit file bootstrap.service does not exist.

*** RASPI BACKGROUND SERVICE ***
chmod: cannot access '/home/admin/_background.sh': No such file or directory
cp: cannot stat './assets/background.service': No such file or directory
Failed to enable unit: Unit file background.service does not exist.
*** Prepare TOR source+keys ***
sudo: /home/admin/config.scripts/internet.tor.sh: command not found**

**Comment by nyxnor** [comment]
Been 2 weeks, have you upgraded to version 1.6.3?
Reflash the microSD card.

**Comment by nyxnor** [comment]
Pls close this issue.
