### ISSUE TITLE
Update balanceofsatoshis to latest version

### ISSUE THREAD

**Issue by kytmanov** [raspiblitz/raspiblitz#1959]
What is right way to update _balanceofsatoshis_ tools? BOS current version is v7.17, however raspiblitz goes with 6.1.

**Comment by kytmanov** [comment]
Looks like the right way to pull the latest version

```
cd config.scripts
./bonus.bos.sh update
```

**Comment by scarolan** [comment]
Thank you for this!  Let's add some more keywords to make this easier to find. If your Balance of Satoshis app is out of date, you can upgrade it by running the script mentioned by kytmanov. Do not run the npm commands that bos outputs on the command line.
