### ISSUE TITLE
BTCPayServer error 502 Bad Gateway (nginx/1.14.2)

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#1965]
Happening with  new installs, didn't reproduce on updates.
```
$ sudo systemctl status btcpayserver
fail:Configuration: No Database option was configured.
````

to fix run:
```
$ echo "sqlitefile=sqllite.db" | sudo tee -a /home/btcpay/.btcpayserver/Main/settings.config
```
or edit `/home/btcpay/.btcpayserver/Main/settings.config` manually.

This line is not kicking in because the setting.config is not present before btcpayserver is first run.
https://github.com/rootzoll/raspiblitz/blob/c395e3a6d438c2da16a231dc172c79e7cf3cbd22/home.admin/config.scripts/bonus.btcpayserver.sh#L476

**Comment by we-do-it-lu** [comment]
No need to restart the service after having corrected this config file?

**Comment by openoms** [comment]
@we-do-it-lu 
yes, use:
`sudo systemctl restart btcpayserver`

**Comment by rootzoll** [comment]
PR #2043 was merged - final testing if this fixes the problem

**Comment by rootzoll** [comment]
Ok fixed it on my test setup ... keeping open for final testing when closer to release.

**Comment by rootzoll** [comment]
Looks good on testing for v1.7. Closing issue.
