### ISSUE TITLE
Do you need to do port-forwarding on the router?

### ISSUE THREAD

**Issue by tifDev** [raspiblitz/raspiblitz#1967]
F.e. It's needed to open-ports in the router if you want to run raspiblitz with a Node + Tor + ElectRS ?

**Comment by rootzoll** [comment]
If you connect over Tor you dont need port-forwarding ... a Tor hidden service (onion-address) can run behind a NAT and is publicly reachable.

**Comment by tifDev** [comment]
And what if I don't connect to Tor, I still need to do port-forwarding in ISP's router? 


Also, I still need to do port-forwarding to run a Tor hidden service unless I connect to other unknown server running a Tor hidden service (correct me if I'm wrong)

**Comment by rootzoll** [comment]
> And what if I don't connect to Tor, I still need to do port-forwarding in ISP's router?

You only need port-forwarding when you dont use Tor (so you use clearnet IP) AND you wanna be publical reachable to peers you never connected to before. You can also run a routing node without Tor behind a NAT with no forwarded ports .. it only means that your node needs always to reachout to the other peers (initiate the connection) and those peers need to be publicly available (have a working port forwarding or run on a hosted server). 

> Also, I still need to do port-forwarding to run a Tor hidden service unless I connect to other unknown server running a Tor hidden service (correct me if I'm wrong)

If you run Tor even connecting to other peers that are publicly reachable on clearnet will be done thru Tor (using an Tor exit node). If you run Tor you can basically forget about port-forwarding. The only downside of using Tor is that you are not publicly reachable to peers running on the clearnet ... but again, that only means that your Tor node then has to initiate the connection to those nodes and you can still establish a working channel.

**Comment by tifDev** [comment]
Any tutorial about this? It would be nice to have this topic a bit more detailed and with an example.
I thought that I would only need to open-ports if I don't use TOR and if I would want to allow others to connect to my node (in case I don't want inbound connections, only outbound, port-forwarding wouldn't be needed).

**Comment by rootzoll** [comment]
@openoms is there a chapter on this (planned) in your "Managing a Node" tutorial?
https://openoms.gitbook.io/lightning-node-management/

**Comment by openoms** [comment]
Not planning to cover clearnet methods. We are planning to go Tor by default.
Exposing your home IP and exposing ports on your router is not advised to avoid compromising privacy and security of the home network.

**Comment by tifDev** [comment]
Yes Tor is a better option. I'll go digg more on this. 

Thank you both.
