### ISSUE TITLE
SCP channel backup option 

### ISSUE THREAD

**Issue by woeisme** [raspiblitz/raspiblitz#1969]
In addition to current USB or Dropbox backup options I think it would be helpful to offer SCP to allow users to backup their channel state to a host either within their local LAN or remotely. If setup with Public Keys this should run reliably.

**Comment by nyxnor** [comment]
Menu > Repair > Backup LND

**Comment by woeisme** [comment]
Thanks for this but Backup LND should not mandate a node reboot without at least warning the user. I also think this should be under backup options (possibly as well as under repair).
Looks like I'll file another issue.
