### ISSUE TITLE
There is no value for network in /home/admin/raspiblitz.info

### ISSUE THREAD

**Issue by cedricwalter** [raspiblitz/raspiblitz#197]
Using WIfi and no Ethernet
Building sdcard by using RaspbianStretchDesktop.sh
At reboot while still connected though hdmi, and login as admin/raspiblitz

i get the following error message when running There is no value for network in /home/admin/raspiblitz.info

**Comment by rootzoll** [comment]
RaspbianStretchDesktop.sh is in between versions - please use the sd card image or even better wait some more days for the version 1.0-rc1 release. thx.
