### ISSUE TITLE
2021-01-24 08:57:09.102 [ERR] BTCN: Can't accept connection: unable to accept connection from mypublicip:35988: EOF

### ISSUE THREAD

**Issue by gtx1070rig** [raspiblitz/raspiblitz#1972]
Hello,

i have several lines in the lnd logfile like written in the subject....
Is there any error or can i ignore it?

port is increaing like:

....:35810: EOF
.....35866: EOF

**Comment by rootzoll** [comment]
I am not familiar with those errors ... maybe best would be to head over to the LND Dev Slack and get some answers there: https://dev.lightning.community

**Comment by gtx1070rig** [comment]
seems to be only port scanners
