### ISSUE TITLE
Adapt for Zeus App with build in Tor pairing

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#1973]
https://twitter.com/ZeusLN/status/1353465407185637377?s=20

**Comment by openoms** [comment]
The manual process is described here; https://github.com/openoms/bitcoin-tutorials/blob/master/Zeus_to_RaspiBlitz_through_Tor.md

**Comment by rootzoll** [comment]
The MOBILE dialog is now using for Zeus Android & iOS the Tor connect. Further refactoring on the dialogs will be done on issue #2090 that will reorganize MOBILE into a CONNECT submenu.

**Comment by rootzoll** [comment]
Tested and works fine - with v1.7 Zeus will be Tor only by default.
