### ISSUE TITLE
LND Backup should use checksum not filesize comparison for verifying archive integrity

### ISSUE THREAD

**Issue by woeisme** [raspiblitz/raspiblitz#1974]
When using Menu>Repair>Backup LND 
we should be using standard checksumming hashes (md5 or sha) for checking backup integrity not filesize as this can differ depending on underlying OS.

**Comment by rootzoll** [comment]
The lnd rescue file already contains the md5 checksum as part of the filename:
https://github.com/rootzoll/raspiblitz/blob/82e0d6c3714ce1b2878780c4bdef72a6417f71c7/home.admin/config.scripts/lnd.rescue.sh#L44

So you think this should be pointed out more clearly in the instructions?

**Comment by nyxnor** [comment]
@woeisme Answer was enough? If yest, pls close this.

**Comment by nyxnor** [comment]
@rootzoll Please close this
