### ISSUE TITLE
Test new LCD drivers

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#1985]
see https://github.com/rootzoll/raspiblitz/issues/1436#issuecomment-766440294 ... could also be related to: https://github.com/rootzoll/raspiblitz/issues/1199#issuecomment-736564381

**Comment by openoms** [comment]
The 64bit display driver are included in https://github.com/rootzoll/raspiblitz/pull/1858

**Comment by rootzoll** [comment]
PR merged ... but it looks like we need to deactivate the LCD touchscreen for v1.7 until we fix & refactor it for v1.8

**Comment by rootzoll** [comment]
As part of the RC1 testing & some refactoring of the display part. The new LCD drivers look good. Closing the issue.

The fix of calibration of Touchscreen is now part of this issue: #2150
