### ISSUE TITLE
Changes to ./XXdebugLogs.sh debug logs

### ISSUE THREAD

**Issue by nyxnor** [raspiblitz/raspiblitz#1986]
Could not open a pull withou a lot of junk coming on, sorry.... pls recommend me decent videos on how to do this (pull request), the ones I watched seems not to be very helpful.
Based on this https://github.com/rootzoll/raspiblitz/pull/1947

Changes: https://github.com/Ben10Brasileiro/raspiblitz/commit/8a71586c900149e8049f1d74aa3bfc9f74afa807
This file: https://github.com/Ben10Brasileiro/raspiblitz/blob/deb-2nd/home.admin/XXdebugLogs.sh

After these changes are made or cancelled, dont know if there is a better way than deleting my fork and doing  modifications only on new branches, not on the default v1.6.

**Comment by rootzoll** [comment]
Merged your PR into a interims fork of v1.6 and cherrypicked them over to the `dev` btranch to be part of v1.7RC1 release. Ready for final testing :)

**Comment by nyxnor** [comment]
Good. I will try to do a best PR next time.

**Comment by nyxnor** [comment]
This is done, gotta cleanse.
