### ISSUE TITLE
Use an issue template

### ISSUE THREAD

**Issue by nyxnor** [raspiblitz/raspiblitz#1991]
_There are times people write 1 line and expect others to understand, so I made this template
I dont like extensive issues templates, so I made this compact one.
Inspired by mempool template https://github.com/mempool/mempool/issues/new_

## Hardware and Software

"1.6.3"
"Raspbian GNU/Linux 10 (buster)"
armv7l
Raspberry Pi 4 Model B Rev 1.1
SSD
HDMI
### Actual Behavior:
It will be faster to understand issues

### Expected behaviour:
To be easy to write and understand

### Steps to reproduce:
Just try

### Additional info (logs): 
Code for this: [blitz.issueTemplate.txt](https://github.com/rootzoll/raspiblitz/files/5899421/blitz.issueTemplate.txt)

## Screenshots
![image](https://user-images.githubusercontent.com/69700936/106359757-61a96b00-62f3-11eb-95cb-d1e9a4ec419e.png)

**Comment by nyxnor** [comment]
Also, take a look at this: 
https://github.com/debian-cryptoanarchy/cryptoanarchy-deb-repo-builder/issues/new/choose
![kixuniltemplate](https://user-images.githubusercontent.com/69700936/113440423-e429d600-93db-11eb-9c17-d7b905ca9414.png)

**Comment by rootzoll** [comment]
To cut down workload of the v1.7.1 release - pushing this organizational change to v1.8

**Comment by cstenglein** [comment]
Basic templates now implemented :)
