### ISSUE TITLE
build_sdcard.sh contains non existent default value for branch

### ISSUE THREAD

**Issue by charlesleer** [raspiblitz/raspiblitz#1996]
if [ ${#wantedBranch} -eq 0 ]; then
  wantedBranch="master"

There is no master so the bash script fails in the end and the user is left with an empty home dir, probably not the best option to have master as default option.

Manually giving v1.6 made the script run fine.

**Comment by rootzoll** [comment]
Thanks thats a good reminder for the preperation of the next release.

**Comment by rootzoll** [comment]
OK the sd card build got a big update for the upcomming v1.7RC1 release and is not depending on some master branch anymore. Closing this issue.
