### ISSUE TITLE
Termbin is not printing the all the debug logs

### ISSUE THREAD

**Issue by nyxnor** [raspiblitz/raspiblitz#2012]
Please consider saving the debug logs to a file, so the termbin prints the entire contents. 
This is because there is a time out, termbin just run debug again with a time out, doesnt get the previous outputs.

If I run `debug`, it prints the file and transfer to var
if I run `debug -l`, do all this above plus print the termbin link below. 
This solves the issue of not printing the entire debug logs.
Also, the end path of termbin on the XXdebugLogs.sh will need to be updated with the path and file name you guys choose.

I edited the debug alias on _commands.sh:

```
# command: debug
function debug() {
  cd /home/admin
if  [[ $1 = "-l" ]]; then
        bash XXdebugLogs.sh > /var/cache/raspiblitz/debug.log && cat /var/cache/raspiblitz/debug.log | nc termbin.com 9999
else
        bash XXdebugLogs.sh > /var/cache/raspiblitz/debug.log && cat /var/cache/raspiblitz/debug.log
fi
}
```

But, if you dont want to add another script file, just add the code to _commands.sh

Just found there is a onion pasting sites like this https://p.pastly.xyz/ (Will redirect when using tor browser).
If someone knows how to http post there.... cause else termbin.com will still know who is posting.

**Comment by rootzoll** [comment]
Thanks :) Will take a look for the next release.

**Comment by nyxnor** [comment]
Well, first decent pull request.
Closing this now, continue on the pull request above.
