### ISSUE TITLE
[Update] RTL v0.10.1

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2019]
https://twitter.com/RTL_App/status/1363582174587465729?s=20

**Comment by openoms** [comment]
Just noting here that need to test with the Terminal, likely needs a port change in the config to make Loop work.
https://github.com/rootzoll/raspiblitz/issues/1993

**Comment by openoms** [comment]
A new optional feature in RTL is to add support for the boltz.exchange api which needs to have the boltzd running:
https://lnd.docs.boltz.exchange/en/latest/

**Comment by rootzoll** [comment]
Merged with #1994 which contains v0.10.0 .. will update to v0.10.1

**Comment by rootzoll** [comment]
OK RTL 10.0.1 tests looking good ... keeping open for final release testing.
