### ISSUE TITLE
retry creating wallet UI is confusing

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#202]
during setup on waalet creation, if passwords do not match  - it shows a everything (OK dialog) is ready first and then asks to enter password again - that is confusing

**Comment by geco91** [comment]
see #278 - would recommend to rewrite to python script to make also better UI here for v1.1

**Comment by rootzoll** [comment]
closing .. SSH process is working good enough and coming versions will solve this much better with a TOR-WEBUI.
