### ISSUE TITLE
Change Font Size On Raspiblitz

### ISSUE THREAD

**Issue by pkepler** [raspiblitz/raspiblitz#2025]
I have searched "issues" for changing font size and haven't found the fix for this.  How do I make this fill the entire screen?  Thanks in advance.
![IMG_0458](https://user-images.githubusercontent.com/46732761/109320929-95a67c00-781e-11eb-897a-8e4c3b209356.JPG)

**Comment by pkepler** [comment]
I have reopened this issue after some Telegram suggestions.  Those steer me to changing font size but I think this looks like the Raspiblitz software is sending out a higher resolution than this 4 inch screen is set to.  I think I need to lower the resolution on the pi.  I appreciate any help.  My CLI interface is weak but I am learning so if you help please be specific.  Thank you.

**Comment by NilByte** [comment]
I would try `sudo raspi-config`

https://pimylifeup.com/raspberry-pi-screen-resolution/

**Comment by pkepler** [comment]
I did try that.  This LCD is the 4 inch LCD  http://www.lcdwiki.com/4inch_HDMI_Display-C.  Shows a native resolution of 800 * 480.    I tried all of the options in the menu.  None of them filled the screen.  Most appeared to be incompatible as the screen just kept flashing blue screen.  I found this in another thread:
```
# Force use HDMI
hdmi_force_hotplug=1
# force a specific HDMI mode
hdmi_group=2
hdmi_mode=87

# custom display resolution (480x320 looks good , and 720x480 is not too bad too,3rd res is: 810x540 )
#         /----------------- Width: 480px ( or 720px /or 810px)
#         |   /------------- Height: 320px ( or 480px /or 540px)
#         |   |   /--------- Refresh: 60Hz
#         |   |   | /------- Aspect ratio: 6=15:9 (1=4:3, 2=14:9, 3=16:9, 4=5:4, 5=16:10)
#         |   |   | | /----- Margins: 0=disabled (1=enabled)
#         |   |   | | | /--- Interlace: 0=progressive (1=interlaced)
#         |   |   | | | | /- Reduced blanking: 0=normal (1=reduced)
#         |   |   | | | | |
hdmi_cvt 480 320 60 6 0 0 0

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
hdmi_drive=2
```
Even though this is for a 3.5 inch screen I think I will try it.

**Comment by openoms** [comment]
@pkepler try this solution: https://github.com/rootzoll/raspiblitz/issues/244#issuecomment-476713706

**Comment by nyxnor** [comment]
@pkepler Close this if solved pls.

**Comment by pkepler** [comment]
Problem not solved but I don't care any longer.
