### ISSUE TITLE
Scripts to automate an email send of your LND Channel.Backup file upon any change/update

### ISSUE THREAD

**Issue by davterra** [raspiblitz/raspiblitz#2028]
RaspiBlitz has an option to upload your Channel.Backup to Dropbox, but this simple process will automatically email a fresh Channel.Backup to whatever email address you stipulate, any time the backup file is changed/updated.

Details in this gist:
https://gist.github.com/davterra/8ae5753a2b7b6d9a63d4872139a6a64d

**Comment by davterra** [comment]
NOTE: I found a couple of typos in the gist, and fixed at 14:50 UTC 3/1. If anyone copied the files before that, please re-copy.

**Comment by frennkie** [comment]
We already have the ability to setup email notifications.
So that part of of the gist isn't needed.

**Comment by davterra** [comment]
Really? I'm new to this project but I only have seen the DropBox and USB backup options. Where can I find info about an existing email SCB/backup setup?

**Comment by nyxnor** [comment]
@davterra config.scripts/blitz.notify.sh

**Comment by rootzoll** [comment]
@davterra is the existing notify script working for you? Can we close this issue?

**Comment by davterra** [comment]
@rootzoll Sure, you can close it. I'm curious as to why this existing feature remains undocumented? I haven't tested it because my method is working fine for me. I have tried ssmtp in the past and ended up using mutt because I found it easier to configure, but it looks like you have that all scripted out. If it needs documentation, I would be willing to test it and add documentation to the README, if you want.

**Comment by rootzoll** [comment]
Its not well documented because its still an experimental feature added by @frennkie .. adding some more documentation is much welcome :)

**Comment by davterra** [comment]
OK. I'm on the road all of this week, so likely won't get started testing the existing script until next week, but happy to give it a try and write something up.
