### ISSUE TITLE
Reasearch Pushnotifications on events

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#203]
Check optional services like https://pushover.net for getting notifications on events (also for mobile wallets like zap, etc) ... but also keep in mind the possible privacy leak thru such services.

**Comment by geco91** [comment]
I think this topic is just a nice to have at the moment and can be closed.

**Comment by rootzoll** [comment]
OK I will close this .. if anybody sees this issue of more important please post to it and I wil open it up again.
