### ISSUE TITLE
Deprecate LNDmanage

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2031]
Some users report that LNDmanage is making problems on their nodes. Also the project is not very active anymore and most of the features are possible with other tools. 

May consider a soft removal for next release:
- remove from GUI
- deactivate on update (force turn off on update, even if it was on before  - so user needs to run command line install manually to reactivate)

**Comment by keblek** [comment]
this might be a chance to add lndmon https://github.com/lightninglabs/lndmon

**Comment by openoms** [comment]
LNDmanage is a python based rebalancing tool. Nothing to do with lndmon.

**Comment by keblek** [comment]
I use bos for that so I wasn't familiar with this. My bad.

**Comment by rootzoll** [comment]
removed it from GUI and update-provisiong for next release .. we can switch it back on if a new release is comming
changes made in branch https://github.com/rootzoll/raspiblitz/tree/2089-sphinx .. waiting to merge

**Comment by DocBrown101** [comment]
The new release is now available:
https://github.com/bitromortac/lndmanage/releases/tag/v0.12.0

**Comment by rootzoll** [comment]
@DocBrown101 I opened an issue to update it for v1.7.1 see #2314
