### ISSUE TITLE
lnrpc error - local network connection refused causing reboot loop

### ISSUE THREAD

**Issue by originaljeremy** [raspiblitz/raspiblitz#2039]
PRECEDING ISSUE: I experienced an unknown error similar to https://github.com/rootzoll/raspiblitz/issues/1618. However, after several attempts to access, a final reboot resulted in ping/nmap not revealing host. This occurred soon after disabling lnbits and sphinx relay server following several weeks of nominal performance. I followed the issue and solutions, i.e. fan shim removal, etc, to no effect.

I had enabled/disabled various services and options: rtl, sphinx relay server (including an unsuccessful attempt to establish an IP2TOR Bridge), lightning loop, lightning pool, lnbits, static channel backup on usb drive, accept keysend

I had generated a recovery file immediately prior to the error.

I have reprovisioned 1.6.3 using the same password set as the original install, and installed recovery file via dialogue.

After complete chain sync, the raspiblitz goes into a reboot loop. 

The pi only remains open to my session briefly, so I was unable to copy current configs for bitcoin and lnd to determine if there is some rpc/password mismatch

Additionally, blk01567.dat seems unable to open, leading to a db error, unable to copy over a good file due to the reboot issue.

Unable to run 'systemctl daemon-reload' as logs suggest due to reboot issue.

Bootstrap update is again generating the same output as issue 1618 above.

I have reprovisioned a second time, with the same results.

I/O error requiring ssd replacement suspected, but just in case I wanted to post the issue for review.

Logs as follows:

***************************************************************
* RASPIBLITZ DEBUG LOGS 
***************************************************************
blitzversion: 1.6.3
chainnetwork: bitcoin / main
 17:03:19 up 2 min,  2 users,  load average: 1.91, 0.98, 0.38

*** BLOCKCHAIN SYSTEMD STATUS ***
● bitcoind.service - Bitcoin daemon
   Loaded: loaded (/etc/systemd/system/bitcoind.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
Warning: The unit file, source configuration file or drop-ins of bitcoind.service changed on disk. Run 'systemctl daemon-reload' to reload units.

*** LAST BLOCKCHAIN ERROR LOGS ***
sudo journalctl -u bitcoind -b --no-pager -n8
-- Logs begin at Fri 2021-03-05 17:00:59 GMT, end at Fri 2021-03-05 17:03:19 GMT. --
-- No entries --

*** LAST BLOCKCHAIN 20 INFO LOGS ***
sudo tail -n 20 /mnt/hdd/bitcoin/debug.log
2021-03-05T16:42:50Z init message: Loading banlist...
2021-03-05T16:42:50Z Using /16 prefix for IP bucketing
2021-03-05T16:42:50Z Cache configuration:
2021-03-05T16:42:50Z * Using 2.0 MiB for block index database
2021-03-05T16:42:50Z * Using 8.0 MiB for chain state database
2021-03-05T16:42:50Z * Using 1014.0 MiB for in-memory UTXO set (plus up to 286.1 MiB of unused mempool space)
2021-03-05T16:42:50Z init message: Loading block index...
2021-03-05T16:42:50Z Opening LevelDB in /mnt/hdd/bitcoin/blocks/index
2021-03-05T16:42:50Z Opened LevelDB successfully
2021-03-05T16:42:50Z Using obfuscation key for /mnt/hdd/bitcoin/blocks/index: 0000000000000000
2021-03-05T16:43:03Z LoadBlockIndexDB: last block file = 2417
2021-03-05T16:43:03Z LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=56, size=72170298, heights=666095...667120, time=2021-01-15...2021-01-22)
2021-03-05T16:43:03Z Checking all blk files are present...
2021-03-05T16:43:03Z Unable to open file /mnt/hdd/bitcoin/blocks/blk01567.dat
2021-03-05T16:43:03Z : Error loading block database.
Please restart with -reindex or -reindex-chainstate to recover.
2021-03-05T16:43:03Z Aborted block database rebuild. Exiting.
2021-03-05T16:43:03Z Shutdown: In progress...
2021-03-05T16:43:03Z scheduler thread exit
2021-03-05T16:43:03Z Shutdown: done

*** LND SYSTEMD STATUS ***
● lnd.service - LND Lightning Daemon
   Loaded: loaded (/etc/systemd/system/lnd.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
Warning: The unit file, source configuration file or drop-ins of lnd.service changed on disk. Run 'systemctl daemon-reload' to reload units.

*** LAST LND ERROR LOGS ***
sudo journalctl -u lnd -b --no-pager -n12
-- Logs begin at Fri 2021-03-05 17:00:59 GMT, end at Fri 2021-03-05 17:03:19 GMT. --
-- No entries --

*** LAST 30 LND INFO LOGS ***
sudo tail -n 30 /mnt/hdd/lnd/logs/bitcoin/mainnet/lnd.log
2021-03-03 12:50:51.231 [INF] LTND: Waiting for chain backend to finish sync, start_height=555003
2021-03-03 15:01:15.648 [DBG] RPCS: [listchannels] fetched 181 channels from DB
2021-03-03 15:03:41.144 [DBG] RPCS: [listchannels] fetched 181 channels from DB
2021-03-05 15:51:41.671 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: unable to sync PoV of the wallet with current best block in the main chain: Post "http://127.0.0.1:8332": dial tcp 127.0.0.1:8332: connect: connection refused
2021-03-05 15:51:42.037 [ERR] LTND: unable to determine if wallet is synced: Post "http://127.0.0.1:8332": dial tcp 127.0.0.1:8332: connect: connection refused
2021-03-05 15:51:42.038 [INF] RPCS: Stopping RPC Server
2021-03-05 15:51:42.041 [INF] RPCS: Stopping ChainRPC Sub-RPC Server
2021-03-05 15:51:42.047 [INF] RPCS: Stopping WatchtowerRPC Sub-RPC Server
2021-03-05 15:51:42.051 [INF] RPCS: Stopping RouterRPC Sub-RPC Server
2021-03-05 15:51:42.054 [INF] RPCS: Stopping SignRPC Sub-RPC Server
2021-03-05 15:51:42.054 [INF] RPCS: Stopping AutopilotRPC Sub-RPC Server
2021-03-05 15:51:42.058 [INF] RPCS: Stopping InvoicesRPC Sub-RPC Server
2021-03-05 15:51:42.060 [INF] RPCS: Stopping VersionRPC Sub-RPC Server
2021-03-05 15:51:42.062 [INF] RPCS: Stopping WalletKitRPC Sub-RPC Server
2021-03-05 15:51:42.062 [INF] RPCS: Stopping WatchtowerClientRPC Sub-RPC Server
2021-03-05 15:51:42.092 [INF] LTND: Shutdown complete
2021-03-05 15:53:00.116 [INF] LTND: Version: 0.11.1-beta commit=v0.11.1-beta, build=production, logging=default
2021-03-05 15:53:00.116 [INF] LTND: Active chain: Bitcoin (network=mainnet)
2021-03-05 15:53:00.116 [INF] LTND: Opening the main database, this might take a few minutes...
2021-03-05 15:53:00.116 [INF] LTND: Opening bbolt database, sync_freelist=false
2021-03-05 15:56:11.696 [INF] CHDB: Checking for schema update: latest_version=17, db_version=17
2021-03-05 15:56:11.696 [INF] LTND: Database now open (time_to_open=3m11.57931686s)!
2021-03-05 15:56:11.722 [INF] RPCS: password RPC server listening on 0.0.0.0:10009
2021-03-05 15:56:11.723 [INF] RPCS: password gRPC proxy started at 0.0.0.0:8080
2021-03-05 15:56:11.723 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.
2021-03-05 16:43:04.526 [INF] LTND: Received terminated
2021-03-05 16:43:04.526 [INF] LTND: Shutting down...
2021-03-05 16:43:04.526 [INF] LTND: Gracefully shutting down.
2021-03-05 16:43:04.527 [ERR] LTND: unable to set up wallet password listeners: shutting down
2021-03-05 16:43:04.559 [INF] LTND: Shutdown complete
*** LAST NGINX LOGS ***
sudo journalctl -u nginx -b --no-pager -n20
-- Logs begin at Fri 2021-03-05 17:00:59 GMT, end at Fri 2021-03-05 17:03:19 GMT. --
Mar 05 17:01:50 raspberrypi systemd[1]: Starting A high performance web server and a reverse proxy server...
Mar 05 17:01:50 raspberrypi nginx[618]: nginx: [emerg] BIO_new_file("/mnt/hdd/app-data/nginx/tls.cert") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/mnt/hdd/app-data/nginx/tls.cert','r') error:2006D080:BIO routines:BIO_new_file:no such file)
Mar 05 17:01:50 raspberrypi nginx[618]: nginx: configuration file /etc/nginx/nginx.conf test failed
Mar 05 17:01:50 raspberrypi systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
Mar 05 17:01:50 raspberrypi systemd[1]: nginx.service: Failed with result 'exit-code'.
Mar 05 17:01:50 raspberrypi systemd[1]: Failed to start A high performance web server and a reverse proxy server.
--> CHECK CONFIG: sudo nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

- TOUCHSCREEN is OFF by config
- Loop is OFF by config
- RTL is OFF by config
- Electrum Rust Server is OFF by config
- BTCPayServer is OFF by config
- LNbits is OFF by config
- Thunderhub is OFF by config
- SPECTER is OFF by config
- SPHINX is OFF by config

*** MOUNTED DRIVES ***
Filesystem           Type         1K-blocks      Used            Available    Use%      Mounted on
/dev/root              ext4          61078228       5873368     52673556   11%        /
devtmpfs             devtmpfs   4045052         0                4045052      0%         /dev
tmpfs                   tmpfs        4078844          0               4078844      0%         /dev/shm
tmpfs                   tmpfs        4078844          8664         4070180      1%         /run
tmpfs                   tmpfs         5120               4               5116            1%        /run/lock
tmpfs                   tmpfs        4078844          0               4078844      0%        /sys/fs/cgroup
tmpfs                   tmpfs        32768              0               32768          0%        /var/cache/raspiblitz
/dev/mmcblk0p1  vfat          258095            52308        205787        21%      /boot
tmpfs                   tmpfs       815768             0                815768        0%       /run/user/1000
/dev/sda1            ext4         960379920      366473636 545051860  41%      /mnt/hdd
tmpfs                  tmpfs        815768            0                 815768        0%       /run/user/1001

*** WIFI Info ***
activated=0
connected=0
localip=''

*** HARDWARE TEST RESULTS ***
raspberryPi=4
powerFAIL=0
powerWARN=0
powerMIN='870000 microVolt'
tempFAIL=0
tempWARN=0
tempMAX='4300 centiGrad'

*** SYSTEM STATUS (can take some seconds to gather) ***
localIP='192.168.x.x'
tempCelsius='42.8'
uptime=128
upsStatus='OFF'
startcountBlockchain=0
bitcoinActive=0
startcountLightning=0
lndActive=0
blitzTUIActive=0
blitzTUIRestarts=0
scriptRuntime=0

**Comment by nyxnor** [comment]
Use the recommended SSD enclosure. Others can be faulty.
https://github.com/rootzoll/raspiblitz#package-standard-around-250-usd

**Comment by rootzoll** [comment]
@jeremy-op which ssd casing are you using? Is it that one from the shopping list?

**Comment by originaljeremy** [comment]
I am using a 1tb Verbatim external ssd

**Comment by originaljeremy** [comment]
https://www.amazon.com/Verbatim-1TB-External-Hard-Drive/dp/B005AT5V00

**Comment by rootzoll** [comment]
So this is an HDD not an SSD .. I dont have experience with that brand. But you could rule out the problem when you run the HDD on a USB2 port (instead on the blue USB3 ports) of the RaspberryPi4. USB2 is much slower - but because you use an HDD anyway the slowdown should not be too much.

**Comment by originaljeremy** [comment]
Yes, sorry - I meant hdd. I see now I typed it incorrectly.

**Comment by originaljeremy** [comment]
Running over USB2 caused the raspiblitz to recover previous config, prompt for new password 'a', force reboot, on reboot 'blockchain info' loading screen displays while the same issue occurs. Logs as follows:

***********************************************
Running RaspiBlitz Bootstrap 1.6.3
Mon  8 Mar 18:31:15 GMT 2021
***********************************************
# blitz.lcd.sh check-repair
# --> old kernel detected - no need to update LCD drivers.
error='unkown command'
isMounted: 0
HDD is there but not AutoMounted yet - checking Setup
Temp mounting data drive (sda)
Refreshing links between directories/drives ..
HDD contains already a configuration: 1
Found existing configuration
Found valid configuration
Calling Data Migration ..
STARTED Migration/Init
prechecks OK
default values OK
Checking old bitcoin.conf ...
check issue #217 -> ok rpcallow exists
check issue #950 -> ok ^rpcport does not exist
check issue #950 -> ok ^rpcbind does not exist
check issue #217 -> ok main.rpcport exists
check issue #217 -> ok main.rpcbind exists
check issue #950 -> ok test.rpcport exists
check issue #950 -> ok test.rpcbind exists
Version Code: 1.6.3
Version Data: 1.6.3
OK - version of config data is up to date
END Migration/Init
Calling Provisioning ..
STARTED Provisioning from preset config file
CHECK IF SD CARD NEEDS EXPANSION
rootPartition(mmcblk0p2)
rootPartitionBytes(63591940096)
### CHECKING ROOT PARTITION SIZE ###
Size in Bytes is: 63591940096 bytes on (mmcblk0p2)
Size looks good. Bigger than 8192000000 byte disk is used.
### BASIC SYSTEM SETTINGS ###
Setting lightning alias: XXXXXX
Old SSH PubKey exists on HDD > copy them HDD to SD card for next start
Copy HDD content for user admin
mkdir: cannot create directory ‘/home/admin/.bitcoin’: File exists
mkdir: cannot create directory ‘/home/admin/.lnd’: File exists
cp: '/mnt/hdd/lnd/lnd.conf' and '/home/admin/.lnd/lnd.conf' are the same file
cp: '/mnt/hdd/lnd/tls.cert' and '/home/admin/.lnd/tls.cert' are the same file
mkdir: cannot create directory ‘/home/admin/.lnd/data’: File exists
*** Make backup of LND directory
OK Backup is valid.


installing bash completion for bitcoin-cli and lncli
--2021-03-08 18:33:05--  https://raw.githubusercontent.com/bitcoin/bitcoin/master/contrib/bitcoin-cli.bash-completion
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4247 (4.1K) [text/plain]
Saving to: ‘bitcoin-cli.bash-completion’

     0K ....                                                  100% 9.83M=0s

2021-03-08 18:33:06 (9.83 MB/s) - ‘bitcoin-cli.bash-completion’ saved [4247/4247]

--2021-03-08 18:33:06--  https://raw.githubusercontent.com/lightningnetwork/lnd/master/contrib/lncli.bash-completion
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1498 (1.5K) [text/plain]
Saving to: ‘lncli.bash-completion’

     0K .                                                     100% 3.52M=0s

2021-03-08 18:33:06 (3.52 MB/s) - ‘lncli.bash-completion’ saved [1498/1498]

OK - bash completion available after next login
type "bitcoin-cli getblockch", press [Tab] → bitcoin-cli getblockchaininfo
SWAP already OK

*** Setting and Activating Firewall ***
Reading package lists...
Building dependency tree...
Reading state information...
ufw is already the newest version (0.36-1).
The following package was automatically installed and is no longer required:
  libbluetooth3
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 204 not upgraded.
deny incoming connection on other ports
Default incoming policy changed to 'deny'
(be sure to update your rules accordingly)
allow outgoing connections
Default outgoing policy changed to 'allow'
(be sure to update your rules accordingly)
allow: ssh
Skipping adding existing rule
Skipping adding existing rule (v6)
allow: bitcoin testnet
Skipping adding existing rule
Skipping adding existing rule (v6)
allow: bitcoin mainnet
Skipping adding existing rule
Skipping adding existing rule (v6)
allow: litecoin mainnet
Skipping adding existing rule
Skipping adding existing rule (v6)
allow: lightning testnet
Skipping adding existing rule
Skipping adding existing rule (v6)
allow: lightning mainnet
Skipping adding existing rule
Skipping adding existing rule (v6)
allow: lightning gRPC
Skipping adding existing rule
Skipping adding existing rule (v6)
allow: lightning REST API
Skipping adding existing rule
Skipping adding existing rule (v6)
allow: transmission
Skipping adding existing rule
Skipping adding existing rule (v6)
allow: public web HTTP
Skipping adding existing rule
Skipping adding existing rule (v6)
allow: local web admin HTTPS
Skipping adding existing rule
Skipping adding existing rule
Skipping adding existing rule
open firewall for auto nat discover (see issue #129)
Skipping adding existing rule
Skipping adding existing rule
Skipping adding existing rule
enable lazy firewall
Firewall is active and enabled on system startup


*** Update System ***
raspberrypi-bootloader was already set on hold.
Hit:1 http://raspbian.raspberrypi.org/raspbian buster InRelease
Hit:2 http://archive.raspberrypi.org/debian buster InRelease
Hit:3 https://deb.torproject.org/torproject.org buster InRelease
Reading package lists...
OK - System is now up to date
### RUNNING PROVISIONING SERVICES ###
Provisioning BLITZ WEB SERVICE - run config script
Turning ON: Web
Hit:1 http://raspbian.raspberrypi.org/raspbian buster InRelease
Hit:2 http://archive.raspberrypi.org/debian buster InRelease
Hit:3 https://deb.torproject.org/torproject.org buster InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
apache2-utils is already the newest version (2.4.38-3+deb10u4).
nginx is already the newest version (1.14.2-2+deb10u3).
The following package was automatically installed and is no longer required:
  libbluetooth3
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 204 not upgraded.
Synchronizing state of nginx.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable nginx
Reading package lists...
Building dependency tree...
Reading state information...
python3-jinja2 is already the newest version (2.10-2).
The following package was automatically installed and is no longer required:
  libbluetooth3
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 204 not upgraded.
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: j2cli in /usr/local/lib/python3.7/dist-packages (0.3.10)
Requirement already satisfied: jinja2>=2.7.2 in /usr/lib/python3/dist-packages (from j2cli) (2.10)
Provisioning LND interims update - keep default
Provisioning TESTNET - keep default
Provisioning TOR - run config script
os='raspbian'
making sure services are not running
switching the TOR ON

*** Check if TOR service is functional ***
TOR not running ... proceed with switching to TOR.

TOR package/service is installed and was prepared earlier .. just activating again
*** Enable TOR Service ***
The unit files have no installation config (WantedBy=, RequiredBy=, Also=,
Alias= settings in the [Install] section, and DefaultInstance= for template
units). This means they are not meant to be enabled using systemctl.
 
Possible reasons for having this kind of units are:
• A unit may be statically enabled by being symlinked from another unit's
  .wants/ or .requires/ directory.
• A unit's purpose may be to act as a helper for some other unit which has
  a requirement dependency on it.
• A unit may be started when needed via activation (socket, path, timer,
  D-Bus, udev, scripted systemctl call, ...).
• In case of template units, the unit is meant to be enabled with some
  instance name specified.

*** Changing bitcoin Config ***
Addding TOR config ...
*** Putting LND behind TOR ***
Make sure LND is disabled
editing /etc/systemd/system/lnd.service
Enable LND again
Created symlink /etc/systemd/system/multi-user.target.wants/lnd.service → /etc/systemd/system/lnd.service.
OK

sudo: unknown user: sphinxrelay
sudo: unable to initialize policy plugin
Setup logrotate
OK - TOR is now ON
needs reboot to activate new setting
Provisioning AUTO PILOT - keep default
Provisioning NETWORK UPnP  - keep default
Provisioning AUTO NAT DISCOVERY - keep default
Provisioning DYNAMIC DOMAIN - keep default
Provisioning RTL - keep default
Provisioning Lightning Loop - keep default
Provisioning BTCRPCexplorer - keep default
Provisioning ElectRS - keep default
Provisioning BTCPayServer - keep default
Provisioning lndmanage - not active
Provisioning LND Port
User is running standard LND port: 9735
Provisioning DNS Server - keep default
Provisioning Root SSH Keys - keep default
Provisioning SSH Tunnel - not active
Provisioning ZeroTier - not active
Provisioning LCD rotate - run config script
# Turn ON: LCD ROTATE
# OK - a restart is needed: sudo shutdown -r now
Provisioning Touchscreen - not active
Provisioning UPS - not active
Provisioning LNbits - keep default
Provisioning JoinMarket - keep default
Provisioning Specter - keep default
Provisioning Faraday - keep default
Provisioning Balance of Satoshis - keep default
Provisioning ThunderHub - keep default
Provisioning Mempool Explorer - keep default
Provisioning letsencrypt - keep default
Provisioning kindle-display - keep default
Provisioning pyblock - keep default
Provisioning Stacking Sats Kraken - keep default
Provisioning Pool - keep default
Sphinx-Relay - keep default
Provisioning CircuitBreaker - keep default
Running the custom install script ..
'/mnt/hdd/app-data/custom-installs.sh' -> '/home/admin/custom-install.sh'
There are no custom user installs so far.
Done

*** Replay backup of LND conf/tls
Copying TLS ...
On next final restart admin creds will be updated by _boostrap.sh
DONE

*** Repair Bitcioin Conf (if needed)
Aligning lnd.conf & bitcoin.conf
Not setting local network hostname
Prepare fstab for permanent data drive mounting ..
datadisk --> sda
datapartition --> sda1
# unmounting all drives
# waiting until uuid gets available
# mount /mnt/hdd
# waiting until mounting is active
# OK - fstab updated for EXT4 layout
DONE - Give raspi some cool off time after hard building .... 5 secs sleep
END Provisioning
rebooting
shutdown in 1min

**Comment by rootzoll** [comment]
We recommedn the use of SSDs nowadays because HDDs on a raspberrypi tend to get into data corruption problems. So I would recommend to get a SSD - best would also to stick close to the shopping list because some SSDs are too power hungry also for the RaspberryPi and as mentioned some SSD casings also make problems. Those mentioned in the shopping list we had the best results so far.

If you had funds/channels on the LND I would recommend to get to the terminal and export an LND-Rescue-File and use that then again on a fresh setup with the new SSD. This chapter in the FAQ should be a good starting point: https://github.com/rootzoll/raspiblitz/blob/v1.6/FAQ.md#how-can-i-recover-my-coins-from-a-failing-raspiblitz

**Comment by originaljeremy** [comment]
Ok, thank you.
