### ISSUE TITLE
Confusing wording?

### ISSUE THREAD

**Issue by keblek** [raspiblitz/raspiblitz#2042]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/68111648/110259925-58728480-7faa-11eb-91ad-46fd4f34b89a.png">

Would be clearer if it said, "it can be hard to connect to pi when away from home".

**Comment by rootzoll** [comment]
Thanks will put in list for next release.

**Comment by rootzoll** [comment]
OK changed the wording. Will be part of v1.7RC1 release. Closing issue.
