### ISSUE TITLE
Adapt to new LND PGP manifest scheme

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2046]
There are now multiple signatures for the manifest - see: https://github.com/lightningnetwork/lnd/releases/tag/v0.12.1-beta

Adapt `lnd.update.sh` for this like already done with the build script.

**Comment by openoms** [comment]
This is adapted to the latest release format: https://github.com/openoms/lightning-node-management/blob/master/lnd.updates/lnd.update.sh
