### ISSUE TITLE
Issue connecting to Btc-rpc, RTL, & Electrum RS

### ISSUE THREAD

**Issue by Shampow8** [raspiblitz/raspiblitz#2049]
I have my node set up and I downloaded btc-rpc explorer, RTL web node manager, Electrum Rust Server, etc.. But, when I try to scan the QR code it doesn't allow me to visit the website. I get an error message.

Unable to connect:
The site could be temporarily unavailable or too busy. Try again in a few moments.

If you are unable to load any pages, check your device’s data or Wi-Fi connection.

This happens on all web browsers.

**Comment by openoms** [comment]
Try restarting the node.

Test nginx with:
`sudo nginx -t`

**Comment by nyxnor** [comment]
@Shampow8 Close this pls if solved.
