### ISSUE TITLE
Recover funds

### ISSUE THREAD

**Issue by jetlagv1** [raspiblitz/raspiblitz#205]
My raspiblitz system doesn't want to start lnd anymore after rebooting. It looks like it the harddrive is corrupted. How can I recover the funds? Some funds are in channels and some in the wallet.

**Comment by RolfHodl** [comment]
Hello jetlagv1,

Rootzoll write some helpfull informations about this state of the raspiblitz.

https://github.com/rootzoll/raspiblitz#recover-your-coins-from-a-failing-raspiblitz

hope that helps you!

**Comment by jetlagv1** [comment]
Hi CryptoSigmunt. Thank you for posting the link but it doesn't seem to take me anywhere. I'm not that familiar with github and I'm using it on my phone right now but the link only takes me to the first page of Raspiblitz. Can you point me a little further?

**Comment by RolfHodl** [comment]
Then it's a browser issue... it should bring you to the bottom of the first page where Rootzoll discribes how to recover funds.
Headline is "Recover your Coins from a failing RaspiBlitz" ;)

**Comment by fluidvoice** [comment]
"It looks like it the hard drive is corrupted." why do you think this?  You should post debug log output so we can see the errors. Try the terminal command 
`sudo journalctl -f -u lnd`
and/or by running these two scripts:
```
./XXupdateScripts.sh
./XXdebugLogs.sh
```

**Comment by WetPuppyKisses** [comment]
This is always has been my fear.

I tried to get the private key from one of my address with no luck. The dumpprivatekey command is not working for me. I am pretty sure that I am doing something wrong.

anyone knows how to get the private key with the raspiblitz?

**Comment by fluidvoice** [comment]
I'm thinking there is nothing specific about Raspiblitz with respect to wallets and keys.  It's running Bitcoin Core under the hood. So you might get better results searching and posting this question on Bitcoin core discussion sites. I don't know the answer off the top of my head.  See: [https://bitcoin.org/en/community](https://bitcoin.org/en/community)
Did you try using the bitcoin-qt salvagewallet command?
[G50 ~]$ bitcoin-qt --help |grep -b2 -i keys
7884-
7885-  -salvagewallet
7902:       Attempt to recover private keys from a corrupt wallet on startup
7974-

**Comment by DaReaLDeviL** [comment]
So the 24 Word Seed is just for LN? I don't get the whole picture in it. I thought saving my 24 words will always recover funds who are not in any channels? And to secure it more I can do something like a password D?

**Comment by rootzoll** [comment]
To clear things up: Bitcoind is not managing any wallet - you can see that wallet funtion is deactivated in `/mnt/hdd/bitcoin/bitcoin.conf`. @WetPuppyKisses thats why a dumpprivatekey command is not working on bitcoind.

LND is doing all the wallet handling of your on-chain and off-chain funds. To backup and recover your private key - thats the word seed list you get when creating your LND wallet.

Sadly it seems that LND has still no export function after that:
https://github.com/lightningnetwork/lnd/issues/732

When you setup a fresh RaspiBlitz and you come to the point to create the LND wallet you can say that you already have a Mnemonic Seed (the word list) and enter it. Then LND will work with your old private key and recover all the on-chain funds for you.

I never tried, but the Mnemonic Seed (word list) should be standard and should also work in other bitcoin wallets.

The thing with your off-chain funds (bitcoin locked in multisig lighting channel) is that the Mnemonic Seed does not recover all your channel states. Here it gets tricky .. LND should be able on rescanning the blockhain discover that you have a funds in a channel - but cannot force close it. If you are lucke your channel counter part will force close and unfreeze the funds - but there is also the danger that the channel counter part will try to cheat with an old state and you cannot stop it.

That brings us to the topic of backup on your node ... I started a FAQ on that:
https://github.com/rootzoll/raspiblitz/blob/master/FAQ.md

For more details on recover funds please checkout the LND Dev Slack channel https://lightningcommunity.slack.com 

I am closing this issue for RaspiBlitz for now. If anybody finds good resources on the internet about this topic please still post here.

**Comment by walletofsatoshi** [comment]
Seed is not working on other bip39 Wallets like electrum

**Comment by walletofsatoshi** [comment]
so I recovered funds on new setup today with lnd folder from previous setup on a new setup. When I check funds directly via raspiblitz menu I am getting this error 
./00mainMenu.sh: line 419: lnbalance: command not found

but when I connected via zapwallet reckless can access all funds and all channels were recovered. So if someone needs help if not finding funds after recovery just connect via zapwallet reckless and it should show up. If you need any help ping me.

**Comment by rootzoll** [comment]
The `./00mainMenu.sh: line 419: lnbalance: command not found` error is not critical an will be fixed in next release.

@walletofsatoshi can you describe more in detail on how you managed the recover with "zapwallet reckless" - is that a special version of zap wallet?

**Comment by walletofsatoshi** [comment]
No I am connecting zap wallet over internet . I and ran few commands from terminal for command not found from earlier similar issue which fixed it.

The balance was not showing in raspiblitz since it was giving error with command not found issue but was showing on my zapwallet.

**Comment by rootzoll** [comment]
@walletofsatoshi ah ok got it, thx.
