### ISSUE TITLE
Fee-PerMil unit is confusing or wrong

### ISSUE THREAD

**Issue by Svobodan** [raspiblitz/raspiblitz#2051]
**Issue:**
When listing channels with "lnchannels" option in RaspiBlitz menu the description says:

> Fee-PerMil -> amount based fee (millisatoshis per 1 satoshi) on forwarding

But then the table shows value that is 1000 times higher than it should. For instance the default fee rate value after opening a channel is 1 meaning one milionth, not one thousandth as suggested. If value is set to 10000, then fee rate is 1%.

Or perhaps the intention was to say "1 permil of a millisatoshi per satoshi"? This would be confusing for human as it combines fractions that include prefixes with percentages.

**Suggestion:**

1. Change values (divide by 1000) in the table to match PerMil (‰)
or
2. Change values to percent - most familiar to humans but too many decimal places
or
3. Change description to:
> Fee Rate -> amount based fee (1 satoshi per million satoshi) on forwarding

**Background:**
I remember I was confused the first time seeing this and I just assumed that permil means per million but in fact it means per thousand. Today I was remindend of this when responding to someone regarding RTL https://github.com/Ride-The-Lightning/RTL/issues/621 where I describe what units should be used IMO.

**Comment by Svobodan** [comment]
[https://github.com/Ride-The-Lightning/RTL/issues/621#issuecomment-798298671](url)

**Comment by rootzoll** [comment]
Thanks I will take a look for the next release.

**Comment by Svobodan** [comment]
This is what they have on 1ml.com. I find that quite easy to read.

![fee_rate_1ML](https://user-images.githubusercontent.com/77900472/111086542-df7cab00-851c-11eb-9cc9-56dea810fc9c.png)

**Comment by openoms** [comment]
Fee calculation has many standards unfortunately:

![image](https://user-images.githubusercontent.com/43343391/111230641-dd2f5500-85df-11eb-9204-e8f5dab3548e.png)
![image](https://user-images.githubusercontent.com/43343391/111230720-f7693300-85df-11eb-8a6e-c2e86ff2c806.png)
