### ISSUE TITLE
Raspberry Pi Shutting Off during Boot Up Phase

### ISSUE THREAD

**Issue by paedeveloper** [raspiblitz/raspiblitz#2055]
Hello! I just flashed my SD Card with RaspiBlitz and when I boot up, I always get a last message

 `i2c /dev entries driver`

and then the raspberry pi turns off by itself.

Have not been able to fix it so far. 

Can anyone help?

**Comment by rootzoll** [comment]
This error is a nasty one .. see this on-going issue:
https://github.com/rootzoll/raspiblitz/issues/1940

I am closing this one as a duplicate.
