### ISSUE TITLE
Tor by Default

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2056]
So the goal is to have Tor now by default switched on. This will make the setup shorter (one option less) and also enables to use Tor already as much as possible thru the setup. Also for a future Web-GUI ist can start with offering a Tor-Webseite for setup.

The following sub tickets are part of this bigger mission:
- [x] https://github.com/rootzoll/raspiblitz/issues/1990
- [x] https://github.com/rootzoll/raspiblitz/issues/1973
- [x] https://github.com/rootzoll/raspiblitz/issues/1888
- [x] https://github.com/rootzoll/raspiblitz/pull/1819
- [x] https://github.com/rootzoll/raspiblitz/issues/1652
- [x] check Bitcoind is using/upgrading to TorV3
- [x] check LND is using/upgrading to TorV3
- [x] dont ask anymore if IBD should be done over Tor or CleanIP (just go TorByDefault)

**Comment by Kixunil** [comment]
What kind of web UI are you planning? I have some [nice UI](https://github.com/Kixunil/selfhost-dashboard) and working on more. Feel free to use it if you like it.

It's designed to integrate with `selfhost` packages from my repository, but should be easy enough to do it outside or just use the base selfhost packages. They are very small and platform-independent. I know of someone who already tried these things on RPi and it works without huge problems. There's a bug with dashboard not reconnecting to postgres but that's should be easy to fix and I plan to do it soon.

`selfhost` supports both Tor and clearnet and is quite clean and composable (although not as much as I want it to be) so maybe that's useful too.

**Comment by rootzoll** [comment]
@Kixunil thanks for info on your WebUI ... we plan to go for a WebUI for the v1.8 release. I moved that over to the following issue: https://github.com/rootzoll/raspiblitz/issues/43

**Comment by nyxnor** [comment]
### Edit: He/She is now able to do it using bridges and tor:// to both onion address or clear ones.

I think https://github.com/rootzoll/raspiblitz/issues/2054 is also a ticket for Tor by default, cause if @pretyflaco can't surpass that, he won't be able to use Blitz.
Consider tor replace the Tor packages on source.list as mentioned here https://github.com/rootzoll/raspiblitz/issues/2054#issuecomment-801091282
Explanation: 
* Another layer of protection, I think `UseBridges 1` on torrc might do it for censorship.
* Adding anonimity with APT over Tor for TOR packages would be awesome if added by default. See my next comment as it worked for Flaco.

Edit: removed this line:
> It is a v2 address, so a v3 attack to the tor network wont affect the installation or update.

**Comment by openoms** [comment]
@Ben10Brasileiro just keep in mind that v2 services will be retired starting from 15th July 2021: https://blog.torproject.org/v2-deprecation-timeline

**Comment by nyxnor** [comment]
Edit (25/03/2021): It is more valuable to use `tor://onionAddress.onion` over `tor://deb.torproject.org` and here is why (but will have to wait until v3 repo):
1. It is [end-to-end encrypted reaching the onion service](https://blog.torproject.org/tor-heart-apt-transport-tor-and-debian-onions), so no exit nodes can see the info. The passes all 6 hops encrypted, just unencrypted on server and client side. With this option, metadata analysis of the packages fails, as each encryption makes the package a different size. [Step 4 and 5 of tor docs](https://2019.www.torproject.org/docs/onion-services) and [git info](https://gitweb.torproject.org/torspec.git/tree/rend-spec-v3.txt) // [This is Tor connection when reaching clearnet](https://support.torproject.org/https/https-1/), and for when reaching hidden services, there is no data leakage on exit nodes.
2. Tor onion repo is http, not https, but it doesnt make a difference as Roger Dingledine (arma) stated: "[Tor's .onion handshake basically gives you all of that for free"](https://blog.torproject.org/facebook-hidden-services-and-https-certs)
4. If using Tor for APT, including onion would be the best thing. FULL TOR. [Paper of tor design, search of end-to-end.](https://svn-archive.torproject.org/svn/projects/design-paper/tor-design.pdf). Although I will wait to put Tor repo v3 on the code (hopefully July).

Old comment (works, but less secure by a bit, as explained topic 1 above).
@openoms That is a legitimate concern.
Mirrors are another option, if they are not blocked too (but the ISP can log the DNS queries, if the user dont take some actions, so maybe someday it could notice it.This is why I present the solution below (tested on desktop, but on the pi would be the same thing using the raspbian archive site with tor:// at the beggining).

I changed https with tor on the url, with the clearnet Tor project site, but this time the request will be made with tor (I think that is how it works based on it actually hitting, and the tor project using tor:// at the beggining.
To back this claim:
* https://askubuntu.com/questions/381377/apt-get-update-through-tor, 
* and this archived repo from a really long time ago https://github.com/timretout/apt-transport-tor.

But this would only be for `UPDATE`. For different ways of getting tor (INSTALLATION) https://support.torproject.org/gettor/
I tried with `tor://` and `tor+http://` but both worked, did not see a difference.
```
deb        tor://deb.torproject.org/torproject.org      buster            main
deb-src    tor://deb.torproject.org/torproject.org      buster            main
```

Output
```
root@debian:/etc/apt# apt update
Hit:4 tor://security.debian.org/debian-security buster/updates InRelease         
Hit:9 tor://deb.debian.org/debian buster InRelease                           
Hit:10 tor://deb.torproject.org/torproject.org buster InRelease                 
Hit:12 tor://deb.debian.org/debian buster-updates InRelease
Fetched 9,511 B in 2s (4,498 B/s)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
```

Edit to this comment.
To get the sources worked for the person under repressive regime. The person added bridges too. More details on the main issue being discussed about some problems/errors.
The person could not hit with `https://`, but did manage to hit with `tor://` and bridges.
![TorCens](https://user-images.githubusercontent.com/69700936/111801871-45728500-88c5-11eb-8ed6-e5113e68d4ae.jpg)

**Comment by rootzoll** [comment]
OK to most important issues are part if the v1.7 release ... some smaller parts are pushed to v1.7.1

**Comment by nyxnor** [comment]
@openoms Found the v3 repo:
Onion list: https://onion.torproject.org/ // http://xao2lxsmia2edq2n5zxg6uahx6xox2t7bfjw6b5vdzsxi7ezmqob6qid.onion/
Tor v3 repo:
http://apow7mjfryruh65chtdydfmqfpj5btws7nbocgtaovhvezgccyjazpqd.onion/

**Comment by rootzoll** [comment]
OK ... this looks & tested good so far for v1.7 release. Closing issue.
