### ISSUE TITLE
Add Forwarding Statistics

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#206]
It would be great if you can see on the LCD the forwarding total amount and/or last date as a running statistic. For code inspiration: https://github.com/hpbock/lndFwdingDiagram

Its would be OK to have it every 1min gather/update the statistic as part of the _background.sh process not to put too much load on the LND. This issue can be used to start a display info file on the HDD thats part of the comming display service.

**Comment by frennkie** [comment]
done: https://github.com/rootzoll/raspiblitz/pull/1004/files
