### ISSUE TITLE
Test & make sure updated apps run correctly

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2066]
merged #2043 .. but now make sure that all those apps run correctly.

BTCpayServer has still error:
`Mar 16 23:14:36 raspberrypi dotnet[12088]: Unhandled exception. System.InvalidOperationException: No database option was configured.` see https://github.com/rootzoll/raspiblitz/pull/2043#issuecomment-800674779

**Comment by openoms** [comment]
BTCpay is fixed in: https://github.com/rootzoll/raspiblitz/pull/2067

**Comment by rootzoll** [comment]
Worked in Test:
- [X] BTCPayServer
- [X] Thunderhub
- [X] BOS
- [X] Specter
- [X] joininbox & joinmarket

**Comment by rootzoll** [comment]
OK my first tests look good - keeping this issue open for final testing before release.

**Comment by rootzoll** [comment]
OK .. apps looking good. Closing issue for v1.7 release.
