### ISSUE TITLE
Screen remains blank

### ISSUE THREAD

**Issue by josephtyler** [raspiblitz/raspiblitz#2082]
I ordered the screen that was linked to in the README file. I set Raspiblitz up a few weeks ago and the screen just came in today, maybe there were some missing installation steps because I didn't have the screen connected during setup?

I turned the screen on in the raspiblitz config, and after a reboot it remains blank.

Sadly, the calibrate script does nothing.

The only errors I see when turning the screen on is that `apt-get update` seems to fail, but it seems that all of the apt packages are still installed in the following lines.

Any help you can offer would be greatly appreciated.

**Comment by openoms** [comment]
Reminds me of this issue: https://github.com/rootzoll/raspiblitz/issues/1992#issuecomment-790586335
you might find something helpful there.

**Comment by nyxnor** [comment]
@josephtyler Was this solved? Pls close if so.

**Comment by nyxnor** [comment]
@rootzoll Please close this
