### ISSUE TITLE
[Feature request] [Onboarding] Some kind of hint to the official RaspiBlitz documentation in the setup phase

### ISSUE THREAD

**Issue by timrauhut** [raspiblitz/raspiblitz#2083]
When I set up my RaspiBlitz as a new user it would be great to get a hint in the beginning, for example, a link, to the official RaspiBlitz documentation or RaspiBlitz wiki where I can find more information when I get stuck in the setup.

**Comment by rootzoll** [comment]
Yeah this could be part of the UI rework ... targeting for v1.8

**Comment by rootzoll** [comment]
@mrsellars once the v1.8.0 with the new WebUI is out - feel free to share your ideas in more detail where to add more on-boarding information. Pushing this to v1.8.1 for now.

**Comment by rootzoll** [comment]
@cstenglein now that we have the new documentation, shoudl we add a link to it during the WebUI setup?

**Comment by cstenglein** [comment]
Sure => Ticket

**Comment by rootzoll** [comment]
OK tickt is now open on WebUI repo:
https://github.com/raspiblitz/raspiblitz-web/issues/724

**Comment by cstenglein** [comment]
Will be added with https://github.com/raspiblitz/raspiblitz-web/pull/782
