### ISSUE TITLE
[Feature request] HDD sync status in the copy station script (XXcopyStation.sh)

### ISSUE THREAD

**Issue by timrauhut** [raspiblitz/raspiblitz#2084]
When I start a new "sync batch" with a lot of fresh HDDs it would be nice to get the current sync status every 10 minutes or so in percent of each HDD. With this information, it would be possible to remove already synced HDDs from the rack and get new ones in.

**Comment by rootzoll** [comment]
Will take a look again if we are closer to a 1.7.1rc2 - then we can test directly on a working copy station.
