### ISSUE TITLE
Watchtower client setup

### ISSUE THREAD

**Issue by Svobodan** [raspiblitz/raspiblitz#2085]
I am trying to set up a watchtower client and connect to a watchtower following this manual: https://github.com/lightningnetwork/lnd/blob/master/docs/watchtower.md

When I get to turning on the client I get this:
```
$ sudo lnd --wtclient.active
loadConfig: either bitcoin.active or litecoin.active must be set to 1 (true)
```
I am worried I will mess something up if I fiddle with the bitcoin.active when I do not uderstand it. How should I go about this?

**Comment by openoms** [comment]
Use this guide: https://github.com/openoms/lightning-node-management/blob/master/watchtower.md

**Comment by Svobodan** [comment]
Thanks! I have got it up and running.

**Comment by maximlomans** [comment]
yeah thanks openoms ; ) me too searched and found this 'watchtower' thread, now i almost have watchtower set up , if only the guide link was as willing : ( we'll decypher the url and get there on foot towards openoms/lightning-node-management and look for the blob master...SUMMARY.md

**Comment by openoms** [comment]
The directory structure has changed. 
New link: 
https://github.com/openoms/lightning-node-management/blob/master/advanced-tools/watchtower.md
or for a prettier format (and Spanish option) :
https://www.lightningnode.info/advanced-tools/watchtower

**Comment by openoms** [comment]
closing as solved
