### ISSUE TITLE
lnd_graph_crawl on raspiblitz

### ISSUE THREAD

**Issue by SepticFrank** [raspiblitz/raspiblitz#2087]
Hi all,

This would be a really cool feature to run using a raspiblitz. Is it possible?

Apologies if this is the wrong place for this. This is my first time using Github.

Thanks

https://github.com/mutatrum/lnd_graph_crawl

**Comment by openoms** [comment]
This is really cool, would like to see it! Added the `hackaton` label for the weekend.
Twitter thread from @mutatrum : https://twitter.com/mutatrum/status/1372954677772496898

**Comment by nyxnor** [comment]
Done, pls close this issue @SepticFrank
