### ISSUE TITLE
Update Sphinx-Relay 2.0.3

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2089]
Make sure for the Sphix-Relay to be up-to-date and work with the latest releases of the Sphix App.
https://github.com/stakwork/sphinx-relay/releases

Also fix issues related to Sphinx:
- [x] #1862 
- [x] #2002 
- [x] retest stable update/recovery
- [x] add check that at user has at least one channel open before connecting app
- [x] check fresh install again over menu (there was 'enter password for user sphinxrelay' not sure why)

**Comment by rootzoll** [comment]
Opened the branch https://github.com/rootzoll/raspiblitz/tree/2089-sphinx to work on all Sphinx releated issued. 

The connection test within the local network works fine ... but when using IP2Tor I get a "Cannot connect Server" error on pairing while even telnet is giving me a response on that ip/port.

**Comment by rootzoll** [comment]
OK the connection problem got fixed. Improved the connection test & also checking now if already on app connected with the connection string.

**Comment by rootzoll** [comment]
merged the branch ... so this issue is ready for testing

**Comment by we-do-it-lu** [comment]
@rootzoll "Make sure for the Sphix-Relay to be up-to-date" 
What do you mean by this? That one should remove than add again the SPHINX service for Blitz to pick up and install the latest code? 
I have SPHINX installed already, bumped into what appears to be bugs in it / but am still pocking around / discovering it.
Won't remove than re-install SPHINX service from Blitz menu destroy the Tribe I have created already in it?

**Comment by rootzoll** [comment]
@we-do-it-lu I am missing the context of your problem in this thread. Basically the Sphinx-Relay and the App version need to be up-to-date to work together. An RaspiBlitz under UPDATE there is the possibility to update the Sphinx-Relay while keeping your data. If you have problems please wait for the v1.7 release .. an early ReleaseCadidate v1.7RC1 will become available for the weekend - but its not advised to use that with your production node because its a still early version for testing and bug finding.

**Comment by we-do-it-lu** [comment]
@rootzoll you perfectly answered my interrogations. thank you!
... But I don't have SPHINX-Relay in "Update Options" 🤔
Running Blitz v1.6.3

**Comment by openoms** [comment]
@rootzoll just testing this. 
Good to see that it install with the latest release:
```
# Reset to the latest release tag --> v2.0.4
HEAD is now at 288ca9c Merge pull request #162 from stakwork/connect2
```

But the install got stuck on this `sudo` I think: https://github.com/rootzoll/raspiblitz/blob/47f3455704b14125213c82bf58ecb4ce6aea1faa/home.admin/config.scripts/bonus.sphinxrelay.sh#L306

**Comment by openoms** [comment]
Successful tests with the latest Sphinx-relay and a dedicated second, parallel node https://github.com/rootzoll/raspiblitz/issues/2073#issuecomment-805260911

Made a tribe as well:
![image](https://user-images.githubusercontent.com/43343391/112312260-85a77e00-8c9e-11eb-85fe-ae32ebd8aca3.png)

Connection code:
`YFsuxCApuU-TBIRWeWY_Gl52IOx2clJKZYLxDn78Z9RgcWNx9zUube7mkK4IyXQjLril-tgKZs3wOxDlWqpiyxp8jTbt`

I am:
openoms
`03acad130810892cd39fb7a1f8d9e5090337f7f3e2e3d8ba09b3370c32db284447`

**Comment by openoms** [comment]
anyone in this Sphinx tribe? 
who is the lewildbeast?
I only see it now that I made a competing one sorry, but anyway I cannot join this (no route).
![IMG_20210324_141425_099.png](https://user-images.githubusercontent.com/43343391/112325234-695e0e00-8cab-11eb-9a34-4dc8a16bae53.png)

**Comment by we-do-it-lu** [comment]
I get "There was an error. Please try again later." 
Blitz v1.6.3
Latest version of SPHINX on iPhone.

**Comment by we-do-it-lu** [comment]
You can try to join mine your end if you like: 
sphinx.chat://?action=tribe&uuid=YFpmJB-parnCVOvTaNmwg5LKWXpGuU_6ISrPpf2KX1Mjrli7K272Hk7txpODKt__DrNPC5eKvcERRU4vKOB2lNK-5TZA&host=tribes.sphinx.chat
![TribeJayDeLux](https://user-images.githubusercontent.com/26678816/112328202-66b4e600-8cb6-11eb-924d-e48298b1c227.jpg)

**Comment by openoms** [comment]
> I get "There was an error. Please try again later." 
> Blitz v1.6.3
> Latest version of SPHINX on iPhone.

what are you doing then and where do you see the message? Try with the latest sphinx-relay install script (coming in the new release soon).

**Comment by we-do-it-lu** [comment]
The message "There was an error. Please try again later." I am getting at the moment is a modal pop-up on SPHINX App on my iPhone when I scan your Tribe QR code.
I apologise for most likely having missed part of the story. 
I don't know how to "Try with the latest sphinx-relay install script"; script to run from the command line?

**Comment by openoms** [comment]
@we-do-it-lu 
```
# download
wget -O bonus.sphinxrelay.sh https://raw.githubusercontent.com/rootzoll/raspiblitz/dev/home.admin/config.scripts/bonus.sphinxrelay.sh
# have a look
cat bonus.sphinxrelay.sh
# uninstall old version (keep data)
bash bonus.sphinxrelay.sh off
# install 
bash bonus.sphinxrelay.sh on
```

You can watch what is going on on your Sphinx relay with:

`sudo journalctl -n 100 -fu sphinxrelay`

**Comment by we-do-it-lu** [comment]
@openoms thank you, spot on, I managed to join your Tribe. No further comments.

**Comment by openoms** [comment]
@rootzoll 
the Sphinx relay is now supported to connect over Tor as well so IP2Tor for it is redundant.
Needs Orbot on Android, but seems native on iOS:
https://github.com/stakwork/sphinx-relay/wiki/Home-node-FAQ#apps

**Comment by rootzoll** [comment]
@openoms I opened a new issue for v1.7.1 to optimize for Tor connection and dropping IP2Tor long term for SphinxApp - see:
https://github.com/rootzoll/raspiblitz/issues/2182#issue-859681846

**Comment by rootzoll** [comment]
All tests ran OK .. closing for v1.7 release.
