### ISSUE TITLE
LNWL Filtering blocks from 534*** after every reboot

### ISSUE THREAD

**Issue by goodc0re** [raspiblitz/raspiblitz#209]
I updated Raspiblitz as per instructions (clean HDD script) and flashing the sdcard with latest version 0.98 of the image. 

Setup went well (Bitcoin / mainnet). 

Even though the node was previously up to date and running on bitcoin mainnet, and was only offline for 30 minutes or so, LNWL filtered the blockchain from approximately height 534*** which took several hours. 

After it was finished, I went to setup to enable and setup the DynDNS service. A reboot was needed. 
The node was only offline for a minute and yet LNWL again started to rescan the chain from height 534***. 

This might be related to https://github.com/lightningnetwork/lnd/issues/2326 ?

**Comment by geco91** [comment]
Thanks for testing and researching. Yeah it seems as long as the node was not funded, a rescan from birth of wallet is mandatory. I am adding some notice to the user about this if possible.

**Comment by rootzoll** [comment]
I merged the new script into version 0.99 (= 1.0 RC2). Closing issue.

**Comment by IvanThinking** [comment]
Can anyone comment on WHY simply rebooting this beast prior to funding means a rescan is needed?

**Comment by rootzoll** [comment]
@IvanThinking the 0.52 version of lnd has fixed that - after the initial scan during setup it seems to rescan just the missed parts. 0.52 will be part of 1.0 release of RaspiBlitz.
