### ISSUE TITLE
CONNECT menu to collect how to connect wallets and services

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#2090]
Would help with answering the questions of how I connect XX app or wallet to the node.

By default should show connection to bitcoind and LND:

- [x] Bitcoind RPC for Specter Desktop and a remote Joininbox / JoinMarket
https://d11n.net/connect-specter-desktor-with-raspiblitz.html
https://github.com/openoms/joininbox/blob/master/prepare_remote_node.md
- [x] Fully Noded (from the MOBILE menu)
- [x] Bitcoind P2P - Bisq connects to v2 Tor service
https://twitter.com/openoms/status/1355885287881240578 
- [x] LND rest and GRPC with the text with
  - [x] TLS cert (from LNDCREDS)
  - [x] macaroons (from LNDCREDS)
  - [ ] Tor Hidden Services
  - [x] LNDconnect as now in the MOBILE menu for Zeus / Zap
  - [ ] show the own watchtower service address
  - [ ] connect third party watchtowers
  
Then could change dynamically depending on what is installed:
- [x] LND connection string for BTCpayserver (from LNDCREDS)
- [x] Electrum Server from the ELECTRS menu
- [ ] Can consider showing the various ports to open different services
- [ ] Hidden services for the various services

**Comment by rootzoll** [comment]
Just quick note: There is already a "CONNECT" menu entry for connectig to another Lightning peer. We could change that to "PEERING" ... or will that get a sub entry in the new "CONNECT" menu?

**Comment by openoms** [comment]
I wonder if we could declutter the Main menu significantly.
Currently with only LN related services installed I can only see 33% of the options:
![image](https://user-images.githubusercontent.com/43343391/112274943-f470e100-8c76-11eb-964f-574fc28b7454.png)

I am thinking to breakdown to a couple of submenus:
```
INFO - for the status screen
LIGHTNING - submenu for LN wallet related actions
    FUNDING
    CONNECT - can be called PEERING
    CHANNEL
    SEND
    RECEIVE
    NAME
    CLOSEALL
    CASHOUT
    lnbalance
    lnchannels
    lnfwdreport
SERVICES - all the installed app info-s including:
    TOR - show nyx + dilaog editbox for toorc
    LND - logs + dialog editbox for lnd.conf
    BITCOIN - logs + dialog editbox for bitcoin.conf
ADD/REMOVE - instead of the current SERVICES menu to install apps 
SETTINGS - kept as it is with the toggle options
SUBSCRIBE
CONNECT - some extra mentioned above and including:
    MOBILE
    LNDCREDS
REPAIR
UPDATE - as it is (could adjust the menu height automatically to not hide options)
REBOOT
OFF

X - can be configured to be the Cancel button instead (they do similar)
```
Should extend the height slightly to accommodate all the remaining lines.
What do you think? it is not too much work to refactor the menu and I can do it.
Need to create 3 submenu files for LIGHTNING, SERVICES and CONNECT.

**Comment by keblek** [comment]
is if possible to view this as a grid rather than a list? could have the columns be categories (LN, security, utilities, etc)

**Comment by openoms** [comment]
@keblek, no the dialog system is pretty limited. A tradeoff for being extremely lightweight and compatible: https://bash.cyberciti.biz/guide/Bash_display_dialog_boxes

**Comment by openoms** [comment]
#2119 is ready to be merged, but of course would benefit from more testing.
There are a lot of new menu options as described in the first comment and the commits.

One more thing I'd like to add is the watchtower info and connection to the CONNECT menu.
Should be easy to do by following: https://github.com/openoms/lightning-node-management/blob/master/watchtower.md

**Comment by rootzoll** [comment]
PR merged ... putting on final testing for v1.7RC2 :)

**Comment by rootzoll** [comment]
OK ... the connect menu is really nice and tested well :) Looks ready for v1.7. Closing issue for release.
