### ISSUE TITLE
LND v0.5beta waiting for chain sync

### ISSUE THREAD

**Issue by surrelito** [raspiblitz/raspiblitz#210]
So I have finished the setup and everything went smooth. I didnt have the same screen but was no problem installing it as soons as I could access the terminal inside the mainmeny.(Adafruit pitft).

But now I have : 
bitcoin v.0.17.0 mainnet sync OK <100%>
Public xx.xx.xxx.xxx:xxxx Not reacable
LND v0.5beta waiting for chain sync

The machine is working and values are being changed on the screen and also everything in the mainmeny works.

Should I just wait for this to finish or do I need to do something?

Very excited at this point :D 

Thanks / R

Edit : I have already been syncing stuff for days so I dont really know why its syncing again

**Comment by fluidvoice** [comment]
what is your output of running ./XXdebugLogs.sh from the SSH terminal?

**Comment by surrelito** [comment]
Hi. It actually started working when I sent some btc to a new adress. I couldnt go with "Fund your on-chain wallet because it didnt give me an adress. But i generated a new one from the console.

**Comment by rootzoll** [comment]
As long as the LND wallet has no funding - it rescans from birth on every start. I added a notice about that to LCD infoscreen in new version 0.99 (=1.0RC2) - hope this reduces confusion. I am closing this ticket for now.
