### ISSUE TITLE
Freezing on Boot with Pi 4 Fresh Install

### ISSUE THREAD

**Issue by ChiefGyk3D** [raspiblitz/raspiblitz#2117]
Attempted to run with the image and it seems to be stuck at 
i2c /dev entries driver and never moves on beyond that. 
For reference it's a Pi 4 4GB and 2GB I tried and I plan to run it without a display when it's all done, but set up is being done with a HDMI monitor.

**Comment by ChiefGyk3D** [comment]
Upon further investigation it looks like this may be similar to #1058

**Comment by kytmanov** [comment]
I have similar issue, so when I reboot my node I connect a keyboard and press ctrl+d and then it is able to boot.

**Comment by mantiev** [comment]
i'm getting the same - fresh install - everything is new - gets stuck at the same point - ctrl+d with keyboard didn't work.  I have used LCD and HDMI and get the same with each.

**Comment by rootzoll** [comment]
I am not able to reproduce this problem on my test machines ... but the v1.7RC2 tries to adress this "i2c freeze". @ChiefGyk & @kytmanov can you download the RC2, test and report back? See download here: https://github.com/rootzoll/raspiblitz/blob/dev/README.md#downloading-the-software

**Comment by nyxnor** [comment]
No reports on this issue within v1.7.0, pls close this.
