### ISSUE TITLE
Improve 'headless' Mode

### ISSUE THREAD

**Issue by Nerfzooka** [raspiblitz/raspiblitz#2120]
![headlessRaspiblitz](https://user-images.githubusercontent.com/23216537/113026767-6786c580-9157-11eb-8ff0-b3b85a011e28.jpg)
Hey Blitzy Folk!
I assembled and configured my lovely Raspiblitz and it's working AWESOMELY.  I asked it to run tor, Electrum Rust server, and the BTC RPC Explorer with no problems.  
I can SSH into it with nary a glitch so I took off the LCD.  Everything is running smoothly so I decided to venture off the map into RasbiBlitz Commandline.  I looked at a script "00infoLCD.sh" it had comments about headless CPU/log clutter, just add the line "headless=on" into /mnt/hdd/raspiblitz.conf , so I added the line to the file and rebooted.  Everything is still working but the info screen still updates every 20 seconds or so.
![raspiCovered](https://user-images.githubusercontent.com/23216537/113029526-86d32200-915a-11eb-9e69-dab783dbd833.png)

**Comment by nyxnor** [comment]
Good you are interested in what is running, very nice.
About the update, maintain the default time, there is no problem in that... but if you want to let more time pass for each update, add `sleep 30` (unit is seconds) here https://github.com/rootzoll/raspiblitz/blob/755b7460ca7d8f6aa614748e534ec0941fc891ea/home.admin/00infoBlitz.sh#L306 or here
https://github.com/rootzoll/raspiblitz/blob/755b7460ca7d8f6aa614748e534ec0941fc891ea/home.admin/00mainMenu.sh#L176
I advert this will not improve anything.

I can see that cat looking deep into my eyes.

**Comment by Nerfzooka** [comment]
Oh, the main menu script!  I've been looking for that, Thanks Ben10Brasileiro.

**Comment by rootzoll** [comment]
Hi there @Nerfzooka thanks for testing on this. The headless mode in v1.6.1 was a quick fix by @PatrickScheich just slowing down the info-loop.

With the now upcoming v1.7 release I refactored the display modes you can run your RaspiBlitz that can be set with:
`sudo /home/admin/config.scripts/blitz.display.sh set-display [lcd|hdmi|headless]`

If you choose `headless` now it will completly deactivate the auto-login of the pi user that had running the infoscreen in loop for HDMI or LCD users and is causing quite some cpu/system load.

This will be part of the v1.7RC2 coming in the next days - happy to get feedback on it.

BTW for people building the sd card themselves the `headless` can now be set already on building the image .. so there is no pi user auto-login and no LCD driver installs from the start.

**Comment by rootzoll** [comment]
OK headless mode looks fine on test runs of RC2 - will be part of final v1.7 release.
