### ISSUE TITLE
Repair SD card Filesystem Extension

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2126]
With the change to 64-bit base image of RaspiOS the filesystem extension to the full capacity or the users sd card is not working correctly. To be fixed for final release.

**Comment by openoms** [comment]
Here I just extracted the script from raspi-config.
Tested ok with the 64bit pure debian image: https://github.com/openoms/joininbox/blob/master/scripts/standalone/expand.rootfs.sh

**Comment by rootzoll** [comment]
The problem was not with the expand itself - the baseimage name changed and so it was not correctly triggered.

Just merged the fix - so this should now be ready for v1.7 release and final testing.

**Comment by rootzoll** [comment]
Ok multiple test show that the filesystem is now expanding corretly. Closing the issue.
