### ISSUE TITLE
Sync slow process and 0 peers

### ISSUE THREAD

**Issue by tibxfool** [raspiblitz/raspiblitz#2127]
Goodmorning,

I am currently syncing the blockchain after a crash. When I started I had about 10 peers and now its down to 0. Process seems to be very slow now. Is this normal? Currently at 48.08% and very slowly increasing. Can I reboot the PI without having to completely start from the beginning to reconnect to the peers?  I started syncing on the 28th March and progress was lot better.

Thx.
Frits

**Comment by openoms** [comment]
you can restart any time
if no peers can add the manually

**Comment by tibxfool** [comment]
Thanks. Will more peers speed up the process?

**Comment by openoms** [comment]
if there is 1 peer bitcoind will connect to more.
The difference is between having peers or none.
Of for some reason the peers connected are the bottleneck a restart helps.

**Comment by tibxfool** [comment]
without a restart back to 11 now. :-)

Thanks for your help!
