### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by Jackkwakman** [raspiblitz/raspiblitz#2129]
[
![Schermafbeelding 2021-04-02 om 17 02 24](https://user-images.githubusercontent.com/24440207/113427406-3f0bff00-93d5-11eb-8f7f-34d046338dd6.png)
](url)

**Comment by nyxnor** [comment]
How is it going? Still the same error?
Run `debug` and then run the command at the end to generate a link for it please and post it here.
Always provide generous amount of information, or else no one can help.

**Comment by rootzoll** [comment]
@Jackkwakman also remember to use your Password-B that is used for additional Apps like RTL on RaspiBlitz ... Password-A is just for your System-Login like SSH

**Comment by nyxnor** [comment]
Pls close this issue rootzoll, no more information provided in 2 weeks.
