### ISSUE TITLE
Missing codepage or helper program, or other error.

### ISSUE THREAD

**Issue by wwhitley** [raspiblitz/raspiblitz#2146]
mount: /mnt/hdd: wrong fs type, bad option, bad superblock on /dev/sda1, missing codepage or helper program, or other error.
FAIL blitz.datadrive.sh tempmount --> temp mount failed
Please report issue to the raspiblitz github.

**Comment by nyxnor** [comment]
Are you using the recommended hardware? Others can be faulty.
https://github.com/rootzoll/raspiblitz#package-standard-around-250-usd

**Comment by nyxnor** [comment]
@wwhitley Please close this issue or ask a question/provide more logs.

**Comment by nyxnor** [comment]
pls close this Rootzoll
