### ISSUE TITLE
Update Emergency Fallback List

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2153]
Also add this for the v1.9 milestone ...
https://github.com/rootzoll/raspiblitz/issues/1888

**Comment by nyxnor** [comment]
Now he disabled capcthas and is working with `torsocks`  https://github(dot)com/ayeowch/bitnodes/issues/49#issuecomment-832627013 [change (dot) to .]
I dont know if this is going to be permanent.

**Comment by rootzoll** [comment]
We can have a static file list always as fallback of last resort. To try to get a updated list would be good to have for the v1.8

**Comment by rootzoll** [comment]
Fatpack automatically gets a fresh list to create a static file - because this is happeing during sd card build also tor is not needed.
