### ISSUE TITLE
Dynamic DNS not asking for domain name 

### ISSUE THREAD

**Issue by severedStrings** [raspiblitz/raspiblitz#216]
When I go to "Services" then "DynamicDNS",  it just pumps out this info and goes back to the main screen.
<img width="352" alt="screen shot 2018-12-26 at 4 03 31 pm" src="https://user-images.githubusercontent.com/6830352/50434204-502d5200-0928-11e9-889e-86c68cce2098.png">

Can you think of anything obvious that I could have done wrong that would cause it to skip past asking me for the Domain name?

**Comment by severedStrings** [comment]
I closed my issue. I think it was my old router / my fault. It only supports www.dyndns.org and I don't want to use that service.

**Comment by rootzoll** [comment]
Someone else had the a similar problem - did you used the spacebar to "check" the "DynamicDNS" Option before hitting OK/Enter?
