### ISSUE TITLE
New: Homer Dashboard

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2162]
see https://github.com/rootzoll/raspiblitz/pull/2152/#issuecomment-815985212 thx to @hashes4merkle

development is happening on this branch: https://github.com/rootzoll/raspiblitz/tree/2152-homer

**Comment by rootzoll** [comment]
OK I did some small fixes, put it as part of the recovery, added the `update` and was working on persitence for the config.

So the config will be stored and should be edited by the user at:`/mnt/hdd/app-data/homer/config.yml` ... this file will be lionked into the homer nginx assets in the end. Because it in `app-data` it will survive updates & migrations

**Comment by rootzoll** [comment]
@hashes4merkle if we can get this stable - happy to add to the final v1.7 release (targeted for next week) ... but no pressure, we can also target for v1.7.1 :)

**Comment by deverickapollo** [comment]
@rootzoll Tested install, update and delete on a new environment. Looks good.  

Still waiting on comments from upstream to see if those dependency issues can be resolved.  Would like to avoid using --legacy-peer-deps if we can.

**Comment by rootzoll** [comment]
OK so maybe lets push ist to v1.7.1

**Comment by deverickapollo** [comment]
Homer dependencies resolved.  We can pull from master branch or wait for the next release.

**Comment by rootzoll** [comment]
Sweet :) V1.7 final is quite close .. lets put it into v1.7.1

**Comment by rootzoll** [comment]
PR pushed to v1.8.0 --> #2541

**Comment by rootzoll** [comment]
Merged for v1.8.0 release - final testing.

**Comment by rootzoll** [comment]
OK tested - closing for release.
