### ISSUE TITLE
LIT + RTL .. make them work together

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2164]
doesnt need to be part of RC2 ... but should be part of the final release.

**Comment by openoms** [comment]
Covered in: https://github.com/rootzoll/raspiblitz/commit/be6e9bbbc9440b1954c30c74a0fd28ab24555ea0 and
https://github.com/rootzoll/raspiblitz/commit/172bb54e6d895ee6b173650961572854bc64cf0f
commited directly since were small changes and tested ok quickly.

**Comment by rootzoll** [comment]
Looks good sofar ... Final Test: Upgrade my production node to v1.7RC3 and test LoopIn with RTL (& LIT installed).

**Comment by openoms** [comment]
Bad news on this, because the Loop REST interface is not yet implemented in LiT: https://github.com/Ride-The-Lightning/RTL/issues/660

It means Loop will be only usable with LiT and the CLI, not RTL in this version.

**Comment by rootzoll** [comment]
Thanks for the clarification ... I will push this issue to the v1.7.1

**Comment by rootzoll** [comment]
LIT will not yet be part of WebUI v1.8.0 release ... but pushing this to v1.8.1 to recheck LIT & RTL integration again.

**Comment by rootzoll** [comment]
LIT also not yet part of 1.9 ..m pushing it to v1.10
