### ISSUE TITLE
Question: Changing Pi to larger capacity RAM model.

### ISSUE THREAD

**Issue by hermanlim** [raspiblitz/raspiblitz#2168]
I plan to 'upgrade' my Pi from a 4GB to 8GB model.

With regards to running Raspiblitz, is this just a simple case of plugging in the existing SD card/SSD to the new Pi or do I need to go through the setup process again to take into account the increased RAM?

**Comment by nyxnor** [comment]
Yes, just move the SD and the SSD, will work fine.

**Comment by hermanlim** [comment]
Confirm. No adverse issues from the process apart from IP address change, which was easily addressed at router end.
