### ISSUE TITLE
bitcoind not listening on RPC port 8332 in some cases

### ISSUE THREAD

**Issue by goodc0re** [raspiblitz/raspiblitz#217]
bitcoind is not listening on RPC port 8332 in some cases 
Adding rpcport = 8332 to bitcoin.conf fixes this issue.

**Comment by fluidvoice** [comment]
in what cases?  Any idea what could be causing a port change? I thought 8332 is the default.
If there is a bug in the code, it would be good if it can be identified and fixed.

**Comment by goodc0re** [comment]
The node was moved from a LAN IP to a public WAN IP without changing any settings whatsoever. Upon reboot RPC did not listen on port 8332 anymore. 

Adding rpcport=8332 alone did also not help, now I added: 

rpcport=8332
rpcallowip=127.0.0.1
rpcbind=127.0.0.1:8332

And only now is it listening on the port again.

**Comment by fluidvoice** [comment]
Could you kindly post debug logs which show this?  I think that would help the dev's a lot.
Also when you say "Upon reboot RPC did not listen on port 8332 anymore", what port WAS it listening on then? Or do you mean that it just was not responding to requests on port 8332?

**Comment by fluidvoice** [comment]
> The node was moved from a LAN IP to a public WAN IP without changing any settings whatsoever. Upon reboot RPC did not listen on port 8332 anymore.
> 
> Adding rpcport=8332 alone did also not help, now I added:
> 
> rpcport=8332
> rpcallowip=127.0.0.1
> rpcbind=127.0.0.1:8332
> 
> And only now is it listening on the port again.

I had the same problem and adding these 3 lines seems to have fixed it. thanks!

**Comment by rootzoll** [comment]
OK .. needs final test run with migration and fresh install if scripts/config run without error

**Comment by rootzoll** [comment]
fresh install runs OK with new settings. RPC is listening on 8332.
I had no old node to test migration - keep fingers crossed ;)

closing the issue for release.
