### ISSUE TITLE
Move Repo from Personal to Organization

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2184]
To be able to give issue managing access right to the repo to sible users (without giving write access to code) I would need to move it into an organization - see: https://github.com/rootzoll/raspiblitz/issues/193#issuecomment-821088073

This is to research if its possible without breaking links, etc for the v1.7.1

Also this can be combined with:
- [x] adding wiki - see #2038
- [ ] ability to give `Triage` access for people helping managing issues
- [ ] repo for dashboard/webUI
- [ ] repo for homepage
- [x] enbable DIscussions - see #2270

details to be determineed after v1.7 release - added teamdiscuss lable

**Comment by openoms** [comment]
We are squatting https://github.com/raspiblitz already.
Will look around what more is possible here: https://github.com/orgs/raspiblitz/dashboard

**Comment by nyxnor** [comment]
I dont want to have privileged options as Im still learning. Triage seems good enough if I can close old issues with it https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization

Related to documentation https://github.com/rootzoll/raspiblitz/issues/879


![motivation](https://user-images.githubusercontent.com/69700936/115312203-6fd38e80-a160-11eb-88ff-a89a634cd4d1.png)
Issues count now
![238](https://user-images.githubusercontent.com/69700936/115312110-46b2fe00-a160-11eb-989f-b393b95762bd.png)

If you are reading this, close your solved issue or I will keep haunting you.

**Comment by rootzoll** [comment]
I move this to v1.8 - just to get v1.7.1 quicker ready.

Also as a sidenote - dispite gossip I heard ... it looks like the repo can keep its followers & stars when getting moved:
https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/transferring-a-repository

**Comment by rootzoll** [comment]
Its still on the todo list ... just gets more complex now with the new repos for BlitzAPI & WebUI. Maybe thats something for a community event end of year to do together. Will push it up to v1.8.2 for now.

**Comment by cstenglein** [comment]
Done :raised_hands:
