### ISSUE TITLE
Slow to sync, odd bitcoind behavior.

### ISSUE THREAD

**Issue by benjamin-wilson** [raspiblitz/raspiblitz#2191]
I have all the hardware that was suggested however I'm 4 days into the sync and only passed 50%. It doesn't seem to be utilizing system resources much. I've documented my findings on stack exchange but posting here for more specific raspiblitz help.

https://bitcoin.stackexchange.com/questions/105493/raspiblitz-slow-sync-performance

**Comment by nyxnor** [comment]
The percentage is based on the (current block downloaded)/(total blocks). The first blocks were not big, most recent blocks start getting full, that is why it slow down the percentage number. Also, to print debug logs:
 `/home/admin/XXdebugLogs.sh | torsocks nc termbin.com 9999`.
 
 If it was presented how much data in bytes were downloaded, and how many remains, it would be clear the example I gave above, PRs welcome.

**Comment by benjamin-wilson** [comment]
It's not a matter of newer or older blocks or the sync progress. Simply restarting bitcoind will 10x the sync speed for a short while. I go over this in detail on stackexchange. Currently the node is behaving and syncing at an acceptable rate but if it slows down again I'll post XXdebugLogs.

**Comment by benjamin-wilson** [comment]
Woke up this morning and it's slow again. Logs: https://termbin.com/3ipr

**Comment by nyxnor** [comment]
For what is worth, I can say this is normal behavior. The logs also seems fine. On start up, there is always a peak.

**Comment by SCH00N3R** [comment]
I am seeing the same behaviour on my unit. Is it normal or consistent anomalous behaviour (in terms of what is expected)?
I can sync much faster by periodically rebooting the raspiblitz. As there is nothing about the data or peer connections that changes, it seems that it is likely that the process that indexes the blockchain data is suffering from some sort of bug that causes it to slow down. Something is cleared out by a reboot, and the process is able to resume at a normal rate for an hour or two and then begins to degrade again.

**Comment by rootzoll** [comment]
Whats the temperature of your devices? ... the raspberrypi throttles down performance if it runs too hot, what might low down of sync extremly.

**Comment by SCH00N3R** [comment]
Initially I was sync'ing with a 2TB HDD. I recently acquired a 500GB USB SSD and figured I would clone the blockchain over to that drive just to see if the sync process speeds up. That definitely resolved that issue for me. Sync rate is now hugely improved. I did increase dbcache to 2048 (from 128) in bitcoin.conf to reduce disk I/O. Not certain if that is also boosting performance. I plan to change it back to 128 once sync is complete. I am beginning to think that my issue was completely disk performance related.

Anyhow, prior to upgrading to SSD my temps were not exceeding 58C. Now they are in the mid 60s C. Does anyone know the temperature at which the throttling kicks in? I have a fan and case on my device. The only thing I can think of that may help is putting it out in the garage where it is cooler (it is currently winter where I am).

Thank you!

**Comment by SCH00N3R** [comment]
Found my own answer: https://www.raspberrypi.com/news/thermal-testing-raspberry-pi-4/

80 C is the SoC hard temp limit. It throttles WAY down to reduce temp. So if your device is creeping over 80 C, synch'ing will be drastically impacted.

**Comment by rootzoll** [comment]
Yeah HDDs are not recommended because their performace on initial sync is really bad and they are prune to lose power and data corrupt over the longtime - SSD should be the standard for running a RaspiBlitz if possible. Another reason why even a SSD can be slow is also, when you connect it on a RaspberryPi thru the USB2 ports (black) and not as it should be on the USB3 ports (blue).
