### ISSUE TITLE
Rapsiblitz webadmin and RTL GUI fails

### ISSUE THREAD

**Issue by silvester235** [raspiblitz/raspiblitz#2195]
I finished to set up the raspibliz today.

However I use it without LCD and therefore would like to use the webadmin.

Loged in via ssh and the "RaspiBlitz Status Screen" shows:
Web admin -> http://10.0.1.9:3000

If I enter http://10.0.1.9:3000 in the Chrome Browser it brings me to RTL GUI.

--------
RTL:
"Open in your local web browser & accept self-signed cert: https://10.0.1.9:3001"

Error in the Chrome browser "This site can’t be reached- ERR_CONNECTION_TIMED_OUT"

So I can't log in to the Web admin at all. And RTL login works with at a different port but only as http not as https.

I am confused now.
Is there a way to fix this?

<img width="451" alt="Screen Shot 2021-04-18 at 21 32 47" src="https://user-images.githubusercontent.com/79768798/115150969-fb7fe900-a094-11eb-95a8-40f11fbf7191.png">
<img width="499" alt="Screen Shot 2021-04-18 at 21 26 39" src="https://user-images.githubusercontent.com/79768798/115150976-0470ba80-a095-11eb-8112-5c4d30eb10d8.png">

**Comment by silvester235** [comment]
Here are the RASPIBLITZ DEBUG LOGS 

https://termbin.com/gktg

**Comment by rootzoll** [comment]
There is no WebAdmin for RaspiBlitz itself yet .. just a stub for testing. A full WebUI is targeted for v1.8 now.

The RTL timing out on https is a but strange - when its still reachable (and i dint see an error in logs for RTL) it might be a problem with nginx. 

Best way would be wait some more days for the v1.7 (where RTL has an upadte anyway) and then report back if that fixed it for you.

**Comment by silvester235** [comment]
@rootzoll 
Thanks for the update.

nginx is the problem indeed. I get 404 error when I try to install ngix

My local mirror has an error in the URL structure. Err:1 http://mirror1.ku.ac.th/raspbian/raspbian... instead of http://mirror1.ku.ac.th/raspbian... resulting in 404.

Is there a way to report the wrong mirror URL structure?

**Comment by nyxnor** [comment]
For nginx
```
sudo nginx -t
sudo systemctl status nginx
sudo systemctl restart nginx
```

For the mirror (delete wrong info)
```
sudo nano /etc/apt/sources.list
deb http://mirror1.ku.ac.th/raspbian/raspbian/ main contrib rpi non-free
```

**Comment by nyxnor** [comment]
pls close this if it worked.
