### ISSUE TITLE
Connecting Mobile Apps

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2198]
The mobile Apps are having problem connecting to the RaspiBlitz.

ZAP Android --> Its seems its not accepting the LND with the new TLS settings. Need to do further tests.
Zeus --> is not connecting to the Tor services ... says its offline - can be someting with my iOS test device. Need to do further tests.

**Comment by rootzoll** [comment]
@openoms could the zeus app not connecting anymore be a side effect of #1604 .. will check in the Tor addresses

**Comment by openoms** [comment]
unlikely.
The Hidden Service for 8080 is managed by tor@default and the default torrc, no changes there.

**Comment by The34Goon** [comment]
I just went through the installation process again and had no trouble connecting Zeus-IOS v0.5.1 to 1.7RC2 over Tor.

Bonus: Nice to finally see the complete QR in fullscreen-terminal.

**Comment by rootzoll** [comment]
OK I got Zeus running over Tor - all cool there.

But Zap-Android has the problem that it requires the IP in the TLS certificate and seems not to play nice with the new LND settings. @openoms I think I will remove also Zap-Android for v1.7 .. to get it back in we might need to open a issue on the Zap-Android repo on it.
