### ISSUE TITLE
Telegraf WebUI

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2199]
Experimental telegraf background service was added with #1369 ... see if its possible to make it a permanent install (add to provison for updste/recover) & see if we can add a WebUI integration.

**Comment by PatrickScheich** [comment]
**telegraf** is just a metric collecting agent. Normally it pumps the measurements into a backend infratructure.
Often a timeseries database like **influxdb**, on top of that DB sits a "nice graphic frontend" like **grafana**.

I'm currently not aware of any lightweight WebGUI for the telegraf output.

In my environment I use a seperate Raspi4 as InfluxDB and grafana host.
So it could be run on a respberry pi but I would not recomend to run it on the raspiblitz.

**Comment by holgern** [comment]
It seems to me that questdb could be a lightweight alternative?
https://questdb.io/docs/third-party-tools/telegraf/

**Comment by holgern** [comment]
I think when using a retention-policies for influxdb which deletes old data automatically, the memory usage should be fine.

https://docs.influxdata.com/influxdb/v1.7/query_language/database_management/#create-retention-policies-with-create-retention-policy

This seems also a good alternative: keep the raw data only for a certain amount of time and then downsample the data

https://docs.influxdata.com/influxdb/v1.8/guides/downsample_and_retain/
