### ISSUE TITLE
Restore from seed has zero balance.

### ISSUE THREAD

**Issue by Zerkez** [raspiblitz/raspiblitz#221]
Hello all.
After two months of operation, my Raspberry got an error. I wanted to recover the funds I followed the instructions (https://github.com/rootzoll/raspiblitz#recover-your-coins-from-a-failing-raspiblitz)
Seed recovery has been successful, unfortunately, the wallet status is zero. It was the amount that I would like to recover. Any ideas?

**Comment by DaReaLDeviL** [comment]
Same in my case. Could't close channels and had to do a real new sd card with all sucessfull restored 24 word seed and pw but no funds in it. Do I miss something or are the funds all gone, couse this is still with a onchain an ln wallet?! Or do I miss something.

**Comment by Smiggel** [comment]
Same happened to me before. I contacted the developers after Lightning and restoring the balance using a seed is not yet implemented as far as I understand. So for now, it seems the funds are lost. I hope that I eventually get my funds back too with my seed.

**Comment by fluidvoice** [comment]
> Same happened to me before. I contacted the developers after Lightning and restoring the balance using a seed is not yet implemented as far as I understand. So for now, it seems the funds are lost. I hope that I eventually get my funds back too with my seed.

Can you point to the forum/page/thread saying this? I find it hard to believe given there are nodes with a very large amount of money in their channels. I don't see people risking that kinda money if funds recovery did not work. If fund recovery via seed is not implemented, what other fund recovery means *IS* implemented?

**Comment by Smiggel** [comment]
https://github.com/lightningnetwork/lnd/issues/2078

**Comment by Smiggel** [comment]
@fluidvoice https://github.com/lightningnetwork/lnd/issues/2078

Even with 0.5 it’s Still not working. Funds don’t resterende with the seed.

**Comment by DaReaLDeviL** [comment]
So please help me to understand. My 24 word seed is the wallet for the fullnode which is conected to the LN Wallet or what is here the corolation between them? I tried restore a wallet to test on electrum but i dont get a balance. my buddy does with his raspiblitz. 

I secured my 24 word seed with the password D. So is this which comes here into play and a maybe "restore problem" on electrum wallet? Or is it like Smiggel said that it is like broken?

**Comment by rootzoll** [comment]
I tried to sum up the situation on a similar ticket here:
https://github.com/rootzoll/raspiblitz/issues/205#issuecomment-452856277

Backup & Recover of channel states are topics LND has most def to improve on. Hope there is something coming soon. I will close this issue for now.
