### ISSUE TITLE
Error formating HDD

### ISSUE THREAD

**Issue by ronledfordjr** [raspiblitz/raspiblitz#2210]
![error 1](https://user-images.githubusercontent.com/79236343/115318944-65a39700-a144-11eb-8c1a-01e0bd59e979.PNG)
![error 2](https://user-images.githubusercontent.com/79236343/115318946-6805f100-a144-11eb-910d-26b43b1a2b65.PNG)

Error formatting HDD with new BTRFS.

This is my third node and I have not had any issues to this point.

![status](https://user-images.githubusercontent.com/79236343/115319415-67ba2580-a145-11eb-995b-0fad6b5abd49.PNG)

**Comment by nyxnor** [comment]
run `lsblk` to see available drives.

**Comment by ronledfordjr** [comment]
![mount](https://user-images.githubusercontent.com/79236343/115711300-f773f580-a338-11eb-9806-30a6c77862e9.PNG)

**Comment by nyxnor** [comment]
Your thumb drive or second disk was mounted first as sda, and your SSD was mounted second as sdb.
Try again just with the SSD and the micro SD card attached.

**Comment by rootzoll** [comment]
Yes please make sure to not have a thumbdrive connected while doing a BTRFS format for now.
I will mark this issue for v1.8.1 when we will start to check back on BTRFS again.

**Comment by 21-btcclub** [comment]
I have a similar error
/home/admin/XXdebugLogs.sh | nc termbin.com 9999
****
and when i start without the usb stick, raspiblitz will Format in EXT4 layout (old)
How can i use BTRFS format without a thumbdrive connected?

**Comment by ronledfordjr** [comment]
Thank you
