### ISSUE TITLE
ZapDesktop connect to Node

### ISSUE THREAD

**Issue by DaReaLDeviL** [raspiblitz/raspiblitz#222]
The new App for IOs is working like it should with the newest version of Raspiblitz.

Now i try it with ZapDesktop Version 0.3.2beta to Rapsiblitz 0.99 but have some problems to give it the right TLS-Certificate and Macaroon path. Can someone please point me in the right direction?

Thank you in advanced!

**Comment by hcarrega** [comment]
I can’t even take iOS app working :) I think e need to read more about lnd , but everything it’s working on RaspiBlitz

**Comment by DaReaLDeviL** [comment]
Where can I assist you on the iOS app? Come into the IRC of freenode #raspiblitz I will try to help you.

**Comment by hcarrega** [comment]
i think the problem is easy nothing is setup on lnd.conf on IP's

**Comment by DaReaLDeviL** [comment]
Maybe you can test the desktop app and help me on there?

**Comment by DaReaLDeviL** [comment]
Ok now I get it. You have to copy the tls.cert and admin.macaroon from the raspiblitz to your local pc and give this folder in your zapdesktop. dont forget to point to the right port and now it works!

**Comment by fluidvoice** [comment]
I sure hope they improve the ease of use of Lightning in the future. This stuff is impossible for the general public.

**Comment by wuestenigel** [comment]
Hey,
where do I find the admin.macaroon file and where do I find my ip:port settings to connect with?

**Comment by zer0trst** [comment]
@wuestenigel 

Using filezilla, connect via SFTP into your raspi and copy the following files to your pc, point to these two files where it asks you in Zap.

      /home/admin/.lnd/tls.cert

      /home/admin/.lnd/data/chain/bitcoin/mainnet/admin.macaroon

**Comment by wuestenigel** [comment]
Great, what is username and PW for connecting with SFTP?

What will be the URL and  port I have to enter later in Zap?

**Comment by zer0trst** [comment]
Connect to sftp:// local IP of your node:21 user name admin and the same PW you set for admin when setting up the node

If you’re only connecting zap locally then use the same local ip of your node in zap with port 10009. 

If you want to connect from outside your local network you’ll need to connect to your nodes external IP, you will need to open up NAT ports on your router and add the applicable lines to your conf file to allow for remote connection as well - all something I haven’t done yet myself so can’t help you any further with that.

Good luck

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by wuestenigel** [comment]
Instantly worked! So much appreciated!

**Comment by wuestenigel** [comment]
Any ideas what would be the REST API / Node URL in Joule chrome Extension?

Basically I think I need the port.
