### ISSUE TITLE
Check WebUI for Referrer-Policy: no-referrer

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2225]
Make sure that the Dashboard is not leaking onion adresses to external websites - see:
https://github.com/getumbrel/umbrel/issues/639

**Comment by cstenglein** [comment]
Should be easy to spot since create-react-app ships with eslint rules which produce wanings on build / serve for that case:

Example:

![image](https://user-images.githubusercontent.com/9399034/122654197-45d72200-d139-11eb-8ff6-e6052f0221a8.png)
