### ISSUE TITLE
Fix: Keep BOS data on update

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2235]
Got a report that after update to v1.7.0 the old BOS data was gone. Check if we can reproduce @openoms and fix.

**Comment by openoms** [comment]
the `/home/bos/.bos` directory is not preserved currently so should be done for 1.7.1.
There is only the Telegram API key for me, but other nodes connected would be stored therr too. Probably info from swaps too.
Otherwise bos uses no database, so that's why did not miss it so far.

**Comment by rootzoll** [comment]
@openoms anything still todo on this issue for v1.7.1?

**Comment by openoms** [comment]
No, it should work with the PR merged.
