### ISSUE TITLE
Fix: Keep JoinMarke data on update

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2236]
Got a report that after update to v1.7.0 the old Joinmarket data was gone. Check if we can reproduce @openoms and fix.

**Comment by openoms** [comment]
The JM data is symlinked from `mnt/hdd/app-data/.joinmarket` to `/home/joinmarket/` and was preserved for me. 
Can't reproduce this so far.
Also the script did not change since the previous release.

**Comment by rootzoll** [comment]
I think we can close this - I got the report back that it was just slow somehow.
