### ISSUE TITLE
Recommended screen no longer available

### ISSUE THREAD

**Issue by pandascrape** [raspiblitz/raspiblitz#2243]
The screen in the recommended kit list has not been available on Amazon for some months now.

Unfortunately there does not appear to be another compatible screen that is as cheap, however this screen and case appears to be available in both US and Europe: https://www.amazon.com/Raspberry-Touchscreen-320x480-Monitor-Display/dp/B07WQW6H9S

Please could you confirm that this should be compatible, and perhaps update the recommended kit list on the GitHub repo?

And thanks for the great work. You are bitcoin heroes :)

**Comment by rootzoll** [comment]
@Animalmother9000 can you please create more international Links to alternative LCD models that we know that work for the shopping list? You can just post them here and I can add them top the GitHub Repo.

**Comment by NilByte** [comment]
I'm using this one and have not had any problems with it.

https://www.amazon.de/gp/product/B06X191RX7/ref=ppx_yo_dt_b_asin_title_o02_s01?ie=UTF8&psc=1

**Comment by rootzoll** [comment]
OK the PR #2253 gives now some alternative models to search for. See: https://github.com/rootzoll/raspiblitz#amazon-shopping-list-buy-parts--build-it-yourself

Closing issue.
