### ISSUE TITLE
IP2Tor: Not able to get HTTPS response

### ISSUE THREAD

**Issue by thecharacter** [raspiblitz/raspiblitz#2247]
I upgraded to v1.7 and got this error. This is specially happening with the LNbits webinterface order. I reinstalled LNbits but getting the same error. I'm able to access LNBits with the https://xxxxx.onion address and with my LetsEncrypt domain but services such as LNurlp and LNurlw the require HTTPS communication beyond my local network fail. 

Note: I updated Tor per the repair menu and reinstalled LNbits. 

![Screen Shot 2021-04-28 at 3 16 20 PM](https://user-images.githubusercontent.com/70460811/116479865-34f2ea00-a835-11eb-9dab-81db745587c1.png)

**Comment by rootzoll** [comment]
Thanks for the report. Have you already closed all subscriptions (IP2Tor & LetsEncrypt) and renewed them also. 

Note: This might give you a new port and break links that you already distributed in your local community.

@frennkie can you also take a look here?

**Comment by thecharacter** [comment]
@rootzoll yeah I closed everything and created new subscriptions. Still getting this error.

**Comment by rootzoll** [comment]
Hmm .. I added I bit more debug info to the v1.7 code. Please go to MAINMENU > UPDATE > PATCH > PATCH-MENU > PATCH (you dont need to reboot) and then please take a picture again of the Warning window.

**Comment by thecharacter** [comment]
Cool here it is. 

![Screen Shot 2021-04-29 at 3 27 57 PM](https://user-images.githubusercontent.com/70460811/116626460-1d346800-a900-11eb-93c9-a90c63d125c7.png)

**Comment by rootzoll** [comment]
Can you EXIT to terminal and run the command `/home/admin/config.scripts/internet.dyndomain.sh off` and reboot and let me know if that changed someting.

**Comment by thecharacter** [comment]
Ran the command rebooted and got the same warning. I deleted the subscriptions and created new subscriptions and got same warning. 

![Screen Shot 2021-04-29 at 11 24 28 PM](https://user-images.githubusercontent.com/70460811/116657109-bb492200-a942-11eb-828e-befac86455f4.png)

**Comment by klnit** [comment]
I have the same issue and think it is the reason for #2240
Please link it to this issue

**Comment by frennkie** [comment]
This error message seems to come from here: https://github.com/rootzoll/raspiblitz/blob/v1.7/home.admin/config.scripts/blitz.subscriptions.letsencrypt.py#L751 which is called from here

```
config.scripts/bonus.lnbits.sh:123:        domainWarning=$(sudo /home/admin/config.scripts/blitz.subscriptions.letsencrypt.py subscription-detail ${domain} ${port} | jq -r ".warning")
``` 

@rootzoll is this more than a warning? As far as I see it the actual "IP2Tor" services is working fine here..

**Comment by JurGi7** [comment]
Hello, I have the same or similar problem, since the update to 1.7.0 my LetsEncrypt IP2TOR subscription no longer works. This message comes up briefly and I don't have an entry under subscription 🤔. 
[
![Screenshot from 2021-05-04 11-01-25](https://user-images.githubusercontent.com/55794093/117001896-3152dd80-ace3-11eb-93d0-af99f74f7246.png)
](url)

**Comment by rootzoll** [comment]
hey @thecharacter I merged a possible fix to the v1.7 branch. Can you please test if this fixes this for you with first updating to that oatch with MAINMENU > UPDATE > PATCH > PATCHMENU > PATCH and then do a reboot.

Then under SUBSCRIVE > LIST remove the LetsEncrypt and then re-add it fresh.

**Comment by JurGi7** [comment]
in my case - patch installed, everything works again. thanks rootzoll

**Comment by thecharacter** [comment]
It's working thank you.

**Comment by peterbaricic** [comment]
Hi,
I have the same issue (not able to get https response), but also when I try to unsubscribe from ip2tor and letsencrypt, ip2tor unsubscribe is working, but unsubscribing letsencrypt gives me an error='letsencrypt acme failed'

**Comment by maddadder** [comment]
> Hi,
> I have the same issue (not able to get https response), but also when I try to unsubscribe from ip2tor and letsencrypt, ip2tor unsubscribe is working, but unsubscribing letsencrypt gives me an error='letsencrypt acme failed'

I also got the above error and was able to fix: 'letsencrypt acme failed' by editing /mnt/hdd/raspiblitz.conf and changing from letsencrypt=on to letsencrypt=off and then attempted to unsubscribe and it worked

**Comment by peterbaricic** [comment]
> > Hi,
> > I have the same issue (not able to get https response), but also when I try to unsubscribe from ip2tor and letsencrypt, ip2tor unsubscribe is working, but unsubscribing letsencrypt gives me an error='letsencrypt acme failed'
> 
> I also got the above error and was able to fix: 'letsencrypt acme failed' by editing /mnt/hdd/raspiblitz.conf and changing from letsencrypt=on to letsencrypt=off and then attempted to unsubscribe and it worked

I have letsencrypt=off and it still gives me the same error

**Comment by maddadder** [comment]
> > > Hi,
> > > I have the same issue (not able to get https response), but also when I try to unsubscribe from ip2tor and letsencrypt, ip2tor unsubscribe is working, but unsubscribing letsencrypt gives me an error='letsencrypt acme failed'
> > 
> > 
> > I also got the above error and was able to fix: 'letsencrypt acme failed' by editing /mnt/hdd/raspiblitz.conf and changing from letsencrypt=on to letsencrypt=off and then attempted to unsubscribe and it worked
> 
> I have letsencrypt=off and it still gives me the same error

Wait. I think I got it mixed up. Try setting it to on. That way it can turn it off. Sorry about the confusion.

**Comment by peterbaricic** [comment]
> > > > Hi,
> > > > I have the same issue (not able to get https response), but also when I try to unsubscribe from ip2tor and letsencrypt, ip2tor unsubscribe is working, but unsubscribing letsencrypt gives me an error='letsencrypt acme failed'
> > > 
> > > 
> > > I also got the above error and was able to fix: 'letsencrypt acme failed' by editing /mnt/hdd/raspiblitz.conf and changing from letsencrypt=on to letsencrypt=off and then attempted to unsubscribe and it worked
> > 
> > 
> > I have letsencrypt=off and it still gives me the same error
> 
> Wait. I think I got it mixed up. Try setting it to on. That way it can turn it off. Sorry about the confusion.

that worked, thanks

**Comment by rootzoll** [comment]
This error message `Target is not HTTPS` comes when you try to make an IP2Tor subscription, but the onion service is not responding.

For future versions have a script that checks reachability of an onion service BEFORE trying to create an IP2Tor subscription .. for example with: torsocks curl http://soveng42aj6ynynkqeyut2dwnmwou45epfpuwvjy2t45fpxn3dk2ymad.onion

If a non working onion-service is detected the user should be offered to renew the onion hidden service BEFORE trying to make the IP2Tor bridge. Because its some re-work .. will push this to v1.8.0

**Comment by kevkevinpal** [comment]
<img width="499" alt="Screen Shot 2021-12-08 at 11 53 48 AM" src="https://user-images.githubusercontent.com/15950706/145258736-e4a33dfb-5432-44a8-b8e7-14ba996d9540.png">

is this error related to this issue? It is rejecting my subscription when trying to subscribe with IP2Tor

**Comment by kevkevinpal** [comment]
> This error message `Target is not HTTPS` comes when you try to make an IP2Tor subscription, but the onion service is not responding.
> 
> For future versions have a script that checks reachability of an onion service BEFORE trying to create an IP2Tor subscription .. for example with: torsocks curl http://soveng42aj6ynynkqeyut2dwnmwou45epfpuwvjy2t45fpxn3dk2ymad.onion
> 
> If a non working onion-service is detected the user should be offered to renew the onion hidden service BEFORE trying to make the IP2Tor bridge. Because its some re-work .. will push this to v1.8.0

Does this mean this happens when the tor service for what we want to bridge is not working or the ip2tor shop service isn't working? For example, would I need to renew my sphinx hidden tor service before trying to make the IP2Tor bridge or just wait some time till the service is working?

**Comment by rootzoll** [comment]
> Does this mean this happens when the tor service for what we want to bridge is not working or the ip2tor shop service isn't working?

@kevkevinpal in the case I had on my test machine it was because the tor onion service on my blitz was not reachable. The IP2Tor service makes a test call to the service before creating an invoice to check if it gets an HTTPS response but this fails - it gets no response at all and it gives back this error. You can test this by going into MAINMENU > SPHINX and there you copy the onion address and check if you can call with a normal Tor browser (with prefix `http://` or `https://`). Can you test on your device?

**Comment by rootzoll** [comment]
I also had this error again on one of my test machines .. even tho my tor service with https was working when I call it from my desktop tor browser.  But #3129 may have solved the issue. To recheck with v1.8.1

**Comment by Mexxblitz** [comment]
![Timeout](https://user-images.githubusercontent.com/88730884/200119410-4be4e37e-31e9-4354-8dc4-4de30ba8ad02.png)

Is this also Related to the topic? Constantly getting this error message. 
What is happening in the background and is there a way to fix it?

Here the Error Syntax: 
###### ERROR DETAIL FOR DEBUG #######

Error Short:
timeout on getting invoice
Shop:
fulmo7x6yvgz6zs2b2ptduvzwevxmizhq23klkenslt5drxx2physlqd.onion
Bridge:
{'id': 'c62cc284-7f56-4f77-a583-cec3fc905dc7', 'site': 'ip2tor.fulmo.org', 'created_at': '2022-01-14T17:50:59Z', 'modified_at': '2022-11-05T12:10:19Z', 'ip': '46.165.236.103', 'is_enabled': True, 'is_alive': True, 'name': 'eu-fra3', 'is_testnet': False, 'offers_tor_bridges': True, 'tor_bridge_duration': 86400, 'tor_bridge_price_initial': 28000, 'tor_bridge_price_extension': 18000, 'offers_rssh_tunnels': False, 'rssh_tunnel_price': 1000, 'terms_of_service': '-', 'terms_of_service_url': '-', 'ci_date': '2022-11-05T12:10:19Z', 'ci_message': '', 'ci_status': 0, 'owner': 6, 'tor_bridge_duration_hours': 24, 'tor_bridge_price_initial_sats': 28, 'tor_bridge_price_extension_sats': 18}
Error Detail:
{'url': 'http://fulmo7x6yvgz6zs2b2ptduvzwevxmizhq23klkenslt5drxx2physlqd.onion/api/v1/public/pos/1df168a8-a94e-49d3-b33b-433374a44a5e/', 'status': 'M', 'message': None, 'item_details': [{'url': 'http://fulmo7x6yvgz6zs2b2ptduvzwevxmizhq23klkenslt5drxx2physlqd.onion/api/v1/public/po_items/7cb782f4-fde2-4250-961b-9a6c09b5056c/', 'product_id': 'a2079bab-7ef2-4dfc-b041-fb6bf02bdce6', 'product': {'url': 'http://fulmo7x6yvgz6zs2b2ptduvzwevxmizhq23klkenslt5drxx2physlqd.onion/api/v1/tor_bridges/a2079bab-7ef2-4dfc-b041-fb6bf02bdce6/', 'id': 'a2079bab-7ef2-4dfc-b041-fb6bf02bdce6', 'comment': 'RaspiBlitz', 'status': 'I', 'host': {'url': 'http://fulmo7x6yvgz6zs2b2ptduvzwevxmizhq23klkenslt5drxx2physlqd.onion/api/v1/hosts/c62cc284-7f56-4f77-a583-cec3fc905dc7/', 'ip': '**(...)**', 'name': 'eu-fra3', 'site': {'domain': 'ip2tor.fulmo.org', 'name': 'ip2tor.fulmo.org'}, 'is_testnet': False, 'ci_date': '2022-11-05T12:13:35Z', 'ci_status': 0, 'ci_message': ''}, 'port': 45762, 'target': 'kno5a4duvvo2nswsn6oex5ibqj3cyk53dpuq7wwfqraobpcamo6nbvid.onion:443', 'suspend_after': '2022-11-06T12:20:39Z'}, 'position': 0, 'price': 28000, 'quantity': 1, 'po': 'http://fulmo7x6yvgz6zs2b2ptduvzwevxmizhq23klkenslt5drxx2physlqd.onion/api/v1/public/pos/1df168a8-a94e-49d3-b33b-433374a44a5e/'}], 'ln_invoices': [], 'timestamp': '2022-11-05T12:13:46Z'}

Press Enter to continue ...

**Comment by cstenglein** [comment]
IP2Tor is dead for now => closed
