### ISSUE TITLE
Add instructions for switching between mainnet and testnet

### ISSUE THREAD

**Issue by deverickapollo** [raspiblitz/raspiblitz#2248]
Currently, the guide does not describe how to alternate between mainnet and testnet.  We should update instructions to include these steps. 

Steps I'm aware of:

1. Edit bitcoin.conf 
    - testnet=1
2. Edit lnd.conf 
    - bitcoin.testnet=1 and comment out #bitcoin.mainnet=1
3. Create lnd wallet for testnet. 
4. Restart

**Comment by openoms** [comment]
The switch is scripted and can be activated in the SETTINGS menu.

**Comment by deverickapollo** [comment]
Ok thanks! I missed this option.
