### ISSUE TITLE
Minimize / confirm restarts after installing services

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#2249]
When running a routing node any downtime should be minimized.
Restarting the whole node should be the last resort.

I often only use the install scripts in cli to avoid restarts from the menu.
Some services now start automatically in the `raspiblitz.info` has the `state=ready`.

Also just toggling the options on and off in SETTINGS can trigger the restart.
Should aim to modify the scripts to not need full restarts and at least have a chance to confirm before forcing it with a simple notification like:
"Some services will only work after restart."

**Comment by nyxnor** [comment]
Tried to change passwords A, B, C. They all asked to restart, but for sure C just needs to restart LND.
Also, changing password C does not let you exit the menu screen, you are stuck there, `exit` button does not work.

**Comment by rootzoll** [comment]
The new setup process also tries to do the setup in one go without restart. Because a WebUI does not wrok well with restarts I put this on the list for v1.8 that password resetting should not require restarts anymore.

**Comment by rootzoll** [comment]
v1.7.2 needed one setup-restart in the end .. so I we need also have the WebUI being able to handle restarts.

**Comment by openoms** [comment]
Still restarting after activating the Testnets. It can be avoided.

**Comment by rootzoll** [comment]
I think the amount of restart in general was reduced quite good since this issue was created ... closing now. If there is still a restart that somebody likes to see go away please open a new ssue on every single one.
