### ISSUE TITLE
Move everything that needs to survive upgrade to HDD

### ISSUE THREAD

**Issue by frennkie** [raspiblitz/raspiblitz#225]
Files that should still be in-place after a burn-new-SD-card-upgrade ist done should all be on SD card.
Should also include the ssh host keys in `/etc/ssh/`.

**Comment by rootzoll** [comment]
adapted scripts to move everything.
- needs testing on fresh setup
- needs testing on update setup

**Comment by rootzoll** [comment]
looks good on fresh setup - needs still testing on update

**Comment by rootzoll** [comment]
looks good on recover setup also - the ssh keys get created fresh on every new RaspiBlitz and are now stored in `/mnt/hdd/ssh` and they get reused on recover/update with new sd card.
