### ISSUE TITLE
Multi user setup

### ISSUE THREAD

**Issue by chkpnt** [raspiblitz/raspiblitz#2261]
Sorry, can't find anything related to this in the readme and faq: Can I use one Raspiblitz for multiple wallets? Or is a multi-user setup more Apple like and I would need one Raspiblitz for each family member?

**Comment by rootzoll** [comment]
The RaspiBlitz itself is just a system for one Admin ... but check software like LNbits (activate on RaspiBlitz MAINMENU > SERVICES > LNbits) that is like a sub-account management system for your Lightning node and of course you can offer basic services to your family like providing a Electrum server or have them running a lightning wallet on their computer or mobile phone that just needs one channel to your RaspiBlitz and you provide good connectivity with multiple channels and an extra layer of privacy to them.

**Comment by chkpnt** [comment]
Okay, thanks. I don't own a RaspiBlitz yet., I'm just trying to figure out if it would fit my thoughts. But as I'm not very experienced in this space, the thoughts themselves may be wrong.

For Lightning, I'm currently using a custodial BlueWallet, which can be easily be funded by an on-chain transaction. For the backend, a self-hosted LNDHub instance can be used, and I just read that LNbits has a LNDHub integration: So maybe this is exactly what I'm looking for: the family members could connect to the LNDHub instance on RaspiBlitz and create Lightning wallets and fund them by their own. And I'm only responsible for the initial channel setup and the backups.

I'll read more about the software bundled with RaspiBlitz, thanks for the hints.
