### ISSUE TITLE
Can't connect to my node from Fully Noded after upgrade to 1.7.0

### ISSUE THREAD

**Issue by xpsx** [raspiblitz/raspiblitz#2269]
Good evening,

I recently updated my raspiblitz from 1.6.3 to 1.7.0
and now I can't connect to my node from (Fully Noded)
the node is really slow when it I want to view the info.
here is the debug log:

https://termbin.com/yjup

**Comment by openoms** [comment]
Try using the CONNECT menu to connect Fully Noded.
The hidden service is not exposed by default any more.

**Comment by xpsx** [comment]
I already tried it, it gives me error connection was lost, after timeout

**Comment by openoms** [comment]
Running this has helped people.before recreating the Hidden Service:
```
/home/admin/config.scripts/internet.hiddenservice.sh bitcoin8332 8332 8332
```
restart Tor or the whole node to rebuild the Tor circuits.

**Comment by xpsx** [comment]
> Running this has helped people.before recreating the Hidden Service:
> 
> ```
> /home/admin/config.scripts/internet.hiddenservice.sh bitcoin8332 8332 8332
> ```
> 
> restart Tor or the whole node to rebuild the Tor circuits.

Perfect! thanks
