### ISSUE TITLE
Blockchain txindex=0 and new torrent source

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#227]
Check:
https://twitter.com/Stadicus3000/status/1079677441956868097

And for future Electrum Server:
https://twitter.com/Stadicus3000/status/1079677444032995328

If everything works without txindex, maybe also change torrents to:
https://getbitcoinblockchain.com

**Comment by geco91** [comment]
would recommend to check this again for v1.1 .. RaspiBolt has now also removed the txindex .. see:
https://github.com/Stadicus/guides/pull/325

Ask emzy if he can also test a bitcoind with electrum server and give feedback on.

**Comment by CommanderPoe** [comment]
> would recommend to check this again for v1.1 .. RaspiBolt has now also removed the txindex .. see:
> [Stadicus/guides#325](https://github.com/Stadicus/guides/pull/325)
> 
> Ask emzy if he can also test a bitcoind with electrum server and give feedback on.

i was indeed running bitcoind without txindex on the pi when i first used the raspibolt.

**Comment by Emzy** [comment]
I have my RaspiBlitz all the time with txindex=0 running. No issues so far.
electrs and Electrum Personal Server don't need it. Only the Electrumx would need txindex=1

**Comment by vmavromatis** [comment]
I'm fully synced with txindex=1. Do I gain something by switching to txindex=0?

**Comment by Emzy** [comment]
Faster sync time and less disk space. 
The txindex is 19GB in size. But I have no measure how much faster it would be without txindex.

**Comment by rootzoll** [comment]
Testing with torrents from getbitcoinblockchain.com .. they download fast (good seeding), lets see if this works.

**Comment by rootzoll** [comment]
OK getbitcoinblockchain.com sources seem to work in testing

TODO: before final v1.3 package use latest files from that page or add realtime download of latest torrents

**Comment by rootzoll** [comment]
Ah shoot - seeing just now that getbitcoinblockchain.com stopped updating torrent sources last month. OK so ...

Create new torrents for blockchain without index switched on:
TODO: New Torrents for Bitcoin with mainnet/testnet
TODO: New Torrents for Litecoin with mainnet

**Comment by rootzoll** [comment]
OK - tests with new torrents were good. 
Requested help for good seeding:
https://github.com/rootzoll/raspiblitz/issues/285#issuecomment-507224479

**Comment by rootzoll** [comment]
OK. See new torrents are working and seeding is getting good. txindex=0 is now the new default.
