### ISSUE TITLE
Telegraf show wrong CPU temperature

### ISSUE THREAD

**Issue by ghost** [raspiblitz/raspiblitz#2272]
Telegraf shows the wrong CPU temperature in Grafana.

CPU:
<img width="529" alt="GPU" src="https://user-images.githubusercontent.com/83650650/117007803-58f97400-acea-11eb-8f49-6c20b74bc390.png">
GPU:
<img width="524" alt="CPU" src="https://user-images.githubusercontent.com/83650650/117007808-5a2aa100-acea-11eb-966f-ec152f81994c.png">

**Comment by PatrickScheich** [comment]
You are totally right, 

- `cpu_temperature` returns milli celcius as an integer.
- `gpu_temperature` returns celcius as a float

to get the proper CPU temperature in celcius you can use this...
![grafik](https://user-images.githubusercontent.com/50054697/117115337-47b57380-ad8d-11eb-9630-01b5661eda23.png)

**Comment by ghost** [comment]
Works! Thanks!

**Comment by rootzoll** [comment]
@PatrickScheich happy to merge a PR on this for the v1.7.1
