### ISSUE TITLE
Electrum Server failed to start

### ISSUE THREAD

**Issue by ronledfordjr** [raspiblitz/raspiblitz#2277]
RPi 4B 8GB
Raspiblitz 1.7
SSD 1TB

https://termbin.com/im2v5

I am trying to install again.

**Comment by ronledfordjr** [comment]
2nd install
![pal06 electrum](https://user-images.githubusercontent.com/79236343/117117729-80395b00-ad55-11eb-94c0-0da09c546e25.PNG)
 failed

**Comment by openoms** [comment]
We will need to use a more recent release of Rust: https://github.com/romanz/electrs/blob/master/doc/usage.md#build-dependencies

Can try to install the latest Rust with:
`sudo apt install cargo`

and uncomment (put a # in front of) the line:
https://github.com/rootzoll/raspiblitz/blob/be19c565cb5fb570abcd7cf6ad83cc5e4b840520/home.admin/config.scripts/bonus.electrs.sh#L266
in :
`nano config.scripts/bonus.electrs.sh`

Now installing electrs again should work.

**Comment by ronledfordjr** [comment]
Thank you. Should I update the other two nodes?

**Comment by openoms** [comment]
Sorry, what other two nodes?

electrs on 1.7 works, I couldn't reproduce your issue, but if you have this problem now there is a solution.

**Comment by ronledfordjr** [comment]
I have three raspiblitz 1.7 nodes.

**Comment by ronledfordjr** [comment]
Thank you for the help
