### ISSUE TITLE
HDD not mounting

### ISSUE THREAD

**Issue by adz4u28** [raspiblitz/raspiblitz#228]
i already have an external usb hdd that works perfectly fine in raspibolt, i formatted it etc for raspiblitz, but when booting it refuses acknowledge it exists. however i can traverse it in terminal, make files etc. any idea why it wont see it on boot? i have it listed on fstab but for the life of me i cant get the raspibolt initial setup to recognise it :( could you point me in the right direction? i even renamed it BLOCKCHAIN to no avail. its mounted fine but im lost and any assistance would be greatly appreciated.

**Comment by geco91** [comment]
hi. is ist ext4 format?

**Comment by adz4u28** [comment]
yes it is

**Comment by fluidvoice** [comment]
Almost everything is done with the various scripts in the /home/admin folder. Inspect the 30initHDD.sh and 40addHDD.sh scripts and see what they do. But these get run by 10setupBlitz.sh which itself gets run by 00mainMenu.sh when you start setup or SSH into your device and choose "Bitcoin" to setup. So that should setup your HDD correctly.  So minimally, you should be able to SSH in and run `./00mainMenu.sh`

**Comment by fluidvoice** [comment]
a somewhat similar problem here. Might help to take a look: https://github.com/rootzoll/raspiblitz/issues/233

**Comment by adz4u28** [comment]
yeah all that happens for me is:
admin@RaspiBlitz:~ $ ./00mainMenu.sh
Starting the main menu ...
***********************************************************
WARNING: NO HDD FOUND -> Shutdown, connect HDD and restart.
***********************************************************
i can write to the hd, i can list it,copy to it, rename etc  you name it i can do it. except this will not see it and im really stumped. 
like i said, im a linux noob, but looking through the script 30initHDD.sh shows me its looking for sda1 or sda2 and my external drive is called sda ?

admin@RaspiBlitz:~ $ lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda           8:0    0 447.1G  0 disk /mnt/hdd
mmcblk0     179:0    0  14.8G  0 disk
├─mmcblk0p1 179:1    0  43.9M  0 part /boot
└─mmcblk0p2 179:2    0   7.3G  0 part /

**Comment by fluidvoice** [comment]
> NO HDD FOUND

If I grep for "WARNING:" I don't find this warning message anywhere.  What script has this message?
Are you sure you're running the latest raspiblitz release?

**Comment by adz4u28** [comment]
100% i literally downloaded it yesterday and wrote it to a card :( from the guide.

grep -r "WARNING" ./
./raspiblitz/home.admin/00mainMenu.sh:  echo "WARNING: NO HDD FOUND -> Shutdown, connect HDD and restart."

**Comment by fluidvoice** [comment]
Wow, it looks like I'm the one not running the latest code. This might explain the problems I've been having. Will update my node.

**Comment by fluidvoice** [comment]
we just need to figure out why sda1 does not exist for you. For me...

$ lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda           8:0    0 465.8G  0 disk 
└─sda1        8:1    0 465.8G  0 part /mnt/hdd
mmcblk0     179:0    0  29.8G  0 disk 
├─mmcblk0p1 179:1    0  43.8M  0 part /boot
└─mmcblk0p2 179:2    0  29.8G  0 part /

**Comment by fluidvoice** [comment]
It's def looking for sda1 in the bootstrap script: https://github.com/rootzoll/raspiblitz/blob/ed748e433ff3548da05530d97756143e5b4f5991/home.admin/_bootstrap.sh#L75

**Comment by fluidvoice** [comment]
does your /home/admin/raspiblitz.log show anything interesting?

**Comment by adz4u28** [comment]
***********************************************
Running RaspiBlitz Bootstrap 0.99
Mon 31 Dec 18:23:30 GMT 2018
***********************************************
:(

**Comment by fluidvoice** [comment]
The problem may be that you manually did some things with fstab and/or creating other things. The scripts depend on the state of fstab. Dont' do anything manually. I would reformat EXT4 and label "BLOCKCHAIN" and reboot letting the scripts do all the init/setup.

**Comment by fluidvoice** [comment]
The scripts seem to want the device to be at /dev/sda1 which yours is not. So try reformatting with ...
`sudo mkfs.ext4 /dev/sda1 -F -L BLOCKCHAIN`
this was taken directly from this line is the scripts: https://github.com/rootzoll/raspiblitz/blob/843042b8f707582e6c2674b7cbe0d55035e4bc4b/home.admin/30initHDD.sh#L41

**Comment by adz4u28** [comment]
yeah gives me an error saying sda1 doesnt exist, removed the entry in fstab, made no difference. still says no hd 

how do i make my external usb disk sda1 instead of sda ? using the cmd above wont work.

**Comment by fluidvoice** [comment]
> yeah gives me an error saying sda1 doesnt exist, removed the entry in fstab, made no difference. still says no hd
> 
> how do i make my external usb disk sda1 instead of sda ? using the cmd above wont work.

This doesn't work?:
`sudo mkfs.ext4 /dev/sda1 -F -L BLOCKCHAIN`

**Comment by adz4u28** [comment]
okay, sorted it. i fdisked it and removed the lot. rebooted now working. wow.. that was a very intense introduction to linux... haha
now finally i have the bitcoin menu up... wow... :) 
thankyou so much for your assistance!

**Comment by fluidvoice** [comment]
cool. I'm surprised it actually needed to be re-partitioned and not just reformatted with that `mkfs` command I gave above.  Is that true?
please close this issue now.

**Comment by adz4u28** [comment]
no the cmd you posted above wouldnt work because it couldnt find sda1. hence why i used fdisk to redo it.

**Comment by fluidvoice** [comment]
what was the fdisk command line you used? for the sake of others who might have same problem.

**Comment by adz4u28** [comment]
sudo fdisk /dev/sda
accept defaults then
w to write it out.
sudo fdisk -l /dev/sda to check

**Comment by fluidvoice** [comment]
It's funny because nowhere in the scripts or the README does it talk about partitioning or `fdisk`
This command is not run anywhere.

**Comment by rootzoll** [comment]
@piezzo or @frennkie maybe you can help us out here to understand why there was a problem:

I always thought that if there is a HDD device "sda" to have a mountable hdd there needs to be at least a partion called "sda1" - thats what the RaspiBlitz looks for at boot up.

But above someone had a mounted HDD just called "sda". When and how does this happen? 

lsblk --->
NAME MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
sda 8:0 0 447.1G 0 disk /mnt/hdd
mmcblk0 179:0 0 14.8G 0 disk
├─mmcblk0p1 179:1 0 43.9M 0 part /boot
└─mmcblk0p2 179:2 0 7.3G 0 part /

**Comment by frennkie** [comment]
@rootzoll As you pointed out `sda1` is the first partition on the first disk, If there is no `sda1` then most likely reason is that there are no partitions at all...
