### ISSUE TITLE
[v1.7] Tor sources not downloaded on Debian

### ISSUE THREAD

**Issue by adevoss** [raspiblitz/raspiblitz#2283]
When executing 'build_sdcard.sh' on Debian the sources are not downloaded.

Fixed by adding "debian" to the if then statement on line 206 where the sources are downloaded depending on the 'baseimage'.

**Comment by nyxnor** [comment]
Correct, also if its based on debian, should work, so no need to put if statement for the OS.
But for Ubuntu focal should put architecture at the beggining:
```
Note: Ubuntu Focal dropped support for 32-bit, so instead use:
distribution=(lsb_release -sc)
   deb     [arch=arm64] https://deb.torproject.org/torproject.org $distribution main
   deb-src [arch=arm64] https://deb.torproject.org/torproject.org $distribution main
```
 https://support.torproject.org/apt/tor-deb-repo/
 
 
 I already corrected here https://github.com/rootzoll/raspiblitz/pull/2172/commits/6882a11270757c1b1821327fae14111de73447bf# (Not merged yet)
  Line 542  
  The build_sdcard.sh will be changed to be non-interactive, so Tor wont be there anymore.

**Comment by nyxnor** [comment]
Adevoss, please close this regarding that Tor sources will not be included in the build script because of non interactive setup process https://github.com/rootzoll/raspiblitz/issues/2242 and arm64 in this issue https://github.com/rootzoll/raspiblitz/issues/1752#issuecomment-826326858
