### ISSUE TITLE
What are the requirements for LiteCoin LN?

### ISSUE THREAD

**Issue by jgabriel98** [raspiblitz/raspiblitz#2285]
I've just discovered thuis topic, and saw somewhere that you need a 1TB SSD for bitcoin LN, since the blockchain is big and will grow.

But i have some questions:
* But what are the HD/SSD spaces needed for litecoin LN as a routing node?
 * and a SSD is that essential, or can i use a hard drive?, or a usb stick? or even the SD card itself?
 * i plan to use my raspberrypi 4 only as a routing Node, does it change the requirements somehow?
 * can a raspbeery pi zero W take the job too?

**Comment by rootzoll** [comment]
Using the sd card for blockchain storage in general is not recommended and I dont think that a raspberryPi zero will give you enough performance ... RaspberryPi 3 is really the lower limit and RP4 recommended (you want USB3).

A 500GB SSD should be fine, HDD will work too but is much slower. USB sticks are not recommended for safe data storage.

**Comment by cstenglein** [comment]
@jgabriel98 Were your questions answered? 

Closing this for now, if you got more questions, please re-open the issue / make a new one. :)
