### ISSUE TITLE
[v1.7] Not syncing (0 peers)

### ISSUE THREAD

**Issue by adevoss** [raspiblitz/raspiblitz#2286]
After reading #2050 for me this problem still exists.

In the bitcoin log all starts OK (I think) and then at the end there are only lines like this:
`2021-05-08T16:59:59Z connect() to 127.0.0.1:9050 failed after select(): Connection refused (111)`
bitcoind and lnd are running.
tor service is `active (exited)`
`sudo netstat -tulpn` shows no port 9050.

**Comment by openoms** [comment]
this is a tor problem. Error 111 suggests that Tor is not running,

I suggest to reflash with the v1.7 image instead of a lengthy debugging.

**Comment by adevoss** [comment]
Installed it again (on a Debian amd64 VM). Same problem.
When I remove Tor (internet.tor.sh off) btc blockchain is syncing (1 peer).
Don't know about lightning. Didn't had the patience to wait.

`internet.tor.sh off` then `internet.tor.sh on` doesn't help.
Is this fixable?
Output script (the end):
```
use with the port: 80
or the port: 443
sudo: unknown user: sphinxrelay
sudo: unable to initialize policy plugin
Setup logrotate
Job for tor@default.service failed because the control process exited with error code.
See "systemctl status tor@default.service" and "journalctl -xe" for details.
OK - Tor is now ON
needs reboot to activate new setting
```
I didn't install sphinx.

**Comment by openoms** [comment]
So you are not running on an RPi but in a amd64 VM?

`sudo journalctl -n 100 -u tor@default`

can give you more clues or you can try running Tor without systemd with:

`sudo -u debian-tor tor`

and see the output.

**Comment by adevoss** [comment]
Yes.

First statement gives a log with (among other things):
`[warn] Directory /mnt/hdd/tor/web80/ cannot be read: Permission denied`
What should the permissions be? I copied the SSD to the VM. It can be that permissions are changed.
Now the owner is `debian-tor` and the mode is `700`.

Second statement starts tor. Bitcoin is syncing now.
Would be nice if the manual step can be skipped.

**Comment by rootzoll** [comment]
> Bitcoin is syncing now

Sounds good. Closing issue.
