### ISSUE TITLE
LCD Screen - 2nd line missing node address, terminal session

### ISSUE THREAD

**Issue by ronledfordjr** [raspiblitz/raspiblitz#2288]
I have one node missing part of its node address on terminal but shows on LCD screen. Hopefully not a big deal.

![term seesion CPM3](https://user-images.githubusercontent.com/79236343/117567725-f9e98580-b082-11eb-801d-1f99b3863f37.PNG)

![IMG_0186 90](https://user-images.githubusercontent.com/79236343/117567789-6bc1cf00-b083-11eb-9283-13b0d5e683a6.jpg)

**Comment by cstenglein** [comment]
I usually use ssh with my Linux PC and can't reproduce the issue there.

I see that you are using PuTTY(?), but I can't reproduce it there as well with a windows machine with PuTTY 0.75 (got an issue there with q's & x's showing in the main menu but other than that shows the address fine).

What OS and Software are you using to access the session?

**Comment by ronledfordjr** [comment]
Thanks, I logged into terminal and figured it out. I am new at this.

**Comment by cstenglein** [comment]
No worries @ronledfordjr , happy to help :)
