### ISSUE TITLE
ggf. auf opensats.org listen

### ISSUE THREAD

**Issue by vv01f** [raspiblitz/raspiblitz#2292]
@rootzoll auf https://opensats.org/ wäre dieses Projekt IMO recht passend gelistet.

**Comment by rootzoll** [comment]
Gute Idee @vv01f .. will take a look, makes sense to have an organization with 501 managing the donations.

**Comment by rootzoll** [comment]
https://opensats.org/blog/bitcoin-grants-july-2023
