### ISSUE TITLE
RaspiBlitz Took a Dump

### ISSUE THREAD

**Issue by Peter-Bravestrong** [raspiblitz/raspiblitz#2293]
I found my RaspiBlitz in this state (possibly due to power outage):

![pi_dump](https://user-images.githubusercontent.com/75873795/117710805-5cc44500-b187-11eb-8c51-4b074f5ca065.jpg)

No route to SSH in. Power cycling Pi leads to same screen.

Any ideas how to resolve?

**Comment by openoms** [comment]
option 1: connect a USB keyboard and press CTRL+D

option 2 (recommended): reflash the SDcard with the 1.7 image and let the recovery process run (channels will be restored from the disk)

**Comment by Peter-Bravestrong** [comment]
Thank you, openoms, Option 1 worked. Exploring Option 2 soon.
