### ISSUE TITLE
Service tor@lnd fails to start

### ISSUE THREAD

**Issue by janis-mueller** [raspiblitz/raspiblitz#2299]
tor@lnd service is inactive on reboot and can't be manually be started (all of the sudden, no modifications made to it by me)
```sudo service tor@lnd status``` gives the following error:
 ```/usr/bin/install: invalid user ‘_tor-lnd’```
full log: https://termbin.com/wb18

This probably is also the reason why other nodes can't add me as a peer anymore...

raspiblitz v 1.6.3

**Comment by openoms** [comment]
Please reflash the SDcard with the 1.7 image.

**Comment by janis-mueller** [comment]
Flashing to v. 1.7 fixed it - closing.
