### ISSUE TITLE
Litecoin Integration

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#23]
Today I uploaded the basic Litecoin integration. You can now choose in the first setup screen if you want to run your RaspiBlitz on Bitcoin or on Litecoin.

![bildschirmfoto 2018-07-29 um 22 35 34](https://user-images.githubusercontent.com/2472225/43370642-03580792-9383-11e8-81f4-8d7842cd7aca.png)

Use latest SD card image linked in master README.md

Im still running the setup process tests. Any help on trying out Litecoin on the Lightning Network with RaspiBlitz is welcome. Here are some links to try out:

https://github.com/ecurrencyhodler/Litecoin-Resources/blob/master/Lightning%20Network%20Apps.md

Let me know your feedback and issues.

**Comment by vnnkl** [comment]
fyi, might be interesting later on
https://github.com/lightningnetwork/lnd/issues/1331

**Comment by rootzoll** [comment]
@vnnkl thats sweet :) If you see any progress on this that we can utilize for the RaspiBlitz let me know. I also try to keep an ear open.

**Comment by rootzoll** [comment]
seems everybody is happy with the litecoin integration :) .. I close issue for now
