### ISSUE TITLE
Add bluewallet Support

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#230]
https://bluewallet.io

and check their LndHub wrapper:
https://github.com/BlueWallet/LndHub

Could one Blitz host multipüle accounts this way?

**Comment by rootzoll** [comment]
just a reminder: https://lightning-wallet.com .. seems like a standalone, but to keep on mind.

**Comment by openoms** [comment]
Testing the guide on this one: https://github.com/dangeross/guides/blob/master/raspibolt/raspibolt_6B_lndhub.md

**Comment by openoms** [comment]
got stuck on this already:
```admin@openomsRaspiBlitz:~/download/redis-5.0.3 $ sudo systemctl start redis
admin@openomsRaspiBlitz:~/download/redis-5.0.3 $ sudo systemctl status redis
● redis.service - Redis In-Memory Data Store
   Loaded: loaded (/etc/systemd/system/redis.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2019-02-17 08:32:53 GMT; 4s ago
  Process: 4961 ExecStop=/usr/local/bin/redis-cli shutdown (code=exited, status=203/EXEC)
  Process: 4959 ExecStart=/usr/local/bin/redis-server /etc/redis/redis.conf (code=exited, status=203/EX
 Main PID: 4959 (code=exited, status=203/EXEC)

Feb 17 08:32:53 openomsRaspiBlitz systemd[1]: redis.service: Unit entered failed state.
Feb 17 08:32:53 openomsRaspiBlitz systemd[1]: redis.service: Failed with result 'exit-code'.
Feb 17 08:32:53 openomsRaspiBlitz systemd[1]: redis.service: Service hold-off time over, scheduling res
Feb 17 08:32:53 openomsRaspiBlitz systemd[1]: Stopped Redis In-Memory Data Store.
Feb 17 08:32:53 openomsRaspiBlitz systemd[1]: redis.service: Start request repeated too quickly.
Feb 17 08:32:53 openomsRaspiBlitz systemd[1]: Failed to start Redis In-Memory Data Store.
Feb 17 08:32:53 openomsRaspiBlitz systemd[1]: redis.service: Unit entered failed state.
Feb 17 08:32:53 openomsRaspiBlitz systemd[1]: redis.service: Failed with result 'exit-code'.```

**Comment by geco91** [comment]
recommend to give this a shot for v1.1 - but when takes too long to delay this feature

**Comment by rootzoll** [comment]
Recheck on the guide for v1.1 release: https://twitter.com/bluewalletio/status/1096460638799450113

**Comment by rootzoll** [comment]
Also take a look at the pebble wallet while on mobile wallet integration.
https://github.com/IndieSquare/pebblewallet

**Comment by openoms** [comment]
I am very reluctant to use the Bluewallet until they stop sending the xpubs to blockchain.info. https://twitter.com/richblov8s/status/1108883868399095810?s=19

**Comment by openoms** [comment]
see https://github.com/rootzoll/raspiblitz/issues/810 for developments

**Comment by openoms** [comment]
> Also take a look at the pebble wallet while on mobile wallet integration.
> https://github.com/IndieSquare/pebblewallet

Pebble is now discontinued. Some of the team is working on the Nayuta wallet, which is promising, but not open source yet. I tried and paired with my Blitz successfully.

**Comment by openoms** [comment]
Looked at BlueWallet again, but I don't feel it being ready for recommendation/implementation:
* thankfully instead of blockchain.info the wallet connects to Electrum servers. Possible to use a custom server, but only with TCP (unencrypted) and it is not planned to change anytime soon: https://github.com/BlueWallet/BlueWallet/issues/579
![image](https://user-images.githubusercontent.com/43343391/75854985-366b8280-5de9-11ea-890f-5b5db6181aaf.png)

* Communication with LND is over clearnet too:
 https://github.com/BlueWallet/LndHub/issues/33
Despite the screen suggests a https endpoint all tutorials use TCP.
![image](https://user-images.githubusercontent.com/43343391/75855343-f658cf80-5de9-11ea-9f40-61269d48db64.png)

* positive is that logging seems to be not too intruding:
https://github.com/BlueWallet/BlueWallet/blob/master/analytics.js

**Comment by ncoelho** [comment]
Just to give an update on these issues (thanks for pointing them out, sometimes we get overwhelmed on our own little world...)

Since release [v5.1.0](https://github.com/BlueWallet/BlueWallet/releases/tag/v5.1.0) all calls to 3rd party APIs were removed and all wallet types are connecting to our Electrum Servers. There may be some code leftovers, but these are not being used, the heavy work is done.

TLS support for Electrum (with ElectrumX) was merged to master on https://github.com/BlueWallet/BlueWallet/commit/7b5db85c9b6443f9f39289dc6217025b79b7c646 and it will be released by default on the next store update.

Regarding the LNDhub connection, it supports TLS and the connection is made over SSH. 

Any feedback just let me know. Thanks!

**Comment by ncoelho** [comment]
Another update.

https://github.com/BlueWallet/BlueWallet/releases/tag/v5.3.0 introduces TLS for Electrum Personal Server and also for Electrs, we had to disable batching for these specific implementations since they are not following the specifications completely.

**Comment by ghost** [comment]
@ncoelho Does the LNDhub connection also support TOR?

@openoms With TOR and the above mentioned changes for Electrum, would you then feel it´s ready for implementation on Raspiblitz?

**Comment by openoms** [comment]
@INSG2020 my concerns above have been fixed, so would be happy to see LNDhub on the RaspiBlitz as an optional service.

The connection for clients would need en exposed port / remote-ssh-tunnel or Tor2IP service.
Not sure if BlueWallet plays well with Orbot to connect to an LNDHub serving on a .onion.

You can already connect BlueWallet to the Electrum Rust Server Running on the Blitz.
Also there is a browser based LN onboarding service in the form of LNbits.

**Comment by rootzoll** [comment]
Just to mention the lastest LNbits (as of v1.6.1 RaspiBlitz release) .. has a LNDhub plugin. Maybe that is already a start for some ...
![Bildschirmfoto 2020-10-14 um 20 59 29](https://user-images.githubusercontent.com/2472225/96033410-5293cf80-0e60-11eb-9bc9-3f8a3645acf4.png)

**Comment by nyxnor** [comment]
**Jun 19 of 2021 Found some errors with this script, correcting it**

**Note this script is experimental and is not working** (Help wanted)

Guides that will help, but use the Blitz paths and ports:
* https://github.com/dangeross/guides/blob/master/raspibolt/raspibolt_6B_lndhub.md
* https://medium.com/@jpthor/running-lndhub-on-mac-osx-5be6671b2e0c

Journey:
* First, the passwordB is not sourced from bitcoin.conf firle, it is on the script just for testing
* Second, these logs:
```
(node:21500) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:21500) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
```
* Third, not working with the path I set for node:
```
raspberrypi systemd[2645]: lndhub.service: Failed at step EXEC spawning /usr/bin/node: No such file or directory
```

Script:
```bash
#!/bin/bash

redisVersion="6.0.9"

sudo apt install -y tcl

cd /home/admin/download
rm -rf /home/admin/download/*
wget http://download.redis.io/releases/redis-${redisVersion}.tar.gz
tar xzf redis-${redisVersion}.tar.gz
cd redis-${redisVersion}/
make && sudo make install

sudo mkdir /mnt/hdd/redis
sudo adduser --system --group --no-create-home redis
sudo chown redis:redis /mnt/hdd/redis
sudo chmod 770 /mnt/hdd/redis
sudo mkdir /etc/redis
sudo sed -i "s/^supervised .*/supervised systemd/g" redis.conf
sudo sed -i "s/^dir .\//dir \/mnt\/hdd\/redis/g" redis.conf
sudo cp redis.conf /etc/redis

sudo tee /etc/systemd/system/redis.service >/dev/null <<EOF
[Unit]
Description=Redis In-Memory Data Store
After=network.target

[Service]
User=redis
Group=redis
ExecStart=/usr/local/bin/redis-server /etc/redis/redis.conf
ExecStop=/usr/local/bin/redis-cli shutdown
Restart=always

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl start redis
sudo systemctl status redis --no-pager

sudo systemctl enable redis

bash /home/admin/config.scripts/bonus.nodejs.sh on

sudo ufw allow 3050 comment 'allow LndHub'
sudo ufw reload

cd /home/admin/download/
sudo git clone https://github.com/BlueWallet/LndHub
cd /home/admin
sudo mv /home/admin/download/LndHub /home/bitcoin/
sudo mv /home/bitcoin/LndHub /home/bitcoin/.lndhub
sudo cp /home/admin/.lnd/data/chain/bitcoin/mainnet/admin.macaroon /home/bitcoin/.lndhub/
sudo cp /home/admin/.lnd/tls.cert /home/bitcoin/.lndhub/
sudo chown -R bitcoin:bitcoin /home/bitcoin/.lndhub/

rpcuser=raspibolt
rpcpassword=passowrd_b

sudo -u bitcoin tee /home/bitcoin/.lndhub/config.js >/dev/null <<EOF
let config = {
  enableUpdateDescribeGraph: false,
  postRateLimit: 100,
  rateLimit: 200,
  bitcoind: {
    rpc: 'http://${rpcuser}:${rpcpassword}@$127.0.0.1:8332/wallet/wallet.dat',
  },
  redis: {
    port: 6379,
    host: '127.0.0.1',
    family: 4,
    db: 0,
  },
  lnd: {
    url: '127.0.0.1:10009',
    password: '',
  },
};

if (process.env.CONFIG) {
  console.log('using config from env');
  config = JSON.parse(process.env.CONFIG);
}

module.exports = config;
EOF

sudo npm config set prefix '/home/bitcoin/.npm-global'
export PATH=/home/bitcoin/.npm-global/bin:$PATH
sudo npm install

cd /home/bitcoin/.lndhub
npm install @babel/cli -g
npm install @babel/core -g
sudo -u bitcoin mkdir /home/bitcoin/.lndhub/build
sudo -u bitcoin sed -i "s/^let server = app.listen(process.env.PORT || 3000.*/let server = app.listen\(process.env.PORT || 3050, function () {/g" /home/bitcoin/.lndhub/index.js
sudo -u bitcoin sed -i "s/^  logger.log('BOOTING UP', 'Listening on port ' + (process.env.PORT || 3000));/  logger.log('BOOTING UP', 'Listening on port ' + (process.env.PORT || 3050));/g" /home/bitcoin/.lndhub/index.js
npm run babel ./ --out-dir ./build --copy-files --ignore node_modules
cd /home/admin

sudo node /home/bitcoin/.lndhub/build/index.js

sudo tee /etc/systemd/system/lndhub.service >/dev/null <<EOF
[Unit]
Description=LndHub Wrapper for Lightning Daemon
Wants=lnd.service
After=lnd.service

[Service]
WorkingDirectory=/home/bitcoin/.lndhub
ExecStart=/usr/bin/node build/index.js

User=bitcoin
Group=bitcoin
Type=simple
KillMode=process
LimitNOFILE=128000
TimeoutSec=240
Restart=always
RestartSec=60

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable lndhub
sudo systemctl start lndhub

echo
echo "DONE"
```

see logs with:
```
sudo journalctl -f -u lndhub
```

**Comment by rootzoll** [comment]
It looks like that Redis will get a default service for the WebUI BackendAPI with v1.8 .. so I push this to v1.8.1 to then take a look again.

**Comment by nyxnor** [comment]
redis.service is working, just having trouble with babel lines that copy files. So this is close to be accomplished if someone debugs further

**Comment by xanoni** [comment]
I installed this recently on RaspiBolt. Is the script above still the latest? I see a few problems. I can't test it without a RaspiBlitz, but here are the things I would change: 

1. Your script runs as user `admin`, right? Then the `git clone` command shouldn't need a `sudo`
2. The `sudo npm install` command should be run from the `/home/bitcoin/.lndhub` directory, but seems it's run from `/home/admin` instead? It has to move down a few lines in the script.
3. Besides, we can run `sudo -u bitcoin npm install` instead of running it as `root`
4. The command `sudo npm config set prefix '/home/bitcoin/.npm-global'` should be run as user `bitcoin` instead (`sudo -u bitcoin [...]`) ... otherwise it will append the prefix to file `/root/.npmrc` instead of to file `/home/bitcoin/.npmrc`
5. Babel should be installed via `sudo -u bitcoin npm install -g @babel/core @babel/cli` (which will install it into the above-defined npm prefix directory: `/home/bitcoin/.npm-global/`) .... the current script sets `admin`'s `$PATH` to `/home/bitcoin/.npm-global/bin` but then installs `babel` somewhere else, so it won't be found by anyone
6. Once the above is fixed, we can run `sudo -u bitcoin babel ./ --out-dir ./build --copy-files --ignore node_modules` without the `npm run` prefix ... but we need to make sure that `bitcoin`'s `$PATH` includes `/home/bitcoin/.npm-global/bin`
7. Delete this line: `sudo node /home/bitcoin/.lndhub/build/index.js` ... this launches LndHub and shouldn't be part of the build script

**Comment by xanoni** [comment]
Regarding the firewall settings / port forwarding:

I decided to only expose LndHub over Tor. BlueWallet supports that, you just enter the Onion link in the app.

Thus, one could delete these two lines:
```bash
sudo ufw allow 3050 comment 'allow LndHub'
sudo ufw reload
```

And instead add a Hidden Service in `/etc/tor/torrc`:
```
# External port 3000, internal port 3050
HiddenServiceDir /var/lib/tor/hs_lndhub_3000/
HiddenServicePort 3000 127.0.0.1:3050
```

If you wanted to use clearnet, as suggested by the current script, then you would also have to set up an `nginx` reverse proxy (for SSL).

**Comment by nyxnor** [comment]
Thanks for the corrections. Local IP access needs to be a allowed, a self signed certificate can be used.
You are in the right direction, finish this to claim the bounty.

**Comment by xanoni** [comment]
Okay I can finish it this week. The Blitz environment is close enough to the Bolt, so I should be able to test it on a Bolt with some modifications.

**Comment by jmillionaire** [comment]
@xanoni , how's it going? i'd love to contribute by adding to the 200k bounty.

it seems like a number of us are trying to execute this "Uncle Jim" BlueWallet/LndHub/LNBits/Raspiblitz plan. i'm not programming savvy, perhaps i should've bought an Umbrel but i am enjoying the struggle at times when things actually work.

**Comment by xanoni** [comment]
> @xanoni , how's it going? i'd love to contribute by adding to the 200k bounty.
> 
> 
> 
> it seems like a number of us are trying to execute this "Uncle Jim" BlueWallet/LndHub/LNBits/Raspiblitz plan. i'm not programming savvy, perhaps i should've bought an Umbrel but i am enjoying the struggle at times when things actually work. 

Good that you're responding here because I wasn't sure if anyone still cared about this, and there's always endless other stuff.

It shouldn't be difficult, I already have it running on RaspiBolt. Just needs to be repackaged and tested.

**Comment by jmillionaire** [comment]
> > @xanoni , how's it going? i'd love to contribute by adding to the 200k bounty.
> > it seems like a number of us are trying to execute this "Uncle Jim" BlueWallet/LndHub/LNBits/Raspiblitz plan. i'm not programming savvy, perhaps i should've bought an Umbrel but i am enjoying the struggle at times when things actually work.
> 
> Good that you're responding here because I wasn't sure if anyone still cared about this, and there's always endless other stuff.
> 
> It shouldn't be difficult, I already have it running on RaspiBolt. Just needs to be repackaged and tested.

do you have a Blitz to do so?

**Comment by xanoni** [comment]
> > > @xanoni , how's it going? i'd love to contribute by adding to the 200k bounty.
> 
> > > it seems like a number of us are trying to execute this "Uncle Jim" BlueWallet/LndHub/LNBits/Raspiblitz plan. i'm not programming savvy, perhaps i should've bought an Umbrel but i am enjoying the struggle at times when things actually work.
> 
> > 
> 
> > Good that you're responding here because I wasn't sure if anyone still cared about this, and there's always endless other stuff.
> 
> > 
> 
> > It shouldn't be difficult, I already have it running on RaspiBolt. Just needs to be repackaged and tested.
> 
> 
> 
> do you have a Blitz to do so? 

Not right now but I know well enough how the Blitz works so I think I can fake one on the Bolt. 

Someone might have to do a proper test for me, though :)

**Comment by jmillionaire** [comment]
> > > > @xanoni , how's it going? i'd love to contribute by adding to the 200k bounty.
> > 
> > 
> > > > it seems like a number of us are trying to execute this "Uncle Jim" BlueWallet/LndHub/LNBits/Raspiblitz plan. i'm not programming savvy, perhaps i should've bought an Umbrel but i am enjoying the struggle at times when things actually work.
> > 
> > 
> > > 
> > 
> > 
> > > Good that you're responding here because I wasn't sure if anyone still cared about this, and there's always endless other stuff.
> > 
> > 
> > > 
> > 
> > 
> > > It shouldn't be difficult, I already have it running on RaspiBolt. Just needs to be repackaged and tested.
> > 
> > 
> > do you have a Blitz to do so?
> 
> Not right now but I know well enough how the Blitz works so I think I can fake one on the Bolt.
> 
> Someone might have to do a proper test for me, though :)

i'll volunteer!

**Comment by xanoni** [comment]
> > > > > @xanoni , how's it going? i'd love to contribute by adding to the 200k bounty.
> 
> > > 
> 
> > > 
> 
> > > > > it seems like a number of us are trying to execute this "Uncle Jim" BlueWallet/LndHub/LNBits/Raspiblitz plan. i'm not programming savvy, perhaps i should've bought an Umbrel but i am enjoying the struggle at times when things actually work.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Good that you're responding here because I wasn't sure if anyone still cared about this, and there's always endless other stuff.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > It shouldn't be difficult, I already have it running on RaspiBolt. Just needs to be repackaged and tested.
> 
> > > 
> 
> > > 
> 
> > > do you have a Blitz to do so?
> 
> > 
> 
> > Not right now but I know well enough how the Blitz works so I think I can fake one on the Bolt.
> 
> > 
> 
> > Someone might have to do a proper test for me, though :)
> 
> 
> 
> i'll volunteer! 

Thank you that makes it a lot easier ... my main fear was missing something and frustrating people if there's a bug. I'll try to message you somewhere.

**Comment by jmillionaire** [comment]
> > > > > > @xanoni , how's it going? i'd love to contribute by adding to the 200k bounty.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > it seems like a number of us are trying to execute this "Uncle Jim" BlueWallet/LndHub/LNBits/Raspiblitz plan. i'm not programming savvy, perhaps i should've bought an Umbrel but i am enjoying the struggle at times when things actually work.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > Good that you're responding here because I wasn't sure if anyone still cared about this, and there's always endless other stuff.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > It shouldn't be difficult, I already have it running on RaspiBolt. Just needs to be repackaged and tested.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > do you have a Blitz to do so?
> > 
> > 
> > > 
> > 
> > 
> > > Not right now but I know well enough how the Blitz works so I think I can fake one on the Bolt.
> > 
> > 
> > > 
> > 
> > 
> > > Someone might have to do a proper test for me, though :)
> > 
> > 
> > i'll volunteer!
> 
> Thank you that makes it a lot easier ... my main fear was missing something and frustrating people if there's a bug. I'll try to message you somewhere.

@jcmillionaire on Reddit.

**Comment by xanoni** [comment]
> @jcmillionaire on Reddit.

Not a Redditor but I pinged you on Telegram 2 days ago (saw you in the Blitz channel)... seems you no longer use that?

**Comment by xanoni** [comment]
FYI: So I've started putting this together, but ran out of time and need to finish it later ... don't use this in the current form, please. (It's quite close, though. Stay tuned.)

https://github.com/xanoni/raspiblitz/blob/lndhub/home.admin/config.scripts/bonus.lndhub.sh

Diff: https://github.com/xanoni/raspiblitz/commit/972a789978c22022b13052fa61f8858a43b8127a#diff-b611401c764b220e480b4e7350fd52c53b46103512711c862d726744d98698af

**Comment by xanoni** [comment]
@nyxnor @openoms 

Wanted to quickly check a few assumptions with you while I'm finishing this up and testing it.

**Dependencies:**

1. Do you generally prefer to lock all software to a specific version for reproducibility, or to just install the latest (including checking out `master` of repos such as LndHub)?
2. OK to use the `redis-server` package from `apt`? I've been using that with LndHub just fine so far. (Noticed that you download manually instead.)
3. I noticed that the Blitz has an own script to download/install `node` ... I'm using that for now, but just wanted you to be aware that there's also an official `apt` repository with armhf && arm64 binaries, which might be easier to maintain going forward: https://github.com/nodesource/distributions/blob/master/README.md#debinstall

Here are some other repos, in case you want to include any of them: https://github.com/xanoni/RaspberryPi-Setup-Scripts/blob/main/scripts/add-critical-repos.sh

**Deployment:**

4. You install LndHub into `~bitcoin/.lndhub` ... however, personally I avoid `/home/` and prefer to install everything on the SSD and then just have a Symlink to the SSD in the home dir instead... this also allows me to use `ProtectHome=true` in the systemd file ... is this approach OK with you?
5. Do you prefer to have node `node_modules` in the global location (under `/usr/local/`), or use an LndHub-specific folder? (I'd just use the global one if you don't care.)
6. Have we already stored somewhere if the user wants just Tor / just SSL / Tor+SSL, or should I prompt the user directly in the script?
7. Should the LndHub logfiles be handled by / accessible just via systemd, or do you want me to write them to some specific folder as well?

**Security:**

8. Should I create a dedicated `lndhub` user, or do you prefer to have everything under `bitcoin`, the way it is now?
9. FYI, I'll have to write the URL-encoded Bitcoin RPC credentials into the LndHub config, hope that's fine (of course I'll `chmod 600` the file)

**Upgrades/removal:**

10. Does Raspiblitz handle automatic removal and upgrades of `bonus` packages, such as LndHub? Is this something I should implement? If yes, what other component would be good to look at as an example?

**Comment by openoms** [comment]
Will come back to answer in detail if needed, but here are some quick notes:

look at the structure of existing scripts, for example bonus.thunderhub.sh is fairly well commented, many of your questions will be answered by that

could use apt to install node, but then it it needs to be changed in all the other scripts so there are no multiple methods to install

aim to use a dedicated user and symlinks to the disk

`on` and `off` is required, `update` is nice to have

**Comment by xanoni** [comment]
> look at the structure of existing scripts, for example bonus.thunderhub.sh is fairly well commented, many of your questions will be answered by that

I think I looked at the most important scripts, but for most of these 10 questions (specifically 1 / 2 / 3 / 4 / 5 / 7 / 8), my question is more "do you want things to be exactly like in the other script(s), or is it OK if I do it somewhat differently if I believe it makes sense to do that" :)

**Comment by openoms** [comment]
you can do anything sensible which does not interfere with the other parts and tests successfully on working raspiblitz system + BlueWallet.

I see no problem using apt for the dependencies. Pinning the apt packages are usually not necessary because they are well tested with the underlying OS (see the comment on NodeJS above).

The unique data needs to be recoverable during an SDcard update (this is the main reason to. symlink it from `/mnt/hdd/app-data`). This is to be tested as well. 

Have a Tor+SSL port available to be used for the IP2Tor service in case there are problems with the Tor implementation in BW and to test.

**Comment by openoms** [comment]
LNDHub itself should be pinned to the tested version to be able to fallback with a reinstall with an optional update feature as a nice to have.

**Comment by openoms** [comment]
once the install script works with at least the options of `on` and `off` the next step will be to look at the `menu` entry and how to connect with a QRcode from the menu.
Then for the recovery and other integrations search in the codebase for example where `bonus.thunderhub.sh` pops up in the other scripts.

**Comment by xanoni** [comment]
Okay! thank you I have what I need then

**Comment by resignedScientist** [comment]
So what's the status here? Do you need help @xanoni ?
My linux skills are not enough to really help, but I can test it on my Raspiblitz if you want.

**Comment by xanoni** [comment]
Sorry but I'm currently somewhat disconnected from this world here. Life.

**Comment by seinzfiction** [comment]
@rootzoll is there some support required on this item? I'd be interested to do some work on this.

**Comment by openoms** [comment]
@seinzfiction thank you for the offer. Before working to integrate LNDhub itself check if the the latest LNbits might provide an LNDHub plugin which would make it available for the LND and CLN funding source as well.

**Comment by seinzfiction** [comment]
@rootzoll The current LNBits offers a LNDHub extension already. But as far as I understood and experienced it, this extension offers LNDHub for the LNBits users wallets. Via this way it is not possible to offer LNDHub access for the Raspiblitz Lightning wallet directly.

**Comment by openoms** [comment]
So multiple users must be handled by LNbits then - they need to create a wallet and get the LNDhub link individually as I undestand
This is indeed less convenient then just having one LNDhub link to share so might justify the standalone LNDhub implementation.

**Comment by seinzfiction** [comment]
@openoms you're right. LNBits provides custodial Lightning wallets to 3rd party users and the LNDHub extension in LNBits can be used to access those wallets through Blue Wallet directly.

**Comment by prusnak** [comment]
There is a very promising reimplementation of LndHub in Go language here: https://github.com/getAlby/lndhub.go
I recommend to use this as a LndHub/BlueWallet server.

**Comment by Smiggel** [comment]
Tried LNbits with LNDHub but Raspiblitz does not save the settings. It loses the wallet and the LNDHub installation. When I create a wallet, and close LNBits, and re-open it again, the wallet is gone.

**Comment by rootzoll** [comment]
> Tried LNbits with LNDHub but Raspiblitz does not save the settings. It loses the wallet and the LNDHub installation. When I create a wallet, and close LNBits, and re-open it again, the wallet is gone.

@callebtc can you take a look or patch us to the right LNbits person what persistence error this could be with LNDhub plugin?

**Comment by jmillionaire** [comment]
> Tried LNbits with LNDHub but Raspiblitz does not save the settings. It loses the wallet and the LNDHub installation. When I create a wallet, and close LNBits, and re-open it again, the wallet is gone.

I had to bookmark my LNBits on Tor Browser

**Comment by callebtc** [comment]
If the wallet is gone (not the extension) it would rather sound like a deeper db persistance problem. But then nothing in LNbits would work.

@Smiggel what do you mean exactly by "the wallet is gone"?

@rootzoll how do I test this without a blitz?

**Comment by rootzoll** [comment]
> @rootzoll how do I test this without a blitz?

Maybe @arcbtc can sponsor a RaspiBlitz from FULMO for future testing?

**Comment by Smiggel** [comment]
> @Smiggel what do you mean exactly by "the wallet is gone"?

Perhaps I am understanding incorrectly how it should, but here is what I do:

1. Installed LND bits.
2. Installed LND Hub
3. Create a wallet
4. Close the browser
5. Open the browser and browse to LND bits

After point 5 I expect to see my wallet from step 3. However, I don’t see the wallet anymore. When I look at the extensions, I see the “install” button again for LND hub.

I would except the wallet to be there and the extension installed.

**Comment by arbadacarbaYK** [comment]
> I would except the wallet to be there and the extension installed.

Did you open the wallet by its URL or just open LNbits ? You either need to save the URL of the wallet or import it to e.g. BlueWallet by using the "Export-via-QR-to-phone" feature, see the popup you click when generating a wallet 😋 Sats are still on your node so nevermind about the lost link.

**Comment by Smiggel** [comment]
Thanks, I will give that a try.

**Comment by cstenglein** [comment]
BlueWallet doesn't support Lightning anymore

@rootzoll closing this for now
