### ISSUE TITLE
force close error code 500

### ISSUE THREAD

**Issue by LuxStatera** [raspiblitz/raspiblitz#2301]
I tried to force close a channel on the RTL page but I get an error message. Error Code: 500. Error Message: Unknown Error. I also tried to ssh in and close the channels that way but after the latest update the option to close channels is gone.

**Comment by openoms** [comment]
the option is in the LIGHTNING mneu
can also use the `-f` option with `lncli closechannel`

Try:
`lncli closechannel -h`

**Comment by openoms** [comment]
Also the CLOSEALL option only appears if you have at least one channel open according to:
`lncli listchannels`

Your channel might have been closed already, refresh RTL.

**Comment by openoms** [comment]
closing for inactivirty
