### ISSUE TITLE
Wrong message during the IP2TOR subscription process

### ISSUE THREAD

**Issue by AxelHamburch** [raspiblitz/raspiblitz#2302]
When I abort a changing of my IP2TOR subscripton for LNBITS I get the message:

"restarting Sphinx Relay to pic a new public url (please wait) ..."

Looks like a wrong message, or not?

![2021-05-15 10_43_19-OpenSSH SSH client - sphinx relay](https://user-images.githubusercontent.com/84231978/118361160-51f42080-b58a-11eb-9f78-26675b41ef61.jpg)

**Comment by rootzoll** [comment]
Thanks for the report .. changed for v1.7.1 release.
