### ISSUE TITLE
Bootloop after shutdown and 1.7.0

### ISSUE THREAD

**Issue by wa1id** [raspiblitz/raspiblitz#2303]
Hello, 

I wanted to update from 1.6.3 to 1.7.0 so I shutdown the rpi from the menu. Then i removed the sdcard and flashed version 1.7.0 on it. After putting it back and starting the rpi I get in a bootloop with this message flashing for 1 second: 
![signal-2021-05-15-170250](https://user-images.githubusercontent.com/23665945/118366041-68f13d80-b59f-11eb-82d8-520d58b93e40.jpeg)

I tried flashing again with 1.6.3 but even this is not working now. What can I do to solve this issue?

EDIT: flashed on another sdcard and currently its booting up. The previous sdcard just...died?

**Comment by nyxnor** [comment]
Yes, sd card failure. As this was solved, pls close this issue.
