### ISSUE TITLE
apt upgrade

### ISSUE THREAD

**Issue by dalamanster** [raspiblitz/raspiblitz#2321]
Hi there,

is it safe to update raspiblitz with "apt update + apt upgrade" ? 
Or should I always wait for official raspiblitz releases ? 

I want to have packages with latest security updates.

Thank you

**Comment by openoms** [comment]
we can't predict if new versions of everything will break things.
If there is anything specific you want to update use
`sudo apt install PACKAGE_NAME`

If the system breaks the tested release (latest SDcard image) is there as a fallback.

**Comment by openoms** [comment]
Since the Tor configuration has been refactored apt upgrade is less prone to break and it is the best practice running linux to keep paackages up to date.
Usually it is not necessary to run this between releases, but can do especially if there is some known vulnerability.
