### ISSUE TITLE
just got everything up and running...

### ISSUE THREAD

**Issue by DrBlackross** [raspiblitz/raspiblitz#2323]
and noticed "ThunderBase Token" ??
"This token gives you access to the full ThunderBase API." whats this?

(oh and should i worry)

**Comment by openoms** [comment]
Is this the paid service token for ThunderHub by any chance? Could you give some more details?
Is there anything actionable for us?

**Comment by DrBlackross** [comment]
yea i think it was the paid service, doesn't matter went back RTL
