### ISSUE TITLE
LND Balance changing without new TXNs

### ISSUE THREAD

**Issue by inpharmaticist** [raspiblitz/raspiblitz#2330]
Hello,

I've noticed my lightning balance changing every now and then without doing any transactions. In this case, it went up ~11k sats. Not sure what's going on.

![3667d33b-a71a-4e15-ad22-4e17390c2693](https://user-images.githubusercontent.com/49789899/119701669-7b723f00-be09-11eb-8040-57db776d9f5b.png)
![917c72db-8588-4f91-8a9b-79a82b3f2cb4](https://user-images.githubusercontent.com/49789899/119701676-7e6d2f80-be09-11eb-9fac-8d94066f72c3.png)

**Comment by inpharmaticist** [comment]
Just went up another 10k sats

![cbcb3da6-efef-4198-bdbe-df8152cc6d91](https://user-images.githubusercontent.com/49789899/119719153-4c65c880-be1d-11eb-8373-7873ee6dd493.png)

**Comment by openoms** [comment]
This is normal and changiing with the mempool (`bitcoin-cli estimatesmartfee 1` results).

There is always a reserve on the channels you opened to be able to pay a force (unilateral) close.
As miner fees go up, the reserve goes up as well and vice versa.

This reserve is on;y used in case of a force close and the sats are yours, but cannot be spent on LN when the miner fees are high.

**Comment by inpharmaticist** [comment]
Wow, I'm surprised I've never noticed before. Is there a way to monitor this on the lncli side, perhaps as it changes over time?

**Comment by openoms** [comment]
here are the actual values:
`lncli listchannels | grep commit_fee`

It is chainging when the peers are online and aggreeing on the new commitment txn according to their 
`bitcoin-cli estimatesmartfee 1` afaik.

This is a common question on all LN forums.

**Comment by devotedcorey** [comment]
Thanks

**Comment by inpharmaticist** [comment]
Thanks
