### ISSUE TITLE
UndervoltageReports in Logs: 2

### ISSUE THREAD

**Issue by ronledfordjr** [raspiblitz/raspiblitz#2338]
https://termbin.com/i0uk2

I am using a Raspberry Pi Power Supply

What is the command to run the hardware test? I've looked through the menu and I may have overlooked it.

Thanks

**Comment by nyxnor** [comment]
Hardware test was removed and the mention of documentation also https://github.com/rootzoll/raspiblitz/pull/2281
It is going to be refactored later.

**Comment by ronledfordjr** [comment]
Thanks
