### ISSUE TITLE
nginx failed - electrum 

### ISSUE THREAD

**Issue by Adrianvic032** [raspiblitz/raspiblitz#2342]
Hi there,
  Please advice. The following error is up when I try to start Electrum server on newly installed fully syncd Raspiblitz v: 1.7.1.

Error:
Nginx:(emerg) PEM_read_bio_DHparams("/etc/ssl/certs/dhparams.pem) failed SSL error.

nginx config file: /etc/nginx/nginx.conf  -  ssl error : 0909006c

Any help - highly appriciated - Thanks

**Comment by openoms** [comment]
there is no v1.7.1 yet.
Plase reflash the latest v1.7.0 image.

**Comment by Adrianvic032** [comment]
Sorry, typo error. Its Raspiblitz version 1.7.0
Thanks for your promt email reply. I still get 'nginx failed' error and
electrum is not starting. Please advice. Thanks

**Comment by Adrianvic032** [comment]
Sorted after re-image from scratch. Thanks

**Comment by nyxnor** [comment]
Good that it was sorted. Please close this Adrianvic
