### ISSUE TITLE
Zap Android doesn't connect - SSL handshake aborted

### ISSUE THREAD

**Issue by agd-media** [raspiblitz/raspiblitz#2348]
While Zeus connects to my node, Zap Android is showing following error:

SSL handshake aborted: ssl=0x7e1a8f9588: I/O error during system call. Connection reset by peer

I tried the bonusxxxx.sh and refreshing the certs. No success.

I wouldn't have this problem if RTL, Thunderhub or Zeus would support lnurl open channel.

**Comment by NilByte** [comment]
Zap Android mobile connect was disabled in 1.7.0 menu. 

I had to edit menu to enable it again and then had no trouble connecting Zap Android mobile wallet again.

home.admin/97addMobileWallet.sh

https://github.com/rootzoll/raspiblitz/commit/ba8cd7a62b1e216772c065a2a4757543ae08064a

**Comment by agd-media** [comment]
How did you edit the menu? Just deleting the # in 97addMobileWallet.sh won't work.

**Comment by agd-media** [comment]
That worked! ZAP connected after like 10 tries.

**Comment by rootzoll** [comment]
There were some updates for ZAP wallet - will check for v1.7.1 if we can re-add ZAP by default.

**Comment by rootzoll** [comment]
Pushing this up to v1.8.0 (due to time limitations).

**Comment by michaelWuensch** [comment]
Hi, I am the maintainer of Zap Android.
I don't run a raspiblitz myself, but if you run into trouble, just drop a message here and I will see if I can help.
Lately there were bigger changes, like integrated tor support without orbot, but everything should still work the same in regards to lndconnect string.
When accessing a .onion node no cert needs to be transmitted.
Zap iOS is not maintained at the moment.

**Comment by jigglycrumb** [comment]
I just connected Zap Android (0.5.2-beta) successfully with Raspiblitz 1.7.1 over Tor. I had to add the option back to the connect menu manually like @NilByte mentioned, the rest worked just fine.

**Comment by rootzoll** [comment]
Opened `2348zap` branch to test Zap wallet integration again.

**Comment by rootzoll** [comment]
OK Zap iOS & Android tests look good again ... adding back to RaspiBlitz SSH connect menu for v1.7.2.
Merging branch into `dev` & ready for final testing.

**Comment by rootzoll** [comment]
Thru new tor refactor there is no default tor hidden service anymore for LND Rest or GRPC with v1.7.2RC2 .. need to add them on demand when user wants to connect mobile.

**Comment by rootzoll** [comment]
OK Tor service gets now created if needed. keeping for final testing.

**Comment by rootzoll** [comment]
OK tested. Ready for relase. Closing issue.
