### ISSUE TITLE
Zapconnect

### ISSUE THREAD

**Issue by eurtnl** [raspiblitz/raspiblitz#235]
OK, so i finally got it up and running. Now i would like to connect Zap. But i get the next error:
*** Setup ***

Installing zapconnect. Please wait...

Getting github.com/LN-Zap/zapconnect (please wait) ...
./97addMobileWalletZap.sh: line 17: cd: /usr/local/gocode/src/github.com/LN-Zap/zapconnect: No such file or directory

and then nothing...:(

**Comment by eurtnl** [comment]
Oh wait...now i got this:
*** STEP 2 : Click on Scan (make whole QR code fill camera) ***
./97addMobileWalletZap.sh: line 51: zapconnect: command not found
(To shrink QR code: OSX->CMD- / LINUX-> CTRL-) Press ENTER when finished.

but no qr code

**Comment by fluidvoice** [comment]
echo "If its not working - check issues on GitHub:"
echo "https://github.com/LN-Zap/zap-iOS/issues"
echo "https://github.com/LN-Zap/zapconnect/issues"

**Comment by fluidvoice** [comment]
the script failed to build zapconnect so nothing is running.

**Comment by eurtnl** [comment]
no kidding ;-)
So what tot do now?

**Comment by fluidvoice** [comment]
It looks like the script needs 'go' installed. Does Zap have directions on building this?

```
echo "Installing zapconnect. Please wait..."
export GOROOT=/usr/local/go
export PATH=$PATH:$GOROOT/bin
export GOPATH=/usr/local/gocode
export PATH=$PATH:$GOPATH/bin
echo ""
echo "Getting github.com/LN-Zap/zapconnect (please wait) ..."
cd $GOPATH/src/github.com/LN-Zap/zapconnect
go get -d github.com/LN-Zap/zapconnect
echo ""
echo "Building github.com/LN-Zap/zapconnect ..."
make


```

**Comment by eurtnl** [comment]
So you're suggesting i should install go? I'll have a look

**Comment by fluidvoice** [comment]
try `sudo apt-get install golang`

**Comment by fluidvoice** [comment]
Btw, I just saw something than indicated that **zapconnect** is deprecated for **lndconnect**:
https://github.com/LN-Zap/lndconnect
But it needs go also:

```
go get -d github.com/LN-Zap/lndconnect
cd $GOPATH/src/github.com/LN-Zap/lndconnect
make
```

**Comment by fluidvoice** [comment]
LNDConnect is talked about here: https://medium.com/@JimmyMow/announcing-zap-desktop-0-3-0-beta-7eb3b7df4a8c

**Comment by eurtnl** [comment]
ok, did `sudo apt-get install golang` and `go get -d github.com/LN-Zap/lndconnect`
now it says
package github.com/LN-Zap/lndconnect: cannot download, $GOPATH not set. For more details see: go help gopath
should i reboot first?

**Comment by fluidvoice** [comment]
try running these first:
```
export GOROOT=/usr/local/go
export PATH=$PATH:$GOROOT/bin
export GOPATH=/usr/local/gocode
export PATH=$PATH:$GOPATH/bin
```

**Comment by eurtnl** [comment]
Did that and than make. now i get:
```
go get ./...
import cycle not allowed
package github.com/LN-Zap/lndconnect
	imports encoding/base64
	imports encoding/binary
	imports errors
	imports runtime
	imports internal/bytealg
	imports internal/cpu
	imports runtime
Makefile:4: recipe for target 'dep' failed
```

**Comment by fluidvoice** [comment]
I can't even get past the `go get` command it keeps telling me 
> cannot download, $GOPATH not set
 
I don't know squat about go programming and apparently they like to over complicate their build environment.

**Comment by RolfHodl** [comment]
Try to run the mobile install a second time. This does trigger the download. First it failed like you stated.

**Comment by fluidvoice** [comment]
> Try to run the mobile install a second time. This does trigger the download. First it failed like you stated.

what do you mean by "mobile install"?

**Comment by RolfHodl** [comment]
The menu point
-Main Menu -> Mobile -> Yes -> Zap

I had it to rune 2 times until I get a QR Code. Then it worked from mobile and desktop.

**Comment by fluidvoice** [comment]
This only works if, as mentioned above, if you already have 'go' installed.  The script does not install go for you so it will fail to build zapconnect or lndconnect.  What directions did you use to install go?

**Comment by eurtnl** [comment]
I get this error when installing ZAP:
```
*** Setup ***

Installing zapconnect. Please wait...

Getting github.com/LN-Zap/zapconnect (please wait) ...
import cycle not allowed
package github.com/LN-Zap/zapconnect
	imports encoding/base64
	imports encoding/binary
	imports errors
	imports runtime
	imports internal/bytealg
	imports internal/cpu
	imports runtime

Building github.com/LN-Zap/zapconnect ...
go get ./...
import cycle not allowed
package github.com/LN-Zap/zapconnect
	imports encoding/base64
	imports encoding/binary
	imports errors
	imports runtime
	imports internal/bytealg
	imports internal/cpu
	imports runtime
Makefile:4: recipe for target 'dep' failed
make: *** [dep] Error 1
```
Than it says:
```
******************************
Connect Zap Mobile Wallet
******************************

GETTING THE APP
At the moment this app is in closed beta testing and the source code has not been published yet.
Go to http://www.zap-ios.jackmallers.com sign up with your email (confirmation can take time)
iOS: Read https://developer.apple.com/testflight/testers/

*** STEP 1 ***
Once you have the app is running make sure you are on the same local network (WLAN same as LAN).
During Setup of the Zap app you should get to the 'Connect Remote-Node' screen.

---> Click on Scan
Make the this terminal as big as possible - fullscreen would be best.
Then PRESS ENTER here in the terminal to generare the QR code and scan it with the app.

*** STEP 2 : Click on Scan (make whole QR code fill camera) ***
./97addMobileWalletZap.sh: line 51: zapconnect: command not found
(To shrink QR code: OSX->CMD- / LINUX-> CTRL-) Press ENTER when finished.
```
But no QR code

Guess it has something to do with `import cycle not allowed`.
How to solve that?

**Comment by fluidvoice** [comment]
what is displayed if you run this:
`export | grep GO`
`which go`
`go version`
`go environment`
I think you need to learn how to install golang correctly on Raspbian.  I think what is failing is the make (go building) is not finding the build dependencies (imports).  Try searching the Raspbian and Raspberri Pi forums, or maybe golang forums or Zap forums.

**Comment by rootzoll** [comment]
In the lastest SD card build. GO should be installed.

@eurtnl did you started with the lastest sd card relase or did you some update with XXupdateScripts in between?

**Comment by zer0trst** [comment]
I've hit the same wall - fresh install of 0.99 on sd card today.

after running

      go get -d github.com/LN-Zap/lndconnect

all i get is this

![image](https://user-images.githubusercontent.com/46293453/50597813-6e7cea00-0ef4-11e9-9b39-9a37b8da7f51.png)

Here is my go Env file

![image](https://user-images.githubusercontent.com/46293453/50597880-a84df080-0ef4-11e9-8ae9-62c4edc5ea29.png)

**Comment by fluidvoice** [comment]
> In the lastest SD card build. GO should be installed.
> 
> @eurtnl did you started with the lastest sd card relase or did you some update with XXupdateScripts in between?

Good pointer, thanks. I will try to run the 16 lines you used in the SD card build script:
https://github.com/rootzoll/raspiblitz/blob/ed748e433ff3548da05530d97756143e5b4f5991/build.sdcard/raspbianStretchDesktop.sh#L346

```
# Go is needed for ZAP connect later
echo "*** Installing Go ***"
wget https://storage.googleapis.com/golang/go1.11.linux-armv6l.tar.gz
if [ ! -f "./go1.11.linux-armv6l.tar.gz" ]
then
    echo "!!! FAIL !!! Download not success."
    exit 1
fi
sudo tar -C /usr/local -xzf go1.11.linux-armv6l.tar.gz
sudo rm *.gz
sudo mkdir /usr/local/gocode
sudo chmod 777 /usr/local/gocode
export GOROOT=/usr/local/go
export PATH=$PATH:$GOROOT/bin
export GOPATH=/usr/local/gocode
export PATH=$PATH:$GOPATH/bin
echo ""
```

I literally put these lines in a shell script and ran it...
$ `touch install-go.sh`
$ `chmod +x install-go.sh` 
$ `sudo vi install-go.sh`  (then insert lines and save)

First clean up previous install
`sudo apt purge golang`
`sudo apt autoremove`   
`sudo apt update`
`sudo rm -rf /usr/local/go`
`sudo rm -rf /usr/local/golang`

now run proper install
$`./install-go.sh`  (the download is 97MB)

after...
$ `which go`
> /usr/local/go/bin/go

$ `go version`
> go version go1.11 linux/arm

$ `go env`
> GOARCH="arm"
> GOBIN=""
> GOCACHE="/home/admin/.cache/go-build"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="arm"
> GOHOSTOS="linux"
> GOOS="linux"
> GOPATH="/usr/local/gocode"
> GOPROXY=""
> GORACE=""
> GOROOT="/usr/local/go"
> GOTMPDIR=""
> GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm"
> GCCGO="gccgo"
> GOARM="6"
> CC="gcc"
> CXX="g++"
> CGO_ENABLED="1"
> GOMOD=""
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build664352346=/tmp/go-build -gno-record-gcc-switches"
> 

Then the rest:

$ `go get -v -d github.com/LN-Zap/lndconnect`
> github.com/lightningnetwork/lnd (download)
> github.com/btcsuite/btclog (download)
> github.com/miekg/dns (download)
> Fetching https://golang.org/x/net/proxy?go-get=1
> Parsing meta tags from https://golang.org/x/net/proxy?go-get=1 (status code 200)
> get "golang.org/x/net/proxy": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/proxy?go-get=1
> get "golang.org/x/net/proxy": verifying non-authoritative meta tag
> Fetching https://golang.org/x/net?go-get=1
> Parsing meta tags from https://golang.org/x/net?go-get=1 (status code 200)
> golang.org/x/net (download)
> 

$ `cd $GOPATH/src/github.com/LN-Zap/lndconnect`
$ `make`
> go get ./...
> go install -v ./...

$ `lndconnect --help`
> Usage:
>   lndconnect [OPTIONS]

**Comment by zer0trst** [comment]
Works for me now.

I removed previous install of golang

      sudo apt purge golang
      sudo apt autoremove   
      sudo apt update

then I ran

      wget https://storage.googleapis.com/golang/go1.11.linux-armv6l.tar.gz
      sudo tar -C /usr/local -xzf go1.11.linux-armv6l.tar.gz
      sudo rm *.gz
      sudo mkdir /usr/local/gocode
      sudo chmod 777 /usr/local/gocode
      export GOROOT=/usr/local/go
      export PATH=$PATH:$GOROOT/bin
      export GOPATH=/usr/local/gocode
      export PATH=$PATH:$GOPATH/bin

went to mobile wallet menu in raspbiblitz, ran it and voila it works!

Thanks!

**Comment by fluidvoice** [comment]
Nice! I'll remove previous install and try it again.

**Comment by fluidvoice** [comment]
There is no Zap wallet for Android?  Looks like this functionality does not exist in the Zap desktop wallet (on Linux)

**Comment by eurtnl** [comment]
> In the lastest SD card build. GO should be installed.
> 
> @eurtnl did you started with the lastest sd card relase or did you some update with XXupdateScripts in between?

I did a fresh install yesterday, no update.

**Comment by eurtnl** [comment]
> Works for me now.
> 
> I removed previous install of golang
> 
> ```
>   sudo apt purge golang
>   sudo apt autoremove   
>   sudo apt update
> ```
> then I ran
> 
> ```
>   wget https://storage.googleapis.com/golang/go1.11.linux-armv6l.tar.gz
>   sudo tar -C /usr/local -xzf go1.11.linux-armv6l.tar.gz
>   sudo rm *.gz
>   sudo mkdir /usr/local/gocode
>   sudo chmod 777 /usr/local/gocode
>   export GOROOT=/usr/local/go
>   export PATH=$PATH:$GOROOT/bin
>   export GOPATH=/usr/local/gocode
>   export PATH=$PATH:$GOPATH/bin
> ```
> went to mobile wallet menu in raspbiblitz, ran it and voila it works!
> 
> Thanks!

This did work for me too, thanks guys!

**Comment by fluidvoice** [comment]
> > Works for me now.
> > I removed previous install of golang
> > ```
> >   sudo apt purge golang
> >   sudo apt autoremove   
> >   sudo apt update
> > ```
> > then I ran
> > ```
> >   wget https://storage.googleapis.com/golang/go1.11.linux-armv6l.tar.gz
> >   sudo tar -C /usr/local -xzf go1.11.linux-armv6l.tar.gz
> >   sudo rm *.gz
> >   sudo mkdir /usr/local/gocode
> >   sudo chmod 777 /usr/local/gocode
> >   export GOROOT=/usr/local/go
> >   export PATH=$PATH:$GOROOT/bin
> >   export GOPATH=/usr/local/gocode
> >   export PATH=$PATH:$GOPATH/bin
> > ```
> > went to mobile wallet menu in raspbiblitz, ran it and voila it works!
> > Thanks!
> 
> This did work for me too, thanks guys!

Please close this issue. thanks.

**Comment by zer0trst** [comment]
Okay I have reset my blitz again (due to other reasons) and can confirm I did have to also run the following

      go get -d github.com/LN-Zap/zapconnect
 
and

      go get -d github.com/LN-Zap/lndconnect


Not sure why this made it work but it did..?

**Comment by fluidvoice** [comment]
The script 97addMobileWalletZap.sh needs to be modified to something like this in the first half of the file, second half remains the same:


source /mnt/hdd/raspiblitz.conf
clear
echo "*** Setup ***"
echo ""
echo "Installing lndconnect. Please wait..."
export GOPATH=/usr/local/gocode
export PATH=$PATH:$GOPATH/bin
echo ""
echo "Getting github.com/LN-Zap/lndconnect (please wait) ..."
mkdir $GOPATH/src/github.com/LN-Zap/lndconnect
cd $GOPATH/src/github.com/LN-Zap/lndconnect
go get -d github.com/LN-Zap/lndconnect
echo ""
echo "Building github.com/LN-Zap/lndconnect ..."
make
cd
sleep 3

**Comment by rootzoll** [comment]
I will recheck for verison 1.0 - thx.

**Comment by rootzoll** [comment]
OK. I had to fix the GOPATH again (for the next release), but then it installed zapconnect correctly and displayed the QR code. I was also able to scan the QR code with the ZAp mobile app and macaroon+TLS showed up correctly in the app.

But I was not able to connect with my dyndns or with publicIP - I had to replace it in the app with the local LAN IP an the the app was working with my RaspiBlitz. The macaroons/TLS are OK with the dyndns/publicIP, because they are working with no problem in Shango and Zap Desktop. So this looks like a bug on the Zap mobile site.

I wrote I tweet to the iOS dev: https://twitter.com/rootzoll/status/1086028470646394880

So I close this issue for now for the next release - if you have further problems, please request reopen.
