### ISSUE TITLE
Use the new LND wallet auto-unlock

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2356]
Instead the custom workaround ... see:
https://twitter.com/mynodebtc/status/1405665230231855105?s=20

**Comment by openoms** [comment]
Note regarding LND:
https://twitter.com/guggero/status/1409384492134023170?s=19

**Comment by rootzoll** [comment]
Once refactored - it would be a candidate to add auto-unlock to the WebUI system settings in a v1.8.1

**Comment by rootzoll** [comment]
Also see note here: #2762

**Comment by rootzoll** [comment]
Also see: #4164

**Comment by rootzoll** [comment]
OK PR waiting #4752

**Comment by rootzoll** [comment]
PR merged
