### ISSUE TITLE
change "cash out" to another term

### ISSUE THREAD

**Issue by nyxnor** [raspiblitz/raspiblitz#2358]
cash out meaning ([source](https://www.merriam-webster.com/dictionary/cash%20out)) -> to convert (noncash assets) to cash. How to use cash out in a sentence.

You can find it in BBcashoutWallet.sh and 99lightningMenu.sh

Another term because Im open to suggestions to rewrite those files:
* withdrawal ([source](https://www.merriam-webster.com/dictionary/withdrawal)) -> removal from a place of deposit or investment
* other

**Comment by rootzoll** [comment]
I think "Withdraw All Funds" is the the basic idea of this feature. Would that work as a replacement?

**Comment by openoms** [comment]
ACK
In c-lightning the command is literally:
`lightning-cli withdraw [address] all`

**Comment by rootzoll** [comment]
This was alrteady fixed in previous releaes. Closing issue.
