### ISSUE TITLE
Add Spanish Support Chat to Website/Documentation

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2368]
https://twitter.com/RaspiBlitz/status/1407460616575631366

**Comment by nyxnor** [comment]
https://t.me/raspiblitz
https://t.me/raspiblitz_DE
https://t.me/raspiblitz_es
https://t.me/raspiblitz_IT
https://t.me/Raspiblitz_RU

**Comment by rootzoll** [comment]
OK doc & website updated. Closing issue.
