### ISSUE TITLE
RTL auth & config

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#238]
The documentation is updated.
RTL.conf is required on the RTL root folder for the app to work now.
Check for what is needed to make it run and maye use/set password B to improve auth.

**Comment by zer0trst** [comment]
Guessing this is why I cannot login to RTL webui?

I go to put my password in and the login button and every other button on the page doesn't work except "Clear". 

Is there a guide somewhere on doing this, cannot find in the documentation?

I Tried putting the macaroon and lnd.conf paths into RTL.conf as directed over at https://github.com/ShahanaFarooqui/RTL but this just crashed the server, couldn't load the page at all even after reboot.

**Comment by zer0trst** [comment]
So now I also have an issue with Zap wallet not connecting to node which I didn't have a problem with at all until installing RTL.

Zap responds with

     Unable to connect to host: Failed to connect before the deadline

I have removed RTL and done a complete shut down and reboot but still having the same problem.

Any direction will be appreciated

Thanks

**Comment by RolfHodl** [comment]
Login into your node
go to the terminal
go to path /usr/local/gocode/bin/
execute ./zapconnect -j
copy paste this into your app.

Hope this helps.

**Comment by zer0trst** [comment]
Thanks @CryptoSigmund All that gives me is a whole bunch of cipher and my IP address at the end. No where I can really put that?


Ever since installing (and now removed) RTL, This is what Zap wallet gives me when I go to try and connect to my node on my local network. Prior to installing RTL (which didn't work and I removed - see above) I could connect to Node through Zap fine through local network.. 

![image](https://user-images.githubusercontent.com/46293453/50726497-bd778900-1159-11e9-8de8-51baa471c184.png)

**Comment by RolfHodl** [comment]
This whole cipher is for the ios app when you dont use scan. Instead use paste but copy this thing in the first place ;).

But I can see from your screenshot you are talking about the desktop app. So maybe it is possible that rtl changed the tsl.cert . Try to download it again and replace it on your pc.

The modification on the tls.cert also occurs when you do the "Router AutoNAT" on Services.

Hope the ip is from your local lan to avoid problems with double nat and some other things when you connect from the outside.

Please let my know if it helps.

**Comment by fluidvoice** [comment]
> This whole cipher is for the ios app when you dont use scan. Instead use paste but copy this thing in the first place ;).
> 
> But I can see from your screenshot you are talking about the desktop app. So maybe it is possible that rtl changed the tsl.cert . Try to download it again and replace it on your pc.
> 
> The modification on the tls.cert also occurs when you do the "Router AutoNAT" on Services.
> 
> Hope the ip is from your local lan to avoid problems with double nat and some other things when you connect from the outside.
> 
> Please let my know if it helps.

OMG, this is so complicated and non user-freindly. TLS cert's, macaroon files, etc.  A nightmare to configure all this stuff.  Lightning needs MUCH more simplification for mass adoption.

**Comment by zer0trst** [comment]
@fluidvoice Agree, Joe public struggle with IP let alone let alone TLS certs and macaroons but realistically I also don't see Joe Public having any interest in running their own node either.

@CryptoSigmund 
> 
> 
> This whole cipher is for the ios app when you don't use scan. Instead use paste but copy this thing in the first place ;).
> 
> But I can see from your screenshot you are talking about the desktop app. So maybe it is possible that rtl changed the tsl.cert . Try to download it again and replace it on your pc.
> 
> The modification on the tls.cert also occurs when you do the "Router AutoNAT" on Services.

Thanks yes I am talking about desktop. Sorry I should have stated desktop app though I am having the same issue with the iOS app as well.

I did think that RTL may have modified the tls.cert and tried getting new copy off the server and copying to my local machine but this didn't fix it unfortunately..

> Hope the ip is from your local lan to avoid problems with double nat and some other things when you connect from the outside.

When I run zapconnect -j I get this

      {"c":"MIIB+TCCAZ+     **SOME CIPHER**   =","m":"     **MORE CIPHER**     =
      =","ip":"**My External IP Address??**:10009"} 

It shouldn't be reporting my external IP should it? I am only trying to connect zap over local network and my node actually runs behind TOR. Could this be a NAT issue as you mention or is it normal for zapconnect -j to feed back my external IP?

**Comment by Smiggel** [comment]
I have the same problem. RTL was installed. It did not work and could not access it on port 3000. I removed it and noticed that I could no longer use zap wallet to connect to my node. I use the internal IP address to access it. I don't allow external access.

So, I tried to re-connect it with a new scan. When I use the menu to connect a mobile wallet I see the confirmation message that I only want to allow local access. No matter what It will no longer connect.

When I copy/paste the output of zapconnect -j it used my external ip address. Even with a portforward in the firewall it will still not connect to my node. So seems that something is wrong with the cert and macaroon files after the RTL installation.

I run the node on a Raspberry Pi btw. :-)

**Comment by Smiggel** [comment]
I looks like the LND config is update? In my case the line rpclisten=0.0.0.0:10009 was suddenly disabled. When I uncomment it, it all works fine again.

**Comment by zer0trst** [comment]
My LND conf didn’t change to make rpclisten commented, I suspect RTL changed rpclisten to `0.0.0.0:10009` from `localhost:10009` which is the reason why `zapconnect -j` gives me my external IP.  

I’m only trying to connect zap locally so I have tried changing it back to `rpclisten=localhost:10009` and restarted lnd but it has not generated new cert, key and macaroon, in doing this i notice I also no longer have a tls.key file in admin/.lnd ?

This is why I’m trying to figure out best way to generate new cert, key and macaroon in my post here: https://github.com/rootzoll/raspiblitz/issues/251

I see there are a couple of responses in there now, I will give those things a try when I get time and report back.

Thanks


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zer0trst** [comment]
Still have the issue after generating new tls.cert and still missing tls.key?

**Comment by rootzoll** [comment]
I updated the RTL for the next release so that it will automatically setup the RTL.conf ... using password B to login. Tests looking good. (will be part of next release)

During the install of RTL the the LND-RPC got deactivated due to an earlier bug. This looks OK now - so I removed the deactivation: RTL and ZP should now be able to run together at the same time.

Connecting ZAP in general is part of another issue: #235

So the basic RTL auth&conf is implemented. The rest is up for testing, please report on new issues ... will close this for now.
