### ISSUE TITLE
error on search address in mempool

### ISSUE THREAD

**Issue by GabrielRCL** [raspiblitz/raspiblitz#2381]
I can't search for any address in the mempool, it always gives this error:
Error: Connection to server lost, please retry

this error only happens with addresses. (blocks and transactions I can search normally)

DEBUG:
https://termbin.com/3kyf

![image](https://user-images.githubusercontent.com/68721111/123528791-cdd0a500-d6c0-11eb-9e10-999048d9cacb.png)

**Comment by openoms** [comment]
You need to have the Electrum Server: Electrs installed to search addresses. Give it a day to build the index and try again.

**Comment by nyxnor** [comment]
It is synced, he has eletrs, I dont know what the problem is tho.
```
Jun 27 00:46:03 raspberrypi electrs[1764]: 2021-06-27T00:46:03.217+01:00 - INFO - best=0000000000000000000526132e9400bcad0e912014c2ab98b8a4273ca6209fbe height=688930 @ 2021-06-26T23:45:35Z (1 left to index)
```

**Comment by openoms** [comment]
Try a full restart first of all.

**Comment by GabrielRCL** [comment]
I Reboot in my raspiblitz and now the error is this
![image](https://user-images.githubusercontent.com/68721111/123533661-75fc6300-d6ed-11eb-836b-1fd4f6e9e5d8.png)

**Comment by openoms** [comment]
we use 1000 as a limit: https://github.com/rootzoll/raspiblitz/blob/a22589c86109d56ecc1e1aca7abb214c7e9189c7/home.admin/config.scripts/bonus.electrs.sh#L311

Can be edited in : `/home/electrs/.electrs/config.toml` , but first try some other address.

**Comment by GabrielRCL** [comment]
thx :)
