### ISSUE TITLE
Changing the ALIAS in lnd.conf does not change name when using punctuations

### ISSUE THREAD

**Issue by litux** [raspiblitz/raspiblitz#2386]
Changed Raspiblitz Node Alias in lnd.conf and restarted the lnd service 
Want to use punctuations there (Like this: PLEBNET.org-NAME) The punctuation and - do not get picked up unfortunately 
How to solve this?

**Comment by openoms** [comment]
edit the lnd.conf directly from the SYSTEM menu or:

`sudo nano /mnt/hdd/lnd/lnd/conf`

**Comment by litux** [comment]
I did this initially directly on the command line and restarted lnd Took some time to pick this up as it seems, can see it now in the emboss.space site In the terminal "raspiblitz" Menu it isn't picked up though, the Status screen title still without punctuation and -

**Comment by openoms** [comment]
special characters are filtered to not cause problems in the scripts. See: https://xkcd.com/327/

Can try editing the hostname in  `/mnt/hdd/raspiblitz.conf`. Put the string between single quotes: '

**Comment by litux** [comment]
That did the trick in the terminal, tnx
