### ISSUE TITLE
raspiblitz stuck on: *** Test if chainnetwork is ready ... ***

### ISSUE THREAD

**Issue by rolandbitcoinspot** [raspiblitz/raspiblitz#239]
Hi,

my raspiblitz is tuck on the following error message. *** Test if chainnetwork is ready ... *** (see image)
device is online and has an internet connection as far as i can see. had VPN on but shut that down also.

![image](https://user-images.githubusercontent.com/7946176/50595993-f3d7ae80-0ea2-11e9-8093-23bf38df1d4f.png)

**Comment by rootzoll** [comment]
Either this is some older version of raspiblitz or did you copy over your own blockchain from another computer?

**Comment by fluidvoice** [comment]
If you ever started up bitcoind using SSH the blockchain DB can get into a state where the files are owned by the user "admin" instead of the user "bitcoin".  I had some problems because of this. And to fix it I had to use the command `chown` to recursively change all the files rights to `bitcoin:bitcoin`.  I don't remember the exact syntax I used. See the man page for `chown`. Note, performing these two commands should show nothing if your blockchain DB is correct:
$ `ls -al /mnt/hdd/bitcoin/blocks | grep admin`
$ `ls -al /mnt/hdd/bitcoin/chainstate | grep admin`

**Comment by rolandbitcoinspot** [comment]
> If you ever started up bitcoind using SSH the blockchain DB can get into a state where the files are owned by the user "admin" instead of the user "bitcoin". I had some problems because of this. And to fix it I had to use the command `chown` to recursively change all the files rights to `bitcoin:bitcoin`. I don't remember the exact syntax I used. See the man page for `chown`. Note, performing these two commands should show nothing if your blockchain DB is correct:
> $ `ls -al /mnt/hdd/bitcoin/blocks | grep admin`
> $ `ls -al /mnt/hdd/bitcoin/chainstate | grep admin`

Hi 

> Either this is some older version of raspiblitz or did you copy over your own blockchain from another computer?

I reinstalled the microsd card, the bc files were probably still there from the previous install. any steps i can take in this instance ?

**Comment by fluidvoice** [comment]
> I reinstalled the microsd card, the bc files were probably still there from the previous install. any steps i can take in this instance ?

As I said you need to check the file rights with the `ls` commands I gave and change them to `bitcoin:bitcoin` with the `chown` command if they are wrong.

**Comment by rolandbitcoinspot** [comment]
Thanks for your reply, checked the ownership, no problem there it seems.
I guess the problem is that i did not format my HD when i installed the new raspiblitz image,
Can i format the HD anyway and start the setup process over  without having to reinstall the image ?

**Comment by fluidvoice** [comment]
> Thanks for your reply, checked the ownership, no problem there it seems.
> I guess the problem is that i did not format my HD when i installed the new raspiblitz image,
> Can i format the HD anyway and start the setup process over without having to reinstall the image ?

Yes I think so. try this from SSH shell:
`sudo umount -l /mnt/hdd`
`./30initHDD.sh`

**Comment by rootzoll** [comment]
@fluidvoice To automatically fix that onwership problem of blockchain data I added a I chown line into the bootstrap - getting executed on every startup - just in case for the future.

@rolandbitcoinspot I closing this issue for now. Please post if you get stuck again at that spot.
