### ISSUE TITLE
Unit bitcoind.service could not be found.

### ISSUE THREAD

**Issue by Tyson-Smiter** [raspiblitz/raspiblitz#2390]
Finally finished downloading the blockchain from a trusted laptop node. Raspiblitz initially said that bitcoind service was running, but after an hour wait, bitcoind service is NOT running.

Should I try to restart everything from scratch again or is there a way I can salvage/debug this?

Link to error logs:
https://termbin.com/bkpg

![bitcoindservice not be found](https://user-images.githubusercontent.com/34221646/124143708-32cd2780-da40-11eb-9fa3-8964801e0252.png)

**Comment by openoms** [comment]
at this point best to reflash the Sdcard. If you have the chain on the disk already it will be picked up during the new new bitcoin node setup.

**Comment by Tyson-Smiter** [comment]
Thank you. Reflashing did the trick
