### ISSUE TITLE
Raspian Lite for custom images?

### ISSUE THREAD

**Issue by raucao** [raspiblitz/raspiblitz#2393]
I'm wondering why [the docs for custom builds](https://github.com/rootzoll/raspiblitz#build-the-sd-card-image) ask to start from a full RaspiOS image instead of the Lite version. Due to an unrelated issue, I connected a display on first boot and noticed that there's a full desktop environment installed on the card. Perhaps there's a reason this is necessary?

**Comment by raucao** [comment]
Just saw #2389, which would make this question obsolete, of course. (And I would also be in favor of the proposal there.)

**Comment by nyxnor** [comment]
Cause there isnt a Liter version that is 64bit, that can support channel db larger than 1GB.

**Comment by raucao** [comment]
I see. Thanks.
