### ISSUE TITLE
Change the command Prompt from $ to ₿

### ISSUE THREAD

**Issue by Psychoshybc1** [raspiblitz/raspiblitz#2400]
just change the $ in the Bash to ₿ for obvious reasons.

**Comment by openoms** [comment]
lol yeah. 
`$` is the Linux convention and not related to the USD and also the sign to reference variables in bash.

Here is how to modify manually: https://stadicus.github.io/RaspiBolt/raspibolt_62_commandline.html

I guess a PR to implement would be welcome.

**Comment by MiguelMedeiros** [comment]
Hey @rootzoll !
Shouldn't this PR be closed?

**Comment by openoms** [comment]
Closing as solved on v1.7.2.
