### ISSUE TITLE
when update torproject.org buster InRelease doesn't support architecture 'armhf'

### ISSUE THREAD

**Issue by Tracachang** [raspiblitz/raspiblitz#2416]
Hello

When updating from terminal:
`sudo apt update`:
`N: Skipping acquire of configured file 'main/binary-armhf/Packages' as repository 'https://deb.torproject.org/torproject.org buster InRelease' doesn't support architecture 'armhf'`

Reading the tor documentation: https://support.torproject.org/apt/tor-deb-repo/

In nano /etc/apt/sources.list I can see:
`deb https://deb.torproject.org/torproject.org buster main`
`deb-src https://deb.torproject.org/torproject.org buster main`

To fix this error, since the tor package repository offers support for arm64 I have modified the file to:
`deb [arch=arm64] https://deb.torproject.org/torproject.org buster main`
`deb-src [arch=arm64] https://deb.torproject.org/torproject.org buster main`

**Comment by nyxnor** [comment]
Duplicate https://github.com/rootzoll/raspiblitz/issues/2357
