### ISSUE TITLE
/home/admin/00infoblitz.sh: line 383: cannot create temp file for here-document: No space left on device

### ISSUE THREAD

**Issue by ronledfordjr** [raspiblitz/raspiblitz#2423]
Hello, I am receiving this message on all four of my nodes.

![IMG_0270](https://user-images.githubusercontent.com/79236343/125938228-6b3d5ddb-235d-4e6f-8b22-c053bc04e72a.jpg)

https://termbin.com/qxdg

**Comment by openoms** [comment]
```
/dev/root      ext4       15G   14G     0 100% /
```
Your root partition (on the SDcard) has filled up.

It is recommended to use a 32 GB card.

You can find out what is taking up space with the linux command:
```
sudo du -hd1 /
```
explore paths going deeped in the directory tree.

Flashing the v1.7.0 image new on your existing card or a new 32Gb card would solve this.

**Comment by ronledfordjr** [comment]
ordering 32GB sd cards. I did reboot all nodes and message went away. Thanks

**Comment by ronledfordjr** [comment]
I have new 32GB cards and I am still receiving error.

I ran sudo du -hd1 / and I posted results.

![Raspblitz out of memory](https://user-images.githubusercontent.com/79236343/136715642-245cc2fd-760a-4d07-9fe5-d31ac571e354.png)

**Comment by openoms** [comment]
`sudo df -h` - this shows block level usage which might be not freed until the application deleted the data is restarted
and
`lsblk` - just shows the mounted devices
are the other useful commands.
Does reboot help? 
There is an great interactive tool to explore disk usage called `ncdu`.
Install:
`sudo apt install ncdu`
run:
`ncdu`
