### ISSUE TITLE
blitz.local

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2424]
To make it easier to call the RaspiBlitz from the local web browser - it should advertise itself as e.g. `blitz.local`

See deatils on this in this article:
https://www.howtogeek.com/167190/how-and-why-to-assign-the-.local-domain-to-your-raspberry-pi/

**Comment by openoms** [comment]
This was a privacy concern discussed in: https://github.com/rootzoll/raspiblitz/issues/819

Need to assume that ISP provided routers are leaking the device names to the ISP.

Currently the base image name is untouched so it would be `raspberrypi.local` or other default if a custom image was used.

**Comment by rootzoll** [comment]
> Need to assume that ISP provided routers are leaking the device names to the ISP.

Yeah I always have that blind spot because I am free to chose my own router - not everybody is priviledged to have.

**Comment by openoms** [comment]
This could be closed depending on the outcome of #2890

**Comment by rootzoll** [comment]
Yepp that also came to my mind ... technically for a `blitz.local` the raspiblitz announces itself on the network. I mean we could go without "blitz.local" by default - because by default the Blitz has a LCD display to tell the user the local IP.

**Comment by rootzoll** [comment]
OK .. deciding to not go with the `blitz.local` to preserve privacy in the local network and possible ISP router. The Raspiblitz has the LCD Display  by default - that gives the IP to enter into browser. - that should work for now. Closing issue.
