### ISSUE TITLE
Line failure caused raspiblitz not booting

### ISSUE THREAD

**Issue by lucbran** [raspiblitz/raspiblitz#243]
Hi,
one week ago installed Raspiblitz and got my full node running. Opened LN channel with some funds. Everything perfect (except still wondering how to set an alias name to the node..).
Yesterday after temporary internet line failure I cannot have raspiblitz booting. System is asking login password and then terminal takes me to root. How to re boot raspiblitz with terminal command?(I switched off and restarted but not working).
Thanks for help

**Comment by fluidvoice** [comment]
sudo reboot

**Comment by lucbran** [comment]
not working.. may be flash drive corrupted now? I am trying to reinstall with new image flash drive following documentation instruction but seems process is aborted when creating mnt/hdd folder as same already exists.. any idea?

**Comment by fluidvoice** [comment]
> not working.. may be flash drive corrupted now? I am trying to reinstall with new image flash drive following documentation instruction but seems process is aborted when creating mnt/hdd folder as same already exists.. any idea?

try running the script `./XXcleanHDD.sh` first.

**Comment by lucbran** [comment]
I tried everything as shown in documentation but no way.. I am now reinstalling with fresh sd card (had to download again all blockchain) and hope to retrieve my previous wallet by the seed.
My only concern this doesnt happen again as I dont wnt to gothrough the same process again.. There must be a way to boot raspiblitz in case of power or line failure and on raspberry shows: enter login for maintenance...
I entered login pwd and was back to root position but no idea how to restart raspiblitz (sudo reboot doesnt work)...

**Comment by fluidvoice** [comment]
so if you unplug it from power and start it back up, what does it do?

**Comment by lucbran** [comment]
when booting, raspberry returns an error asking pwd for maintenanec. I enter password and terminal takes me to root but no idea how to restart raspiblitz ..

**Comment by fluidvoice** [comment]
A picture or screen capture would help

**Comment by lucbran** [comment]
unfortunately i am in the process of reinstalling everything... 
but my question is: has anyone got power failure and was able to reboot raspiblitz without any particular command to be entered?
i am concerned this could happen again..

**Comment by fluidvoice** [comment]
maybe get a UPS with spike/surge protection. Something unusual happened to your system. I've had multiple power failures before and also unplugged the power when running and didn't have any problem with the system coming back up as normal without any special commands entered.

**Comment by lucbran** [comment]
this relieves me! may be I got something wrong then..
ok in the meantime I am still re validating the LN nodes.. when finished will see if i have been able to recover seed and satoshis I had in the previous wallet...(read some users couldnt get them back).
thanks for your help!

**Comment by rootzoll** [comment]
to protect from power outages (UPS) - this enhancement-research-issue could be a good follow up:  #263 ... about the satoshis from the previous wallet see: #266

At the moment when a raspiBlitz is not booting up after a power-outage I would recommend updating with a fresh sd card - its a bit of work, but this way the OS itself at least gets to a clean state and tries to recover your personal data that is on the HDD - for more detail on updating see:
https://github.com/rootzoll/raspiblitz/blob/master/FAQ.md#how-to-update-my-raspiblitz-after-version-098

I will close this issue for now.
