### ISSUE TITLE
Waiting close Channel does not proceed

### ISSUE THREAD

**Issue by clockshell** [raspiblitz/raspiblitz#2442]
Hello!

My node was offline for a while, so ACINQ closed the channel to my node. It is yet still pending to close. ACINQ claims that my node has not picked up the closing confirmation.

So now I am using Raspiblitz 1.7 on this node:

`03eea3e2115e1d2c1038e0826f36dabc1b91d019445c07ecfc3a3b0930f285620e@au4y64saizeewrqp6cizbpegtf5tsgif74p6vi4y72ux2fyl4sczsyqd.onion:9735`

This is the output of lncli pendingchannels:

`     "waiting_close_channels": [
         {
             "channel": {
                 "remote_node_pub":
"03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f",
                 "channel_point":
"aa96601ce517e070563b0aabe964d228fc91098e1d0f0f031d1bce39c30ef443:1",
                 "capacity": "403645",
                 "local_balance": "0",
                 "remote_balance": "0",
                 "local_chan_reserve_sat": "0",
                 "remote_chan_reserve_sat": "0",
                 "initiator": "INITIATOR_LOCAL",
                 "commitment_type": "LEGACY"
             },
             "limbo_balance": "0",
             "commitments": {
                 "local_txid": "",
                 "remote_txid": "",
                 "remote_pending_txid": "",
                 "local_commit_fee_sat": "0",
                 "remote_commit_fee_sat": "0",
                 "remote_pending_commit_fee_sat": "0"
             }
         }
     ]`

How can I get my node to pick up the closing confirmation?

**Comment by clockshell** [comment]
Bump

**Comment by rootzoll** [comment]
Closing because duplicate: #2452
