### ISSUE TITLE
Lightning Pool Bug: Unable to fetch latest batch

### ISSUE THREAD

**Issue by rek79** [raspiblitz/raspiblitz#2447]
I have Lightning Pool up and running.  The account was successfully created.  I was also able to create an ask order.  However, the order is never accepted even though the premium is within market range.  These are the period errors received:
![image](https://user-images.githubusercontent.com/9994060/127177546-59d95f1a-d429-44d5-a0da-25418fda5193.png)
![image](https://user-images.githubusercontent.com/9994060/127205521-0be75d95-691b-4c72-8305-b6549b424f2d.png)
LIT logs:
![image](https://user-images.githubusercontent.com/9994060/127205203-bcc1257c-ced1-41c8-b49d-94585ed5cd5b.png)

**Comment by rek79** [comment]
Are those errors normal and possibly the main reason order is not accepted is due to node tier T0 and offered liquidity only 400,000 sats?

**Comment by openoms** [comment]
Try restarting the service.
`sudo systemctl resatrt litd`

you should see the orders regardless of your node status or funds.

**Comment by rek79** [comment]
I tried restarting litd.  That caused litd service to startup and then fail.  I rebooted which seemed to speed up load times on Thunderhub and refresh on Lightning Pool.  I opening an issue at https://github.com/lightninglabs/pool/issues/274#issue-954287177.  One comment is leading to Tor connection being to slow to respond.  I'm wondering if I can change some settings in config while still keeping TOR only active.

**Comment by rek79** [comment]
Update: I was able to fill a bid order.   I'm still not able to fill an ask order but, from what I hear, this is due to low demand and T1 nodes taking precedence.  I occasionally receive the "unable to fetch batch" warnings but that is probably due to slow Tor connection.  I'll close this issue out.
