### ISSUE TITLE
How to export the blockchain/reuse in other node?

### ISSUE THREAD

**Issue by tifDev** [raspiblitz/raspiblitz#2449]
I have 1 node running, but I want to setup more nodes and I don't want to download the whole blockchain again because my internet is shitty.

**So, how can I export the blockchain from my current node to reuse in other nodes?**

Thank you!

**Comment by rootzoll** [comment]
If the other node is also a RaspiBlitz you can use the COPY over LAN option
during the new node setup.

tifDev ***@***.***> schrieb am Do., 29. Juli 2021, 01:27:

**Comment by tifDev** [comment]
So basically:

**The target machine**, just needs to be connected to the LAN/local network.
**The source machine** will sync the Blokchain to it: MAINMENU > REPAIR > COPY-SOURCE

Thank you, already syncing !
