### ISSUE TITLE
Waiting for DHCP

### ISSUE THREAD

**Issue by MlchaeI** [raspiblitz/raspiblitz#245]
I'm getting a message on my raspberry pi that says "Waiting for DHCP... Not able to get local IP. Will try reboot every".

I was able to connect to my raspberry pi before and had the IP address show up like the pictures in the guide.

**Comment by fluidvoice** [comment]
Switch to static IP on your RPi.  I was having frequent SSH disconnects until I did this.  See the Raspberry Pi forums if you need help. I did this by changing only the **/etc/dhcpcd.conf** file to include this (change for your own router and LAN IP needs):

```
# Example static IP configuration:
interface eth0
static ip_address=192.168.2.101/24
static routers=192.168.2.1 192.168.2.185
static domain_name_servers=8.8.4.4 8.8.8.8 192.168.2.1 2804:cd4:e002:2200:822a:a8ff:fee3:293e

interface wlan0
static ip_address=192.168.2.100/24
static routers=192.168.2.1 192.168.2.185
static domain_name_servers=8.8.4.4 8.8.8.8 192.168.2.1 2804:cd4:e002:2200:822a:a8ff:fee3:293e

```
You will also need to setup your router to expose this IP to the public.
