### ISSUE TITLE
RTL won't install without --unsafe-perm

### ISSUE THREAD

**Issue by inpay** [raspiblitz/raspiblitz#246]
after switching on service RTL install script fails at node_gyp with root file access permission error
Fixed with npm --unsafe-perm

**Comment by fluidvoice** [comment]
log file output showing the error would help other people who hit the same issue.

**Comment by rootzoll** [comment]
At the moment it always uses the latest code of RTL from github on install. I lot of changed in RTL - I have to retest, adapt and then fix to a certain commit/tag/realease on install.

**Comment by rootzoll** [comment]
For the next release I prepared the RTL. First tests show its installs fine.
Marking this issue for final testing before getting closed.

**Comment by rootzoll** [comment]
test new version of RTL - installs without problem. closing issue.
