### ISSUE TITLE
Out of memory: killed bitcoind after 4 hours of syncing (4gb PI 4)

### ISSUE THREAD

**Issue by shadowcpy** [raspiblitz/raspiblitz#2463]
The OOM reaper kills my bitcoind while syncing repeatedly as it runs out of memory.
The `dbcache = 3072` on my 4gb pi 4.
Logs here: https://pastebin.com/EC4iGHx2
(RaspiBlitz v.1.7.0, Node from FULMO)

**Comment by raucao** [comment]
Can you see if swap space is available and used?

**Comment by openoms** [comment]
in the SYSTEM menu edit the bitcoin.conf and reduce the `dbcache` to 1024.

**Comment by rootzoll** [comment]
reducing dbcache for 4GB models with next v1.7.1 release
