### ISSUE TITLE
Raspiblitz keeps launching the menu "Copy blockchain from another latptop/node over lan"

### ISSUE THREAD

**Issue by tifDev** [raspiblitz/raspiblitz#2466]
So I started the copy of the blockchain from my source node to the target node using my laptop to connect to them and launch the commands.

After some time my laptop lost the ssh connection to the RPI's due to idle time.

I connected to the target RPI to check if the copy went well and it launched this menu:

![image](https://user-images.githubusercontent.com/39730484/128632080-b83ce2f1-d464-44ca-b1e5-18934c1af45e.png)

Then I select BLITZ > Keep the blockchain data > then launches this screen:

![image](https://user-images.githubusercontent.com/39730484/128632144-ed012b3c-f9a0-4023-a5ff-a4d1564c8a93.png)

I pressed enter and says that the data is good and restarts.

When I connect again it repeats the same process every time, I'm stuck.

**How can I solve this?**

**NOTE**: The first time I connected to the target RPI after the copy of the blockchain finished it asked also to set Password C _(after hit "Enter" on the second screen attached above)_ to lightning, then created a new Lightning wallet and restarted automatically.

**Comment by openoms** [comment]
I would suggest to restart the process by flashing a new SDcard.

Make sure the bitcoin node is stopped on the source node.

**Comment by tifDev** [comment]
I wanted to avoid doing the whole process again.

**Comment by rootzoll** [comment]
The v1.7.1 will come with a refactored setup process - I hope this will fix such situations. For now I dont think there is a quick fix other then try a fresh sd card and if still stuck format SSD fresh and start sync from the beginning.

**Comment by tifDev** [comment]
In other setup it also gave errors but in the other day it worked and now it's fine. The blockchain copy over Lan it's a bit unstable but yes, let's hope that it will get fixed with next release.

Taking the moment to ask you if I can copy from a PC by connecting both disks in the same computer? https://github.com/rootzoll/raspiblitz/issues/2484

Thank you.
