### ISSUE TITLE
Umbrel migration - unable to unlock LND wallet

### ISSUE THREAD

**Issue by ChadOhman** [raspiblitz/raspiblitz#2468]
Hi there,

I've migrated my Umbrel to RaspiBlitz however I'm not able to unlock my LND wallet. I was told in the migration that changing Password C had failed and to use the default Umbrel password: moneyprintergobrr

Using this password or the password I had intended on using results in a looping screen:
![image](https://user-images.githubusercontent.com/2351/128661213-dc6bab55-9591-4c6d-a507-602793b43c52.png)

I've had the RaspiBlitz online for at least four days and copied over a fresh up to date blockchain on the migration date. I can't seem to figure out what's going on. Any help is greatly appreciated.

Here are my debug logs:
https://termbin.com/rdgk

**Comment by openoms** [comment]
In the logs: Your LND is waiting for the password. 

I think the defaul is:
`moneyprintergobrrr`
with 3 `r`-s

**Comment by ChadOhman** [comment]
Wow, yup.

_walks away in embarrassment_
