### ISSUE TITLE
Screen Won't Go Back From QR Code

### ISSUE THREAD

**Issue by joelklabo** [raspiblitz/raspiblitz#2471]
I'm unable to get my screen to display the status screen again after showing a QR code. Is there a command that can do that?

**Comment by openoms** [comment]
`sudo pkill fbi` or `sudo killall -3 fbi`
to remove the QRcode

`sudo init 5` and `sudo init 3`
to restart the touchscreen

**Comment by joelklabo** [comment]
Great, thank you.
