### ISSUE TITLE
FAIL on RTL install

### ISSUE THREAD

**Issue by kayloehmann** [raspiblitz/raspiblitz#2472]
Hi everyone,

i just downloaded and setup a raspiblitz today.
When trying to enable RTL service i get this error.

![grafik](https://user-images.githubusercontent.com/34281638/129051917-8c2bcb03-821c-4e8f-aead-074094a573fe.png)

Following the proposed solution does not have any effect.

What can i do?

Thanks!

**Comment by kayloehmann** [comment]
I fixed it by installing a new image!

**Comment by ugligatschu** [comment]
Hi, i have the same problem, what was your solution? Greets ugligatschu

**Comment by rootzoll** [comment]
Have you run the command (as shown in the message) on the terminal manually to see the error during install? 

BTW new RaspiBlitz v1.7.1 will be released beginning of October. RTL install will be updated and tested in that version ... so a simple solution would be to wait a bit and then update.

**Comment by ugligatschu** [comment]
Yes i tried it like this:
```
admin@edisraspiblitz:~ $ /home/admin/config.scripts/bonus.rtl.sh on
# making sure services are not running
# INSTALL RTL
nodeJS is already installed
Installed nodeJS v10.24.0
adduser: Der Benutzer »rtl« existiert bereits.
```

**Comment by ugligatschu** [comment]
and btw, newer go asked to set "password D" during installation?

**Comment by rootzoll** [comment]
Hmmm .. something get messed up on your old RaspiBlitz. Best would be to insert a fresh sd card and make a fresh recover. 

About "Password D" ... password D is deprecated - its no longer needed. RaspiBlitz works now just with Password A,B & C.

**Comment by ugligatschu** [comment]
Ok thanks i will do this. 
where do i find how to prepare a „fresh recovery“. Does the thos impact open channels?

**Comment by ugligatschu** [comment]
I got some help and it seems to work again.
`sudo userdel rtl `
And then 
`/home/admin/config.scripts/bonus.rtl.sh on`
worked for me
