### ISSUE TITLE
blitz.datadrive.sh parsing issue when called in 00raspiblitz.sh

### ISSUE THREAD

**Issue by nicolasdiehl** [raspiblitz/raspiblitz#2477]
Recently I wanted to connect via ssh but couldn't, having no display and no funds on it yet I tried restarting with a power reset to see what happened, this happened:

Starting the main menu ...
/dev/fd/63: line 26: unexpected EOF while looking for matching `''
/dev/fd/63: line 28: syntax error: unexpected end of file
loading config data
checking bitcoind - please wait ..
can take longer if device was off or first time

these errors appear every time the status screen updates. I'll do some debugging later but in the meantime you could give me some advice. Thanks.

**Comment by rootzoll** [comment]
The power reset seems to have corrupted some files .. best procedure here to start with a fresh sd card and let the system recover.

**Comment by nicolasdiehl** [comment]
I connect with ssh. I found out that the errors only appear when the function is called within another (not py, sh) file. if i call it directly then there are no errors. could it be that there are some minor piping issues going on with displaying stuff on ssh? will update later with exact location and outputs

i reset everything except blockchain and the errors still exist.

**Comment by rootzoll** [comment]
Can you be more detailed what py-scripts you are calling?

**Comment by nicolasdiehl** [comment]
The chain goes like this:
https://github.com/rootzoll/raspiblitz/blob/v1.7/home.admin/00raspiblitz.sh#L13 calls
`source <(sudo /home/admin/config.scripts/blitz.datadrive.sh status)`
then https://github.com/rootzoll/raspiblitz/blob/v1.7/home.admin/config.scripts/blitz.datadrive.sh#L402 calls
`echo "raidCandidate[${drivecounter}]='${mountoption}'"` which gives the error for me when calling it through 00raspiblitz.shs call
which gets it's output for mountoption from the lines prior.
if i run `lsblk -o NAME,VENDOR | grep "^${disk}" | awk '$1=$1' | cut -d " " -f 2` (like it does for mountoption) it gives this output for me:
```
VENDOR
ASMT
`-sda1
SanDisk'
`-sdb1
mmcblk0
|-mmcblk0p1
`-mmcblk0p2
```
if i call`
sudo /home/admin/config.scripts/blitz.datadrive.sh status` in the terminal directly, 
then the output is:
```
# RASPIBLITZ DATA DRIVE Status

# BASICS
isMounted=1
isBTRFS=0
hddRaspiData=1
isSSD=0
datadisk='sda'
datapartition='sda1'
hddBlocksBitcoin=1
hddBlocksLitecoin=0
hddBytes=1000203091968
hddGigaBytes=931
hddUsedInfo='387G (45%)'
hddDataFreeKB=506262456
hddAdapterUSB='174c:55aa'
hddAdapterUSAP=1

# RAID
isRaid=0
raidCandidate[0]='sdb 28 GB SanDisk''
raidCandidates=1

# SWAP
isSwapExternal=0
```
but if i call my 00test.sh containing:
```
#!/bin/bash
source <(sudo /home/admin/config.scripts/blitz.datadrive.sh status)
```
(just like in 00raspiblitz.sh)
then the output is:
```
/dev/fd/63: line 21: unexpected EOF while looking for matching `''
/dev/fd/63: line 27: syntax error: unexpected end of file
```
There is some error happening while filtering the infos. i don't think there is something corrupted, just that script is parsing it's info the wrong way.

**Comment by rootzoll** [comment]
Thanks for the details ... my best guess is that the `disk` var is empty and this leads to parsing going south. I added a check on disk with `f [ ${devMounted} -eq 0 ] && [ "${disk}" != "${hdd}" ] && [ "${hdd}" != "" ] && [ "${disk}" != "" ]; then` ... but I am not able to test this.

This will be part of v1.7.1 release.

**Comment by nicolasdiehl** [comment]
this did not fix it as my `vedorname` variable is read out as `SanDisk'` somehow, (see above quotes containing it).
the single quotation mark is causing the issue, if i add escaping with sed then it works:
https://github.com/rootzoll/raspiblitz/blob/v1.7/home.admin/config.scripts/blitz.datadrive.sh#L400
`vedorname=$(lsblk -o NAME,VENDOR | grep "^${disk}" | awk '$1=$1' | cut -d " " -f 2 | sed 's/\x27/\x27"\x27"\x27/g')`
this stores it as SanDisk'"'"' which will not throw an error when called with `source` here:
https://github.com/rootzoll/raspiblitz/blob/v1.7/home.admin/00raspiblitz.sh#L13

see this example:
```
admin@raspberrypi:~ $ a='harry'"'"'s'
admin@raspberrypi:~ $ echo ${a}
harry's
```

**Comment by rootzoll** [comment]
Its a good idea to sanatize the vendorname ... instead escaping special characters I added a sed that will strip all non-alphanumeric characters from the string with `sed 's/[^a-zA-Z0-9]//g'` .. that should solve the problem more broadly.

**Comment by rootzoll** [comment]
testing went well with the latest release candidates ... so closing this issue for final v1.7.1 release.
