### ISSUE TITLE
Autonat problem

### ISSUE THREAD

**Issue by eurtnl** [raspiblitz/raspiblitz#248]
Hi there,
I just turned on Autonat in services, but after reboot my RaspiBlitz gets in a loop where i have to unlock LND Wallet over and over.
How can i solve this problem or how to disable Autonat?

**Comment by rootzoll** [comment]
yeah the lnd autonat is still broken
to deactivate manually there is a script to be called:
/home/admin/config.scripts/lnf.autonat.sh off

Am So., 6. Jan. 2019, 12:52 hat Eurt.nl <notifications@github.com>
geschrieben:

**Comment by eurtnl** [comment]
OK, thanks i disabled the autonat

**Comment by rootzoll** [comment]
I reopend the issue as a TODO for the 1.0 release to remove the option from the menu for now. This LND feature seems not ready to have it as an option for people to switch on generally. I will leave the script to switch it on manually for people how wnat to still test it.

**Comment by rootzoll** [comment]
removed autonat from service menu - test if service menu is till working fine

**Comment by rootzoll** [comment]
OK - service menu is tested and fixed.
