### ISSUE TITLE
LCD Display "INVOICE" Err: Invoice no remote capacity

### ISSUE THREAD

**Issue by GregorWedlich** [raspiblitz/raspiblitz#2493]
When i push "INVOICE" on the Raspiblitz LCD Display i become the following Error:

`Err: Invoice no remote capacity`

Anybody has an idea? Channel is open and Raspiblitz V 1.7 installed.

**Comment by rootzoll** [comment]
If you opened a channel fresh then all the sats are on your side of the channel - there are no further sats you would be able to receive --> you have "no remote capacity". There is an easy way to fix this: Spend some sats ;) .. for example donwload a mobile wallet like phoenix or muun and send some sats from your node to that mobile wallet.

**Comment by GregorWedlich** [comment]
Thank you for the explanation, i had then read up a bit and that also understood because I have then carried out my first transaction and already the channel was no longer empty.
