### ISSUE TITLE
70initLND.sh failed

### ISSUE THREAD

**Issue by berlinxray** [raspiblitz/raspiblitz#2494]
Generating new Wallet ....
Traceback (most recent call last):
  File "/home/admin/config.scripts/lnd.initwallet.py", line 7, in <module>
    import grpc
ValueError: source code string cannot contain null bytes
FAIL!! -> MISSING seedwords data - but also no err data ?!?
CHECK output data above - PRESS ENTER to restart 70initLND.sh

**Comment by openoms** [comment]
not sure what happened there.
Best to try to reflash the SDcard to restart the setup process.

**Comment by cstenglein** [comment]
@berlinxray  Do you still have this issue?

Closed for now, if it still appears, please re-open
