### ISSUE TITLE
use `trap` to make sure tempfiles are deleted on any kind of script exit

### ISSUE THREAD

**Issue by m00ninite** [raspiblitz/raspiblitz#2498]
If the yield generator is running, the raspiblitz status screen will dump the joinmarket maker info into /tmp every few seconds. Eventually this fills up the SD card, causing the device to crash (a month or 2 of uptime). The blitz can only be recovered if you pop it into another computer and nuke /rootfs/tmp.

There are thousands of files like this:
![image](https://user-images.githubusercontent.com/80651189/130827076-1c8c07c7-11f0-4732-aab2-bfbb42b7f476.png)

Bug appears to be in [home.admin/00infoBlitz.sh](https://github.com/rootzoll/raspiblitz/blob/fc1d44104bc22d85ebebd7b0d6ee2240722a9edf/home.admin/00infoBlitz.sh#L291)

Proposed solution is to clear the previous temp file when writing a new one. or just reusing the same one. This does bring up another question though.. should /tmp be mounted as a RAM disk rather than to the SD card? Writing tmp files to the SD can cause a lot of thrashing on an already fragile storage medium.

**Comment by openoms** [comment]
Thanks, should create the tempfile in `/dev/shm` as in the rest of the scripts.

**Comment by openoms** [comment]
Will use `trap` to ensure the tempfiles are deleted as in: https://www.putorius.net/mktemp-working-with-temporary-files.html#cleanup-of-residual-data

**Comment by rootzoll** [comment]
@openoms whats the status on this for v1.7.1?

**Comment by openoms** [comment]
Changed in most places focusing on the important ones like passwords or the ones building up (running often). Can be closed.
