### ISSUE TITLE
Prebuilt Raspiblitz SSH Login issue

### ISSUE THREAD

**Issue by TheDawsers** [raspiblitz/raspiblitz#2501]
Hi. 

New prebuilt unit arrived today - new to this, obviously! :)  Have connected the unit to the router & powered up.  Start screen appears telling me to login to our Raspiblitz - have tried using the Command Prompt on Windows (didn't work!) and also tried to use PuTTY - entered the IP address for the SSH connection, but I get the following message:

'Remote side unexpectedly closed the connection'

Have tried to use the 32 bit & 64 bit versions of PuTTY, but no luck with either!

Have pinged the IP address, which returned a successful message, so I am now at a loss as my computer skills are a bit dated.....hence why I bought a pre-built unit.....

Any help for how to activate the login would be greatly appreciated so that I can complete the setup process and get my node active.

Many thanks

Carl

**Comment by maximlomans** [comment]
...don't panic, it's typical behavior, you haven't created any ssh-keys yet - access your pi via keyboard +hdmi - and run ssh-keygen -t rsa and ssh-keygen -t dsa ..you'll get reply asking where you want the files stored -just go with default location, basically just hit enter , unless you want to passphrase protect them in which case you enter one - typically i do so with dsa cert only but it's up to you - reload ssh server sudo service ssh reload and try putty again - see what that gives 
you're welcome ; )

**Comment by TheDawsers** [comment]
Thanks - so I will need a USB/HDMI keyboard? 

This unit was supposed to be 'plug & play', which is why we paid for the pre-built unit :(  I even tried the Microsoft PowerShell option, but that didn't work either...

Thank you for your advice - will get a keyboard & try your recommendations.

Cheers

**Comment by maximlomans** [comment]
come on, you must have a keyboard and a screen somewhere in the house ... just plug em in that way you have direct access to your pi - afterwards you can ssh to it from wherever

**Comment by maximlomans** [comment]
also maybe if you are using a diff keyboard to the default US you'll have to edit the config file which is at /etc/default/keyboard and replace "us" with whichever keyboard you have that is just for direct access , putty will adjust automatically

**Comment by TheDawsers** [comment]
Only laptops - no separate keyboards :(

**Comment by maximlomans** [comment]
..okay, rdp and vnc .. google them, it's better than despairing ... they might give you yet another option to access .. cant lose either way you'll learn something new which will come handy - 

honestly, i think you bit off more than you can chew, right now - if ssh gives you such tremors, than i don't see how taking responsibility for a Bitcoin Node is gonna help you sleep better or improve your finances - there are serious penalties for screwing up on The Blockchain .. You sure you're not rushing into this ... take the time to fully grasp at least the basics of both blockchain tech and linux administration ... i was once where you are now, if i had given up i wouldn't be able to ..... well you get the idea 

stay positive and curious the rest will follow - and never just follow anyone's advice before first double triple checking with other opinions

**Comment by TheDawsers** [comment]
We are for sure learning, but have no plans to jump in until we know what we are doing. We have been in the crypto investing field only since last year, so still have a lot to understand :)  

SSH is not stressing us, just annoying that it doesn't just function - no doubt there is a setting somewhere that is messing with things.  We'll get to the bottom of it soon - will let you know :)

**Comment by rootzoll** [comment]
Please flash a fresh raspiblitz image onto the sd card and try again to login per SSH - it seems like that on transport some sd cards get damaged and SSH logins fail.

How to download the sd card image and flash it you find instructions & links here:
https://github.com/rootzoll/raspiblitz#downloading-the-software

**Comment by maximlomans** [comment]
he's the boss, can't argue with him, ....but i still think it odd that a supposedly corrupt sdcard manages to boot up but fails to start an ssh service. : o
...having said that, i do not have a raspiblitz setup, i 've installed LND and all the modules Lndconnect, BTCPay, Zap on win7 etc  manually but got stuck here and there, so i came over to drool on what could' av been : (
 
 I still think you should get your self a small portable keyboard , you'll be needing it anyways now that you are the proud owner of a raspberrypi - i bought a Rapoo for 19eu,  a few years back it came in like a cherry on top of all my pies : p

**Comment by TheDawsers** [comment]
> Please flash a fresh raspiblitz image onto the sd card and try again to login per SSH - it seems like that on transport some sd cards get damaged and SSH logins fail.
> 
> How to download the sd card image and flash it you find instructions & links here:
> https://github.com/rootzoll/raspiblitz#downloading-the-software

Thank you - will try it today & let you know.  If this is the case, then it might be a good idea to send the SD Card seperately as they are quite difficult to get out of the pre-built unit.

**Comment by TheDawsers** [comment]
> he's the boss, can't argue with him, ....but i still think it odd that a supposedly corrupt sdcard manages to boot up but fails to start an ssh service. : o
> ...having said that, i do not have a raspiblitz setup, i 've installed LND and all the modules Lndconnect, BTCPay, Zap on win7 etc manually but got stuck here and there, so i came over to drool on what could' av been : (
> 
> I still think you should get your self a small portable keyboard , you'll be needing it anyways now that you are the proud owner of a raspberrypi - i bought a Rapoo for 19eu, a few years back it came in like a cherry on top of all my pies : p

I agree - also if this is a known issue, then surely it would be a good idea to remove the SD card from the unit before shipping.

In any case I will be getting a small portable keyboard :)

**Comment by TheDawsers** [comment]
Seems that the SD card was corrupt - flashed the fresh raspiblitz image to the SD, and immediately login starts working & setup is progressing :)

Thanks @rootzoll for the advice.  It was not a difficult process, but getting the SD card out was not easy from the case as the space is very small.  Also if it is a known issue, then maybe the SD card should be packed seperately, but prepped and ready to go......

**Comment by maximlomans** [comment]
Aaah - ok, glad to hear it - i never read in which state your raspiblitz was in when ssh conn failed - i assumed it was up and running and that either the ssh server wasn't active or it wasn't yet configured etc - 
I noticed the documentation is broad on this project and it covers pretty much everything . i suppose you can close this issue now.
enjoy the Lightning ; )
