### ISSUE TITLE
v1.7 Installing Lightning Terminal results in 502 Bad Gateway for RTL

### ISSUE THREAD

**Issue by benjamin-wilson** [raspiblitz/raspiblitz#2503]
After installing Lightning Terminal though the services menu, visiting the RTL https address results in 502 and http address won't connect.

**Comment by benjamin-wilson** [comment]
Looks like the RTL service was simply stopped during the install. 

```
Aug 27 20:48:22 raspberrypi systemd[1]: Stopping RTL daemon...
Aug 27 20:48:22 raspberrypi systemd[1]: RTL.service: Main process exited, code=killed, status=15/TERM
Aug 27 20:48:22 raspberrypi systemd[1]: RTL.service: Succeeded.
Aug 27 20:48:22 raspberrypi systemd[1]: Stopped RTL daemon.
```

Fixed with

`sudo service RTL start`

**Comment by openoms** [comment]
RTL needs restarting due to the Loop integration working inside LiT.
Should be double checked to be restarted if stopped.

**Comment by rootzoll** [comment]
OK RTL is now restarted when LIT gets installed. This will be part of v1.7.1rc2 for final testing.
