### ISSUE TITLE
Swap Error

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2504]
I had "Read-error on swap device" on two of my test machines ... maybe my power net had a glitch but keeping an eye on this until final release. The `_provision_.sh` script is switching swap on (created on SSD) but those devices never restarted after that going thru sync. Maybe keep for v1.8 in mind, that the WebUI needs to be able to handle reboots during setup.

**Comment by rootzoll** [comment]
V1.7.1 has now a `final setup reboot` this should mitigate the problem with a fresh swap on the HDD

**Comment by openoms** [comment]
more here: https://github.com/rootzoll/raspiblitz/issues/2859
