### ISSUE TITLE
Error Update Mempool

### ISSUE THREAD

**Issue by GabrielRCL** [raspiblitz/raspiblitz#2506]
I'm not able to update the mempool, could someone help me?
![image](https://user-images.githubusercontent.com/68721111/131227761-c18e93c4-13a0-4e9c-a776-a8222dc2b509.png)

i use git -c but nothing happens
![image](https://user-images.githubusercontent.com/68721111/131227768-b9c1f5da-b229-4595-ae42-b2e3d01988e1.png)

i change cp to mv in:
https://github.com/rootzoll/raspiblitz/blob/79ccb8d3433a59ee8268b458436dbb4f3a824aa3/home.admin/config.scripts/bonus.mempool.sh#L358
but not working too

**Comment by nyxnor** [comment]
Try this
```bash
sudo cp /home/mempool/mempool/mempool-config.json /home/admin
pinnedVersion="v2.1.2"
sudo -u mempool git -C /home/mempool/mempool reset --hard $pinnedVersion
bash config.scripts/bonus.mempool.sh update
```

**Comment by GabrielRCL** [comment]
> Try this
> 
> ```shell
> sudo cp /home/mempool/mempool/mempool-config.json /home/admin
> pinnedVersion="v2.1.2"
> sudo -u mempool git -C /home/mempool/mempool reset --hard $pinnedVersion
> bash config.scripts/bonus.mempool.sh update
> ```

the directory "/home/mempool/mempool/" was missing the file "mempool-config.json". however, I found it in the directory "/home/admin".
I made a copy using the inverse command:
"sudo cp /home/admin/mempool-config.json /home/mempool/mempool"

but hasn't updated yet, although he says he's updated.

![image](https://user-images.githubusercontent.com/68721111/131558830-18ed9a8d-76fb-4710-a6b1-8edd3b9cd5f2.png)

how to share my debug.log?

**Comment by nyxnor** [comment]
leave this open, it is not fixed yet. also permission ddenied is because of the user you are running on

**Comment by rootzoll** [comment]
v1.7.1 will come with the latest mempool v2.2.2

**Comment by GabrielRCL** [comment]
> leave this open, it is not fixed yet. also permission ddenied is because of the user you are running on

it seems that it was solved yes, it returned some errors but it worked.
