### ISSUE TITLE
Wallet recovery failed with AttributeError: 'bytes' object has no attribute 'encode'

### ISSUE THREAD

**Issue by lessless** [raspiblitz/raspiblitz#2507]
Hi,

I'm trying to run a recovery script to restore a wallet:  `lnd.initwallet.py scb mypassword  “twenty four words of seeds“ 2021-08-29-channel.backup`

but it throws an error: 

```
# OK SCB file exists
# *** RECOVERING LND WALLET FROM SEED + SCB ***
b'65...ab'
Traceback (most recent call last):
  File "/home/lnd/bin/lnd.initwallet.py", line 281, in <module>
    main()
  File "/home/lnd/bin/lnd.initwallet.py", line 273, in main
    scb(stub, wallet_password, seed_words, seed_password, file_path_scb)
  File "/home/lnd/bin/lnd.initwallet.py", line 120, in scb
    channel_backups=scb_hex_str.encode()
AttributeError: 'bytes' object has no attribute 'encode'
```

I'm running script with `Python 3.7.3`, if I add `print(sys.version)` just before the `main()` then I can see

```
3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0]
```

right on the top of the output 

Also, can you please advise on how to restore the wallet created by RaspiBlitz without that script?

Thanks.

**Comment by lessless** [comment]
cc @frennkie (due to https://github.com/rootzoll/raspiblitz/pull/841/files#diff-be8867ca998cffd1217366230c977acda82fdf7c693d6d47615d7faa16173af7R123)

**Comment by openoms** [comment]
The script is not designed to be run outside of the the raspiblitz environment.

Follow the https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md#recovering-using-scbs on any system running LND:

`lncli create -multi_file=channel.backup`
