### ISSUE TITLE
Cannot fund LNbits

### ISSUE THREAD

**Issue by benjamin-wilson** [raspiblitz/raspiblitz#2510]
After installing LNbits, I cannot fund a wallet because "self-payments not allowed". I don't see a way to fund the lnbits wallet without a second node.

**Comment by rootzoll** [comment]
Yeah ... my old workaround is to install a mobile wallet - send there and then send back into LNbits.

@arcbtc is there a easier way in the meanwhile?

**Comment by openoms** [comment]
This is an LNBits limitation for now. Keep an eye on their developments. Closing.

**Comment by ZeroPointEnergy** [comment]
Just stumbled over this problem. It's possible without a second wallet by looping a payment with the CLI `lncli payinvoice --allow_self_payment <invoice>`

**Comment by rootzoll** [comment]
I marked this for a later release to check what options developed in the meantime.

**Comment by rootzoll** [comment]
Closing this one in favor of new #4192
