### ISSUE TITLE
Unnecessary System Reboot After Setting Accept-Keysend Parameter

### ISSUE THREAD

**Issue by stealth2600** [raspiblitz/raspiblitz#2511]
When setting the accept-keysend parameter from the Raspiblitz menu, the system is forced to do a complete reboot. This is unnecessary as LND only needs to be restarted. Can this be updated to restart LND instead of reboot the entire system? Thanks for the help!

**Comment by rootzoll** [comment]
OK changed. Will be part of v1.7.1rc2. Closing issue.

**Comment by stealth2600** [comment]
> 
> 
> OK changed. Will be part of v1.7.1rc2. Closing issue.

Thank you! I greatly appreciate all of your work on Raspiblitz, its awesome!
