### ISSUE TITLE
'nutc': unknown terminal type.

### ISSUE THREAD

**Issue by kelevra8** [raspiblitz/raspiblitz#2514]
Hi everyone, I stuck already in the really beginning, so I would appreciate your help. After I try to connect via win10 command window with ssh @ adminIP and password the following message appears right after "Starting the main menu...": 'nutc': unknown terminal type.
Do I need anonther terminal version? I would be thankful for any advices.

**Comment by rootzoll** [comment]
I am not a windows user .. heard that `PowerShell` should work well to login into RaspiBlitz.

**Comment by kelevra8** [comment]
PowerShell caused similar issue. I was able to connect over secure shell by using the freeware putty.
Thank you. You can close the issue.
