### ISSUE TITLE
node disconnected and prevented connections/logins

### ISSUE THREAD

**Issue by Tharika1990** [raspiblitz/raspiblitz#2518]
Hello, can someone please assist me to understand a recent issue that I've had?

I'm using an RPI 4 and it was running Raspiblitz like a charm for a few weeks, then all of a sudden it was no longer accessible by other devices on the network (despite the ethernet LEDs indicating a connection).

I tried connecting a screen to troubleshoot it (I'm not using an LCD screen and am happy to run it headless). However, when booting up it was persistently stuck on [ OK ] Started Load/Safe RF Kill Switch Status.

I then attempted a few fixes suggested on various forums, such as Alt + F2 (which just brought up a black screen), and tried logging in by appending cmdline.txt with " init=/bin/bash", it allowed me to log in but with the following error:

bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
root@(none):/#

I assumed it might be a hardware fault, to test this I flashed a new SD card with the Raspiblitz image and ran through the setup again with the old external harddrive connected. The startup wizard detected the old configuration and rebuilt, including maintaining all the channels again, very impressive!

I now have a functioning Raspiblitz again, however I'm hoping to avoid this issue in the future. I there any way to troubleshoot what happened in order to mitigate against it happening again?

Have others used good scripts / monitoring tools to monitor for outages / operational issues?

Last but not least, I tried to donate to the project but the tallyco.in portal seems to be down, is there another way to donate using my Raspiblitz node?

**Comment by cstenglein** [comment]
@Tharika1990 is this still relevant? Closing for now, if it's still relevant, please re-open
