### ISSUE TITLE
stuck at 94% 

### ISSUE THREAD

**Issue by fritzschoff** [raspiblitz/raspiblitz#253]
I get this screen for 2 days now... And it is always something about 94%... Any idea what is wrong?
![bildschirmfoto 2019-01-08 um 11 27 03](https://user-images.githubusercontent.com/39312833/50825061-55cb6480-1338-11e9-8f1a-76dfcc00cd8a.png)

**Comment by rootzoll** [comment]
Try a reboot. Of this screen - press CTRL-C or CTRL-Z and then write on terminal:
`sudo shutdown -r now`

**Comment by fritzschoff** [comment]
I did, but it won't work. I will setup everything from beginning.

**Comment by fluidvoice** [comment]
you did not show any of the debug logs so no way anyone can help you.
run this from an SSH shell and post the output:
`sudo tail -n 100 /mnt/hdd/bitcoin/debug.log`
