### ISSUE TITLE
Credit Scoring System For Peers

### ISSUE THREAD

**Issue by originaljeremy** [raspiblitz/raspiblitz#2530]
Long term, I see the need for a node operator to evaluate the creditworthiness of peers, and based on that evaluation, offer partial funding in a dual-funded channel. 

example:

A node is determined to have a creditworthiness of 0 (no history positive or negative), and my node might have an outstanding offer to fund 5% of a dual funded channel.

With positive credit, my standing offer might increase to a certain maximum percent; and with negative credit, I might remove the 5% offer, or even ban the peer altogether.

Creditworthiness might be based on the 'connectedness' (or other metrics) of the peer, the frequency of its fee changes, or even information that might be gathered from public sources - i.e. if it advertises a twitter account from one of its claimed profiles on a widely-used LN explorer, you could assign credit factors based on follower count, engagement statistics, sentiment analysis of replies, etc. Linked websites could be awarded score modifiers based on alexa rank. Of course, the operator could arbitrarily modify scores, and offers of credit could be gamified in various ways. 

I imagine all this would need to be built on top of a basic CRM that would be a service on the Blitz. It would be awesome if it integrated with the popular explorers like Amboss, 1ML, etc... so that publicly available information from their servers could be automatically populated inside the CRM. 

Is this an idea worth pursuing? Is anyone working on something like this and I don't know it?

**Comment by openoms** [comment]
It is an interesting idea and could be self hosted on a raspiblitz, but the development is very much  outside of the scope of this project.

Similar is closed source  BOS Score: lightningnode.info/advanced-tools/bosscore
and building on that the https://terminal.lightning.engineering/#/ also from Ligthning Labs.

Some open source, alternative system and social scoring would be best attached to a Lightning explorer project as you mentioned amboss.space and 1ml.com.
