### ISSUE TITLE
Activating LND wallets as secondory option when running C-Lightning

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2534]
To be tested:

- activate LND mainnet in Settings menu, answere PassordC setting & get shown seed words
- activate LND testnet and check seedwords in seedwords.info file

**Comment by openoms** [comment]
Fixing this in https://github.com/rootzoll/raspiblitz/pull/2536 and testing

- [x] activate LND mainnet in Settings menu, answere PassordC setting & get shown seed words
- [x] activate LND testnet and check seedwords in seedwords.info file

**Comment by openoms** [comment]
ok, tests are successful, merging https://github.com/rootzoll/raspiblitz/pull/2536
