### ISSUE TITLE
[Update] Bitcoin Core v22.0.0

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#2540]
Manual update script with PGP verification: https://github.com/openoms/bitcoin-tutorials/tree/master/raspiblitz.updates#v220

WIll record any issues here.

edit: https://twitter.com/openoms/status/1437711892521394176

**Comment by rootzoll** [comment]
Can you also merge this into the build script .. I will do a new build for the 1.7.1RC2 anyway.

**Comment by openoms** [comment]
ok - updated the build script.

the bitcoin.update.sh will need to be refactored due to the divergent verification methods

**Comment by rootzoll** [comment]
OK let me know when ready to test

**Comment by openoms** [comment]
for the custom upgrades we should probably just not allow downgrades below 22 so thee will be only one way to verify.

Alternatively get the user to paste a custom PGP keyID

**Comment by rootzoll** [comment]
Yeah I think thats a fair trade off.

**Comment by giovannizotta** [comment]
I've updated manually with @openoms' script, no problems.

**Comment by SkabbMask** [comment]
Also updated manually with @openoms script :D ran smooth, no problems!

**Comment by openoms** [comment]
https://github.com/rootzoll/raspiblitz/commit/11a67de7cb2970b09d00700e9f8649d0af40a59f

the Bitcoin update script is also changed to use the new community signing process.
Can paste a custom signing pubkey fingerprint with the fallback to W. J van der Laan's.
No support for downgrading below 22.0.

**Comment by rootzoll** [comment]
Worked good in the release candidates ... closing issue for v1.7.1 release.
