### ISSUE TITLE
customized installation

### ISSUE THREAD

**Issue by nyxnor** [raspiblitz/raspiblitz#2543]
installation, not build. Build should be minimal, installation user choice.

### Bitcoin Network should be checklist to select one or more options:
https://github.com/rootzoll/raspiblitz/blob/dev/home.admin/setup.scripts/dialogBlockchainLightning.sh
- [ ] Bitcoin
- [ ] LND
- [ ] C-Lightning
------------
### Chain should be checklist to select one or more options:
https://github.com/rootzoll/raspiblitz/blob/dev/home.admin/config.scripts/network.chain.sh
- [ ] Main
- [ ] Test
- [ ] Signet
------------
### Network should be checklist to select one or more options
https://github.com/rootzoll/raspiblitz/blob/dev/home.admin/config.scripts/internet.tor.sh
- [ ] Public IP
- [ ] tor
- [ ] i2p
------------

**Comment by nyxnor** [comment]
i2p PR will conflict with tor PR because of this https://github.com/rootzoll/raspiblitz/blob/dd94f8cc9b6e15fa46aaca7018a21f20f2dd39d2/home.admin/config.scripts/internet.tor.sh#L58

**Comment by rootzoll** [comment]
For the SSH dialogs checklists are a very bad user experience - it maybe OK for later things like Services and Settings but for Setup I would like to avoid them. Also there are some dependencies ... so you cannot run LND without any Layer1 etc. 

Also now I just made a rework for those setup menus and trying to get a v1.7.1 out of the door. This now starts to reopen the discussion of this process again. Doing this would delay the v1.7.1 for weeks again with all the needed testing. And after v1.7.1 the next goal is the WebUI with v1.8.0 ... earliest point todo a next iteration on the SSH setup process/UI with my resources I can see with a v1.8.1 - which wil be quite far in the future.

**Comment by nyxnor** [comment]
not for this release, 1.8.1 it is.

**Comment by rootzoll** [comment]
For RaspiBlitz I think we stay the way it is right now .. there is a NixBlitz project in the works that will further go down the road of System by Confing.
