### ISSUE TITLE
bitcoind service is NOT RUNNING!

### ISSUE THREAD

**Issue by TheTiny** [raspiblitz/raspiblitz#2544]
I am currently dowloading/verifizing the blockchain.
I currently have difficulties with authentification to unlock the LND Wallet.
I can tell from the logs: "Loading Block Index"
Tail on /mnt/hdd/bitcoin/debug.log tells me its still syncing.
But calling df -h tells me the disc space does not fill up.
I assume there is something wrong. 
```
/home/admin/XXdebugLogs.sh | nc termbin.com 9999
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
https://termbin.com/gcl0o
```

**Comment by nyxnor** [comment]
Hallo, not everybody speaks German so I am susceptible to the translator.
Wait for the blockchain to be fully synced to try to unlock the lnd wallet, lnd needs it that way.
Also, all working fine, it is syncing.

```
*** BLOCKCHAIN SYSTEMD STATUS ***
● bitcoind.service - Bitcoin daemon
   Loaded: loaded (/etc/systemd/system/bitcoind.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2021-09-14 11:16:51 BST; 4h 10min ago
```
```
2021-09-14T14:26:27Z Rolling forward 00000000000000000082dcdfb99c8b663828fd40fd68f343a17f766e1dee9bdc (499641)
2021-09-14T14:26:30Z Rolling forward 0000000000000000003c2cc296d753717135a38cfea6bc3ddba640aac063fb3b (499642)
2021-09-14T14:26:34Z Rolling forward 00000000000000000005869d321a8f2046d1e47f55b97920c9e4bb8a971db40b (499643)
2021-09-14T14:26:37Z Rolling forward 0000000000000000002d429f39afec70c938e888c3417d690bbc85e83529991c (499644)
```

**Comment by TheTiny** [comment]
Thank you for the quick reply @nyxnor!
Thats what I had hoped to hear. Buy if everything works as expected, shouldn't the /mnt/hdd slowly but surely fillup with more blockchain to store?

**Comment by nyxnor** [comment]
yes, just watch the logs
```
sudo tail -fu /mnt/hdd/bitcoin/debug.log
```

**Comment by TheTiny** [comment]
I do! I can tell there is work going on.
I am just irritiated that I dont see changes on the disk space calling "df -h"

**Comment by TheTiny** [comment]
Its running normal again and the disk starts to grow.
Case closed...
