### ISSUE TITLE
mempool & bitcoin 22

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2546]
fix will be in mempool v2.3.0 to be in time for v1.7.1 ... otherwise add workaround as in:
https://github.com/mempool/mempool/issues/778#issuecomment-919194258

**Comment by softsimon** [comment]
Simply adding `deprecatedrpc=addresses` to `bitcoin.conf` solves this.

The getrawtransaction output will then contain both the new and old style of the scripthash datastructure:
```
"address": "tb1qft5p2uhsdcdc3l2ua4ap5qqfg4pjaqlp250x7us7a8qqhrxrxfsqaqh7jw",
"addresses": [
   "tb1qft5p2uhsdcdc3l2ua4ap5qqfg4pjaqlp250x7us7a8qqhrxrxfsqaqh7jw"
],
```

Might be good since this may affect other apps depending on the old getrawtransaction data.
