### ISSUE TITLE
[Update] Electrs v0.9

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#2548]
https://github.com/romanz/electrs/blob/v0.9.0-rc1/RELEASE-NOTES.md

v0.9.0-rc1 is out

it comes with a database format change so will reindex for a few hours.
Will need to see how long it takes in the RPi before it is usable again.

**Comment by openoms** [comment]
New install of v0.9.0-rc1 on an RPi4 built ok in ~40 minutes.
Now indexing.
Does it need the reboot after installing?

**Comment by openoms** [comment]
Got an error:
```
Sep 19 20:05:55 tblitz electrs[21430]: [2021-09-19T19:05:55.276Z DEBUG electrs::p2p] got 2000 new headers                                                                                                         
Sep 19 20:05:55 tblitz electrs[21430]: [2021-09-19T19:05:55.280Z INFO  electrs::index] indexing 2000 blocks: [211201..213200]                                                                                     
Sep 19 20:05:55 tblitz electrs[21430]: [2021-09-19T19:05:55.280Z DEBUG electrs::p2p] loading 10 blocks
Sep 19 20:05:55 tblitz electrs[21430]: [2021-09-19T19:05:55.280Z TRACE electrs::p2p] send: GetData([WitnessBlock(00000000000003d56833b4af2f0e89e05adda37512f6f221d12d1ae5b0c71978), WitnessBlock(00000000000003cd6f9db462781341f221a94cb223926d098959ba2bd5c57605), WitnessBlock(00000000000002453ca221807941e44343fbba729caf8b43f8303f0ad6db6097), WitnessBlock(0000000000000354e8e0f3128f7d1f07ae62b989e1d0600c4742c07cd42ef77b), WitnessBlock(00000000000001eb7dfea1dc3d56fb5adfa74a272bbf0f35eb6ae14de30c8d01), WitnessBlock(00000000000002282b68cc9a12561c80f9a0101334af108994f4cf4b242b7376), WitnessBlock(00000000000001efcefe7deb3c02a32fe5d5428be37a50bd1c8e40b8c7cf8504), WitnessBlock(000000000000011bbdc96f199075097ba212ac81b7a06e19fcd4870762da7a75), WitnessBlock(0000000000000463bfedf09b852474c255b9cc60556316ecdf94d873c3c3e09b), WitnessBlock(000000000000022f5d525efaaa6c37d4be525bfd8cf0fce2c4869e0def0f09de)])
Sep 19 20:05:55 tblitz electrs[21430]: [2021-09-19T19:05:55.332Z INFO  electrs::db] closing DB at /mnt/hdd/app-storage/electrs/db/bitcoin                                                                         
Sep 19 20:05:55 tblitz electrs[21430]: Error: initial sync failed
Sep 19 20:05:55 tblitz electrs[21430]: Caused by:
Sep 19 20:05:55 tblitz electrs[21430]:     0: failed to get block 00000000000003d56833b4af2f0e89e05adda37512f6f221d12d1ae5b0c71978                                                                                
Sep 19 20:05:55 tblitz electrs[21430]:     1: p2p failed to recv
Sep 19 20:05:55 tblitz electrs[21430]:     2: I/O error: unexpected end of file
Sep 19 20:05:55 tblitz systemd[1]: electrs.service: Main process exited, code=exited, status=1/FAILURE
Sep 19 20:05:55 tblitz systemd[1]: electrs.service: Failed with result 'exit-code'.
```

The block is clearly present:
```
admin@tblitz:~ $ bitcoin-cli getblockstats '"00000000000003d56833b4af2f0e89e05adda37512f6f221d12d1ae5b0c71978"'                                                                                                   
{
  "avgfee": 81696,
  "avgfeerate": 222,
  "avgtxsize": 366,
  "blockhash": "00000000000003d56833b4af2f0e89e05adda37512f6f221d12d1ae5b0c71978",
  "feerate_percentiles": [
    53,
    112,
    193,
    228,
    387
  ],
  "height": 211201,
  "ins": 1093,
  "maxfee": 2000000,
  "maxfeerate": 4950,
  "maxtxsize": 7820,
  "medianfee": 50000,
  "mediantime": 1354851953,
  "mediantxsize": 258,
  "minfee": 0,
  "minfeerate": 0,
  "mintxsize": 192,
  "outs": 1495,
  "subsidy": 2500000000,
  "swtotal_size": 0,
  "swtotal_weight": 0,
  "swtxs": 0,
  "time": 1354860145,
  "total_out": 10170591692559,
  "total_size": 248647,
  "total_weight": 994588,
  "totalfee": 55390002,
  "txs": 679,
  "utxo_increase": 402,
  "utxo_size_inc": 30150
}
```

**Comment by openoms** [comment]
this is weird, when looking the bitcoinlogs 
`/mnt/hdd/bitcoin/debug.log` was not available despite the `bitcoind.service` had no errors.

`sudo systemctl restart bitcoind`
brought back the `debug.log` and the electrs synced continued.

n.b.: the `tbitcoind` and `sbitcoind` services are running too

**Comment by openoms** [comment]
The error above happened again at a different block. Bitcoind is working normally this time and electrs restarts to no avail.

Will sync to the latest scripts from `dev`, restart and see how it goes.

**Comment by openoms** [comment]
Likely cause:
`maxuploadtarget=5000` in the `bitcoin.conf`

The solution is to add:
`whitelist=download@127.0.0.1`
to bitcoin.conf when electrs is installed

**Comment by rootzoll** [comment]
This is the status auf Electrs after updating RaspiBlitz with a Electrs v0.9 ... so it says `initialSynced=1`while `syncProgress=0%` .. so can it make sense to reset the "/mnt/hdd/app-storage/electrs/initial-sync.done"?

![Bildschirmfoto 2021-09-21 um 00 50 12](https://user-images.githubusercontent.com/2472225/134087004-86745a59-ec60-4214-91ad-174498565384.png)

**Comment by openoms** [comment]
Now it is synced after ~10 h indexing + compaction, but cycling this:
```
Sep 21 08:09:59 tblitz systemd[1]: Stopped Electrs.
Sep 21 08:09:59 tblitz systemd[1]: Started Electrs.
Sep 21 08:09:59 tblitz electrs[17255]: Config { network: Bitcoin, db_path: "/mnt/hdd/app-storage/electrs/db/bitcoin", daemon_dir: "/home/electrs/.bitcoin", daemon_auth: UserPass("raspibolt", "<sensitive>"), daemon_rpc_addr: V4(127.0.0.1:8332), daemon_p2p_addr: V4(127.0.0.1:8333), electrum_rpc_addr: V4(0.0.0.0:50001), monitoring_addr: V4(127.0.0.1:4224), wait_duration: 20s, index_batch_size: 10, index_lookup_limit: Some(200), auto_reindex: true, ignore_mempool: false, sync_once: false, server_banner: "Welcome to electrs v0.9.0-rc1 - the Electrum Rust Server on your RaspiBlitz", args: [] }
Sep 21 08:09:59 tblitz electrs[17255]: [2021-09-21T07:09:59.991Z INFO  electrs::metrics::metrics_impl] serving Prometheus metrics on 127.0.0.1:4224
Sep 21 08:10:00 tblitz electrs[17255]: [2021-09-21T07:10:00.140Z INFO  electrs::db] "/mnt/hdd/app-storage/electrs/db/bitcoin": 141 SST files, 31.648221717 GB, 3.942450137 Grows
Sep 21 08:10:05 tblitz electrs[17255]: [2021-09-21T07:10:05.388Z INFO  electrs::chain] loading 701527 headers, tip=0000000000000000000a1dbe25fd3236403c74be52c821cfcaf76081f0ef0429
Sep 21 08:10:10 tblitz electrs[17255]: [2021-09-21T07:10:10.281Z INFO  electrs::chain] chain updated: tip=0000000000000000000a1dbe25fd3236403c74be52c821cfcaf76081f0ef0429, height=701527
Sep 21 08:10:41 tblitz electrs[17255]: [2021-09-21T07:10:41.427Z INFO  electrs::server] serving Electrum RPC on 0.0.0.0:50001
Sep 21 08:11:01 tblitz electrs[17255]: [2021-09-21T07:11:01.435Z INFO  electrs::server] stopping Electrum RPC server
Sep 21 08:11:01 tblitz electrs[17255]: [2021-09-21T07:11:01.435Z WARN  electrs::thread] tip_loop thread failed: JSON-RPC error: transport error: Didn't receive response data in time, timed out.
Sep 21 08:11:01 tblitz electrs[17255]: [2021-09-21T07:11:01.435Z INFO  electrs::db] closing DB at /mnt/hdd/app-storage/electrs/db/bitcoin
Sep 21 08:11:01 tblitz systemd[1]: electrs.service: Succeeded.
Sep 21 08:12:01 tblitz systemd[1]: electrs.service: Service RestartSec=1min expired, scheduling restart.
Sep 21 08:12:01 tblitz systemd[1]: electrs.service: Scheduled restart job, restart counter is at 180.
Sep 21 08:12:01 tblitz systemd[1]: Stopped Electrs.
```

Full restart showing the config and database size:
```
Sep 21 08:15:52 tblitz systemd[1]: Started Electrs.
Sep 21 08:15:52 tblitz electrs[19817]: Config { network: Bitcoin, db_path: "/mnt/hdd/app-storage/electrs/db/bitcoin", daemon_dir: "/home/electrs/.bitcoin", daemon_auth: UserPass("raspibolt", "<sensitive>"), daemon_rpc_addr: V4(127.0.0.1:8332), daemon_p2p_addr: V4(127.0.0.1:8333), electrum_rpc_addr: V4(0.0.0.0:50001), monitoring_addr: V4(127.0.0.1:4224), wait_duration: 20s, index_batch_size: 10, index_lookup_limit: Some(200), auto_reindex: true, ignore_mempool: false, sync_once: false, server_banner: "Welcome to electrs v0.9.0-rc1 - the Electrum Rust Server on your RaspiBlitz", args: [] }
Sep 21 08:15:52 tblitz electrs[19817]: [2021-09-21T07:15:52.320Z INFO  electrs::metrics::metrics_impl] serving Prometheus metrics on 127.0.0.1:4224
Sep 21 08:15:52 tblitz electrs[19817]: [2021-09-21T07:15:52.541Z INFO  electrs::db] "/mnt/hdd/app-storage/electrs/db/bitcoin": 128 SST files, 31.648277035 GB, 3.942450132 Grows
Sep 21 08:15:57 tblitz electrs[19817]: [2021-09-21T07:15:57.903Z INFO  electrs::chain] loading 701527 headers, tip=0000000000000000000a1dbe25fd3236403c74be52c821cfcaf76081f0ef0429
Sep 21 08:16:02 tblitz electrs[19817]: [2021-09-21T07:16:02.559Z INFO  electrs::chain] chain updated: tip=0000000000000000000a1dbe25fd3236403c74be52c821cfcaf76081f0ef0429, height=701527
Sep 21 08:16:33 tblitz electrs[19817]: [2021-09-21T07:16:33.781Z INFO  electrs::server] serving Electrum RPC on 0.0.0.0:50001
Sep 21 08:16:53 tblitz electrs[19817]: [2021-09-21T07:16:53.453Z INFO  electrs::server] stopping Electrum RPC server
Sep 21 08:16:53 tblitz electrs[19817]: [2021-09-21T07:16:53.453Z WARN  electrs::thread] tip_loop thread failed: JSON-RPC error: transport error: Didn't receive response data in time, timed out.
Sep 21 08:16:53 tblitz electrs[19817]: [2021-09-21T07:16:53.453Z INFO  electrs::db] closing DB at /mnt/hdd/app-storage/electrs/db/bitcoin
Sep 21 08:16:53 tblitz systemd[1]: electrs.service: Succeeded.
```

**Comment by openoms** [comment]
Seems like a communication problem with bitcoind (which is running without errors):
```
WARN  electrs::thread] tip_loop thread failed: JSON-RPC error: transport error: Didn't receive response data in time, timed out.
```
Rebuilding electrs now from the latest master where the rust bitcoin crate is bumped: https://github.com/romanz/electrs/commit/3041e89cd2fb377541b929d852ef6298c2d4e60a

Note: also happening in a my amd64 Ubuntu 20.04 VM

**Comment by rootzoll** [comment]
Maybe we wanna stick with the old electrs for the v1.7.1 and push the new one to 1.8.0?

**Comment by openoms** [comment]
> Maybe we wanna stick with the old electrs for the v1.7.1 and push the new one to 1.8.0?

yes, might make sense as it also avoids the reindexing after flashing the SDcard. People could update later electively. Downgrading from the rc1 for the release now. (partially reverting https://github.com/rootzoll/raspiblitz/commit/0e129268d70e145e114a6056d88058b67fd9e406)

EDIT: still there might be problem with connecting to Bitcoin Core 22.0 ?
The downgraded v0.8.12 needs to be tested too and I need to reindex again.

Will first see if the master has the issue solved.

**Comment by openoms** [comment]
@rootzoll now the issue with the restarts is solved and Electrs 0.9.0 seems to be significantly more performant compared to the previous database version, also it takes less space now.

There is no question that we should byte the bullet regarding the reindexing the question is just when?

I would like to include electrs v0.9.0 in the blitz v1.7.1 if the stable release is out by then.

**Comment by Kixunil** [comment]
FTR @romanz [wants to realease next **RC** in a ~week](https://github.com/romanz/electrs/issues/490#issuecomment-922505724)

Given that the db will have to be reindexed eventually anyway, doing it sooner will cause the benefits to be experienced for longer time, so doing it ASAP looks the most rational. Perhaps notify the users in some way to only upgrade when they don't need to use electrs for a while.

**Comment by openoms** [comment]
> This is the status auf Electrs after updating RaspiBlitz with a Electrs v0.9 ... so it says `initialSynced=1`while `syncProgress=0%` .. so can it make sense to reset the "/mnt/hdd/app-storage/electrs/initial-sync.done"?
> 
> ![Bildschirmfoto 2021-09-21 um 00 50 12](https://user-images.githubusercontent.com/2472225/134087004-86745a59-ec60-4214-91ad-174498565384.png)

can confirm this witha  working electrs on latest master:
```
##### STATUS ELECTRS SERVICE
configured=1
serviceInstalled=1
serviceRunning=1
syncProgress=0%
tipSynced=0
electrumResponding=1
initialSynced=1
localIP='192.168.3.139'
portTCP='50001'
localTCPPortActive=1
publicTCPPortAnswering=0
portHTTP='50002'
localHTTPPortActive=1
publicHTTPPortAnswering=0
TORrunning=1
nginxTest=1
```

**Comment by openoms** [comment]
ok, PR waiting for the stable release with the status fixed

**Comment by rootzoll** [comment]
Merged it in best hopes that a stable realease will come soon ... if not available by end of next week we need to reverse back.

**Comment by romanz** [comment]
[`v0.9.0-rc2`](https://github.com/romanz/electrs/releases/tag/v0.9.0-rc2) is released - please let me know if there is any open issue :)

**Comment by openoms** [comment]
Had a report that `v0.9.0-rc2` had no restarts so updating for the next raspiblitz RC

**Comment by openoms** [comment]
Got this error on TG:
![image](https://user-images.githubusercontent.com/43343391/134769743-372775cf-cd04-47d2-8d9a-a45d6264b283.png)

Changing the config solved it, will need to adapt the default:
`sudo nano /home/electrs/.electrs/config.toml`

add:
```
wait_duration_secs = 10
```

**Comment by Kixunil** [comment]
Head up, you may want to implement the logic of deleting old database described in https://github.com/romanz/electrs/blob/master/doc/usage.md#important-changes-from-versions-older-than-090

**Comment by rootzoll** [comment]
The final 0.9.0 has been released: https://twitter.com/roman_zeyde/status/1443484929480921090?s=20

**Comment by rootzoll** [comment]
Deleting of old database to be done in next release. We just recommend/allow electrs for 1TB drives for some time now so it should be fine to have the old db as a fall back in case of a downgrade for now.

**Comment by rootzoll** [comment]
@openoms the install of electrs failed on my latest test with RC3:

```
HEAD is now at 557911e Release 0.9.0
    Updating crates.io index
./config.scripts/bonus.electrs.sh: line 462: 29769 Segmentation fault      sudo -u electrs cargo build --locked --release
```

**Comment by romanz** [comment]
Could you please share the build log?
Also, how much RAM is available during the build?

**Comment by rootzoll** [comment]
RAM its a 8GB RP4 with around 5GB free RAM when build starts.
Where do I find the build log file?

**Comment by Kixunil** [comment]
Just stdout. Sefault during *build* is super-strange.

**Comment by romanz** [comment]
Could you please retry the build with higher verbosity:
```
cargo build --locked --release -v
```

**Comment by romanz** [comment]
Maybe single-threaded building can also help (using `--jobs=1` cargo flag)?
https://doc.rust-lang.org/cargo/commands/cargo-build.html#miscellaneous-options

**Comment by openoms** [comment]
> @openoms the install of electrs failed on my latest test with RC3:
> 
> ```
> HEAD is now at 557911e Release 0.9.0
>     Updating crates.io index
> ./config.scripts/bonus.electrs.sh: line 462: 29769 Segmentation fault      sudo -u electrs cargo build --locked --release
> ```

Couldn't reproduce this so far. Could it be possible that it was a one off memory error causing this? Did you try again on the same board or on an other one? (would consider labeling that RPi for testing only if this would be the case)

```
$ cargo -V
cargo 1.42.1

$ uname -a
Linux raspberrypi 5.10.17-v8+ #1403 SMP PREEMPT aarch64 GNU/Linux
```

**Comment by openoms** [comment]
Reproduced on a complete new install, looking into it:
```
Cloning into 'electrs'...
...
HEAD is now at 557911e Release 0.9.0
    Updating crates.io index
/home/admin/config.scripts/bonus.electrs.sh: line 462: 12171 Segmentation fault      sudo -u electrs cargo build --locked --release
```

Running manually ( adding `-v` or `--jobs=1` does not make a difference ):
```
admin@171rc3:/home/electrs/electrs $ sudo -u electrs cargo build --locked --release 
    Updating crates.io index
Segmentation fault
```

```
$ cargo -V
cargo 1.42.1

$ uname -a
Linux 171rc3 5.10.63-v8+ #1457 SMP PREEMPT aarch64 GNU/Linux
```

**Comment by Kixunil** [comment]
Could you run `sudo -u electrs gdb --args cargo build --locked --release` and then type `bt` after it segfaults? (You may need to `apt install gdb`.) This looks like a bug in `cargo` (may or may not be introduced by packaging), not `electrs` but I am capable and willing to help with diagnosing.

Am I correct assuming it's Armbian based on Debian 10?

**Comment by openoms** [comment]
> Could you run `sudo -u electrs gdb --args cargo build --locked --release` and then type `bt` after it segfaults? (You may need to `apt install gdb`.) This looks like a bug in `cargo` (may or may not be introduced by packaging), not `electrs` but I am capable and willing to help with diagnosing.

Thank you for the help. It might need some additional things, the output is only:
 ```
Type "apropos word" to search for commands related to "word"...
Reading symbols from cargo...(no debugging symbols found)...done.
warning: Missing auto-load script at offset 0 in section .debug_gdb_scripts
of file /usr/bin/cargo.
Use `info auto-load python-scripts [REGEXP]' to list them.
(gdb) bt
No stack.
(gdb) 
```

> Am I correct assuming it's Armbian based on Debian 10?

Yes, running the 64bit Raspberry OS which is based on Debian 10

**Comment by romanz** [comment]
Does it fail also when building electrs 0.8.*?

**Comment by romanz** [comment]
Does it fail during `Updating crates.io index` or during the compilation?

**Comment by romanz** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=918854 may be related...
We can also check only the dependencies' download (without actually building) by running:
```
$ CARGO_LOG=debug cargo fetch -v
<lots of debug logs>
```

**Comment by romanz** [comment]
We can also check only the dependencies' download (without actually building) by running:
```
$ cargo fetch
```

**Comment by romanz** [comment]
If the segfault is HTTP-related, we can increase the relevant log verbosity here:
https://doc.rust-lang.org/cargo/reference/config.html#http

**Comment by openoms** [comment]
It is likely a Rust installation issue with `apt`. Affecting an other Rust project as well the same way with segfault during `Updating crates.io index` : https://github.com/rootzoll/raspiblitz/issues/2579

**Comment by openoms** [comment]
> CARGO_LOG=debug cargo fetch -v

this finishes with similar:
```
    Updating crates.io index
[2021-10-10T09:16:16Z DEBUG cargo::sources::git::utils] skipping gc as there's only 0 pack files
[2021-10-10T09:16:16Z DEBUG cargo::sources::git::utils] doing a fetch for https://github.com/rust-lang/crates.io-index
[2021-10-10T09:16:16Z DEBUG cargo::sources::git::utils] initiating fetch of refs/heads/master:refs/remotes/origin/master from https://github.com/rust-lang/crates.io-index
Segmentation fault
```
```
$ cargo fetch
    Updating crates.io index
Segmentation fault
```

Everything works when using the script 
```
sudo -u electrs curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sudo -u electrs sh -s -- -y
```
to download rust under the `electrs` user. This was the method we used previously so will fall back to it.

**Comment by romanz** [comment]
Sounds good - the only question I have is whether we should pin a specific Rust version (using `--default-toolchain` rustup flag)?
For example, electrs `master` is using [1.41.1](https://github.com/romanz/electrs/blob/master/rust-toolchain), but probably can compile with other Rust versions as well.

**Comment by openoms** [comment]
The script installs `rustc 1.55.0`
```
info: default toolchain set to 'stable-aarch64-unknown-linux-gnu'
  stable-aarch64-unknown-linux-gnu unchanged - rustc 1.55.0 (c8dfcfe04 2021-09-06)
Rust is installed now. Great!
```
but electrs does download the specified version anyway: 
```
admin@171rc3:/home/electrs/electrs $  sudo -u electrs /home/electrs/.cargo/bin/cargo build --locked --release || exit 1
info: syncing channel updates for '1.41.1-aarch64-unknown-linux-gnu'
info: latest update on 2020-02-27, rust version 1.41.1 (f3e1a954d 2020-02-24)
info: downloading component 'cargo'
```
Would pinning Rust affect future updates? We can do it anyway as it is only pinned for the `electrs` user

**Comment by romanz** [comment]
My mistake - I forgot that cargo downloads the needed components before the build, so there is no need to "pin" it during `rustup` installation :)
Maybe we can even use `--default-toolchain none` (tested inside a Docker container) to prevent downloading latest Rust (if nobody is using it):
```
$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sudo sh -s -- -y --default-toolchain none
info: downloading installer
info: profile set to 'default'
info: default host triple is x86_64-unknown-linux-gnu
info: skipping toolchain installation


Rust is installed now. Great!

To get started you may need to restart your current shell.
This would reload your PATH environment variable to include
Cargo's bin directory ($HOME/.cargo/bin).

To configure your current shell, run:
source $HOME/.cargo/env

$ ~/.cargo/bin/cargo build
info: syncing channel updates for '1.41.1-x86_64-unknown-linux-gnu'
info: latest update on 2020-02-27, rust version 1.41.1 (f3e1a954d 2020-02-24)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'rust-docs'
info: installing component 'rust-std'
info: installing component 'rustc'
info: installing component 'rustfmt'
    Updating crates.io index
  Downloaded dirs-next v2.0.0
  Downloaded serde_derive v1.0.130
  Downloaded bitcoincore-rpc v0.14.0
  Downloaded electrs-rocksdb v0.15.0-e1
<snip>

**Comment by openoms** [comment]
ok, updated and tested ok (will run again on a clean install)

for anyone on raspiblitz v17.1RC3 to test the latest state run in the CLI:
`patch`
before installing `electrs` (or connecting Fully Noded to CL)

**Comment by Kixunil** [comment]
Sorry, forgot that you must run `run` in `gdb`, then it should segfault and then you should use `bt`

Would recommend considering signature verification of Rust if you need to fall back.

According to the bug report @romanz linked it could have something to do with proxy. Do you happen to set Tor proxy as system-wide configuration? Perhaps try to turn it off to see if it helps?

**Comment by rootzoll** [comment]
Now tested again on the same machine with the fix of @openoms .. and it installed fine :)
Removing the `bug confirmed` lable. Will test again on another machine for final testing.
Thanks everybody for the quick response.

**Comment by rootzoll** [comment]
OK. Test worked fine also in second test machine. Closing issue for release.
