### ISSUE TITLE
Issues with certificates IP2Tor, BTCPay

### ISSUE THREAD

**Issue by Xaspr** [raspiblitz/raspiblitz#2550]
Hi,

I struggle with the certificates with an IP2Tor bridge. In Firefox and other browsers I get the message that the certificate is an untrusted self-signed certificate (lnd autogenerated cert by localhost). This is also the case for the local network logins of BTCPay, RTL and Lightning Terminal. 

Both the subscriptions for letsencrypt and the IP2Tor Bridge are active, and I've tried cancelling and subscribing again. If I go to BTCPay Server Info in the Raspiblitz menu I see a warning that there's no HTTPS response. Accessing the hidden service directly via Tor is possible (without warnings). **EDIT1**: This is false. After applying the letsencrypt subscription and opening another tor browser, it now gives the same message: 

> "Warning: Potential Security Risk Ahead
> Tor Browser detected a potential security threat and did not continue to ****.onion. If you visit this site, attackers could try to steal information like your passwords, emails, or credit card details.

Any ideas on how to fix this, also for the logins via the local network?

**Comment by rootzoll** [comment]
Just checked for the upcoming v1.7.1 release the IP2Tor & LetsEncrypt features. I had to remove the DYNU domain service for the LetsEncrypt Certificate for now - so if you use that please cancel and try the DUCKDNS one.

**Comment by Xaspr** [comment]
Thank you! I'm away for a few weeks now. When I get back I'll check out if 1.7.1 fixes it.

**Comment by openoms** [comment]
closing for inactivirty
