### ISSUE TITLE
Re-Check COPY over LAN

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2553]
Got stuck at ths point on one test run ... after source had completly transferrred the chain and the target was waiting more than 6 hours to continue-

![Bildschirmfoto 2021-09-19 um 19 34 27](https://user-images.githubusercontent.com/2472225/133937253-98e89294-eb55-4806-913c-0a4788b09075.png)
.

**Comment by openoms** [comment]
Tested this successfully by copying from an RPi4 to Ubuntu VM. Also restarting the copy worked after a connection break.

**Comment by rootzoll** [comment]
Found the problem in a change I did to the boostrap service.

**Comment by rootzoll** [comment]
Process needs to be retested with latest dev branch.

**Comment by openoms** [comment]
I wonder if the same issue caused the syncing problem with electrs: https://github.com/rootzoll/raspiblitz/issues/2548
continuing the tests.

**Comment by rootzoll** [comment]
re-test worked. closing issue for release.
