### ISSUE TITLE
Clean Up Sphinx Script

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2558]
Its now a lot of options how to connect Sphinx App ... maybe remove the IP2Tor here to clean up again.

**Comment by openoms** [comment]
- [ ] add git verify-commit - commits are not signed, only merges and tags by git web-flow
in connection with #2686

**Comment by rootzoll** [comment]
This can be revisited/refactored when adding Sphinx as an App to the WebUI in a later release.

**Comment by rootzoll** [comment]
Planning to set Sphinx-App on the deprectaed status for next release.

**Comment by rootzoll** [comment]
Starting from Raspiblitz v1.11.1:
The Sphinx-Relay is deprecated and may be removed in future versions.
Needs to be manual installed manually after every update/recover on terminal with:
`./config.scripts/bonus.sphinxrelay.sh on`
