### ISSUE TITLE
LND unable to open databases

### ISSUE THREAD

**Issue by nerdmaster02** [raspiblitz/raspiblitz#2559]
My node crashed and upon recovering via SD card change, I started receiving the following error when LND attempts to start:

`raspberrypi lnd[1532]: unable to open databases: unable to open local channeldb: unable to create new channeldb: writeat /home/bitcoin/.lnd/data/graph/mainnet/channel.db: negative offset`

Here is my debug:
https://termbin.com/wrfx7

Thanks!

**Comment by openoms** [comment]
You can ask to confirm on the LND Slack https://dev.lightning.community/ or github to confirm but this looks like a database corruption to me.

Will likely need to recover from the SEED and SCB to have your channels force closed and return onchain after the timelock:
https://github.com/rootzoll/raspiblitz/blob/v1.7/FAQ.md#2-recover-from-wallet-seed


See https://github.com/rootzoll/raspiblitz/issues/2532 for similar.

Use stable hardware and a UPS to avoid power cuts!
