### ISSUE TITLE
Specter config needs fixing

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2563]
Specter installs & starts but the config seems still broken .. these are the results when trying to login:

![Bildschirmfoto 2021-09-21 um 17 28 50](https://user-images.githubusercontent.com/2472225/134200587-a6e90094-b4bb-46e6-957d-1de6c41365db.png)

seeing those specter logs ... not sure if related:
```
Sep 21 16:22:47 testbrel python3[16484]: [2021-09-21 16:22:47,540] ERROR in wallet_manager: Prevented Trying to update wallet_Manager with broken <BitcoinRpc http://localhost:8332>
Sep 21 16:22:47 testbrel python3[16484]: [2021-09-21 16:22:47,545] INFO in wallet_manager: Specter seems to be disconnected from Bitcoin Core. Skipping wallets update.
Sep 21 16:23:21 testbrel python3[16484]: [2021-09-21 16:23:21,727] INFO in checker: Checker health Checking every 600 seconds now
```

@openoms any idea?

**Comment by openoms** [comment]
Ok needed some changes, but now after installation can be configured for the parallel networks with:
```
config.scripts/bonus.specter.sh config testnet
config.scripts/bonus.specter.sh config signet
```
and choose between the nodes within Specter.

![image](https://user-images.githubusercontent.com/43343391/134230495-accd2a74-c1bc-482d-9b2b-c5cec0f7caab.png)

**Comment by rootzoll** [comment]
Looks good on first test :) login works now

**Comment by openoms** [comment]
Small changes to fix installation in the Ubuntu VM: https://github.com/rootzoll/raspiblitz/commit/90421b1c3b33860ec57a765e4718419828aeefcd

**Comment by rootzoll** [comment]
Tests working ... closing for v1.7.1 release.
