### ISSUE TITLE
[New] CLN update script

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#2564]
Part of the `cln.install.sh` script already, needs testing and integration to the `UPDATE` menu.

**Comment by openoms** [comment]
added to the menu in 6b34ce9

**Comment by openoms** [comment]
Note: Downgrading not working even from the latest master to the latest release:
```
$ sudo journalctl -fu lightningd
raspberrypi sh[30747]: Refusing to migrate down from version 178 to 176
```

**Comment by rootzoll** [comment]
"Forward Ever - Backward Never"
https://www.youtube.com/watch?v=QfdRZiF72FE

**Comment by rootzoll** [comment]
Runs thru wuth same version  .. to be final tested after release as soon as a new c-lightnig version is available.
