### ISSUE TITLE
Change "medium difficulty" build to match maintainer build

### ISSUE THREAD

**Issue by Csi18nAlistairMann** [raspiblitz/raspiblitz#2566]
Summary: following the "medium difficulty" build process results in different defaults than assumed by the maintainer build. One effect is that the LCD is left inoperable.

Detail:

The "medium difficulty" build process /should/ result in an image substantially similar to that of the maintainer build. We know this because we read at https://github.com/rootzoll/raspiblitz#build-the-sd-card-image "if you want to build that image yourself - here is a quick guide"

If one examines the maintainer image file /home/pi/.bash_history we can see the maintainer used the following build command:
wget --no-cache https://raw.githubusercontent.com/rootzoll/raspiblitz/v1.7/build_sdcard.sh && sudo bash build_sdcard.sh false true rootzoll v1.7 lcd true true

However https://github.com/rootzoll/raspiblitz#build-the-sd-card-image suggests we use the command:
wget https://raw.githubusercontent.com/rootzoll/raspiblitz/v1.7/build_sdcard.sh && sudo bash build_sdcard.sh

Notice the maintainer build overrides build_sdcard.sh's internal defaults, the medium difficulty build honours them.

The differences are:
$fatpack is true for the former, false for the latter;
$githubBranch is "v1.7" for the former, "dev" for the latter;
$displayClass is "lcd" for the former, "hdmi" for the latter.

Solutions:
EITHER
1. build_sdcard.sh should have its defaults changed to match the maintainer build. This would be my preferred solution as it's most consistent with the aim "Build your own Lightning Node on a RaspberryPi with a nice Display."

OR
2. README.md should have its invocation of build_sdcard.sh changed to include the maintainer overrides. Quick and dirty!

POSSIBLY
3. If it's of value to have different defaults locally, build_sdcard.sh could look for a local file that contains local defaults to override it's own. Absence of such a file - as would be expected for a new user - would leave the maintainer defaults in place.

Happy to offer PRs for the above. 

Comments?

**Comment by rootzoll** [comment]
At the moment the goal of the idea of the defaults was to have as least additional depencencies possible - for those that wanna build their own image.

> $fatpack is true for the former, false for the latter;

fatpack might already install frameworks (to speed up install times of additional apps later)

$displayClass is "lcd" for the former, "hdmi" for the latter.

> LCD add the drivers for the LCD shield - hdmi runs without additional drivers

$githubBranch is "v1.7" for the former, "dev" for the latter;

> yeah dev might not be the best choice here 


I can see that from another perspective it makes sense to have the defaults the same as the maintainer build. So I push this to v1.8 where we will to the next changes to sd build script. If you like to update the README for the v1.7.1 wit a PR that can make sense.
