### ISSUE TITLE
Web Admin IP and Port Only Displayed in Info option for Ride The Lightning

### ISSUE THREAD

**Issue by stealth2600** [raspiblitz/raspiblitz#2568]
For some reason the info option only displays the web admin ip and port if you are running RTL. It does not display the ip/port if you are running Thunderhub. Can this be fixed to show the web admin ip/port regardless of whether its RTL or Thunderhub that's being used? Thanks for the help!

**Comment by rootzoll** [comment]
With v1.8.0 there will be coming a RaspiBlitz WebUI that than as RTL and Thunderhub as Apps you can easily jump to. Closing this issue.
