### ISSUE TITLE
Hardware case and display not fully compatible

### ISSUE THREAD

**Issue by raumi75** [raspiblitz/raspiblitz#257]
I bought the case and the display from the German shopping list. the case is officially for a 3.2" display whereas the display is slightly larger (3.5"), so the top frame does not close. It works ok and the price is great, but I have a feeling there might be a better solution.

**Comment by fluidvoice** [comment]
I have a 3.5" display and use this one. https://thecryptocloak.com/product/lightningshell/
It's a bit more expensive but is customizable (name and colors) and can hold a HDD as well.
It says "**Raspberry Pi Screen max dimensions (87mm x 56mm x 7mm)**"
Which display exactly do you have?
Mine is by Kuman: http://www.kumantech.com/kuman-35-inch-tft-lcd-display-480x320-rgb-pixels-touch-screen-monitor-for-raspberry-pi-3-2-model-b-b-a-a-module-spi-interface-with-touch-pen-sc06_p0014.html

**Comment by raumi75** [comment]
That case looks very good. I personally won't change anything and just use the case without the frame. "works for me"™️

I bought the one from the German shopping list: https://www.amazon.de/gp/product/B06X191RX7

**Comment by fluidvoice** [comment]
> That case looks very good. I personally won't change anything and just use the case without the frame. "works for me"
> 
> I bought the one from the German shopping list: https://www.amazon.de/gp/product/B06X191RX7

this one is cheap and might work for you: https://www.amazon.de/Ils-Generation-Schicht-5-Zoll-Display-Raspberry/dp/B079122RMQ/

**Comment by goodc0re** [comment]
Had the same issue with the case from the German shopping list and think that the shopping list should be changed or a note added that the case doesn't fit.

**Comment by rootzoll** [comment]
Its correct that the final topping of the case in the german shopping list does not fit. But that was OK from my side because the bigger LCD covers the top perfectly. If someone ca recommend a better fitting case in the same price point on amazon feel free to make a pull request. I added a short note to ignore to topping in the README.
