### ISSUE TITLE
Inactive channels, reconnect fails with "general SOCKS server failure"

### ISSUE THREAD

**Issue by DerHuette** [raspiblitz/raspiblitz#2578]
Hi!
I am running my raspiblitz for some weeks now (behind tor) and have 8 channels open. Overnight, two of these channels became inactive. The nodes don't appear in the list of peers anymore. When I try to reconnect to these peers, I get the error message "socks connect tcp 127.0.0.1:9070->peer-IP:port: unknown error general SOCKS server failure"

I can connect to other peers without problem, tor and clearnet. I am sure the two nodes aren't offline, they are big nodes, zigzag and rompert. 

What can I do to solve this problem? 

Thank you in advance!

**Comment by openoms** [comment]
Try restarting Tor 
`sudo systemctl restart tor`
then lnd
`sudo systemctl restart tor`
Alternatively restart the whole node.

Can also test removing  `tor.streamisolation` from the lnd.conf.

**Comment by DerHuette** [comment]
Thank you for your answer!

I already tried restarting tor, lnd and the whole node. Did not work. 

And there is no entry "tor.streamisolation" in my lnd.conf (raspiblitz 1.7). 

But, after a few days of waiting, the channels are active again! Would like to understand that (and do not), but for now, everything is ok again.
