### ISSUE TITLE
CRTL: Error: connect econnrefused 127.0.0.1:6100

### ISSUE THREAD

**Issue by ros-mac** [raspiblitz/raspiblitz#2580]
This may be reported already and I couldn't see it. CRTL web interface http/https.
I tried sudo ufw allow 6100 and a reload, but didn't work.

Sep 27 11:41:05 raspberrypi node[9487]: --- cl-rest api server is ready and listening on port: 6100 --- warn
Sep 27 11:41:09 raspberrypi node[755]: [2021-09-27T10:41:09.512Z] ERROR: GetInfo => Get Info Error: {"name":"RequestError","message":"Error: connect ECONNREFUSED 127.0.0.1:6100","cause":{"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":6100},"error":{"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":6100},"options":{"url":"https://localhost:6100/v1/getinfo","rejectUnauthorized":false,"json":true,"headers":{},"method":"GET","qs":{},"simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false}}

**Comment by openoms** [comment]
check please:
`sudo systemctl status cRTL`
and
`sudo journalctl -fu cRTL`

**Comment by openoms** [comment]
Also patch to the latest `dev` and be aware of the variable changes in #2575

Run the commands after patching:
https://github.com/rootzoll/raspiblitz/pull/2575#issuecomment-927261596

EDIT: 
in https://github.com/rootzoll/raspiblitz/commit/09da8bdd26004470f1eba35a799f17430fc94b2c introduced a check during boot do just make sure you reboot after patching to the latest `dev`

Best to reinstall cRTL afterwards.

**Comment by ros-mac** [comment]
Thanks! I patched it and rebooted and I had to correct an if statement at line 228 in bonus.rtl.sh
Then I reset the wallet from the menu and restarted the clnrest.service
And it worked!

**Comment by openoms** [comment]
Thanks there are indeed some extra characters. Fixing now.
