### ISSUE TITLE
[CL] Spark wallet v0.3.0rc for BOLT12 offers in a GUI

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#2584]
With C-lightning installed offers are available from the CLI already: https://github.com/openoms/raspiblitz/blob/cln-FAQ/FAQ.cl.md#offers

Spark wallet gives a nice interface in it's latest release candidate: https://github.com/shesek/spark-wallet/releases/tag/v0.3.0rc
![image](https://user-images.githubusercontent.com/43343391/135454668-0d4626a6-6d22-4daa-ae19-a6473d3af239.png)

![image](https://user-images.githubusercontent.com/43343391/135454853-d0ab3512-67ae-43c5-a25f-80d00216ac01.png)

![image](https://user-images.githubusercontent.com/43343391/135454875-eb713d6c-07e2-438c-aac6-2f9ae29cd36c.png)

cli example to request a BOLT12 invoice for 21 sats:
```
lightning-cli fetchinvoice  lno1pgvkxun9v96x2epqwa5hg6pq2dcxzuntyptkzmrvv46pugq0clnzex2k5d9umw3snfyqnn8a0tw2ujutv3x2eqd5m3vdgw3y0y 21000
```

**Comment by rootzoll** [comment]
So we will include this into v1.7.1? Is the PR ready to merge?

**Comment by openoms** [comment]
It is an RC, but the only GUI implementing offers. I think it would be good to make it available. The PR is ready for final testing in the next raspiblitz rc.

**Comment by rootzoll** [comment]
On install test I got a fail ... @openoms can you take a look and also re-test on your side?

```
fatal: destination path 'spark-wallet' already exists and is not an empty directory.
HEAD is now at 8fa1be2 Fix typo

> spark-wallet@0.2.17 dist:npm
> ./scripts/build.sh

+ mkdir -p dist
+ rm -rf 'dist/*'
+ babel -d dist --ignore src/transport/granax-dep/node_modules src
./scripts/build.sh: line 8: babel: command not found
```

**Comment by rootzoll** [comment]
Also on another test node the install of Spark failed (see below) .. @openoms any change for a quick fix here before v1.7.1 release?

**Comment by openoms** [comment]
likely can solved by installing the babel dependency beforehand

https://manpages.debian.org/unstable/openbabel/babel.1.en.html

testing with:
`sudo apt install -y openbabel`

```
$ babel
No output file or format spec!
Open Babel 2.4.1 -- Nov 12 2018 -- 12:24:14
Usage: babel [-i<input-type>] <name> [-o<output-type>] <name>
Try  -H option for more information.

WARNING: babel is deprecated and will be removed in a future release
         of Open Babel. You should use obabel instead. For information
         on the differences please see:
             http://openbabel.org/docs/current/Command-line_tools/babel.html
```

Hmm, it looks like it is not that babel! 
```
> spark-wallet@0.2.17 dist:npm
> ./scripts/build.sh

+ mkdir -p dist
+ rm -rf 'dist/*'
+ babel -d dist --ignore src/transport/granax-dep/node_modules src
babel: cannot write output format!
```

**Comment by rootzoll** [comment]
I can remove/deactivate the spark wallet from SERVICES menu and just have it as a script in the v1.7.1 ... we can add it later to the menus when integration is more mature.

**Comment by openoms** [comment]
found the pendency it is `npm babel-cli` fixing now. It was tested ok in the VM, but it needs to be installed separately on the raspberry pi

**Comment by openoms** [comment]
install looks good now and given this is the only GUI for offers I'd like to keep it in, but indeed it is all  a bit experimental.

people can copy and paste offers in their web browser though!

**Comment by rootzoll** [comment]
Thanks ... this looks good now :) Closing issue.
