### ISSUE TITLE
After enabling Channel Autopilot and LND auto-unlock ZAP Mobile wallet can't connect

### ISSUE THREAD

**Issue by eurtnl** [raspiblitz/raspiblitz#259]
After enabling Channel Autopilot and LND auto-unlock ZAP Mobile wallet can't connect. 

Tried a new qr, but also no connection.
Any idea how to solve?

**Comment by rootzoll** [comment]
When switchen on auto-unlock it changes the tlsextraip=0.0.0.0 in the lnd.conf ... hmmm could be that this conflicts with the tls.cert used by ZAP .. not sure yet. Will put this on my list to test before 1.0 release. If anybody has more insight, please share.

**Comment by Smiggel** [comment]
Is rpclisten=0.0.0.0:10009 not commented in the lnd.conf?

**Comment by eurtnl** [comment]
Well i was able to connect ZAP desktop with the same tls.cert

**Comment by raumi75** [comment]
So the workaround is to edit `/mnt/hdd/lnd/lnd.conf`, remove the `#` in the `rpclisten` line and  `sudo service lnd restart`

**Comment by rootzoll** [comment]
I will re-check that the rpclisten is active/open by default on final release tests. Thx.

**Comment by rootzoll** [comment]
When enable/disable the Auto-Unlock there is the need to reconnect the mobile/desktop wallets, because the macaroon/TLS changes. I added a Dialog-Box with the info about that, when switching Auto-Unlock on/off.

 Testing OK so far now. Closin this issue for next release so far.
