### ISSUE TITLE
Why BTC value in my wallet has changed?

### ISSUE THREAD

**Issue by eurtnl** [raspiblitz/raspiblitz#260]
![screenshot 2019-01-09 at 19 56 54](https://user-images.githubusercontent.com/45401395/50921662-e09b8480-1448-11e9-9e93-dc2459e22e2a.png)
Today i decided to fund my wallet with a small amount for testing purpose. So i send 0.001 BTC to my wallet, had dinner, connected ZAP dektop. And i found my wallet as shown above.

As you can see, 10 minutes after receiving my deposit, something/one send 0.00064982 BTC (**it was not me!**). Now when you deduct 0.00064982 from 00.1 that would leave 0,00035018. But my wallet says it has 0,00089888. Why the difference?

What happend?

**Comment by fluidvoice** [comment]
from SSH:
`lncli listchaintxns`

**Comment by fluidvoice** [comment]
You have autopilot turned on, right?  Your node opened a channel of 0.00060000 BTC with (ln.BitSoapBox.com):
https://1ml.com/node/027a532a96510407b6ca0252fdb045fae98a40febe08b443533b9edc2dd5db127d
The other differences are probably because of bitcoin transaction fees.

**Comment by eurtnl** [comment]
Yeah i figured that, now stopping autopilot :-)

**Comment by rootzoll** [comment]
To prevent that confusing behavior AutoPilot is turned off by default ;)
