### ISSUE TITLE
v.1.7.1-RC3: C-Lightning node alias can't be changed via menu option

### ISSUE THREAD

**Issue by LightRider5** [raspiblitz/raspiblitz#2608]
After I installed C-Lightning I tryed to change the alias of the node in the options menu. 

But that failed with:

`/home/bitcoin/.lightning/config` 
`FAIL - missing /home/bitcoin/.lightning/config `

The name of the node stayed as default: REDRAGE

I checked via terminal but the config file exists. 
I wrote into the config file:

`alias="nodename"`

and it worked and the node alias changed.

**Comment by openoms** [comment]
Thanks for reporting, was a quick fix.
Run `patch` from the terminal and it should work now (no restart needed).

**Comment by rootzoll** [comment]
fix tested & worked. Will be part of final release.
