### ISSUE TITLE
RTL installation does not show address and instructions

### ISSUE THREAD

**Issue by raumi75** [raspiblitz/raspiblitz#261]
How do I scroll to see the relevant part?

![screenshot rtf install](https://user-images.githubusercontent.com/1858579/50943182-a901fc00-148b-11e9-9c1e-9bb956186255.png)

Focus is on OK. Mouse or Tab-key don't do the trick.

**Comment by rootzoll** [comment]
normally it should be the arrow down key.
I added more space fore this dialog.
the relevant address should also be displayed on the LCD after reboot

closing this issue for now.
