### ISSUE TITLE
see Ram on initial screen during sync

### ISSUE THREAD

**Issue by nyxnor** [raspiblitz/raspiblitz#2610]
https://github.com/rootzoll/raspiblitz/blob/dev/home.admin/setup.scripts/eventBlockchainSync.sh
```sh
grep -oP "MemTotal:\s*\K\w+" /proc/meminfo
```
or directly GB
```sh
free --giga | grep -oP "Mem:\s*\K\w+"
```

**Comment by rootzoll** [comment]
The v1.7.1 already will show the GB RAM on the first setup LCD screen - see:
https://github.com/rootzoll/raspiblitz/blob/dc49f922dcec0fd328307783559fb9b4937e8976/home.admin/setup.scripts/eventInfoWait.sh#L183
