### ISSUE TITLE
Bonus: kindle-display - why not setup cronjob by default

### ISSUE THREAD

**Issue by frennkie** [raspiblitz/raspiblitz#2616]
As far as I see it the install script for the kindle-display only hints that a cronjob could be setup: https://github.com/rootzoll/raspiblitz/blob/v1.7/home.admin/config.scripts/bonus.kindle-display.sh#L167

Why don't we actually setup this by default?
I just upgraded from 1.7.0 to 1.7.1 and had to remember to set up the cronjob - otherwise my kindle wouldn't update.

@dennisreimann thoughts? ;-D

**Comment by dennisreimann** [comment]
Yes, for sure, I guess I couldn't figure out how to do it when I added the script.

**Comment by rootzoll** [comment]
I added this to the v1.8.0 milestone as a wish to be community contributed :)

**Comment by openoms** [comment]
The user's crontab would be in:
`/var/spool/cron/crontabs/kindledisplay`

So can just do (to be tested):
```
USERNAME=kindledisplay
HOME_DIR=/home/$USERNAME
APP_ROOT_DIR=$HOME_DIR/kindle-display
APP_SERVER_DIR=$APP_ROOT_DIR/server
CRON_FILE=$APP_SERVER_DIR/cron.sh

echo "
SHELL=/bin/bash
PATH=/bin:/usr/bin:/usr/local/bin
*/5 * * * * $CRON_FILE > /dev/null 2>&1 
" | sudo tee /var/spool/cron/crontabs/$USERNAME
```

**Comment by frennkie** [comment]
@openoms The scripts in /var/spool/cron/crontabs/ all have this at the top:

``` 
sudo cat /var/spool/cron/crontabs/admin
# DO NOT EDIT THIS FILE - edit the master and reinstall.
# (- installed on Tue Oct 12 19:24:41 2021)
# (Cron version -- $Id: crontab.c,v 2.13 1994/01/17 03:20:37 vixie Exp $)
```

Another way to implement cronjobs (besides trying to pipe to `crontab -e`) is to create a file in `/etc/cron.d/`. Crontab files in this path additionally have a `username` field so that the job is run as this user (instead of `root`).

```
admin@raspberrypi:~ ₿ cat /etc/cron.d/kindle-display
# /etc/cron.d/kindle-display

SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# Example of job definition:
# .---------------- minute (0 - 59)
# |  .------------- hour (0 - 23)
# |  |  .---------- day of month (1 - 31)
# |  |  |  .------- month (1 - 12) OR jan,feb,mar,apr ...
# |  |  |  |  .---- day of week (0 - 6) (Sunday=0 or 7) OR sun,mon,tue,wed,thu,fri,sat
# |  |  |  |  |
# *  *  *  *  * user-name command to be executed
*/5 * * * * kindledisplay /home/kindledisplay/kindle-display/server/cron.sh > /dev/null 2>&1
```

Any objections?

**Comment by openoms** [comment]
@frennkie no, obviously it is better to use the recommended way :)

**Comment by rootzoll** [comment]
I was not able to test because I have not a kindle display - but closing issue fingers crossed for release.
