### ISSUE TITLE
menu Cancel and BackToMenu buttons exit on v1.7.1

### ISSUE THREAD

**Issue by dipunm** [raspiblitz/raspiblitz#2618]
Steps to reproduce:

1. $ ssh admin@.....
2. Input: `Ctrl+C`
3. $ menu
4. Go to `Connect`
5. Select `Back to menu`

Result: I have to re-enter the menu by typing `menu` again.
Expected: I was redirected to the main menu before.

**Comment by rootzoll** [comment]
This is by design. `menu` just calls the menu directly just one time. The loop around the menu is done by using the `raspiblitz`command (`00raspibllitz.sh` script).
