### ISSUE TITLE
Opt out of telemetry for Thunderhub

### ISSUE THREAD

**Issue by dipunm** [raspiblitz/raspiblitz#2620]
During installation, there is a new message from next.js which I think we are not addressing at the moment.

We can remove telemetary as we have done for RTL by running the command shown here:
https://nextjs.org/telemetry#how-do-i-opt-out
```
npx next telemetry disable
```

**Comment by rootzoll** [comment]
This merged with the PR from openoms:
https://github.com/rootzoll/raspiblitz/blob/217c1766d2f46bc38c4cfbcf48dde84a928a5eec/home.admin/config.scripts/bonus.thunderhub.sh#L98

@dipunm is your PR #2628 now a duplicate or an needed addition?

**Comment by dipunm** [comment]
I suppose it is now a duplicate, although I prefer the env variable method because it is easy to see and understand and is permanent whereas the npx command could be undone later with no trace.

I'll do the rebase now, I've given my thoughts, I'll let you make the final decision. It's no harm to also add the environment variable.

**Comment by rootzoll** [comment]
This looks good .. closing for v1.7.2 release
