### ISSUE TITLE
Tried Patching getting this error

### ISSUE THREAD

**Issue by Canadian-Alien** [raspiblitz/raspiblitz#2627]
![E7593665-065E-4014-B461-1DB2171706FB](https://user-images.githubusercontent.com/92589876/137502540-1d89841a-263c-4f18-b673-1528b28f1cf0.jpeg)

**Comment by Canadian-Alien** [comment]
![szdvzsvd](https://user-images.githubusercontent.com/92589876/137503601-33d5949b-d53d-46a3-9d57-3a72276ef318.jpg)

**Comment by nyxnor** [comment]
do not patch, flash the sd card
