### ISSUE TITLE
GPG signed with subkey 

### ISSUE THREAD

**Issue by TheButterZone** [raspiblitz/raspiblitz#2630]
raspiblitz-v1.7.1-2021-10-12.img.gz.sig was with your subkey ending in 47DA instead of primary ending in 6461. Not sure if that was intentional since 6461 is on https://github.com/rootzoll/raspiblitz/blob/v1.7/FAQ.md#how-to-verify-the-sd-card-image-after-download and the readme page.

**Comment by rootzoll** [comment]
Yes I am signing with my subkey .. is this too confusing?

**Comment by TheButterZone** [comment]
When you put something other than your subkey on those pages, yes...

**Comment by rootzoll** [comment]
TODO: Add main & sub key fingerprints to documentation.

**Comment by rootzoll** [comment]
The sub key is now mentioned in the "Downloading the Software" section:
https://github.com/rootzoll/raspiblitz/blob/dev/README.md#downloading-the-software

**Comment by rootzoll** [comment]
OK also added info on sub key in FAQ. Will be part of v1.7.2. Closing issue.
