### ISSUE TITLE
Cannot verify hash

### ISSUE THREAD

**Issue by sobradob** [raspiblitz/raspiblitz#2632]
Hi, 

I cannot verify the hash compared to what is expected (`4b5481e0f27afe9b5aa8bab5805f7df033f2596db29a1e47c25d2f0109d9c003`).

Am I doing something wrong?

```
openssl sha256 raspiblitz-v1.7.1-2021-10-12.img 

SHA256(raspiblitz-v1.7.1-2021-10-12.img)= 9ecfad2a12d84f6071409f096bb71f6d229c5b8d4df73c029131d3e96f597679
```

**Comment by rootzoll** [comment]
You need to make the checksum on the `img.gz` file - not the `.img` ... so make the checksum before unzipping/unpacking the image.

**Comment by sobradob** [comment]
thanks for explaining!
