### ISSUE TITLE
Add squeaknode app

### ISSUE THREAD

**Issue by yzernik** [raspiblitz/raspiblitz#2636]
This app has dependency on Bitcoin and LND.
https://github.com/yzernik/squeaknode

**Comment by rootzoll** [comment]
Always open to further apps to add. @yzernik are you planning to submit an install script for this?

See video for details:
"How to contribute to RaspiBlitz Development"
https://www.youtube.com/watch?v=ZVtZepV3OfM

**Comment by yzernik** [comment]
Yes, I'll try to get a pull request up in the next few days. Thanks

**Comment by openoms** [comment]
What's a squeak?

**Comment by yzernik** [comment]
@openoms It's the name for a post in the squeaknode app, similar to a tweet. But it's open source and immutable, and timestamped with the latest bitcoin block hash, and signed with a private key.

Looks like this:
![Screenshot from 2021-11-08 04-09-47](https://user-images.githubusercontent.com/890133/140739688-c848f2d9-c70d-4dd5-9f27-c808ddcd5210.png)

**Comment by openoms** [comment]
Thanks for the explanation! Would be nice to have this clear straight in the project readme.

**Comment by yzernik** [comment]
@openoms Good idea. Updated the readme: https://github.com/yzernik/squeaknode/pull/1788

**Comment by yzernik** [comment]
Opened PR: https://github.com/rootzoll/raspiblitz/pull/2731

**Comment by rootzoll** [comment]
@yzernik  on preparing the PR for merge I am not sure anymore if the zmq entry are still correct - its merged now into dev but please check if you see anything missing

**Comment by yzernik** [comment]
Thanks @rootzoll it's been a few months since I put up the PR, and v0.3 of Squeaknode is now released.

I'll try to put up an update here in the next few days.

Thanks!

**Comment by rootzoll** [comment]
@yzernik on my testing machine after installing Squeaknode it does not startup. Can you help? See error:

```
Jun 01 17:58:13 raspberrypi systemd[1]: Started squeaknode.
Jun 01 17:58:16 raspberrypi sh[362698]: Traceback (most recent call last):
Jun 01 17:58:16 raspberrypi sh[362698]:   File "/home/squeaknode/squeaknode/./venv/bin/squeaknode", line 5, in <module>
Jun 01 17:58:17 raspberrypi sh[362698]:     from squeaknode.main import main
Jun 01 17:58:17 raspberrypi sh[362698]:   File "/home/squeaknode/squeaknode/venv/lib/python3.9/site-packages/squeaknode/main.py", line 31, in >
Jun 01 17:58:17 raspberrypi sh[362698]:     from squeaknode.node.squeak_node import SqueakNode
Jun 01 17:58:17 raspberrypi sh[362698]:   File "/home/squeaknode/squeaknode/venv/lib/python3.9/site-packages/squeaknode/node/squeak_node.py", >
Jun 01 17:58:17 raspberrypi sh[362698]:     from squeaknode.admin.webapp.app import SqueakAdminWebServer
Jun 01 17:58:17 raspberrypi sh[362698]:   File "/home/squeaknode/squeaknode/venv/lib/python3.9/site-packages/squeaknode/admin/webapp/app.py", >
Jun 01 17:58:17 raspberrypi sh[362698]:     from flask_login import current_user
Jun 01 17:58:17 raspberrypi sh[362698]:   File "/home/squeaknode/squeaknode/venv/lib/python3.9/site-packages/flask_login/__init__.py", line 16>
Jun 01 17:58:17 raspberrypi sh[362698]:     from .login_manager import LoginManager
Jun 01 17:58:17 raspberrypi sh[362698]:   File "/home/squeaknode/squeaknode/venv/lib/python3.9/site-packages/flask_login/login_manager.py", li>
Jun 01 17:58:17 raspberrypi sh[362698]:     from .utils import (login_url as make_login_url, _create_identifier,
Jun 01 17:58:17 raspberrypi sh[362698]:   File "/home/squeaknode/squeaknode/venv/lib/python3.9/site-packages/flask_login/utils.py", line 13, i>
Jun 01 17:58:17 raspberrypi sh[362698]:     from werkzeug.security import safe_str_cmp
Jun 01 17:58:17 raspberrypi sh[362698]: ImportError: cannot import name 'safe_str_cmp' from 'werkzeug.security' (/home/squeaknode/squeaknode/v>
Jun 01 17:58:17 raspberrypi systemd[1]: squeaknode.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by rootzoll** [comment]
Removing squeaknode visibly from v1.8.0 release (deactivating entry in SERVICES menu) - pushing to v1.8.1

**Comment by rootzoll** [comment]
@yzernik whats the status - can you help pn the error posted above. Otherwise I will push up to a later release.
