### ISSUE TITLE
LND alias

### ISSUE THREAD

**Issue by eurtnl** [raspiblitz/raspiblitz#264]
Hi there,

How can i add ⚡️ to my alias and is there a way to add a logo (.png) to the LND alias?

**Comment by rootzoll** [comment]
To keep things safe I recommend just basic characters. But you can try emoticons/UTF8symbols manual with `sudo nano /mnt/hdd/lnd/lnd.conf` and change in that file the `alias` string. Do restart after that.

I am not aware that it is possible to set an PNG for alias.
