### ISSUE TITLE
Loosing Network and waiting for DHCP although node is setup with Static

### ISSUE THREAD

**Issue by bitsam** [raspiblitz/raspiblitz#2640]
Just recently my Node has dropped off the network and has an error message, waiting for DHCP. Although I use a static IP address. the last time it happened, multiple reboots did not work and led me to do a full network check. However, I don't believe it is my network. I happened again just now and one reboot it came back up. What logs can I show to see why this is happening?

My node is still on v1.7.0, I'd like to know what is going on with this error before moving to v1.7.1

**Comment by bitsam** [comment]
I notice in the DEBUG.log that it refers to my configuration as dhcp=1, however in /etc/dhcpcd.conf I have set it to static. I can't see where to change the dhcp setting below.

*** NETWORK ***
localip=x.x.x.x
dhcp=1
network_device=eth0

**Comment by bitsam** [comment]
Thanks, I'll check it out. However the point is I don't want to rely on my
Node being given an IP address. I want to set the IP statically on the
node. Which I have done on many other raspi projects. The issue here is not
that my node has or has not a DHCP address. It is that RaspiBlitz has a
setting for DHCP which I can not see where I can disable this.

Reason I changed the dhcpd.conf was in some generic raspi instructions.
Maybe I have made an error in the .conf file I changed. Will also check
that out and post an update.

**Comment by bitsam** [comment]
> why did you have to edit dhcpd.conf, (dhcp daemon=server) that is for wifi 'AccessPoint' clients on a wifi hotspot, why would you want that on a bitcoin node ? it's /etc/dhcp/dhclient.conf at most, if the router isn't binding the node's ip address, you could set it there by adding eth0's mac address - sudo ifconfig eth0 and take note of its mac, that's all you need to get ip from dhcp server (router) , no ? but even that isn't required, especially since you have a static ip, i assume via router ip bind or dhcp reservation. just remove whatever you entered in dhcpd - sudo service networking restart &..see what gives

for the record, the official raspbian userguide states to change the IP address in the dchpd.conf file. Also I have been running a Raspiblitz node for over 2 years and never had this happen before.

https://www.raspberrypi.com/documentation/computers/configuration.html#static-ip-addresses

**Comment by rootzoll** [comment]
The `dhcp=1` value you describe in the debug log is from the command line output from `/home/admin/config.scripts/internet.sh status` in your selfconfig context the `dhcp=1` is maybe a bit missleading .. the script just checks if the blitz got an IP given from the local network or not - what is usally done by the DHCP:
https://github.com/rootzoll/raspiblitz/blob/5e074d0ccaeac8c6f1a54fc4bb12750244801bcf/home.admin/config.scripts/internet.sh#L78

The "waiting for DHCP" comes basically when no IP is given by the local network - see:
https://github.com/rootzoll/raspiblitz/blob/5e074d0ccaeac8c6f1a54fc4bb12750244801bcf/home.admin/_bootstrap.sh#L349

If you see that message your ethernet device is reporting an IP starting with `169.` what is usually a placeholder for local link before DHCP is able to give the device a local IP.
https://askubuntu.com/questions/660355/why-169-254-0-0-appears-by-default-in-the-routing-table

What is strange if you set a static IP on your device from the beginning. I am not sure what it means when in a static IP scenario the ethernet device drops back to a placeholder IP .. but from the link above it might also default to when there is an error to claim that static set IP maybe.

**Comment by bitsam** [comment]
Thank you for the update, and explanation of the dhcp=1 value. Can I add this info to the readme under troubleshooting?

**Comment by rootzoll** [comment]
> Can I add this info to the readme under troubleshooting?

Sure feel free to add this info in more detail to the FAQ by opening a PR.
