### ISSUE TITLE
Next Citadel update won't support the Umbrel migration script anymore

### ISSUE THREAD

**Issue by AaronDewes** [raspiblitz/raspiblitz#2642]
I'm currently focused on buiilding Citadel and can't implement a fix for this, but the next Citadel update will change the data layout by renaming the umbrel dir to citadel. This means the exisiting migration logic needs changes to work with Citadel.

**Comment by rootzoll** [comment]
Thanks for the heads up - will mark to adapt for next release. If possible can you please simply post links into your code where you make the changes?

**Comment by AaronDewes** [comment]
Basically, I just did 

```
mv /mnt/hdd/umbrel /mnt/hdd/citadel
```

Everything else is the same.

**Comment by rootzoll** [comment]
@AaronDewes just to ask are you also using the default password `moneyprintergobrrr` for the lnd wallet like umbrel since 0.3.9 or did you implemented changes to that part?

**Comment by rootzoll** [comment]
Added code changes for citadel for v1.7.2 .. to be tested with fresh sd card build.

**Comment by AaronDewes** [comment]
>  just to ask are you also using the default password moneyprintergobrrr for the lnd wallet like umbrel since 0.3.9 or did you implemented changes to that part?

I did implement some changes to the unlocking logic so lnd.conf is a bit different from Umbrel's default, but you seem to be overwriting it anyway, so it shouldn't matter.

The password stays the same though (currently). With the security changes we're discussing right now, I don't think a separate password for LND would still make sense in Citadel.

**Comment by rootzoll** [comment]
OK cool ... if you change something on that LND wallet password side give me a heads up so that I can adjust the migration procedure.

**Comment by AaronDewes** [comment]
Sure! Anything else would be vendor lock-in in my opinion by breaking migration logic of other systems.

**Comment by rootzoll** [comment]
Migrationtest from Citadel to RaspiBlitz looked good in testing ... closing issue for v1.7.2 release.

**Comment by cezars** [comment]
what is the default user and password wen u connect to the ssh ?

**Comment by AaronDewes** [comment]
> what is the default user and password wen u connect to the ssh ?

Please ask this somewhere else, not here. GitHub issues are mostly for tracking bugs, not questions. Also, it's not possible to know from your question if you're talking about RaspiBlitz, Umbrel or Citadel. Please ask at the appropriate place for the project you want to know this.

**Comment by cezars** [comment]
> Citadel

sry for posting here but i try to find all over the social media, its about Citadel because i use migrate function from umbrel  to citadel and its downloding all the node data again and i need to delete the umbrel node data. sry again for posting here but i really need help to delete the data and i cant connect via ssh to do so (first i made a mistake flashing nirvati-os and after this i flashed again citadel-os-v0.2.3)

**Comment by AaronDewes** [comment]
Please contact me at t.me/runcitadel or DM @runcitadel on Twitter (German or English).

Citadel does not have a migration system from Umbrel, you can not keep Umbrel data when moving to Citadel right now, so your data will be erased when setting up Citadel.
