### ISSUE TITLE
tRTL is not working

### ISSUE THREAD

**Issue by lessless** [raspiblitz/raspiblitz#2645]
Hi,

testnet RTL is now working because it's looking for macaroons at `/mnt/hdd/app-data/lnd/data/chain/bitcoin/testnet/` while they’re stored at `/mnt/hdd/lnd/data/chain/bitcoin/testnet/`

**Comment by openoms** [comment]
run 
`patch`
 for an update of tRTL.
 
 It is looking for the macaroons in `/home/rtl/.lnd/` where they are symlinked.
 
 Post the output of :
 
` sudo journalctl -n30 -u tRTL`
if the patch and reinstall does not fix it.

**Comment by openoms** [comment]
@lessless did you have this sorted?

**Comment by lessless** [comment]
Yup, everything is sorted. Thanks.
