### ISSUE TITLE
Message "statusscan blocked (124) - fallback to old results" while Syncing

### ISSUE THREAD

**Issue by gitrollo** [raspiblitz/raspiblitz#2646]
Hello everyone, I get this message while syncing. Is this a problem?
This message is displayed every few minutes. Syncing then stops for a few seconds.

![image](https://user-images.githubusercontent.com/92853565/138063298-21e05490-6f49-456c-9383-c266d37f829f.png)

**Comment by openoms** [comment]
no, it is not a problem. It is just the display script stopping for a few seconds, not the sync itself.

**Comment by rootzoll** [comment]
for v1.7.2 ... rename message to be less confusing.

**Comment by rootzoll** [comment]
This message will be gone with changing to the background scan process .. that will get merged from branch https://github.com/rootzoll/raspiblitz/tree/2388redis for v1.7.2 - closing issue.
