### ISSUE TITLE
Error running joinmarket tumbler 1st time (missing logs dir during install)

### ISSUE THREAD

**Issue by wilfredallyn** [raspiblitz/raspiblitz#2648]
After installing `v1.7.1`, I tried to run the joinmarket tumbler by calling `tumbler.py` but ran into this error

```
(jmvenv) joinmarket@node:~/joinmarket-clientserver/scripts $ python tumbler.py --help
Traceback (most recent call last):
  File "tumbler.py", line 193, in <module>
    main()
  File "tumbler.py", line 25, in main
    tumble_log = get_tumble_log(logsdir)
  File "/home/joinmarket/joinmarket-clientserver/jmclient/jmclient/taker_utils.py", line 219, in get_tumble_log
    fileHandler = logging.FileHandler(os.path.join(logsdir, 'TUMBLE.log'))
  File "/usr/lib/python3.7/logging/__init__.py", line 1092, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.7/logging/__init__.py", line 1121, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/home/joinmarket/joinmarket-clientserver/scripts/logs/TUMBLE.log'
```

The `FileNotFoundError` is caused because the `logs` directory (`/home/joinmarket/joinmarket-clientserver/scripts/logs`) is not created during installation.

I was able to run the tumbler after creating the directory (`mkdir /home/joinmarket/joinmarket-clientserver/scripts/logs`).

I believe that the problem is fixed by adding something along the lines of `sudo -u joinmarket mkdir /home/joinmarket/joinmarket-clientserver/scripts/logs` to the [joinmarket config script](https://github.com/rootzoll/raspiblitz/blob/v1.7/home.admin/config.scripts/bonus.joinmarket.sh).

**Comment by openoms** [comment]
Thank you for reporting!
That is strange all the logs should be in
`/home/joinmarket/.joinmarket/logs`
so this can be a joinmarket issue if reproducible.

Anyway please update joininbox to v0.6.2 and reinstall JM to v0.9.3.
