### ISSUE TITLE
The repair option "RESET-LND" leaves the node name of LND persistent

### ISSUE THREAD

**Issue by alaznem** [raspiblitz/raspiblitz#2650]
The repair option "RESET-LND" leaves the node name of LND persistent.

If the user does setup a new LND node, the old name is being taken, although a new name has been chosen by the user during LND setup.

I'm not completely sure if this is an issue for all services, but thunderhub didn't upgrade the listed nodes.

:question: If this is confirmed, could just changing the docs by adding the information to perform a LND -> NAME action after RESET-LND improve the situation already?

**Comment by rootzoll** [comment]
Makes sense to also reset the name on RESET-LND - will check for next release.

**Comment by rootzoll** [comment]
There is now a request for a new name before resetting the LND - see:
https://github.com/rootzoll/raspiblitz/blob/217c1766d2f46bc38c4cfbcf48dde84a928a5eec/home.admin/98repairMenu.sh#L120

Setting to final testing.

**Comment by openoms** [comment]
RESET-LND should offer the options to restore an LND wallet from rescue file / SCB or seed.
See: https://github.com/rootzoll/raspiblitz/issues/2832

**Comment by rootzoll** [comment]
Tested the reset of LND thru repair menu - it asks for a new name but has not set it.  `lnd.conf` shows after reset:
```
[Application Options]
# alias=ALIAS # up to 32 UTF-8 characters
```

**Comment by rootzoll** [comment]
OK name in lnd.conf is now set. Closing for release.
