### ISSUE TITLE
Filter bitcoind logs for .onion addresses

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2653]
see https://github.com/rootzoll/raspiblitz/issues/2639#issuecomment-950190651 and make sure that in future logs such onion addresses get filtered before output.

**Comment by nyxnor** [comment]
If possible to include related to this issue:
Filter Lightning logs for `balance`, `sat`/``btc` etc

**Comment by alaznem** [comment]
> see [#2639 (comment)](https://github.com/rootzoll/raspiblitz/issues/2639#issuecomment-950190651) and make sure that in future logs such onion addresses get filtered before output.

@rootzoll (and/or anyone reading this) : if you point me to the lines where the rpc password is being filtered and replaced with `****`, then I could try to make a pr with the onion filter which would output `****.onion` instead.

> If possible to include related to this issue: Filter Lightning logs for `balance`, `sat`/``btc` etc

However, I'm not sure if i can also add the lnd log filter as described by @nyxnor @ https://github.com/rootzoll/raspiblitz/issues/2653#issuecomment-950360368

**Comment by alaznem** [comment]
@rootzoll : hostname='XYZ' cointans also sensitive user data.

So to sum up what to filter to prevent users from exposing sensitive data to the public with uploading their debug files:

- **.onion addresses**
- **hostname='XYZ'**
- **balance, sat/``btc` etc**

**Comment by rootzoll** [comment]
All the debug output is happening in the following script:
https://github.com/rootzoll/raspiblitz/blob/v1.7/home.admin/config.scripts/blitz.debug.sh

**Comment by rootzoll** [comment]
It would make sense to write a special script (or a special parameter on blitz.debug.sh) that will filter-out all the sensitive data from a file and then apply this on the debug.log before outputting it to in the `debug` shortcut:
https://github.com/rootzoll/raspiblitz/blob/1b7f9d51d84dbdf1076ee8327f11ee9d3897159a/home.admin/_commands.sh#L117

**Comment by rootzoll** [comment]
redact nodeIDs
```
sed -i 's/[a-z0-9]*@/***@/' /var/cache/raspiblitz/debug.log
```
redact IPv4s
```
sed -i 's/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/*.*.*.*/' /var/cache/raspiblitz/debug.log
```
redact Onions
```
sed -i 's/[a-z0-9]*.onion/***.onion/' /var/cache/raspiblitz/debug.log
```
redact hostname
```
sed -i 's/hostname=[^\r\n]*/hostname=*****/'  /var/cache/raspiblitz/debug.log
```
redact balances
```
sed -i 's/[0-9]* mSAT/* mSAT/' /var/cache/raspiblitz/debug.log
sed -i 's/[0-9]*.[0-9]* BTC/* BTC/' /var/cache/raspiblitz/debug.log
```

**Comment by nyxnor** [comment]
great changes.
I don't think anyone uses debug for seeing the this information such as balance, so no compromises.

**Comment by rootzoll** [comment]
Testing looks good. Closing issue for v1.7.2 release
