### ISSUE TITLE
Move system monitoring into background loop

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2654]
At the moment the pi user is gathering alle the info for the display in a regular loop. This puts quite some load on the sytsem. The idea is to push that system monitoring loop into the background process that updates in different time intervals system values into the redis db. And the pi user running the infoscreen simply calls that values from the redis cache to display.

Having the pi user gathering the system infos with a lot of sudos creates lots of pam sessions & inflates the `auth.log`. This would be reduced because the background process is run by root and would not need sudo.

**Comment by david-bakin** [comment]
I thought the current system info stuff is stored, not in a db, but in files - `/var/cache/raspiblitz/info.{html,json}` - which are already stored in `tmpfs`.   I see nothing wrong with that.  Unless you're already running redis already (is that new to 1.7.1 or 1.7.2?), why change? (And even if you are running redis, why change?)

**Comment by rootzoll** [comment]
At the moment the raspiblitz.info is used for temp storage of system state and its still on the admin home dir. We disacussed moving it to the tmpfs but then decided to go a step forward by using an established cache system like redis. The idea behind the move from files to redis is to easier integrate with the coming backend API that is needed for the WebUI in v1.8. But maybe also @frennkie can elaborate on this further.

**Comment by rootzoll** [comment]
@david-bakin see https://github.com/rootzoll/raspiblitz/issues/88#issuecomment-471280122

**Comment by rootzoll** [comment]
Thats what being prepared in the following branch:
https://github.com/rootzoll/raspiblitz/tree/2388redis

**Comment by rootzoll** [comment]
OK this tested goff now over RCs .. closing issue for release.
