### ISSUE TITLE
Remove sudo from commands/scripts run as root

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2655]
as can be seen in the auth.log file .. also calling a command with sudo as root user causes an pam_session to open & close - this is not needed (because root does not need sudo) and commands/scripts should be checked to reduce sudo load on the system.

**Comment by rootzoll** [comment]
Checked scripts that are assumed to run by root should have a check for root user at the beginning and exit with error when run by another user.

**Comment by openoms** [comment]
This is likely cause of the occasional errors seen in logs:
```
sudo: unable to initialize PAM: Too many open files
sudo: unable to initialize PAM: Too many open files
```
and the plebty of PAM warnings in `sudo journalctl -f`

**Comment by rootzoll** [comment]
A lot of sudo removal especially during setup/provision is done in the following branch:
https://github.com/rootzoll/raspiblitz/tree/2388redis

**Comment by rootzoll** [comment]
All seems to work fine with the reduced sudos .. closing issue for release.
