### ISSUE TITLE
[x86] Manual choice of a partition to be mounted as /mnt/hdd

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#2656]
As discussed in https://github.com/rootzoll/raspiblitz/issues/2104#issuecomment-950288141
working with different platforms including VMs the biggest problem seems to be automating which disk / volume / partition to choose to become `/mnt/hdd`.
For X86 we could avoid this by offering a manual step (with some dialog help) to choose from the available disks and make sure no boot or OS partition is getting overwritten.

I remember @nyxnor mentioned a tool to help listing the available partitions in a dialog like interface already, but can't find it now.

**Comment by nyxnor** [comment]
I did not find it also but here is a minimal script:
```sh
mountable="$(lsblk -lp -o NAME,SIZE,TYPE,MOUNTPOINT | grep "part  $" | grep -v "K part\|M part" | awk '{print $1, $2}')"
mount_ask=$(dialog --menu "Use spacebar to select" 10 50 2 ${mountable} 2>&1 >/dev/tty)
```
It greps unmount partitions which are not measured in Kilobyte or Megabite, so either Gigabyte or Terabyte will do.
Maybe print LABEL to now which contains the BLOCKCHAIN label.

Also check this
https://github.com/LukeSmithxyz/voidrice/blob/2ddfa7ab0f2597b26be9872e37d7374b75a72678/.local/bin/dmenumount#L53
```sh
lsblk -rpo "name,type,size,mountpoint" | grep 'part\|rom' | awk '$4==""{printf "%s (%s)\n",$1,$3}'
```

**Comment by nyxnor** [comment]
Found the [comment](https://github.com/rootzoll/raspiblitz/issues/1500#issuecomment-919101678), [project](https://github.com/SL-RU/ranger_udisk_menu).
But looking at it, python is unecessary if I can do the same with dialog/whiptail and shell

**Comment by openoms** [comment]
Instead of a manual choice the logic for now is to use the second (nonOS) disk if running on x86_64 including VMs.
