### ISSUE TITLE
Extremely large logs that don't seem to be rotating.

### ISSUE THREAD

**Issue by david-bakin** [raspiblitz/raspiblitz#2659]
RaspiBlitz 1.7.0 - but running bitcoind v22.

I have extremely large logs that don't seem to be rotating.

The files `syslog.1`, `auth.log.1`, and `daemon.log.1` start with entries at Sep-28 - about 3 weeks ago at this point, which is when I last rebooted.

Not sure what else you'd like for debugging purposes ... let me know if there's something I can add (also I'm not sure what `/var/log` _should_ look like on a raspiblitz with properly functioning log rotate...)

Attached files:

- [`debug.log`](https://github.com/rootzoll/raspiblitz/files/7406190/debug.log)
- [`logrotate` service status](https://github.com/rootzoll/raspiblitz/files/7406191/logrotate.status.txt)
- [`ls -l` of `/var/log`](https://github.com/rootzoll/raspiblitz/files/7406192/ls-of-var-log.txt)
- [`rsyslog` service status](https://github.com/rootzoll/raspiblitz/files/7406193/rsyslog.status.txt)

**Comment by rootzoll** [comment]
v1.7.1 updates the log rotate policies ... please check if an update to v1.7.1 solves your issue

**Comment by ChuckNorrison** [comment]
I also ran out of disk space with those files in /var/log. Journal was also 1GB big. In my case my daemon, syslog and auth log was at 2GB each and with 15GB overall my sd card was full. Deleted the files and restarted rsyslog to fix the problem for now. 

this should help for the journal part:

 `sudo journalctl --vacuum-size=100M`

Iam already running v1.7.1

**Comment by rootzoll** [comment]
Thanks. Will revisit this issue for v1.8 release.

**Comment by rootzoll** [comment]
Found some ways to reduce log load in the future:

Some apps like mempool have a heavy debug logging - have to go deeper there for v1.8.1
```
May 17 17:26:10 raspberrypi node[248305]: May 17 17:26:10 [248305] DEBUG: New mempool size: 4161 Change: 10
May 17 17:26:10 raspberrypi node[248305]: May 17 17:26:10 [248305] DEBUG: Mempool updated in 0.288 seconds
May 17 17:26:12 raspberrypi node[248305]: May 17 17:26:12 [248305] DEBUG: Updating mempool
May 17 17:26:12 raspberrypi node[248305]: May 17 17:26:12 [248305] DEBUG: Fetched transaction 1 / 8
```

Also the `00infoBlitz.sh` has still some sudo calls to gather information - those also produce quite some logging footprint in the auth.log - for v1.8.1 those information gatherings should move into the background script (where sudo is not needed) and infodisplay should just get values from cache. Also makes sense for the WebUI to get access to those status informations.

**Comment by myxmaster** [comment]
Why are those logs on the SD at all? Can't they be moved to the SSD by default like other logs?

**Comment by rootzoll** [comment]
Considering that the SSD is/might not always be connected/available so far we did not moved the logs.
