### ISSUE TITLE
check tune2fs to optimize ext4 settings

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2666]
Maybe push to v1.9 for data storage optimizations

https://www.systutorials.com/docs/linux/man/8-tune2fs/
https://www.unixtutorial.org/commands/tune2fs

**Comment by dipunm** [comment]
This should be closed now right?

**Comment by rootzoll** [comment]
tune2fs gets applied on ext4 data drives here: 
https://github.com/rootzoll/raspiblitz/blob/6a677a6baacc98a89d99bf93cf9e7053dabfebd5/home.admin/config.scripts/blitz.datadrive.sh#L784
