### ISSUE TITLE
Opening service page installs RTL

### ISSUE THREAD

**Issue by corbelantoine** [raspiblitz/raspiblitz#267]
The screen won't display anything and then starts to install RTL when any key is pressed.
Tor is also going to be uninstalled because of a "configuration change". However Tor is set to "on" in the raspiblitz conf.

Please note raspi has been recovered from disk after reinstalling the image on the sd card.

**Comment by rootzoll** [comment]
I will give the service menu a test run after recover sd card, when I do final release tesing - see if I can reproduce. Thx.

**Comment by rootzoll** [comment]
I recoverd by SD card and the service menu is runnig fine. This issue seems fixed or is not reproducable. I am closing the the issue.
