### ISSUE TITLE
LND Wallet locked after upgrade to 1.7.1

### ISSUE THREAD

**Issue by ronledfordjr** [raspiblitz/raspiblitz#2675]
I upgraded three nodes to 1.7.1 and one node is struggling.

https://termbin.com/7l9g

![2021-10-28_07-21](https://user-images.githubusercontent.com/79236343/139254479-d33e51b1-e454-41a7-b60e-61affa7cccd6.png)

Is reflashing the SD and starting over the answer? Did I input the wrong Password C?

**Comment by GitmoBTC** [comment]
I ran into this same issue while upgrading to 1.7.1, see here: https://github.com/rootzoll/raspiblitz/issues/2652. Will keep an eye on this thread for a solution, and I'll let you know if I find one.

**Comment by ronledfordjr** [comment]
Now Blockchain hungup on restart.

I deactivated the Auto-Unlock feature in Settings and now it stops at restarts on the blockchain.

https://termbin.com/yl6v

![2021-10-29_04-28](https://user-images.githubusercontent.com/79236343/139411942-c3789807-6714-4e5b-a98b-3a1a9199d9b8.png)
.

**Comment by ronledfordjr** [comment]
For some reason Telegram freezes when I attach files.

![2021-10-29_06-01](https://user-images.githubusercontent.com/79236343/139424749-93dfb849-82bf-42f2-9ee6-eab88f33a90d.png)

![2021-10-29_06-02](https://user-images.githubusercontent.com/79236343/139424760-fac536a9-e756-4b98-9603-fc19d83d641a.png)

![2021-10-29_06-02_1](https://user-images.githubusercontent.com/79236343/139424771-94a3b07b-3e96-4d76-a373-d6138e556dc9.png)

![2021-10-29_06-04](https://user-images.githubusercontent.com/79236343/139424781-ba6b9d40-6291-461b-af6c-ece6c91d479c.png)

**Comment by openoms** [comment]
Did you try to reflash this node with the 1.7.1 image dated `2021-10-28` ? Might be the quickest way to fix things,

**Comment by ronledfordjr** [comment]
I will this weekend. My day gig gets in the way of what's important. 😎

**Comment by ronledfordjr** [comment]
Thanks for help. Node is running but without funds. I just used Seed Phrase to rebuild LND Wallet since it worked recovering funds before.

**Comment by ronledfordjr** [comment]
Thanks and I will try this tonight.

**Comment by ronledfordjr** [comment]
Reset LND, however, still no funds. Is it worth my time to Repair Options>Reset-LND? Or, just do a fresh install and attempt to use SEED Phrase again?

**Comment by openoms** [comment]
The seed phrase only recovers the onchain funds and can also be used in BlueWallet.
To recover from seed and SCB or ln-rescue file start with a new SDcard.

If you run into errors see this: https://github.com/rootzoll/raspiblitz/issues/2639#issuecomment-958021833

**Comment by ronledfordjr** [comment]
I appreciate all of the advice on this issue. I reverted back to 1.7.0 and the seed phrase worked when I created wallet. Now I am going to send the funds to cold storage and then upgrade to 1.7.1.
