### ISSUE TITLE
RESEARCH: enable blockchain fast-sync 

### ISSUE THREAD

**Issue by fluidvoice** [raspiblitz/raspiblitz#268]
this is just to doc discussion on this enhancement. To allow running the node in pruned mode to allow potentially faster blockchain syncing and the use of a smaller/cheaper USB drive instead of large HDD/SD

this would need adding the following parameter to the **bitcoind** service startup:
-prune=100000 (~1 year of blocks - 100GB storage)
-prune=50000 (~6 months of blocks - 50GB storage)
-prune=25000  (~3 months of blocks - 25GB storage)
-prune=5000  (~2 weeks of blocks - 5GB storage) 

I'm assuming as of now that the time a LN channel is open needs to be less than the prune limit.
  If so, prune=50000 would mean once every 6 months close and re-open long term channels, which is not too bad.  
  Prune=5000 would allow bringing a node up quickly, but you'd want to download via torrent or FTP, probably on a different machine, a bigger blockchain snapshot and install it.  A script to automate this would be great.

NOTES: 
Pruning is only performed on the tail end (most recent) part of the blockchain. The node still must download and verify the entire history of the blockchain. So there is no time saved, only space.
In order to save sync time, a validated and already pruned chain would need to be downloaded and copied/installed (ie, from a trusted entity).  This is supposedly what the BTCPay server implementation does.
BTCPay server uses "fast-sync", which is turned off by default, to speed it up. This supposedly copies the chain from an already synced pruned node. See their notes, disadvantages, etc: https://github.com/btcpayserver/btcpayserver-docker/tree/master/contrib/FastSync

**Comment by rootzoll** [comment]
related to issue #215

**Comment by rootzoll** [comment]
Instructions on FastSync and Raspberry:
https://github.com/btcpayserver/btcpayserver-doc/blob/master/RaspberryPiDeployment.md

**Comment by ppachur** [comment]
I've been running lnd on top of a pruned bitcoind (latest arm-binary versions) and ran into the problem that once the block containing the funding-TX of any channel is pruned, lnd won't start anymore. Unfortunately, if you prune old blocks, sooner or later you will run into this problem.

If this happens, log output looks like this:
`lnd            | 2019-01-17 08:36:31.310 [INF] CRTR: Syncing channel graph from height=555566 (hash=0000000000000000000efd7e2f7d488aabb71ad045c8b90238899372342709f3) to height=558874 (hash=0000000000000000001765d76919f2934ceac78b5102819944088c9d4bb84282)
lnd            | 2019-01-17 08:36:31.313 [ERR] SRVR: unable to start server: -1: Block not available (pruned data)
lnd            | 
lnd            | 2019-01-17 08:36:31.313 [INF] LTND: Shutdown complete
lnd            | -1: Block not available (pruned data)`

-> Until LND is somehow able to handle this, don't do it. ;)

**Comment by fluidvoice** [comment]
> I've been running lnd on top of a pruned bitcoind (latest arm-binary versions) and ran into the problem that once the block containing the funding-TX of any channel is pruned, lnd won't start anymore. Unfortunately, if you prune old blocks, sooner or later you will run into this problem.
> 
> If this happens, log output looks like this:
> `lnd | 2019-01-17 08:36:31.310 [INF] CRTR: Syncing channel graph from height=555566 (hash=0000000000000000000efd7e2f7d488aabb71ad045c8b90238899372342709f3) to height=558874 (hash=0000000000000000001765d76919f2934ceac78b5102819944088c9d4bb84282) lnd | 2019-01-17 08:36:31.313 [ERR] SRVR: unable to start server: -1: Block not available (pruned data) lnd | lnd | 2019-01-17 08:36:31.313 [INF] LTND: Shutdown complete lnd | -1: Block not available (pruned data)`
> 
> -> Until LND is somehow able to handle this, don't do it. ;)

This may be a clue: https://github.com/lightningnetwork/lnd/issues/2292#issuecomment-445365251

> "BTCPay made nodes without a seed, as a result, we don't know what the wallet's birthday is and are forced to rescan from genesis. Bitcoind doesn't have the blocks we need, so the rescan will fail"
> **2018-12-07 12:36:37.646 [ERR] LNWL: Unable to complete chain rescan: -1: Block not available (pruned data)**

I don't know what he means here by node seed and wallet birthday.  I kinda get what he's talking about but he does not explain how to remedy the problem.  How to properly create the node w/seed.

**Comment by fluidvoice** [comment]
And also this: https://github.com/ElementsProject/lightning/issues/2250#issuecomment-453799099

> So on BTCPay side, I solved it by just waiting everything is fully synched before starting c-lightning or LND.
> 
> That said, there are several problems with my solution:
> 
> Old channels can't be properly validated
> If the LN wallet need a rescan, it will get stuck without any possibility for me to fix the situation just by resynching bitcoin core
> I will let other c-lightning or LND people opening an issue about it, as they have probably a better idea about how they would like such bitcoin core feature to be exposed than me.

**Comment by fluidvoice** [comment]
So perhaps stop the lnd service and restart it after bitcoind is fully synced.  Just a test to see if lnd will start that way or not with the same error?

**Comment by ppachur** [comment]
@fluidvoice my problem was a bit different. :)

Initially, everything worked well, but after the backend (bitcoind) pruned the block in question, lnd would not start anymore. 
I was able to recover the lnd by replacing the backend bitcoind with a full node (no pruning).

That said: Enabling pruning in bitcoind will lead to lnd not being able to start once the block has been pruned. So according to above calculations:If you set prune=5000, your node will fail to restart after ~2 weeks (which somewhat correlates with my observations.;))

**Comment by fluidvoice** [comment]
I understood what the problem was.  You need to read those other issues to see how the problem can be worked around.  BTCPay server has figured out how to do it.

**Comment by fluidvoice** [comment]
> @fluidvoice my problem was a bit different. :)
> 
> Initially, everything worked well, but after the backend (bitcoind) pruned the block in question, lnd would not start anymore.
> I was able to recover the lnd by replacing the backend bitcoind with a full node (no pruning).
> 
> That said: Enabling pruning in bitcoind will lead to lnd not being able to start once the block has been pruned. So according to above calculations:If you set prune=5000, your node will fail to restart after ~2 weeks (which somewhat correlates with my observations.;))

Yeah understood. I don't think it's wise to set pruning lower than 50000 (about six months).


But I think there may be other ways to speed up the syncing other than pruning.  
Like using the bitcoind `-assumevalid` argument:
https://bitcoincore.org/en/2017/03/08/release-0.14.0/#assumed-valid-blocks
**BTCPay server has a "fastsync" feature that I think is using another method:**
https://github.com/btcpayserver/btcpayserver-docker/tree/master/contrib/FastSync

**-assumevalid**

> **...will skip verifying signatures in the blocks before the assumed valid block. Since verifying signatures consumes a lot of CPU during IBD, using assumed valid blocks can significantly speed up IBD. All blocks after the assumed valid block will still have their signatures checked normally.**


> New users to Bitcoin probably won’t know about any valid blocks, but they probably also won’t know all the consensus rules—so they can simply use the copy of the full node software they download. Bitcoin Core 0.14.0 ships with a default assumed valid block that is set during the release process by having multiple well-known developers each confirm that a certain block is known to be valid by them (example).
> 
> Anyone who wants to verify all signatures using Bitcoin Core can still do so by starting the program using -assumevalid=0. Anyone who wants to specify an alternative assumed valid block can specify the block identifier as a parameter to assumevalid; for example:
> 
> -assumevalid=00000000000000000013176bf8d7dfeab4e1db31dc93bc311b436e82ab226b90
>
> The default assumed valid block in Bitcoin Core 0.14.0 is #453354, 16 Februrary 2017, with hash 00000000000000000013176bf8d7dfeab4e1db31dc93bc311b436e82ab226b90.

**Comment by fluidvoice** [comment]
tested on my notebook.  It doesn't look like it speeds up the sync. My internet connection is maxed out and the bitcoin DB being created seems progressing at a speed similar to before.   I'm guessing this is why BTCPay server does not use this technique for their "fastsync" feature.

Appended to **bitcoin.conf**:
```
/# Assume valid block number 534292 on 2018-07-29 0000000000000000002e63058c023a9a1de233554f28c7b21380b6c9003f36a8
assumevalid=0000000000000000002e63058c023a9a1de233554f28c7b21380b6c9003f36a8
```
When starting up bitcoind the output shows:

> 2019-01-25 12:48:59 Assuming ancestors of block 0000000000000000002e63058c023a9a1de233554f28c7b21380b6c9003f36a8 have valid signatures.

**Comment by fluidvoice** [comment]
> assumevalid only disables script verification as that is expensive. Everything else (PoW, UTXOs, merkle root, etc.) is still checked. – Andrew Chow♦ Jan 18 at 4:53

**Comment by fluidvoice** [comment]
So I think perhaps the first step is for people to download the BTCPay UTXO snapshot.  And perhaps @rootzoll should create a torrent for this so we don't all add traffic to this server. We can then experiment/test with starting up using this, then later script can be created to automate (as BTCPay does). It looks like all you do is download then extract the tar file to your bitcoin data directory, then restart? I need to verify. Seems like there must be more to it than that.

/# you can run this multiple times to resume a broken/failed download...
/mnt/hdd/download $ `sudo wget http://utxosets.blob.core.windows.net/public/utxo-snapshot-bitcoin-mainnet-551636.tar --show-progress --continue`

> --2019-01-25 07:04:25--  http://utxosets.blob.core.windows.net/public/utxo-snapshot-bitcoin-mainnet-551636.tar
> Resolving utxosets.blob.core.windows.net (utxosets.blob.core.windows.net)... 52.239.160.170
> Connecting to utxosets.blob.core.windows.net (utxosets.blob.core.windows.net)|52.239.160.170|:80... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 3550351360 (3.3G) [application/x-tar]
> Saving to: ‘utxo-snapshot-bitcoin-mainnet-551636.tar’
>

**Comment by fluidvoice** [comment]
@rootzoll this page explains how to create your own fast-sync UTXO snapshot from an already running full node, which would be good for various reasons but importantly for seeding the torrent: https://github.com/btcpayserver/btcpayserver-docker/tree/master/contrib/FastSync
This script shows details:
https://github.com/btcpayserver/btcpayserver-docker/blob/master/contrib/FastSync/save-utxo-set.sh

**Comment by rootzoll** [comment]
@fluidvoice After version 1.0 release this can be a topic to get deeper into - much thanks for the research so far.

**Comment by geco91** [comment]
recommend to be added to the 1.1 milestone

**Comment by fluidvoice** [comment]
> IBD on Clearnet with Tor activated for Lightning went well, in 2days 2 hours on my RPi4 4gb + SSD: https://twitter.com/openoms/status/1162118831965446145.
> 
> Only concern was that, when the IBD finished the LND was restarted and waited to finish the blockchain scan until unlocked again. This added hours to have LND ready because it needed to scan the last ~5 percent of the blockchain. Ideally both bitcoin and LND sync should finish before restarting the services to put bitcoin behind Tor too or maybe wait for a manual trigger and keep in sync until looked at?

For usability I think having to wait 2 days before you can do anything is a big **downer**. Long term I still wonder if we could implement something like BTCPay's Fast-sync to get the node up and usable as fast as possible, and do a IBD/full-sync in the background or while the fast-synced (pruned) node is running.  Once the full-sync is complete the system can be restarted to activate that. See this [Enable fast-sync research thread](https://github.com/rootzoll/raspiblitz/issues/268#issuecomment-457614871).
So for example prompt to do either the fast-sync installation or full-sync.  And fast-sync can be marked "experimental" at first.  And **note importantly the idea is that a fast-sync turns into a full-sync node once the IBD is finished.** 
 Raspiblitz could create it's own UTXO snapshot for this which should be similar to BTCPay's at around 3.5GB size and perhaps that can be downloaded via torrent?  So the time to get the node online would only be about the time to download this 3.5GB and the SD-card image.
  A lot of testing would have to go into this ;-) naturally since you'd need to make sure any wallet created while in the pruned state still works once the node turns into full-sync. It might require re-creating the old wallet from backup?  I don't know how the DB changes.  May be too much work right now.

**Comment by rootzoll** [comment]
I think such a feature like running on neutrino while validating the full blockchain in the background have to come from bitcoin core itself. I would love to so have it .. but it would eat up much dev time and can be a bigsource for error. With the RP4 we are now in a area that self-sync is possible and I would like to get rid of downloading prepared blockchains or UTXO sets as much as possible from now on. Any optimizaton on that should now come from the bitcoin core itself.
