### ISSUE TITLE
BTCPayServer Update

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2682]
https://blog.btcpayserver.org/btcpay-server-1-3-0/

**Comment by openoms** [comment]
tested working on v1.7.1 with a simple reinstall after editing the version in the script

**Comment by openoms** [comment]
To update BTCPayServer to v1.3.3:
```
# download new btcpay install script
wget https://raw.githubusercontent.com/openoms/raspiblitz/git-verify-everywhere/home.admin/config.scripts/bonus.btcpayserver.sh -O config.scripts/bonus.btcpayserver.sh

# download the PGP verification script
wget https://raw.githubusercontent.com/openoms/raspiblitz/git-verify-everywhere/home.admin/config.scripts/blitz.git-verify.sh -O config.scripts/blitz.git-verify.sh
# make it executable
chmod +x config.scripts/blitz.git-verify.sh 

# run the update
config.scripts/bonus.btcpayserver.sh update
```

Included in PR:  https://github.com/rootzoll/raspiblitz/pull/2708

**Comment by farahats9** [comment]
It would be nice if we could get the latest version 1.4.x for the new UI overhaul.
The only difference in the script I think is upgrading dotnet from v3.1 to v6.0

**Comment by openoms** [comment]
we are updating to the latest, see the CHANGES.md

**Comment by rootzoll** [comment]
Yes BTCPay will come on version v1.4.4.0  with the v1.7.2 Raspiblitz ... closing issue for release.
