### ISSUE TITLE
RESET-LND doesn't create a new wallet

### ISSUE THREAD

**Issue by grnqrtr** [raspiblitz/raspiblitz#2685]
Selecting RESET-LND asked me to setup a new alias, but that was it, it didn't walk me through setting up a new wallet or anything. It seems like all it did was wipe the old lnd and set a new alias.

It looks like the RESET-LND option is supposed to run `/home/admin/70initLND.sh` but that script doesn't even seem to exist.

**Comment by openoms** [comment]
Will try to reproduce. Just to confirm:
Are you running v1.7.1 and updated by reflashing the SDcard?

Also please try running:
`patch`
and see if the issue persists.

**Comment by grnqrtr** [comment]
Sorry, yes, v1.7.1 on a new SDcard. I actually had already ran `patch` to fix a different issue.

**Comment by openoms** [comment]
Yes, instead of 
`home/admin/70initLND.sh` 

it should be
```
/home/admin/config.scripts/lnd.install.sh on mainnet initwallet
```

Will test the fix, but you could try now.

Can display the new seed afterwards with:
```
sudo /home/admin/config.scripts/lnd.install.sh display-seed mainnet
```

**Comment by grnqrtr** [comment]
This did work to create a new wallet, but what I actually wanted to do was restore a wallet from seed. It seems like it should give you that option like it does when first initializing a new node?

**Comment by openoms** [comment]
Will need to ping @rootzoll here because that seem to need user flow not present currently in the new setup process.

What you can do now is to delete the existing wallet:
**DANGER** `sudo rm -rf /mnt/hdd/lnd/data` **DANGER**
and use:
`lncli create`

or might just make sense to reflash the SDcard and start new by restoring the seed (this flow exists now).

**Comment by grnqrtr** [comment]
As always, thanks for the help @openoms!
