### ISSUE TITLE
IP2TOR Subscription Failing

### ISSUE THREAD

**Issue by doccodez** [raspiblitz/raspiblitz#2689]
When attempting to use any bridge the subscription fails after payment is sent? "Error: Fail on subscription storage" ![image](https://user-images.githubusercontent.com/14829495/139591575-43c101ef-eb57-409a-9b38-6445892905fb.jpeg)![image](https://user-images.githubusercontent.com/14829495/139591579-0da4bce5-9a73-43e0-991e-7d02475527e3.jpeg)

**Comment by rootzoll** [comment]
On the first view this seems to be a local issue because it has problems of storing the subscription to the toml file.
Can you take a look if the following file already exists `/mnt/hdd/app-data/subscriptions/subscriptions.toml` and if yes if contains text data .. can you check if its valid toml with validators like this: https://www.toml-lint.com

Another thing to check is also the amount of free space on the HDD ... what does "HDD use" on the LCD display say?

**Comment by doccodez** [comment]
The HDD use is at 456GB (27%) so that doesn't seem to be the issue. However, the subscriptions.toml file is not there. @rootzoll

**Comment by openoms** [comment]
is this solved? IP2Tor subscriptions are tested ok. Did you lose any sats @cubanhodl ?

**Comment by doccodez** [comment]
This is not solved and I did in the process of attempting to open a bridge. It would pay the invoice and then attempt to open the bridge before getting the error above. @rootzoll @openoms

**Comment by rootzoll** [comment]
> However, the subscriptions.toml file is not there.

Maybe its a problem with the script not being able to write into `subscriptions` directory. @cubanhodl can you post the result of the following command:
```
sudo ls -la /mnt/hdd/app-data | grep subscriptions
```

**Comment by frennkie** [comment]
@cubanhodl the Subscription was created on Oct. 31th and ran for 24 hours. So I believe that @rootzoll 's idea is right: Please check the file/directory permissions on the path where the subscriptions are saved.

**Comment by doccodez** [comment]
This is the result of that command.
drwxr-xr-x  2 bitcoin     bitcoin     4096 Jun 23 21:36 subscriptions

@rootzoll

**Comment by rootzoll** [comment]
@cubanhodl can you run a `sudo chown admin:admin /mnt/hdd/app-data/subscription` and then check again if subscriptions can be created?

**Comment by rootzoll** [comment]
OK for v1.7.2 I added a command that on bootstrap the `/mnt/hdd/app-data/subscriptions` directory will always be set to owner admin. Hope this prevents such errors in the future ... closing for v1.7.2 release.
