### ISSUE TITLE
TOR Exit Node?

### ISSUE THREAD

**Issue by qx4p** [raspiblitz/raspiblitz#270]
After activating TOR i saw that the torrc file doesn't contain `ExitPolicy reject *:* `. Does this mean that I'm running a full TOR Exit Node now? I don't want my private internet connection to be used for any illegal stuff. Can I just add `ExitPolicy reject *:* ` to torrc and be safe? Maybe this should be the default configuration?

**Comment by rootzoll** [comment]
As of the manual ... 
https://www.torproject.org/docs/tor-manual.html.en
... adding "ExitRelay 0" to the config, should be the safest way to make sure Exit-Traffic is off.
I added it to the default config of RaspiBlitz.
