### ISSUE TITLE
After reflashing 1.7.1 - 90% of my channels disconnected and every rebalance shows error insufficient_balance

### ISSUE THREAD

**Issue by agd-media** [raspiblitz/raspiblitz#2704]
WIth version 1.7.0 everything was fine. Now after the update when I start the Raspiblitz most of the channels  are online and active. After a few hours 90% of my channels are offline. I have to restart the hardware (which takes at least double as longer than with version 1.7.0) to bring back the channels into an active state. Bos reconnect doesn't work here.
Rebalances are not successful. Always ends with error: "Insufficient_balance", even though I have enough balance in the channels.

Edit: Tor isn't connecting, which could be the reason for the errors. lnd.log shows ttl expired and general socks failure.
Edit2: After a hardware restart, tor.log shows

```
Nov 08 14:00:13 raspberrypi tor[936]: Nov 08 14:00:13.000 [notice] Bootstrapped 100% (done): Done
Nov 08 14:00:16 raspberrypi tor[936]: Nov 08 14:00:16.000 [warn] Failed to find node for hop #1 of our path. Discarding this circuit.
Nov 08 14:00:17 raspberrypi tor[936]: Nov 08 14:00:17.000 [notice] Our circuit 0 (id: 132) died due to an invalid selected path, purpose Hidden service: Establishing introduction point. This may be a torrc configuration issue, or a bug.
Nov 08 14:01:13 raspberrypi tor[936]: Nov 08 14:01:13.000 [notice] No circuits are opened. Relaxed timeout for circuit 92 (a General-purpose client 3-hop circuit in state waiting to see how other guards perform with channel state open) to 60000ms. However, it appears the circuit has timed out anyway.
```
Edit3: Updating Tor now ...
Edit4: After updating Tor, everything seems to be running stable.

**Comment by rootzoll** [comment]
@nyxnor @openoms was there any problem with a tor update in v1.7.1? Any similar reports on the support chats?
Something to be addressed for the v1.7.2 released here?

**Comment by nyxnor** [comment]
no similar reports to investigate

**Comment by rootzoll** [comment]
OK .. no similar reports since two weeks. Closing issue - but anybody that will run into the same please report still so that we can reopen.
