### ISSUE TITLE
How to exit the status screen to use the shell?

### ISSUE THREAD

**Issue by got3nks** [raspiblitz/raspiblitz#2710]
I misconfigured the firewall on my Raspiblitz and now can't log in through SSH.

I plugged in the HDMI port to a monitor but whenever I plug in a USB keyboard the input goes to the LCD screen (which is showing the status of the node) so any command is ignored (I tried CTRL+C without luck).

How do I exit from the status screen to be able to execute commands?

**Comment by nyxnor** [comment]
> I misconfigured the firewall on my Raspiblitz and now can't log in through SSH.

Flash the sd card, it is not possible to advise if we don't know what you did with it.

**Comment by got3nks** [comment]
I found a workaround: after shutting down the Raspberry I unplugged the SSD drive and then powered on again. Since Raspiblitz fails to boot and start its processes, I was able to login as root and use the shell through the LCD screen output. 

Probably a _SIGINT_ handler should be added in the process used to show the status on the LCD monitor to prevent this issue.

I think flashing the SD card is the very last resort when you use your Rpi not only as a Bitcoin node but you do a bunch of stuff with it.

**Comment by rootzoll** [comment]
TODO: When [ssh.reset](https://github.com/rootzoll/raspiblitz/blob/v1.7/FAQ.md#how-can-i-repair-my-ssh-login) is used also make sure to open firewall port.

**Comment by got3nks** [comment]
> TODO: When [ssh.reset](https://github.com/rootzoll/raspiblitz/blob/v1.7/FAQ.md#how-can-i-repair-my-ssh-login) is used also make sure to open firewall port.

Although that's a good idea, it would still require to remove the SD card from the Raspberry. Wouldn't be possible to use something like this in the 00infoLCD.sh script?

```
quit() {
  echo "SIGINT or SIGTERM received, exiting..."
  kill -9 $$
}

trap quit INT
trap quit TERM
```

**Comment by rootzoll** [comment]
@got3nks tried to trap those signal in the `00infoLCD.sh` but was still not able to exit that loop with connected USB keyboard. 

If you searching for a way "to shutdown" the device there is the idea to detect if the LAN cable is getting removed and to use that as a signal to shutdown. Would that be a future solution?

TODO in this ticket:
- [x] check ssh port open when ssh.reset file is detected
- [x] check if the trap mechanism help to break loop during setup/sync (already in branch)

**Comment by got3nks** [comment]
The point is there is no way to interact with the OS when the LCD screen is connected. If we can break from the loop and be able to use a keyboard would be much better than having to remove the SD card from the Raspberry to fix the filesystem.

**Comment by openoms** [comment]
From an adversarial point of view it is good that you cannot interact with the node without knowing the password or switching off.
That means the passwords and secrets only stored in the memory are flushed and the funds are safer against malicious physical access.
This is intentional.

**Comment by rootzoll** [comment]
Exiting the status screen with CTRL+c is now orking again. Closing issue for release.
