### ISSUE TITLE
Block Explorer missing after 1.7.1 Update (migration)

### ISSUE THREAD

**Issue by velgard1** [raspiblitz/raspiblitz#2714]
If it really is it is only a minor issue, but I wanted to report it anyway.
After an issue with BTRFS I waited for the new release and used a migration file to setup 1.7.1 without BTRFS.
After syncing I checked all services I had used (e.g. Mempool Explorer) and wondered that I was not able to connect to the Block Explorer.
I then realized that the service was not mentioned within the menu and therefore it was not installed - installation worked and I could use it afterwards as before.

**Comment by rootzoll** [comment]
Thanks for the report ... will check if recovering is still functioning for blockexplorer on next v1.7.2 release.

**Comment by rootzoll** [comment]
OK did a test with the v1.7.2rc1d and BlockExplorer gets installed correctly on recover/update.

**Comment by velgard1** [comment]
Thanks, I hope I don't have to migrate next time, but it's good to know that it should work.
