### ISSUE TITLE
LCD won't show status screen (stuck at 100% on blue screen)

### ISSUE THREAD

**Issue by dantrauner** [raspiblitz/raspiblitz#2717]
Has anyone else encountered this before? I updated to 1.7.1 recently and seem to be synced with the blockchain, but the LCD won't switch away from the "in-progress" screen to the usual black status screen.

![screen](https://user-images.githubusercontent.com/1462423/141705332-f11c237d-3c32-4278-9a03-6f24623c25a7.jpg)

**Comment by openoms** [comment]
login with ssh as it shows and restart from.the menu

**Comment by dantrauner** [comment]
Definitely tried that first — doesn’t seem to work. What script bootstraps the LCD? I figured maybe there’s a problem with that and running it manually/debugging there would help.

**Comment by dantrauner** [comment]
I just reflashed the SSD in the end and the issue is obviously now gone, but I guess this is some kind of edge case bug. I'll try to debug more thoroughly if I ever see it again.
