### ISSUE TITLE
screen updating in a loop

### ISSUE THREAD

**Issue by Darien46** [raspiblitz/raspiblitz#2718]
my node is synced, the screen has been stuck for 2 days. It says screen updating in a loop. not sure how to properly address this issue.

**Comment by openoms** [comment]
is it your desktop monitor or LCD?
press CTRL+C or try a restart through ssh

**Comment by Darien46** [comment]
It is happening on the lcd screen. I have restarted it a couple of times
now. It always goes back to the same spot during the reboot and says screen
updating in loop. On my monitor when I hash in, everything is synced and
running perfectly fine

**Comment by Darien46** [comment]
Monitor screen after control C. How do I proceed. When I put in admin
password, it goes back to screen you see, which says updating in loop

**Comment by Darien46** [comment]
the control c did not allow me to restart through hash. it asked for adin password and continued on same screen indication looping

**Comment by rootzoll** [comment]
If this issue still persist please try to make a photo of the LCD screen so that I can get an idea at which point of the display process this is happening.

**Comment by Darien46** [comment]
Pi lcd screen. Stuck 2 weeks

**Comment by Darien46** [comment]
My screen when I hash in from my phone that tells me it's updating in a
loop.

**Comment by Darien46** [comment]
Hi,
Will you be able to assist me with this?

**Comment by rootzoll** [comment]
Again .. please send a photo of your screen. Or if you cannot send a photo please quote the exact text you see on your screen. Without any more detailed info this is hard to debug from remote.

**Comment by Darien46** [comment]
Sorry,
I am attaching photos to this email. I'll try to go into the github and add
the photos. I apologize, I'm not a tech wizard. I attached the photos to
this email thread. I appreciate your time.

**Comment by openoms** [comment]
closing for inacivity
