### ISSUE TITLE
blitz.web.api.sh: install poetry and install dependencies with it

### ISSUE THREAD

**Issue by cstenglein** [raspiblitz/raspiblitz#2721]
the `blitz.web.api.sh` the script doesn't install the dependencies cause it's missing poetry`.

https://python-poetry.org/docs/#installation
and then `poetry install` in the /home/admin/blitz_api directory instead of the pip install

**Comment by cstenglein** [comment]
@fusion44 is poetry needed? With your latest fixes, the api runs without issues on a blitz.

If not, we can close this issue.

**Comment by fusion44** [comment]
Poetry is only useful for development purposes. Everyone else should use a standard pip install. There was a problem because I had included a git dependency which, pip didn't like. Should be fixed now.

**Comment by cstenglein** [comment]
Thx for the clarification @fusion44 
:)
