### ISSUE TITLE
Zap android wallet connection QR code

### ISSUE THREAD

**Issue by Dehumanizer77** [raspiblitz/raspiblitz#2739]
Please add an option of showing the QR code for connecting Zap android wallet, as it's not currently in the Connect/Mobile menu and it took me some time before I realized I need to get the Tor hostname from /mnt/hdd/tor/lndrpc10009/hostname as Zap does not support REST as Zeus does. 
Not a problem for me now, since I have it configured already and it works, but it might help other new users.

**Comment by rootzoll** [comment]
Zap Android had a problem in the past - thats why it was removed. But its on the list to be checked & added again: see #2348

**Comment by rootzoll** [comment]
closing because of duplicate
