### ISSUE TITLE
Update LIT & test Lightning Node Connect

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2748]
https://lightning.engineering/posts/2021-11-30-lightning-terminal/

**Comment by rootzoll** [comment]
Use for testing LNC to RaspiBlitz node: https://terminal.lightning.engineering

**Comment by openoms** [comment]
Tested ok with all connections over Tor: https://github.com/rootzoll/raspiblitz/commit/9ac00f305f3aaabc64def1b005258adc8b23bfc7

**Comment by openoms** [comment]
update to 0.6.1 https://twitter.com/lightning_help/status/1466915276671254530?s=19

**Comment by rootzoll** [comment]
quick side check on #2715

**Comment by rootzoll** [comment]
Latest version is already in code `0.6.1-alpha` on `dev` branch and quick test install ran OK.
Set again to final testing for v1.7.2 release candidates.

**Comment by rootzoll** [comment]
OK works fine in testing. Closing issue for release.
