### ISSUE TITLE
Potential config file corruption

### ISSUE THREAD

**Issue by AaronDewes** [raspiblitz/raspiblitz#2750]
This is a potential issue, I don't think it actually happened yet.

In many places, RaspiBlitz currently uses `echo "something=something" >> /mnt/hdd/raspiblitz.conf`.

If the user manually modifies the config file, and for some reason removes the newline at the end (it's unlikely, I just wanted to report this), this command will end up with the config file looking something like this:

Before:

```
oldConfig=oldValue
```

Expected:

```
oldConfig=oldValue
something=something
```

Actual config file:

```
oldConfig=oldValuesomething=something
```

In this scenario, doing `echo "something=something" | tee -a /mnt/hdd/raspiblitz.conf` would be better.

Even though this is unlikely you may find it's worth fixing it, because it can be fixed by a simple search and replace.

**Comment by openoms** [comment]
Good point thanks and easy to fix.

**Comment by rootzoll** [comment]
See discussion on changing how we edit the config file here:
https://github.com/rootzoll/raspiblitz/pull/2755#issuecomment-987948372

**Comment by rootzoll** [comment]
The solution in the redis branch is still using the old `>>` way to add values:
https://github.com/rootzoll/raspiblitz/blob/fd46eb202fdbe6fdb1cad91414148ab4945d8540/home.admin/config.scripts/blitz.conf.sh#L50

- [x] on this issue: replace that with the `tee -a` solution

**Comment by rootzoll** [comment]
OK change on the redis branch is in ... ready for final testing

**Comment by rootzoll** [comment]
Scripts works fine during the RCs. Closing this issue for v1.7.2 release.
