### ISSUE TITLE
ItchySats - peer-to-peer CFDs on Bitcoin for Raspiblitz? 

### ISSUE THREAD

**Issue by 1010Tom** [raspiblitz/raspiblitz#2753]
Hi guys,

ItchyMax here from https://github.com/itchysats/itchysats/

We are building a tool which enables users to trade CFDs (BTC/USD) on Bitcoin - no trust and no accounts needed - just you and your keys. 

We are currently preparing a plugin for Umbrel and wondered if users of this distro would be interested in this? If so, we are happy to work on this and create a service. 

p.s. if you want to give it a try in a save environment, we have a blog post about how to run ItchySats on testnet: 
https://itchysats.medium.com/p2p-bitcoin-cfds-give-it-a-try-4db2d5804328

You can also find us on twitter: https://twitter.com/itchysats)

**Comment by rootzoll** [comment]
Could be interesting to integrate - but not on my personal prio list ... would need someone to take the lead on this. Marking as "help wanted". Happy to assist on any open technical questions.

**Comment by 1010Tom** [comment]
Hi @rootzoll ,

I finally had time to implement it. An early draft but working branch can be found here: https://github.com/itchysats/raspiblitz/tree/itchysats

Before I open a PR here, I was wondering, is there a preference to build from source or can we download the release binary from github. I saw both being done by different apps so I wanted to ask. 

The linked branch above has both implemented, first fetching the source, and then I overwrote it with downloading the release binary from github.

Building ItchySats from source takes a long time on a RPi4 and I don't know about the performance on a RPi3.

**Comment by rootzoll** [comment]
Hi - first let me point you out to our new template for additional apps ... it contains much information on how to add your app to raspiblitz - maybe check your bonus script for more details here:
https://github.com/rootzoll/raspiblitz/blob/dev/home.admin/config.scripts/bonus.template.sh

Also make sure to base your PR to the `dev` branch once you open it.

>  I was wondering, is there a preference to build from source or can we download the release binary from github.

Basically both is fine. When using binaries keep in mind that RaspiBlitz also opens up to other CPU architectures. Building from source code is might be more flexible. Dont worry about RPi3 - they are not recommended anymore to use with RaspiBlitz.

**Comment by 1010Tom** [comment]
Hi, thanks for sharing the new template. I'll see to update what I have so far accordingly. 

Does anything speak against an interactive installation menu where the user is being asked if he/she wants to build from source or download the release?

**Comment by rootzoll** [comment]
Added to v1.8.0 release

**Comment by rootzoll** [comment]
Because the re-install of itchysats during an update/recover I fixed the install in `_provision_.sh` with `bonus.itchysats.sh on --download` even if the user before installed from code because there cannot be an interactive dialog blocking the recover/update process.

**Comment by rootzoll** [comment]
I needed to fix the version to 0.4.20 because the github API has a ratelimit and once it blocks the IP the install failed.

**Comment by rootzoll** [comment]
OK is installing and recovering fine - closing issue for v1.8.0 release

**Comment by 1010Tom** [comment]
Thanks for the fixes @rootzoll . One minor bug sneaked in which made the `update` function useless as it would have re downloaded the smae version. I've provided a fix here: https://github.com/rootzoll/raspiblitz/pull/3154
