### ISSUE TITLE
Windows-to-raspi blockchain COPY over SCP is capped at 4.2Mb/s

### ISSUE THREAD

**Issue by henkisdabro** [raspiblitz/raspiblitz#2758]
It seems the copy speed is capped at 4Mb/s (max 4.2Mb/s) using the GIT bash terminal. My LAN is Gigabit and my Raspi hardware is RPi4 4Gb, Samsung 1TB Plus SSD and UGreen USB3 enclosure (the recommended SSD and enclosure). Is there a reason the copy is so slow and what should I do to speed it up? Is the USB bus speed restricting this?

**Comment by Grov-r** [comment]
Hi
I'm copying right now over windows7 shell (pscp in command line) im averaging 8000kb.s on gigabit wired.
Rpi4/4g and samsung T5 1gb ssd on USB3 port.
I dont know what the limiting factor is, but it's a bit faster over here, but could be 4, 5x faster.

**Comment by henkisdabro** [comment]
thanks for your answer!

I googled and found issues around SCP+Windows and decided not to dwell on this path any longer. I hence opted to try+install WSL2 for Windows 10 (basically Microsoft's own virtual machine implementation) with the full Ubuntu Linux Kernel. After re-flashing the raspiblitz SD card and formatting/wiping the USB3 SDD, I reran the raspiblitz setup by `ssh`-ing into raspiblitz via the Windows10/Ubuntu WSL2 (through Windows Terminal) and this time copied over the locally synced blockchain folders onto raspiblitz using the `rsync` command which is the raspiblitz-recommended procedure for Linux machines and now it is copying with between 47-75Mb/s speeds which is excellent.

Perhaps this can be added in the setup docs as a good and viable solution for Windows 10/11 users?
