### ISSUE TITLE
PyBLOCK new version

### ISSUE THREAD

**Issue by curly60e** [raspiblitz/raspiblitz#2759]
Improvements:

The package structure was changed.
Improved installation with PYPI in just one command (pip3 install pybitblock)
This let you execute it in every part of the system typing "pyblock"
Updating it changed: pip3 install pybitblock -U

Problems:

When you install Pyblock with pip3, all config files will create in the folder you execute it.
For nodes like RaspiBlitz it will make this an issue.

Solutions:

RaspiBlitz could use just the information located in the pybitblock folder and continue using RaspiBlitz execution format like nothing happened.
![imagen](https://user-images.githubusercontent.com/55191248/144708778-0f664bef-6c7f-42d2-8551-1db1c68914a6.png)

**Comment by rootzoll** [comment]
OK PR #2811 merged. Update option was removed in change to new pip3 install. Can now directly started with raspiblitz-shortcut `pyblock` when installed. Setting to final testing for v1.7.2 release candidates.
