### ISSUE TITLE
Exeption on Subscription

### ISSUE THREAD

**Issue by ttrueten** [raspiblitz/raspiblitz#2777]
Hi there,
I got Permisson errors when I try to subscribe / generate a Let's encrypt certificate.

![Auswahl_012](https://user-images.githubusercontent.com/12172681/145199079-ab32e263-5523-4e47-96d6-c0a390e6e83e.jpg)

https://termbin.com/jf2m

Cheers,
Thomas

**Comment by rootzoll** [comment]
Thanks for the report ... can you check if the following directory exists `/mnt/hdd/app-data/subscriptions` and if yes what are the permissions on that directory and also if exists the file `subscriptions.toml`with command `sudo ls -la /mnt/hdd/app-data/subscriptions/subscriptions.toml` on terminal?

**Comment by rootzoll** [comment]
Note: Might be releated to issue #2689 already fixed for upcomming v1.7.2

**Comment by ttrueten** [comment]
Hello,

drwxr-xr-x 2 bitcoin bitcoin 4096 Dec  3 10:33 subscriptions

the directory itself is empty.

**Comment by rootzoll** [comment]
@ttrueten I think we found the reason and this should fix it:
https://github.com/rootzoll/raspiblitz/commit/236fc76e92a1fbb7bf2aa979180d6ad22d04fa39

Putting this issue on final testing for Release Candidates of v1.7.2

**Comment by rootzoll** [comment]
OK tested again - works so far. CLosing for v1.7.2 release.
