### ISSUE TITLE
Is the current microSDHC card brand/model recommendation critical?

### ISSUE THREAD

**Issue by henkisdabro** [raspiblitz/raspiblitz#2788]
The Samsung PRO Endurance 32Gb microSDHC card that is recommended doesn't have the fastest read/write, nor offers the longest warranty out there and other brands offer Endurance cards as well. Is this recommendation critical, meaning other cards have been tested and deemed unsuitable for the Raspiblitz project? Or is the "endurance" feature the most critical aspect of the microSDHC card and other brands' models would work equally well?

**Comment by openoms** [comment]
Any Endurance model is a good choice. 
If you are looking at metrics search for the one tolerating the highest number of write cycles.
The recommendation in the shopping list is based on experience and accessibility. Not "critical."
