### ISSUE TITLE
rootzoll: rb1 going for a few weeks now (no trans yet) BUT can I talk to you about an idea re RB?

### ISSUE THREAD

**Issue by philiprhoades** [raspiblitz/raspiblitz#2789]
rootzoll,

I know this is not the right place to ask this question but I couldn't find another method to contact you . .

I have an idea that involves raising research funds for my non-profit - possibly using my RB / LN - you could point me in the right direction I think . .

Thanks,
Phil.

**Comment by nyxnor** [comment]
I am not rootz but see tallycoin, it is being integrated here https://github.com/rootzoll/raspiblitz/pull/2617

**Comment by philiprhoades** [comment]
@nyxnor ,

Thanks!

**Comment by rootzoll** [comment]
cleared thru DMs
