### ISSUE TITLE
Running raspiblitz behind vpn

### ISSUE THREAD

**Issue by rolandbitcoinspot** [raspiblitz/raspiblitz#279]
Hi there.
I have a raspiblitz and it is working fine. however: i would like to run it behind a vpn so i wont disclose my home ip address. Is it possible to run raspiblitz behind a vpn and does anyone have experience with this ?

Thanks
Keep up the good work!

Roland.

**Comment by rootzoll** [comment]
A VPN solution is not part of RaspiBlitz yet, but to hide your home IP you can at the moment activate TOR (services > TOR).

**Comment by rolandbitcoinspot** [comment]
But if i activate TOR, my node wont be seen in the "regular" LN explorers wont it ? people will have to specifically connect to it trough tor?

**Comment by rootzoll** [comment]
Thats correct, if you want to be a routing node, TOR is not a perfect option. TOR is a good (and cheap) option if you want a personal Lightnig Node to send/receive and not publish your personal IP.

A VPN feature for Routing Nodes is missing. Contributions welcome.

**Comment by fluidvoice** [comment]
bumped into this article on how to run your own VPN
[Secure & Ad-free Internet Anywhere With Streisand and Pi Hole](https://ifelse.io/2019/01/12/secure-ad-free-internet-anywhere-with-streisand-and-pi-hole/)

**Comment by rolandbitcoinspot** [comment]
thanks for all the replies. i will keep my LN node on my VPS for now.
I also had a bunch of replies on a reddit thread, be sure to check those out.
https://www.reddit.com/r/lightningnetwork/comments/ahoxwr/running_lightning_node_behind_vpn/
i will close this for now.
