### ISSUE TITLE
LNBits - wrong github reference

### ISSUE THREAD

**Issue by fjone** [raspiblitz/raspiblitz#2792]
I installed LNBits on my raspi but noticed a lot of new extensions didn't get installed.

It seems like LNBits development has moved to this repo "https://github.com/lnbits/lnbits-legend"

https://github.com/rootzoll/raspiblitz/blob/a500cc7cf2727f9cf1c587fcca8307b72e9c4f66/home.admin/config.scripts/bonus.lnbits.sh#L264

**Comment by openoms** [comment]
thanks for the report. Are all the extension get installed if you correct that line?

**Comment by rootzoll** [comment]
lnbits repo was moved but the link should still point to the LNbits legend. The reason why an old version gets installed is because for raspiblitz by default the tag`raspiblitz` on the LNbits repo is installed. But @arcbtc promised to move the tag for the next release.

But it makes sense to change the link to the repo anyway - so marking that as TODO:
- [x] adapt lnbits repo URL for v1.7.2
- [x] make sure raspiblitz tag gets moved to new version

**Comment by openoms** [comment]
LNbits seems to install ok, but don't know if should be concerned here
```
Installing collected packages: pylightning
Successfully installed pylightning-0.0.7.3
# processing assets
sudo: ./venv/bin/quart: command not found
# updating databases
sudo: ./venv/bin/quart: command not found

*** Updating Firewall ***
```
 after adding quart to the install:
` sudo -u lnbits ./venv/bin/pip install quart`

```
# processing assets
Usage: quart [OPTIONS] COMMAND [ARGS]...
Try 'quart --help' for help.

Error: No such command 'assets'.
# updating databases
Usage: quart [OPTIONS] COMMAND [ARGS]...
Try 'quart --help' for help.

Error: No such command 'migrate'.
```

**Comment by rootzoll** [comment]
I think in the latest LNbits verison Quart got replaced with FastAPI so might be able to drop that extra install.

**Comment by rootzoll** [comment]
Removed Quart - still installs :)

**Comment by zanderisrael** [comment]
There is a new version with the lndpos extension, its not on the raspiblitz branch.
Is there a need for that tag at all? Why not install 0.4.0 that was released recently?

**Comment by openoms** [comment]
There is a new tag with new functionality, will test and update https://github.com/lnbits/lnbits-legend/releases/tag/0.6.0

**Comment by rootzoll** [comment]
v1.7.2 is no picking up the https://github.com/lnbits/lnbits-legend tag=0.6.0
Closing this issue for release.
