### ISSUE TITLE
Update BTC RPC Explorer to version 3.3.0?

### ISSUE THREAD

**Issue by henkisdabro** [raspiblitz/raspiblitz#2796]
I found that an updated version has been released; currently raspiblitz runs BTC RPC Explorer version 3.2.0

https://github.com/janoside/btc-rpc-explorer/releases/tag/v3.3.0

**Comment by rootzoll** [comment]
OK first test with the update looks fine - will be part of v1.7.2 release candidates. Keep open for final testing.

**Comment by rootzoll** [comment]
Final testing looking good. Closing issue for v1.7.2 release.
