### ISSUE TITLE
Typo in tor.install.sh

### ISSUE THREAD

**Issue by adevoss** [raspiblitz/raspiblitz#2799]
Line 186:
`sudo chmod -v 755 "${tor_conf_dir}""${tor_conf_dir}"/torrc.d`
should be
`sudo chmod -v 755 "${tor_conf_dir}" "${tor_conf_dir}"/torrc.d`
(added space between variables)

I think this is a typo but I'm not sure.

**Comment by rootzoll** [comment]
@adevoss thanks for giving this a review. 👀 @nyxnor

**Comment by rootzoll** [comment]
comitted fix to `dev` branch

**Comment by rootzoll** [comment]
tests looking good thru the RC2 testing. Closing for v1.7.2 release.
