### ISSUE TITLE
Stuck post Blockchain Download

### ISSUE THREAD

**Issue by evilgrinz** [raspiblitz/raspiblitz#28]
UNKOWN STATE
It seems that something went wrong during sync/download/copy of the blockchain.
Maybe try --> ./60finishHDD.sh

Do i need to just re-dl it? Is it just timing out trying to sync? I enter this command, and it just pops again after 5 minutes.

**Comment by rootzoll** [comment]
Make sure ta have the latest SD-Card image - check README.md
Quick solution would be to delete your blockchain directory: sudo rm -r /mnt/hdd/bitcoin
The make a fresh reboot.

**Comment by evilgrinz** [comment]
ill give it a go, and refresh the image thanks

**Comment by charlesrocket** [comment]
looks like issue is fixed with the fresh image, can't reproduce. try to delete ln folder and conf files from hdd as well

**Comment by rootzoll** [comment]
thx, so I will close this issue fo now

**Comment by evilgrinz** [comment]
any good reference site for ssh commands, pretty new to it

**Comment by rootzoll** [comment]
@evilgrinz 

How SSH Works:
https://www.youtube.com/watch?v=zlv9dI-9g1U

For intro into Raspi/Linux Terminal ... Hack5 has a quite entertaining show lineup:
https://www.youtube.com/watch?v=b5NmtmNwMgU&list=PLW5y1tjAOzI2ZYTlMdGzCV8AJuoqW5lKB
