### ISSUE TITLE
Sync Restarts Continuously 

### ISSUE THREAD

**Issue by ghost** [raspiblitz/raspiblitz#2800]
![image](https://user-images.githubusercontent.com/93434906/146264611-3a527066-4a44-43e2-aa20-231847b656ee.png)

Attempting to bind sparrow wallet to node IP address and entered the following commands below all the other settings in Bticoinconf with my IP, user and password (generic below). 

![image](https://user-images.githubusercontent.com/93434906/146265080-211a13b6-9206-4f76-8c0f-f4fd7c21f01b.png)

Once done the settings needed to be restarted to save. Now, sync it continues to restart the sync, and asking me that I continue to enter my password C over and over again.

**Comment by openoms** [comment]
CTRL + C
type:
`menu`
see your bitcoinLOGS in SYSTEM
also
`sudo journalctl -fu bitcoind`

**Comment by ghost** [comment]
Thank you, it solved my problem. Can you help with connecting to Sparrow Wallet? I am entering my ip as stated in their guide, but the connection has not been made. I can't figure out why.

**Comment by openoms** [comment]
probably the firewall blocking.
Use the CONNECT menu bitcoinRPC option or Electrs.

**Comment by ghost** [comment]
Y'all are the bomb! Thank you openoms
