### ISSUE TITLE
Imposible to download reliably Raspiblitz SD-image from http with a poor Internet connectionn

### ISSUE THREAD

**Issue by thelwyn** [raspiblitz/raspiblitz#281]
Downloading the image from China has been a PITA, the http download would always fail at some point, classic for a large download file here. I had to ask a friend back in Europe to upload it for me to Baidu Cloud (the Chinese cloud) and download it from there.

I saw another issue mentioning a torrent but only found torrents for the blockchain (If I understood correctly), without more information and non very informative filename ('update' in many of them for example).

-Is there a torrent file of Raspiblitz image to seed?
-If not, what about (re?)creating a torrent in this github for the poor souls with terrible unstable Internet connections? (I'm willing to seed obviously).

**Comment by fluidvoice** [comment]
I wonder if it would work to download and run the script that builds the SD card image:
https://github.com/rootzoll/raspiblitz/blob/master/build.sdcard/raspbianStretchDesktop.sh
It must be run from the booted Pi/Raspbian.

**Comment by fluidvoice** [comment]
You can do this with the `wget` --continue option. Here I stopped the download at 5MB then continued it again.

$ `wget --show-progress https://wiki.fulmo.org/downloads/raspiblitz-0.99-2018-12-24.img.gz`
--2019-01-20 18:03:44--  https://wiki.fulmo.org/downloads/raspiblitz-0.99-2018-12-24.img.gz
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving wiki.fulmo.org (wiki.fulmo.org)... 83.169.23.201
Connecting to wiki.fulmo.org (wiki.fulmo.org)|83.169.23.201|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2420962511 (2,3G) [application/x-gzip]
Saving to: ‘raspiblitz-0.99-2018-12-24.img.gz’

18-12-24.img.gz       0%[                    ]   **5,02M**   313KB/s    eta 2h 53m **^C**

$ `wget --continue --show-progress https://wiki.fulmo.org/downloads/raspiblitz-0.99-2018-12-24.img.gz`
--2019-01-20 18:04:11--  https://wiki.fulmo.org/downloads/raspiblitz-0.99-2018-12-24.img.gz
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving wiki.fulmo.org (wiki.fulmo.org)... 83.169.23.201
Connecting to wiki.fulmo.org (wiki.fulmo.org)|83.169.23.201|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 2420962511 (2,3G), 2415637711 (2,2G) remaining [application/x-gzip]
Saving to: ‘raspiblitz-0.99-2018-12-24.img.gz’

piblitz-0.99-2018-1   0%[                    ]   **5,29M**  42,4KB/s    eta 17h 29m^

**Comment by fluidvoice** [comment]
This page has some other good info on https://www.howtoforge.com/linux-basics-how-to-download-files-on-the-shell-with-wget
Of course you can do `man wget`

**Comment by rootzoll** [comment]
@thelwyn version 1.0 release of the RaspiBlitz is comming closer. for such main releases I am much happy to provide a torrent of the image (and publishing in github repo) if this helps.

**Comment by thelwyn** [comment]
@fluidvoice I was on Windows when downloading the image. Didn't think of switching to Linux to wget it at that time, I will think of it next time! I also tried your other suggestion and DL Raspbian by torrent + build the image using the script. It worked, after turning on a VPN (I guess something was blocked again by the Great Chinese Firewall...)

@rootzoll that would be great! I'll seed.

**Comment by rootzoll** [comment]
@thelwyn raspiblitz version 1.0 torrent file is up: https://github.com/rootzoll/raspiblitz/raw/master/raspiblitz-v1.0-2018-02-18.torrent ... help on seeding is welcome :)

Closing then issue for now.

**Comment by thelwyn** [comment]
Yay! Downloading now, seeding then :)
