### ISSUE TITLE
Lightning-Charge 

### ISSUE THREAD

**Issue by eurtnl** [raspiblitz/raspiblitz#282]
Hi, 

Will this work on RaspiBlitz? 

- [https://github.com/ElementsProject/lightning-charge](url)

- [https://github.com/ElementsProject/wordpress-lightning-publisher](url)

**Comment by fluidvoice** [comment]
Lightning-Charge and Elements runs on top of the **c-lightning** daemon, the Blockstream implementation of LN.  RaspiBlitz runs on top of the **lnd** daemon, the Lightning Labs implementation. It probably would not work to run both at the same time on a Pi.

**Comment by eurtnl** [comment]
Ok, thanks!
