### ISSUE TITLE
VPS & Tor

### ISSUE THREAD

**Issue by Tanki90** [raspiblitz/raspiblitz#2821]
Hello, 

I configured my Raspiblitz in Clearnet with a public ip from DigitalOcean
Tutorial: https://www.mobycrypt.com/turn-your-self-hosted-lightning-network-node-to-public-in-10-minutes/ 

Is it possible to run the node in Clearnet for requests etc. and activate Tor only for Applications like LNBits, Zeus Wallet, Sphinx Chat, Bos Telegram Bot.... to have better security or is it better with dyndns?

**Comment by openoms** [comment]
It is possible, but corrently not implemented. Tor only is default and you could manually activate the clearnet access for LND.
DynDNS does not provide any security or privacy since it is just resolves to the given IP address.

See: https://github.com/rootzoll/raspiblitz/issues/2787

**Comment by Tanki90** [comment]
Yeah, but I deactivate ''run behind tor'' in the menu and configure my node with the tutorial above with a public ip...
To get access with applications like lnbits, zeus..... i need DynDNS and open ports in the cloud server with openvpn 
(those are my security concerns)

My thoughts are to connect only the Applications over a Tor Adresse.
Maybe with Hybrid Mode....or i have a mistake in thinking..idk

**Comment by openoms** [comment]
My point was that you should keep the "run behind tor" option on and add the clearnet access on top.

Currently you would need to to edit the lnd.check.sh or deactivate (comment) the `ExecStartPre=...` line in `/etc/systemd/system/lnd.service` for the modified Tor related settings to persist in the lnd.conf.

**Comment by Tanki90** [comment]
aah ok thx. you are the man
