### ISSUE TITLE
[1.7.2RC1] bad substitution error with _cache.sh focus

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#2828]
```
# OK - the chain is synced
# Calling:
sudo -u bitcoin /usr/local/bin/lncli -n=mainnet --rpcserver localhost:10009 newaddress p2wkh

{
    "address": "xxxxxxxxxxxxxxxxxxxxxxxxx"
}
generating QR code ... please wait
/home/admin/BBfundWallet.sh: line 85: ln_${LNTYPE}_${$chain}net_wallet_onchain_pending: bad substitution
/home/admin/BBfundWallet.sh: line 86: ln_${LNTYPE}_${$chain}net_wallet_onchain_balance: bad substitution
```

`eval` or similar needs to be used in:
https://github.com/rootzoll/raspiblitz/blob/c3a4eb3bfbdfd9769c8d796b1523fb844da1acd0/home.admin/BBfundWallet.sh#L85

**Comment by adevoss** [comment]
There is a double '$' sign in this line. Removing the second one will solve it I think.

**Comment by openoms** [comment]
yes, that should be it, thanks @adevoss.

**Comment by openoms** [comment]
there has been a few more so will leave this open for final testing

**Comment by rootzoll** [comment]
Hope we got them all .. no further reports since RC2 release. Closing issue.
