### ISSUE TITLE
Wrong version of bitcoin core displayed on LCD screen (21.0.0 instead of 0.21.0)

### ISSUE THREAD

**Issue by we-do-it-lu** [raspiblitz/raspiblitz#2829]
Wrong version of bitcoin core displayed on LCD screen (21.0.0 instead of 0.21.0)

**Comment by rootzoll** [comment]
A dont have a 0.21 version running anymore to check - mybe the bitcoin-cli was a bit too early to bump the number to major version ... but from v22 on that numbering is the new normal - see: https://github.com/bitcoin/bitcoin/releases
