### ISSUE TITLE
add REPAIR-LND menu to offer restore from file, seed+SCB and seed only

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#2832]
Currently testing

**Comment by rootzoll** [comment]
OK the PR changed quite a lot because if the change to the new proto files. Because a test with a new sd card build is needed I merge it and then now it needs to be final tested on the following details:

- [x] new sd card build with merged PR - running?
- [x] recover with SEED for on-chain funds
- [ ] recover with SEED & SCB for on-chain funds & closing channels (during setup & LND repair menu)
- [ ] run/test Blitz TUI
- [ ] run/test Wallet-Auto-Unlock (or change to new LND method)

**Comment by openoms** [comment]
The route - REPAIR- LND - SEED+SCB has a problem - investigating
![image](https://user-images.githubusercontent.com/43343391/149676115-133fbe56-69c3-42e8-a690-77c7dc4ff5dd.png)

This was an easy fix: a1fe1ec

Run `patch` on the v1.7.2rc1d image to get the change.

**Comment by rootzoll** [comment]
Needed to add the "scan recovery window" again to `lnd unlock` & `iniwallet from seed` to make lnd find the on-chain funds again.

**Comment by openoms** [comment]
> Needed to add the "scan recovery window" again to `lnd unlock` & `iniwallet from seed` to make lnd find the on-chain funds again. 

It is there for the restore from seed: https://github.com/rootzoll/raspiblitz/blob/2ded9deb981cb0d374473dea7b098a185a8a6533/home.admin/99lndRepairMenu.sh#L440

and for seed+SCB: https://github.com/rootzoll/raspiblitz/blob/2ded9deb981cb0d374473dea7b098a185a8a6533/home.admin/99lndRepairMenu.sh#L269

**Comment by rootzoll** [comment]
On setup the actual scan happens after the reboot and thats were the normal lnd cli based unlock is used

**Comment by openoms** [comment]
That is right. The rescan is done if the REPAIR-LND menu is used (without restart).
If restoring with a fresh setup the rescan would need to be done manually from the menu after the initial setup and bitcoind sync.

If this is documented clearly might be enough or at least where I got to.

(This is also an issue for CL - the rescan there is fully manual, only documented in the FAQ.cl.md - could add some new logic there too)

**Comment by DocBrown101** [comment]
I have made one step forward but now I get a new error message:
```
WALLET --> UNLOCK WALLET - SCAN 0
WALLET --> SEED + SCB
lnd-wallet-seed+scb lnd.initwallet.py scb returned error /home/admin/config.scripts/lnd.initwallet.py scb mainnet ... --> the given filepathSCB - file does not exist or no permission +

Press ENTER to return to main menu.
```

**Comment by rootzoll** [comment]
The repair options got soem attention with this issue #2901 @DocBrown101 if you have some time best to wait for v1.7.2
