### ISSUE TITLE
[SECURITY] Replace `scp` with `sftp`

### ISSUE THREAD

**Issue by nyxnor** [raspiblitz/raspiblitz#2834]
Replace `scp` with `sftp`. Both were created by OpenBSD for OpenSSH, but scp is being deprecated in favor of [sftp](https://undeadly.org/cgi?action=article;sid=20210910074941).
The change is compatible with the same options.
man [scp](https://man.openbsd.org/scp)
man [sftp](https://man.openbsd.org/sftp)
man [sftp-server](https://man.openbsd.org/sftp-server.8)

**Comment by rootzoll** [comment]
Merged #3206 - setting this to final testing for v1.9.0 release

**Comment by rootzoll** [comment]
Got more than one error report on the use of sftp - see #3584 ... will change back to scp command for blockchain upload for v1.9.0 release.
