### ISSUE TITLE
Reconnecting Raspiblitz to Network after Power Outage

### ISSUE THREAD

**Issue by terrapin88** [raspiblitz/raspiblitz#284]
Hi all,

This is likely a very elementary issue that my novice self is running into. The power at home flickered off earlier in the week and now I cannot seem to fire back up my raspiblitz. When trying to ssh in, no connection can be established and when using advanced IP scanner the device shows up as dead.

Hoping someone can walk me through this to get back up and running. 

Thanks!

**Comment by hcarrega** [comment]
Check issue #263

**Comment by rootzoll** [comment]
In the best case just the SD card with the OS has some problem. If you had installed version 0.98 or later this can be fixed by writing ne fresh RaspiBlitz sd card image and let it recover the data from the HDD. Mechanism: update raspiblitz --> see FAQ : https://github.com/rootzoll/raspiblitz/blob/master/FAQ.md#how-to-update-my-raspiblitz-after-version-098

**Comment by terrapin88** [comment]
Thanks rootzoll - I think I'm on the right track. After rewriting the SD card I can now login, but it is requesting the default login credentials rather than those previously set. At this point, I receive the error message "No HDD found." 

Forgive my ignorance, but I thought this section of the FAQ may be relevant, but am not 100% how to proceed:

**I connected my HDD but it still says 'Connect HDD' on the display?**
Your HDD may have no partitions yet. SSH into the RaspiBlitz as admin (see command and password on display) and you should get offert the option to create a partition.

**Comment by fluidvoice** [comment]
It's not that you don't have any partitions. The system cannot find your HDD at all. 
If you run these commands from an SSH session do you see "sda" similar to me?
In addition to below, I would check your USB cable, and also verify your HDD is still working by connecting it to another computer and verify it's recognized.

$ `lsblk`

> NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
> sda           8:0    0 465.8G  0 disk 
> └─sda1        8:1    0 465.8G  0 part /mnt/hdd
> mmcblk0     179:0    0  29.8G  0 disk 
> ├─mmcblk0p1 179:1    0  43.8M  0 part /boot
> └─mmcblk0p2 179:2    0  29.8G  0 part /

if you don't see "sda" then install **hwinfo**...
$ `sudo apt-get install hwinfo`

then when you run this, do you see similar to me?...
$ `hwinfo --disk |grep -B4 -A18 "block/s"`

> 18: SCSI 00.0: 10600 Disk
>   [Created at block.245]
>   Unique ID: N0O2.URxHHBVxyUB
>   Parent ID: 3t9U.nXi7rxFKh4B
>   SysFS ID: /class/block/sda
>   SysFS BusID: 0:0:0:0
>   SysFS Device Link: /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.1/1-1.1.3/1-1.1.3:1.0/host0/target0:0:0/0:0:0:0
>   Hardware Class: disk
>   Model: "JMicron Generic"
>   Vendor: usb 0x152d "JMicron"
>   Device: usb 0x0578 "Generic"
>   Revision: "0204"
>   Serial ID: "0123456789ABCDEF"
>   Driver: "usb-storage", "sd"
>   Driver Modules: "usb_storage"
>   Device File: /dev/sda (/dev/sg0)
>   Device Files: /dev/sda, /dev/disk/by-id/usb-JMicron_Generic_0123456789ABCDEF-0:0, /dev/disk/by-path/platform-3f980000.usb-usb-0:1.1.3:1.0-scsi-0:0:0:0
>   Device Number: block 8:0-8:15 (char 21:0)
>   Speed: 480 Mbps
>   Module Alias: "usb:v152Dp0578d0204dc00dsc00dp00ic08isc06ip50in00"
>   Drive status: no medium
>   Config Status: cfg=new, avail=yes, need=no, active=unknown
>   Attached to: #1 (USB Controller)
>

**Comment by rootzoll** [comment]
I extended the FAQ on this topic ...

**## I connected my HDD but it still says 'Connect HDD' on the display?**

Your HDD may have no partitions yet. SSH into the RaspiBlitz as admin (see command and password on display) and you should get offert the option to create a partition. If this is not the case:

Check/Exchange the USB cable. Connect the HDD to another computer and check if it shows up at all .. 

OSX: https://www.howtogeek.com/212836/how-to-use-your-macs-disk-utility-to-partition-wipe-repair-restore-and-copy-drives/

Windows:
https://www.lifewire.com/how-to-open-disk-management-2626080

Linux/Ubuntu:
https://askubuntu.com/questions/86724/how-do-i-open-the-disk-utility-in-unity

**Comment by fluidvoice** [comment]
Linux/Raspbian (command line): 
https://www.addictivetips.com/ubuntu-linux-tips/manually-partition-a-hard-drive-command-line-linux/
While it's not nearly as easy as using the graphical app `gparted`, the command line app `parted` is already included in the Raspbian distro your Raspiblitz node is running, so you could probably also do this directly on your Pi if you needed/wanted to. @rootzoll

**Comment by rootzoll** [comment]
@fluidvoice thx - added it

**Comment by geco91** [comment]
recommend this issue to close
