### ISSUE TITLE
Where do I plug in the fan? 

### ISSUE THREAD

**Issue by b-ryan** [raspiblitz/raspiblitz#2841]
I purchased the heatsink case that comes with fans: https://www.amazon.com/Raspberry-Armor-Metal-Aluminium-Heatsink/dp/B07VWM4J4L/ref=sr_1_4?geniuslink=true&keywords=armor+case+for+raspberry+pi+4+black&qid=1640214649&sr=8-4

In restrospect I'm not sure if this was a mistake on my part or something I inferred from the instructions, it's been awhile since I made the purchase. Is this case appropriate and if so is there somewhere to plug in the fan? I'm not sure which pins to use.

Thanks

**Comment by openoms** [comment]
You don't need the fan with the heatsink. Just leave it unplugged.
