### ISSUE TITLE
passwordA in plaintext in log file

### ISSUE THREAD

**Issue by adevoss** [raspiblitz/raspiblitz#2848]
Security issue??
The password is in `raspiblitz.setup.log`

**Comment by rootzoll** [comment]
At which point? Can you give more information? If its about passwordB - that is stored in the lnd/bitcoin configs anyway. Passwotd C only if user activates LND-auto-unlock. Bit PasswordA should never be stored on disk or in any logs.

**Comment by adevoss** [comment]
`cat raspiblitz.setup.log`
...
setPasswordA=1
passwordA='xxxxxxxxxxx'
...
password is replaced here by me. In the file there is the actual password in plain text.

**Comment by rootzoll** [comment]
Thanks for the report - good catch. I think I found it - it was a left over from an debug output while refactoring the setup process for the 1.7.1 - its not super critical, but good to have that out of the system for v1.7.2

**Comment by rootzoll** [comment]
OK this fix will be part of v1.7.2 release. Closing issue.
