### ISSUE TITLE
Seeding newest Blockchain Torrents

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#285]
For the upcomming version 1.0 release help on the seeding of the following torrents would be needed:

https://github.com/rootzoll/raspiblitz/raw/master/home.admin/assets/raspiblitz-bitcoin1-2018-10-13-base.torrent

https://github.com/rootzoll/raspiblitz/raw/master/home.admin/assets/raspiblitz-bitcoin1-2019-01-16-update.torrent

much thx :)

**Comment by baebb** [comment]
is there a way to run the seeding from our existing raspiblitz node? I don't have any machines with 200gb free space

**Comment by fluidvoice** [comment]
> is there a way to run the seeding from our existing raspiblitz node? I don't have any machines with 200gb free space

Note: you may need to setup low upload/seed speed limit so the torrent seeding does not slow down your bitcoin/LN syncing too much.
**Install Transmission on the Raspberry Pi For An “Always-on” Torrent Client**
https://www.addictivetips.com/media-streaming/kodi/install-transmission-raspberry-pi-torrent/

**Comment by fluidvoice** [comment]
> For the upcomming version 1.0 release help on the seeding of the following torrents would be needed:
> 
> https://github.com/rootzoll/raspiblitz/raw/master/home.admin/assets/raspiblitz-bitcoin1-2018-10-13-base.torrent
> 
> https://github.com/rootzoll/raspiblitz/raw/master/home.admin/assets/raspiblitz-bitcoin1-2019-01-16-update.torrent
> 
> much thx :)

Downloading now in the background w/slow speed limit.

**Comment by karloluiten** [comment]
Added, now downloading, 400mbit/s up once finished ;)

**Comment by born2los3built2win** [comment]
Added and seeding..

**Comment by freerko** [comment]
Continuing serving the base-torrent from October, currently ~300 times (>70TB) and added the update-torrent from January on the boxes where I didn't add it already 😄

**Comment by raumi75** [comment]
Downloading now. Should have 800Mbit/s upload shortly

**Comment by Stadicus** [comment]
Torrents are seeding, good luck for the RaspiBlitz launch!

Additional idea: could you provide an RSS feed with the new updated torrents, so that my server could automatically download/seed these as well?

**Comment by rootzoll** [comment]
@Stadicus can you try if this RSS works for you?
http://wiki.fulmo.org/downloads/raspiblitz-torrents-rss.xml

**Comment by Stadicus** [comment]
Great, seems to work with Synology DownloadStation.

![grafik](https://user-images.githubusercontent.com/19550140/51833474-da861e80-22f7-11e9-8b56-bbc9e2f77f15.png)

**Comment by rootzoll** [comment]
TODO: create torrent from version 1.0 release and add it to the RSS .. check if "subscribed" clients catch automatiocally the new torrent and seed it

**Comment by raumi75** [comment]
Can't figure out how to make the rss-feed work in rTorrent. However, 2.5 TB of blockchain has been downloaded from my rootserver, so far.

**Comment by rootzoll** [comment]
@raumi75 do you have problems with the Raspiblitz RSS mentioned above in special or adding RSS to rtorrent in general?

**Comment by raumi75** [comment]
@rootzoll I do not know how to add rss to rtorrent in general.

**Comment by vmavromatis** [comment]
I'm doing my part! Good luck with the launch!

**Comment by rootzoll** [comment]
@raumi75 I dont have experience with rtorrent RSS yet - would be a topic to reasearch..

**Comment by rootzoll** [comment]
It looks like we have a good seeding level - for version 1.0 release :) 

Much thanks to all - will remove this ticket from Milestone 1.0 but keep it open for future improvements like the RSS.

**Comment by raumi75** [comment]
I'm happily seeding from my rootserver with Gigabit uplink. Now my free volume is used up and it starts costing money. We need more seeders! Right now, there are only 8 seeders for the big file. When the version 1.0 image comes out, there might be higher demand.

**Comment by rootzoll** [comment]
@raumi75 so much thanks for spending your free volume - thats great :) 

8 seeders I think is a base to start on, my test torrent download runs OK .. in the README I mention that is a overnight wait time and that looks kind in that area. And if there are really a lot of people at the same time downloading I think the torrent peer2peer scale effect will kick in .. people while downloading are helping also with their upload.

But to add a little more bandwidth during 1.0 release I will fund some additional seeding thu justseed.it .. thats why I put this issue back on the milestone list.

TODO: add some additional seeding thru justseed.it during 1.0 release.

**Comment by rootzoll** [comment]
Additional seeding for launch secured.

**Comment by rootzoll** [comment]
OK .. v1.3 release of RaspiBlitz is comming closer and there was a change to drop the txindex=1 requirement for blockchain data - this will make it easier to use self-validated blockchains from other computers. But for this change all new torrents are needed - so this is a big torrent update and I need help preparing a good seed on these 4 files for the v1.3 release:

```
http://github.com/rootzoll/raspiblitz/raw/v1.3/home.admin/assets/raspiblitz-bitcoin2-2019-05-01-base.torrent
http://github.com/rootzoll/raspiblitz/raw/v1.3/home.admin/assets/raspiblitz-bitcoin2-2019-06-29-update.torrent
http://github.com/rootzoll/raspiblitz/raw/v1.3/home.admin/assets/raspiblitz-litecoin2-2019-06-29-base.torrent
http://github.com/rootzoll/raspiblitz/raw/v1.3/home.admin/assets/raspiblitz-litecoin2-2019-06-29-update.torrent
```

@Stadicus I moved the torrent RSS to a new server: 
`https://raspiblitz.com/raspiblitz-torrents-rss.xml`

**Comment by Omicron59** [comment]
You want me to share these new files on my torrent server?

**Comment by jsspanjer** [comment]
http://github.com/rootzoll/raspiblitz/raw/v1.3/home.admin/assets/raspiblitz-bitcoin2-2019-05-01-base.torrent 
...is too large.

**Comment by rootzoll** [comment]
@mamar59 that would be awesome :)

@jsspanjer too large? the old base torrent was not much smaller. Where do you get that error message? Or is that local space on your machine?

**Comment by jsspanjer** [comment]
I'm uploading to a seedbox. It can do 2 MiB torrent files max

**Comment by AbelLykens** [comment]
@jsspanjer try gzipping (or normal zipping) the torrent?

**Comment by rootzoll** [comment]
@jsspanjer unzipping would take too much time on the raspberrypi (too slow with that much data). But its OK if you not seed that big one (its based on a already in circulation torrent and should have good seeding). The three smaller torrents are most important to get a good seeding. Thanks for helping out.

**Comment by derPUPE** [comment]
fresh 1.3 torrents activated 
10 MBIT UL assigned ✓

**Comment by jsspanjer** [comment]
Ok. Rest is running. 10Gbps UL line.

**Comment by rootzoll** [comment]
With the coming v1.4 release there will be a new torrent update:
https://github.com/rootzoll/raspiblitz/raw/v1.4/home.admin/assets/raspiblitz-bitcoin2-2020-01-28-update.torrent

Help seeding is welcome - thx :D

**Comment by jsspanjer** [comment]
Done

**Comment by tril0byte** [comment]
I've been seeding all the raspiblitz torrents and their traffic recently went to zero. I presume the latest release (1.5) doesn't use torrent by default (but 1.4 did)?

Downloading 1.5 now, only 2 peers, could use some more seeds:
https://github.com/rootzoll/raspiblitz/raw/master/home.admin/assets/raspiblitz-v1.5-2020-05-08.img.gz.torrent

**Comment by rootzoll** [comment]
torrent is still available - but is becoming a fallback more and more.
Also had my seeding down over the lightning hacksprint to relax on my bandwith for the livestreams ... starting seeding now also again in my machine :)

**Comment by Omicron59** [comment]
![image](https://user-images.githubusercontent.com/46853496/81725315-f7f7e100-9485-11ea-8667-44f541c8c0ee.png)

hello everyone I always try to share torrents, I enjoy a good fiber connection, if there are other files to share, I can manage it without problem

**Comment by rootzoll** [comment]
@mamar59 much thx :)

**Comment by frennkie** [comment]
Initial block download (IBD) over torrent no longer in scope.
