### ISSUE TITLE
Bullseye Problems

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2851]
Got report that the new Bullseye base image might cause some trouble ...

- SSH service does not start reliebale (but this can also be related to changes in the ssh shell scripts)
- hardware support: problems getting the touchscreen to run

TODO: retest touchscreen

**Comment by openoms** [comment]
see my experience on with ssh on Armbian Buster: https://github.com/rootzoll/raspiblitz/issues/2820#issuecomment-1001242865

if the problem with ssh is similar we should double check the `sshd_config` on restore and reset.

**Comment by rootzoll** [comment]
@fusion44 does this https://github.com/rootzoll/raspiblitz/issues/2820#issuecomment-1001242865 reflects the error you observed?

**Comment by rootzoll** [comment]
OK Touchscreen restested - works as it is fo far on my tests.
So its just down to the SSH issue that is addressed in #2820
Closing this issue.
