### ISSUE TITLE
error initializing LND - (LND service is not running.)

### ISSUE THREAD

**Issue by GabrielRCL** [raspiblitz/raspiblitz#2858]
What's up guys, how's it going? will someone be able to help me?
my raspiblitz turned off overnight by itself and now doesn't want to turn on LND, what could I do?
![image](https://user-images.githubusercontent.com/68721111/147788576-81e6c0bb-155f-4922-ab1f-3f347137fb49.png)

already restarted 2x and still the error continues. raspiblitz makes an automatic backup right? how can i use this automatic backup?
I already did the repair and I have the backup, what can I do to fix this problem without losing my channel funds?

DEBUG:
https://termbin.com/e6cb

**Comment by GabrielRCL** [comment]
i have SEED, LND_Rescue (Backup-Repair-raspblitz), and i have Backup_All_Channels (created in RTL a 1month ago).
should i burn a new image to the microSD?
do i need to save something first?
I have never backed up before and am scared of losing my funds. Could someone explain to me how I can recover my channels?

**Comment by openoms** [comment]
The channel.db is corrupted.
Please close if you have been able to recover the funds from seed + SCB.
