### ISSUE TITLE
can't do initial boot

### ISSUE THREAD

**Issue by cryptodengo** [raspiblitz/raspiblitz#2863]
I'm using Pi 3B. No LCD screen, only HDMI. 

I get stuck in the line:
found device /dev/disk/...

**Comment by cryptodengo** [comment]
Could you please help me?
Thanks, happy new year.

**Comment by openoms** [comment]
unplug the hdmi, reboot and connect via ssh as described in the readme

**Comment by cstenglein** [comment]
@cryptodengo  is this still an issue with 1.9.0?

Closing this for now, please re-open if it still persists.
