### ISSUE TITLE
Raspiblitz doesn't enter SSH Main Menu after completing sync

### ISSUE THREAD

**Issue by treebeard4** [raspiblitz/raspiblitz#2865]
Hi all,

I'm a newbie who bought a Raspiblitz with a pre-synced blockchain a few weeks ago. The initial setup worked fine and the node quickly synced the newest blocks to reach 100.00%. From there it didn't enter the SSH Main Menu, but remained on the "Node is Syncing" screen. 
Issue #2643 seems to describe a similar problem - my Raspiblitz doesn't switch to the Main Menu at all though. The suggested solution for issue #2643 (running patch and then restart) didn't fix the problem. 
Any ideas what to try next? 
Thanks!

**Comment by openoms** [comment]
reflash your SDcard with the latest image as in the readme:
https://github.com/rootzoll/raspiblitz#downloading-the-software

won't need to download the chain again

**Comment by treebeard4** [comment]
After reflashing the SDcard, the issue remains unsolved. I've left the Raspi running for 24 hours, it still shows the "Node is syncing" screen with 100.00% progress and between 10 and 13 peers.
Is there anything else I can try next or any other info I can provide?
Thanks!

**Comment by openoms** [comment]
press ctrl+c

type:
`menu`
for the menu

check the LNDLOGS in SYSTEM

type:
`debug`
for more logs

**Comment by treebeard4** [comment]
Enabling the touchscreen and rebooting the Raspi seems to have solved the issue. Thanks for the help :)
