### ISSUE TITLE
Changing node hex color fails

### ISSUE THREAD

**Issue by block57043** [raspiblitz/raspiblitz#2868]
Hi all,

I'm new here but wanted to report an issue I found. I was trying to change my node's hex color using the following command: lightningd --rgb 000000 and I received an error that ended with "STATUS_FAIL_INTERNAL_ERROR: Failed to bind on 2 socket: Address already in use". I also tried it with an = after rgb and also received the same error. I ended up manually editing the lnd.conf myself to change the color but wanted to raise the issue here.

**Comment by openoms** [comment]
set the color in the c-lightning config file instead

**Comment by cstenglein** [comment]
@sawyer655321 is this still relevant? Closing for now, if it's still relevant, please re-open
