### ISSUE TITLE
Cancelling alias change

### ISSUE THREAD

**Issue by AngelicInsight** [raspiblitz/raspiblitz#287]
I opened the alias change menu item but selected the cancel option without entering an input. The Raspberry Pi automatically rebooted and now loops with the following error after entering password A.

![raspiblitz_error](https://user-images.githubusercontent.com/46824053/51508594-cea3d500-1daa-11e9-9a08-6e08eb12e8ec.PNG)

Running 1.0 RC3 (0.99-2019-01-22) with Litecoin

**Comment by AngelicInsight** [comment]
A fresh SD card image appears to have returned it to normal functionality.

**Comment by rootzoll** [comment]
Thanks for the report. The  "alias change" is kind of fresh - will check/fix the cancel option again.

**Comment by rootzoll** [comment]
OK fixed and tested again. Works :) Closing issue.
