### ISSUE TITLE
Lightening Not Syncing

### ISSUE THREAD

**Issue by KUKID24** [raspiblitz/raspiblitz#2873]
My node has been in the syncing status for over a month now. Blockchain progress hit 100% after the first few days but lightening has been "waiting" and hasn't progressed at all since then.

**Comment by openoms** [comment]
ctrl+c
type:
menu
SYSTEM - LNDLOGS
to see what the problem is

**Comment by KUKID24** [comment]
LNDLOGS is not shown as an option under SYSTEM but bitcoinLOG, torLOG, and customLOG are shown. I did find the error lines in the debug report below. 

lndErrorShort='Unknown Error - see logs'
lndErrorFull='[lncli] could not load global options: unable to read macaroon path (check the network setting!): open /home/bitcoin/.lnd/data/chain/bitcoin/mainnet/admin.macaroon: no such file or directory'
# OK: log 'ERROR: [lncli] could not load global options: unable to read macaroon path (check the network setting!): open /home/bitcoin/.lnd/data/chain/bitcoin/mainnet/admin.macaroon: no such file or directory' written to /home/admin/systemd.lightning.log
lndRPCReady=1

**Comment by hermanlim** [comment]
Have you tried running /home/admin/config.scripts/lnd.credentials.sh directly?
There is a script there to reset/check/sync the macaroons.
Obviously you would want to check that the directory /home/bitcoin/.lnd/data/chain/bitcoin/mainnet/ exists! :)

**Comment by openoms** [comment]
the process did not make it to install LND at all yet.
Would suggest to reflash the SDcard with the latest image and restart the setup process.

It will pick up the timechain from the disk, so you won't need to download that again.

**Comment by KUKID24** [comment]
that worked everything seems to be loaded correctly now. Thanks for your help
