### ISSUE TITLE
tor@.service / tor@service failing

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#2877]
There is a failed service:
```
₿ systemctl --type=service | grep tor@
  tor@default.service                                                                               loaded active     running      Anonymizing overlay network for TCP
● tor@service.service                                                                               loaded failed     failed       Anonymizing overlay network for TCP (instance service)
```
fixed by: 
```
sudo systemctl disable tor@service
sudo systemctl reset-failed tor@service
```

I wonder it should not be enabled in https://github.com/rootzoll/raspiblitz/blob/2bb53ceb9626c3d4c43c4cf7f76574db9dc7f6e9/home.admin/config.scripts/tor.install.sh#L221
what do you think @nyxnor ?

**Comment by nyxnor** [comment]
Yes, reset-failed is a good idea, ACK

```sh
  # enable tor services
  sudo systemctl unmask tor@default
  sudo systemctl reset-failed tor@*
  sudo systemctl daemon-reload
  sudo systemctl enable --now tor@ tor@service
  sudo systemctl restart tor@default
```

 reset-failed [PATTERN...]
      so `tor*` would work

**Comment by openoms** [comment]
that is just  a temporary fix until restart. I think  `tor@` should not be enabled at all as it is not part of the default Tor installation either.

**Comment by nyxnor** [comment]
no problem, remove it pls.
just discoverede now it is for instances.

**Comment by rootzoll** [comment]
On a test recovery on LIT its exiting because of an torsocks error @nyxnor @openoms has anyone of you seen this before?

```
Jan 17 09:27:38 raspberrypi torsocks[4109977]: could not load config: could not read UI password: mandatory password for UI not configured. specify either a password directly or a file or environment variable that contains the password
```

**Comment by openoms** [comment]
@rootzoll this is a litd error just appears with torsocks because the binary is run with tor because of the Lightning Terminal Connect would leak the IP otherwise.

Looks like the config does not have the PasswordB placed as the password for the GUI.

Likely fixed with 5970f03d

**Comment by rootzoll** [comment]
OK LIT looks good now.

**Comment by openoms** [comment]
still there on recovery with latest commit on `dev`:
```
sudo systemctl list-units --failed
  UNIT                LOAD   ACTIVE SUB    DESCRIPTION
● tor@service.service loaded failed failed Anonymizing overlay network for TCP (instance service)

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.
1 loaded units listed.
```

**Comment by openoms** [comment]
```
₿ sudo systemctl list-units --failed
  UNIT LOAD ACTIVE SUB DESCRIPTION
0 loaded units listed.
```

**Comment by rootzoll** [comment]
OK looks good so far.  Closing issue for v1.7.2 release.
