### ISSUE TITLE
I can not turn off  plugin cl feeadjuster, it turns on automatically after reboot

### ISSUE THREAD

**Issue by Tracachang** [raspiblitz/raspiblitz#2888]
Hi

I've just tested cl plugin feeadjuster and I decided to turn it off since I am running CLBOSS. I've realized that after a reboot of cl, feeadjuster boots automatically.

I have tried disabling with:
`cl plugin stop /home/bitcoin/cl-plugins-available/plugins/feeadjuster/feeadjuster.py
`
and with:
`config.scripts/cl-plugin.feeadjuster.sh off`

it prints the message that it is not enabled/uninstalled:

`default config entry for 'feeadjuster' exists
Stop the 
{
   "code": -32602,
   "message": "Could not find plugin home/bitcoin/cl-plugins-enabled/.py"
}
 delete symlink
 Edit /home/bitcoin/.lightning/config
 The  was uninstalled`

But every time I reboot or restart cl, I have to stop it manually since feeadjusters starts automatically.

**Comment by openoms** [comment]
Thanks for reporting. Now it is fixed in `dev` for the next release. 
To remove the plugin on your system run:
  ```
  plugin="feeadjuster"
  source <(/home/admin/config.scripts/network.aliases.sh getvars cl mainnet)
  
  echo "Stop the ${plugin}"
  $lightningcli_alias plugin stop home/bitcoin/${netprefix}cl-plugins-enabled/${plugin}.py

  echo "# delete symlink"
  sudo rm -rf /home/bitcoin/${netprefix}cl-plugins-enabled/${plugin}.py
  
  echo "# Edit ${CLCONF}"
  sudo sed -i "/^feeadjuster/d" ${CLCONF}

  # setting value in raspi blitz config
  /home/admin/config.scripts/blitz.conf.sh set ${netprefix}feeadjuster "off"

  echo "# The ${plugin} was uninstalled"
  ```
