### ISSUE TITLE
Ip2tor subscription issue 

### ISSUE THREAD

**Issue by jmillionaire** [raspiblitz/raspiblitz#2889]
Hi, @openoms, I contacted you on Twitter about trying to re-establish a IP2TOR subscription. I cancelled my subscription, have tried renewing and it times out.

**Comment by openoms** [comment]
Are you on the latest release: v1.7.1? 
Are you able to pay other LN invoices?

@rootzoll is there anything to do client side to update an IP2Tor subscription?

**Comment by frennkie** [comment]
@jmillionaire sorry for the inconvenience... there was a system crash on ip2tor some days ago. Services were restored but unfortunately the backend LND node was down yesterday - therefore you got those timeouts. Node is back online since 3am and it should work - please try it.

**Comment by frennkie** [comment]
Please make sure that you order the bridge correctly - especially if you use the "custom" feature. I have on request from yesterday for the address: `02...ac@ir..qd.onion:9735:9735` <- this can not work.
It you only be `ir..qd.onion:9735`.

**Comment by jmillionaire** [comment]
@frennkie i've tried each site (fra, nam) and the process gets stuck at `#### Paying invoice ...` 

anything you can see on your end for invoice: `lnbc280n1ps7...d9hqq5clprc` ?

thanks for your help.

**Comment by jmillionaire** [comment]
sorry, just now understood your correction above. tried again trimming the address, it's still stuck on `#### Paying invoice ...`

`# invoice: lnbc300n1ps7...0eqptdvdjv`

**Comment by jmillionaire** [comment]
i'm seeing 2 payments completed in RTL now, though, but no active subscription in my Raspiblitz.

**Comment by jmillionaire** [comment]
finally worked. thanks!
