### ISSUE TITLE
LN Unknown Chain

### ISSUE THREAD

**Issue by VinceDot** [raspiblitz/raspiblitz#289]
Hello I am trying to setup my Raspberry PI with Raspiblitz 0.99 and have successfully downloaded the torrents but now that I created my LN wallet I am not being asked to unlock my LN wallet, this is the message I get : 

`Unlock LND Wallet --> lncli --chain= unlock`

`HELP: Enter your PASSWORD C`
`You may wait some seconds until you get asked for password.`

`[lncli] unknown chain:`

Thanks for your help

**Comment by rootzoll** [comment]
Is this on first reboot after creating your wallet? 

It seems that on your install is getting no info about the selected network from /mnt/hdd/raspiblitz.conf

Can you check if this files exists and when it exists post the content of it? Thx.

**Comment by hikedev** [comment]
I did run into the same issue with "raspiblitz-0.99-2019-01-22". [lncli] unknown chain:
I think its a timing problem when you press to fast or instant ok when you setup lightning the first time.

Even if I did add the raspiblitz.conf with the expected values you will run into more lnd and missing files issues, as a result, the installation will not continue to set up the firewall(ufw) settings etc...

I went with rewriting the img to the sd card from scratch and kept the blockchain like in a normal update and during setup I always did wait the maximum amount of time during the progress screens and now everything works fine.

Thanks for the amount of work you guys put into this, alone from the few scripts I overlooked I can tell this was quite some work. ;)

**Comment by VinceDot** [comment]
I will try rewriting the img because effectively I do not have raspiblitz.conf on my HDD. I may have been too fast when pressing ok I will try to wait more between user prompts

Thanks for your help

**Comment by VinceDot** [comment]
I'm now getting the same issue as #293 whenever I launch my Raspberry after rewriting the img. Using "raspiblitz-0.99-2019-01-22".

**Comment by rootzoll** [comment]
This is a bug we have to look deeper into and analysis already started in ticket #293.

**Comment by VinceDot** [comment]
If I can give further information about this problem, I tried running `./XXsyncScripts.sh dev -clean` and I could start the setup again from scratch, it recognized the blockchain on HDD but then apparently couldn't connect to the bitcoind server. 

![capture](https://user-images.githubusercontent.com/38355904/51792453-5fb2eb80-21b1-11e9-9086-fae6b40235b1.PNG)

I tried running `lsblk && ls -al /mnt/hdd && cat /mnt/hdd/raspiblitz.conf` but apparently raspiblitz.conf is missing.

![capture 2png](https://user-images.githubusercontent.com/38355904/51792459-85d88b80-21b1-11e9-9cbf-c3a4706b4c22.PNG)
