### ISSUE TITLE
Add Jam to Raspiblitz WebUI

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2891]
For v1.7.2 the JoinMarket WebUI was merged but just available thru commandline install - see #2747 

For v1.8 update and integrate into SSH and Web one-click install menus.

**Comment by rootzoll** [comment]
The RaspiBlitz will start for v1.8.0 with just a limited set of apps to install over WebUI - but JoinMarket is a hot candidate for a quick follow up 1.8.1 release.

**Comment by dergigi** [comment]
> JoinMarket is a hot candidate for a quick follow up 1.8.1 release

Awesome! [v0.0.6](https://github.com/joinmarket-webui/joinmarket-webui/milestone/5) will be quite okay already, and I hope that we'll be having something proper (and almost feature-complete) with [v0.0.7](https://github.com/joinmarket-webui/joinmarket-webui/milestone/6). Getting there!

**Comment by openoms** [comment]
Related PR: #3321 

A few more tasks:
- [x] add Jam to menu and recovery
- [x] expose the order-book on /obwatch with nginx. needs: https://github.com/openoms/joininbox/pull/98
- [x] make the display (00infoBlitz.sh) recognise when the YG is running with Jam
- [x] test

**Comment by rootzoll** [comment]
TODO: Make it WebUI ready. @openoms image content & description needed.

**Comment by openoms** [comment]
Referring to https://jamapp.org/

**Comment by cstenglein** [comment]
Added issue here as well https://github.com/cstenglein/raspiblitz-web/issues/519

**Comment by rootzoll** [comment]
Because of time constrains - pushing this to v1.10

**Comment by rootzoll** [comment]
OK Backend & WebUI prepared: https://github.com/cstenglein/raspiblitz-web/pull/545#event-8064122396

ToDo on RaspiBlitzScripts:
- [x] install/on fatpack
- [x] status

**Comment by rootzoll** [comment]
OK I prepared the installscripts of JAM (and JoinMarket as dependency) for the need to be installed by WebUI - see & test on branch: `2891-webuiapps` - BUT there is one thing thats still a bit tricky:

@openoms I added in that branch the `install` action on the JAM & JoinMarket install scripts. But still the most of the joinmarket install is happening in the `on` section - I think on calling a script from JoinInBox here: https://github.com/rootzoll/raspiblitz/blob/6bd2e38f610aadcb22e02fd03ec37b266eed50cd/home.admin/config.scripts/bonus.joinmarket.sh#L228 .. is there a way to already call just the install/compile without the inital config? So when the WebUI calls the `on` it will not take multiple minutes anymore?

**Comment by openoms** [comment]
The `install` option can call only the install without config with:
```
sudo -u joinmarket /home/joinmarket/install.joinmarket.sh -i install
```

Then the `on` option can do:
```
# configure joinmarket (includes a check if it is installed)
sudo -u joinmarket /home/joinmarket/start.joininbox.sh

# set the raspiblitz.conf
/home/admin/config.scripts/blitz.conf.sh set joinmarket "on"
```

**Comment by rootzoll** [comment]
@openoms the `install` section of the joinmarket install script had still a lot of config section that require the HDD/SSD being already available in it - I think I moved most of them over in to the `on` section (see branch `2891-fix` as long as not merged) but I think I still saw some references of the JoinInBox referring to `/home/joinmarket` which later on in the `on` section gets linked to `/mnt/hdd/app-data/.joinmarket` .. are you sure there is no config going on when calling `install.joinmarket.sh -i install`. 

```
gpg: Signature made Sun 09 Oct 2022 13:50:05 BST
gpg:                using RSA key 13C688DB5B9C745DE4D2E4545BFB77609B081B65
gpg: Good signature from "openoms <oms@tuta.io>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 13C6 88DB 5B9C 745D E4D2  E454 5BFB 7760 9B08 1B65
# goodSignature(1)
# correctKey(1)

##########################################################################
# OK --> the PGP signature of the checked out v0.7.4 tag is correct
##########################################################################

cp: -r not specified; omitting directory '/home/joinmarket/joininbox/scripts/jam-remote'
cp: -r not specified; omitting directory '/home/joinmarket/joininbox/scripts/standalone'
# Set ssh access off with the joinmarket user
grep: /home/joinmarket/joinin.conf: No such file or directory
joinmarketSSH=on

# Disable ssh access with the joinmarket user
touch: cannot touch '/home/joinmarket/joinin.conf': Permission denied
```

Please during ReleaseCadidate make sure to test all of JAM on the RaspiBlitz fatpack image - and not just on the VMs, etc.

**Comment by rootzoll** [comment]
OK Jam will be part of the next v1.9.0 release. Closing issue.
