### ISSUE TITLE
Is it possible to clone the microSD card and everything works?

### ISSUE THREAD

**Issue by henkisdabro** [raspiblitz/raspiblitz#2894]
I received the recommended `Samsung Endurance PRO` microSD card in the mail and would now like to migrate my existing raspiblitz install from my current Sandisk microSD card onto this new Samsung microSD card. How can I clone this microSD card (recommended procedure) and can I rest assured the entire setup will work exactly as intended if cloned?

**Comment by openoms** [comment]
In short just choose a procedure for your operating system: https://duckduckgo.com/?q=how+to+clone+an+sdcard

However the best course of action is just to wait for the next SDcard image release and flash it on your new card and keep the old as a backup.
