### ISSUE TITLE
SYSTEM Monitoring + Configuration 

### ISSUE THREAD

**Issue by The34Goon** [raspiblitz/raspiblitz#2896]
When did the lightning options get removed from this menu?
![image](https://user-images.githubusercontent.com/60571408/149756684-1d33e02b-6319-41bb-b857-eebf7424e3a5.png)

**Comment by openoms** [comment]
put
`lightning=on`
to your 
`/mnt/hdd/raspiblitz.conf`

**Comment by rootzoll** [comment]
@openoms `lightning` in conf should normally be `lnd` or `cl` (if those implementations installed & active)  ... the value `on` might make problems down the road.

**Comment by The34Goon** [comment]
lnd is what I had in at first and then changed to =on, after which everything broke.

Now back to lnd but still no log option.

**Comment by openoms** [comment]
sorry, was wrong from memory
so use:
`lightning=lnd`
and try adding:
`lnd=on`
if it is not there
