### ISSUE TITLE
CL: test seed and expose the hsm-secret hex

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#2897]
Basic idea (and manual process)
```
# display:
sudo -u bitcoin xxd /home/bitcoin/.lightning/bitcoin/hsm_secret

# get seed and generate an hsm_secret in a temporary location:
lightning-hsmtool generatehsm /dev/shm/test_hsm_secret

# compare
xxd /dev/shm/test_hsm_secret

# delete temp file
srm /dev/shm/test_hsm_secret
```

To back up the hsm secret need to only write down the alphanumeric charachters in the two lines displayed with:
```
sudo -u bitcoin xxd /home/bitcoin/.lightning/bitcoin/hsm_secret
```

To restore (example from https://lightning.readthedocs.io/BACKUP.html#backing-up-your-c-lightning-node):
```
cat > hsm_secret_hex.txt <<HEX
00: 30cc f221 94e1 7f01 cd54 d68c a1ba f124
10: e1f3 1d45 d904 823c 77b7 1e18 fd93 1676
HEX
xxd -r hsm_secret_hex.txt > hsm_secret

sudo chown bitcoin:bitcoin hsm_secret

# move in place (will overwrite! - remove the ##)
## /home/bitcoin/.lightning/bitcoin/hsm_secret

chmod 0400  /home/bitcoin/.lightning/bitcoin/hsm_secret
```

**Comment by openoms** [comment]
there is also https://github.com/rsbondi/clightning-go-plugin/tree/master/dump_keys to create an xpub and xpriv from the hsm_secret.

Will need to figure out how to build it and try.

**Comment by openoms** [comment]
The next candidate is: https://github.com/jb55/clightning-dumpkeys

```
# install the secp256k1 library
cd ~/Downloads
git clone https://github.com/bitcoin-core/secp256k1.git
cd secp256k1
./autogen.sh
./configure
make
make check  # run the test suite
sudo make install
```
```
# configure dynamic links
sudo ldconfig
```

```
# build clightning-dumpkeys
cd ~/Downloads
git clone https://github.com/jb55/clightning-dumpkeys
cd clightning-dumpkeys
make
```
Usage:
```
cd ~/Downloads/clightning-dumpkeys
sudo -u bitcoin ./clightning-dumpkeys /home/bitcoin/.lightning/bitcoin/hsm_secret
```
How to use the result: https://github.com/jb55/clightning-dumpkeys#output-descriptors


Also the root public keys can be exported with: 
```
lightning-hsmtool dumponchaindescriptors /home/bitcoin/.lightning/bitcoin/hsm_secret
```

**Comment by rootzoll** [comment]
@openoms can we close this issue or does this documentation still needs some transfere?

**Comment by openoms** [comment]
will close this as recorded in the FAQ.cl.md, but will open a new one once I find a way to import a descriptor or xpub to an external wallet (other than the bitcoin-cli)
