### ISSUE TITLE
If upnp is enabled for lnd and a upnp router isn't available, lnd shuts down and wallet cannot be unlocked

### ISSUE THREAD

**Issue by nkinnan** [raspiblitz/raspiblitz#2907]
This is rather confusing since all you see is "unknown failure".  Took me a while to figure out what was going on.

**Comment by rootzoll** [comment]
Thanks for the report. Its to be considered to remove this option from the RaspiBlitz SETTINGS menu and also remove the `lnd.autonat.sh` option for the v1.8 ... because its a simple option in the `lnd.conf` that does not need an extra config entry anyway.

**Comment by rootzoll** [comment]
Removed for v1.8 release. Closing issue.
