### ISSUE TITLE
RESEARCH: Check synergy with Casa one OpenSourced

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#291]
Casa is going to open source their set end of Jan - they say:
https://twitter.com/CasaHODL/status/1086687198232088576

Lets check it out and see what can be reused - for example the WebUI for Setup process would be something to look at.

**Comment by rootzoll** [comment]
https://hub.docker.com/u/casanode

**Comment by nyxnor** [comment]
Plan to reuse Casa or this can be closed as there is another issue about "add admin webUI".
