### ISSUE TITLE
LND: how to test the seedwords (aezeed) with chantools

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#2911]
Again a tool from Oliver in chantools:
https://github.com/guggero/chantools/blob/master/doc/chantools_derivekey.md#chantools-derivekey
```
chantools derivekey --identity --neuter
```
Will prompt for the 24 words in the terminal and displays the nodeID which can be compared to the running setup.

I am reluctant to put this into any menu to not encourage people to enter seedwords anywhere, but can make a good FAQ entry.

**Comment by rootzoll** [comment]
@openoms will you do a FAQ entry on this for v1.8.0?
