### ISSUE TITLE
New raspios_arm64-2022-01-28 

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#2915]
New update of our base image:

https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2022-01-28/

@rootzoll I think it would be worth it to base the next RC on this to avoid a long `apt update && apt upgrade`

**Comment by rootzoll** [comment]
OK - the bootscreen has on fresh install some warning on ssh (because we deleted old certs fro relase) .. but the rest seems fine with the updated base image during RC2 testing. So closing this image for v1.7.2 release.
