### ISSUE TITLE
CL: encrypt hsm_secret before backup to make sure it is not running again

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#2925]
To guarantee that the CL node is not started accidentally after backup the `hsm_secret` should be encrypted and locked

**Comment by rootzoll** [comment]
Do you want this still for v1.7.2 or do we push for later release?

**Comment by openoms** [comment]
yes, would like to get it done as just force closed a few channels because of this

**Comment by rootzoll** [comment]
OK .. you should be no problem to work on this while the RC2 is out and then have it part of RC3 for quick testing before final v1.7.2 release.

**Comment by openoms** [comment]
tested
- [x] cl  BACKUP and 
- [x] MIGRATION

restoring at the start work too both with the 
- [x] migration and
- [x] rescue file

can test the menu once more
- [x]  FILERESTORE
- [x]  SEEDRESTORE

**Comment by rootzoll** [comment]
@openoms can we close issue for release?

**Comment by openoms** [comment]
will run those two more tests, but not expecting new issues

**Comment by openoms** [comment]
Ok, tested succesfully and closing.

Found a non-showstopper issue, to be fixed later: #2979
