### ISSUE TITLE
:,(  Special Characters

### ISSUE THREAD

**Issue by OfficialBigAl** [raspiblitz/raspiblitz#2931]
Hi,

Trying to recover wallet from 2019 (Version 1.1/1.2) and LND Password & Seed contain special characters. 
From the command line I've tried to 'LnCli Create' and manage to get all the way though to the end but get RPC errors.
 
Is there a way to allow special characters in passwords.

Regards Al.

**Comment by rootzoll** [comment]
Thru the raspiblitz SSH-UI we dont allow special characters in passwords to prevent such problems. But basically if you use the `lncli` commands directly and you still get problems its best to consult with the lnd dev support slack: https://lightning.engineering/slack.html

**Comment by cstenglein** [comment]
@giybs372 is the issue still relevant?

closing for now, if it still relevant, please re-open the issue. :)
