### ISSUE TITLE
Dirty update to dev or v1.7.2

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#2934]
Having questions about errors after patching from v1.7.1 to dev (or v1.7.2 later when it is merged to the v1.7 branch)

This continues to be not the intended update method and if running into issues the quickest solution will be to reflash the SDcard with the latest image.

Some setups are salvageable so will make notes here:

To fix redis in `admin`:
```
sudo apt install redis-server
cd
sudo ./_background.scan.sh install
sudo ./_background.scan.sh
restart
```

**Comment by rootzoll** [comment]
Yeah `patching` from the menu is not the recommended update method - especially for this release. A fresh sd card image is needed. But its good to have some advise noted down ... just in case someone goes that route.

**Comment by openoms** [comment]
Also a good time to run a full:
```
sudo apt update
sudo apt upgrade -y
```

**Comment by openoms** [comment]
To bring everything up-to-date (summarizing together with the above):

```
sudo apt update
sudo apt upgrade -y

python_libs="grpcio==1.42.0 googleapis-common-protos==1.53.0 toml==0.10.2 j2cli==0.3.10 requests[socks]==2.21.0"
torbox_libs="pytesseract mechanize PySocks urwid Pillow requests setuptools"
sudo -H python3 -m pip install --upgrade pip
sudo -H python3 -m pip install ${python_libs} ${torbox_libs}

sudo apt install -y redis-server
cd
sudo ./_background.scan.sh install
sudo ./_background.scan.sh
restart
```

**Comment by cstenglein** [comment]
We are on 1.9.0 already => closing
