### ISSUE TITLE
Dropbox option still part of README

### ISSUE THREAD

**Issue by ralf-br** [raspiblitz/raspiblitz#2935]
Dropbox support was removed from the menu 
https://github.com/rootzoll/raspiblitz/commit/11bf41d3620a3f3163e248737005c3206df57ded#diff-7c21b01079dae13797c3ca0c4c1093cee6741e9885abdc5f92b4f52c484b282f

but is still part of the README
https://github.com/rootzoll/raspiblitz/tree/dev#a-dropbox-backup-target

That part should be deleted or linked to the existing NextCloud description. https://github.com/rootzoll/raspiblitz/tree/dev#lnd-staticchannelbackup-on-nextcloud

Sorry for all those README "issues" and not directly providing pull requests... Maybe in the future.

**Comment by rootzoll** [comment]
Thanks for the notice. Removed the dropbbox section. Will be part of v1.7.2 release.
