### ISSUE TITLE
LCD Info Fixes

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#295]
see https://twitter.com/derPUPE/status/1089572872841035779

IPv6 still breakes line & headline says "+ TOR" but addresses dont run that way

**Comment by fluidvoice** [comment]
Mine still does this too.

**Comment by rootzoll** [comment]
@fluidvoice I commited a fix to the dev branch. Can you test if this fixes the line break on your RaspiBlitz? You can check out dev branch scripts with: `./XXsyncScripts.sh dev` - will not delete other added scripts and update this way should be OK, when you run the 0.99 base image.

**Comment by fluidvoice** [comment]
OK will try.  FYI, if I seemed to disappear it's I'm travelling for the next few weeks.  Not sure yet if I'll bring my Raspiblitz with me. ;-)

**Comment by fluidvoice** [comment]
Looks good!  Will try to test TOR later if possible. As said above, will be offline a lot.

![Image](https://i.imgur.com/c3SeVGI.png)

**Comment by rootzoll** [comment]
@fluidvoice thanks a lot and save travels :)

I tested TOR mode and looks good. I will close this issue for now.
