### ISSUE TITLE
[v1.7.2rc2c] No QR codes on LCD

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#2956]
The display device seems to have changed.

The LCD is not on `/dev/fb1` any more, but on `/dev/fb0`
And it is not writable with `admin`:
```
$ sudo ls -la /dev/fb0
crw-rw---- 1 root video 29, 0 Feb 12 20:40 /dev/fb0
```
Will need sudo for /dev/tty1
```
ls -la /dev/tty1
crw------- 1 root root 4, 1 Feb 12 20:52 /dev/tty1
```

**Comment by openoms** [comment]
when switching to HDMI it appears on `/dev/fb0` as well, so no distinction is needed any more.

**Comment by openoms** [comment]
Well now switched back to LCD and `/dev/fb1` appeared - now that is the LCD :/.

Can anyone reproduce this?

**Comment by openoms** [comment]
Right, it seems that the script was taking care of this behaviour, the original problem is caused by the lack of `sudo` with fbi.

**Comment by rootzoll** [comment]
OK PR merged.

**Comment by rootzoll** [comment]
Thanks - this fixed it. Closing issue for v1.7.2 release.
