### ISSUE TITLE
No HDD available space check

### ISSUE THREAD

**Issue by thelwyn** [raspiblitz/raspiblitz#296]
If it's still time for the 1.0 release, that would be nice to add a check of the available space on the HDD before starting to download the blockchain.

I found out after 120Gb of download that I had plugged the wrong HDD and that obviously that wouldn't be enough for a >250gb blockchain =)

I know, all blame is on me, but still, that would be nice!

**Comment by rootzoll** [comment]
Thanks for sharing your experience. I added a small HDD size check for version 1.0 release.

**Comment by thelwyn** [comment]
Great!
