### ISSUE TITLE
Make LND auto-compact default

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#2967]
Getting regular reports of system slowdowns and channel.db-s of multiple GBs in long running or very active nodes.
Compacting the channel.db helps always, so would make sense to make it regular by default.
The default timeout is 1 week, we could make it like 2 months so it wouldn't compact on every restrart.

Note that only the first compact process takes very long.

Will also be able to  compact manually from the menu: https://github.com/rootzoll/raspiblitz/issues/2752

**Comment by rootzoll** [comment]
@openoms can we close issue for release?

**Comment by openoms** [comment]
yes, this method of compacting was tested extensively
