### ISSUE TITLE
P2SH vs Bech32 Balance

### ISSUE THREAD

**Issue by RolfHodl** [raspiblitz/raspiblitz#297]
Hello Folks,

in the settings menu in zap you can chose between p2sh (standard setting) or bech32. If you move funds to the p2sh and bech32 only one balance is shown and not added up. So if you remove funds, lets say from the bech32, it shows a balance of 0, but still some sats on the p2sh. After a reboot it then shows the remaining balance on the p2sh address.

Is it possible to get a total of both or show each type of balance?

**Comment by rootzoll** [comment]
This seems a ZAP related question .. I would advise to ask the question on their repo: https://github.com/LN-Zap
