### ISSUE TITLE
dev 1.7.2.rc2  build_sdcard.sh on Ubuntu 20.04

### ISSUE THREAD

**Issue by mrsieb** [raspiblitz/raspiblitz#2970]
Installing on VM or Similar Environment 

wget https://raw.githubusercontent.com/rootzoll/raspiblitz/dev/build_sdcard.sh
sudo bash build_sdcard.sh -f true -b dev -d headless -t false -w off

Parameter Call is different now 

Script stops because of python version.
have to add ppa and manually install python 3.10 to pass through.
`sudo add-apt-repository ppa:deadsnakes/ppa`

Original Version is 3.7 on the OS

Fresh LND wallet generaton still fail because of missing google modules

after installing 
`sudo python3 -m pip install grpcio grpcio-tools googleapis-common-protos pathlib2`
wallet generations works

Afterwards everything runs like a charme, "HDD" detection seams also working without any workaround.

_Originally posted by @mrsieb in https://github.com/rootzoll/raspiblitz/issues/2661#issuecomment-1041399492_

**Comment by mrsieb** [comment]
@openoms 
What would be the correct way to update a system with this method?
I just tried to call the script from the main branch, the script fails with lnd 14.2 already installed so it runs not to the end.
Anyhow after a reboot it seams the system is running on 1.7.2 main. (only i have to set Password A again)

I mean how to trick the system  to run the update process like if it is done over the menu when it runs on a PI?
Of course i cloud complete delete the OS and start from a fresh OS but i think this is not necessary.

**Comment by openoms** [comment]
There is no update process. The update option makes a rescue file as a backup and shuts down prompting to reflash.

You can use the patch menu being aware of this https://github.com/rootzoll/raspiblitz/issues/2934.

**Comment by mrsieb** [comment]
> You can use the patch menu being aware of this #2934.
Thx, one other thing 

**Not supported/untested** is moving the data directory between different operating systems (for example MacOS <-> Linux or Windows <-> Linux) or different system architectures (for example ARM -> amd64). Data corruption or unexpected behavior can be the result. Users switching between operating systems or architectures should always use Option 2!

Do you have experience migrate lnd from ARM -> amd64 ?

**Comment by openoms** [comment]
yes, multiple times, without issues. https://twitter.com/openoms/status/1407377844024528905?s=19

Will close this issue as no longer relevant to the OP.
