### ISSUE TITLE
[Update] Lightning-Terminal Update to v0.6.3-alpha

### ISSUE THREAD

**Issue by shadowcpy** [raspiblitz/raspiblitz#2971]
Update the Lightning Terminal to v0.6.2-alpha in 1.7.2
The currently used version in 1.7.1 sets a too low MaxMinerFee, leading to failed loop outs
The CLI still works, as one can override the setting there
[Relevant Issue](https://github.com/lightninglabs/lightning-terminal/issues/307)

**Comment by openoms** [comment]
Thank you for the report! It looks like the fix did not make it into a release yet: https://github.com/lightninglabs/lightning-terminal/issues/303#issuecomment-1002202213, but we should look out for it.


Also note that the `bos` command line can be used too to Loop out, see the options with:
`bos increase-inbound-liquidity -h`

**Comment by openoms** [comment]
good timing https://github.com/lightninglabs/lightning-terminal/releases/tag/v0.6.3-alpha

**Comment by openoms** [comment]
updated ok to v0.6.3 just by changing the version number, but it doesn't accept my password_B

edit: needed to unlock the lnd wallet - reported the UX nit on Slack

**Comment by rootzoll** [comment]
Test worked. Closing for release.
