### ISSUE TITLE
50copyHDD.sh is missing from 1.7.1, should be calling blitz.copychain.sh instead

### ISSUE THREAD

**Issue by bfeeny** [raspiblitz/raspiblitz#2974]
98repairBlockchain.sh calls 50copyHDD.sh in several places.  It should instead be calling blitz.copychain.sh

I don't think I have permissions to do a PR, so putting it here so someone can create it.

**Comment by openoms** [comment]
Thanks for the report and you could open a PR, but this is fixed in `dev`.
