### ISSUE TITLE
zapconnect is replaced by lndconnect

### ISSUE THREAD

**Issue by RolfHodl** [raspiblitz/raspiblitz#298]
https://github.com/LN-Zap/lndconnect/releases

qr didn't worked anymore after the "auto login" (new tls was genereated) so I had to download the lndconnect to get it up again.

Maybe upgrade the menu to something like

Connection String for Zap internal IP ./lndconnect -j -i
Connection String for Zap external IP ./lndconnect -j

Keep up the good work Christian!

**Comment by rootzoll** [comment]
Thx for the hint :) 

I updated the dev branch to use lndconnect. Seems to work now - running last tests. Will be part of next release.

Yes, when you turn on/off the auto-unlock ZAP needs to be reconnected. There is a dialog box informing about that. Better integration and UX should be best done with a WebGUI SetUp/Manahing ... but thats still some way to go.

Closing this issue for now.
