### ISSUE TITLE
loop command fails on 1.7.2

### ISSUE THREAD

**Issue by bfeeny** [raspiblitz/raspiblitz#2982]
Upgraded from 1.7.1 to 1.7.2
Created a few Loop Outs in Lightning Terminal
From command line try to execute some loop commands such as "loop monitor", "loop suggestswaps", etc.
```
admin@172.16.5.244:~‚Çø loop setparams
[loop] unable to read macaroon path : open /home/admin/.loop/mainnet/loop.macaroon: no such file or directory 
```

Error always returned is` [loop] unable to read macaroon path : open /home/admin/.loop/mainnet/loop.macaroon: no such file or directory `

**Comment by openoms** [comment]
see the LIT menu for details about switching to the `lit` user and commands to use

**Comment by openoms** [comment]
Is this solved with typing:
`lit`
then:
`lit-pool -h`
for the options?

**Comment by bfeeny** [comment]
Yes, that works, or just doing lit-loop, I was typing loop

**Comment by openoms** [comment]
ok, thanks for the update. Closing as solved.
