### ISSUE TITLE
Flickering Dialogs during Updateprocess

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2986]
Got report that under

Ubuntu 20.04.3 LTS
Gnome 3.36.8
Standard Terminal

it flickers (strange repeat repeat times & pauses) during update waitscreen process.

**Comment by openoms** [comment]
This has been the case for me in my Debian Desktop default gnome-terminal also since v1.7.1. 
Didn't consider it a bug.

**Comment by JessieRaspi** [comment]
I use the Windows 10 terminal. Same for me since 1.7.1.

**Comment by rootzoll** [comment]
Havent seen this in a long time - cloing. Reopen if anybody still experience with a version >=1.10.0
