### ISSUE TITLE
Touchscreen not booting into status screen (stops at pi shell)

### ISSUE THREAD

**Issue by JoKohono** [raspiblitz/raspiblitz#2991]
With the 1.7.2 update I'm observing that the system boot occasionally stops at the shell (user pi).

All services are running properly though and since it's only approx 1 in 5 times, it's not a serious issue at all. 

However: what is the command(sequence) to manually start the LCD status screen?!

[image](https://user-images.githubusercontent.com/70069936/155395275-202fa783-0b53-4088-a4b0-3b8319ecbff6.jpeg)

**Comment by NilByte** [comment]
`menu` and then select INFO.

**Comment by JoKohono** [comment]
@NilByte : 
Menu>Info produces the status screen with the Blitz on the left. 
 
I was looking for manually starting the status screen on the Touchscreen-UI (with the Info/Node/Invoice/Off buttons). 

But I think I found it: 
As user pi, execute /home/admin/00infoLCD.sh
