### ISSUE TITLE
System keeps disabling ssh password after every update

### ISSUE THREAD

**Issue by w-canvas** [raspiblitz/raspiblitz#2994]
After disabling ssh password one time, system keeps turning it off at every raspiblitz update, while restoring persistent configuration at boot.

Fixed it by placing the `ssh.reset` file on boot partition root and manually changing the `PasswordAuthentication` field to `yes` on the following files inside the ssd:

```
/mnt/hdd/app-data/sshd/ssh/sshd_config
/mnt/hdd/app-storage/ssh-old-backup/sshd_config
```

**Comment by rootzoll** [comment]
Does is now survive updates?

**Comment by w-canvas** [comment]
>Does is now survive updates?

Don't know. Haven't reflashed since.

It did correctly accept my password ssh connection after changing the `ssh_config` files in the ssd.

**Comment by cstenglein** [comment]
@w-canvas Do you still have this issue?

Closed for now, if it still appears, please re-open
