### ISSUE TITLE
armbian-config non-exsitance breaks armbian SDcard build

### ISSUE THREAD

**Issue by harvhat** [raspiblitz/raspiblitz#2995]
line 293 of  build_sdcard.sh

'''
[ "${baseimage}" = "armbian" ] && armbian_dependencies="armbian-config" # add armbian-config
'''

However there is no package called "armbian-config" so the whole 'apt install' line fails while the build script continues on anyway, unsuccessfully of course.

I'm thinking armbian-config should be a variable that points to a list of packages, perhaps?

**Comment by nyxnor** [comment]
We haven't tested armbian for a while. That was an old line if you follow the blames.

Can you check any package with a similar name on armbian? Look at their source repositories.

**Comment by harvhat** [comment]
I didn't realize armbian was a OS distro. The comment in the code "# experimental: fallback for all debian on arm" had me thinking it was just what a moniker for any debian on arm, hence my confusion. Indeed there appears to be a armbian-config package in armbian, however I was not trying to install raspiblitz that armbian so didn't test it. I'm using raspios_arm64 but it didn't get picked up because the hostname was not "raspberrypi" (I already have other raspberrypi's on my network after all!)

That, however, is a different issue. (I added an option to force a particular baseimage which defaults to "auto" to solve that)

More related to this issue though is the build process breaking when even 1 of the items on the apt lengthy install list isn't found, for then _none_ of them are installed, yet the build continues full steam ahead instead if exiting.

I solved this by writing a apt_install() function, which will exit if it fails, and calling that everywhere ```apt install -y``` is called.

Though maybe just a ```|| exit 1``` is all you really need.

**Comment by nyxnor** [comment]
Make a merge request so we can see.
For 1 package to be found would require people running on different systems.

**Comment by harvhat** [comment]
Sorry nyxnor I'm not sure which code you want to see, or even what you mean about finding one package on different systems.

**Comment by harvhat** [comment]
Ok @nyxnor I made a pull request for the apt_install() function bit (#3002) and the "added an option to force a particular baseimage" bits are in the setting-base-os branch of my fork. I don't plan on making a PR for that as I think OS detection needs a more major overhaul anyways. But it's there if you want to see.

**Comment by nyxnor** [comment]
> However there is no package called "armbian-config" so the whole 'apt install' line fails while the build script continues on anyway, unsuccessfully of course.

When using armbian, there is no package called armbian-config, maybe we should update that package name to the new one.

> I didn't realize armbian was a OS distro. The comment in the code "# experimental: fallback for all debian on arm" had me thinking it was just what a moniker for any debian on arm, hence my confusion. Indeed there appears to be a armbian-config package in armbian, however I was not trying to install raspiblitz that armbian so didn't test it. I'm using raspios_arm64 but it didn't get picked up because the hostname was not "raspberrypi" (I already have other raspberrypi's on my network after all!)

Think you answered here.
So if your os wasn't detected, would be great to fix the auto detection if you know how.

**Comment by harvhat** [comment]
I agree, can't say I know how though. What I did for myself was add a ```-o base_os``` option to the command line args, I could make PR for this but I think improving the os detection a better idea. (Maybe do both though?).  I've found Armbian so I can download and test but the other one referred to in the code as "a clean alternative image of debian for RaspberryPi". I don't know where to find that (or which) that is. If you could inform me then I could get that and then look into the detection issue more. This will take me longer then a few days (at least) though.

**Comment by nyxnor** [comment]
> Maybe do both though?

I don't see a problem with adding a `-o` option, I just think it is better if detected, because if it is not detected, it is not supported and if the detection if wrong, then it must be corrected.

Some marker files can be found on neofetch code for os and distro detection.

https://github.com/dylanaraps/neofetch/blob/ccd5d9f52609bbdcd5d8fa78c4fdb0f12954125f/neofetch#L986

**Comment by harvhat** [comment]
That link is helpful for Armbian at least.
Do you know where I can find this "a clean alternative image of debian for RaspberryPi" that sets  ```baseimage="debian_rpi64"```
Does it have a more official name?

**Comment by cstenglein** [comment]
@harvhat  is this still relevant? Closing for now, if it's still relevant, please re-open
