### ISSUE TITLE
Check Webseeds of Torrents and help Seeding

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#3]
RaspiBlitz uses Bittorrent for downloading:

SD-Image: [OUTDATED LINK] --> check end of thread
Blockchain Download: [OUTDATED LINK]  --> check end of thread

If you want to help out: Seeding this torrents would be great.

Both contain WebSeed-URLs for better availability and speed ... but on my test I was not seeing my torrent client using those WeebSeeds. If someone with more torrent expertise could check out if WebSeeds work ... test feedback welcome.

**Comment by rootzoll** [comment]
Webseeds seems ok. Helping to seed the preindexed blockchain is still needed:
Blockchain Download: [OUTDATED LINK]

A question for torrent experts: I have quite a long list of trackers in my list. Is this maybe a downside, when clients connect to different trackers. Or are clients normally checking all trackers and will find all of the other peers?

**Comment by vnnkl** [comment]
not sure what you mean with long list, but if you have more than 4 trackers, consider reducing them.
Peers should be able to find each other by DHT anyway.

see:
https://www.reddit.com/r/torrents/comments/3ysqbt/psa_adding_a_lot_of_trackers/

**Comment by rootzoll** [comment]
@vnnkl thanks for the background. I reduced the trackers and made a new torrent. 

It would be great if anybody can help seed those two torrents:
http://wiki.fulmo.org/downloads/raspiblitz-litecoin-2018-07-29.torrent
http://wiki.fulmo.org/downloads/raspiblitz-bitcoin-2018-07-16.torrent

Older blockchain torrents can be removed.

**Comment by rootzoll** [comment]
TODO: Try Webseed again with new torrent client. #127

**Comment by arcbtc** [comment]
Is anyone seeding the torrent?
![image](https://user-images.githubusercontent.com/33088785/46585731-5cfa8200-ca6c-11e8-9401-4f97604c8108.png)

**Comment by rootzoll** [comment]
@arcbtc its still seeding on my iMac. New torrent is in the works - should have again webseed to support availability.

**Comment by rootzoll** [comment]
rtorrent (debian default) seems not supporting webseed yet :(
https://github.com/rakshasa/rtorrent/issues/66

**Comment by jagottsicher** [comment]
Seeding both lightcoin and bitcoin

**Comment by rootzoll** [comment]
Thanks for all the seeding help. 

Everyone who joined the torrent seeding check that you have the latest torrents:
https://github.com/rootzoll/raspiblitz/tree/master/home.admin/assets
bitcoin: 2018-10-13
litecoin: 2018-07-29

Closing this ticket for now.
