### ISSUE TITLE
Invoice description

### ISSUE THREAD

**Issue by baebb** [raspiblitz/raspiblitz#300]
Hi @rootzoll, would be possible to set an invoice description when generating new lightning invoices? Seems possible by using the `--memo="Hi there"` option in lncli:
![image](https://user-images.githubusercontent.com/8374514/52024258-8a9b9780-2543-11e9-827a-75ec07280ad6.png)

**Comment by rootzoll** [comment]
Yes you can set a invoice this way. But the script on the SSH menu to create an invoice is designed to be as simple as possible to create and test an invoice with your RaspiBlitz. If you want to have more options you can experience the LNCLI directly or you install the RTL webGUI .. there you can set a memo in an invoice much better then any SSH dialog ever could. In future versions of RaspiBlitz its the idea that the RTL webGUI will replace the SSH dialogs anyway.
