### ISSUE TITLE
Question, no issue: Did I just create a second instance of c-lightning?

### ISSUE THREAD

**Issue by robinvonmises** [raspiblitz/raspiblitz#3004]
I just setup my new RaspiBlitz 1.7.2 with c-lightning.

When everything was done, I left the ssh panel to get to the command line.

To change the color of my node i ran

lightningd --rgb blabla

The output was "creating new directory in admin/.lighting [] creating new hsm_secret" etc.....

What have I done?... I rebooted fastly because I thought I am just creating a second instance of c-lightning. Everything seems fine but I still have those files in admins home folder. is it save just to delete them?

**Comment by openoms** [comment]
you have run `lightningd` with the `admin` user, but it runs already with systemd with the `bitcoin` user. You can delete the .lightning dir under admin.

You will never need to run lightningd yourself. Check the FAQ.cl.md an the output of the command:
`alias`
for command line usage specific to the blitz.
