### ISSUE TITLE
[Joinmarket] display the stats in status when the YG started by the joinmarket-API

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#3006]
API docs: https://joinmarket-org.github.io/joinmarket-clientserver/api/

![image](https://user-images.githubusercontent.com/43343391/156266441-bdc6530e-e5fd-4d32-b0ff-866086908be3.png)

**Comment by rootzoll** [comment]
@openoms Whats the status of this issue for v1.9 release?

**Comment by openoms** [comment]
covered in #3321. closing
