### ISSUE TITLE
DynDNS Status red

### ISSUE THREAD

**Issue by ghost** [raspiblitz/raspiblitz#301]
Hello,

first, thanks for this project.

I activated the dyndns service in the settings and I noticed, that the domain is displayed red on the dashboard although the correct IP address is attached to the domain. I am not an expert, but is this line correct?: https://github.com/rootzoll/raspiblitz/blob/c35e28f029d565a648190ce309ec44491158bca9/home.admin/00infoBlitz.sh#L192 
Also is it possible to show the networkConnectionsInfo with dyndns activated?

**Comment by rootzoll** [comment]
@FastTrackBeginner Good catch :) I forgot to replace my static test address there - commited fix to dev branch. Will be part of next release - closing the issue.
