### ISSUE TITLE
Provide credentials to connect Alby browser extension (SSH GUI)

### ISSUE THREAD

**Issue by MoritzKa** [raspiblitz/raspiblitz#3011]
As a user of RaspiBlitz I would like to have a simple access to the credentials that I need to connect to getalby.com. Currently I have to look them up separately. 

Would propose one screen adjustment and 1 new screen:

1. Add Alby to the ["Connect Options"](https://github.com/rootzoll/raspiblitz/blob/v1.7/home.admin/99connectMenu.sh) screen: Connect Alby browser wallet 
2. new screen: Describe how to connect to Alby:
          - To install Alby open https://getalby.com/ with your preferred browser and click on the "Add to browser button"
          - Use these credentials to connect your node
          - (Show) "Public node URL" or "TOR REST URL" (depending how RaspiBlitz is configured): ....
          - (Show) Admin macaroon: ...
         - If you run your RaspiBlitz behind TOR download and install the Alby app as described during the setup process within the extension. The Alby app allows you to easily connect to your node even when you are not in the same network.

**Comment by rootzoll** [comment]
Compare with: #3031

**Comment by rootzoll** [comment]
https://github.com/rootzoll/raspiblitz/pull/3031 merged for v1.8.0 release ... final test of Alby SSH connect menu

**Comment by bumi** [comment]
updated proposal: https://github.com/rootzoll/raspiblitz/pull/3125

<img width="520" alt="image" src="https://user-images.githubusercontent.com/318/168930974-edf690de-5892-4a84-99ad-4b33d99a666f.png">

<img width="820" alt="image" src="https://user-images.githubusercontent.com/318/168930650-ef76c43b-aaa3-4127-b006-3e6bf2d54a57.png">

**Comment by rootzoll** [comment]
OK PR merged - closing issue, will be part of v1.8.0 release :)
