### ISSUE TITLE
blitz.web.api.sh: set Password B as "login_password"

### ISSUE THREAD

**Issue by cstenglein** [raspiblitz/raspiblitz#3013]
The `blitz.web.api.sh` currently uses the `.env.sample` as base and sets the current values afterwards:

https://github.com/rootzoll/raspiblitz/blob/v1.7/home.admin/config.scripts/blitz.web.api.sh#L115

As a user I would like to login using my Password B. This is achieved by setting `login_password` to the Password B in the `.env`.

https://github.com/fusion44/blitz_api/blob/main/.env_sample#L7

**Comment by rootzoll** [comment]
This works already now with password A even - closing issue.
