### ISSUE TITLE
casa node GitHub

### ISSUE THREAD

**Issue by hcarrega** [raspiblitz/raspiblitz#302]
https://twitter.com/casahodl/status/1091103708803346432?s=21

**Comment by rootzoll** [comment]
thanks for the update ... I was waiting for that. Will be important for the further planning of RaspiBlitz after 1.0 release. I hope the RaspiBlitz did a little push into that direction :) I encourage everybody to check it out and let me know your experience in building a casa from custom hardware.

**Comment by nyxnor** [comment]
pls close this.
