### ISSUE TITLE
Local browser on Raspiblitz?

### ISSUE THREAD

**Issue by Nerfzooka** [raspiblitz/raspiblitz#3021]
I'd like to run Specter wallet, but when I enable it says:
>Specter Desktop
>______________
>Open in your local browser...

Is there a local browser on the Raspiblitz?
If so, how does one get to it?

**Comment by openoms** [comment]
Local browser as on your desktop. Open a browser on your computer and use the IPaddress displayed. You an click the link also.

**Comment by Nerfzooka** [comment]
You are right, @openoms, you only see that message if you're SSHed into the Raspiblitz.  That makes sense now.

Thanks!
