### ISSUE TITLE
Getting emergency mode screen on every boot (CTRL+D to continue works)

### ISSUE THREAD

**Issue by kilrau** [raspiblitz/raspiblitz#3039]
I am facing https://github.com/rootzoll/raspiblitz/issues/782 / https://github.com/rootzoll/raspiblitz/issues/1053 with a fresh `1.7.2` c-lightning node setup. Not on first boot, but on every boot thereafter. Re-flashed SSD several times using balena etcher & ubuntu disk image writer to no avail.

It's def the sd card that causes it, not the SSD:
![emergency mode](https://user-images.githubusercontent.com/19181985/159792965-a88d5c87-c5f0-49e3-a6c5-ddf9fce0352b.jpg)

CTRL+D "fixes" it and everything works just fine:
![starting default target](https://user-images.githubusercontent.com/19181985/159793093-de5d64d7-6fe5-4a25-8a95-cf8ef2729ed2.jpg)
![raspiblitz boot success](https://user-images.githubusercontent.com/19181985/159793177-8433ae88-26b2-4bb9-ad2b-e890ebd83d4e.jpg)

Not a perpetual solution though to always have a keyboard on the pi for just this. Manually running `sudo tune2fs -c 1 /dev/mmcblk0p2`, `sudo tune2fs -C 2 -c 1 /dev/mmcblk0p2` and `sudo touch /forcefsck` + reboot didn't help.

Also tried inserting sd card back into computer and running `sudo fsck -f -y /dev/sdb2` (the sd card's `rootfs` partition) which actually seems to have fixed some things:
```
~$ sudo fsck -f -y /dev/sdb2
fsck from util-linux 2.36.1
e2fsck 1.46.3 (27-Jul-2021)
rootfs: recovering journal
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
Free blocks count wrong (60184773, counted=60184769).
Fix? yes

Free inodes count wrong (15436024, counted=15436020).
Fix? yes


rootfs: ***** FILE SYSTEM WAS MODIFIED *****
rootfs: 147436/15583456 files (0.2% non-contiguous), 2270015/62454784 blocks
```

But... still emergency mode on boot.

**Comment by rootzoll** [comment]
Did you tried a new/another sd card?

**Comment by kilrau** [comment]
Yup, with another sd card it works just fine. Since the underlying issue remains a mystery (the "broken" sd card works flawlessly with a plain debian system on the same pi), should we add an entry in https://github.com/rootzoll/raspiblitz/blob/v1.7/FAQ.md#debug ?

Anyhow, closing here.

**Comment by rootzoll** [comment]
Yeah the reason is hard to say - maybe there is one sector bad on the sd card hardware that is critical when running the raspiblitz image but not when running another image on the same sd card hardware.

If you like to add an entry on this as an PR that would be nice. thx.
