### ISSUE TITLE
INFO screen in the LCD display not showing after disabling Lightning capabilities

### ISSUE THREAD

**Issue by raulcano** [raspiblitz/raspiblitz#3040]
Hi all,

I have a Raspiblitz v1.7.1 running on a Raspberry Pi 4.
The extra services I enabled are JoinMarket and Electrum server.

Last week I disabled Lightning, since I was not making use of it. After that, the screen showing in the LCD is a blue one, instead of the typical INFO screen.

![image](https://user-images.githubusercontent.com/1665639/160224870-d92866ae-bb43-4a8b-bfb1-ad64552a7011.png)

If I connect to my node via SSH and click on the Info option, I can in fact see the info screen in my laptop, but not in the LCD display:

![image](https://user-images.githubusercontent.com/1665639/160224907-ee7b6cc7-4eab-4452-a128-ff008eeaea63.png)

I restarted a couple of times and the problem persists.
Also, I tried this:

```
sudo init 3
sudo init 5
restart
```

But no luck either.

Any help will be much appreciated. 
Thanks!

**Comment by openoms** [comment]
Not sure if this is fixed in v1.7.2 should test.

**Comment by rootzoll** [comment]
I tested again on my machine for - it looks OK so far for 1.8.0. Closing this issue for now - but please reopen if you spot the problem again.
