### ISSUE TITLE
[CL] CLBOSS needs a warning

### ISSUE THREAD

**Issue by kilrau** [raspiblitz/raspiblitz#3043]
I was close to a heart attack today when I installed [CLBOSS](https://github.com/ZmnSCPxj/clboss) via the Blitz menu and suddenly funds were seemingly moving out of my CL node. Just CLBOSS doing its thing, but this needs a proper warning that CLBOSS is taking control over funds and will take action right after installation.

**Comment by rootzoll** [comment]
@openoms can you add a notice there for the v1.8 release?

**Comment by rootzoll** [comment]
@openoms is this addressed or should I push to v1.8.1?

**Comment by openoms** [comment]
not yet, but will add a notice to the menu also

**Comment by rootzoll** [comment]
@openoms Can I close for v1.8.0 RC2 release?

**Comment by rootzoll** [comment]
@openoms please signal when we can close this one - or we push to v1.8.1
