### ISSUE TITLE
Fee Report on Status Screen (sat or mSat)?

### ISSUE THREAD

**Issue by RemoRitzmann** [raspiblitz/raspiblitz#3046]
I see on Status Screen the line
Fee Report: 11717 sat
But I guess it is meant to be 11717 mSat.

Thanks for clarifying or updating. 
 
Something else: Since we write 1'000'000.000 in SI-System for one million, it would be great to customize the higher " ' " for thousands instead of using the "." We could set the SI-System view in Node Settings & Options.

**Comment by openoms** [comment]
This is fixed already. You can run 
`patch`
to pull the latest changes from the `v1.7` branch.

We get the numbers straight form the lightning implementation so not dealing with the formattiing.

**Comment by RemoRitzmann** [comment]
Great thanks, that worked fine for me.
