### ISSUE TITLE
High CPU load due to LND on v1.7.1

### ISSUE THREAD

**Issue by rene78** [raspiblitz/raspiblitz#3047]
I'm experiencing rather high CPU usage. Any idea what can be done to fix it?

![image](https://user-images.githubusercontent.com/36115705/161310371-8ecfe0f0-c137-49d9-9fe1-900e6f9ab3a1.png)
![image](https://user-images.githubusercontent.com/36115705/161310582-0786e50e-043f-4ed3-9f6a-2a2b5764742f.png)

**Comment by rene78** [comment]
Looks like I was able to fix it by adding a setting in the lnd config file:

- Enter `sudo nano .lnd/lnd.conf`
- Add the following line to the config file: `db.bolt.auto-compact=1`
- Reboot your Raspiblitz

After some compacting during which the CPU load was still high, everything turned back to normal again.

Found here: https://github.com/lightningnetwork/lnd/issues/6065#issuecomment-987699012

**Question: Would it make sense to add this setting by default?**

**Comment by rootzoll** [comment]
Thanks for the report - adressing the lnd database compaction was also part of the v1.7.2 release. Closing issue.
