### ISSUE TITLE
[Research] Automate image creation with Packer

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#3053]
https://www.packer.io/ as recommended by @bodymindarts looks to be hugely useful tool built for just what we need to make image creation easier.

instead of a long and trusted manual process as in https://github.com/rootzoll/raspiblitz/blob/v1.7/FAQ.md#what-is-the-process-of-creating-a-new-sd-card-image-release and  
https://github.com/rootzoll/raspiblitz/pull/3052
the build could be more automated down to a single line from the start including the installation of the base image.

Related issues: 
https://github.com/rootzoll/raspiblitz/issues/2842
https://github.com/rootzoll/raspiblitz/issues/2389
PR: 
https://github.com/rootzoll/raspiblitz/pull/3052

**Comment by openoms** [comment]
There has been already an initial config done for packer by @nolith and @geco91, but not sure if it has been used so far: https://github.com/rootzoll/raspiblitz/tree/dev/alternative.platforms/amd64/packer

**Comment by openoms** [comment]
there is excellent progress in: https://github.com/rootzoll/raspiblitz/issues/2842

**Comment by openoms** [comment]
# Packer build notes

Workflow on github and locally tested on Debian to generate a .qcow2 format amd64 image.
Works when mounted with libvirt / virsh / virt-manager (https://virt-manager.org/) and also when written to disk with legacy boot (non-UEFI).

Issue: https://github.com/rootzoll/raspiblitz/issues/3053
Templates are sourced from: https://github.com/chef/bento

## Local build
with the [Makefile](https://github.com/openoms/raspiblitz/blob/ci-amd64/Makefile) (needs ~10 GB free space):
```
git clone https://github.com/openoms/raspiblitz
cd raspiblitz
git checkout add-amd64-image-build
make amd64-lean-image
```

## Images generated in github actions
Find the images in the green runs in github actions at:
https://github.com/openoms/raspiblitz/actions

The images are built using the dev branch.

## Write the image to a disk connected with USB
identify the connected disk with `lsblk` eg `/dev/sdd`
```
gzip -dkv debian-11.5-amd64-lean.qcow2.gz
sudo qemu-img dd bs=4M if=debian-11.5-amd64-lean.qcow2  of=/dev/sdd
```
## Convert qcow2 to raw image
warning the raw lean image is 32 GB
```
gzip -dkv debian-11.5-amd64-lean.qcow2.gz
qemu-img convert debian-11.5-amd64-lean.qcow2 debian-11.5-amd64-lean.img
```
and write to a disk connected with USB with Balena Etcher or `dd`.

## Extend the partition on the new disk
* Use Disks to resize the Extended Partition to the full size of the disk
* To extend the LVM:
```
# identify the USB connected disk
lsblk
# download the script
git clone https://git.scs.carleton.ca/git/extend-lvm.git
# run with the disk as the parameter (sde for example)
sudo bash extend-lvm/extend-lvm.sh /dev/sde
```

## Getting started
press CTRL+D to get to a login prompt
username: `admin`
password: `raspiblitz`

## Add Gnome desktop
connect to the internet (easiest to plug in a LAN cable - use a USB - LAN adapter if have no port)
```
sudo apt install gnome
sudo systemctl start gdm
```

## Workflow notes
* Packer .json settings:
    * `disk_size` - the size op the raw image. The .qcow2 file is compressed.
    * `template`  - image filename
    * `output_directory` - directory under builds where the image will be placed

* There is a `vagrant` user set up for the build which will need to be deleted

**Comment by rootzoll** [comment]
Changing the sd card build process is quite a big refactor .. @openoms do you really want to do this for 1.9.0 .. I would at least recommend to push this to 1.10.0

**Comment by openoms** [comment]
The amd64 image creation is now working locally and github actions.

The arm64-rpi image build does run well in GitHub actions now, but not locally yet as don't know how to take this step:
```
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64
```
Related issue to track or contribute to with a solution: https://github.com/mkaczanowski/packer-builder-arm/pull/246

Edit: will try to run the arm64-rpi build without docker locally

**Comment by rootzoll** [comment]
- [ ] check how much the paker script can be used to shorten/optimise the release build process of the sd card

**Comment by rootzoll** [comment]
@openoms I tested this automatic lean-build for rpi: https://github.com/rootzoll/raspiblitz/actions/runs/3741413796

I was not able to flash to a 32GB sd card - only a 64GB sd card worked. It looks like the image is of a size of 32.2GB
![Bildschirm­foto 2022-12-21 um 01 56 40](https://user-images.githubusercontent.com/2472225/208795979-b45c2ce6-4afb-4ffd-b2dc-af730881b577.png)

When then starting up on a rpi was not able to connect per SSH: `Connection refused`

**Comment by openoms** [comment]
Let's reduce it to 28GB then. Can try to debug the image starting as an arm64 VM as well.

**Comment by rootzoll** [comment]
@openoms this is now done? Should add "final testing"?

**Comment by openoms** [comment]
Yes, I am the images for a while so can say the process is mature enough.
