### ISSUE TITLE
BTCPay - NBXPlorer update needs database pinned or migrated to postgesql

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#3055]
For now to keep the old database format it seems that need to add to the 
`Execstart=` line in the nbxplorer systemd service.
```
--nomigrateevts --nomigraterawtxs
```

https://github.com/dgarage/NBXplorer/blob/master/docs/Postgres-Migration.md

**Comment by rootzoll** [comment]
When was this change introduced? Does this effect already people running the v1.7.2?

**Comment by ghost** [comment]
This occurred for me when updating BTCPay from 1.7.2

**Comment by openoms** [comment]
> When was this change introduced? Does this effect already people running the v1.7.2?

no, it is in the last few versions of NBXplorer, not in the one shipped with v1.7.2.

@Bucherbp for now you can reinstall BTCPay from SERVICES to reset to the pinned version.

**Comment by ghost** [comment]
> @Bucherbp for now you can reinstall BTCPay from SERVICES to reset to the pinned version.

Yep, already done, thanks.

**Comment by rootzoll** [comment]
As PR #3096 is mergd - closing this issue.
