### ISSUE TITLE
A possible service that can be added to the service menu REBALANCE-LND

### ISSUE THREAD

**Issue by JMadisonTP** [raspiblitz/raspiblitz#3056]
is it possbile to have rebalance-lND be added to a future update 
https://github.com/C-Otto/rebalance-lnd#using-the-raspibolt-guide
 
Do you think this is a good idea, for re-balancing channels and approx fees or you think BOS is better and no need for it?

**Comment by rootzoll** [comment]
Basically RaspiBlitz is open to add small configuration scripts - but would need to be a PR from somebody.
