### ISSUE TITLE
[AMD64] Server going to standby [Fixed]

### ISSUE THREAD

**Issue by ghost** [raspiblitz/raspiblitz#3060]
The server I am using (an old screenless laptop) went to sleep after a while.
Had to edit /etc/gdm3/greeter.dconf-defaults
Changed sleep-inactive-ac-type='suspend' to sleep-inactive-ac-type='nothing'

**Comment by rootzoll** [comment]
Thanks for sharing - noted for a later release. @openoms or do you have this already as part of another PR?

**Comment by openoms** [comment]
Not in a PR, but https://github.com/rootzoll/raspiblitz/issues/3027 is related.
