### ISSUE TITLE
Is there a chance to get "total_rebalance_fee" onto dashboard of C-Lightning RTL?

### ISSUE THREAD

**Issue by RemoRitzmann** [raspiblitz/raspiblitz#3062]
I see it in lightning-cli rebalancereport, 
 by the way it would be great to switch "lightning-cli rebalanceall" on or off by the menu or from C-Lightning RTL.
 I can start it, but I have not yet found out how to enable it in a way that it is restarting when raspiblitz restarts.

**Comment by rootzoll** [comment]
That is basically a request for the RTL team ... best would be to head over to their GitHub repo and check if there is a similar request already pending or open a new issue: https://github.com/Ride-The-Lightning/RTL/issues
