### ISSUE TITLE
Bug reports: Can't open PID file /mnt/hdd/bitcoin/bitcoind.pid

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#3064]
The dreaded pid file issue is back:
raspberrypi systemd[1]: bitcoind.service: Can't open PID file /mnt/hdd/bitcoin/bitcoind.pid (yet?) after start: Operation not permitted

https://t.me/raspiblitz/100924
![image](https://user-images.githubusercontent.com/43343391/162972378-9b25b975-446e-4629-88cf-e1cfaec839e0.png)
![image](https://user-images.githubusercontent.com/43343391/162972416-e613eb00-f3c9-4102-b69e-35872c326634.png)

Suggested solution to clean the bitcoind service from it, it can be a problem that it is in this custom path on the disk.

My bitcoind works ok without it:
```
₿ sudo systemctl cat bitcoind
# /etc/systemd/system/bitcoind.service
# RaspiBlitz: systemd unit for bitcoind
# based  on https://github.com/bitcoin/bitcoin/blob/master/contrib/init/bitcoind.service
[Unit]
Description=Bitcoin daemon

After=bootstrap.service
Wants=bootstrap.service

# for use with sendmail alert
#OnFailure=systemd-sendmail@%n

[Service]
ExecStartPre=-/home/admin/config.scripts/blitz.systemd.sh log blockchain STARTED
ExecStart=/usr/local/bin/bitcoind -daemonwait \
                                  -conf=/mnt/hdd/bitcoin/bitcoin.conf \
                                  -datadir=/mnt/hdd/bitcoin \
                                  -debuglogfile=/mnt/hdd/bitcoin/debug.log

# Make sure the config directory is readable by the service user
PermissionsStartOnly=true
ExecStartPre=/bin/chgrp bitcoin /mnt/hdd/bitcoin

# Process management
####################
Type=forking
# PIDFile=/mnt/hdd/bitcoin/bitcoind.pid
Restart=on-failure
TimeoutStartSec=infinity
TimeoutStopSec=600

# Directory creation and permissions
####################################
# Run as bitcoin:bitcoin
User=bitcoin
Group=bitcoin

StandardOutput=null
StandardError=journal

# Hardening measures
####################
# Provide a private /tmp and /var/tmp.
PrivateTmp=true
# Mount /usr, /boot/ and /etc read-only for the process.
ProtectSystem=full
# Deny access to /home, /root and /run/user
ProtectHome=true
# Disallow the process and all of its children to gain
# new privileges through execve().
NoNewPrivileges=true
# Use a new /dev namespace only populated with API pseudo devices
# such as /dev/null, /dev/zero and /dev/random.
PrivateDevices=true
# Deny the creation of writable and executable memory mappings.
MemoryDenyWriteExecute=true

[Install]
WantedBy=multi-user.target
```

Can edit with:
`sudo systemctl edit --full bitcoind`

**Comment by rootzoll** [comment]
So you suggest that we run it without custom path by default starting with v1.8?

**Comment by openoms** [comment]
Yes, we don't need to define the path of the pid file.

**Comment by rootzoll** [comment]
OK removed the PID file entries from systemd service/install of bitcoind. Vecause this is just systemd related a simple update/recover should change this on all existing system with an new image. Needs final testing.

**Comment by rootzoll** [comment]
The file /mnt/hdd/bitcoin/bitcoind.pid still gets created (somewhat automatically by bitcoind) but its no longer forced thru config and everything seems to run OK on tests. Closing issue for release.
