### ISSUE TITLE
UX: Main menu back button is not working properly.

### ISSUE THREAD

**Issue by MiguelMedeiros** [raspiblitz/raspiblitz#3065]
### Description
When I click on the `Main menu` button on any dialog screen the script stops and exit directly to terminal.

### Steps to reproduce
1. open `./00mainMenu.sh`
2. select `SYSTEM` option
3. select the `<Main menu>` option

https://user-images.githubusercontent.com/5798170/163505455-7ef2c58f-0102-4b1c-8979-727aa7449b11.mp4

### Expected behaviour
The "back to main menu" option should go back to `./00mainMenu.sh` script.

https://user-images.githubusercontent.com/5798170/163505439-c3de5257-e257-4a9a-b21c-810702961457.mp4

### Possible solution
At the end of the file `./99systemMenu.sh` add the following code:

```bash
# go back to main menu (and show)
/home/admin/00mainMenu.sh
exit 0
;;
```
![image](https://user-images.githubusercontent.com/5798170/163505265-2412720a-6c84-4bc3-a3d8-4c2daa343333.png)

### Observation
Maybe we should fix all the other `Main menu` and `back menu` buttons.

**Comment by MiguelMedeiros** [comment]
I noticed that after syncing everything this bug stopped happening. :thinking:

**Comment by rootzoll** [comment]
Normally `00mainMenu.sh` gets not called during sync and is just ready after sync. You can call it manually also with shortcut `menu`, but its more for special debug/repair operations. Normally it will just be called internally as part of a loop when you call `raspiblitz`... just then the back button returns to main menu.
