### ISSUE TITLE
Satoshis from Channels Missing after lnd problems and forced close

### ISSUE THREAD

**Issue by Lossmerhoddle** [raspiblitz/raspiblitz#3068]
Hi, 
I do no longer see my Satoshis on my Raspiblitz (V1.7.2) after I forced closed all my channels on April 20th. Also my onchain Satoshis are no longer shown.
I did the forced close of channels because lnd no longer worked properly. I was able to start lnd, but as soon as I accessed it via RTL, for example it would chrash. After that I was able to restart. Of course I also restarted the Raspiblitz, that did not help either.
Help would be much appreciated, since there were quite a few Satoshis on my Raspiblitz, at least for my standards.

I checked the transactions via the command "lncli closedchannels" on my Raspiblitz and found the closing_tx_hashes in the blockchain.com search. Status of the transactions there is "confirmed". with 132s confimations for one of the transaction as an example.
Does it just take time to go through or should I take any action?

**Comment by NilByte** [comment]
If you find the transactions confirmed on the blockchain, then it's just the waiting time that hasn't expired yet.

You can try to run `lncli pendingchannels` and see if not it displays info on `blocks_til_maturity`.

https://www.massmux.com/how-to-resolve-waiting-close-status-lightning-channel/?utm_source=rss&utm_medium=rss&utm_campaign=how-to-resolve-waiting-close-status-lightning-channel

**Comment by Lossmerhoddle** [comment]
> If you find the transactions confirmed on the blockchain, then it's just the waiting time that hasn't expired yet.
> 
> You can try to run `lncli pendingchannels` and see if not it displays info on `blocks_til_maturity`.
> 
> https://www.massmux.com/how-to-resolve-waiting-close-status-lightning-channel/?utm_source=rss&utm_medium=rss&utm_campaign=how-to-resolve-waiting-close-status-lightning-channel

Thanks for answering, I ran the command and received the following output:
"{`
    "total_limbo_balance": "0",
    "pending_open_channels": [
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
    ],
    "waiting_close_channels": [
    ]
}"
So there is no info on blocks_til_maturity.

I ran lncli walletbalance and the total_balance and confirmed_balance shows my Satoshis. Since I cannot run RTL, Thunderhub nor lnd from the Raspiplitz Terminal Window, what will be the best and easiest way to move my Satoshis to another wallet before I reinstall lnd on my Raspiblitz? Can the command line call lndcli sendcoins be recommended? Command line still seems to work.

**Comment by Lossmerhoddle** [comment]
Ok, I ran the lndcli sendcoins command and it worked, thanks for your help!
