### ISSUE TITLE
Files not being persisted on hdd

### ISSUE THREAD

**Issue by jaonoctus** [raspiblitz/raspiblitz#3071]
## Description

After the boot and inital config from scratch, if I restart the machine before bitcoind is sincronized, the `/mnt/hdd/bitcoin` folder and many others are missing.

And even if I try to recreate them, after the restart the data there will be lost.

## Environment

- Raspiblitz: v1.7.2
- Machine: Raspiberry 4

**Comment by rootzoll** [comment]
This could be related to your hardware setup (maybe the HDD/SSD controller) what parts are you using? Are they as recommended on the parts list or is it even ordered as a pre-assembled node? https://github.com/rootzoll/raspiblitz#amazon-shopping-list-buy-parts--build-it-yourself

**Comment by godidev** [comment]
Hi! @jaonoctus Did you find a solution? maybe trying different hardware?

I'm having the same problem. Tried to burn raspiblitz img in the sd again and used the same ssd. 
It insta detected the blockcahim and could continue the blockchain syncro, but 5hours later `/mnt/hdd/bitcoin` folder is missing again xd

I'm not using the recommended parts btw, just the parts I already had at home.

**Comment by jaonoctus** [comment]
@godidev not yet.

> I'm not using the recommended parts btw, just the parts I already had at home.

Same

**Comment by cstenglein** [comment]
@jaonoctus  is the issue still present in 1.9.0?

closing for now, if it still appears, please re-open the issue. :)
