### ISSUE TITLE
ERROR: btc-testrun-fail when provisioning

### ISSUE THREAD

**Issue by heyitsmeez** [raspiblitz/raspiblitz#3075]
Hi I am trying to deploy Raspiblitz 1.7.2 C-lightning using ssd with existing Blockchain data, data is cleansed but then while provisioning I get the following error:

SYSTEM RUN INTO AN ERROR:
btc-testrun-fail

From PUTTY:

###########################################################
# /home/admin/raspiblitz.log

***********************************************
Running RaspiBlitz Bootstrap 1.7.2
Sat 19 Feb 23:49:23 GMT 2022
***********************************************
# *** /home/admin/config.scripts/blitz.ssh.sh checkrepair
# countKeyFiles(8)
# OK: SSHD RUNNING
## INIT raspiblitz.info
baseimage=raspios_arm64
cpu=aarch64
displayClass=lcd
displayType=
setupPhase=boot
setupStep=0
fsexpanded=0
state=starting
btc_mainnet_sync_initial_done=0
btc_testnet_sync_initial_done=0
btc_signet_sync_initial_done=0
ln_lnd_mainnet_sync_initial_done=0
ln_lnd_testnet_sync_initial_done=0
ln_lnd_signet_sync_initial_done=0
ln_cl_mainnet_sync_initial_done=0
ln_cl_testnet_sync_initial_done=0
ln_cl_signet_sync_initial_done=0
## INIT RaspiBlitz Cache ... wait background.scan.service to finish first scan loop
- waiting for background.scan.service --> systemscan_runtime()
- waiting for background.scan.service --> systemscan_runtime()
- waiting for background.scan.service --> systemscan_runtime()
- waiting for background.scan.service --> systemscan_runtime()
- waiting for background.scan.service --> systemscan_runtime()
- waiting for background.scan.service --> systemscan_runtime(11)
OK - logs are at 33 MB - within safety limit
Waiting for HDD/SSD ...
total 636
drwxr-xr-x   4 root root   4096 Feb 19 23:48 .
drwxr-xr-x 123 root root  12288 Feb 19 23:49 ..
-rw-r--r--   1 root root 577771 Mar 13  2021 moduli
-rw-r--r--   1 root root   1650 Mar 13  2021 ssh_config
drwxr-xr-x   2 root root   4096 Mar 13  2021 ssh_config.d
-rw-r--r--   1 root root   3289 Mar 13  2021 sshd_config
drwxr-xr-x   2 root root   4096 Mar 13  2021 sshd_config.d
-rw-------   1 root root   1381 Feb 19 23:48 ssh_host_dsa_key
-rw-r--r--   1 root root    606 Feb 19 23:48 ssh_host_dsa_key.pub
-rw-------   1 root root    505 Feb 19 23:48 ssh_host_ecdsa_key
-rw-r--r--   1 root root    178 Feb 19 23:48 ssh_host_ecdsa_key.pub
-rw-------   1 root root    411 Feb 19 23:48 ssh_host_ed25519_key
-rw-r--r--   1 root root     98 Feb 19 23:48 ssh_host_ed25519_key.pub
-rw-------   1 root root   2602 Feb 19 23:48 ssh_host_rsa_key
-rw-r--r--   1 root root    570 Feb 19 23:48 ssh_host_rsa_key.pub
-rw-r--r--   1 root root    342 Feb 28  2020 ssh_import_id
HDD/SSD connected: sda
No HDMI switch found.
No FS EXPAND needed. needsExpansion(0) fsexpanded(0)
No WIFI RESTORE because no /var/cache/raspiblitz/hdd-inspect/wpa_supplicant.conf
SSH SERVER CERTS RESTORE activating old SSH host keys
# *** /home/admin/config.scripts/blitz.ssh.sh restore
# restore sshd host keys from: /var/cache/raspiblitz/hdd-inspect/sshd/ssh/sshd
# OK - sshd keys restore done
# INFO - ssh-root keys backup not available
No SSHRESET switch found.
check that display class in raspiblitz.conf from HDD is different from as it is now in raspiblitz.info ...
infoFileDisplayClass(lcd)
confFileDisplayClass(lcd)
No DISPLAY RESTORE because no need to change
No UASP FIX needed
isMounted: 0
HDD already part of system: 0
Temp mounting (1) data drive
Temp mounting (1) result: 1
HDD is there but not AutoMounted yet - Waiting for user Setup/Update
# df
Filesystem     1K-blocks      Used Available Use% Mounted on
/dev/root       61214608   5162260  53530016   9% /
devtmpfs          456788         0    456788   0% /dev
tmpfs             491412        16    491396   1% /dev/shm
tmpfs             196568       652    195916   1% /run
tmpfs               5120         0      5120   0% /run/lock
tmpfs              32768       616     32152   2% /var/cache/raspiblitz
/dev/mmcblk0p1    258095     30522    227573  12% /boot
tmpfs              98280        20     98260   1% /run/user/1000
/dev/sda1      960302096 451553260 459894412  50% /mnt/hdd
# lsblk -o NAME,FSTYPE,LABEL
NAME        FSTYPE LABEL
sda
└─sda1      ext4   BLOCKCHAIN
mmcblk0
├─mmcblk0p1 vfat   boot
└─mmcblk0p2 ext4   rootfs
# RASPIBLITZ DATA DRIVE Status

# BASICS
isMounted=1
isBTRFS=0
hddRaspiData=1
hddRaspiVersion='1.7.2'
isSSD=0
datadisk='sda'
datapartition='sda1'
hddCandidate='sda'
hddPartitionCandidate='sda1'
hddBlocksBitcoin=1
hddBytes=1000203091968
hddGigaBytes=931
hddUsedInfo='431G (50%)'
hddDataFreeBytes=470931877888
hddDataFreeKB=459894412
hddDataFreeGB=438
hddAdapterUSB=''
hddAdapterUSAP=0

# RAID
isRaid=0
raidCandidates=0

# SWAP
isSwapExternal=0

Displaying Info Message: Please Login for Recovery
## WAIT LOOP: USER SETUP/UPDATE/MIGRATION
# PROVISION PROCESS with setupPhase(setup)
Temp mounting (2) data drive (hddFormat='ext4')
Temp mounting (2) result: 1
Refreshing links between directories/drives ..

*** Enable Tor Service ***
*** Create directories and set permissions ***
mkdir: created directory '/mnt/hdd/app-data/tor'
mkdir: created directory '/mnt/hdd/app-data/tor/torrc.d'
mkdir: created directory '/mnt/hdd/tor'
mkdir: created directory '/mnt/hdd/tor/sys'
mkdir: created directory '/mnt/hdd/tor/sys/keys'
mkdir: created directory '/mnt/hdd/tor/services'
mkdir: created directory '/mnt/hdd/tor/onion_auth'
mode of '/mnt/hdd/tor' changed from 0755 (rwxr-xr-x) to 0700 (rwx------)
mode of '/mnt/hdd/app-data/tor' retained as 0755 (rwxr-xr-x)
mode of '/mnt/hdd/app-data/tor/torrc.d' retained as 0755 (rwxr-xr-x)
mode of '/etc/tor/torrc' retained as 0644 (rw-r--r--)
failed to change mode of '/mnt/hdd/app-data/tor/torrc.d/*' from 0644 (rw-r--r--) to 0644 (rw-r--r--)
changed ownership of '/mnt/hdd/tor/sys/keys' from root:root to debian-tor:debian-tor
changed ownership of '/mnt/hdd/tor/sys' from root:root to debian-tor:debian-tor
changed ownership of '/mnt/hdd/tor/services' from root:root to debian-tor:debian-tor
changed ownership of '/mnt/hdd/tor/onion_auth' from root:root to debian-tor:debian-tor
changed ownership of '/mnt/hdd/tor' from root:root to debian-tor:debian-tor
ownership of '/mnt/hdd/app-data/tor/torrc.d' retained as root:root
ownership of '/mnt/hdd/app-data/tor' retained as root:root
- /etc/tor/torrc will get edited

*** updating Tor config /etc/tor/torrc ***
## See https://github.com/torproject/tor/blob/main/src/config/torrc.sample.in

%include /mnt/hdd/app-data/tor/torrc.d

DataDirectory /mnt/hdd/tor/sys
PidFile /mnt/hdd/tor/sys/tor.pid

SafeLogging 0
Log notice stdout
Log notice file /mnt/hdd/tor/notice.log
Log info file /mnt/hdd/tor/info.log

RunAsDaemon 1
ControlPort 9051
SocksPort 9050 IsolateDestAddr
ExitRelay 0
CookieAuthentication 1
CookieAuthFileGroupReadable 1

- /mnt/hdd/app-data/tor/torrc.d/bridges already edited
# DO NOT EDIT! This file is generated by raspiblitz and will be overwritten
[Service]
ReadWriteDirectories=-/mnt/hdd/tor
[Unit]
After=network.target nss-lookup.target mnt-hdd.mount

# df
Filesystem     1K-blocks      Used Available Use% Mounted on
/dev/root       61214608   5068416  53623860   9% /
devtmpfs          456788         0    456788   0% /dev
tmpfs             491412        16    491396   1% /dev/shm
tmpfs             196568       680    195888   1% /run
tmpfs               5120         0      5120   0% /run/lock
tmpfs              32768       624     32144   2% /var/cache/raspiblitz
/dev/mmcblk0p1    258095     30522    227573  12% /boot
tmpfs              98280        20     98260   1% /run/user/1000
tmpfs              98280        20     98260   1% /run/user/1001
/dev/sda1      960302096 451538372 459909300  50% /mnt/hdd
# lsblk -o NAME,FSTYPE,LABEL
NAME        FSTYPE LABEL
sda
└─sda1      ext4   BLOCKCHAIN
mmcblk0
├─mmcblk0p1 vfat   boot
└─mmcblk0p2 ext4   rootfs
# Sourcing /var/cache/raspiblitz/temp/raspiblitz.setup
# migrationFile()
# Sourcing /mnt/hdd/raspiblitz.conf
# RASPIBLITZ CONFIG FILE
raspiBlitzVersion='1.7.2'
lcdrotate='1'
lightning='cl'
network='bitcoin'
chain='main'
hostname='removed'
runBehindTor='on'
# Sourcing /var/cache/raspiblitz/temp/raspiblitz.setup
# setting PASSWORD A

OK - password A changed for user pi, root, admin & bitcoin
...
Calling _provision.setup.sh for basic setup tasks ..
Follow in a new terminal with: 'tail -f raspiblitz.provision-setup.log'
***********************************************************
ERROR - please report to development team
***********************************************************
state(error) message(btc-testrun-fail)
https://github.com/rootzoll/raspiblitz#support
command to shutdown --> off
admin@192.168.1.100:~ ₿
admin@192.168.1.100:~ ₿ ^C
admin@192.168.1.100:~ ₿ tail -f raspiblitz.provision-setup.log
# (41/50) checking if bitcoind is running ...
# (42/50) checking if bitcoind is running ...
# (43/50) checking if bitcoind is running ...
# (44/50) checking if bitcoind is running ...
# (45/50) checking if bitcoind is running ...
# (46/50) checking if bitcoind is running ...
# (47/50) checking if bitcoind is running ...
# (48/50) checking if bitcoind is running ...
# (49/50) checking if bitcoind is running ...
# (50/50) checking if bitcoind is running ...

^C

**Comment by cstenglein** [comment]
@heyitsmeez is this still an issue with 1.9.0?

Closing this for now, please re-open if it still persists.
