### ISSUE TITLE
Suez - Missing click module

### ISSUE THREAD

**Issue by PegasusNZ** [raspiblitz/raspiblitz#3092]
The Suez module fails on 1.7.2 with missing click module, yet the module is installed

**Comment by openoms** [comment]
please try to run:

`config.scripts/bonus.suez.sh update`
to get the latest version and recheck the dependencies

**Comment by PegasusNZ** [comment]
That did not help unfortunately

**Comment by openoms** [comment]
```
config.scripts/bonus.suez.sh off
config.scripts/bonus.suez.sh on
```
should do it

**Comment by PegasusNZ** [comment]
I did turn it off and on no change seems to be a programming error in Poetry with lazy coding! I changed my locale to New Zealand en-NZ UTF8 so the time would be correct! So far postgres and poetry have not liked that! No problem 

Actually looking at the dependencies in the poetry project file, it requires python 3.6.2 and the RaspiBlitz has python 3.9.2 seems to be the problem

**Comment by openoms** [comment]
tagging to test Suez in v1.8.0rc-s which have Python > 3.9

**Comment by openoms** [comment]
Suez works ok on v1.8.0rc2 for both CLN and LND
