### ISSUE TITLE
Connecting the pi to wifi

### ISSUE THREAD

**Issue by pkclyoni** [raspiblitz/raspiblitz#310]
Is it possible to connect the pi to wifi instead of using a lan cable?

**Comment by Otti24xx** [comment]
Hi pkclyoini yes it is possible: 

Look https://github.com/Stadicus/guides/blob/master/raspibolt/raspibolt_20_pi.md 

"Prepare Wifi"

**Comment by rootzoll** [comment]
Added the question to the FAQ. Closing the issue.

**Comment by thelwyn** [comment]
And if you didn't prepare for wifi but would like to use it afterwards, you can run "sudo raspi-config" from the  terminal to open the default raspbian configuration menu > NETWORK > WIFI and enter SSIDD and password of the wlan you want to join.
