### ISSUE TITLE
Failure after installing Touchdisplay

### ISSUE THREAD

**Issue by TAP2BTC** [raspiblitz/raspiblitz#3103]
Hey guys, since two weeks i'm running my own node with a raspiblitz. A few days ago i was playing a Little Bit with it and installed the touchdisplay (didnt see the Info here in github) and now i don’t know what to do. I uninstalled the touchdisplay and rebooted my blitz for two times but i still see the Display like in the Photo (now without the touchbuttons/touchdisplay). 
![D52FF138-EE6F-4A21-988A-C4BB33F3DC11](https://user-images.githubusercontent.com/105286756/167619818-a145ba52-efd7-4d1f-a24f-779bb9eb50a2.jpeg)
![70E9706E-B54D-4C79-8798-39D2CFA361CA](https://user-images.githubusercontent.com/105286756/167619853-aa97cc8f-53a6-46df-bf86-6bbb4d361cca.png)
My infodisplay looks like the second Photo.
I‘ve my debug logs which you see bellow. 
I can only Go back to the Mainmenu with ./00mainMenu.sh. 
I’m new in this and an absolute beginner and i don’t know what to do with this. Can anyone Tell me what i have to do know? I can‘t find something like this anywhere. 

* RASPIBLITZ DEBUG LOGS 
***************************************************************
blitzversion: 1.7.2
chainnetwork: bitcoin / main
 22:39:57 up 18 min,  2 users,  load average: 2.18, 2.26, 1.69

*** SETUPPHASE / BOOTSTRAP ***
see logs: cat /home/admin/raspiblitz.log
setupPhase--> done
state--> ready

*** BACKGROUNDSERVICE ***
to monitor Background service call: sudo journalctl -f -u background

*** BLOCKCHAIN (MAINNET) SYSTEMD STATUS ***
● bitcoind.service - Bitcoin daemon
     Loaded: loaded (/etc/systemd/system/bitcoind.service; enabled; vendor preset: enabled)
     Active: activating (start) since Mon 2022-05-09 22:39:43 BST; 14s ago
    Process: 135019 ExecStartPre=/home/admin/config.scripts/blitz.systemd.sh log blockchain STARTED (code=exited, status=0/SUCCESS)
    Process: 135035 ExecStartPre=/bin/chgrp bitcoin /mnt/hdd/bitcoin (code=exited, status=0/SUCCESS)
Cntrl PID: 135036 (bitcoind)
      Tasks: 14 (limit: 4532)
        CPU: 14.021s
     CGroup: /system.slice/bitcoind.service
             ├─135036 /usr/local/bin/bitcoind -daemonwait -pid=/mnt/hdd/bitcoin/bitcoind.pid -conf=/mnt/hdd/bitcoin/bitcoin.conf -datadir=/mnt/hdd/bitcoin -debuglogfile=/mnt/hdd/bitcoin/debug.log
             └─135069 /usr/local/bin/bitcoind -daemonwait -pid=/mnt/hdd/bitcoin/bitcoind.pid -conf=/mnt/hdd/bitcoin/bitcoin.conf -datadir=/mnt/hdd/bitcoin -debuglogfile=/mnt/hdd/bitcoin/debug.log

May 09 22:39:43 raspberrypi systemd[1]: bitcoind.service: Consumed 16.374s CPU time.
May 09 22:39:43 raspberrypi systemd[1]: Starting Bitcoin daemon...

*** LAST BLOCKCHAIN (MAINNET) ERROR LOGS ***
sudo journalctl -u bitcoind -b --no-pager -n8
-- Journal begins at Fri 2022-05-06 19:54:30 BST, ends at Mon 2022-05-09 22:39:57 BST. --
May 09 22:39:41 raspberrypi systemd[1]: bitcoind.service: Control process exited, code=killed, status=11/SEGV
May 09 22:39:42 raspberrypi systemd[1]: bitcoind.service: Failed with result 'signal'.
May 09 22:39:42 raspberrypi systemd[1]: Failed to start Bitcoin daemon.
May 09 22:39:42 raspberrypi systemd[1]: bitcoind.service: Consumed 16.374s CPU time.
May 09 22:39:43 raspberrypi systemd[1]: bitcoind.service: Scheduled restart job, restart counter is at 59.
May 09 22:39:43 raspberrypi systemd[1]: Stopped Bitcoin daemon.
May 09 22:39:43 raspberrypi systemd[1]: bitcoind.service: Consumed 16.374s CPU time.
May 09 22:39:43 raspberrypi systemd[1]: Starting Bitcoin daemon...

*** LAST BLOCKCHAIN (MAINNET) 20 INFO LOGS ***
sudo tail -n 20 /mnt/hdd/bitcoin/debug.log
2022-05-09T21:39:43Z Using /16 prefix for IP bucketing
2022-05-09T21:39:43Z Cache configuration:
2022-05-09T21:39:43Z * Using 2.0 MiB for block index database
2022-05-09T21:39:43Z * Using 8.0 MiB for chain state database
2022-05-09T21:39:43Z * Using 502.0 MiB for in-memory UTXO set (plus up to 286.1 MiB of unused mempool space)
2022-05-09T21:39:43Z init message: Loading block index…
2022-05-09T21:39:43Z Switching active chainstate to Chainstate [ibd] @ height -1 (null)
2022-05-09T21:39:43Z Opening LevelDB in /mnt/hdd/bitcoin/blocks/index
2022-05-09T21:39:43Z Opened LevelDB successfully
2022-05-09T21:39:43Z Using obfuscation key for /mnt/hdd/bitcoin/blocks/index: 0000000000000000
2022-05-09T21:39:54Z LoadBlockIndexDB: last block file = 3030
2022-05-09T21:39:54Z LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=9, size=13925808, heights=735506...735514, time=2022-05-08...2022-05-08)
2022-05-09T21:39:54Z Checking all blk files are present...
2022-05-09T21:39:54Z Opening LevelDB in /mnt/hdd/bitcoin/chainstate
2022-05-09T21:39:54Z Opened LevelDB successfully
2022-05-09T21:39:54Z Using obfuscation key for /mnt/hdd/bitcoin/chainstate: 39341d2937aed7b8
2022-05-09T21:39:55Z Loaded best chain: hashBestChain=00000000000000000006918a850b1af41497024b7ed333c16ffda77db0b0d9a2 height=735514 date=2022-05-08T20:27:51Z progress=0.999700
2022-05-09T21:39:55Z init message: Verifying blocks…
2022-05-09T21:39:55Z Verifying last 6 blocks at level 3
2022-05-09T21:39:55Z [0%]...[16%]...[33%]...[50%]...
*** LND (MAINNET) SYSTEMD STATUS ***
● lnd.service - Lightning Network Daemon
     Loaded: loaded (/etc/systemd/system/lnd.service; enabled; vendor preset: enabled)
     Active: inactive (dead)

May 09 22:23:45 raspberrypi systemd[1]: Dependency failed for Lightning Network Daemon.
May 09 22:23:45 raspberrypi systemd[1]: lnd.service: Job lnd.service/start failed with result 'dependency'.

*** LAST LND (MAINNET) ERROR LOGS ***
sudo journalctl -u lnd -b --no-pager -n12
-- Journal begins at Fri 2022-05-06 19:54:30 BST, ends at Mon 2022-05-09 22:39:57 BST. --
May 09 22:23:45 raspberrypi systemd[1]: Dependency failed for Lightning Network Daemon.
May 09 22:23:45 raspberrypi systemd[1]: lnd.service: Job lnd.service/start failed with result 'dependency'.

*** LAST 30 LND (MAINNET) INFO LOGS ***
sudo tail -n 30 /mnt/hdd/lnd/logs/bitcoin/mainnet/lnd.log

*** C-LIGHTNING (MAINNET) SYSTEMD STATUS ***
- not activated -

*** BLOCKCHAIN (TESTNET) SYSTEMD STATUS ***
- OFF by config -
*** LND (TESTNET) SYSTEMD STATUS ***
- OFF by config -

*** C-LIGHTNING (TESTNET) SYSTEMD STATUS ***
- not activated -

*** BLOCKCHAIN (SIGNET) SYSTEMD STATUS ***
- OFF by config -
*** LND (SIGNET) SYSTEMD STATUS ***
- OFF by config -

*** C-LIGHTNING (SIGNET) SYSTEMD STATUS ***
- not activated -

*** NGINX SYSTEMD STATUS ***
● nginx.service - A high performance web server and a reverse proxy server
     Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/nginx.service.d
             └─raspiblitz.conf
     Active: active (running) since Mon 2022-05-09 22:22:23 BST; 17min ago
       Docs: man:nginx(8)
   Main PID: 1025 (nginx)
      Tasks: 5 (limit: 4532)
        CPU: 119ms
     CGroup: /system.slice/nginx.service
             ├─1025 nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
             ├─1028 nginx: worker process
             ├─1030 nginx: worker process
             ├─1031 nginx: worker process
             └─1032 nginx: worker process

May 09 22:22:20 raspberrypi systemd[1]: Starting A high performance web server and a reverse proxy server...
May 09 22:22:23 raspberrypi systemd[1]: Started A high performance web server and a reverse proxy server.

*** LAST NGINX LOGS ***
sudo journalctl -u nginx -b --no-pager -n20
-- Journal begins at Fri 2022-05-06 19:54:30 BST, ends at Mon 2022-05-09 22:39:57 BST. --
May 09 22:22:20 raspberrypi systemd[1]: Starting A high performance web server and a reverse proxy server...
May 09 22:22:23 raspberrypi systemd[1]: Started A high performance web server and a reverse proxy server.
--> CHECK CONFIG: sudo nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

- BLITZAPI is not running
- TOUCHSCREEN is OFF by config
- Loop is OFF by config
- LND-RTL is OFF by config
- CL-RTL is OFF by config
- Electrum Rust Server is OFF by config
- LIT is OFF by config
* BTCPayServer is OFF by config
* BTC-RPC-Explorer is OFF by config
- LNbits is OFF by config
- Thunderhub is OFF by config
- SPECTER is OFF by config
- SPHINX is OFF by config

*** MOUNTED DRIVES ***
Filesystem     Type      Size  Used Avail Use% Mounted on
/dev/root      ext4       29G  5.8G   22G  22% /
devtmpfs       devtmpfs  1.9G     0  1.9G   0% /dev
tmpfs          tmpfs     1.9G   16K  1.9G   1% /dev/shm
tmpfs          tmpfs     769M  760K  769M   1% /run
tmpfs          tmpfs     5.0M     0  5.0M   0% /run/lock
tmpfs          tmpfs      32M  8.0K   32M   1% /var/cache/raspiblitz
/dev/mmcblk0p1 vfat      253M   30M  223M  12% /boot
/dev/sda1      ext4      916G  438G  432G  51% /mnt/hdd
tmpfs          tmpfs     385M   16K  385M   1% /run/user/1000
tmpfs          tmpfs     385M   16K  385M   1% /run/user/1001

*** DATADRIVE ***
# RASPIBLITZ DATA DRIVE Status

# BASICS
isMounted=1
isBTRFS=0
hddRaspiData=1
hddRaspiVersion='1.7.2'
isSSD=1
datadisk='sda'
datapartition='sda1'
hddCandidate='sda'
hddPartitionCandidate='sda1'
hddBlocksBitcoin=1
hddBytes=1000203820544
hddGigaBytes=931
hddUsedInfo='438G (51%)'
hddDataFreeBytes=463178088448
hddDataFreeKB=452322352
hddDataFreeGB=431
hddAdapterUSB='174c:1153'
hddAdapterUSAP=1

# RAID
isRaid=0
raidCandidates=0

# SWAP
isSwapExternal=1
SwapExternalPath='/mnt/hdd/swapfile'

*** NETWORK ***
localip=*.*.*.*
localiprange=*.*.*.*/24
dhcp=1
network_device=eth0

*** HARDWARE TEST RESULTS ***
UndervoltageReports in Logs: 0

*** SYSTEM CACHE STATUS ***
system_init_time="1652131344"
system_cpu_load=" 1.93, 2.21, 1.68"
system_ram_available_mb="3352"
system_up="1084"
system_temp_celsius="74"
system_vm_vagrant="0"
system_count_start_blockchain="60"
system_count_longscan="0"
system_temp_fahrenheit="165"
system_ram_mb="3844"
system_count_undervoltage="0"
system_ram_gb="4"
system_board="rp4"
system_count_start_lightning="0"
system_ups_status="OFF"
system_count_start_tui="0"
ln_default_error_short=""
ln_default_online="0"
ln_default_version="0.14.2-beta"
ln_default_error_full=""
ln_default_running="0"
ln_default_locked="0"
ln_default_activated="1"
ln_default_ready="0"
ln_default_sync_initial_done="1"
btc_default_error_full=""
btc_default_error_short=""
btc_default_online="0"
btc_default_ready="0"
btc_default_running="0"
btc_default_sync_initial_done="1"
btc_default_activated="1"
btc_default_version="v22.0.0"
_____________________________________
Will be very thankful for some help and sure i‘m thankful for your work you do for all of us! 🙏🏼
Andy

**Comment by openoms** [comment]
Enter the menu and disable the Touchscreen in SETTINGS. It is not working well for now.

**Comment by TAP2BTC** [comment]
Yes i done that. But now my Display shows this in the picture after every reboot/Start of my Blitz. Also every time I exit Settings or other points in the main menu, I have to go over ./00mainMenu.sh. Otherwise i only see a black Display. 
![776D739F-AE92-4FE5-A236-2D430F52CC00](https://user-images.githubusercontent.com/105286756/167705566-8be25c22-f2af-476c-b7f4-44acabefa3af.jpeg)

**Comment by TAP2BTC** [comment]
I flashed the SD-Card & built a new one. Everything is Fine now. Merci
