### ISSUE TITLE
RTL create invoice the confirmation screen is blank

### ISSUE THREAD

**Issue by PegasusNZ** [raspiblitz/raspiblitz#3108]
When creating an invoice in RTL. The confirmation/advanced options screen is blank. Invoice date is 1970 and what I believe should be a QRcode displays N/A. The invoice is created in the invoice list

**Comment by rootzoll** [comment]
This sounds like a RTL bug (maybe missing an await or something) please report to the RTL repo first:
https://github.com/Ride-The-Lightning/RTL

Closing issue. Please reopen if you get feedback that something in the RaspiBlitz integration needs to be changed/optimized.
