### ISSUE TITLE
WebUI ElectrumServer as an App

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#3110]
Even if electrum server (electrs) has no WebUI itself - it makes to offer its install soon after the v1.8.0 release thru the WebUI in the App section - showing status and connection options. So that people can use it with their own electrum apps and hardware wallets.

**Comment by rootzoll** [comment]
Sadly needs to be pushed to v1.10 because of missing time.

**Comment by cstenglein** [comment]
Is there any info provided from raspiblitz / the api for electrs already?

Got the basic work for the ui part done, just needs some interaction ;)

**Comment by rootzoll** [comment]
I have started to prepare the electrs script for webinstall - Work in Progress

**Comment by rootzoll** [comment]
Syndata can be gathered from the following script:
`/home/admin/config.scripts/bonus.electrs.sh status-sync`

**Comment by rootzoll** [comment]
More Application Status of electrs could be called with: `/home/admin/config.scripts/bonus.electrs.sh status` but that should not be called in monitoring loop

**Comment by rootzoll** [comment]
Works on my test - closing issue for release.
