### ISSUE TITLE
RTL nginx config

### ISSUE THREAD

**Issue by PegasusNZ** [raspiblitz/raspiblitz#3117]
I am not sure if this is intentional or may cause errors but it seems the proxy redirects for RTL cause the server to complain and not start.
The problem is "listen localhost:300X" 
RTL still works on port 3000 but ssl and tor proxy redirects to RTL will fail

**Comment by rootzoll** [comment]
Rechecked for v1.8.0 release. RTL https id working on port 3001 and also the onion proxies on ports 3002 & 3003 look good. Closing issue for release.
