### ISSUE TITLE
raspiblitz lightning

### ISSUE THREAD

**Issue by domodomodomo3** [raspiblitz/raspiblitz#3118]
my raspiblitz node has a problem. the lightning progress is slowly going backwards and wont finish. i tried a restart. i tried updating to the newest version (1.7.2), tried new sd. nothing helped. This is not my first setup. my node was running perfectly for three years now. the longest i waited for lightning to finish is three weeks now. what can i do? how to fix it?
here is my log: https://l.termbin.com/g9n0

can someone help?

**Comment by md-weber** [comment]
Could be a duplicate https://github.com/rootzoll/raspiblitz/issues/3058

**Comment by openoms** [comment]
thanks, same link, closing as duplicate.
