### ISSUE TITLE
multiple unlock lnd wallet requests

### ISSUE THREAD

**Issue by thephizzz** [raspiblitz/raspiblitz#3119]
My raspiblitz is, and has been up and running fine for many months. Just recently, every two hours or so, it asks me to unlock the lnd wallet, again. The btc node continues to run fine. I log in and re-enter the lnd wallet password and everything runs fine.
But then it repeats this in a few hours.

**Comment by thephizzz** [comment]
Forgot to include:
Raspiblitz v1.7.1
LND 0.13.3-beta
Bitcoin v22.0.0

**Comment by rootzoll** [comment]
This us hard to debug without logs ... best would be best to post a debug report:
https://github.com/rootzoll/raspiblitz/blob/v1.7/FAQ.md#how-do-i-generate-a-debug-report

Or wait some more weeks to change to v1.8.0 and see if this fixes it. If that takes to long often also a new sd card image of the v1.7.2 fixes broken system states.

**Comment by cstenglein** [comment]
@thephizzz is this still occurring?
Closing this issue for now, if it still persists with 1.9.0, please re-open

**Comment by thephizzz** [comment]
It stopped with v1.8, but has started again with v1.9.
I entered my new issue and logs in #3879, so this can be closed. Thanks.
