### ISSUE TITLE
Booting issue

### ISSUE THREAD

**Issue by TimmyP13** [raspiblitz/raspiblitz#3122]
Had a power outage and trying to boot back up my system. Seems to hang on this screen. Do I just need to wait longer or do I have an issue?
![IMG_1082](https://user-images.githubusercontent.com/105677336/168679405-72403d07-d5bb-478c-b65b-8a40c3d9aa1f.jpg)
 Thanks!

**Comment by rootzoll** [comment]
A power outage has always the danger of data corruption & loss. If you are lucky just your sd card with the OS eneded up ins some inconsistent sate. So first try should be to flash a new sd card with the latest RaspiBlitz image and see if you can get thru the recovery process. https://github.com/rootzoll/raspiblitz#downloading-the-software

**Comment by TimmyP13** [comment]
Ok I will try it. Thanks for the response!

**Comment by openoms** [comment]
please close if resolved or abandoned
