### ISSUE TITLE
cln-grpc value error in raspiblitz.conf

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#3126]
![signal-2022-05-18-133903_001](https://user-images.githubusercontent.com/2472225/169030779-aa5f7df2-2dd8-4b07-a9c6-14fbfe18c899.jpeg)

**Comment by rootzoll** [comment]
The error dissapers when the variable in the craspiblitz config gets renamed form `cln-grpc` to `clngrpc`.

@openoms I will make a quick commit by changing the variable name all over the code base.

**Comment by rootzoll** [comment]
@openoms while looking thru the code I see a
`/home/admin/config.scripts/blitz.conf.sh set ${netprefix}clngrpc "off"`
but never a place where its set to `on` is that correct?

**Comment by rootzoll** [comment]
@openoms I also hamonized the naming of the tor service to `${netprefix}clnGRPCport` ... putting it all to this PR  #3128 for you to review befre merge - see if I broke anything.

**Comment by openoms** [comment]
> @openoms while looking thru the code I see a `/home/admin/config.scripts/blitz.conf.sh set ${netprefix}clngrpc "off"` but never a place where its set to `on` is that correct?

yes, sorry I have realised the problem with dashes and changed in a rush incompletely.
This is the value which is not on, but set to the actual port number or off.
Fixed #3128 ,can be merged now to have this sorted.

**Comment by rootzoll** [comment]
Looks good now - closing issue.
