### ISSUE TITLE
Bitcoin Node Startup Issue

### ISSUE THREAD

**Issue by mroxso** [raspiblitz/raspiblitz#3133]
I restarted my raspiblitz (v1.7.2).

Now the bitcoin log shows the following:
`2022-05-19T07:40:25Z connect() to 127.0.0.1:9050 failed after wait: Connection refused (111)`

The bitcoin node is not booting up because of this.

**Comment by openoms** [comment]
it is a Tor error. Monitor with:
`sudo journalctl -fu tor@default`

try:
`sudo systemctl restart tor`

or another full reboot.

**Comment by mroxso** [comment]
mmh true. seems like my tor service is not working. but a restart isn't fixing it for me.

-- Journal begins at Sun 2022-05-22 18:17:54 BST. --
May 23 16:56:53 raspiblitz tor[1992128]: May 23 16:56:53.030 [warn] Failed to parse/validate config: Failed to configure rendezvous options. See logs for details.
May 23 16:56:53 raspiblitz tor[1992128]: May 23 16:56:53.030 [err] Reading config failed--see warnings above.
May 23 16:56:53 raspiblitz systemd[1]: tor@default.service: Control process exited, code=exited, status=1/FAILURE
May 23 16:56:53 raspiblitz systemd[1]: tor@default.service: Failed with result 'exit-code'.
May 23 16:56:53 raspiblitz systemd[1]: Failed to start Anonymizing overlay network for TCP.
May 23 16:56:53 raspiblitz systemd[1]: tor@default.service: Scheduled restart job, restart counter is at 5.
May 23 16:56:53 raspiblitz systemd[1]: Stopped Anonymizing overlay network for TCP.
May 23 16:56:53 raspiblitz systemd[1]: tor@default.service: Start request repeated too quickly.
May 23 16:56:53 raspiblitz systemd[1]: tor@default.service: Failed with result 'exit-code'.
May 23 16:56:53 raspiblitz systemd[1]: Failed to start Anonymizing overlay network for TCP.

**Comment by mroxso** [comment]
I fixed it with the following commands:
`sudo chmod 700 -R /mnt/hdd/tor/`
`sudo systemctl restart tor`

so i changed the permissions to be a bit more private.
i dont know why they were to peremissive.

now it seems to work fine again.
