### ISSUE TITLE
API+WebUI: After recovery WebUI does not load values

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#3135]
On the RC1 I can go thru the complete recovery/update process with the WebUI, but once its rebooted and the Dashboard loads after wallet unlock  I only see spinning circles that never go away:

![Bildschirmfoto 2022-05-19 um 11 51 22](https://user-images.githubusercontent.com/2472225/169266041-eadfe707-725c-4fc8-a44a-0b67acdb6f7c.png)

@fusion44 this is something to look into together in Oslo.

**Comment by openoms** [comment]
can confirm this on latest and same in the App screen. Nothing obvious in the blitzapi logs.

I went with New node - Keep Blockchain not the recovery route.

Same also after a restart.

Also a couple of times reproduced now that the restart is just a shutdown, the blitz does not come back on after the final reboot after recovery.

**Comment by rootzoll** [comment]
@fusion44 & @cstenglein ... as far as I can see on loading the dashboard checking the network I see just pings coming back as events and `locked: true` even tho the lnd is not locked (when checking thru SSH) and also the WebUI not asking to unlock ... could that be the issue?

![Bildschirmfoto 2022-05-30 um 22 59 43](https://user-images.githubusercontent.com/2472225/171059336-f0af3df9-e2e7-4fad-8442-1a2fb547ac3e.png)

**Comment by rootzoll** [comment]
This also happens on restarts of the blitz. Then wallet is locked - WebUI askes to unlock, unlock request returns true - but no events happen after that on the subscribe SSE channel.

@fusion44 it seems this is related to the time the API is started - if I restart the systemd API service manually the next login/gettingevents to the WebUI is working.

**Comment by rootzoll** [comment]
Try to fix the bug on API side: https://github.com/fusion44/blitz_api/issues/97

**Comment by rootzoll** [comment]
@fusion44 I tried the blitz api with the refactored startup merged on a fresh raspiblitz setup/recovery - systemd tells me the API is running (see picture) - but calling `/api/v1/docs` returns a 502 Bad Gateway - so I am not able to start the setup/recovery thru the webUI

![Bildschirmfoto 2022-06-13 um 23 19 25](https://user-images.githubusercontent.com/2472225/173448174-bd86c34d-3804-40ad-9a3e-a9bd84e339e2.png)

When I sync the API from my local code I see in the logs:

```
Jun 13 22:24:23 python[128190]: ERROR:root:unknown lightning node: none
Jun 13 22:24:24 python[128190]: INFO:     Started server process [128190]
Jun 13 22:24:24 python[128190]: INFO:uvicorn.error:Started server process [128190]
Jun 13 22:24:24 python[128190]: INFO:     Waiting for application startup.
Jun 13 22:24:24 python[128190]: INFO:uvicorn.error:Waiting for application startup.
```

So it looks like the API gets stuck in a loop ... and never finishes "Startup"

**Comment by rootzoll** [comment]
OK if https://github.com/fusion44/blitz_api/pull/113 gets merged we should be OK. Tests look good.

**Comment by rootzoll** [comment]
Hmm Test with fresh setup of core lightning has still a problem:

![Bildschirmfoto 2022-06-14 um 15 42 22](https://user-images.githubusercontent.com/2472225/173594057-f841aec3-02f3-4731-99ee-4a3bcff23bc4.png)

So there is the message `{"bitcoin": "done", "bitcoin_msg": "", "lightning": "offline", "lightning_msg": "Unable to connect to CLN daemon, waiting..."}` but even cln is ready on the SSH side - the API is not signaling a ready state so UI keeps on waiting forever.

- calling `lightning-cli getinfo` on SSH works
- A reload of the webUI does not change anything.
- A start/stop of the blitzapi service does not change anything.

**Comment by rootzoll** [comment]
Same is also happening with a fresh just Bitcoin setup. This is the message on system_startup_info `{"bitcoin": "done", "bitcoin_msg": "", "lightning": "disabled", "lightning_msg": ""}`

**Comment by rootzoll** [comment]
OK fixed & tested everything so far - there is still an issue core lightnig when wallet lock is activated #3167 - but because that is not a default, its not a showblocker anymore.

**Comment by rootzoll** [comment]
So there is a show stopper with the API: https://github.com/fusion44/blitz_api/issues/120

**Comment by rootzoll** [comment]
OK got it fixed in the raspiblitz repo - will make a RC2 update soon for testing.

**Comment by rootzoll** [comment]
This one looks good now - closing for v1.8.0 release.
