### ISSUE TITLE
PUTTY Zeichensatz

### ISSUE THREAD

**Issue by Otti24xx** [raspiblitz/raspiblitz#314]
Habe SD Karte mit Version 1.0 erstellt - läuft alles super. Frage zum Zeichensatz, bei mir zeigt es Buchstaben am Rand statt einer Linie an:

                 lqqqqqqqqqqqq bitcoin / main qqqqqqqqqqqqqqk
                 x  Lightning Catching-Up Blockchain        x
                 x  Progress: 100000/562855                 x
                 x  re-rescan every start until funding     x

**Comment by rootzoll** [comment]
hmm ... bei meinem Testbuild scheint es soweit gut ... doch jeder build ist anders. Ganz am Anfang beim build script werden die Zeichensätze installiert ... ggf. gabs da nen Aussetzer.

**Comment by Otti24xx** [comment]
Hallo Christian, das Einrichten lief ohne Stocken durch, ja am Anfang erinnere ich mich an drei Zeichensatzdateien, ich glaube US und DE... kommt das evtl. vom Putty, kann man da auch noch was einstellen? Aber Super Arbeit! Danke! läuft alles klasse

**Comment by rootzoll** [comment]
Danke :) Mit Putty hab ich keine aktuellen Erfahrungen - falls jemand nen Tip hat, welchen Zeichensatz man einbinden muss, damit es mit Putty out-of-the-box korrekt aussieht bitte gerne. 

Damit ist der issue für 1.0 release nicht kritisch. Ich lass ihn mal als enhancement offen.

**Comment by frennkie** [comment]
The - non default (?!) - settings I am using on Putty are:

* Terminal -> Keyboard -> Function keys and keypad: Xterm R6
* Windows -> Translation -> Remote Char Set: UTF-8

@Otti24xx Please test and let us know whether this works for you.

**Comment by frennkie** [comment]
Hm.. I guess this is also needed: 

```
Windows -> Translation -> [X] Enable VT 100 line drawing even in UTF-8 mode
```

**Comment by M73** [comment]
These 3 worked for me:

> The - non default (?!) - settings I am using on Putty are:
> 
> ```
> Terminal -> Keyboard -> Function keys and keypad: Xterm R6
> ```
> ```
> Windows -> Translation -> Remote Char Set: UTF-8
> ```
> 
> Hm.. I guess this is also needed:
> ```
> Windows -> Translation -> [X] Enable VT 100 line drawing even in UTF-8 mode
> ```

Thanks @frennkie
