### ISSUE TITLE
Bonjour services

### ISSUE THREAD

**Issue by PegasusNZ** [raspiblitz/raspiblitz#3144]
UFW blocks bonjour services , you may like to accept data on 224.0.0.251?

**Comment by rootzoll** [comment]
What would be the benefit to open the bonjour services?

**Comment by PegasusNZ** [comment]
> What would be the benefit to open the bonjour services?

The benefit is a empty log! I have been having trouble with RTL and LIT and my iPad fills the log with bonjour requests!

**Comment by PegasusNZ** [comment]
I am not familiar with UFW but I have bypassed UFW on port 3000 for RTL and RTL no longer hangs like it was doing! Even though port 3000 was open in UFW according to the logs it was still blocking and the hanging seemed to relate to log updates?
