### ISSUE TITLE
Can't get to the menu from status screen

### ISSUE THREAD

**Issue by Nerfzooka** [raspiblitz/raspiblitz#3158]
My headless raspiblitz is running well, maybe too well, it won't exit from the status screen when I ssh in.  The FAQ says "SSH into your RaspiBlitz and EXIT to terminal from the menu."  I tried EXIT, exit, x, control x, control d, escape, control q, \q, quit and whatever else I could think of, but only control c ended the status screen by cutting off the ssh connection.  How do you get to the menu while sshing?
![statusScreen](https://user-images.githubusercontent.com/23216537/172022514-7a17b3e0-ba32-486c-9282-34a4d0285d62.png)

**Comment by openoms** [comment]
Use the `admin` user to log in, not `pi`

**Comment by Nerfzooka** [comment]
oooooh, of course.   Thanks openoms
![superAdmin](https://user-images.githubusercontent.com/23216537/172026570-b7b2d8e8-d5c8-4e57-b6e8-0445161d4b21.png)
!
