### ISSUE TITLE
Check Umbrel migration for new 0.5.0 version

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#3159]
https://blog.getumbrel.com/introducing-umbrel-0-5-a-beautiful-personal-server-os-for-self-hosting-dcbee7e23b64

Also now that they have also core lightning - this needs to be part of the migration process, too.

**Comment by openoms** [comment]
This helps moving to a docker based setup, but just for FYI: https://github.com/dsbaars/unbrel

**Comment by rootzoll** [comment]
unbrel is a nice hack of Umbrel ;) ... but the topic of this issue is more to adapt to their changes in HDD layout in 0.5.0 (they moved lots of files around - but I already have that adapted) and to support also migratiing the new Core Lightning data to raspiblitz. See progress in branch: https://github.com/rootzoll/raspiblitz/tree/3159umbrel

**Comment by rootzoll** [comment]
OK implemented - also the core lightning migration from raspiblitz 0.5.0 to raspiblitz 1.8.0
final testing during RC2

**Comment by rootzoll** [comment]
No bad reports during rc phase - closing issue for v1.8.0 release.
