### ISSUE TITLE
protobuf 3.20.1 update

### ISSUE THREAD

**Issue by mark0st83** [raspiblitz/raspiblitz#3162]
Seems like a problem with pip.

Same with bench dev (v1.8R1) and v1.7

After a `build_sdcard.sh` with a fresh Debian11 the setup stucks in „LND Credentials“ and after the 2 min the setup stopped:

```
Calling _provision.setup.sh for basic setup tasks ..
Follow in a new terminal with: 'tail -f raspiblitz.provision-setup.log'
***********************************************************
ERROR - please report to development team
***********************************************************
state(error) message(lnd-no-macaroons)
https://github.com/rootzoll/raspiblitz#support
command to shutdown --> off
```

Try to make new macaroons over the menu failed. (Found no files)
`lnd.initwallet.py`:
```
admin@10.0.0.113:~ ₿ sudo /home/admin/config.scripts/lnd.initwallet.py new mainnet password
Traceback (most recent call last):
  File "/home/admin/config.scripts/lnd.initwallet.py", line 31, in <module>
    from lndlibs import walletunlocker_pb2 as lnrpc
  File "/home/admin/config.scripts/lndlibs/walletunlocker_pb2.py", line 14, in <module>
    from . import lightning_pb2 as lightning__pb2
  File "/home/admin/config.scripts/lndlibs/lightning_pb2.py", line 33, in <module>
    _descriptor.EnumValueDescriptor(
  File "/usr/local/lib/python3.9/dist-packages/google/protobuf/descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

I found a possible solution on GitHub [here](https://github.com/protocolbuffers/protobuf/issues/10051) and [here](https://github.com/deepmind/alphafold/issues/478)

I added `pip3 install --upgrade protobuf==3.20.0` in the build_sdcard.sh on line 307

`python_libs="grpcio==1.42.0 googleapis-common-protos==1.53.0 toml==0.10.2 j2cli==0.3.10 requests[socks]==2.21.0 protobuf==3.20.0"`

The build with Python 3.9.2 and bench v1.7 seems to work. The 1.8r1 seems to work with a empty SSD, but it looks like it stucks with delete data and use blockchain.
But maybe this is just a other problem.

To switch on Python 3.10.1 like in the guide seems to work aswell.

———————————————————-
Update:

After further tests:

All tested builds works with the change in build_sdcard.sh

The problem with the stuck SSD delete is because a dead swap-delete process.

in v1.7 the delete can stopped with ctrg-c, after that the process continues.  In 1.8r1 the setup is completely inscreen and didn’t changed to shell

If I delete it manually and then start the setup everything is fine.

Is this because the swapfile belongs to another pc? (Because the VM snapshots/backups and restore)

**Comment by rootzoll** [comment]
@openoms are there some protobuffs we need to update for v1.8.0?

**Comment by openoms** [comment]
It seems to need protobuff > 3.19.0.
I have 3.19.1 on my amd64 server based on Debian 11 and on my test RPi. That should work.

what was your original protobuff version @mark0st83?

**Comment by mark0st83** [comment]
I had to reinstall the „missbuild“ VM to look, but it was a fresh upgraded 11.2. So i think it was Version 3.12.4 https://packages.debian.org/source/bullseye/protobuf

**Comment by openoms** [comment]
Thank you for the report, it is indeed a pip mess. 
Running:
```
sudo python3 -m pip install grpcio-tools
```

Installed protobuff protobuf-3.20.1:
```
Collecting protobuf<4.0dev,>=3.12.0
  Downloading protobuf-3.20.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 5.4 MB/s eta 0:00:00
 ```
 
 But if protobuff 3.12 is already present it does not upgrade as it meets the requirement.

Let's add the upgrade to the dependencies in build_sdcard.sh so all have the right versions.

**Comment by openoms** [comment]
So protobuff 3.19.1 seems to work ok, but the latest is protobuf-3.20.1.
Shall we pin the latest?

**Comment by rootzoll** [comment]
> Shall we pin the latest?

I think yes - so we can test it with the RC2.

@openoms Let me know when this is done, then I would start to prepare/test image for 1.8.0rc2 release.

**Comment by mark0st83** [comment]
I will Setup a 1.8r1 with the latest later.

**Comment by openoms** [comment]
The change did not break anything on live systems:
```
python_libs="grpcio==1.42.0 googleapis-common-protos==1.53.0 toml==0.10.2 j2cli==0.3.10 requests[socks]==2.21.0 protobuf==3.20.1"
sudo -H python3 -m pip install --upgrade pip
sudo -H python3 -m pip install ${python_libs}
```

**Comment by mark0st83** [comment]
I just saw that I’ve already tested a bunch of settings.

I’ve  already tested:

V1.8r1
Python 3.9.2
Protobuf 0.20.1

V1.8r1
Python 3.9.2
Protobuf 0.20.1

now live:
V1.7
Python 3.9.2
Protobuf 0.20.0

And several settings with Python 3.10.1, but that makes no different to me.

so I’m thinking 0.20.1 would be fine for the Realeasecandidate.

**Comment by rootzoll** [comment]
OK tested fine so far - closing for v1.8.0 release.
