### ISSUE TITLE
Unable to reactivate LND Static Channel Backup on Nextcloud

### ISSUE THREAD

**Issue by benniblitz** [raspiblitz/raspiblitz#3163]
RaspiBlitz v1.7.2   LND 0.14.2-beta

I've been having a few issues reactivating LND static channel back up on Nextcloud after the latest update.

It used to work well for a few months, then it stopped working.

I used the free nextcloud service provided at https://free.files.cnow.at/

I tired to get it working again by firstly de-activating through the SSH menu, and then activating the LND Static Channel Backup.

After activating, I am then prompted to enter the server URL, then user name, then password.

It accepts and then runs and flashes briefly on the screen the following:
...
Nextcloud Setting changed ..
rm: cannot remove '/var/cache/raspiblitz/.tmp' : Operation not permitted
sed: -e expression #1, char 59: unknown option to ‘s’
err=’Nextcloud credentials are missing’
...

No files are written to the server and the LND Static Channel Backup on Nextcloud option does not have a * in the menu

I then also restarted the node and tried again to no avail.

I have also tried two other nextcloud servers 

https://use05.thegood.cloud/
https://nextcloud05.webo.cloud/

But again to no avail.

![Picture1](https://user-images.githubusercontent.com/101555945/173179770-d9960d64-15d3-4d83-9841-d5f57cfdc458.png)

**Comment by rootzoll** [comment]
Maybe related and fixed in issue #3116 which will be part of upcoming v1.8.0 release. Please test if an update to v1.8.0 is the fixes this once its available and report back.

**Comment by cstenglein** [comment]
@benniblitz  is this still relevant in 1.9.0? Closing for now, if it's still relevant, please re-open
