### ISSUE TITLE
Derive BTC-address vom seed ?

### ISSUE THREAD

**Issue by stn021** [raspiblitz/raspiblitz#3168]
Hello,
after a few failed attempts my node now works. The failed attempts led to a number of diffferent seed-phrases.

So now I would like to check the seeds for onchain balances. 

The seeds are aezeed, obviously. How can I derive the BTC-addresses from the seed? There must be a way, raspiblitz also does that.

**Comment by openoms** [comment]
yes, via lnd. recover the wallet from seed from the REPAIR-LND menu.
