### ISSUE TITLE
LND - check if seedwords belong to a node

### ISSUE THREAD

**Issue by stn021** [raspiblitz/raspiblitz#3169]
Hello,

apparently there is no way to display the LND-seed on raspiblitz.

Due to a number of failed attempts at starting a node I now have several seeds.
Is there a way to test which one of those belongs to the node currently running?

Also I would like to suggest that the LND-seedwords get stored in a file, just like the seed for C-Lightning.
The cleartext of the words could be securely deleted on certain conditions, just like C-Lightning.
The user might even be offered the option to delete them intentionally, for example in the raspiblitz-menu.

**Comment by openoms** [comment]
for how to check the nodeid derived from the seed see the answer here: https://github.com/rootzoll/raspiblitz/issues/2911#issue-1113764349

The lnd wallet is encrypted by default (unlike CLN - which is not) so would not want to reduce the security by saving the cleartext seed.
You an backup the wallet.db file itself (as a file) as well if you don't have / know the seed.
