### ISSUE TITLE
Unable to backup channels for C-Lightning

### ISSUE THREAD

**Issue by stn021** [raspiblitz/raspiblitz#3174]
Hello,

for C-Lightning there are several options for backing up the channels.
None of these work on raspiblitz.

The entry "wallet=..." in the config-file fails with "cannot open database", maybe due to user-privileges of users bitcoin and admin.

The backup-plugin does not work either, neither on raspiblitz nor on the original Core-Lightning. In https://github.com/rootzoll/raspiblitz/issues/2983 I found how to change raspiblitz/home.admin/config.scripts/cl-plugin.backup.sh. But afterwards the initialization 'config.scripts/cl-plugin.backup.sh on' failed because of No such file or directory: '/home/bitcoin/cl-plugins-available/plugins/backup/requirements.txt'

I have been at this for a while and could not find how to backup the CLI-channels on raspiblitz.
Please let me know how I can do that.

THX, regards, stn

**Comment by openoms** [comment]
The backup plugin does mirror the CLN channel database to the SDcard by default in `/home/bitcoin`. If your changes are not working now try running:
`patch` 
(same as UPDATE - PATCH)
or flash a new SDcard.

**Comment by stn021** [comment]
If I understand correctly
- The CLN channel database is /mnt/hdd/app-data/.lightning/bitcoin/lightningd.sqlite3
- The backup-plugin should either create files with time+date and maybe the word "backup" in the filename or there should be a second lightningd.sqlite3 somewhere that is the mirror of the working database

Not sure which one is correct. I could not find the correct folder on the SDcard.
Could you please name the exact location of the backup-folder for CLN?

**Comment by openoms** [comment]
As above, see:

`sudo ls -la /home/bitcoin/`

**Comment by stn021** [comment]
I did that. The folder /home/bitcoin contains 7 files and 17 folders.
The files and folders are the usual stuff in any home-directrory, like .local/, .cache/, .config/, .bashrc and similar plus a few raspiblitz-specific ones.
None of those are obvious backups.

Which one of the files is the backup of the CLN channel database ?

Unless something is wrong with the backup, in that case of course there would not be any file and I would not know, which specific file to look for.

**Comment by openoms** [comment]
Here it is:
```
₿ sudo ls -la /home/bitcoin/lightningd.sqlite3.backup
-rw-r--r-- 1 bitcoin bitcoin 208668154 Jun 21 22:16 /home/bitcoin/lightningd.sqlite3.backup
```

It is recreated (and the old one renamed with a date and saved) when you run 
```
config.scripts/cl-plugin.backup.sh on
```

Can try running the commands:
```
config.scripts/cl-plugin.backup.sh off
config.scripts/cl-plugin.backup.sh on
```

or reflash the SDcard if it does not work for you.

**Comment by stn021** [comment]
OK, now we are getting closer :-)

Just to be sure I re-checked my version of raspiblitz. I have raspiblitz-v1.7.2-2022-02-20.img.gz. That is the newest one available for download.
The SD-cards are fresh, see below.


At the moment I actually have 3 nodes with CLN.

The file /home/bitcoin/lightningd.sqlite3.backup does not exist on any one of them.
So I tried to recreate and did 'config.scripts/cl-plugin.backup.sh on' as you said.


The result on all three nodes is the same:

```
admin@192.168.0.75:~ ₿ config.scripts/cl-plugin.backup.sh on
# Checking dependencies
ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/home/bitcoin/cl-plugins-available/plugins/backup/requirements.txt'
# Stop the lightningd.service
ls: cannot access '/home/bitcoin/.lightning/bitcoin/backup.lock': No such file or directory
# Initialize the backup plugin
Traceback (most recent call last):
  File "/home/bitcoin/cl-plugins-available/plugins/backup/backup-cli", line 2, in <module>
    from backends import get_backend
  File "/home/bitcoin/cl-plugins-available/plugins/backup/backends.py", line 5, in <module>
    from backend import Backend
  File "/home/bitcoin/cl-plugins-available/plugins/backup/backend.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
# The crontab for admin now is:
@weekly /home/admin/config.scripts/cl-plugin.backup.sh backup-compact mainnet

# Started the lightningd.service
```


Please note in line 3 the missing file /home/bitcoin/cl-plugins-available/plugins/backup/requirements.txt'. That same file is also missing in the original of the backup-plugin in the core-lightning repository.

For some reason at the moment the backup-plugin does not work, neither in raspiblitz nor core-lightning.
I assume that your installation is a bit older and apparently the plugin worked at that time.

**Comment by openoms** [comment]
I have old and fresh installs.
Try running:
`patch`
for the latest fixes and try to delete the plugins dir to have it redownloaded:
`sudo rm -rf /home/bitcoin/cl-plugins-available/plugins`

then again:
`config.scripts/cl-plugin.backup.sh on`

**Comment by stn021** [comment]
The last several times I ran 'patch' it refused to run and demanded that I commit first.

This time it actually worked.
And finally the backup-file is there too.

Thank you.

**Comment by openoms** [comment]
also al

**Comment by 0xtrr** [comment]
> The last several times I ran 'patch' it refused to run and demanded that I commit first.

How did you fix this issue @stn021? I'm having the exact same problem with the plugin but when I try to run patch it just errors on unstaged changes
```
admin@192.168.1.49:~ ₿ patch
# your active GitHubUser is: rootzoll
# your wanted GitHubUser is: rootzoll
# OK
# your active branch is: v1.7
# your wanted branch is: v1.7
# OK
# *** SYNCING RASPIBLITZ CODE WITH GITHUB ***
# This is for developing on your RaspiBlitz.
# THIS IS NOT THE REGULAR UPDATE MECHANISM
# and can lead to dirty state of your scripts.
# REPO ----> origin	https://github.com/rootzoll/raspiblitz.git (push)
# BRANCH --> v1.7
# ******************************************
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.
# COPYING from GIT-Directory to /home/admin/
# - basic admin files
# - asset directory
# - config.scripts directory
# - setup.scripts directory
# ******************************************
# Syncing Webcontent ..
# Checking if the content of BlitzPy changed ..
# checkSumBlitzPyBefore = 2e35e76c81cad5e7c909542d94940c95  -
# checkSumBlitzPyAfter  = 2e35e76c81cad5e7c909542d94940c95  -
# BlitzPy did not changed.
# ******************************************
# OK - shell scripts and assets are synced
# Reboot recommended

```

**Comment by openoms** [comment]
to solve this reset you source code directory:
```
cd
rm -rf ./raspiblitz
git clone https://github.com/rootzoll/raspiblitz
patch
```
