### ISSUE TITLE
Copy Blockchain over LAN sometimes works and sometimes does not

### ISSUE THREAD

**Issue by stn021** [raspiblitz/raspiblitz#3176]
Hello,

this is weird. I flash a new card, clear all partitions from the SSD and boot.
As expected the setup starts.
I set up an existing seed but otherwise everything is new, mode "SEEDONLY".

Everything seems to work normally, except for the last step before reboot. There sometimes I can choose "SELFSYNC" vs "COPY" and sometimes this is simply skipped and after reboot a selfsync starts.

In that case usually I flash the SD again, and again clear all partitions from the SSD and start over. Usually after 2-3 attempts the menu "Selfsync" vs "COPY" ist finally shown.

I have done this a number of times and I absolutely have no idea why the last item sometimes appears and sometimes not. I am sure that I enter the same things every time.

So, my question would be either:

Is there any possible reason why that happens, can I do something to avoid this?
OR
Is there a way to force a copy over LAN after the first reboot?

THX, regards, stn

**Comment by rootzoll** [comment]
The upcomming v1.8.0 will have an improved detection when to offer COPY - if you like you can alrready test this with 1.8.0RC2 (not for production nodes): https://raspiblitz.fulmo.org/images/raspiblitz-v1.8.0rc2-2022-06-20.img.gz

**Comment by stn021** [comment]
THX
