### ISSUE TITLE
LND v0.15.0 update 

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#3181]
v0.15.0-beta.rc6 was tagged 9 days ago. 
https://github.com/lightningnetwork/lnd/releases/

Tested and running ok on both aarch64 and amd64 so far.

**Comment by openoms** [comment]
The stable is out: https://github.com/lightningnetwork/lnd/releases/tag/v0.15.0-beta

**Comment by ktecho** [comment]
@openoms Have you tested if an upgrade in Raspiblitz 1.7.2 to this v0.15.0 is succesful?

**Comment by openoms** [comment]
yes, as above was running the rc6 for a while

**Comment by openoms** [comment]
@rootzoll just realized that when updating LND from the menu a full reboot is called. Is there any particular reason why this is necessary?

Running:
```
/home/admin/config.scripts/lnd.update.sh reckless
sudo systemctl start lnd
lncli unlock
```
is sufficient.

**Comment by drmartinberger** [comment]
After updating Raspiblitz 1.7.2 to LND v0.15.0 the Raspiblitz menu entry `LND -> lnbalance` shows an error
`*** YOUR SATOSHI BALANCES ***`
`[lncli] flag provided but not defined: -1`
`parse error: Invalid numeric literal at line 1, column 10`
and the `LN EARNED (FORWARD) FEES` shows 0 sats incorrectly (probably a consequential error)

Maybe this is something to have an eye on or even a separate ticket?

**Comment by openoms** [comment]
yes please open a separate issue as it is likely a problem with the script, not LND itself.

**Comment by rootzoll** [comment]
@openoms 
> just realized that when updating LND from the menu a full reboot is called. Is there any particular reason why this is necessary?

It just my habbit that when infrastructure setup is changed - a fresh reboot is a good routine. I know its some more minutes of downtime of the node, but I think it makes sense ... especially because we plan to have in the future more error analysis during startup - to detect & assist problems - so this would get utilized for such updates.

**Comment by rootzoll** [comment]
@openoms so we just need to compile fresh protobuffs and thsi issue can go into final testing, correct?

**Comment by openoms** [comment]
yes, LND v0.15.0 seems to work ok, but new protobuffs are needed due to the new APIs (for Taproot mainly)

**Comment by drmartinberger** [comment]
> After updating Raspiblitz 1.7.2 to LND v0.15.0 the Raspiblitz menu entry `LND -> lnbalance` shows an error `*** YOUR SATOSHI BALANCES ***` `[lncli] flag provided but not defined: -1` `parse error: Invalid numeric literal at line 1, column 10` and the `LN EARNED (FORWARD) FEES` shows 0 sats incorrectly (probably a consequential error)
> 
> Maybe this is something to have an eye on or even a separate ticket?



> yes please open a separate issue as it is likely a problem with the script, not LND itself.

Opened #3196 .

**Comment by openoms** [comment]
> It just my habbit that when infrastructure setup is changed - a fresh reboot is a good routine. I know its some more minutes of downtime of the node, but I think it makes sense ... especially because we plan to have in the future more error analysis during startup - to detect & assist problems - so this would get utilized for such updates.

Ok, makes sense. I think it just bothers me on the machine I use to run a lot of custom services, not really applicable for a typically user or if it is they can work around using the scripts only as I do.

It just feels good to see a long a uptime.

**Comment by rootzoll** [comment]
OK I updated the protos - seem much smaller as before. I put this on  final testing & will make a test sd card build to run first tests

**Comment by 22388o** [comment]
Hey guys, I did upgrade to new version in my Raspiblitz and was no problem. Had reboot okay too.

**Comment by rootzoll** [comment]
OK tested fine so far - will be part of v1.8.0 release. Closing issue.
