### ISSUE TITLE
Feature Request: Web UI Console

### ISSUE THREAD

**Issue by robinvonmises** [raspiblitz/raspiblitz#3184]
It would be pretty neat to have a console inside the new web UI like for example the Homebridge UI (image below) has.

That way you could fully control the node right in the browser. No need to extra log in by Terminal or any other software like PuTTY

![grafik](https://user-images.githubusercontent.com/70470874/175259133-a1f6ac0f-fa5d-45bb-9d3c-d4a3d09bf5ce.png)

**Comment by openoms** [comment]
See this issue: https://github.com/rootzoll/raspiblitz/issues/2767#issue-1072605211

exposing your admin access to the web is not without tradeoffs though

**Comment by rootzoll** [comment]
Closing as duplicate - https://github.com/rootzoll/raspiblitz/issues/2767#issue-1072605211
