### ISSUE TITLE
Solved: how to force copy over lan of the blockchain-data

### ISSUE THREAD

**Issue by stn021** [raspiblitz/raspiblitz#3192]
**The problem :** after a new install of raspiblitz there may or may not be the option to copy "COPY (over lan)" or "SELFSYNC" the blockchain. 

SELFSYNC gets the blockchain by download. That can take a week easily.

The data can also be copied from an existing raspiblitz in the local network, but that option seems to depend on some kind of detection that at least in my network almost never works.

**The solution :** So, in case COPY (over lan) is not shown in the menu raspiblitz will reboot and start one week of  SELFSYNC. At that point press CTRL-C, then type 'menu', in the menu choose 'REPAIR' then 'RESET-CHAIN  Delete Blockchain & Re-Download'

Then you get the option COPY (over lan). YAY :-)

Maybe this would be something for the FAQ because automatic unnecessary SELFSYNC is really time-wasting and really annoying.

**Comment by rootzoll** [comment]
Thanks for providing a way how to get it wotk with v1.7.2 - in upcomming v1.8.0 the detection should be better/fixed .. so I hope this workaround is no longer needed.
