### ISSUE TITLE
Parse error in lnbalance on Raspiblitz 1.7.2 after update to LND v0.15.0

### ISSUE THREAD

**Issue by drmartinberger** [raspiblitz/raspiblitz#3196]
After updating Raspiblitz 1.7.2 to LND v0.15.0 the Raspiblitz menu entry `LND -> lnbalance` shows an error
`*** YOUR SATOSHI BALANCES ***`
`[lncli] flag provided but not defined: -1`
`parse error: Invalid numeric literal at line 1, column 10`
and the `LN EARNED (FORWARD) FEES` shows 0 sats incorrectly (probably a consequential error)

**Comment by openoms** [comment]
works on my v1.7.2 LND node
might have been fixed post release, can you try to run:
`patch`
and try again?

**Comment by rootzoll** [comment]
I tested the script with v1.8.0rc3 (lnd 1.5.0) working OK.

**Comment by cstenglein** [comment]
Closing this issue for now, if it still persists with 1.9.0, please re-open
