### ISSUE TITLE
Reduce swapiness for SD cards and SSDs to avoid hardware failure

### ISSUE THREAD

**Issue by ghost** [raspiblitz/raspiblitz#3207]
I was testing this distro for home server, and saw that page bellow of how to reduce the swapiness to better preserve the SD and SSD,I tested it on my blitz and it works fine.

https://yunohost.org/it/backup/avoid_hardware_failure

**Comment by openoms** [comment]
Closing as solved with introducing ZRAM https://github.com/rootzoll/raspiblitz/issues/2905
