### ISSUE TITLE
fresh install of raspiblitz 1.7.2  failed to complete yesterday, today a diff story

### ISSUE THREAD

**Issue by maximlomans** [raspiblitz/raspiblitz#3209]
For some odd reason, the fresh install of raspiblitz 1.7.2  failed to complete yesterday .
Today i re-flashed the same sd-card and instead of using new passwords i used the same ones i had on the previous node with the same name - 

yesterday the wallet wasnt created, both lnd and bitcoind couldnt start
today the installer finished , including creating the new wallet, the
process is still running but today i am hopefull it will complete.
wait .. it's done, including the self reboot.

what happened and why ?
i had a hunch, and i followed it through.
the only thing i did differently today was use the same passwords, i assume the installer script still made use of previous data, but because the passwords were different to what it found on file, it couldnt complete the whole initial setup process.
 
- but i had chosen a fresh install yesterday too

even though i deleted all data as i had selected yesterday too

**Comment by openoms** [comment]
Is there a question, suggestion or request?

**Comment by maximlomans** [comment]
well, actually it was an impulse
