### ISSUE TITLE
LIT Node Connect

### ISSUE THREAD

**Issue by mark0st83** [raspiblitz/raspiblitz#3215]
Hello,

I have problems with Lightning Terminal Node Connect. After copy pairing phrase and copy into the field on terminal.lightning.engineering there happens nothing. 
Looking into the logs shows me the connection tried to complete but there may be an issue.

`torsocks[1757173]: 2022-07-08 12:31:26.556 [WRN] GRPC: [core] grpc: Server.Serve failed to create ServerTransport:  connection error: desc = "transport: http2Server.HandleStreams failed to receive the preface from client: error decrypting payload: error reading from go-back-n: EOF" `

`WRN] GRPC: [core] grpc: Server.Serve failed to complete security handshake from "mailbox:Xxxxxxxxxxxxxxx@mailbox.terminal.lightning.today:443": error reading from go-back-n: receive timeout `

`torsocks[1757173]: 2022-07-08 12:36:17.627 [DBG] MBOX: Server: got failure on receive socket, re-trying: rpc error: code = Canceled desc = context canceled `

I have reinstalled it and also updated to 0.6.7-alpha. I didn’t know where to look for the problem.

**Comment by openoms** [comment]
The connection is torified in order to not expose your IP address to the Terminal server. 
Tor has issues now: status.torproject.org, make sure to update: https://github.com/rootzoll/raspiblitz/issues/3179

**Comment by mark0st83** [comment]
Yeah I’m already updated Tor to 0.4.7.8 one or two weeks ago. That’s because I had massive problems with peer-connections. But after I switched from Umbrel to raspiblitz I haven’t connected with lit yet.

**Comment by openoms** [comment]
Testing the https://terminal.lightning.engineering/#/connect/pair with the old version (v0.6.3-alpha) in raspiblitz v1.7.2:
```
₿ sudo journalctl -fu litd
-- Journal begins at Mon 2022-04-04 15:52:30 BST. --
Jul 20 23:19:27 raspberrypi torsocks[18288]: 2022-07-20 23:19:27.876 [DBG] GRPC: [core] Subchannel Connectivity change to READY
Jul 20 23:19:27 raspberrypi torsocks[18288]: 2022-07-20 23:19:27.876 [DBG] GRPC: [core] pickfirstBalancer: UpdateSubConnState: 0x40004fc580, {READY <nil>}
Jul 20 23:19:27 raspberrypi torsocks[18288]: 2022-07-20 23:19:27.876 [DBG] GRPC: [core] Channel Connectivity change to READY
Jul 20 23:19:27 raspberrypi torsocks[18288]: 2022-07-20 23:19:27.902 [DBG] GRPC: [core] Subchannel Connectivity change to READY
Jul 20 23:19:27 raspberrypi torsocks[18288]: 2022-07-20 23:19:27.902 [DBG] GRPC: [core] pickfirstBalancer: UpdateSubConnState: 0x4000295df0, {READY <nil>}
Jul 20 23:19:27 raspberrypi torsocks[18288]: 2022-07-20 23:19:27.902 [DBG] GRPC: [core] Channel Connectivity change to READY
Jul 20 23:19:55 raspberrypi torsocks[18288]: 2022-07-20 23:19:55.897 [WRN] GRPC: [core] grpc: Server.Serve failed to create ServerTransport:  connection error: desc = "transport: http2Server.HandleStreams failed to receive the preface from client: error decrypting payload: error reading from go-back-n: cannot receive, gbn exited"
```


testing with the new (lit v0.7.0-alpha) version and getting the error:
![image](https://user-images.githubusercontent.com/43343391/180064169-5a21d377-1cc7-4987-b794-df3ee098a8f8.png)
need to trigger the creation of lit macaroons ?


Looking here https://github.com/lightninglabs/lightning-terminal/blob/master/doc/config-lnd-remote.md and in `litcli help`, but found no clues yet

There is only a session.db file which I tried to reset:
```
₿ sudo ls -la /home/lit/.lit/mainnet/
total 32
drwx------ 2 lit lit  4096 Jul 20 20:20 .
drwxr-xr-x 4 lit lit  4096 Jul 20 19:42 ..
-rw------- 1 lit lit 32768 Jul 20 20:20 session.db
```

OK, on a reinstall with blitz v1.8.0rc4 and LIT reinstalled to v0.7.0-alpha the connect option works.

**Comment by guggero** [comment]
> @guggero could you please suggest how can we have the lit.macaroon created?

We did change a few things in LiT recently related to macaroons and LNC. So my answer would've been to update LiT as well (which you already did now).
Good to hear things are working now!
