### ISSUE TITLE
BTCPay 1.6.1 Update

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#3217]
https://twitter.com/BtcpayServer/status/1545444707169636353?s=20&t=zvQ7vNt2AhIcSYuwHpAlWw

**Comment by openoms** [comment]
Updated ok from the menu in v1.7.2.

There is now a warning in the dashboard about needing the postgres backend for NBXplorer:

```
Wallet Balance
x.xxxx BTC

We would like to show you a chart of your balance. Please [migrate to the new NBXplorer backend](https://github.com/dgarage/NBXplorer/blob/master/docs/Postgres-Migration.md) for that data to become available.
```

Would like to have some help with autogenerating the postgres instance: #3218

**Comment by openoms** [comment]
To use the latest script to update BTCpay on v1.7.2 simply run `patch`
https://twitter.com/openoms/status/1530626502139727877?s=20&t=qxIfAvijayuNsuFQc7ECzw
or
```
# download
wget -O /home/admin/config.scripts/bonus.btcpayserver.sh https://github.com/rootzoll/raspiblitz/blob/dev/home.admin/config.scripts/bonus.btcpayserver.sh

# update
/home/admin/config.scripts/bonus.btcpayserver.sh update
```

**Comment by rootzoll** [comment]
Install looks good with new version - closing issue for v1.8.0
