### ISSUE TITLE
Add postgres backend for NBXplorer / BTCPayServer

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#3218]
So far we have an older version of NBXplorer pinned: #3055 #3217 

Help would be appreciated to have postgres set up automatically. 

Keep in mind that postgres can potentially serve the lightning instances as well.

**Comment by NicolasDorier** [comment]
just bump nbxplorer, and add those env variables: (replace with your own connection string if database is different)

```
      NBXPLORER_POSTGRES: User ID=postgres;Host=postgres;Port=5432;Application Name=nbxplorer;MaxPoolSize=20;Database=nbxplorer${NBITCOIN_NETWORK:-regtest}
      NBXPLORER_AUTOMIGRATE: 1
      NBXPLORER_NOMIGRATEEVTS: 1
```

Note that AUTOMIGRATE will just be ignored for new installs, so you can safely set that up for all.
You can also leave it after migration, it will be ignored.

In BTCPay, you need to link the database with the EXPLORERPOSTGRES.

```
BTCPAY_EXPLORERPOSTGRES: User ID=postgres;Host=postgres;Port=5432;Application Name=btcpayserver;MaxPoolSize=80;Database=nbxplorer${NBITCOIN_NETWORK:-regtest}
```

You know it's working if you can see btcpayserver wallet graph.

More doc is there https://github.com/dgarage/NBXplorer/blob/master/docs/Postgres-Migration.md

but I think this is all you need.

**Comment by NicolasDorier** [comment]
version is `nicolasdorier/nbxplorer:2.3.28`

**Comment by NicolasDorier** [comment]
Ping me if you have any issues. Though I didn't have any issues since I auto migrated people. Got a few perf issues on some big instances, but this has been fixed, so I doubt you'll have any issue.

**Comment by openoms** [comment]
> version is `nicolasdorier/nbxplorer:2.3.28`

we are using https://github.com/dgarage/NBXplorer. That's the right repo, right?
https://github.com/dgarage/NBXplorer/releases/tag/v2.3.28

**Comment by NicolasDorier** [comment]
yes, sorry I was linking the docker image

**Comment by openoms** [comment]
The command line arguments for these (using them in the systemd service or rather in `/home/btcpay/.nbxplorer/Main/settings.config`):
```
NBXPLORER_POSTGRES: User ID=postgres;Host=postgres;Port=5432;Application Name=nbxplorer;MaxPoolSize=20;Database=nbxplorer${NBITCOIN_NETWORK:-regtest}
NBXPLORER_AUTOMIGRATE: 1
NBXPLORER_NOMIGRATEEVTS: 1
```
```
--postgres='User ID=postgres;Host=postgres;Port=5432;Application Name=nbxplorer;MaxPoolSize=20;Database=nbxplorermainnet'
--automigrate=1
--nomigrateevts=1
```

**Comment by NicolasDorier** [comment]
yes. Note systemd can also set environment variable.  (be careful there are spaces in the connection string)

**Comment by openoms** [comment]
@NicolasDorier are you planning to continue the PGP signing of the BTCPayServer releases as well (there were some signatures from Kukks before)?

**Comment by NicolasDorier** [comment]
you mean for signing the release? I don't pay attention to it, git commit is signing automatically. Sometimes Kukks can make releases.

**Comment by openoms** [comment]
> you mean for signing the release? I don't pay attention to it, git commit is signing automatically. Sometimes Kukks can make releases.

yes, we verify the tags - which is really just the signature of the last git commit. The issue is this being a random person (from a PR maybe) is that we cannot verify the updates.

**Comment by openoms** [comment]
I used the setting for postgres in the /home/btcpay/.nbxplorer/Main/settings.config for NBXplorer:
```
postgres='User ID=postgres;Host=postgres;Port=5432;Application Name=nbxplorer;MaxPoolSize=20;Database=nbxplorermainnet'
automigrate=1
nomigrateevts=1
```
Getting the error:
```
info: NBXplorer.DatabaseSetup: Postgres services activated
dotnet[3263134]: Unhandled exception. System.ArgumentException: Format of the initialization s
tring does not conform to specification starting at index 84.    
```

Will need to initialize the postgres database. Do you have a script for that already?

**Comment by NicolasDorier** [comment]
no I guess the problem come from the quote `'`, you don't need initialise the db, NBX should do it.

**Comment by NicolasDorier** [comment]
@openoms if you use `settings.config`, remove quote.

**Comment by openoms** [comment]
ok, works without quotes..
to fix 
```
Unhandled exception. System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known
```
needed to set the 
`Host=postgres;` to `Host=localhost;` 
since not dockerised.

but now expects a password:
```
Unhandled exception. Npgsql.NpgsqlException (0x80004005): No password has been provided but the backend requires one (in MD5)
```
It would be ideal to password protect the btcpay database.

will also need to:
- [x] symlink the postgres data directory (`/var/lib/postgresql/13/main/`) to the disk

**Comment by NicolasDorier** [comment]
The doc for connection string is here https://www.npgsql.org/doc/connection-string-parameters.html

**Comment by openoms** [comment]
What worked with a hardcoded password `raspiblitz` so far:

Install postgres:
```
sudo apt install -y postgresql
sudo systemctl enable postgresql
sudo systemctl start postgresql
```
Autogenerate the database:
```
sudo -u postgres psql -c "create database nbxplorermainnet;"
sudo -u postgres psql -c "create user btcpay with encrypted password 'raspiblitz';"
sudo -u postgres psql -c "grant all privileges on database nbxplorermainnet to btcpay;"
```

NBXplorer config:
```
echo "\
network=mainnet
btc.rpc.user=raspibolt
btc.rpc.password=PASSWORD_B
postgres=User ID=btcpay;Host=localhost;Port=5432;Application Name=nbxplorer;MaxPoolSize=20;Database=nbxplorermainnet;Password='raspiblitz';
automigrate=1
nomigrateevts=1
" | sudo -u btcpay tee  /home/btcpay/.nbxplorer/Main/settings.config
```
```
₿ sudo journalctl -fu nbxplorer -n 100
...
info: NBXplorer.PostgresMigration: The migration completed in 0 minutes.
...
```

Can change the database password with:
```
newPassword="test9"
sudo -u postgres psql -c "alter user btcpay with encrypted password '${newPassword}';"
sudo -u btcpay sed -i "s/Password=*/Password='${newPassword}';/g" /home/btcpay/.nbxplorer/Main/settings.config
```

Ideas how to best avoid the hardcoded password are welcome.
It needs to be recoverable (as a priority) and I feel reluctant to tie it to any existing one.
