### ISSUE TITLE
lightning terminal loop out error 

### ISSUE THREAD

**Issue by BitromNO** [raspiblitz/raspiblitz#3220]
Hi! 
I have upgraded to lnd 0.15 beta and tried a loop out yesterday. 
In history it says (Temporary Failure - The swap cannot continue due to an internal error. Manual intervention such as a restart is required. funds are gone but nothing happend)
Is there a way to restart or abort the swap?

**Comment by openoms** [comment]
Try the cli 
```
sudo su - lit

lit-loop --help
```

**Comment by BitromNO** [comment]
> 

"type": "LOOP_OUT",
            "state": "FAILED",
            "failure_reason": "FAILURE_REASON_TIMEOUT",
