### ISSUE TITLE
JAM v0.0.8 needs NPM and node update

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#3224]
```
##########################################################################
# OK --> the PGP signature of the checked out a958ba6 commit is correct
##########################################################################

npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: jam@0.0.8
npm ERR! notsup Not compatible with your version of node/npm: jam@0.0.8
npm ERR! notsup Required: {"node":">=16.11.0","npm":">=8.0.0"}
npm ERR! notsup Actual:   {"npm":"7.24.0","node":"v16.10.0"}
```

**Comment by openoms** [comment]
We are 2 major versions behind with NodeJS:
https://nodejs.org/dist/
![image](https://user-images.githubusercontent.com/43343391/178535087-cae895e0-5614-4f5c-8060-4a4580dde3ac.png)
Can we update to the latest or at least a v0.17.x @rootzoll @cstenglein ?

**Comment by rootzoll** [comment]
The nodeJS v18 line seems to be the best to switch to and will be active until Oct next year:

https://nodejs.org/en/about/releases/
![Bildschirmfoto 2022-07-12 um 20 43 03](https://user-images.githubusercontent.com/2472225/178570550-91404040-d4f3-4c37-9764-346bd36fe44a.png)

I will basically create a sd card build with v18 and see if any problems come up.

**Comment by openoms** [comment]
Also npm can be installed as latest, no need to stick to v7 any more

**Comment by openoms** [comment]
Settled on a more conservative nodeJS update which works with JAM also and has lower risk of breaking anything else.

**Comment by rootzoll** [comment]
Looks good so far - closing issue for v1.8.0
