### ISSUE TITLE
[Feature Request] Make installation and configuration of LNDg possible

### ISSUE THREAD

**Issue by md-weber** [raspiblitz/raspiblitz#3230]
I would love to have the possibility to install and configure LNDg right from the main menu. 

https://github.com/cryptosharks131/lndg

**Comment by openoms** [comment]
There is a PR, but not-functional currently: https://github.com/rootzoll/raspiblitz/pull/3153
Might need a new one.

**Comment by mark0st83** [comment]
I've installed lndg with 1.7.2 and a virtual setting on debian (proxmox). I've used @openoms [documentation ](https://github.com/openoms/lightning-node-management/blob/en/hardware/raspiblitz/lndg.md)for this.
I had to change a few things in the nginx.sh and a few commands from @openoms 

But it works

**Comment by allyourbankarebelongtous** [comment]
I'm working on this now, see https://github.com/allyourbankarebelongtous/raspiblitz/tree/integrate_lndg. Still hasn't been tested yet, should get to that this weekend. After successful testing I'll submit a PR.

**Comment by rootzoll** [comment]
PR #3313 is candidate to be merged in v1.9.0

**Comment by rootzoll** [comment]
Merging #3313 into feature branch `3313-lndg` to test and finish last smal things.

**Comment by rootzoll** [comment]
- [x] Make sure to still fix this: https://github.com/rootzoll/raspiblitz/pull/3313#discussion_r1024539631

**Comment by rootzoll** [comment]
OK recovery test worked - merging `3313-lndg` branch. And to be final tested during RC phase.
