### ISSUE TITLE
Invalid Password C during sync after Recover  

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#3235]
Was a node with the blockchain a bit behind (off-time) and then running a recover - the sync screen asks to unlock the lightning wallet. Even its the correct passwort it comes back as "unvalid" an the WebUI does not offer a retry. When the WebUI gets reloaded thru the browser Lighting says its started ... so unlock may have worked in the background.

**Comment by rootzoll** [comment]
![Bildschirmfoto 2022-07-20 um 19 13 41](https://user-images.githubusercontent.com/2472225/180042869-23e0e917-439b-40c8-abbd-0bea51ef6f08.png)

@cstenglein when does this "Invalid Password" notice gets created and can iz be remobved when there is no further password input box anymore?

**Comment by cstenglein** [comment]
Will show the correct error with https://github.com/cstenglein/raspiblitz-web/issues/387

~~I guess you entered the password wrong / had connection issues the first time & then it worked, since lightning displays as started?~~

Nvm, is in the description :)

**Comment by cstenglein** [comment]
Should be fixed now in master, please test :)

**Comment by rootzoll** [comment]
Dont have the time to reproduce (would need a node with a blockchain some days behind) - will move issue to v1.8.1 to see if we need to give it another try.

**Comment by cstenglein** [comment]
Think it also has to do with the API or redis, just tested it with 1.8.0:

Unlocking the wallet returned an unknown error.

Trying to unlock it again, it now displays the following:

![image](https://user-images.githubusercontent.com/9399034/181645797-6714fcb2-f283-4f54-bdce-b87f592049d3.png)

The main issue that the unlock input is still available is that I get `ln_default_locked` with `1` even after unlock:

![image](https://user-images.githubusercontent.com/9399034/181645911-6558849f-af39-40af-ab26-8bc34b66559c.png)

On the Terminal, it still displays the unlock input as well. Trying to unlock it leads to the same error, but aborting the input on the ssh dialog then leads to the WebUI correctly getting `ln_default_locked` with ´0` and thus the lightning status.
