### ISSUE TITLE
raspiblitz and miners

### ISSUE THREAD

**Issue by hrshit-Glix12** [raspiblitz/raspiblitz#3238]
"**Raspiblitz**" mine block itself or use(require) third party miners ...? if third party miners require then how to connect each other raspiblitz and third party miner.....?

**Comment by rootzoll** [comment]
A ASIC to connect to the RaspiBlitz would be needed. To connect an ASIC and control it with RaspiBlitz a mining software is needed that is not abvailable yet - this issue discusses adding such software in the future: #414
