### ISSUE TITLE
Kepp same TLS certs/macaroons after Update

### ISSUE THREAD

**Issue by raumi75** [raspiblitz/raspiblitz#324]
After upgrading to version 1.0, my Shango connection was working fine. Then I noticed that there was no dynamic dns in the services section. So I added that again, just to have a proper setup.

What I did not realize was that it generates a new tls certificate and throws away the old one. In my case that was not necessary because I was using the same domain.

Is there a reason for that behavior? Could we move the old tls.* files somewhere instead of deleting them? In my case, I recovered the keys from a backup because I did not want to reconnect my clients.

```
/home/admin/config.scripts/lnd.newtlscert.sh 
```

**Comment by rootzoll** [comment]
Thats right .. on the recover/update if might do that. I will add this to the next 1.1 release.

**Comment by rootzoll** [comment]
TODO: Check if dyndns stay stable after update process.

**Comment by rootzoll** [comment]
To prevent TLS renew on update I havent found an elegant solution. For now after an update you most prob need to re-connected your devices. 

But I changed the delete to a move like this:
```
echo "keep old tls data as backup"
sudo mv /mnt/hdd/lnd/tls.cert /mnt/hdd/lnd/tls.cert.old 
sudo mv /mnt/hdd/lnd/tls.key /mnt/hdd/lnd/tls.key.old 
```

But it could even happen that on a update its called twice ... so this is not a solution yet, just a first tweak.

Maybe before an update/recovery begins it should backup the TLS and Macroons and when its done setting everything up it will copy them back - not sure.

**Comment by rootzoll** [comment]
Moving for a more enhanced solution to future release milestone.

**Comment by rootzoll** [comment]
On the beginning of a update TLS certs and macaroons are getting now backuped and replayed at the end of a backup - so after a update connections to external devices/wallets should stay stable.

TODO: Test on update.

**Comment by rootzoll** [comment]
DONE: Still found the bug, that when AUTO-UNLOCK is active before update. The re-activating of that feature during final recovery setup dialogs is still changening the TLS certs again.

**Comment by rootzoll** [comment]
OK now tested and works.

**Comment by openoms** [comment]
Users have been reporting that the they could not connect Zap after chnaging their IP.
Manually resetting the TLS.cert helped.

Should this be automated every time when the publicIP is triggered to changed in lnd.conf
by the 
```
  # RECHECK PUBLIC IP
  # when public IP changes, restart LND with new IP
```
function of _background.sh?
