### ISSUE TITLE
 message(btc-testrun-fail)

### ISSUE THREAD

**Issue by jessehodl** [raspiblitz/raspiblitz#3242]
###########################################################
# /home/admin/raspiblitz.log

***********************************************
Running RaspiBlitz Bootstrap 1.7.2
Sat 19 Feb 23:51:34 GMT 2022
***********************************************
# *** /home/admin/config.scripts/blitz.ssh.sh checkrepair
# countKeyFiles(8)
# OK: SSHD RUNNING
## INIT raspiblitz.info
baseimage=raspios_arm64
cpu=aarch64
displayClass=lcd
displayType=
setupPhase=setup
setupStep=0
fsexpanded=0
state=starting
btc_mainnet_sync_initial_done=0
btc_testnet_sync_initial_done=0
btc_signet_sync_initial_done=0
ln_lnd_mainnet_sync_initial_done=0
ln_lnd_testnet_sync_initial_done=0
ln_lnd_signet_sync_initial_done=0
ln_cl_mainnet_sync_initial_done=0
ln_cl_testnet_sync_initial_done=0
ln_cl_signet_sync_initial_done=0
## INIT RaspiBlitz Cache ... wait background.scan.service to finish first scan loop
- waiting for background.scan.service --> systemscan_runtime()
- waiting for background.scan.service --> systemscan_runtime()
- waiting for background.scan.service --> systemscan_runtime()
- waiting for background.scan.service --> systemscan_runtime()
- waiting for background.scan.service --> systemscan_runtime()
- waiting for background.scan.service --> systemscan_runtime()
- waiting for background.scan.service --> systemscan_runtime(7)
OK - logs are at 33 MB - within safety limit
Waiting for HDD/SSD ...
total 636
drwxr-xr-x   4 root root   4096 Feb 19 23:48 .
drwxr-xr-x 123 root root  12288 Feb 19 23:51 ..
-rw-r--r--   1 root root 577771 Mar 13  2021 moduli
-rw-r--r--   1 root root   1650 Mar 13  2021 ssh_config
drwxr-xr-x   2 root root   4096 Mar 13  2021 ssh_config.d
-rw-r--r--   1 root root   3289 Mar 13  2021 sshd_config
drwxr-xr-x   2 root root   4096 Mar 13  2021 sshd_config.d
-rw-------   1 root root   1381 Feb 19 23:48 ssh_host_dsa_key
-rw-r--r--   1 root root    606 Feb 19 23:48 ssh_host_dsa_key.pub
-rw-------   1 root root    513 Feb 19 23:48 ssh_host_ecdsa_key
-rw-r--r--   1 root root    178 Feb 19 23:48 ssh_host_ecdsa_key.pub
-rw-------   1 root root    411 Feb 19 23:48 ssh_host_ed25519_key
-rw-r--r--   1 root root     98 Feb 19 23:48 ssh_host_ed25519_key.pub
-rw-------   1 root root   2602 Feb 19 23:48 ssh_host_rsa_key
-rw-r--r--   1 root root    570 Feb 19 23:48 ssh_host_rsa_key.pub
-rw-r--r--   1 root root    342 Feb 28  2020 ssh_import_id
HDD/SSD connected: sda
No HDMI switch found.
No FS EXPAND needed. needsExpansion(0) fsexpanded(0)
No WIFI RESTORE because no /var/cache/raspiblitz/hdd-inspect/wpa_supplicant.conf
No SSH SERVER CERTS RESTORE because no /var/cache/raspiblitz/hdd-inspect
No SSHRESET switch found.
No DISPLAY RESTORE because no /var/cache/raspiblitz/hdd-inspect/raspiblitz.conf
No UASP FIX needed
isMounted: 0
HDD already part of system: 0
Temp mounting (1) data drive
Temp mounting (1) result: 1
HDD is there but not AutoMounted yet - Waiting for user Setup/Update
# df
Filesystem     1K-blocks      Used Available Use% Mounted on
/dev/root       30350796   5143160  23939444  18% /
devtmpfs         1933972         0   1933972   0% /dev
tmpfs            1968596        16   1968580   1% /dev/shm
tmpfs             787440       748    786692   1% /run
tmpfs               5120         0      5120   0% /run/lock
tmpfs              32768         0     32768   0% /var/cache/raspiblitz
/dev/mmcblk0p1    258095     30522    227574  12% /boot
tmpfs             393716        20    393696   1% /run/user/1000
tmpfs             393716        20    393696   1% /run/user/1001
/dev/sda1      960379920 468950560 442574936  52% /mnt/hdd
# lsblk -o NAME,FSTYPE,LABEL
NAME        FSTYPE LABEL
sda
└─sda1      ext4   BLOCKCHAIN
mmcblk0
├─mmcblk0p1 vfat   boot
└─mmcblk0p2 ext4   rootfs
# RASPIBLITZ DATA DRIVE Status

# BASICS
isMounted=1
isBTRFS=0
hddRaspiData=0
hddRaspiVersion=''
isSSD=1
datadisk='sda'
datapartition='sda1'
hddCandidate='sda'
hddPartitionCandidate='sda1'
hddBlocksBitcoin=1
hddBytes=1000203091968
hddGigaBytes=931
hddUsedInfo='448G (52%)'
hddDataFreeBytes=453196734464
hddDataFreeKB=442574936
hddDataFreeGB=422
hddAdapterUSB='174c:1153'
hddAdapterUSAP=1

# RAID
isRaid=0
raidCandidates=0

# SWAP
isSwapExternal=0

Displaying Info Message: Please Login for Setup
## WAIT LOOP: USER SETUP/UPDATE/MIGRATION
# PROVISION PROCESS with setupPhase(setup)
Temp mounting (2) data drive (hddFormat='ext4')
Temp mounting (2) result: 1
Refreshing links between directories/drives ..

*** Enable Tor Service ***
*** Create directories and set permissions ***
mkdir: created directory '/mnt/hdd/app-data/tor'
mkdir: created directory '/mnt/hdd/app-data/tor/torrc.d'
mkdir: created directory '/mnt/hdd/tor'
mkdir: created directory '/mnt/hdd/tor/sys'
mkdir: created directory '/mnt/hdd/tor/sys/keys'
mkdir: created directory '/mnt/hdd/tor/services'
mkdir: created directory '/mnt/hdd/tor/onion_auth'
mode of '/mnt/hdd/tor' changed from 0755 (rwxr-xr-x) to 0700 (rwx------)
mode of '/mnt/hdd/app-data/tor' retained as 0755 (rwxr-xr-x)
mode of '/mnt/hdd/app-data/tor/torrc.d' retained as 0755 (rwxr-xr-x)
mode of '/etc/tor/torrc' retained as 0644 (rw-r--r--)
failed to change mode of '/mnt/hdd/app-data/tor/torrc.d/*' from 0644 (rw-r--r--) to 0644 (rw-r--r--)
changed ownership of '/mnt/hdd/tor/sys/keys' from root:root to debian-tor:debian-tor
changed ownership of '/mnt/hdd/tor/sys' from root:root to debian-tor:debian-tor
changed ownership of '/mnt/hdd/tor/onion_auth' from root:root to debian-tor:debian-tor
changed ownership of '/mnt/hdd/tor/services' from root:root to debian-tor:debian-tor
changed ownership of '/mnt/hdd/tor' from root:root to debian-tor:debian-tor
ownership of '/mnt/hdd/app-data/tor/torrc.d' retained as root:root
ownership of '/mnt/hdd/app-data/tor' retained as root:root
- /etc/tor/torrc will get edited

*** updating Tor config /etc/tor/torrc ***
## See https://github.com/torproject/tor/blob/main/src/config/torrc.sample.in

%include /mnt/hdd/app-data/tor/torrc.d

DataDirectory /mnt/hdd/tor/sys
PidFile /mnt/hdd/tor/sys/tor.pid

SafeLogging 0
Log notice stdout
Log notice file /mnt/hdd/tor/notice.log
Log info file /mnt/hdd/tor/info.log

RunAsDaemon 1
ControlPort 9051
SocksPort 9050 IsolateDestAddr
ExitRelay 0
CookieAuthentication 1
CookieAuthFileGroupReadable 1

- /mnt/hdd/app-data/tor/torrc.d/bridges already edited
# DO NOT EDIT! This file is generated by raspiblitz and will be overwritten
[Service]
ReadWriteDirectories=-/mnt/hdd/tor
[Unit]
After=network.target nss-lookup.target mnt-hdd.mount

# df
Filesystem     1K-blocks      Used Available Use% Mounted on
/dev/root       30350796   5040920  24041684  18% /
devtmpfs         1933972         0   1933972   0% /dev
tmpfs            1968596        16   1968580   1% /dev/shm
tmpfs             787440       748    786692   1% /run
tmpfs               5120         0      5120   0% /run/lock
tmpfs              32768         8     32760   1% /var/cache/raspiblitz
/dev/mmcblk0p1    258095     30522    227574  12% /boot
tmpfs             393716        20    393696   1% /run/user/1000
tmpfs             393716        20    393696   1% /run/user/1001
/dev/sda1      960379920 468950640 442574856  52% /mnt/hdd
# lsblk -o NAME,FSTYPE,LABEL
NAME        FSTYPE LABEL
sda
└─sda1      ext4   BLOCKCHAIN
mmcblk0
├─mmcblk0p1 vfat   boot
└─mmcblk0p2 ext4   rootfs
# Sourcing /var/cache/raspiblitz/temp/raspiblitz.setup
# migrationFile()
# Sourcing /mnt/hdd/raspiblitz.conf
# RASPIBLITZ CONFIG FILE
raspiBlitzVersion='1.7.2'
lcdrotate='1'
lightning='lnd'
network='bitcoin'
chain='main'
hostname='GroeFreiheit'
runBehindTor='on'
# Sourcing /var/cache/raspiblitz/temp/raspiblitz.setup
# setting PASSWORD A

OK - password A changed for user pi, root, admin & bitcoin
...
Calling _provision.setup.sh for basic setup tasks ..
Follow in a new terminal with: 'tail -f raspiblitz.provision-setup.log'
***********************************************************
ERROR - please report to development team
***********************************************************
state(error) message(btc-testrun-fail)
https://github.com/rootzoll/raspiblitz#support
command to shutdown --> off
admin@192.168.178.9:~ ₿ off

Green activity light stays dark and LCD turns white when shutdown complete.
Then wait 5 seconds and disconnect power.
-----------------------------------------------
stop electrs - please wait ..
stop lightning - please wait ..
stop bitcoind (1) - please wait ..
stop bitcoind (2) - please wait ..
starting shutdown ...

**Comment by cstenglein** [comment]
@jessehodl  is this still an issue with 1.9.0?

Closing this for now, please re-open if it still persists.
