### ISSUE TITLE
Connect mobile failed because cl.rest.sh was not 'on'

### ISSUE THREAD

**Issue by NicolaLS** [raspiblitz/raspiblitz#3243]
Hi I set up a new node (erased user data but kept old blockchain) and choose `c-lightning` then I wanted to connect to [Zeus](https://github.com/ZeusLN/zeus), but it failed to output the macaroon qr. I looked into the scripts and noticed that `hex_macaroon=$(xxd -plain /home/bitcoin/c-lightning-REST/certs/access.macaroon | tr -d '\n')` (in `/home/admin/config.scripts/cl.rest.sh` line 32) did not work because `/home/bitcoin/c-lightning-REST` did not even exist. I just called the `/home/admin/config.scripts/cl.rest.sh on` manually and the directories got created and everything worked fine.

Did I miss something in the setup or could this be a bug ?

**Comment by rootzoll** [comment]
Will make a quick check with upcoming v1.8.0 if this problem still exists.
