### ISSUE TITLE
LNbits Security Patch

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#3247]
https://twitter.com/lnbits/status/1552250374068883457?s=20&t=zjAeJ0x9rrsiY5Qzg3lpAw .. make sure to release v1.8.0 with an LNbits including the security patch.

**Comment by arcbtc** [comment]
You can close. This was a false alarm. The report was very a very legitimate source, which is why we jumped the gun on asking people to disable their installs. Better safe than sorry
