### ISSUE TITLE
CL Wallet Encryption on after recovery

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#3248]
I have a node with core lightning running next to default lnd. The wallet encryption is turned off. Then I run a recovery/update and core lightning mainnet is not running after (startup fails). If "SETTINGS" I see that wallet encryption is on for Core Lightning. If I turn it off - core lightning is running OK again.

Still have to reproduce that problem.

**Comment by openoms** [comment]
Closing as this has been addressed already.
