### ISSUE TITLE
Services Channel Autopilot

### ISSUE THREAD

**Issue by fritzschoff** [raspiblitz/raspiblitz#325]
I got some coins in my wallet and I wanted to activate the channel autopilot. But everytime I hit enter, I got the following screen: 
![screenshot 2019-02-17 at 11 41 30](https://user-images.githubusercontent.com/39312833/52911789-1b46d700-32a9-11e9-915e-253c0aa3b283.png)
I also did a restart. Maybe I read the documentation wrong, but do I need to open a channel first?
Regards,
Max

**Comment by rootzoll** [comment]
did you used space before enter to activate autopilot?

Am So., 17. Feb. 2019, 11:43 hat Max <notifications@github.com> geschrieben:

**Comment by fritzschoff** [comment]
wow, can't tell ya how dumb I feel now...

**Comment by rootzoll** [comment]
You were not the first reporting this .. added more text info about that in
coming v1.0 release.

Am So., 17. Feb. 2019, 13:08 hat Max <notifications@github.com> geschrieben:
