### ISSUE TITLE
Just a suggestion.... 

### ISSUE THREAD

**Issue by DrBlackross** [raspiblitz/raspiblitz#3253]
for the https://github.com/rootzoll/raspiblitz/tree/dev/alternative.platforms#amd64-image

try installing the liquorix kernel, with ssd... for some reason the instructions suggest a usb drive (took forever to boot, then realized it was just how i was reading it), once i just wrote the image a 120gb ssd and expanded the system on my desktop..... BOOOM! boot up in 5 seconds. now with a liquorix kernel (on amd), i see the grub for 3 seconds then instant gnome login manager, crazy fast.

**Comment by DrBlackross** [comment]
and yes, once i migrate my NES rpi node to this wicked AMD rack mount job, i will retire my NES node

(and wait for 8.0, i do actually like it, just wish the raspiblitz 8.0 image was out for amd)

**Comment by DrBlackross** [comment]
Oh yeah, and turn off suspend lol
$ sudo systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target

**Comment by BitromNO** [comment]
its fast! no doubt! i use a MSI Cubi-N mini pc, with internal disk for os and blockchain, and im so happy with it. no more cabels sticking out! 
just patch it to v.1.8 in the patch menu. the version came out yesterday :)

**Comment by BitromNO** [comment]
> Oh yeah, and turn off suspend lol $ sudo systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target

i beleve they are going to make this ready in v1.8.1, ive alreasy made an issue: 
https://github.com/rootzoll/raspiblitz/issues/3245

**Comment by DrBlackross** [comment]
yea was kinda fun, had it all set up in the rack mount case, dragged it down to the basement, mounted it into the 2nd (wall house) rack, ran power and net.... fired it up.

came upstairs, its pinging out LOL

go back down look over across the basement and the power led is flashing like a jack russell :0  

OH, as far as updating goes, same as any, use the menu to update to 1.8, then i'll have the web front end like i did with NESpi?
also is there a way to get the cpu temp info (like which part of the script to edit, etc)?

**Comment by wchancao** [comment]
Did you connect the nes pi data ssd into the pc? Or did you sync a new node with a new data ssd?

**Comment by DrBlackross** [comment]
i had 5.25 2tb hard drive to use, its a server hard drive (barracuda), sooooo its mounted in a server case LOL, the main boot drive is a 120gb ssd kingston (that has raspiblitz on it with filesystem expanded).... 

i was redoing the NESpi since the fan went out (cooling is a big issue with that tiny case) and replaced the 1tb drive that failed in there (that i JUST backed up the month before) so i had to resync anyway and checked here and saw rootz put out a 1.8, tried it, liked the web interface.... looked at git hub the next day so on a lark checked on the status of an amd64 option since i've mucked with other alternate installations of raspiblitz before, and hey, there was a 1.72 amd64 image there. so i went and repurposed my old chia farm server (waste of time) for raspiblitz (better turn over) lol

**Comment by DrBlackross** [comment]
you would think after 30+ years of bulletin board systems..... i would be used to this. but i still post like its an irc chat

(see ^ had to re-edit my post again)

**Comment by DrBlackross** [comment]
> Did you connect the nes pi data ssd into the pc? Or did you sync a new node with a new data ssd?

BUT, i did use my .bitcoin folder on my desktop (linux) to move the blockchain over to the Nespi before in the past... it does speed it up, the RPI is a bit slow when it comes to tor, with the AMD in the basement im already at 25% sync'd after a day, with the Nespi's RPI4 it took a week for me to get to that percent 

(i don't have a mobo for my threadripper or i'd thrown it on that LOL)

**Comment by DrBlackross** [comment]
i do miss the LTC lightning node

**Comment by DrBlackross** [comment]
> Did you connect the nes pi data ssd into the pc? Or did you sync a new node with a new data ssd?

i used the restore node lnd-rescue-*.tar.gz route, but i do have the old HDD here in the desktop just in case to copy down to the basement, then after the node was sync'd updated to 1.8, then things got weird... mempool, and the webui (no special password characters, just keeps telling me pass word wrong) doesn't work. RTL and ThunderHub do.

but no ports open for mempool or webui

sudo lsof -i -P -n | grep LISTEN
cupsd       551         root    6u  IPv6  14506      0t0  TCP [::1]:631 (LISTEN)
cupsd       551         root    7u  IPv4  14507      0t0  TCP 127.0.0.1:631 (LISTEN)
redis-ser   557        redis    6u  IPv4  13090      0t0  TCP 127.0.0.1:6379 (LISTEN)
redis-ser   557        redis    7u  IPv6  13091      0t0  TCP [::1]:6379 (LISTEN)
sshd        610         root    3u  IPv4  13765      0t0  TCP *:22 (LISTEN)
sshd        610         root    4u  IPv6  13767      0t0  TCP *:22 (LISTEN)
mariadbd    660        mysql   22u  IPv4  14977      0t0  TCP 127.0.0.1:3306 (LISTEN)
tor         758   debian-tor    6u  IPv4  13972      0t0  TCP 127.0.0.1:9050 (LISTEN)
tor         758   debian-tor    7u  IPv4  13973      0t0  TCP 127.0.0.1:9051 (LISTEN)
postgres    782     postgres    5u  IPv6  14107      0t0  TCP [::1]:5432 (LISTEN)
postgres    782     postgres    6u  IPv4  14108      0t0  TCP 127.0.0.1:5432 (LISTEN)
zerotier-  1954 zerotier-one    6u  IPv4  17536      0t0  TCP 127.0.0.1:9993 (LISTEN)
zerotier-  1954 zerotier-one    7u  IPv6  17537      0t0  TCP [::1]:9993 (LISTEN)
zerotier-  1954 zerotier-one   14u  IPv4  17137      0t0  TCP 192.168.1.32:9993 (LISTEN)
zerotier-  1954 zerotier-one   16u  IPv4  17139      0t0  TCP 192.168.1.32:57403 (LISTEN)
zerotier-  1954 zerotier-one   18u  IPv4  17141      0t0  TCP 192.168.1.32:43254 (LISTEN)
bitcoind   6475      bitcoin   12u  IPv4  26547      0t0  TCP 127.0.0.1:8332 (LISTEN)
bitcoind   6475      bitcoin   19u  IPv4  27478      0t0  TCP 127.0.0.1:28332 (LISTEN)
bitcoind   6475      bitcoin   21u  IPv4  27480      0t0  TCP 127.0.0.1:28333 (LISTEN)
bitcoind   6475      bitcoin   36u  IPv4 110137      0t0  TCP 127.0.0.1:8333 (LISTEN)
bitcoind   6475      bitcoin   37u  IPv4 110138      0t0  TCP 127.0.0.1:8334 (LISTEN)
node      49370      mempool   30u  IPv6 120033      0t0  TCP *:8999 (LISTEN)
lnd       49562      bitcoin    8u  IPv4 115714      0t0  TCP *:10009 (LISTEN)
lnd       49562      bitcoin   11u  IPv4 114972      0t0  TCP *:8080 (LISTEN)

:(

(screenshots below.... )

![Screenshot from 2022-08-09 12-13-02](https://user-images.githubusercontent.com/20823032/183703899-c2089173-a3ea-4104-a40d-ed1dc08e058c.png)
![Screenshot from 2022-08-09 12-13-39](https://user-images.githubusercontent.com/20823032/183703900-8a11db52-86bb-4433-ab15-2be72b1392b9.png)
![Screenshot from 2022-08-09 12-14-14](https://user-images.githubusercontent.com/20823032/183703902-014fd6e1-4468-4b46-b93e-5d16e87ab498.png)


don't know where to look in the logs for any errors

**Comment by DrBlackross** [comment]
hmmmm....
after removing blitzapi (webgui)
this few by the screen.

dialogcancel(0) (19)
Blitz API + webUI settings changed ..
# UNINSTALL Web API
Failed to stop blitzapi.service: Unit blitzapi.service not loaded.
Failed to disable unit: Unit file blitzapi.service does not exist.
rm: cannot remove '/etc/systemd/system/blitzapi.service': No such file or directory
userdel: user 'blitzapi' does not exist

**Comment by cstenglein** [comment]
@DrBlackross is this still relevant? Closing for now, if it's still relevant, please re-open

**Comment by DrBlackross** [comment]
Honestly i forgot about it, been out of country off and on too much, but it worked fine while i was away. i did upgrade to 1.9 through the menu, still working fine but cant remember how to move funds from chain balance to channel balance lol

btw, did you drop the ltc/lnd node build?

**Comment by DrBlackross** [comment]
BTW, amd64 1.10.0rc1 works (good so far on fresh reinstall) BUT....
 
Err:6 http://archive.raspberrypi.org/debian bullseye InRelease                   
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 82B129927FA3303E

you need to remove out the raspi apt sources /\
i was trying to push liquorix kernel on the "new" setup after it rebooted.

also during new install with old blockchain hdd (and your supplied kernel, i re-imaged the previous main drive with the raspiblitz-amd64-debian-lean.img 1.10.0.rc1) i saw these fly by a few times..

/home/admin/config.scripts/bonus.bos.sh: line 213: cd: /home/bos/balanceofsatoshis: Permission denied
/home/admin/config.scripts/bonus.thunderhub.sh: line 103: cd: /home/thunderhub/thunderhub: Permission denied
/home/admin/config.scripts/bonus.mempool.sh: line 138: cd: /home/mempool: Permission denied
fatal: could not create work tree dir 'mempool': Permission denied
/home/admin/config.scripts/bonus.mempool.sh: line 140: cd: mempool: Permission denied
fatal: not a git repository (or any of the parent directories): .git
sudo: unable to execute /home/admin/config.scripts/blitz.git-verify.sh: Permission denied

(was kinda weird, ill check it after it mostly settles)

but so far, i like it! (well on the rpi4 it looked cool)

**Comment by DrBlackross** [comment]
had to re-chown everything in /home/admin to current admin, that fixed the permission denied

sudo chown admin:admin -R /home/admin

then went into menu and updated bos....

but thunderhub, mempool, lndg

sudo /home/admin/config.scripts/bonus.lndg.sh off
sudo /home/admin/config.scripts/bonus.thunderhub.sh off
sudo /home/admin/config.scripts/bonus.mempool.sh off
sudo /home/admin/config.scripts/bonus.lit.sh off
sudo /home/admin/config.scripts/bonus.rtl.sh off

then remove their directories out the /home folder
weird part 
root@raspiblitz-amd64-debian-lean:/home/admin# /home/admin/config.scripts/bonus.rtl.sh install
fatal: could not create leading directories of '/home/rtl/RTL': Permission denied
had to make the /home/rtl then chown rtl:rtl -R /home/rtl
and re-run
/home/admin/config.scripts/bonus.rtl.sh install
then it (re)installed

hmmm.... no love. going to roll back to raspiblitz-amd64-image-2023-05-23-e776671 and start totally fresh, and re-import my lnd wallet (maybe)
(i can bitbang and break everything, i swear lol)

**Comment by DrBlackross** [comment]
Heads up, fresh install by imaging with balenaEtcher-1.5.100-x64 of raspiblitz-amd64-image-2023-05-23-e776671.zip (and extra steps to *.img) to the main hdd works great, once the node is fully sync'd i'll try importing the lnd-rescue.

**Comment by DrBlackross** [comment]
and then using the migration file

[raspiblitz.log](https://github.com/user-attachments/files/23569681/raspiblitz.log)

turns out the script didnt like the filenamed "CURRENT-Raspiblitz-BACKUP.tar.gz" from previous mitigation backup of old HD, it wants a file named Raspiblitz-*.targz regardless

**Comment by DrBlackross** [comment]
took a few to get it to take the migration file, i think it worked, but i wont know till the node is done syncing
