### ISSUE TITLE
BlitzAPI: no SSE messages if blocks are syncing

### ISSUE THREAD

**Issue by cstenglein** [raspiblitz/raspiblitz#3255]
Usually, if the blockchain is syncing, the WebUI shows a Syncscreen.

My Raspiblitz was at 100%, but due to the load, had to catch up with the blockchain.

If the blockchain is syncing, no messages arrived over SSE, so there are no updates (not even hardware info etc.)

![image](https://user-images.githubusercontent.com/9399034/181690785-c7fff9f8-2413-422f-bd81-962e120168ad.png)

**Comment by rootzoll** [comment]
The state in the redis is changed on sync (thats why the SSH & LCD is changing) but I think the API does not reflect monitor this - @fusion44 is this correct? Do we wanna optimize this vor v1.9?

**Comment by rootzoll** [comment]
To recheck during ReleaseCandidate phase of v1.9 (putting on final testing) - also try to find a way to reproduce the szenario.

**Comment by cstenglein** [comment]
@fusion44 Issue still appears currently.

I have CLN syncing currently, so it shouldn't let me into the webUI, but it did.

Weird thing is, I only get `btc_info` and `system_startup_info` messages, not the others. 

![grafik](https://github.com/raspiblitz/raspiblitz/assets/9399034/4d6e00fe-8047-4b08-827c-18b01cc2de2a)

**Comment by rootzoll** [comment]
@cstenglein & @fusion44 what was the status of this issue - is it still relevant?

**Comment by cstenglein** [comment]
Not sure since it's hard to reproduce.

We can close this and re-open if needed if you like.
