### ISSUE TITLE
amd64 image does not work with already used data ssd

### ISSUE THREAD

**Issue by wchancao** [raspiblitz/raspiblitz#3257]
I want to swith my Raspiblitz 1.7.2 from raspberry pi to a pc with core i5 cpu and 8gb of ram. Following @openoms instructions i setup a new node with the pc, everything went well, started syncing blockchain for couple of hours so i stop it. Flashed the os ssd again and connected the data ssd to the pc, but now it doesn't work, it keeps rebooting 5 seconds after i type the admin password. This is what raspiblitz.log says

![IMG_20220729_113624_143](https://user-images.githubusercontent.com/488773/181794576-a4c52469-1fcb-421a-9e4b-927be769438a.jpg)

I'll try to connect the data ssd via usb and see if works.

UPDATE:
Connecting via usb doesnt work
Switching SATA ports doesnt work
Booting without connecting to the monitor doesnt work
Its something in the system init script that is not allowing the initial setup with an already used data disk connected

**Comment by cstenglein** [comment]
@wchancao is this still relevant? Closing for now, if it's still relevant, please re-open
