### ISSUE TITLE
Link to Mempool didn't work anymore after update from v1.7.1 to v1.8.0

### ISSUE THREAD

**Issue by rene78** [raspiblitz/raspiblitz#3259]
Steps:

1. Updated RaspiBlitz from 1.7.1 to v1.8.0
2. Tried to open mempool.space but realized that url has changed to a different IP address
3. Tried to open the new url but the request timed out
4. Then I went to the new webinterface and uninstalled the mempool.space app
5. Tried to reinstall within the webinterface but installation failed
6. Installation via the SSH menu suceeded then and everything works as before

Hardware: RaspiBlitz with metal case and 4GB RAM

**Comment by rootzoll** [comment]
I think we need better error reporting on WebUI installs to see what goes wrong there. At least mempool app install to be retested - see if can be reproduced.

**Comment by rootzoll** [comment]
better error reporting will be done in #3318 - closing this issue.
