### ISSUE TITLE
Webinterface doesn't receive data from the API

### ISSUE THREAD

**Issue by freerko** [raspiblitz/raspiblitz#3262]
Hi,

I've set up a new RaspiBlitz v1.8.0 on a Raspi4 with 8GB of RAM. I am able to login to the new web interface, but only see static stuff and spinning wheels:
<img width="1421" alt="Bildschirmfoto 2022-07-30 um 14 16 03" src="https://user-images.githubusercontent.com/22474172/181913869-c191098d-4fd5-4fa9-b0fb-45ed50c77d8d.png">

Sometimes its just a spinning wheel (and after 10 minutes or so (!) it finally turns into the screenshot above):
![Bildschirmfoto 2022-07-30 um 14 25 55](https://user-images.githubusercontent.com/22474172/181914153-bde03dcb-a112-407d-ae00-d16d77d1bc15.png)

In the settings, there is no information on RaspiBlitz or Blitz-API versions but the Reboot button works, so there has to be some communication to the API (or does that use a different connection?)
<img width="826" alt="Bildschirmfoto 2022-07-30 um 14 16 17" src="https://user-images.githubusercontent.com/22474172/181913933-f48742c2-b8f5-4fb8-8222-5e6c2bb301e8.png">

After a reboot its still the same. 

The Blitz_API seems to be running:
> root@raspberrypi:~# ps aux | grep api | grep -v grep
> blitzapi     783  2.2  0.7 929144 29628 ?        Ssl  13:03   0:46 /usr/bin/python -m uvicorn app.main:app --port 11111 --host=0.0.0.0 --root-path /api

But with this via SSH on the RaspiBlitz:

> curl --header "Content-Type: application/json" \
>  --request POST \
>  --data '{"password":"mypassword"}' \
>  http://127.0.0.1:11111/system/login

I get `{"detail":"Not Found"}`, with `curl -N http://127.0.0.1:11111/v1/bitcoin/getblockchaininfo` the same Not Found

I can't find any logfile for the blitz_api. How can I debug this further?

**Comment by 3773** [comment]
I have the same problem. I have already done the patch update.

**Comment by rootzoll** [comment]
@cstenglein can you help debug this?

**Comment by cstenglein** [comment]
I think the path should be `http://127.0.0.1:11111/api/v1/bitcoin/getblockchaininfo`

(Note the `/api ` path)

Otherwise I can look into It more next weekend.

**Comment by cstenglein** [comment]
@freerko Maybe try to check what happened with the blitzAPI:

`sudo journalctl | grep 'BlitzBackendAPI' -A 100`

In the RaspiBlitz Telegram someone had a python issue which resulted in the api not installing a dependency correctly.

**Comment by freerko** [comment]
Your command didn't return anything as the logs where full of other stuff from the last three weeks. 
Weird thing is, after a reboot now the API and Webinterface run without issues for the first time. I didn't change anything and already did several reboots after I've set it up three weeks ago, but now after one other reboot it just works 🤷‍♂️

**Comment by cstenglein** [comment]
@rootzoll should we investigate that or leave it closed?

**Comment by rootzoll** [comment]
I

**Comment by rootzoll** [comment]
I reopned so that we can focus for v1.8.1 to improve on this again.

**Comment by ChuckNorrison** [comment]
Same behaviour for me. Iam running v1.8.0 on clearnet without TOR. Using lnd and not c-lightning.

`sudo ./blitz.web.api.sh update-code` results with some errors

> Building wheels for collected packages: psutil
>   Building wheel for psutil (setup.py) ... done
>   Created wheel for psutil: filename=psutil-5.9.2-cp39-cp39-linux_aarch64.whl size=284003 sha256=cf93688db71a43242f64f178c89598d06ab8df8aa62a00c5d329b26861f746f8
>   Stored in directory: /root/.cache/pip/wheels/90/b2/61/285f7409a9dd2ffa1aa0684602a619f61b4c7b41c7ba7ba7e3
> Successfully built psutil
> Installing collected packages: wrapt, urllib3, typing-extensions, tenacity, sniffio, setuptools, pyzmq, python-json-logger, psutil, protobuf, idna, h11, grpcio, frozenlist, charset-normalizer, certifi, attrs, yarl, uvicorn, requests, pydantic, grpcio-tools, googleapis-common-protos, deprecated, aioredis, redis, fastapi, fastapi-plugins
>   Attempting uninstall: wrapt
>     Found existing installation: wrapt 1.12.1
> ERROR: Cannot uninstall 'wrapt'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
> --- Logging error ---
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/dist-packages/pip/_internal/utils/logging.py", line 177, in emit
>     self.console.print(renderable, overflow="ignore", crop=False, style=style)
>   File "/usr/local/lib/python3.9/dist-packages/pip/_vendor/rich/console.py", line 1752, in print
>     extend(render(renderable, render_options))
>   File "/usr/local/lib/python3.9/dist-packages/pip/_vendor/rich/console.py", line 1390, in render
>     for render_output in iter_render:
>   File "/usr/local/lib/python3.9/dist-packages/pip/_internal/utils/logging.py", line 134, in __rich_console__
>     for line in lines:
>   File "/usr/local/lib/python3.9/dist-packages/pip/_vendor/rich/segment.py", line 245, in split_lines
>     for segment in segments:
>   File "/usr/local/lib/python3.9/dist-packages/pip/_vendor/rich/console.py", line 1368, in render
>     renderable = rich_cast(renderable)
>   File "/usr/local/lib/python3.9/dist-packages/pip/_vendor/rich/protocol.py", line 36, in rich_cast
>     renderable = cast_method()
>   File "/usr/local/lib/python3.9/dist-packages/pip/_internal/self_outdated_check.py", line 130, in __rich__
>     pip_cmd = get_best_invocation_for_this_pip()
>   File "/usr/local/lib/python3.9/dist-packages/pip/_internal/utils/entrypoints.py", line 58, in get_best_invocation_for_this_pip
>     if found_executable and os.path.samefile(
>   File "/usr/lib/python3.9/genericpath.py", line 101, in samefile
>     s2 = os.stat(f2)
> FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/pip3.9'
> Call stack:
>   File "/usr/local/bin/pip", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.9/dist-packages/pip/_internal/cli/main.py", line 70, in main
>     return command.main(cmd_args)
>   File "/usr/local/lib/python3.9/dist-packages/pip/_internal/cli/base_command.py", line 101, in main
>     return self._main(args)
>   File "/usr/local/lib/python3.9/dist-packages/pip/_internal/cli/base_command.py", line 223, in _main
>     self.handle_pip_version_check(options)
>   File "/usr/local/lib/python3.9/dist-packages/pip/_internal/cli/req_command.py", line 148, in handle_pip_version_check
>     pip_self_version_check(session, options)
>   File "/usr/local/lib/python3.9/dist-packages/pip/_internal/self_outdated_check.py", line 237, in pip_self_version_check
>     logger.info("[present-rich] %s", upgrade_prompt)
>   File "/usr/lib/python3.9/logging/__init__.py", line 1442, in info
>     self._log(INFO, msg, args, **kwargs)
>   File "/usr/lib/python3.9/logging/__init__.py", line 1585, in _log
>     self.handle(record)
>   File "/usr/lib/python3.9/logging/__init__.py", line 1595, in handle
>     self.callHandlers(record)
>   File "/usr/lib/python3.9/logging/__init__.py", line 1657, in callHandlers
>     hdlr.handle(record)
>   File "/usr/lib/python3.9/logging/__init__.py", line 948, in handle
>     self.emit(record)
>   File "/usr/local/lib/python3.9/dist-packages/pip/_internal/utils/logging.py", line 179, in emit
>     self.handleError(record)
> Message: '[present-rich] %s'
> Arguments: (UpgradePrompt(old='22.1.2', new='22.2.2'),)
> \# BRANCH ---> main
> \# old commit -> a4e9f7bf23e4b30e67aef3fb3c0208c11a2f1cd3
> \# new commit -> bd19c41fd55648efd4440fcc93c7d6928ef35f4b
> \# blitzapi updates and restarted

`sudo journalctl -fu blitzapi` results

> raspberrypi python[1712724]: WARNING:root:Key 'tor_web_addr' not found in Redis DB.

The menu way:

> chmod: cannot access '/home/bitcoin/.lightning/bitcoin': No such file or directory
> chmod: cannot access '/home/bitcoin/.lightning/bitcoin/lightning-rpc': No such file or directory
> cat: /home/bitcoin/.lightning/config: No such file or directory
> tee: /home/bitcoin/.lightning/config: No such file or directory
> rpc-file-mode=0660
> Cloning into '/home/blitzapi/blitz_api'...

After installation from menu was done, there was no service blitzapi 

`sudo systemctl status blitzapi`

> Unit blitzapi.service could not be found

So i tried to pip install manually

```
cd /home/blitzapi/blitz_api
pip install -r requirements.txt
```
Results with:

> Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
> Ignoring cffi: markers 'python_version >= "3.9" and python_version < "4.0" and implementation_name == "pypy"' don't match your environment
> Ignoring colorama: markers 'python_version >= "3.9" and python_version < "4.0" and platform_system == "Windows"' don't match your environment
> Ignoring py: markers 'python_version >= "3.9" and python_version < "4.0" and implementation_name == "pypy"' don't match your environment
> Ignoring pycparser: markers 'python_version >= "3.9" and python_version < "4.0" and implementation_name == "pypy"' don't match your environment
> [...]
> FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/pip3.9'

so i ended up here
![image](https://user-images.githubusercontent.com/2964146/194321282-ad1e84eb-052a-440c-bde0-6d55b027bb96.png)

**Comment by rootzoll** [comment]
> raspberrypi python[1712724]: WARNING:root:Key 'tor_web_addr' not found in Redis DB.

@fusion44 can this be a reason of the API falling into an excpetion and not delivering data

**Comment by fusion44** [comment]
If the backend doesn't catch the error properly it might crash. Can't check right now though. Will do tomorrow.

**Comment by fusion44** [comment]
Hmm no, that's not it. The code just returns an empty string if a key is not found:

```python
async def redis_get(key: str) -> str:
    v = await redis_plugin.redis.get(key)

    if not v:
        logging.warning(f"Key '{key}' not found in Redis DB.")
        return ""

    return v.decode("utf-8")
```

From @ChuckNorrison's the logs above:
```
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/pip3.9'
```
Maybe a system level Python problem?

**Comment by ChuckNorrison** [comment]
python works for me, but the file pip3.9 does not exist on my system

> admin@192.168.8.160:~ ₿ python --version
> Python 3.9.2

> admin@192.168.8.160:~ ₿ pip --version
> pip 22.1.2 from /usr/local/lib/python3.9/dist-packages/pip (python 3.9)

Reproduce this error with 
> sudo pip3 list

// fixed with
> sudo cp /home/admin/.local/bin/pip3.9 /usr/bin/
> sudo python3 -m pip install --upgrade pip
> sudo pip install wrapt --upgrade --ignore-installed

From blitz menu install WebUI. Blitz service is available again and stucks with loading animations. Here ist the journal output from blitzapi

> Oct 09 22:34:08 raspberrypi python[1645513]: INFO:     127.0.0.1:43290 - "GET /setup/status HTTP/1.0" 500 Internal Server Error
> Oct 09 22:34:08 raspberrypi python[1645513]: ERROR:    Exception in ASGI application
> Oct 09 22:34:08 raspberrypi python[1645513]: Traceback (most recent call last):
> Oct 09 22:34:08 raspberrypi python[1645513]:   File "/usr/local/lib/python3.9/dist-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
> Oct 09 22:34:08 raspberrypi python[1645513]:     result = await app(  # type: ignore[func-returns-value]
> Oct 09 22:34:08 raspberrypi python[1645513]:   File "/usr/local/lib/python3.9/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
> Oct 09 22:34:08 raspberrypi python[1645513]:     return await self.app(scope, receive, send)
> Oct 09 22:34:08 raspberrypi python[1645513]:   File "/usr/local/lib/python3.9/dist-packages/fastapi/applications.py", line 269, in __call__
> Oct 09 22:34:08 raspberrypi python[1645513]:     await super().__call__(scope, receive, send)
> Oct 09 22:34:08 raspberrypi python[1645513]:   File "/usr/local/lib/python3.9/dist-packages/starlette/applications.py", line 124, in __call__
> Oct 09 22:34:08 raspberrypi python[1645513]:     await self.middleware_stack(scope, receive, send)
> Oct 09 22:34:08 raspberrypi python[1645513]:   File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 184, in __call__
> Oct 09 22:34:08 raspberrypi python[1645513]:     raise exc
> Oct 09 22:34:08 raspberrypi python[1645513]:   File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 162, in __call__
> Oct 09 22:34:08 raspberrypi python[1645513]:     await self.app(scope, receive, _send)
> Oct 09 22:34:08 raspberrypi python[1645513]:   File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/cors.py", line 84, in __call__
> Oct 09 22:34:08 raspberrypi python[1645513]:     await self.app(scope, receive, send)
> Oct 09 22:34:08 raspberrypi python[1645513]:   File "/usr/local/lib/python3.9/dist-packages/starlette/exceptions.py", line 93, in __call__
> Oct 09 22:34:08 raspberrypi python[1645513]:     raise exc
> Oct 09 22:34:08 raspberrypi python[1645513]:   File "/usr/local/lib/python3.9/dist-packages/starlette/exceptions.py", line 82, in __call__
> Oct 09 22:34:08 raspberrypi python[1645513]:     await self.app(scope, receive, sender)
> Oct 09 22:34:08 raspberrypi python[1645513]:   File "/usr/local/lib/python3.9/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
> Oct 09 22:34:08 raspberrypi python[1645513]:     raise e
> Oct 09 22:34:08 raspberrypi python[1645513]:   File "/usr/local/lib/python3.9/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
> Oct 09 22:34:08 raspberrypi python[1645513]:     await self.app(scope, receive, send)
> Oct 09 22:34:08 raspberrypi python[1645513]:   File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 670, in __call__
> Oct 09 22:34:08 raspberrypi python[1645513]:     await route.handle(scope, receive, send)
> Oct 09 22:34:08 raspberrypi python[1645513]:   File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 418, in handle
> Oct 09 22:34:08 raspberrypi python[1645513]:     await self.app(scope, receive, send)
> Oct 09 22:34:08 raspberrypi python[1645513]:   File "/usr/local/lib/python3.9/dist-packages/fastapi/applications.py", line 269, in __call__
> Oct 09 22:34:08 raspberrypi python[1645513]:     await super().__call__(scope, receive, send)
> Oct 09 22:34:08 raspberrypi python[1645513]:   File "/usr/local/lib/python3.9/dist-packages/starlette/applications.py", line 124, in __call__
> Oct 09 22:34:08 raspberrypi python[1645513]:     await self.middleware_stack(scope, receive, send)
> Oct 09 22:34:08 raspberrypi python[1645513]:   File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 184, in __call__
> Oct 09 22:34:08 raspberrypi python[1645513]:     raise exc
> Oct 09 22:34:08 raspberrypi python[1645513]:   File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 162, in __call__
> Oct 09 22:34:08 raspberrypi python[1645513]:     await self.app(scope, receive, _send)
> Oct 09 22:34:08 raspberrypi python[1645513]:   File "/usr/local/lib/python3.9/dist-packages/starlette/exceptions.py", line 93, in __call__
> Oct 09 22:34:08 raspberrypi python[1645513]:     raise exc
> Oct 09 22:34:08 raspberrypi python[1645513]:   File "/usr/local/lib/python3.9/dist-packages/starlette/exceptions.py", line 82, in __call__
> Oct 09 22:34:08 raspberrypi python[1645513]:     await self.app(scope, receive, sender)
> Oct 09 22:34:08 raspberrypi python[1645513]:   File "/usr/local/lib/python3.9/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
> Oct 09 22:34:08 raspberrypi python[1645513]:     raise e
> Oct 09 22:34:08 raspberrypi python[1645513]:   File "/usr/local/lib/python3.9/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
> Oct 09 22:34:08 raspberrypi python[1645513]:     await self.app(scope, receive, send)
> Oct 09 22:34:08 raspberrypi python[1645513]:   File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 670, in __call__
> Oct 09 22:34:08 raspberrypi python[1645513]:     await route.handle(scope, receive, send)
> Oct 09 22:34:08 raspberrypi python[1645513]:   File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 266, in handle
> Oct 09 22:34:08 raspberrypi python[1645513]:     await self.app(scope, receive, send)
> Oct 09 22:34:08 raspberrypi python[1645513]:   File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 65, in app
> Oct 09 22:34:08 raspberrypi python[1645513]:     response = await func(request)
> Oct 09 22:34:08 raspberrypi python[1645513]:   File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 231, in app
> Oct 09 22:34:08 raspberrypi python[1645513]:     raw_response = await run_endpoint_function(
> Oct 09 22:34:08 raspberrypi python[1645513]:   File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 160, in run_endpoint_function
> Oct 09 22:34:08 raspberrypi python[1645513]:     return await dependant.call(**values)
> Oct 09 22:34:08 raspberrypi python[1645513]:   File "./app/routers/setup.py", line 31, in get_status
> Oct 09 22:34:08 raspberrypi python[1645513]:     setupPhase = await redis_get("setupPhase")
> Oct 09 22:34:08 raspberrypi python[1645513]:   File "./app/utils.py", line 64, in redis_get
> Oct 09 22:34:08 raspberrypi python[1645513]:     return v.decode("utf-8")
> Oct 09 22:34:08 raspberrypi python[1645513]: AttributeError: 'str' object has no attribute 'decode'
> Oct 09 22:34:08 raspberrypi python[1645513]: ERROR:uvicorn.error:Exception in ASGI application

@fusion44 is this helpful?

**Comment by ChuckNorrison** [comment]
Another error found in the blitzapi journal with the same reason

> Oct 09 23:26:20 raspberrypi systemd[1]: Started BlitzBackendAPI.
> Oct 09 23:26:27 raspberrypi python[2134895]: INFO:     Started server process [2134895]
> Oct 09 23:26:27 raspberrypi python[2134895]: INFO:uvicorn.error:Started server process [2134895]
> Oct 09 23:26:27 raspberrypi python[2134895]: INFO:     Waiting for application startup.
> Oct 09 23:26:27 raspberrypi python[2134895]: INFO:uvicorn.error:Waiting for application startup.
> Oct 09 23:26:27 raspberrypi python[2134895]: INFO:     Application startup complete.
> Oct 09 23:26:27 raspberrypi python[2134895]: INFO:uvicorn.error:Application startup complete.
> Oct 09 23:26:27 raspberrypi python[2134895]: INFO:     Uvicorn running on http://0.0.0.0:11111 (Press CTRL+C to quit)
> Oct 09 23:26:27 raspberrypi python[2134895]: INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:11111 (Press CTRL+C to quit)
> Oct 09 23:26:27 raspberrypi python[2134895]: ERROR:asyncio:Task exception was never retrieved
> Oct 09 23:26:27 raspberrypi python[2134895]: future: <Task finished name='Task-7' coro=<_handle_gather_hardware_info() done, defined at ./app/repositories/system.py:170> exception=AttributeError("'str' object has no attribute 'decode'")>
> Oct 09 23:26:27 raspberrypi python[2134895]: Traceback (most recent call last):
> Oct 09 23:26:27 raspberrypi python[2134895]:   File "./app/repositories/system.py", line 173, in _handle_gather_hardware_info
> Oct 09 23:26:27 raspberrypi python[2134895]:     info = await get_hardware_info()
> Oct 09 23:26:27 raspberrypi python[2134895]:   File "./app/repositories/system.py", line 117, in get_hardware_info
> Oct 09 23:26:27 raspberrypi python[2134895]:     return await get_hardware_info_impl()
> Oct 09 23:26:27 raspberrypi python[2134895]:   File "./app/repositories/hardware_impl/raspiblitz.py", line 14, in get_hardware_info_impl
> Oct 09 23:26:27 raspberrypi python[2134895]:     loads = (await redis_get("system_cpu_load")).split(",")
> Oct 09 23:26:27 raspberrypi python[2134895]:   File "./app/utils.py", line 64, in redis_get
> Oct 09 23:26:27 raspberrypi python[2134895]:     return v.decode("utf-8")
> Oct 09 23:26:27 raspberrypi python[2134895]: AttributeError: 'str' object has no attribute 'decode'
> Oct 09 23:26:36 raspberrypi python[2134895]: INFO:     127.0.0.1:43368 - "GET /lightning/list-all-tx?reversed=true HTTP/1.0" 200 OK

**Comment by ChuckNorrison** [comment]
Reflashed my sdcard with v1.8.0 and my WebUI works. Just one box with loading animation left. 

Logs keeps printing (created a pull request https://github.com/fusion44/blitz_api/pull/154)
> WARNING:root:Key 'tor_web_addr' not found in Redis DB.

![image](https://user-images.githubusercontent.com/2964146/194845753-5e62aea2-f138-4163-b82d-cbac0d8d6f59.png)

**Comment by muraschal** [comment]
I have the same error after migration to a proxmox vm, any ideas on how to fix this?

Proxmox Setup:
- Debian 11.5
- 1TB SSD OS // 1 TB SS Blockchain
thanks a lot guys! @cercatrova21 

[https://l.termbin.com/8hl6p](https://l.termbin.com/8hl6p)

![image](https://user-images.githubusercontent.com/4194026/195272300-63e47e6e-8ee2-4124-8122-3e709290bfe3.png)

![image](https://user-images.githubusercontent.com/4194026/195318906-d26eb571-4da8-4c24-b303-f981461378ea.png)

**Comment by muraschal** [comment]
Update:

After a RaspiBlitz (Version 1.8.0b with lnd 0.15.2) Cleaninstall on Ubuntu, the Error is still persistent.
I'cant be the only one having this issues, can i manually fix this with a workaround?

thanks

**Comment by cstenglein** [comment]
@ChuckNorrison the issue with the one loading box is in the webUI, I created an issue for that: https://github.com/cstenglein/raspiblitz-web/issues/493

**Comment by muraschal** [comment]
after debugging session with @cstenglein we did not find a solution... 

![image](https://user-images.githubusercontent.com/4194026/195834212-4f1f74d0-4ec7-4eab-ba62-a052c4d5aabe.png)
![image](https://user-images.githubusercontent.com/4194026/195834787-748e8b02-3e5d-41b8-b3f1-3de8105b0e14.png)

**Comment by benjamin-wilson** [comment]
Clean Proxmox 1.8 CLN install:

```
Oct 14 08:04:03 debian python[3531]: ERROR:uvicorn.error:Exception in ASGI application
Oct 14 08:04:03 debian python[3531]: Traceback (most recent call last):
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
Oct 14 08:04:03 debian python[3531]:     result = await app(  # type: ignore[func-returns-value]
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
Oct 14 08:04:03 debian python[3531]:     return await self.app(scope, receive, send)
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/fastapi/applications.py", line 269, in __call__
Oct 14 08:04:03 debian python[3531]:     await super().__call__(scope, receive, send)
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/starlette/applications.py", line 124, in __call__
Oct 14 08:04:03 debian python[3531]:     await self.middleware_stack(scope, receive, send)
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 184, in __call__
Oct 14 08:04:03 debian python[3531]:     raise exc
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 162, in __call__
Oct 14 08:04:03 debian python[3531]:     await self.app(scope, receive, _send)
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/cors.py", line 84, in __call__
Oct 14 08:04:03 debian python[3531]:     await self.app(scope, receive, send)
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/starlette/exceptions.py", line 93, in __call__
Oct 14 08:04:03 debian python[3531]:     raise exc
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/starlette/exceptions.py", line 82, in __call__
Oct 14 08:04:03 debian python[3531]:     await self.app(scope, receive, sender)
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
Oct 14 08:04:03 debian python[3531]:     raise e
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
Oct 14 08:04:03 debian python[3531]:     await self.app(scope, receive, send)
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 670, in __call__
Oct 14 08:04:03 debian python[3531]:     await route.handle(scope, receive, send)
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 418, in handle
Oct 14 08:04:03 debian python[3531]:     await self.app(scope, receive, send)
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/fastapi/applications.py", line 269, in __call__
Oct 14 08:04:03 debian python[3531]:     await super().__call__(scope, receive, send)
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/starlette/applications.py", line 124, in __call__
Oct 14 08:04:03 debian python[3531]:     await self.middleware_stack(scope, receive, send)
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 184, in __call__
Oct 14 08:04:03 debian python[3531]:     raise exc
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 162, in __call__
Oct 14 08:04:03 debian python[3531]:     await self.app(scope, receive, _send)
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/starlette/exceptions.py", line 93, in __call__
Oct 14 08:04:03 debian python[3531]:     raise exc
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/starlette/exceptions.py", line 82, in __call__
Oct 14 08:04:03 debian python[3531]:     await self.app(scope, receive, sender)
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
Oct 14 08:04:03 debian python[3531]:     raise e
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
Oct 14 08:04:03 debian python[3531]:     await self.app(scope, receive, send)
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 670, in __call__
Oct 14 08:04:03 debian python[3531]:     await route.handle(scope, receive, send)
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 266, in handle
Oct 14 08:04:03 debian python[3531]:     await self.app(scope, receive, send)
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 65, in app
Oct 14 08:04:03 debian python[3531]:     response = await func(request)
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 231, in app
Oct 14 08:04:03 debian python[3531]:     raw_response = await run_endpoint_function(
Oct 14 08:04:03 debian python[3531]:   File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 160, in run_endpoint_function
Oct 14 08:04:03 debian python[3531]:     return await dependant.call(**values)
Oct 14 08:04:03 debian python[3531]:   File "./app/routers/setup.py", line 31, in get_status
Oct 14 08:04:03 debian python[3531]:     setupPhase = await redis_get("setupPhase")
Oct 14 08:04:03 debian python[3531]:   File "./app/utils.py", line 64, in redis_get
Oct 14 08:04:03 debian python[3531]:     return v.decode("utf-8")
Oct 14 08:04:03 debian python[3531]: AttributeError: 'str' object has no attribute 'decode'
```

**Comment by fusion44** [comment]
> Clean Proxmox 1.8 CLN install:
> 
> ```
> Oct 14 08:04:03 debian python[3531]: ERROR:uvicorn.error:Exception in ASGI application
> Oct 14 08:04:03 debian python[3531]: Traceback (most recent call last):
> line 78, in __call__
> ...
> Oct 14 08:04:03 debian python[3531]:     return await dependant.call(**values)
> Oct 14 08:04:03 debian python[3531]:   File "./app/routers/setup.py", line 31, in get_status
> Oct 14 08:04:03 debian python[3531]:     setupPhase = await redis_get("setupPhase")
> Oct 14 08:04:03 debian python[3531]:   File "./app/utils.py", line 64, in redis_get
> Oct 14 08:04:03 debian python[3531]:     return v.decode("utf-8")
> Oct 14 08:04:03 debian python[3531]: AttributeError: 'str' object has no attribute 'decode'
> ```

Hmm this looks unrelated to the original SSE data connection issue. Was there a warning (similar to `Key 'xxx' not found in Redis DB.` printed in the logs before this error message?

**Comment by benjamin-wilson** [comment]
No mentions of `Redis` in the logs

**Comment by ChuckNorrison** [comment]
@fusion44 to reproduce please uninstall the web ui + api from blitz menu and install again.

**Comment by ChuckNorrison** [comment]
This will fix the issue
https://github.com/fusion44/blitz_api/pull/159
