### ISSUE TITLE
LND StaticChannelBackup USB Drive wrong about the number of usb devices

### ISSUE THREAD

**Issue by DocBrown101** [raspiblitz/raspiblitz#3266]
I am trying to enable the "LND StaticChannelBackup USB Drive" function on version 1.8, but I cannot.
![image](https://user-images.githubusercontent.com/11892773/182043548-e52572a4-579c-44f0-b16a-8a2565019e2c.png)

I have only one USB stick connected, but I still get this error message:
![image](https://user-images.githubusercontent.com/11892773/182043561-996dbbd2-619b-4f03-a610-5df9aebc36e0.png)

I did a completely new installation without restoring anything.

This is what lsblk displays:
![image](https://user-images.githubusercontent.com/11892773/182043640-1a07bf52-89c9-4d01-81cc-ab5b98fbc744.png)

**Comment by rootzoll** [comment]
Will look into this for the next release.

**Comment by sunboyy** [comment]
I also get this error. I think that zram is causing the problem.

**Comment by rootzoll** [comment]
Should now work again with v1.9ö0 release. Final testing for Release Candidate.
