### ISSUE TITLE
Strange bug: Helipad db is owned by sphinxrelay user after upgrading to v1.8.0

### ISSUE THREAD

**Issue by SpencerPearson** [raspiblitz/raspiblitz#3268]
When I opened up Helipad after the 1.8.0 upgrade I was not seeing any boosts post-upgrade. Logs were saying that the Helipad service was encountering an error trying to write to a read-only database. The problem was somehow after upgrading, the Helipad db was owned by the sphinxrelay user. What I did to fix:

`sudo systemctl stop helipad`
`sudo chown helipad /mnt/hdd/app-data/helipad/database.db`
`sudo systemctl start helipad`

Unsure if stopping and starting the service again is technically necessary, but after these steps I refreshed the browser and was able to see the new post-upgrade boosts at localip:2112 like normal!

**Comment by rootzoll** [comment]
Ok tested - will now be fixed for next release.
