### ISSUE TITLE
Updated API version ready?

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#3272]
Plan is to deliver with API version 0.6.0
https://github.com/fusion44/blitz_api/milestone/2

**Comment by rootzoll** [comment]
We agreed on having similar branch namings for releases (v1.8, v1.9, v1.10, ..) also in API & WebUI repos like on RaspiBlitz repo to keep releases patchable.

@fusion44 please create a `v1.9` branch on blitz_api repo merged will all the code you have ready for the next release. I will adapt the api install script on the raspiblitz side to use such release branches.

**Comment by rootzoll** [comment]
as soon as `refactor_system` is renamed to `dev` and `blitz-v1.9` is available - merge: https://github.com/rootzoll/raspiblitz/pull/3546

**Comment by rootzoll** [comment]
To be fixed for rc2:
- [ ] https://github.com/fusion44/blitz_api/issues/184

**Comment by cstenglein** [comment]
Should be done => closed
