### ISSUE TITLE
Updated WebUI ready?

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#3273]
Plan is to deliver with at least v1.0.1
https://github.com/cstenglein/raspiblitz-web/milestone/3

**Comment by rootzoll** [comment]
We agreed on having similar branch namings for releases (v1.8, v1.9, v1.10, ..) also in API & WebUI repos like on RaspiBlitz repo to keep releases patchable.

@cstenglein please create a v1.9 branch on raspiblitz-web repo merged will all the code you have ready for the next release. I will adapt the webui install script on the raspiblitz side to use such release branches.

**Comment by cstenglein** [comment]
Done: `release/v1.9`

See https://github.com/cstenglein/raspiblitz-web/branches

Regarding merges: Some PRs still require functionality from the API like https://github.com/cstenglein/raspiblitz-web/pull/527
Should I merge that as well?
