### ISSUE TITLE
CLN v0.12.1 update

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#3274]
This is to document an issues and changes needed related to the update.
Needed to use for example commando/runes and poncho (#3269)

update CLN to the latest rc found in https://github.com/ElementsProject/lightning/tags eg. 'v0.12.0rc1':
```
# upgrade pip first
sudo pip install --upgrade pip
# update CLN
config.scripts/cl.install.sh update v0.12.0rc1
```

**Comment by BitromNO** [comment]
when running v0.12.0rc1 i cannot get it to run in clearnet, unchecked tor in the menu but it still advertises onion adress.

**Comment by openoms** [comment]
Note that rc2 is now available.

>i cannot get it to run in clearnet, unchecked tor in the menu but it still advertises onion adress.

this is unrelated to the CLN version. You will need to set the cln config manually.
See https://lightning.readthedocs.io/TOR.html for the different options.

**Comment by rootzoll** [comment]
done in other issue. closing.
