### ISSUE TITLE
Status screen is disarranged

### ISSUE THREAD

**Issue by status21** [raspiblitz/raspiblitz#3275]
Where the bitcoin version should be there are line brakes and confusing text.
_cache.sh is producing the following output:

/home/admin/_cache.sh meta btc_mainnet_version

value="v23.0.0
Core

Bitcoin
the
from

license,"
initiated=1
lasttouch="1659615339"
outdatesecs="-1"
stillvalid="1"

**Comment by openoms** [comment]
This is solved. Update to v1.8.0 or on v1.7.2 run `patch`.
