### ISSUE TITLE
Default rpcuser: "raspibolt"

### ISSUE THREAD

**Issue by tongokongo** [raspiblitz/raspiblitz#3276]
Hey, the default rpcuser is `raspibolt`, isn't it a bit counterintuitive when there is another project called `raspibolt`? Should it be renamed to `raspiblitz`?

**Comment by rootzoll** [comment]
Using that default rpcuser is a tribute to the RaspiBolt project - on which the RaspiBlitz started on. Its a bit hidden and only more experienced users might notice it ... so I like it to keep it that way as a reminder and story to tell if somebody is noticing like you :)

**Comment by zynos** [comment]
That it is a tribute is really cool! It is a nice easter egg :D

**Comment by tongokongo** [comment]
Thanks, good to know it's deliberate, I thought it was the detail that was omitted ;)
