### ISSUE TITLE
Updating RaspiBlitz to new Version (Bitcoin Core RPC)

### ISSUE THREAD

**Issue by btcpuertorico** [raspiblitz/raspiblitz#3279]
https://github.com/rootzoll/raspiblitz#updating-raspiblitz-to-new-version

_"It is worth noting here that your SSH password will be reset to raspiblitz."_

Also noticed that Bitcoin Core RPC needs to be disabled and re-enabled for it to accept connections again. All clients (Sparrow/Specter) lost connectivity.

**Comment by rootzoll** [comment]
Can you describe more in detail what you mean here? Basically on an update a complete new bitcoin core gets installed with reboots and everything - that clients loose connectivity would be expected if open.

**Comment by btcpuertorico** [comment]
I mean, seems like bitcoin RPC service stopped listening after reboot. No authentication error, just no response.

**Comment by rootzoll** [comment]
Can you spot any error message regarding the RPC startup when you check the bitcoin logs after reboot?

**Comment by cstenglein** [comment]
@giybs372 is the issue still relevant

closing for now, if it still relevant, please re-open the issue. :)
