### ISSUE TITLE
CPU temps don't change in amd64

### ISSUE THREAD

**Issue by wchancao** [raspiblitz/raspiblitz#3283]
The CPU temperatures shown in 00infoBlitz.sh don't change in an amd64 Dell Optiplex 5040, they always stay at 27C and 81F. They work in an amd64 Dell Optiplex 7010. I can get the temps installing lmsensors and running sensors.

**Comment by wchancao** [comment]
Looking through the scripts and googling a little bit, it seems that the correct temp for the cpu is the one displayed as `x86_pkg_temp` in `cat /sys/class/thermal/thermal_zone*/type`
Right now, the script in Raspiblitz is pointing to `/sys/class/thermal/thermal_zone0/temp` which is `acpitz`

**Comment by BitromNO** [comment]
have the same issue on MSI Cubi-N

**Comment by openoms** [comment]
not sure how to provide a solution which works on all hardware, but `lm-sensors` is a good one.
On my Debian laptop:
```
₿ sudo apt install lm-sensors
₿ sensors
iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:        +41.0°C  

pch_skylake-virtual-0
Adapter: Virtual device
temp1:        +43.5°C  

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +46.0°C  (high = +100.0°C, crit = +100.0°C)
Core 0:        +43.0°C  (high = +100.0°C, crit = +100.0°C)
Core 1:        +46.0°C  (high = +100.0°C, crit = +100.0°C)

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +44.0°C  (crit = +128.0°C)

thinkpad-isa-0000
Adapter: ISA adapter
fan1:        3229 RPM
temp1:        +44.0°C  
temp2:            N/A  
temp3:         +0.0°C  
temp4:         +0.0°C  
temp5:         +0.0°C  
temp6:         +0.0°C  
temp7:         +0.0°C  
temp8:         +0.0°C  

BAT0-acpi-0
Adapter: ACPI interface
in0:          17.18 V  
```

and server:
```
₿ sensors
nouveau-pci-0400
Adapter: PCI adapter
GPU core:    862.00 mV (min =  +0.82 V, max =  +1.21 V)
fan1:        2790 RPM
temp1:        +54.0°C  (high = +95.0°C, hyst =  +3.0°C)
                       (crit = +105.0°C, hyst =  +5.0°C)
                       (emerg = +135.0°C, hyst =  +5.0°C)
power1:       18.73 W  (crit =  87.00 mW)

nvme-pci-0500
Adapter: PCI adapter
Composite:    +58.9°C  (low  =  -5.2°C, high = +79.8°C)
                       (crit = +84.8°C)

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +61.0°C  (high = +81.0°C, crit = +91.0°C)
Core 0:        +57.0°C  (high = +81.0°C, crit = +91.0°C)
Core 1:        +56.0°C  (high = +81.0°C, crit = +91.0°C)
Core 2:        +58.0°C  (high = +81.0°C, crit = +91.0°C)
Core 3:        +61.0°C  (high = +81.0°C, crit = +91.0°C)
Core 4:        +61.0°C  (high = +81.0°C, crit = +91.0°C)
Core 5:        +58.0°C  (high = +81.0°C, crit = +91.0°C)

nvme-pci-0700
Adapter: PCI adapter
Composite:    +47.9°C  (low  = -273.1°C, high = +69.8°C)
                       (crit = +79.8°C)
Sensor 1:     +48.9°C  (low  = -273.1°C, high = +65261.8°C)
Sensor 2:     +47.9°C  (low  = -273.1°C, high = +65261.8°C)
Sensor 5:     +62.9°C  (low  = -273.1°C, high = +65261.8°C)
```

**Comment by openoms** [comment]
an other good option is checking the temperature in `htop`:
* run `htop`
* press F2
* Display options
*  [x]    Also show CPU temperature (requires libsensors)

![image](https://user-images.githubusercontent.com/43343391/184717877-a5aa3948-961c-401a-8838-f12514f98bf2.png)

**Comment by BitromNO** [comment]
Ive been using htop for a while. 
What I want is to identify what temp sensor I need, and change it in the script or if there is a conf file or something, so it shows in the info screen.

**Comment by rootzoll** [comment]
@openoms can this issue be closed?

**Comment by openoms** [comment]
Not actionable for now. If someone has a solution for the script it is welcome.

I use htop and Cockpit for a comprehensive dashboard.
