### ISSUE TITLE
[v1.8] Typo in blitz.web.ui.sh

### ISSUE THREAD

**Issue by adevoss** [raspiblitz/raspiblitz#3286]
line 83
`echo "# http://[LOCAIP]"`
should be 
`echo "# http://[LOCALIP]"`

**Comment by rootzoll** [comment]
LOL "LOCAIP" https://www.youtube.com/watch?v=S431bmMVUJw - good catch :)
Fixed with https://github.com/rootzoll/raspiblitz/commit/73f1a4c4719d9003da9092e086a0d3ce4ad424c0
