### ISSUE TITLE
CLN: make the wallet reset more reliable

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#3295]
the old config and channel database can be left
behind when using SEEDRESTORE and FILERESTORE

**Comment by openoms** [comment]
While testing found that

https://github.com/rootzoll/raspiblitz/blob/7074455380eec200bfcaa35cd6cca066fcf9bef3/home.admin/99clRepairMenu.sh#L195

does not delete the files in the directory for an unknown reason to me.
After #3296 the while .lightning/bitcoin directory is deleted and then recreated so the cleanup works.

This behaviour is possibly related to: https://github.com/ElementsProject/lightning/issues/5119

**Comment by openoms** [comment]
@21OrangePill and anyone using `SEEDRESTORE` or `FILERESTORE` on a running CLN node please run `patch` on `v1.8`

**Comment by YBHQ** [comment]
~~~~

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by openoms** [comment]
closing as tested successfully, Will be part of v1.8.1
