### ISSUE TITLE
Add video to WebUI app store for mempool

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#3309]
see: https://twitter.com/mempool/status/1564987890198872065?s=20

**Comment by cstenglein** [comment]
@rootzoll on Twitter they said:

> Feel free to embed it from [@BitcoinTV](https://twitter.com/bitcoinTV)

Should we embed it via link or provide it locally from the raspiblitz?

**Comment by rootzoll** [comment]
When its not too big we should provide it locally as a static file.

**Comment by cstenglein** [comment]
Done
