### ISSUE TITLE
After updating to 1.0, Litecoin mainnet, no prompt to unlock wallet

### ISSUE THREAD

**Issue by goodc0re** [raspiblitz/raspiblitz#331]
After updating to 1.0, Litecoin mainnet, no prompt to unlock wallet, instead this: 

![screenshot 2019-02-19 at 15 27 12](https://user-images.githubusercontent.com/2564288/53022741-14ac9100-345c-11e9-8d8a-fbaab18c708a.png) 

After exiting this screen with control-c, the prompt to unlock lnd appears, some users might not know how to proceed though.

**Comment by rootzoll** [comment]
jikes - other litecoin mainnet updates were reported working - so not sure where this is coming from.

Would recommend the hard way of updating .. make backup of LND data dir, setup fresh Litecoin Blitz 1.0 and then play the backup back - see FAQ: https://github.com/rootzoll/raspiblitz/blob/master/FAQ.md#how-to-backup-my-lightning-node

**Comment by nyxnor** [comment]
pls close this
