### ISSUE TITLE
upgrading issues

### ISSUE THREAD

**Issue by giybs372** [raspiblitz/raspiblitz#3311]
having multiple issues trying to upgrade to 1.8 - the current one is the HDD light continues to flash even after unplugging the network cable, and can no longer ssh into the raspi

**Comment by rootzoll** [comment]
If now after so many days the HDD is still blinking, just cut power and try again with a fresh flashed sd card.

**Comment by cstenglein** [comment]
@giybs372 is the issue still present in 1.9.0?

closing for now, if it still appears, please re-open the issue. :)
