### ISSUE TITLE
Tutorial link is gone 404

### ISSUE THREAD

**Issue by SH4LT1S** [raspiblitz/raspiblitz#3312]
In https://github.com/rootzoll/raspiblitz#only-seed-only-seed-word-list-fallback at `The password A,B,C idea is based on the [RaspiBolt Guide Preparations](https://raspibolt.org/preparations.html#write-down-your-passwords) - check out for more background.` link at https://raspibolt.org/preparations.html#write-down-your-passwords is 404

**Comment by rootzoll** [comment]
Thanks - link is fixed.
