### ISSUE TITLE
Printing debug logs not possible

### ISSUE THREAD

**Issue by merce2** [raspiblitz/raspiblitz#3314]
Hello!

When I try to print the debug logs, I get an error. What is the problem here?

Printing debug logs. Be patient, this should take maximum 2 minutes ..
ls: reading directory '/mnt/hdd': Input/output error
(standard_in) 1: syntax error
/home/admin/config.scripts/blitz.datadrive.sh: line 438: * 1024: syntax error: operand expected (error token is "* 1024")
Redacting ..
# redacting file: /var/cache/raspiblitz/debug.log
https://l.termbin.com/54jy

**Comment by rootzoll** [comment]
Your termbin link shows a working debug file ... so your problem is that its not printed on the console?
