### ISSUE TITLE
Blockchain progress stuck

### ISSUE THREAD

**Issue by merce2** [raspiblitz/raspiblitz#3315]
Hello! I have tried to synch the blockchain and for the first 78 % everything went fine. But now there is no progress anymore and it seems like the raspiblitz is trying to restart all the time.

![Bildschirmfoto 2022-09-10 um 10 58 56](https://user-images.githubusercontent.com/113235607/189476623-5db6976f-c5ff-41c6-852d-f11142b53d4b.png)

Thanks for your help!

**Comment by rootzoll** [comment]
The restarts dont look good. Exit with CTRL+c to the terminal and the execute command `debug` - please post the sections under `*** BLOCKCHAIN (MAINNET) SYSTEMD STATUS ***` to check for errors.

**Comment by cstenglein** [comment]
@merce2  is this still an issue with 1.9.0?

Closing this for now, please re-open if it still persists.
