### ISSUE TITLE
Password WebUI don't work

### ISSUE THREAD

**Issue by Tinus016** [raspiblitz/raspiblitz#3316]
I cant login on the WebUI whit my SSH password, (password A) on the web page. I have already changed the password once but without success, logging in via SSH is possible. I've tried to patch the WebUI it worked but stil not able to log in.

**Comment by cstenglein** [comment]
Do you have special characters except `.` `_` `-` in your password A?

**Comment by Tinus016** [comment]
Nope only <code>-</code>

**Comment by rootzoll** [comment]
@fusion44 we need better debug data on this - what would be the best way to get any possible exceptions happening here? Is there anything for v1.8.1 we can add to capture this better?

**Comment by fusion44** [comment]
I don't want to log the actual password. 
Currently the logging is very basic and not good at all. A redo is on my radar but I don't think I can get it done for 1.8.1.

As a quick hack we can enable debug logging in `main.py` (on the top after the imports). This will enable a more thorough logging, but I do not think it it'll log the reason a password was rejected.

**Comment by rootzoll** [comment]
TODO: make ssh script that test password give more debug details when password is wrong and loop this thru API. Also make the rest of the API code on checking password giving back more debug info in general when password is wrong.

**Comment by deverickapollo** [comment]
Also seeing this bug on my node. @cstenglein -  Any notable areas I should review to debug this issue?

**Comment by tlindi** [comment]
me too

**Comment by cstenglein** [comment]
@hashes4merkle check if the API is running

`sudo service blitzapi status`

**Comment by rootzoll** [comment]
Had a problem with a password containing a `-` on SSH & WebUI on testing RC1 - so todo for RC2:
- [x] check setup & recover passwords with special chars for RC2
