### ISSUE TITLE
API Endpoint to get debug report

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#3322]
- endpoint calls ssh debug report and outputs them for the GUI to display
- more details on backend API
- needs token protected endpoint

**Comment by cstenglein** [comment]
Related issues:

- https://github.com/fusion44/blitz_api/issues/160
- https://github.com/cstenglein/raspiblitz-web/issues/49

**Comment by rootzoll** [comment]
@rootzoll Take care about this: https://github.com/fusion44/blitz_api/issues/160

**Comment by rootzoll** [comment]
OK @fusion44 & @cstenglein fix waiting to be merged.
https://github.com/fusion44/blitz_api/pull/175

**Comment by cstenglein** [comment]
Done, can be tested

**Comment by rootzoll** [comment]
Tested fine with v1.9.0rc4 - closing for release.
