### ISSUE TITLE
Logs filled whole SD Card and (maybe some autoclearing process needed?)

### ISSUE THREAD

**Issue by donovan-ringley** [raspiblitz/raspiblitz#3326]
I have a Raspi with 32GB SD Card. At some point, the node simply stopped working because "No space left on device". 

The full logs was probably not root cause of my issues. I think that for some other reason bitcoind kept restarting filling the logs.

**I would like to ask to add some mechanism that wont allow logs from filling up whole SD card. Probably some autodelete.**

This was quite bad situation for me. I am not home much and my node died when I was abroad so I lost access to it. I was quite unhappy that this happed for such a reason.

**Comment by rootzoll** [comment]
Logs are already on auto-rotate-delete  ... could you spot which log made the problem? Which bonus apps do you have installed?

**Comment by donovan-ringley** [comment]
Sadly I have already deleted them. But I believe it was `/var/log/syslog.1` and maybe one more that I am not able to recall.

**Comment by donovan-ringley** [comment]
My enabled services:
![image](https://user-images.githubusercontent.com/91415449/191988548-e639c362-6ce2-4631-a57c-5d51d55e868a.png)

**Comment by rootzoll** [comment]
TODO: Setup test device with this services, keep running for some days and check for growing logs.

**Comment by rootzoll** [comment]
OK logs are reduced. Open for final testing.
