### ISSUE TITLE
Failed Payment for IP2TOR Subscription w/ CLN

### ISSUE THREAD

**Issue by JMadisonTP** [raspiblitz/raspiblitz#3335]
I am trying to purchase a IP2TOR subscription to open up LnBIts. but the payment keeps failing. here is the information.
my node is funded on base layer and has (1) channel open from LNBig for inbound approx 700k sats. Running CLN.

###### ERROR DETAIL FOR DEBUG #######

Error Short:
payment failed
Shop:
fulmo7x6yvgz6zs2b2ptduvzwevxmizhq23klkenslt5drxx2physlqd.onion
Bridge:
{'id': '32d1662a-a41c-4ccf-9f8f-87c5f47f0341', 'site': 'ip2tor.fulmo.org', 'created_at': '2022-01-14T17:24:54Z', 'modified_at': '2022-09-29T15:15:34Z', 'ip': '172.81.177.248', 'is_enabled': True, 'is_alive': True, 'name': 'nam-tor2', 'is_testnet': False, 'offers_tor_bridges': True, 'tor_bridge_duration': 86400, 'tor_bridge_price_initial': 30000, 'tor_bridge_price_extension': 20000, 'offers_rssh_tunnels': False, 'rssh_tunnel_price': 1000, 'terms_of_service': '-', 'terms_of_service_url': '-', 'ci_date': '2022-09-29T15:15:34Z', 'ci_message': '', 'ci_status': 0, 'owner': 6, 'tor_bridge_duration_hours': 24, 'tor_bridge_price_initial_sats': 30, 'tor_bridge_price_extension_sats': 20}
Error Detail:
{'invoice': 'lnbc300n1p3ntdc8pp52qm2kva6vmdgm2hvfphrjx0ndl39hzdjg7yjqlnnx3vcts39v0qqdzq2p8n5gp3vyerqdn9vsej6vehxvej6dph8ymj6cf48yej6c3sxgmkveryvvexycfscqzpgxqzuysp520ehj0243tuecjzc7pf9r8dlzqdtcjhd6xgfq4gz9x8034xgeqdq9qyyssqvedqac4kcq3lscstrh4ymt5ccwgru3unerm79lu9m2c206rysgsz2djt352rzfgv3atmd0w70unq9p48lytzvlw2y22wg5wzmvlvgfqpdjnl66', 'timestamp': '2022-09-29T15:17:32Z'}

**Comment by JMadisonTP** [comment]
I went and change LnBits funding source to CLN and tried IP2Tor again. Payment is still failing.

**Comment by rootzoll** [comment]
Not sure if IP2Tor will stay active in generel see:
https://github.com/rootzoll/raspiblitz/issues/3417#issuecomment-1310303480

If yes - check also payment with CLN. If not close issue with release.
