### ISSUE TITLE
v1.8 Installing Lightning Terminal results in 502 Bad Gateway for RTL

### ISSUE THREAD

**Issue by skifreak27** [raspiblitz/raspiblitz#3344]
Seen this issue posted elsewhere with different revs but have not discovered a resolution.  Get bad gateway 502 error when trying to log into web GUI for RTL on raspiblitz.  LIT GUI works fine. 

Have tried removing and re-installing RTL multiple times.  Have tried rebooting multiple times. 

When entering 
`sudo service RTL status`

I receive the following error/failure; 

![image](https://user-images.githubusercontent.com/115095796/194095116-b3d614c7-df3a-44d7-9c23-ada6cc8263eb.png)

Seems that RTL is not installing or running correctly.

Have also tried service start and stop to no avail.  Any help would be super appreciated.

**Comment by skifreak27** [comment]
Is this just a dead project or what?

**Comment by jimmymsaliba** [comment]
I'm having a similar issue.  Can access LIT Gui but not the Raspiblitz UI and RTL.

**Comment by jimmymsaliba** [comment]
I ended up fixing mine and it looks like it was related to installing JoinMarket instead of LIT.  After checking the /var/log/nginx/error.log I was getting errors related to JM.  Uninstalled JM and removed the related .conf files in /etc/nginx/sites-enabled/ directory.  Nginx started just fine after that.  Hope this helps!

**Comment by rootzoll** [comment]
Will recheck for v1.9 release

**Comment by rootzoll** [comment]
OK I was nozt able to reproduce this. I installed RTL (for lnd) and then installed LIT and JoinMarket (also JAM) and RTL still works. Maybe this got fixed already. Please this on your side as soon a Release Candidate of v1.9 is avalilable and report back.
