### ISSUE TITLE
SCB backup to USB doesn't work

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#3348]
Having reports of the USB backup option not working due it trying to format the ZRAM partition instead.

Related also to the similar method for CLN  to be implemented #3303

**Comment by rootzoll** [comment]
TODO: to be tested once #3303 is merged

**Comment by rootzoll** [comment]
Testing looks good for LND - havent seen a CLN backup, test when opening/closing channels in RC (also test copies to Nextcloud & sd card)

**Comment by rootzoll** [comment]
#3393 merged - see needed final tests above
