### ISSUE TITLE
Node status stuck at 100% progress. Not moving to menu screen. Info screen loop error

### ISSUE THREAD

**Issue by dannuttall** [raspiblitz/raspiblitz#3358]
After syncing the blockchain, my node is stuck displaying 100%. It's been in this state for 24 hours now. 
![image](https://user-images.githubusercontent.com/25965241/194874958-0bda825f-b682-4deb-a24a-c5f60a9b0faa.png)

It looks the same if I SSH in. If I CTRL+C and enter the menu manually, then look at the status screen, I get the following error:
![image](https://user-images.githubusercontent.com/25965241/194874884-058ccdd1-aa26-416b-b599-28a1c580f884.png)

I installed the RTL web interface and that says the node is fine. 

The above 2 things are slightly annoying but if my node is running fine I'm not too bothered, but if there's something I could try to fix it then I'd love to know!

Here's my log:
https://l.termbin.com/hat5c

**Comment by NilByte** [comment]
Check this:

https://github.com/rootzoll/raspiblitz/issues/3352

And this:

https://twitter.com/openoms/status/1579354351210229761

**Comment by dannuttall** [comment]
@NilByte Thanks updating LDN seemed to resolve the stuck on 100% screen. I still get the info screen update loop error. Is that a problem?

**Comment by NilByte** [comment]
If you followed the steps:

Steps:
- connect with ssh 
- press CTRL+C
- type: menu
- select UPDATE - LND 
- update to LND v0.15.2-beta

And Raspiblitz rebooted now showing your channels active in status screen, then update should have been successful.

What is the info screen update loop error you notice?

**Comment by dannuttall** [comment]
@NilByte yes I followed those steps and the status screen is now showing channels, although 0/0, not sure if that's a problem?

The update loop error is this:

<img width="475" alt="image" src="https://user-images.githubusercontent.com/25965241/194906044-35bc9141-205b-4fd2-95dd-e8c16b147b2a.png">

**Comment by NilByte** [comment]
`Screen is updating in a loop .... press 'x' now to get back to menu.`

Is normal behavior when you access the status screen via ssh. 

If you haven't opened any channels yet, then `0/0 Channels 0 sat 3 peers` is normal status.

**Comment by dannuttall** [comment]
thank you

**Comment by Delivator** [comment]
~~I have the same issue on `RaspiBlitz 1.8.0` with `lnd version 0.16.0-beta commit=v0.16.0-beta`~~

~~Anyone know if this is a known issue? Should I open a new issue?~~

**Comment by Delivator** [comment]
~~My screen looks like this~~
![image](https://user-images.githubusercontent.com/11231245/231565017-fe569deb-4196-42af-a71a-fba39644fd93.png)
![image](https://user-images.githubusercontent.com/11231245/231565284-ef96e92a-b95b-4759-8754-ca7910d0f9af.png)
~~and this is my debug log: https://l.termbin.com/e90e~~

**Comment by Delivator** [comment]
okay looks like it just took a very long time even though it said 100%
