### ISSUE TITLE
Link in readme not resolving: "Can I run RaspiBlitz on other computers than RaspberryPi?"

### ISSUE THREAD

**Issue by BCsRock** [raspiblitz/raspiblitz#3361]
Inside `README.md` there are two references to the FAQ which seems to have been removed in the past. 

At the end of [Section Build the SD Card](https://github.com/rootzoll/raspiblitz#build-the-sd-card-image), there is the Question 

Can I run RaspiBlitz on other computers than RaspberryPi

with a link to : https://github.com/rootzoll/raspiblitz/blob/v1.8/FAQ.md#can-i-run-raspiblitz-on-other-computers-than-raspberrypi

This link is not resolving as this section has been removed from the FAQ in the past. 

Suggestion: 
Directly link the user to: https://github.com/rootzoll/raspiblitz/blob/v1.8/alternative.platforms/README.md instead of going to the FAQ first. 

Also in `README.md`, directly at the next section [FAQ](https://github.com/rootzoll/raspiblitz#faq) it also refers to the same question with same target link.

**Comment by rootzoll** [comment]
Thx - got that link fixed in the dev branch. Will be part of next release.
