### ISSUE TITLE
RTL unreachable after updating to 1.8

### ISSUE THREAD

**Issue by SomeBTChomer** [raspiblitz/raspiblitz#3363]
RTL isn't reachable on ports 3000/3001 or the provided onion address after flashing to 1.8, opening the onion link shows an nginx error.

Uninstalling and reinstalling via the mainmenu and the webUI also didn't help.

**Comment by robinvonmises** [comment]
I have had a problem few days ago, that RTL (neither LND, nor CLN) wasn't running, because clrest was not able to start. Are you using CLN as lightning implementation, too?

Then try this, worked for me

https://github.com/rootzoll/raspiblitz/issues/3324#issuecomment-1266869029

**Comment by SomeBTChomer** [comment]
Thanks, but no CLN here, only LND is active.

**Comment by rootzoll** [comment]
Did it repair with the the new v1.8.0c sd card image update?

**Comment by cstenglein** [comment]
@SomeBTChomer does it still appear with 1.9.0?

Closing for now, if it still appears, please re-open
