### ISSUE TITLE
Unable to sweep LND on-chain funds

### ISSUE THREAD

**Issue by papssaj** [raspiblitz/raspiblitz#3364]
I have a RaspiBlitz running with the following specifications:

RaspiBlitz: 1.8.0
bitcoin: v23.0.0
LND: 0.15.2-beta

The LND node has been running for ~7 months. A few days ago, all my last LND channels were forced closed by the other peers. I'm not sure if this was related to the LND bug or something with Tor or something completly unrelated. Anyway, I decided that I would like to switch from LND to C-lightning on that occasion. Before doing that, I installed the lastet LND hotfix version 0.15.2-beta according to a small tutorial from openoms to avoid any risk. Thereafter I installed c-lightning to run in parallel and changed eg LNbits to use it as a default.

After that, I closed all channels that the node has, which worked as expected. Now my LND node reported on-chain funds as expected, and also respective UTXOs. Before moving all my funds back to my hardware wallet, I did a small test transaction which worked successfully from LND onchain to the hardware wallet. After that however, when I tried to sweep the on-chain funds to my normal bitcoin wallet, I got the following error:

Unable To Broadcast Sweep Transaction: Unmatched Backend Error: -26: Non-mandatory-script-verify-flag (script Failed An Op_equalverify Operation)

I managed to identify the UTXO which is causing a problem (by using the 'Lease' functionality in Ride the Lightning). It was the UTXO with the change from my LND on-chain to hardware wallet transaction.

Because I didn't have any other ideas, I opened a bug with LND: https://github.com/lightningnetwork/lnd/issues/7022

Unfortunately, one developer investigated that apparently my LND has sent the change to an address for which it does not posses the private key. We confirmed that by using the seed words with chantools and importing all private keys in electrum. The balance shown is 0. There is further information about the addresses in the issue.

Would you have any idea if this issue might be related to the parallel use of c-lightning, and would you have ideas how I could get the funds back? This is very unfortunate, since the amount lost is very large.

**Comment by openoms** [comment]
Sorry to read this. Was the right thing to do to open an issue with LND as it seems to be bug even if not caused but could possibly be prevented there.

Unfortunately I can say no more than what the LND devs did after their investigation. 
This problem is not related to using CLN at the same time as those completely different wallets and not interacting.
A memory corruption can happen, but the chance to result in another valid bitcoin address is extremely low.
The ways to prevent corruption are to use a machine with ECC memory and a checksumming copy-on-write filesystem like ZFS. That is a recommendation to use for significant amount of funds with the risk appetite being everyone's own decision. Really sorry that these comments can't really help after the fact.

**Comment by openoms** [comment]
Got another report of a similar case on Telegram https://t.me/raspiblitz/114533 

There seems to be an issue @guggero. Directed the user to the LND Slack with more details.

Please let us know if anything can be done on the Raspiblitz side to fix or prevent this.

**Comment by papssaj** [comment]
Thanks a lot for your reply. For me it was just important to make sure that it was not a weird combination of steps and tools that could always lead to this outcome. I completly understand that there is a likelyhood of loosing the funds, it's stated clearly in all RaspiBlitz guides and of course also in LND documentation. It's still a suprise if it happens because nobody thinks he's the one that will be hit :-D.

Based on the second comment I assume it could still be a software issue, correct? The likelyhood of this happening in a very similar setup twice in a row is probably low. Unfortunately, after the LND feedback was that it is not a software issue, I reset my RaspiBlitz and therefore have no more logs, except for the backed up the wallet.db file. If that would be interesting for you (@openoms ) to look at please let me know and I'm happy to provide it.

**Comment by guggero** [comment]
> Got another report of a similar case on Telegram https://t.me/raspiblitz/114533
> 
> There seems to be an issue @guggero. Directed the user to the LND Slack with more details.
> 
> Please let us know if anything can be done on the Raspiblitz side to fix or prevent this.

That's a completely different error message and address type. Let's not jump to conclusions please. I messaged the user on two platforms, I need more information. Could just be a weird edge case around Taproot addresses, let's not toss around "loss of funds" before we at least see some logs.

**Comment by cstenglein** [comment]
@papssaj is this still relevant?

Closing for now, if it still persists, please re-open.

**Comment by stakoholic** [comment]
hello, i have actually the same problem, i want so sweep all my funds and i get this . unmatched backend error: -26: non-mandatory-script-verify-flag , im on lnd 0.17.3-beta
