### ISSUE TITLE
Restore default settings/ app selection??

### ISSUE THREAD

**Issue by 1thales** [raspiblitz/raspiblitz#3366]
I cant reactivate WebUI and generally noticed it is not a good idea to decativate any app since Raspiblitz is not well tested for this. How do I restore default settings/ app selection? would really appreciate any help

**Comment by cstenglein** [comment]
Do you have more info on this?
What does "reactivate WebUI" mean? What errors do you get?

**Comment by 1thales** [comment]
I deactivated WebUI then reactivated it from the menu. I get "unknown error" in the UI

**Comment by 1thales** [comment]
I would love to be able to go back to "factory" settings

**Comment by rootzoll** [comment]
running a recover with a fresh sd card image is the normal way to get back to "factory" settings

**Comment by 1thales** [comment]
Its not. There is some conf file in the hard drive that is making blitz restore its state

**Comment by rootzoll** [comment]
In the process of starting with a fresh sd card image it will ask you if you like to start the recovery - but you can cancel that and then you will get offered the "Fresh Setup" option.
