### ISSUE TITLE
Lightning wallet recovery

### ISSUE THREAD

**Issue by jerbearstare** [raspiblitz/raspiblitz#3368]
### *BASIC ISSUE*

I misplaced my password D, but still have my recovery seed. Will I be able to retrieve my BTC if something happens to my node, without password D?

If so how do I create a new password D / reset my lightning node? So I can load a good amount of sats to get my channels going

**Comment by openoms** [comment]
you can change the password D in the menu. Do it now so you won't have issues later.

**Comment by jerbearstare** [comment]
in  "*set password*" within the menu there is only password **A, B &C**

is the password **D** a figment of my imagination?

**Comment by openoms** [comment]
You are right, actually the password D is not used for a good while now. 
It was how we called the optional passphrase with the seed. 
If you generated your wallet from the menu recently there was no passwordD given.
