### ISSUE TITLE
Update c-lightning-REST to v0.9.0

### ISSUE THREAD

**Issue by benjamin-wilson** [raspiblitz/raspiblitz#3370]
Previous versions of c-lightning-REST will not list multiple channels per peer. This causes all REST consumers such as RTL and Zeus to display the incorrect number of channels.

See: [https://github.com/Ride-The-Lightning/RTL/issues/988#issuecomment-1227595503](https://github.com/Ride-The-Lightning/RTL/issues/988#issuecomment-1227595503) 

The current version is v0.7.2. [cl.rest.sh](https://github.com/rootzoll/raspiblitz/blob/b20293a0c90f531477774c9a810b5491c81d0166/home.admin/config.scripts/cl.rest.sh)

**Comment by rootzoll** [comment]
Thx. Will take a look for next release.

**Comment by rootzoll** [comment]
OK updated to 0.9.0 - will be part of next release. Closing issue.
