### ISSUE TITLE
node stuck @ "node is syncing"

### ISSUE THREAD

**Issue by podkilla** [raspiblitz/raspiblitz#3381]
I have found issues #3350 and #3352 and updated to LND 0.15.3-beta.
I also ran 'patch' and restarted my node.

This did not solve the issue.
lncli getinfo still shows:
"synced_to_chain": false

[Here](https://l.termbin.com/4ph8) are some debug logs.

Let me know if i need to provide more info.

**Comment by podkilla** [comment]
Checking again after an hour - everything seems normal again.

Closing this.

**Comment by TheBlueMastiff** [comment]
I have the same problem and updating LND to 0.15.3 and running `patch` didn't fix it for me.

**Comment by podkilla** [comment]
Maybe opening a new case is the better option then. Maybe post some debug logs as well.
