### ISSUE TITLE
How to connect to a TEoS watchtower with CLN

### ISSUE THREAD

**Issue by wchancao** [raspiblitz/raspiblitz#3394]
Steps to install and connect a CLN node to a The Eye of Satoshi (TEoS) watchtower, using the watchtower-client plugin.

`sudo su bitcoin`

Install rustc and cargo
`curl https://sh.rustup.rs -sSf | sh`
`source "$HOME/.cargo/env"`

Clone the repo from [https://github.com/talaia-labs/rust-teos](url)
`cd /home/bitcoin/cl-plugins-available`
`git clone https://github.com/talaia-labs/rust-teos`

Compile the watchtower-client plugin
`cd rust-teos`
`cargo install --path watchtower-plugin`

Symlink the compiled plugin
`ln -s /home/bitcoin/cl-plugins-available/rust-teos/target/release/watchtower-client /home/bitcoin/cl-plugins-enabled/watchtower-client`
`exit`

Restart lightningd
`sudo systemctl restart lightningd`

To connect to a tower, use
`cl registertower tower_id`

If you want to connect to a tower through Tor, add this line to the cl.conf file
`watchtower-proxy=127.0.0.1:9050`

**Comment by steepdawn974** [comment]
FYI, I built this into a bonus script.
https://github.com/rootzoll/raspiblitz/pull/3404

Feel free to test. Feedback is appreciated!

**Comment by rootzoll** [comment]
PR merged - fInal dev continues in `eos-watchtower` branch

**Comment by rootzoll** [comment]
OK tested on recover and install keeps consistent. Merged into `dev` branch - to be functional tested as Release Canidate for v1.9.0 release.
