### ISSUE TITLE
Node sync stuck at 100%.  Electrs won't start.

### ISSUE THREAD

**Issue by Zestforlife808** [raspiblitz/raspiblitz#3406]
***************************************************************
* RASPIBLITZ DEBUG LOGS
***************************************************************
blitzversion: 1.8.0
chainnetwork: bitcoin / main
 07:55:18 up 52 min,  3 users,  load average: 2.10, 2.19, 2.04

*** SETUPPHASE / BOOTSTRAP ***
see logs: cat /home/admin/raspiblitz.log
setupPhase--> done
state--> ready

*** BACKGROUNDSERVICE ***
to monitor Background service call: sudo journalctl -f -u background

*** BLOCKCHAIN (MAINNET) SYSTEMD STATUS ***
● bitcoind.service - Bitcoin daemon
     Loaded: loaded (/etc/systemd/system/bitcoind.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2022-11-02 07:04:15 GMT; 51min ago
    Process: 2461 ExecStart=/usr/local/bin/bitcoind -daemonwait -conf=/mnt/hdd/bitcoin/bitcoin.conf -datadir=/mnt/hdd/bitcoin -debuglogfile                        =/mnt/hdd/bitcoin/debug.log (code=exited, status=0/SUCCESS)
   Main PID: 2529 (bitcoind)
      Tasks: 18 (limit: 4531)
        CPU: 2min 48.323s
     CGroup: /system.slice/bitcoind.service
             └─2529 /usr/local/bin/bitcoind -daemonwait -conf=/mnt/hdd/bitcoin/bitcoin.conf -datadir=/mnt/hdd/bitcoin -debuglogfile=/mnt/h…

Nov 02 07:03:12 raspberrypi systemd[1]: Starting Bitcoin daemon...
Nov 02 07:04:15 raspberrypi systemd[1]: Started Bitcoin daemon.

*** LAST BLOCKCHAIN (MAINNET) ERROR LOGS ***
sudo journalctl -u bitcoind -b --no-pager -n8
-- Journal begins at Fri 2022-10-28 07:28:00 BST, ends at Wed 2022-11-02 07:55:18 GMT. --
Nov 02 07:03:12 raspberrypi systemd[1]: Starting Bitcoin daemon...
Nov 02 07:04:15 raspberrypi systemd[1]: Started Bitcoin daemon.

*** LAST BLOCKCHAIN (MAINNET) 20 INFO LOGS ***
sudo tail -n 20 /mnt/hdd/bitcoin/debug.log
tail: cannot open '/mnt/hdd/bitcoin/debug.log' for reading: No such file or directory

*** LND (MAINNET) SYSTEMD STATUS ***
● lnd.service - Lightning Network Daemon
     Loaded: loaded (/etc/systemd/system/lnd.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2022-11-02 07:04:18 GMT; 51min ago
    Process: 7420 ExecStartPre=/home/admin/config.scripts/lnd.check.sh prestart mainnet (code=exited, status=0/SUCCESS)
   Main PID: 7697 (lnd)
     Status: "Wallet unlocked"
      Tasks: 10 (limit: 4531)
        CPU: 37.702s
     CGroup: /system.slice/lnd.service
             └─7697 /usr/local/bin/lnd --configfile=/home/bitcoin/.lnd/lnd.conf

Nov 02 07:04:15 raspberrypi systemd[1]: Starting Lightning Network Daemon...
Nov 02 07:04:18 raspberrypi systemd[1]: Started Lightning Network Daemon.

*** LAST LND (MAINNET) ERROR LOGS ***
sudo journalctl -u lnd -b --no-pager -n12
-- Journal begins at Fri 2022-10-28 07:28:00 BST, ends at Wed 2022-11-02 07:55:18 GMT. --
Nov 02 07:04:15 raspberrypi systemd[1]: Starting Lightning Network Daemon...
Nov 02 07:04:18 raspberrypi systemd[1]: Started Lightning Network Daemon.

*** LAST 30 LND (MAINNET) INFO LOGS ***
sudo tail -n 30 /mnt/hdd/lnd/logs/bitcoin/mainnet/lnd.log
2022-11-02 07:47:19.073 [DBG] RPCS: [channelbalance] local_balance=0 mSAT remote_balance=0 mSAT unsettled_local_balance=0 mSAT unsettled_re                        mote_balance=0 mSAT pending_open_local_balance=0 mSAT pending_open_remote_balance=0 mSAT
2022-11-02 07:47:55.763 [DBG] RPCS: [walletbalance] Total balance=0 BTC (confirmed=0 BTC, unconfirmed=0 BTC)
2022-11-02 07:47:56.045 [DBG] RPCS: [channelbalance] local_balance=0 mSAT remote_balance=0 mSAT unsettled_local_balance=0 mSAT unsettled_re                        mote_balance=0 mSAT pending_open_local_balance=0 mSAT pending_open_remote_balance=0 mSAT
2022-11-02 07:48:19.961 [DBG] RPCS: [feereport]
2022-11-02 07:48:31.734 [DBG] RPCS: [walletbalance] Total balance=0 BTC (confirmed=0 BTC, unconfirmed=0 BTC)
2022-11-02 07:48:32.022 [DBG] RPCS: [channelbalance] local_balance=0 mSAT remote_balance=0 mSAT unsettled_local_balance=0 mSAT unsettled_re                        mote_balance=0 mSAT pending_open_local_balance=0 mSAT pending_open_remote_balance=0 mSAT
2022-11-02 07:49:05.365 [DBG] RPCS: [walletbalance] Total balance=0 BTC (confirmed=0 BTC, unconfirmed=0 BTC)
2022-11-02 07:49:06.026 [DBG] RPCS: [channelbalance] local_balance=0 mSAT remote_balance=0 mSAT unsettled_local_balance=0 mSAT unsettled_re                        mote_balance=0 mSAT pending_open_local_balance=0 mSAT pending_open_remote_balance=0 mSAT
2022-11-02 07:49:42.469 [DBG] RPCS: [walletbalance] Total balance=0 BTC (confirmed=0 BTC, unconfirmed=0 BTC)
2022-11-02 07:49:42.815 [DBG] RPCS: [channelbalance] local_balance=0 mSAT remote_balance=0 mSAT unsettled_local_balance=0 mSAT unsettled_re                        mote_balance=0 mSAT pending_open_local_balance=0 mSAT pending_open_remote_balance=0 mSAT
2022-11-02 07:49:56.935 [DBG] RPCS: [feereport]
2022-11-02 07:50:23.262 [DBG] RPCS: [walletbalance] Total balance=0 BTC (confirmed=0 BTC, unconfirmed=0 BTC)
2022-11-02 07:50:23.566 [DBG] RPCS: [channelbalance] local_balance=0 mSAT remote_balance=0 mSAT unsettled_local_balance=0 mSAT unsettled_re                        mote_balance=0 mSAT pending_open_local_balance=0 mSAT pending_open_remote_balance=0 mSAT
2022-11-02 07:51:01.327 [DBG] RPCS: [walletbalance] Total balance=0 BTC (confirmed=0 BTC, unconfirmed=0 BTC)
2022-11-02 07:51:01.648 [DBG] RPCS: [channelbalance] local_balance=0 mSAT remote_balance=0 mSAT unsettled_local_balance=0 mSAT unsettled_re                        mote_balance=0 mSAT pending_open_local_balance=0 mSAT pending_open_remote_balance=0 mSAT
2022-11-02 07:51:40.062 [DBG] RPCS: [walletbalance] Total balance=0 BTC (confirmed=0 BTC, unconfirmed=0 BTC)
2022-11-02 07:51:40.494 [DBG] RPCS: [channelbalance] local_balance=0 mSAT remote_balance=0 mSAT unsettled_local_balance=0 mSAT unsettled_re                        mote_balance=0 mSAT pending_open_local_balance=0 mSAT pending_open_remote_balance=0 mSAT
2022-11-02 07:51:41.608 [DBG] RPCS: [feereport]
2022-11-02 07:52:18.243 [DBG] RPCS: [walletbalance] Total balance=0 BTC (confirmed=0 BTC, unconfirmed=0 BTC)
2022-11-02 07:52:18.607 [DBG] RPCS: [channelbalance] local_balance=0 mSAT remote_balance=0 mSAT unsettled_local_balance=0 mSAT unsettled_re                        mote_balance=0 mSAT pending_open_local_balance=0 mSAT pending_open_remote_balance=0 mSAT
2022-11-02 07:52:56.668 [DBG] RPCS: [walletbalance] Total balance=0 BTC (confirmed=0 BTC, unconfirmed=0 BTC)
2022-11-02 07:52:57.173 [DBG] RPCS: [channelbalance] local_balance=0 mSAT remote_balance=0 mSAT unsettled_local_balance=0 mSAT unsettled_re                        mote_balance=0 mSAT pending_open_local_balance=0 mSAT pending_open_remote_balance=0 mSAT
2022-11-02 07:53:21.937 [DBG] RPCS: [feereport]
2022-11-02 07:53:37.286 [DBG] RPCS: [walletbalance] Total balance=0 BTC (confirmed=0 BTC, unconfirmed=0 BTC)
2022-11-02 07:53:37.643 [DBG] RPCS: [channelbalance] local_balance=0 mSAT remote_balance=0 mSAT unsettled_local_balance=0 mSAT unsettled_re                        mote_balance=0 mSAT pending_open_local_balance=0 mSAT pending_open_remote_balance=0 mSAT
2022-11-02 07:54:10.480 [DBG] RPCS: [walletbalance] Total balance=0 BTC (confirmed=0 BTC, unconfirmed=0 BTC)
2022-11-02 07:54:10.833 [DBG] RPCS: [channelbalance] local_balance=0 mSAT remote_balance=0 mSAT unsettled_local_balance=0 mSAT unsettled_re                        mote_balance=0 mSAT pending_open_local_balance=0 mSAT pending_open_remote_balance=0 mSAT
2022-11-02 07:54:53.381 [DBG] RPCS: [walletbalance] Total balance=0 BTC (confirmed=0 BTC, unconfirmed=0 BTC)
2022-11-02 07:54:53.776 [DBG] RPCS: [channelbalance] local_balance=0 mSAT remote_balance=0 mSAT unsettled_local_balance=0 mSAT unsettled_re                        mote_balance=0 mSAT pending_open_local_balance=0 mSAT pending_open_remote_balance=0 mSAT
2022-11-02 07:54:55.105 [DBG] RPCS: [feereport]

*** CORE LIGHTNING (MAINNET) SYSTEMD STATUS ***
- not activated -

*** BLOCKCHAIN (TESTNET) SYSTEMD STATUS ***
- OFF by config -
*** LND (TESTNET) SYSTEMD STATUS ***
- OFF by config -

*** CORE LIGHTNING (TESTNET) SYSTEMD STATUS ***
- not activated -

*** BLOCKCHAIN (SIGNET) SYSTEMD STATUS ***
- OFF by config -
*** LND (SIGNET) SYSTEMD STATUS ***
- OFF by config -

*** CORE LIGHTNING (SIGNET) SYSTEMD STATUS ***
- not activated -

*** NGINX SYSTEMD STATUS ***
● nginx.service - A high performance web server and a reverse proxy server
     Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/nginx.service.d
             └─raspiblitz.conf
     Active: active (running) since Wed 2022-11-02 07:03:00 GMT; 52min ago
       Docs: man:nginx(8)
   Main PID: 870 (nginx)
      Tasks: 5 (limit: 4531)
        CPU: 156ms
     CGroup: /system.slice/nginx.service
             ├─870 nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
             ├─871 nginx: worker process
             ├─872 nginx: worker process
             ├─873 nginx: worker process
             └─874 nginx: worker process

Nov 02 07:02:58 raspberrypi systemd[1]: Starting A high performance web server and a reverse proxy server...
Nov 02 07:03:00 raspberrypi systemd[1]: Started A high performance web server and a reverse proxy server.

*** LAST NGINX LOGS ***
sudo journalctl -u nginx -b --no-pager -n20
-- Journal begins at Fri 2022-10-28 07:28:00 BST, ends at Wed 2022-11-02 07:55:18 GMT. --
Nov 02 07:02:58 raspberrypi systemd[1]: Starting A high performance web server and a reverse proxy server...
Nov 02 07:03:00 raspberrypi systemd[1]: Started A high performance web server and a reverse proxy server.
--> CHECK CONFIG: sudo nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

*** BLITZAPI SYSTEMD STATUS ***
● blitzapi.service - BlitzBackendAPI
     Loaded: loaded (/etc/systemd/system/blitzapi.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2022-11-02 07:02:59 GMT; 52min ago
   Main PID: 785 (python)
      Tasks: 12 (limit: 4531)
        CPU: 1min 209ms
     CGroup: /system.slice/blitzapi.service
             └─785 /usr/bin/python -m uvicorn app.main:app --port 11111 --host=0.0.0.0 --root-path /api

Nov 02 07:04:14 raspberrypi python[785]: ERROR:root:Unknown answer from Bitcoin Core. Reason: Internal Server Error
Nov 02 07:04:17 raspberrypi python[785]: WARNING:root:LND_GRPC: Unhandled initialization event: {'state': <LnInitState.BOOTSTRAP…vailable'}
Hint: Some lines were ellipsized, use -l to show in full.

*** LAST BLITZAPI LOGS ***
sudo journalctl -u blitzapi -b --no-pager -n20
-- Journal begins at Fri 2022-10-28 07:28:00 BST, ends at Wed 2022-11-02 07:55:19 GMT. --
Nov 02 07:03:37 raspberrypi python[785]: ERROR:root:Unknown answer from Bitcoin Core. Reason: Internal Server Error
Nov 02 07:03:39 raspberrypi python[785]: ERROR:root:Unknown answer from Bitcoin Core. Reason: Internal Server Error
Nov 02 07:03:41 raspberrypi python[785]: ERROR:root:Unknown answer from Bitcoin Core. Reason: Internal Server Error
Nov 02 07:03:43 raspberrypi python[785]: ERROR:root:Unknown answer from Bitcoin Core. Reason: Internal Server Error
Nov 02 07:03:45 raspberrypi python[785]: ERROR:root:Unknown answer from Bitcoin Core. Reason: Internal Server Error
Nov 02 07:03:47 raspberrypi python[785]: ERROR:root:Unknown answer from Bitcoin Core. Reason: Internal Server Error
Nov 02 07:03:49 raspberrypi python[785]: ERROR:root:Unknown answer from Bitcoin Core. Reason: Internal Server Error
Nov 02 07:03:51 raspberrypi python[785]: ERROR:root:Unknown answer from Bitcoin Core. Reason: Internal Server Error
Nov 02 07:03:53 raspberrypi python[785]: ERROR:root:Unknown answer from Bitcoin Core. Reason: Internal Server Error
Nov 02 07:03:55 raspberrypi python[785]: ERROR:root:Unknown answer from Bitcoin Core. Reason: Internal Server Error
Nov 02 07:03:57 raspberrypi python[785]: ERROR:root:Unknown answer from Bitcoin Core. Reason: Internal Server Error
Nov 02 07:03:59 raspberrypi python[785]: ERROR:root:Unknown answer from Bitcoin Core. Reason: Internal Server Error
Nov 02 07:04:01 raspberrypi python[785]: ERROR:root:Unknown answer from Bitcoin Core. Reason: Internal Server Error
Nov 02 07:04:04 raspberrypi python[785]: ERROR:root:Unknown answer from Bitcoin Core. Reason: Internal Server Error
Nov 02 07:04:06 raspberrypi python[785]: ERROR:root:Unknown answer from Bitcoin Core. Reason: Internal Server Error
Nov 02 07:04:08 raspberrypi python[785]: ERROR:root:Unknown answer from Bitcoin Core. Reason: Internal Server Error
Nov 02 07:04:10 raspberrypi python[785]: ERROR:root:Unknown answer from Bitcoin Core. Reason: Internal Server Error
Nov 02 07:04:12 raspberrypi python[785]: ERROR:root:Unknown answer from Bitcoin Core. Reason: Internal Server Error
Nov 02 07:04:14 raspberrypi python[785]: ERROR:root:Unknown answer from Bitcoin Core. Reason: Internal Server Error
Nov 02 07:04:17 raspberrypi python[785]: WARNING:root:LND_GRPC: Unhandled initialization event: {'state': <LnInitState.BOOTSTRAPPING: 'boot                        strapping'>, 'msg': 'Connected but waiting to start, RPC services not available'}

- TOUCHSCREEN is OFF by config
- Loop is OFF by config
- LND-RTL is OFF by config
- CL-RTL is OFF by config

*** LAST 20 ElectRS LOGS ***
sudo journalctl -u electrs -b --no-pager -n20
-- Journal begins at Fri 2022-10-28 07:28:00 BST, ends at Wed 2022-11-02 07:55:19 GMT. --
Nov 02 07:54:22 raspberrypi systemd[1]: electrs.service: Consumed 9.192s CPU time.
Nov 02 07:54:22 raspberrypi systemd[1]: Started Electrs.
Nov 02 07:54:22 raspberrypi electrs[420814]: Starting electrs 0.9.7 on aarch64 linux with Config { network: Bitcoin, db_path: "/mnt/hdd/app                        -storage/electrs/db/bitcoin", daemon_dir: "/home/electrs/.bitcoin", daemon_auth: UserPass("raspibolt", "<sensitive>"), daemon_rpc_addr: 127                        .0.0.1:8332, daemon_p2p_addr: 127.0.0.1:8333, electrum_rpc_addr: 0.0.0.0:50001, monitoring_addr: 127.0.0.1:4224, wait_duration: 10s, jsonrp                        c_timeout: 15s, index_batch_size: 10, index_lookup_limit: None, reindex_last_blocks: 0, auto_reindex: true, ignore_mempool: false, sync_onc                        e: false, disable_electrum_rpc: false, server_banner: "Welcome to electrs v0.9.7 - the Electrum Rust Server on your RaspiBlitz", args: [] }
Nov 02 07:54:22 raspberrypi electrs[420814]: [2022-11-02T07:54:22.842Z INFO  electrs::metrics::metrics_impl] serving Prometheus metrics on                         127.0.0.1:4224
Nov 02 07:54:22 raspberrypi electrs[420814]: [2022-11-02T07:54:22.842Z INFO  electrs::server] serving Electrum RPC on 0.0.0.0:50001
Nov 02 07:54:22 raspberrypi electrs[420814]: [2022-11-02T07:54:22.891Z INFO  electrs::db] "/mnt/hdd/app-storage/electrs/db/bitcoin": 160 SS                        T files, 37.543608995 GB, 4.696187474 Grows
Nov 02 07:54:27 raspberrypi electrs[420814]: [2022-11-02T07:54:27.479Z INFO  electrs::chain] loading 761248 headers, tip=000000000000000000                        0640e114b9e6272b9688178273e193ef957e02fad1069f
Nov 02 07:54:32 raspberrypi electrs[420814]: [2022-11-02T07:54:32.133Z INFO  electrs::chain] chain updated: tip=0000000000000000000640e114b                        9e6272b9688178273e193ef957e02fad1069f, height=761248
Nov 02 07:54:32 raspberrypi electrs[420814]: [2022-11-02T07:54:32.179Z INFO  electrs::index] indexing 131 blocks: [761249..761379]
Nov 02 07:54:32 raspberrypi electrs[420814]: thread 'p2p_loop' panicked at 'invalid message: OversizedVectorAllocation { requested: 1200007                        2, max: 4000000 }', src/p2p.rs:250:70
Nov 02 07:54:32 raspberrypi electrs[420814]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Nov 02 07:54:32 raspberrypi electrs[420814]: [2022-11-02T07:54:32.201Z INFO  electrs::db] closing DB at /mnt/hdd/app-storage/electrs/db/bit                        coin
Nov 02 07:54:32 raspberrypi electrs[420814]: Error: electrs failed
Nov 02 07:54:32 raspberrypi electrs[420814]: Caused by:
Nov 02 07:54:32 raspberrypi electrs[420814]:     0: sync failed
Nov 02 07:54:32 raspberrypi electrs[420814]:     1: failed to get block 000000000000000000070742427fa10ec3c66d006160155a704d9f56d090a3ea
Nov 02 07:54:32 raspberrypi electrs[420814]:     2: receiving on an empty and disconnected channel
Nov 02 07:54:32 raspberrypi systemd[1]: electrs.service: Main process exited, code=exited, status=1/FAILURE
Nov 02 07:54:32 raspberrypi systemd[1]: electrs.service: Failed with result 'exit-code'.
Nov 02 07:54:32 raspberrypi systemd[1]: electrs.service: Consumed 9.108s CPU time.

*** ElectRS Status ***
##### STATUS ELECTRS SERVICE
configured=1
serviceInstalled=1
serviceRunning=0
serviceRunning=0
tipSynced=0
initialSynced=0
electrumResponding=0
infoSync='Not running - check: sudo journalctl -u electrs'

- LIT is OFF by config
- BTCPayServer is OFF by config
- BTC-RPC-Explorer is OFF by config
- LNbits is OFF by config
- Thunderhub is OFF by config
- SPECTER is OFF by config
- SPHINX is OFF by config

*** MOUNTED DRIVES ***
Filesystem     Type      Size  Used Avail Use% Mounted on
/dev/root      ext4       30G   13G   16G  45% /
devtmpfs       devtmpfs  1.9G     0  1.9G   0% /dev
tmpfs          tmpfs     1.9G   16K  1.9G   1% /dev/shm
tmpfs          tmpfs     769M  1.1M  768M   1% /run
tmpfs          tmpfs     5.0M     0  5.0M   0% /run/lock
tmpfs          tmpfs      32M     0   32M   0% /var/cache/raspiblitz
/dev/mmcblk0p1 vfat      253M   31M  222M  12% /boot
/dev/sda1      ext4      916G  505G  365G  59% /mnt/hdd
tmpfs          tmpfs     385M   16K  385M   1% /run/user/1000
tmpfs          tmpfs     385M   16K  385M   1% /run/user/1001

*** DATADRIVE ***
# RASPIBLITZ DATA DRIVE Status

# BASICS
isMounted=1
isBTRFS=0
hddRaspiData=1
hddRaspiVersion='1.8.0'
isSSD=1
datadisk='sda'
datapartition='sda1'
hddCandidate='sda'
hddPartitionCandidate='sda1'
hddBlocksBitcoin=1
hddBytes=1000203820544
hddGigaBytes=931
hddUsedInfo='505G (59%)'
hddDataFreeBytes=391858528256
hddDataFreeKB=382674344
hddDataFreeGB=364
hddAdapterUSB=''
hddAdapterUSAP=0

# RAID
isRaid=0
raidCandidate[0]='zram0 4 GB zram0'
raidCandidates=1

# SWAP
isSwapExternal=1
SwapExternalPath='/mnt/hdd/swapfile'

*** NETWORK ***
localip=192.168.50.105
localiprange=192.168.50.0/24
dhcp=1
network_device=eth0

*** HARDWARE TEST RESULTS ***
UndervoltageReports in Logs: 0

*** SYSTEM CACHE STATUS ***
system_up="3163"
system_ram_gb="4"
system_count_undervoltage="0"
system_vm_vagrant="0"
system_count_start_blockchain="1"
system_temp_celsius="74"
system_ram_available_mb="3183"
system_temp_fahrenheit="165"
system_ups_battery=""
system_board="rp4"
system_init_time="1667372583"
system_count_longscan="0"
system_cpu_load=" 2.10, 2.19, 2.04"
system_count_start_tui="0"
system_count_start_lightning="1"
system_ram_mb="3844"
system_ups_status="OFF"
ln_default_sync_initial_done="1"
ln_default_tor="0"
ln_default_channels_pending="0"
ln_default_recovery_mode="0"
ln_default_error_short=""
ln_default_alias="RaspiBlitz"
ln_default_fees_total="0"
ln_default_sync_progress="100.00"
ln_default_peers="0"
ln_default_channels_active="0"
ln_default_version="0.15.0-beta"
ln_default_error_full=""
ln_default_channels_inactive="0"
ln_default_sync_chain="0"
ln_default_ready="1"
ln_default_wallet_channels_balance="0"
ln_default_running="1"
ln_default_wallet_onchain_balance="0"
ln_default_wallet_onchain_pending="0"
ln_default_locked="0"
ln_default_wallet_channels_pending="0"
ln_default_channels_total="0"
ln_default_recovery_done="0"
ln_default_online="0"
ln_default_activated="1"
btc_default_error_short=""
btc_default_blocks_verified="761379"
btc_default_online="1"
btc_default_version="v23.0.0"
btc_default_sync_progress="0.9999960708098895"
btc_default_ready="1"
btc_default_mempool_transactions="3311"
btc_default_sync_initialblockdownload="0"
btc_default_blocks_data_kb="483495200"
btc_default_port="8333"
btc_default_sync_initial_done="1"
btc_default_synced="1"
btc_default_sync_percentage="100.00"
btc_default_peers="12"
btc_default_activated="1"
btc_default_running="1"
btc_default_blocks_behind="0"
btc_default_blocks_headers="761379"
btc_default_error_full=""

*** LOGFILES ***
Archived and active journals take up 302.0M in the file system.
672M    /var/log

*** OPTION: SHARE THIS DEBUG OUTPUT ***
An easy way to share this debug output on GitHub or on a support chat
Use the following command and share the resulting link using termbin.com service and tor proxy:
 debug -l
If tor is failing and you don't mind leaking your ip address to the termbin service, use without tor:
 debug -l -n

![image](https://user-images.githubusercontent.com/12157502/199434663-1f9f9376-8afd-411f-be65-939650c98c71.png)

This setup has been working well for some time and suddenly stopped working.

**Comment by vv01f** [comment]
Hi @Zestforlife808, 
as quite somepeople already found out yesterday via Twitter or Telegram …
plz update LND (to 0.15.4-beta) and electrs (to 0.9.9). The issue is similar to the need for updating LND to 0.15.2-beta … a faulty common component of the two packages (btcd) …

1. For LND you find the Update option in the menu: Update / LND / …
2. For electrs you can use the cli or wait for a new image release enabling the [update in the menu](https://github.com/rootzoll/raspiblitz/pull/3402) as well; cli (leave menu with Ctrl+c) commands:

    cd /home/electrs/electrs
    sudo -u electrs git fetch
    sudo -u electrs git reset --hard v0.9.9
    sudo -u electrs /home/electrs/.cargo/bin/cargo build --locked --release

**Comment by rootzoll** [comment]
LND had a critical bug and also electrs was affected - see: https://twitter.com/openoms/status/1587415789484785667?s=20&t=mVPCiRGA2K8HFJznD4vFaQ

Will release a new sd card image v1.8.0c today that can be used to update and will come with fixes for lnd & electrs.

**Comment by Zestforlife808** [comment]
@vv01f @rootzoll Thanks for the quick replies.  I will wait for the image, update, and report back.

**Comment by Mexxblitz** [comment]
I have the same Issue with Electrum, LND is working again but Electrum not. Where can I find the new Image release to update Electrum?

**Comment by vv01f** [comment]
The new image 1.8.0**c** at: https://github.com/rootzoll/raspiblitz#downloading-the-software includes electrs 0.9.9 as well.

**Comment by lupn3** [comment]
#https://github.com/romanz/electrs/issues/787

**Comment by Zestforlife808** [comment]
I updated with the linked image and I'm back in action.  Thanks to all.
