### ISSUE TITLE
SHA 256 Checksum does not match

### ISSUE THREAD

**Issue by mschlappa** [raspiblitz/raspiblitz#3408]
I downloaded the SD Card Image File for Installation and get a different checksum than documented:

My executed command: shasum -a 256 raspiblitz.img 
4d9666120ac4d6ef9da74cec444c0c4e8984815abe2f1fd33c5317bd820b910a  raspiblitz.img

Checksum should be (documentation):
42c96fb29e03eb8276b40861f77b141bde30a2ff461947e107cff7d24c5a8096

What can i do?

**Comment by rootzoll** [comment]
Sorry I was right in the middle of uploading a new sd card image with the lnd hot fix called v1.8.0c .. the SHA sum was already from the new image while the link to the file was still old - the new one still in test & upload. Now the new sd card image is online - reload the README and download the enw sd card image.
