### ISSUE TITLE
3.2" Case vs 3.5" Screen?

### ISSUE THREAD

**Issue by aaronn** [raspiblitz/raspiblitz#341]
The linked case says it snaps around a 3.2" screen, but the linked screen in the reference shopping list is 3.5". Just double checking – is this correct and fits despite what's listed?

**Comment by raumi75** [comment]
You can‘t put the top frame on becaus the display is too large, but that‘s not really important. It will look like the photo in the readme.

**Comment by aaronn** [comment]
Got it. Thank you.

**Comment by dhniels** [comment]
I bought the [waveshare 3.2" pi display](https://amzn.to/2CF1Y2Z), and I can confirm the frame does fit around the 3.2" display. 

The [example pi display in the Readme](https://github.com/rootzoll/raspiblitz/raw/master/pictures/raspiblitz.jpg) appears to be the 3.5" model (frame doesnt fit, doesnt have the 3 buttons on the end.) 

However the 3.2" model has an issue with wrapping the text, and as a result the status screen gets all messed up. [Here is a photo](http://magaimg.net/img/7kjg.jpg). Not sure if theres a way to remedy this?

**Comment by rootzoll** [comment]
On testing I gave up on the 3.2" because of this text wrapp problem. 3.5" working fine and on the case just ignore the topping - looks good without it :)

**Comment by openoms** [comment]
@dhniels 
I have came around this thread: https://raspberrypi.stackexchange.com/questions/3543/how-do-i-increase-the-terminal-font-size
Get the list of fonts in your terminal:  `ls -la /usr/share/consolefonts/`
and try something smaller, for example:
` sudo setfont /usr/share/consolefonts/Uni3-TerminusBold14.psf.gz`
Try some others and please let us know which gave you the desired result with the 3.2" screen.

**Comment by openoms** [comment]
you can also run `sudo  dpkg-reconfigure console-setup` to choose and keep the setting after reboot

**Comment by dhniels** [comment]
@openoms brilliant, thank you! the smallest font I could see was `Uni3-Terminus12x6.psf.gz` which still wraps just a couple characters, but at least the status screen is readable now.

i wonder if a smaller font can be downloaded and set? or perhaps a way to edit the status screen itself (removing the lightning bolt ascii art for example) to prevent the text wrapping?

**Comment by openoms** [comment]
This is open source, so anything is possible :) . There should be plenty of other fonts available.
The easiest is still probably what you suggest is to edit the screen contents.
You need to edit the `00infoBlitz.sh`.

Run the inbuilt text editor with:
 `sudo nano 00infoBlitz.sh`
press the down arrow to scroll to the bottom and you will find the ASCII art.
To save press: CTRL+O, CTRL+X to exit.
Might need to restart to take effect.

**Comment by dhniels** [comment]
@openoms Thanks for pointing me to the file! I was able to get it to fit on the 3.2” display by changing to the Uni3-Terminus12x6 font, removed 3 characters from the dashed line, removed the spaces between the dash next to “free mem”, and removing “net” from the bitcoin line. Here is a photo of [my fancy 3.2” RaspiBlitz](http://magaimg.net/img/7lvt.jpg) in action!
