### ISSUE TITLE
IP2TOR Subscription unable to succeed 

### ISSUE THREAD

**Issue by Mexxblitz** [raspiblitz/raspiblitz#3417]
After countless hours trying to establish a subscription for the IP2TOR Bridge Service for LNBits I'm still getting the same Error Message. 

First apiGetOrder loop to around 50 times. 

Then afterwards, one of the following Error messages pops up: 
1. Error: Failed HTTP Request
2. Error: Failed to get Invoice

Any idea how to fix this?

**Comment by raulcano** [comment]
I experience a similar error when trying to buy a subscription IP2TOR for BTCPay server.
After the apiGetOrder attemps, I get a screen telling that the invoice could not be retrieved.
![image](https://user-images.githubusercontent.com/1665639/200282695-42399da3-402b-4f29-aa54-f39162c33081.png)

The details screen shows this:
![image](https://user-images.githubusercontent.com/1665639/200282842-13bd2bea-d2e4-477f-a9b5-47fea942721d.png)

**Comment by Mexxblitz** [comment]
Did you manage to get it working again? I still can't get a subscription!

**Comment by raulcano** [comment]
Nope. I tried every single day since I posted my comment, but same error unfortunately.

Do you know if there are other shops we could try for this?
It is quite interesting that the subscription menu allows you to input the onion address of a shop, but it comes prefilled with the fulmo one. If other providers offered that service, we could try ....

**Comment by Mexxblitz** [comment]
That is a good question. I havnt heard about other shops but will do my research. 

Maybe a maintainer could asnwer our question. Atleast if this is a known error.

**Comment by rootzoll** [comment]
At the moment the IP2Tor service run by FULMO is broken and its unsure if it will be further maintained by FULMO. Sorry. But basically its open source and somebody from the community can run an alternative IP2Tor shop & bridge (users can change the onion shop address in the beginning of the subscription dialog). If someone provides a stable alternative I can set that shop as a default in the next RaspiBlitz release. If there is no running shop within the next weeks I might remove the service from the feature set of RaspiBlitz with next version.

Here is the Ip2Tor Shop+Brigde open source code by @frennkie if anybody want to try it out:
https://github.com/frennkie/django-ip2tor

If you are a big fan/user of the Ip2Tor service and you dont want to see it go away - let @fulmolightning on twitter know and motivate for further FULMO support: https://twitter.com/fulmolightning

**Comment by raulcano** [comment]
Thanks for that @rootzoll . 
I wrote Fulmo to see if they are planning resuming the service. 
Also, I'll have a look at the code you linked and see if I could do that myself. If so, it won't be soon, so I'd have to let you know in due time...
Cheers!

**Comment by Miguel-sdj** [comment]
Does anyone have any more updates on the case?

**Comment by raulcano** [comment]
I asked fulmo and it's likely they won't resume the service. Time to check
for alternatives or to build your own IP2TOR with the instructions in the
linked repo.

Miguel Cabral ***@***.***> schrieb am Do., 17. Nov. 2022,
18:48:

**Comment by Mexxblitz** [comment]
Are there any other options on how to use LNbits from outside your home network than IP2TOR Bridges?

**Comment by raulcano** [comment]
Hi @rootzoll , I forked the Frennkie's source code and I am slowly building a IP2TOR Shop + Bridge, using Docker to isolate each service (nginx, django, tor, redis, postgres, ...)

Here are the repos:
- https://github.com/raulcano/docker-ip2tor-shop
- https://github.com/raulcano/docker-ip2tor-host

I'm still stuck after running the Daphne server (in localhost [+ Tor]). It doesn't accept HTTP requests and I honestly don't know how to proceed. If/When I get to something more stable I'll report back.

**Comment by rootzoll** [comment]
@raulcano great to hear - keep us updated.

@frennkie any help/support you can give @raulcano in getting his IP2Tor forks running would be highly appreciated.

**Comment by raulcano** [comment]
Thanks , will do.

@frennkie , in case you read this. I'm stuck in this step of your instructions:

```
Initial setup

-> go to Sites and change the initial domain name (and display name)
-> go to user and create operator (and add to "operators" group)
-> go to Hosts and create your first host
```

Daphne and nginx are running, and receiving connections even (can see in the logs when I try to access via browser).
The point is that I don't know where these "Sites" , "User" or "Hosts" pages are, so I'm not sure I can progress without adding the right entries.

For what is worth:
- redis is running and throws no errors in the logs
- the database is running fine (or so it seems). Migrations are executed and tables created successfully
- the celery-beat and celery-worker are not running (I disabled them to add services one by one)

Also, I'm new to most of those things so I'm pretty much learning as I go ...

Some screenshots of the startup

![image](https://user-images.githubusercontent.com/1665639/203834427-424359eb-4699-4f6f-afc0-7f13dee69810.png)

![image](https://user-images.githubusercontent.com/1665639/203834478-aeae385f-76e8-408b-b596-df2808223bb0.png)

![image](https://user-images.githubusercontent.com/1665639/203834645-c2b1fe71-7c38-4f02-9ed0-981b823c30b3.png)

**Comment by raulcano** [comment]
Once started (see screenshots above), I visit from my browser 
http://localhost:8000/

Results:
![image](https://user-images.githubusercontent.com/1665639/203835137-8e4b4472-2800-4c07-924a-3548d81f4a45.png)

![image](https://user-images.githubusercontent.com/1665639/203835165-5e566c24-3c33-4a64-9442-51797b3f6ea2.png)

The key seems to be in that "No application configured for scope type 'http'"
It looks the whole setup is not listening to http, or I am missing the correct paths.


On the other hand, if I open a browser console and try to create a socket, I get an error.
I type:
`new WebSocket("ws://localhost:8000") `


![image](https://user-images.githubusercontent.com/1665639/203943818-6883b44e-0cfe-4dec-bf3d-5f34ad0ad86a.png)

And from the server logs I get
![image](https://user-images.githubusercontent.com/1665639/203943990-aaef8272-6de8-4a48-8ca8-4e888228c2be.png)



This is the nginx config file I'm running at the moment:
https://github.com/raulcano/docker-ip2tor-shop/blob/master/.docker/shop.localhost.conf

```
server {
    # Listen on port for incoming requests.
    listen 88;
    server_name  localhost;

    # Django media
    location /media/  {
      root /usr/share/nginx;

    }
    # Django static
    location /static/ {
      root /usr/share/nginx;
    }

    location / {
        proxy_pass http://django:8001;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $server_name;
        # proxy_set_header X-Forwarded-Proto https;

    }
}
```

**Comment by raulcano** [comment]
Since this thread was about the IP2Tor in Raspiblitz not working, I opened an issue in my docker implementation of the shop to bring the discussion there, with my last 2 posts, which belong to a different scope: https://github.com/raulcano/docker-ip2tor-shop/issues/1

**Comment by rootzoll** [comment]
@raulcano I can see you closed the issue. Can you sum up the status of your work?

**Comment by raulcano** [comment]
Well, it's still work in progress.
I haven't understood from frennkie's code in GitHub which server he used to get to the admin pages, so I managed to access the admin pages via the integrated django development server, which takes care of http requests. I need to change that to a more production ready server (gunicorn maybe?) and update Nginx properly, also for https.

The docker compose structure itself is pretty advanced, but won't get the whole system working yet.
Things that work:
-django development server for http requests
- Tor hidden service
- connection to redis container
- connection to the database container

Things that don't work
- calls to Daphne sockets throw an error
- also I haven't gone through the celery parts just yet .
-pretty much everything else

**Comment by rootzoll** [comment]
@raulcano so I wanna go into release candidate phase for v1.9 within the next days. So I wil start to deactivate IP2Tor feature for now with the possibility to maybe get revived in future versions.

**Comment by raulcano** [comment]
Thanks for the heads up. I'm actively working on the revamped IP2TOR shop, but it won't be ready soon enough.
I'll let you know once I'm closer to a stable version.
Cheers!

**Comment by rootzoll** [comment]
@raulcano https://ip2tor.com/#tor_bridges seems to time out .. any update on the state of the service. BTW sorry for the delayed v1.9.0 release - but hopefully we now getting closer to a final release.

**Comment by raulcano** [comment]
Hi! Sorry about this. I'll need to check what happened this weekend and report back.

**Comment by rootzoll** [comment]
@raulcano any idea yet whats wrong?

**Comment by raulcano** [comment]
I think it's related to the certificates. Will try again tomorrow...

rootzoll ***@***.***> schrieb am Mo., 8. Mai 2023, 21:08:

**Comment by raulcano** [comment]
Hi @rootzoll, I'm having trouble finding the time to fix this, sorry. If you can intend to launch a new release please deactivate my service. As soon as I fix it and leave it on a more stable way I'll let you know. Cheers!

**Comment by rootzoll** [comment]
@raulcano OK looks like we finally will release v1.9.0 this week and so also the ip2tor.com as a subscribe option ... but it still has the problem when I test it: `('failed HTTP code', {'status_code': 502, 'timestamp': '2023-05-23T13:09:13Z'})`

**Comment by raulcano** [comment]
Hi @Rootzoll, it was impossible for me to work on that during this month,
but I'm actively trying to solve this issue this weekend. Hopefully I'll
manage...
Also, congrats on the new release!

**Comment by raulcano** [comment]
Ok, I think the problem is solved. There was a huge log file that broke
Redis and everything else with it.
I will take care of that in the server and document it in the github page

**Comment by rootzoll** [comment]
@raulcano I tested the 24h bridge and it worked fine - If you like you can make a tweet about the new service now available thru the RaspiBlitz SSH subscription menus and I am happy to retweet the annoucement.

**Comment by raulcano** [comment]
Ok, will do in a second. Thanks!
