### ISSUE TITLE
Reduce bloat of the SDcard image

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#3427]
The bitcoin user directory has a lot of data left over from compiling the CLN GRPC plugin:
```
₿ sudo du -hd1 /home/bitcoin
261M	/home/bitcoin/bitcoin
4.0K	/home/bitcoin/cl-plugins-enabled
1.7G	/home/bitcoin/cl-plugins-available
4.0K	/home/bitcoin/scl-plugins-enabled
40K	/home/bitcoin/.config
562M	/home/bitcoin/lightning
248M	/home/bitcoin/.cargo
106M	/home/bitcoin/.local
1.4G	/home/bitcoin/.rustup
4.0K	/home/bitcoin/tcl-plugins-enabled
36K	/home/bitcoin/.gnupg
482M	/home/bitcoin/.cache
4.9G	/home/bitcoin
```

Can be deleted after (in) the SDcard build:
```
/home/bitcoin/.rustup
/home/bitcoin/.cargo/
/home/bitcoin/.cache
```

Then need to test if there is anything else needed from here:
```
sudo du -ahd1 /home/bitcoin/cl-plugins-available/cln-grpc/debug/
4.0K	/home/bitcoin/cl-plugins-available/cln-grpc/debug/cln-grpc.d
0	/home/bitcoin/cl-plugins-available/cln-grpc/debug/.cargo-lock
336M	/home/bitcoin/cl-plugins-available/cln-grpc/debug/incremental
4.0K	/home/bitcoin/cl-plugins-available/cln-grpc/debug/examples
1.1G	/home/bitcoin/cl-plugins-available/cln-grpc/debug/deps
3.4M	/home/bitcoin/cl-plugins-available/cln-grpc/debug/.fingerprint
199M	/home/bitcoin/cl-plugins-available/cln-grpc/debug/build
```
apart from the binary:
```
/home/bitcoin/cl-plugins-available/cln-grpc/debug/cln-grpc
```

**Comment by rootzoll** [comment]
Added to a lot of `git clones` the parameter `--single-branch` to reduce the amount of data a git repo with a lot of branches might take

**Comment by rootzoll** [comment]
`--single-branch` seems to make trouble for some scripts (with git verify), will use it selectivly. Also will now enforce a 32GB sd card after we recommended upgrade from 16GB to 32GB since 1.5

**Comment by rootzoll** [comment]
OK I tested with the cleanup cl install scripts ... Spark & Sparko work, but RTL has some socket issues. Can this be caused by the clean ups? Or just a cRTL thing to investigate seperatly?

**Comment by rootzoll** [comment]
OK merged. Closing issue for now.
