### ISSUE TITLE
WebUi Installscripts delivering version -> API -> WebUI

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#3429]
https://github.com/cstenglein/raspiblitz-web/blob/master/src/utils/availableApps.ts

**Comment by rootzoll** [comment]
@cstenglein whats the status here - still targeting for 1.9. or should I push up to 1.10?

**Comment by cstenglein** [comment]
You & @fusion44 need to decide that since most of the work is on your part:

- RaspiBlitz: providing the version info somewhere so that blitzAPI can get it
- BlitzAPI: providing the info somewhere
- webUI: using the info, which is the least work IMO

**Comment by rootzoll** [comment]
The RaspiBlitz already provised this information in the cache:
```
admin@192.168.178.61:~ ₿ cache export | grep "1.8.0"
raspiBlitzVersion="1.8.0"
codeVersion="1.8.0"
```

Best would be to use the `codeVersion` field, because it is the most direct source of the code version. @fusion44 can you provide this information thru the API?

**Comment by fusion44** [comment]
Sure, `raspiBlitzVersion` is already being [delivered](https://github.com/fusion44/blitz_api/blob/36be181e77291da242de9b430285b9fd05011d1c/app/system/impl/raspiblitz.py#L65) correctly. Adding `codeVersion` won't be a problem.

**Comment by fusion44** [comment]
@rootzoll What is the difference between `raspiBlitzVersion` and `codeVersion`?

**Comment by rootzoll** [comment]
`raspiBlitzVersion` comes from the config file - says which version the config is from. `codeVersion` is directly from the code files. Normally both are the same ... just on starting a recovery `raspiBlitzVersion` could differ from `codeVersion`. `codeVersion` is the the better source to use in this case.

**Comment by cstenglein** [comment]
So `codeVersion` is specific to the app? Or is that the version of the installscripts?

If it's the second case, then this issue isn't what I thought it would be. I thought the app versions are provided by raspiblitz to the UI. Can we open another issue in that case?

**Comment by rootzoll** [comment]
Ah OK sorry .. I now added version information to the status of the install scripts for the apps (already merged into dev). Next step is to add this to the API ..@fusion44 I will provide an PR for that.

**Comment by rootzoll** [comment]
OK PR is open to be merged for Blitz API: https://github.com/fusion44/blitz_api/pull/174

@cstenglein basically you can already implement this on webUI side now .. just expect that a request to `http://192.168.178.147/api/latest/apps/status` will now also have in here:
```
  {
    "id": "thunderhub",
    "installed": true,
    "status": "online",
    "address": "http://192.168.178.147:3010",
    "httpsForced": "0",
    "httpsSelfsigned": "1",
    "hiddenService": "653obthlroknoz6lofrnq57molekgqk72hcawchxuynqzps5sael2nqd.onion",
    "authMethod": "password_b",
    "details": {},
    "error": ""
  },
  {
```
a `version` field that will have a version string to be displayed.

**Comment by DocBrown101** [comment]
I'm not sure if this fits here, but with the version raspiblitz-min-v1.9.0rc1 the API and the webUI can not be activated.

![image](https://user-images.githubusercontent.com/11892773/209932700-e9a2f8a6-475f-4bee-ae84-ff0e766785e0.png)
A success message is given, but it is false and visible far too quickly.

**Comment by rootzoll** [comment]
- [x] retest install API+UI on min image

**Comment by rootzoll** [comment]
Tested with v1.9.0rc4 minimal image. API & WebUI installs and works after reboot. Also Verisons of API & WebUI get shown under settings and are part of the debug report. Closing issue for v1.9.0 release.
