### ISSUE TITLE
Python Error on version 1.8.0c 

### ISSUE THREAD

**Issue by willheisenberg** [raspiblitz/raspiblitz#3434]
I had an python error before an tried to solve it by updating python and pip but this leaded to another issue:

Nov 11 12:14:23 raspberrypi python[909]: INFO:     Started server process [909]
Nov 11 12:14:23 raspberrypi python[909]: INFO:uvicorn.error:Started server process [909]
Nov 11 12:14:23 raspberrypi python[909]: INFO:     Waiting for application startup.
Nov 11 12:14:23 raspberrypi python[909]: INFO:uvicorn.error:Waiting for application startup.
Nov 11 12:14:24 raspberrypi python[909]: INFO:     Application startup complete.
Nov 11 12:14:24 raspberrypi python[909]: INFO:uvicorn.error:Application startup complete.
Nov 11 12:14:24 raspberrypi python[909]: INFO:     Uvicorn running on http://0.0.0.0:11111 (Press CTRL+C to quit)
Nov 11 12:14:24 raspberrypi python[909]: INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:11111 (Press CTRL+C to quit)
Nov 11 12:15:23 raspberrypi python[909]: ERROR:root:Unknown answer from Bitcoin Core. Reason: Internal Server Error
Nov 11 12:16:54 raspberrypi python[909]: WARNING:root:LND_GRPC: Unhandled initialization event: {'state': <LnInitState.BOOTSTRAPPING: 'bootstrapping'>, 'msg': 'Connected but waiting to start, RPC services not avaLnInitState.BOOTSTRAPPING: 'bootstrapping'>, 'msg': 'Connected but waiting to start, RPC services not available'}

Has anybody something similar or any idea what the problem is?

**Comment by cstenglein** [comment]
> Connected but waiting to start, RPC services not available

Have you unlocked the LND wallet? Looks like it's waiting for that.

**Comment by willheisenberg** [comment]
The error before btw showed this:
python in version: version checked. upgrade: False

**Comment by willheisenberg** [comment]
> > Connected but waiting to start, RPC services not available
> 
> Have you unlocked the LND wallet? Looks like it's waiting for that.

By unlocking you mean  exactly what? I just opened a channel which worked before. Now not sure have to test it.

**Comment by willheisenberg** [comment]
The channel is still working

**Comment by cstenglein** [comment]
Discussed on another channel:

API seems to work, do you know if there is an issue there @fusion44 or can we close this?

**Comment by fusion44** [comment]
I'm not aware of a problem currently.

**Comment by cstenglein** [comment]
@willheisenberg Can you check again on 1.9.0? Should be fixed AFAIK.

Closing this for now, if it still happens, please re-open.

**Comment by willheisenberg** [comment]
Heyi cannot because I just set up my own node now. So everything from the scratch
