### ISSUE TITLE
Incompatible python package for armhf armbian buster

### ISSUE THREAD

**Issue by rek79** [raspiblitz/raspiblitz#3435]
https://github.com/rootzoll/raspiblitz/blob/1a04af5c99c2b74a89a0f9a7f0398dc37e602f3a/build_sdcard.sh#L318

Building under Armbian Buster Odroid HC2, I get the following error:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-api-core 2.10.2 requires googleapis-common-protos<2.0dev,>=1.56.2, but you have googleapis-common-protos 1.53.0 which is incompatible.
google-api-core 2.10.2 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.20.1 which is incompatible.
```
I changed following two dependencies which seemed to work:
```
googleapis-common-protos==1.56.4
protobuf==4.21.9
```

`python_libs="grpcio==1.42.0 googleapis-common-protos==1.56.4 toml==0.10.2 j2cli==0.3.10 requests[socks]==2.21.0 protobuf==4.21.9"`

**Comment by rek79** [comment]
I'm not sure if this was due to installing googleapis manually after patching from 1.7.1 to 1.8 did not succeed.  I could have installed a later version that was incompatible.

**Comment by rootzoll** [comment]
@openoms is there anyting special building these under "Armbian Buster Odroid HC2"?

**Comment by rek79** [comment]
@rootzoll I've been checking build_sdcard.sh line by line.  Besides the issues above I've found that the standard repo for apt-get is limited to python 3.7

```
admin@odroidxu4:/dev$ apt-cache policy python3
python3:
  Installed: 3.7.3-1
  Candidate: 3.7.3-1
  Version table:
 *** 3.7.3-1 500
        500 http://deb.debian.org/debian buster/main armhf Packages
        100 /var/lib/dpkg/status
```
I was able to install python 3.10 from source.  I'm wondering if we should add that method as a fallback when checking for python 3.8, 3.9, and 3.10 in the build script.  We could also check if version 3.7 or older is installed or marked as candidate, and then use Deadsnakes PPA to install 3.8 or newer:

```
PythonInstalledMajorVersion=$(apt-cache policy python3 | grep "Installed: " | cut -d ":" -f 2 | cut -d "." -f 1)
PythonInstalledMinorVersion=$(apt-cache policy python3 | grep "Installed: " | cut -d ":" -f 2 | cut -d "." -f 2)
PythonCandidateMajorVersion=$(apt-cache policy python3 | grep "Candidate: " | cut -d ":" -f 2 | cut -d "." -f 1)
PythonCandidateMinorVersion=$(apt-cache policy python3 | grep "Candidate: " | cut -d ":" -f 2 | cut -d "." -f 2)
```
Check if candidate version is less than 3.8, and if so, use deadsnakes PPA to get updated version of Python3:
```
sudo apt install software-properties-common -y
sudo add-apt-repository ppa:deadsnakes/ppa -y
sudo apt update
sudo apt install python3.10 -y
```
I'm thinking that we could put this logic right before:
https://github.com/rootzoll/raspiblitz/blob/6e426871a9c24854e67be0ddf8ccd816296319a0/build_sdcard.sh#L305
That way apt_install grabs the correct python dependencies for the updated version.

This would help keep older hardware compatible with the standard build script.  Let me know your thoughts and I can work on this a bit more if deemed valuable.

**Comment by rek79** [comment]
Looks like `sysbench` is also not available for armhf buster.  I'll keep compiling a list and start to suggest fallback code in a new PR to install from source or alt PPA.
