### ISSUE TITLE
After 1.8.0 Update USB Backup is not possible

### ISSUE THREAD

**Issue by lazyrudi** [raspiblitz/raspiblitz#3436]
I tried to create a USB Backup and ran in the problem that more than one backup targets are connected. Than I tried a backup without the USB and got the information the Zram was detected as Backup USB device... What do I have to do to backup my Raspiblitz to my external USB drive?
<img width="682" alt="Bildschirm­foto 2022-11-12 um 16 48 25" src="https://user-images.githubusercontent.com/110254141/201486016-9c275924-f0da-4b0a-8602-7b093bbd9d8a.png">
<img width="682" alt="Bildschirm­foto 2022-11-12 um 17 42 07" src="https://user-images.githubusercontent.com/110254141/201486040-ba72da73-c902-4608-bfc2-e3b2c027cbd5.png">

**Comment by fjone** [comment]
Hi there!
I'm having the same issues with version 1.8.0c running CLN.

There is no option to setup a automatic backup of the sqlite3 file on a external thumbdrive.

Also tried to format a thumbdrive with ext4 but the system don't discover the new thumbdrive in the /mnt directory

**Comment by cwgriswold** [comment]
Delete the zram package if you already have a swap partition. Check with lsblk.

 sudo /home/admin/download/zram-swap/zram-swap.sh stop
 sudo /home/admin/download/zram-swap/install.sh —uninstall

**Comment by openoms** [comment]
The fix is part of this PR for the next release: https://github.com/rootzoll/raspiblitz/pull/3393

**Comment by lazyrudi** [comment]
Perfect now it works. Will this be fixed in 1.8.1, or do I have to uninstall zram again?

**Comment by rootzoll** [comment]
@lazyrudi see changed file https://github.com/rootzoll/raspiblitz/pull/3393/files#diff-6323998d129bbc54941c000be2316e847564ddf42bcfb454559f5e8b78831d9b

its on final testing but it should fix with release of next version (which was renamed from 1.8.1 to 1.9.0) with zram running

**Comment by lazyrudi** [comment]
Thanks for the Info !!! 👍🏻﻿
