### ISSUE TITLE
lightning wallet locked

### ISSUE THREAD

**Issue by maximotodev** [raspiblitz/raspiblitz#3449]
![Screenshot from 2022-11-16 10-47-25](https://user-images.githubusercontent.com/94984249/202233031-84b043a5-6b07-4be2-9520-3a203640b060.png)

my node is failing to unlock the lightning wallet, any idea how to fix this?

thanks in advance

**Comment by rootzoll** [comment]
On the terminal - can you simply try: `lncli unlock`?

**Comment by maximotodev** [comment]
output:
![Screenshot from 2022-11-16 11-23-51](https://user-images.githubusercontent.com/94984249/202236274-30b008e7-6e52-444e-b222-c0ff79613d63.png)

**Comment by rootzoll** [comment]
Please restart your raspiblitz once and then run from command line `menu` and go `CONNECT` > `RESET` (recreate LND Macaroons & TLS certs)

**Comment by maximotodev** [comment]
![Screenshot from 2022-11-16 11-31-58](https://user-images.githubusercontent.com/94984249/202238375-362939d3-5ebe-41ae-af58-5411b5443f3a.png)
there is no reset option :(

**Comment by rootzoll** [comment]
Ah OK - your using core lightning (not LND) ..  @openoms can you take a look why CLN wallet does not unlock?

**Comment by openoms** [comment]
The problem is as in the in the OP,  lightningd fails with a Tor error.
@ShogunWarlord can you enter the CLN menu again and post if the error is the same after restart?

**Comment by maximotodev** [comment]
![Screenshot from 2022-11-16 23-41-18](https://user-images.githubusercontent.com/94984249/202357416-aed3b2e8-6642-4ed2-9425-5cbd9b9f90b8.png)
wallet unlocked, thank you guys!
