### ISSUE TITLE
Can not mount HDD

### ISSUE THREAD

**Issue by ronledfordjr** [raspiblitz/raspiblitz#3457]
I am doing a new install to old equipment. I was having issues with updating to latest version.

https://l.termbin.com/zwh8z

**Comment by rootzoll** [comment]
OK I can see `state--> errorHDD` 

This is not an SSD but an old HDD right?

Can you post the `cat /home/admin/raspiblitz.log` and outout if `sudo df`

**Comment by cstenglein** [comment]
Since there was no further answer, closing for now.
