### ISSUE TITLE
No connection

### ISSUE THREAD

**Issue by willheisenberg** [raspiblitz/raspiblitz#3458]
Its the third time i flashed raspiblitz ob my pi 4 and now the third time there is no connection with ssh. There is no ping nothing. Turn off and on doesnt help as well. Any suggestions?

**Comment by cwgriswold** [comment]
Use balenaetcher and let it check the sd card after flash. I figured that when balenaetcher finds  an issue after flash raspi isn’t starting. Try a different sd card. Also check if lan leds flashing when powered on.

**Comment by willheisenberg** [comment]
I'm gonna to do that later. But btw it's strange because it works for a while. This time it worked like 1 week and than today again no connection possible.

**Comment by willheisenberg** [comment]
With balena i couldnt find anything. But for sure with this sd card nothing is booting anymore, because only the red led is on and the yellow one is not flashing.
I use now a different sd card ans lets see what happens after a while.

**Comment by openoms** [comment]
Likely a hardware issue. Make sure to use a new Endurance type SDcard and flash again.

**Comment by willheisenberg** [comment]
Thx that worked :)
