### ISSUE TITLE
Where to find bitcoin rpcuser?

### ISSUE THREAD

**Issue by tibbar-etihw** [raspiblitz/raspiblitz#346]
Trying to connect to my bitcoin node from a mobile wallet. I have no idea where to find or set the rpcuser. Any help is greatly appreciated.

**Comment by rootzoll** [comment]
rpc is already is already active - see bitcoind config:
cat /mnt/hdd/bitcoin/bitcoin.conf

A screenshot of the mobile wallet input/connect screen would be helpfull to give more details.

**Comment by tibbar-etihw** [comment]
Thank you so much @rootzoll . Found the config file with the info I needed. Never used a CLI before so thank you very much.
