### ISSUE TITLE
LND uninstall does not run cleanly

### ISSUE THREAD

**Issue by dennisreimann** [raspiblitz/raspiblitz#3461]
When running `config.scripts/lnd.install.sh off mainnet`  one encounters the following error:

```sh
config.scripts/lnd.install.sh off mainnet
# Configuring the LND instance on mainnet
# removing mainnet lnd service (if active)
# lnd --> off
# LND is REMOVED as default lightning implementation
# blitz.conf.sh set lightning 
# FAIL: missing parameter
```

The missing parameter is caused by the [`blitz.conf.sh set lightning ""`](https://github.com/rootzoll/raspiblitz/blob/15b460098c4efc841a9ee86fdb5bc91c12361e34/home.admin/config.scripts/lnd.install.sh#L551) command, which does not seem to like empty inputs. I think it should be the `delete` command instead of `set`.

Other than that the uninstall process worked.

**Comment by rootzoll** [comment]
Thx. Its already changed in the `dev` branch for next release: https://github.com/rootzoll/raspiblitz/blob/5fb809c2ec8f061a03abca385c7d8e9316f84c50/home.admin/config.scripts/lnd.install.sh#L555
