### ISSUE TITLE
[v1.9.0dev-2022-11-27] WebUI install script doesn't show local ip at the end

### ISSUE THREAD

**Issue by cstenglein** [raspiblitz/raspiblitz#3485]
When turning the webUI off & on again (with the current dev image), the comment at the end says:

```
# The WebUI is now available under:
# http://[LOCALIP]
```

It should show the local IP instead of the placeholder.

**Comment by openoms** [comment]
we often use:
```
localip=$(hostname -I | awk '{print $1'}'
```
to get the value

**Comment by ChuckNorrison** [comment]
should be fixed here:
https://github.com/rootzoll/raspiblitz/pull/3496
