### ISSUE TITLE
[amd64][Research] Blockchain backup - copy with LVM snapshots

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#3488]
Snapshot, copy and clone is already [possible on ZFS ](https://github.com/openoms/bitcoin-tutorials/blob/master/zfs/sync-chain.md) and likely on BTRFS, but the amd64 image LVM volume might allow this on EXT4 as well.

Might be a good option to use for the Data disk/partition as well.

https://tldp.org/HOWTO/LVM-HOWTO/snapshots_backup.html

**Comment by rootzoll** [comment]
Closing because we tend to delegate Snapshotting (with ZFS or BTRFS) to outside of RaspiBlitz - see: https://github.com/raspiblitz/raspiblitz/issues/2045#issuecomment-2471845122
