### ISSUE TITLE
An error occured: server is still in the process of starting

### ISSUE THREAD

**Issue by Undergotten** [raspiblitz/raspiblitz#3492]
Hi all! My RaspiBlitz node was offline for a few months because of personal problems. Got it back up and running, and I would like to close a channel I left unattended and get my funds back so I can start again, but I keep getting this error. I was running 1.7 and upgraded to 1.8 because I thought that might be the problem, but I'm still getting this message whenever I try to close the channel. Any ideas what might be causing this?

I'm not very technical, but I can give logs to help if someone can tell me what directory on the raspiblitz they are in. Thanks in advance

**Comment by rootzoll** [comment]
Does this problem still persist? Which version of LND are you running?

**Comment by Undergotten** [comment]
> 

Yes, it still persists. I'm not sure how to tell what version I'm running. I just flashed the image to the pi4. I got the error message trying to close the channel in both Thunderhub and in the RaspiBlitz WEBui main menu. 

I just tried to force close it in RideTheLightning and did not recieve an error. I will update you on if that changes things. 

How can I check what version of LND I'm running? I can SSH to the pi4 RaspiBlitz, but the menu doesn't load. It just stays at 100% syncing. If I go to CLI I can tell you, if you let me know what directory to look in for logs/data. 

Thank you for your help. You do amazing work.

**Comment by rootzoll** [comment]
> How can I check what version of LND I'm running? I can SSH to the pi4 RaspiBlitz, but the menu doesn't load. It just stays at 100% syncing. If I go to CLI I can tell you, if you let me know what directory to look in for logs/data.

OK - it its syning its not ready to work with thunderhub or RTL. In SSH you can CTRL+c to exit to the terminal and then type `menu`. Under INFO you should see LND Version. Please report back here.

**Comment by Undergotten** [comment]
> 

Been using this thing for a year and had no idea about the "menu" command. That's very handy. Thank you! 

I am running LND 0.15.0-beta. Is that the latest? 

Edit: I can see now, looking at a different thread, that I should be running 1.5.4-beta. How do I upgrade LND? "sudo apt update/upgrade" does nothing, and that's the extent of my knowledge. Haha. 

Edit 2: Ok, I see there is an LND update option in the menu. Going to try the "reckless" update. I'll report back how it goes. Thanks for the help, again, ROOTZOLL! 

-Undergotten

**Comment by rootzoll** [comment]
If you run into further problems (updating the running system) just do the normal system update way by flashing a new sd card with the 1.8.0c image you can download here: https://github.com/rootzoll/raspiblitz#downloading-the-software .. it contains all the LND bugfixes.
