### ISSUE TITLE
PasswordA not working after rebuild

### ISSUE THREAD

**Issue by McX424** [raspiblitz/raspiblitz#3497]
I was forced to rebuild my SD card after a reboot failed to boot back up again. After this rebuild it ran through the process and all is synced up and running. The only issue is that I am unable to log in where the Password A is required. RTL using password B and C are both fine. 

I have tried my old password as well as the default password but neither are working. Is there a way to restore my Password A?

**Comment by ChuckNorrison** [comment]
in the process of reflash you got prompted for a new Password A. If you did not remember this password, reflash again till the prompt for password A gets displayed and follow instructions.

Till that point you can login as admin and the default password.
