### ISSUE TITLE
Static IP address?

### ISSUE THREAD

**Issue by CommanderPoe** [raspiblitz/raspiblitz#350]
Used to have the Raspibolt config now playing with the raspiblitz I was wondering what happens with the internal IP address in case it changes for users that dont use LCD screen? 

I have not read anything in the guide regarding that issue.

**Comment by rootzoll** [comment]
normally with the LCD its easy to see if local IP changes and with dynamic IP its more flexible because you can change networks easy. But I can add something about setting a static address to the FAQ?. What text would you recommend?

**Comment by CommanderPoe** [comment]
Oh thanks a lot for the answer, unfortunately Im not a techie person, but that was one of the first things that came to my mind when i decided to play with this guide since i dont have an LCD screen, I have some friends who started using the raspiblitz configuration and they dont own an LCD screen but i didn't raised the question. I thought you were maybe the right person to ask this kind of questions in case someone ( like me and my friends ) decided to use the guide without the LCD screen.

**Comment by rootzoll** [comment]
The RaspiBolt had a chapter of network settings ... including static IP:
https://github.com/Stadicus/guides/blob/master/raspibolt/raspibolt_20_pi.md#connecting-to-the-network
