### ISSUE TITLE
Random letters on SSH menu after reboot & services install

### ISSUE THREAD

**Issue by HenrySabio** [raspiblitz/raspiblitz#3502]
Want to start off and first confirm - my node is running with NO current issues.
The issue is present via terminal when i SSH into my raspiblitz and pretty much every menu i go into - the terminal view has these random characters going around the edge of every window/box.

Multiple reboots and even removing/re-adding things i installed doesn't change anything either.

<img width="765" alt="Screenshot 2022-12-08 at 12 52 51 PM" src="https://user-images.githubusercontent.com/41017185/206528268-47b30fca-3ef2-461e-a3eb-ae8583cbe933.png">

**Comment by ChuckNorrison** [comment]
Looks like your terminal client to ssh into does not support those characters... the q's should be displayed as a border or long line. Some unicode settings available on this terminal? 

You could try this command prior ssh into the blitz (linux only)

`export LANG=$LANG.UTF-8`

**Comment by HenrySabio** [comment]
@ChuckNorrison that solved it!
Thank you, so strange that it wasn't initially an issue.
Used a minor variant for my macOS terminal: `export LANG=en_US.UTF-8`
