### ISSUE TITLE
Port Forwarding ?

### ISSUE THREAD

**Issue by LexKell** [raspiblitz/raspiblitz#3516]
**New Flash Install v1.8.0 - 
I can't connect to LND or ElectRS with the new install. Ports are open. Any other glaring issues?**

blitzversion: 1.8.0
chainnetwork: bitcoin / main
 

*** SETUPPHASE / BOOTSTRAP ***
see logs: cat /home/admin/raspiblitz.log
setupPhase--> done
state--> ready

*** BACKGROUNDSERVICE ***
to monitor Background service call: sudo journalctl -f -u background

*** BLOCKCHAIN (MAINNET) SYSTEMD STATUS ***
● bitcoind.service - Bitcoin daemon
     Loaded: loaded (/etc/systemd/system/bitcoind.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2022-12-14 03:09:49 GMT; 9min ago
    Process: 6566 ExecStartPre=/home/admin/config.scripts/blitz.systemd.sh log blockchain STARTED (code=exited, status=0/SUCCESS)
    Process: 6571 ExecStartPre=/bin/chgrp bitcoin /mnt/hdd/bitcoin (code=exited, status=0/SUCCESS)
    Process: 6572 ExecStart=/usr/local/bin/bitcoind -daemonwait -conf=/mnt/hdd/bitcoin/bitcoin.conf -datadir=/mnt/hdd/bitcoin -debuglogfile=/mnt/hdd/bitcoin/debug.log (code=exited, status=0/SUCCESS)
   Main PID: 6573 (bitcoind)
      Tasks: 18 (limit: 9353)
        CPU: 1min 34.440s
     CGroup: /system.slice/bitcoind.service
             └─6573 /usr/local/bin/bitcoind -daemonwait -conf=/mnt/hdd/bitcoin/bitcoin.conf -datadir=/mnt/hdd/bitcoin -debuglogfile=/mnt/hdd/bitcoin/debug.log

Dec 14 03:09:19 raspberrypi systemd[1]: Starting Bitcoin daemon...
Dec 14 03:09:49 raspberrypi systemd[1]: Started Bitcoin daemon.

*** LAST BLOCKCHAIN (MAINNET) ERROR LOGS ***
sudo journalctl -u bitcoind -b --no-pager -n8
-- Journal begins at Mon 2022-12-12 19:49:22 GMT, ends at Wed 2022-12-14 03:19:45 GMT. --
Dec 14 03:09:19 raspberrypi systemd[1]: Starting Bitcoin daemon...
Dec 14 03:09:49 raspberrypi systemd[1]: Started Bitcoin daemon.

*** LAST BLOCKCHAIN (MAINNET) 20 INFO LOGS ***
sudo tail -n 20 /mnt/hdd/bitcoin/debug.log
2022-12-14T03:09:49Z 2 block-relay-only anchors will be tried for connections.
2022-12-14T03:09:49Z init message: Starting network threads…
2022-12-14T03:09:49Z DNS seeding disabled
2022-12-14T03:09:49Z net thread start
2022-12-14T03:09:49Z addcon thread start
2022-12-14T03:09:49Z msghand thread start
2022-12-14T03:09:49Z opencon thread start
2022-12-14T03:09:49Z tor: Got service ID 6yhf4h6g2vym7emsvqtf3l4ske4uk3dlk5utdwyoiug5ckefhqqkslid, advertising service ***.onion:8333
2022-12-14T03:09:49Z AddLocal(***.onion:8333,4)
2022-12-14T03:09:49Z Leaving InitialBlockDownload (latching to false)
2022-12-14T03:09:49Z init message: Done loading
2022-12-14T03:10:04Z Imported mempool transactions from disk: 2878 succeeded, 0 failed, 0 expired, 0 already there, 0 waiting for initial broadcast
2022-12-14T03:10:04Z loadblk thread exit
2022-12-14T03:16:28Z New outbound peer connected: version: 70016, blocks=767321, peer=6 (outbound-full-relay)
2022-12-14T03:16:34Z New outbound peer connected: version: 70016, blocks=767321, peer=7 (outbound-full-relay)
2022-12-14T03:16:46Z New outbound peer connected: version: 70016, blocks=767321, peer=8 (outbound-full-relay)
2022-12-14T03:16:52Z New outbound peer connected: version: 70016, blocks=767321, peer=9 (outbound-full-relay)
2022-12-14T03:18:03Z New outbound peer connected: version: 70016, blocks=767321, peer=13 (outbound-full-relay)
2022-12-14T03:18:41Z Socks5() connect to ***.onion:8333 failed: host unreachable
2022-12-14T03:18:49Z New outbound peer connected: version: 70016, blocks=767321, peer=14 (outbound-full-relay)

*** LND (MAINNET) SYSTEMD STATUS ***
● lnd.service - Lightning Network Daemon
     Loaded: loaded (/etc/systemd/system/lnd.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Wed 2022-12-14 03:18:46 GMT; 59s ago
    Process: 78677 ExecStartPre=/home/admin/config.scripts/lnd.check.sh prestart mainnet (code=exited, status=0/SUCCESS)
    Process: 78931 ExecStart=/usr/local/bin/lnd --configfile=/home/bitcoin/.lnd/lnd.conf (code=exited, status=1/FAILURE)
   Main PID: 78931 (code=exited, status=1/FAILURE)
        CPU: 4.950s

Dec 14 03:18:46 raspberrypi systemd[1]: lnd.service: Consumed 4.950s CPU time.

*** LAST LND (MAINNET) ERROR LOGS ***
sudo journalctl -u lnd -b --no-pager -n12
-- Journal begins at Mon 2022-12-12 19:49:22 GMT, ends at Wed 2022-12-14 03:19:45 GMT. --
Dec 14 03:17:42 raspberrypi systemd[1]: lnd.service: Failed with result 'exit-code'.
Dec 14 03:17:42 raspberrypi systemd[1]: Failed to start Lightning Network Daemon.
Dec 14 03:17:42 raspberrypi systemd[1]: lnd.service: Consumed 4.288s CPU time.
Dec 14 03:18:42 raspberrypi systemd[1]: lnd.service: Scheduled restart job, restart counter is at 8.
Dec 14 03:18:42 raspberrypi systemd[1]: Stopped Lightning Network Daemon.
Dec 14 03:18:42 raspberrypi systemd[1]: lnd.service: Consumed 4.288s CPU time.
Dec 14 03:18:42 raspberrypi systemd[1]: Starting Lightning Network Daemon...
Dec 14 03:18:46 raspberrypi lnd[78931]: unable to open databases: unable to open graph DB: channel db cannot revert to prior version
Dec 14 03:18:46 raspberrypi systemd[1]: lnd.service: Main process exited, code=exited, status=1/FAILURE
Dec 14 03:18:46 raspberrypi systemd[1]: lnd.service: Failed with result 'exit-code'.
Dec 14 03:18:46 raspberrypi systemd[1]: Failed to start Lightning Network Daemon.
Dec 14 03:18:46 raspberrypi systemd[1]: lnd.service: Consumed 4.950s CPU time.

*** LAST 30 LND (MAINNET) INFO LOGS ***
sudo tail -n 30 /mnt/hdd/lnd/logs/bitcoin/mainnet/lnd.log
2022-12-14 03:18:43.288 [DBG] ARPC: Autopilot RPC server successfully register with root gRPC server
2022-12-14 03:18:43.288 [DBG] PRPC: Peers RPC server successfully register with root gRPC server
2022-12-14 03:18:43.288 [DBG] RRPC: Router RPC server successfully register with root gRPC server
2022-12-14 03:18:43.288 [INF] RPCS: RPC server listening on *.*.*.*:10009
2022-12-14 03:18:43.291 [DBG] NTFR: ChainNotifier REST server successfully registered with root REST server
2022-12-14 03:18:43.291 [DBG] IRPC: Invoices REST server successfully registered with root REST server
2022-12-14 03:18:43.291 [DBG] NRPC: Neutrino REST server successfully registered with root REST server
2022-12-14 03:18:43.291 [DBG] VRPC: Versioner REST server successfully registered with root REST server
2022-12-14 03:18:43.297 [DBG] SGNR: Signer REST server successfully registered with root REST server
2022-12-14 03:18:43.298 [DBG] WLKT: WalletKit REST server successfully registered with root REST server
2022-12-14 03:18:43.298 [DBG] ARPC: Autopilot REST server successfully registered with root REST server
2022-12-14 03:18:43.298 [DBG] PRPC: Peers REST server successfully registered with root REST server
2022-12-14 03:18:43.298 [DBG] RRPC: Router REST server successfully registered with root REST server
2022-12-14 03:18:43.299 [INF] RPCS: gRPC proxy started at *.*.*.*:8080
2022-12-14 03:18:43.299 [INF] LTND: Opening the main database, this might take a few minutes...
2022-12-14 03:18:43.299 [INF] LTND: Opening bbolt database, sync_freelist=true, auto_compact=true
2022-12-14 03:18:43.299 [INF] CHDB: Not compacting database file at /home/bitcoin/.lnd/data/graph/mainnet/channel.db, it was last compacted at 2022-12-12 02:54:19.264381486 +0000 GMT (48h24m24s ago), min age is set to 672h0m0s
2022-12-14 03:18:43.299 [INF] CHDB: Not compacting database file at /home/bitcoin/.lnd/data/chain/bitcoin/mainnet/macaroons.db, it was last compacted at 2022-12-12 02:54:19.45781145 +0000 GMT (48h24m23s ago), min age is set to 672h0m0s
2022-12-14 03:18:43.300 [INF] CHDB: Not compacting database file at /home/bitcoin/.lnd/data/graph/mainnet/sphinxreplay.db, it was last compacted at 2022-12-12 02:54:19.509617506 +0000 GMT (48h24m23s ago), min age is set to 672h0m0s
2022-12-14 03:18:43.300 [INF] LTND: Creating local graph and channel state DB instances
2022-12-14 03:18:43.322 [DBG] CHDB: Populating in-memory channel graph, this might take a while...
2022-12-14 03:18:44.229 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: waiting to start, RPC services not available
2022-12-14 03:18:46.246 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: waiting to start, RPC services not available
2022-12-14 03:18:46.279 [DBG] CHDB: Finished populating in-memory channel graph (took 2.949249711s, num_node_features=18391, num_nodes=18142, num_channels=172166)
2022-12-14 03:18:46.279 [INF] CHDB: Checking for schema update: latest_version=27, db_version=29
2022-12-14 03:18:46.279 [ERR] CHDB: Refusing to revert from db_version=29 to lower version=27
2022-12-14 03:18:46.291 [ERR] LTND: unable to open graph DB: channel db cannot revert to prior version
2022-12-14 03:18:46.291 [ERR] LTND: Shutting down because error in main method: unable to open databases: unable to open graph DB: channel db cannot revert to prior version
2022-12-14 03:18:46.294 [INF] LTND: Shutdown complete

*** CORE LIGHTNING (MAINNET) SYSTEMD STATUS ***
- not activated -

*** BLOCKCHAIN (TESTNET) SYSTEMD STATUS ***
- OFF by config -
*** LND (TESTNET) SYSTEMD STATUS ***
- OFF by config -

*** CORE LIGHTNING (TESTNET) SYSTEMD STATUS ***
- not activated -

*** BLOCKCHAIN (SIGNET) SYSTEMD STATUS ***
- OFF by config -
*** LND (SIGNET) SYSTEMD STATUS ***
- OFF by config -

*** CORE LIGHTNING (SIGNET) SYSTEMD STATUS ***
- not activated -

*** NGINX SYSTEMD STATUS ***
● nginx.service - A high performance web server and a reverse proxy server
     Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/nginx.service.d
             └─raspiblitz.conf
     Active: active (running) since Wed 2022-12-14 03:09:44 GMT; 10min ago
       Docs: man:nginx(8)
    Process: 9144 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
    Process: 9145 ExecStart=/usr/sbin/nginx -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
   Main PID: 9146 (nginx)
      Tasks: 5 (limit: 9353)
        CPU: 307ms
     CGroup: /system.slice/nginx.service
             ├─9146 nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
             ├─9147 nginx: worker process
             ├─9148 nginx: worker process
             ├─9149 nginx: worker process
             └─9150 nginx: worker process

Dec 14 03:09:43 raspberrypi systemd[1]: Starting A high performance web server and a reverse proxy server...
Dec 14 03:09:44 raspberrypi systemd[1]: Started A high performance web server and a reverse proxy server.

*** LAST NGINX LOGS ***
sudo journalctl -u nginx -b --no-pager -n20
-- Journal begins at Mon 2022-12-12 19:49:22 GMT, ends at Wed 2022-12-14 03:19:45 GMT. --
Dec 14 03:08:23 raspberrypi systemd[1]: Starting A high performance web server and a reverse proxy server...
Dec 14 03:08:25 raspberrypi nginx[652]: nginx: [emerg] host not found in upstream "mempool.space" in /etc/nginx/snippets/mempool.conf:39
Dec 14 03:08:25 raspberrypi nginx[652]: nginx: configuration file /etc/nginx/nginx.conf test failed
Dec 14 03:08:25 raspberrypi systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
Dec 14 03:08:25 raspberrypi systemd[1]: nginx.service: Failed with result 'exit-code'.
Dec 14 03:08:25 raspberrypi systemd[1]: Failed to start A high performance web server and a reverse proxy server.
Dec 14 03:09:43 raspberrypi systemd[1]: nginx.service: Scheduled restart job, restart counter is at 1.
Dec 14 03:09:43 raspberrypi systemd[1]: Stopped A high performance web server and a reverse proxy server.
Dec 14 03:09:43 raspberrypi systemd[1]: Starting A high performance web server and a reverse proxy server...
Dec 14 03:09:44 raspberrypi systemd[1]: Started A high performance web server and a reverse proxy server.
--> CHECK CONFIG: sudo nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

*** BLITZAPI SYSTEMD STATUS ***
● blitzapi.service - BlitzBackendAPI
     Loaded: loaded (/etc/systemd/system/blitzapi.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2022-12-14 03:08:24 GMT; 11min ago
   Main PID: 833 (python)
      Tasks: 9 (limit: 9353)
        CPU: 13.619s
     CGroup: /system.slice/blitzapi.service
             └─833 /usr/bin/python -m uvicorn app.main:app --port 11111 --host=*.*.*.* --root-path /api

Dec 14 03:18:44 raspberrypi python[833]: WARNING:root:LND_GRPC: Unhandled initialization event: {'state': <LnInitState.BOOTSTRAPPING: 'bootstrapping'>, 'msg': 'Connected but waiting to start, RPC services not available'}
Dec 14 03:18:46 raspberrypi python[833]: WARNING:root:LND_GRPC: Unhandled initialization event: {'state': <LnInitState.BOOTSTRAPPING: 'bootstrapping'>, 'msg': 'Connected but waiting to start, RPC services not available'}

*** LAST BLITZAPI LOGS ***
sudo journalctl -u blitzapi -b --no-pager -n20
-- Journal begins at Mon 2022-12-12 19:49:22 GMT, ends at Wed 2022-12-14 03:19:45 GMT. --
Dec 14 03:10:02 raspberrypi python[833]: WARNING:root:LND_GRPC: Unhandled initialization event: {'state': <LnInitState.BOOTSTRAPPING: 'bootstrapping'>, 'msg': 'Connected but waiting to start, RPC services not available'}
Dec 14 03:10:04 raspberrypi python[833]: WARNING:root:LND_GRPC: Unhandled initialization event: {'state': <LnInitState.BOOTSTRAPPING: 'bootstrapping'>, 'msg': 'Connected but waiting to start, RPC services not available'}
Dec 14 03:10:06 raspberrypi python[833]: WARNING:root:LND_GRPC: Unhandled initialization event: {'state': <LnInitState.BOOTSTRAPPING: 'bootstrapping'>, 'msg': 'Connected but waiting to start, RPC services not available'}
Dec 14 03:10:08 raspberrypi python[833]: WARNING:root:LND_GRPC: Unhandled initialization event: {'state': <LnInitState.BOOTSTRAPPING: 'bootstrapping'>, 'msg': 'Connected but waiting to start, RPC services not available'}
Dec 14 03:10:10 raspberrypi python[833]: WARNING:root:LND_GRPC: Unhandled initialization event: {'state': <LnInitState.BOOTSTRAPPING: 'bootstrapping'>, 'msg': 'Connected but waiting to start, RPC services not available'}
Dec 14 03:10:12 raspberrypi python[833]: WARNING:root:LND_GRPC: Unhandled initialization event: {'state': <LnInitState.BOOTSTRAPPING: 'bootstrapping'>, 'msg': 'Connected but waiting to start, RPC services not available'}
Dec 14 03:10:14 raspberrypi python[833]: WARNING:root:LND_GRPC: Unhandled initialization event: {'state': <LnInitState.BOOTSTRAPPING: 'bootstrapping'>, 'msg': 'Connected but waiting to start, RPC services not available'}
Dec 14 03:11:16 raspberrypi python[833]: WARNING:root:LND_GRPC: Unhandled initialization event: {'state': <LnInitState.BOOTSTRAPPING: 'bootstrapping'>, 'msg': 'Connected but waiting to start, RPC services not available'}
Dec 14 03:11:18 raspberrypi python[833]: WARNING:root:LND_GRPC: Unhandled initialization event: {'state': <LnInitState.BOOTSTRAPPING: 'bootstrapping'>, 'msg': 'Connected but waiting to start, RPC services not available'}
Dec 14 03:12:21 raspberrypi python[833]: WARNING:root:LND_GRPC: Unhandled initialization event: {'state': <LnInitState.BOOTSTRAPPING: 'bootstrapping'>, 'msg': 'Connected but waiting to start, RPC services not available'}
Dec 14 03:12:23 raspberrypi python[833]: WARNING:root:LND_GRPC: Unhandled initialization event: {'state': <LnInitState.BOOTSTRAPPING: 'bootstrapping'>, 'msg': 'Connected but waiting to start, RPC services not available'}
Dec 14 03:13:25 raspberrypi python[833]: WARNING:root:LND_GRPC: Unhandled initialization event: {'state': <LnInitState.BOOTSTRAPPING: 'bootstrapping'>, 'msg': 'Connected but waiting to start, RPC services not available'}
Dec 14 03:14:29 raspberrypi python[833]: WARNING:root:LND_GRPC: Unhandled initialization event: {'state': <LnInitState.BOOTSTRAPPING: 'bootstrapping'>, 'msg': 'Connected but waiting to start, RPC services not available'}
Dec 14 03:14:31 raspberrypi python[833]: WARNING:root:LND_GRPC: Unhandled initialization event: {'state': <LnInitState.BOOTSTRAPPING: 'bootstrapping'>, 'msg': 'Connected but waiting to start, RPC services not available'}
Dec 14 03:15:33 raspberrypi python[833]: WARNING:root:LND_GRPC: Unhandled initialization event: {'state': <LnInitState.BOOTSTRAPPING: 'bootstrapping'>, 'msg': 'Connected but waiting to start, RPC services not available'}
Dec 14 03:16:37 raspberrypi python[833]: WARNING:root:LND_GRPC: Unhandled initialization event: {'state': <LnInitState.BOOTSTRAPPING: 'bootstrapping'>, 'msg': 'Connected but waiting to start, RPC services not available'}
Dec 14 03:17:40 raspberrypi python[833]: WARNING:root:LND_GRPC: Unhandled initialization event: {'state': <LnInitState.BOOTSTRAPPING: 'bootstrapping'>, 'msg': 'Connected but waiting to start, RPC services not available'}
Dec 14 03:17:42 raspberrypi python[833]: WARNING:root:LND_GRPC: Unhandled initialization event: {'state': <LnInitState.BOOTSTRAPPING: 'bootstrapping'>, 'msg': 'Connected but waiting to start, RPC services not available'}
Dec 14 03:18:44 raspberrypi python[833]: WARNING:root:LND_GRPC: Unhandled initialization event: {'state': <LnInitState.BOOTSTRAPPING: 'bootstrapping'>, 'msg': 'Connected but waiting to start, RPC services not available'}
Dec 14 03:18:46 raspberrypi python[833]: WARNING:root:LND_GRPC: Unhandled initialization event: {'state': <LnInitState.BOOTSTRAPPING: 'bootstrapping'>, 'msg': 'Connected but waiting to start, RPC services not available'}

- TOUCHSCREEN is OFF by config
- Loop is OFF by config

*** LND-RTL ***
● RTL.service - RTL Webinterface
     Loaded: loaded (/etc/systemd/system/RTL.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2022-12-14 03:10:18 GMT; 9min ago
    Process: 12612 ExecStartPre=/home/admin/config.scripts/bonus.rtl.sh prestart lnd mainnet (code=exited, status=0/SUCCESS)
   Main PID: 12725 (node)
      Tasks: 11 (limit: 9353)
        CPU: 6.217s
     CGroup: /system.slice/RTL.service
             └─12725 /usr/bin/node /home/rtl/RTL/rtl

Dec 14 03:10:15 raspberrypi systemd[1]: Starting RTL Webinterface...
Dec 14 03:10:18 raspberrypi systemd[1]: Started RTL Webinterface.

- CL-RTL is OFF by config

*** LAST 20 ElectRS LOGS ***
sudo journalctl -u electrs -b --no-pager -n20
-- Journal begins at Mon 2022-12-12 19:49:22 GMT, ends at Wed 2022-12-14 03:19:46 GMT. --
Dec 14 03:19:02 raspberrypi systemd[1]: electrs.service: Consumed 8.266s CPU time.
Dec 14 03:19:02 raspberrypi systemd[1]: Started Electrs.
Dec 14 03:19:02 raspberrypi electrs[81492]: Starting electrs 0.9.7 on aarch64 linux with Config { network: Bitcoin, db_path: "/mnt/hdd/app-storage/electrs/db/bitcoin", daemon_dir: "/home/electrs/.bitcoin", daemon_auth: UserPass("raspibolt", "<sensitive>"), daemon_rpc_addr: *.*.*.*:8332, daemon_p2p_addr: 127.0.0.1:8333, electrum_rpc_addr: 0.0.0.0:50001, monitoring_addr: 127.0.0.1:4224, wait_duration: 10s, jsonrpc_timeout: 15s, index_batch_size: 10, index_lookup_limit: None, reindex_last_blocks: 0, auto_reindex: true, ignore_mempool: false, sync_once: false, disable_electrum_rpc: false, server_banner: "Welcome to electrs v0.9.7 - the Electrum Rust Server on your RaspiBlitz", args: [] }
Dec 14 03:19:02 raspberrypi electrs[81492]: [2022-12-14T03:19:02.440Z INFO  electrs::metrics::metrics_impl] serving Prometheus metrics on *.*.*.*:4224
Dec 14 03:19:02 raspberrypi electrs[81492]: [2022-12-14T03:19:02.440Z INFO  electrs::server] serving Electrum RPC on *.*.*.*:50001
Dec 14 03:19:02 raspberrypi electrs[81492]: [2022-12-14T03:19:02.597Z INFO  electrs::db] "/mnt/hdd/app-storage/electrs/db/bitcoin": 974 SST files, 56.666298477 GB, 4.696112756 Grows
Dec 14 03:19:06 raspberrypi electrs[81492]: [2022-12-14T03:19:06.548Z INFO  electrs::chain] loading 761240 headers, tip=000000000000000000022fa13b5abb217c073ed005a73834cb886470af426678
Dec 14 03:19:10 raspberrypi electrs[81492]: [2022-12-14T03:19:10.324Z INFO  electrs::chain] chain updated: tip=000000000000000000022fa13b5abb217c073ed005a73834cb886470af426678, height=761240
Dec 14 03:19:10 raspberrypi electrs[81492]: [2022-12-14T03:19:10.382Z INFO  electrs::index] indexing 2000 blocks: [761241..763240]
Dec 14 03:19:10 raspberrypi electrs[81492]: thread 'p2p_loop' panicked at 'invalid message: OversizedVectorAllocation { requested: 12000072, max: 4000000 }', src/p2p.rs:250:70
Dec 14 03:19:10 raspberrypi electrs[81492]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Dec 14 03:19:10 raspberrypi electrs[81492]: [2022-12-14T03:19:10.589Z INFO  electrs::db] closing DB at /mnt/hdd/app-storage/electrs/db/bitcoin
Dec 14 03:19:10 raspberrypi electrs[81492]: Error: electrs failed
Dec 14 03:19:10 raspberrypi electrs[81492]: Caused by:
Dec 14 03:19:10 raspberrypi electrs[81492]:     0: sync failed
Dec 14 03:19:10 raspberrypi electrs[81492]:     1: failed to get block 000000000000000000070742427fa10ec3c66d006160155a704d9f56d090a3ea
Dec 14 03:19:10 raspberrypi electrs[81492]:     2: receiving on an empty and disconnected channel
Dec 14 03:19:10 raspberrypi systemd[1]: electrs.service: Main process exited, code=exited, status=1/FAILURE
Dec 14 03:19:10 raspberrypi systemd[1]: electrs.service: Failed with result 'exit-code'.
Dec 14 03:19:10 raspberrypi systemd[1]: electrs.service: Consumed 8.122s CPU time.

*** ElectRS Status ***
##### STATUS ELECTRS SERVICE
configured=1
serviceInstalled=1
serviceRunning=0
serviceRunning=0
tipSynced=0
initialSynced=0
electrumResponding=0
infoSync='Not running - check: sudo journalctl -u electrs'

*** LAST 20 LIT LOGS ***
sudo journalctl -u litd -b --no-pager -n20
-- Journal begins at Mon 2022-12-12 19:49:22 GMT, ends at Wed 2022-12-14 03:19:46 GMT. --
Dec 14 03:18:46 raspberrypi torsocks[79253]: 2022-12-14 03:18:46.682 [DBG] GRPC: [core] Subchannel picks a new address "*.*.*.*:10009" to connect
Dec 14 03:18:46 raspberrypi torsocks[79253]: 2022-12-14 03:18:46.683 [WRN] GRPC: [core] grpc: addrConn.createTransport failed to connect to {*.*.*.*:10009 127.0.0.1:10009 <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused". Reconnecting...
Dec 14 03:18:46 raspberrypi torsocks[79253]: 2022-12-14 03:18:46.683 [DBG] GRPC: [core] Subchannel Connectivity change to TRANSIENT_FAILURE
Dec 14 03:18:46 raspberrypi torsocks[79253]: 2022-12-14 03:18:46.683 [WRN] GRPC: [core] grpc: addrConn.createTransport failed to connect to {*.*.*.*:10009 127.0.0.1:10009 <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused". Reconnecting...
Dec 14 03:18:46 raspberrypi torsocks[79253]: 2022-12-14 03:18:46.683 [DBG] GRPC: [core] Subchannel Connectivity change to TRANSIENT_FAILURE
Dec 14 03:18:46 raspberrypi torsocks[79253]: 2022-12-14 03:18:46.683 [DBG] GRPC: [core] pickfirstBalancer: UpdateSubConnState: 0x400003aea0, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial tcp *.*.*.*:10009: connect: connection refused"}
Dec 14 03:18:46 raspberrypi torsocks[79253]: 2022-12-14 03:18:46.683 [DBG] GRPC: [core] Channel Connectivity change to TRANSIENT_FAILURE
Dec 14 03:18:46 raspberrypi torsocks[79253]: 2022-12-14 03:18:46.683 [DBG] GRPC: [core] pickfirstBalancer: UpdateSubConnState: 0x40000abfe0, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial tcp *.*.*.*:10009: connect: connection refused"}
Dec 14 03:18:46 raspberrypi torsocks[79253]: 2022-12-14 03:18:46.683 [DBG] GRPC: [core] Channel Connectivity change to TRANSIENT_FAILURE
Dec 14 03:18:46 raspberrypi torsocks[79253]: 2022-12-14 03:18:46.683 [DBG] GRPC: [core] Channel Connectivity change to SHUTDOWN
Dec 14 03:18:46 raspberrypi torsocks[79253]: 2022-12-14 03:18:46.683 [DBG] GRPC: [core] Subchannel Connectivity change to SHUTDOWN
Dec 14 03:18:46 raspberrypi torsocks[79253]: 2022-12-14 03:18:46.683 [ERR] LITD: Could not start subservers: error subscribing to lnd wallet state: lnd version incompatible, need at least v0.13.0-beta, got error on state subscription: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp *.*.*.*:10009: connect: connection refused"
Dec 14 03:18:46 raspberrypi torsocks[79253]: 2022-12-14 03:18:46.684 [DBG] GRPC: [core] Channel Connectivity change to SHUTDOWN
Dec 14 03:18:46 raspberrypi systemd[1]: litd.service: Main process exited, code=exited, status=1/FAILURE
Dec 14 03:18:46 raspberrypi torsocks[79253]: 2022-12-14 03:18:46.684 [DBG] GRPC: [core] Subchannel Connectivity change to SHUTDOWN
Dec 14 03:18:46 raspberrypi torsocks[79253]: 2022-12-14 03:18:46.684 [INF] SGNL: Received shutdown request.
Dec 14 03:18:46 raspberrypi torsocks[79253]: 2022-12-14 03:18:46.684 [INF] SGNL: Shutting down...
Dec 14 03:18:46 raspberrypi torsocks[79253]: 2022-12-14 03:18:46.684 [INF] SGNL: Gracefully shutting down.
Dec 14 03:18:46 raspberrypi torsocks[79253]: error subscribing to lnd wallet state: lnd version incompatible, need at least v0.13.0-beta, got error on state subscription: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp *.*.*.*:10009: connect: connection refused"
Dec 14 03:18:46 raspberrypi systemd[1]: litd.service: Failed with result 'exit-code'.

* BTCPayServer is OFF by config
* BTC-RPC-Explorer is OFF by config
- LNbits is OFF by config
- Thunderhub is OFF by config
- SPECTER is OFF by config
- SPHINX is OFF by config

*** MOUNTED DRIVES ***
Filesystem     Type      Size  Used Avail Use% Mounted on
/dev/root      ext4       30G   15G   14G  54% /
devtmpfs       devtmpfs  3.9G     0  3.9G   0% /dev
tmpfs          tmpfs     3.9G   16K  3.9G   1% /dev/shm
tmpfs          tmpfs     1.6G  1.1M  1.6G   1% /run
tmpfs          tmpfs     5.0M     0  5.0M   0% /run/lock
tmpfs          tmpfs      32M   28K   32M   1% /var/cache/raspiblitz
/dev/mmcblk0p1 vfat      253M   32M  222M  13% /boot
/dev/sda1      ext4      916G  659G  212G  76% /mnt/hdd
tmpfs          tmpfs     787M   16K  787M   1% /run/user/1000
tmpfs          tmpfs     787M   16K  787M   1% /run/user/1001

*** DATADRIVE ***
# RASPIBLITZ DATA DRIVE Status

# BASICS
isMounted=1
isBTRFS=0
hddRaspiData=1
hddRaspiVersion='1.8.0'
isSSD=1
datadisk='sda'
datapartition='sda1'
hddCandidate='sda'
hddPartitionCandidate='sda1'
hddBlocksBitcoin=1
hddBytes=1000141693440
hddGigaBytes=931
hddUsedInfo='659G (76%)'
hddDataFreeBytes=226765631488
hddDataFreeKB=221450812
hddDataFreeGB=211
hddAdapterUSB='174c:1153'
hddAdapterUSAP=1

# RAID
isRaid=0
raidCandidate[0]='zram0 9 GB zram0'
raidCandidates=1

# SWAP
isSwapExternal=1
SwapExternalPath='/mnt/hdd/swapfile'

*** NETWORK ***
localip=*.*.*.*
localiprange=*.*.*.*/24
dhcp=1
network_device=eth0

*** HARDWARE TEST RESULTS ***
UndervoltageReports in Logs: 0

*** SYSTEM CACHE STATUS ***
system_temp_celsius="60"
system_board="rp4"
system_count_start_tui="0"
system_ups_status="OFF"
system_count_longscan="0"
system_count_undervoltage="0"
system_cpu_load=" 1.73, 1.72, 1.08"
system_temp_fahrenheit="140"
system_ram_available_mb="6930"
system_vm_vagrant="0"
system_ram_gb="8"
system_ups_battery=""
system_up="700"
system_init_time="1670987309"
system_count_start_blockchain="1"
system_count_start_lightning="10"
system_ram_mb="7862"
ln_default_online="0"
ln_default_activated="1"
ln_default_error_short=""
ln_default_sync_initial_done="0"
ln_default_running="0"
ln_default_error_full=""
ln_default_version="0.15.0-beta"
ln_default_locked="0"
ln_default_ready="0"
btc_default_synced="1"
btc_default_peers="7"
btc_default_sync_initial_done="1"
btc_default_error_full=""
btc_default_sync_percentage="100.00"
btc_default_online="1"
btc_default_mempool_transactions="3076"
btc_default_port="8333"
btc_default_blocks_behind="0"
btc_default_running="1"
btc_default_activated="1"
btc_default_blocks_data_kb="493060364"
btc_default_version="v23.0.0"
btc_default_blocks_verified="767321"
btc_default_sync_progress="0.999991788403774"
btc_default_blocks_headers="767321"
btc_default_sync_initialblockdownload="0"
btc_default_error_short=""
btc_default_ready="1"

**Comment by rootzoll** [comment]
LND is on restarting:
```
Dec 14 03:18:46 raspberrypi lnd[78931]: unable to open databases: unable to open graph DB: channel db cannot revert to prior version
```

You seam to have flashed an older image ... please make sure to have the latest image: v1.8.0c
https://github.com/rootzoll/raspiblitz#downloading-the-software

**Comment by cstenglein** [comment]
Closing for now, please re-open if it still appears with 1.9.0
