### ISSUE TITLE
Add masking of LNBits logs to debug -l

### ISSUE THREAD

**Issue by tlindi** [raspiblitz/raspiblitz#3520]
LNbits user authentication is clear text in URL.

When user runs
debug - l

Log files are pushed to cloud. File reveals LNbits log file lines like
**III.PPP.AAA.DDR** - - [14/Dec/2022:14:54:12 +0200] "GET /wallet?usr=**HEREis-long-hex**&wal=**HERE-is-another-long-hex**

Those usr and wal atlest should be masked before sending log file to cloud.

issue found during debugging: https://github.com/rootzoll/raspiblitz/issues/3519

**Comment by rootzoll** [comment]
To be added to the debug redacting section: https://github.com/rootzoll/raspiblitz/blob/b589b57215b57a0a1a97153d354a35716c4669fa/home.admin/config.scripts/blitz.debug.sh#L5

**Comment by rootzoll** [comment]
Ok merge into dev. Will be part of v1.9.0 release.
