### ISSUE TITLE
IP2Tor disable or revive?

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#3524]
The IP2Tor service provided by FULMO is not working correctly and will not be continued. Thats wy the following issues were reported:

- [x] #2247
- [x] #3335
- [x] #3417

There is some commitment by the community to setup a new instance of this service .- but we have to see if that will be ready for v1.9.0 or in that version the IP2Tor gets deactivated for now.

**Comment by rootzoll** [comment]
https://github.com/rootzoll/raspiblitz/issues/3417#issuecomment-1357579606

- [x] deactivate IP2Tor in suibscriptions menu
- [x] remove IP2 Tor from docu
- [x] remove IP2Tor from bonus apps
- [x] remove IP2Tor from conecting devices

**Comment by rootzoll** [comment]
- [ ] Recheck FULMO services ... and also #2773 for services like LNbits & BTCPay

**Comment by frennkie** [comment]
My node has not been stable over the last month.. sorry about that.. :-/

Also the backup node (Fulmo Node02) wasn't paired correctly... this has been fixed now.

**Comment by poweruser0815** [comment]
HI, don´t now why - but now it is working (Fulmo Node) since approx. 10 days

**Comment by unlockingscript** [comment]
I can confirm, I am working with it since 3rd Jan. Works better for me than before.

**Comment by openoms** [comment]
the default:
`fulmo7x6yvgz6zs2b2ptduvzwevxmizhq23klkenslt5drxx2physlqd.onion`
is down.
Are there alternatives?

any experience with: https://ip2tor.com/#tor_bridges ?

**Comment by rootzoll** [comment]
ip2tor.com shoudl become the new default shop ... but its also having some problems - see here: https://github.com/rootzoll/raspiblitz/issues/3417#issuecomment-1533472557

**Comment by rootzoll** [comment]
Quick update: tested today the ip2tor.com (that is the first option in the RaspiBlitz v1.9.0 SSH subscription menus) and its now working again.
