### ISSUE TITLE
Missing fonts or something

### ISSUE THREAD

**Issue by tryolly** [raspiblitz/raspiblitz#353]
Hi, Not a major problem just slightly annoying. I'm accessing my raspiblitz from putty using windows 10 and the screen is never displayed properly. It has letters instead of borders. I'm sure I'm just missing the correct font for it or something, if so, which one do I need to get?
![capture3](https://user-images.githubusercontent.com/47936671/53296016-545bea00-385b-11e9-8162-29b129d00449.PNG)

**Comment by raumi75** [comment]
Looks like #314 which was submitted in German. Still looking for someone with putty-skills. Most people here seem to be using Mac and Linux.

**Comment by tryolly** [comment]
thanks raumi, looks like the issue will get solved eventually. I can wait.

**Comment by rootzoll** [comment]
@tryolly I dont have a putty win10 either to test - maybe try in putte settings to change the font of the terminal. Please rport back if you find anything.

**Comment by OfficialBigAl** [comment]
You have to have the right emulation/dictionary ;)  Try these settings...
![image](https://user-images.githubusercontent.com/46918332/53301648-5028d000-384d-11e9-897c-3f64dec2cf1b.png)

**Comment by rootzoll** [comment]
I will add this to the FAQ soon - thanks :)

**Comment by tryolly** [comment]
Thanks guys. That fixed it up perfectly.
