### ISSUE TITLE
LNbits LNURL withdraw not working with front end nginx proxy

### ISSUE THREAD

**Issue by tlindi** [raspiblitz/raspiblitz#3535]
I read many similar SSL/cert issues but none matched to my issue.

I want to access LNbits LNURL without VPS/VPN and any external vendors except my ISP.

I have configured DNS correctly and hostname matching LetsEncrypt cert is used in all the required locations.

I have tested following setups:

**Working setup 1)**
browser<->private IP-net<->raspiblizt-ngnix(ssl 5001 proxy_pass http 5000 to)<->lnbits

**Optional Working setup 2)**
browser<->internet<->router (with ssl 443 portforward to)<->raspiblizt-ngnix(ssl 5001 proxy_pass http 5000 to)<->lnbits

**Optional Working setup 3)**
browser<->internet<->router (with ssl 443 portforward to)<->raspiblitz nginx(ssl 443 proxy_pass https 5001 to)<->raspiblizt-ngnix(ssl 5001 proxy_pass http 5000 to)<->lnbits

**Not working Setup 4) with separate host as front nginx host to proxy 443 to raspiblitz (and other hosts too) <- ISSUE**
browser<->internet<->router (with ssl 443 portforward to)<->front nginx host (ssl 443 proxy_pass https 5001 to)<->raspiblizt-ngnix(ssl 5001 proxy_pass http 5000 to)<->lnbits

**SETUP 1)**
Please study following logs for working setup here:
![http2 0-to port 5001 stays http2 0-and-works - SHAREABLE](https://user-images.githubusercontent.com/7249767/208160406-493b1620-de6a-4085-9925-6736cbc166bf.png)

Browser console debug shows no issues and networking seems ok.
![Working-privateIP - SHAREABLE](https://user-images.githubusercontent.com/7249767/208160720-6fe5f154-3e85-4b8c-a2f5-9e09aa4f7b42.png)

**SETUP 4)**
Not working case logs:
![http2 0-goes-http1 0--notWorking- SHAREABLE](https://user-images.githubusercontent.com/7249767/208161184-c070a623-728c-44a4-b693-03e8fedd541c.png)

LNbits shows an error:
![LNbits-Error](https://user-images.githubusercontent.com/7249767/208161539-53c103a9-49f7-4c94-8cfe-7bc0cf6b68b1.png)

Browser debug shows an error and networking has some issues:
![Working-not-https-error-426-from Browser - SHAREABLE](https://user-images.githubusercontent.com/7249767/208163558-3786708b-4d4a-4f21-b677-3cf4bc823187.png)

![Working-not-https - SHAREABLE](https://user-images.githubusercontent.com/7249767/208160921-cfe0e573-0700-4391-8e7c-71af31ca7cf1.png)

**_Only case when I have issue is when nginx proxy is on another host!_**
My setup has many hosts on internal network to where I proxy_pass trafic from this front nginx. So it is mandatory to forward all 443 from internet to nginx outside of raspiblitz. Multible browsers were tested too and cookies / browser data was cleared also. All the other sites and their functionalities work. Event other parts of LNbits itself are ok. Also LND channels are fine and funds flow.

No avail. any ideas

ps. sorry about long issue and bad pictures.

**Comment by tlindi** [comment]
issue cleared some samples from interwebs had escape "\\" for $ on these nginx lines. Like this
  proxy_set_header Host \\$http_host;
  proxy_set_header X-Real-IP \\$remote_addr;
  proxy_set_header X-Forwarded-For \\$proxy_add_x_forwarded_for;
  
 Removed "\\" as following
   proxy_set_header Host $http_host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  
  and now all good :)

**Comment by rootzoll** [comment]
@tlindi you closed this issue .. was there anything in there to be changed on the raspiblitz code side?

**Comment by tlindi** [comment]
No need to make changes on raspiblitz - I had escape "\\" typo on my config.
