### ISSUE TITLE
LightningTipBot and LNDg SETTINGS conflict

### ISSUE THREAD

**Issue by allyourbankarebelongtous** [raspiblitz/raspiblitz#3537]
In the dev branch, both LightningTipBot and LNDg use option "g" to select for install in 00settingsMenuServices.sh.

  OPTIONS+=(g 'LightningTipBot' ${lightningtipbot})
fi

# just available for LND
if [ "${lightning}" == "lnd" ] || [ "${lnd}" == "on" ]; then
  OPTIONS+=(r 'LND RTL Webinterface' ${rtlWebinterface})
  OPTIONS+=(t 'LND ThunderHub' ${thunderhub})
  OPTIONS+=(l 'LND LIT (loop, pool, faraday)' ${lit})
  OPTIONS+=(g 'LND LNDg (auto-rebalance, auto-fees)' ${lndg})

This results in installing LightningTipBot when you want to install LNDg, and then it showing that both are installed. PR incoming to fix today.

**Comment by rootzoll** [comment]
Thx. PR merged. Will be part of v1.9 release :)
