### ISSUE TITLE
Syncing problem pi crashes and crashes on sync

### ISSUE THREAD

**Issue by q2lamer** [raspiblitz/raspiblitz#3539]
Hi the node is always crashing sometimes after 10min sometimes after 9 hours, but it always crash on syncing and i have no clue why. im a noob on linux for sure so i add here the debug.log maybe someone can look over i would really appreate it.

all brand new 2TB WD Gaming Drive USB 3.0 8gb Raspberyy pi 4 silicon power sd card 1gbit Lan connection to internet Passive cooling case from armor and a 3.5 lcd on top of it
temperatures is between 50-72 C max

Debug log file:

[](https://l.termbin.com/9918p)

it just happens after i finish typing here

SIGINT or SIGTERM received, exiting...braries: libc.so.6: cannot open shared object file: Input/output error error

./00raspiblitz.sh: /home/admin/_cache.sh: /usr/bin/env: bad interpreter: Input/output error /bin/bash: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: Input/output error sleep: error while loading shared libraries: libc.so.6: cannot open shared object file: Input/output error ./00raspiblitz.sh: /home/admin/_cache.sh: /usr/bin/env: bad interpreter: Input/output error /bin/bash: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: Input/output error sleep: error while loading shared libraries: libc.so.6: cannot open shared object file: Input/output error ./00raspiblitz.sh: /home/admin/_cache.sh: /usr/bin/env: bad interpreter: Input/output error /bin/bash: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: Input/output error sleep: error while loading shared libraries: libc.so.6: cannot open shared object file: Input/output error ./00raspiblitz.sh: /home/admin/_cache.sh: /usr/bin/env: bad interpreter: Input/output error /bin/bash: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: Input/output error sleep: error while loading shared libraries: libc.so.6: cannot open shared object file: Input/output error ./00raspiblitz.sh: /home/admin/_cache.sh: /usr/bin/env: bad interpreter: Input/output error /bin/bash: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: Input/output error sleep: error while loading shared libraries: libc.so.6: cannot open shared object file: Input/output error ./00raspiblitz.sh: /home/admin/_cache.sh: /usr/bin/env: bad interpreter: Input/output error /bin/bash: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: Input/output error sleep: error while loading shared libraries: libc.so.6: cannot open shared object file: Input/output error ./00raspiblitz.sh: /home/admin/_cache.sh: /usr/bin/env: bad interpreter: Input/output error /bin/bash: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: Input/output error sleep: error while loading shared libraries: libc.so.6: cannot open shared object file: Input/output error ./00raspiblitz.sh: /home/admin/_cache.sh: /usr/bin/env: bad interpreter: Input/output error /bin/bash: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: Input/output error sleep: error while loading shared libraries: libc.so.6: cannot open shared object file: Input/output error ./00raspiblitz.sh: /home/admin/_cache.sh: /usr/bin/env: bad interpreter: Input/output error /bin/bash: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: Input/output error sleep: error while loading shared libraries: libc.so.6: cannot open shared object file: Input/output error ./00raspiblitz.sh: /home/admin/_cache.sh: /usr/bin/env: bad interpreter: Input/output error /bin/bash: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: Input/output error sleep: error while loading shared libraries: libc.so.6: cannot open shared object file: Input/output error ./00raspiblitz.sh: /home/admin/_cache.sh: /usr/bin/env: bad interpreter: Input/output error /bin/bash: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: Input/output error ^Csleep: error while loading shared libraries: libc.so.6: cannot open shared object file: Input/output error SIGINT or SIGTERM received, exiting...

**Comment by openoms** [comment]
Likely the RPi4 cannot provide sufficient power for that 2 TB drive and errors on power usage spikes.
I prefer using an X825 USB-SATA adapter board which can be powered with a 4A barrel connector powering the disk reliably.

**Comment by cstenglein** [comment]
@q2lamer  is this still an issue?

Closing this for now, please re-open if it still persists.
