### ISSUE TITLE
LNDg with Raspiblitz

### ISSUE THREAD

**Issue by moisesaer** [raspiblitz/raspiblitz#3547]
Is possible to use LNDg with RASPIBLITZ?
If possible, how I install it on Raspiblitz?

**Comment by redmac68** [comment]
Hi, LNDg seems to be included as an optional service in the next release of Raspiblitz (v1.9.0).
https://github.com/rootzoll/raspiblitz/issues/3230
This release should be available soon?

**Comment by rootzoll** [comment]
The goal is to have a first ReleaseCandidate out of v1.9.0 before Christmas to test. That version will include LNDg install from the SSH menus. See: https://github.com/rootzoll/raspiblitz/blob/dev/CHANGES.md#whats-new-in-version-190-of-raspiblitz

**Comment by cstenglein** [comment]
LNDg is included with 1.9.0, closing.
