### ISSUE TITLE
Alby will not connect

### ISSUE THREAD

**Issue by dskvr** [raspiblitz/raspiblitz#3550]
Details:
1. Migrated from Umbrel
2. Have confirmed ISP is not blocking tor
3. Have connected successfully to port 80 over tor (the site title shows `Raspiblitz Web` but the page does not actually load)
4. Have 100x checked onion and macaroon details.
5. When visiting `hash.onion:8080/v1/getinfo` the page never loads. 

Are there any troubleshooting guides? I have been running in circles but cannot find any relevant details. 

Edit: I didn't put it in the list above, but yes, I have the alby companion app installed.

**Comment by openoms** [comment]
type in terminal:
```
blitzhelp
```
for command line help.
Have a look around in the menu.
Use the command:
```
debug
```
Can share the link from:
```
debug -l
```

**Comment by jigglycrumb** [comment]
I just updated to 1.8.0c and have the same issue. I suspect it might be a problem with the SSL certificate.
When I open `hash.onion:8080/v1/getinfo` with Tor browser, it shows a certificate problem.
I then see an error page about the missing macaroon when I continue anyway.

However when I connect using my local LAN IP, it works flawlessly.

**Comment by openoms** [comment]
It is a self-signed certificate by LND. Click Advanced and accept it. The browser will connect afterwards.

**Comment by dskvr** [comment]
> Can share the link from:
> debug -l

@openoms https://l.termbin.com/hljm

**Comment by openoms** [comment]
> @openoms https://l.termbin.com/hljm

not sure what is this, but you can reset the LND tls.cert in the CONNECT menu.

**Comment by dskvr** [comment]
@openoms Confused, you asked me to shared it.

>Can share the link from:

**Comment by openoms** [comment]
> @openoms Confused, you asked me to shared it.

I meant I am not sure what that tls error in your logs is about.

**Comment by dskvr** [comment]
I reset TLS
- still getting an alby connection error, albeit a different one.
```
A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
```

- still not fully loading page on raspiblitz web via tor

here is the new log after TLS reset, and attempting to connect to web via tor 

https://l.termbin.com/pk5tg

I also have a ticket open with Alby and have shared this issue. 

From my end it's very difficult to debug this and identify the cause of the issue. ~Alby logs are clean since TLS reset~, and the logs I sent you look clean as well. I see peer errors in the logs sent above, but can confirm I have sufficient outgoing/incoming peers. 

Alby logs actually have a new error
```
background.bundle.js:2 Native companion disconnected
```

I have also attempted to connect through an Onion over VPN connection, to eliminate ISP concerns from the equation.

_Do you have an lnurl?_

**Comment by cstenglein** [comment]
@dskvr  is this still an issue?

Closing this for now, please re-open if it still persists.
