### ISSUE TITLE
Services - Custom Restart script does not verify service

### ISSUE THREAD

**Issue by tlindi** [raspiblitz/raspiblitz#3555]
![image](https://user-images.githubusercontent.com/7249767/208672896-961e4303-49bc-4c25-96b8-b2aaa8d46980.png)

restart line says "nlbits"

correct should be "lnbits"

so if user wants to copy paste restart command, it will fail.

**Comment by rootzoll** [comment]
I mean you typed in "nlbits", right? typo in, typo out

**Comment by tlindi** [comment]
shouldn't script verify that typed service exists before proceeding and informing user?!?

**Comment by rootzoll** [comment]
should is a good question. It means that script needs to be maintained by some developer more constanly - and get extended with every new possible service added. As far as I understood its just a learning tool showing you the real linux command you can use in the future directly. If sombody would like to spend hers/his dev time on maintaining & extending that script in the future thats fine with me (its open source) happy to merge PRs .. but if not I think its also fine as it is.
