### ISSUE TITLE
Download LND rescue file: 'run in new terminal'-hint is missing for Windows

### ISSUE THREAD

**Issue by gregorsbueezer** [raspiblitz/raspiblitz#3581]
When downloading the LND rescue file, the hint "run in new terminal" is missing for the Windows variant
![grafik](https://user-images.githubusercontent.com/86912958/209936875-b9755f87-c6f6-44d3-a14d-7362dd4fb7d2.png)

**Comment by rootzoll** [comment]
Will be part of v1.9.0rc2 - closing issue.
