### ISSUE TITLE
Copy Blockchain (sftp)

### ISSUE THREAD

**Issue by muraschal** [raspiblitz/raspiblitz#3584]
Hi guys
I suspect there is a bug in the sftp markup:
`sftp -r ./chainstate ./blocks bitcoin@192.168.1.112:/mnt/hdd/bitcoin`

![image](https://user-images.githubusercontent.com/4194026/210088997-d75c520b-5459-48c3-be27-85b87ff9c664.png)
![image](https://user-images.githubusercontent.com/4194026/210089766-4849c626-9fef-495c-a0db-3158c15fc0a2.png)

As you can see, I can connect via SFTP on filezilla without any problems:
![image](https://user-images.githubusercontent.com/4194026/210089774-20d305ef-ded7-4dac-bc2c-f6c73fb873c8.png)

Thanks!

**Comment by muraschal** [comment]
Okay I could help myself, it works with **scp**.
But I don't understand why sftp was declared in the instructions, thanks!

**Comment by robinvonmises** [comment]
same here, used scp instead of sftp to copy the blockchain

**Comment by rootzoll** [comment]
Thx for the report. Will set back to scp for windows blockchain upload for v1.9.0rc2
