### ISSUE TITLE
lnd/bitcoin 100% sync but node not running

### ISSUE THREAD

**Issue by Omicron59** [raspiblitz/raspiblitz#3588]
Good evening I have launched a rescan of the lnd, since a few days my node no longer wants to pass the synchronization, I tried to meter the new version v1.9 thinking fix my problem but still not, if someone can enlighten me please

thank you in advance

https://l.termbin.com/0a3e

![image](https://user-images.githubusercontent.com/46853496/210439547-53b7aa46-6356-4483-90ac-f0848078fe8f.png)

![image](https://user-images.githubusercontent.com/46853496/210439752-1283dd94-343c-4885-9970-316f672589df.png)

**Comment by Omicron59** [comment]
Hi when I scan the lnd it never ends and I just saw this error what to do?

[ERR] LNWL: Unable to complete chain rescan: -1: Block not found on disk

![image](https://user-images.githubusercontent.com/46853496/211202586-fcedef6f-d90b-41ae-ae64-283b549adbb9.png)

**Comment by rootzoll** [comment]
Whats the lncli getinfo output? Havent seen that error myself - a search in the lnd github shows: https://github.com/lightningnetwork/lnd/issues/4296#issuecomment-630573181

Solution might be to reindex or delete/resync bitcoin blockchain. Try the `repair` command on RaspiBlitz terminal.

**Comment by Omicron59** [comment]
Yop! rootzoll thank you for your return, I launched a few days ago a repartion and download of the blockchain, I hope this will solve my problem

![image](https://user-images.githubusercontent.com/46853496/212498663-7490a741-55e2-49a9-bb50-efcf5bb93e74.png)

**Comment by Omicron59** [comment]
Hello after a download of the blockchain and a restart of the node all is finally OK again thank you for your return
