### ISSUE TITLE
[documentation] ZFS ops

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#3590]
Mount a ZFS dataset to `/mnt/hdd`:
```
zfs create fourdiskpool/hdd
zfs mount fourdiskpool/hdd /mnt
```
or change an existing mountpoint for a whole pool:
```
sudo zfs set mountpoint=/mnt/hdd POOL1
```
then to automount:
```
echo "\
[Service]
ExecStartPre=/sbin/zfs load-key -a
ExecStartPre=/sbin/zfs mount -la
" | sudo tee /etc/systemd/system/bootstrap.service.d/zfsautomount.conf
```
or in cron:
```
cronjob="@reboot sudo /sbin/zfs load-key -a; sudo /sbin/zfs mount -la"
(crontab -u admin -l; echo "$cronjob" ) | crontab -u admin -
```

Find a more detailed description from the beginning if the ZFS pool creation here: https://github.com/openoms/bitcoin-tutorials/blob/master/zfs/create-raspiblitz-zfs-disk.md

**Comment by rootzoll** [comment]
Closing because we now tend to not doing ZFS within RaspiBlitz: https://github.com/raspiblitz/raspiblitz/issues/2045#issuecomment-2471845122
