### ISSUE TITLE
just received my raspiblitz metal case. White screen problem

### ISSUE THREAD

**Issue by Ayahualulco** [raspiblitz/raspiblitz#3592]
Hi! I just received my raspiblitz metal case from fulmo and when I plug it in, I get a white screen. Nothing else. I left it plug in for a while so I think tehre is a problem. Any hints on what that could be and how it could be fixed. I also contacted fulmo to let them know since thsi is out of the box. Thanks!

**Comment by openoms** [comment]
Reflash the SDcard with the latest image. It can be corrupted during the shipping.
