### ISSUE TITLE
Lightning Node not working after being offline for quite some time

### ISSUE THREAD

**Issue by KurioseNaturale** [raspiblitz/raspiblitz#3593]
Hello,

my LN node (Raspiblitz) has been offline for quite a while. Recently I started it again but after downloading the blockchain I get always the same error even after restarting the node. 

When "Lightning Process" is showing 98.39% the screen pops up as in the attached jpeg.

After debugging it shows me following url to share: https://termbin.com/a99y

Appreciate any help <3
![Terminal](https://user-images.githubusercontent.com/122109704/211049081-f5d481ee-505c-4797-9abb-22aad62a51c4.JPG)
![Terminal2](https://user-images.githubusercontent.com/122109704/211049164-6ae252b4-9eb2-44d2-b6e1-49ec55c69e9c.JPG)

**Comment by cgall7** [comment]
I'm having the same issue. Blockchain progress is 100% but Lightning is stuck at 99.99% with 0 peers.

**Comment by mattharvill** [comment]
Having same issue too. Wasn't using for over a year, tried to boot up (had to restart more than 1x). I'm stuck at:
**Blockchain Progress:** 100% 11 peers
**Lightning Progress:** 99.99% 0 peers
Thanks!

Edit: I just tried "restart" command in Terminal. After bootup, **Lightning Progress:** said **"prepare sync"**  then changed back to 99.99% 0 peers

Edit 2: I typed in CTRL+C (exit blockchain progress screen) +  typed 'menu' and the menu appeared as expected...maybe it's working?

**Comment by rootzoll** [comment]
@KurioseNaturale I can see an error in your LND logs

```
Jan 06 15:45:10 raspberrypi lnd[5275]: goroutine 504 [running]:
Jan 06 15:45:10 raspberrypi lnd[5275]: github.com/btcsuite/btcwallet/wallet.(*Wallet).handleChainNotifications(0x1d700d0)
Jan 06 15:45:10 raspberrypi lnd[5275]:         github.com/btcsuite/btcwallet@v0.11.1-0.20200904022754-2c5947a45222/wallet/chainntfns.go:117 +0xe00
Jan 06 15:45:10 raspberrypi lnd[5275]: created by github.com/btcsuite/btcwallet/wallet.(*Wallet).SynchronizeRPC
Jan 06 15:45:10 raspberrypi lnd[5275]:         github.com/btcsuite/btcwallet@v0.11.1-0.20200904022754-2c5947a45222/wallet/wallet.go:201 +0x104
Jan 06 15:45:10 raspberrypi systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 06 15:45:10 raspberrypi systemd[1]: lnd.service: Failed with result 'exit-code'.
```

Also @cgall7 & @mattharvill please test if you have the same problem when updating to the lastest Release Cadidate v1.9.0rc1. Its a sd card update. CTRL+C to terminal and then use command `menu` and choose "UPDATE" > "RELEASE" and use the new sd card image provided here: https://github.com/rootzoll/raspiblitz/tree/v1.9#downloading-the-software .. if you still get this LND syncing error, please report back again with a debug report (use command on terminal `debug`)

**Comment by mattharvill** [comment]
@rootzoll thanks for your reply. I followed your directions and got it up and running. Thank you!

**Comment by Slumach** [comment]
I have the same issue with one of my nodes. If I update to latest release, am I going to lose my wallet, there is a balance in the wallet. Nvm i found my recovery seed.
