### ISSUE TITLE
detect error on lncli create

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#36]
on a testrun where in creating the lnd wallet I used a cipher word list from a wallet that had also a passphrase (pass d). But I dont entered a password d. that was leadingto a output of:

`[lncli] rpc error: code = Unknown desc = invalid passphrase `

But the setup script was not detecting this and tried to continue and failed (because no macaroons got created). Try to detect any error output on the lncli create within 70initLND.sh.

**Comment by pettergo** [comment]
not sure if this is the same issue, but i'm getting an error on [Incli] open
---------------------
[lncli] open /home/bitcoin/.lnd/admin.macaroon: no such file or directory

****************************************************************************
Unlock LND Wallet --> lncli unlock
****************************************************************************
HELP: Enter your PASSWORD C
****************************************************************************
[lncli] open /home/admin/.lnd/tls.cert: no such file or directory

Wallet still locked - please try again or Cancel with CTRL+C
[lncli] open /home/admin/.lnd/tls.cert: no such file or directory
hel
Wallet still locked - please try again or Cancel with CTRL+C
[lncli] open /home/admin/.lnd/tls.cert: no such file or directory
 
Wallet still locked - please try again or Cancel with CTRL+C
[lncli] open /home/admin/.lnd/tls.cert: no such file or directory

Wallet still locked - please try again or Cancel with CTRL+C
[lncli] open /home/admin/.lnd/tls.cert: no such file or directory

Wallet still locked - please try again or Cancel with CTRL+C
[lncli] open /home/admin/.lnd/tls.cert: no such file or directory
 
Wallet still locked - please try again or Cancel with CTRL+C
[lncli] open /home/admin/.lnd/tls.cert: no such file or directory

Wallet still locked - please try again or Cancel with CTRL+C
[lncli] open /home/admin/.lnd/tls.cert: no such file or directory
^Cadmin@raspberrypi:~ $ ls
00infoBlitz.sh   30initHDD.sh      50torrentHDD.sh   91addBonus.sh     download
00infoLCD.sh     40addHDD.sh       60finishHDD.sh    AAunlockLND.sh    LCD-show
00mainMenu.sh    50copyHDD.sh      70initLND.sh      assets            wget-log
10setupBlitz.sh  50downloadHDD.sh  80scanLND.sh      BBconnectPeer.sh  XXcleanHDD.sh
20initDialog.sh  50syncHDD.sh      90finishSetup.sh  BBfundWallet.sh   XXscreenMonitor.sh
admin@raspberrypi:~ $ 60finishHDD.sh
-bash: 60finishHDD.sh: command not found
admin@raspberrypi:~ $ start 60finishHDD.sh
-bash: start: command not found
admin@raspberrypi:~ $ run  60finishHDD.sh
-bash: run: command not found
admin@raspberrypi:~ $ 
------------------------------------------------
-------------------------------------------------
Edit: Not an issue anymore with raspiblitz-2018-08-15.img.
