### ISSUE TITLE
mempool not working after password B change

### ISSUE THREAD

**Issue by matrix79** [raspiblitz/raspiblitz#3602]
changed app password (password B) over normal CLI menu and after rebooting raspiblitz mempool didn't sync new blocks.
checked /home/mempool/mempool/backend/mempool-config.json and noticed, that the old password was still in the config file.

so while lnd.conf and BTC-RPC-Explorer got the right update, mempool config was not proper updated. should get checked and as a bug get fixed if it was not only a special case for me.

**Comment by rootzoll** [comment]
Thx for the report. Fix merged and will be part of v1.9.0rc2 - closing issue.

**Comment by flyerbear** [comment]
This happened to me too (changed password B and mempool stopped syncing). What is the immediate fix until 1.9.0 is released? Should I update the password in `/home/mempool/mempool/backend/mempool-config.json` to my new pw B? Is it just stored in cleartext here?

**Comment by rootzoll** [comment]
@flyerbear yes you can edit the password directly in the `mempool-config.json` - ist just cleartext `CORE_RPC.PASSWORD="[PASSWORDB]"`
