### ISSUE TITLE
circuitbreaker web ui cannot yet be accessed in raspiblitz

### ISSUE THREAD

**Issue by RemoRitzmann** [raspiblitz/raspiblitz#3603]
Hi, I have problems setting up circuitbreaker in raspiblitz, it's installed, service is running but I cannot open the web ui. How can I see the circuitbreaker's version? I asked Joost here https://github.com/lightningequipment/circuitbreaker/issues/36 too.

**Comment by RemoRitzmann** [comment]
sudo su - circuitbreaker
circuitbreaker -V
**0.11.1-beta.rc3**

**Comment by RemoRitzmann** [comment]
Ok, now I have to figure out how to show web ui.

**Comment by joostjager** [comment]
I've added docker CI builds to circuitbreaker and proper version reporting. But not sure if you can run a docker image on raspiblitz?

**Comment by rootzoll** [comment]
just merged PR #3599  - will be part of RaspiBlitz v1.9

**Comment by cstenglein** [comment]
@RemoRitzmann Have you upgraded to 1.9 and did this fix your issue?

Closing this for now, if it still persists, please re-open
