### ISSUE TITLE
RaspiBlitz Sync

### ISSUE THREAD

**Issue by Lilflowerbed1** [raspiblitz/raspiblitz#3604]
I updated the RaspiBlitz img to the latest version. The screen I am seeing has been displaying for days saying "Preparing Blockchain sync please wait..." I asked a telegram group for RaspiBlitz and someone said I'm fine. It's just not showing any percentage of the blockchain sync and wanted to see if anyone can help me out or if this takes days. I've looked around and some people say Raspi is slow so it's taken some weeks to sync. 
![IMG_9400](https://user-images.githubusercontent.com/97019486/211918301-f15dca3a-1c51-43cc-ac26-64a5d9183f0e.jpg)

**Comment by tysecure** [comment]
Is your SSD in good shape?

**Comment by Lilflowerbed1** [comment]
It got delivered from Germany recently. SSD looks fine
I’ll replace when I can to see if that’s the issue, gratitude! I shutdown,
disconnected SSD reconnected and at least now I’m seeing this screen. At
least some of the restarts I want to say are from me tinkering with it.

**Comment by StellarStoic** [comment]
I'm seeing the same screen. The first installation I try stuck at blockchain sync at around 40% after 5 days of sync. Then I waited another 2 days and got nothing. An error I already forgot about. (something about a couple of thousands of tries). 

I decided to flash the SD card again and did a fresh install with the existing blockchain on SSD. And I'm here where you are. The web view says Waitsync "Provision done"  

I was hoping for a smoother installation but now I know it's a pain in the butt

**Comment by Lilflowerbed1** [comment]
Have you tried joining the telegram group. I wasn't able to get into the english speaking one but got on the spanish speaking RaspiBlitz telegram group.

**Comment by StellarStoic** [comment]
I am in the EN telegram group but Telegram with more than 100 members is too much for me. Can't follow the noise. 
here's the link. Try again and wait for shieldy bot to ask you. Confirm that you are human. https://t.me/raspiblitz

**Comment by cstenglein** [comment]
@Lilflowerbed1  is this still an issue?

Closing this for now, please re-open if it still persists.
