### ISSUE TITLE
Blockchain sync counts backwards

### ISSUE THREAD

**Issue by kilrau** [raspiblitz/raspiblitz#362]
State t0:
![image](https://user-images.githubusercontent.com/19181985/53359931-868d4a80-3934-11e9-9a07-144d823f9147.png)

State t1:
![image](https://user-images.githubusercontent.com/19181985/53360038-cbb17c80-3934-11e9-8f54-b23b907264bb.png)

Just a small display bug which might cause confusion - of course sync works as it should. Counted correctly on the pi's display when not SSH'ed in. Started getting weird once SSH'ed in.

**Comment by rootzoll** [comment]
Thanks for noticing. The data on progress is getting displayed as it is delivered from the bitcoind. There might be a better non-confusing way to display in future UI. At the moment its of those little quirks to live with.

I am closing the issue. There is a error situation where it really can happen over long time seeing the progress going down .. please open/post on issue again if tahts the case.
