### ISSUE TITLE
cannot backup SCB to USB from the blitz menu

### ISSUE THREAD

**Issue by kittyboy717** [raspiblitz/raspiblitz#3627]
when trying to backup the static channel backup to usb drive from the blitz menu this error is received.

![pic1](https://user-images.githubusercontent.com/123324528/213934000-180774de-5837-4bd6-ab46-b02df08a5221.png)

drive is available and formatted to FAT32.

**Comment by openoms** [comment]
When there is no extra USB device attached the following command:
```
sudo /home/admin/config.scripts/blitz.backupdevice.sh status
```
Should show:
```
### blitz.backupdevice.sh ###
backupdevice=0
backupCandidates=0
```
Is it the case for you?


tested with a simple 1GB USB drive my blitz (synced with the dev branch) nehaves correctly:
```
admin@192.168.2.149:~ ₿ sudo /home/admin/config.scripts/blitz.backupdevice.sh status
### blitz.backupdevice.sh ###
backupdevice=0
backupCandidate[0]='sdb 0 GB sdb'
backupCandidates=1
admin@192.168.2.149:~ ₿ lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda           8:0    0 931.5G  0 disk 
└─sda1        8:1    0 931.5G  0 part /mnt/hdd
sdb           8:16   1   930M  0 disk 
└─sdb1        8:17   1   929M  0 part 
mmcblk0     179:0    0  29.7G  0 disk 
├─mmcblk0p1 179:1    0   256M  0 part /boot
└─mmcblk0p2 179:2    0  29.5G  0 part /
zram0       254:0    0   4.7G  0 disk [SWAP]
```

If you have run the command:
```
patch
```
on v1.8.0 already you can sync with the `dev` or `v1.9` brnach using the UPDATE - PATCH menu to test if that solves the issue.

**Comment by kittyboy717** [comment]
with device removed i receive the following:
```
### blitz.backupdevice.sh ###
backupdevice=0
backupCandidate[0]='zram0 4 GB zram0'
backupCandidates=1
```
even after rebooting, patching, etc.
i'm guess it is the zram issue afterall...

do you still recommend syncing with dev or v1.9??

**Comment by openoms** [comment]
yes, it is fixed there. See #3436.

**Comment by kittyboy717** [comment]
okay. ^.^
went ahead and flashed an SD with v1.9.
i'll have to wait until i get a clear-ish day before i upgrade (have a bit of added software --  wireguard, charge-lnd, etc.).

i'm sure it'll work since it's already been an issue, but i'll report back afterward to confirm.
ty again for the support~!!

**Comment by kittyboy717** [comment]
device added for backup -- as expected.
^.^
