### ISSUE TITLE
[feat] Offer a choice of disks and partitions to be used as the datadrive or backupdrive

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#3628]
Thinking to apply this first on amd64 to help to install on various disk configurations.

Instead of the automatic choice of `blitz.datadrive.sh` a list of available disks and partitions could be offered as a choice.

For example:
```
#!/bin/bash

# Get a list of all drives and partitions
drives=$(lsblk -o NAME,SIZE -b | grep -P [svn])
drives=$(echo "$drives" | awk '{print $1 " " $2/1024/1024 "MB"}')

# Get a list of all ZFS volumes and the available space
zfs_volumes=$(zfs list -Ho name,avail)

# Add the ZFS volumes to the list of drives
drives="$drives $zfs_volumes"

# Show a dialog box with a list of choices for the user to select
selected_drive=$(dialog --stdout --menu "Select a drive:" 0 0 0 $(echo "$drives" | tr '\n' ' '))

# Print the selected drive
echo "Selected drive: $selected_drive"
```

On an RPi eith SDcard (skipped), SSD and a USB drive attached:
![image](https://user-images.githubusercontent.com/43343391/214062741-e4919a46-0d98-407b-9b8f-db3d6f4c2019.png)

On a server with various disks with the ZFS pools listed counting the available space:
![image](https://user-images.githubusercontent.com/43343391/214067409-13727929-3b2b-4530-9812-11ccfa2a0025.png)

**Comment by rootzoll** [comment]
Closing this issue because we tend to remove BTRFS and not do ZFS within RaspiBlitz - see: https://github.com/raspiblitz/raspiblitz/issues/2045#issuecomment-2471845122

But there will be more options to choose drives on Setup.
