### ISSUE TITLE
RaspiBlitz Tor WebUI: Opening Mempool.space does not work (redirects to local IP?)

### ISSUE THREAD

**Issue by ExchangeREC** [raspiblitz/raspiblitz#3635]
Hi everyone,

when accesing the Raspiblitz WebUI of version 1.8.0.c **via Tor** and then heading to
 _-> Apps -> Mempool.space -> "Open"_
It opens a "_about:blank_" page. 

I think it maybe tries to open the local Mempool.space IP instead of the Tor hidden service address?
Could the Raspiblitz Web UI, when accessed over Tor, automatically recognize that it is accessed over Tor and redirect to the hidden service of Mempool.space instead of the (allegedly) local one?

**Comment by rootzoll** [comment]
Marked for v1.10 to check all WebUI services with Tor again

**Comment by cstenglein** [comment]
Added a detection if the url ends with ".onion"
If it does, the "Open" buttons opens the TOR url, otherwise the local ip

**Comment by cstenglein** [comment]
This should work with 1.9.0

Closing this for now, if it doesn't work, please re-open.
