### ISSUE TITLE
Mempool and Thunderhub can not be installed

### ISSUE THREAD

**Issue by StellarStoic** [raspiblitz/raspiblitz#3640]
My issue is that every installation try of a Mempool and Tunderhub has failed on **V1.8 patched** 
The 32GB SD card is new, fast, and durable. I'm running Blitz over wifi on Raspberry 4b 8Gb, 2TB SSD

As I said. installing Mempool or Thunderhub always failed.
![Screenshot (199)](https://user-images.githubusercontent.com/34000272/215330382-09416be3-1cde-4a0c-901c-4d36972f9382.png)
********************************************************
![Screenshot (201)](https://user-images.githubusercontent.com/34000272/215330493-9e7100cc-3548-473f-a51d-a51670f24ebe.png)

Here are the logs...

`sudo cat /var/cache/raspiblitz/debug.log | nc termbin.com 9999`
raspiblitz debug logs: https://termbin.com/3oefe 
Mempool installation log: https://termbin.com/zkux
Thunderhub installation log: https://termbin.com/ricl7 (Line 3282 gives an error about connection but I am sure the connection is just fine and I'm not behind any proxy)

Then I upgraded the Raspiblitz to **v1.9.0rc1** as Openoms suggested
Raspiblitz debug logs: https://termbin.com/tlqu

I could install Thunderhub (The status on webUI says installation successful and even got the links to the service) but couldn't run it (I reinstalled it two times and could not get it to run. Log was always the same "This site can’t be reached")
thunderbird log: https://termbin.com/atio

![Screenshot (206)](https://user-images.githubusercontent.com/34000272/215343648-9814ed60-7335-4b47-822f-b37e92a12a96.png)

When trying to install Mempool, it said it is already installed but it wasn't (No logs, just a picture)

![Screenshot (202)](https://user-images.githubusercontent.com/34000272/215330628-acbf5ee2-a201-42c0-be4d-a2593db8ffc0.png)

Openoms also suggested updating node version with `config.scripts/bonus.nodejs.sh on`
Old node version: v16.14.2
node version after update: 18.12.0
I also did `config.scripts/bonus.nodejs.sh off` and "on" again

There were no changes doing that. I still can't install mempool and thundehub .

For example what Thunderhug log is complaining about after all that...

*** LAST 20 Thunderhub LOGS ***
sudo journalctl -u thunderhub -b --no-pager -n20
-- Journal begins at Sun 2023-01-29 04:34:17 GMT, ends at Sun 2023-01-29 16:03:2        6 GMT. --
Jan 29 16:02:45 raspberrypi systemd[1]: thunderhub.service: Scheduled restart jo        b, restart counter is at 4.
Jan 29 16:02:45 raspberrypi systemd[1]: Stopped ThunderHub daemon.
Jan 29 16:02:45 raspberrypi systemd[1]: thunderhub.service: Consumed 1.603s CPU         time.
Jan 29 16:02:45 raspberrypi systemd[1]: Started ThunderHub daemon.
Jan 29 16:02:46 raspberrypi npm[679854]: > thunderhub@0.13.6 start
Jan 29 16:02:46 raspberrypi npm[679854]: > cross-env NODE_ENV=production nest start
Jan 29 16:02:46 raspberrypi npm[679978]: sh: 1: cross-env: not found
Jan 29 16:02:46 raspberrypi systemd[1]: thunderhub.service: Main process exited,code=exited, status=127/n/a
Jan 29 16:02:46 raspberrypi systemd[1]: thunderhub.service: Failed with result 'exit-code'.
Jan 29 16:02:46 raspberrypi systemd[1]: thunderhub.service: Consumed 1.690s CPUtime.
Jan 29 16:03:17 raspberrypi systemd[1]: thunderhub.service: Scheduled restart job, restart counter is at 5.
Jan 29 16:03:17 raspberrypi systemd[1]: Stopped ThunderHub daemon.
Jan 29 16:03:17 raspberrypi systemd[1]: thunderhub.service: Consumed 1.690s CPU time.
Jan 29 16:03:17 raspberrypi systemd[1]: Started ThunderHub daemon.
Jan 29 16:03:18 raspberrypi npm[684376]: > thunderhub@0.13.6 start
Jan 29 16:03:18 raspberrypi npm[684376]: > cross-env NODE_ENV=production nest start
Jan 29 16:03:19 raspberrypi npm[684728]: sh: 1: cross-env: not found
Jan 29 16:03:19 raspberrypi systemd[1]: thunderhub.service: Main process exited,code=exited, status=127/n/a
Jan 29 16:03:19 raspberrypi systemd[1]: thunderhub.service: Failed with result 'exit-code'.
Jan 29 16:03:19 raspberrypi systemd[1]: thunderhub.service: Consumed 1.896s CPU time.

Next, I will start fresh and update node to v18.12.9 before installing other apps.

_To be continued..._

**Starting fresh on v1.8...**

The first app that I tried to install is Mempool and got the same error as before.  ("Try to update to npm@9.4.0") So I did that and came across a blockade about some permissions and here's the log of a mempool install: https://termbin.com/zw37
![Screenshot (222)](https://user-images.githubusercontent.com/34000272/215351425-9bab1219-c608-420a-9fb0-3db2e79113b4.png)

Updating npm with `npm install -g npm@9.4.0`  give this results:  https://termbin.com/u9v6n

![Screenshot (224)](https://user-images.githubusercontent.com/34000272/215351588-903f4197-0cb3-4732-8c2b-7e8c7656a213.png)

I've tried to update npm with `sudo npm install -g npm@9.4.0` and the new version is installed but that still didn't solve the problem with these two apps unfortunately. 
The Network error has gone after an npm update and there's another one https://termbin.com/vqq8

![Screenshot (225)](https://user-images.githubusercontent.com/34000272/215355590-6a147caa-e24a-4181-b93d-2d3c65a59c24.png)

**********************************

**MEMPOOL has been installed**

I asked chatGPT what this error could be, and the AI gave me an important clue...

![Screenshot (226)](https://user-images.githubusercontent.com/34000272/215565568-cc987a9b-9105-4b78-a8af-0a8ca655005a.png)

 Deleting  `sudo rm -rf /home/mempool/mempool/frontend/node_modules`  folder lets through a clean installation of  Mempool. 

The mempool operation is completed :)

Next is Thunderhub...

**Comment by openoms** [comment]
A few things here:
the first screenshot suggests a connection problem - maybe related to VPN / ISP?


when there are permission errors often using `sudo` is the solution, but thsi shouldn't be necessary for the pinned versions. 

The install works on my RPi on the dev branch so couldn't reproduce this so far.

Consider trying again a bit later and see if anyone else has this issue.

**Comment by StellarStoic** [comment]
Mempool has been successfully installed after deleting `/home/mempool/mempool/frontend/node_modules` folder.

**Comment by StellarStoic** [comment]
I repeated the process a few time. Fresh instalation of v1.8+patch (No way I can install mempool and thunderhub on this stable versions). 
On v1.9rc1 mempool installed smothly (Could be because of the newer node version 18.12.9) but I still can't install thunderhub I always get some weird errors https://termbin.com/8b3z.

**Comment by StellarStoic** [comment]
I will close this issue since I think that's unique to my setup.
RTL is working so Thunderhub is not really necesery for me atm. 
I will post if I get some new clues.

**Comment by StellarStoic** [comment]
After idk how many tries, I finally installed everything that Raspiblitz app stack has to offer including the ones I have issues with. 

What makes this happen...

Flashed 1.8.0 version > +patch > upgrade to 1.9.0rc2

I upgraded npm with `sudo npm install -g npm@9.4.2`

Then I followed this [tutorial](https://thisdavej.com/upgrading-to-more-recent-versions-of-node-js-on-the-raspberry-pi/)  where I upgraded the nodejs to the recent version which is now _v18.12.0_

I did run the `sudo apt update` command along the process and it could be that the issue was there the whole time because the Pi's dependencies weren't updated. I never run this command before.

**Comment by dskvr** [comment]
I am having a similar problem. When thunderhub is installed via raspiblitz GUI, it reports successful installation but port `3010` is not accessible.

**Comment by StellarStoic** [comment]
> I am having a similar problem. When thunderhub is installed via raspiblitz GUI, it reports successful installation but port `3010` is not accessible. 

I didn't have issues with ports. Check firewall or look if something else has occupied this port number.
