### ISSUE TITLE
Raspiblitz showing 2 network connections

### ISSUE THREAD

**Issue by ryan1501** [raspiblitz/raspiblitz#3645]
My raspiblitz is showing it is connected to wifi and ethernet.  I'm only able to connect to what is showing on wifi. How do I change this to show only my ethernet ip?

**Comment by openoms** [comment]
where is this displayed?

usually where the local IP is gathered the first value is taken:
```
localip=$(hostname -I | awk '{print $1}')
```

**Comment by ryan1501** [comment]
looking at my router I see where it says I have raspberry pi hooked up to ethernet and wifi. I think it splits into to around the "preparing setup" screen on raspiblitz

**Comment by openoms** [comment]
the comand:
`ip -a`  and `hostname -I`
shows you the IP addresses on all available interfaces.

By default we use the first value from  `hostname -I`.

Currently there is no way to choose which other one to display.
