### ISSUE TITLE
Dark theme Payment received checkmark not visible.

### ISSUE THREAD

**Issue by tlindi** [raspiblitz/raspiblitz#3648]
![image](https://user-images.githubusercontent.com/7249767/215793635-4cf151ea-bb0e-484e-9fda-01396d50abd7.png)

**Comment by rootzoll** [comment]
This seems to be Breez releated - not RaspiBlitz ... maybe post issue on Breez repos?

**Comment by tlindi** [comment]
Oops. Sorry. U right, I posted totally wrong plase.
