### ISSUE TITLE
BTCPay Server: need to update NBXplorer because of big block

### ISSUE THREAD

**Issue by ndeet** [raspiblitz/raspiblitz#3649]
The 3,9 MB block breaks NBXplorer prior to version 2.3.45, so no payments will show up. You are currently running v 2.3.28 https://github.com/rootzoll/raspiblitz/blob/v1.8/home.admin/config.scripts/bonus.btcpayserver.sh#L6

See this issue https://github.com/dgarage/NBXplorer/issues/398

Likely not needed but would be good to also bump BTCPay to the latest version 1.7.5.0.

**Comment by NicolasDorier** [comment]
@openoms already on it

**Comment by openoms** [comment]
@ndeet does the update using the menu UPDATE - > BTCPAY work?

if any problems can test test https://github.com/rootzoll/raspiblitz/pull/3641

by switching to the branch:
`btcpay-postgres`
in UPDATE -> PATCH

**Comment by ndeet** [comment]
@opennoms sorry if this is a non problem as you have an update mechanism in place. I checked only the setup script on master branch and saw the outdated NBXplorer and just wanted to raise the issue as users will likely hit that issue soon. Can't test myself atm as my rpi4 currently runs a BTCPay docker setup for some development/testing stuff.

**Comment by openoms** [comment]
No problem, I wouldn't mind to have someone confirming that the update mechanism works even on the older versions before closing.

**Comment by poweruser0815** [comment]
It works. After Installation of 1.9r2 Message disappear. Now other problems which I need to verify. If I created a page and try to open the payment, but it shows nothing. Http 500 bad request
