### ISSUE TITLE
checksum missing last character.

### ISSUE THREAD

**Issue by lewildbeast** [raspiblitz/raspiblitz#3650]
I believe your sha256 checksum displayed for your minimal install image is missing the last 'f' on the page https://github.com/rootzoll/raspiblitz/tree/v1.9

a5e14858a8a5976009bdc198f868f898185cbd9cebde72d077d5ffbf64bb817**f**  /raspiblitz-min-v1.9.0rc1-2022-12-21.img.gz

**Comment by rootzoll** [comment]
thx. Should get fixed with next RC fiels upload.
