### ISSUE TITLE
Uninstalled Blitz API + WebUI and now can't install it back (v1.9.0rc1)

### ISSUE THREAD

**Issue by StellarStoic** [raspiblitz/raspiblitz#3656]
I attempted reinstalling the Blitz API + WebUI because I was getting "403 Forbidden" errors.

Now, I am trying to install it back and I quickly get a notice "_The Blitz API + webUI was installed.  See the status screen for more_"

![Screenshot (242)](https://user-images.githubusercontent.com/34000272/216838609-ed52506b-2111-4594-ab92-eb9deecd5e11.png)

**But it is not installed**
Log clearly says "_BLITZAPI is not running_" https://termbin.com/sc3u5
And when I get back to NodeSettings & Options, the first [  ] A option is without the star. 

I was able to screenshot when this appears for a millisecond

![Screenshot (244)](https://user-images.githubusercontent.com/34000272/216843219-f6430958-742d-4fd1-a17f-c6dc43ef31ca.png)

Are there any other ways to install Blitz API and webUI back?

**Comment by rootzoll** [comment]
OK added fix - please test with next v1.9.0rc2 release

**Comment by StellarStoic** [comment]
Perfect. Everything is as it should be. Thanks
