### ISSUE TITLE
Depreciated TorV2 hostnames in 1.80c

### ISSUE THREAD

**Issue by woeisme** [raspiblitz/raspiblitz#3659]
I recently restored my SD card after a power outage. (jumped from 1.8.0 with LND hotfix directly to 1.8.0c)

The node was hanging attempting to connect to tor nodes that seem to have the TorV2 depreciated hostname format. Eventually I manually added some tor nodes and was back up and running but this could be a problem. 

[see Tor announcement](https://github.com/bitcoin/bitcoin/blob/master/doc/tor.md#compatibility)

relevent entries I noticed in my bitcoin.conf:

> addnode=fno4aakpl6sg6y47.onion
> addnode=toguvy5upyuctudx.onion
> addnode=ndndword5lpb7eex.onion
> addnode=6m2iqgnqjxh7ulyk.onion
> addnode=5tuxetn7tar3q5kp.onion

**Comment by rootzoll** [comment]
OK .. #3662 schould fix this during next update
