### ISSUE TITLE
Wallet empty after failing opening a channel

### ISSUE THREAD

**Issue by StifflersMoM69** [raspiblitz/raspiblitz#366]
I tired open a channel with a node, which failed with eror code (0)? Since failure my Wallet Balance is empty.

**Comment by rootzoll** [comment]
It will "come back" ... it seems that the LND wallet needs some time to take the failed multisig outputs back into account. But I also dont think that this good feedback to the user - please feel free to move over to the LND Dev slack and let them know: https://dev.lightning.community

**Comment by lucbran** [comment]
Hi
had same problem...solved after rebooting..

**Comment by nyxnor** [comment]
pls close this.
