### ISSUE TITLE
1.9.0rc2 CLN grpc plugin not installed

### ISSUE THREAD

**Issue by cstenglein** [raspiblitz/raspiblitz#3674]
Looks like the cln grpc plugin is not installed with 1.9.0rc2

BlitzAPI needs the gprc plugin to work.

**Comment by fusion44** [comment]
On my node the gRPC plugin is already activated for some reason. Can't remember activating it manually, but it was a  long time ago already when i set it up.
![image](https://user-images.githubusercontent.com/503952/218333061-6867037b-27b3-4497-8136-1626e4f12ae6.png)

Normally it should be enough to add `grpc-port=4772` to the core lightning config.

**Comment by openoms** [comment]
It is activated and preinstalled in the fatpack:
```
lightning-cli plugin list

...
      {
         "name": "/home/bitcoin/cl-plugins-available/cln-grpc",
         "active": true,
         "dynamic": false
      },
...
```

During provision:
https://github.com/rootzoll/raspiblitz/blob/b91506b4fb7e6d41edb8c35c4803369af920d671/home.admin/_provision_.sh#L320

recovery:
https://github.com/rootzoll/raspiblitz/blob/b91506b4fb7e6d41edb8c35c4803369af920d671/home.admin/_provision.setup.sh#L347

SETTINGS:
https://github.com/rootzoll/raspiblitz/blob/b91506b4fb7e6d41edb8c35c4803369af920d671/home.admin/00settingsMenuBasics.sh#L445

**Comment by rootzoll** [comment]
TODO: Recheck of fresh install & recover of rc2
