### ISSUE TITLE
1.9.0rc2 http error 500 BTYpay

### ISSUE THREAD

**Issue by poweruser0815** [raspiblitz/raspiblitz#3680]
Hi, when I create a page in a store e.g. Standard Teashop, then no code opens for payment - seems to have something to do with the mapping HTTPS / HTTP - Firefox - no error - Chrome shows http 500 error

**Comment by rootzoll** [comment]
@openoms can you take a look

**Comment by rootzoll** [comment]
rc3 will contain an update of BTCPay - please retest with rc3 once its out

**Comment by cstenglein** [comment]
@poweruser0815 Do you still have this issue?

Closed for now, if it still appears, please re-open
