### ISSUE TITLE
Mempool.space unable to search by wallet address

### ISSUE THREAD

**Issue by hagrace4** [raspiblitz/raspiblitz#3686]
When trying to search a public wallet address using [mempool.space](http://mempool.space/) from my self-hosted node. The wallet address is valid, and has an incoming transaction. I am able to search by Tx hash and see the wallet as an output, but when I click the address output i receive the error as well.  Also occurs when searching for Any wallet.

I am receiving the following error:
"Error loading address data.
(Connection to server lost, please retry)"

I can search anything by Tx hash, but am unable to search successfully by a public wallet address.
![Screenshot from 2023-02-18 19-00-02](https://user-images.githubusercontent.com/36256262/219909743-15313b51-16a8-4dca-8f38-48b453c8e856.png)

**Comment by openoms** [comment]
install an electrum server such as Electrs
