### ISSUE TITLE
Over 2 weeks and only 36% synced

### ISSUE THREAD

**Issue by ChumBoxBaron** [raspiblitz/raspiblitz#3687]
This is probably frequently asked but not sure what to do... any way to troubleshoot if I've done something wrong? I'm a noob but I got a node operational once before.

**Comment by Nerfzooka** [comment]
Your hardware may be slower, but it took my pi4 3 weeks to sync to100% last month.
At 2 weeks it got to 85%

**Comment by ChumBoxBaron** [comment]
: ( i have a pi4...

**Comment by openoms** [comment]
when cnnected to yor node with ssh press CTRL+C, type:
menu
choose SYSTEM and bitconLOGS to see what is happening.

**Comment by cstenglein** [comment]
@ChumBoxBaron is that still an issue?

Closing for now, if not please re-open
