### ISSUE TITLE
Update & Test LND v0.16.0

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#3692]
The first RC for lnd 0.16.0 is out - lets start to test internally:
https://github.com/lightningnetwork/lnd/releases/tag/v0.16.0-beta.rc1

And once the final lnd is out - we can go v1.9.0rc3 and also go final soon after.

**Comment by kravens** [comment]
LND 0.16.0 beta is working fine for me on the latest raspiblitz 1.9.0 build so far. I've been updating via Update -> Patch menu.

**Comment by rootzoll** [comment]
OK merged the updated lnd for testing  with 1.9.0rc3
