### ISSUE TITLE
Ship a patched CLN 23.02

### ISSUE THREAD

**Issue by Semisol** [raspiblitz/raspiblitz#3706]
Due to CLN requiring the raw description to an invoice that has a description hash, LNbits and BTCPayServer are breaking.

There are 3 solutions:
1. Patch CLN. This is the most straightforward method. I have also tested it.
2. Patch LNbits and BTCPayServer. Would be too time consuming, and still, it requires you have access to the description field, which 99% of the time the app doesn't.
3. Ship an outdated version. This is not good for compatibility and security reasons, and makes you miss out on new features.

Here's a tested patch:
```diff
diff --git a/plugins/pay.c b/plugins/pay.c
index 268e4fca1..bcfdc9a88 100644
--- a/plugins/pay.c
+++ b/plugins/pay.c
@@ -1073,7 +1073,7 @@ static struct command_result *json_pay(struct command *cmd,
                                                    JSONRPC2_INVALID_PARAMS,
                                                    "Invalid bolt11: missing description");
                        }
-                       if (!description)
+                       if (!description && false)
                                return command_fail(cmd,
                                                    JSONRPC2_INVALID_PARAMS,
                                                    "bolt11 uses description_hash, but you did not provide description parameter");
```

**Comment by openoms** [comment]
I suggest to use `sed` to change that line after downloading and PGP verifying the code for maximum transparency (don't maintain a patched fork).

**Comment by callebtc** [comment]
Great to see this. The breaking change is [here](https://github.com/ElementsProject/lightning/commit/2afe7a1856b04177898e2dea6b1050d4c8477d87).

**Comment by openoms** [comment]
The
``` 
sudo -u bitcoin sed      .....            plugins/pay.c
```
line can be put here:
https://github.com/rootzoll/raspiblitz/blob/1ae636b265a21edf2102787e5bbff0984727fc1c/home.admin/config.scripts/cl.install.sh#L137

so either change can be tested and PRs are welcome.

Patch to the `dev` branch and after the install script is edited uninstall the CLN binaries:
```
config.scripts/cl.install.sh off purge
```
install and switch the service on:
```
config.scripts/cl.install.sh on
```

**Comment by Semisol** [comment]
> The
> 
> ```
> sudo -u bitcoin sed      .....            plugins/pay.c
> ```
> 
> line can be put here:
> 
> https://github.com/rootzoll/raspiblitz/blob/1ae636b265a21edf2102787e5bbff0984727fc1c/home.admin/config.scripts/cl.install.sh#L137
> 
> so either change can be tested and PRs are welcome.
> 
> Patch to the `dev` branch and after the install script is edited uninstall the CLN binaries:
> 
> ```
> config.scripts/cl.install.sh off purge
> ```
> 
> install and switch the service on:
> 
> ```
> config.scripts/cl.install.sh on
> ```

git apply?

**Comment by openoms** [comment]
> git apply?

Any solution can play which can be easily applied even now if someone wants to fix their instance.

**Comment by openoms** [comment]
We will be able to use this PR / commit in master when merged or the minor version release soon: https://github.com/ElementsProject/lightning/pull/6092

**Comment by rootzoll** [comment]
We will use core-lightning v23.02.2 which contains a rollback on the critical change - PR #3716 merged
