### ISSUE TITLE
Force close with several nodes

### ISSUE THREAD

**Issue by puehri** [raspiblitz/raspiblitz#3713]
Hi,

it is currently the second time, this happens. I don't know why or how.
Sometimes my node automatically closes channels (Today were 4 channels closed. Only 3 in the screenshot, the other one already closed).

Is there a setting i don't know? Or might this be a bug? 
Has anyone else experienced this?

I am using the currently released version of RaspiBlitz 1.8.

![grafik](https://user-images.githubusercontent.com/128312484/226191795-18fd6322-78ef-4fe3-ac2b-c3def2b6ff0d.png)

I first experienced this 2 weeks ago, but due to "Remote Force Close" I thought they closed the channel, but thy don't know either, at least those I asked.

**Comment by rootzoll** [comment]
There is no special feature or setting in raspiblitz to force close channels automatically ... best would be (if you havent already) to ask in the Telegram groups if others saw similar things (links listed at https://raspiblitz.org) or ask in other lnd or cln user groups.

**Comment by puehri** [comment]
Did not happen again. -> Closed
