### ISSUE TITLE
Tor README contradiction

### ISSUE THREAD

**Issue by raumi75** [raspiblitz/raspiblitz#372]
The README.md file states:

> To try it out just switch on the service - you can deactivate later on if its not working for you.
> 
> The TOR integration is experimental and at the moment there is no way to switch off TOR again.

Which of these lines is true? Can I deactivate it later or can I never switch it off again?

**Comment by rootzoll** [comment]
It can be switched on and off now ... the other line was a left over from the old doc.

**Comment by rootzoll** [comment]
OK removed from the README.
