### ISSUE TITLE
Use Tor socks for CoinJoin plugin BTCPAY server

### ISSUE THREAD

**Issue by kravens** [raspiblitz/raspiblitz#3729]
![image](https://user-images.githubusercontent.com/9646902/229341109-62777fdb-4e14-4cef-b79f-69081e81eacc.png)
I've been playing with the new plugin from BTCPay server that allows to do CoinJoins and host a coordinator service, but I get this error that only clearnet is used. From Kukks the dev I got this specific configuration line that is missing: https://github.com/btcpayserver/btcpayserver-docker/blob/6e9b85a9c82a78b6bd5b6ddba330bd853a4998ba/docker-compose-generator/docker-fragments/opt-add-tor.yml#L14

>  btcpayserver:
    environment:
      HIDDENSERVICE_NAME: BTCPayServer
      HIDDENSERVICE_REVERSEPROXY: nginx
      BTCPAY_TORRCFILE: /usr/local/etc/tor/torrc-2
      BTCPAY_SOCKSENDPOINT: tor:9050
    volumes:
      - "tor_servicesdir:/var/lib/tor/hidden_services"
      - "tor_torrcdir:/usr/local/etc/tor/"

Is it possible to add this line by default in Raspiblitz? (I'm on 1.9 branch, running behind Tor but added hybrid clearnet for LND and BTCPay myself)
Or should I set it up manually somewhere?

**Comment by kravens** [comment]
![image](https://user-images.githubusercontent.com/9646902/229342183-c6a4ba14-adfa-451b-95e9-67f51d8d781a.png)
Fun fact, the BTCPay Server is actually running behind Tor while showing this error.

**Comment by openoms** [comment]
Here is where BTCpay is configured:
https://github.com/rootzoll/raspiblitz/blob/dev/home.admin/config.scripts/bonus.btcpayserver.sh#L80-L96
rewriting the file:
`/home/btcpay/.btcpayserver/Main/settings.config`

You can test editing manually then restart BTCpay.

**Comment by openoms** [comment]
Managed to reproduce, but these are settings for a Docker setup. Maybe @Kukks could give us some pointers what is expected here if BTCpay is not running in Docker and Tor is available?

**Comment by Kukks** [comment]
I believe a  config line  `socksendpoint=tor:9050` should do the trick

**Comment by openoms** [comment]
> socksendpoint=tor:9050

thanks! Adding:
```
socksendpoint=127.0.0.1:9050
```
to the file:
```
/home/btcpay/.btcpayserver/Main/settings.config
sudo systemctl restart btcpayserver
```
did it:
```
info: PayServer:      Connected to WebSocket of NBXplorer (BTC)
info: Configuration:  Now listening on: http://127.0.0.1:23000
info: zksnacks:       Connected to coordinator
```
![image](https://user-images.githubusercontent.com/43343391/232208349-65006dd4-7c9f-4b6f-8408-a1101ccf895e.png)


Adding it to the the default config.

**Comment by Kukks** [comment]
> > socksendpoint=tor:9050
> 
> thanks! Adding:
> ```
> socksendpoint=127.0.0.1:9050
> ```
> to the file:
> ```
> /home/btcpay/.btcpayserver/Main/settings.config
> sudo systemctl restart btcpayserver
> ```
> did it:
> ```
> info: PayServer:      Connected to WebSocket of NBXplorer (BTC)
> info: Configuration:  Now listening on: http://127.0.0.1:23000
> info: zksnacks:       Connected to coordinator
> ```
> ![image](https://user-images.githubusercontent.com/43343391/232208349-65006dd4-7c9f-4b6f-8408-a1101ccf895e.png)
> 
> 
> Adding it to the the default config.

For future reference,  all the docker env variables are usable in the configfl file if your remove the BTCPAY_ prefix

**Comment by kravens** [comment]
> > > socksendpoint=tor:9050
> > 
> > 
> > thanks! Adding:
> > ```
> > socksendpoint=127.0.0.1:9050
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to the file:
> > ```
> > /home/btcpay/.btcpayserver/Main/settings.config
> > sudo systemctl restart btcpayserver
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > did it:
> > ```
> > info: PayServer:      Connected to WebSocket of NBXplorer (BTC)
> > info: Configuration:  Now listening on: http://127.0.0.1:23000
> > info: zksnacks:       Connected to coordinator
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://user-images.githubusercontent.com/43343391/232208349-65006dd4-7c9f-4b6f-8408-a1101ccf895e.png)
> > Adding it to the the default config.
> 
> For future reference, all the docker env variables are usable in the configfl file if your remove the BTCPAY_ prefix

Can confirm that adding this line fixed the configuration for me too, no more warnings that I'm coinjoining via clearnet! Thanks for the help ⚡
