### ISSUE TITLE
Blockchain progress gives several restarts after minutes and stops

### ISSUE THREAD

**Issue by smartbart1** [raspiblitz/raspiblitz#3730]
Blockchain progress get stuck. 

" Failed to start Bitcoin daemon"

Already tried flashing ssd again.

What can I do?

Log:

`***************************************************************
* RASPIBLITZ DEBUG LOGS
***************************************************************
blitzversion: 1.8.0
chainnetwork: bitcoin / test
 16:23:08 up  3:05,  2 users,  load average: 2.67, 2.61, 2.68

*** SETUPPHASE / BOOTSTRAP ***
see logs: cat /home/admin/raspiblitz.log
setupPhase--> done
state--> ready

*** BACKGROUNDSERVICE ***
to monitor Background service call: sudo journalctl -f -u background

*** BLOCKCHAIN (MAINNET) SYSTEMD STATUS ***
● bitcoind.service - Bitcoin daemon
     Loaded: loaded (/etc/systemd/system/bitcoind.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sun 2023-04-02 14:07:46 BST; 2h 15min ago
    Process: 324163 ExecStartPre=/home/admin/config.scripts/blitz.systemd.sh log blockchain STARTED (code=exited, status=0/SUCCESS)
    Process: 324174 ExecStartPre=/bin/chgrp bitcoin /mnt/hdd/bitcoin (code=exited, status=1/FAILURE)
        CPU: 62ms

Apr 02 14:07:46 raspberrypi systemd[1]: bitcoind.service: Failed with result 'exit-code'.
Apr 02 14:07:46 raspberrypi systemd[1]: Failed to start Bitcoin daemon.

*** LAST BLOCKCHAIN (MAINNET) ERROR LOGS ***
sudo journalctl -u bitcoind -b --no-pager -n8
-- Journal begins at Wed 2022-07-20 12:10:49 BST, ends at Sun 2023-04-02 16:23:08 BST. --
Apr 02 14:07:46 raspberrypi systemd[1]: bitcoind.service: Control process exited, code=exited, status=1/FAILURE
Apr 02 14:07:46 raspberrypi systemd[1]: bitcoind.service: Failed with result 'exit-code'.
Apr 02 14:07:46 raspberrypi systemd[1]: Failed to start Bitcoin daemon.
Apr 02 14:07:46 raspberrypi systemd[1]: bitcoind.service: Scheduled restart job, restart counter is at 6.
Apr 02 14:07:46 raspberrypi systemd[1]: Stopped Bitcoin daemon.
Apr 02 14:07:46 raspberrypi systemd[1]: bitcoind.service: Start request repeated too quickly.
Apr 02 14:07:46 raspberrypi systemd[1]: bitcoind.service: Failed with result 'exit-code'.
Apr 02 14:07:46 raspberrypi systemd[1]: Failed to start Bitcoin daemon.

*** LAST BLOCKCHAIN (MAINNET) 20 INFO LOGS ***
sudo tail -n 20 /mnt/hdd/bitcoin/debug.log
2023-04-02T13:05:15Z UpdateTip: new best=000000000000046ca16470171307eb6e43acfa20a24632c09478a047899818a1 height=214002 version=0x00000001 log2_work=69.218606 tx=10432417 date='2012-12-28T11:10:15Z' progress=0.012825 cache=468.3MiB(3461090txo)
2023-04-02T13:05:15Z UpdateTip: new best=000000000000035062f487684d4786271810a5b891da488e5b0035f1c380bd76 height=214003 version=0x00000002 log2_work=69.218633 tx=10432878 date='2012-12-28T11:17:24Z' progress=0.012826 cache=468.3MiB(3461138txo)
2023-04-02T13:05:15Z UpdateTip: new best=000000000000039004f3b036dfe3a55bf4fa58e8eccb2a3182310e9ea2f6c944 height=214004 version=0x00000001 log2_work=69.218660 tx=10433133 date='2012-12-28T11:24:04Z' progress=0.012826 cache=468.3MiB(3461143txo)
2023-04-02T13:05:15Z UpdateTip: new best=00000000000003648c6adb0c4b458739e79c953854b1c7e2ae2206e6cd7d9252 height=214005 version=0x00000002 log2_work=69.218687 tx=10433145 date='2012-12-28T11:23:44Z' progress=0.012826 cache=468.3MiB(3461127txo)
2023-04-02T13:05:15Z UpdateTip: new best=0000000000000121a01c5f271d3f6a1fe00169b056d4158494850911877c8757 height=214006 version=0x00000001 log2_work=69.218714 tx=10433152 date='2012-12-28T11:24:26Z' progress=0.012826 cache=468.3MiB(3461118txo)
2023-04-02T13:05:15Z UpdateTip: new best=00000000000001d50183c9d4b462276f3dd67b677187a2aa9d0f4036f5cbf817 height=214007 version=0x00000001 log2_work=69.218741 tx=10433195 date='2012-12-28T11:26:36Z' progress=0.012826 cache=468.3MiB(3460998txo)
2023-04-02T13:06:37Z Unable to open file /mnt/hdd/bitcoin/blocks/blk00034.dat
2023-04-02T13:06:37Z ERROR: WriteBlockToDisk: OpenBlockFile failed
2023-04-02T13:06:37Z *** Failed to write block
2023-04-02T13:06:37Z Error: A fatal internal error occurred, see debug.log for details
2023-04-02T13:06:37Z tor: Thread interrupt
2023-04-02T13:06:37Z Shutdown: In progress...
2023-04-02T13:06:37Z addcon thread exit
2023-04-02T13:06:37Z RemoveLocal(bphqzt2bz57nthuw3kuhnhdxcjjo7gbgfrke32trrgsipq6jozw7wdyd.onion:8333)
2023-04-02T13:06:37Z torcontrol thread exit
2023-04-02T13:06:37Z opencon thread exit
2023-04-02T13:06:37Z ERROR: ProcessNewBlock: AcceptBlock FAILED (AcceptBlock: Failed to find position to write new block to disk)
2023-04-02T13:06:37Z msghand thread exit
2023-04-02T13:06:37Z DeleteAuthCookie: Unable to remove random auth cookie file: filesystem error: cannot remove: Read-only file system [/mnt/hdd/bitcoin/.cookie]
2023-04-02T13:06:37Z net thread exit

*** LND (MAINNET) SYSTEMD STATUS ***
- OFF by config -

*** CORE LIGHTNING (MAINNET) SYSTEMD STATUS ***
- not activated -

*** BLOCKCHAIN (TESTNET) SYSTEMD STATUS ***
- OFF by config -
*** LND (TESTNET) SYSTEMD STATUS ***
- OFF by config -

*** CORE LIGHTNING (TESTNET) SYSTEMD STATUS ***
- not activated -

*** BLOCKCHAIN (SIGNET) SYSTEMD STATUS ***
- OFF by config -
*** LND (SIGNET) SYSTEMD STATUS ***
- OFF by config -

*** CORE LIGHTNING (SIGNET) SYSTEMD STATUS ***
- not activated -

*** NGINX SYSTEMD STATUS ***
● nginx.service - A high performance web server and a reverse proxy server
     Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/nginx.service.d
             └─raspiblitz.conf
     Active: active (running) since Sun 2023-04-02 13:18:28 BST; 3h 4min ago
       Docs: man:nginx(8)
   Main PID: 867 (nginx)
      Tasks: 5 (limit: 4531)
        CPU: 165ms
     CGroup: /system.slice/nginx.service
             ├─867 nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
             ├─869 nginx: worker process
             ├─870 nginx: worker process
             ├─871 nginx: worker process
             └─872 nginx: worker process

Apr 02 13:18:26 raspberrypi systemd[1]: Starting A high performance web server and a reverse proxy server...
Apr 02 13:18:28 raspberrypi systemd[1]: Started A high performance web server and a reverse proxy server.

*** LAST NGINX LOGS ***
sudo journalctl -u nginx -b --no-pager -n20
-- Journal begins at Wed 2022-07-20 12:10:49 BST, ends at Sun 2023-04-02 16:23:08 BST. --
Apr 02 13:18:26 raspberrypi systemd[1]: Starting A high performance web server and a reverse proxy server...
Apr 02 13:18:28 raspberrypi systemd[1]: Started A high performance web server and a reverse proxy server.
--> CHECK CONFIG: sudo nginx -t
nginx: [emerg] cannot load certificate "/mnt/hdd/app-data/nginx/tls.cert": BIO_new_file() failed (SSL: error:02001005:system library:fopen:Input/output error:fopen('/mnt/hdd/app-data/nginx/tls.cert','r') error:2006D002:BIO routines:BIO_new_file:system lib)
nginx: configuration file /etc/nginx/nginx.conf test failed

*** BLITZAPI SYSTEMD STATUS ***
● blitzapi.service - BlitzBackendAPI
     Loaded: loaded (/etc/systemd/system/blitzapi.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2023-04-02 13:18:27 BST; 3h 4min ago
   Main PID: 780 (python)
      Tasks: 9 (limit: 4531)
        CPU: 2min 4.166s
     CGroup: /system.slice/blitzapi.service
             └─780 /usr/bin/python -m uvicorn app.main:app --port 11111 --host=0.0.0.0 --root-path /api

Apr 02 14:07:45 raspberrypi python[780]:     raise HTTPException(
Apr 02 14:07:45 raspberrypi python[780]: fastapi.exceptions.HTTPException: 500

*** LAST BLITZAPI LOGS ***
sudo journalctl -u blitzapi -b --no-pager -n20
-- Journal begins at Wed 2022-07-20 12:10:49 BST, ends at Sun 2023-04-02 16:23:09 BST. --
Apr 02 14:07:45 raspberrypi python[780]: future: <Task finished name='Task-131' coro=<_handle_forward_event_listener() done, defined at ./app/repositories/lightning.py:236> exception=HTTPException(status_code=500, detail='Socket closed')>
Apr 02 14:07:45 raspberrypi python[780]: Traceback (most recent call last):
Apr 02 14:07:45 raspberrypi python[780]:   File "./app/repositories/ln_impl/lnd_grpc.py", line 687, in listen_forward_events
Apr 02 14:07:45 raspberrypi python[780]:     async for e in _router_stub.SubscribeHtlcEvents(request):
Apr 02 14:07:45 raspberrypi python[780]:   File "/usr/local/lib/python3.9/dist-packages/grpc/aio/_call.py", line 326, in _fetch_stream_responses
Apr 02 14:07:45 raspberrypi python[780]:     await self._raise_for_status()
Apr 02 14:07:45 raspberrypi python[780]:   File "/usr/local/lib/python3.9/dist-packages/grpc/aio/_call.py", line 236, in _raise_for_status
Apr 02 14:07:45 raspberrypi python[780]:     raise _create_rpc_error(await self.initial_metadata(), await
Apr 02 14:07:45 raspberrypi python[780]: grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
Apr 02 14:07:45 raspberrypi python[780]:         status = StatusCode.UNAVAILABLE
Apr 02 14:07:45 raspberrypi python[780]:         details = "Socket closed"
Apr 02 14:07:45 raspberrypi python[780]:         debug_error_string = "{"created":"@1680440865.097885694","description":"Error received from peer ipv4:127.0.0.1:10009","file":"src/core/lib/surface/call.cc","file_line":952,"grpc_message":"Socket closed","grpc_status":14}"
Apr 02 14:07:45 raspberrypi python[780]: >
Apr 02 14:07:45 raspberrypi python[780]: During handling of the above exception, another exception occurred:
Apr 02 14:07:45 raspberrypi python[780]: Traceback (most recent call last):
Apr 02 14:07:45 raspberrypi python[780]:   File "./app/repositories/lightning.py", line 256, in _handle_forward_event_listener
Apr 02 14:07:45 raspberrypi python[780]:     async for i in ln.listen_forward_events():
Apr 02 14:07:45 raspberrypi python[780]:   File "./app/repositories/ln_impl/lnd_grpc.py", line 715, in listen_forward_events
Apr 02 14:07:45 raspberrypi python[780]:     raise HTTPException(
Apr 02 14:07:45 raspberrypi python[780]: fastapi.exceptions.HTTPException: 500

- TOUCHSCREEN is OFF by config
- Loop is OFF by config
- LND-RTL is OFF by config
- CL-RTL is OFF by config
- Electrum Rust Server is OFF by config
- LIT is OFF by config
- BTCPayServer is OFF by config
- BTC-RPC-Explorer is OFF by config
- LNbits is OFF by config
- Thunderhub is OFF by config
- SPECTER is OFF by config
- SPHINX is OFF by config

*** MOUNTED DRIVES ***
Filesystem     Type      Size  Used Avail Use% Mounted on
/dev/root      ext4       29G  9.5G   19G  34% /
devtmpfs       devtmpfs  1.9G     0  1.9G   0% /dev
tmpfs          tmpfs     1.9G   16K  1.9G   1% /dev/shm
tmpfs          tmpfs     769M  992K  768M   1% /run
tmpfs          tmpfs     5.0M     0  5.0M   0% /run/lock
tmpfs          tmpfs      32M     0   32M   0% /var/cache/raspiblitz
/dev/mmcblk0p1 vfat      253M   31M  222M  12% /boot
/dev/sda1      ext4      916G  8.1G  862G   1% /mnt/hdd
tmpfs          tmpfs     385M   16K  385M   1% /run/user/1000
tmpfs          tmpfs     385M   16K  385M   1% /run/user/1001

*** DATADRIVE ***
# RASPIBLITZ DATA DRIVE Status

# BASICS
isMounted=1
isBTRFS=0
ls: reading directory '/mnt/hdd': Input/output error
hddRaspiData=0
hddRaspiVersion=''
isSSD=0
datadisk='sda'
datapartition='sda1'
hddCandidate='sda'
hddPartitionCandidate='sda1'
hddBlocksBitcoin=0
(standard_in) 1: syntax error
hddBytes=
hddGigaBytes=
hddUsedInfo='9.5G
16K
31M
8.1G (341121%)'
/home/admin/config.scripts/blitz.datadrive.sh: line 438: * 1024: syntax error: operand expected (error token is "* 1024")
error='unkown command'

*** NETWORK ***
localip=192.168.1.103
localiprange=192.168.1.0/24
dhcp=1
network_device=eth0

*** HARDWARE TEST RESULTS ***
UndervoltageReports in Logs: 0

*** SYSTEM CACHE STATUS ***
system_init_time="1680437910"
system_up="11113"
system_vm_vagrant="0"
system_ups_battery=""
system_temp_celsius="46"
system_count_start_blockchain="6"
system_ram_mb="3844"
system_count_start_lightning="1"
system_cpu_load=" 2.86, 2.65, 2.69"
system_count_undervoltage="0"
system_ram_gb="4"
system_ram_available_mb="3518"
system_board="rp4"
system_temp_fahrenheit="115"
system_count_start_tui="0"
system_ups_status="OFF"
system_count_longscan="1"
ln_default_running="0"
ln_default_wallet_onchain_pending="0"
ln_default_channels_pending="0"
ln_default_channels_active="0"
ln_default_alias="willemskantine"
ln_default_activated="1"
ln_default_recovery_mode="0"
ln_default_recovery_done="0"
ln_default_sync_progress="27.92"
ln_default_version="0.15.4-beta"
ln_default_wallet_channels_pending="0"
ln_default_fees_total="0"
ln_default_locked="0"
ln_default_channels_inactive="0"
ln_default_peers="0"
ln_default_sync_initial_done="0"
ln_default_ready="0"
ln_default_sync_chain="0"
ln_default_error_full=""
ln_default_wallet_onchain_balance="0"
ln_default_tor="0"
ln_default_online="0"
ln_default_error_short=""
ln_default_wallet_channels_balance="0"
ln_default_channels_total="0"
btc_default_blocks_behind="571002"
btc_default_sync_initial_done="0"
btc_default_port="8333"
btc_default_blocks_data_kb="5038784"
btc_default_sync_initialblockdownload="1"
btc_default_activated="1"
btc_default_peers="10"
btc_default_version="v23.0.0"
btc_default_online="0"
btc_default_mempool_transactions="0"
btc_default_ready="0"
btc_default_error_full=""
btc_default_sync_percentage="1.23"
btc_default_synced="0"
btc_default_blocks_headers="783616"
btc_default_error_short=""
btc_default_blocks_verified="212614"
btc_default_sync_progress="0.01231570998585008"
btc_default_running="0"

*** LOGFILES ***
Archived and active journals take up 176.0M in the file system.
189M    /var/log

*** OPTION: SHARE THIS DEBUG OUTPUT ***
An easy way to share this debug output on GitHub or on a support chat
Use the following command and share the resulting link using termbin.com service and tor proxy:
 debug -l
If tor is failing and you don't mind leaking your ip address to the termbin service, use without tor:
 debug -l -n

Press ENTER to return to main menu.
`

**Comment by smartbart1** [comment]
Also, when trying to remove hdd completely to strart fresh it returns:

rm: cannot remove '/mnt/hdd/*': Read-only file system

**Comment by rootzoll** [comment]
Yeah something with your SSD looks quite strange. Is that a selfbuild setup or a ready-build node (e.g. from Fulmo)?

**Comment by smartbart1** [comment]
it's selfbuild, bought Samsung T7 Portable SSD 1TB and never used before. Reformatted ssd, but same problem. I will now try to download blockchain on windows and ssh to raspberry pi.

Btw, also didn't get my lcd elegoo working, but that may be another issue and is not that important to me.

**Comment by smartbart1** [comment]
@rootzoll 

2023-04-06T18:39:30Z Unable to open file /mnt/hdd/bitcoin/blocks/rev00007.dat
2023-04-06T18:39:30Z ERROR: UndoWriteToDisk: OpenUndoFile failed
2023-04-06T18:39:30Z *** Failed to write undo data
2023-04-06T18:39:30Z Error: A fatal internal error occurred, see debug.log for details
2023-04-06T18:39:30Z tor: Thread interrupt
2023-04-06T18:39:30Z Shutdown: In progress...
2023-04-06T18:39:30Z DeleteAuthCookie: Unable to remove random auth cookie file: filesystem error: cannot remove: Read-only file system [/mnt/hdd/bitcoin/.cookie]
2023-04-06T18:39:30Z ERROR: ConnectTip: ConnectBlock 00000000000007982b6fd9de79e64b18b356835c6865b1380b9483f9ce4b15b4 failed, Failed to write undo data
2023-04-06T18:39:30Z opencon thread exit
2023-04-06T18:39:30Z ERROR: ProcessNewBlock: ActivateBestChain failed (Failed to write undo data)
2023-04-06T18:39:30Z msghand thread exit
2023-04-06T18:39:30Z RemoveLocal(jczcfdsw2g2hujxsj5cnvqqw7cbwdp3vm5owhbsrmsgaen3rdpoeucad.onion:8333)
2023-04-06T18:39:30Z torcontrol thread exit
2023-04-06T18:39:30Z addcon thread exit
2023-04-06T18:39:30Z net thread exit

**Comment by cricktor** [comment]
A Samsung T7 might be too power hungry, while the Samsung T5 seems to work fine. What are the specs of the T7 regarding power consumption?

Inspect your logs with respect to low power issues detected because all the USB interfaces share a common max. power budget of not more than 1.2A on a Raspi 4B. Do you use the true original Raspi power supply? Bad clones could be a nightmare.
