### ISSUE TITLE
so i died error

### ISSUE THREAD

**Issue by Smiril** [raspiblitz/raspiblitz#3737]
04 18:07:36 raspberrypi python[765]: ERROR:root:Unknown answer from Bitcoin Core. Reason: Internal Server Error
Apr 04 18:07:37 raspberrypi dialog[439487]: *** err
Apr 04 18:07:37 raspberrypi dialog[439487]: /dev/tty1: Permission denied
Apr 04 18:07:37 raspberrypi dialog[439487]: *** err
Apr 04 18:07:37 raspberrypi dialog[439487]: Oh, oh, it's an error! possibly I die!

whats this error?

**Comment by openoms** [comment]
can ignore the errors from dialog - these are only from the terminal menu boxes - it couldn't display something this time

you can monitor the journal of individual services using the systemd service name with eg:
```
sudo journalctl -fu bitcoind
```

**Comment by Smiril** [comment]
thank you
