### ISSUE TITLE
LNbits admin UI

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#3799]
On the new LNbits versions extensions can only be installed in admin mode or by the allowed admin users.

Advice would be welcome how to best automate this - or how it is intended by the LNbits devs.

For now the manual process:
```
# stop lnbits
sudo systemctl stop lnbits.service
# add the line: 'LNBITS_ADMIN_UI=true' to the env
echo "LNBITS_ADMIN_UI=true" | sudo tee -a  /home/lnbits/lnbits/.env
# start LNbits again
sudo systemctl start lnbits.service
```
```
# or edit the config file manually
sudo nano  /home/lnbits/lnbits/.env
# and add the line
LNBITS_ADMIN_UI=true
# save and restart the lnbits service
```

Next need to check the logs for the newly generated super user account:
```
sudo journalctl -fu lnbits --since "2 hour ago" | grep "super user account"
```
Will output something like:
```
May 06 19:02:09 raspberrypi sh[821212]: 2023-05-06 19:02:09.04 | SUCCESS | ✔️ Access super user account at: http://127.0.0.1:5000/wallet?usr=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
copy the part with the `/wallet?usr=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx` and paste after your LNbits address in the browser to access the admi UI.

To set it to false once all the needed extension are installed:
```
# stop lnbits
sudo systemctl stop lnbits.service
# disable the ADMIN UI
sudo sed "s/LNBITS_ADMIN_UI=.*/LNBITS_ADMIN_UI=false/g" /home/lnbits/lnbits/.env
# start LNbits again
sudo systemctl start lnbits.service
```

**Comment by rootzoll** [comment]
This was done already in v1.10.0 - closing
