### ISSUE TITLE
RC4: waitsetup response returns wrong message field: "Please Login for Update"

### ISSUE THREAD

**Issue by cstenglein** [raspiblitz/raspiblitz#3805]
When doing a recovery with RC4, the response from `setup/status` looks like this 

```json
{
    "setupPhase": "update",
    "state": "waitsetup",
    "message": "Please Login for Update",
    "initialsync": ""
}
```

The message is wrong IMO since you don't need to login to start the recovery process.

**Comment by cstenglein** [comment]
The same message comes before the provisioning:

```json
{
    "setupPhase": "update",
    "state": "waitprovision",
    "message": "Please Login for Update",
    "initialsync": ""
}
```

**Comment by rootzoll** [comment]
"Login" comes from the SSH days - chaged to a more neutral wording. Will be part of v1.9.0
