### ISSUE TITLE
raspiblitz-1.8.0c web ui settings->shutdown button gives no feedback

### ISSUE THREAD

**Issue by jalbstmeijer** [raspiblitz/raspiblitz#3820]
Hi,

When shutting down a node through the web ui settings->shutdown option, you won't get any visual feedback when confirming a shutdown.
Meaning, I tend to keep on clicking on it although it is already in the shutdown process.

Gr, J

**Comment by rootzoll** [comment]
Yeah thats something on our todo to improve.

**Comment by cstenglein** [comment]
Related to https://github.com/cstenglein/raspiblitz-web/issues/382

**Comment by cstenglein** [comment]
Done with the current version. It now displays a loading spinner while rebooting / shutting down.
