### ISSUE TITLE
QUESTION: 2,8" adafruit display also work?

### ISSUE THREAD

**Issue by MrHyde22** [raspiblitz/raspiblitz#383]
I still have a 2.8 "display of adafruit left, but when I connect it comes only a white screen Unfortunately, I do not know how I get the driver, can someone help me?

**Comment by fluidvoice** [comment]
> I still have a 2.8 "display of adafruit left, but when I connect it comes only a white screen Unfortunately, I do not know how I get the driver, can someone help me?

a question better asked on the Raspberry Pi forum I think.

**Comment by rootzoll** [comment]
Using a different LCD screen is an interesting hack. If someone likes to contribute - open to it. But its not part of the main development at the moment. So I am closing the issue for now.
