### ISSUE TITLE
Lightning Terminal error when trying to create custodial account on version v1.9.0rc5

### ISSUE THREAD

**Issue by FlorianHubl** [raspiblitz/raspiblitz#3831]
When I try to create a custodial account on the Lightning Terminal I get a error: "Unable to register custodial account, proxy error with context lit: invalid macaroon: permission denied" on the Raspiblitz version v1.9.0rc5.
<img width="341" alt="Bildschirmfoto 2023-05-14 um 01 27 03" src="https://github.com/rootzoll/raspiblitz/assets/49409175/9b02d1ef-a8b7-4d0d-8c65-f5191419aaed">

**Comment by rootzoll** [comment]
Steps to reproduce:

https://docs.lightning.engineering/lightning-network-tools/lightning-terminal/accounts#docs-internal-guid-587703e5-7fff-5b2b-8389-3bd9e7bf6d0b

**Comment by rootzoll** [comment]
@guggero I created fresh macaroons but still getting this error - can you give an hint what else to try to make this this work?

**Comment by guggero** [comment]
Which macaroons did you re-create? I think the error can either be from old lnd macaroons or old litd macaroons. Best to try and re-create both (for lnd, you need to delete all three default macaroons, `admin.macaroon`, `readonly.macaroon` and `invoice.macaroon` (singular, not `invoices.macaroon`), then restart `lnd`).

**Comment by rootzoll** [comment]
@guggero I did a complete refresh of all lnd macaroons - especially the admin.macaroon that is named in `litd.conf` with `remote.lnd.macaroonpath=/home/lit/.lnd/data/chain/bitcoin/mainnet/admin.macaroon`, still the same error - where are the litd macaroons are located

**Comment by guggero** [comment]
Not sure where they are on RaspiBlitz, the default location is `~/.lit/<network>/lit.macaroon`.

**Comment by rootzoll** [comment]
@guggero OK found it. I deletetd it also and now it works. 

@FlorianHubl so new lnd macaroons are needed that are created with the right to create subaccounts. On final v1.9.0 release you will be able to do this on RaspiBlitz under "CONNECT > RESET" which then will also reset the litd macaroon.

@guggero quick question in general if we would renew the macaroons by default on the new update - this would make all old macaroons that might get used for example to connect with Zeus invalid, correct? Or if we keep the macaroon.db deleted macaroons still stay valid?

**Comment by guggero** [comment]
As long as  the `macaroon.db` is not deleted, then all previously issued macaroons are still valid.

**Comment by rootzoll** [comment]
@guggero is there anyway to make lnd renew the macaroons without "delete & restart"? Because a restart always is time consuming, locks the wallet and so we need a manual enter of password C again - which is kind of a hassle.

**Comment by guggero** [comment]
Yes, you can bake a new one (see `lncli listpermissions` and `lncli bakemacaroon`) and then delete the old one.

**Comment by rootzoll** [comment]
@guggero Thx. 

TODO for v1.10.0: rewrite `lnd.credentials.sh` to rebacke/sync macaroons without restarting lnd

**Comment by rootzoll** [comment]
Solution so far: On RaspiBlitz SSH menu under "CONNECT > RESET" which then will also reset the litd macaroon now.
