### ISSUE TITLE
Update Shango QR code

### ISSUE THREAD

**Issue by StifflersMoM69** [raspiblitz/raspiblitz#384]
Hi!
I am trying to connect my mobile wallet (shango) and i always get this error after scanning QR Code.

**Comment by rootzoll** [comment]
Shango changed the content of their QR code - will adapt in v1.1 release.

**Comment by rootzoll** [comment]
There was already a commit on master to fix the QR code: https://github.com/rootzoll/raspiblitz/commit/e754d531c748af70f7344a4ac8c2a66fb0c2d7a2

Check if that is working with the lastest version of Shango.

**Comment by StifflersMoM69** [comment]
I can't get it work. Now the code is not beeing recognized. Nothing happens.

**Comment by rootzoll** [comment]
In version 1.0 there is still that old connect QR code that is not working. Please try again once v1.1 is released and you made the update.

**Comment by rootzoll** [comment]
OK v1.1 tested fine with the latest Shango app. Closing issue for v1.1 release.
