### ISSUE TITLE
LND stuck at "scanning blocks"

### ISSUE THREAD

**Issue by 2Beardy** [raspiblitz/raspiblitz#3853]
Here is my debug file. I have been attempting to fix this issue. LND is stuck at "scanning for blocks" but both LND and Main are 100% sync according to the info screen. I have tried patching, repairing, resetting, rebooting, I just can't figure it out. Any recommendations? To note, I am very much dumb on this and it's my first attempt
[debug.txt](https://github.com/rootzoll/raspiblitz/files/11521310/debug.txt)

https://l.termbin.com/surl

**Comment by rootzoll** [comment]
There will be an RaspiBlitz v1.9.0 update this week with a new LND - please try if that update solves your issue.

**Comment by cstenglein** [comment]
@2Beardy  is this still an issue with 1.9.0?

Closing this for now, please re-open if it still persists.
