### ISSUE TITLE
Blockchain Sync Stuck at Same Block Height for Days now

### ISSUE THREAD

**Issue by uncleJim21** [raspiblitz/raspiblitz#3876]
Not sure what happened but I suspect there's something wrong with either read/write or corruption of the magic number. Here are the logs I have:
https://l.termbin.com/1tbcg

**Comment by openoms** [comment]
keep monitoring the bitcoind logs to see what's going wrong - find it in menu - SYSTEM

**Comment by uncleJim21** [comment]
Bitcoind keeps running on a loop saying that leveldb's magic number is corrupted

**Comment by openoms** [comment]
Will need to resync to solve that. Can use the REPAIR menu to reset the chain.

**Comment by cstenglein** [comment]
@uncleJim21 is that still an issue?

Closing for now, if it still is, please re-open.

**Comment by uncleJim21** [comment]
@cstenglein I mean it's still an issue from the standpoint that the DB corrupts and has no recourse without hours of effort. I am just pulling the plug on Raspibitz it's not worth the effort for me. Thanks.
