### ISSUE TITLE
html Status Page

### ISSUE THREAD

**Issue by raumi75** [raspiblitz/raspiblitz#388]
Discussing #88 I posted a command to use a browser to render a dynamic web page on the LCD of the RaspiBlitz without using too much resources.

This weekend I've toyed around with that idea and made some svg-graphics that should render on the pi. The html-code so far is only a mockup, but it's possible to breathe life into this. @frennkie has already prepared python code to make the info-page more flexible.

I'd love to hear feedback from everyone. It's okay to shoot me down, if you think this is not the RaspiBlitz-Way of doing it. I won't take it personal.

You can take a look at it right here: https://jsfiddle.net/raumi75/g8zae1tL/2/

Please feel free to fork and improve it!

**Comment by raumi75** [comment]
This would be a dark mode

https://jsfiddle.net/raumi75/g8zae1tL/31/

**Comment by rootzoll** [comment]
Great work :D I hope you already got some feedback on twitter for the next iterations. Let me know if you have further revisions ready - I will share on twitter to get more feedback on it.

**Comment by rootzoll** [comment]
I am putting this on the v1.1 release milstone. But no pressure and no promise - the main focus of the 1.1 release will be making maintenace and recover easier - but every cool improvement otherwise that is ready by then (targeting (late) April) I love to include :)

**Comment by jay653** [comment]
i like the darkmode! will look good with a fancy case for the raspi.

**Comment by frennkie** [comment]
@raumi75 I'm making progress on this.. do you want to complete the mockup...?! :-D

**Comment by rootzoll** [comment]
HTML status page will get replaced with WebUI login on v1.8.0 release. Closing issue.

**Comment by cstenglein** [comment]
> Closing issue.

Wasn't closed until now. Closing.
