### ISSUE TITLE
lncli listpayments throws error

### ISSUE THREAD

**Issue by dskvr** [raspiblitz/raspiblitz#3950]
```
lncli listpayments
[lncli] could not load global options: could not load TLS cert file: open /root/.lnd/tls.cert: no such file or directory
```

Not sure why it's looking there, because tls.cert is in `/mnt/hdd/lnd` not `/root/.lnd` (And yes, it works when using ` --tlscertpath`, but would prefer for `lncli` to be usable. )

`lncli version 0.15.4-beta commit=v0.15.4-beta`

`/mnt/hdd/lnd/version.info` is empty, otherwise I would provide LND version.

Using most recent raspiblitz

**Comment by rootzoll** [comment]
OK can you test if the available v1.10rc2 is fixing this - download here: https://github.com/raspiblitz/raspiblitz/tree/v1.10#downloading-the-software
