### ISSUE TITLE
can you split Raspiblitz_standard.stl into two files

### ISSUE THREAD

**Issue by eliddell1** [raspiblitz/raspiblitz#396]
I have a small monoprice mini, and am using freecad/Cura to print.  I will admit i am not an expert with freecad, but i can't fit Raspiblitz_standard.stl as one print on my little guy.  and I can't figure out how to separate the bottom and middle pieces from that stl file.  Is it possible to deliver them as two separate stl files?

**Comment by rootzoll** [comment]
I am not into 3D printing myself .. I will post your request on twitter - maybe someone is joining in :)

**Comment by rootzoll** [comment]
@eliddell1 join in on twitter: https://twitter.com/JasonEbacher/status/1102699568846856193

**Comment by CryptoCloaks** [comment]
Let us know if this works!

[RaspiBlitz Standard - 2 Pieces.zip](https://github.com/rootzoll/raspiblitz/files/2928685/RaspiBlitz.Standard.-.2.Pieces.zip)

**Comment by CryptoCloaks** [comment]
For future reference to build on your 3D printing skills.
Take a look at a free program called Fusion360, it's an amazing program for 3D modeling etc.

It will help take your 3D printing to the next level!

**Comment by rootzoll** [comment]
@eliddell1 OK - I added the two splitted files to the GitHub master branch.
@CryptoCloaks much thanks for helping out :D
