### ISSUE TITLE
After update to v1.9.0 - CL Lightning Wallet can not be unlocked

### ISSUE THREAD

**Issue by Minervaaaaa** [raspiblitz/raspiblitz#3968]
This message I get:
A dependency job for lightningd.service failed. See 'journalctl -xe' for details.

This shows my command line:
![grafik](https://github.com/raspiblitz/raspiblitz/assets/92528954/42ef04fa-d7aa-40e6-bd22-116efef0c653)

![grafik](https://github.com/raspiblitz/raspiblitz/assets/92528954/3a6947d3-e210-4782-b569-99df61f66967)

The correct password C was used and I restarted the raspiblitz already via command line. 
Any ideas what could help? Thanks a lot for your help!

**Comment by openoms** [comment]
The following log lines would help a lot. Please share here if not sensitive.

**Comment by Minervaaaaa** [comment]
![grafik](https://github.com/raspiblitz/raspiblitz/assets/92528954/12125a94-6d5c-4d57-99a6-0a8748d0302b)

![grafik](https://github.com/raspiblitz/raspiblitz/assets/92528954/90463621-5371-48cd-b602-77ce988d3837)

**Comment by Minervaaaaa** [comment]
![grafik](https://github.com/raspiblitz/raspiblitz/assets/92528954/280beca3-32a8-4d7e-9624-9e540c392332)

**Comment by Minervaaaaa** [comment]
> The following log lines would help a lot. Please share here if not sensitive.
Are these the right logs you need to look through? Thanks a lot!

**Comment by openoms** [comment]
> Are these the right logs you need to look through? Thanks a lot!

Not really. When you enter the CLN menu after a minute there are the last lines of the journal for CLN and cl.log shown. Have a look at and paste thise please.

**Comment by 0xtrr** [comment]
> This message I get: A dependency job for lightningd.service failed. See 'journalctl -xe' for details.
> 
> This shows my command line: ![grafik](https://user-images.githubusercontent.com/92528954/246319821-42ef04fa-d7aa-40e6-bd22-116efef0c653.png)
> 
> ![grafik](https://user-images.githubusercontent.com/92528954/246319966-3a6947d3-e210-4782-b569-99df61f66967.png)
> 
> The correct password C was used and I restarted the raspiblitz already via command line. Any ideas what could help? Thanks a lot for your help!

If you write `sudo tail -n 50 /mnt/hdd/bitcoin/debug.log` in the terminal to get the Bitcoin Core debug log up, do you find the following line?

```
2023-06-21T15:27:36Z Error: Failed to load database path '/mnt/hdd/bitcoin/wallet.dat'. Data is not in recognized format.
```

Because this seems like the same error as reported in #3970.

**Comment by Minervaaaaa** [comment]
![grafik](https://github.com/raspiblitz/raspiblitz/assets/92528954/169de8ac-2574-4a44-a130-0f80898dcecf)

Looks like I get the same message...
Is any fix for this already available? 
Thanks!

**Comment by 0xtrr** [comment]
I ended up with doing a backup of the CLN data, deleting all data from the HDD besides the blockchain, and then reinstalling the node as a "fresh" node. After the reinstall I restored the CLN node with the backup file. Seems to work just fine now.

**Comment by rootzoll** [comment]
@openoms is in this issue still something relevant for v1.10.0?

**Comment by openoms** [comment]
Didn't get to reproduce this problem. Closing, please reopen if comes up again.
