### ISSUE TITLE
error: cannot open '/mnt/hdd/bitcoin/debug.log' for reading: No such file or directory

### ISSUE THREAD

**Issue by GerdOpp** [raspiblitz/raspiblitz#3969]
Hi all,

Like some other users, I get this error message:
tail: cannot open '/mnt/hdd/bitcoin/debug.log' for reading: No such file or directory

- After reading in telegram group, I restarted bitcoind and the error is gone.
- But when I re-start the raspiblitz it reappears.

Is there anything else I can do that I have overlooked so far?

---------------

UPDATE: I tried booting with a newly flashed SD card and choosing REPAIR. After this, the error is gone. Issue solved!

**Comment by so7ow** [comment]
Any way to fix this error aside from a reflash? Getting it on v1.10 here.

**Comment by rootzoll** [comment]
v1.11.0 (once released) should address this.

**Comment by NilByte** [comment]
SSH and run:

`sudo nano /mnt/hdd/bitcoin/debug.log`

Save the file, but it seems like it doesn't persist a reboot.
