### ISSUE TITLE
Blockchain Progress: x restarts - disablewallet=0

### ISSUE THREAD

**Issue by GregorWedlich** [raspiblitz/raspiblitz#3971]
If I want to connect my Raspiblitz to Fully Noded App (with Bitcoind), for example, it activates the wallet function. As soon as this happens, my node can no longer connect. Only changing the configuration to disablewallet=1 allows my node to synchronize again. However, this way I cant use the node as a wallet or connect it to the "Fully Noded" app.

**Comment by rootzoll** [comment]
I was not able top reproduce this problem - works on my test machine. Would need to take a look into the debug report when your node cannot connect: https://github.com/raspiblitz/raspiblitz/blob/dev/FAQ.md#how-do-i-generate-a-debug-report
