### ISSUE TITLE
Displaying QR code on the LCD/display

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#398]
see https://github.com/rootzoll/raspiblitz/pull/334 merged into dev

test, maybe clean up and also check what to do for people that run the RaspiBlitz without LCD.

**Comment by raumi75** [comment]
Thanks for merging. People without LCD still have the option to display the QR the regular way via ssh.

**Comment by openoms** [comment]
@rootzoll I found that `ANSIUTF8` format QRcode is way smaller then`ANSI256`.
Could this solve the scaling issues or might lead some problems in different terminals? 

Please try in different terminals and OS-es:
```
qrencode -t ANSIUTF8 "https://github.com/rootzoll/raspiblitz/issues/398"
qrencode -t ANSI256 "https://github.com/rootzoll/raspiblitz/issues/398"
```
![image](https://user-images.githubusercontent.com/43343391/109962473-22e84580-7ce3-11eb-9c78-a2e8016d0b4c.png)
