### ISSUE TITLE
Upgrade Raspiblitz v1.9.0 - Blockchain does not connect and update anymore

### ISSUE THREAD

**Issue by md-weber** [raspiblitz/raspiblitz#3988]
I have a similar problem to https://github.com/raspiblitz/raspiblitz/issues/3614 while my debug.log looks a bit different.

Steps I did:

- [x] Flashed a new SD Card to Version 1.9.0 (GitHub release)
- [x] Followed the upgrade progress
- [x] Everything worked fine for a week
- [x] Now no new peers can be found

After shortly checking the logs I find the following errors:

1.  tail: cannot open '/mnt/hdd/lnd/logs/bitcoin/mainnet/lnd.log' for reading: No such file or directory
2. 2023-07-03T17:57:15Z Error: Failed to load database path '/mnt/hdd/bitcoin/wallet.dat'. Data is not in recognized format.
3. Jul 03 18:57:11 raspberrypi systemd[1]: Dependency failed for Lightning Network Daemon.
Jul 03 18:57:11 raspberrypi systemd[1]: lnd.service: Job lnd.service/start failed with result 'dependency'.

Full debug.log file: https://l.termbin.com/2dup

**Comment by openoms** [comment]
This seems to be a duplicate of #3970 

Can you please try the solution here:
https://github.com/raspiblitz/raspiblitz/issues/3970#issuecomment-1619671508

**Comment by md-weber** [comment]
Ah, great I will try that. If I have more / other information I will add it to 3970. Thanks and will close this issue.
