### ISSUE TITLE
LNDg Bad request

### ISSUE THREAD

**Issue by kobold77** [raspiblitz/raspiblitz#3996]
Hi together. 
I installed LNDg to rebalance my channels automatically. But I have the problem that every time I get the message "400 Bad request" and "The plain HTTP request was sent to HTTPS port". 

I have already released the port via the firewall in the raspiblitz, but the page is still not accessible.

**Comment by rootzoll** [comment]
Just retested on dev branch again - lndg installs fine & can be called. I would suggest wait until RaspiBlitz 1.10.0 release. If you still have problems with LNDg still then reopen this issue.
