### ISSUE TITLE
Run RaspiBlitz behind TOR

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#4]
Running the RaspiBlitz behind Tor as a hidden service would be great ... not just because beeing more anon. Its perfect to make the node publicly available even when behind a NAT - without having to set port forwarding, etc.

See discussions for inspiration here: https://twitter.com/Stadicus3000/status/1017704449303867393

First step would be to write a shell script that installs and setups a TOR hidden service and takes care about the settings. If we then have also a script that would reverse this process, we could add a option into the main menu to switch TOR on and off.

**Comment by rootzoll** [comment]
Also check: https://github.com/Sjors/armbian-bitcoin-core/commit/ef915416546d1dd0a41f8fc479a2a67f9ae8a8f8

**Comment by rootzoll** [comment]
See my latest comments on TOR PR: https://github.com/rootzoll/raspiblitz/pull/39

In short: It seems we need to compile latest LND from source to get LND running together with TOR on a raspberry/ARM. If anybody can provide a LND build script that rauns on rasbian that would be cool. Then I could continue to work on the TOR integration.

**Comment by rootzoll** [comment]
Getting the seed nodes fresh instead of having them static in `96addTorService.sh` would an improvement.

**Comment by vnnkl** [comment]
im not familiar with dig yet, will look into it and leave this here for memo:
https://bitnodes.earn.com/api/#dns-seeder

**Comment by rootzoll** [comment]
TOR support for Shango Wallet is coming:
https://github.com/neogeno/shango-lightning-wallet/issues/37
This would mean that if we can get LND running behind TOR .. it could connect without any dyndns or port-forwarding-configuration-on-router. This sounds like the easiest first way we should approach.
