### ISSUE TITLE
Update BtcPay to 1.12.5

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#4000]

**Comment by rootzoll** [comment]
doing in branch changes110 - to be tested after fastpack. if not working revert to v1.9 versions (btcpay & nbx, webflow signer).

**Comment by openoms** [comment]
Manual update on v1.9 looking good.

**Comment by rootzoll** [comment]
https://www.nobsbitcoin.com/btcpay-server-v1-12-4/

**Comment by rootzoll** [comment]
Its now version 1.12.5

**Comment by rootzoll** [comment]
Installs on testing. Closing for ReleaseCandidate.
