### ISSUE TITLE
Preserve clrest macaroon and cert after reinstall (store on disk)

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#4007]
The clrest cert directories need symlinks to the disk.
will likely need to add a raspiblitz.conf option for `${netprefix}clrest` also

**Comment by rootzoll** [comment]
Do you want todo this still for v1.11.0 or push this for later?

**Comment by openoms** [comment]
Need to update to RTL v0.15 https://github.com/Ride-The-Lightning/RTL/releases which uses the clnrest plugin, but c-lightning-REST is needed for Zeus still.

**Comment by rootzoll** [comment]
@openoms were you able to test this. Can we close this issue?

**Comment by openoms** [comment]
worked even when using the migration file. Closing.
