### ISSUE TITLE
Defining fixed IP (or Domain) to be used by LND

### ISSUE THREAD

**Issue by cryptomulde** [raspiblitz/raspiblitz#401]
Hello,

I am running my Raspiblitz from home and I tunnel ports 1833, 8333 and 9735 to a Google Cloud instance. I don't have static IP from my ISP and I don't want my public-home-ip to be announced.

Is there a way to configure Raspiblitz to use my Gcloud static IP?

I tried several ways but none of them lead to success. (maybe I just did it wrong)

1. setting DYNDNS to my static IP (1ml.com still shows my home address and not my DNS nor GCloud IP)
2. changing raspiblitz.info in /mnt/hdd/raspiblitz.info If i changed that manually raspiblitz info screen showed me my static Gcloud IP, but after rebooting changes were lost again.

Is there a way to either add my DNS link or my GCloud static IP to be shown on 1ml.com?

I think the easiest way would be just to set my GoogleCloud IP in the right config file and I would be good.

I don't know how to do it, that I can restart plus it gets announced the 1ml.com the right way.

Appreciate your help!

**Comment by CommanderPoe** [comment]
Isnt easier to run your node on tor?

**Comment by cryptomulde** [comment]
I always taught I will only be able to connect to TOR nodes if I use tor.

I wrote a tutorial on that approach and I wanted to use my method.
https://medium.com/@cryptomulde/free-static-ip-for-btc-lightning-node-b1eef6b592cd

**Comment by CommanderPoe** [comment]
> I always taught I will only be able to connect to TOR nodes if I use tor.

As far as im concerned you are not publicly reachable, however if a node running on tor added the other party as peer first, they will be able to open channels.

**Comment by cryptomulde** [comment]
I want to be publicly reachable, but not with my home-ip, hence I tweaked with google cloud static ip.

**Comment by rootzoll** [comment]
@cryptomulde you are the first requesting this - setting a static IP is not a standard feature on the RaspiBlitz. So my take aways ...

TODO: for v1.1 make it easy to set a static ip - witch config script `lnd.staticip.sh`. Maybe add an option in raspiblitz.conf like `staticIP=1` and then dont reset publicIP anymore.

To make it possible in v1.0 some manual steps are needed. You can try to set static in in the lnd.service from systemd. Do you know how to edit a systemd service?

You need to change this line:
`ExecStart=/usr/local/bin/lnd --externalip=${publicIP}`
replace `${publicIP}` with your IP string. 

Just one note on this `hack` - when changing some config/services on the raspiblitz it might overwrite the lnd.service again (dyndns, etc.). Just keep that in mind until this gets a feature in v1.1

**Comment by cryptomulde** [comment]
Thx for your help!
I edited the lnd.service but it does not seem to work.
Replacing "PublicIP" with my numerical IP gives me this:
2019-03-06 01:23:32.733 [ERR] SRVR: unable to create server: can't create router: unexpected EOF
Replacing "PublicIP" with my numerical DynDNS gives me this:
 unable to create server: can't create router: ReadVarBytes: sig is larger than the max allowed size [count 166, max 80]

I have auto unlock activated. LND shuts down after the error and is trapped in unlocking loop.

LND work when I reset to old state `ExecStart=/usr/local/bin/lnd --externalip=${PublicIP}`

**Comment by cryptomulde** [comment]
2019-03-06 01:36:00.922 [ERR] SRVR: unable to create server: can't create router: unexpected EOF

Also getting that error with "PublicIP" now will have to find out tomorrow. Need to sleep :P 

EDIT: 
seems to work now with static numerical IP set. will follow up later.
EDIT2:
Still working. I don't know where these "can't create router" issues came from.

**Comment by cryptomulde** [comment]
I played around a little more and I found out something new to me.
I can simply change raspiblitz.conf by typing `sudo nano /mnt/hdd/raspiblitz.conf`
I edit `PublicIP=` with either my numerical static IP or the DNS pointing to my IP.
Seems easier to me than editing lnd.service - also editing lnd.service was giving my issues and failed starting after I tried editing it.

**Comment by rootzoll** [comment]
Editing the raspiblitz.conf could be a way for the future. But at the moment the publicIP is checked at every startup and even in time intervalls in the background .. so the RaspiBlitz would overwrite that edit in his config again in v1.0 ... thats why editing the service is the safest way at the moment before this becomes a feature in v1.2

**Comment by rootzoll** [comment]
V1.2 will habe a config script to set a fixed domain or IP for the RaspiBlitz (to be used by LND).

```
/home/admin/config.scripts/internet.setaddress.sh on [IP or DOMAIN]
```

TODO: Final testing before release.

**Comment by rootzoll** [comment]
OK. Works on v1.2 :) Closing issue.
