### ISSUE TITLE
check if mempool STDOUT_LOG_MIN_PRIORITY is set

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#4011]
found a large syslog and daemon.log:
![image](https://github.com/raspiblitz/raspiblitz/assets/43343391/526e7c03-7b8a-4238-b04d-f0f774455580)

Looks like it is this setting not applied for mempool:
```
    "STDOUT_LOG_MIN_PRIORITY": "info"
 ```
https://github.com/raspiblitz/raspiblitz/pull/3426/files

shouldcheck and correct with a script option in systemd.

Thanks to @surfac3 for the help to debug this.

Turns out that also LNbits are BTCPay were disfunctional on the node filling up the logs. Can be solved by uninstalling unused services (and avoiding dirty updates).

**Comment by rootzoll** [comment]
Following PR should fix that logs can grow that big:
https://github.com/raspiblitz/raspiblitz/pull/4038

**Comment by rootzoll** [comment]
@openoms do you also want to fix that mempool logging level?

**Comment by openoms** [comment]
on a recovery it should be applied.
I think here a dirty update was the issue.
Can be closed.
