### ISSUE TITLE
Install the Raspiblitz Web UI afterwards

### ISSUE THREAD

**Issue by marius0106** [raspiblitz/raspiblitz#4034]
Hi everybody,

i have an raspiblitz installation without the webUI, can i somehow install it afterwards? 
Here is the webUI that i mean.

greetings,
marius

**Comment by redmac68** [comment]
-> ssh onto your raspiblitz
-> Go to "SETTINGS" option in the menu
-> Use the spacebar to select the first option "Blitz API + WebUI"
-> Select OK
... follow the instructions...
Good luck.

**Comment by lorenzoPrimi** [comment]
I don't find this option on my 'RaspiBlitz v1.11.0rc2' so I need to do something different?
