### ISSUE TITLE
1.10 rc2: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

### ISSUE THREAD

**Issue by cstenglein** [raspiblitz/raspiblitz#4062]
When using the 1.10.0, I regularly get multiple messages of these kind:

```
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
```

**Comment by cstenglein** [comment]
Solution for Ubuntu:
Fixed it by going to my `/etc/default/locale` file and adding either `LC_ALL="en_US.UTF-8"` or `LANGUAGE=<your language locale>`

**Comment by rootzoll** [comment]
So this was a local Laptop issue or is there something still to change on the raspiblitz?

**Comment by cstenglein** [comment]
I fixed it on my pc by setting a fallback locale, but I think there could be a solution for the blitz itself, since the issue first appeared on 1.10

**Comment by rootzoll** [comment]
Ok thats `locale -a` output on a v1.10.0rc2
```
C
C.UTF-8
en_GB.utf8
POSIX
```

and thats on my v1.9.0
```
C
C.UTF-8
en_GB.utf8
en_US
en_US.iso88591
en_US.utf8
POSIX
```

So yeas there is something missing.

**Comment by rootzoll** [comment]
`/etc/locale.gen` has not uncommented
```
# en_US ISO-8859-1
# en_US.ISO-8859-15 ISO-8859-15
# en_US.UTF-8 UTF-8
```

which should normally happen here in the build script:
https://github.com/raspiblitz/raspiblitz/blob/3997b3badf782099a1bdbbdcb62537b85bc5893f/build_sdcard.sh#L295

So not sure why the "FIXING THE LOCALES" section was not effective.
