### ISSUE TITLE
 Migration to VM: lcd vs. headless

### ISSUE THREAD

**Issue by Firewalker99** [raspiblitz/raspiblitz#4073]
Hi, 
if you want to migrate from a Raspberry Pi to VM (proxmox) and raspiblitz.conf the hdd is "lcd" the system reboots continiously till you change the raspiblitz.conf to "headlesss"
Maybe a info dialog helps to prevent this error in the future.

LOG:==> /home/admin/raspiblitz.systeminit.log <==

check that display class in raspiblitz.conf from HDD is different from as it is now in raspiblitz.info ...
infoFileDisplayClass(headless)
confFileDisplayClass(lcd)
DISPLAY RESTORE - need to update displayClass from (headless) to (lcd)'
# blitz.display.sh set-display lcd
baseimage(debian)
# old(headless)
# new(lcd)                    
err='baseimage not supported'            
No UASP FIX needed

**Comment by rootzoll** [comment]
Thanks for the report .. we will optimize migration to VM in a later release - any earlier community patches welcome.
