### ISSUE TITLE
Got error when running lnd on mainnet

### ISSUE THREAD

**Issue by kccheung** [raspiblitz/raspiblitz#41]
I cannot start the lnd service properly and got the following error:

`unable to load RPC credentials for bitcoind: please set all or none of bitcoind.rpcuser, bitcoind.rpcpass, and bitcoind.zmqpath`

And I found that `bitcoind.zmqpath` is not set in my lnd.conf:

It works after adding `bitcoind.zmqpath=tcp://127.0.0.1:29000` to lnd.conf.

**Comment by rootzoll** [comment]
Thanks - I updated the lnd.conf and will test run it.
