### ISSUE TITLE
v1.10.0rc3 Stops at "Your RaspiBlitz is ready for Setup"

### ISSUE THREAD

**Issue by marssystems** [raspiblitz/raspiblitz#4111]
A fresh install of v1.10.0rc3, using a new 1Tb Toshiba SSD stops -  showing the message -  "Your RaspiBlitz is ready for Setup"

When I SSH in - I get the same message.
Using ctrl-c  to get to the command prompt, just closes the SSH session.
When I SSH back in, I just get the message again.

**Comment by marssystems** [comment]
Ok - sussed it !!
You can only continue Setup via the web browser.
This is not immediately obvious from the LCD screen or from SSH.

![Screenshot 2023-08-17 085403](https://github.com/raspiblitz/raspiblitz/assets/6579336/a5a99bc6-6b5a-4c37-907e-4cdd97fed16e)

Maybe the message should be something like -  Login via a web browser to continue Setup.

**Comment by rootzoll** [comment]
Might it be that you sshed in with "pi" and not with "admin" user?

**Comment by marssystems** [comment]
No - I always login using the admin user.

**Comment by marssystems** [comment]
ust flashed a new sd card and now I get the correct menu screen. I didn't change my Terminus SSH login settings as they were already correctly set.
So I can't explain it - just glad it fixed itself.
