### ISSUE TITLE
[v1.10rc] zram is not activated

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#4116]
Found and had reports that zram is not activated on the v1.10RC nodes: https://t.me/raspiblitz/134952
The install script runs ok, so will need to check if there is an error during the provision.

Related increase the size of the fallback swap file: https://github.com/raspiblitz/raspiblitz/pull/4114

**Comment by cAP5L0CK** [comment]
Confirmed that zram was not activated on my 1.10RC3 node, and activated it via the script.  And confirmed it then survived a reboot.

**Comment by openoms** [comment]
on my node there is no zram mentioned in the log files after recovery:
```
ls -la *.log
-rw-r----- 1 root sudo    5434 Jul 25 11:07 raspiblitz.log
-rw-r----- 1 root sudo  128615 Jul 14 15:11 raspiblitz.provision-update.log
-rw-r----- 1 root sudo 1531446 Jul 14 20:59 raspiblitz.setup.log
-rw-r----- 1 root root    5652 Jul 14 13:16 raspiblitz.systeminit.log

sudo grep -E zram *.log
```

adding logging

**Comment by rootzoll** [comment]
the zram install script needed to run the version check (git reset) also with `sudo -u admin`. Added also zram status to debug info. #4132 merged. Tested OK on my recover machine. Will be part of v1.10.0rc4 for final testing.

**Comment by rootzoll** [comment]
zram is now again activated by default
