### ISSUE TITLE
Lost-HDD ?

### ISSUE THREAD

**Issue by tweetytoo** [raspiblitz/raspiblitz#4118]
(1) I am not very techsavvy. 

(2) Some time ago, I noticed my raspiblitz was not active on the internet. IIRC, it said "logs full"

I tried to reboot, but then got a "lost-HDD" message, which is what I now see on boot.

I've tried to reflash and replace the SSD, but that's not the issue (I think).

(3) So, do I have any software fixes for this, or is the HDD somehow bricked?

(4) Recent logs, when I tried to reformat the HDD:

```
> Linux raspberrypi 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Sat Sep  3 13:33:57 2022 from 192.168.68.112
Starting SSH user interface ... (please wait)
# start ssh menu loop
# starting ssh menu loop ... 

># controlSetupDialog.sh
mkdir: cannot create directory '/var/cache/raspiblitz/temp': File exists
# Starting basic setup dialog ...

>Running Format: (ext4) ()
># DATA DRIVE - FORMATTING to EXT4 layout (old)
># missing valid third parameter as the device (like 'sda')
># run 'status' to see candidate devices
>FAIL ON FORMATTING THE DRIVE:
>missing parameter
>Please report as issue on the raspiblitz github.
># menu loop received exit code 1 --> exit to terminal

 
***********************************
* RaspiBlitz Commandline
* Here be dragons .. have fun :)
***********************************
Your setup is not finished.
For setup logs: cat raspiblitz.log
or call the command 'debug' to see bigger report.
Blitz command line options: blitzhelp
Back to menus use command: raspiblitz

admin@192.168.68.120:~ ₿ Connection to 192.168.68.120 closed by remote host.
```

Now it says

```
>RaspiBlitz 1.8.0 / noHDD / 192.168.68.120
 
                                                       │ Waiting for HDD/SSD ...         │  
                                                       │ Please connect a >=1TB          │  
                                                       │ HDD or SSD to the device.
```

**Comment by tweetytoo** [comment]
So do I need to get a new SSD? Or is there a way to check/fix it when it's "not detected"?

**Comment by rootzoll** [comment]
Try again with a fresh flashed sd card - if also second try fails your HDD/SSD seems not working in your setup.

**Comment by tweetytoo** [comment]
Thanks for the reply @rootzoll , but I've indeed swapped for newly flashed cards 3x. No luck :(

**Comment by Scotty-99** [comment]
Hi, I've the same issue. I wanted to install version 1.9 and since then I had this problem

**Comment by merle94** [comment]
Same problem here. For me it appeared during updating from 1.9 to 1.10
HDD just worked fine. SD flashed and got this lost HDD error.

Edit: tried it with a new sd card and freshly flashed. Same error. 
HDD worked just fine with 1.9. No hardware was exchanged. Same hardware Setup for 1.8 1.9 

Edit edit: tried to go back to 1.9, no success, same error, so I guessed the HDD was corrupt. Wiped the HDD and setup 1.10. Seems to work.

**Comment by rootzoll** [comment]
OK so the problem is that `hddCandidate` is empty .. can be seen here that the second brackets are empty
`>Running Format: (ext4) ()`

Improved the HDD/SSD detection .. try if the following RaspberryPi v1.11.0RC1 image (Download under Artifacts) fixes this:
https://github.com/raspiblitz/raspiblitz/actions/runs/7201966440

**Comment by tweetytoo** [comment]
Thanks for the suggestion but I gave up long ago and threw the whole rig away.

**Comment by jhub-beep** [comment]
I do have the same issue with lost hdd message and `>Running Format: (ext4) ()` while the SSD is connected to an USB 3.0 port of my Raspi 4. I am struggling to find the download of the suggested RaspberryPi v1.11.0RC1 under artifacts. I would willingly try the image. Please advice where to find @rootzoll. Thank you

**Comment by jhub-beep** [comment]
After login at github the download link appeared... 👍 let you know the result after flashing the 1.11.0RC1

**Comment by jhub-beep** [comment]
Still does not work for me with my Crucial BX500 2.5 SSD 1 TB while it is connected at an USB 3.0 port. When I use other Unix based OS it does work with this disc on those ports. I go ahead with the minimal image on an USB 2.0 port and might try later with next release.

**Comment by merle94** [comment]
Giving again some feedback on this issue :
1. Node lost power 
2. After reboot got into "emergency mode"
3. Get into "emergency mode" after every reboot from now on 
4. Re-flashed SD card
5. Now getting the "lost HDD"-issue
