### ISSUE TITLE
1.10rc4 installation: still tries to copy 'assets/bitcoind.service

### ISSUE THREAD

**Issue by cstenglein** [raspiblitz/raspiblitz#4140]
When installing the 1.10rc4 and following the logs, the following error pops up:

```
Copy HDD content for user admin
cp: cannot stat '/home/admin/assets/bitcoind.service': No such file or directory
*** Make backup of LND TLS files
```

**Comment by cstenglein** [comment]
Most likely that's the line where it's happening:

https://github.com/raspiblitz/raspiblitz/blob/v1.9/home.admin/_provision_.sh#L94

**Comment by rootzoll** [comment]
Thx. I removed the line.
