### ISSUE TITLE
rootz, did you drop the ltc/lnd node?

### ISSUE THREAD

**Issue by DrBlackross** [raspiblitz/raspiblitz#4143]
i still have the back up tarball for my old ltc node, was just wondering...

**Comment by DrBlackross** [comment]
since i've installed raspiblitz 1.9 on the rackmount amd64 setup (works great with the previous node data)... i was thinking of shifting the old ltc-lnd node over to the rpi4 setup from the tarball or build another rackmount system for that.

**Comment by DrBlackross** [comment]
n/m noticed in 1.7.1
"Remove: Litecoin (fork recommended) https://github.com/rootzoll/raspiblitz/issues/2542"

**Comment by rootzoll** [comment]
Yes its removed - there was the idea in the litecoin community to friendly fork raspiblitz to maintain a ltc-raspiblitz but I never saw any action on that.
