### ISSUE TITLE
Only Recommend 8GB Raspiblitz on README

### ISSUE THREAD

**Issue by geco91** [raspiblitz/raspiblitz#4147]
also let FULMO shop know to basically just default to 8GB

**Comment by xXCHNGx** [comment]
Does this only apply to RPi 5 or also for RPi 4 (when using an RPi 4 with 4GB (Electrs instead of Fulcrum))?

**Comment by rootzoll** [comment]
RaspberryPis 4 & 5 with less 8GB RAM will still work - its just that it makes sense to recommend 8GB to have the best experience.

**Comment by xXCHNGx** [comment]
Thank you very much for the explaination!

**Comment by rootzoll** [comment]
OK now part of the new documentation at https://docs.raspiblitz.org/docs/setup/get-hardware
