### ISSUE TITLE
shopping lists should include heatsink set

### ISSUE THREAD

**Issue by fluidvoice** [raspiblitz/raspiblitz#415]
My Pi 3B+ did not come with heatsinks and I think that most are that way.
The Pi's throttle around temp 80C and this gets hit running Raspiblitz so it's best to use heatsinks.
A common one in USA is [this one for $5 on Amazon](https://www.amazon.com/LoveRPi-Performance-Heatsink-Raspberry-Heatsinks/dp/B018BGRDVS/).  But it's a bit tall so might now work for some cases. 
This 3-piece set looks good and biggest heatsink is perhaps lower (8mm):
[https://www.amazon.co.uk/GorillaPi-Raspberry-aluminium-Significant-Advantage/dp/B01FY9196K](https://www.amazon.co.uk/GorillaPi-Raspberry-aluminium-Significant-Advantage/dp/B01FY9196K)
yet another option: https://www.amazon.com/dp/B00TNKBZH0/

**Comment by rootzoll** [comment]
added this issue to the "Check all Shopping Lists" task for v1.1 https://github.com/rootzoll/raspiblitz/issues/365 - closing this issue

**Comment by fluidvoice** [comment]
https://twitter.com/fluidvoice/status/1104899653005381633
