### ISSUE TITLE
Cannot reconnect to channel peers

### ISSUE THREAD

**Issue by orangedmind** [raspiblitz/raspiblitz#4151]
Hello all,
since my Raspiblitz (Core Lightning) was crashed, I rebuilt and tried to restore it using clrescue file.
Unfortunately it seems that the sqllite file was corrupted. So I rebuilt the node using raspiblitz v1.9.0 with seed and recovered the channels with emergency.recover.
Worked fine so far, I have access to my channels again.
Problem:
My channels are all shown as disconnected in the RTL or Console. I can execute the Close, but the Node says, that this is not possible until I am connected to the peer again.
My Bitcoin Node is fully synced. My CL Node can connect to new peers without any problems, but the peers of the existing channels can apparently no longer be connected.
Noticeably, a Network Address is displayed for new peers, while it seems to be missing for the peers of the channels.
Does anyone have an idea how I can reconnect to the peers?
![image](https://github.com/raspiblitz/raspiblitz/assets/107464027/76bb6637-4c2b-463d-958c-c1948255a663)

**Comment by rootzoll** [comment]
Such a personal problem with channels is best discussed in the Telegram Community Channel: https://t.me/raspiblitz

If there is anything that need fixing on the RaspiBlitz software itself - please reopen the issue.
