### ISSUE TITLE
Question about LND transactions

### ISSUE THREAD

**Issue by zuardi** [raspiblitz/raspiblitz#416]
Guys, 
I've finally set my node up and I've been trying to open some channels. But every time I fund my wallet with on-chain BTC, a significant part of it is sent elsewhere and is never added to Total Balance. Autopilot is OFF. Am I being robbed?
<img width="1152" alt="Captura de Tela 2019-03-09 às 22 55 50" src="https://user-images.githubusercontent.com/26280396/54079620-9276f600-42be-11e9-8020-49af89bfe5b7.png">

**Comment by rootzoll** [comment]
@zuardi its a quirk with LND not counting the "change outputs" of a BTC transaction (to fund a channel) until they are confirmend. So far it just needs time to have the balance available again.

**Comment by zuardi** [comment]
thanks for your response! I had figured it out and closed it.
