### ISSUE TITLE
LND DB version mismatch

### ISSUE THREAD

**Issue by kellnoid89** [raspiblitz/raspiblitz#4175]
My node wasn't syncing lightning for a while and I tried to upgrade lnd and raspiblitz to resolve the issue. This ended up with me having a database version mismatch for lnd.

I'm not sure how to proceed. I have lnd updated to the most recent version already.

Log: https://l.termbin.com/icgl

**Comment by openoms** [comment]
Please check again. It is either running ok now as LND is on the latest stable release or you have updated to LND master / a v0.17.0 rc previously.

In the latter case you need to run the major version (v0.17) again as downgrade is not possible.

**Comment by kellnoid89** [comment]
Thank you. I upgraded to one of the 0.17 rcs.

Working again!
