### ISSUE TITLE
SD card Ran completely out of space.

### ISSUE THREAD

**Issue by CommanderPoe** [raspiblitz/raspiblitz#418]
I just realised today that my node has **ZERO** free **GB** on sd card. 
<img width="571" alt="Screenshot 2019-03-10 at 20 05 39" src="https://user-images.githubusercontent.com/33594578/54090039-16d58180-4370-11e9-948f-66950bc68d08.png">

Today ZAP was failing on me and i decided to restart it (reload the qr code connecting via the node), when i did this message appeared: _"Cannot write to 'go1.11.linux-armv6l.tar.gz' (No space left on device)."_ see img below.
<img width="568" alt="Screenshot 2019-03-10 at 20 07 53" src="https://user-images.githubusercontent.com/33594578/54090099-e6421780-4370-11e9-9b65-b56224f1d495.png">

I checked the issues #15  and #16  but they all have to do with Exapnding the files which they are all supposed to be embeded within the latest configuration of the Raspiblitz... I have no idea what's going on from here...

I also noticed couple of days ago that my node runs out of FREE MEMORY as well from times to times when i back up the lnd files, i tried 2 different methods, one using `scp -r ... ` from my desktop pc and using cyberduck to copy the whole directory, both times after the copy it did ran out of FREE MEMORY and yes both times i stopped lnd. I dont even know if this helps for the space issue tbh. Any help could be more than welcome.

**Comment by fluidvoice** [comment]
http://ask.xmodulo.com/find-biggest-files-directories-linux.html
https://www.makeuseof.com/tag/increase-storage-raspberry-pi/
let us know if you have some log files or something filling it up and maybe there is some change we can make to Raspiblitz config files.

**Comment by CommanderPoe** [comment]
Nothing seems particularly weird... 
<img width="569" alt="Screenshot 2019-03-10 at 20 39 52" src="https://user-images.githubusercontent.com/33594578/54090513-3d49eb80-4375-11e9-9ffe-ec3c3f7f2dd6.png">

i tried to expand the files system but im getting this in return: _There was an error running option A1 Expand Filesystem_

**Comment by CommanderPoe** [comment]
I ran the same commands with the bitcoin user and after lot of permission denied i got this.
<img width="566" alt="Screenshot 2019-03-10 at 20 53 25" src="https://user-images.githubusercontent.com/33594578/54090647-98c8a900-4376-11e9-9113-979c8dad214a.png">

The root user doesnt show anything weird as well. it the bitcoin user. notice 
222G	./mnt/hdd/bitcoin/blocks
19G	./mnt/hdd/bitcoin/indexes/txindex
**12G	./var/log**
2.9G	./mnt/hdd/bitcoin/chainstate
1.1G	./mnt/hdd
359M	./usr/lib/arm-linux-gnueabihf
111M	./usr/bin
101M	./var
99M	./usr/local/go/pkg/tool/linux_arm
99M	./usr/local/bin
93M	./mnt/hdd/lnd/data/graph/mainnet
84M	./mnt/hdd/bitcoin/blocks/index
74M	./mnt/hdd/lnd/data/chain/bitcoin/mainnet
61M	./var/lib/apt/lists
57M	./usr/lib/gcc/arm-linux-gnueabihf/6

**Comment by fluidvoice** [comment]
there are 3 users for Raspiblitz (**admin**, **bitcoin**, and **pi**) You'll have to run the commands for all three and that's why you get denied messages.  so you have to...
sudu -u pi ...
sudo -u admin ...
sudo -u bitcoin ...
probably for expanding the SD card partition you'll have to use pi user.
how big is your card?
`sudo -u pi lsblk`
and what does this show...
`sudo ls -alS /var/log`

**Comment by fluidvoice** [comment]
better is `sudo du -h /var/log`

**Comment by CommanderPoe** [comment]
admin -
<img width="682" alt="Admin" src="https://user-images.githubusercontent.com/33594578/54091015-155d8680-437b-11e9-8247-02599f45449f.png">

bitcoin -
<img width="679" alt="Bitcoin" src="https://user-images.githubusercontent.com/33594578/54091020-26a69300-437b-11e9-9f39-1dec6610bb3d.png">

Pi -
<img width="682" alt="Pi" src="https://user-images.githubusercontent.com/33594578/54091027-31612800-437b-11e9-8526-658ba1de8775.png">

`sudo ls -alS /var/log`
<img width="674" alt="Screenshot 2019-03-10 at 21 25 31" src="https://user-images.githubusercontent.com/33594578/54091031-41790780-437b-11e9-9ca5-74d0daec6b54.png">
`sudo du -h /var/log`
<img width="483" alt="Screenshot 2019-03-10 at 21 27 30" src="https://user-images.githubusercontent.com/33594578/54091037-60779980-437b-11e9-968b-d98d431ff855.png">

@fluidvoice ... Defo var/log is punishing me... why?

**Comment by CommanderPoe** [comment]
i have to mention something... When i recovered all my channels, i deleted the old LOG that was on that lnd directory in hopes a new one be created for a friend to analyse it.. could that be the reason? 
that was half and a week ago when i restored my old lnd directory.

**Comment by fluidvoice** [comment]
well it looks like you have over 10GB of log files in /var/log. From your `df` output looks like your SD card is 16GB? so that's prob the root of the problem. These files need to be cleaned out. The **daemon.log** file alone is 7.4GB. We need to see how to limit this growth.

**Comment by CommanderPoe** [comment]
> well it looks like you have over 10GB of log files in /var/log. From your `df` output looks like your SD card is 16GB? 

Yes it is.

>so that's prob the root of the problem. These files need to be cleaned out. The **daemon.log** file alone is 7.4GB. We need to see how to limit this growth.

Howcome no body else has experienced issues like this? Maybe bigger space in SD card and maybe they are all bound to face issues like these sooner or later? How can i clean out that space?  Does my argument about deleting the logs from the lnd folder when i copied got anything to do with it? Why are those logs so big?

**Comment by fluidvoice** [comment]
> > well it looks like you have over 10GB of log files in /var/log. From your `df` output looks like your SD card is 16GB?
> 
> Yes it is.
> 
> > so that's prob the root of the problem. These files need to be cleaned out. The **daemon.log** file alone is 7.4GB. We need to see how to limit this growth.
> 
> Howcome no body else has experienced issues like this? Maybe bigger space in SD card and maybe they are all bound to face issues like these sooner or later? How can i clean out that space? Does my argument about deleting the logs from the lnd folder when i copied got anything to do with it? Why are those logs so big?

I don't know yet. I'm learning as I go. Not an expert on Linux logging.

**Comment by fluidvoice** [comment]
I would delete the **/var/log/daemon.log*** and **/var/log/syslog*** files then reboot.
You might have to use `sudo -u root` to delete them.
@rootzoll we might have to do cleanup/delete these when booting up if disk space is low or this folder has grown too large.

**Comment by fluidvoice** [comment]
apparently this is supposed to be controlled by "logrotate" on Debian/Raspbian such that they get cleaned up every 7 days. Perhaps this needs a different configuration. Logrotate can be used to clean out the files also.  Needs research.

**Comment by rootzoll** [comment]
This is already on the v.1.1 todo list with issue: https://github.com/rootzoll/raspiblitz/issues/394

**Comment by fluidvoice** [comment]
@CommanderPoe **correction!:** read up on `logrotate` before deleting those files. Dunno if they get recreated properly if not "rotated" or managed by `logrotate`.
see...
https://raspberrypi.stackexchange.com/questions/22545/why-are-system-logs-not-rotating
https://www.raspberrypi.org/forums/viewtopic.php?t=134971

**Comment by fluidvoice** [comment]
> This is already on the v.1.1 todo list with issue: #394

Is there a list somewhere showing v1.1 todo list?  so I can check next time :)

**Comment by fluidvoice** [comment]
see also: https://www.linode.com/docs/uptime/logs/use-logrotate-to-manage-log-files/

Config info: Looks like two config files are used, one includes the other...
**/etc/rsyslog.conf** which includes the second **/etc/logrotate.d/rsyslog**

admin@THUNDA:~ $ `cat /etc/rsyslog.conf `
#. /etc/rsyslog.conf	Configuration file for rsyslog.
#.
#.			For more information see
#.			/usr/share/doc/rsyslog-doc/html/rsyslog_conf.html **(DOESN'T EXIST!)**


#################
#### MODULES ####
#################

module(load="imuxsock") # provides support for local system logging
module(load="imklog")   # provides kernel logging support
#module(load="immark")  # provides --MARK-- message capability

#. provides UDP syslog reception
#module(load="imudp")
#input(type="imudp" port="514")

#. provides TCP syslog reception
#module(load="imtcp")
#input(type="imtcp" port="514")


###########################
#### GLOBAL DIRECTIVES ####
###########################

#
#. Use traditional timestamp format.
#. To enable high precision timestamps, comment out the following line.
#.
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

#
#. Set the default permissions for all log files.
#
$FileOwner root
$FileGroup adm
$FileCreateMode 0640
$DirCreateMode 0755
$Umask 0022

#
#. Where to place spool and state files
#
$WorkDirectory /var/spool/rsyslog

#
#. Include all config files in /etc/rsyslog.d/
#
$IncludeConfig /etc/rsyslog.d/*.conf


###############
#### RULES ####
###############

#
#. First some standard log files.  Log by facility.
#
auth,authpriv.*			/var/log/auth.log
*.*;auth,authpriv.none		-/var/log/syslog
#cron.*				/var/log/cron.log
daemon.*			-/var/log/daemon.log
kern.*				-/var/log/kern.log
lpr.*				-/var/log/lpr.log
mail.*				-/var/log/mail.log
user.*				-/var/log/user.log

#
#. Logging for the mail system.  Split it up so that
#. it is easy to write scripts to parse these files.
#
mail.info			-/var/log/mail.info
mail.warn			-/var/log/mail.warn
mail.err			/var/log/mail.err

#
#. Some "catch-all" log files.
#
*.=debug;\
	auth,authpriv.none;\
	news.none;mail.none	-/var/log/debug
*.=info;*.=notice;*.=warn;\
	auth,authpriv.none;\
	cron,daemon.none;\
	mail,news.none		-/var/log/messages

#
#. Emergencies are sent to everybody logged in.
#
*.emerg				:omusrmsg:*

**Comment by fluidvoice** [comment]
admin@THUNDA:~ $ `less /usr/share/doc/rsyslog/README.Debian `
admin@THUNDA:~ $ `cat /etc/logrotate.d/rsyslog`
/var/log/syslog
{
	rotate 7
	daily
	missingok
	notifempty
	delaycompress
	compress
	postrotate
		invoke-rc.d rsyslog rotate > /dev/null
	endscript
}

/var/log/mail.info
/var/log/mail.warn
/var/log/mail.err
/var/log/mail.log
/var/log/daemon.log
/var/log/kern.log
/var/log/auth.log
/var/log/user.log
/var/log/lpr.log
/var/log/cron.log
/var/log/debug
/var/log/messages
{
	rotate 4
	weekly
	missingok
	notifempty
	compress
	delaycompress
	sharedscripts
	postrotate
		invoke-rc.d rsyslog rotate > /dev/null
	endscript
}

**Comment by CommanderPoe** [comment]
Well... I deleted the first four on my list, daemon.log daemon.log.1 syslog syslog.1 (some of them were 1 week old) that were occupying a big chunk of the sd card, around 60%. 

When i rebooted it asked me to unlock lnd and it tootk sometime with some error that had never appeared but in the end when the blockchain synched lnd started working properlyu and this morning i have all channels back in place. Maybe i rushed to do that, but it seems to be working properly atm. I will check all that when i get home, thanks @fluidvoice

**Comment by fluidvoice** [comment]
> Well... I deleted the first four on my list, daemon.log daemon.log.1 syslog syslog.1 (some of them were 1 week old) that were occupying a big chunk of the sd card, around 60%.
> 
> When i rebooted it asked me to unlock lnd and it tootk sometime with some error that had never appeared but in the end when the blockchain synched lnd started working properlyu and this morning i have all channels back in place. Maybe i rushed to do that, but it seems to be working properly atm. I will check all that when i get home, thanks @fluidvoice

Coolio. Glad it's working for you.  @rootzoll will address this config issue in the next release v1.1
In the meantime you can probably avoid this problem reoccurring by applying this users' **logrotate** configuration: https://github.com/rootzoll/raspiblitz/issues/394#issuecomment-471535483

Can you please close this issue now.

**Comment by CommanderPoe** [comment]
The sd card is filling up even faster now... Yesterday only 25% of the sd was used today 60% this is madness.

**Comment by LightningK0ala** [comment]
I'm also having this issue, just noticed today my 30GB SD Card is full. My /var/log/daemon.log (I have 2) are almost 20GB.

**Comment by fluidvoice** [comment]
> I'm also having this issue, just noticed today my 30GB SD Card is full. My /var/log/daemon.log (I have 2) are almost 20GB.

connect via SSH, go to command line, then run:
`sudo systemctl stop bitcoind.service` 
`sudo systemctl stop lnd.service`
`sudo rm /var/log/daemon* && sudo rm /var/log/*.gz`
Edit your **/mnt/hdd/lnd/lnd.conf** file and set **debuglevel=info**
then restart.

**Comment by CommanderPoe** [comment]
> > I'm also having this issue, just noticed today my 30GB SD Card is full. My /var/log/daemon.log (I have 2) are almost 20GB.
> 
> connect via SSH, go to command line, then run:
> `sudo systemctl stop bitcoind.service`
> `sudo systemctl stop lnd.service`
> `sudo rm /var/log/daemon* && sudo rm /var/log/*.gz`
> Edit your **/mnt/hdd/lnd/lnd.conf** file and set **debuglevel=info**
> then restart.

@LightningK0ala did u try this? did it work for you?

**Comment by fluidvoice** [comment]
> @LightningK0ala did u try this? did it work for you?
works for this guy: https://github.com/rootzoll/raspiblitz/issues/423#issuecomment-472406125

**Comment by LightningK0ala** [comment]
I went the route of tweaking logrotate settings to limit the size of the logs. But I've never used it before and not sure the change I made yesterday worked as I expected.

`debuglevel=info` should do the trick, making that change now.

**Comment by fluidvoice** [comment]
> I went the route of tweaking logrotate settings to limit the size of the logs. But I've never used it before and not sure the change I made yesterday worked as I expected.
> 
> `debuglevel=info` should do the trick, making that change now.

what did you set your logrotate settings for the **daemon** and **syslog**?

**Comment by LightningK0ala** [comment]
Added this to `/etc/logrotate.d/rsyslog`:
```
/var/log/daemon.log
{
    size 250M
    rotate 2
    create
}
```

Yesterday I cleaned my daemon.log files from /var/log and this morning there are already 2 daemon.log (758M) and daemon.log.1 (1.4G). So don't think I did it right.

**Comment by rootzoll** [comment]
I have done the following measures to fix this issue for the v1.1 release ... is that enough?

1. LND logging level is set to `info`

2. Added config to `/etc/init.d/rsyslog`:
```
/var/log/daemon.log
{
        rotate 4
        size=100M
        missingok
        notifempty
        compress
        delaycompress
        sharedscripts
        postrotate
                invoke-rc.d rsyslog rotate > /dev/null
        endscript
}

3. If on boot log dir is detected to be >1GB it all gets emergency deleted:
`sudo rm -r /var/log/*`
```

So v1.1 will reduce the log load, will keep daemon.log small and has a safe guard on boot to flush the logs if they get out of control again. Please let me know if you see more things to do on this.

This is now in testing and will be released as a new image end of week for everybody to easy update.

**Comment by fluidvoice** [comment]
as I mentioned elsewhere, for v1.1 it might be better just turning off logging completely and create scripts for enable and disable it.  That because 99% of the time nobody is going to use these logs - prob just dev's when debugging a problem.  And doing ZERO logging will make the SD cards last longer and could even make the system run a little faster.

**Comment by rootzoll** [comment]
Zero logging is maybe a bit too hard - but I switched the services lnd, bitcoind & RTL to just send error messages to the journal logs. 

```
StandardOutput=null
StandardError=journal
```

**Comment by rootzoll** [comment]
OK - logs look good after testrun. auth.log seems to grow per day around 10MB but I put it on rotation with 100MB max too. So I close this issue for v1.1 release.

**Comment by RemoRitzmann** [comment]
I had the same problem (filling up SD-Card /dev/root to 100%) 
My Problem was reindex-chainstate with the wrong user beeing logged in, so it coppied parts of the BLOCKCHAIN /root/.bitcoin/blocks/ until there was no mor space. Because I followed "Please restart with -reindex or -reindex-chainstate to recover." in a log file. 
My solution was to do it with "bitcoin" user like this:
sudo -u bitcoin bitcoind -reindex-chainstate

**Comment by rootzoll** [comment]
Wrong user being logged in ... was this something raspiblitz was doing by default or more an individual error on your side?

**Comment by RemoRitzmann** [comment]
my bad, but good to know now. Thanks!
