### ISSUE TITLE
Feature Request - Ordisrespector patch bonus script

### ISSUE THREAD

**Issue by fanaticalfishing** [raspiblitz/raspiblitz#4181]
Many raspiblitz users are not interested in storing ordinals on their nodes.
This webpage has an easy way to patch bitcoin core to exclude them.

https://v2.minibolt.info/bonus-guides/bitcoin/ordisrespector

it would be nice if Raspiblitz had a bonus script that would implement these changes.

**Comment by openoms** [comment]
Ordinals is just a numbering system. 
You can not avoid storing these transactions  in the blocks and the UTXO-s in the UTXO set as they are valid in the bitcoin consensus.
The patch is about excluding them from your mempool, but that has undesired side-effects to fee estimation which is very important for lightning nodes.

Will not provide support for this, but you are free to make a custom script for personal use.
