### ISSUE TITLE
Tracker: [Could not resolve hostname]

### ISSUE THREAD

**Issue by PBJellytime** [raspiblitz/raspiblitz#419]
So synching the pi overnight and today, logged in this evening to find the error message in the title and stopped at about 2%

**Comment by fluidvoice** [comment]
That is not nearly enough information for anyone to begin to guess what your problem is.
What happens when you reboot it?

**Comment by PBJellytime** [comment]
Nothing yet as I haven’t tried it, thought I'd post in case it's a known issue that I couldn't find when I searched. I'll reboot later and see what happens

**Comment by PBJellytime** [comment]
So it seems to be a DHCP issue in the end, i've rebooted and plugged directly into the router and its picked up where it left off
