### ISSUE TITLE
[v1.10] LNBits 502 Bad Gateway after trying to update extension

### ISSUE THREAD

**Issue by adevoss** [raspiblitz/raspiblitz#4190]
Updating an LNBits extension failed. Now even LNBits won't show.
What's a way to fix this? A reboot doesn't help.

**Comment by adevoss** [comment]
Removing some files of the offending LNBits extension via SSH and a reboot 'solved' the problem.
Then reinstalled the old version of the extension.

Will ask the people at LNBits for more info.

**Comment by rootzoll** [comment]
@dni can you take a look what needs to be improved here?

**Comment by adevoss** [comment]
@dni It's the Bolt card extension 0.0.3 does not crash LNBits, 0.0.4 does.

**Comment by dni** [comment]
yes we deployed a version for the upcoming `0.11.0` lnbits release the boltcards `0.0.4` wasnt supposed to be installable in `0.10.10`, that is fixed. extensions will be incompatible 

@adevoss can you verify this. it should look like that. now

![screenshot-1695651882](https://github.com/raspiblitz/raspiblitz/assets/1743657/d3592551-e186-4fee-a550-7e89cb281e25)

**Comment by adevoss** [comment]
@dni Your screenshot is from another extension.
This is what the boltcard extension looks now:

![Schermafdruk van 2023-09-25 18-48-34-boltcards](https://github.com/raspiblitz/raspiblitz/assets/26113384/14b792a4-5bfe-4f54-bcce-a6446bb714e5)

**Comment by dni** [comment]
so, i guess the issue is resolved? it was a issue on lnbits extensions repository!

**Comment by adevoss** [comment]
> so, i guess the issue is resolved?

Yes
