### ISSUE TITLE
Funding LNBits from the same Raspiblitz node (lnd)

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#4192]
### Discussed in https://github.com/raspiblitz/raspiblitz/discussions/4191

<div type='discussions-op-text'>

<sup>Originally posted by **adevoss** September 25, 2023</sup>
Trying out LNBits.

There are sats on my node.
Created a new LNBits user and a new LNBits wallet.

Now I want to fund the new LNBits wallet with the sats on my node.
How can this be done?
Don't know if this is a Raspiblitz question or a LNBits one. Starting here.

In the FAQ of LNBits (https://docs.lnbits.org/guide/faq.html) there is an answer to this question:
```
lnd.conf
allow-circular-route=1 
allow-self-payment=1
```
but after that change lnd won't restart. Does it has to be inserted in a specific place in lnd.conf? I just inserted these line at the beginning.

Setup:
Raspiblitz v1.10
LNBits version: 0.10.9
lnd: LND_GRPC 0.16.4-beta </div>

**Comment by adevoss** [comment]
It already is possible to fund LNBits wallets (https://github.com/lnbits/lnbits/issues/1967) by using the TOPUP button.
Asked in that issue what the above FAQ is about.

**Comment by adevoss** [comment]
Related: #2510
