### ISSUE TITLE
High CPU Load lnd/bitcoind on 1.9.0

### ISSUE THREAD

**Issue by chuegel** [raspiblitz/raspiblitz#4193]
I'm experiencing high cpu load on the latest RaspiBlitz. Node ist fully sync'ed

![image](https://github.com/raspiblitz/raspiblitz/assets/6955465/22579765-eb5a-4ada-8929-0c4fde2007a6)

![image](https://github.com/raspiblitz/raspiblitz/assets/6955465/9fd9f89f-2985-4b32-bfaf-8fbf08ed11cc)

![image](https://github.com/raspiblitz/raspiblitz/assets/6955465/4bd791c0-ae6a-477e-8f08-440385f1d241)

![image](https://github.com/raspiblitz/raspiblitz/assets/6955465/c5bd9547-d1bb-4cd6-a817-4c8a0756023f)

Is this normal?

**Comment by rootzoll** [comment]
Please try again with new released RaspiBlitz v1.10.0 and check if that CPU load still persists.
https://github.com/raspiblitz/raspiblitz#downloading-the-software

**Comment by chuegel** [comment]
Yes, that helped:

![image](https://github.com/raspiblitz/raspiblitz/assets/6955465/7ab81233-57e3-40b0-b10c-61c3811713f3)

Thanks!
