### ISSUE TITLE
1.10.0rc6 stuck on starting Raspiblitz

### ISSUE THREAD

**Issue by farahats9** [raspiblitz/raspiblitz#4194]
I updated to 1.10.0rc6 from 1.9.0 because my node stops working every day. But now when I SSH into the node the update does not finish and still stuck on "Starting Raspiblitz Please Wait ..." it has been 12 hours now. Also I checked the /mnt/hdd is not mounted in the system yet, even though it is connected.

Where can I find any logs for this to post it?

**Comment by adevoss** [comment]
In /home/admin there are three raspiblitz log files. And there is raspiblitz.info

**Comment by farahats9** [comment]
Sorry, I already reverted back to v1.9 but there was some error about `btrfs` no being installed and also `tor_web_addr` not found in Redis. I hope this helps.
