### ISSUE TITLE
[v1.10] Make LNBits configuration persistant

### ISSUE THREAD

**Issue by adevoss** [raspiblitz/raspiblitz#4204]
After starting to use LNBits I changed the configuration file `/home/lnbits/lnbits/.env` (allowed users added)
When upgrading / reinstalling Raspiblitz that file will be lost.

**Comment by rootzoll** [comment]
With a soon comning LNbits update more configuration options will change (super user, etc) - lets add also persisting LNbits manual configs to that momemt. Should best fit with v1.11.1

**Comment by rootzoll** [comment]
move it to app-data
and delete on deinstall when yes to remove data option

**Comment by rootzoll** [comment]
Commit to `4568-lnbits` and merge this as part of #4768

**Comment by rootzoll** [comment]
OK is now part of PR #4768

- [x] Test persistant .env thru recover
- [x] Inform Local Meetup that .env can get lost "one more time"
