### ISSUE TITLE
BUG  v1.10 uses Core Lightning v23.02.2 not v23.08.1 

### ISSUE THREAD

**Issue by harvhat** [raspiblitz/raspiblitz#4205]
As the titles says,  v1.10 uses Core Lightning v23.02.2 not v23.08.1 as the changelog indicates

```
cl --version v23.02.2
```

**Comment by harvhat** [comment]
More info. I updated via building  SD card the image on  new SD card.
It shows I can do a "reckless" upgrade to v23.08.1 in the upgrade menu. 
At first quick glance cl.install.sh looks correct.  So odd.

**Comment by harvhat** [comment]
/mnt/hdd/raspiblitz.conf file has

```
clInterimsUpdate='v23.02.2'
```

Perhaps this is the issue.

**Comment by harvhat** [comment]
For some reason the git repo (home/bitcoin//bitcoin/lightning) was at v23.02.2

```sudo -u bitcoin git log -n 10
commit bfc6fedfbfc7f8006fc6d3c40d558f7d6abfa2bd (HEAD -> master, tag: v23.02.2)
Author: Rusty Russell <rusty@rustcorp.com.au>
Date:   Tue Mar 14 08:06:58 2023 +1030

    CHANGELOG.md: v23.03.2
    
    Signed-off-by: Rusty Russell <rusty@rustcorp.com.au>
```

I have both a `raspiblitz.provision-update.log` and a `raspiblitz.setup.log` which is newer.

```
~₿ s -lh *.log
-rw-r----- 1 root sudo 3.2K Oct  1 17:54 raspiblitz.log
-rw-r----- 1 root sudo 128K Oct  1 13:04 raspiblitz.provision-update.log
-rw-r----- 1 root sudo 340K Oct  1 14:17 raspiblitz.setup.log
```
 And grepping through them I see:

```
~₿ grep HEAD.*CHANGELOG raspiblitz.provision-update.log raspiblitz.setup.log
raspiblitz.provision-update.log:HEAD is now at e66d642e3 CHANGELOG.md: update for v23.08.1 release
raspiblitz.provision-update.log:HEAD is now at e66d642e3 CHANGELOG.md: update for v23.08.1 release
raspiblitz.setup.log:HEAD is now at bfc6fedfb CHANGELOG.md: v23.03.2
raspiblitz.setup.log:HEAD is now at bfc6fedfb CHANGELOG.md: v23.03.2
```

Hmm something seems not right. 

The **Documention** tag should problem be removed from this issue.

**Comment by harvhat** [comment]
I'm going to try and reproduce this, will take a day or so as I have to close channels and sleep and stuff. But if anyone has any ideas leave a comment.

**Comment by rootzoll** [comment]
@openoms can it be a problem with fresh install when in `raspiblitz.conf` there is an old/outdated `clInterimsUpdate` set - like here https://github.com/raspiblitz/raspiblitz/issues/4205#issuecomment-1742451696

**Comment by harvhat** [comment]
I had installed a fresh v1.09 a few days before using the blockchain data from my LND install (/bitcoin/blocks and /bitcoin/chainstate) onto a new 8 gig rpi4. Then v1.10 came out and I upgraded. 

I build the image myself via: 
```
wget https://raw.githubusercontent.com/rootzoll/raspiblitz/v1.10/build_sdcard.sh
sudo bash build_sdcard.sh -f 0 -d headless
sudo shutdown -r now
```
Then I only installed RTL and Mempool Space from the menu.

Also, probably unrelated, there are some diretories and files in /mnt/hdd that aren't own by any user

/mnt/hdd/app-data/passwords
/mnt/hdd/app-data/passwords/salt.txt
/mnt/hdd/app-data/passwords/b.hash

/mnt/hdd/app-data/selfsignedcert
/mnt/hdd/app-data/selfsignedcert/selfsigned.cert
/mnt/hdd/app-data/selfsignedcert/selfsigned.key
/mnt/hdd/app-data/selfsignedcert/localhost.conf

and all the cache files in
/mnt/hdd/app-storage/mempool/cache/

**Comment by harvhat** [comment]
I've tried one rebuild and it is still using v23.02.2.  

in `bootstrap.sh`
line 721 logs it (eventually to become raspiblitz.setup.log)
line 722 sets it (`source ${configFile}`)  

I haven't been able to get through all the logic prior to that yet since I don't know the code flow well enough.

Is it not distinguishing between recovering and updating?
Why is that line `clInterimsUpdate='v23.02.2'` even in my raspiblitz.conf file?

I thinking of moving all funds off the node and building a completely new one.

**Comment by harvhat** [comment]
Running `config.scripts/cl.update.sh info` on fresh install I get

```
₿ /home/admin/config.scripts/cl.update.sh info
# basic data
clInstalledVersion='v23.08.1'
clInstalledVersionMajor='v23'
clInstalledVersionMain='08'
clInstalledVersionMinor='1'
# the verified/recommended update option
clUpdateInstalled='0'
clUpdateVersion='v23.02.2'
clUpdateComment='Please keep in mind that downgrading afterwards is not tested. Also not all additional apps are fully tested with the this update - but it looked good on first tests.'
# reckless update option (latest Core Lightning release from GitHub)
clLatestVersion='v23.08.1'
```
Which obviously **isn't correct**. It also shows up in the dialog as:

![Update-CL-options-231007-15](https://github.com/raspiblitz/raspiblitz/assets/100391772/a95a82b6-2903-4e09-9c75-faec391fe18b)

**Comment by harvhat** [comment]
I'm going to close this (my original issue) as not reproducible and  open another one regarding the bad line in config.scripts/cl.update.sh.
