### ISSUE TITLE
Error when trying to create ZAP QR-code

### ISSUE THREAD

**Issue by cryptomulde** [raspiblitz/raspiblitz#421]
When I try to create the QR-code for Zap wallet it gives me the following error when it's trying to run "make". Any idea how to fix this? I tried installing manually, without success.
![image](https://user-images.githubusercontent.com/48246159/54162153-cdab2d80-4454-11e9-86ad-ccf604aa9203.png)

**Comment by cryptomulde** [comment]
Will try again with a clean image of the sd card.

**Comment by rootzoll** [comment]
Working on a quick rediced v1.1 release that wil also have an updated RTL by end of week ... maybe its worth waiting for that.

TODO: Recheck ZAP connect before release

**Comment by rootzoll** [comment]
OK tested fine on my machines. Closing issue for v1.1 release.
