### ISSUE TITLE
cl.update.sh uses `clUpdateVersion="v23.02.2"` instead of  `clUpdateVersion=""`

### ISSUE THREAD

**Issue by harvhat** [raspiblitz/raspiblitz#4210]
**Bug description**

The variable `clUpdateVersion` is incorrectly set to the previous version of core-lightning.
[ed. in  home.admin/config.scripts/cl.update.sh]

**To Reproduce**

1. Build a fresh cl node based on Raspiblitz v1.10.0
2. Look at line 23 and see 
    `clUpdateVersion="v23.02.2" # example: v23.02.2 # keep empty if no newer version as sd card build is available`
4. Also look at the raspiblitz menu -> Update -> CL and see it showing up incorrectly

![Update-CL-options-231007-15](https://github.com/raspiblitz/raspiblitz/assets/100391772/3e8cce6a-922c-464d-a4d0-64dfc58753ae)

**Comment by harvhat** [comment]
Although from the comment on line 23 it would appear that simply setting `clUpdateVersion=""` would solve this issue, it does not.  There appears to be a missing test somewhere for the condition where the latest version is already the installed and recommended one.

**Comment by harvhat** [comment]
This issue also affects v1.9 so that if one ran VERIFIED update while still in v1.9 and then upgraded to v1.10 (like I did) the install script would install CL v23.08.1 briefly, but then because `clInterimsUpdate='v23.02.2'` will be in raspiblitz.conf (from the VERIFIED update that did nothing) it will rollback to v23.02.2.  This will likely screw the install up in a subtle and possibly bad way.

This seems serious for anyone using Core Lightning.

**Comment by openoms** [comment]
Will likely need to remove the old version here and test the recovery:
https://github.com/raspiblitz/raspiblitz/blob/60b5c47240459bceca20ea34f8d921d5ba9d0677/home.admin/config.scripts/cl.update.sh#L23

**Comment by harvhat** [comment]
If I simply remove and leave empty, as it should be, then the current version of CL shows up as "reckless" in the menu (nothing shows up as verified). If you select reckless it's a noop (or should be) except that it has the side effect of leaving 
` clInterimsUpdate='v23.08.1'` in raspiblitz.conf which (it appears) will cause a future raspiblitz upgrade to not upgrade CL properly, assuming it's using a newer version of CL.

Since this error existed at  least since v1.9 this happened to me when I upgraded from 1.9 to 1.10 see #4205
I'm trying to figure out **why** it does that now. The upgrade process should definitely not upgrade and immediately rollback, at least one CL API function wasn't working after that, this issue perhaps being the cause (see https://github.com/ElementsProject/lightning/issues/6738#issuecomment-1746173053).

**Comment by harvhat** [comment]
Perhaps I don't understand the intent of the interim update feature. I would have expected an interim update to only be good only until the next raspiblitz release, maybe still good after that but only if the interim update version is still higher then the raspiblitz released version, but this is not how it is coded in `_provision_.sh`.  Same goes for 'reckless', I would not expect reckless to carry forward yet it does. Is this how it's meant to be?

Also I am working with the dev branch is this correct thing to do?

Thanks

**Comment by openoms** [comment]
>Perhaps I don't understand the intent of the interim update feature. I would have expected an interim update to only be good only until the next raspiblitz release, maybe still good after that but only if the interim update version is still higher then the raspiblitz released version, but this is not how it is coded in _provision_.sh. Same goes for 'reckless', I would not expect reckless to carry forward yet it does. Is this how it's meant to be?

you are right, these should be fixed
Got a similar report here: https://t.me/raspiblitz/137650
https://l.termbin.com/sw45

**Comment by rootzoll** [comment]
OK checked for v1.11.0 release that has a CLN update. It only provides the RECKLESS update option. Closing.
