### ISSUE TITLE
Raspiblitz doesnt start after updating to version 1.10.0

### ISSUE THREAD

**Issue by Sigevi** [raspiblitz/raspiblitz#4211]
Raspiblitz stucks after flashing it serveral times with the new update. 
It always works if i flash the version 1.9.0 again. But not once with v1.10.0.
Now it works just to the point when the Display says: "Starting Raspiblitz, Please wait...

That stays for days...

But in the Version 1.9.0. there was an other problem. Lightning shuts down everytime after a few days when it was running. 
A reboot helps just for a few hours or maybe days.
![unnamed](https://github.com/raspiblitz/raspiblitz/assets/147330980/7cffccb9-c8bd-4ee7-996f-79ef6f09ea8e)

**Comment by gecko20** [comment]
Same here after an update from version 1.8.0

**Comment by salenjak** [comment]
> But in the Version 1.9.0. there was an other problem. Lightning shuts down everytime after a few days when it was running. A reboot helps just for a few hours or maybe days. !

I believe this is related to SD card being full. https://github.com/raspiblitz/raspiblitz/issues/4149

When you reboot, the logs are cleared and everything works for a few days.

**Comment by Sigevi** [comment]
But how can i fix that bug? I've already formated the SD-Card and flashed it new. The Card has a capacity of 32gb. That should be easy enough. And it worked just until the Update...

**Comment by rootzoll** [comment]
It looks like the raspberrypi does not get an local network connection thru the LAN cable. Do you see any status lights next to the LAN cable plug?

**Comment by Sigevi** [comment]
![Screen Bild](https://github.com/raspiblitz/raspiblitz/assets/147330980/62a3e088-f7bd-4d33-8f0a-e741a16a5d64)
![Lan Bild](https://github.com/raspiblitz/raspiblitz/assets/147330980/06b855a6-edbb-481a-8223-c9d5545c140a)

Yes the status lights are working. I now changed again to the v1.9.0 beacuse there was no chance to start it with the version v.1.10.0. With this version you can see on the picture, that it is shutting down the LND 0.17.0-beta. At least it worked for 1 Week now. 
Before first trying to download the electrum rust server it worked for months.

**Comment by Sigevi** [comment]
> It looks like the raspberrypi does not get an local network connection thru the LAN cable. Do you see any status lights next to the LAN cable plug?

Yeah you were right. For some reason the LAN cable did not work properly. So i changed the cable and now i was able to pla the version 1.10.0. 
But now i am just happy that it works again and i wait to reinstall the Electrum server and BTCpay. Maybe in a few weeks again... Thanks for your support!
