### ISSUE TITLE
New base image for RPi - RaspiOS on Debian Bookworm

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#4215]
Announcement: https://www.raspberrypi.com/news/bookworm-the-new-version-of-raspberry-pi-os/

On top of the issues already covered for the amd64 build using Bookworm (Debian 12) there are a few things to check:

From: https://wiki.debian.org/NewInBookworm

- [x] change `/bin/sh` to `/bin/bash` - this is about using bash as sh - it is not happening here
- [x ] install rsyslog with system-log-daemon packages - `rsyslog` is installed in https://github.com/raspiblitz/raspiblitz/blob/fbd234f796efa2bf5822487305c933b85c69e403/build_sdcard.sh#L351
- [x] use `command -v` instead of `which` - not using `which` in scripts

From https://www.raspberrypi.com/news/bookworm-the-new-version-of-raspberry-pi-os/:
- [x] `dhcpd` is changed to `NetworkManager` #4407 
- [x] X11 is changed to Wayland display manager - check if the LCD or drivers are affected - the LCD scripts work with Debian12 on RPi4 and RPi5

**Comment by rootzoll** [comment]
@openoms what is the status of the checkboxes above?

**Comment by openoms** [comment]
@rootzoll updated the statuses above, there is only one left about `dhcpd` affecting the `internet.dns.sh` script.

On Debian12 there is neither:
```
/etc/dhcpcd.conf
/etc/dhcpd.conf
```

Also the command `host` was not installed for the `test`.
Needed:
```
sudo apt install bind9-host
```
Then the test is successful:
```
host w3c.org | grep -c "w3c.org has address"
1
```

but if this would fail setting the DNS in `/etc/dhcpcd.conf` wouldn't work.

**Comment by openoms** [comment]
Commands to set the DNS on Debian12:
```
sudo nmcli con mod "Wired connection 1" ipv4.dns "1.1.1.1"
sudo nmcli con mod "Wired connection 1" ipv4.ignore-auto-dns yes

# restart the connection
sudo nmcli con down "Wired connection 1"
sudo nmcli con up "Wired connection 1"

# check global
nmcli dev show  | grep DNS

# check
nmcli con show "Wired connection 1" | grep DNS
IP4.DNS[1]:                             1.1.1.1
IP4.DNS[2]:                             192.168.8.1
```

**Comment by rootzoll** [comment]
The different DNS handling is now worked in?

**Comment by openoms** [comment]
> The different DNS handling is now worked in?

Nope, not implemented yet, just tested manually.

**Comment by rootzoll** [comment]
Ready for ReleaseCandidate
