### ISSUE TITLE
plugin-clnrest.py: Killing plugin: disabled itself: No module named 'gunicorn'

### ISSUE THREAD

**Issue by orangedmind** [raspiblitz/raspiblitz#4216]
After updating raspiblitz to version 1.10.0 Core Lightning no longer starts.
When I check the cllog I only find the message:

2023-10-11T15:31:36.408Z INFO    plugin-clnrest.py: Killing plugin: disabled itself: No module named 'gunicorn'

I already tried installing the packagage via "pip install gunicorn" but after restart of the node the issue remains.
Any ideas?

**Comment by harvhat** [comment]
What version of core-lightning got installed?  If you previously updated to an interim update the update process will likely be borked. From the command line check `grep clInterimsUpdate /mnt/hdd/raspiblitz.conf` 
and the actual version with `lightning-cli -v` which I suppose wont work in your case.
You can also check the logs with:
`grep HEAD.*CHANGELOG raspiblitz.provision-update.log raspiblitz.setup.log`
and post the output.

If there is no output from `grep clInterimsUpdate /mnt/hdd/raspiblitz.conf`  then it's likely another issue and not what I'm thinking.

**Comment by harvhat** [comment]
Actually I'm also getting
`plugin-clnrest.py: Killing plugin: disabled itself: No module named 'gunicorn'`
in the logs even on a fresh install so it's not a upgrade issue.

**Comment by openoms** [comment]
the clnrest plugin is not used currently and it should not crash lightningd even if it is not running.

@orangedmind please double check if CLN recovered since.
You can check the installed version wih:
```
₿ lightningd --version
v23.08.1
```

**Comment by openoms** [comment]
The dependencies are not installed by pip, but using poetry in the directory:
`/home/bitcoin/lightning`
https://github.com/raspiblitz/raspiblitz/blob/60b5c47240459bceca20ea34f8d921d5ba9d0677/home.admin/config.scripts/cl.install.sh#L55

Can try updating the deps with:
```
cd /home/bitcoin/lightning
sudo -u bitcoin git reset --hard v23.08.1
sudo -u bitcoin poetry install
```

update:
even when doing this I am getting:
```
INFO    plugin-clnrest.py: Killing plugin: disabled itself: No module named 'gunicorn'
```
but it is not a breaking issue and the node comes up ok. 

Will need to fix this for the next release to have the `plugin-clnrest.py` working, but note that it might interfere with C-lightning-REST

**Comment by orangedmind** [comment]
I followed your instructions for updating the preps. 
After a restart of the raspiblitz sames behavior, CL does not start.

**Comment by openoms** [comment]
@orangedmind you need to share more info.
enter the CLN menu which will display the last lines of `cllog` and `sudo journalctl -fu lightningd`

**Comment by orangedmind** [comment]
Please find below the requested logs.
![image](https://github.com/raspiblitz/raspiblitz/assets/107464027/e9129543-9403-4eae-8a2b-dd3eedba2531)

![image](https://github.com/raspiblitz/raspiblitz/assets/107464027/16a258a7-2489-45b0-9ba8-b7589ea916ad)

**Comment by openoms** [comment]
You need to delete the erroneous line 20 from the CLN config as shown in the errorr message.

**Comment by orangedmind** [comment]
Thank you. CL is running again.
