### ISSUE TITLE
RTL stuck after typing password

### ISSUE THREAD

**Issue by cryptomulde** [raspiblitz/raspiblitz#422]
When I try to log into my Raspiblitz via RTL it loads up the page and I can insert my password.
After that RTL is stuck in that screen. Any ideas how to fix this?
![image](https://user-images.githubusercontent.com/48246159/54162277-372b3c00-4455-11e9-8456-3548d0afefb2.png)

**Comment by cryptomulde** [comment]
Will try again with a clean image of the sd card.

**Comment by rootzoll** [comment]
Working on a quick rediced v1.1 release that wil also have an updated RTL by end of week  ... maybe its worth waiting for that.

**Comment by cryptomulde** [comment]
I think it had to do with Cookies. Found out it is working on Chrome. Deleted Cookies on Firefox and it was fixed.

**Comment by rootzoll** [comment]
For version v1.1 the new RTL update is included - tested well on my machines. Closing Issue.
