### ISSUE TITLE
# FAIL: missing config file: /mnt/hdd/raspiblitz.conf

### ISSUE THREAD

**Issue by semaf** [raspiblitz/raspiblitz#4276]
### Discussed in https://github.com/raspiblitz/raspiblitz/discussions/4275

What is the proper way to run build_sdcard.sh script to install raspiblitz on an existing (new) Raspberry Pi?
I forked raspiblitz and made some changes in my fork repo.
I am running the script (with proper parameters, username, branch) on a freshly new RPi (debian 12, bookworm) after apt update and apt upgrade, but each time I receive an error: **`FAIL: missing config file: /mnt/hdd/raspiblitz.conf`**
Where is the config file generated? In which script is the hdd mounted? I don't have any /mnt/hdd mount point.

One of the points where /mnt/hdd will not mount:

```
[Install]
WantedBy=multi-user.target

# the API is now running on port 11111 & doc available under:
# http:///api/docs
# check for systemd:  sudo systemctl status blitzapi
# check for logs:     sudo journalctl -f -u blitzapi
# blitz.conf.sh set blitzapi on
# FAIL: missing config file: /mnt/hdd/raspiblitz.conf
* Adding Raspiblitz WebUI ...
# GITHUB_USER(raspiblitz)
GITHUB_REPO(raspiblitz-web)
GITHUB_BRANCH(release/v1.10)
GITHUB_COMMITORTAG()
# INFO: No GITHUB_COMMITORTAG provided .. will use latest code on branch
# INSTALL WebUI
# clone github: raspiblitz/raspiblitz-web
# checkout branch: release/v1.10
branch 'release/v1.10' set up to track 'origin/release/v1.10'.
# using lastest code in branch
# Compile WebUI
v20.5.1
nodeJS 20 is already installed
```

Another point where it cant mount /mnt/hdd:

```adding modification to /boot/cmdline.txt
OK install of LCD done ... reboot needed
blitz.conf.sh set displayClass lcd
FAIL: missing config file: /mnt/hdd/raspiblitz.conf
getting default user/repo from build_sdcard.sh
branch(v1.10)
defaultAPIuser(fusion44)
defaultAPIrepo(blitz_api)
defaultWEBUIuser(raspiblitz)
defaultWEBUIrepo(raspiblitz-web)
```

At the end:
```
adding modification to /boot/cmdline.txt
OK install of LCD done ... reboot needed
blitz.conf.sh set displayClass lcd
FAIL: missing config file: /mnt/hdd/raspiblitz.conf
BUILD DONE - see above
```

**Comment by rootzoll** [comment]
the `FAIL: missing config file: /mnt/hdd/raspiblitz.conf` can be ignored during setup. Because its confusing I removed this error log for the future release.
