### ISSUE TITLE
BlitzAPI: add a availability check / ping endpoint

### ISSUE THREAD

**Issue by cstenglein** [raspiblitz/raspiblitz#4280]
See https://github.com/fusion44/blitz_api/issues/145

Can just respond with 200, so it's a ping

**Comment by rootzoll** [comment]
Is that still on my todo list?

**Comment by cstenglein** [comment]
@rootzoll yes

**Comment by rootzoll** [comment]
@fusion44 go ahead

**Comment by rootzoll** [comment]
@fusion44 what is the status here?

**Comment by fusion44** [comment]
I've implemented the basics today. Should be ready by Friday at latest.
