### ISSUE TITLE
can't install chantools

### ISSUE THREAD

**Issue by ghost** [raspiblitz/raspiblitz#4294]
Everytime i try to install chantools i get this errormessage.
Updatet LND to latest Version.
Have tried to install chantools over the Raspiblitz Menu and both methods mentioned in the readme from the chantools repo.

![image](https://github.com/raspiblitz/raspiblitz/assets/129442607/1552a147-4870-43f1-8c9a-80adf5393cf1)

LND not installed or a version not tested with chantools
lncli version 0.17.2-beta commit=v0.17.2-beta

**Comment by rootzoll** [comment]
OK PR #4296 will update to latest chantools which install & run in my test RPi machine.

**Comment by rootzoll** [comment]
So far so good. Closing for ReleaseCandidate.
