### ISSUE TITLE
status screen: tail: cannot open '/mnt/hdd/bitcoin/debug.log' for reading: No such file or directory

### ISSUE THREAD

**Issue by YuckFouBTC** [raspiblitz/raspiblitz#4300]
**Describe the bug**
Flashed a new node with RaspiBlitz v1.10.0 and am seeing "tail: cannot open '/mnt/hdd/bitcoin/debug.log" on INFO - RaspiBlitz Status Screen before even attempting to open any channels.
Screenshot: 
![Screenshot from 2023-12-06 02-25-52](https://github.com/raspiblitz/raspiblitz/assets/115867254/1b9b7414-7b6f-43a8-aaa6-dbade84c6934)
This appears to be the same issue that was reported in https://github.com/raspiblitz/raspiblitz/issues/4003.  Since that issue was Closed and the problem still exists, I am opening a new issue.

**To Reproduce**
DOWNLOAD FATPACK SD CARD IMAGE ⮕ [raspiblitz-fat-v1.10.0-2023-09-22.img.gz](https://raspiblitz.fulmo.org/images/raspiblitz-fat-v1.10.0-2023-09-22.img.gz)
SHA-256: 50b48e078d162dfafc2b80025cf493141b0d8ab5774519bff4c3239d5d246f8f
Flash new 32GB SDHC card with that image using [Balena Etcher](https://www.balena.io/etcher/).
Boot up RaspiBlitz using that flashed 32GB SDHC card.

**Debug file**
Please let me know which additional command(s) you would like me to include the output from here and I will share that info.
From status screen when ssh'ing in, I did a Ctrl-C, then this:
```
tail: cannot open '/mnt/hdd/bitcoin/debug.log' for reading: No such file or directory
tail: cannot open '/mnt/hdd/bitcoin/debug.log' for reading: No such file or directory

Screen is updating in a loop .... press 'x' now to get back to menu.^CSIGINT or SIGTERM received, exiting...
Killed
admin@192.168.1.247:~ ₿ cat /mnt/hdd/bitcoin/bitcoin.conf | grep main.debuglogfile
main.debuglogfile=/mnt/hdd/bitcoin/debug.log
admin@192.168.1.247:~ ₿ ls -l /mnt/hdd/bitcoin/debug.log
ls: cannot access '/mnt/hdd/bitcoin/debug.log': No such file or directory
admin@192.168.1.247:~ ₿ cd /mnt
admin@192.168.1.247:/mnt ₿ ls -la
total 16
drwxr-xr-x  4 root root 4096 Oct 26 21:37 .
drwxr-xr-x 18 root root 4096 Oct 26 21:44 ..
drwxr-xr-x  9 root root 4096 Nov 29 02:17 hdd
drwxr-xr-x  2 root root 4096 Oct 26 21:37 storage
admin@192.168.1.247:/mnt ₿ cd hdd
admin@192.168.1.247:/mnt/hdd ₿ ls -la
total 7893060
drwxr-xr-x  9 root       root             4096 Nov 29 02:17 .
drwxr-xr-x  4 root       root             4096 Oct 26 21:37 ..
drwxr-xr-x 11 bitcoin    bitcoin          4096 Nov 11 08:01 app-data
drwxr-xr-x  3 bitcoin    bitcoin          4096 Oct 26 21:44 app-storage
drwxrwxrwx  5 bitcoin    bitcoin          4096 Dec  6 02:37 bitcoin
drwxr-xr-x  5 bitcoin    bitcoin          4096 Nov 27 23:21 lnd
drwx------  2 root       root            16384 Oct 23 18:30 lost+found
-rw-rw-r--  1 root       sudo              694 Nov 29 02:17 raspiblitz.conf
-rw-------  1 root       root       8082423808 Oct 26 21:52 swapfile
drwxrwxrwx  2 bitcoin    bitcoin          4096 Oct 27 08:54 temp
-rw-r--r--  1 admin      admin           10603 Oct 26 21:47 .tmux.conf.local
drwx------ 11 debian-tor debian-tor       4096 Dec  5 00:00 tor
admin@192.168.1.247:/mnt/hdd ₿ cd bitcoin/
admin@192.168.1.247:/mnt/hdd/bitcoin ₿ ls -la
total 18144
drwxrwxrwx 5 bitcoin bitcoin     4096 Dec  6 02:37 .
drwxr-xr-x 9 root    root        4096 Nov 29 02:17 ..
-rw------- 1 bitcoin bitcoin       31 Oct 23 18:46 banlist.json
-rw-r--r-- 1 bitcoin bitcoin      944 Dec  1 02:04 bitcoin.conf
drwx------ 3 bitcoin bitcoin   241664 Dec  5 12:17 blocks
drwx------ 2 bitcoin bitcoin   159744 Dec  6 02:42 chainstate
-rw-r--r-- 1 bitcoin bitcoin       11 Oct 26 23:34 copy_begin.time
-rw-r--r-- 1 bitcoin bitcoin       11 Oct 27 06:24 copy_end.time
-rw------- 1 bitcoin bitcoin   247985 Nov 11 10:40 fee_estimates.dat
drwx------ 3 bitcoin bitcoin     4096 Oct 27 09:04 indexes
-rw------- 1 bitcoin bitcoin 16394894 Nov 11 10:40 mempool.dat
-rw------- 1 bitcoin bitcoin       99 Nov 11 10:43 onion_v3_private_key
-rw------- 1 bitcoin bitcoin  1489021 Dec  6 02:37 peers.dat
-rw------- 1 bitcoin bitcoin        4 Nov 11 10:41 settings.json
admin@192.168.1.247:/mnt/hdd/bitcoin ₿ sudo updatedb
admin@192.168.1.247:/mnt/hdd/bitcoin ₿ locate debug.log
admin@192.168.1.247:/mnt/hdd/bitcoin ₿ cd
admin@192.168.1.247:~ ₿ locate bitcoind.check.sh
admin@192.168.1.247:~ ₿ 
```

**Comment by YuckFouBTC** [comment]
I was able to fix this by doing this:

```
admin@192.168.1.247:~ ₿ bitcoin-cli stop
admin@192.168.1.247:~ ₿ su bitcoin
[use PASSWORD A here]
bitcoin@woody:/home/admin $ /usr/local/bin/bitcoind -daemonwait -conf=/mnt/hdd/bitcoin/bitcoin.conf -datadir=/mnt/hdd/bitcoin
Bitcoin Core starting
bitcoin@woody:/home/admin $ exit
exit
admin@192.168.1.247:~ ₿ sudo tail -n 1000 -f /mnt/hdd/bitcoin/debug.log
# ... I am now able to see the data again in /mnt/hdd/bitcoin/debug.log
```

**Comment by so7ow** [comment]
> I was able to fix this by doing this:
> 
> ```
> admin@192.168.1.247:~ ₿ bitcoin-cli stop
> admin@192.168.1.247:~ ₿ su bitcoin
> [use PASSWORD A here]
> bitcoin@woody:/home/admin $ /usr/local/bin/bitcoind -daemonwait -conf=/mnt/hdd/bitcoin/bitcoin.conf -datadir=/mnt/hdd/bitcoin
> Bitcoin Core starting
> bitcoin@woody:/home/admin $ exit
> exit
> admin@192.168.1.247:~ ₿ sudo tail -n 1000 -f /mnt/hdd/bitcoin/debug.log
> # ... I am now able to see the data again in /mnt/hdd/bitcoin/debug.log
> ```

Does this fix persist through a reboot? For me, simply restarting the bitcoin service fixes the issue until the next reboot. I guess that's pretty much what you're doing here too.

**Comment by YuckFouBTC** [comment]
> Does this fix persist through a reboot? For me, simply restarting the bitcoin service fixes the issue until the next reboot. I guess that's pretty much what you're doing here too.
Ah, good question.  I've not tried a reboot yet.  Will soon.  I'll try to circle back to let you know.

**Comment by YuckFouBTC** [comment]
> Does this fix persist through a reboot? For me, simply restarting the bitcoin service fixes the issue until the next reboot. I guess that's pretty much what you're doing here too.

Ah, good point. I've not tried a reboot yet. I suppose it will resurface. What command do you use to just restart the service?

**Comment by so7ow** [comment]
> > Does this fix persist through a reboot? For me, simply restarting the bitcoin service fixes the issue until the next reboot. I guess that's pretty much what you're doing here too.
> 
> 
> 
> Ah, good point. I've not tried a reboot yet. I suppose it will resurface. What command do you use to just restart the service?

`systemctl restart bitcoind`

**Comment by YuckFouBTC** [comment]
Rebooted the raspiblitz node.  The problem did not resurface.  I'll chalk this up as it's a random problem that doesn't happen every time the node is rebooted, but can resurface again whenever it's the most undesirable time.

In case it does happen again in the future, I have issued the command "systemctl restart bitcoind", chose admin identity at the prompt, and used PASSWORD A.  At least this way the restart command should be in my shell's history and I'll remember to use it in case the debug.log file goes missing again.

**Comment by rootzoll** [comment]
I added some lines to the `bitcoin.check.sh` that will ensure that a bitcoin debug log exists. This will be part of RaspiBlitz v1.11.0 from RC2 on. Please test (once its out and you have a node to test with) and report if problem still persists.

**Comment by YuckFouBTC** [comment]
I have permanently retired this node that I saw this bug with.

I want to help test here since I think RaspiBlitz is the best lightning node software of them all.

I am at a point where I could reflash and test, except I don't know where to find the newer version of raspiblitz to test with.  If you could point me in the right direction on where to look for it, I will give it a shot and let you know.  Otherwise I am just closing this out and trusting that you have handled it.

**Comment by YuckFouBTC** [comment]
I have permanently retired this node that I saw this bug with.

I want to help test here since I think RaspiBlitz is the best lightning node software of them all.

I am at a point where I could reflash and test, except I don't know where to find the newer version of raspiblitz to test with. If you could point me in the right direction on where to look for it, I will give it a shot and let you know. Otherwise I am just closing this out and trusting that you have handled it.

**Comment by YuckFouBTC** [comment]
I have permanently retired this node that I saw this bug with.

I want to help test here since I think RaspiBlitz is the best lightning node software of them all.

I am at a point where I could reflash and test, except I don't know where to find the newer version of raspiblitz to test with. If you could point me in the right direction on where to look for it, I will give it a shot and let you know. Otherwise I am just closing this out and trusting that you have handled it.
