### ISSUE TITLE
SSH Main Menu Fails to Launch After 4 Hours of RaspiBlitz Uptime

### ISSUE THREAD

**Issue by neversleep404** [raspiblitz/raspiblitz#4323]
**Describe the bug**
The SSH main menu fails to launch after the RaspiBlitz has been running for an extended period. It becomes inaccessible and only a restart resolves the issue.

PI 5 running on raspiblitz-arm64-rpi-image-2023-12-14-fac733a
The issue has been persisting for several weeks
This issue may potentially be related to Issue #4298

**To Reproduce**
After 4 Hours of Running RaspiBlitz, the SSH Main Menu Fails to Start During SSH Login.
At least for the first hour, SSH Main Menu works perfectly.

**Debug file**

![Bildschirmfoto 2023-12-16 um 01 53 54](https://github.com/raspiblitz/raspiblitz/assets/80689652/9e118b69-960a-4338-b636-1dd458e22ff3)

**Comment by rootzoll** [comment]
So the line "# starting ssh menu loop ..." is the last line you see and then it hangs forever, correct?

https://github.com/raspiblitz/raspiblitz/blob/622135c5704d3482a7113bf0744be30b01f53f6d/home.admin/00raspiblitz.sh#L79

**Comment by neversleep404** [comment]
> So the line "# starting ssh menu loop ..." is the last line you see and then it hangs forever, correct?

Correct.

**Comment by neversleep404** [comment]
After a New Installation and SEED+SCB Words Seed & channel.backup file recovery all working fine.
