### ISSUE TITLE
Disallow SSH from internet by default.

### ISSUE THREAD

**Issue by fluidvoice** [raspiblitz/raspiblitz#433]
Think about should we allow only to manage the node via HTTP from the internet and, by default, only allow SSH from the LAN. Then perhaps have a script or option to allow SSH from the internet? This is safer, more secure, no? 

> only allowing password authentication from within your network. Add the following to the end of your sshd_config:
> 
> PasswordAuthentication no
> Match Address 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
>     PasswordAuthentication yes
>

_Originally posted by @fluidvoice in https://github.com/rootzoll/raspiblitz/issues/431#issuecomment-473285667_

**Comment by rootzoll** [comment]
Good point. Added for future release.

**Comment by nyxnor** [comment]
pls close this. This is solved with ufw. Allowing through the internet with Tor on https://github.com/rootzoll/raspiblitz/blob/v1.6/home.admin/config.scripts/internet.hiddenservice.sh.
