### ISSUE TITLE
Shell Script for installing Neovim

### ISSUE THREAD

**Issue by bvolution** [raspiblitz/raspiblitz#4349]
Hi, I recently wanted to start coding a few small scripts on my raspiblitz and for this I intended to use neovim.
However via apt aswell as the appimage it was impossible to install recent version of neovim. The most recent version available was 0.4.4 via apt. That was not sufficient for my needs. Thats why I developed a tiny shell script that builds neovim in version 0.95.0 an cleans up everything afterwards. 

I thought I leave it here as it might be beneficial to others as well.
```sh
# Source https://github.com/neovim/neovim/blob/master/BUILD.md
echo "================================================"
echo "Building and installing version 0.95.0 of neovim"
echo "================================================"
cd /tmp/
pip install cmake
sudo apt-get install -y ninja-build gettext cmake unzip curl
git clone https://github.com/neovim/neovim
cd neovim/
git checkout stable
make CMAKE_BUILD_TYPE=RelWithDebInfo
# try dkpg else use normal make install
cd build && cpack -G DEB && sudo dpkg -i nvim-linux64.deb || cd /tmp/neovim && sudo make install
cd build/bin/
sudo mv nvim /usr/bin/
nvim --version
pip uninstall -y cmake
sudo apt-get remove -y ninja-build gettext cmake curl
cd ~
sudo rm -rf /tmp/neovim/
```

**Comment by geco91** [comment]
@bvolution latest `nvim` on RaspiBlitz is version 0.7.2 .. would that work for you?
