### ISSUE TITLE
Extrem slow blockchain copy via scp

### ISSUE THREAD

**Issue by LightRider5** [raspiblitz/raspiblitz#435]
I am copying the blockchain from my mac book but the speed is extremely slow.
![Bildschirmfoto 2019-03-16 um 16 30 58](https://user-images.githubusercontent.com/48626097/54477512-e32fa700-4808-11e9-86fe-499a93b48700.png)

Any ideas about that? Or is my question to general?

Thx

**Comment by rootzoll** [comment]
On my local network I get between 10-20 MB/s on transfere .. where the bottle neck is more likely the USB2.0 bus of the Raspberry. Why it is so slow on your setup its hard to say. Is your Laptop on WLAN? Is there any other process running on the Raspberry that blocks the USB2.0 bus bandwidth?  

BTW the next release v1.1 will replace SCP with rsync for MacOS and Linux: https://github.com/rootzoll/raspiblitz/issues/397

**Comment by fluidvoice** [comment]
> I am copying the blockchain from my mac book but the speed is extremely slow.
> 
> Any ideas about that? Or is my question to general?
> 
> Thx

What is your storage media?  Some low quality flash drives (USB/SD) have very slow write speeds esp when copying a large amount of data where they get hot and slow down even more.  WLAN and router are possible problem sources too.

**Comment by LightRider5** [comment]
Thanks for your answers. Yeah normaley i have a speed about 15 MB/s in the LAN. The Laptop is on WLAN. The storage medias are two WD elements. Maybe its because the blockchain is on an external HDD. Maybe i try to copy it via rsync.

**Comment by nyxnor** [comment]
please close this.
