### ISSUE TITLE
I can received sats on-chain but cannot do/send any transactions On-Chain

### ISSUE THREAD

**Issue by chamoBtC** [raspiblitz/raspiblitz#4354]
**Describe the bug**
Not sure if this is a bug but for some strange reason I cannot send any transactions through On-Chain  I  tried few times with no success. Always is  messsage of Error. Within the browser interface sometimes I cannot see my balance or transactions and yet I can see my balance in Ride the Lightning.

See attachment 

Please advise

Thank you 

<img width="1085" alt="Screenshot 2024-01-07 at 5 46 34 AM" src="https://github.com/raspiblitz/raspiblitz/assets/151878066/a5689f37-0d64-4782-a53a-57104244cd55">

<img width="559" alt="Screenshot 2024-01-07 at 5 52 07 AM" src="https://github.com/raspiblitz/raspiblitz/assets/151878066/123a3399-df4a-4fac-9ca5-9776ebcbd77d">

<img width="904" alt="Screenshot 2024-01-07 at 5 45 51 AM" src="https://github.com/raspiblitz/raspiblitz/assets/151878066/46bde51b-80bf-4832-aef4-ec4aec649f7c">

**Comment by chamoBtC** [comment]
See balance zero in the browser interface

<img width="1090" alt="Screenshot 2024-01-07 at 5 57 11 AM" src="https://github.com/raspiblitz/raspiblitz/assets/151878066/24154da0-ad8b-4e45-91c0-4dab9c829630">

**Comment by rootzoll** [comment]
Can you see that the transaction you send has been confirmed on the blockchain?
Have you alraedy tried to send a transaction from your node and that one might still wauting for confirmation?

**Comment by chamoBtC** [comment]
Will send you a screenshot later. Still can't send any sats through the node. I have almost like 1M sats and now it says that I only have 906 sats. Not sure if it is because I changed the name of my node. Very confused

**Comment by chamoBtC** [comment]
here is the message I  get enytime I want to send sats on chain

<img width="988" alt="Screenshot 2024-01-22 at 6 00 35 PM" src="https://github.com/raspiblitz/raspiblitz/assets/151878066/7d55395e-9c3e-49ed-9bc9-c760cf0dac44">

**Comment by rootzoll** [comment]
It looks like you've encountered an error while trying to broadcast a transaction on the blockchain. It simply means that the fee that has been set for the transaction is lesser than the minimum fee that has to be paid for a transaction to be accepted into the network, into the memory pool (mempool), from where the transaction will sit waiting to be confirmed.
