### ISSUE TITLE
random freezes crashes headless RPI4 4Gb over Tor

### ISSUE THREAD

**Issue by woeisme** [raspiblitz/raspiblitz#4357]
**Describe the bug**
My raspiblitz node (over Tor) will hang and become unresponsive for no discernible reason at random intervals

**To Reproduce**
Run stock Raspiblitz v1.10 without screen 

**Debug file**

https://l.termbin.com/4bc5

**Comment by openoms** [comment]
The termbin link is 404. Can you maybe add also what parts are you using? SSD + adapter model? Do you have a UPS? Anything stands out in the logs?

**Comment by Toromambo** [comment]
EVF EKEY

**Comment by cstenglein** [comment]
Is this still an issue?
Closing for now, if it still is an issue, please re-open.
