### ISSUE TITLE
[RPi5] Support Pimoroni NVMe Base

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#4359]
https://shop.pimoroni.com/products/nvme-base?variant=41219587178579
https://www.youtube.com/watch?v=odG7FbptgWQ
Should already work from the configs with the adaption of pineberrypi nvme board ('pciex1_gen=3' not needed) - BUT ...

it needs at least the raspberryPi has an updated firmeware `Wed  6 Dec 18:29:25 UTC 2023 (1701887365)` which did not come with the first batch of RPi5s

To see installed version:
`sudo rpi-eeprom-update`

To install new firmware (manual trigger of reboot needed after that):
`sudo rpi-eeprom-update -a`

**Comment by redmac68** [comment]
I can confirm it works with raspiblitz v1.11.0rc1 (basic setup - bitcoin, LND, RTL running)
Definitely needs the firmware update as above first or the nvme disk is not detected.
I am running with 'pciex1_gen=3' on a test rpi5 8GB with Samsung_SSD_970_EVO_Plus_2TB_S6P1NS0T208608F. 
Box is doing very little useful work - 1 channel.

Using Pimoroni NVMe Base with OS on SD.

sudo hdparm -t --direct /dev/nvme0n1p1

/dev/nvme0n1p1:
 Timing O_DIRECT disk reads: 2328 MB in  3.00 seconds = 775.86 MB/sec

**Comment by neversleep404** [comment]
How would the migration process work?
https://github.com/raspiblitz/raspiblitz/issues/4259#issuecomment-1880322366

**Comment by rootzoll** [comment]
Please add all the NVMes (manufacture & model & size) that you are running with the PIMORONI Base as a comment to this issue - for performance test you can use: `sudo hdparm -t --direct /dev/nvme0n1p1`

**Comment by TrezorHannes** [comment]
Using Pimoroni NVMe Base with OS on SD (allows for quicker update iterations).

## NVMe
```
Crucial P3 2TB PCIe M.2 2280 SSD
CT2000P3SSD8
Node                  Generic               SN                   Model                                    Namespace Usage                      Format           FW Rev  
--------------------- --------------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- --------
/dev/nvme0n1          /dev/ng0n1            2342E880D515         CT2000P3SSD8                             1           2.00  TB /   2.00  TB    512   B +  0 B   P9CR30A
```

```
sudo hdparm -t --direct /dev/nvme0n1p1

/dev/nvme0n1p1:
 Timing O_DIRECT disk reads: 1236 MB in  3.00 seconds = 411.38 MB/sec
 ```

**Comment by Emzy** [comment]
Using Pimoroni NVMe Base with OS on SD

NVMe
```
1TB Lexar NM620 M.2 PCIe 3.0 x4 NVMe 3D-NAND TL (LNM620X001T-RNNNG)
lspci
0000:01:00.0 Non-Volatile memory controller: Shenzhen Longsys Electronics Co., Ltd. Lexar NM620 NVME SSD (DRAM-less) (rev 01)
```

```
sudo hdparm -t --direct /dev/nvme0n1p1

/dev/nvme0n1p1:
 Timing O_DIRECT disk reads: 2420 MB in  3.00 seconds = 806.21 MB/sec
```

**Comment by david-bakin-sl** [comment]
I'm about to build a RPi5+Pimoroni NVMe Base+2TB NVMe ... and was wondering if I dare try to sync the whole chain (rather than start with a copy of the chain from my existing 'blitz).  Would the fast drive be expected to improve sync-from-genesis time?  (And if so, how much?)

(I tried this sync last year sometime with an external USB SSD and I forget exactly but I think it took 10 days more or less, working against another node on the local LAN.)

**Comment by redmac68** [comment]
In my case full sync was much faster ~ 4 days.

**Comment by neversleep404** [comment]
A copy of the blockchain from the USB SSD directly to the NVMe should be much faster. With a blockchain size of 550GB and a conservatively estimated USB transfer rate of 400 MB/s, the copying process only takes 24 minutes.
Copying from one Raspberry Pi to another takes several hours, and a full sync over the internet takes about 3-6 days (I have a gigabit internet connection) and depends on the other Bitcoin full nodes. Lightning and Electrum also take their time.

If the weather god cooperates, I will receive my HatDrive tomorrow! It's from Pineberry Pi and I can run a few tests. My Pimoroni NVMe Base will probably take another 1-2 weeks to arrive.

**Comment by rootzoll** [comment]
@neversleep404 
> A copy of the blockchain from the USB SSD directly to the NVMe should be much faster.

Yeah it seems to make sense to provide a migration tools now to copy from external HDD/SSD. I would target that for v1.11.1 to not further delay the v1.11.0 release. Will opened a new ticket for that: #4377

Can somebody in the meantime test if on the RaspberryPi5 with the Pimoroni NVMe Base an additional connected USB SSD (the one we used before) can still copy lots of dummy data correctly without drops in power?

**Comment by neversleep404** [comment]
Using Pimoroni NVMe Base with OS on SD while running Raspiblitz
WD_BLACK SN770 2 TB WDS200T3X0E

sudo hdparm -t --direct /dev/nvme0n1p1

/dev/nvme0n1p1:
 Timing O_DIRECT disk reads: 2248 MB in  3.00 seconds = 749.08 MB/sec

**Comment by rootzoll** [comment]
Were running the Pimoroni NVMe base now for multiple weeks with the release candidates. All looks good - closing issue for release.
