### ISSUE TITLE
Setting fee sats/vbyte for closing channel miscalculates actual fee rate

### ISSUE THREAD

**Issue by abinition** [raspiblitz/raspiblitz#4372]
Upon closing a channel, (I) selected 50 sats/vbyte, but when transaction was viewed on mempool, it showed 24.7 sats/vbyte.  Afterwards, tried doing a "force close" which added a CPFP, this increased fee rate to 47.5 sats/vbyte.  Hope it confirms.

Devs should check the math calculation for channel close and apply the correct fee amount from what is selected on web interface.

Hard to reproduce without opening and then closing channels, which costs $$.

**Comment by rootzoll** [comment]
What did you use? LND or CLN? Which WebUI or Terminal?

**Comment by abinition** [comment]
It was RTL web interface.

**Comment by abinition** [comment]
re-opened on https://github.com/Ride-The-Lightning/[RTL](https://github.com/Ride-The-Lightning/RTL) issue  #1345
