### ISSUE TITLE
Make it easy to connect a Mobile Wallet using RaspiBlitz as Backend

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#44]
For example:
https://github.com/Stadicus/guides/blob/master/raspibolt/raspibolt_68_shango.md

Find an easy way to help user setup the connection. May require a solid solution for easy external reachability of RaspiBlitz LND first ... TOR or IPv6-Tunnel with fixed address, requiring no local config of ports of Router and DynDns.

**Comment by vnnkl** [comment]
my pr above only does LAN,
before we have tor running we could use dyndns if ports get opened by user and extend getPublicIP script?
https://www.datenreise.de/en/bash-update-script-for-no-ip-com-dyndns/

**Comment by rootzoll** [comment]
@vnnkl  Local LAN is great for now to gain experience about the "pairing process". The publicIP/TOR/DynDNS is a topic thats high on my list. Hope to get to it soon.

**Comment by rootzoll** [comment]
Beside Shango ... there is also ZAP Wallet, that can connect to LND. 
https://ln-zap.github.io/zap-tutorials/iOS-remote-node-setup

@anybody ... feel free to play with it also for the RaspiBlitz and let us know your experience :)

**Comment by vnnkl** [comment]
zap requires https://github.com/LN-Zap/zapconnect to construct the qr code, did not have success to install on first try (go related), so did not try it out yesterday.
will look into it again later on

**Comment by rootzoll** [comment]
zap developer will be at the lightninghackday and assist on integration :)

**Comment by hopitas** [comment]
How about spark wallet? [https://github.com/shesek/spark-wallet#server-installation](url)
Servern needs running c-lightning though...

**Comment by rootzoll** [comment]
We did a ZAP wallet integration at lightning hackday :)
Also there is a Shango integration now.

@hopitas integration of c-lightning to also connect spark is an idea on our issue list :) 
https://github.com/rootzoll/raspiblitz/issues/46
if you like to helpout on that connect with @renepickhardt
