### ISSUE TITLE
LNbits 0.12.0

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#4402]
a maybe upgrade for next raspiblitz release 
https://www.nobsbitcoin.com/lnbits-v0-12-0/

LNbits now introduces a login system - so this needs to be intilized correctly. Is admin super user still needed? Can we set a admin user still our self on install with password B? The admin login needs to be displayed to user in SSH & WebUi menus.

**Comment by rd2madnss** [comment]
Current Version is now 0.12.2

**Comment by dennisreimann** [comment]
fyi: I upgraded my LNbits instance via `config.scripts/bonus.lnbits.sh install lnbits 0.12.3`. Afterwards the superuser can be set with `sudo vim /home/lnbits/lnbits/.env` and adding the line `SUPER_USER=seeTheAccountMenuToLookupYourUserId`.

One more `sudo systemctl restart lnbits` and it seems to work like a charm.

**Comment by therealsupermax** [comment]
This is great. I'll give this a test @dennisreimann

**Comment by therealsupermax** [comment]
> fyi: I upgraded my LNbits instance via `config.scripts/bonus.lnbits.sh install lnbits 0.12.3`. Afterwards the superuser can be set with `sudo vim /home/lnbits/lnbits/.env` and adding the line `SUPER_USER=seeTheAccountMenuToLookupYourUserId`.
> 
> One more `sudo systemctl restart lnbits` and it seems to work like a charm.

I just ran command `config.scripts/bonus.lnbits.sh install lnbits 0.12.3` and said it was already installed?
Also how do I edit the .env file when running `sudo vim /home/lnbits/lnbits/.env`?

Thanks. Getting more proficient in CLI.

**Comment by rootzoll** [comment]
PR merged #4596 - RaspiBlitz v1.11.1 will have lnbits v0.12.8
