### ISSUE TITLE
Github public signing key expired

### ISSUE THREAD

**Issue by semaf** [raspiblitz/raspiblitz#4406]
Hey,

The public signing key of Github has expired on 16.01.2024 and not renewed. During installation you get the warning.

```
pub   rsa2048/4AEE18F83AFDEB23 2017-08-16 [SC] [expired: 2024-01-16]
      5DE3E0509C47EA3CF04A42D34AEE18F83AFDEB23
uid                 [ expired] GitHub (web-flow commit signing) <noreply@github.com>

pub   rsa4096/B5690EEEBB952194 2024-01-16 [SC]
      968479A1AFF927E37D1A566BB5690EEEBB952194
uid                 [ unknown] GitHub <noreply@github.com>
```

https://github.com/web-flow.gpg -> 4AEE18F83AFDEB23 
https://keyserver.ubuntu.com/pks/lookup?search=968479A1AFF927E37D1A566BB5690EEEBB952194&fingerprint=on&op=index

Discussion: https://github.com/orgs/community/discussions/89880
Github announcement: https://github.blog/2024-01-16-rotating-credentials-for-github-com-and-new-ghes-patches/

**Comment by rootzoll** [comment]
We addressed the problem with the expired Webflow key already for the upcmming v1.11.0 release.

**Comment by semaf** [comment]
> We addressed the problem with the expired Webflow key already for the upcmming v1.11.0 release.

Can you point to the file where the fix is? Would like to give a test.

**Comment by rootzoll** [comment]
Basically update the following script: https://github.com/raspiblitz/raspiblitz/blob/dev/home.admin/config.scripts/blitz.git-verify.sh

**Comment by rootzoll** [comment]
Looks good now. Closing issue.
