### ISSUE TITLE
Failed to set LN password. Not beeing ask to enter PW again.

### ISSUE THREAD

**Issue by LeoPeo7** [raspiblitz/raspiblitz#441]
I am installing Raspblitz v1 on my Raspberry Pi.
When it asked for a LN Password, my two entered Passwords didn't match.
It didn't ask me to set the PW again and continued to scan the bitcoin blockchain to 100%.

Now I am maybe stuck at "Lightning Filtering Blockchain".
It shows me in Progress:  ?/567672  Please wait...

Do I need to start over again? Main Blockchain is synced.

**Comment by fluidvoice** [comment]
Login via SSH then hit ctrl-c to get to a command prompt, then run
`/home/admin/70initLND.sh` 
what happens?
if more problems what is your output of running
`/home/admin/XXdebugLogs.sh`

**Comment by LeoPeo7** [comment]
I corrupted my blockchain.
Fuck me. I am starting from 0.
I tried a few things but in the end my blockchain got corrupted. I am
redownloading.

Thanks anyway for your help

Brad <notifications@github.com> schrieb am Mo., 18. März 2019, 20:29:

**Comment by rootzoll** [comment]
@LeoPeo7 check v1.1 it should support you better with repairing a broken blockchain.
