### ISSUE TITLE
LNDg - Can not login with RPC (Password B)

### ISSUE THREAD

**Issue by bvolution** [raspiblitz/raspiblitz#4418]
**Describe the bug**
I cant log into lndg (webbrowser ip.to.my.raspi:8889) with my RPC Password B.
With the same password I am able to log into RTL for example (so the password is correct in general).
In the past LNDg login worked just fine. I did work with my node for a few weeks, I am not
sure what could have changed.

I tried to uninstall and reinstall lndg (keeping my data base though).
I also tried to copy the RPC Password directly from the bitocin.conf 
`sudo nano /mnt/hdd/bitcoin/bitcoin.conf`

However the error remains.

![grafik](https://github.com/raspiblitz/raspiblitz/assets/155586969/74a47af1-7b76-4a0e-8ab5-aa998b8cd8f1)

I would highly appreciated any tips or suggestions

Is there anyway to just reset the lndg password?

**Comment by bvolution** [comment]
**Update:** In the past I have manually changed my Password B (RPC). However this does not seem to include to also change the password for LNDg. I was able to fix it via

**Solution**
`sudo ./config.scripts/bonus.lndg.sh setpassword <mynewpassword>`

**Suggestion**
Which should maybe be added to the menu -> Password -> Change Password

**Comment by rootzoll** [comment]
OK - created a new branch 4418-lndg to prepare a fix. 
Password should now be changed this way - but still needs to be tested.

BUT I ran into install problems when testing for RaspiBlitz v1.11.0 release. @allyourbankarebelongtous please take a look here: https://github.com/raspiblitz/raspiblitz/blob/4418-lndg/home.admin/config.scripts/bonus.lndg.sh

First the LNDg version 1.7.0 failed with this when running after install on gunicorn logs:
![Bildschirmfoto 2024-02-15 um 12 02 19](https://github.com/raspiblitz/raspiblitz/assets/2472225/6ee4ff4d-5119-472a-9af5-f8db24948058)

Then I saw there is a new version of LNDg 1.8.0 lets use that one - but that hangs even during install when running the "jobs.py":
![Bildschirmfoto 2024-02-15 um 12 01 53](https://github.com/raspiblitz/raspiblitz/assets/2472225/6bf552fa-f875-4ad1-a279-fd8bd75da6b8)

If this gets not resolved may consider deactivating LNDg for next RaspiBlitz release coming soon. Would love not to. 

TODO: fix install of v1.8.0
TODO: test new password change

**Comment by rootzoll** [comment]
@allyourbankarebelongtous can you help fixing this (see above) for upcoming RaspiBlitz release?

**Comment by rootzoll** [comment]
@cryptosharks131 can you help fixing this (see above) for upcoming RaspiBlitz release?

**Comment by cryptosharks131** [comment]
Hi @rootzoll the `jobs.py` looks good above but in v1.8.0 it will no longer exit after each run with the addition of the `controller.py` file. You can now run the single `controller.py` file to start start all services (jobs, rebalancer, htlc-stream, trading) but running each file individually is still okay as well.

**Comment by rootzoll** [comment]
OK because there is no PR to fix this I will deactivate LNDg for the next release and push install script for repair to v1.11.1

see: https://github.com/raspiblitz/raspiblitz/blob/5199eb2219db38d6ada907712bf59e45d3080e36/home.admin/00settingsMenuServices.sh#L63

**Comment by allyourbankarebelongtous** [comment]
Sorry folks, missed all this until @cryptosharks131 brought it up to me. I'll get on it and see what I can do.

**Comment by rootzoll** [comment]
@allyourbankarebelongtous we still have a testing week before final release - if you can get a repair PR in by then happy to have it not deactivated for v1.11.0 release.

**Comment by dragsugg** [comment]
With running lndg the update to the newest raspiBlitz v1.11.0rc4 stucked. I've tried to unlock with lncli, but this didn't work either. The log shows this:

Sat Mar 16 21:11:36 2024 : [Data] : Data execution completed...sleeping for 20 seconds
Sat Mar 16 21:11:56 2024 : [Data] : Starting data execution...
Sat Mar 16 21:11:56 2024 : [Data] : Error processing background data: <_InactiveRpcError of RPC that terminated with:
 status = StatusCode.UNKNOWN
 details = "wallet locked, unlock it to enable full RPC access"
 debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-03-16T21:11:56.159093546+00:00", grpc_status:2, grpc_message:"wallet locked, unlock it to enable full RPC access"}"
>
Sat Mar 16 21:11:56 2024 : [Data] : Data execution completed...sleeping for 20 seconds
Sat Mar 16 21:12:16 2024 : [Data] : Starting data execution...

After unlocking the log shows following in a loop:

Sat Mar 16 15:08:13 2024 : [Data] : Starting data execution...Sat Mar 16 15:08:20 2024 : [Data] : Data execution completed...sleeping for 20 seconds
Sat Mar 16 15:08:40 2024 : [Data] : Starting data execution...Sat Mar 16 15:08:47 2024 : [Data] : Data execution completed...sleeping for 20 seconds
Sat Mar 16 15:09:07 2024 : [Data] : Starting data execution...Sat Mar 16 15:09:17 2024 : [Data] : Data execution completed...sleeping for 20 seconds
Sat Mar 16 15:09:37 2024 : [Data] : Starting data execution...Sat Mar 16 15:09:53 2024 : [Data] : Data execution completed...sleeping for 20 seconds
Sat Mar 16 15:10:13 2024 : [Data] : Starting data execution...Sat Mar 16 15:10:21 2024 : [Data] : Data execution completed...sleeping for 20 seconds
Sat Mar 16 15:10:41 2024 : [Data] : Starting data execution...Sat Mar 16 15:10:48 2024 : [Data] : Data execution completed...sleeping for 20 seconds
Sat Mar 16 15:11:08 2024 : [Data] : Starting data execution...Sat Mar 16 15:11:15 2024 : [Data] : Data execution completed...sleeping for 20 seconds

Don't mind the times, I didn't find the right logfile and took it from someone else who had the same error

**Comment by rootzoll** [comment]
The final relase was delayed and there might be still a week to submit a PR to fix the LNDg. @allyourbankarebelongtous is there a change to get this done in time?

**Comment by rootzoll** [comment]
@dragsugg ok I might have fixed it. Please go in raspiblitz v1.11RC4or5 to terminal and run the following 3 commands:
```
/home/admin/config.scripts/bonus.lndg.sh off
patch code
/home/admin/config.scripts/bonus.lndg.sh on
```

Let me know if that fixes the LNDg

**Comment by dragsugg** [comment]
Great, that works! I've deinstalled lndg on rc3, kept the data, updated to rc5 without problems, run the 3 commands and lndg works again. 👍

**Comment by rootzoll** [comment]
OK closing this issue for final release.

**Comment by bvolution** [comment]
Thanks to all contributors sorry I could not do more. Thanks for fixing the issue.
