### ISSUE TITLE
Cannot create directory: file exists on fresh setup

### ISSUE THREAD

**Issue by cstenglein** [raspiblitz/raspiblitz#4421]
When doing a fresh setup, on "Setup System" I was following the logs and saw that part:

```
Copy HDD content for user admin
mkdir: cannot create directory ‘/home/admin/.bitcoin’: File exists
mkdir: cannot create directory ‘/home/admin/.lnd’: File exists
cp: '/mnt/hdd/lnd/lnd.conf' and '/home/admin/.lnd/lnd.conf' are the same file
cp: '/mnt/hdd/lnd/tls.cert' and '/home/admin/.lnd/tls.cert' are the same file
mkdir: cannot create directory ‘/home/admin/.lnd/data’: File exists
*** Make backup of LND TLS files
```

- `mkdir` and `cp` should now display these warnings (hard drive was empty)
- There should be no backup necessary on a fresh setup

**Comment by rootzoll** [comment]
So this is happening here in the provision script: https://github.com/raspiblitz/raspiblitz/blob/3c207ac909fc0654a282fe5862bfeceed47358e6/home.admin/_provision_.sh#L79
