### ISSUE TITLE
**issue of zerotier network id entering**  (rpi 5 with RaspiBlitz v1.11.0rc2)

### ISSUE THREAD

**Issue by dondelion** [raspiblitz/raspiblitz#4425]
**issue of zerotier network id entering**
Hello I'm running rpi 5 with RaspiBlitz v1.11.0rc2
I have a problem entering Zerotier network ID in settings menu --> i could fill  my network ID in the box but it couldn't confirm my entry instead it created a new line  :(

I've been running 2 pi4 raspiblitz without this problem.
please help I think this could be just a UI bug <3

<img width="479" alt="image" src="https://github.com/raspiblitz/raspiblitz/assets/82316368/02e2f2ca-ea87-4ced-b2bf-fc210d9b61fb">
<img width="486" alt="image" src="https://github.com/raspiblitz/raspiblitz/assets/82316368/b142171f-e2f6-4a73-a6b8-bd7ec6fac2af">

**Comment by rootzoll** [comment]
I was not able to reproduce this. I was able to copy & paste the networkid into the field and press ENTER to start the install/connection. I treid on MacOS ... you are on Windows?

As fallback you can go to the terminal and call the script directly with the networkid as parameter:
SSHMENU > EXIT > `./config.scripts/bonus.zerotier.sh on [networkid]`

**Comment by dondelion** [comment]
Yes , i ssh via Putty on Windows. Not sure why this happened. btw thank you so much for a manual enter

**Comment by openoms** [comment]
Look up how to insert to the terminal in Putty. Right click I think.

**Comment by dondelion** [comment]
I can navigate and enter text via putty on any menu except this one. I'll try to flash my raspiblitz and see the result.

**Comment by kravens** [comment]
I have the same issue, using either powershell or windows terminal.
Also on an iPhone using the Termius app it does not work.
When pressing Enter or Return the menu goes to the next line instead of triggering the <Ok> signal.

**Comment by rootzoll** [comment]
For v1.11.1 try switching between whiptail & dialog

**Comment by rootzoll** [comment]
@dondelion & @kravens openoms did a PR to address this problem that can be tested with upcoming v1.11.0rc4 (hopefully availavle within the next 2 days) - please test and report if this fixes it for you.

**Comment by rootzoll** [comment]
RC4 is out for testing. Looks good on my machine. Closing issue for release. Please comment/reopen if this error shoes again after v1.11.0rc4.

**Comment by kravens** [comment]
On my Pi5 the menu is still an issue, it skips straight to this screen from the ''installing zerotier'' message when pressing Enter once: 
![image](https://github.com/raspiblitz/raspiblitz/assets/9646902/501c1ebc-00b5-4729-9e45-b6487bec9ab3)
But I don't see the menu where I'm prompted to enter the network ID.
*RC4 and updated to latest 1.11 scripts via patch menu.

**Comment by rootzoll** [comment]
@kravens please patch again to code in v1.11 branch and let me know if it now works.

**Comment by kravens** [comment]
![image](https://github.com/raspiblitz/raspiblitz/assets/9646902/1decccca-b5f4-4862-a8f0-c6a3302a1c48)
🎉 works now!

**Comment by rootzoll** [comment]
Will be part of final release.
