### ISSUE TITLE
cant cash out

### ISSUE THREAD

**Issue by eliddell1** [raspiblitz/raspiblitz#443]
All my channels are closed but no matter which  of my wallet addresses i try to cash out to, i get the error:
 FAIL - not a valid address ()

I have tried sending to my exodus and to a binance account.  my satoshis are untouchable. and im sort of livid.

**Comment by fluidvoice** [comment]
> All my channels are closed but no matter which of my wallet addresses i try to cash out to, i get the error:
> FAIL - not a valid address ()
> 
> I have tried sending to my exodus and to a binance account. my satoshis are untouchable. and im sort of livid.

Login with SSH then ctrl-c to a command line and run this to hopefully show what's going on when the error happens...
`sudo tail -n 50 /mnt/hdd/lnd/logs/bitcoin/mainnet/lnd.log`

**Comment by rootzoll** [comment]
@eliddell1 you can also try to activate RTL WebUI in service sub menu and try to send funds from there OR try to send funds directly with `lncli` on the terminal.

**Comment by nyxnor** [comment]
pls close this.
