### ISSUE TITLE
[amd64] reboot loop when recovering from SSD - the recover flow needs review

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#4435]
**Describe the bug**
Flashed an nvme disk to boot from in a Lenovo X270 laptop with the image from https://github.com/raspiblitz/raspiblitz/actions/runs/7933357199
Used a data disk from an RPi to recover from.
The first boot went ok, but got into a reboot loop afterwards by one of the raspiblitz scripts.

Booted to Linux recovery mode to edit the `raspiblitz.info`
![image](https://github.com/raspiblitz/raspiblitz/assets/43343391/fb8de3cb-6539-406d-a584-484e630d46f1)

deleted:
```
state='reboot'
```

after reboot it got to 
```
setupPhase=`done`
state='ready'
```
edited the `raspiblitz.info` again with:
```
setupPhase=`boot`
state='recover'
```

The recovery was successfully started after the manual interventions.

This logic will need to be reviewed for amd64.

**Comment by bitcoinorshit** [comment]
I have this same issue in x86 kvm. my main disk failed and i'm attempting to recover node drive qcow2. 

going in to recovery mode and deleting the line state='reboot' is not changing the outcome.

**Comment by bitcoinorshit** [comment]
I have this same issue. my main disk failed and i'm attempting to recover using image https://github.com/raspiblitz/raspiblitz/actions/runs/8037562914

going in to recovery mode and deleting the line state='reboot' is not changing the outcome.

It seems to continue to wright the `state='reboot'` in `raspiblitz.info`

**Comment by openoms** [comment]
This issue is still present. 

Commenting out 
https://github.com/raspiblitz/raspiblitz/blob/425442c2481954a37460e9a62846b69997f5f2d3/home.admin/_bootstrap.sh#L468-L470

in `/home/admin/_bootstrap.sh`
stops the bootloop and can proceed to fix the disk.


Snippet to fix the GPT integrity:
```
# Function to check and fix GPT integrity
check_and_fix_gpt() {
    local device=$1
    output=$(sudo gdisk -l $device 2>&1)
    if echo "$output" | grep -q "PMBR size mismatch"; then
        echo "GPT PMBR size mismatch detected on $device. Fixing..."
        sudo sgdisk -e $device
        echo "Fixed GPT PMBR size mismatch on $device."
    elif echo "$output" | grep -q "The backup GPT table is not on the end of the device"; then
        echo "Backup GPT table is not at the end of $device. Fixing..."
        sudo sgdisk -e $device
        echo "Fixed backup GPT table location on $device."
    else
        echo "No GPT issues detected on $device."
    fi
}

# List all block devices
devices=$(lsblk -dno NAME | grep -E '^sd|^nvme|^vd')

# Check and fix each device
for dev in $devices; do
    check_and_fix_gpt /dev/$dev
done
```

**Comment by openoms** [comment]
Fixes in: https://github.com/raspiblitz/raspiblitz/commit/5209508584c4751eae77548e96636cb77a8502dd
and  
- [ ] #4576

**Comment by rootzoll** [comment]
PR merged - final testing
