### ISSUE TITLE
[API/WebUI] Electrs will not be shown as installed 

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#4436]
With v1.11.0rc3 (with fixed API) Electrs is installed (thru ssh menues previously) but does but still shows in WebUI as uninstalled.

This is the SSH menus:
![Bildschirmfoto 2024-02-24 um 20 58 06](https://github.com/raspiblitz/raspiblitz/assets/2472225/00e1ca0d-47be-4ede-a4a4-f3b5d3ae7f40)

This is the WebUI:
![Bildschirmfoto 2024-02-24 um 20 58 00](https://github.com/raspiblitz/raspiblitz/assets/2472225/3d883d4a-a043-427b-a6ef-b78d7af1f1b2)

@fusion could this still be a side effect from the API?

**Comment by rootzoll** [comment]
Sidenote: Electrs is still building the index ... maybe thats why its not shown as installed?

**Comment by fusion44** [comment]
This is because every other script returns the installed status as `installed=1`, but electrs returns `serviceInstalled=1`. I'll add a special path for this. We should unify this for the next major release. Not sure why I didn't catch this during development. Doesn't seem to have been changed recently.

Electrs: https://github.com/raspiblitz/raspiblitz/blob/ec67c362f755ad968001d10d7815406cd8309a1e/home.admin/config.scripts/bonus.electrs.sh#L39
RTL: https://github.com/raspiblitz/raspiblitz/blob/ec67c362f755ad968001d10d7815406cd8309a1e/home.admin/config.scripts/bonus.rtl.sh#L71

**Comment by rootzoll** [comment]
@fusion44 I will change script to "installed"

**Comment by rootzoll** [comment]
BTW it was not unified because we didnt prepare the electrs script for fatpack/webui yet. I will go thru.

**Comment by rootzoll** [comment]
@fusion44 normally "installed" for a fatpack/webui app just means the user/codebase is preinstalled but not "on". Thats why there is the value `configured` that indicates if the App is "on" (1) or "off" (0). Thats how it should be when unified ... but it seems we dont have that 100% the same with all WebUI apps yet.

```
configured=1
installed=1
```

But you can also look into the `raspiblitz.conf` with the value `ElectRS` to check if its installed - that is much quicker if you dont need any other values.

**Comment by rootzoll** [comment]
Prepared a PR #4438 to fix the install script - testing at the moment.

**Comment by fusion44** [comment]
Ok perfect. I'll adapt once the pr is merged.


I can't use the conf file, because I need the connection info too. Maybe we can cache this into redis in the future.

**Comment by rootzoll** [comment]
PR merged. But just to note .. during electrs install now running into this (network) error:
```
Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  network failure seems to have happened
  if a proxy or similar is necessary `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  SSL error: received early EOF; class=Ssl (16); code=Eof (-20)
```

Seems not releated to the refactor of the install script, just some network error but I get it now constanly @openoms do you see anything that could cause this from our side?

Thats what the GTP doctor says:

The error you're encountering during the installation process on your Debian system is related to a network issue, specifically an SSL (Secure Sockets Layer) error, while trying to update the Rust package registry from `crates.io`. The error message "SSL error: received early EOF; class=Ssl (16); code=Eof (-20)" indicates that the connection was unexpectedly closed by the other side, which in this context likely means there was a problem with the SSL handshake or data transfer between your computer and the GitHub server hosting the `crates.io` index.

There are several potential causes for this issue:

1. **Network Issues**: Temporary network problems can disrupt the connection. This might be on your end, your ISP's, or even a temporary issue with GitHub's servers.

2. **Proxy or Firewall**: If you're behind a proxy or a firewall, it might be blocking or interfering with the secure connection to GitHub. The error message suggests using the `net.git-fetch-with-cli` configuration if a proxy or similar setup is necessary.

3. **SSL/TLS Configuration**: Misconfiguration or outdated SSL/TLS settings on your system might cause compatibility issues with GitHub's servers.

4. **GitHub Outage or Rate Limiting**: GitHub occasionally has outages or might rate limit connections if there's too much traffic from a single IP address or network, although this is less likely to present as an SSL error.

### How to Resolve the Issue

- **Check Network Connection**: Ensure your internet connection is stable and reliable. You might want to try a different network to rule out local network issues.

- **Proxy or Firewall Configuration**: If you're using a proxy or firewall, check its configuration. You can use the suggested `net.git-fetch-with-cli` Cargo configuration to let Git handle fetching, which might bypass the issue if Git is correctly configured for your proxy or firewall. Add the following to your Cargo configuration file (`~/.cargo/config` or `.cargo/config.toml`):

  ```toml
  [net]
  git-fetch-with-cli = true
  ```

- **SSL/TLS Settings**: Ensure your system's SSL/TLS certificates are up to date. You might need to update your system's certificates or the OpenSSL library.

- **Retry Later**: If the issue is on GitHub's end, waiting a bit and trying again later might resolve the problem.

- **GitHub Status**: Check [GitHub's status page](https://www.githubstatus.com/) to see if there are any ongoing issues with their services.

If you continue to experience issues after trying these steps, you might want to search for or ask for help on forums specific to Rust or Debian, as others may have encountered and resolved similar issues.

So I guess its "Retry Later" - lets see.

**Comment by rootzoll** [comment]
OK the "Retry Later" strategy worked - electrs is now installing and the Electrs is now showing up in the Applications section of the webUI when openend

But I now see two "Open" Buttons on the EletcRS item - see:
![Bildschirmfoto 2024-02-25 um 19 48 42](https://github.com/raspiblitz/raspiblitz/assets/2472225/6fd75e10-58f5-4adf-8637-aa69b63ef3c8)

@cstenglein I guess this is still to be fixed on the WebUI, correct?

**Comment by rootzoll** [comment]
This looks good now. Closing issue.
