### ISSUE TITLE
New Install with image from 2024-02-25 and CL Resultat in a not running CL

### ISSUE THREAD

**Issue by neversleep404** [raspiblitz/raspiblitz#4445]
Build raspiblitz-arm64-rpi-image-2024-02-25-45c5c0f
Fresh install of a new Pi 5 with SD-Card and NVMe results in an not running CL.
Shows "missing Data" in red.
On the LCD Display is also the green onion Link missing.

A Update from a running PI 5 from a build from last week okkures in following errors:

![Bildschirmfoto 2024-02-27 um 00 36 43](https://github.com/raspiblitz/raspiblitz/assets/80689652/b9ee7c03-5431-4101-ad06-5dd6c130495f)

![Bildschirmfoto 2024-02-27 um 00 41 16](https://github.com/raspiblitz/raspiblitz/assets/80689652/92e516b2-f97a-4031-b74f-2837c2a6eab3)

**Comment by openoms** [comment]
Can you share the CLN error log please:
```
sudo journalctl -fu lightningd -n50
```

might be related:
https://github.com/raspiblitz/raspiblitz/issues/4442

Can test if it is solved by running:
```
config.scripts/cl.install.sh on mainnet
```
or if that results to any error

**Comment by neversleep404** [comment]
This screenshots are from a fresh and clean setup of raspiblitz-arm64-rpi-image-2024-02-25-45c5c0f.
Blockchain existet and is used. All other data are deleted (in the setup process). In the setup I selected CL without any backup.
These are the Results:
![Bildschirmfoto 2024-02-28 um 01 50 29](https://github.com/raspiblitz/raspiblitz/assets/80689652/0ea95664-73f0-4857-abb4-c6b28b886629)

![Bildschirmfoto 2024-02-28 um 01 52 45](https://github.com/raspiblitz/raspiblitz/assets/80689652/f1fcef10-d85f-4355-ae6a-4546cfab30d3)

sudo journalctl -fu lightningd -n50

![Bildschirmfoto 2024-02-28 um 01 57 10](https://github.com/raspiblitz/raspiblitz/assets/80689652/74e3ba63-65aa-432d-9e86-b776593552f9)

config.scripts/cl.install.sh on mainnet

![Bildschirmfoto 2024-02-28 um 01 58 46](https://github.com/raspiblitz/raspiblitz/assets/80689652/937be919-c82e-4f62-afa9-11b2c8cd2b63)

![Bildschirmfoto 2024-02-28 um 01 59 20](https://github.com/raspiblitz/raspiblitz/assets/80689652/a250a2a8-7603-43d3-880a-1474a8032efc)

![Bildschirmfoto 2024-02-28 um 01 59 55](https://github.com/raspiblitz/raspiblitz/assets/80689652/50d20b15-eac6-4526-83fb-3a44c566a826)

![IMG_2385](https://github.com/raspiblitz/raspiblitz/assets/80689652/ad882d00-81f0-443f-96a7-dc6ee1f543ac)

**Comment by openoms** [comment]
Found the cause, it is the backup plugin failing.
The temporary solution is to deactivate it with running:
```
config.scripts/cl-plugin.backup.sh off
```

**Comment by neversleep404** [comment]
> Found the cause, it is the backup plugin failing. The temporary solution is to deactivate it with running:
> 
> ```
> config.scripts/cl-plugin.backup.sh off
> ```

Ok. It worked.
I try now the raspiblitz-arm64-rpi-image-2024-02-28-ede510f with a fresh and clean installation

**Comment by neversleep404** [comment]
raspiblitz-arm64-rpi-image-2024-02-28-ede510f works fine

**Comment by openoms** [comment]
> raspiblitz-arm64-rpi-image-2024-02-28-ede510f works fine

ok thanks for testing. Is the backup plugin on now?
```
cl plugin list
```
to be sure can also run:
```
config.scripts/cl-plugin.backup.sh on
```
to reinitialize the plugin.

**Comment by neversleep404** [comment]
It is on, No need to reinitialize it.
"name": "/home/bitcoin/cl-plugins-available/plugins/backup/backup.py",
         "active": true,
         "dynamic": true

**Comment by rootzoll** [comment]
Closing for release.
