### ISSUE TITLE
Watchtower Plugin CLN v23.11.2 failure stops CLN

### ISSUE THREAD

**Issue by neversleep404** [raspiblitz/raspiblitz#4457]
Installing Watchtower on RC3 CLN v23.11.2 on a PI 5 stops with a failure. 
Switching the Plugin off and CLN works again "cl-plugin.watchtower-client.sh off mainnet".

![Bildschirmfoto 2024-03-08 um 12 54 29](https://github.com/raspiblitz/raspiblitz/assets/80689652/e965a9b3-3c98-4776-ba41-0c41f26256ea)

![Bildschirmfoto 2024-03-08 um 12 56 35](https://github.com/raspiblitz/raspiblitz/assets/80689652/b1b87487-5ee5-4394-ad69-eafcb917ddb9)

![Bildschirmfoto 2024-03-08 um 12 55 37](https://github.com/raspiblitz/raspiblitz/assets/80689652/fc06c0ab-b486-4397-a7e6-cec067a216a9)

![Bildschirmfoto 2024-03-08 um 12 58 36](https://github.com/raspiblitz/raspiblitz/assets/80689652/8ba2da2d-4760-45ca-bfc9-d21d287531a9)

**Comment by openoms** [comment]
In
```
sudo journalctl -fu lightningd
```
getting the wrong config option:
```
raspiblitz-amd64 sh[2244002]: lightningd: Config file /home/bitcoin/.lightning/config line 16: watchtower-proxy=127.0.0.1:9050: unknown option
```

**Comment by openoms** [comment]
Instead of `watchtower-proxy=127.0.0.1:9050` it needs to be `proxy=127.0.0.1:9050`
as in https://github.com/talaia-labs/rust-teos/tree/master/watchtower-plugin#core-lightning-cln-config

**Comment by neversleep404** [comment]
raspiblitz-arm64-rpi-image-2024-03-10-b8fbb54 works fine on my Test System. Watchtower client plugin did not stops CLN.

**Comment by rootzoll** [comment]
Closing for Release.
