### ISSUE TITLE
"auto-unlock is OFF" constantly written to the log

### ISSUE THREAD

**Issue by fluidvoice** [raspiblitz/raspiblitz#446]
Is it necessary to write this to the log every 10 seconds forever?
admin@RaspiBlitz:/var/log $ sudo grep -c "auto-unlock is OFF" daemon.log
**1936**

https://github.com/rootzoll/raspiblitz/blob/3b6e93f84fac386856ac418e55273f9ca061f582/home.admin/_background.sh#L172

**Comment by rootzoll** [comment]
Good catch. This is not needed. TODO next release: remove that debug output.

**Comment by rootzoll** [comment]
OK just tested on v1.2 testmachine:
```
sudo grep -c "auto-unlock is OFF" /var/log/daemon.log
```
and git zero returns. Closing Issue.
