### ISSUE TITLE
Upgrading lnd or bitcoin or litecoin node?

### ISSUE THREAD

**Issue by born2los3built2win** [raspiblitz/raspiblitz#447]
What is the process of upgrading to newer version that is released or LND or Bitcoin or litecoin node? Through raspiblitz it should be done or through the command line? #

**Comment by rootzoll** [comment]
see update info in FAQ: https://github.com/rootzoll/raspiblitz/blob/master/FAQ.md#how-to-update-my-raspiblitz-after-version-098
