### ISSUE TITLE
nginx certificate error raspiblitz 1.11rc4

### ISSUE THREAD

**Issue by cdemkos** [raspiblitz/raspiblitz#4470]
nginx is not able to load a needed certificate:

`--> CHECK CONFIG: sudo nginx -t
2024/03/13 09:49:35 [emerg] 705420#705420: cannot load certificate "/mnt/hdd/app-data/nginx/tls.cert": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/mnt/hdd/app-data/nginx/tls.cert, r) error:10000080:BIO routines::no such file)
nginx: configuration file /etc/nginx/nginx.conf test failed`

**Comment by openoms** [comment]
Are you running in bitcoin only mode or with CLN?

**Comment by cdemkos** [comment]
> with CLN

**Comment by cdemkos** [comment]
After deleting the whole setup and data drive and installing [raspiblitz-fat-v1.11.0rc4-2024-03-15.img.gz](https://raspiblitz.fulmo.org/images/raspiblitz-fat-v1.11.0rc4-2024-03-15.img.gz) nginx seems to work again.
