### ISSUE TITLE
Running v1.1 now.

### ISSUE THREAD

**Issue by devdotmohit** [raspiblitz/raspiblitz#448]
1. Lightning Filtering Blockchain. It still shows - Progress: ?/567850.
2. du: cannot access '/mnt/hdd/bitcoin/indexes/txindex/042742.log': No such file or directory

**Comment by CommanderPoe** [comment]
> 1. Lightning Filtering Blockchain. It still shows - Progress: ?/567850.

It is always like this to me... take some minutes then its all goodie

**Comment by rootzoll** [comment]
The scanning info is on the list to be improved for future releases.

@codeoholic did it worked after a waiting time? The `cannot access` is a bit unsual

**Comment by fluidvoice** [comment]
> 1. Lightning Filtering Blockchain. It still shows - Progress: ?/567850.
> 2. du: cannot access '/mnt/hdd/bitcoin/indexes/txindex/042742.log': No such file or directory

Verify that LND is indeed running?... run:
`/home/admin/XXdebugLogs.sh`
Also run this and post the resulting URL:
`sudo tail -n 500 /mnt/hdd/lnd/logs/bitcoin/mainnet/lnd.log | nc termbin.com 9999`

**Comment by frennkie** [comment]
@codeoholic closeing due to inactivity and old version. Please try 1.5 or upcoming 1.6 and check/report issues separately.
