### ISSUE TITLE
[proxmox] BUILD FAILED --> PGP Verify not OK in German enviroment

### ISSUE THREAD

**Issue by M2402** [raspiblitz/raspiblitz#4497]
**Describe the bug**
Installing on a Intel NUC in a Proxmox environment, Debian 11.7.
Following https://cercatrova.blog/raspiblitz-auf-proxmox-installieren/

End of output... (see complete output in attached file)
-----------------------------------------------------
goodSignature(0)
correctKey(0)
BUILD FAILED --> PGP Verify not OK / signature(0) verify(0)
-----------------------------------------------------

**To Reproduce**
tried multiple VMs, same result

**Debug file**
[build card output.txt](https://github.com/raspiblitz/raspiblitz/files/14736510/build.card.output.txt)

**Comment by rootzoll** [comment]
Marked for inspection on next Proxmox testing round

**Comment by openoms** [comment]
Switch to a US English environment to solve this.

**Comment by rootzoll** [comment]
OK tested again with the lastest build script in `dev` branch and it works in my Proxmox environment. Closing issue.
