### ISSUE TITLE
configuring firewall

### ISSUE THREAD

**Issue by renepickhardt** [raspiblitz/raspiblitz#45]
I was looking to see if raspiblitz has a firewall activated but realized you just install it but don't configure it.

https://github.com/rootzoll/raspiblitz/blob/ee67947a631926779783d4cc22127108b4d8e284/build.sdcard/raspbianStretchDesktop.sh#L92

for basic usage (bitcoin + lightning) the following patch should fix this:

```
ufw allow ssh
ufw allow 8333
ufw allow 9735
ufw default deny incoming
ufw default allow outgoing
ufw enable
```

**Comment by rootzoll** [comment]
@renepickhardt totally correct. Now that people start to use the RaspiBlitz at home (not just for hacking on a event) we need to add firewall config. 

@vnnkl thx for the PR :) ... hope to integrate it till the end of this week.

**Comment by renepickhardt** [comment]
hey @vnnkl that is my PR!  srsly: I already provided the patch to the correct line
@rootzoll feel free to merge anyway (:

**Comment by vnnkl** [comment]
@renepickhardt 
I know, i referenced it in the pr. did not realize you wanted to open a pr yourself beyond this issue with pointers on where you'd put the changes, feel free to go ahead and open one to be merged

**Comment by renepickhardt** [comment]
@vnnkl no problem I already said above that rootzoll can merge your request. so everything is cool. Hope to meet you at the lightning hackday!

**Comment by rootzoll** [comment]
OK. Thanks all. I added firewall to the end of the configuration process. Do anybody think, having the firewall up after the whole sync/scan process is a problem?

**Comment by renepickhardt** [comment]
@vnnkl as discussed on the lightning hackday:
```
curl -i -H "Accept: application/json" -d '{"amount":ENTER_AN_INTEGER_AMOUNT_OF_SATOSHIS_INSTEAD_OF_THIS}' http://ln.rene-pickhardt.de/invoice
``` 
@rootzoll : why not doing it first?

**Comment by vnnkl** [comment]
@renepickhardt succeeded on 2nd attempt √

**Comment by renepickhardt** [comment]
@vnnkl thanks. 2nd attempt? How come it was difficult? finding a route should not have been an issue I guess? I assume you did the 0.8 mBTC? Also thanks for the drink at ROOM77. There was so much going on I didn't even manage to properly say good bye :(
