### ISSUE TITLE
redact i2p details from the debug link output

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#4507]
https://t.me/raspiblitz/142222

**Comment by rootzoll** [comment]
OK all adresses like `m3hlmj2gz2co5gu4ss3wj4b7ebeg2xbkrr65ogxvhn76uxna5qma.b32.i2p`will now get redacted.
see PR #4513
@openoms is that all it needs?

**Comment by openoms** [comment]
I think so
