### ISSUE TITLE
v1.11.0rc Hangs on Shutdown

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#4517]
Happens on RP4 with min & fat image of v1.11.rc6

![photo_5217749038705793262_y](https://github.com/raspiblitz/raspiblitz/assets/2472225/55f08ef1-98ec-4cca-9f77-2fc41dd8ece2)

**Comment by rootzoll** [comment]
there is also a reboot happening even before the boostrap script starts (because stop flag gets ignored). Very tricky on a min-image where you dont see anything on the LCD and the it hangs on reboot and not responding to SSH.

**Comment by rootzoll** [comment]
It looks like it does not hang when the sd card gets build on a real RaspberryPi and not in packer.

**Comment by openoms** [comment]
The latest image had no problems on restart during recovery on RPi4 and RPi5

**Comment by rootzoll** [comment]
The latest image rc6 contain a fix that needs to be tested more.

**Comment by rootzoll** [comment]
Looks good now - closing for v1.11.0 release
