### ISSUE TITLE
Persistent error notice

### ISSUE THREAD

**Issue by glensidecross** [raspiblitz/raspiblitz#453]
I'm running 1.0

I have the following error message: /mnt/hdd/raspiblitz.conf: -: line 5

This shows periodically on the raspi LCD.

**Comment by geco91** [comment]
line 5 could be the name of the RaspiBlitz ... it could be that you set an invalid string there. 

First try to SSH in and in main menu choose `NAME - change name/alias` and enter one without any special chars.

If you still have a problem ... please SSH in, go to terminal and check the config file with:
`sudo cat /mnt/hdd/raspiblitz.conf`
and post the content here.

**Comment by nyxnor** [comment]
please close this.
