### ISSUE TITLE
RC6 Bugs

### ISSUE THREAD

**Issue by neversleep404** [raspiblitz/raspiblitz#4535]
The update from RC5 to  did not work "out of the box". 
Missing parameters: dtparam=nvme in the config.txt
Without this parameter, NVME cannot be detected.

Similarly, rotating the screen by 180 degrees using "dtoverlay=waveshare35a:rotate=270" does not work in the config text. Only after inserting it following the completion of the setup program does the screen rotate.

**Comment by rootzoll** [comment]
This is addressed with this following PR #4530 and should be fixed with v1.11.0rc7 - @neversleep404 please test if r7 fixes all this once izts out.

**Comment by rootzoll** [comment]
closed for final release
