### ISSUE TITLE
Recheck DuckDNS

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#4547]
![duckdns](https://github.com/raspiblitz/raspiblitz/assets/2472225/cef21950-15e1-4f1b-b74c-d5b86a6a68f0)

**Comment by cdemkos** [comment]
![Bildschirmfoto vom 2024-04-18 22-16-23](https://github.com/raspiblitz/raspiblitz/assets/152734664/7cf86970-6051-4b67-af7b-4b9b4306344f)

**Comment by rootzoll** [comment]
Also recheck #2255 when on this

**Comment by rootzoll** [comment]
Seems like an email is now required to run letsencrypt on duckdns ... PR #4560 should fix this with v1.11.1rc1
