### ISSUE TITLE
Allow to use existing bitcoin folder

### ISSUE THREAD

**Issue by 1thales** [raspiblitz/raspiblitz#4558]
I have an HDD with a recently synced bitcoin blochchain. Not Mynode or Umrel, it was synced using just core on rapsiOS. Unfortunately Raspiblitz currently suggest two options (FRESHSETUP and FROMBACKUP) both requiring formatting HDD. Is there a possibility to just point it to the bitcoin folder?

**Comment by rootzoll** [comment]
At the moment that would be too much work for an edge case and there night be more changes in the future soon that make that even harder (introducing system boot partition, etc).
