### ISSUE TITLE
RTL Webinterface

### ISSUE THREAD

**Issue by amcitaly** [raspiblitz/raspiblitz#456]
Hello community, 
do someone know this: if I activate the RTL Webinterface from the Raspiblitz menu, it is sufficient to look the RTL on the windows machine? under the same local network of course, thank you. Bz I cant reach the RTL on my pc
![WEB ADMIN](https://user-images.githubusercontent.com/46417649/54822461-43a96300-4ca5-11e9-887e-5d915c01e643.PNG)

**Comment by rootzoll** [comment]
The WebUI is served as a webpage within the local network. You can call it from a windows machine, just anter that address into a web browser. 

> Bz I cant reach the RTL on my pc

Is that the same machine you run the SSH terminal on?

**Comment by fluidvoice** [comment]
login via SSH then ctrl-c to command line and run
`sudo netstat -pln | grep 3000`
`nc -z -v -w5 192.168.1.66 3000` 
Perhaps your router needs to have port 3000 forwarding turned on?

**Comment by amcitaly** [comment]
Thank you guys is done! Is my mistake, in these days I have been trying set the RTL with the configuration file that I found in the project of Shahana and for sure I make a mess
![RPI CONF](https://user-images.githubusercontent.com/46417649/54859356-658a0080-4d0c-11e9-8dd1-2f2cfda581ae.PNG)
Then the Raspi reconnize the folder RTL to put is settings as not empty so it can't install, I have cancel the folder and is done now. Sorry I didn't see that there was the possibility to automatically set it up by the Raspiblitz menu on Services, is so easy 
![LND NODE](https://user-images.githubusercontent.com/46417649/54859383-ae41b980-4d0c-11e9-88b1-5442f8d26da6.PNG)
Thank you very much 👍
