### ISSUE TITLE
cl-plugin.summary.sh - not working properly

### ISSUE THREAD

**Issue by Der-Zett** [raspiblitz/raspiblitz#4564]
**Describe the bug
On MENU->CLN->SUMMARY the following output is displayed:

mkdir: cannot create directory ‘/home/bitcoin/cl-plugins-available’: File exists
fatal: destination path 'plugins' already exists and is not an empty directory.

**To Reproduce**
Repeat from MENU->CLN->SUMMARY

**Raspiblitz-Version**
v1.11 (Stable)

It seems that summary-plugin is currently not being maintained. You can read about it in /home/bitcoin/cl-plugins-available/plugins/README.md

+++SNIP+++
Archived plugins

The following is a list of archived plugins that are no longer maintained and reside inside the 'archived' subdirectory.
Any plugins that fail CI will be archived.

If you like a plugin from that list, feel free to update and fix it, so we can un-archive it.

| [summary][summary]                   | Print a nice summary of the node status                                                     |
+++SNAP+++

The plug-in is still available at /home/bitcoin/cl-plugins-available/plugins/archived/summary/

Quick Fix:

Modify cl-plugin.summary.sh to reflect the "new" Path:

```
diff cl-plugin.summary.sh cl-plugin.summary_FIX.sh
15c15
< if [ ! -f "/home/bitcoin/cl-plugins-available/plugins/summary/summary.py" ]; then
---
> if [ ! -f "/home/bitcoin/cl-plugins-available/plugins/archived/summary/summary.py" ]; then
25,26c25,26
<   sudo -u bitcoin pip install --user -r /home/bitcoin/cl-plugins-available/plugins/summary/requirements.txt 1>/dev/null
<   $lightningcli_alias plugin start -H /home/bitcoin/cl-plugins-available/plugins/summary/summary.py 1>/dev/null
---
>   sudo -u bitcoin pip install --user -r /home/bitcoin/cl-plugins-available/plugins/archived/summary/requirements.txt 1>/dev/null
>   $lightningcli_alias plugin start -H /home/bitcoin/cl-plugins-available/plugins/archived/summary/summary.py 1>/dev/null
44c44
<   $lightningcli_alias plugin stop /home/bitcoin/cl-plugins-available/plugins/summary/summary.py
---
>   $lightningcli_alias plugin stop /home/bitcoin/cl-plugins-available/plugins/archived/summary/summary.py
```

**Comment by rootzoll** [comment]
@openoms can you take a look at this for v1.11.1 release?
