### ISSUE TITLE
[1.11.2 amd64] WebUI only shows Settings, Home and Apps show spinning circle

### ISSUE THREAD

**Issue by adevoss** [raspiblitz/raspiblitz#4569]
After provisioning and syncing blockchain Home page and Apps page show spinning circle.
Apps are installed.

**To Reproduce**
Install Debian 12
Execute build_sdcard.sh and reboot with existing datadrive.

**Debug file**
https://termbin.com/yfw8

**Comment by FragoriK** [comment]
My node is up and running since 2 weeks and I have had this issue since scratch. The app page never loads and has the loading circle.
The home page sometimes load after a while but the « connection details » part , this one only loaded once and then never again.
Same issue on iphone or mac, also same issue with the last 2 releases.

**Comment by FragoriK** [comment]
Also on the settings page, the raspiblitz version and the blitz-api don t show. Only the raspiblitz webui shows version 1.3.0-dev

**Comment by velgard1** [comment]
I experience more or less the same issue - I think I had the same with V1.10 already, but it worked from time to time or took only very long to show up...

I don't see SAT/BTC values and a loading section, at the bottom in the Lightning section I also don't have values. It also shows only webui 1.2.0.

Apart from the UI everything seems to be fine, no matter if it's SSH, BitBanana (former ZAP) or RTL.

**Comment by velgard1** [comment]
Reinstalled API+WebUI and it works now (with my Pi4 config V1.2.0 was installed).

**Comment by FragoriK** [comment]
Used to have the same issue for months… then this morning I uninstalled and reinstalled webUI via ssh and now it works fine and smooth…
Seems like Velgard1 did the same thing a month ago and has the same result, so maybe it just needs a uninstall / reinstall … fyi it can be done without restarting the node and takes only a couple minutes :)

**Comment by woiwoiwoiwoi** [comment]
Same issue here. For Apps, I get a spinning circle. Uninstalling and reinstalling did not fix the issue.

**Comment by adevoss** [comment]
Today I tried `build_sdcard.sh` from `dev` branch.
All fine accept LNbits (502 Bad Gateway)

**Comment by StartmeupLuca** [comment]
> Used to have the same issue for months… then this morning I uninstalled and reinstalled webUI via ssh and now it works fine and smooth… Seems like Velgard1 did the same thing a month ago and has the same result, so maybe it just needs a uninstall / reinstall … fyi it can be done without restarting the node and takes only a couple minutes :)

how do you  uninstall and reinstall the webUI?

**Comment by cstenglein** [comment]
> how do you uninstall and reinstall the webUI?

Via SSH:

Settings -> Uncheck `Blitz API + WebUI` and confirm to uninstall. Then re-check it and confirm to install.

**Comment by cstenglein** [comment]
Could be fixed by https://github.com/fusion44/blitz_api/pull/272

**Comment by rootzoll** [comment]
This issue got removed from v1.11.3 milestone because its collected as same/similar under: https://github.com/raspiblitz/raspiblitz/issues/3608

**Comment by cstenglein** [comment]
Closed as duplicate, see https://github.com/raspiblitz/raspiblitz/issues/3608
