### ISSUE TITLE
RPC PW

### ISSUE THREAD

**Issue by apierp1** [raspiblitz/raspiblitz#457]
/mnt/hdd/bitcoin/bitcoin.conf stores rpcpassword in plain text by default. Is this avoidable?

**Comment by apierp1** [comment]
So does lnd.conf

**Comment by fluidvoice** [comment]
> /mnt/hdd/bitcoin/bitcoin.conf stores rpcpassword in plain text by default. Is this avoidable?

This is a Linux admin question, not related to Raspiblitz. The solution involves file privileges and user access.  What are you concerned about?  Is your LAN and machine not secure?

**Comment by geco91** [comment]
The RPC password has to be stored in bitcoin.conf ... thats the normal way to set the RPC password for bitcoind. LND needs the password also to be able to connect to the bitcoind.

I recommend this issue to be closed.
