### ISSUE TITLE
BonusApp: Add Public Pool for Solo Mining

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#4581]
Public Pool seems a good fit to mine with smaller Miners like BitAxe, etc ...
https://github.com/benjamin-wilson/public-pool

see: https://github.com/raspiblitz/raspiblitz/discussions/3942#discussioncomment-9330744

@WantClue if you are working on a RaspiBlitz PR for this, let us know :)

**Comment by WantClue** [comment]
I do and it's kinda functional. I'm planning on releasing it soon.

**Comment by WantClue** [comment]
short update on my side got a functional working one. Only thing is I'm not sure how you want to communicate this, but it appears to only run on a pi5 with nvme. pi5 with usb won't work, pi4 also wont work.

Shall I create a test clause in the script to check for pi version and nvme drive and deny the install otherwise ? @rootzoll

**Comment by rootzoll** [comment]
OK I merged #4647 into the branch `4581-publicpool` https://github.com/raspiblitz/raspiblitz/tree/4581-publicpool 

I changed that the apps will run in the user home of the sd card (not on the SSD app-data - that should be just for data that survives reinstalls during updates).

Together with some other adaption (see commit messages of branch) I think I got some basics running.

Was able to call the WebUI:
![Bildschirmfoto 2024-07-18 um 22 23 54](https://github.com/user-attachments/assets/19bc3559-beb4-4569-bf91-5e7c24b03dbd)

Also my little test NerdAxe was able to connect to the stratumpol and API seemed up.
It also installed on my Pi4 with ols SSD drive - so that does not seem to be an issue.

Only the WebUI didnt seem to be picking up any data from my miner. Also showing to connect to `stratum+tcp://public-pool.io:21496` .. not to my local IP (which I used with the miner) and nothing under `Online Devices`. @WantClue is there still some config missing?

**Comment by WantClue** [comment]
As I said you won't be able to run it long enough on user home see my PR.
Or with creating the new user is there more than 2GB free on /home/{APPID} ?

You're correct for the UI I missed to commit 1 change, I'll push it in a sec.

**Comment by WantClue** [comment]
In order to change the webui to actually show data from the local public pool instance it needs a change on the environment.prod.ts file therefore I suggest the following change:

`# Modify the environment.prod.ts file
echo "# Updating environment.prod.ts with correct API and STRATUM URLs"
sudo -u ${APPID} tee /home/${APPID}/${APPID}-ui/src/environments/environment.prod.ts > /dev/null << EOL
export const environment = {
    production: true,
    API_URL: 'http://${localIP}:${PORT_API}',
    STRATUM_URL: '${localIP}:${PORT_STRATUM}'
};
EOL`

**Comment by rootzoll** [comment]
> As I said you won't be able to run it long enough on user home see my PR. Or with creating the new user is there more than 2GB free on /home/{APPID} ?

What part of the directory does need that space? RaspiBlitz has different places to put data. The base should always be the home user directory `/home/{APPID} ` where the app lives and gets executed from - thats running at the moment from the sd card. But with that home user directory subdirectories can be linked to other places - either per configuration of the app if possible or by `ln` (linking a directory thru linux file system)... the following places exists:

`/mnt/hdd/app-data/{APPID} ` --> on the SSD/NMVe, for data of an app that is critical and needs to survive recoveries .. will also be part of migration data ZIP when user moves to a different hardware

`/mnt/hdd/app-storage/{APPID}` --> on the SSD/NMVe, for data of an app that is OK to be lost and can be rebuild .. like blockchain data or electrum indexes. Normally survives recovery but will not be part of a migration ZIP if user moves hardware. Apps should automatically rebuild/redownload that data if missing.

`/var/cache/raspiblitz/{APPID}` --> a RAM drive, limited space (32MB at the moment), fast, all is gone after reboot

**Comment by rootzoll** [comment]
```
The script is now adding the environment.prod.ts changes:

admin@192.168.178.60:~ ₿ sudo cat /home/publicpool/publicpool-ui/src/environments/environment.prod.ts
export const environment = {
  production: true,
  API_URL: 'http://192.168.178.60:3334',
  STRATUM_URL: '192.168.178.60:3333'
};
```

Still seeing on the WeUI:
![Bildschirmfoto 2024-07-22 um 00 27 27](https://github.com/user-attachments/assets/11e4f827-fe38-4e2d-b653-97516215b41f)

@WantClue is there anything more todo? https://github.com/raspiblitz/raspiblitz/blob/023cf57a0265609c899cb52f31162c7e38cf014b/home.admin/config.scripts/bonus.publicpool.sh#L102

**Comment by Peter71131** [comment]
Is this still planned to be a part of the next release? Inital it was MS 1.11.2 and i thought maybe it is already included in the actual release?

**Comment by rootzoll** [comment]
@Peter71131 We rushed 1.11.2 as a quick patch version ... this PR is still on the list for next release v1.11.3

**Comment by rootzoll** [comment]
OK Publicpool will be part of RaspiBlitz v1.11.3rc1 with PR #4785
