### ISSUE TITLE
Update Node.js

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#4587]
```
node -v
v20.5.1
```
Latest LTS is:
v20.13.1

All Web Apps need to be tested.

**Comment by rootzoll** [comment]
OK the https://deb.nodesource.com/setup_20.x  repo that we use is really just offering v20.5.1 .. so this is no quick update. Pushing it back to later release and for further team discuss.

**Comment by cstenglein** [comment]
Most likely the issue is that node source changed the distro to "nodistro".

In the install script, the distro is still in there.

Should be able to update to the newest 20.x version without issues since there are no breaking changes

**Comment by rootzoll** [comment]
Final testing when #4767 merged.
