### ISSUE TITLE
[feature-request] Add Tailscale to config.scripts

### ISSUE THREAD

**Issue by NilByte** [raspiblitz/raspiblitz#4607]
Tailscale seems quite easy to install following this guide:

https://tailscale.com/download/linux/rpi-bullseye

To get scanning of QR code for Bitbanana connect to work, I had to add line in lnd.conf:

`tlsextradomain=<my tailscale domain>`

Latest Bitbanana app 0.8.1 has added Tailscale as VPN option and it works well. No slow response time in app as when it's connected over Tor.

**Comment by rootzoll** [comment]
PR to add tailscale: #4712
