### ISSUE TITLE
Unable to resolve hostname on Update

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#462]
see https://twitter.com/bhavman2/status/1110247015244414976

check to change hostname of raspberry just before reboot to prevent those errors messages.

**Comment by bhavman2** [comment]
Close to 24 hours into this issue. Status hasn't changed even after reboot. 

![image](https://user-images.githubusercontent.com/35750982/55006079-61731280-4f9a-11e9-8dce-d338bba83d3f.png)

command line flashes "sudo: unable to resolve host bhavman2LND" at the bottom of the terminal window every 5 seconds.. any ideas?

**Comment by CommanderPoe** [comment]
Raspi-Config hostname? then set the old name you have on V1.0 ? Or is it something related to bitcoind rpc username?

**Comment by bhavman2** [comment]
Looks like v1.1 set my hostname from the node alias I had set in the previous version which included brackets. Removing the brackets from my hostname did the trick. Not sure why I didn't encounter this issue with v1.0 though.

**Comment by rootzoll** [comment]
TODO: check to change hostname of raspberry just before reboot to prevent those errors messages.
TODO: sanatize hostnames on update/migration

**Comment by rootzoll** [comment]
This should be fixed now for v1.2 release
