### ISSUE TITLE
apps not running on web ui

### ISSUE THREAD

**Issue by up1son** [raspiblitz/raspiblitz#4631]
Hello, I started using raspiblitz web ui but in the apps section nothing appears, a yellow circle remains spinning as it is loading but it stays like this and nothing happens, what could be happening and can be solved.
![raspi](https://github.com/raspiblitz/raspiblitz/assets/171509381/57d3a4bd-4d23-4000-b428-2a5300760e8a)

**Comment by rootzoll** [comment]
This issue got removed from v1.11.3 milestone because its collected as same/similar under: https://github.com/raspiblitz/raspiblitz/issues/3608

**Comment by cstenglein** [comment]
Closed as duplicate, see #3608
