### ISSUE TITLE
missing files in txindex

### ISSUE THREAD

**Issue by rookey** [raspiblitz/raspiblitz#464]
I've set up the latest version of RaspiBlitz and copied all blockchain data from my local node, now since finishing the setup, bitcoind creates thousands of files in indexes/txindex (which I didn't seem to have on my desktop node), while in another console I'm getting the status message 

```
Lightning Filtering Blockchain
Progress: ?/569027
Please wait- this can take some long time
Its OK to close terminal and ssh back in later
```
However, occasionally, I see several messages like
```
cannot access '/mnt/hdd/bitcoin/indexes/txindex/102629.ldb': no such file or directory
```
popping up, and indeed, these files seem to be missing. Is it possible/necessary to recreate them somehow?

thanks!

**Comment by rootzoll** [comment]
Had the blockchain you copied over from your compter `txindex=1` switched on in its `bitcoin.conf`?

**Comment by rookey** [comment]
Yes - actually it didn't before, but the setup instructions ("Copying from another computer") indicated that's how this setting is supposed to be, so I changed it, triggering this extensive indexing process.

Meanwhile my node is running fine apart from a few hitches, so the indexing process could be completed at the end. Just wanted to leave this here in case someone else runs into similar problems.

Could I also set txindex=0 on the raspiblitz without problems?

**Comment by rootzoll** [comment]
> Could I also set txindex=0 on the raspiblitz without problems?

Thats the plan for a future release: https://github.com/rootzoll/raspiblitz/issues/227

Feel free to try early and report if you see any problems with going forward without txindex.

**Comment by rookey** [comment]
awesome, thanks!
