### ISSUE TITLE
[WebUI] Setup-Redesign - Systemstates

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#4644]
After v1.11.1rc1 check what support is needed here:
https://github.com/raspiblitz/raspiblitz-web/issues/747

**Comment by escapedcat** [comment]
If this worked before the design update, everything should be correct. We'll have a look.

**Comment by cstenglein** [comment]
Since this was already done and the CLN seed word issue will be checked in 1.11.3,  I moved this issue in there as well.
