### ISSUE TITLE
stuck at lightning filtering blockchain v1.1

### ISSUE THREAD

**Issue by coinicarus** [raspiblitz/raspiblitz#466]
the issue i experience starts with the screen below waiting for bitcoind to get ready
![image](https://user-images.githubusercontent.com/47729697/55118030-418b3e00-50c3-11e9-9f6e-4a655ab94ab1.png)

then we move onto the following:
![image](https://user-images.githubusercontent.com/47729697/55118067-6a133800-50c3-11e9-922b-317922d31de1.png)
it never moves past this. i have tried the sudo shutdown - r now twice to no avail 
when i attempt to get the logs i receive the following error: 
![image](https://user-images.githubusercontent.com/47729697/55118532-0c7feb00-50c5-11e9-8cd5-f7695970c621.png)
[update i re-ran it correctly this time  /home/admin/XXdebugLogs.sh | nc termbin.com 9999, user error :) here is the log
https://termbin.com/kfld9 
I then ran sudo tail -n 500 /mnt/hdd/lnd/logs/bitcoin/mainnet/lnd.log | nc termbin.com 9999
got the logs here:
https://termbin.com/vsds

I then ran the following from this post: https://github.com/rootzoll/raspiblitz/issues/450  

 sudo grep -A100 "LTND: Version:" /mnt/hdd/lnd/logs/bitcoin/mainnet/lnd.log | nc termbin.com 9999

here is the log:
https://termbin.com/5d93

&
sudo grep ERR /mnt/hdd/lnd/logs/bitcoin/mainnet/lnd.log | nc termbin.com 9999
for some reason i didnt get a folder location back when i ran this so im hoping this log is with the previous one above 

Thank you for your time and assistance

**Comment by fluidvoice** [comment]
some are reporting running the script `./70initLND.sh` fixed this LND getting stuck "filtering blockchain".

**Comment by coinicarus** [comment]
> some are reporting running the script `./70initLND.sh` fixed this LND getting stuck "filtering blockchain".

ok cool! i will try this :) i'm guessing run the script and restart the node?

**Comment by coinicarus** [comment]
> > some are reporting running the script `./70initLND.sh` fixed this LND getting stuck "filtering blockchain".
> 
> ok cool! i will try this :) i'm guessing run the script and restart the node?

forget it i got it i think :) thank you again!

**Comment by coinicarus** [comment]
so far so good! it rebooted and came up now it shows completing final sync 👍 
![image](https://user-images.githubusercontent.com/47729697/55126734-51ffe080-50e4-11e9-9113-5118dd5fb301.png)

**Comment by coinicarus** [comment]
officially up and running, thank you again! 
![image](https://user-images.githubusercontent.com/47729697/55198445-613a6900-518c-11e9-8fa8-3cf2c4df4e63.png)
