### ISSUE TITLE
Reboot bleibt hängen, nach Neuinstallation des RaspiBlitz

### ISSUE THREAD

**Issue by Navycommander-DE** [raspiblitz/raspiblitz#4669]
Hallo zusammen,

ich habe einen RaspiBlitz neu zusammen gebaut und installiert.
Nach dem vollständigen Download der Blockchain, bleibt der Blitz immer im Reboot hängen.
Habe dann ca. 24h gewartet, hing aber immer noch im Reboot.

Wenn ich Einstellungen im Menü ändere (z.B. rotate display) und dann reboote, ende ich immer im selben Problem.

Ich habe auch schon probiert, die Watchdog Runtime auf 3600 einzustellen wie in diesem Beitrag erklärt.
(https://github.com/raspiblitz/raspiblitz/issues/4534) 

Da ich noch ein Neuling im Linux Space bin, wäre ich für Hilfe sehr dankbar.

Gruß NC

**To Reproduce**
Wenn ich Einstellungen im Menü ändere (z.B. rotate display) und dann reboote, ende ich immer im selben Problem.
Oder wenn ich über das Menü den Pi reboote auch das selbe.

**Debug file**
![Screenshot 2024-07-29 132722](https://github.com/user-attachments/assets/477c0477-28f2-41ac-8f86-84aeeb8d12d7)
![thumbnail_IMG_4092](https://github.com/user-attachments/assets/5413ad76-ebb4-48ed-8da4-e5613d08b2c3)
[Debug File 2024-07-29 - 135500.txt](https://github.com/user-attachments/files/16412309/Debug.File.2024-07-29.-.135500.txt)

**Comment by rootzoll** [comment]
That watchdog hang is a bit of a quirk we dont have found yet - see here: #4534 (closing becasue of double)

Workaround:  just cut power and reconnect to trigger the reboot - its safe todo all other important processes altready stopped.
