### ISSUE TITLE
On Debian 12.6 VM, `build_sdcard.sh` always fails after cutting off Internet on its own

### ISSUE THREAD

**Issue by woiwoiwoiwoi** [raspiblitz/raspiblitz#4677]
**Describe the bug**
The `build_sdcard.sh` script always seems to cut off Internet connection at a specific moment. After a reboot, the script then completes successfully. As far as I can tell, the last package that is installed and configured is `recolvconf`.

**To Reproduce**
Using virt-manager, I installed Debian, using the `debian-12.6.0-amd64-DVD-1.iso` image. I also tried out the OSBoxes 64 Bit 12.6 image. The `build_sdcard.sh` script from the dev channel always aborts here:

![raspiblitz](https://github.com/user-attachments/assets/77557fee-293f-40ac-b565-b5a4771cf198)

After a reboot, the script completes successfully and everything appears to be working fine.

**Comment by tbshfr** [comment]
I can confirm the bug, after the package resolvconf is installed, dns resolving does not work anymore and the script exits because deb.debian.org cant be resolved.
After a reboot the install works.

**Comment by rootzoll** [comment]
Please give us two more weeks .. VM install on debian is the next big TODO on our list.

**Comment by rofra** [comment]
I also confirm the issue when building on Raspberry Pi 4B directly from sdcard after booting on 2024-03-15-raspios-bookworm-arm64.img.xz . 
Seems like /etc/resolv.conf is emptied after resolvconf package installation

**Comment by rofra** [comment]
I wrote a pull request #4715 for solving the issue

**Comment by rootzoll** [comment]
PR merged - final testing
