### ISSUE TITLE
Update to mempool 3.0.0

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#4680]
Try with: https://github.com/mempool/mempool/tree/v3.0.0-dev8

**Comment by kravens** [comment]
I tried installing it on 1.11.2 by modifying bonus.mempool.sh to tag 3.0.0, but it failed. Looks like newer npm version is required together with some other updated dependencies.

**Comment by rootzoll** [comment]
PR #4747 merged and will be part of v1.11.3rc1 for testing.
