### ISSUE TITLE
[1.11.1/dev] build_sdcard.sh failing

### ISSUE THREAD

**Issue by adevoss** [raspiblitz/raspiblitz#4682]
Script fails:
⠙ Generating browser application bundles (phase: sealing)...Killed
FAIL - npm run build did not run correctly, aborting (1)

**To Reproduce**
- install Debian 12 (no GUI) on a VM.
- execute `build_sdcard.sh -b dev -f 1 -d headless -t 0 -w off` from `dev` branch

**Comment by adevoss** [comment]
`build_sdcard.sh -b dev -f 0 -d headless -t 0 -w off` works (no fatpack, now v1.11.2)

**Comment by rootzoll** [comment]
Give us 2 more weeks - to optimze the VM install is next after v1.11.2 release

**Comment by rootzoll** [comment]
@adevoss I did some successfull build on Debian12 for VMs - if you find the time please retry with latest `build_sdcard.sh` from `dev` branch - thx.

**Comment by adevoss** [comment]
`build_sdcard.sh -b dev -f 0 -d headless -t 0 -w off` works. Build and Recovery.  (displays v1.11.2)
But still #4568

**Comment by rootzoll** [comment]
Thanks - so closing this issue. #4568 is still on my list for v1.11.3
