### ISSUE TITLE
Tor exiting always after update to v1.11.2

### ISSUE THREAD

**Issue by BlueSnake830** [raspiblitz/raspiblitz#4709]
**Describe the bug**
I've updated to raspiblitz v1.11.2 from v1.10.0. After the update, TOR is not running again -> LND cannot activate the channels anymore.

I've also tried the steps, mentioned on https://github.com/raspiblitz/raspiblitz/issues/2176#issuecomment-818753214, but doesn't fix the issue. (The error messages were the same.)

**To Reproduce**
Start raspiblitz v1.11.2.
- I've restarted / shut-down reaspiblitz several times, but no peer connection for lnd established.

**Debug file**

sudo systemctl status tor
● tor.service - Anonymizing overlay network for TCP (multi-instance-master)
     Loaded: loaded (/lib/systemd/system/tor.service; enabled; preset: enabled)
     Active: active (exited) since Mon 2024-08-26 13:50:38 BST; 33min ago
   Main PID: 630 (code=exited, status=0/SUCCESS)
        CPU: 6ms

Aug 26 13:50:38 raspberrypi systemd[1]: Starting tor.service - Anonymizing overlay network for TCP (multi-instance-master)...
Aug 26 13:50:38 raspberrypi systemd[1]: Finished tor.service - Anonymizing overlay network for TCP (multi-instance-master).

Events (TOR/NYX NOTICE-ERR):
 │ 14:32:08 [NYX_NOTICE] No nyxrc loaded, using defaults. You can customize nyx by placing a configuration file at /var/lib/tor/.nyx/config (see https://nyx.torproject.org/nyxrc.sample for its options).
 │ 14:32:08 [NOTICE] New control connection opened.
 │ 14:31:48 [NOTICE] Tried for 120 seconds to get a connection to 172.81.178.22:9735. Giving up. (waiting for circuit) [7 duplicates hidden]
 │ 14:31:45 [NOTICE] We'd like to launch a circuit to handle a connection, but we already have 35 general-purpose client circuits pending. Waiting until some finish. [21262 similar message(s) suppressed in
 │   last 600 seconds]
 │ 14:31:15 [NOTICE] Tried for 120 seconds to get a connection to soa.nodes.lightning.directory:53. Giving up. (waiting for circuit) [1 duplicate hidden]
 │ 14:31:09 [WARN] Rejecting SOCKS request for anonymous connection to private address 127.0.0.1. [3 similar message(s) suppressed in last 300 seconds]
 │ 14:30:43 [NOTICE] Tried for 120 seconds to get a connection to aqkmmsxed5xslm3a7usejdovls3wr5pyc6coylripp3t47booor7nyad:9735. Giving up. (waiting for rendezvous desc) [6 duplicates hidden]
 │ 14:30:34 [NOTICE] Tried for 120 seconds to get a connection to n3dgg7m6c6v7scc6zkonbuxsn7ijwnk4v4lcueiton7pin7u5ll276ad:9735. Giving up. (waiting for rendezvous desc) [6 duplicates hidden]
 │ 14:30:34 [NOTICE] Tried for 120 seconds to get a connection to znk2nrq4qikvwl6okwk2lbzwc32bw7nqami3ldvyf4sw2mxnt5biybad:9735. Giving up. (waiting for rendezvous desc) [6 duplicates hidden]
 │ 14:29:57 [NOTICE] Failed to find node for hop #1 of our path. Discarding this circuit. [9 duplicates hidden]
 │ 14:29:15 [NOTICE] Tried for 120 seconds to get a connection to soa.nodes.lightning.directory:0. Giving up. (waiting for circuit)
 │ 14:26:12 [NOTICE] Tried for 120 seconds to get a connection to ui2idgukrecwroq2hfzcw4auquaup6bpdzfy2jbofqxnks3ddcvw35yd:9735. Giving up. (waiting for rendezvous desc)
 │ 14:26:12 [NOTICE] Tried for 120 seconds to get a connection to 90.112.235.247:9735. Giving up. (waiting for circuit)
 │ 14:26:12 [NOTICE] Tried for 120 seconds to get a connection to d6ochvm5iadge6yyr3jvbamvzejcqaobvaikzbf62rnt7rrgf63iyeyd:9735. Giving up. (waiting for rendezvous desc)
 │ 14:25:38 [NOTICE] Closed 1 streams for service aqkmmsxed5xslm3a7usejdovls3wr5pyc6coylripp3t47booor7nyad.onion for reason resolve failed. Fetch status: No more HSDir available to query.
 │ 14:25:29 [NOTICE] Closed 1 streams for service n3dgg7m6c6v7scc6zkonbuxsn7ijwnk4v4lcueiton7pin7u5ll276ad.onion for reason resolve failed. Fetch status: No more HSDir available to query.
 │ 14:25:29 [NOTICE] Closed 1 streams for service znk2nrq4qikvwl6okwk2lbzwc32bw7nqami3ldvyf4sw2mxnt5biybad.onion for reason resolve failed. Fetch status: No more HSDir available to query.
 │ 14:24:59 [WARN] Rejecting SOCKS request for anonymous connection to private address 127.0.0.1. [4 similar message(s) suppressed in last 300 seconds]
 │ 14:24:09 [NOTICE] Tried for 120 seconds to get a connection to ln1qwl4ngup90xurs68cmk7fx3qmjj6vw0smylkhnfqxa5az93summ0qcrt7zm.nodes.lightning.directory.:0. Giving up. (waiting for circuit)
 │ 14:23:05 [NOTICE] Tried for 120 seconds to get a connection to 116.227.55.191:9735. Giving up. (waiting for circuit)
 │ 14:23:05 [NOTICE] Tried for 120 seconds to get a connection to qvwiy3ml66dwfgvqbkmzsihq3ju3dtcmxy7k3ue3unrxczulza5yz4qd:9735. Giving up. (waiting for rendezvous desc)
 │ 14:23:05 [NOTICE] Tried for 120 seconds to get a connection to tk6b7gg2qboj3oe4pqazlqmderhbexulx3iup2jhk7urlu23roy2usad:9735. Giving up. (waiting for rendezvous desc)
 │ 14:22:28 [NOTICE] Tried for 120 seconds to get a connection to iqb5putk6rym4dtbz24h7w365vpgjibwvvve42jd56oumharx332muqd:9735. Giving up. (waiting for rendezvous desc)
 │ 14:22:28 [NOTICE] Tried for 120 seconds to get a connection to hywhe6xua36w5aya3hjwlelbabi3naqkbbe6ube5ohfwhokzwkykdtqd:9735. Giving up. (waiting for rendezvous desc)
 │ 14:22:28 [NOTICE] Tried for 120 seconds to get a connection to xxwb4h6bubywpw4knjghzoaocp7yi3cccvyjnuehpqjhew7l73r5k7ad:9735. Giving up. (waiting for rendezvous desc)
 │ 14:22:07 [NOTICE] Tried for 120 seconds to get a connection to [2602:ffb6:4:c927:f816:3eff:fea0:ef40]:9735. Giving up. (waiting for circuit)
 │ 14:22:07 [NOTICE] Tried for 120 seconds to get a connection to 235p6kn5odzvuvx4qmrzdf47xh2pjzfw36rnhbguzl3ym4ebcfodjuyd:9735. Giving up. (waiting for rendezvous desc)
 │ 14:22:07 [NOTICE] Tried for 120 seconds to get a connection to 172.81.179.14:9735. Giving up. (waiting for circuit)
 │ 14:21:54 [NOTICE] Tried for 120 seconds to get a connection to moemmlkquunz2apwpsweb5yuxhjgw22qmsomrgizvvbald4vzkk5f6yd:9735. Giving up. (waiting for rendezvous desc)
 │ 14:21:54 [NOTICE] Tried for 120 seconds to get a connection to qubfdvosyihden5236tm4nnmmm2vw6ditrcpomgky7efw7m65kja2bid:9735. Giving up. (waiting for rendezvous desc)
 │ 14:21:54 [NOTICE] Tried for 120 seconds to get a connection to td5wtk7m46httshtq5qyitata2hicbpiieh5j45q4jiwef5gfijw3vyd:9735. Giving up. (waiting for rendezvous desc)
 │ 14:21:45 [NOTICE] We'd like to launch a circuit to handle a connection, but we already have 35 general-purpose client circuits pending. Waiting until some finish. [9501 similar message(s) suppressed in last │   600 seconds]

**Comment by rootzoll** [comment]
Can you turn off TOR and see if LND is finding peer?
SSHMENU > SETTINGS > "Run behind Tor" to not selected & OK

**Comment by cstenglein** [comment]
Do you have LNDg installed by any chance?

A friend had a similar issue and the culprit was LNDg.

**Comment by BlueSnake830** [comment]
I now found the root cause after starting from scratch. LNDg was not installed. 

My router received a new feature to block TOR traffic for specific VLANs. This feature was enabled automatically Unfortunately there is a bug in the router firmware such that TOR is always blocked for all VLANs. 

So this is no bug in RaspiBlitz.
