### ISSUE TITLE
RTL unable to login Password Not Found In LND Config! V.1.1

### ISSUE THREAD

**Issue by born2los3built2win** [raspiblitz/raspiblitz#471]
Im on version 1.1 Im not able to login RTL 
i get the error msg  Password Not Found In LND Config!
1. i reset my rpc (b) password.
2. uninstalled and reinstalled RTL
<img width="1348" alt="Screen Shot 2019-03-28 at 3 07 31 PM" src="https://user-images.githubusercontent.com/25369917/55185682-44416e00-516b-11e9-871f-07aede3a0939.png">

**Comment by rootzoll** [comment]
This is a RTL based question - I am not that deep into the RTL code. Can you post the issue over at: https://github.com/ShahanaFarooqui/RTLFullApplication

**Comment by born2los3built2win** [comment]
Done thank you

**Comment by goodc0re** [comment]
Having the same issue.

**Comment by rootzoll** [comment]
For visitors -- continue here: https://github.com/ShahanaFarooqui/RTLFullApplication/issues/7

**Comment by ShahanaFarooqui** [comment]
Please redirect all RTL related issues to repo: https://github.com/ShahanaFarooqui/RTL/
