### ISSUE TITLE
[feat] Alby Hub 

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#4727]
https://blog.getalby.com/what-is-alby-hub/

https://github.com/getAlby/hub

https://github.com/getAlby/hub/tree/master/scripts/linux-x86_64

**Comment by bumi** [comment]
Let me know if I can help. Alby Hub is a single executable available for different environments.
As "node backend" it either works with a built in LDK based node or it can connect to a LND node (which could/should be the default for raspiblitz) If used with LND we can configure the address, cert, and macaroon with an env variable. 

no other config should be needed.

There is also a docker container if that helps.

Note: currently Alby Hub still requires an Alby account and has email notifications and similar enabled by default. In a future version this will be lifted.

**Comment by MoritzKa** [comment]
Oh that would be cool! Then I can restart my Raspiblitz again.

**Comment by boilroaming** [comment]
I really hope this will some soon.

**Comment by rookey** [comment]
that would be awesome! I was somewhat confused why this doesn't work yet, as there's a menu item to connect to Getalby in Raspiblitz 1.11.x already. :)

**Comment by itstomekk** [comment]
I see people asking for Alby Hub on Raspiblitz! +1

**Comment by MindaugasN** [comment]
Looking forward for this 👍

**Comment by rootzoll** [comment]
for a start I used `https://getalby.com/install/hub/pi-aarch64-install.sh` and translated it into a the template install script:

https://github.com/raspiblitz/raspiblitz/blob/4727-albyhub/home.admin/config.scripts/bonus.albyhub.sh

Its in branch `4727-albyhub` to be tested and further developed:

- [X] test also on x86 systems
- [X] move install dir to home of user `albyhub`
- [X] move data to `/mnt/hdd/app-data/albyhub`
- [X] different port than 80
- [X] make dependend on LND (install & systemd start after)
- [X] add prestart
- [x] set LND node per ENV in prestart
- [x] added to Recover & SSH menus

**Comment by rootzoll** [comment]
OK first PR is ready:  #4848

Next orga TODOs:

- [x] Test PR & squash-commit to `dev` branch
- [x] Fork `v1.11` to `v1.11-albyhub` and cherry-pick PR
- [x] Let users know how to become early-testers

And then finally for v1.12.0 release:

- [x] Remove `(preview)` text
- [x] Add to CHANGES

**Comment by rootzoll** [comment]
AlbyHub is planned to come with RaspiBlitz v1.12.0. For everybody wanting to have **Early-Access to AlbyHub with RaspiBlitz v1.11.3** you can follow this steps:

- go to terminal and use commad "github"
- under "BRANCH" change to "v1.11-albyhub" (OK) 
- restart RaspiBlitz with command "restart"
- when you again in the SSH menu you should find AlbyHub under SERVICES

Please report any feedback, bugs or still missing features/settings here on the GitHub issue.

**Comment by dragsugg** [comment]
Works excellent! Thank you! 😊

**Comment by Kolomona** [comment]
Can this be fast tracked? The Alby-pocalypse is coming soon.

![Screenshot_2024-11-23_12-18-04](https://github.com/user-attachments/assets/bfcceb7b-7345-4325-8142-8161e236c320)

**Comment by adevoss** [comment]
Switched from `dev` branch to `v1.11-albyhub` branch.
Gave me the spinning circle

Reinstall using `v1.11-albyhub` branch. All fine.

**Comment by voidzero** [comment]
I changed the hostname in `/etc/hostname` (and changed it back to `raspberrypi`) and maybe I shouldn't have done that:

![image](https://github.com/user-attachments/assets/ac9e1701-866b-40d3-9983-cba2d9e2c6c3)

@rootzoll any suggestions on how to fix this? I'm comfortable to work on the cli. Just no idea where to look for this.

**Comment by bumi** [comment]
@voidzero in Alby Hub the LND certificate does not get updated if LND changes that one. 
we have an update for this coming that makes sure always the updated data from the env variable is used.

**Comment by voidzero** [comment]
Thanks @bumi, What can I do in the mean time to fix this problem? I've looked all over the place... maybe I need to update some record in the `/mnt/hdd/app-data/albyhub/nwc.db` sqlite db?

**edit** Found it. Here are the steps:

1. get the hex value of the currently active (valid) certificate:
  `xxd -p -c 0 /mnt/hdd/lnd/tls.cert`
2. Edit the albyhub sqlite database:
  `sqlite3 /mnt/hdd/app-data/albyhub/nwc.db`
3. Get the current value of the `LNDCertHex` key in the `user_configs` database just in case you mess things up:
  `select value from user_configs where key = 'LNDCertHex';`
4. replace the value with the output from the first step:
  `update user_configs set value = 'REALLYLONGSTRINGHERE' where key = 'LNDCertHex';`
5. restart albyhub:
  `systemctl restart albyhub`
6. ???
7. Profit!

**Comment by NodeDiver** [comment]
In case this folder or file is empty:  `.../app-data/albyhub/nwc.db` <- this one might be an empty file, check its size.

You might want to try this folder:
`.../app-data/alby-albyhub/data/albyhub/nwc.db`

At least that happens on an Umbrel, I'm not sure how folders are organized on your raspi

**Comment by openoms** [comment]
Small issue:
got this during install
´´´
rm: cannot remove 'albyhub-server.tar.bz2': Permission denied
´´´
Will update with test findings.

Update: smooth sailing on my amd64 server, connected Alby Go and NWC to Amethyst through the Aby webUI, working great.

**Comment by rootzoll** [comment]
> rm: cannot remove 'albyhub-server.tar.bz2': Permission denied

see PR #4866 - that delete has a sudo now

**Comment by steepdawn974** [comment]
Two (stylistic) comments:

1. @bumi I don't see any signature files in your releases. Raspiblitz should generally verify binaries after download before installing them... 
2. Imho there should not be a dependency on LND. AlbyHub could run with the embedded LDK node...

just my 50 sats

**Comment by rootzoll** [comment]
@steepdawn974 I think it makes sense to offer AlbyHub on LND with RaspiBlitz - its a Full-Node and LND is one of its base Lightning implementations it provides (and people might already have channels with) - AlbyHub is an extension of the things you can then do with your LND.

To base AlbyHub on LDK would just make sense if it would be a genreal third Lightning Implementation on RaspiBlitz that you can choose on install, uses the local Bitcoin Core and can also provide services to other Apps in RaspiBlitz .. but I dont think thats the focus here and a too big of a change/task. 

If you really just want a lightweight AlbyHub with LDK you might not need all the Fullnode complexity of RaspiBlitz and possibly just install it plain on a RaspberryPi Zero: https://guides.getalby.com/user-guide/alby-account-and-browser-extension/hidden-archives/raspberry-pi-zero

**Comment by bumi** [comment]
@steepdawn974 yes, important actually. and now that we are a bit more stable and have regular releases we need to add this. We'll make sure to have this with the next release

**Comment by steepdawn974** [comment]
> @steepdawn974 I think it makes sense to offer AlbyHub on LND with RaspiBlitz - its a Full-Node and LND is one of its base Lightning implementations it provides (and people might already have channels with) - AlbyHub is an extension of the things you can then do with your LND.

@rootzoll 
Fair enough on the LDK node part.

However, since people are running with CLN instead of LND, it would be better if the installer detected which one is running and/or asked the user which Lightning implementation they want as a backend to AlbyHub.

**Comment by rootzoll** [comment]
> However, since people are running with CLN instead of LND, it would be better if the installer detected which one is running and/or asked the user which Lightning implementation they want as a backend to AlbyHub.

@steepdawn974  RaspiBlitz is able to run CLN & LND at the same time (only possible when managed by SSH menus) .. so if you run CLN and want to use AlbyHub you can activate LND first and then have AlbyHub available.

I know its not perfect, but I really dont want another Lightningnode just running "on the side managed only by an bonus app" on RaspiBlitz - this will introduce confusion on multiple levels. Like why is my Screen not showing my balance why were funds not backuped with my seed, etc ... @bumi best would be if AlbyHub also would support Core Lightning

**Comment by bumi** [comment]
CLN support has been requested, but if nobody contributes it we don't have it on the roadmap, supporting more nodes means much more complexity to handle. We try to support LND as it's mostly adopted and optimize for simplicity with the embedded LDK.

**Comment by steepdawn974** [comment]
@bumi I thought it is already supported, but mixed it up with the Alby Extension (where CLN is supported) .. sorry.

**Comment by rootzoll** [comment]
OK we have a RaspiBlitz v1.11.4 Release Candidate with AlbyHUb (SSH & WebUI) for you to test .. any feedback over the weekend would be great: https://github.com/raspiblitz/raspiblitz/blob/v1.11/CHANGES.md#whats-new-in-version-1114-of-raspiblitz

**Comment by tcmilleriii** [comment]
New here but hardware for my raspiblitz is en-route and I’d so love to get Alby Hub up and running with it!

**Comment by rootzoll** [comment]
OK RaspiBlitz v1.11.4 with AlbyHub just got released: https://x.com/rootzoll/status/1871612490716688759

**Comment by MoritzKa** [comment]
Thanks for publishing Alby Hub. Super cool!!!

Just two questions regarding updates:
- How are new Alby Hub versions made available on the WebUI? Does the Alby team need to do anything in particular?
- Will users find a button on their WebUI if another Hub update is available? 

I think about writing a post on blog.getalby.com.

**Comment by rootzoll** [comment]
> Thanks for publishing Alby Hub. Super cool!!!

:) Thx .. Alby Hub is a great functional & educational tool for lightning. Happy to have it on the RaspiBlitz

> How are new Alby Hub versions made available on the WebUI? Does the Alby team need to do anything in particular? Will users find a button on their WebUI if another Hub update is available?

So far there is no special update mechanism for AlbyHub. It will basically be our default way that when we do a new RaspiBlitz Release we will ship also updated versions of our bonus apps - like AlbyHub.

It would be great if you @MoritzKa or somebody from the AlbyHub team - when you release a new version of AlbyHub already open an issue on RaspiBlitz repo - letting us know about the new release and if there are any possible needed changes/migrations compared to the existing version (changes in config, setup process, database migrations, ...). Then we can add this to our next milestone planning.

Also signed releases would be great for security in the future .. if you will have multiple people signing (e.g. in rotation) it would be good to know all of the possible valid signers so our install script will not fail if we hit an unknown signer. New, updated or removed signers can be announced in github issue about new release.

Beside from that it would be great to have one named contact (github account name) that we can reffer in issues if a user comes with error reports to support us in figuring out if its on the RaspiBlitz or AlbyHube side and point into the right direction. Would then add that contact to the install script.
