### ISSUE TITLE
Can't even setup the OS

### ISSUE THREAD

**Issue by wolfieboy09** [raspiblitz/raspiblitz#4741]
**Describe the bug**
When I turn the pi on to set it up for the first time, it fails. I had to create a `wpa_supplicant.conf` and the `ssh` file

**To Reproduce**
No idea

**Debug file**
N/A
I use PuTTY, and this is after it shutdown
![image](https://github.com/user-attachments/assets/d8f5a02d-e456-4ca9-8cf1-5ccdc5686d6a)

**Comment by cstenglein** [comment]
Looks like the wifi config is wrong.

**Comment by rootzoll** [comment]
@wolfieboy09 see FAQ section about Wifi config: https://docs.raspiblitz.org/docs/faq#is-it-possible-to-connect-the-blitz-over-wifi-instead-of-using-a-lan-cable

**Comment by cstenglein** [comment]
Closed for now - if it still appears please re-opem :)
