### ISSUE TITLE
[RPi5] + Boot from NVMe/without SD card - Update without reflashing

### ISSUE THREAD

**Issue by AnathosN** [raspiblitz/raspiblitz#4742]
Hi,

a while back when the RPi5 hit the market, I decided to enhance my RaspiBlitz and run the OS from an NVMe SSD instead of the SD card, as I experienced several broken SD cards and upgrading issues with the SD card over the last years.

To do so I activated the normal upgrade process, but flashed the new version onto the SSD directly with an USB Adapter instead of flashing it to an SD card. I had boot from PCIe activated with a boot stick and then installed the preflashed SSD with an NVMe shield using the PCIe connection.

I kept my Data disk - 2x 2TB SSD in an icybox raid case connected via USB3.

Everything works fine so far, the normal updates run from the menu. In think I had to reinstall LNBits because it wouldn't start initially but the rest worked out of the box afaik.

Now I would like to migrate to one of the new major releases (I think I am still on 1.10) and the obvious option would be to start the migration normally, remove the SSD, make a backup image, flash it with the new version and reinstall it and hope everything just boots up fine.

However I asked myself, if there is a way to update to a major release without reflashing. Is there a way or a script to just install all the updates while the system is running?

This would make live much easier for me. :)

**Comment by rootzoll** [comment]
Hi. 

> Now I would like to migrate to one of the new major releases (I think I am still on 1.10) and the obvious option would be to start the migration normally, remove the SSD, make a backup image, flash it with the new version and reinstall it and hope everything just boots up fine.

That would also be my best guess - you would need todo so for the next versions until v1.12.0. The goal for that version is to support boot from NVMe by default. How we will do this exactly is still in research - but it will be a standariized process. You will be able to follow the development here: #4324 

I am closing this issue.
