### ISSUE TITLE
question about opening a custom channel

### ISSUE THREAD

**Issue by coinicarus** [raspiblitz/raspiblitz#475]
I am attempting to register my node with 1ml.com - i noticed i can only open channels with connected peers, is there no way to do custom channels yet? just wondering. 
thank you!

**Comment by openoms** [comment]
@coinicarus use the [CONNECT] Connect to a peer menu item on RaspiBlitz to add the node you want to open a channel with (1ML in this case).

**Comment by coinicarus** [comment]
> @coinicarus use the [CONNECT] Connect to a peer menu item on RaspiBlitz to add the node you want to open a channel with (1ML in this case).

thank you! i will try this now :)

**Comment by coinicarus** [comment]
thank you! my confusion was the peers, im all set thank you again :)
