### ISSUE TITLE
Zap wallet connection issue 

### ISSUE THREAD

**Issue by walletofsatoshi** [raspiblitz/raspiblitz#476]
Still having issue connecting zapwallet to raspiblitz 1.1

Error connecting to server. It worked well in the initial version 0.9 but not working with newer versions 1 and 1.1

**Comment by openoms** [comment]
do you have the port 10009 forwarded on your router?

**Comment by walletofsatoshi** [comment]
This was not needed in v0.9 since I am accessing from LAN so no I have not

**Comment by openoms** [comment]
Try running this filling your LAN IP:
`lndconnect  --host=your.RaspiBlitz.LAN.IP`

**Comment by openoms** [comment]
BTW you can connect to the new v0.4 Zap desktop, by adding the `-j` option:
`lndconnect -j --host=your.RaspiBlitz.LAN.IP`

**Comment by walletofsatoshi** [comment]
So it worked with port forwarding and going reckless thanks
