### ISSUE TITLE
API Whishlist

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#4771]
https://github.com/fusion44/blitz_api/pull/272
https://github.com/fusion44/blitz_api/pull/270

**Comment by rootzoll** [comment]
@fusion44 will you be able to get those two PR checked & merged (`dev` & `blitz-v1.11` branch) so I can target a RaspiBlitz v1.11.3rc1 build for the weekend?

**Comment by fusion44** [comment]
Both of the PR's are merged and synced to the branch Blitz-v1.11
