### ISSUE TITLE
gRPC Settings

### ISSUE THREAD

**Issue by bvolution** [raspiblitz/raspiblitz#4798]
**Describe the bug**
I am observing some strange behavior after I ran `sudo apt-get update && sudo apt-get upgrade -y`
I am currently not able to login into lndg, which fails with the following error message:
```sh
An error has occured!
LNDg cannot reach the gRPC for LND. Make sure LND is running and/or your gRPC settings are correct.
```

**Question**
How / where can I check the gRPC settings? I noticed that during the sys update / upgrade I was asked about `/etc/pam.d`, if this should be overwritten, I chose no, as I was unsure if this is going to hurt my system. How could I fix gRPC if I broke it somehow?

In the lnd.conf I could not identify something strange, this should be as expected

```
rpcmiddleware.enable=true
rpclisten=0.0.0.0:10009
bitcoind.rpchost=127.0.0.1:8332
```

**Comment by rootzoll** [comment]
Best would be to have a debug log to check the state of your system after the upgrade: https://docs.raspiblitz.org/docs/faq#debug

**Comment by bvolution** [comment]
I tried in the meantime uninstalling and reinstalling from the menu. Here is the debug. Ty rootzoll 
https://termbin.com/xidj

I will now try a plain restart of the raspiblitz. I call out a tiny bouty of 2.100 sats if one can help me get lndg to run again.

**Comment by bvolution** [comment]
I am sorry, to have bothered you.... restart did fix it.
