### ISSUE TITLE
APP btc-rpc-explorer - howto use "local only" without TOR

### ISSUE THREAD

**Issue by HannesMC** [raspiblitz/raspiblitz#4816]
Hello,

my case did not match the default issues.

`Raspiblitz v1.11.2
Bitcoin Fullnode + Lightning Network + Tor
`
If i install btc-rpc-explorer, its installed with TOR Access.
- Is it possible to disable TOR for this App? I just want to use it locally without Tor. 
- My second question is about the default configuration of btc-rpc-explorer after installation. I tested it with an 2nd device with TOR. I think the system tells too much about itself. The simple implementation and the easy installation is top. In the worst case, a simple installation can lead to software being used as it was installed. Anyone who wants to activate more features and is a professional will already know how to do this. 

thx for your great work and keep on.

**Comment by rootzoll** [comment]
There is no option to switch Tor off for just a single service at the moment ... but you can switch tor off completly with SSMENU > SETTINGS > "Run behind Tor" to OFF.
