### ISSUE TITLE
IDEA: Price indicator on display

### ISSUE THREAD

**Issue by WetPuppyKisses** [raspiblitz/raspiblitz#482]
This may be not strictly an issue but I would like some help to add the Bitcoin price in dollars on the display of the RaspiBlitz (Once fully synced)

I am not expert on bash programming, but I took as reference the following:

https://github.com/84adam/wink.sh/blob/master/wink.sh
https://github.com/8go/coinbash

The ideal would be that the price is automatically updated every 15 minutes or so.

**Comment by rootzoll** [comment]
In the mid term we will change from the LCD ASCII mode to the LCD graphics mode with maybe even more info. This could be part of that.

**Comment by nyxnor** [comment]
please close this. @raulcano started this, but now maybe the lcd wont work. Also, webui will solve this much easier.
