### ISSUE TITLE
CLN peers are counted as channels in cl.monitor.sh

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#4834]
Recovering with a 0 channel CLN node as default this screen does not go away.
![image](https://github.com/user-attachments/assets/40494cfe-0a72-4d21-829f-e4ba1692c3ca)
The webui loads ok.

goes away to the menu when I add a peer to CLN, but then it shows as having a channel 
![image](https://github.com/user-attachments/assets/201bb109-930e-4fab-aa11-efacd2238655)

**Comment by rootzoll** [comment]
PR #4846 to fix submitted. Should be merged into `v1.11` (as a after-release hot patch) and then also cherry-picked over to `dev` for v1.12.0 release.
