### ISSUE TITLE
RTL for CLN did not work. 

### ISSUE THREAD

**Issue by neversleep404** [raspiblitz/raspiblitz#4839]
Updated from 1.11.1 to 1.11.3 first with MINIMAL SD Card Image then with FATPACK. Same Error with RTL. CPU Load is 5.51.
What could I do?

![Bildschirmfoto 2024-11-09 um 10 39 59](https://github.com/user-attachments/assets/1cbff0cc-4cc3-4007-904a-4cd9bc324cbb)
![Bildschirmfoto 2024-11-09 um 10 45 59](https://github.com/user-attachments/assets/2ec0ab7a-a801-41d8-acd1-b4776ccf79e4)

**Comment by neversleep404** [comment]
With a disabled RTL, the load is at 2.71

**Comment by rootzoll** [comment]
I tested an update/recover with CLN & RTL on a RP4 .. and I was not able to reproduce this so far.

**Comment by aquilafedele** [comment]
I have the same error.
Updated from 1.11.2 to 1.11.3, removed RTL, reinstalled RTL and got the same error.
Let me know how I can help providing more details!

**Comment by neversleep404** [comment]
It is not so important for me. I have issues since last year. I think I make a payout of my Satoshi and wait for Version 1.12 to start with a clean wallet and a new installation.

**Comment by neversleep404** [comment]
without RTL it works perfect

**Comment by rootzoll** [comment]
> I have the same error.
> Updated from 1.11.2 to 1.11.3, removed RTL, reinstalled RTL and got the same error.
> Let me know how I can help providing more details!

@openoms can you take a loook?

**Comment by Hagbard89** [comment]
same issue here, let me know if you need further informations

**Comment by openoms** [comment]
Did not come accross the problem so far
![image](https://github.com/user-attachments/assets/de7eb7d1-f8e6-402a-8f19-9be498ed3faf)

Can you please test and paste the errors here when running:
```
sudo -u rtl sh -c " export RTL_CONFIG_PATH=/mnt/hdd/app-data/rtl/cRTL/; /usr/bin/node /home/rtl/RTL/rtl"
```

Downgrading CLN to 24.08.1 to test, but you can also try upgrading CLN from the update menu to the latest release to fix.

**Comment by Hagbard89** [comment]
im getting :  ERROR: RTL => http://localhost:7000 is already in use. 
Is it save to update to 24.11? i'm on 24.08.1-modded. what can i do to use a other port?

**Comment by rootzoll** [comment]
@Hagbard89 can you post the result of:
```
sudo netstat -tuln | grep 7000
```

And check if its diffenetent when you deinstall RTL for CLN?

**Comment by Hagbard89** [comment]
tcp6       0      0 :::7000                 :::*                    LISTEN
with CRTL deinstalled there's no output

**Comment by openoms** [comment]
Downgraded CLN , works with that too.
![image](https://github.com/user-attachments/assets/fb313927-5ffa-422c-b91f-da52d3640be1)
Will try a fresh install next.

**Comment by openoms** [comment]
you can try removing RTL entirely with the command:
```
config,scripts/bonus.rtl.sh off cl mainnet purge 
```
then reinstall it.

@Hagbard89 please post the exact error you are having either in the logs or on screen.

**Comment by Hagbard89** [comment]
this fixed it! CRTL is now showing all values correctly, no errors during uninstall and reinstall. Thank you very much!
