### ISSUE TITLE
Mobile Wallet Connection Improvements

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#484]
On next release test again the mobile wallet connection processes. Had some issue with latest shango download in local network and also recheck issues like tose ones:
https://github.com/rootzoll/raspiblitz/issues/476
https://github.com/rootzoll/raspiblitz/issues/393

Also if possible copy over the LCD display QR code ... the QR code zoom in/out is really a pain.

**Comment by rootzoll** [comment]
Check and replace forwarded ports and domains for QRcode info.
take the info from the raspiblitz.conf sshtunnel info

**Comment by openoms** [comment]
Noting that Shango was last updated in 2018 Dec 8 and still early access release.

**Comment by rootzoll** [comment]
I will keep Shango as a option for now, but Zeus ist now also part of the list.

**Comment by rootzoll** [comment]
OK Wallet connection looks good so far for v1.2 - closing issue.
