### ISSUE TITLE
Forwarding Ports by autossh Tunnel

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#485]
A method for people that are behind a NAT and cannot change that to make ports public by a ssh reverse tunnel using a public sshd server.

**Comment by cryptomulde** [comment]
noice!

**Comment by rootzoll** [comment]
DONE: test port forwarding of LND 9735
DONE: test with more then 3 forwardings
DONE: check if working after updated (in combination with mobile wallet)

**Comment by rootzoll** [comment]
See FAQ: How to setup port-forwarding with a SSH tunnel?

**Comment by rootzoll** [comment]
OK. Its working for v1.2. Closing issue.

**Comment by frennkie** [comment]
I'm having issues with this. See #1194 

This does not survive a DSL reconnect with a changed IP.

```
ExecStart=/usr/bin/autossh -M 0 -N -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=2 [PLACEHOLDER]
```

This does:

```
ExecStart=/usr/bin/autossh -M 20000 -N -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=2 [PLACEHOLDER]
```

**Comment by rootzoll** [comment]
- [x] before ports add an optional parameter for m ... for example "--m:20000"

**Comment by rootzoll** [comment]
@frennkie ok this is implemented and merged into v1.6 & dev ... let me know if this fixes it for you

**Comment by rootzoll** [comment]
tested: on recovery the `sudo cat /etc/systemd/system/autossh-tunnel.service` shows that it regenerates the optional monitoring parameter in the service file

**Comment by rootzoll** [comment]
OK. Closing this for the v1.6.1 release.
