### ISSUE TITLE
After `build_sdcard.sh` finishes in VM, no initialisation happens in terminal

### ISSUE THREAD

**Issue by woiwoiwoiwoi** [raspiblitz/raspiblitz#4850]
I ran 1.11.1 or 1.11.2 before on Debian 12.6.0 via virt-manager on Opensuse Tumbleweed. Worked really well (except for one hiccup in the script). Now I'm trying a fresh install and can't get it to work.

First try:

1. Debian 12.8.0 netinst on Opensuse Tumbleweed in virt-manager. I tried 12.6.0 netinst afterwards, same result.
2. run `build_sdcard.sh`, minimal, no errors noticed
3. shutdown, add second disk, reboot
4. log in as admin, launch terminal (in Gnome)
5. all I get is this:
```
Starting SSH user interface ... (please wait)
***********************************************************
Stop signal detectecd - OK ready for manual provision.
If your ready for shutdown use the following command:
release --> for an official release
release -quick --> during development
REMOVE AUDIO DEVICE from VM before next boot up.
***********************************************************
```

Second try:

1. I decided to try a ready made image for amd64 for the first time
2. EDIT: tried `raspiblitz-amd64-image-2024-10-28-45df8b3 ` and `raspiblitz-amd64-image-2024-09-14-33d826b`
3. UEFI images don't work for me, I tried with and without SecureBoot
4. Legacy image `raspiblitz-amd64-image-2024-10-28-45df8b3 ` works, but I end up at the same screen as above:
```
Starting SSH user interface ... (please wait)
***********************************************************
Stop signal detectecd - OK ready for manual provision.
If your ready for shutdown use the following command:
release --> for an official release
release -quick --> during development
REMOVE AUDIO DEVICE from VM before next boot up.
***********************************************************
```

What can I try to do to fix this?

**Comment by woiwoiwoiwoi** [comment]
Just noticed that if I log in with the original user that was created during Debian install, I get the message:

` Starting Raspiblitz v1.11.3...`

and then:

`VM stopped for manual provisioning`

and then I'm logged out.

**Comment by rootzoll** [comment]
`REMOVE AUDIO DEVICE from VM before next boot up.`

Virtual Machines should have no audio-device .. can you check in your setup?

Background: "manual provisioning" is needed for development and I needed an outside "flag" to trigger it. I choose "audio device" because its not needed and does not come by default with VMs under proxmox. It could be that "virt-manager on Opensuse" is adding a audio device by default. 

Maybe I can improve this by ignoring that one special audio-device that "virt-manager" uses .. can you post me the output of the following command before you remove the audio-device: `lspci`

**Comment by woiwoiwoiwoi** [comment]
Fantastic, that was it, thank you! Have I mentioned I love this project and all of you? :-)

Here's the output:
```
lspci
00:00.0 Host bridge: Intel Corporation 82G33/G31/P35/P31 Express DRAM Controller
00:01.0 VGA compatible controller: Red Hat, Inc. Virtio 1.0 GPU (rev 01)
00:02.0 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:02.1 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:02.2 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:02.3 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:02.4 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:02.5 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:02.6 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:02.7 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:03.0 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:03.1 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:03.2 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:03.3 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:03.4 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:03.5 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:1b.0 Audio device: Intel Corporation 82801I (ICH9 Family) HD Audio Controller (rev 03)
00:1f.0 ISA bridge: Intel Corporation 82801IB (ICH9) LPC Interface Controller (rev 02)
00:1f.2 SATA controller: Intel Corporation 82801IR/IO/IH (ICH9R/DO/DH) 6 port SATA Controller [AHCI mode] (rev 02)
00:1f.3 SMBus: Intel Corporation 82801I (ICH9 Family) SMBus Controller (rev 02)
01:00.0 Ethernet controller: Red Hat, Inc. Virtio 1.0 network device (rev 01)
02:00.0 USB controller: Red Hat, Inc. QEMU XHCI Host Controller (rev 01)
03:00.0 Communication controller: Red Hat, Inc. Virtio 1.0 console (rev 01)
04:00.0 SCSI storage controller: Red Hat, Inc. Virtio 1.0 block device (rev 01)
05:00.0 Unclassified device [00ff]: Red Hat, Inc. Virtio 1.0 memory balloon (rev 01)
06:00.0 Unclassified device [00ff]: Red Hat, Inc. Virtio 1.0 RNG (rev 01)
07:00.0 SCSI storage controller: Red Hat, Inc. Virtio 1.0 SCSI (rev 01)
08:00.0 SCSI storage controller: Red Hat, Inc. Virtio 1.0 block device (rev 01)
```

Would you recommend using something else than virt-manager? VMs are not my specialty and I thought virt-manager is kind of a standard.

**Comment by woiwoiwoiwoi** [comment]
Ah and regarding the ready made UEFI images not working for me: is there something I could try to fix this? The VM I set up from scratch using Debian and then running the script works just fine as UEFI.

The BIOS version should work just fine, I guess? But I don't know how long you'll keep providing the legacy builds.

**Comment by rootzoll** [comment]
OK this are all Audio devcies that can be set thru Proxmox:

```
03:0c.0 Audio device: Intel Corporation 82801I (ICH9 Family) HD Audio Controller (rev 03)
03:0c.0 Audio device: Intel Corporation 82801FB/FBM/FR/FW/FRW (ICH6 Family) High Definition Audio Controller (rev 01)
03:0c.0 Multimedia audio controller: Intel Corporation 82801AA AC'97 Audio Controller (rev 01)
```

```
00:1b.0 Audio device: Intel Corporation 82801I (ICH9 Family) HD Audio Controller (rev 03)
```

So it seems that the default VirtManager Audio devcie is the same that can set by Proxmox and we cannot make a special case out of it.

**Comment by rootzoll** [comment]
> regarding the ready made UEFI images 

Thats something for the future to improve - give us some more updates to work on it.

**Comment by woiwoiwoiwoi** [comment]
> So it seems that the default VirtManager Audio devcie is the same that can set by Proxmox and we cannot make a special case out of it.

I've played around with this a little bit now, maybe that's interesting to you. The same three devices are offered in my case, the default one is the mentioned one. However, on my system, only the third one seems to work.

I've disabled audio now, as recommended, the Raspiblitz does not need it anyway. But I do actually use audio on two different VMs (using the AC'97 Audio Controller).

> Thats something for the future to improve - give us some more updates to work on it.

Fantastic, thanks again for all your work!

**Comment by woiwoiwoiwoi** [comment]
Hey, just ran the script for the first time since, to install 1.11.4, and the issue persists. Did you mean to remove the audio device requirement or is it intended to stay that way? I'm fine either way, but other people might stumble over this as well.

**Comment by rootzoll** [comment]
Yeah I will check if I can further trim it down to one special audio devcie on Proxmox and not audio in general.
