### ISSUE TITLE
Updating lnd and bitcoind

### ISSUE THREAD

**Issue by benthecarman** [raspiblitz/raspiblitz#488]
Is it possible to update lnd and bitcoind by doing a `make install` of the repos?  Otherwise would we need to wait for raspiblitz to be updated to get the updated versions of lnd and bitcoind.

Thanks

**Comment by openoms** [comment]
This can give you some clues: https://github.com/Stadicus/guides/blob/master/raspibolt/raspibolt_faq.md#how-to-upgrade-bitcoin-core
You can do anything with the RaspiBlitz as it is 100% open source.
