### ISSUE TITLE
SSH-Option "Close All Channels" - Try cooperative close first

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#4884]
The "Close All Channels" option in den SSH menus calls the script: 
https://github.com/raspiblitz/raspiblitz/blob/dev/home.admin/BBcloseAllChannels.sh

But it just does a "force close" .. to try/offer a "Cooperative Close" first would be more economic aof course.

**Comment by rootzoll** [comment]
@TrezorHannes  Tested the merged PR .. looks like if I choose "Cooperative Close" it will still ask on every channel point if I want to close Unilaterally (forced closed) - see:
 
![Bildschirmfoto 2024-12-18 um 23 57 14](https://github.com/user-attachments/assets/e14f1d8d-178f-4bc7-aa33-196e889ddcd1)

So depending on state of channels (active, etc) it might ask for different things.

**Comment by TrezorHannes** [comment]
@rootzoll Oh no, just figured `--force` has a different purpose in `closechannel` vs `closeallchannels`.

I will need to get back to the drawing board. There are two options to consider:
```
lncli closeallchannels
   --force                  ask for confirmation once before attempting to close existing channels
   -s, --skip_confirmation  Skip the confirmation prompt and close all channels immediately
```
So `force` is not even force-closing, it'll just ask for confirmation once, and then closing all: active as coop, inactive as force-close.
`skip_confirmation` does what it says, no confirmation needed at all and closes all immediately.

I'm pondering whether we should revert the PR, the original script does what it should do, my apologies. 
Wdyt?

**Comment by rootzoll** [comment]
Yes I reverted back to the old script for now. It was quite some years back since I implemented it and not often testing it, so the details were also not present at my side. This was a good refresher.
