### ISSUE TITLE
Stopped for manual provision while no audio device in Proxmox VM

### ISSUE THREAD

**Issue by adevoss** [raspiblitz/raspiblitz#4899]
After fresh install of Debian 12 and executing build_sdcard (`dev` branch) with option `-b v1.11-albyhub` the script finishes with the message:
REMOVE AUDIO DEVICE from VM before next boot up.

The VM configuration has no audio device (see image)
![RaspiblitzVMconfig](https://github.com/user-attachments/assets/db9314d5-d661-4d14-9ea0-faa43d3d088c)

How do I manual provision?

**Comment by rootzoll** [comment]
hmm .. this is normally just a trick for developers .. you have really no audio device added, strange.

Can you post here the result of command `lspci` from your booted up terminal?

**Comment by adevoss** [comment]
There is an audio device ???? Didn't expect that.
`00:1b.0 Audio device: Intel Corporation 82801I (ICH9 Family) HD Audio Controller (rev 03)`
That's a question for the Proxmox forum then.

What script starts provisioning?

**Comment by adevoss** [comment]
Not a Raspiblitz issue.
From the Proxmox forum: Machine `q35` has an audio device.

So I switched to default (`i440fx`). That has no audio device.
Now provisioning.

So if you use a VM (not Proxmox specific) doublecheck when installing if the VM has an audio device (`lspci`)
