### ISSUE TITLE
Loop of LND Unlock, Filtering Blockchain

### ISSUE THREAD

**Issue by wuestenigel** [raspiblitz/raspiblitz#494]
Hey guys,

I'm struggling for some months about one problem:

Whenever I want to do some stuff in the main menu (like transferring my onchain funds), I'm prompeted to insert my LND password. After that, some strange block filtering starts with 570323/570323 and wait and inserting LND password again and again and again.
*SOMETIMES* after  this, I may get back to the main menu and I can select an option. But then everything starts again.

What I already did:
- upgraded from 0.9 to 1.0 and waited about 5 weeks to verify
- upgraded from 1.0 to 1.0
- replaced power supply with the recommended one from the main post about raspiblitz
- tried some commands from #292 

I'm totally lost. I only want my device running and maybe have some fun with Joule, Zap and connect to my Casa node.

Thank you so much guys for any kind of help

<img width="566" alt="Bildschirmfoto 2019-04-05 um 15 37 51" src="https://user-images.githubusercontent.com/17941907/55631988-93198400-57b9-11e9-9ea4-943c3c7a73aa.png">
<img width="1380" alt="Bildschirmfoto 2019-04-05 um 15 37 35" src="https://user-images.githubusercontent.com/17941907/55631989-93198400-57b9-11e9-9e7c-c73bc8a398d9.png">
<img width="506" alt="Bildschirmfoto 2019-04-05 um 15 37 19" src="https://user-images.githubusercontent.com/17941907/55631990-93198400-57b9-11e9-94fd-ebc685d8eed5.png">
<img width="434" alt="Bildschirmfoto 2019-04-05 um 15 37 09" src="https://user-images.githubusercontent.com/17941907/55631991-93b21a80-57b9-11e9-820e-34fa5c6dfea9.png">

**Comment by rootzoll** [comment]
A Unlock-Loop is happening, when LND is crashing and the RaspiBlitz tries to start it up again. On every re-startup after a crash, you are asked to unlock your wallet again.

The question is why LND is crashing. If we look at the logs you posted (under LND Error Logs), there is "LND panic invalid page type 13434: 10" and last normal log around that time was "syncing channel graph" that seems to be the reason. But I have no idea what that is. That seems to be a LND problem. So it would be best to ask at the LND Dev Slack or GitHub for more details: https://dev.lightning.community

Possibly related LND GitHub issues could be those: https://github.com/LightningNetwork/lnd/issues?utf8=%E2%9C%93&q=is%3Aissue+panic+sync+channel+graph

But we are preparing the new RaspiBlitz v1.2 release which will have the new LND 0.60 on board (once the final release is out). There is a change that this is fixed than, but thats not 100%.

**Comment by wuestenigel** [comment]
Thanks, I'm patient to the next cool versions of raspiblitz.

 Is there at least a way to load my funds from the Wallet? (they are onchain, not LND)

**Comment by fluidvoice** [comment]
> A Unlock-Loop is happening, when LND is crashing and the RaspiBlitz tries to start it up again. On every re-startup after a crash, you are asked to unlock your wallet again.
> 
> The question is why LND is crashing. If we look at the logs you posted (under LND Error Logs), there is "LND panic invalid page type 13434: 10" and last normal log around that time was "syncing channel graph" that seems to be the reason. But I have no idea what that is. That seems to be a LND problem. So it would be best to ask at the LND Dev Slack or GitHub for more details: https://dev.lightning.community
> 
> Possibly related LND GitHub issues could be those: https://github.com/LightningNetwork/lnd/issues?utf8=%E2%9C%93&q=is%3Aissue+panic+sync+channel+graph
> 
> But we are preparing the new RaspiBlitz v1.2 release which will have the new LND 0.60 on board (once the final release is out). There is a change that this is fixed than, but thats not 100%.

A similar LND "invalid page type" panic was reported here: https://github.com/lightningnetwork/lnd/issues/2626
And @Roasbeef said 

> "Looks like rasp pi disk corruption."

So you might want to try testing your power supply to make sure it's adequate, and perhaps buy a better new SD card and burn it and start anew.  Which exact power supply and SD card are you using?

To **run the power supply test script** (all in one line):
`wget https://raw.githubusercontent.com/rootzoll/raspiblitz/4abbdd18aa0ec44553d1fd875f2c5a6b98d9721c/home.admin/config.scripts/blitz.powertest.sh && sudo chmod +x blitz.powertest.sh && ./blitz.powertest.sh`

if that one fails to run try this one:

`wget https://raw.githubusercontent.com/openoms/raspiblitz/powertest/home.admin/XXpowertest.sh && sudo chmod +x XXpowertest.sh && ./XXpowertest.sh`

If you have consistent voltage above 1.25V then probably your problem is the SD card.
The best quality SD card is probably the **Samsung PRO Endurance 32GB** listed in the shopping list.

**Comment by wuestenigel** [comment]
Hey,
I'm in the loop again after upgrading to v1.2

<img width="1302" alt="Bildschirmfoto 2019-05-04 um 15 03 06" src="https://user-images.githubusercontent.com/17941907/57179402-e137ab00-6e7d-11e9-9931-c39f666fda21.png">
<img width="1169" alt="Bildschirmfoto 2019-05-04 um 15 03 01" src="https://user-images.githubusercontent.com/17941907/57179403-e137ab00-6e7d-11e9-9195-1fa5d9268043.png">
<img width="1351" alt="Bildschirmfoto 2019-05-04 um 15 02 13" src="https://user-images.githubusercontent.com/17941907/57179404-e137ab00-6e7d-11e9-8b10-cd2a8af6c2a7.png">


Any ideas how I can fix this? Is there any way to release my 0.05 BTC (onchain)?

**Comment by fluidvoice** [comment]
Please provide links to these full logs.
raspiblitz: `sudo /home/admin/XXdebugLogs.sh | nc termbin.com 9999`
syslog: `sudo cat /var/log/syslog | nc termbin.com 9999`
bitcoind: `sudo cat /mnt/hdd/bitcoin/debug.log | nc termbin.com 9999`
lnd: `sudo cat /mnt/hdd/lnd/logs/bitcoin/mainnet/lnd.log | nc termbin.com 9999`

**Comment by fluidvoice** [comment]
In the meantime there is a recent LND release in the past 24 hours that has some bug fixes. So perhaps we can apply it and see if it fixes things for you?  Most unusual in your logs is that "**panic: invalid page type**".
https://github.com/lightningnetwork/lnd/releases/tag/v0.6.1-beta-rc1
edit: ack! just saw it requires building. So not easy.
Lets see the links to those full logs and maybe report this in an LND issue.

**Comment by wuestenigel** [comment]
@fluidvoice thanks!

raspiblitz: https://termbin.com/l68f
syslog: https://termbin.com/ec8e
bitcoind: https://termbin.com/6xt4
lnd: https://termbin.com/pwwu

**Comment by fluidvoice** [comment]
@wuestenigel I would try burning the SD card and trying again to see if the problem is reproducible or perhaps something bad on disk.

**Comment by wuestenigel** [comment]
@fluidvoice Thanks for the idea. I'm struggling with this for months since v0.9.

Completely changed my power supply and SD Card and flashed it like 10x times.

I just want to release my funds so I'm safe and may start from scratch again. :/

**Comment by fluidvoice** [comment]
> @fluidvoice Thanks for the idea. I'm struggling with this for months since v0.9.
> 
> Completely changed my power supply and SD Card and flashed it like 10x times.
> 
> I just want to release my funds so I'm safe and may start from scratch again. :/

Oh, I didn't realize this was the same problem (lnd panic) as before. I didn't read the comments above.  Very strange as nobody else is seeing this.  Sad this problem persists for so long for you.  My guess would be something corrupted on disk that LND reads.  I would go through the wallet backup procedures, install from scratch, then restore your wallet.

**Comment by fluidvoice** [comment]
> @fluidvoice Thanks for the idea. I'm struggling with this for months since v0.9.
> 
> Completely changed my power supply and SD Card and flashed it like 10x times.
> 
> I just want to release my funds so I'm safe and may start from scratch again. :/

@wuestenigel A LND dev said about your issue **"it seems like you've encountered database corruption."**  This could be why you continue to see this problem no matter how many times you upgrade or burn the SD card - because the database is not on the SD card but on your HDD.
Best thing is prob to backup your wallet, reinstall everything from scratch, and restore your wallet.

**Comment by wuestenigel** [comment]
@fluidvoice Thanks for your help. Problem is this may take another weeks or months(!!!) to download the data again. I had this experience already.

Do you know if it may be ok to delete everything without the blockchain data?

**Comment by fluidvoice** [comment]
> @fluidvoice Thanks for your help. Problem is this may take another weeks or months(!!!) to download the data again. I had this experience already.
> 
> Do you know if it may be ok to delete everything without the blockchain data?

You could try it.  Delete only the LND data (**/mnt/hdd/lnd**) and burn a new SD card, while keeping the blockchain data (**/mnt/hdd/bitcoin**).  It might work but might not. I'd prob try it...  

`sudo systemctl stop lnd.service`
`sudo systemctl stop bitcoind.service`
[edit: see my below post]`sudo rm -rf /mnt/hdd/lnd`
`sudo shutdown now`
now burn new SD card and reinstall.
then perhaps see if you can restore your wallet as per the FAQ directions.

btw, I too got frustrated with delays in downloading/syncing the blockchain so now I made a 2nd copy as a backup on an old spare 500GB 3.5" HDD.  No more weeks of downloading for me!

**Comment by fluidvoice** [comment]
wait...  instead of deleting the LND folder () just rename it...
ie, instead of this line in my post above:
`sudo rm -rf /mnt/hdd/lnd`
do this one instead to move (mv) it - rename it to "**lnd.old**" :
`sudo mv /mnt/hdd/lnd /mnt/hdd/lnd.old`

**Comment by fluidvoice** [comment]
it doesn't work by default that way. I tried it.  You cannot remove the entire directory.  Let me see how to remove only the data portion of that directory.

**Comment by wuestenigel** [comment]
Hey @fluidvoice,

great. Should I rename now or just wait until you experimented a little bit?

Very much appreciated!

Marco

**Comment by fluidvoice** [comment]
> Hey @fluidvoice,
> 
> great. Should I rename now or just wait until you experimented a little bit?
> 
> Very much appreciated!
> 
> Marco

you can restore via the seed phrase when you first created your LND wallet. For me no. I cannot find my seed phrase but no big deal as only a tiny amount of $ was in it.

**Comment by wuestenigel** [comment]
@fluidvoice 

I tried to rename the folder, but after creating a new SD card it says:

./00raspiblitz.sh: line 336: [: -eq: unary operator expected
WARN: LND needs re-setup
*** Check Basic Config ***
*** Check bitcoin Running ***
*** Check bitcoin Responding *** (can take a while)
OK - chainnetwork is working

*** Check LND Config ***
cp: cannot create regular file '/mnt/hdd/lnd/lnd.conf': No such file or directory
sed: can't read /mnt/hdd/lnd/lnd.conf: No such file or directory
chown: cannot access '/mnt/hdd/lnd/lnd.conf': No such file or directory
FAIL - Was not able to setup LND
admin@wuestenigelRaspi:~ $

**Comment by fluidvoice** [comment]
> @fluidvoice
> 
> I tried to rename the folder, but after creating a new SD card it says:
> 
> ./00raspiblitz.sh: line 336: [: -eq: unary operator expected
> WARN: LND needs re-setup
> *** Check Basic Config ***
> *** Check bitcoin Running ***
> *** Check bitcoin Responding *** (can take a while)
> OK - chainnetwork is working
> 
> *** Check LND Config ***
> cp: cannot create regular file '/mnt/hdd/lnd/lnd.conf': No such file or directory
> sed: can't read /mnt/hdd/lnd/lnd.conf: No such file or directory
> chown: cannot access '/mnt/hdd/lnd/lnd.conf': No such file or directory
> FAIL - Was not able to setup LND
> admin@wuestenigelRaspi:~ $

yeah, I found out too. That doesn't work.  It was just a guess on my part. Rename it back to original.
I havent' discovered any tricks.  Stick to the Docs and FAQ procedures.

**Comment by wuestenigel** [comment]
![image](https://user-images.githubusercontent.com/17941907/57597797-1d8b9b00-7551-11e9-8662-70849114eeac.jpg)

Working again!!! There is nothing as good as a clean install. Thanks!!
