### ISSUE TITLE
SweepAll on CashOut

### ISSUE THREAD

**Issue by StifflersMoM69** [raspiblitz/raspiblitz#497]
Hi!
I get this error, altough there are enough sats.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
FINAL FAIL --> Was not able to send transaction with max 20000 sat
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Press ENTER to return to main menu.

**Comment by rootzoll** [comment]
Have you tried the RTL web UI (can be activated under services) to make that transaction? Its way better then the shell script on making transactions.

**Comment by StifflersMoM69** [comment]
There i can only do Lightning Payments or am i able to send to any BTC address?

**Comment by rootzoll** [comment]
With RTL you can manage your on-chain and off-chain funds. See under "LND Wallet" there is a send option for BTC.

**Comment by rootzoll** [comment]
TODO: RTL has a sweep all option when sending BTC funds. Check how they do it and copy that for the shell script.

**Comment by StifflersMoM69** [comment]
Sending Fund Failed
Code
:
500
Message
:
error:insufficient funds available to construct transaction
Code
:
2

**Comment by rootzoll** [comment]
It may have something todo with fees .. maybe start with sending half the funds amount out and then check how much fees you need to set to make it work (raise step by step)

**Comment by rootzoll** [comment]
Also check in the RTL UI if all your channels are closed and setteled. If you have a force closing still running some funds may not be spendale already.

**Comment by StifflersMoM69** [comment]
sending half of funds worked. The fees are much higher then expected

**Comment by CommanderPoe** [comment]
> sending half of funds worked. The fees are much higher then expected

Mempool is been steadily clearing out, but fees are indeed higher than a month ago.

**Comment by rootzoll** [comment]
TODO: Improve the CashOut Script.

**Comment by rootzoll** [comment]
TODO: Test the new --sweepall feature of LND 0.6 with RaspiBlitz v1.2

**Comment by rootzoll** [comment]
The new CASHOUT in v1.2 is much simpler now to the LND 0.6 sendcoins --sweepall feature. No rewrite in python needed. 

TODO: Final testing

**Comment by rootzoll** [comment]
OK. The two tests worked great. I think this improves the CASHOUT experience by a lot. Closing Issue.
