### ISSUE TITLE
QREncode too large with PuTTY

### ISSUE THREAD

**Issue by wmpedersen** [raspiblitz/raspiblitz#498]
I'm trying to connect Shango with PuTTY on Windows as my terminal, but the QR-Code it generates is too large to fit on the screen in full screen or windowed maximized. I've tried using CTRL and CTRL minus but the zoom doesn't work in PuTTY. 

I did manage to scroll the window with Powershell and get it to connect, but it seems like something is different about qrencode with the PuTTY interface.

**Comment by rootzoll** [comment]
This will be solved with the next v1.2 release. It will use the LCD on the RaspiBlitz to display the QR code - so no SSH window resize needed anymore.
