### ISSUE TITLE
RTL - Unlocking Wallet Failed

### ISSUE THREAD

**Issue by goodc0re** [raspiblitz/raspiblitz#499]
See my issue over at the RTL repo:

https://github.com/ShahanaFarooqui/RTL/issues/116

**Comment by Luigybruno** [comment]
Had the same problem.
Try to renew the tls.cert and macaroons.
Raspiblitz main menu, _Export - Macarrons and TLS.cert_ and then _Reset - Renew macarrons and tls_.
Worked for me

**Comment by goodc0re** [comment]
Got it working as per updated comments on ShahanaFarooqui/RTL#116

**Comment by nyxnor** [comment]
pls close this.
