### ISSUE TITLE
Identify biggest needs maintaining a Node

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#5]
Find more articles and user reports like this to identify what are the most important UX fixes to make it easy for people to maintain a Lightning Node:

https://medium.com/andreas-tries-blockchain/bitcoin-lightning-network-2-we-must-first-become-the-lightning-network-49c46953c1d7

**Comment by joevegan** [comment]
Hey @rootzoll I really like what you're doing with this project--there is a huge usability gap in this space. We're about to launch a startup to help resolve some of these user experience issues, please drop me a line if you're interested: joevegan@gmail.com. Sorry for commenting on the issue, but I stumbled upon your git and did not see any other way to get a hold of you.
