### ISSUE TITLE
Question regarding setting up DynamicDNS vs manually opening ports on router

### ISSUE THREAD

**Issue by Z-and** [raspiblitz/raspiblitz#501]
I've successfully setup my RaspiBlitz and have begun playing around with some of its features. However, I still have a few issues that I need to address (namely the DynamicDNS).

I noticed in the guide it recommends registering a DynamicDomain service to forward certain ports (8333, 9735, 10009) in order to make the Pi publicly accessible. I've personally never used a DynamicDNS service before but have already created a static IP for my RaspiBlitz and have manually opened those ports (this was from before when I was setting up my RaspiBolt). You can see below how my port forwarding is configured (192.168.1.44 is the Pi on my local network)

![Verizon](https://user-images.githubusercontent.com/44408809/55812405-eee55500-5ab8-11e9-86b2-182bbf4b7634.JPG)

Will a setup like this suffice or will I still have to setup DynamicDNS? I'm noticing that I'm able to connect to peers but unable to open up new channels. I'm wondering if this has something to do with the firewall settings. I get the following error when trying to open a channel.

![image](https://user-images.githubusercontent.com/44408809/55812344-ce1cff80-5ab8-11e9-996a-0e11f86e1662.png)

**Comment by rootzoll** [comment]
You need both port-forwarding and dynDNS. You need dynDNS to map your changing public IP (given by your ISP) to a domain name so that other clients (especially when you use mobile wallets) can always find your latest publicIP. Once they found your public IP they end up at your router and you need to have to forward the needed ports so that the clients get from your router to your raspiblitz.

**Comment by Z-and** [comment]
> You need both port-forwarding and dynDNS. You need dynDNS to map your changing public IP (given by your ISP) to a domain name so that other clients (especially when you use mobile wallets) can always find your latest publicIP. Once they found your public IP they end up at your router and you need to have to forward the needed ports so that the clients get from your router to your raspiblitz.

Great thank you, appreciate the reply! It was also nice meeting you at the NYC Hackathon back in October last year! I will try this out and report back. I've never used a DynamicDNS service before, are there any guides or instructions that clearly explain what to do?

**Comment by Z-and** [comment]
> You need both port-forwarding and dynDNS. You need dynDNS to map your changing public IP (given by your ISP) to a domain name so that other clients (especially when you use mobile wallets) can always find your latest publicIP. Once they found your public IP they end up at your router and you need to have to forward the needed ports so that the clients get from your router to your raspiblitz.

Great appreciate your response! I went ahead and setup the DynamicDNS, it was a lot more straight forward than I thought.
