### ISSUE TITLE
Add new Torrent Update

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#504]
The last torrent blockchain update file is more then 3 month old - needs update.

**Comment by rootzoll** [comment]
Added a new update torrent - needs testing

**Comment by rootzoll** [comment]
TODO: When local testing with torrent was positive - ask community over twitter to help seeding the torrent.

**Comment by kilrau** [comment]
My raspiblitz is sitting on a 1Gbit upload connection here and I would be happy to help with permanent seeding. Can I use the raspi-internal torrent client for this without killing other processes? If so, please point me to some instructions.

**Comment by rootzoll** [comment]
@kilrau moved the torrent seeding feature to the v1.2 release .. you can subscribe to this issue, to get an info on updates: https://github.com/rootzoll/raspiblitz/issues/24

**Comment by kilrau** [comment]
Done, thx! Sorry, didn't see that issue - but great that it is already in the works!

**Comment by rootzoll** [comment]
OK - new Torrent Update File is tested and works. Opening a new issue to ask people seeding. Closing this issue.
