### ISSUE TITLE
Power Cord from Amazon on USA list "Currenly out of Stock"

### ISSUE THREAD

**Issue by ghost** [raspiblitz/raspiblitz#508]
Currently out out of stock:  Power: http://a.co/d/fVVOYZZ

Should it be replaced with another one for now?  Possibly: https://www.amazon.com/dp/B01N336XEU/ref=dp_cerb_3

**Comment by fluidvoice** [comment]
Yeah that one looks pretty good. From the Amazon reviews...

> Take note that I'm talking specifically about the >>> Pi 3 B+ <<<, not the Pi 3 or even the Pi 3B. I'm also talking about powering both the touchscreen and the Pi 3 B+ from a single wart. With one wart powering both the measured voltage dropped down to 5.1 volts and I had the low voltage warning on the display. I tested the Pi 3 B+ without the touchscreen connected and there was no warning. The voltage measured 5.22 volts without the screen. 


![Screenshot_2019-04-10_18-03-08](https://user-images.githubusercontent.com/373038/55913571-51267e80-5bbb-11e9-89f0-160f1943db67.png)
![Screenshot_2019-04-10_18-02-10](https://user-images.githubusercontent.com/373038/55913637-75825b00-5bbb-11e9-942a-2e7be0d76e51.png)

**Comment by rootzoll** [comment]
@ryanortega I would highly recommend this one: https://www.amazon.com/dp/B07MC7B9X3

**Comment by rootzoll** [comment]
USA Shopping List Updated. Closing the issue.

**Comment by ghost** [comment]
Thanks
