### ISSUE TITLE
BUILD FAILED --> Bitcoin download checksum not OK

### ISSUE THREAD

**Issue by Smiggel** [raspiblitz/raspiblitz#51]
Trying to setup a node the manual way. Installing using the script works fine until it should check the code of Bitcoin and it stops with the error "BUILD FAILED --> Bitcoin download checksum not OK".

Anyone else having this issue?

**Comment by rootzoll** [comment]
Thats line 131 in `rasbianStretchDesktop.sh` .. can you run and post what the output is?
`sha256sum --check SHA256SUMS.asc --ignore-missing`

**Comment by Smiggel** [comment]
I can not execute: sha256sum --check SHA256SUMS.asc --ignore-missing 

The file is missing it seems.

**Comment by Smiggel** [comment]
Ok, figured it out. I was in the wrong folder. :-)

I get this:
bitcoin-0.16.2-arm-linux-gnueabihf.tar.gz: good
sha256sum: WARNING: 20 lines are incorrectly formatted

**Comment by Smiggel** [comment]
Issue is fixed. Tried again. Seems like it went wrong because I stripped Raspbian from packages I don't use. Doing it without the stripping it works fine.
