### ISSUE TITLE
Fahrenheit on Status Screen

### ISSUE THREAD

**Issue by benthecarman** [raspiblitz/raspiblitz#512]
It would be nice if we had an option to have the temperature on status screen to be displayed in Fahrenheit.

**Comment by CommanderPoe** [comment]
Why Fahrenheit ?

**Comment by benthecarman** [comment]
I live in America so when I read 35 C, it doesn't mean much to me but I know that 95 F is really hot.

**Comment by WetPuppyKisses** [comment]
Freedom units.

It should be easy TF = 9TC/5 + 32

The healthiest thing to do is show both readings on the screen, otherwise It would be needed to add a visual settings menu.

**Comment by rootzoll** [comment]
@benthecarman thanks for the PR. Displaying Fahrenheut will be part of upcomming v1.2 release.
