### ISSUE TITLE
Help Torrent Seeding for RaspiBlitz v1.2 Release

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#513]
_Call to the RaspiBlitz Community:_

Much thanks to everybody helped on seeding the RaspiBlitz blockchain so far :)
Welcome if you are new volunteer 👍 

In the preparation of the upcomming RaspiBlitz v1.2 release in the comming weeks there will be a torrent file for the blockchain update that needs good seeding.

**Most important is to seed the new UPDATE torrent:**
https://github.com/rootzoll/raspiblitz/raw/v1.2/home.admin/assets/raspiblitz-bitcoin1-2019-04-09-update.torrent

**But also people see some slow downloads of the BASE torrent - so please add to seeding also if you are not seeding already:**
https://github.com/rootzoll/raspiblitz/raw/v1.2/home.admin/assets/raspiblitz-bitcoin1-2018-10-13-base.torrent

_At the moment you need to run the seeding on an extra computer. Most probably starting from v1.2 there will be the option to also seed the bloockchain torrents directly from the RaspiBlitz. Stay tuned :)_

**Comment by vamp111** [comment]
I'm on it!

**Comment by bhavman2** [comment]
Trying to DL now, will seed after!

**Comment by kilrau** [comment]
![image](https://user-images.githubusercontent.com/19181985/55992994-3b45b600-5cae-11e9-8e73-b8d4b1d7e763.png)

Will let it seed on this machine until https://github.com/rootzoll/raspiblitz/issues/24 is working.

**Comment by thelwyn** [comment]
+1

**Comment by pxsocs** [comment]
+1. Seeding.

**Comment by bitsam** [comment]
what torrent client do you recommend for Windows ? I noticed a lot of Libtorrent clients when downloading the blockchain.

**Comment by thelwyn** [comment]
On Windows, I use qBittorrent , works fine.

**Comment by Omicron59** [comment]
Hi rootzoll I share the torrents to participate in the deploment raspiblitz, I have a good upload connection in France. do you think I need to share the file too https://github.com/rootzoll/raspiblitz/raw/v1.2/home.admin/assets/raspiblitz-bitcoin1-2018-10-13-base.torrent I have the same date on another file

![image](https://user-images.githubusercontent.com/46853496/56031887-f9a22300-5d20-11e9-9202-4fb45bd52c74.png)

**Comment by rootzoll** [comment]
@mamar59 thats the same torrent file (just in another branch of the GitHub) - you are already seeding all of the important files - much thanks :D

**Comment by philbertw4** [comment]
I'm not sure if what I'm about the propose is a good idea or not (or if it has been proposed earlier), but:
* since raspiblitz has an option for downloading the blockchain via torrent as part of its setup process
* perhaps we consider adding "seed the raspiblitz blockchain torrent" as a service on the raspiblitz itself?
* perhaps by default it should be turned on but, as a security precaution, users must confirm this setting prior to completing setup?

Then again I'm not an expert in torrenting or raspberry-pi-ing, so maybe this is too much overhead for the small device and not very helpful for the purpose of seeding the torrent?

**Comment by rootzoll** [comment]
OK I think we have a good basic seed for the upcomming v1.2 release :)
Stay tuned. Closing Issue.

**Comment by kilrau** [comment]
I think you should also ask to seed the 1.2 image itself once it's out.
