### ISSUE TITLE
Still unable to upgrade to 1.1

### ISSUE THREAD

**Issue by lucbran** [raspiblitz/raspiblitz#534]
After one week attempts (including a complete blockchain reinstall)  I am still having probs with upgrading to 1.1.
I wanted to reinstall 1.0 version but unable to locate the dowanload link (I found  https://github.com/rootzoll/raspiblitz/releases but this is not the image file)...
where can I find this? Thanks

**Comment by fluidvoice** [comment]
> After one week attempts (including a complete blockchain reinstall) I am still having probs with upgrading to 1.1.
> I wanted to reinstall 1.0 version but unable to locate the dowanload link (I found https://github.com/rootzoll/raspiblitz/releases but this is not the image file)...
> where can I find this? Thanks

Still having what problems? In your previous issue (https://github.com/rootzoll/raspiblitz/issues/506#issue-431347942) you said the upgrade completed, so what problem did you see?...

> "So I tried after reinstate original name BRNode from sudo nano /mnt/hdd/raspiblitz.conf and reburnt the SD card.  After that sys recognised the original Alias name and **the whole process of updating to 1.1 version was finalized**"

**Comment by lucbran** [comment]
Actuallu it worked for a while ... then looks like blockchain went out of sync and had to sync all over again...
Now after both torrents have been downloaded, going ahead I get following on screen:
 │ Waiting for bitcoind to get ready.                                           │  
 │ error: Could not connect to the server 127.0.0.1:8332  Make sure the         │  
 │ bitcoind server is running and that you are connecting to the correct RPC 

any idea?

**Comment by fluidvoice** [comment]
> Actuallu it worked for a while ... then looks like blockchain went out of sync and had to sync all over again...
> Now after both torrents have been downloaded, going ahead I get following on screen:
> │ Waiting for bitcoind to get ready. │
> │ error: Could not connect to the server 127.0.0.1:8332 Make sure the │
> │ bitcoind server is running and that you are connecting to the correct RPC
> 
> any idea?

Need to know the exact steps you did and what "going ahead" means.

run these commands and post the output:
`sudo cat /mnt/hdd/bitcoin/bitcoin.conf`
`sudo cat /mnt/hdd/lnd/lnd.conf`
`sudo cat /etc/systemd/system/bitcoind.service`
`sudo systemctl status bitcoind -n2 --no-pager`
`sudo bitcoin-cli getblockchaininfo`
`/home/admin/XXdebugLogs.sh`

**Comment by lucbran** [comment]
Hi, 
I guess something is wrong in the alias name... I previously configured name asterisk-asteriskS.P.Rasterisk astersk (looks like this charcter is not accepted int his page)  and  then changed it into S.P.R. (without asterisks..)
 Looks like editing alias name has not been completed?

thanks for your assistance:
sudo cat /mnt/hdd/bitcoin/bitcoin.conf
# mainnet/testnet
testnet=0

# Bitcoind options
server=1
daemon=1
txindex=1
disablewallet=1

# Connection settings
rpcuser=raspibolt
rpcpassword=
zmqpubrawblock=tcp://127.0.0.1:28332
zmqpubrawtx=tcp://127.0.0.1:28333

# Raspberry Pi optimizations
dbcache=100
maxorphantx=10
maxmempool=50
maxconnections=40
maxuploadtarget=5000

datadir=/mnt/hdd/bitcoin
rpcport=8332
rpcallowip=127.0.0.1
rpcbind=127.0.0.1:8332

# lnd configuration

[Application Options]
debuglevel=debug
restlisten=0.0.0.0:8080
tlsextraip=0.0.0.0
maxpendingchannels=5
alias=asteriskasteriskS.P.R.asteriskasterisk (character not allowed in this page)
color=#68F442
nat=false

# RPC open to all connections on Port 10009
rpclisten=0.0.0.0:10009
# Domain, could use https://freedns.afraid.org
#tlsextradomain=lightning.yourhost.com

[Bitcoin]
bitcoin.active=1
bitcoin.node=bitcoind
# enable either testnet or mainnet
#bitcoin.testnet=1
bitcoin.mainnet=1

[Bitcoind]
bitcoind.rpcuser=raspibolt
bitcoind.rpcpass=
bitcoind.rpchost=127.0.0.1
bitcoind.zmqpubrawblock=tcp://*:28332
bitcoind.zmqpubrawtx=tcp://*:28333

[autopilot]
autopilot.active=1
autopilot.maxchannels=5
autopilot.allocation=0.6

# lnd configuration

[Application Options]
debuglevel=debug
restlisten=0.0.0.0:8080
tlsextraip=0.0.0.0
maxpendingchannels=5
alias=**S.P.R.**
color=#68F442
nat=false

# RPC open to all connections on Port 10009
rpclisten=0.0.0.0:10009
# Domain, could use https://freedns.afraid.org
#tlsextradomain=lightning.yourhost.com

[Bitcoin]
bitcoin.active=1
bitcoin.node=bitcoind
# enable either testnet or mainnet
#bitcoin.testnet=1
bitcoin.mainnet=1

[Bitcoind]
bitcoind.rpcuser=raspibolt
bitcoind.rpcpass=
bitcoind.rpchost=127.0.0.1
bitcoind.zmqpubrawblock=tcp://*:28332
bitcoind.zmqpubrawtx=tcp://*:28333

[autopilot]
autopilot.active=1
autopilot.maxchannels=5
autopilot.allocation=0.6

# RaspiBlitz: systemd unit for bitcoind

[Unit]
Description=Bitcoin daemon
Wants=bootstrap.service
After=bootstrap.service

# for use with sendmail alert (coming soon)
#OnFailure=systemd-sendmail@%n

[Service]
User=bitcoin
Group=bitcoin
Type=forking
PIDFile=/home/bitcoin/.bitcoin/bitcoind.pid
ExecStart=/usr/local/bin/bitcoind -daemon -conf=/home/bitcoin/.bitcoin/bitcoin.conf -pid=/home/bitcoin/.bitcoin/bitcoind.pid
KillMode=process
Restart=always
TimeoutSec=120
RestartSec=30
StandardOutput=null
StandardError=journal
[Install]
WantedBy=multi-user.target


● bitcoind.service - Bitcoin daemon
   Loaded: loaded (/etc/systemd/system/bitcoind.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2019-04-22 06:53:56 BST; 58ms ago
  Process: 29221 ExecStart=/usr/local/bin/bitcoind -daemon -conf=/home/bitcoin/.bitcoin/bitcoin.conf -pid=/home/bitcoin/.bitcoin/bitcoind.pid (code=exited, status=0/SUCCESS)
 Main PID: 29222 (bitcoind)
   CGroup: /system.slice/bitcoind.service
           └─29222 /usr/local/bin/bitcoind -daemon -conf=/home/bitcoin/.bitco…id

Apr 22 06:53:56 S.P.R.-Nexus systemd[1]: Starting Bitcoin daemon...
Apr 22 06:53:56 S.P.R.-Nexus systemd[1]: Started Bitcoin daemon.

error: Could not locate RPC credentials. No authentication cookie could be found, and RPC password is not set.  See -rpcpassword and -stdinrpcpass.  Configuration file: (/root/.bitcoin/bitcoin.conf)

XCEPTION: 15dbwrapper_error
Fatal LevelDB error: Corruption: not an sstable (bad magic number)
bitcoin in scheduler


*** LND SYSTEMD STATUS ***
● lnd.service - LND Lightning Daemon
   Loaded: loaded (/etc/systemd/system/lnd.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2019-04-21 19:01:35 BST; 11h ago
 Main PID: 4933 (lnd)
   CGroup: /system.slice/lnd.service
           └─4933 /usr/local/bin/lnd --externalip=82.58.168.135

Apr 21 19:01:35 S.P.R.-Nexus systemd[1]: Started LND Lightning Daemon.

*** LAST 5 LND ERROR LOGS ***
-- Logs begin at Sun 2019-04-21 18:17:01 BST, end at Mon 2019-04-22 06:55:20 BST. --
Apr 21 19:00:35 S.P.R.-Nexus systemd[1]: lnd.service: Unit entered failed state.
Apr 21 19:00:35 S.P.R.-Nexus systemd[1]: lnd.service: Failed with result 'exit-code'.
Apr 21 19:01:35 S.P.R.-Nexus systemd[1]: lnd.service: Service hold-off time over, scheduling restart.
Apr 21 19:01:35 S.P.R.-Nexus systemd[1]: Stopped LND Lightning Daemon.
Apr 21 19:01:35 S.P.R.-Nexus systemd[1]: Started LND Lightning Daemon.

*** LAST 20 LND INFO LOGS ***
2019-04-21 18:53:39.351 [INF] LTND: Version: 0.5.2-beta commit=v0.5.2-beta, build=production, logging=default
2019-04-21 18:53:39.352 [INF] LTND: Active chain: Bitcoin (network=mainnet)
2019-04-21 18:53:39.353 [INF] CHDB: Checking for schema update: latest_version=7, db_version=7
2019-04-21 18:53:39.360 [INF] RPCS: password RPC server listening on [::]:10009
2019-04-21 18:53:39.360 [INF] RPCS: password gRPC proxy started at [::]:8080
2019-04-21 18:53:39.362 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.
2019-04-21 18:40:42.805 [INF] LTND: Version: 0.5.2-beta commit=v0.5.2-beta, build=production, logging=default
2019-04-21 18:40:42.806 [INF] LTND: Active chain: Bitcoin (network=mainnet)
2019-04-21 18:40:42.994 [INF] CHDB: Checking for schema update: latest_version=7, db_version=7
2019-04-21 18:40:43.037 [INF] RPCS: password RPC server listening on [::]:10009
2019-04-21 18:40:43.038 [INF] RPCS: password gRPC proxy started at [::]:8080
2019-04-21 18:40:43.039 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.
2019-04-21 19:00:34.691 [INF] LNWL: Opened wallet
2019-04-21 19:00:35.158 [INF] LTND: Primary chain is set to: bitcoin
2019-04-21 19:00:35.196 [INF] LTND: Shutdown complete2019-04-21 19:01:35.858 [INF] LTND: Version: 0.5.2-beta commit=v0.5.2-beta, build=production, logging=default
2019-04-21 19:01:35.858 [INF] LTND: Active chain: Bitcoin (network=mainnet)
2019-04-21 19:01:35.861 [INF] CHDB: Checking for schema update: latest_version=7, db_version=7
2019-04-21 19:01:35.872 [INF] RPCS: password RPC server listening on [::]:10009
2019-04-21 19:01:35.872 [INF] RPCS: password gRPC proxy started at [::]:8080
2019-04-21 19:01:35.873 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.

*** LAST 20 RTL LOGS ***
-- Logs begin at Sun 2019-04-21 18:17:01 BST, end at Mon 2019-04-22 06:55:20 BST. --
Apr 21 18:40:41 S.P.R.-Nexus systemd[1]: Started RTL daemon.

**Comment by fluidvoice** [comment]
I see two obvious problems in the logs:

> error: Could not locate RPC credentials. No authentication cookie could be found, and **RPC password is not set.** See -rpcpassword and -stdinrpcpass. Configuration file: (/root/.bitcoin/bitcoin.conf)
> 
> XCEPTION: 15dbwrapper_error
> **Fatal LevelDB error: Corruption:** not an sstable (bad magic number)
> bitcoin in scheduler

So it looks like 1) your blockchain DB is possibly corrupted. and 2) RPC username + password is not set correctly via these config file entries:

`bitcoin.conf` file
**rpcuser=raspibolt
rpcpassword=**

`lnd.conf` file
**bitcoind.rpcuser=raspibolt
bitcoind.rpcpass=**

Hard to know how/why this happened not knowing exactly what you did... re-downloading blockchain, re-sync, re-install, etc.  I would try editing these files and put the correct password (your passwordB) and see if it can startup. Of course **if** your blockchain DB is really corrupted you will have to start over.

**Comment by lucbran** [comment]
agree but i guess raspibolt is default user as i dont remember having ever setup userid... how to change this?

**Comment by fluidvoice** [comment]
> agree but i guess raspibolt is default user as i dont remember having ever setup userid... how to change this?

You don't need to change this.  Just make sure your password is correct - what you entered during the install/setup for "passwordB"
Also don't use asterisks "*" in the node/host name.
Use only ASCII letters 'a' through 'z' (case-insensitive), the digits '0' through '9' and the hyphen-minus character ('-')

**Comment by lucbran** [comment]
Looks like pwd in bitcoin.conf and lnd.conf files match so I guess this is probably due to blockchain corrupted... will have to reinstall it all over...

**Comment by fluidvoice** [comment]
> Looks like pwd in bitcoin.conf and lnd.conf files match so I guess this is probably due to blockchain corrupted... will have to reinstall it all over...

Why were the pwd's empty in the config file contents above then, you removed them just to not show them in this issue posting?  It also does not explain the error in the log...

> error: **Could not locate RPC credentials**. No authentication cookie could be found, and **RPC password is not set.**

**Comment by lucbran** [comment]
yeah they were removed when posting...anyway starting a fresh reinstallation even if i already know funds will not be recovered with seed... thanks for your help

**Comment by lucbran** [comment]
ok this is becoming quite embarassing... I formatted HD (not canceled files but just formatted) and went trhough the whole installation process..Downloaded again whole blockchain.
Created wallet and when syncronizing lnd I get Unable to resolve Host S.P.Q.R.
[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"

what is going on? Should I have formatted HD with full cancellation of data or what el;se?

**Comment by fluidvoice** [comment]
> ok this is becoming quite embarassing... I formatted HD (not canceled files but just formatted) and went trhough the whole installation process..Downloaded again whole blockchain.
> Created wallet and when syncronizing lnd I get Unable to resolve Host S.P.Q.R.
> [lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"
> 
> what is going on? Should I have formatted HD with full cancellation of data or what el;se?

Verify your node's public IP address with:
`curl -s http://v4.ipv6-test.com/api/myip.php` 
and check that it's set correctly; see this: https://github.com/rootzoll/raspiblitz/issues/50#issuecomment-453739075

**Comment by fluidvoice** [comment]
Btw, you can search the past Raspiblitz issues for the errors you are seeing by clicking on the "issues" tab above then remove the "is:open" filter (so you search even closed issues), and then past in the text you want to search for.   That's how I found that issue/link I posted, I searched for "Error while dialing dial tcp"

**Comment by lucbran** [comment]
Hi searched everywhere but even after new fresh installation and blockchain download, I get message : unable to resoolve host and follwoing screen appears asking to download the whole blockchain again

I guess i will wait new updated version and try to reinstall rt all over..
![Screenshot from 2019-04-24 19-47-23](https://user-images.githubusercontent.com/22008556/56681711-43e4b600-66ca-11e9-9faa-46b5e9862263.png)

**Comment by fluidvoice** [comment]
> Hi searched everywhere but even after new fresh installation and blockchain download, I get message : unable to resoolve host and follwoing screen appears asking to download the whole blockchain again
> 
> I guess i will wait new updated version and try to reinstall rt all over..
>

I doubt waiting will change anything.  You most likely need to replace some poor quality hardware... power supply, HD, HD case, cables etc.   Or you're doing something wrong with downloading and copying the blockchain without corrupting it.

**Comment by lucbran** [comment]
You are probably right.. it all was previously working when I got a problem in the blockchain.. HDD may be the problem... will replace and restart it over... thanks

**Comment by fluidvoice** [comment]
Run the power-supply test script and post the results here.  
The majority of peoples' problems are from a weak PS:

PowerTest script (all in one line):
`wget https://raw.githubusercontent.com/rootzoll/raspiblitz/4abbdd18aa0ec44553d1fd875f2c5a6b98d9721c/home.admin/config.scripts/blitz.powertest.sh && sudo chmod +x blitz.powertest.sh && ./blitz.powertest.sh`

if that one fails to run try this one:

`wget https://raw.githubusercontent.com/openoms/raspiblitz/powertest/home.admin/XXpowertest.sh && sudo chmod +x XXpowertest.sh && ./XXpowertest.sh
`

**Comment by lucbran** [comment]
Ok first one failed... second one returns: 59.1'C  600/1400 MHz 1.2V.

what doe s it mean?

**Comment by fluidvoice** [comment]
> Ok first one failed... second one returns: 59.1'C 600/1400 MHz 1.2V.
> 
> what doe s it mean?

It means your power supply is poor quality.  Voltage of 1.2V is not sufficient and is causing a lot of CPU throttling (slowed down) from 1400MHz to only 600MHz.  
Which power supply is this?  I hope it's not one of the ones recommended in the Shopping Lists.

**Comment by lucbran** [comment]
I purchased starter kit which include power supply as instructed
https://www.amazon.co.uk/ABOX-Raspberry-Desktop-Starter-Upgraded/dp/B07G786RJ2/ref=sr_1_fkmrnull_1?crid=1KWQD0YVNQ6HW&keywords=abox+raspberry+pi+3+b%2B+model+b+plus+desktop+starter+kit&qid=1556743049&s=computers&sprefix=Abox+raspberry%2Ccomputers%2C186&sr=1-1-fkmrnull

Isn't enough?

**Comment by fluidvoice** [comment]
> I purchased starter kit which include power supply as instructed
> https://www.amazon.co.uk/ABOX-Raspberry-Desktop-Starter-Upgraded/dp/B07G786RJ2/ref=sr_1_fkmrnull_1?crid=1KWQD0YVNQ6HW&keywords=abox+raspberry+pi+3+b%2B+model+b+plus+desktop+starter+kit&qid=1556743049&s=computers&sprefix=Abox+raspberry%2Ccomputers%2C186&sr=1-1-fkmrnull
> 
> Isn't enough?

I don't think so. This one looks good: https://www.adafruit.com/product/1995
![D3R-vJqWwAEPZeq](https://user-images.githubusercontent.com/373038/57041872-a47b7200-6c39-11e9-8452-5289eac50a3a.png)

**Comment by lucbran** [comment]
yo u mean shopping list requirement Powersupply >=3A (choose big & stable output) not sufficient? Any alternative on amazon?

**Comment by fluidvoice** [comment]
> yo u mean shopping list requirement Powersupply >=3A (choose big & stable output) not sufficient? Any alternative on amazon?

The specification "3A" is irrelevant because many of them do not actually put out 5V at that current load.
yes: 
www.amazon.com/dp/B07MC7B9X3
www.amazon.com/MakerBrightTM-MicroUSB-Switching-Supply-Raspberry/dp/B01FIBYQE6/
[edit] in fact that Adafruit one is on Amazon too. I would go for this one as it has a nice thick cable: https://www.amazon.com/Supply-microUSB-Connector-Raspberry-NVIDIA/dp/B07QSX6ZZN/

**Comment by lucbran** [comment]
ok will check if amazon in Italy has this kind of adapters..
What about USB cable to HDD? Do you think problem could be also caused by the usb cable quality?

**Comment by lucbran** [comment]
So, thanks to your precious advice I solved my main 2 problems:
undervoltage problem : solved with new power ssupply 5.25V
blockchain config problem: pwas caused by hostname set to word containing dots. Changed raspi-config hostname and everything went smooth.
Now raspiblitz screen working but when trying menu #detailed wallet balance# I get: ./00mainMenu.sh: line 429: lnchannels: command not found
Press ENTER to return to main menu.

I am thinking to try 1.2 version..what you think?

**Comment by fluidvoice** [comment]
> So, thanks to your precious advice I solved my main 2 problems:
> undervoltage problem : solved with new power ssupply 5.25V
> blockchain config problem: pwas caused by hostname set to word containing dots. Changed raspi-config hostname and everything went smooth.
> Now raspiblitz screen working but when trying menu #detailed wallet balance# I get: ./00mainMenu.sh: line 429: lnchannels: command not found
> Press ENTER to return to main menu.
> 
> I am thinking to try 1.2 version..what you think?

try running `/home/admin/91addBonus.sh` then 00mainMenu.sh

**Comment by lucbran** [comment]
done but stll returns ./00mainMenu.sh: line 429: lnchannels: command not found

**Comment by fluidvoice** [comment]
> done but stll returns ./00mainMenu.sh: line 429: lnchannels: command not found

try this:
`wget https://stadicus.github.io/RaspiBolt/resources/lnbalance`
`wget https://stadicus.github.io/RaspiBolt/resources/lnchannels`
`chmod +x lnbalance && chmod +x lnchannels`
`sudo cp lnchannels /usr/local/bin && sudo cp lnbalance /usr/local/bin`
`/home/admin/00mainMenu.sh`

**Comment by lucbran** [comment]
No words...That's the solution!!! now everything working..Thanks very much..
will now wait few days and try the 1.2 version..
thanks again my friend!

**Comment by fluidvoice** [comment]
glad its working. Please close this issue.
