### ISSUE TITLE
Is the lack of Free Mem somehow related to the Power Cable?

### ISSUE THREAD

**Issue by CommanderPoe** [raspiblitz/raspiblitz#535]
I have noticed that everytime i run some sort of "heavy" process on the pi like: - Copy the whole LND folder to make a backup or - Install Zap Connet. My Free Memory goes to values below 80 which i think is kindda critical. I have experienced several times this issue and a quick restart of the pi usually fix it, but I would like to understand why this is happening? Is that related to the Power Cable? 

This is usually the mem issues it goes as low as 60.
<img width="601" alt="Screenshot 2019-04-21 at 15 16 23" src="https://user-images.githubusercontent.com/33594578/56470851-65843a00-644b-11e9-8480-849077ffac65.png">

the Cable i bought is the one that comes with the ABOX, 5V 3A

**Comment by fluidvoice** [comment]
Cable and power supply ratings mean nothing as they often don't reflect reality - outright lies, or under high load/amps their performance degrades excessively.  With cables the wire thickness/gauge is important and the smaller the gauge (awg) the better/thicker.
I can imagine power supply, or any other, problems that negatively impact receiving network data could possibly cause LND to use more RAM as it dynamically handles channel connectivity. I'm sorta guessing here but I've seen LND at times using excessive RAM and I'm assuming this is from some "abnormal" network condition.  So could your running "heavy" processes cause or contribute to this? Seems plausible but I dunno.

**Comment by CommanderPoe** [comment]
> Cable and power supply ratings mean nothing as they often don't reflect reality (lies).
> I can imagine power supply, or any other, problems that impact network data could possibly cause LND to use more RAM as it dynamically handles channel connectivity. I'm sorta guessing here but I've seen LND at times using excessive RAM and I'm assuming this is from some "abnormal" network condition.

I thought it could be some sort of punctual issue with my system since i never see anyone in here complaining about the RAM. But as far as i understood from your answer just make the quick restart and move along...

**Comment by fluidvoice** [comment]
> > Cable and power supply ratings mean nothing as they often don't reflect reality (lies).
> > I can imagine power supply, or any other, problems that impact network data could possibly cause LND to use more RAM as it dynamically handles channel connectivity. I'm sorta guessing here but I've seen LND at times using excessive RAM and I'm assuming this is from some "abnormal" network condition.
> 
> I thought it could be some sort of punctual issue with my system since i never see anyone in here complaining about the RAM. But as far as i understood from your answer just make the quick restart and move along...

see my edited msg above.  You should run the power-test script to test your power supply.

**Comment by fluidvoice** [comment]
PowerTest script (all in one line):
`wget https://raw.githubusercontent.com/rootzoll/raspiblitz/4abbdd18aa0ec44553d1fd875f2c5a6b98d9721c/home.admin/config.scripts/blitz.powertest.sh && sudo chmod +x blitz.powertest.sh && ./blitz.powertest.sh`

if that one fails to run try this one:

`wget https://raw.githubusercontent.com/openoms/raspiblitz/powertest/home.admin/XXpowertest.sh && sudo chmod +x XXpowertest.sh && ./XXpowertest.sh`

**Comment by fluidvoice** [comment]
If I remember correctly a result showing voltage drops below 1.25V signal an inferior power supply and probably should be replaced.

**Comment by CommanderPoe** [comment]
> wget https://raw.githubusercontent.com/openoms/raspiblitz/powertest/home.admin/XXpowertest.sh && sudo chmod +x XXpowertest.sh && ./XXpowertest.sh

thanks for this... seems like i need a new power supply according to the test.

<img width="568" alt="Screenshot 2019-04-22 at 15 30 00" src="https://user-images.githubusercontent.com/33594578/56502699-916af280-6513-11e9-9555-9dde482bffad.png">
 
I think u guys advised one right? would you share it with me? Im in Europe btw and thanks again

**Comment by CommanderPoe** [comment]
Well it seems like im in need of a new power supply according to the test 

<img width="570" alt="Screenshot 2019-04-22 at 15 31 46" src="https://user-images.githubusercontent.com/33594578/56502791-d000ad00-6513-11e9-9b40-2a78aec4dbef.png">

I think u guys recommended one in another thread right? Would u share it with me? Im in Europe btw

**Comment by fluidvoice** [comment]
See the shopping lists on the main RaspiBlitz page.  @rootzoll keeps them pretty up to date with what we know at the time to be the best choices.
EDIT: I just noticed both UK shopping lists power supply links are no longer valid.
The PS from the Germany/Spain shopping lists is prob a decent choice.  I personally would look for reviews where guys have tested the PS under load to see if it operates as spec'ed. But even then there's no guarantee with these cheap, often poorly QA'ed things made in China.

**Comment by fluidvoice** [comment]
Even if your memory problem persists after new PS, at least you have removed one possible (and common!) source of problems.

**Comment by amcitaly** [comment]
> 
> 
> Well it seems like im in need of a new power supply according to the test
> 
> <img alt="Screenshot 2019-04-22 at 15 31 46" width="570" src="https://user-images.githubusercontent.com/33594578/56502791-d000ad00-6513-11e9-9b40-2a78aec4dbef.png">
> 
> I think u guys recommended one in another thread right? Would u share it with me? Im in Europe btw

This is mine, but i never received messages of undervoltage problems...
![power test](https://user-images.githubusercontent.com/46417649/56797893-0b51f300-6816-11e9-9aa4-7a647b7c31fa.PNG)

**Comment by fluidvoice** [comment]
> This is mine, but i never received messages of undervoltage problems...

try running this and see if anything shows up..
`sudo grep "Under-voltage detected!" /var/log/syslog`

**Comment by amcitaly** [comment]
> 
> 
> > This is mine, but i never received messages of undervoltage problems...
> 
> try running this and see if anything shows up..
> `sudo grep "Under-voltage detected!" /var/log/syslog`

Ooops it seems I have a problem 
![undervoltage](https://user-images.githubusercontent.com/46417649/56841594-067d5580-688f-11e9-9678-33a0f74ddd30.PNG)

**Comment by fluidvoice** [comment]
> Ooops it seems I have a problem

Actually it looks fine.  It says zero undervoltage reports.
So "Under-voltage detected!" was not in there?  I think it's OK.

**Comment by fluidvoice** [comment]
But 1.23V is pretty bad. I'd replace that PS. Btw, found out my PS is equally as bad.

**Comment by amcitaly** [comment]
> 
> 
> > Ooops it seems I have a problem
> 
> Actually it looks fine. It says zero undervoltage reports.
> So "Under-voltage detected!" was not in there? I think it's OK.

Yes probably is fine sorry, when i saw the red I though there was a problem but in fact is "0". I have 2 screen for the raspberry, with one it gives me some undervoltage problem just on starting and I don't use anymore. With the one I use now never have problems. Well I will change the PS on next upgrade to verify, thx

**Comment by fluidvoice** [comment]
> I have 2 screen for the raspberry, with one it gives me some undervoltage problem

That's interesting. Which screen is this that caused under-voltage?  I would have thought all screens consume about the same amount of current.

**Comment by amcitaly** [comment]
Is the most beautiful LCD the one that cause the problem. Apparently they are the same but the one that make problem has the pin on the opposite side of the one I use now. I look on the back and they are similar, if you think can help i will post a pic on the back to compare them. Is this that i bought case+lcd+pen (the problematic one)
![rpi](https://user-images.githubusercontent.com/46417649/56850514-1aaf6a00-6904-11e9-9cdf-fb243e1a3cd1.png)

**Comment by amcitaly** [comment]
> > I have 2 screen for the raspberry, with one it gives me some undervoltage problem
> 
> That's interesting. Which screen is this that caused under-voltage? I would have thought all screens consume about the same amount of current.

Is the most beautiful LCD the one that cause the problem. Apparently they are the same but the one that make problem has the pin on the opposite side of the one I use now. I look on the back and they are similar, if you think can help i will post a pic on the back to compare them. Is this that i bought case+lcd+pen (the problematic one)
![rpi](https://user-images.githubusercontent.com/46417649/56850885-d07cb780-6908-11e9-9ff3-00297cd708d2.png)
