### ISSUE TITLE
UK shopping list power supply links broken or unavailable - needs update

### ISSUE THREAD

**Issue by fluidvoice** [raspiblitz/raspiblitz#537]
See the shopping lists on the main RaspiBlitz page.  @rootzoll keeps them pretty up to date with what we know at the time to be the best choices.
EDIT: I just noticed both UK shopping lists power supply links are no longer valid.

_Originally posted by @fluidvoice in https://github.com/rootzoll/raspiblitz/issues/535#issuecomment-485437642_

**Comment by CommanderPoe** [comment]
the spaniard/german list offer 4 different options for the same brand... Do u think it will help if i choose the most powerful (20W 5V 4A)? also the on/off switch its important to me.

<img width="1011" alt="Screenshot 2019-04-22 at 17 19 40" src="https://user-images.githubusercontent.com/33594578/56507882-14e01000-6523-11e9-80d6-0e08b323ff8e.png">

**Comment by fluidvoice** [comment]
Short answer is yes, pick higher amp rating when possible.  Just keep in mind...  Sometimes the printed spec's are an outright lie.  Sometimes they substitute and ship something else than what was ordered or what reviewers commented on.  I just saw in the picture that this PS showed "20awg" on the wire (20 gauge wire thickness) which is good. The smaller the number the thicker the wire (better) so 20awg is good or even 18awg or lower?  An on/off switch could work if it's good quality but could also drop voltage if it's not.  Best is to use a switch on your AC power outlet or "power bar".  The higher amp rating, 3A or 4A, **usually** means it will keep delivering at least 5 volts while under load of 2A or more, but it's not for sure. Depends on the quality of the PS.
