### ISSUE TITLE
secure and test pi user

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#54]
At the moment the raspiblitz makes an auto login on powerup with user pi to play info to the display. At the moment this user has too much rights. If some gets physical access to the device, you just need to connect a keyboard and you own it.

TODO: Limit rights of unix user pi, use readonly.macaroon with lncli and test what this user could still do.

**Comment by vv01f** [comment]
physical access will always be a problem. but trying to limit …

* [ ] first thing: drop him from sudoers ;) or even better: dont use user pi but leave him be and go with another/new user, e.g. "status", "monitor" or sth. you like
* [ ] one uncomplicated thing to limit the user is a restricted shell, e.g. `sudo chsh -s /bin/rbash pi`
* [ ] another thing is to prevent him from exiting the script, this can be done with [exec](http://wiki.bash-hackers.org/commands/builtin/exec), [trap](http://wiki.bash-hackers.org/commands/builtin/trap) is an alternative fallback … for `/home/pi/.bashrc`
```
# automatic start the LCD info loop
SCRIPT=/home/admin/00infoLCD.sh
# trap may not be necessary when exec is used
trap $SCRIPT EXIT
# replace shell with script => logout when exiting script
exec $SCRIPT
```

[further limits](https://www.tecmint.com/set-limits-on-user-processes-using-ulimit-in-linux/) are possible

**Comment by rootzoll** [comment]
Remove the sudo from pi needs more work to keep info-scripts running - thinking about not investing the time in this for now, because maybe we will make jump to rewrite for ePaper Hat (replacing LCD) anyway soon. Will gather feedback on that from the community on the hackday this week.

But the exec sounds like a quick win. Will test it out. Much thanks.

**Comment by rootzoll** [comment]
exec works great :D
