### ISSUE TITLE
Is it safe/possible to upgrade to lnd v0.6 while still using v1.1 of Raspiblitz?

### ISSUE THREAD

**Issue by Z-and** [raspiblitz/raspiblitz#540]
Subject says it all, just wondering if it's safe to upgrade to lnd 0.6 instead of waiting for v1.2 of Raspiblitz to come out.

**Comment by walletofsatoshi** [comment]
This is next critical upgrade for raspiblitz considering static channel backup on new lnd upgrade should be priority

**Comment by drunkenclam** [comment]
Yes, you can just stop lnd and then exchange the lnd and lncli binary files, they're in /usr/local/bin. Then restart.

**Comment by frennkie** [comment]
@Z-and I can confirm.. completely safe.

**Comment by Z-and** [comment]
Great thanks! At this point I might just wait for v1.2 as it seems to be close to completion

**Comment by bereska** [comment]
@Z-and, @drunkenclam, how exactly did you guys upgraded your lnd to 0.6? a step-by-step guide would be grade for less tech people like me) thanks

**Comment by fluidvoice** [comment]
> @Z-and, @drunkenclam, how exactly did you guys upgraded your lnd to 0.6? a step-by-step guide would be grade for less tech people like me) thanks

This is not advised as nobody wants to try to help people who did manual configurations.
If you want to try out lnd 0.6 I would install/upgrade Raspiblitz to (pre-release) v1.2 which uses **LND 0.6-beta** (beta meaning pre-release).  Keep in mind v1.2 is also not yet formally released so you might hit some issues, but I installed it and it's running OK on my Pi (pic below).  The install/upgrade is the same process as v1.1... burn the SD card, etc... On the README.md page of v1.2 release there is now a link to a v1.2 image to download.
https://github.com/rootzoll/raspiblitz/tree/v1.2#installing-the-software

This image is a candidate to be the final v1.2 release - but there are still some testing going on with it.
NOTE: no complaining if it messes up your config (make backups!) 
**It's PRE-RELEASE you've been warned.**  
That said, it's helpful for people to test out the new stuff. ;-)  
**Run `/home/admin/XXdebugLogs.sh` if you have problems to generate debug info.**

![D5daLZSX4AApfqL (1)](https://user-images.githubusercontent.com/373038/57021675-46cc3300-6c03-11e9-98fc-7c3bf396ab32.png)

**Comment by bereska** [comment]
@fluidvoice, thank you. The reason I asked about a manual upgrade of lnd to 0.6.1 is to check the performance improvement lnd devs were talking about. And I have a BTCPay server running on the same pi. Besides I manually added some packages and dependancies. So re-burning SD would mean re-installing and fine-tuning all that again

**Comment by fluidvoice** [comment]
> @fluidvoice, thank you. The reason I asked about a manual upgrade of lnd to 0.6.1 is to check the performance improvement lnd devs were talking about. And I have a BTCPay server running on the same pi. Besides I manually added some packages and dependancies. So re-burning SD would mean re-installing and fine-tuning all that again

Prob a question better asked to the LND dev's or just find and follow their upgrade doc's (backing up your current config of course; see the `rsync` tool usage)

**Comment by drunkenclam** [comment]
@bereska If you installed BTCpay server and other packages you should also be able to download the LND binaries and copy the files to /usr/local/bin folder? If not, take a few minutes and google how to do that, it helps you much when doing basic commandline work...

**Comment by bereska** [comment]
@drunkenclam, thank you. I do know how to handle binaries. I just thought there is something raspiblitz specific not to break anything

**Comment by fluidvoice** [comment]
Are you guys sure that the new LND release does not contain any config changes or changes other than simply updated binaries?

**Comment by drunkenclam** [comment]
That's exactly how you update LND. If you download the current 0.6 beta, all you get are those two binary files...

I'm running on LND master (compiling from source on the raspi) and I update nearly every week, depending on what was merged. You won't break anything this way.

**Comment by bereska** [comment]
for those who want to do it the right way https://gist.github.com/daniel-vera-g/92b33ffc6b7d4754056254f92ede4a1b

**Comment by frennkie** [comment]
@Z-and I believe this is outdated now -> closing.

Please urgently make sure that you are running at least `LND` version **0.7.1** as a security flaw has been discovered which was fixed in that version.
