### ISSUE TITLE
Lcd does not indicate

### ISSUE THREAD

**Issue by Lupus-Pluvia** [raspiblitz/raspiblitz#541]
hello have the following problem despite installation, the display does not show me the info display on the resberry flash.  just stay wise only at the start comes a bite text.  Display is Kedai Version 6.1.3 please help

**Comment by fluidvoice** [comment]
Post a picture of what you see on the LCD and HDMI screen during bootup, a picture of the back of the LCD and the link to where you bought the LCD.  If you plug a keyboard into the Pi are you able to access the terminal/command-line when pressing Ctrl-d or Ctrl-Alt-F1 or Ctrl-Alt-F2 ?

**Comment by Lupus-Pluvia** [comment]
![20190425_052204](https://user-images.githubusercontent.com/49962031/56707790-9a79e080-671a-11e9-87f6-067ef6b669bc.jpg)
![20190425_052204](https://user-images.githubusercontent.com/49962031/56707797-a2d21b80-671a-11e9-9922-ab2d4fbd727e.jpg)
![20190425_051435](https://user-images.githubusercontent.com/49962031/56707800-a9609300-671a-11e9-92c0-183c83aab0c1.jpg)
![20190425_051423](https://user-images.githubusercontent.com/49962031/56707809-b41b2800-671a-11e9-9406-f9b1708a196f.jpg)
![20190425_050457](https://user-images.githubusercontent.com/49962031/56707814-bb423600-671a-11e9-854a-5be4da392741.jpg)



I bought it here
https://rover.ebay.com/rover/0/0/0?mpre=https%3A%2F%2Fwww.ebay.de%2Fulk%2Fitm%2F191921112753
From the principle, the output should be dipped that it is not output via HDMI.

**Comment by Lupus-Pluvia** [comment]
![Screenshot_20190425-053750_eBay](https://user-images.githubusercontent.com/49962031/56708346-a4044800-671c-11e9-9547-1a3f5e3d6273.jpg)
The display looks like this except that it is the version 6.1.3 and from 2018 can only photograph the back tonight

**Comment by fluidvoice** [comment]
It it listed in one of the shopping lists?

**Comment by Lupus-Pluvia** [comment]
![20190425_051530](https://user-images.githubusercontent.com/49962031/56708501-31479c80-671d-11e9-9585-49d12c6f5a29.jpg)

had forgotten another picture

**Comment by Lupus-Pluvia** [comment]
No it is not thought I could take what I had with me

**Comment by Lupus-Pluvia** [comment]
but if the display from the list is used to 100% it can be ordered

**Comment by Lupus-Pluvia** [comment]
I have now ordered the display from the list, I have to pay attention to during commissioning or is that automatically?

**Comment by fluidvoice** [comment]
> had forgotten another picture

that looks good/normal, seems like it's booting up correctly.  This is perhaps a driver issue (if) that LCD is actually supported.  One way to find out, is to ask about this LCD on the **Raspberry Pi** and **Raspbian** user forums.

**Comment by fluidvoice** [comment]
> I have to pay attention to during commissioning or is that automatically?

I don't understand the question.  Nothing special is needed to be done for the LCD, just follow the documented installation procedure.

**Comment by fluidvoice** [comment]
> I have now ordered the display from the list

What is the link to the new LCD you bought?

**Comment by Lupus-Pluvia** [comment]
this is the link that was in the list

**Comment by fluidvoice** [comment]
> this is the link that was in the list

There are many lists.  One for each country - USA, UK, Germany, France, Spain, etc.  I'm just curious which one you bought.
