### ISSUE TITLE
_background.sh should monitor low-memory condition and restart

### ISSUE THREAD

**Issue by fluidvoice** [raspiblitz/raspiblitz#546]
As per incidents below/linked **users' nodes are running out of memory *over time*** and it's causing problems which gets resolved by restarting, freeing up memory.  But it could be automated where the LND (and perhaps bitcoind?) service is restarted by a background process that is monitoring the free mem.
It's unknown if the memory growth is a LND memory leak or growth resulting from dynamic state - channels open, connections, or network conditions.  But restarting is the workaround.

> > > or, just do it automatically (say using some config setting like LowMemoryRestart=lnd.service)
> > 
> > 
> > This is interesting, im gonna try it.
> 
> I didn't mean that such a setting exists. It doesn't. What I meant was that we could modify the scripts to create and use a config setting like that.

Perhaps might be a setting for the amount of free memory (low-water mark) such that LND and Bitcoind get restarted when memory goes below the set value.  This allows the number to be variable.  
Eg...  
LowMemResetBitcoinMB=64
LowMemResetLndMB=64

@rootzoll what do you think?  Is this an advisable/feasible thing to add?

_Originally posted by @fluidvoice in https://github.com/rootzoll/raspiblitz/issues/542#issuecomment-486687525_

**Comment by fluidvoice** [comment]
For example, perhaps **_background.sh** should check for low free/available memory **once per hour** the same as it is scanning for under-voltage reports here:
https://github.com/rootzoll/raspiblitz/blob/7459786b80975fc8c2a57c8458f5587480d3a52f/home.admin/_background.sh#L65

**Comment by nyxnor** [comment]
Memory is in stable consumption now, rarely this case occur anymore. Pls close this.
