### ISSUE TITLE
Bitcoin 0.18.1

### ISSUE THREAD

**Issue by frennkie** [raspiblitz/raspiblitz#548]
As far as I see https://github.com/bitcoin/bitcoin/milestone/35 Bitcoin 0.18 is expected to be released "soon". So it might make sense to track this for the 1.2 milestone of RaspiBlitz.

**Comment by rootzoll** [comment]
v1.2 is already in final testing. I think for the v1.2 I will stick to the old bitcoin version. 

But I mark this ticket for the next v1.3 release .. which should not take to long after v1.2.

**Comment by fluidvoice** [comment]
yes. and better to wait to find out if any LN problems w/resolution with the new release first.
Being on the bleeding edge comes with risks. There should be "must-have" or security concerns to warrant upgrading from day one.  Does 0.18 have must-haves?

**Comment by openoms** [comment]
Just clarified with @roasbeef: lnd is supporting the bitcoind 0.18.0 release already! The RPC changes to `sendrawtransaction` is merged in to the master post 0.18.0, so could be a problem only when building bitcoin from source. 
Updating to 0.18 will come with a higher `assumevalid` value so will make the Initial Block Download quicker.

**Comment by rootzoll** [comment]
I updated the v1.3 branch now including LND 0.7.1 and BitcoinCore 0.18.0 ... tests look good on my machine. Will be part of the v1.3 final release.

**Comment by fluidvoice** [comment]
> I updated the v1.3 branch now including LND 0.7.1 and BitcoinCore 0.18.0 ... tests look good on my machine. Will be part of the v1.3 final release.

You might want to hold off release until we can get Tor completely working. It seems it's failing for some even on the Pi4

**Comment by rootzoll** [comment]
Sure .. fixing TOR is still on the TODO list for the v1.3 release ... or are the new versions of LND/bitcoind adding to the Tor issue?

**Comment by rootzoll** [comment]
Updated to latest bitcoin core 0.18.1 release.
