### ISSUE TITLE
Supporting additional altcoins

### ISSUE THREAD

**Issue by chainfailure** [raspiblitz/raspiblitz#55]
Are you guys accepting PR's that add additional altcoins? I'm currently working on a Viacoin raspiblitz, and was planning on maintaining my own fork. However I would much prefer not diverting from upstream like that.

**Comment by rootzoll** [comment]
We already have litecoin integration. If its like litecoin a altcoin fork based on bitcoin source and will not add further complexity (just a third if-else here and there) why not. You can send PR along ... just might discuss it with the greater community before deciding adding.

I dont know Viacoin - maybe also not the others. Can you give a short introduction:
Are there binaries compiled for ARM (like for bitcoin and litecoin)?
How big is the Blockchain?
TOR seems a big deal on your website .. would you like to review upcoming TOR feature for raspiblitz and give feedback if all implemented legit?

**Comment by chainfailure** [comment]
> We already have litecoin integration. If its like litecoin a altcoin fork based on bitcoin source and will not add further complexity (just a third if-else here and there) why not.

Installation should be 1-on-1 with litecoin, so I dont expect any additional complexity setting it up.

> Are there binaries compiled for ARM (like for bitcoin and litecoin)?

Yes, actually. They can be found here: https://github.com/viacoin/viacoin/releases/tag/v0.15.1

> How big is the Blockchain?

12-ish gigabyte off the top of my head, but I don't have a full-node with me right now. Will come back at this.

> TOR seems a big deal on your website .. would you like to review upcoming TOR feature for raspiblitz and give feedback if all implemented legit?

Sure! 

> I dont know Viacoin - maybe also not the others. Can you give a short introduction:

We're a currency that mainly focusses on privacy and speed, but being decentralized is def something that aligns with our ideas of a cryptocurrency worthwhile. Hence we're looking for methods to get people easily up and running with their own node.

>  You can send PR along ... just might discuss it with the greater community before deciding adding.

Neat, I'll get started then :smile:

**Comment by rootzoll** [comment]
Still open for others alt-coins, but ticket is kind of old now. So I closing it for now.
