### ISSUE TITLE
Format HDD error

### ISSUE THREAD

**Issue by rpjcbs** [raspiblitz/raspiblitz#552]
Getting the below error when doing initial set up:

*** Formatting the HDD ***
WARNING ALL DATA ON HDD WILL GET DELETED - CAN TAKE SOME TIME
Wait until you get a OK or FAIL
mke2fs 1.43.4 (31-Jan-2017)
/dev/sda2 contains a exfat file system labelled 'SEAGATE'
Creating filesystem with 488327168 4k blocks and 122085376 inodes
Filesystem UUID: 153f115a-ea64-443e-b2f2-23e344fb1408
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208, 
	4096000, 7962624, 11239424, 20480000, 23887872, 71663616, 78675968, 
	102400000, 214990848

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (262144 blocks): done
Writing superblocks and filesystem accounting information: done       

format ext4 done - wait 6 secs
FAIL - was not able to format the HDD to ext4 with the name 'BLOCKCHAIN'

I'm using a Seagate 2TB HDD which I formatted to ExFAT before connecting to my Pi.

**Comment by fluidvoice** [comment]
What is your output of running this from a SSH terminal command line?
`sudo lsblk -o UUID,NAME,FSTYPE,SIZE,LABEL,MODEL`

**Comment by rpjcbs** [comment]
So after I got that error, I turned my Pi off and on and it's now downloading the blockchain... weird

**Comment by rpjcbs** [comment]
@fluidvoice - Scrap that, the torrent blockchain and download have been stuck on 0% and 3% for over 48 hours.

So I went to try to ultra-slow method and got this error:

*** Activating Blockain Sync ***
mkdir: cannot create directory ‘/mnt/hdd/bitcoin’: Read-only file system
OK - sync is activated

*** Checking HDD ***
FAIL - HDD is empty.
admin@RaspiBlitz:~ $

**Comment by fluidvoice** [comment]
Looks most likely a power supply problem.  Insufficient power causing HDD failure and/or corruption.
This "Read-only file system" error is a common symptom of that.  Which power supply and HDD are you using?  That Seagate doesn't have it's own PS, just plugged into the Pi's USB right?  You should prob power the HDD separately with a powered USB hub or a USB drive "Y-cable".
See this similar issue: https://github.com/rootzoll/raspiblitz/issues/545#issue-437207335

**Comment by rpjcbs** [comment]
@fluidvoice thanks for your help, I purchased this - https://www.amazon.co.uk/gp/product/B00P0C4M5M/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1 - off of Amazon and it came today. Just plugged it into my Pi, the HDD and power and it's downloaded further than it did yesterday.

Will leave that for a day or two and see how it goes, thanks again

**Comment by fluidvoice** [comment]
> @fluidvoice thanks for your help, I purchased this - https://www.amazon.co.uk/gp/product/B00P0C4M5M/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1 - off of Amazon and it came today. Just plugged it into my Pi, the HDD and power and it's downloaded further than it did yesterday.
> 
> Will leave that for a day or two and see how it goes, thanks again

both of the y-cable USB are plugged into the Pi or one is plugged into a separate power supply?
I recommend using separate PS.

**Comment by rpjcbs** [comment]
@fluidvoice separate power supplies.

Blockchain downloaded, just doing all the other stuff now. Letting it run it's course, thanks for the help.
