### ISSUE TITLE
During blockchain download, download stalls and message appears no screen session found

### ISSUE THREAD

**Issue by coinicarus** [raspiblitz/raspiblitz#553]
I'm installing a new node and for some reason, my blockchain download gets stuck and this message-no screen session found appears in the cmd window in the download blockchain status area, also once this message appears the download doesnt continue it'll just stay stuck, if i hit X and abort and restart i may get slightly further, but once the message shows up it stalls again. see screenshot below. i am ready to scrap my torrent download and start a new one. I do have the screen connected and on it i just see the normal light blue screen with the login and IP info, so i dont think that error has anything to do with the actual screen LOL. thank you for your time and assistance. 
![image](https://user-images.githubusercontent.com/47729697/56932221-dd3c0f80-6ab0-11e9-9e0d-8d2e39b2a94d.png)

update: I figured i would unplug the screen to remove it as a source of the issue, same issue persists. if it really was an issue with the screen it seems it would be detected earlier on.

**Comment by fluidvoice** [comment]
Could be a network problem. If you are using WiFi try switching to wired/Ethernet.  
The "screen" is not a physical screen. It's a virtual terminal session, "screen" is a Linux command.

**Comment by coinicarus** [comment]
> Could be a network problem. If you are using WiFi try switching to wired/Ethernet.
> The "screen" is not a physical screen. It's a virtual terminal session, "screen" is a Linux command.

Thank you for your help. I was using a wired connection, i started over from scratch again and have now gotten past this point  :)

**Comment by coinicarus** [comment]
see previous comment for resolution, i didnt figure out the root cause. i restarted my blockchain download from the beginning and it went through perfectly this time.
