### ISSUE TITLE
Sent funds to wallet and node rebooted

### ISSUE THREAD

**Issue by bitsam** [raspiblitz/raspiblitz#555]
I have just setup a new node, and selected Funding. I sent funds to the new wallet address, however, i crashed out of the funding screen. When I went back into the funding screen a different wallet address. 

Do both wallets stay on the node? What happens to the first wallet address I have already sent money to? If I create two new addresses and send bitcoin to both, will that fund a single LND wallet?

**Comment by rootzoll** [comment]
LND will create always a new funding address - but all funds will get to the same wallet.
