### ISSUE TITLE
[v1.2 testing] 05hardwareTest.sh ouput screens

### ISSUE THREAD

**Issue by fluidvoice** [raspiblitz/raspiblitz#559]
**(8060 centiGrad)** shown is improper format.  Should this be "**80.6 Celsius**"?
The normal English words for temperature are Fahrenheit and Celsius.
I ran the test while still syncing just for kicks - my CPU is smoking! ;-)

![Screenshot_2019-04-30_23-55-25](https://user-images.githubusercontent.com/373038/57004330-9f201800-6ba4-11e9-8743-7de2dfad8470.png)

**Comment by fluidvoice** [comment]
Also a small typo here:
![Screenshot_2019-05-01_00-07-17](https://user-images.githubusercontent.com/373038/57004396-23729b00-6ba5-11e9-8b93-f00c8ff2ae7e.png)

**Comment by fluidvoice** [comment]
And "FAIL detected" is confusing here.  Nothing has actually failed, has it?  My system is running fine, if a tad warmly ;-)  A better description of what the implications are for these FAIL and WARN messages (what they mean) would help.

> *** Hardware Test Report ***
> 
> RaspiBlitz Hardwaretest v0.1
> Starting sysbench to run for 60 seconds (--max-time=60 --cpu-max-prime=10000)
> 74.1'C 1200/1400 MHz 1.2563V
> --> Temp FAIL detected
> --> Temp WARN detected
> 76.8'C 1200/1400 MHz 1.2563V
> --> Temp FAIL detected
> --> Temp WARN detected
> 77.9'C 1200/1400 MHz 1.2563V
> --> Temp FAIL detected
> --> Temp WARN detected
>

**Comment by rootzoll** [comment]
I chaned temp FAIL to CRITICAL. Typo corrected.
Yeah the Centigrad was a quick way to go forward because I was not finding I working way to convert the number into float again. Its just for us in the support forums, to have a number at all. I leave to make a working conversion to a PR for a future version ;)
