### ISSUE TITLE
error after change of hostname

### ISSUE THREAD

**Issue by vv01f** [raspiblitz/raspiblitz#56]
ref: https://github.com/rootzoll/raspiblitz/blob/77a8f90402cc3a17be98394854b546ec22c89376/build.sdcard/raspbianStretchDesktop.sh#L36

problem: when manually applying the script, this line results in error "unable to resolve host raspberrypi"

measure: applying hostname after other changes such as memory split

relating to such problems I'd like to suggest using `cmd1 && cmd2` in case `cmd2` depends on `cmd1` etc.
common example where to apply this, is usage of `apt-get` or `apt` with the commands `update`, `upgrade` and `install`

**Comment by vv01f** [comment]
relating to such problems I'd like to suggest using `cmd1 && cmd2` in case `cmd2` depends on `cmd1` etc.

**Comment by rootzoll** [comment]
Changing hostname should be already at end of the setup - right before the final reboot. Let me check for leftovers of old code.

**Comment by rootzoll** [comment]
Found it in the manual SD card setup. Good find. Thanks. Will move to the end before reboot / LCD setup.
