### ISSUE TITLE
[v1.2 testing] working but with startup circular/timing related errors

### ISSUE THREAD

**Issue by fluidvoice** [raspiblitz/raspiblitz#561]
I got in a circular error state where the script hits the below error every time it boots up which brings up the dialog to recreate the blockchain.  The debug.log should be fresh on each boot but it's not.  Everything was working so I'm not sure why **'Please restart with -reindex or -reindex-chainstate to recover'** showed up in the debug.log, perhaps my date/time not set correctly?  Anyway I ctrl-c out of the blockchain re-do dialog, then I deleted debug.log to clear out the -reindex statements and rebooted.  Then I got an error about debug.log not found.  But after some time later not sure, the debug.log was created again - probably when the bitcoind.service was auto-restarted.  Then everything progressed as normal.

https://github.com/rootzoll/raspiblitz/blob/aaed704014a077da66bd4c1f8034618af9fa70a2/home.admin/00mainMenu.sh#L170

>         reindex=$(sudo cat /mnt/hdd/${network}/debug.log | grep -c 'Please restart with -reindex or -reindex-chainstate to recover')

**Comment by fluidvoice** [comment]
Actually everything did not work right away after that. Then when running `00mainMenu.sh` I got:

> ****************************************
> * The LND service is not running.
> ****************************************
> If you just started some config/setup, this might be OK.
> 
> 2 RESTARTS DETECTED - LND might be in a error loop
> 
> -> Use following command to debug: /home/admin/XXdebugLogs.sh
> -> To force Main Menu run: /home/admin/00mainMenu.sh
> -> To try restart: sudo shutdown -r now
> 
so I did `sudo reboot now`
then went to cmd line and 
`sudo tail -f /mnt/hdd/bitcoin/debug.log` and waited for bitcoind sync to finish
then ran 00mainMenu.sh, unlocked my wallet, and opened the status screen.
At this point, LND showed in red not started/ready yet.
I tailed the lnd.log and it showed wallet needs to be unlocked.
So then I ran 00mainMenu.sh again, it unlocked the wallet, and finally showed the status screen showing everything running correctly.   **There seems to be some timing related issues here... if you don't wait long enough it appears that things are not running correctly.**  I need to test just running the menu system and waiting long enough is sufficient for everything starting up correctly.

![Screenshot_2019-05-01_03-56-14](https://user-images.githubusercontent.com/373038/57008246-19f92b00-6bc5-11e9-8e2b-b936d7299409.png)

**Comment by fluidvoice** [comment]
After that I ctrl-c out of that status screen and saw this:
![Screenshot_2019-05-01_04-00-42](https://user-images.githubusercontent.com/373038/57008345-c9ce9880-6bc5-11e9-81d6-8efefeebe291.png)

**Comment by fluidvoice** [comment]
`/home/admin/XXdebugLogs.sh | nc termbin.com 9999`
https://termbin.com/485n

**Comment by fluidvoice** [comment]
OK, so then tried again from scratch:
`sudo reboot now`
waited for the node to come up, then SSH in and let it go to the "initial boot" menu. 
If I then let the go through all the menu screens as normal everything eventually comes up OK.
So it looks like maybe the only problem(s) is not clearing out the debug.log (and perhaps journalctl) as these files are used to look for errors and might find error from a prior boot.

**Comment by rootzoll** [comment]
I added the deletion of bitcoin & lnd log files on every boot. I thinkthats OK now, because the log errors are still in the systemd journals and seen in XXdebugLogs.sh in the case we have to debug a error case where the system starts to reboot. The error in journal logs are not used to detect the error loops.

**Comment by rootzoll** [comment]
That the "chain not synced" in the status screen is a non critical timing issue - happens sometime.

**Comment by rootzoll** [comment]
I incresed the restartCount to 4 for LND before it will detect a loop error - so just in case a error goes away with an additional unlocking

**Comment by nyxnor** [comment]
pls close this.
