### ISSUE TITLE
detailed wallet balance error

### ISSUE THREAD

**Issue by tibxfool** [raspiblitz/raspiblitz#563]
Hi All,

After a fresh new build I am having problems running the balance command from the menu and get the following error. How is it that after a fresh install the error occurs. Used the same image as previous installs, raspiblitz-v1.1-2019-03-18.img.gz. Very strange because I never had the error after a new install. Zap IOS wallet connects ok and shows correct balance.

**./00mainMenu.sh: line 419: lnbalance: command not found**

  RaspiBlitz v1.1  Tibxfool
               bitcoin Fullnode + Lightning Network
        ,/     -------------------------------------------
      ,'/      load average: 1.14, 1.16, 1.24, CPU 59°C
    ,' /       Free Mem 350M / 927M  Free HDD 594G (64%)
  ,'  /_____,  ssh admin@192.168.178.11 ▼3.0GiB ▲1.8GiB
 .'____    ,'
      /  ,'    bitcoin v0.17.0.1 mainnet Sync OK (100.00%)
     / ,'      Public 83.84.179.176:8333 38 connections
    /,'
   /'          LND 0.5.2-beta wallet 96927 sat
               0/1 Channels 353812 sat 7 peers

Thanks for your help

**Comment by fluidvoice** [comment]
This is a small error in the v1.2 scripts.  To fix it try this from a SSH command line:

`wget https://stadicus.github.io/RaspiBolt/resources/lnbalance`
`wget https://stadicus.github.io/RaspiBolt/resources/lnchannels`
`chmod +x lnbalance && chmod +x lnchannels`
`sudo cp lnchannels /usr/local/bin && sudo cp lnbalance /usr/local/bin`

**Comment by fluidvoice** [comment]
oh, sorry @fdvanoye I thought you were using v1.2 but it may be that running the above lines still fixes your problem?  @stadicus may have moved this stuff. 
cc: @rootzoll

**Comment by Stadicus** [comment]
I was not aware that other scripts depend on my repository, otherwise I might have been more careful with renaming stuff. Could be a good idea to port these two scripts directly into the RaspiBlitz repo, as they are not mine but by @robclark56 anyway.

**Comment by geco91** [comment]
Recommend this to be fixed in v1.3 - adding scripts to RaspiBlitz repo makes sense.

**Comment by rootzoll** [comment]
Listed to be fixed in v1.3 release.

**Comment by tibxfool** [comment]
Was away for a few weeks abroad, sorry for the late reply. Ran the commands as suggested by fluidvoice. Lightning filtering blockchain after a few weeks rest. Hope to get 1.3 installed soon, thx for your help!

**Comment by tibxfool** [comment]
Morning, the scripts fixed the problem :-). Will go for the 1.2 upgrade now. Thanks!

**Comment by tibxfool** [comment]
FYI, installed 1.2 and had the same wallet balance error again. Ran the suggested fluidvoice commands and got it working again.
