### ISSUE TITLE
Fixing TOR on/off switching

### ISSUE THREAD

**Issue by HonmaSokyu** [raspiblitz/raspiblitz#564]
I just updated my raspi to 1.2 version and I cant connect anymore?

Please Help :)

Thank you very much ;)

Debug Log:
https://termbin.com/wuqn

Main screen:
https://imgur.com/0J9VVRo

**Comment by fluidvoice** [comment]
might be a networking problem.  Are you using ethernet or wifi? 
post the URL of running this (all one line):
`sudo cat /mnt/hdd/bitcoin/bitcoin.conf && sudo cat /mnt/hdd/lnd/lnd.conf && sudo cat /mnt/hdd/bitcoin/debug.log | nc termbin.com 9999`
also note that you might have a power supply problem as 1.2 volts is below adequate level.
Please run the hardwaretest script:

> *** HARDWARE TEST RESULTS ***
> UndervoltageReports in Logs: 0
> powerFAIL=0
> powerWARN=1
> powerMIN='1200000 microVolt'
> tempFAIL=0
> tempWARN=6
> tempMAX='6770 centiGrad'
> IMPORTANT: There are some hardware issues with your setup.
> 'Run Hardwaretest' in main menu or: **sudo /home/admin/05hardwareTest.sh**
>

**Comment by HonmaSokyu** [comment]
Thanks for the fast reply :)

Im using Ethernet, like before with 1.1 version.

URL: https://termbin.com/npyu

I bought the power supply for EU of Amazon from the list on raspiblitz. Which one to buy then?

**Comment by fluidvoice** [comment]
> Thanks for the fast reply :)
> 
> Im using Ethernet, like before with 1.1 version.
> 
> URL: https://termbin.com/npyu
> 
> I bought the power supply for EU of Amazon from the list on raspiblitz. Which one to buy then?

Lots of network socket errors:
> 2019-05-03T17:48:40Z socket send error Broken pipe (32) 

and failure to reach TOR hosts...
> 2019-05-03T17:47:44Z Socks5() connect to e6g4kddog7nac23w.onion:8333 failed: host unreachable
> 2019-05-03T17:47:50Z Socks5() connect to ndndword5lpb7eex.onion:8333 failed: host unreachable

**Comment by fluidvoice** [comment]
I want to see what's in your config files:
`sudo cat /mnt/hdd/bitcoin/bitcoin.conf`
`sudo cat /mnt/hdd/lnd/lnd.conf`

**Comment by HonmaSokyu** [comment]
Bitcoin.conf:
rpcport=8332
rpcallowip=127.0.0.1
rpcbind=127.0.0.1:8332
onlynet=onion
addnode=fno4aakpl6sg6y47.onion
addnode=toguvy5upyuctudx.onion
addnode=ndndword5lpb7eex.onion
addnode=6m2iqgnqjxh7ulyk.onion
addnode=5tuxetn7tar3q5kp.onion

LND.conf:
# lnd configuration

[Application Options]
debuglevel=info
maxpendingchannels=5
alias=UlaLa
color=#68F442
nat=false

# RPC open to all connections on Port 10009
rpclisten=0.0.0.0:10009
# REST open to all connections on Port 8080
restlisten=0.0.0.0:8080
# Domain, could use https://freedns.afraid.org
tlsextradomain=tty.sdf.org
tlsextraip=0.0.0.0

[Bitcoin]
bitcoin.active=1
bitcoin.node=bitcoind
# enable either testnet or mainnet
#bitcoin.testnet=1
bitcoin.mainnet=1

[Bitcoind]
bitcoind.rpcuser=raspibolt
bitcoind.rpcpass=
bitcoind.rpchost=127.0.0.1
bitcoind.zmqpubrawblock=tcp://*:28332
bitcoind.zmqpubrawtx=tcp://*:28333

[autopilot]
autopilot.active=0
autopilot.maxchannels=5
autopilot.allocation=0.6

**Comment by fluidvoice** [comment]
That's the problem. Your **bitcoin.conf** file is missing a bunch of entries.  Now the question is how/why is this?  I didn't have this problem when I upgraded to v1.2

**Comment by HonmaSokyu** [comment]
Dont know. I didnt change anything, dont even know how to change something in those files?

So we just have to change some lines? Please guide me ;) Will donate some sats :D

**Comment by fluidvoice** [comment]
I was trying to see if there is a Raspiblitz log that might show this file getting over-written or something. 
When you installed, the menu system prompted you to re-enter some passwords right?

**Comment by HonmaSokyu** [comment]
Right...

**Comment by fluidvoice** [comment]
looks possible it was overwritten here. Need to verify with @rootzoll 
https://github.com/rootzoll/raspiblitz/blob/480a67729081cdd81357f508c0174b9ce05fa38e/home.admin/config.scripts/internet.tor.sh#L191

Did you have TOR already enabled in v1.1 before upgrading or did you turn it on after upgrading?

**Comment by fluidvoice** [comment]
please prepend the title of this issue with "[v1.2]" to bring more attention to it.

**Comment by HonmaSokyu** [comment]
WIth 1.1 i tried DNS and it didnt work. So then i tried with TOR and worked just fine from the start. I connected to peers and opened channels and funded them with RTL web and ZAP mobile.

Then today i upgraded to 1.2 and from start it worked but then i tried to "Forwarding Ports by autossh Tunnel" so i could connect outside my network and I failed :)

Allready tried flashing SD card again but no luck :)

Try again from scratch? or? :)

**Comment by fluidvoice** [comment]
> i upgraded to 1.2 and from start it worked
 
Interesting. I had similar... v1.2 worked at first (without TOR) then failed after I added TOR and poked around with some other things (that I don't remember), but mine failed in a different way than you with different error - add my config file was not over-written like yours.

**Comment by fluidvoice** [comment]
try resetting your bitcoin.conf file back to default:
`sudo cp /home/admin/assets/bitcoin.conf /mnt/hdd/bitcoin/bitcoin.conf`
then edit **/mnt/hdd/bitcoin/bitcoin.conf** `sudo nano /mnt/hdd/bitcoin/bitcoin.conf`
and change "rpcpassword=" set to your passwordB
then restart:
`sudo reboot now`

**Comment by fluidvoice** [comment]
> Then today i upgraded to 1.2 and from start it worked but then i tried to "Forwarding Ports by autossh Tunnel" so i could connect outside my network and I failed :)

so what exactly did you do to enable autossh tunnel, before it started failing, you ran this or something else?... **`/home/admin/config.scripts/internet.sshtunnel.py`**

**Comment by HonmaSokyu** [comment]
Thanks! That helped. Getting back online :)
Send me an invoice for 100k sat ill pay it :)

I ran this " /home/admin/config.scripts/internet.sshtunnel.py on test@raspiblitz.com "10009<20009" " and enabled DNS.

**Comment by fluidvoice** [comment]
I have a tip link on my profile page here on Github :)

**Comment by fluidvoice** [comment]
@rootzoll is there a potential problem here?

> I ran this " /home/admin/config.scripts/internet.sshtunnel.py on [test@raspiblitz.com](mailto:test@raspiblitz.com) "10009<20009" " and enabled DNS.

**Comment by HonmaSokyu** [comment]
Just for clarification "test@raspiblitz.com" was replaced by "tty.sdf.org".

**Comment by ghost** [comment]
Have the same issue, appears on my Pi with v1.2 when I deactivated TOR in the advanced settings - maybe this helps in finding the bug.

**Comment by fluidvoice** [comment]
> Have the same issue, appears on my Pi with v1.2 when I deactivated TOR in the advanced settings - maybe this helps in finding the bug.

When you deactivated TOR, what exactly happened and you saw?  The password error?
@rootzoll another guy I think saw this too.  A bug in there somewhere?

**Comment by rootzoll** [comment]
Since v1.2 it should make sure on every restart, that the RPC passwords are in sync between butcoind/lnd config - but not sure whats happening if they are completly missing. I will put this on the test list for 1.3 release.

TODO: Test switching between TOR/non-TOR ... see if bitcoind/lnd conf stays stable

**Comment by rootzoll** [comment]
OK with v1.3 the missing of RPC username/password on the switch off of TOR should be fixed.
