### ISSUE TITLE
Everything stops after Torrents are downloading for some minutes

### ISSUE THREAD

**Issue by asdbaba** [raspiblitz/raspiblitz#566]
Can't ssh back in and downloading is stuck
Can't type x or anything just cut the power
This happened also with version 1.1, I'm on 1.2, 1.0 doesn't have this issue but torrent is outdated and it takes forever to sync

**Comment by fluidvoice** [comment]
Instead of SSH, plug a keyboard into your Pi and use Alt+F2 and login as user 'admin'

**Comment by asdbaba** [comment]
Wasn't able to Alt+F2 not even with keyboard input, but after the night I was able to ssh back in and now everything works. I think downloading the torrents something got stuck for a while
