### ISSUE TITLE
Update to lnd 0.7.1 & bitcoin 0.18.0

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#568]
https://github.com/lightningnetwork/lnd/releases
Check if 0.6.1 is out of RC.

- remove LND restart on external IP change?

**Comment by bitsam** [comment]
Looks like 0.6.1 is now in beta.

**Comment by openoms** [comment]
Can update now:
https://github.com/openoms/bitcoin-tutorials/blob/master/lnd.update.v0.6.1-beta.sh

` wget https://raw.githubusercontent.com/openoms/bitcoin-tutorials/master/lnd.update.v0.6.1-beta.sh && sudo bash lnd.update.v0.6.1-beta.sh`

Tested on multiple nodes already: https://twitter.com/openoms/status/1126937869778673664

**Comment by Omicron59** [comment]
Hi thanks to you @openoms , it works perfectly on the rapiblitz 1.2 :+1:

**Comment by rootzoll** [comment]
Keep bitcoin to 0.17.1 until LND >=0.6.2 ... see: https://twitter.com/alexbosworth/status/1129402043360108545

**Comment by openoms** [comment]
Downgraded for the incoming PR (and my test branch) https://github.com/rootzoll/raspiblitz/pull/597/commits/6821b14edc082d9951c14468001c9df36dc0bad0

**Comment by rootzoll** [comment]
lnd 0.7 is getting prepared and should be ready when 1.3 is ready:
https://github.com/lightningnetwork/lnd/releases/tag/v0.7.0-beta-rc1
-> best hope to fix: #638
-> lucky shot to fix: #632

then we also can update bitcoind to 0.18
https://github.com/bitcoin/bitcoin/releases/tag/v0.18.0

**Comment by openoms** [comment]
Should update Go to v1.12.6 as well.
`The binaries are compiled with go1.12.6`

RTL is also updated to v0.4.1 now https://github.com/ShahanaFarooqui/RTL/releases

**Comment by rootzoll** [comment]
RTL Update --> #660
Go Updated

O TODO: Update Protobuffs for LND 0.7

**Comment by openoms** [comment]
Made a temporary update script to help testing lnd v0.7.0-beta-rc1:
`wget https://raw.githubusercontent.com/openoms/bitcoin-tutorials/master/lnd.update.v0.7.0-beta-rc1.sh && sudo bash lnd.update.v0.7.0-beta-rc1.sh`
![Screenshot from 2019-06-18 22-12-40](https://user-images.githubusercontent.com/43343391/59720275-4d942100-9216-11e9-9a90-9b2de173ce1f.png)

**Comment by openoms** [comment]
lnd v0.7.0-beta-rc2 is out: https://github.com/lightningnetwork/lnd/releases/tag/v0.7.0-beta-rc2
>We’re targeting lnd v0.7.1. to fix these remaining RPC compatibility issues.

Full compatibility with Bitcoin Core 0.18 is aimed for lnd v0.7.1 so we too should stay on Bitcoin Core v 0.17.1

Update script to test this new version: https://github.com/openoms/bitcoin-tutorials/blob/master/lnd.update.v0.7.0-beta-rc2.sh
`$ wget https://raw.githubusercontent.com/openoms/bitcoin-tutorials/master/lnd.update.v0.7.0-beta-rc2.sh && sudo bash lnd.update.v0.7.0-beta-rc2.sh`

**Comment by rootzoll** [comment]
OK - LND 0.7.0 will now running with v1.3 release.

**Comment by rootzoll** [comment]
LCD 0.7.1 got released and we got confirmation that its working with bitcoin 0.18.0.
Updated to that versions for v1.3 release.
