### ISSUE TITLE
lnd wallet recreate without input wallet password

### ISSUE THREAD

**Issue by livestradamus** [raspiblitz/raspiblitz#569]
How do I delete an existing lnd wallet?
I've deleted all underneath /home/admin/.lnd but it still asks for input wallet password (which I don't remember)
But at start I still get:
`Unlock LND Wallet --> lncli --chain=bitcoin unlock`

I've deleted all under /home/admin/.lnd, reentered the seed and at the end get this
`[lncli] rpc error: code = Unknown desc = wallet already exists`

**Comment by fluidvoice** [comment]
`sudo systemctl stop lnd.service`
`sudo rm -f /mnt/hdd/lnd/data/chain/bitcoin/mainnet/wallet.db`
`sudo reboot now`

**Comment by livestradamus** [comment]
Thank you.
