### ISSUE TITLE
missing permissions (here still inline sudo)

### ISSUE THREAD

**Issue by vv01f** [raspiblitz/raspiblitz#57]
https://github.com/rootzoll/raspiblitz/blob/77a8f90402cc3a17be98394854b546ec22c89376/build.sdcard/raspbianStretchDesktop.sh#L235

still in dir `/home/admin/download` and current user will not have write permission for wget

as well as

https://github.com/rootzoll/raspiblitz/blob/77a8f90402cc3a17be98394854b546ec22c89376/build.sdcard/raspbianStretchDesktop.sh#L327

 and

https://github.com/rootzoll/raspiblitz/blob/77a8f90402cc3a17be98394854b546ec22c89376/build.sdcard/raspbianStretchDesktop.sh#L328

in  dir `/home/admin`

I suggest

1. putting grouped commands such as installation for bitcoin, litecoind and lightning in functions, this way the user can be set on calling the function rather than on every command – also it would make it easier to have the user calling e.g. to install litecoin but not bitcoin or any other combination of provided other client/blockchain etc. 
2. before proceeding with a file, check `test -f ${fn}` is recommended or check on success for previous command (with e.g. `&&` or `test $? -eq 0`)
3. checking once in the beginning of a script if the needed rights are given and reject any execution if so, e.g.:

```
#!/bin/sh
# first check if user is root or script was run with privileges (e.g. sudo)
# such functions can be written once in a library-script
# and used several times after `source lib.sh` 
function requireRights() {
  {
    test "$UID" = "0" || test "$EUID" = "0" || test $(id -u) -eq 0
  } || {
    printf "%s\n" "This script must be run with root privileges!" 1>&2 && exit 1
  }
}

requireRights
```

**Comment by rootzoll** [comment]
The go zip gets deleted after installed - so should be OK there.
The LCD-show i will let own the admin in the future.
The raspbianStretchDesktop.sh is used just once with user pi if user wants to build own SD card image - so I like to keep it linear - functions maybe a bit to much at this point.
To add some checkpoints if files exist (to check on success of prior actions) makes sense to prevent follow up errors. Thanks for the input.
