### ISSUE TITLE
Bash autocomplete fixed

### ISSUE THREAD

**Issue by chacham18** [raspiblitz/raspiblitz#571]
After installing the latest release, lncli bash_completion is not working. I get general bash autocomplete, but not for lncli. I believe this is something that was forgotten - probably this code? https://github.com/breez/lightninglib/blob/master/contrib/lncli.bash-completion

Please advise and let me know if you encounter the same issue. I tested ssh on 2 different machines with same results.

**Comment by fluidvoice** [comment]
Raspiblitz has nothing to do with how the `lncli` or `lnd` operate.  It doesn't even compile them.  It just installs and configures the already compiled binaries.  You should ask the LND dev's and/or open an issue with them.

**Comment by chacham18** [comment]
> https://github.com/breez/lightninglib/blob/master/contrib/lncli.bash-completion

Not sure why it happened, but I've just created a file named lncli within the /etc/bash_completion.d/ folder with the code above and now autocomplete works now. If you experience the same problem with your raspiblitz and want bash_completion to work, this is the quick fix instead of waiting for LND to fix their compiled binaries.

**Comment by chacham18** [comment]
Also, now I see that this was added to a the 91addBonus.sh script - why it is not installed by default as before?

**Comment by fluidvoice** [comment]
the comment in the script says why @rootzoll commented it out in that script... 

> "(auto install deactivated to reduce third party repos)"

**Comment by chacham18** [comment]
Ok. But it contains 2 important functions that are still part of the main menu interface - the listing of channels and of balance. Right now, it shows error message if user selects lnchannels or lnbalance from the ./00mainmenu.sh after fresh install.

**Comment by fluidvoice** [comment]
Yeah, I saw that reported by another user/issue.   Thanks for reporting this! 
 https://github.com/rootzoll/raspiblitz/issues/563#issuecomment-489416235

**Comment by geco91** [comment]
The call of this script could have slipped on the setup refactoring - recommend this to be fixed in v1.3 again.

**Comment by rootzoll** [comment]
Listed to be fixed in v1.3 release

**Comment by rootzoll** [comment]
OK. Implemented fix for v1.3 - needs final testing.

**Comment by rootzoll** [comment]
testing looks good. This fix will be part of 1.3 release.
