### ISSUE TITLE
RESEARCH: enable 2-factor/phone auth for SSH

### ISSUE THREAD

**Issue by fluidvoice** [raspiblitz/raspiblitz#577]
supposedly it's possible.  Helpful?
https://www.cnx-software.com/2019/05/03/two-factor-authentication-ssh-armbian/
![Armbian-Two-Factor-Authentication-SSH](https://user-images.githubusercontent.com/373038/57200897-81b5ca00-6f67-11e9-9b4c-eb65be751181.png)

**Comment by CommanderPoe** [comment]
Would something like this mean that i can securely open the port 22 so i can ssh from anywhere in the world from my cellphone without being worried about my security 24/7 ? If so, A big YES !

**Comment by geco91** [comment]
That could be an interesting option. The tutorial is aimed at armbian OS ... but there is also a link to setup with custom debian. Can anybody try this and confirm that it is working also on rasbian?

https://www.vultr.com/docs/how-to-setup-two-factor-authentication-2fa-for-ssh-on-debian-9-using-google-authenticator

BUT: If it involves installing some third-party code (on the RaspiBlitz) - that is not part of debian packages, I would not recommend to add this feature.

**Comment by nyxnor** [comment]
[Authy ](https://raw.github.com/authy/authy-ssh/master/authy-ssh)option, but it is [unmantained](https://github.com/authy/authy-ssh/blob/master/authy-ssh).
[There is authrelia, maintained but written in go.](https://github.com/authelia/authelia)
Url type: https://stackpointer.io/unix/linux-totp-password-generator/629/

**Comment by nyxnor** [comment]
https://github.com/rootzoll/raspiblitz/issues/1681#issuecomment-854552788
Openoms gave a better guide here with multiple options.
