### ISSUE TITLE
--force-yes is deprecated

### ISSUE THREAD

**Issue by vv01f** [raspiblitz/raspiblitz#58]
according to man, for `apt` resp. `apt-get` the option `force-yes` should be replaced by either of 
`--allow-unauthenticated`, `--allow-downgrades`, `--allow-remove-essential` and `--allow-change-held-packages` while needed

**Comment by rootzoll** [comment]
@vv01f Which of these options would you recommend to replace `force-yes`?

**Comment by vv01f** [comment]
well, help-packages sounds like nobrainer, the others seem to be serious and should only be added after test and when deemed necessary – so better not for a whole list of packages

another idea was to write packages in a simple list to be installed, uninstalled etc. – this way users can simply add/remove things to their needs without touching the scripts.
in such a file the options could be added simply to be split off and merged in the command while iteration.
