### ISSUE TITLE
Display don't work after driver install

### ISSUE THREAD

**Issue by ghost** [raspiblitz/raspiblitz#582]
I bought a display via eBay to get it to work for my Raspiblitz Pi. The display is already mounted and enlightens, but nothing is shown after installment of the drivers.

Maybe you can help me.

I did the following steps:

I got the drivers from here --> http://en.kedei.net/raspberry/raspberry.html

It's the LCD_show_v6_1_3

1.) So i ssh into the Raspiblitz
2.) Downloading the drivers with sudo wget "http://en.kedei.net/raspberry/v6_1/LCD_show_v6_1_3.tar.gz"
3.) Unpacking tar -xzvf LCD_show_v6_1_3.tar.gz

Following the other steps below. Everything finishes successfully and Pi is rebooting, but after reboot nothing is shown on the display.

**Description for installation from the display manufacturer:**

b. Using the drive.

 1. Writing your own image files to the SD card, and start the Raspberry Pi

 2. Ensure that the network connection is normal

 3. The LCD screen and the Raspberry Pi board is properly connected

 4. Copy the driver to raspberry pi (using ssh or use U disk medium mounted)

 5. Unzip the file and start the installation.

      First expansion sd card    sudo raspi-config select expand_roofts then sudo reboot

     Restart enter the following command:

    Unzip the file      tar -xzvf LCD_show_v6.tar.gz

    Jumped into a folder       cd LCD_show_v6

    To upgrade the system update        sudo apt-get update

      Backup data       sudo ./LCD_backup

    Install the driver       sudo ./LCD35_v

    Wait for some time and the system will install the driver automatically restarts

    If you want to re-use before installing the system, you can use       sudo ./LCD_restore

 

    Note: Before you update your system, you must use at the command sudo apt-mark hold raspberrypi-bootloader

    Then use the following command,

    sudo apt-get update

    sudo apt-get upgrade

 Otherwise it will fail in the future may restart

**Comment by geco91** [comment]
Using other LCDs then in the recommended shopping list is experimental.
You may need to uninstall the other LCD driver first? Not sure.
See doc of preinstalled LCD driver: https://github.com/goodtft/LCD-show

I recommend to keep this issue open for some days for community comments and then to close it.

**Comment by ghost** [comment]
I don't think the the display has some hardware error, seems to be a problem with the driver installation, maybe you have an idea if the not defined path is OK or do I need to extract it into another path of the Raspiblitz installation to get it to work?

**Comment by ghost** [comment]
Just did some restarts of the Pi and each time it is booting again it shows for some seconds the first screen on the photo, before and afterwards the display stays again white but enlighted.

![Screenshot_20190508-182328](https://user-images.githubusercontent.com/38157132/57391457-e61e9680-71be-11e9-96fc-c802693aee80.jpg)
![Screenshot_20190508-182334](https://user-images.githubusercontent.com/38157132/57391458-e61e9680-71be-11e9-8fa4-818185939d58.jpg)

**Comment by openoms** [comment]
Please post a picture of the back of the LCD panel. Also could be helpful to see the link to the product (where you bought from).

**Comment by ghost** [comment]
Link to the product: https://www.ebay.at/itm/3-5-TFT-LCD-Touch-Screen-Module-320-480-RGB-Display-Case-For-Raspberry-Pi/391223449334?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2060353.m2749.l2649

This is a photo of the backside of the display - hope you can read it (don't want to unmount it again, it's a KeDei:

![IMG_20190512_205419](https://user-images.githubusercontent.com/38157132/57586650-0d47d180-74f9-11e9-873f-f5453b1e6e85.jpg)

The link to the driver is in my first post.

I tried the display with the official Raspbian OS and the mentioned driver, it works without any problems. The issue only occurs with Raspiblitz OS.

**Comment by openoms** [comment]
> The link to the driver is in my first post.
> 
> I tried the display with the official Raspbian OS and the mentioned driver, it works without any problems. The issue only occurs with Raspiblitz OS.

The RaspiBlitz is not an OS, it is a collection of helper scripts/GUI running on the Raspbian OS.

Did you try the display only with the default settings (clean Raspiblitz 1.2 SD card)? Does it work during boot the same way? 

It is probably that KeDei driver messing up something.
There are two drivers you could try on the linked site. Test the other one as well.

Can test driver for the default screen in the shopping list as well (easier if you you just burn a new SD): 
```
sudo rm -rf LCD-show
git clone https://github.com/goodtft/LCD-show.git
chmod -R 755 LCD-show
cd LCD-show/
sudo ./LCD35-show
```

**Comment by ghost** [comment]
I will try the other driver in the next days but think this will also not work.

Yes, I tried the display with default settings on clean Raspiblitz 1.2 SD card. It just shows for 2 or 3 seconds the commands on the screenshot above, after that it's only enlighted.

> Can test driver for the default screen in the shopping list as well (easier if you you just burn a new SD):

> 

You mean that I should test it with this commands again?

**Comment by thelwyn** [comment]
I initially got an LCD from kedei in China too and couldn't get it to work me neither with the same driver that you got from their website, following the same steps. I suspect there was a conflict with the preinstalled driver from Raspiblitz but I didn't have time to look more and just bought another one that worked immediately with the provided driver.

**Comment by ghost** [comment]
Seems we are sitting in the same boat :) Will also try another one.
