### ISSUE TITLE
[Feature Request] SSL for RTL

### ISSUE THREAD

**Issue by benthecarman** [raspiblitz/raspiblitz#583]
Would be nice if there was an option to enable SSL for RTL and a script would automatically do the setup required.

**Comment by geco91** [comment]
This is part of the open research issue to add a NGINX server that then can manage a HTTPS cert:
https://github.com/rootzoll/raspiblitz/issues/255

Until then its recommended to use RTL just within your local network.
I recommend this issue to close - because its part already of an open issue.

**Comment by benthecarman** [comment]
Did not see that issue, will close
