### ISSUE TITLE
LND password error

### ISSUE THREAD

**Issue by btc21cluib** [raspiblitz/raspiblitz#586]
LND not running
when I try lncli unlock
I get
[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"

here the debug link https://termbin.com/432a

**Comment by fluidvoice** [comment]
Looks like the wrong wallet password was entered.  So the password is not what you are entering.

**Comment by btc21cluib** [comment]
no password I correct - now after now blockchain download I got this error:
[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"
Here are my debug log:
https://termbin.com/sk3x

**Comment by fluidvoice** [comment]
Looks like possible data corruption...
> [ERR] SRVR: unable to create server: unable to read bucket for chain

possibly because your power supply is weak (only 1.2 volts)
I recommend to get a better power supply and re-install as per the docs and FAQ

**Comment by btc21cluib** [comment]
So Problem solved after many many useless try. 
The best is to follow the 1) Recover LND data
https://github.com/rootzoll/raspiblitz/blob/master/FAQ.md
right now its not finish but looks totally good for me
                 ┌──────── Node is Syncing (136) ──────────┐
                 │  Blockchain Progress :  98.45 %         │  
                 │  Lightning Progress  : prepare sync     │  
 
Thank´s rootzoll for your good work.

**Comment by fluidvoice** [comment]
> So Problem solved after many many useless try.
> The best is to follow the 1) Recover LND data
> https://github.com/rootzoll/raspiblitz/blob/master/FAQ.md
> right now its not finish but looks totally good for me
> ┌──────── Node is Syncing (136) ──────────┐
> │ Blockchain Progress : 98.45 % │
> │ Lightning Progress : prepare sync │
> 
> Thank´s rootzoll for your good work.

Did you by chance enable TOR then disabled it later?  Could that be what caused the problem?

**Comment by btc21cluib** [comment]
@fluidvoice  I never enable TOR. You think I should try?
My syncronization is now 99.92%, I'll wait for the 100, and it shouldn t work, I'll try.
