### ISSUE TITLE
lnd.setaddress script "set locale"

### ISSUE THREAD

**Issue by cryptomulde** [raspiblitz/raspiblitz#587]
Hello,

in version 1.1 I just manually edited the raspiblitz.conf in my hdd folder to change the ip addresses. Sometimes after reboots I had to manually readjust them.
In the config script there is this "lnd.setaddress.sh" and what I understood it will fix raspiblitz.conf manually to an ip-address of my choice.
So far so good. I tried to set the IP and I receive this error message.

![image](https://user-images.githubusercontent.com/48246159/57434277-eceaef00-723a-11e9-95d1-1d5c7f405d07.png)

I tried to fix it with the help of google, but none of those worked and after reboot I am getting the same issues. 

EDIT: node seems to be reachable via custom ip when I check bitnodes, but does not show in 00InfoBlitz.sh and raspiblitz.conf changes back randomly. So to me it seems this is just a "beauty-issue" and it works like intended. Only shows wrong numbers in infoscreen.

**Comment by rootzoll** [comment]
I will take a look at this for the next release. After reboot RaspiBlitz should only change the "publiIcIP" entry (that is always the public IP of your router) but not the "lndAddress" value, that will be used instead if available.

**Comment by cryptomulde** [comment]
Is there any way to manipulate the "publicIP" field with a custom-manual set one?

**Comment by rootzoll** [comment]
The value "publicIP" is getting ignored once "lndAddress" is set ... so why manipulate it? Setting "lndAddress" is the way to do that.

**Comment by cryptomulde** [comment]
Ok, will wait for the next release then.

**Comment by rootzoll** [comment]
I tested `lnd.setaddress.sh`and was able to set a fixed domain or IP and it was displayed on the LCD. 
Also I dont get that perl warning on my machine.
So I mark this issue as "final testing" and may close this on v1.3 release if there is not more input on this. But feel free to open it up again if the v1.3 still having the issue.
