### ISSUE TITLE
Fix: missing debug.log file on hdd message

### ISSUE THREAD

**Issue by gehrlein** [raspiblitz/raspiblitz#588]
When starting up the Raspiblitz (v1.2) it shows the following issue:

![Untitled](https://user-images.githubusercontent.com/26669810/57447306-16197880-7257-11e9-8769-4d4a2836b364.png)

This is uncritical issue since everything afterwards works just fine.

**Comment by rootzoll** [comment]
added fix for this - will be part of v1.3 release.

**Comment by rootzoll** [comment]
Do final testing for v1.3 release.

**Comment by rootzoll** [comment]
This is now fixed for v1.3 release.
