### ISSUE TITLE
never trust user input: e.g. when no whitespaces allowed

### ISSUE THREAD

**Issue by vv01f** [raspiblitz/raspiblitz#59]
https://github.com/rootzoll/raspiblitz/blob/d85e63c5c573d7e01a86cdfc38c6054557c2ce76/home.admin/20initDialog.sh#L14

just replace possible whitespaces with e.g. `result=$( cat $_temp | tr -d [:space:] )` before writing to system files

**Comment by rootzoll** [comment]
merged. thx.
