### ISSUE TITLE
Fresh install - stuck on Hashing 13%

### ISSUE THREAD

**Issue by scarzie** [raspiblitz/raspiblitz#591]
I'm just setting up my node for the first time and I'm up to the point where I've downloaded the blockchain and now it is hashing - it says I'm "Hashing: Checking Hash [13%]" 30800.0 / 224257.5 MB and has been stuck there for some time.

I tried restarting and it started hashing again from 0% and stopped at the exact same point.  I'm leaving it open to see if it will power through at some point, but am hoping that y'all may have some ideas.  Any help is much appreciated!

![Capture](https://user-images.githubusercontent.com/50489543/57529963-289dbb80-7304-11e9-97a4-680f6490e70f.JPG)

**Comment by openoms** [comment]
Press x, delete the downloaded blockchaindata and start again. Your downloaded data is corrupt.
