### ISSUE TITLE
ensure ssh was enabled  

### ISSUE THREAD

**Issue by vv01f** [raspiblitz/raspiblitz#60]
if the user forgot to add the `ssh` to make the pi accessible or sshd was disabled for some reason, maybe the not running service should be recognized and handled.

**Comment by rootzoll** [comment]
I think we can rule this out. There are two scenarios how to setup the raspiblitz:

A) Use the prepared image. In this case the the ssh is enabled by default.
B) Want to build SD card yourself - here you need to add the ssh to enter your fresh rasbian to init setup: https://github.com/rootzoll/raspiblitz#build-the-sd-card-image

In both cases the user will not forget.
