### ISSUE TITLE
XXcleanUp.sh - add resetBlockchain option

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#606]
In some cases people want to trigger a reset on the blockchain data. Add that option to the XXcleanup.sh script and start the "get blockchain" script again and see that it offers reboot when done.

**Comment by btc21cluib** [comment]
How can I add the XXcleanup.sh script ?

**Comment by bitsam** [comment]
+1 , Thanks @rootzoll  that is what I was asking for in issue  #596

**Comment by rootzoll** [comment]
@btc21cluib correction: the script is calles XXcleanHDD.sh and is already part of RaspiBlitz. If you call it, it cleans everything from the HDD (also the LND data), but is keeping the blockchain data ... so you can use the HDD for a fresh RaspiBlitz setup, without the need to download the blockchain data.

What we taking about here is to extend the functionality to also use the script to just delete the blockchain data. That will be part of a future release.

**Comment by rootzoll** [comment]
Added a `-blockchain` parameter to `XXcleanHDD.sh` - that will delete all the blockchain data and trigger the new `XXrepairBlockchain.sh`. To be final tested.

**Comment by rootzoll** [comment]
Tests look good. This is part of v1.3 release.
