### ISSUE TITLE
enhance torrent

### ISSUE THREAD

**Issue by vv01f** [raspiblitz/raspiblitz#61]
the torrent needs quite a while, mainly because it is seeded rarely; this could be changed if the torrent continues to seed later on after setup.

* [ ] dont download blockchain that was not asked for at setup (e.g. bitcoin, dir `testnet3`) – also notice that some coredevs (e.g. Peter Todd) want testnet3 to be much bigger than mainnet to discover size issues while testing first and early in advance
* [ ] add webseed (as the FTP storage) to the torrent file or manually to the torrent
* [ ] priorize files in torrent, e.g.
  + [ ] dir `blocks` high
  + [ ] dir `chanstate` normal as this could be indexed on your own (slow but not crucial data)
* [ ] make use of systemd, `transmission-daemon.service` and config in `/lib/…`, see [this comment](http://www.techjawab.com/2014/08/how-to-install-transmission-on.html#bc_0_33B)
* [ ] switch from `transmission-cli` to `transmission-daemon` [#25](https://github.com/rootzoll/raspiblitz/issues/25)
* [ ] access to status by a limited users would be problematic, so better a separate user "torrent" for running the daemon, other users can be in group "torrent" and have rights to the dirs by that 
* [ ] show download status in infoLCD
* [ ] replace rpc-password `YOUR_PASSWORD_GOES_HERE` with a random string, maybe customized; `sed -i "s/YOUR_PASSWORD_GOES_HERE/"$(< /dev/urandom tr -dc _A-Z-a-z0-9 | head -c${1:-128};echo;)"/" ${path_to_settings_json}`
* [ ] add local ip range besides localhost to rpc-whiteliste
* [ ] possible option to priorize or disable download for main/testnet via `transmission-remote -t ${torrenthash} -pl ${subpath}` (prio low) or `-t ${torrenthash} -G ${subpath}`
* [ ] ensure no download to sdcard to lower wear 
* [ ] `rsync -rtvL` (dont move nor copy; and dereference links) files (while setupState 50) when seeding afterwards is anticipated
* [ ] support RSS feeds with either [flexget.](https://flexget.com/Cookbook/Transmission) or [feedtransmission](https://github.com/lupus78/feedtransmission) – the latter looks smaller
* [ ] list torrents by date-time-stamp and delete until one left or "keep amount"/"free diskspace requirement" is met
* [ ] create dir for torrents and ensure groups/rights
  + [ ] watch-dir `/mnt/hdd/torrents`
  + [ ] download-dir `/mn/hdd/complete`
  + [ ] incomplete-dir `/mnt/hdd/incomplete`

`~/.config/transmission-daemon/settings.json` (old, manual config, better use it in `/etc`)
```
{
    "alt-speed-down": 50,
    "alt-speed-enabled": false,
    "alt-speed-time-begin": 540,
    "alt-speed-time-day": 127,
    "alt-speed-time-enabled": false,
    "alt-speed-time-end": 1020,
    "alt-speed-up": 50,
    "bind-address-ipv4": "0.0.0.0",
    "bind-address-ipv6": "::",
    "blocklist-enabled": true,
    "blocklist-url": "http://john.bitsurge.net/public/biglist.p2p.gz",
    "cache-size-mb": 4,
    "dht-enabled": true,
    "download-dir": "/mnt/hdd/complete",
    "download-queue-enabled": true,
    "download-queue-size": 5,
    "encryption": 1,
    "idle-seeding-limit": 30,
    "idle-seeding-limit-enabled": false,
    "incomplete-dir": "/mnt/hdd/incomplete",
    "incomplete-dir-enabled": false,
    "lpd-enabled": false,
    "message-level": 2,
    "peer-congestion-algorithm": "",
    "peer-id-ttl-hours": 6,
    "peer-limit-global": 200,
    "peer-limit-per-torrent": 50,
    "peer-port": 51413,
    "peer-port-random-high": 65535,
    "peer-port-random-low": 49152,
    "peer-port-random-on-start": false,
    "peer-socket-tos": "default",
    "pex-enabled": true,
    "pidfile": "/mnt/hdd/torrents/d.pid",
    "port-forwarding-enabled": true,
    "preallocation": 1,
    "prefetch-enabled": true,
    "queue-stalled-enabled": true,
    "queue-stalled-minutes": 30,
    "ratio-limit": 2,
    "ratio-limit-enabled": false,
    "rename-partial-files": true,
    "rpc-authentication-required": false,
    "rpc-bind-address": "0.0.0.0",
    "rpc-enabled": true,
    "rpc-host-whitelist": "",
    "rpc-host-whitelist-enabled": false,
    "rpc-password": "YOUR_PASSWORD_GOES_HERE",
    "rpc-port": 9091,
    "rpc-url": "/transmission/",
    "rpc-username": "",
    "rpc-whitelist": "127.0.0.1,10.0.0.*",
    "rpc-whitelist-enabled": true,
    "scrape-paused-torrents-enabled": true,
    "script-torrent-done-enabled": false,
    "script-torrent-done-filename": "",
    "seed-queue-enabled": false,
    "seed-queue-size": 10,
    "speed-limit-down": 100,
    "speed-limit-down-enabled": false,
    "speed-limit-up": 100,
    "speed-limit-up-enabled": false,
    "start-added-torrents": true,
    "trash-original-torrent-files": false,
    "umask": 18,
    "upload-slots-per-torrent": 14,
    "utp-enabled": true,
    "watch-dir": "/mnt/hdd/torrents/",
    "watch-dir-enabled": true
```

`randompwd.sh`
```
#!/bin/sh
len=32
test -z ${1} -o ${1} -lt ${len} 2> /dev/null && {
        len=32
}
< /dev/urandom tr -dc _A-Z-a-z0-9 | head -c${1:-${len}};echo;
```

**Comment by rootzoll** [comment]
Had some similar idea in mind. Never worked with transmission-daemon before, can you point to a good tutorial/guide for debian/rasbian?

**Comment by vv01f** [comment]
woked here:

* just ran it as user admin
* adjusted settings (manually via remote-command, json was updated automatically)
* created directories
* added torrent to watch-dir => started automatically
* still waiting for it to finish while softlink to directory already is in place for user pi to continue

… but will test with a fresh raspbian to ensure it works in the script (like create dirs based on settings file) as well.

**Comment by rootzoll** [comment]
Feel free to make a pullrequest containing the torrent-daemon integration when your tests work out. Can the daemon also subscribe to a RSS where we can publish updated torrents? Old torrents need then to be deleted at one point to free HDD space.

**Comment by vv01f** [comment]
updated ticket on e.g. rss and deleting torrents

**Comment by rootzoll** [comment]
torrents seem to run quite stable in the latest versions - if anyone has detailed instructions how to further improve, please add here .. closing this for now.
