### ISSUE TITLE
Node is syncing (xxx)

### ISSUE THREAD

**Issue by ErwanLetard** [raspiblitz/raspiblitz#620]
Hi, 
I m not sure it's an issue as syncing seems to carry on but I got a question. 
What indicates the number in the parenthesis after "node syncing" ? 
Sometimes I have 1, sometimes 570 etc ...
Thank you !

<img width="351" alt="Capture d’écran 2019-05-20 à 07 46 54" src="https://user-images.githubusercontent.com/46328426/57998881-93ed4780-7ad3-11e9-9574-58126fa68b4b.png">

**Comment by fluidvoice** [comment]
My guess is that number is the process number for LND or other process. Maybe the background process showing the information.

**Comment by Byte1122** [comment]
Hi @ErwanLetard , have you solved it?
