### ISSUE TITLE
Cant connect with ZAP when on mobile network

### ISSUE THREAD

**Issue by adolfosrs** [raspiblitz/raspiblitz#635]
I'm being able to connect remotely to my node using Zap when I'm on a regular wi-fi connection (not local). But I'm not being able to connect when trying it on a mobile 4G network. I'm on a complete different network when trying the wifi approach. 

And I'm also being able to ssh through the 4G connection but when trying to connect using zap the app refuses to connect. 

When trying to scan the lndconnect QR code with my phone already on the mobile network I get the following: 

> Could not connect to server. (Name resolution failure)

I'm currently using a DynamicDNS from http://freedns.afraid.org

**Comment by rootzoll** [comment]
Hard to say whats wrong. Maybe head over to the ZAP iOS github and ask how you can get more info on the exact reason? https://github.com/LN-Zap/zap-iOS

**Comment by HonmaSokyu** [comment]
Hey!

Ill just ask here. Can someone please point me to the direction "how to connect ZAP with my Node, through Mobile network? 

Is it still not possible, because i have TOR on my Node?

Thank you!

**Comment by rootzoll** [comment]
I am closing this issue - but if there is any more info to add for future users, please add still as a comment.

**Comment by adolfosrs** [comment]
FYI I have opened a new issue on LN-Zap repo. No answer so far.

https://github.com/LN-Zap/zap-iOS/issues/178
