### ISSUE TITLE
Shango "Invalid TLS fingerprint" when scanning QR code

### ISSUE THREAD

**Issue by goodc0re** [raspiblitz/raspiblitz#636]
Updated raspiblitz to latest image, installed latest Version of Shango iOS from testflight today. 

When scanning the QR code an error pops up and disappears immediately so it's hard to catch but I'm pretty sure it was 

"invalid tls fingerprint"

**Comment by rootzoll** [comment]
Will add tests with the lastest Shango to the next realease issues.

**Comment by rootzoll** [comment]
OK - got the same error with my android shango and fixed this for v1.3
