### ISSUE TITLE
better bitcoind warm up time

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#65]
At the moment on a already setup raspiblitz the script gives the the system a fixed grace period to warm up. But even sometimes 120 seconds are not enough. So after a minumum time (60 secs) a script should really check if warm up is done before continue by check if you get no error output when calling bitcoin-cli.

**Comment by geco91** [comment]
@rootzoll new checking for error works fine on the LCD. When logging in as admin there seems to be still a second based waiting time.

**Comment by rootzoll** [comment]
OK. Now also the admin on login has better detection.
