### ISSUE TITLE
Can't close lightning channels

### ISSUE THREAD

**Issue by tryolly** [raspiblitz/raspiblitz#652]
Hi, I'm trying to close my open channels but keep getting an error message (see attached image). My hdd is failing so I want to close all channels before switching to new drive. Any help in closing the channels would be appreciated.
![Capture3](https://user-images.githubusercontent.com/47936671/59310205-fdceca80-8ce8-11e9-9061-cf620f95536a.PNG)

**Comment by rootzoll** [comment]
try the following command:
```
sudo -u bitcoin lncli closeallchannels --force
```
leave main menu first by using "X Terminal"

**Comment by tryolly** [comment]
will do, but got to go to work now. I'll try in about 9 hours and let you know how it goes.

**Comment by tryolly** [comment]
So I got home and there were several errors with the PI, this is no doubt due to hdd. After a very slow shutdown I restarted it and before going to terminal I tried closing the channels from the menu screen again. It worked this time without issue, so yay, time to sort out a new hdd now.

Thanks for the help.

**Comment by rootzoll** [comment]
Make sure to check the power supply (big & stable) is important - better even add a powered usb hub between Raspberry Pi and HDD ... because most HDD problems come from weak power supplies. Good Luck.
