### ISSUE TITLE
how to generate new wallet?

### ISSUE THREAD

**Issue by ghost** [raspiblitz/raspiblitz#658]
hi,

I forgot to make a note on the words and would love to generate a new wallet, how could i do it?

thx,
fuligjimmy

**Comment by rootzoll** [comment]
I would consider a fresh setup. But you can keep the blockchain:
- cash out all your funds and channels
- exit to terminal - run command: `./XXcleanHDD.sh` (it will keep the blockchain data)
- shutdown - run command: `sudo shutdown -r now`
- make a fresh sd card
- and then follow the fresh setup

**Comment by HenrySabio** [comment]
@rootzoll I didn't want to reopen a new issue for the same thing, but this was a year ago.
Is there a way to create a new wallet without cleaning the drive and a fresh raspiblitz SD build?

Edit: Deleting the wallet file does not work.
initLND runs again to ask you to create a new wallet or import, but fails when tries to create a new seed and provides and RPC Gen Seed error.

I'm just going to do it the way you outlined above instead.

**Comment by rootzoll** [comment]
To reset the LND wallet check in the SSH Main Menu `REPAIR` > `RESET-LND` ... if you dont see this option, you may need to update the RaspiBlitz release. v1.5 final is now available.

**Comment by billgre** [comment]
Hi i received a ready 2 go raspi. I made my Lnd wallet but not an on chain one. Never asked for it.

**Comment by rootzoll** [comment]
@billgre The LND is managing both - your on-chain and off-chain funds. By default Bitcoin is just an information service on the blockchain for LND.
