### ISSUE TITLE
RTL Update to v0.4.2

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#660]
https://github.com/ShahanaFarooqui/RTL/releases/tag/v0.4.1

**Comment by rootzoll** [comment]
Updated for v1.3 release ... final testing.

**Comment by openoms** [comment]
One can hardly keep up: https://github.com/ShahanaFarooqui/RTL/releases/tag/v0.4.2

https://twitter.com/openoms/status/1141276758097977345

**Comment by rootzoll** [comment]
OK - updated and testet. RTL 0.4.2 is part of v1.3 release.
