### ISSUE TITLE
Red text of death

### ISSUE THREAD

**Issue by inpharmaticist** [raspiblitz/raspiblitz#662]
I upgraded to v 1.2 and after running for a day or so this happens. I've restarted and it happens again after about a day.

![raspiblitz death screen](https://user-images.githubusercontent.com/49789899/59818648-906afd00-92d9-11e9-8782-6b7f80bd7c45.jpg)

**Comment by rootzoll** [comment]
ouch - looks like some HDD error. Repair/recovery would depend if you had funding/channels on there?

**Comment by inpharmaticist** [comment]
I've been able to restart and it works for a day or so. I was able to close channels and remove funds, so no concerns there. I notice this is not an issue when TOR is turned off. This wasn't an issue with v1.1 so I might try that again.
