### ISSUE TITLE
extracted img file hash

### ISSUE THREAD

**Issue by rafaelpac** [raspiblitz/raspiblitz#680]
Hi! I extracted the .gz file using Linux and got a 4Gb file. Then I extracted it on Windows (7-zip) and got a 8Gb file. Which one is correct? What is the SHA256 of the .img file?

**Comment by Dimpelmoser** [comment]
... the SHA256 for checking the file <raspiblitz-v1.2-2019-05-02.img.gz> after the download can be found on https://github.com/rootzoll/raspiblitz below the download-links.
To bring the image file to the SD card it may be helpful to read https://www.raspberrypi.org/documentation/installation/installing-images/README.md.

**Comment by rafaelpac** [comment]
Thanks. I checked the SHA256 for the .gz file and it is correct. But when extracted, on Linux and on Windows, I got two different .img files, with different hashes.

**Comment by openoms** [comment]
> Thanks. I checked the SHA256 for the .gz file and it is correct. But when extracted, on Linux and on Windows, I got two different .img files, with different hashes.

There is no need to extract, just burn the compressed img.gz directly with Etcher.

**Comment by woeisme** [comment]
I noticed an issue with flashing the http://raspiblitz.com/raspiblitz-v1.3RC1-2019-07-04.img.gz to sdcard only when I did:

`zcat raspiblitz-v1.3RC1-2019-07-04.img.gz | sudo dd bs=4M of=/dev/mmcblk0 conv=fsync status=progress'`

did it manage to flash the card correctly and boot.

perhaps this is related to [**Section** Copying a zipped image to the SD card](https://www.raspberrypi.org/documentation/installation/installing-images/linux.md)

> In Linux it is possible to combine the unzip and SD copying process into one command, which avoids any issues that might occur when the unzipped image is larger than 4GB. This can happen on certain filesystems that do not support files larger than 4GB (e.g. FAT), although it should be noted that most Linux installations do not use FAT and therefore do not have this limitation.

**Comment by rootzoll** [comment]
TODO: Add info to v1.3 README on writing sd card linux
