### ISSUE TITLE
Repository 'http://raspbian.raspberrypi.org/raspbian buster InRelease' changed its 'Suite' value from 'testing' to 'stable'

### ISSUE THREAD

**Issue by woeisme** [raspiblitz/raspiblitz#683]
this is easily solvable by explicity running 
`sudo apt update -y` 
which allows the change. 

[first solution found here](https://www.raspberrypi.org/forums/viewtopic.php?p=1495033)

This solution below is probably better and should just be run by bootstrap on first boot.
[additional source with scriptable alternative solution
`sudo apt update --allow-releaseinfo-change` ](https://www.reddit.com/r/raspberry_pi/comments/cam3pj/buster_updates_e_repository/)

**Comment by rootzoll** [comment]
Thanks. TODO: Add this to the v1.3 build script.

**Comment by woeisme** [comment]
> 
> 
> Thanks. TODO: Add this to the v1.3 build script.

Should I close this issue @rootzoll ?

**Comment by rootzoll** [comment]
OK. Is now commited to code and will be part of v1.3 release :) Thanks.
