### ISSUE TITLE
RaspiBlitz complains about locale LC_ALL not being set

### ISSUE THREAD

**Issue by woeisme** [raspiblitz/raspiblitz#684]
Addressed in various places on the internet
[here](https://raspberrypi.stackexchange.com/questions/19854/how-can-i-change-the-locale)

Various solutions are mentioned but commenting out the sshd_config option ` SendEnv LANG LC_*`
keeps ssh client from pushing locales the pi may not have installed and solves the problem quickly.

**Comment by rootzoll** [comment]
Thanks. TODO: Add to v1.3 build script.
