### ISSUE TITLE
v1.3 menu REPAIR options fail (missing bitcoin.conf)

### ISSUE THREAD

**Issue by fluidvoice** [raspiblitz/raspiblitz#685]
Depending on what you choose (RESET-LND or RESET-HDD) and the order that you perform them sometimes you end up with only a **/mnt/hdd/backup.bitcoin.conf** file and sometimes no `bitcoin.conf` file at all. And so the system does not startup properly.  Note, I'm using a VM but it's _likely_ this problem can also happen on a Pi so I thought I should report it.

**Comment by rootzoll** [comment]
TODO: Retest the repair/reset options for v1.3 release.

**Comment by rootzoll** [comment]
OK. I tested and optimized the RESET-HDD, RESET-CAIN & RESET-LND. Looks good so far. Closing issue.
