### ISSUE TITLE
LND not running after update tor 3.5.8. -> 4.0.5

### ISSUE THREAD

**Issue by saloppe73** [raspiblitz/raspiblitz#688]
Aloha,

after a system update LND failed. I think its bc a new tor version and bc it runs smooth without tor. Did I have something to change at the config?

https://termbin.com/89cc

tnx && regards

**Comment by rootzoll** [comment]
Not sure whats up with that manual update of TOR. To reverse to standard setup you can just make a new sd card and boot up with that (like on update) .. all LND channel/fund data is on HDD.

**Comment by saloppe73** [comment]
solved. for any reason I have to stop bitcoind/lnd/tor and restart it manually.
