### ISSUE TITLE
Litecoin Waiting for Litecoind to get ready

### ISSUE THREAD

**Issue by born2los3built2win** [raspiblitz/raspiblitz#703]

**Comment by PapaCoderNit** [comment]
netstat -nlp
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      -                   
tcp6       0      0 :::22                   :::*                    LISTEN      -                   
udp        0      0 0.0.0.0:1900            0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:68              0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:53383           0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           -                   
udp6       0      0 :::45654                :::*                                -                   
udp6       0      0 :::5353                 :::*                                -                   
raw6       0      0 :::58                   :::*                    7           -                   
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node   PID/Program name     Path
unix  2      [ ACC ]     STREAM     LISTENING     13082    -                    /var/run/fail2ban/fail2ban.sock
unix  2      [ ACC ]     STREAM     LISTENING     7451     -                    /run/systemd/private
unix  2      [ ACC ]     SEQPACKET  LISTENING     7462     -                    /run/udev/control
unix  2      [ ACC ]     STREAM     LISTENING     7513     -                    /run/systemd/journal/stdout
unix  2      [ ACC ]     STREAM     LISTENING     13145    -                    /run/user/1000/gnupg/S.gpg-agent.extra
unix  2      [ ACC ]     STREAM     LISTENING     13148    -                    /run/user/1000/gnupg/S.gpg-agent.ssh
unix  2      [ ACC ]     STREAM     LISTENING     13150    -                    /run/user/1000/gnupg/S.gpg-agent
unix  2      [ ACC ]     STREAM     LISTENING     13152    -                    /run/user/1000/gnupg/S.dirmngr
unix  2      [ ACC ]     STREAM     LISTENING     13154    -                    /run/user/1000/bus
unix  2      [ ACC ]     STREAM     LISTENING     13158    -                    /run/user/1000/gnupg/S.gpg-agent.browser
unix  2      [ ACC ]     STREAM     LISTENING     15483    777/systemd          /run/user/1001/systemd/private
unix  2      [ ACC ]     STREAM     LISTENING     15488    777/systemd          /run/user/1001/gnupg/S.gpg-agent.extra
unix  2      [ ACC ]     STREAM     LISTENING     15491    777/systemd          /run/user/1001/gnupg/S.dirmngr
unix  2      [ ACC ]     STREAM     LISTENING     15493    777/systemd          /run/user/1001/gnupg/S.gpg-agent.browser
unix  2      [ ACC ]     STREAM     LISTENING     15495    777/systemd          /run/user/1001/gnupg/S.gpg-agent.ssh
unix  2      [ ACC ]     STREAM     LISTENING     15497    777/systemd          /run/user/1001/bus
unix  2      [ ACC ]     STREAM     LISTENING     15499    777/systemd          /run/user/1001/gnupg/S.gpg-agent
unix  2      [ ACC ]     STREAM     LISTENING     1936     -                    /run/systemd/fsck.progress
unix  2      [ ACC ]     SEQPACKET  LISTENING     12701    -                    /var/run/bluealsa/hci0
unix  2      [ ACC ]     STREAM     LISTENING     14244    -                    /run/user/1000/systemd/private
unix  2      [ ACC ]     STREAM     LISTENING     10661    -                    /var/run/dbus/system_bus_socket
unix  2      [ ACC ]     STREAM     LISTENING     10664    -                    /run/thd.socket
unix  2      [ ACC ]     STREAM     LISTENING     10666    -                    /var/run/avahi-daemon/socket
unix  2      [ ACC ]     STREAM     LISTENING     13775    -                    /var/run/minissdpd.sock
unix  2      [ ACC ]     STREAM     LISTENING     10744    -                    /var/run/dhcpcd.sock
unix  2      [ ACC ]     STREAM     LISTENING     10746    -                    /var/run/dhcpcd.unpriv.sock
