### ISSUE TITLE
Rely only on GPG keys for verification

### ISSUE THREAD

**Issue by Kixunil** [raspiblitz/raspiblitz#706]
GPG verification should be sufficient and the hashes are redundant and prevent smooth upgrades (the script must be changed). They only provide protection against the signer of the software being compromised.

If the protection against signer compromise is desired, multisig might be implemented instead.

**Comment by rootzoll** [comment]
The latest PR from @openoms is using for the hashes the manifest file now - see:
https://github.com/rootzoll/raspiblitz/pull/696/files

As the LND documentation advises the manifest file with the hashes is the only one signed and gets checked against the GPG keys: https://github.com/LightningNetwork/lnd/releases

For the bitcoin-core we could get rid of the extra static hash values also in the build_script - thats something to consider.

**Comment by Kixunil** [comment]
Yes, Bitcoin core is the one I had in mind.

**Comment by rootzoll** [comment]
With the update to bitcoin core 0.18.1 I changed that the hash values will get greped from the sign checked asc file. Will be part of v1.3 release.
