### ISSUE TITLE
read-error on swap device

### ISSUE THREAD

**Issue by wmpedersen** [raspiblitz/raspiblitz#714]
Just installed 1.2 and switched to a proper 3A power supply (the Argon in favour of my 2A Samsung charger) and during sync I noticed tonight after running for a while that it was showing 'read-error on swap device' and that my external hard drive was off. This drive is USB only and pulls power from the Raspberry Pi, so perhaps it's an issue with the individual power supply.

I did a power cycle and will keep an eye on it, but thought I'd bring it up just in case. I guess it makes sense if the raspberry pi ran out of memory and started using swap and then all of a sudden couldn't read from the drive, but I'm still confused as to why the drive turned off...

**Comment by rootzoll** [comment]
Are the error messages consistent or was it just a one time occurence?

**Comment by wmpedersen** [comment]
With the hard drive off it was one after the other. Unfortunately I didn't catch it while it was beginning and the drive was still on. But so far after the power cycle I haven't seen it pop up

**Comment by fluidvoice** [comment]
> This drive is USB only and pulls power from the Raspberry Pi

which drive is it, and do you know what it's current draw is?

**Comment by wmpedersen** [comment]
It's the Toshiba HDTB410XK3AA (The one in your photo). I'm afraid I don't know what the draw is, but it's been running since last without any messages on screen. At about  97~98% percent now.

**Comment by wmpedersen** [comment]
It's been running steady without issue and has crossed 99% on blockchain sync. I'm going to chalk this issue up to power weirdness and close this for now.
