### ISSUE TITLE
Script Reparatur, Reindex, Neuladen der Blockchain wäre gut, wenn Blockchain fehlerhaft ist

### ISSUE THREAD

**Issue by Otti24xx** [raspiblitz/raspiblitz#718]

**Comment by Otti24xx** [comment]
Bitcoind arbeitet nicht mehr, weil ein Fehler gefunden wurde:

EXCEPTION: 15dbwrapper_error
Fatal LevelDB error: Corruption: block checksum mismatch: /mnt/hdd/bitcoin/indexes/txindex/072765.ldb
bitcoin in scheduler

Anzeige im Hauptmenu Raspiblitz:
x  The bitcoind service is not running.   x
x  Login for more details:                x
 x  Use CTRL+c to EXIT to Terminal

**Comment by rootzoll** [comment]
v1.3 will have a "repair" menu where you can select to delete and redownload/sync blockchain.
