### ISSUE TITLE
Help with the setup

### ISSUE THREAD

**Issue by lsilvs** [raspiblitz/raspiblitz#72]
How to setup raspiblitz using `HDMI` rather than `LCD panel`?

I've connected my RPI with the image in the SSD card and connected it to a HDMI screen but I got stuck when it shows `Started D-Bus System Message Bus.` message.

**Comment by vv01f** [comment]
This has very probably nothing to do with the display.
I also could not boot into the pre-built image-file (despite checksum was ok and I also tried thrice) as linked in the README, instead I used the other method to customize a fresh raspbian from scratch. So I suggest you to go that path as well.

**Comment by lsilvs** [comment]
@vv01f Thanks for your response.
I'll give it a try setting up from scratch.
Cheers!
