### ISSUE TITLE
LND fails to start

### ISSUE THREAD

**Issue by osilloh** [raspiblitz/raspiblitz#720]
debugs are at this link.

https://termbin.com/y274

Pi4 4g, original Pi power measely 15.3w (low power warning, proceeded with install anyway) with Fanshim, Seagate STEH1000100 1TB HDD USB3, Kuman LCD uninstalled because of power warning.

<img width="381" alt="image" src="https://user-images.githubusercontent.com/40921996/62915465-48dc7c80-bd30-11e9-9f50-8bd9cf5689be.png">

LND not ready 

![image](https://user-images.githubusercontent.com/40921996/62915542-7cb7a200-bd30-11e9-9648-c8f0ca7a6b75.png)

**Comment by rootzoll** [comment]
Is it correct, that you have TOR activated? The RC1 had still some problems with TOR and from the LND logs it seems that LND is nit able to speak with the TOR service/socket: Aug 13 05:26:02 RaspiBlitz lnd[29950]: dial tcp 127.0.0.1:9050: connect: connection refused

Today or tomorrow I will release the v1.3 RC5 - I tested TOR a lot with that and it looks good. To reuse your already available blockchain with the new release: Go to terminal (CTRL+C), use command "repair" and choose "RESET HDD (but keep blockchain)". Then once the RaspBlitz is powered down ... burn the new RC image to the sd card and start again from the beginning.

I will also adapt the power levels for the power outlet.

**Comment by fluidvoice** [comment]
> debugs are at this link.
> 
> LND not ready
> 

I'd like to see your Tor errors, please run this and paste the link:
`sudo grep "tor[" /var/log/syslog | nc termbin.com 9999`

**Comment by osilloh** [comment]
Yes, I have TOR activated. I have downloaded RC5, I shall give it a try and post any issues. thank you both for your help.

**Comment by osilloh** [comment]
Success!

RC5 worked like a champ. Followed your instructions above and it came up. It still complains about low power as you can see. 

![image](https://user-images.githubusercontent.com/40921996/63390441-d7fa1d80-c34a-11e9-87f9-bc903aa8cd11.png)

Now I just need to fund it and open some channels. Will try to build a BTCpay server as well.

![Pi4b1 3rc5](https://user-images.githubusercontent.com/40921996/63390121-a7fe4a80-c349-11e9-8c86-5ddd2656a9e6.jpeg)
