### ISSUE TITLE
is v1.3 ready for Rpi3 ? 

### ISSUE THREAD

**Issue by bitsam** [raspiblitz/raspiblitz#722]
Hi @rootzoll 
There seems a lot of dev on v1.3 for Rpi4. I would really love to update my Raspiblitz Rpi3B+ to LND 0.7.1 on a stable Raspibltz version. Is it possible to release v1.3 for all existing Raspiblitz running on Rpi3 and continue dev on Rpi4 ?

Thanks
Sam

**Comment by rootzoll** [comment]
V1.3 is very close to finish - if not some last big thing is showing up:
https://twitter.com/rootzoll/status/1161238599045656576?s=20

It was not just stuff for the RP4 - it was also getting the TOR setup right, etc.

**Comment by bitsam** [comment]
Thank you for the update and continued hard work on this project.
