### ISSUE TITLE
No instructions on how to return to menu 

### ISSUE THREAD

**Issue by ostermayer** [raspiblitz/raspiblitz#725]
<img width="872" alt="Screen Shot 2019-08-16 at 9 18 43 AM" src="https://user-images.githubusercontent.com/4887941/63174190-128c4f00-c007-11e9-9914-f2211467861d.png">
If you end up in the situation pictured in the screenshot with the user having exited to the command line there is no obvious command instructions to get back to the menu.

**Comment by ostermayer** [comment]
although $raspiblitz command obviously returns perhaps we should create a wiki page with a list of commands for the user to know

**Comment by fluidvoice** [comment]
you can run `./00mainMenu.sh` 
that plus the debug command `./XXdebugLogs.sh`
are probably the only two you need to know.
