### ISSUE TITLE
1.3 RC5 display switch to sync screen

### ISSUE THREAD

**Issue by RolfHodl** [raspiblitz/raspiblitz#728]
I have the behavior that at a timeframe from about 3-4 hours it switches a short period (about 20 seconds) to the blue screen with the blockchain and lightning % sync back and then to the normal screen. 

Does anyone encountered such behavior?

**Comment by fluidvoice** [comment]
what is "the normal screen"?

**Comment by RolfHodl** [comment]
Sry ;) (normal screen)

![Bildschirmfoto 2019-08-25 um 20 27 39](https://user-images.githubusercontent.com/44261656/63654166-ed21e280-c776-11e9-80eb-4f1bb8a1ef1d.png)

**Comment by openoms** [comment]
> I have the behavior that at a timeframe from about 3-4 hours it switches a short period (about 20 seconds) to the blue screen with the blockchain and lightning % sync back and then to the normal screen.
> 
> Does anyone encountered such behavior?

This is normal behavior. When there is a new block propagated to your node it needs to verify the data and sync lnd as well.

**Comment by RolfHodl** [comment]
Thank you for clearing this up, just curious about to turn this off?! If you have a node in a room where someone works/sleeps it's like disstracting if it switches to that blue screen and back to the "dashboard".

I think it whould be better if the blue screen is just for the IBD and then when a new block comes it is shown in the "dashboard". Otherwise the 100% there will never change?
![63654166-ed21e280-c776-11e9-80eb-4f1bb8a1ef1d](https://user-images.githubusercontent.com/44261656/63747844-5bb28d80-c8a8-11e9-9bae-5a7ce2fe2bb8.png)

**Comment by openoms** [comment]
You could reduce the refresh rate of the screen to avoid catching the short syncing periods.
Could edit:
`sudo nano /home/admin/00infoBlitz.sh`
Increase the `sleep 5` value towards the end in the line 297.
`sleep 30` would result to refreshing only in every 30 seconds which would make it less likely to run into a syncing screen.

**Comment by rootzoll** [comment]
Hopefully with a future version you can also use a epaper with no backlight .. that would be better to have it in your sleeping room anyway. I will close this issue for now.
