### ISSUE TITLE
Download blockchain hangs on checksum error. 

### ISSUE THREAD

**Issue by jetlagv1** [raspiblitz/raspiblitz#73]
I've tried a few times now but when downloading the blockchain it hangs on a checksum error every time at the same point. See attached Pic of the console output attached. 
![img_20180831_171515](https://user-images.githubusercontent.com/5540477/44961256-b8d26800-af0e-11e8-8557-f4a234bbf0c4.jpg)

**Comment by rootzoll** [comment]
Thanks for the report. This was the torrent dowload, right?

**Comment by jetlagv1** [comment]
Yes, it was the torrent which is the only download option in the latest
version of raspiblitz at the moment.

Op di 4 sep. 2018 21:46 schreef Christian Rotzoll <notifications@github.com

**Comment by rootzoll** [comment]
Working on improving FTP/Torrent at the moment - it the moment its still too slow and unstable. But there should be two download options in the latest version >0.86: FTP or Torrent.

**Comment by jetlagv1** [comment]
Hmm, I checked yesterday before posting this issue and I'm sure 2018-07-17b
was the version linked in the Readme. Anyway, I see there is a newer
version now dated 2018-08-28. Downloading it now. I'll let you know hoe it
goes. How was the hackday? 😎

Op di 4 sep. 2018 22:23 schreef Christian Rotzoll <notifications@github.com

**Comment by rootzoll** [comment]
make sure to clean your HDD for a fresh start - just format it (FAT, etc) on another computer before retry.

the hackday was awesome :D still recovering ;)

**Comment by rootzoll** [comment]
I will close this issue - because of old version. Reopen if you have still problems with it with the new version.
