### ISSUE TITLE
Optimize APC UPS support

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#735]
Based on  #707 , check for download - better shutdown times and also supporting the APC netwpork connection for the future.

**Comment by rootzoll** [comment]
Also add a UI for configuration.

**Comment by nyxnor** [comment]
Done, there is just no UI configuration, but this can be added to the webUI.
Edit: Close this, this is already mentioned here https://github.com/rootzoll/raspiblitz/issues/735
