### ISSUE TITLE
HDD > 2TB

### ISSUE THREAD

**Issue by jagottsicher** [raspiblitz/raspiblitz#74]
Can the raspiblitz deal with hdd > 2TB? 

I want to build a little bunch of raspiblitz and want to recycle some big drives (3 TB and 4TB)

**Comment by charlesrocket** [comment]
I can't see why not, but it might be tricky to power them. technically you could stack several hdds to one power source and utilize new [RPi PoE HAT](https://www.raspberrypi.org/products/poe-hat/)s to power boards
