### ISSUE TITLE
how can I connect my node with my 2 node

### ISSUE THREAD

**Issue by Lupus-Pluvia** [raspiblitz/raspiblitz#749]
my 1 node  and 2 node  connect with each other despite port change
![Screenshot_20190903-174129_Chrome](https://user-images.githubusercontent.com/49962031/64188174-2d1d4f80-ce72-11e9-96a4-b375a9cba867.jpg)
and are displayed with an additional IP node 1 has port 9777 node 2 has port 9735
![Screenshot_20190903-174647_Chrome](https://user-images.githubusercontent.com/49962031/64188524-e4b26180-ce72-11e9-8268-2f6f35d450ad.jpg)

**Comment by rootzoll** [comment]
I dont understand the problem. So you have two nodes running from the same public IP and want them to connect?

**Comment by Lupus-Pluvia** [comment]
No, I want you to argue separately

**Comment by rootzoll** [comment]
Sorry I still dont get a clear picture of your issue. I close this for now. If you write a more detailed description we can open the issue again.
