### ISSUE TITLE
Connecting Electrum wallet to my RaspiBlitz

### ISSUE THREAD

**Issue by GiganteX** [raspiblitz/raspiblitz#751]
So in Electrum there's a "Network" dialog, in the "Server" tab i de-select the "Select server automatically" checkbox and instead I enter the IP of the RaspiBiltz in the "Server:" address editbox 192.168.1.25. And the port is the default 50002. I kind of expected that to just work, but no. It just will not connect. Am i in the wrong place, doing the wrong thing? Or is there some configuration settings on the RaspiBlitz that I need to do?

**Comment by openoms** [comment]
For that to work you have to install an Electrum server. Two options:
* Electrum Personal Server: https://stadicus.github.io/RaspiBolt/raspibolt_60_bonus.html#electrum-personal-server (more suitable the RPi3)
* Electrs for a full server for devices with more RAM : https://github.com/openoms/bitcoin-tutorials/blob/master/electrs/README.md

**Comment by GiganteX** [comment]
Thanks for your reply!

That is very strange to me. Electrum does not communicate with bitcoin nodes, only with Electrum servers?

Edit: Of course, port 50002 isn't a bitcoind port. Well, seems I've learned something new today. Then I have no need for my RaspiBlitz as long as I insist of using Electrum for my wallets. hmm live and learn....

**Comment by openoms** [comment]
Use an Electrum Server of your own with Electrum by following one of the guides above.
Using a random server is a privacy leak and can be a security issue in some situations. 
Don't Trust, Verify.
