### ISSUE TITLE
i18n on raspiblitz

### ISSUE THREAD

**Issue by grunch** [raspiblitz/raspiblitz#752]
Hi, I would like to translate raspiblitz to spanish, have you thought about make a i18n module in order to make it easier to add new languages?

**Comment by fluidvoice** [comment]
It would be great but I think it would take a lot of work to do this, a lot of code changes.
The strings displayed to the user are spread out in many shell scripts in a non-modular way using various "echo" and "printf" statements I think.

**Comment by rootzoll** [comment]
For the shell scripts I cannot see that we will go into a i18n direction because it would be too complicated. But in the hopefully not so far future we will start to offer SetUp thru WebBrowser and graphical LCD infoscreens that can be a good point to start on i18n. So @grunch I will add this issue to the "Future Collection" and maybe in some month the call gets back to you :) thx.

**Comment by fluidvoice** [comment]
I looked into this a bit.  It might not be too bad depending on the scripts.  Still investigating. I might try it with one or two shell scripts first as a test. Here is a good primer: [GNU gettext](https://www.gnu.org/software/gettext/manual/html_node/index.html)

A partial that I made for the 00infoLCD.sh script for Brazilian Portuguese:

#: 00infoLCD.sh:20
msgid "plz run as user pi --> su pi"
msgstr "por favor executar como usuário pi --> su pi"

#: 00infoLCD.sh:26
#, sh-format
msgid "  Starting RaspiBlitz v${codeVersion} ..."
msgstr "  Inicializando RaspiBlitz v${codeVersion} ..."

#: 00infoLCD.sh:42
msgid "Waiting for Network ...\\n"
msgstr "Aguardando o rede ... \\n"

#: 00infoLCD.sh:43 00infoLCD.sh:53
msgid "Not able to get local IP.\\n"
msgstr "Não é possível obter o IP local.\\n"

#: 00infoLCD.sh:44
msgid "Is LAN cable connected?\\n"
msgstr "O cabo do LAN está conectado?\\n"

#: 00infoLCD.sh:52
msgid "Waiting for DHCP ...\\n"
msgstr "Aguardando para DHCP...\\n"

#: 00infoLCD.sh:54
msgid "Will try reboot every 5min.\\n"
msgstr "Tentará reiniciar a cada 5 minutos. \\n"

#: 00infoLCD.sh:83
msgid "no internet connection"
msgstr "sem conexão à internet"

**Comment by fluidvoice** [comment]
the script 00infoBlitz.sh looks like a complicated one, so maybe I will try that one as a test and perhaps worst case example.

$ `grep print 00infoBlitz.sh`

> ram_avail=$(free -m | grep Mem | awk '{ print $7 }')
> ram=$(printf "%sM / %sM" "${ram_avail}" "$(free -m | grep Mem | awk '{ print $2 }')")
> hdd_free_ratio=$(printf "%d" "$(df -h | grep '/mnt/hdd$' | awk '{ print $4/$2*100 }')" 2>/dev/null)
> hdd=$(printf "%s (%s%%)" "$(df -h | grep '/mnt/hdd$' | awk '{ print $4 }')" "${hdd_free_ratio}")
> network_rx=$(ifconfig eth0 | grep 'RX packets' | awk '{ print $6$7 }' | sed 's/[()]//g')
> network_tx=$(ifconfig eth0 | grep 'TX packets' | awk '{ print $6$7 }' | sed 's/[()]//g')
>     sync_percentage=$(echo $progress | awk '{printf( "%.2f%%", 100 * $1)}')
> local_ip=$(ip addr | grep 'state UP' -A2 | tail -n1 | awk '{print $2}' | cut -f1 -d'/')
>     ipOfDynDNS=$(getent hosts ${dynDomain} | awk '{ print $1 }')
>       item=$(sudo -u bitcoin tail -n 100 /mnt/hdd/lnd/logs/${network}/${chain}net/lnd.log 2> /dev/null | grep "(height" | tail -n1 | awk '{print $10} {print $11} {print $12}' | tr -dc '0-9')
> printf "

$ `grep echo 00infoBlitz.sh`

>     block_verified="$(echo "${blockchaininfo}" | jq -r '.blocks')"
>     progress="$(echo "${blockchaininfo}" | jq -r '.verificationprogress')"
>     sync_percentage=$(echo $progress | awk '{printf( "%.2f%%", 100 * $1)}')
> public_port="$(echo ${networkInfo} | jq -r '.localaddresses [0] .port')"
> networkConnections=$(echo ${networkInfo} | jq -r '.connections')
>   onionAddress=$(echo ${networkInfo} | jq -r '.localaddresses [0] .address')
>   public_check=$(nc -z -w6 ${public_ip} ${public_port} 2>/dev/null; echo $?)
>  ln_external=$(echo "${ln_getInfo}" | grep "uris" -A 1 | tr -d '\n' | cut -d '"' -f4)
>  ln_tor=$(echo "${ln_external}" | grep -c ".onion")
>    public_check=$(nc -z -w6 ${public_ip} 9735 2>/dev/null; echo $?)
>  ln_sync=$(echo "${ln_getInfo}" | grep "synced_to_chain" | grep "true" -c)
>  ln_version=$(echo "${ln_getInfo}" | jq -r '.version' | cut -d' ' -f1)
>     ln_channels_online="$(echo "${ln_getInfo}" | jq -r '.num_active_channels')" 2>/dev/null
>     ln_peers="$(echo "${ln_getInfo}" | jq -r '.num_peers')" 2>/dev/null
>   echo ""
>

**Comment by fluidvoice** [comment]
I looked into this a bit.  It might not be too bad depending on the script.  
Remains to be seen - still investigating. I might try it with one or two shell scripts as a test to see how difficult it is. 

First at the top of the script include:
```
#. Gnu script internationalization: https://www.gnu.org/software/gettext/manual/html_node/index.html
#. make sure gettext.sh is in the path
source gettext.sh
```

Then edit the script as documented [GNU gettext](https://www.gnu.org/software/gettext/manual/html_node/index.html).

**Comment by grunch** [comment]
BBaker, do you want to create a new branch for this? so we can work on it


/*
 *  Francisco J. Calderón S.
 */

**Comment by fluidvoice** [comment]
> BBaker, do you want to create a new branch for this? so we can work on it 

Francisco, I'm not sure yet.  I'm debating. It's a lot of work and I have other things to work on.
I moved my post to a Gist that I may update if I look more into it - then decide if I want to try to do it:
https://gist.github.com/fluidvoice/0e0bada8e02bb9aad03969cc5cbd0ace
The thing is there is no value in just doing it partially, you have to do the whole thing and it's a very large amount of scripts and edits.  We could start with first only the scripts involved with the installation but I question how useful even that would be. Non English speakers would still struggle with getting it working and understanding if/when there are errors.

Some guys posted about full nodes on the Portuguese Bitcointalk forum so I posted about Raspiblitz to see if there is any interest: https://bitcointalk.org/index.php?topic=5178378.msg52567224#msg52567224

**Comment by fluidvoice** [comment]
I'm also thinking if it would help to try to automate things, say via an awk (or other) program that parses all the shell scripts and lists all the changes needed if not doing some automated changes. Basically if it's possible to not have to do all the script edits by hand?  It's enough work just doing the translations by hand.

**Comment by rootzoll** [comment]
One aim of v1.7 should be to present a first basic web interface and touchscreen improvements ... to check for i18n options there in recommended.

**Comment by frennkie** [comment]
Using Python with Jinja2 and Babel translations kann be made https://github.com/getpelican/pelican-plugins/blob/master/i18n_subsites/localizing_using_jinja2.rst

**Comment by rootzoll** [comment]
Also check https://www.transifex.com tomake it easy for people to help on translations .. its also used by bitcoincore.
