### ISSUE TITLE
Local-Remote Channel Capacity & Channel Status not loading

### ISSUE THREAD

**Issue by nerdminerstore** [raspiblitz/raspiblitz#754]
Installed the fresh 1.3 release on a pi4. The RTL UI the Local Remot Channel Capacity and Channel Status is loading but loads forever and never shows any stats.

![Unbenannt2](https://user-images.githubusercontent.com/54980603/64415905-73eb8f00-d096-11e9-8d66-d956d871bee0.PNG)

**Comment by rootzoll** [comment]
It would make sense to bring this issue first to https://github.com/ShahanaFarooqui/RTL .. if there is  any idea what to fix/optimize on the RaspiBlitz we can reopen this issue.
