### ISSUE TITLE
"checksum not OK" when running the setup script

### ISSUE THREAD

**Issue by adolfosrs** [raspiblitz/raspiblitz#76]
Was mounting the sd card image accessing my rasp by ssh and the bash failed.

`!!! BUILD FAILED --> Bitcoin download checksum not OK`

Is it something anyone else is getting? Thoughts?

**Comment by rootzoll** [comment]
This could happen if the download failed somehow (connectivity, etc.) maybe give it a second try with a fresh flashed SD card.

**Comment by adolfosrs** [comment]
Hey @rootzoll, thanks for the answer. Turns out that the problem was on my rasp locale not set to `en_US`. 

It was checking for  `grep '.tar.gz: OK' -c` and the `sha256sum` check was returning 'SUCESSO' because of the locale. Could fix it by just setting to the proper locale.

Sorry for bothering.
