### ISSUE TITLE
Missing gpg key for deb.torproject.org repository

### ISSUE THREAD

**Issue by freerko** [raspiblitz/raspiblitz#763]
Hi, running _apt-get update_ on a fresh Raspiblitz 1.3 results in following error:
>...
Err:3 https://deb.torproject.org/torproject.org buster InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 74A941BA219EC810
W: GPG error: https://deb.torproject.org/torproject.org buster InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 74A941BA219EC810
E: The repository 'https://deb.torproject.org/torproject.org buster InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

As explained on https://2019.www.torproject.org/docs/debian.html.en this can be fixed with: 

`curl https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc | gpg --import
gpg --export A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89 | apt-key add -`

I think as an alternative it is possible to install the package _deb.torproject.org-keyring_ from that repository to get the current signing key.

**Comment by rootzoll** [comment]
This is now part of the `internet.to.sh pepare` command that is called during sd card build. Thx.
