### ISSUE TITLE
Failing RaspiBlitz - trying to download back up file - noob 

### ISSUE THREAD

**Issue by hch-y** [raspiblitz/raspiblitz#765]
I've had issues with my node for a couple months now, probably due to user error and maybe a failing HHD(had this issue at first https://github.com/rootzoll/raspiblitz/issues/442). Now I've decided to download the channel back up file and start fresh.  Due to serious stupidity on my part I may have committed some fatal errors and have no shot at recovering my funds. I'll do my best to describe where I'm at, any help would be greatly appreciated.

1) Went to ssh into my node and realized that the last time I had tried to fix my node by reflashing my SD card my IP for the node had changed. Of course I was too lazy to find where I'd written it down so I just plugged in a keyboard directly to my pi and and ran /home/admin/config.scripts/lnd.rescue.sh backup. This seems to have worked and stopped my node. 

2) And now realize that I really screwed up because I need to download the file somewhere. So I dig around and find my IP for the node and try to sign in the proper way through terminal on my laptop. This just times out. I'm guessing this is because I've stopped my node and can't access it. Not sure where to go from here.

3) I have tried plugging in a keyboard straight to the pi along with a thumb drive and running scp -r admin@home/admin/lnd-rescue-*.tar.gz ./ but it states that can't resolve the hostname(where it wants to download file?). How do I resolve the hostname issue? I tried running scp -r admin@[NAME OF THUMBDRIVE]/admin/lnd-rescue-*.tar.gz ./ with no success. 

To anyone who read along, thank you very much and any help would be greatly appreciated. At the end of the day I'd really just like to have a fresh node with my funds. Yes, I had funds in open channels when this began and I do have my seed phrase.

**Comment by rootzoll** [comment]
@home is not a valid address to download something from. But lets start at the beginning - I assume you have v1.2 running.

You want the channel backup file ... so lets see if its still available. Please check if under the following locations is still a file called: `channel.backup`

`sudo ls /home/admin/.lnd/data/chain/bitcoin/mainnet/` or `sudo ls /mnt/hdd/lnd/data/chain/bitcoin/mainnet/`

Is there still `channel.backup` file in any of these directories?

**Comment by hch-y** [comment]
@rootzoll thanks for the response! 

I just ran both of those and I get a message saying that there is "no such file or directory" for each one. My external hard drive might be completely fried or something.

**Comment by rootzoll** [comment]
The first path `home/admin/.lnd/data/chain/bitcoin/mainnet/` is just the sd card ... if that is gone it looks not that promising to get to a restore.

**Comment by hch-y** [comment]
hmm, that's bad. anything I can do at this point?

**Comment by hch-y** [comment]
Made some progress, screen shot attached of bug report,
<img width="712" alt="Screen Shot 2019-09-09 at 8 35 22 PM" src="https://user-images.githubusercontent.com/55105048/64575379-80dfdb00-d341-11e9-94a0-0f067fe535cb.png">

**Comment by rootzoll** [comment]
Can you post a screenshot of the following directory listing?
```
sudo ls /mnt/hdd
```

**Comment by hch-y** [comment]
<img width="569" alt="Screen Shot 2019-09-10 at 9 26 28 AM" src="https://user-images.githubusercontent.com/55105048/64617840-267c6400-d3ad-11e9-8e38-b7b63e359177.png">

**Comment by rootzoll** [comment]
Thats not too bad to start with. Whats inside the lnd folder and the lnd backup folder?
```
sudo ls /mnt/hdd/lnd
sudo ls /mnt/hdd/backup_lnd
```

**Comment by hch-y** [comment]
<img width="532" alt="Screen Shot 2019-09-10 at 10 14 32 AM" src="https://user-images.githubusercontent.com/55105048/64621540-d9e85700-d3b3-11e9-92af-ca2572435e0a.png">

**Comment by hch-y** [comment]
oops, ran sudo ls /mnt/hdd/backup_lnd correctly below  

<img width="384" alt="Screen Shot 2019-09-10 at 10 16 18 AM" src="https://user-images.githubusercontent.com/55105048/64621670-11ef9a00-d3b4-11e9-817b-00c3355bdf0c.png">

**Comment by rootzoll** [comment]
I am seeing a data dir :) ... can you try also:
```
sudo ls /mnt/hdd/backup_lnd/data/chain/bitcoin/mainnet/
```
and if that is not working ... remove step by step the ending directoty until its working?

**Comment by hch-y** [comment]
<img width="567" alt="Screen Shot 2019-09-10 at 10 29 36 PM" src="https://user-images.githubusercontent.com/55105048/64663775-d936db80-d41a-11e9-8a85-ddca9ea120bc.png">
<img width="522" alt="Screen Shot 2019-09-10 at 10 31 30 PM" src="https://user-images.githubusercontent.com/55105048/64663781-de942600-d41a-11e9-97aa-b20e037234bc.png">

**Comment by hch-y** [comment]
<img width="413" alt="Screen Shot 2019-09-10 at 10 33 49 PM" src="https://user-images.githubusercontent.com/55105048/64663840-1733ff80-d41b-11e9-8d11-c3dee21c8d14.png">

**Comment by hch-y** [comment]
<img width="539" alt="Screen Shot 2019-09-12 at 11 50 46 AM" src="https://user-images.githubusercontent.com/55105048/64799887-8f9ddc00-d553-11e9-8a71-f39583c01514.png">

any of this helpful?

**Comment by rootzoll** [comment]
OK so the backup_lnd seems from an old update that still dont contains the channel backup file.
You were running RaspiBlitz v1.2 now correct?

Lets give it one more try to see whats in the original LND folder:

```
sudo ls /mnt/hdd/lnd/data/chain/bitcoin/mainnet/
```

and if that is not working ... remove step by step the ending directoty until its working?

**Comment by hch-y** [comment]
Yes, I am running v1.2.  

<img width="503" alt="Screen Shot 2019-09-17 at 9 05 00 AM" src="https://user-images.githubusercontent.com/55105048/65684426-946f8f00-e02d-11e9-808e-2bb5b3ab9592.png">
<img width="413" alt="Screen Shot 2019-09-10 at 10 33 49 PM" src="https://user-images.githubusercontent.com/55105048/65684461-ad784000-e02d-11e9-994d-22b487e0a621.png">

and then, if run the commad below it appears there is some sort of backup file.
<img width="566" alt="Screen Shot 2019-09-26 at 7 19 17 AM" src="https://user-images.githubusercontent.com/55105048/65684587-faf4ad00-e02d-11e9-8b08-78cba5504454.png">


I just don't know how to actually download it to my laptop.

**Comment by nyxnor** [comment]
Pls close this.
