### ISSUE TITLE
Renew TLS certs on IP change and manually from CONNECT

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#766]
see comment by @openoms on #324 :
https://github.com/rootzoll/raspiblitz/issues/324#issuecomment-527331964

Users have been reporting that the they could not connect Zap after chnaging their IP.
Manually resetting the TLS.cert helped.

Should this be automated every time when the publicIP is triggered to changed in lnd.conf
by the

```
 # RECHECK PUBLIC IP
 # when public IP changes, restart LND with new IP
```

function of _background.sh?

**Comment by rootzoll** [comment]
Movin to v1.6 because just an automatic renew of TLS without notifying the user is also confusing and not a good fix. Maybe when LCD interface is more advanced this can be a "notification".

**Comment by rootzoll** [comment]
Moving to v1.7 because 1.6 will not have any new LCD-interface features

**Comment by NilByte** [comment]
When you run duck.dns.org, the scan code for Zap is generated with your public ip address but  Zap wallet will only load code edited to use your domain name instead of public ip.

**Comment by openoms** [comment]
There is a request to renew the TLS cert on expiry for Electrs also: https://t.me/raspiblitz/140628

This is not covered with the reset script if LND is not installed.


For LND the autorefresh is a built in option:
```
; If set, then all certs will automatically be refreshed if they're close to
; expiring, or if any parameters related to extra IPs or domains in the cert
; change.
; tlsautorefresh=false
```
https://github.com/lightningnetwork/lnd/blob/e31d1598932a814c2d44b774e5110746295df711/sample-lnd.conf#L60C1-L63C23

**Comment by rootzoll** [comment]
Tests good on my machine. Closing issue for release.
