### ISSUE TITLE
Blockchain downloaded by blockchain lost

### ISSUE THREAD

**Issue by zionsuperfly** [raspiblitz/raspiblitz#768]
I downloaded the blockchain by torrent. Both (lnd and blockchain) where finished with downloading and hashing. I opened the session with my phone and it started to delete and move block. But my session was not staying open (cell phone went in standby). Now the system will try to redownload again. How can i recover the downloaded blockchain?

**Comment by patrikmojzis** [comment]
I had the same problem. What did you do then? Did you re-download it again or synced up it via BTC network?

**Comment by rootzoll** [comment]
Terminals closing/standbying can be problem, thats why using a terminal on dekstop is recommended for now.

Once we will have the TORBrowser-Setup such processes will be designed to run in the background.
