### ISSUE TITLE
Dumped core Broadcast message?

### ISSUE THREAD

**Issue by LukeParker** [raspiblitz/raspiblitz#769]
I didn't even know the pi used warp propulsion...

Today my v1.2 node's LCD screen had a new message on it:

> Broadcast Message from systemd-journal@pipsqueak (Tue 2019-09-10 23:34:12 BST):
> 
> systemd[1]: Caught <BUS>, dumped core as pid 30063.

Oddly, the node isn't down or anything; everything in RTL is working normally. Don't know what to make of this.

**Comment by rootzoll** [comment]
Unix was build for space ships ;D 

"Core dumps are triggered by the kernel in response to program crashes, and may be passed to a helper program (such as systemd-coredump) for further processing - get deleted after reboot"

Not sure what crashed there ... but looks like it was not a mission critical service. If you can observe that more regularly please report again and I will open up issue again for more investigation. Live long and prosper :)
