### ISSUE TITLE
Is the case for raspberry pi 3 or 4

### ISSUE THREAD

**Issue by maddadder** [raspiblitz/raspiblitz#771]
It does not say what raspberry pi this is for. I printed it out and it did not fit the raspberry pi 4. A simple description would have saved me hours of time. 
https://github.com/rootzoll/raspiblitz/tree/master/case.3dprint/standard

**Comment by rootzoll** [comment]
This is still the old first try case for the RP3 .. it will be replaced by this open source case for the RP4 soon:
https://twitter.com/CryptoCloaks/status/1162136744327876610?s=19

**Comment by maddadder** [comment]
Thanks. Good to know.
