### ISSUE TITLE
tor bitcoin.conf.lnd.conf settings improvements 

### ISSUE THREAD

**Issue by Tracachang** [raspiblitz/raspiblitz#776]
Hello,

Setting up raspiblitz over tor the and checking bitcoin.conf and lnd.conf I do believe some important arguments are missing.

The actual bitcoin.conf over tor setup adds:
- nodes
- onlynet=onion 

I would add:
proxy=127.0.0.1:9050 
bind=127.0.0.1 
dnsseed=0 
dns=0 

Deactivating DNS would avoid Sybil attacks and since you already added nodes, there is no need activate it to find some peers.

For lnd services and based on https://github.com/lightningnetwork/lnd/blob/master/docs/configuring_tor.md

Replace tor.v2 for v3 and add --tor.istreamisolation 

I've also seen that bitcoin user is not in debian-tor group and all guides I've read so far advise to do it, however didn't have any error. So I am not sure what is the benefit.

Thank you.

**Comment by Tracachang** [comment]
I have been doing tests and all works fine.

I have edited /mnt/hdd/bitcoin/bitcoin.conf and my tor settings are (the orginal options are all the nodes and onlynet=onion:

proxy=127.0.0.1:9050
bind=127.0.0.1
onlynet=onion
dnsseed=0
dns=0
(and all the nodes)
addnode=fno4aakpl6sg6y47.onion 

I have edited lnd services
sudo nano /etc/systemd/system/lnd.service

ExecStart=/usr/local/bin/lnd --tor.active --tor.streamisolation --tor.v3 --listen=127.0.0.1:9735

(as you can see I have changed:
 --tor.v2 for --tor.v3
added --tor.streamisolation

**Comment by Tracachang** [comment]
I've edited the tor script and sent a PR.

**Comment by openoms** [comment]
Related to the discussion in: https://github.com/rootzoll/raspiblitz/issues/237

**Comment by rootzoll** [comment]
Thanks for the PR ... will ne part of issue #237 ... closing this now.
