### ISSUE TITLE
Give root password for maintenance (or press Control-D to continuine): = Message after new Installation Vers. 1.3 - SSH is not working

### ISSUE THREAD

**Issue by Otti24xx** [raspiblitz/raspiblitz#782]
after new Installation Vers. 1.3 i get this message on display - SSH is not working, what can i do?

**Comment by joernroeder** [comment]
port 22 is closed after i've run the cleanup script `./XXcleanHDD.sh` as well.
The display says i need to login via ssh but `nmap` returns `22/tcp    closed ssh` for the given ip.

**Comment by rootzoll** [comment]
If you get this "maintenance" notice something got corrupted on the sd card. Best solution is to shutdown (cut power if needed) and write a fresh image to the sd card. On next start you will go thru update/recover process and have to set the Password A again ... but other then that your RaspiBlitz will use your HDD data and continue with your old configuration and channels.

**Comment by joernroeder** [comment]
@rootzoll i did not came across the "maintenance" notice, and had to refresh the sd card a couple of times before it finally worked and i was able to restore my old state. the strange thing is that port for bitcoin ´8333` as well as the webinterface `3000` were still open while `22` was `closed` or `filtered`.

**Comment by Otti24xx** [comment]
Possibly it was a HDD Error, I have now a new SSD, so it works fine!

 

Von: Jörn Röder [mailto:notifications@github.com] 
Gesendet: Mittwoch, 18. September 2019 10:03
An: rootzoll/raspiblitz <raspiblitz@noreply.github.com>
Cc: Otti24xx <johannes.ott@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [rootzoll/raspiblitz] Give root password for maintenance (or press Control-D to continuine): = Message after new Installation Vers. 1.3 - SSH is not working (#782)

 

@rootzoll <https://github.com/rootzoll>  i did not came across the "maintenance" notice, and had to refresh the sd card a couple of times before it finally worked and i was able to restore my old state. the strange thing is that port for bitcoin ´8333as well as the webinterface3000were still open while22wasclosedorfiltered`.

**Comment by sh3raf** [comment]
I'm stuck in this step. After like 10 times with different sd cards (just to be sure) and many tries, no way of rebooting without this problem.

Any suggestion?

**Comment by sh3raf** [comment]
@rootzoll the update/recovery process seems to works but in the end, it still fails after the reboot

**Comment by rootzoll** [comment]
If you disconnect the HDD/SSD on boot up - does it also give that that error, or another?

**Comment by flowthis** [comment]
I`ve been running into the same problem. 

Disconnecting the HDD on bootup results in a brief period in which the following
message is repeated. 

"A start job is running for /dev/dis 96bf..."

It ends after approx. 60 seconds with the initial problem prompt. "Give root passw..."

Have you been able to find a solution @raziel8 ? 
Are there any possible workarounds that may let me reclaim my, otherwise very reliable node @rootzoll ?

**Comment by Otti24xx** [comment]
Hi, i have changed my hdd to SSD – so now it works fine, I think it was a Problem with my HDD.

Best Regards
Johohannes


Von: flowthis
Gesendet: Mittwoch, 20. November 2019 12:03
An: rootzoll/raspiblitz
Cc: Otti24xx; Author
Betreff: Re: [rootzoll/raspiblitz] Give root password for maintenance (orpress Control-D to continuine): = Message after new Installation Vers. 1.3 -SSH is not working (#782)

I`ve been running into the same problem.
Disconnecting the HDD on bootup results in a brief period in which the following
message is repeated.
"A start job is running for /dev/dis 96bf..."
It ends after approx. 60 seconds with the initial problem prompt. "Give root passw..."
Have you been able to find a solution @raziel8 ?
Are there any possible workarounds that may let me reclaim my, otherwise very reliable node @rootzoll ?

**Comment by rootzoll** [comment]
@flowthis is this also happend on an update or during normal operations/reboot?

**Comment by devdotmohit** [comment]
@rootzoll This was the last message I received.
DONE - Give raspi some cool off time after hard building .... 20 secs sleep
END Provisioning
rebooting

Post it, I see a prompt for root password for maintenance.

**Comment by rootzoll** [comment]
Have you connected a USB keyboard and entered the root password? Should be the same passwordA as for the admin user.

**Comment by devdotmohit** [comment]
@rootzoll Does not accepts Password A. It takes raspiblitz as the root password and shows terminal prompt in root directory.

**Comment by rootzoll** [comment]
Ah yeah - you getting this error directly after a recover/update, thats when PasswordA is not yet reset and still the default "raspiblitz".

Try also the CTRL+D or follow the hints in this RaspberryPi forum:
https://www.raspberrypi.org/forums/viewtopic.php?t=176695

So it maybe that somehow after recover/update your system is not shutting down properly and you have to fix Fstab all the time. If you get it fixed it would be interesting if this is just happening on this recover or every reboot/shutdown.

**Comment by devdotmohit** [comment]
@rootzoll  CTRL+D does nothing. Keeps prompting for password over and over.
Giving the root password, I am not sure what to be removed from fstab.
One is /boot, second is / and the third is /mnt/hdd

**Comment by born2los3built2win** [comment]
This fixed it for me
https://ubuntu-mate.community/t/getting-emergency-mode-screen-on-boot-up-every-time/2626/2


Hi !
I had the same issue but I found a solution !
You need another computer under linux and put your pi sdcard in it.
If your RPI sdcard is /dev/sdb do :
sudo umount /dev/sdb1
sudo umount /dev/sdb2
sudo fsck /dev/sdb1
sudo fsck /dev/sdb2

After put the sdcard in the raspberry pi and enjoy :wink:

But I think Ubuntu mate mainteners have to do something for that !

**Comment by devdotmohit** [comment]
@PapaCoderNit Are there any unix commands as well to perform the same actions? I am on MacOS.

**Comment by born2los3built2win** [comment]
> @PapaCoderNit Are there any unix commands as well to perform the same actions? I am on MacOS.

I did it with usb keyboard plugged into the raspberry pi.
Also you want to do your sd card not the hdd..
Check /etc/dev/   and youll see sba and sba1 
The sd card is most likely sba
Run sudo fsck /etc/dev/sba (make sure its your sdcard)

**Comment by rootzoll** [comment]
To prevent this scenario in the future I will add the command `sudo tune2fs -c 1 /dev/mmcblk0p2` into the sd card build script. This should force a fsck automatically on the sd card root partition on every boot and hopefully gets rid of this "maintenance login" screen.

**Comment by born2los3built2win** [comment]
Thank you..

**Comment by sh3raf** [comment]
@flowthis not yet, just came back on this project! Keep you posted

@rootzoll I saw you pushed two commits to solve this issue, let's give a try now. 
Just to be clear: I'm using an HDD, not an SSD

**Comment by rootzoll** [comment]
@raziel8 to have the #782 commit active you need a sd card build with the updated script. A release candidate sd card image of v1.4 will be out the next days - that one will have the commit included.

**Comment by sh3raf** [comment]
@rootzoll thank you so much, waiting for the v1.4 ✌🏼

**Comment by mobycrypt** [comment]
> This fixed it for me
> https://ubuntu-mate.community/t/getting-emergency-mode-screen-on-boot-up-every-time/2626/2
> 
> Hi !
> I had the same issue but I found a solution !
> You need another computer under linux and put your pi sdcard in it.
> If your RPI sdcard is /dev/sdb do :
> sudo umount /dev/sdb1
> sudo umount /dev/sdb2
> sudo fsck /dev/sdb1
> sudo fsck /dev/sdb2
> 
> After put the sdcard in the raspberry pi and enjoy 
> 
> But I think Ubuntu mate mainteners have to do something for that !

I've stucked on the same same "Give root password for maintenance" message after simply plug off during BtcPAY server setup which just hanged.
How I resolved:
1. Connect SD card to another Linux
2. Run GParted partition program, selected partitions and check "Check" where possible (on every partition it's possible).
3. Run it (it showed the window about possible data loss but I confirmed).
4. After 10 seconds operation done, SD card back to raspberry - no errors anymore.

Hope it can help, but beware if you are scared to lose data on SD card.

**Comment by rootzoll** [comment]
As it looks the v1.4 is doing also now more fsck .. but its still asking for manual interference.
Thats why the v1.5 will try if this autofix-flag will no longer showing you this message.
https://github.com/rootzoll/raspiblitz/issues/1053

**Comment by marco-hofmann** [comment]
yes, I've been having the same issue since 1.3. Now Upgraded to 1.4 but still. Is there a way to fix it manually?

**Comment by joernroeder** [comment]
@edgeball i fixed it manually by entering the root password (pw a) and appending the proposed fix for v1.5 `fsck.mode=force fsck.repair=yes` manually into `/boot/cmdline.txt`. the reboot afterwards took a while (i think tue to the repair) but it resumed correctly afterwards

**Comment by rootzoll** [comment]
#1053 see also

**Comment by josusanmartin** [comment]
I was running into this issue, and the problem ended up being the SSD case that I was using. I tried putting the SSD in an old case I had and everything went smoothly.

**Comment by rootzoll** [comment]
@josusanmartin did you just changed the case and it was running again or did you also made a fresh sd card image. Also can you provide I link to that case?

**Comment by josusanmartin** [comment]
This was during the initial sync, so because of the error I ended up creating a fresh image a few times. So I think I created a fresh sd card image when it ended up working too (80% confident since I don't fully remember).

From what I could gather, the "bad drive" was causing the distro to get "corrupted" somehow. Whenever I started completly fresh (formatted ssd and fresh sd image) it would start syncing the blockchain and after a while it would throw io errors. I would reboot and  "the give root password for maintenance" would show up. So I'd create a fresh sd image and it would boot up. But I couldn't get it to start syncing again, so I had to erase the ssd too.

**Comment by rootzoll** [comment]
Thanks for the report. I am collecting to see if we can spot a pattern.

**Comment by sh3raf** [comment]
Thanks for the resolution, I solved changing the USB port, some USB ports can cause this issue also in newer versions apparently

**Comment by stopfeds** [comment]
Currently facing the same issue because I removed the power plug after removing the LAN cable - cause it didn't reconnect to LAN.
Will try to flash a new SD card now...

**Comment by stopfeds** [comment]
> Currently facing the same issue because I removed the power plug after removing the LAN cable - cause it didn't reconnect to LAN.
> Will try to flash a new SD card now...

Worked for me!

**Comment by ronledfordjr** [comment]
Weird, I was having this issue and last night I selected the Auto Unlock Feature for LND, it rebooted and Poof no more CTRL D issue. I rebooted again just now to confirm, no ctrl d issue.

**Comment by tibebugirmatoru** [comment]
Here you have the solution:
1. Give your password to login to maint..mode 
2. Just type fsck -f -y / .....to repair your /
3. then reboot
4. And check cmos battery life
