### ISSUE TITLE
LCD screen displaying incorrectly (Pi 4)

### ISSUE THREAD

**Issue by Aki113s** [raspiblitz/raspiblitz#784]
So my LCD screen on my Pi stays on this screen, ends on the Kill Switch as shown here...its to small to read so this is from a pic I found online but same thing basically.
<a href="https://imgbb.com/"><img src="https://i.ibb.co/zVnRg10/screen.png" alt="screen" border="0"></a>
I can SSH into the Pi and Blockchain is at 91%, so I am getting there. The next step in the directions says once done, I should see the following.
<img src="https://raw.githubusercontent.com/rootzoll/raspiblitz/master/pictures/ssh9z-ready.png" alt="screen" border="0"></a>
I have high doubts based on many reboots my LCD screen sits on the first image, what could be causing it? I assume I should still be able to SSH in to the Pi to verify all is good. I'm so curious as to why it hangs on the boot screen.

Thank you!

**Comment by rootzoll** [comment]
We had similar issues in the past ... somehow the LCD gets not updated anymore, but the system is still progressing. We never got exactly behind why that is happening on some screens ... any idea and investigation wellcome. See issue: #195

**Comment by Aki113s** [comment]
> 
> 
> We had similar issues in the past ... somehow the LCD gets not updated anymore, but the system is still progressing. We never got exactly behind why that is happening on some screens ... any idea and investigation wellcome. See issue: #195

I posted in #195 as well but also to add here, I read through that thread...
A fix seemed to work for me.

So I was having the EXACT same issue. Fresh first time install. Raspberry Pi 4...4GB, Everything synced. In SSH terminal I ran what @pxsocs said.

**cd /home/admin/LCD-show
sudo ./LCD-hdmi**

System rebooted, saw the entire boot run. Then it went to the loading screen, it stayed on Lightning Preparing Sync and rapidly finished. Then the Display worked, unsure if it will happen again, but will see.

My display is VERY small though, the status screen in 25% of what it should be. Small steps yes?

<a href="https://imgbb.com/"><img src="https://i.ibb.co/wrrnSf5/0.jpg" alt="0" border="0"></a>

Is there a way to full size this?? Again I can SSH in no problem, I just love peaking at the temps and when LND is funded I can monitor easier.

Thanks all!!

**Comment by Aki113s** [comment]
I was able to find my answer...
run terminal and type
**sudo raspi-config**
Go to: >Advanced Option > Resolution > just set your resolution compatible fit with your screen.

Apply and let it reboot.

**Comment by nyxnor** [comment]
pls close this.

**Comment by wsurferdude** [comment]
I have an Official Raspberry Pi 7" Touchscreen and to get it to fill the Info screen I modified the following.
framebuffer_width=500
framebuffer_height=360

Just keep on moving these numbers down to make the display larger.  Don't ask me why this works 😝.
