### ISSUE TITLE
Optimize Recovering Old Wallet

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#785]
At the moment the LND channel backup file gets added after the wallet is created. Check if this can be done on wallet crearte ... see:

https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md#recovering-using-scbs

Also re-check if on-chain & channels funds get recovered ... see fail reports:
https://github.com/rootzoll/raspiblitz/issues/595#issuecomment-530329517

**Comment by jodobear** [comment]
After reporting successful on-chain recovery, which did not contain any off-chain recovered funds (see [#595 (comment)](https://github.com/rootzoll/raspiblitz/issues/595#issuecomment-533894645)) I proceeded with recovering off-chain funds following the [recovery.md](https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md#recovering-using-scbs) as suggested above using following command:

`lncli restorechanbackup --multi_file ~/files/channel.backup`

I got the following output:

`[lncli] unable to restore chan backups: rpc error: code = Unknown desc = unable to unpack chan backup: channel already exists`

I do not see any channels, nor funds on my on-chain wallet. `lncli getinfo` currently shows:

```
...
"num_pending_channels": 0,
"num_active_channels": 0,
"num_inactive_channels": 0,
...
```

**Comment by rootzoll** [comment]
Marked for Hackathon Sprint:

- Find solution for better on-chain fund recovery

**Comment by rootzoll** [comment]
TODO: After the old wallet was created from SEED or SEED & SCB ... make sure to have it synced to chain before doing a restart. Otherwise it will work after restart with recovery-window of 0 and not find any funds.

**Comment by rootzoll** [comment]
With v1.5 recovering old funds from SEED will be possible when use on a synced node with empty wallet "REPAIR -> RESET-LND". But to fix recovery from SEED during initial setup is not working yet ... for that we need to re-arrange the setup process first - see https://github.com/rootzoll/raspiblitz/issues/1126
