### ISSUE TITLE
Stupid question may be..

### ISSUE THREAD

**Issue by lucbran** [raspiblitz/raspiblitz#786]
Hi ,
I have setup my Raspiblitz and working weel.. I use for my LN transactions..
I am not sure having understood if and how same can be used as a normal Bitcoin node to validate for example transactions from my Ledger ... Can anyone clear my doubt?

**Comment by Tracachang** [comment]
You can connect your HW with your bitcoin full node using electrum wallet + electrs.

Openoms did an script for that:

https://github.com/openoms/bitcoin-tutorials/blob/master/electrs/README.md
