### ISSUE TITLE
Raspiblitz 1.3 bitcoin-cli parameters

### ISSUE THREAD

**Issue by tkussmaul82** [raspiblitz/raspiblitz#789]
I just wanted to play around with the console and check for some parameters of bitcoin-cli. Do I miss sth. or are there less parameters available than defined in the bicoin documentation? I am really new to this topic and just wondering if I am missing sth.

Thanks a lot in advance for your help!
Regards

![image](https://user-images.githubusercontent.com/54837098/65326693-5c41f980-dbb2-11e9-908e-48b55c56b940.png)

**Comment by rootzoll** [comment]
These are the basic parameters for just the CLI itself you get when you just enter `bitcoin-cli`. To get all the RPC commands from the documentation use `bitcoin-cli help`. And for details on a single command use `bitcoin-cli help [COMMAND]`.
