### ISSUE TITLE
new update to 1.3 wants to format HDD

### ISSUE THREAD

**Issue by Lupus-Pluvia** [raspiblitz/raspiblitz#790]
hello have the following problem the new update wants me to format the hard drive and set up the node again.  how can i handle this or who i am doing this how can i counter this without backup
![15690071783131207701236658331402](https://user-images.githubusercontent.com/49962031/65353042-700a5180-dbec-11e9-9c5c-e3c3b2a68b34.jpg)

**Comment by rootzoll** [comment]
This is unusual. There is a check if the HDD was mounted `df | grep -c /mnt/hdd` and if not it thinks it offers that dialog. But maybe we have to even jump a step before that ... normally on a update it should automatically go into recover-mode. So what was the message on the LCD before you SSHed into the RaspiBlitz?

**Comment by Lupus-Pluvia** [comment]
According to PC expert, the HDD should be broken and can not read or format
