### ISSUE TITLE
Feature Request - add tmux

### ISSUE THREAD

**Issue by frennkie** [raspiblitz/raspiblitz#793]
I have seen that the sd card image includes the `screen` tool. I am more used to `tmux` and it appears to be much more popular than `screen` these days. 

Of course I can simply install it myself after every update but it would be nice if this could be included directly. I'm already working on a PR for this. @rootzoll against which branch should I file the PR?

Here is a preview:
![raspi_tmux](https://user-images.githubusercontent.com/6499251/65387550-afe64b80-dd48-11e9-8592-2c08781e3b7f.png)

**Comment by rootzoll** [comment]
Will merge PR into v1.4 branch once its open.
