### ISSUE TITLE
!!! BUILD FAILED --> LND PGP Verify not OK 

### ISSUE THREAD

**Issue by Tracachang** [raspiblitz/raspiblitz#797]
Hello

I am unable to build sd card (https://github.com/rootzoll/raspiblitz#build-the-sd-card-image) because LND PGP Key does not match

--2019-09-24 17:11:09--  https://keybase.io/roasbeef/pgp_keys.asc
Resolving keybase.io (keybase.io)... 34.237.147.136, 52.206.154.58
Connecting to keybase.io (keybase.io)|34.237.147.136|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6909 (6.7K) [text/plain]
Saving to: ‘pgp_keys.asc’

pgp_keys.asc                                                        100%[================================================================================================================================================================>]   6.75K  --.-KB/s    in 0s      

2019-09-24 17:11:09 (77.4 MB/s) - ‘pgp_keys.asc’ saved [6909/6909]

gpg: WARNING: no command supplied.  Trying to guess what you mean ...
pub   rsa4096 2019-07-10 [SC] [expires: 2020-10-02]
      9769140D255C759B1EB77B46A96387A57CAAE94D
uid           Olaoluwa Osuntokun <laolu32@gmail.com>
sub   rsa4096 2019-07-10 [A] [expires: 2020-10-02]
sub   rsa4096 2019-07-10 [S] [expires: 2020-10-02]
sub   rsa4096 2019-07-10 [E] [expires: 2020-10-02]

!!! BUILD WARNING --> LND PGP author not as expected
Should contain PGP: BD599672C804AF2770869A048B80CD2BB8BD8132
PRESS ENTER to TAKE THE RISK if you think all is OK

gpg: key A96387A57CAAE94D: "Olaoluwa Osuntokun <laolu32@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
goodSignature(0)
correctKey(1)

!!! BUILD FAILED --> LND PGP Verify not OK / signature(0) verify(1)

**Comment by openoms** [comment]
Might be a corrupted download. Delete the LND package (or flash the SDcard again with the Raspbian ) and run again.

**Comment by Tracachang** [comment]
I am flashing SD card to try again, I will keep you updated

**Comment by Tracachang** [comment]
Got same error

**Comment by openoms** [comment]
Hmm, managed to reproduce the error.
What is happening that the script is looking for the PGP fingerprint of roasbeef, but instead the pubkey is shown.
```
PGPpkeys="https://keybase.io/roasbeef/pgp_keys.asc"
PGPcheck=`BD599672C804AF2770869A048B80CD2BB8BD8132`
```

```
 gpg "pgp_keys.asc"
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
pub   rsa4096 2019-07-10 [SC] [expires: 2020-10-02]
      9769140D255C759B1EB77B46A96387A57CAAE94D
uid           Olaoluwa Osuntokun <laolu32@gmail.com>
sub   rsa4096 2019-07-10 [A] [expires: 2020-10-02]
sub   rsa4096 2019-07-10 [S] [expires: 2020-10-02]
sub   rsa4096 2019-07-10 [E] [expires: 2020-10-02]
```

For now you could change the `BD599672C804AF2770869A048B80CD2BB8BD8132` to `9769140D255C759B1EB77B46A96387A57CAAE94D` in line 497 of the build_sdcard.sh https://github.com/rootzoll/raspiblitz/blob/master/build_sdcard.sh#L497 after downloading the script:
`wget https://raw.githubusercontent.com/rootzoll/raspiblitz/master/build_sdcard.sh`
and only run after:
`sudo bash build_sdcard.sh`

Will make a PR to solve it proper.

**Comment by openoms** [comment]
Given can see the pubkey/fingerprint:
`9769140D255C759B1EB77B46A96387A57CAAE94D`
ignoring the error is also safe.

double check here: https://keybase.io/roasbeef
![Screenshot from 2019-09-25 09-48-19](https://user-images.githubusercontent.com/43343391/65587107-35524180-df7d-11e9-818e-37f9e0933824.png)
