### ISSUE TITLE
Rainbow screen on first boot

### ISSUE THREAD

**Issue by operahouserat** [raspiblitz/raspiblitz#803]
When trying to boot my Raspberry Pi 4 for the first time after writing the SD card image to the SD card, this rainbow screen appears. I've now tried two different SD cards and have the same issue.

Any suggestions?

![image](https://user-images.githubusercontent.com/55957347/65837193-6656ad00-e2c2-11e9-8e8b-16284163ba68.png)

**Comment by operahouserat** [comment]
Think it was a power supply issue.

**Comment by Avdhoot28** [comment]
> When trying to boot my Raspberry Pi 4 for the first time after writing the SD card image to the SD card, this rainbow screen appears. I've now tried two different SD cards and have the same issue.
> 
> Any suggestions?
> 
> ![image](https://user-images.githubusercontent.com/55957347/65837193-6656ad00-e2c2-11e9-8e8b-16284163ba68.png)

> Did you got any solution/ Did your raspberry pi 4 got booted successfully ?
