### ISSUE TITLE
Node still private after port fowarding/open :-(

### ISSUE THREAD

**Issue by h2ogeek** [raspiblitz/raspiblitz#807]
I have check pretty much everything that I can think about it to find out why my node still showing as a private on 1ML https://1ml.com/

              RaspiBlitz v1.3  TerraHOLDR
               bitcoin Fullnode + Lightning Network
        ,/     -------------------------------------------
      ,'/      CPU load 0.94, 0.57, 0.56, temp 61°C 142°F
    ,' /       Free Mem 1445M / 1939M  HDDuse 314G (36%)
  ,'  /_____,  ssh admin@
 .'____    ,'  web admin -->
      /  ,'    bitcoin v0.18.1 mainnet Sync OK 100.00%
     / ,'      DynDNS TerraHOLDR.chickenkiller.com
    /,'
   /'          LND 0.7.1-beta wallet 18962 sat
               2/2 Channels 19264 sat 4 peers

The DynDNS and Node address are in yellow 

Here is my node https://1ml.com/node/0307bc77b9ec221b31f6518c6d2714e3ed531aa85448460e43ce64508664023c51

I use DynDNS and I test those ports using the domain and it works

I do know what else to try at this stage :-/

I scan my ports from the local network upto the wlan and they are open:
nmap -p 8333 MY-LOCAL-IP
nmap -p 18333 MY-LOCAL-IP
nmap -p 9735 MY-LOCAL-IP
nmap -p 10009 MY-LOCAL-IP
nmap -p 8080 MY-LOCAL-IP

nmap -p 8333 MY-WLAN-IP
nmap -p 18333 MY-WLAN-IP
nmap -p 9735 MY-WLAN-IP
nmap -p 10009 MY-WLAN-IP
nmap -p 8080 MY-WLAN-IP

UFW show that they are open
To                         Action      From
--                         ------      ----
18333                      ALLOW       Anywhere                   # bitcoin testnet
8333                       ALLOW       Anywhere                   # bitcoin mainnet
9333                       ALLOW       Anywhere                   # litecoin mainnet
19735                      ALLOW       Anywhere                   # lightning testnet
9735                       ALLOW       Anywhere                   # lightning mainnet
10009                      ALLOW       Anywhere                   # lightning gRPC
8080                       ALLOW       Anywhere                   # lightning REST API
49200:49250/tcp            ALLOW       Anywhere                   # rtorrent
80                         ALLOW       192.168.0.0/16             # allow local LAN web
Anywhere                   ALLOW       192.168.0.0/16 1900/udp    # allow local LAN SSDP for UPnP discovery
3000                       ALLOW       192.168.0.0/24             # allow access to RTL from local LAN
22                         ALLOW       192.168.0.0/24             # allow SSH from local LAN
18333 (v6)                 ALLOW       Anywhere (v6)              # bitcoin testnet
8333 (v6)                  ALLOW       Anywhere (v6)              # bitcoin mainnet
9333 (v6)                  ALLOW       Anywhere (v6)              # litecoin mainnet
19735 (v6)                 ALLOW       Anywhere (v6)              # lightning testnet
9735 (v6)                  ALLOW       Anywhere (v6)              # lightning mainnet
10009 (v6)                 ALLOW       Anywhere (v6)              # lightning gRPC
8080 (v6)                  ALLOW       Anywhere (v6)              # lightning REST API
49200:49250/tcp (v6)       ALLOW       Anywhere (v6)              # rtorrent

**Comment by openoms** [comment]
This is normal. Your node is public only the gossip did not reach 1ml.com yet.
You can add their node (https://1ml.com/node/0217890e3aad8d35bc054f43acc00084b25229ecff0ab68debd82883ad65ee8266) as a peer or 
even register your node and add a custom description on 1ml.com by logging in and opening a channel following their instructions given when clicking `claim node` on the info page of your node.

**Comment by h2ogeek** [comment]
Thank you !
