### ISSUE TITLE
Can I point my miner to the bitcoin Fullnode?

### ISSUE THREAD

**Issue by IW8** [raspiblitz/raspiblitz#813]
Can I point my old miner to the bitcoin Fullnode for solo mining? If so, what would be the address?
![image](https://user-images.githubusercontent.com/55857895/66277121-f74ffa00-e867-11e9-9f12-cc80d1813ac4.png)
Thank You in advance.

**Comment by openoms** [comment]
The address of your bitcoind is below the bitcoin version with the port 8333. It is .onion beacuse you have Tor switched on. 
On your local network you can just use the LAN IP (same as for ssh) with the port 8333.

If you need the Bitcoin Core wallet will need to activate it in bitcoin.conf.
`sudo nano /mnt/hdd/bitcoin/bitcoin.conf`
set
`disablewallet=0`
You will need to use the bitcoin-CLI as there is no GUI for the Bitcoin Core wallet on the RaspiBlitz.
run `bitcoind -?` for help with the command line
