### ISSUE TITLE
Accessing the bitcoin wallet

### ISSUE THREAD

**Issue by ikoinu** [raspiblitz/raspiblitz#814]
Just wondering if the native bitcoin wallet is installed and accessible along with the RTL wallet?
If so, how is it accessed from the command line?
Both bitcoind and bitcoin-qt do not work.

Thanks for the assistance!

**Comment by fluidvoice** [comment]
If you need the Bitcoin Core wallet will need to activate it in bitcoin.conf.
`sudo nano /mnt/hdd/bitcoin/bitcoin.conf`
change 
`disablewallet=1`
to
`disablewallet=0`
If you want further information seek the Bitcoin core documentation and/or use the `--help` option when running bitcoind and bitcoin-qt.

**Comment by ikoinu** [comment]
Thank you very much, such a simple fix.
I must have missed that.
