### ISSUE TITLE
Closing just one channel

### ISSUE THREAD

**Issue by PBJellytime** [raspiblitz/raspiblitz#816]
I've got a dead channel but can't seen to close just the one channel using lncli and no options on the main screen except close all channels

**Comment by frennkie** [comment]
What happens when you try to close the channel using `lncli`? Error message?

**Comment by PBJellytime** [comment]
admin@EmJ:~ $ lncli closechannel 655711351584391169
[lncli] rpc error: code = Unknown desc = channel not found

**Comment by frennkie** [comment]
Can you run `lncli listchannels`. 

Then use the **channel_point** value (replace the ':' at the end with a space).

**Comment by PBJellytime** [comment]
That worked, except I need to force close :p 

admin@EmJ:~ $ lncli closechannel 1ccbbb150fb2985abe49fe133debc96580cd771dbd39c8dba0184f475b835493 1
[lncli] rpc error: code = Unknown desc = unable to gracefully close channel while peer is offline (try force closing it instead): channel link not found

**Comment by PBJellytime** [comment]
Thanks for the help guys o7
