### ISSUE TITLE
run raspiblitz in bitcoin Pruned mode

### ISSUE THREAD

**Issue by woeisme** [raspiblitz/raspiblitz#817]
I'd like to switch my raspiblitz install to a pruned node but I'm not sure the best method or if it will mess up the associated LND wallet. 

Is it just as simple as modifying bitcoin.conf to add the prune= parameter and rebooting?

**Comment by openoms** [comment]
Yes, LND should be able to work with pruned mode. Electrs (if it is installed) does not.
I think one of the reasons of run a dedicated hardware is that there is no need for pruning so not recommending.

**Comment by fluidvoice** [comment]
> I'd like to switch my raspiblitz install to a pruned node but I'm not sure the best method or if it will mess up the associated LND wallet.
> 
> Is it just as simple as modifying bitcoin.conf to add the prune= parameter and rebooting?

have a look at this issue thread: https://github.com/rootzoll/raspiblitz/issues/268

**Comment by woeisme** [comment]
> 
> 
> > I'd like to switch my raspiblitz install to a pruned node but I'm not sure the best method or if it will mess up the associated LND wallet.
> > Is it just as simple as modifying bitcoin.conf to add the prune= parameter and rebooting?
> 
> have a look at this issue thread: #268

I've looked at thread @fluidvoice but I'm still uncertain if it's safe to prune from the content, as I plan on keeping this node running for a while. Do I then need to prune but keep 1 years worth of data?

Are there any other downsides I'm not realizing with a pruned node? 
Can I do this on a active full (tor based) node with open lnd channels, merely by adding the 'prune' option to bitcoin.conf and rebooting the RPI4 ?

**Comment by nyxnor** [comment]
@woeisme Have you tried it?
If it worked, please let us now and close this.

**Comment by woeisme** [comment]
closing this as I've not been interested enough to run a pruned node lately.
