### ISSUE TITLE
Node name and it's local usage [Privacy]

### ISSUE THREAD

**Issue by Conimous** [raspiblitz/raspiblitz#819]
Hi,

When setting up the Raspiblitz it prompts for the naming of the LN node right? Y is this tight into the naming of the local machine? Why am asking? Well if you run ur Node on TOR but ur local machine blatantly blasts out its name to ur router, ISPs are able to read those out and figure out which nodes run where, based on the local name of the Raspi.

Why not set it to " Unknown device " or " Raspberry " on the local side of the machine, especially when configured to run on TOR. Keep in mind a lot of people will run their stuff on the ISPS given out network hardware and not all of them run a bridged setup.

Ty in advance for the responses.

**Comment by openoms** [comment]
Agreeing here, we might want to keep the default hostname `raspberry` or at least change it back if Tor is activated.
The MAC adress is known to the router, so the device type is exposed to the ISP (through a proprietary router) but at least the type of usage should not be advertised.

Relevant code: https://github.com/rootzoll/raspiblitz/blob/master/home.admin/config.scripts/lnd.setname.sh

**Comment by rootzoll** [comment]
I removed setting the local networkname by default on fresh setups now. For old setups it will keep the old local network name to not break possible forwarding rules on the routers if configured by hostname.

**Comment by rootzoll** [comment]
OK. Works on my test setups of fresh devices. Closing issue.
