### ISSUE TITLE
Blockchain sync keeps failing

### ISSUE THREAD

**Issue by inpharmaticist** [raspiblitz/raspiblitz#825]
I've had my raspiblitz since v 1.1 or 1.2. It seemed like switching on TOR wasn't working for the LND node, so I thought to start fresh with V1.3. Long story short, I kept getting "blockchain needs to be repaired" warning after downloading the torrent. I thought I'd just try syncing from scratch, got up to 75% of the blockchain indexed and now I'm getting the same issue. 

The hard drive is <1 year old. What else could it be?

![image](https://user-images.githubusercontent.com/49789899/66883984-9a012a80-ef84-11e9-8e03-4cacb3f01f11.png)

**Comment by rootzoll** [comment]
I would recommend using the copy option: See details here: https://github.com/rootzoll/raspiblitz#2-copying-from-another-computer
