### ISSUE TITLE
Seed don't fit LCD screen

### ISSUE THREAD

**Issue by xsoft** [raspiblitz/raspiblitz#831]
Hi,
I have 4 button "TFT28' Touch Shield Fpr RPi" (v2.1 stmpe610+ili19341).
It takes some diggin into make it working, since just white screen was there.

Never mind, to the issue ... at New wallet step ( https://github.com/rootzoll/raspiblitz#setup-a-new-wallet ) the seed did NOT fit the screen. There are 6 columns and literally first and last columns didnt fit. Not even one char.

I guess I can run: './70initLND.sh' to repeate this step ( https://github.com/rootzoll/raspiblitz/issues/404 )
Or is there any (new) way for 1.3 version to recreate wallet and write down full seed.

And also, how to fix the screen issue? When Im on shell (on LCD), all chars at bash are there precisely. Like Im not writing off screen or whatever. But those "blue" dialogs didnt get the propper params of the screen (text size).

So:
1) how to recreate wallet (and write down seed)
2) fix the screen size for rest of the dialogs

Thanks

**Comment by openoms** [comment]
You can change the font size which should make the dialogs and text fit. Search the issues here or RPi FAQs for how to. Needed to do it for some HDMI screens to where the status screen appeared duplicated.
