### ISSUE TITLE
Finding Macaroon Path

### ISSUE THREAD

**Issue by PizzaParkerGM** [raspiblitz/raspiblitz#835]
Not really an issue, just brain dead when it comes to coding.

When I do lncli --macaroonpath value
it just refreshes the help screen and doesn't tell me the path. 

I need the path to finish setting up RTL

Thanks for the help, love the project!

**Comment by woeisme** [comment]
If you choose 'EXPORT' from the main ncurses menu and use the 'SCP' option it will show you the paths in the commands

`/home/bitcoin/.lnd/data/chain/bitcoin/mainnet/readonly.macaroon` etc etc.

**Comment by PizzaParkerGM** [comment]
Thank you! Case closed!
