### ISSUE TITLE
StatusTorrent 'blockchain' rate always says 0

### ISSUE THREAD

**Issue by guilsa** [raspiblitz/raspiblitz#838]
Raspiblitz StatusTorrent 'blockchain' rate does not seem to work, was always 0 for me, even though days later blockchain download was complete.

**Comment by rootzoll** [comment]
I am now also seeding that torrent again - did you had any luck? Also if torrent is not working, cancel it with X and and try another option: https://github.com/rootzoll/raspiblitz#getting-the-blockchain

**Comment by nyxnor** [comment]
Please close this.
