### ISSUE TITLE
Running through TOR

### ISSUE THREAD

**Issue by tomski174** [raspiblitz/raspiblitz#84]
Are there any limitations to my node if i choose to run it through TOR?

**Comment by rootzoll** [comment]
Ther are two things when behind TOR: 

1) LND gRPC (Port 10009) : Not much Mobile wallets or other services that making connection to LND RPC have TOR support (yet). Sometimes its possible you can use bridge thru a local TOR proxy but thats very tricky.

2) LND Node (Port 9735):  Other nodes that dont have running TOR cannot connect to you. But you should be able to open channels to non-TOR nodes.

This is at least based on my experience with TOR when trying it out. Would love to hear other experiences runnign a node behind TOR.

**Comment by tomski174** [comment]
LND v0.5 was released and it states that:

"User privacy is a major consideration in lnd, and in this release, we’ve added additional support for Tor so that Lightning users who accept inbound connection requests can avoid revealing their IP address. Previously, lnd supported outbound Tor connections, but with lnd v0.5-beta, inbound onion services (Tor v2 and v3) are supported. "

Does that mean that nodes hidden by Tor can help to route payments now??

**Comment by rootzoll** [comment]
@tomski174 thats cool seeing better support for TOR inbound connections. I already preparing new LND 0.5 release for the next sd card image - hopefully being ready for next week.

**Comment by rootzoll** [comment]
TODO: recheck TOR with new setup

**Comment by rootzoll** [comment]
OK TOR is now part of the service section. Install and Deinstall look good on tests. Closing Ticket for now.
