### ISSUE TITLE
Normal for Public IP and Address to alternate Yellow and Red?

### ISSUE THREAD

**Issue by Aki113s** [raspiblitz/raspiblitz#840]
It does not permanently stay yellow, it fairly frequently goes from Yellow to Red, sometimes both yellow, sometimes its one of the other for a little bit. Ports are open. I see the node on 1ML.com

**Comment by rootzoll** [comment]
Its the first time such a rotating colors are reported. Not exactly sure why that is happening. The script does a netcat port scan on the public IP with that port number and if that works (exitcode 0) it gets displayed yellow - if not red. So the netcat port scan seems to deliver different results.

**Comment by nyxnor** [comment]
pls close this.
