### ISSUE TITLE
What happens to channel balances when a node goes down?

### ISSUE THREAD

**Issue by woeisme** [raspiblitz/raspiblitz#847]
I was running a full node on a RPI4 until last week when the unit went down. 
I had funds split between 3 open remote channels and the local balance. 
What happens to the remote channel balances the longer the node is down?

Is there any way to recover the funds?
I did backup the channels before it went down.

**Comment by adolfosrs** [comment]
Yes, there is. Make sure to read the following.

https://github.com/rootzoll/raspiblitz#backup-for-on-chain---channel-funds
