### ISSUE TITLE
Node Alias not seen on peers

### ISSUE THREAD

**Issue by VeniVidiViciLA** [raspiblitz/raspiblitz#852]
Hi guys,

Quick question regarding RTL and Raspiblitz.
I built 2 Raspiblitzs and after I added each other as peers I don't see my node aliases in the peer list on RTL.Everything else looks fine.
What am I missing here ?

Thank you!!!

**Comment by rootzoll** [comment]
I dont know why RTL is not showing your alias-name.
I think this question should be posted at the RTL github: https://github.com/Ride-The-Lightning/RTL/issues
