### ISSUE TITLE
Tor channel Connection problem  to my node

### ISSUE THREAD

**Issue by Lupus-Pluvia** [raspiblitz/raspiblitz#854]
hello have a question.  Since I use Tor can not open Chanels to my node, I have to wait until it works.  or is that so.  From my side I can open channel to other node

**Comment by rootzoll** [comment]
If you run your node behind TOR -> only other TOR running nodes can open a channel with you. Normal IP running nodes cannot reach you.

But yes ... you as a node behind TOR can open a channel with a normal IP running node. Thats how you can build channels that bridge between TOR and IP networks.

**Comment by rootzoll** [comment]
Please comment further on this issue - but I will close it for now becuase its not a bug.

**Comment by Lupus-Pluvia** [comment]
thanks for the info and help position
