### ISSUE TITLE
Autopilot on by default on mainnet?

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#86]
Switch the switch from testnet to mainnet on start, I kept on the autopilot. This seems to confuse people, because they see channels after funding they did not opened.

Maybe ask to switch on Autopilot optional after funding. Or make the question part of the initial setup.

**Comment by rootzoll** [comment]
Easy quick way would to put a notice on lnbalances output, to let people know that autopilot is on.

**Comment by frennkie** [comment]
Yepp.. this really confused me yesterday. Leaving it off by default and providing an Option in the GUI would be a more "cautious" approach.

**Comment by machasm1** [comment]
Yep me too!
Tried to close down channels to sendcoins to my BTC wallet only to find that more channels had miraculously sprung open!
Only after a little research did I find out about the autopilot function!!

**Comment by rootzoll** [comment]
OK. Will turn off autopilot by default and see that I put a option into main menu to turn on/off.

**Comment by rootzoll** [comment]
OK. Autopilot is now off by default and can be turned on in the service settings menu. Added also a small notice about autopilot in the funding script.
