### ISSUE TITLE
Fix BootUp Problems - Remove plymouth

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#861]
Like reported in this issue comment - the plymouth packages seem to make problems on bootup.
https://github.com/rootzoll/raspiblitz/issues/796#issuecomment-552233584

So for the 1.4 release we plan to remove those packages in the sd card build like suggested by @openoms 

@frennkie to do see any problems removing those packages in the context of the TouchUI?

**Comment by frennkie** [comment]
Nope... I don't think this would have any impact on BlitzTUI.

**Comment by rootzoll** [comment]
Thanks - I merged the PR by @openoms to remove plymouth then.
