### ISSUE TITLE
Pogoplug

### ISSUE THREAD

**Issue by woeisme** [raspiblitz/raspiblitz#866]
I dug an old pogoplug E02 out of storage the other day and I'm wondering if it is powerful enough to run raspiblitz? 
Anyone know?

[some hardware specs from the openwrt project](https://openwrt.org/toh/hwdata/pogoplug/pogoplug_pogoplug_e02)

**Comment by openoms** [comment]
`RAM MB:256` means no, unfortunately.

**Comment by woeisme** [comment]
damn!
