### ISSUE TITLE
Error message on CLOSEALL (-force)

### ISSUE THREAD

**Issue by frennkie** [raspiblitz/raspiblitz#87]
I used the CLOSEALL option in the GUI and get this message: 

```
[lncli] flag provided but not defined: -force
```

As far as I see it in [BBcloseAllChannels.sh:7](https://github.com/rootzoll/raspiblitz/blob/master/home.admin/BBcloseAllChannels.sh#L7) it should be `command="lncli --chain=${network} closeallchannels --force"` , right?!

**Comment by rootzoll** [comment]
In line BBcloseAllChannels.sh:7 it is at the moment:
command="lncli --chain=${network} --force closeallchannels"

I will change it to - hope that works better - have to testing.
command="lncli --chain=${network} closeallchannels --force"

**Comment by frennkie** [comment]
Yes, that's what I did and it works.
