### ISSUE TITLE
_background.sh should be changed for tor users

### ISSUE THREAD

**Issue by Tracachang** [raspiblitz/raspiblitz#894]
Hello

Checking the _background.sh in home.admin folder I see it requests your public IP every 15 minutes, using an external service with the command `curl -s http://v4.ipv6-test.com/api/myip.php`

Since the idea to use bitcoind and lnd with tor is to hide your IP, there is no interest in requesting your real IP every 15 minutes and could even harm privacy in the worst scenario.

The idea of this script it is to restart lnd if public IP has changed, but even user is not using tor is it really worth to check it every 15 minutes? 

For those who have static IP there is no need and those who has dynamic IP they will probably use a DNS service in order to have a static IP (if they want other lnd peers to be able to open channels to them).

Let me know your thoughts.

**Comment by nyxnor** [comment]
Merged above. Pls close this.
