### ISSUE TITLE
White Screen

### ISSUE THREAD

**Issue by justinsane** [raspiblitz/raspiblitz#899]
Hi everyone,

My node used to work but recently I'm getting a blank white screen (see image below). I'm connected to ethernet. Can anyone advise on troubleshooting steps?

I have a feeling my SD card is messed up? 

As I mentioned, I used to SSH in remotely and everything worked fine. Not sure what happened.  Thanks in advance.

![IMG_8259](https://user-images.githubusercontent.com/1160014/70362488-fae90880-1839-11ea-9e12-bc301af79e01.jpeg)

**Comment by rootzoll** [comment]
This is what it looks when the RaspiBlitz shutdown (and is waiting for you to disconnect and reconnect power). Or when during startup the system does not reach the point where its loading the the software drivers. Are you still able to SSH in?

**Comment by justinsane** [comment]
I'm not able to SSH in. 

I checked the devices connected to my router and the Raspberry Pi wasn't one of them (while connected via Ethernet). 

Is my SD or HDD corrupt since it won't boot? Any idea on the next logical troubleshooting step? 

Thanks in advance!

**Comment by rootzoll** [comment]
If the screen is white and you cant SSH in it looks like the system is not able to boot up and first thing to check/re-write/replace would be the sd card in that case.

**Comment by frennkie** [comment]
If this is not the same problem as in #1436 then I don't see how we can further help here. 

Feel free to reopen if the problem persists and more details can be provided.
