### ISSUE TITLE
Mobile Wallet externalIP/domain

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#93]
one more thing about the mobilewallet shango script. It now looks up for the local ip, this should be the domain name or external ip if used to connect from outside. I had to change this afterreading qr from shango

**Comment by hopitas** [comment]
I followed this guide and got Shango wallet working from external ip: [https://github.com/Stadicus/guides/blob/master/raspibolt/raspibolt_68_shango.md](url)

The 97addMobileWalletShango.sh points many times to

`./.lnd`

dir when it should point to

`/mnt/hdd/lnd`

Fix these and the ip thing and I guess it should work :)

**Comment by rootzoll** [comment]
See link in this tweet - there is advice how to get it to work.
https://twitter.com/RobEdb/status/1041052180743184385

Use for the next fix of script.

**Comment by rootzoll** [comment]
Test also with latest ZAP: https://twitter.com/ottosuess/status/1069983204520722432
If done - make new issue for integration of ZAP URLs.
https://github.com/LN-Zap/zap-iOS/blob/master/docs/zap_connect_uri.md

**Comment by rootzoll** [comment]
Use also the info from this issue to improve the tutorial text on how to handle the process on different OS terminal types: https://github.com/rootzoll/raspiblitz/issues/193

**Comment by rootzoll** [comment]
OK .. prepared mobile wallets and dynamicDNS for version 1.0 release.
