### ISSUE TITLE
Testnet not working due to chainsize checks

### ISSUE THREAD

**Issue by frennkie** [raspiblitz/raspiblitz#949]
I just installed a testnet node and have some issues.

In `00raspiblitz.sh` the chainsize must be larger than `210000000000` - which is not the case on testnet:

```
blockchainsize=$(sudo du -shbc /mnt/hdd/${network}/ 2>/dev/null | head -n1 | awk '{print $1;}')
```

Also the copy scripts (`50cloneHDD.sh`, `50copyHDD.sh`) have lines which most likely only work on a mainnet node (on testnet the file will be in `/mnt/hdd/bitcoin/testnet3/blocks`):

```
count=$(sudo ls /mnt/hdd/bitcoin/blocks 2>/dev/null | grep -c '.dat')
```

**Comment by frennkie** [comment]
I found another issue -> put into separate issue.

**Comment by rootzoll** [comment]
This should now be fixed with merge - set to final testing.

**Comment by rootzoll** [comment]
OK testnet is working so far for v1.4. Closing issue.
