### ISSUE TITLE
Spaces removed from passwords

### ISSUE THREAD

**Issue by mattipt** [raspiblitz/raspiblitz#99]
After prompting for passwords A and B, the script 20initDialog.sh removes all spaces from them. For example if the user chooses "correct horse battery staple" as his/her password A, the script automatically changes this to "correcthorsebatterystaple" which the login password then gets set to.

Please consider not mangling the input but instead escaping the strings as required when setting the passwords.

**Comment by rootzoll** [comment]
You are correct. Spaces within a password should not be mangled with. For a quick fix I removed ' tr -d [:space:] ' from its - the goal was to trim, not to remove every space, but the side effect you discribed is worse.
